microsoft/react-native-windows

- change/@react-native-windows-cli-daf01106-67fe-4d28-8f61-17d4e4f6fd8d.json
- package.json
- packages/@react-native-windows/cli/package.json
- yarn.lock
This PR backports microsoft#10841 to RNW 0.67.
* `loader-utils` to `2.0.3` to resolve CVE-2022-37601
> [0.67] CG 11/7/22: Update `@xmldom/xmldom`

- change/react-native-windows-3cc0e9ad-707a-4364-90b8-dc391040fade.json
- vnext/Microsoft.ReactNative/INativeUIManager.h
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.h
- vnext/Microsoft.ReactNative/XamlUIService.cpp
In #10797, #10689 was rolled back due to a build break that emerged due to a conflicting new API surface on XamlUIService. This brings back the original code in #10689 and fixes the build break.
> Revert rollback of "Simplify root node lookups"

- change/react-native-windows-374819da-ddb8-4457-9ef5-f136eb4f3829.json
- vnext/Mso.UnitTests/object/refCountedObjectTest.cpp
- vnext/Mso.UnitTests/object/unknownObjectTest.cpp
Not sure if something changed on the CI machines that this just started to hit.  But this adds an additional suppression to some test code to unblock CI.
> Suppress warning in test code when discarding a std::async object

- .ado/compliance.yml
- .ado/templates/run-compliance-prebuild.yml
This adds the Anti-Malware Scan task to our CI, which runs Windows Defender on our source.
Closes #10460
> Add Anti-Malware Scan to CI

- packages/playground/Samples/nativeLayout.tsx
- packages/playground/windows/PlaygroundNativeModules/GridItemView.cpp
- packages/playground/windows/PlaygroundNativeModules/GridItemView.h
- packages/playground/windows/PlaygroundNativeModules/GridItemView.idl
- packages/playground/windows/PlaygroundNativeModules/GridItemViewManager.cpp
- packages/playground/windows/PlaygroundNativeModules/GridItemViewManager.h
- packages/playground/windows/PlaygroundNativeModules/GridViewManager.cpp
- packages/playground/windows/PlaygroundNativeModules/GridViewManager.h
- packages/playground/windows/PlaygroundNativeModules/PlaygroundNativeModules.def
- packages/playground/windows/PlaygroundNativeModules/PlaygroundNativeModules.vcxproj
- packages/playground/windows/PlaygroundNativeModules/PlaygroundNativeModules.vcxproj.filters
- packages/playground/windows/PlaygroundNativeModules/PropertySheet.props
- packages/playground/windows/PlaygroundNativeModules/ReactPackageProvider.cpp
- packages/playground/windows/PlaygroundNativeModules/ReactPackageProvider.h
- packages/playground/windows/PlaygroundNativeModules/ReactPackageProvider.idl
- packages/playground/windows/PlaygroundNativeModules/packages.config
- packages/playground/windows/PlaygroundNativeModules/pch.cpp
- packages/playground/windows/PlaygroundNativeModules/pch.h
- packages/playground/windows/playground-win32.sln
- packages/playground/windows/playground-win32/AutolinkedNativeModules.g.cpp
- packages/playground/windows/playground-win32/AutolinkedNativeModules.g.targets
- packages/playground/windows/playground-win32/Playground-Win32.cpp
- packages/playground/windows/playground.sln
- packages/playground/windows/playground/AutolinkedNativeModules.g.cpp
- packages/playground/windows/playground/AutolinkedNativeModules.g.targets
- packages/playground/windows/playground/MainPage.xaml
The GitHub repo Playground projects are missing examples that exercise 3rd party APIs. While there are examples that use 3rd party extensions from NPM, there are some 3rd party APIs that are not used in ecosystem packages (yet).
This native modules project gives us a place to prototype custom view managers and native modules.
The PlaygroundNativeModules project only currently includes a single custom view manager that exercises the `IViewManagerRequiresNativeLayout` functionality.
> Adds test native module project for Playground

- change/react-native-windows-e50a72d1-525f-4752-a90d-fbb61a073ff1.json
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
If attempting to show a flyout on an unfocused window, the flyout will show on top of the window currently in focus and appear unattached to anything in particular.
This change ensures that we only attempt to show a flyout if the XamlRoot attached to the flyout is the same as the active XamlRoot set in XamlUIService.
> Suppress Flyout if XamlRoot does not have focus

- change/react-native-windows-bc1ccb33-c9d8-427a-9fe4-af8cbcd246a0.json
- vnext/Scripts/rnw-dependencies.ps1
This PR does the following:
* Updates checks to allow for verbose output
* Updates messaging for checks looking for specific versions
* Updates the .NET check to look for the SDK, not the Runtime
* Updates the VS check to check for workloads and also have clearer messaging
* Removes the `Choco` check, instead only checking for Choco right before using it in an installer.
* Removes the `Chrome` check, as the Edge launches fine for a web-debugger
* Removes the `MSBuild64LongPath` check, as it's no longer required with VS 2022
Closes #10864
Closes #10865
Closes #10866
> Update `rnw-dependencies.ps1` to improve messaging

- change/react-native-windows-3ee0cf72-a448-421f-a738-e2aac37a7883.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/Shared.vcxitems
Instantiates Blob and FileReader modules by default
Conditional instantiation of the Blob module is only required for the Desktop variant (non-Blob-supporting HTTP modules are still used by consumers of `react-native-win32.dll`).
Resolves #10036
Removed conditions for instantiation (UWP only) of:
- HttpModule
- BlobModule
- FileReaderModule
Drop conditional instantiation `Microsoft::React::NetworkingModule`.
RNTester app:
- XHRExample
- HTTPExample
> Always instantiate Blob module in UWP

- change/react-native-windows-27063fbb-4174-416f-87e8-24c77ce8c128.json
- vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
Note this is a duplicate of https://github.com/microsoft/react-native-windows/pull/10598. See comments there for why it had to be duplicated.
[Per WinAppSDK the CoreWindow class is unsupported](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#core-unsupported-classes). It's used in KeyboardEventHandler for calling GetKeyState, which the docs provide an alternative:
> Instead of the [GetKeyState](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow.getkeystate) method, use the [InputKeyboardSource.GetKeyStateForCurrentThread](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.input.inputkeyboardsource.getkeystateforcurrentthread) method provided by WinUI 3 instead.
This PR makes that change.
- Bug fix …
> Fix WinUI 3 crash when using keyboard due to KeyboardEventHandler using unsupported class

- change/react-native-windows-ff50e610-93be-4811-8f59-c025680f6f77.json
- vnext/Microsoft.ReactNative/Views/ViewControl.cpp
- vnext/Microsoft.ReactNative/Views/ViewControl.h
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/Microsoft.ReactNative/Views/cppwinrt/ViewPanel.idl
In preparation for a change that moves away from a custom ViewPanel implementation to core XAML controls (like Grid and Canvas), this change removes the dependency on ViewPanel wrapper calls to manage children.
It also changes ViewControl to return a generic XAML Panel type rather than ViewPanel. There are no callsites in react-native-windows where this must be a ViewPanel type, but since this is API is exposed via the ViewControl ABI to third parties, this must be considered a breaking change.
This just re-publishes #10640, which was already approved.
> Use standard Panel APIs for children in ViewViewManager

- change/react-native-windows-d6678bf6-0866-4c10-95bb-05c3f23042b9.json
- vnext/Directory.Build.props
- vnext/Folly/cgmanifest.json
In #10881 I missed updating the commit hash for the manifest.
> Align folly commit hash with folly version

- change/react-native-windows-810f7970-4604-4fe4-8b17-3bf02d9c14bb.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Scripts/OfficeReact.Win32.nuspec
- vnext/Scripts/Tfs/Layout-Desktop-Headers.ps1
- Latest version of folly headers depend on fmt.  So, we need to add the fmt headers to the office nuget.
- Also fixed it so that we ship the patched folly headers in the nuget.
- Export additional folly symbols required by office from desktop dll
None of these changes will affect the MS.RN dll.
> Fixes for Office usage of latest canary

- change/react-native-windows-e435a388-efe0-4ff8-ade9-5ac10965c163.json
- vnext/Folly/Folly.vcxproj
- vnext/Folly/Folly.vcxproj.filters
- vnext/fmt/fmt.vcxproj
Fix compilation errors in developer enlistments caused by failed patching of `Folly` files.
We have three different projects that are patching files that are brought from other repos: `Fmt`, `Folly`, and `ReactCommon`.
The `ReactCommon` copies the patch files without using incremental logic where the target has list of inputs and outputs.
The other two projects use the incremental logic.
The problem is that if the external framework has files newer than the patch files in the developer's enlistment, then these patch files are not copied. Thus, developers may see compilation errors with the unpatched code.
These errors are not observed in CI environment because it always sets newer timestamps on checked out files.
To fix the issue, the …
> Fix copying patch files in Folly and Fmt projects

- change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
As we switch to VS 2022, and encourage people to upgrade, this is a problem as our CLI still tries to use VS 2019 if that's all that's installed. It also means if they install VS 2022, our CLI in …
> Fix CLI to search for correct VS version range

- change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
This PR backports #10922 to RNW 0.70.
As we switch to VS 2022, and encourage people to upgrade, this is a problem as our CLI still tries to use VS 2019 if that's all that's installed. It also means …
> [0.70] Fix CLI to search for correct VS version range

- change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
This PR backports #10922 to RNW 0.69.
As we switch to VS 2022, and encourage people to upgrade, this is a problem as our CLI still tries to use VS 2019 if that's all that's installed. It also means …
> [0.69] Fix CLI to search for correct VS version range

- change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
This PR backports #10922 to RNW 0.67.
As we switch to VS 2022, and encourage people to upgrade, this is a problem as our CLI still tries to use VS 2019 if that's all that's installed. It also means …
> [0.67] Fix CLI to search for correct VS version range

- change/react-native-windows-8b277652-e95c-43b7-9c81-00a11493947d.json
- vnext/Mso/smartPtr/cntPtr.h
Avoid template type shadowing for CntPtr.
Clang compiler has a warning if the same template type used for the class and for its members.
The member template type is "shadowing" the class template type.
If warnings are treated as errors, then it may end up being a compilation error.
We must fix it for Meta team who uses Clang compiler.
Changed template type name from `T` to `T1` where the conflict could be found.
It is not the ideal solution because we do not have a build configuration that uses Clang front end.
It would be great to enable RNW compilation using Clang for future verifications.
All code compiles as before, but we still cannot verify that all code is compilable by Clang.
> Avoid template type shadowing for CntPtr

- change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
This PR backports #10922 to RNW 0.68.
As we switch to VS 2022, and encourage people to upgrade, this is a problem as our CLI still tries to use VS 2019 if that's all that's installed. It also means …
> [0.68] Fix CLI to search for correct VS version range

- change/react-native-windows-e1f270c5-39a5-4d8a-8f95-8a311727dca2.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/CompositionHwndHost.idl
- vnext/Microsoft.ReactNative/CompositionRootView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
Modifies the interface of `CompositionRootView` to take a `ReactViewHost` instead of separate properties for `ComponentName` and `InitialProperties`.  This enables updates to those properties to be made atomically rather than triggering two rootview reloads to update them both.  
This aligns the interface much better with how the RootView interfaces have worked in Office for a while.  -- We didn't update the ReactRootView interface to match to avoid making a breaking change. But it makes sense for the new interface to use the newer APIs.
> Use a ReactViewHost to specify view options on CompositionRootView

- change/react-native-windows-11b3105a-6557-4333-84b6-ebcf40ffc432.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHelpers.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/PropertySheets/React.Cpp.props
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
When turning on UseFabric experimental flag on the desktop build I hit a few build errors.  These changes make it so that the dll will build when the UseFabric flag is specified.
Prep for running fabric in Office.
I'm not going to turn on UseFabric by default in the desktop dll yet, since it increases the DLL size from 3.6MB to 5.5MB - And I don't think we'll be shipping fabric in 0.71.
> Minor build fixes to enable fabric in desktop dll

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/playground.yml
- .ado/scripts/RunProcDump.ps1
- .ado/scripts/SetupLocalDumps.cmd
- .ado/templates/cleanup-certificate.yml
- .ado/templates/prepare-build-env.yml
- .ado/templates/upload-build-logs.yml
- packages/integration-test-app/windows/integrationtest/Package.appxmanifest
This PR fixes the capturing of crash dumps of (UWP) applications run
during CI, specifically for the `e2e-test-app`, `playground` and the
`integration-test-app` test apps.
The standard method of capturing local dumps is to set the appropriate
registry keys for Windows Error Reporting to create the dumps in a local
directory. This is what our `SetupLocalDumps.cmd` script sets up for us.
However, this does not work on Azure DevOps machines. I suspect this is
due to a conflict with either the Datacenter/Azure Windows Server
images, or in how the Azure Watson service works, which uploads
crash dumps from ADO machines in an anonymized way MSFT.
No amount of configuring WER, disabling auto-debuggers, analyzing the
Windows Event Log, etc. has worked for trying to get WER to save local
crash …
> Use ProcDump to capture crash dumps in CI pipelines

- change/react-native-windows-cafebabf-5714-4f76-9359-584cca01febc.json
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
- vnext/Shared/Networking/IWebSocketResource.h
We see that application crashes when we do direct debugging with V8 engine that accessed through the Node-API.
The issue is that current task runner (V8 dispatcher queue) implementation lifetime is bound to the `napi_env` object, and any task posted to that queue is crashing. The correct implementation of the task runner must be independent from the `napi_env`.
In [this v8-jsi PR](https://github.com/microsoft/v8-jsi/pull/153) we change the task runner API and the implementation.
In this PR we do the corresponding changes to the `NapiJsiV8RuntimeHolder.cpp` that implements the task runner on top of the JS message queue. The new `NapiTaskRunner` and `NapiTask` do not have dependency on the `napi_env` and can be deleted at any time by …
> [0.68] Fix V8 Node API Task Runner implementation

- change/@office-iss-react-native-win32-7fce2b29-0c20-4c4f-b2c6-8c4e7001f7cd.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
* add new prop alwaysShowToolTip to ViewWin32
* Change files
* Change files
Adding the `alwaysShowToolTip` prop for RNWin32's View.
To keep native behavior where certain components are tagged to not show tooltips while giving clients the flexibility to use JS to override this behavior and show tooltips if necessary.
This change will be backported back to 0.66 so that it can be consumed by Office.
Added `alwaysShowToolTip` prop to the typing for ViewWin32. Also added `alwaysShowToolTip` to the list of `validAttributes`.
> [0.66] Add new prop alwaysShowToolTip to ViewWin32 (#10381)

- change/react-native-windows-9bafa41c-fc12-4ffa-b62c-8a2820372974.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
As described in #10132, controlled text updates from JS to XAML TextBox for TextInput cause the undo redo history to be lost because imperatively setting the XAML TextBox::Text property resets history on the TextBox.
Resolves #10132
This change finds a single diff in the before and after string and uses the SelectedText property which retains undo/redo history.
https://user-images.githubusercontent.com/1106239/174148621-695de902-72be-4e28-a15e-0dd16dcee61b.mp4
> Adds logic to retain undo/redo history for TextInput

- change/react-native-windows-5ac680e0-432f-409a-9330-c652a9b8c923.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHelpers.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Utils/Helpers.cpp
- vnext/Microsoft.ReactNative/Utils/Helpers.h
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
- vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
- vnext/Microsoft.ReactNative/Views/PopupViewManager.cpp
- vnext/Microsoft.ReactNative/XamlHelper.cpp
- vnext/Microsoft.ReactNative/XamlHelper.h
- vnext/Shared/Composition/CompositionSwitcher.interop.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Changes to further support of fabric in the desktop dll. 
- Adds a property to allow apps to override the platform that RNW uses when requesting bundles from metro.  (The Desktop DLL uses win32 currently, and we want it to use windows when running fabric).
- Add the ImageLoader and Animation native modules to the desktop dll, while if def-ing out some of the paper specific functionality.
> More support for running fabric in desktop dll

- change/@office-iss-react-native-win32-09122742-d6a3-4232-ad09-91d594721b50.json
- change/react-native-platform-override-9750f78b-6b48-4fa5-ab0b-31b4fa8e7f0c.json
- change/react-native-windows-d2516c3f-bb61-44bd-980e-846418091114.json
- packages/@office-iss/react-native-win32-tester/tsconfig.json
- packages/@office-iss/react-native-win32/tsconfig.json
- packages/@react-native-windows/tester/tsconfig.json
- packages/playground/tsconfig.json
- packages/react-native-platform-override/tsconfig.json
- vnext/tsconfig.json
At one point core had some bad imports within the .d.ts files which required explicit path redirection for "Utilities" in our tsconfigs.  That has since been fixed in core, so we can remove the workaround.
> Remove work around for broken Utilities import in core

- yarn.lock
This PR updates the following packages to resolve Component Governance alerts.
* `decode-uri-component@0.2.0` to `decode-uri-component@0.2.2`
* `simple-git@3.10.0` to `simple-git@3.15.1`
> [0.70] CG Updates for 12/12/22

- yarn.lock
This PR updates the following packages to resolve Component Governance alerts.
* `decode-uri-component@0.2.0` to `decode-uri-component@0.2.2`
* `simple-git@3.7.1` to `simple-git@3.15.1`
> [0.69] CG Updates for 12/12/22

- change/react-native-windows-a67cca50-e44b-4dfd-82c0-d862ee697ddb.json
- vnext/Microsoft.ReactNative/Views/Text/TextPropertyChangedParentVisitor.cpp
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Text should be marked dirty when descendant text nodes are added or removed, and Text should also be marked dirty when descendants of descendant virtual text nodes have changes to their text content.
Resolves #11007
This change ensures that the Yoga node for Text is appropriately updated when these types of changes occur.
Please note, this is likely to create a slight performance regression for apps that modify nested text content after initial mount, as these changes previously would not trigger text measurement, and now they will. But it's worthwhile to trade correctness for a minor performance benefit.
Ran a test in simple.tsx:
```
import React, {useState} from 'react';
import {AppRegistry, Text, View} …
```
> Mark Text dirty when descendant Text updates occur

- change/react-native-windows-dc9c358f-08b5-4a90-aca1-37f042a31a3f.json
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
In #10811, a bug was introduced where a raw text update to a non-optimized Text component would call ClearValue on the TextBlock::TextProperty. This behavior was introduced to ensure that we cleared out the TextProperty before transitioning from optimized to non-optimized text.
To fix this bug, we check that the text is actually optimized before clearing the TextProperty, and for the case of transitioning text from optimized to non-optimized, added an optional flag that must be set to true before attempting to clear the text.
Please note, we never transition from non-optimized to optimized text, so we don't need to worry about that case.
One of the examples in RNTester was reproing the case where the text …
> Fix raw text update clearing Text

- change/@office-iss-react-native-win32-d749cec8-efe8-47ab-86f3-2a7777738436.json
- change/react-native-windows-d03682bc-a25c-4760-a5f6-c2f540cb8725.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
Remove some legacy code that unnecessarily overrides `onBlur` and `onFocus` in Pressable
As far as I can tell, we were unnecessarily overriding `onFocus` and `onBlur` in the desktop Pressable forks. This (may) have caused Pressable to fail shallow compare and re-render unnecessarily, affecting downstream components in FluentUI React Native. Those specific event handlers are already handled in `Pressability.js` and passed into Pressable via the `{...eventHandlers}` spread across React Native Core, windows, and macOS. 
Tested in Playground. …
> Remove unnecessary overrides to `onFocus` and `onBlur` in Pressable

- change/@office-iss-react-native-win32-d749cec8-efe8-47ab-86f3-2a7777738436.json
- change/react-native-windows-d03682bc-a25c-4760-a5f6-c2f540cb8725.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
Cherry pick of https://github.com/microsoft/react-native-windows/pull/10942 to 0.69-stable
> [0.69] Remove unnecessary overrides to onFocus and onBlur in Pressable

- change/@office-iss-react-native-win32-d749cec8-efe8-47ab-86f3-2a7777738436.json
- change/react-native-windows-d03682bc-a25c-4760-a5f6-c2f540cb8725.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
Cherry pick of https://github.com/microsoft/react-native-windows/pull/10942 to 0.70-stable
> [0.70] Remove unnecessary overrides to onFocus and onBlur in Pressable

- change/@office-iss-react-native-win32-d749cec8-efe8-47ab-86f3-2a7777738436.json
- change/react-native-windows-d03682bc-a25c-4760-a5f6-c2f540cb8725.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
Cherry pick of #10942 to 0.71-stable
> [0.71] Remove unnecessary overrides to onFocus and onBlur in Pressable

- change/@office-iss-react-native-win32-d749cec8-efe8-47ab-86f3-2a7777738436.json
- change/react-native-windows-d03682bc-a25c-4760-a5f6-c2f540cb8725.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
Cherry pick of https://github.com/microsoft/react-native-windows/pull/10942 to 0.68-stable
> [0.68] Remove unnecessary overrides to onFocus and onBlur in Pressable

- yarn.lock
This PR updates the following packages to resolve Component Governance alerts.
* `decode-uri-component@0.2.0` to `decode-uri-component@0.2.2`
* `simple-git@3.7.0` to `simple-git@3.15.1`
* `qs@6.5.2` to `qs@6.5.3`
> [0.67] CG Updates for 12/12/22

- change/@react-native-windows-codegen-ff424731-8dc6-4b44-a5d1-85240605b704.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts
- packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
- packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts
- packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
- yarn.lock
Upgrade to the latest react-native-codegen to get:
- Codegen for `T` in `Promise<T>`
- New supported types in turbo module
This change only upgrades the codegen with types supported in the latest codegen, but it doesn't really upgrade the codegen to use the latest parser because it is not published to npmjs (only in react-native-tscodegen) yet. So generated files are not changed, changing will be observed when react-native-windows upgrades react-native-codegen the next time.
> Upgrade to use the latest react-native-codegen

- change/react-native-windows-d248c415-5cbc-46a9-8128-aa395fea889c.json
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
This was missed when reverting the WinUI Fabric implementation.
> Cleanup unnecessary include in TouchEventHandler

- change/@react-native-windows-telemetry-21753aad-03c1-4294-b3d9-1daa90657f55.json
- change/react-native-windows-c9f4944e-e44c-4b9f-ac94-acc86c1fc249.json
- packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/playground/windows/playground-composition/packages.config
- packages/playground/windows/playground-win32/packages.config
- packages/playground/windows/playground/packages.config
- packages/sample-apps/windows/SampleAppCS/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
- vnext/PropertySheets/JSEngine.props
In #10811, a bug was introduced where a raw text update to a non-optimized Text component would call ClearValue on the TextBlock::TextProperty. This behavior was introduced to ensure that we cleared out the TextProperty before transitioning from optimized to non-optimized text.
To fix this bug, we check that the text is actually optimized before clearing the TextProperty, and for the case of transitioning text from optimized to non-optimized, added an optional flag that must be set to true before attempting to clear the text.
Please note, we never transition from non-optimized to optimized text, so we don't need to worry about that case.
One of the examples in RNTester was reproing the case where the text …
> [0.71] Fix Raw Text Update Clearing Text

- change/react-native-windows-fdeebb2c-7e65-431c-bff1-efc8aeb24786.json
- packages/playground/windows/NuGet.Config
- packages/playground/windows/playground-win32/Playground-Win32.cpp
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
- vnext/Shared/OInstance.cpp
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
Picking up an updated V8 package version and fix the projects that broke because we're not actively testing this configuration. This is cherry picking the same change from 0.70 (#10770) and enabling multi-threaded support in V8 for Fabric.
> V8 Package Update

- change/react-native-windows-02bc19fb-606a-49b9-b555-145c15e79849.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
See #10278.
#10278 indirectly fixes a header list rendering bug (trailing comma skipped if both request and request body have headers).
This bug still exists in branch `0.68-stable` as of `react-native-windows_v0.68.25`.
Missing coverage for `OriginPolicyHttpFilter::SendPreflightAsync`'s header handling.
- Defines test `Microsoft::React::Test::OriginPolicyHttpFilterTest::ValidatePreflightResponseMainAndContentHeadersSucceeds` covering bug fixed by #10278.
- Allows resetting static instance HTTP origin to `nullptr` (empty string).
- Added test `Microsoft::React::Test::OriginPolicyHttpFilterTest::ValidatePreflightResponseMainAndContentHeadersSucceeds`.
> Test Access-Control-Request-Headers

- change/react-native-windows-02bc19fb-606a-49b9-b555-145c15e79849.json
- change/react-native-windows-2b1076e7-13bc-47c6-b7f0-c00f1e0bb5e4.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.69] Test Access-Control-Request-Headers

- yarn.lock
This PR updates the following packages to resolve Component Governance alerts.
* `decode-uri-component@0.2.0` to `decode-uri-component@0.2.2`
* `simple-git@3.7.0` to `simple-git@3.15.1`
* `qs@6.5.2` to `qs@6.5.3`
> [0.68] CG Updates for 12/12/22

- change/react-native-windows-68b9b820-27ca-4ff1-b24f-dd09ca290429.json
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.h
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Enriches `nativeEvent` objects received on JS side in Image `onError` callback with error message.
Resolves  #10491
In place of a `bool` flag indicating success use `winrt::hstring` for event payload and populate it with the error message. Empty string (default) indicates success.
Using a string instead of a more descriptive structure to avoid creating a new RT type required by `winrt::EventHandler`.
Compared Image page in RNTesterApp before and after the change.
Confirmed the only difference is ErrorHandler section now showing "Failed to load image (E_NETWORK_ERROR)" message.
> ReactImage: propagate error messages to JS

- change/react-native-windows-b23dc862-597b-4f85-a0e1-d8972cd1d250.json
- vnext/src/Libraries/NativeComponent/BaseViewConfig.windows.js
We derive BaseViewConfig from the iOS implementation, which included a line that conditionally ignored event props in case the code was used on any platform other than iOS. This prevented event props from reaching native components that used `createViewConfig` (e.g., Text).
Resolves #11058 
Resolves #11060
This removes the conditional function from BaseViewProps for Windows.
Ran this simple example:
```
/**
* Copyright (c) Microsoft Corporation.
* Licensed under the MIT License.
* @format
*/
import React from 'react';
import {AppRegistry, Text} from 'react-native';
export default class Bootstrap extends React.Component {
render() {
return <Text onLayout={e => alert(JSON.stringify(e.nativeEvent.layout))} />; …
```
> Do not conditionally ignore event props

- change/react-native-windows-315d6384-1100-4d1e-a3d3-bee8022d6556.json
- vnext/PropertySheets/Warnings.props
Resolves [#7251]
Removed warnings from the header that weren't being triggered
All warnings removed:
Only 4456 and 4702 included:
> Removed warnings that were not being triggered

- .ignore
- .vscode/settings.json
By default, vscode uses the `.gitignore` file to filter out files when searching and for intellisense. This is usually good because of how many dependencies RNW has that we don't ever look at.
However this limits our ability to easily browse, search, and jump into code we *do* actually want to look at, especially all of the shared C++ in RN (which is only increasing in the new architecture).
This change updates our repo's settings file and adds a new `.ignore` file where we can selectively allow certain folders under `node_modules` to improve the dev experience in vscode.
The new RN architecture means we more directly rely on C++ types defined in shared RN code, so it'll be much easier to work on Fabric if VS Code can see those …
> Fix search of react-native module code in vscode

- packages/@react-native-windows/tester/src/js/examples-win/Switch/SwitchExample.windows.js
The `accessibilityValue` prop is supposed to be an object with 4 properties: 'now', 'min', 'max', 'text'. The SwitchExample override for RNTester on Windows sets the accessibilityValue to a boolean value, which is not correct. For now, this just removes the accessibilityValue in this example as it will be problematic for prop deserialization in Fabric.
> Remove invalid accessibilityValue from SwitchExample

- change/react-native-windows-dfa2ac41-b89e-4284-b024-1919b83bce8a.json
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
For UWP apps, Flyouts were failing to launch with error message "The target view window lost focus before flyout could be shown."
Reverts #10863
> Revert Suppress Flyout if XamlRoot does not have focus

- change/@office-iss-react-native-win32-e6d5c674-2a76-46cb-bec5-e1cc8ce449bb.json
- change/@react-native-windows-cli-50376967-4cd2-4166-84fe-bbf1e72173c6.json
- change/@react-native-windows-codegen-03cb2506-ecd5-4a5f-b89e-8800325b9715.json
- change/@react-native-windows-find-repo-root-b5cc413e-590a-4470-9aa5-de640a8edd88.json
- change/@react-native-windows-fs-2a7cf726-c9b8-4047-83ef-31ccbfe51b58.json
- change/@react-native-windows-package-utils-c4ddf68b-c90f-47b0-a51f-b12caeff9de8.json
- change/@react-native-windows-telemetry-e66b54d8-5dd1-45f4-9276-8d2496a0a6a8.json
- change/@react-native-windows-virtualized-list-7817ad4c-deff-4759-a98d-d43348b60245.json
- change/react-native-windows-24dfeb0e-5cea-4819-8dc3-4667eb5e1f99.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- packages/@react-native-windows/virtualized-list/package.json
- vnext/package.json
> Move 0.70-stable to Legacy

- change/react-native-windows-17404ba8-a05f-44cf-b955-402a2d2aec67.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
Implement tintColor, blurRadius, and resizeMode=repeat for Fabric's Image.
> [Fabric][Image] Add tintColor, blurRadius, and resizeMode = repeat

- .ado/jobs/desktop.yml
- .ado/templates/enable-fabric-experimental-feature.yml
- change/react-native-windows-355cf654-ef14-44c6-b026-3063681c3fce.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/OInstance.cpp
Add verification that we can build the desktop dll with fabric enabled.
And to prove a point, fix some build breaks in the desktop dll when fabric is enabled.
> Ensure fabric desktop dll builds in PR

- .ado/publish.yml
Publishes a 2nd version of the Office nuget with an augmented version number: eg: `0.72.3-fabric` which includes binaries built with fabric support enabled.
Allows easier testing of fabric in office.
> Publish a fabric version of the desktop nuget.

- .ado/publish.yml
Fix the publish build.
My previous attempt to add publishing of fabric nugets as trying to use the matrix variables using template expressions.  Unfortunately, the matrix variables are only available at runtime, and the template expressions are evaluated at compile time.  So, I switched around the matrix and made everything compile time.
> Fix the publish buld

- change/react-native-windows-186959bb-b4aa-4a6d-98ce-d9c41cd1623b.json
- vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.h
Most operations in the NativeAnimatedNodeManager run on the UI thread, including operations that attempt to resolve Paper shadow nodes, and operations to run the tick-driven animations. It's possible that the UI thread operations may run after the NativeAnimatedNodeManager has been destroyed, in which case, we see crashes when unloading the React instance because we're referencing fields on `this` that no longer correspond to a valid NativeAnimatedNodeManager instance.
This change uses the same pattern we use in the PaperUIManagerModule to ensure that the UIManager instance is cleaned up on the UI thread, by posting the shared_ptr to the instance to the UI thread if it's available.
TBD
> Ensure NativeAnimatedNodeManager is destroyed on UI thread

- change/@react-native-windows-telemetry-778ea18a-3b80-476b-92e7-d46058128073.json
- change/react-native-windows-af5ee70c-4767-4145-82a9-61331fa11ab8.json
- packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
- packages/playground/windows/playground-composition/packages.config
- packages/playground/windows/playground-win32/packages.config
- packages/playground/windows/playground/packages.config
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/HermesRuntimeHolder.cpp
- vnext/Shared/HermesRuntimeHolder.h
- vnext/Shared/HermesSamplingProfiler.cpp
- vnext/Shared/HermesSamplingProfiler.h
- vnext/Shared/HermesShim.cpp
- vnext/Shared/HermesShim.h
- vnext/Shared/JSI/RuntimeHolder.h
Enable Hermes sampling profiler for RNW project.
Currently the Hermes sampling profiler does not work.
It prevents any related perf investigations.
The change has the following parts:
- We use new ABI-safe Hermes API based on C. Not all interactions with Hermes are ABI-safe yet. This is just a beginning.
- The `HermesShim` is changed to use the new API.
- We store `HermesRuntimeHolder` in the context properties. It allows us to add current Hermes runtime for the sampling profiling when it starts and then remove it when it is done.
- We must add and remove the runtime for sampling profiler in JS dispatcher queue. In this PR we expose the JS dispatcher from the `ReactDispatcher`.
- New `HermesRuntimeHolder` methods `loadFrom` and …
> Fix Hermes sampling profiler

- change/react-native-windows-30c9bb46-8ce0-4b9d-a42f-64a7b138a63b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/platform/cxx/react/renderer/graphics/Color.h
- vnext/Shared/Shared.vcxitems
#11163 - Add logic for value, disabled, thumbColor, onchange, onvaluechange
> [Fabric] Add initial implementation for Switch

- change/@react-native-windows-telemetry-a883e2fb-184e-4a5c-8e6a-c893f19aab47.json
- change/react-native-windows-161cd4d0-000f-40c3-8a37-f0260ef756d7.json
- packages/@react-native-windows/telemetry/src/test/projects/UsesPackageReference/UsesPackageReference.csproj
- packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/UsesPackagesConfig.vcxproj
- packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityInfoExample.js
- packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- packages/playground/windows/playground/packages.config
- packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Utils/Helpers.h
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/HermesRuntimeHolder.cpp
- vnext/Shared/HermesRuntimeHolder.h
- vnext/Shared/HermesSamplingProfiler.cpp
- vnext/Shared/HermesSamplingProfiler.h
- vnext/Shared/HermesShim.cpp
- vnext/Shared/HermesShim.h
- vnext/Shared/JSI/RuntimeHolder.h
- vnext/Shared/Networking/IWebSocketResource.h
Cherry pick PR #11033 to 0.69-stable branch. Original description:
Enable Hermes sampling profiler for RNW project.
Currently the Hermes sampling profiler does not work.
It prevents any related perf investigations.
The change has the following parts:
- We use new ABI-safe Hermes API based on C. Not all interactions with Hermes are ABI-safe yet. This is just a beginning.
- The `HermesShim` is changed to use the new API.
- We store `HermesRuntimeHolder` in the context properties. It allows us to add current Hermes runtime for the sampling profiling when it starts and then remove it when it is done.
- We must add and remove the runtime for sampling profiler in JS dispatcher queue. In this PR we expose the JS dispatcher from the …
> [0.69] Fix Hermes sampling profiler (#11033)

- change/react-native-windows-f6189755-f586-4f3e-b16b-be081501c566.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
- vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.h
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.cpp
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.h
- vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.cpp
- vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.h
When using a spec file to ensure the correctness of a TurboModule a javascript `string` must be treated as a `std::string`.  The `REACT_METHOD` macros already support using `std::string` or `std::wstring`.  This just extends the correctness check to allow either.
Then I'm simplified some of the existing methods of some of our module, now that they can take a wstring.
Not supported in this iteration is 
```cpp
REACT_METHOD(getString)
void getString(React::ReactPromise<std::wstring> result) noexcept;
```
@ZihanChen-MSFT , feel free to add to this PR, and change say ClipboardModule.cpp's getString to take a wstring.
Otherwise we can treat this PR as a step in the right direction.
> Allow some usage of wstring when using spec files

- change/@office-iss-react-native-win32-9f5db6b7-3bc9-44a5-8782-b196bf715d0a.json
- change/react-native-windows-eebbc51e-322e-4e65-91b9-06e417fca3e5.json
- packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorCodeFrame.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorReactFrames.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorStackFrame.win32.js
- vnext/src/Libraries/LogBox/UI/LogBoxInspectorCodeFrame.windows.js
- vnext/src/Libraries/LogBox/UI/LogBoxInspectorReactFrames.windows.js
- vnext/src/Libraries/LogBox/UI/LogBoxInspectorStackFrame.windows.js
We are providing a windows specific font in various places in the LogBox UI.  But the one we are using on windows is not a monospace font, unlike the ones using on Android/iOS.  This is mostly used to show code, callstacks etc. which are better displayed in monospace.
> LogBox should be using a monospace font

- change/react-native-windows-f8dcfdcc-9a1a-43ae-9fe1-be9df0568477.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/TouchEventEmitter.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/TouchEventEmitter.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/primitives.h
- vnext/overrides.json
- vnext/src/Libraries/Pressability/Pressability.windows.js
Core does not have MouseEnter/Leave events.  In order for apps to be able to do the migration to fabric we will need to keep supporting the MouseEnter/Leave events, even if fabric implements PointerEnter/Leave which will be the events we use going forward.
This adds MouseEnter/Leave to the TouchEventEmitter and ViewProps parsing code.  And extends the touch event handler to raise the mouseEnter/Leave events in addition to the newer pointer events.
One thing to note is that this PR uses the last two bits of the `ViewEvents` bitset.  This might cause issues if core adds additional events. -- But the bitset could be expanded on windows if we need to.
This PR also adds support for pointer/touch/mouse events to fire on text spans and fixes an issue in pressability that was preventing onPressIn …
> [Fabric] MouseEnter/Leave events to align with paper

- change/react-native-windows-c99cd5a3-0fac-4b41-b8c7-cd6099ea9c3b.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/CompositionUIService.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.h
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
- vnext/Microsoft.ReactNative/Modules/AlertModule.h
- vnext/Microsoft.ReactNative/RedBox.cpp
When running fabric, if XAML is not loaded in the app, then alerts cause the app to crash.
Provide a fallback implementation of alert which does not rely on Xaml
> [Fabric] Fix Alert crash when not using XAML

- change/react-native-windows-3e9d5740-8654-448c-9431-3b681c4de19d.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/CompositionUIService.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.h
- vnext/Shared/HermesSamplingProfiler.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Currently when the debug menu is triggered in fabric the app will crash if the app isn't a Xaml app.
- Adds an implementation of the debug menu using `MenuPopup`.
- Fallback to the `MenuPopup` implementation if there is not an active `XamlApplication`.
- Fallback to a no-op if the debug menu is triggered in a non-UI scenario rather than crashing.
- Support `MenuPopup` devmenu in the desktop dll reducing the diff between the dlls
- Moved `SetTopLevelWindowHandle` from `CompositionUIService` to `ReactCoreInjection`
> [Fabric] Fix debug menu crash when not using Xaml

- change/react-native-windows-0c94c8d0-a6e7-4de0-97ee-ea94cd1b841e.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Fabric reads native view configs from the Paper UIManager. In order for the `collapsable` prop to flow from JS to the native props for Fabric, we need to have this prop set in the VM configuration for View in Paper.
Without this prop, `collapsable="false"` will not work in Fabric.
> Adds collapsable prop to Paper VM for View

- change/react-native-windows-0d249a84-b206-4efd-bdcb-1888c83a3b3d.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewEventEmitter.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewEventEmitter.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewShadowNode.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/primitives.h
- vnext/overrides.json
Implements onFocus and onBlur for fabric.  This adds the events to the ViewProps, ViewEventEmitter structures.
Minor fix to add logic to clear the focused component when a component is removed from the tree. (fixes a crash on reload)
Minor fix to fix an issue where updates to borderColor do not by themselves update the border.
This UI now shows the focus as it moves around when using tab/shift+tab.
```jsx
const FocusableViewThingy = () => {
const [isFocused, setIsFocused] = React.useState<boolean>(false);
return (
<View
style={{
backgroundColor: isFocused ? 'red' : 'green',
width: 50,
height: 50,
}}
focusable={true}
onFocus={() => setIsFocused(true)}
onBlur={() => setIsFocused(false)}
/>
);
};
export default class Bootstrap extends React.Component {
render() {
return (
<View …
```
> [Fabric] Implement onFocus and onBlur

- .ado/templates/apply-published-version-vars.yml
Our binaries (the version on the native dll's) for both win32 and UWP are always n-1. I.e. if the buld is 0.64.4 then the binaries are labeled 0.64.3. 
This is because the native versions are picked up from PackageVersions.g.props
This file is updated by beachball. This happens on the 'RnwNpmPublish` phase. but the bulid is happening on other machines .
So they see the versions in the file as the repo was cloned which is actually the previous version, not the updated version.
This change will run the script that updates the packageversion.g.props file on each build machine (after it pulled in all the pipeline/environment variables from that phse.
We are shipping with mismathed versions (nuget is n, binaries …
> Update version logic to fix n-1 bug in version on binaries

- .ado/publish.yml
Upgarde the `yarn install ` step to `prepare-js-env .yml` so that we also build the js scripts.
This is now needed because my previous commit extended the set-version script to also generate the right version.g.props.
An alternative fix would have been to add a parameter and conditionalize the stamp-version call but this seems more consistent, easier to understand at the expense of only a minute on the critical path.
This is a fix for the release pipeline, as it is currently broken.
Broken publish pipeline
change to yaml
> Update Sign phase to do prepare-js-env instead of only yarn install

- change/react-native-windows-6c7cee5f-4e4d-4054-8e32-718e45346198.json
- vnext/ReactCommon/ReactCommon.vcxproj
The ForcedIncludeFiles is including a file that was added as an include in this commit. https://github.com/facebook/yoga/commit/084d5935e6f6bf7306ad8041bdc2f097889b8e58
Code cleanup.
> Remove an unneeded force include from yoga/utils.cpp

- change/react-native-windows-f98b2d6c-89f0-47c2-8138-147e647c09d8.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.h
- vnext/Microsoft.ReactNative/Utils/TransformableText.h
Adds a cache for text measure.
Adds support for `lineHeight`, `letterSpacing`, `maximumNumberOfLines` and `textTransform` properties on text.
> [Fabric] Adds text measure caching. Add support for lineHeight, letterSpacing, maximumNumberOfLines and textTransform

- change/react-native-windows-dbb905be-476d-45bd-9f45-1196b92ce512.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.h
`enableFocusRing` is a property to display native focus visualization.  This adds support for that property.  For now, it's using a simple black rect.  In future this should be updated to align with windows visuals (Ex: rounded rect with black/white border)
This involved creating an extra container visual around views so that the focus rect can be outside the views clip (Ex: a view with a rounded rect would clip the focus rect if the focus rect was within the view's visual)
Also fixed some logic in the `walkTree` method, now that I can see focus it became clearer that I completely messed up the first implementation.
Added handling of the focus command, so now `ref.focus()` works.
> [Fabric] add support for enableFocusRing

- change/react-native-windows-8930e00f-f3bb-4781-b282-37e9df2b9be7.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Implemented `backfaceVisiblity` on fabric.
Note this was never implemented in paper since Xaml doesn't expose it, see https://github.com/microsoft/microsoft-ui-xaml/issues/2728 for more details.
But since it's a pretty trivial implementation for the wincomp implementation I'm going ahead and hooking it up.
> [Fabric] Add support for backface visibility

- change/react-native-windows-7ca5a6b9-f600-42ba-8da0-edd37853ef6a.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
Adds handling of `backgroundColor` on `Text` and nested `Text` components.
Also fixes the implementation of `opacity` on `Text` components.
> [Fabric] Add support for backgroundColor on text and text fragments

- change/react-native-windows-89fafeeb-2f97-4e19-b61a-2b4b290c4b23.json
- vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/windows/WindowsViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/windows/WindowsViewProps.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/windows/primitives.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewProps.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewShadowNode.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/primitives.h
- vnext/Shared/Shared.vcxitems
This reduces the diff we have in ViewProps down to some diffs that we hope to upstream.  @rozele, comments welcome on the specifics here.  Essentially each platform will be able to define their own HostPlatformViewProps with platform specific properties.  I also extended the functionality of HostPlatformViewProps slightly to allow HostPlatformViewProps to override behavior around what props require forms stacking contexts and form views.
> [Fabric] Move Windows specific properties out of ViewProps into HostPlatformViewProps

- change/react-native-windows-29007162-af49-4bbc-a6d3-0f9efe78b98c.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
In WinUI tab will move focus out of a textinput.  Currently in fabric tab will enter a tab into the textinput.  This change updates the behavior to align with paper.  Now the user will have to use CTRL+Tab to enter a tab into a textinput -- and normal tab will move focus to the next control.
> [Fabric] TextInput shouldn't block the tab loop

- change/react-native-windows-50a9690e-5aa4-43e4-8b77-cadc11ba8fc6.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
> [Fabric] Add implementation of ScrollView.scrollto

- change/react-native-windows-5ba1a75b-3ae5-44cf-a4db-a34fc827f883.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Similar to https://github.com/microsoft/react-native-windows/pull/11249, I need to add submitBehavior as a prop to the TextInput Paper VM in order to use it in Fabric
I'm currently implementing blurOnSubmit in Fabric, which reads from submitBehavior. Since blurOnSubmit was never supported in Paper, this prop needed to be added. Merging this will allow the Composition version of Fabric to use it as well.
> Add submitBehavior prop to Paper VM for TextInput

- change/react-native-windows-c68eabbe-3264-4571-b4cf-eca9997af765.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
https://github.com/microsoft/react-native-windows/pull/11344 added a call to TryScrollPosition on ScrollView's visual.  
https://github.com/microsoft/react-native-windows/pull/11323 changed the type of m_visual to IVisual, and moved the ScrollVisual to m_scrollVisual.
> Fix build from merge conflict

- .ado/jobs/universal.yml
- .ado/templates/build-rnw.yml
- package.json
- yarn.lock
* Updated `hermes-engine` to 0.10.0
* Changed how ADO restores Nuget packages to not overwrite the config
> [0.67] Component Governance Updates for 3/13/23

- yarn.lock
* Updated `parse-path` to 4.0.4
* Updated `parse-url` to 6.0.5
> [0.69] Component Governance Updates for 3/13/23

- change/react-native-windows-e85b54fe-59c7-4b2b-84e2-e5c5e12667db.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Shared/Shared.vcxitems
When a component is registered in JS, but does not have a native implementation, we will create an `UnimplementedNativeViewComponentView` which will display an error to the developer in place of the view.
This will show up as a semi-transparent red box, with a string notifying the user which component is missing:
> [Fabric] Add visuals for fallback when a native component isn't registered

- .github/ISSUE_TEMPLATE/bug-report.yaml
Update issue template to use `react-native -v` instead of `react-native --version` since `--version` has been removed in new versions for some reason.
No code change, just github stuff.
Avoid `unknown option '--version'` error when following the steps to file a bug.
Github bug issue template
```
$ npx react-native --version
error: unknown option '--version'
$ npx react-native -v
10.1.3
```
> Update bug-report.yaml version command

- change/react-native-windows-00d5b8db-bd21-4d37-a622-82dbec4eac24.json
- vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
This PR backports #11374 to 0.68.
If there is a noexcept function on the stack, the CRT just calls abort instead of calling the handler registered via SetUnhandledExceptionFilter.
This change registers a handler for the SIG_ABRT (the abort signal) to attempt to collect crash details.
As before, nothing happens by default, this code path is only enabled if EnableDefaultCrashHandler is set to true.
> [0.68] CrashManager: handle abort signal

- change/react-native-windows-00d5b8db-bd21-4d37-a622-82dbec4eac24.json
- vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
This PR backports #11374 to 0.70.
If there is a noexcept function on the stack, the CRT just calls abort instead of calling the handler registered via SetUnhandledExceptionFilter.
This change registers a handler for the SIG_ABRT (the abort signal) to attempt to collect crash details.
As before, nothing happens by default, this code path is only enabled if EnableDefaultCrashHandler is set to true.
> [0.70] CrashManager: handle abort signal

- change/react-native-windows-00d5b8db-bd21-4d37-a622-82dbec4eac24.json
- vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
This PR backports #11374 to 0.71.
If there is a noexcept function on the stack, the CRT just calls abort instead of calling the handler registered via SetUnhandledExceptionFilter.
This change registers a handler for the SIG_ABRT (the abort signal) to attempt to collect crash details.
As before, nothing happens by default, this code path is only enabled if EnableDefaultCrashHandler is set to true.
> [0.71] CrashManager: handle abort signal

- change/react-native-windows-39502c8c-b5bb-4cb1-a869-0a605db2abe3.json
- vnext/Microsoft.ReactNative/Views/Text/TextHitTestUtils.cpp
We occasionally see crashes where we try to access the Width property of a null VisualParent result.
It's not clear why this would ever return null, but to avoid crashing, we'll just return false on the hit test instead.
> Fixes occasional crash in hit testing

- package.json
- yarn.lock
This PR adds a resolution to use `git-up@^7.0.0` to resolve CG alerts for CVE-2022-2900 and CVE-2022-0624.
> [0.69] CG Updates 3/27/23

- change/react-native-windows-a5110142-aafe-4bbf-ac8b-1a6c6cdd9405.json
- vnext/template/metro.config.js
New app projects built against main are unable to create their bundle (see https://github.com/microsoft/react-native-windows/issues/11437).
As such, all PRs are blocked as the New CLI app checks all fail.
The problem is that the metro config needs `transformer.assetRegistryPath` to be set to the location of `'react-native/Libraries/Image/AssetRegistry'`, as for some reason this isn't set anymore upstream.
This PR adds a workaround of specifying that path in our app template's metro.config.js file. This unblocks our PRs but we should probably find a better place than in an app template file.
Unblock our PRs.
Resolves #11437
Updates the new …
> Workaround fix for "missing-asset-registry-path" error to unblock PRs

- change/react-native-windows-3f1cdae2-0985-46e8-811f-5bf27d5897e3.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/QuirkSettings.cpp
- vnext/Microsoft.ReactNative/QuirkSettings.h
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
In multi-window XAML Islands apps that share a single UI thread for each window, focusing a view on a blurred window causes that window to get focus. Generally speaking, focusing a window should be explicit, and it's likely very rare that you would want a view getting focus to cause the entire window to get focus.
This manifests as problematic in two ways:
1. If you have a flyout shown and the flyout gets dismissed because you switch to another window, the parent window for the flyout would steal focus again when react-native-windows attempts to focus the target element.
2. If you re-render a view with a TextInput with `autoFocus={true}` and the parent window for that TextInput is blurred, the window will steal focus.
This change forces the user to first focus the window and update the …
> Suppresses auto-focus under certain conditions

- change/react-native-windows-7857ea29-339a-42e2-958b-383fecd2ce0e.json
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
There are edge cases where an Alert may be shown while the app is exiting. Generally, when the app is exiting, apps will have set the XamlRoot instance on XamlUIService to null. In this case, we may still attempt to show the alert on a XAML Island with a null XamlRoot instance, which would cause a crash.
This change just ensures that, if we are in a XAML Island and we don't have a valid XamlRoot to attach to the ContentDialog, we just treat the alert as dismissed.
Set up simple.tsx example to wire up onDismiss, added native button to Playground-Win32 to clear XamlRoot setting on XamlUIService, confirmed that trying to show an alert after setting XamlRoot to null on XamlUIService results in `onDismiss` …
> Fixes issue where Alert crashes

- change/react-native-windows-145b5e26-99fe-403f-9bb5-8e41695aac40.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
- vnext/Microsoft.ReactNative/Views/ViewPanel.cpp
- vnext/Microsoft.ReactNative/Views/ViewPanel.h
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/Microsoft.ReactNative/Views/cppwinrt/ViewPanel.idl
Currently, `overflow: hidden` is only implemented on `<View>`, but any node should be allowed to use this style.
This moves the logic to handle clipping to ViewManagerBase. This change also removes the Clip related properties from ViewPanel, forcing a breaking change (because ViewPanel is exposed through the ABI).
RNTester `overflow: 'hidden'`:
Test app:
https://user-images.githubusercontent.com/1106239/195151620-ad0ff0df-449f-4950-9f08-18ec6a323450.mp4
Please note, prior to this change, there was also a bug where, after being enabled, disabling the clip did not work correctly because the Clip property was only applied in ArrangeOverride.
> Allow ABIViewManagers to use `overflow: hidden`

- change/react-native-windows-2444e581-3cff-4874-99cb-83042f354ad0.json
- vnext/Directory.Build.props
Resolves intermittent issues due to build tools trying to access file paths that are too long by removing the unnecessary extra deep paths the regression caused. Our CodeGen tool (and …
> Ensure ReactNativeWindowsDir is set in Directory.Build.props 

- change/react-native-windows-2444e581-3cff-4874-99cb-83042f354ad0.json
- vnext/Directory.Build.props
This PR backports #11464 to 0.71.
Resolves intermittent issues due to build tools trying to access file paths that are too long by removing the unnecessary extra deep paths the …
> [0.71] Ensure ReactNativeWindowsDir is set in Directory.Build.props

- change/react-native-windows-2444e581-3cff-4874-99cb-83042f354ad0.json
- vnext/Directory.Build.props
This PR backports #11464 to 0.70.
Resolves intermittent issues due to build tools trying to access file paths that are too long by removing the unnecessary extra deep paths the …
> [0.70] Ensure ReactNativeWindowsDir is set in Directory.Build.props

- change/react-native-windows-2444e581-3cff-4874-99cb-83042f354ad0.json
- vnext/Directory.Build.props
This PR backports #11464 to 0.69.
Resolves intermittent issues due to build tools trying to access file paths that are too long by removing the unnecessary extra deep paths the …
> [0.69] Ensure ReactNativeWindowsDir is set in Directory.Build.props

- change/react-native-windows-2444e581-3cff-4874-99cb-83042f354ad0.json
- vnext/Directory.Build.props
This PR backports #11464 to 0.68.
Resolves intermittent issues due to build tools trying to access file paths that are too long by removing the unnecessary extra deep paths the …
> [0.68] Ensure ReactNativeWindowsDir is set in Directory.Build.props

- change/react-native-windows-298c0d56-3472-45c2-a2e6-8d139481f19c.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
This was causing a WM_CHAR to fallthrough to WM_KEYDOWN and produce a duplicate `sendMessage`
Resolves #11452
There was a switch case fallthrough happening from WM_CHAR to WM_KEYDOWN. The fix is to add a break statement.
Patched the source change into a Fabric app that was reproing the issue (AKA one with a `TextInput`)
> Fix unintended fallthrough causing duplicate WM_CHAR handling in Fabric TextInput

- change/@react-native-windows-codegen-d22ec400-245b-4772-9490-51187b083906.json
- packages/@react-native-windows/codegen/src/index.ts
Metro fails to create a Windows bundle on non-Windows platforms:
```
error Invalid platform "windows" selected.
info Available platforms are: "ios", "android", "macos", "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
```
Windows is not detected on case-sensitive file systems because it fails to import `react-native-codegen/lib/schemaValidator.js`. The filename is PascalCased.
Capitalizing the 's' in `schemaValidator.js` fixes the issue.
Create a Codespaces for https://github.com/microsoft/rnx-kit/tree/tido/bump-react-native. Run:
```
yarn
yarn build-scope test-app
yarn bundle
```
> fix: fix RNW not being detected on case-sensitive file systems

- change/react-native-windows-14dc008b-ae56-4cd9-b6ff-2fc6a6188aaf.json
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
iOS and Android each have their own approach to create view components immediately when the `UIManager.createView` operation is invoked. On Android, the `createView` operations are aggregated in a separate batch and allowed to run for half a frame. On iOS, the `createView` operations always immediately create the native view when the UIManager module method is called.
On Windows, we have been adding the `createView` operation to the batch of operations that invoke when the batch is completed, missing an opportunity to better utilize the UI thread while the JS thread is still busy doing work.
Passes the non-batched UI thread queue to the UIManager and uses that queue for `createView` operations.
Please note, this should not create any UI tearing, as the operations to mount the created …
> Avoid batching create view operations

- change/react-native-windows-a36ec836-ba77-4333-b68b-b14f0bf3fcdb.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Resolves #11461
- Set TXTBIT_MULTILINE and TXTBIT_WORDWRAP
Tested in playground composition on `TextInput` page with multiline.
> Fabric text input multiline

- change/react-native-windows-abfbdd0b-71c7-4d78-97a4-755729f5a8f4.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Resolves #11487
- Set TXTBIT_READONLY
Ran playground Composition with `TextInput` tests.
- Non-editable text can't be edited
- Editable (default) text can be edited
> Fabric text input editable

- change/react-native-windows-a9b52225-279c-4e00-b583-e636f952ea25.json
- packages/playground/Samples/textinput.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.h
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
I've added the support for the `cursorColor` property to the macOS repo already. This PR will help to keep parity between platforms https://github.com/microsoft/react-native-macos/pull/1787 
For our needs, we need to have more control over cursor/caret color. The `cusrorColor` property is already available on macOS after https://github.com/microsoft/react-native-macos/pull/1787 and documented in the docs https://reactnative.dev/docs/textinput#cursorcolor-android. However, there is currently no way to update the cursor/caret color on Windows.
- I've extended `HideCaretIfNeeded` logic to support the custom color of a caret. This function is already, in a sense, changing the color of a caret; however, it always sets it to be …
> Add cursorColor support to TextInput 

- change/react-native-windows-7cf2e2b2-8bb7-40e6-8859-f584c4033f3a.json
- change/react-native-windows-faa13d84-17c3-4e55-80c6-57de778b97ad.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
- Use case-insensitive comparison for CORS preflight responses (#11511)
- Remove change file
- Change files
If you added tests that prove your changes are …
> [0.71] Use case-insensitive comparison for CORS preflight responses (#11511)

- change/react-native-windows-7cf2e2b2-8bb7-40e6-8859-f584c4033f3a.json
- change/react-native-windows-a522f514-d922-4ef1-b08e-b4ed9da35b8e.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
> [0.70] Use case-insensitive comparison for CORS preflight responses (#11511)

- change/react-native-windows-7cf2e2b2-8bb7-40e6-8859-f584c4033f3a.json
- change/react-native-windows-bdf88ba7-a50d-4ef7-981e-8b3236240128.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
> [0.69] Use case-insensitive comparison for CORS preflight responses (#11511)

- change/react-native-windows-68014f5e-e915-4317-9813-190d860bbade.json
- change/react-native-windows-7cf2e2b2-8bb7-40e6-8859-f584c4033f3a.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
> [0.68] Use case-insensitive comparison for CORS preflight responses (#11511)

- change/react-native-windows-4a8225c9-1e85-41fe-8d90-5b644d0b9131.json
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.h
Resolves #11456
Implements some values in `PlatformColor` so that the built in controls can render.
Note that pending #11489, these colors will all be light mode. This will need to be revisited when theming exists.
| Before| After |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/26607885/231325843-c0e6d879-ebfe-47ed-a541-c00ecec59e5f.png) | ![image](https://user-images.githubusercontent.com/26607885/231326494-abd58e91-5f0e-4312-9819-f7ccd7d8045d.png) |
- Manual verification of controls in RNTester
- Integration into a Fabric ap using Button and other non-core controls that use …
> Fabric platform color

- change/react-native-windows-586654cb-7c55-466f-af1f-9dbd6119915e.json
- vnext/PropertySheets/JSEngine.props
Currently the version of V8 being used does not align with the JSI version.
> [0.71] Align V8 version with JSI version

- change/@office-iss-react-native-win32-fdb45b47-c860-41d5-ad06-6559e9e544bb.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.js
The ref property on ViewWin32 was not being correctly forwarded, which would result in refs to ViewWin32 ending up as undefined.
> [0.71] [NetUI] Fix ref's on ViewWin32 (enables ViewWin32.focus() calls to work again)

- change/@office-iss-react-native-win32-c2b31536-e590-4c91-af35-2219dec4d20b.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.js
The ref property on ViewWin32 was not being correctly forwarded, which would result in refs to ViewWin32 ending up as undefined.
> Fix ref's on ViewWin32 (enables ViewWin32.focus() calls to work again)

- change/react-native-windows-1959bf92-81c5-460b-81bf-d0721ed575fa.json
- vnext/PropertySheets/React.Cpp.props
Have C++ Windows SDK macros support Windows 10 and later.
Office, main dependant of `react-native-win32.dll` now supports only Windows 10 and later. Support for Windows 8.1 is no longer needed.
- Bump default setting of `_WIN32_WINNT_VERSION` to `_WIN32_WINNT_WIN10`.
> Bump C++ Windows Version macros to Windows 10

- change/@office-iss-react-native-win32-5447facd-67b7-441f-b3aa-500b5f208fda.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.js
Port of https://github.com/microsoft/react-native-windows/pull/11532 to 0.72
> [0.72] Fix ref's on ViewWin32 (enables ViewWin32.focus() calls to work again)

- change/react-native-windows-653e4153-09a8-46bf-8af3-bbfcca9c5902.json
- vnext/Directory.Build.props
- vnext/Folly/cgmanifest.json
The version of folly being used in 0.71 attempts to suppress -Wunknown-warning-option, which isn't implemented by clang.
This version bump bring in https://github.com/facebook/folly/commit/78df96048658cbe83cfc2e76af090aa50f4e36b4 which fixes this issue.
> [0.71] Minor bump of folly to bring in a fix for clang

- change/react-native-windows-ab602d01-7690-4880-8807-6f30b63422fe.json
- vnext/Directory.Build.props
- vnext/Folly/cgmanifest.json
The version of folly being used in 0.71 attempts to suppress -Wunknown-warning-option, which isn't implemented by clang.
This version bump bring in https://github.com/facebook/folly/commit/78df96048658cbe83cfc2e76af090aa50f4e36b4 which fixes this issue.
> [0.72] Minor bump of folly to bring in a fix for clang 

- change/@react-native-windows-cli-857835a8-a178-4d42-b725-4dbbf8babe70.json
- change/react-native-windows-0ffb618e-eb3c-4e1d-ac63-a02a84886056.json
- packages/@react-native-windows/cli/src/e2etest/healthChecks.test.ts
- packages/@react-native-windows/cli/src/healthCheckList.ts
- packages/@react-native-windows/cli/src/healthChecks.ts
- vnext/Scripts/rnw-dependencies.ps1
Almost any command run through react-native will first require the construction of the react-native config.  Part of react-native-window's contribution to the config runs PowerShell to get the list of health checks.  This change extracts the list of health checks so that the config can be returned without having to trigger PowerShell.
I also added some quotes around the PowerShell path, which fixes the health checks actually running correctly on my machine.
The invocation of PowerShell here is causing an intermittent failure during the strict build graph of Office.  This is also a slight performance improvement over the previous code.
Added a jest test to verify that the list in JS remains in sync with the checks in rnw-dependencies.ps1.
> Avoid having to launch PowerShell for every react-native config query

- change/react-native-windows-1d22a163-fe34-4bb8-84cd-16ca4ee138cb.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
In Fabric if you had specified a border on one side but not varying colors, it would not apply the border.
Resolves #11549
Check not just for non-uniform colors, but also for non-uniform sizes.
| Before | After | Paper |
|--------|--------|--------|
| ![image](https://user-images.githubusercontent.com/26607885/234415769-d959e87d-a2ff-42a2-adc6-23010f207f15.png) | ![image](https://user-images.githubusercontent.com/26607885/236342496-70a974a6-2f41-4239-8d19-09ce08ae1393.png)| ![image](https://user-images.githubusercontent.com/26607885/234415792-179777b3-006c-4ae0-9221-bd1ec42466d0.png) |
Modified pages in RNTester to cause it to repro (existing examples were either too plain or too fancy - none specifically had the repro of "set a single …
> Fix issue with mixed border widths on Fabric

- change/react-native-windows-0d31a01f-9831-4a2f-9b72-e5eeec31c183.json
- vnext/Scripts/rnw-dependencies.ps1
This PR improves the `rnw-dependencies.ps1` script to do a better job detecting Chocolatey's `choco` command.
Sometimes Chocolatey is installed but not in the `PATH`, a scenario which the script could not handle before, preventing installation of necessary components.
Closes #11207
Specifically, if the command is not in the `PATH` for some reason, the script will now try to look in the default install location (as defined by the official chocolatey install script).
This PR also:
1. Makes sure that we re-check for `choco.exe` after running its install script
2. Refactors direct calls to `choco.exe` into a function that ensures that chocolatey is available first
3. Improves message strings
N/A
I've tested installs in each scenario:
* Not …
> Improve Chocolatey detection in rnw-dependencies.ps1

- change/react-native-windows-cafebabf-5714-4f76-9359-584cca01febc.json
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #10966. Original PR description:
We see that application crashes when we do direct debugging with V8 engine that accessed through the Node-API.
The issue is that current task runner (V8 dispatcher queue) implementation lifetime is bound to the `napi_env` object, and any task posted to that queue is crashing. The correct implementation of the task runner must be independent from the `napi_env`.
In [this v8-jsi PR](https://github.com/microsoft/v8-jsi/pull/153) we change the task runner API and the implementation.
In this PR we do the corresponding changes to the `NapiJsiV8RuntimeHolder.cpp` that implements the task runner on top of the JS message queue. The new `NapiTaskRunner` and `NapiTask` do not have dependency on the …
> [0.72] Fix V8 Node API Task Runner implementation (#10966)

- change/react-native-windows-5cf81a32-9afd-461e-b345-5ca54e898dcc.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
Borders were not being drawn for Image and Switch fabric components.
> [Fabric] Fix borders for Image and Switch

- change/@rnw-scripts-doxysaurus-7a64cc60-7a5b-4c0b-8b9e-53447f0f76e8.json
- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
* Updated to `yaml@2.2.2`
Resolves Component Governance alerts.
Updates package versions.
N/A
N/A
> Component Governance Updates 5/8/23

- packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
The test `LegacySelectableTextTest.DoubleClickWhenSelectable` double clicks on a selectable text. This should register as one click to select the text and then pass the second click through to the press handler.
However *sometimes* on Windows Server 2022, both clicks get through, which means the test will fail randomly in CI and/or block unrelated PRs.
This PR changes the test to instead detect when that happens and log a warning, rather than fail the test and/or disable the entire test.
To stop the flaky test from sporadically blocking PRs.
Updated the `LegacySelectableTextTest.DoubleClickWhenSelectable` test.
N/A
Tests pass and show warning.
> Fix flaky DoubleClickWhenSelectable E2E test

- change/@office-iss-react-native-win32-733be819-9ae8-47c0-8e54-1620c7609496.json
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
Basically the types being exported from RNWin32 wouldn't be the specific win32 types unless you are using some new TS magic which most people won't be yet.  ViewProps extends AccessiblityProps, but AccessibilityProps has a .win32 override that is what you really want.
> [0.71] [Win32] Export additional TS types for back compat

- change/react-native-windows-10f7bacb-50c1-47f3-8944-047527d3413f.json
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
Same as #10311, but for AppearanceModule.h, which was added in #10682.
Changes include to not use relative path.
Solution builds.
> Remove relative path from codegen include in AppearanceModule.h

- packages/integration-test-app/tests/MountComponentTests.tsx
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
This PR removes the `Slider` test case in `MountComponentTests.tsx`.
This test has been marked to skip for almost three years now (so I imagine it never worked).
Even though the test was never run, recently just the act of trying to load the `Slider` component within the JS causes an uncaught exception to be thrown in debug builds, which blocks the whole test suite from running.
Closes #11556
Closes #11562
Unblocks integration-test-app from running in debug.
Closes #11556
Closes #11562
This PR removes the `Slider` test case in `MountComponentTests.tsx`.
N/A
Verified the integration-test-app now loads correctly.
> Fix integration test failures in Debug

- change/react-native-windows-74728d8a-1ece-4904-9a2f-2d682cd92eb7.json
- vnext/src/Libraries/Text/Text.windows.js
At some point we lost a bunch of properties on Text -- including accessibilityLabel.  This should light up those properties again.
During various RN merges - we brought in changes that extracted more props out of "restProps", but didn't merge in addition property sets on the components, so we lost the values of a bunch of properties.
> [0.71] Fix a bunch of properties on Text

- packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
This PR backports #11586 to 0.71.
The test `LegacySelectableTextTest.DoubleClickWhenSelectable` double clicks on a selectable text. This should register as one click to select the text and then pass the second click through to the press handler.
However *sometimes* on Windows Server 2022, both clicks get through, which means the test will fail randomly in CI and/or block unrelated PRs.
This PR changes the test to instead detect when that happens and log a warning, rather than fail the test and/or disable the entire test.
> [0.71] Fix flaky DoubleClickWhenSelectable E2E test

- packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
This PR backports #11586 to 0.72.
The test `LegacySelectableTextTest.DoubleClickWhenSelectable` double clicks on a selectable text. This should register as one click to select the text and then pass the second click through to the press handler.
However *sometimes* on Windows Server 2022, both clicks get through, which means the test will fail randomly in CI and/or block unrelated PRs.
This PR changes the test to instead detect when that happens and log a warning, rather than fail the test and/or disable the entire test.
> [0.72] Fix flaky DoubleClickWhenSelectable E2E test

- .ado/jobs/setup.yml
This PR fixes the problem where we're no longer getting the correct error when a PR is missing a change file.
So it's clear why the PR is failing (missing change file).
Closes #11610
Fixed the escaping of ther `yarn change` command in the error output so bash re-adds it properly
N/A
Ran a PR with this change without the change file.
> Fix PR change check

- change/react-native-windows-34076042-6abe-4d4a-8cdd-c76c0fd2685b.json
- change/react-native-windows-4312d17c-cd6d-4960-bcd1-5b3e1950953f.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/ReactCommon/Yoga.cpp
Resolves #11442 
Fixes flex gap extra spacing when children determine parent's main axis size.
This was fixed in Yoga with https://github.com/facebook/yoga/commit/ba27f9d1ecfa7518019845b84b035d3d4a2a665, backported to RN 0.71.0-rc.5 with https://github.com/facebook/react-native/commit/a0ee98dfeec1a75e649a935b733c70ae2cc1628d before we released.
Backports upstream change into v0.71.
> Fixes Flex Gap Extra Spacing when Children Determine Parent's Main Axis Size

- change/react-native-windows-1187ae94-06f0-4d36-bb52-87f96b11cdd7.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
Resolves bug where Fabric app's crash upon launch of Accessibility Insights due to unimplemented method. 
Resolves #11594 
Implements ScrollView props() function on Fabric.
> Implement ScrollView props() Function on Fabric

- packages/@react-native-windows/tester/src/js/examples/View/ViewExample.windows.js
Fix missing import in ViewExample.windows.js.
In https://github.com/microsoft/react-native-windows/pull/10764 some calls to Alert were introduced in ViewExample.windows.js but I'm not sure how it worked as it's missing an import for Alert. I'm not sure how to test accessibility actions, but to ensure this is actually an issue I added a separate `onPress={() => Alert.alert('Alert')}` call to that file and verified that when I press I get an error:
Add missing import.
In RNTester, go to View example and trigger an Alert call and confirm no error:
CC @chiaramooney
> Fix missing import in ViewExample.windows.js

- change/react-native-windows-3ef19692-9e5c-436c-8efe-c0555e8cfd84.json
- vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/src/Libraries/Components/TextInput/TextInput.windows.js
- vnext/src/Libraries/Components/View/View.windows.js
Currently accessibility information is only provided to the system if a component is both accessible and focusable.  This was done as part of some feedback from the accessibility team that all focusable controls need to provide accessible information.  But instead of just making it a requirement for something to be accessible to be focusable, it also made it a requirement that a component be focusable in order to be accessible which prevents applications from providing larger accessibility trees within a focusable component (Which we do in FURN and I'm sure other places).
This change allows the application more flexibility and replaces the previous logic that required accessibility and focusable to be linked with a warning if the developer makes a component focusable without it being …
> Allow apps to provide accessiblity information on non-focusable components

- .ado/variables/shared.yml
Our SBOM manifests can only be signed when running pipelines in the internal ADO for publishing official builds. This PR changes the config not not sign the manifests for PR/CI.
Unblock PRs.
Added variable to only enable signing when on the right ADO instance.
N/A
N/A
> Disable SBOM signing on CI/PRs

- change/react-native-windows-dd0239d5-4995-4d68-9d8a-6e4333066157.json
- vnext/src/Libraries/Text/Text.windows.js
At some point we lost a bunch of properties on Text -- including accessibilityLabel. This should light up those properties again.
During various RN merges - we brought in changes that extracted more props out of "restProps", but didn't merge in addition property sets on the components, so we lost the values of a bunch of properties.
> Fix a bunch of properties on Text

- change/react-native-windows-2d2547a4-0134-4bab-9e67-0b4997c13e26.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
1. At Meta we are using an older version of CppWinRT which doesn't support `multi_threaded_map`. We can't easily upgrade CppWinRT versions because we use clang and have run into issues with coroutines with newer versions of CppWinRT.
2. Using a `multi_threaded_map` in this part of the code is not necessary. The map is only ever used on a single thread. There's a potential performance hit to using `multi_threaded_map` unnecessarily.
Change `multi_threaded_map` to `single_threaded_map` in `WinRTHttpResource::PerformSendRequest`
Ran Playground win32 with a breakpoint on this line to make sure it gets called with RNTester. It does with URL http://localhost:8081/symbolicate.
> Change multi_threaded_map to single_threaded_map in WinRTHttpResource

- .ado/templates/run-compliance-prebuild.yml
Updates Guardian pre-build analysis tasks to v2.
Guardian v1 deprecation.
N/A
Ran compliance pipeline to confirm it still works.
> Update Guardian tasks to v2

- change/@react-native-windows-cli-e0d0ac4b-9d62-43e2-bcd9-1169b0c8c681.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
Fixes #10136
os.arch() returns 'ia32' for x86, and ia32 is not understood by the CLI
> Fix os.arch for x86/arm64

- change/react-native-windows-6c630b6e-c0af-460a-8d41-8dc1fdeedc57.json
- vnext/Scripts/rnw-dependencies.ps1
The dependency script could detect that a Preview install meets the version requirement, but when it came to installing any missing VS components, would fail to remember to use the Preview install.
Best case it would try to install a stable version and add the components to that instead.
This does not solve the problem of not being able to install Preview builds with Choco.
Closes #11665
So that users who have a VS Preview installed don't get another VS build installed - just add components to the existing installed preview.
Closes #11665
Updated the dep script.
N/A
Tested with 17.7 Preview installed and bumping the version number.
> Fix dependency script to install missing components for VS Preview

- change/react-native-windows-f7c98885-c2ec-4944-8d7b-03f0fcc696cc.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- Perf (non-breaking change which improves performance)
Recalculation of Yoga layout due to root view size change does not require that we re-run layout on all roots. It also does not require that we invoke UpdateLayout on any new nodes (as a resize operation is independent of a batch of UIManager operations).
This change limits the scope of Yoga calculation and application of Yoga results to XAML views to only the root view that changed size. This optimization primarily impacts apps with multiple windows, but can also benefit any React Native Windows app with multiple roots.
In a future PR, we could also track impacted roots in view manager operations by looking up the rootTag field on the ShadowNode, and only running Yoga layout on windows with actual …
> Limit Yoga layout to relevant root on resize

- change/@react-native-windows-cli-e0d0ac4b-9d62-43e2-bcd9-1169b0c8c681.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
This PR backports #11659 to 0.72.
* Update runWindowsOptions.ts
os.arch returns ia32 and arm64 for x86 and ARM64 respectively
> [0.72] Fix os.arch for x86/arm64

- change/@react-native-windows-cli-e0d0ac4b-9d62-43e2-bcd9-1169b0c8c681.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
This PR backports #11659 to 0.71.
* Update runWindowsOptions.ts
os.arch returns ia32 and arm64 for x86 and ARM64 respectively
* Change files
* lint
* lint
> [0.71] Fix os.arch for x86/arm64

- change/react-native-windows-6e318099-e71b-442b-952f-ee0dce881d46.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
N/A
Verified I can build `Microsoft.ReactNative.sln` with VS 17.6.
> Disable RestoreUseStaticGraphEvaluation for VS >= 17.6

- change/react-native-windows-6e318099-e71b-442b-952f-ee0dce881d46.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
This PR backports #11681 to 0.72.
N/A
Verified I can build `Microsoft.ReactNative.sln` with VS 17.6 and 17.5.
> [0.72] Disable RestoreUseStaticGraphEvaluation for VS >= 17.6

- change/react-native-windows-6e318099-e71b-442b-952f-ee0dce881d46.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
This PR backports #11681 to 0.71.
N/A
Verified I can build `Microsoft.ReactNative.sln` with VS 17.6 and 17.5.
> [0.71] Disable RestoreUseStaticGraphEvaluation for VS >= 17.6

- change/react-native-windows-6e318099-e71b-442b-952f-ee0dce881d46.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
This PR backports #11681 to 0.69. (Note: Building 0.69 with VS 2022 is not officially supported.)
N/A
Verified I can build `Microsoft.ReactNative.sln` with VS 17.6 and 17.5.
> [0.69] Disable RestoreUseStaticGraphEvaluation for VS >= 17.6

- change/react-native-windows-6e318099-e71b-442b-952f-ee0dce881d46.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
This PR backports #11681 to 0.70.
N/A
Verified I can build `Microsoft.ReactNative.sln` with VS 17.6 and 17.5.
> [0.70] Disable RestoreUseStaticGraphEvaluation for VS >= 17.6

- change/react-native-windows-7d58b39d-845e-4538-940b-3ac36dc79a8c.json
- vnext/Desktop/module.g.cpp
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService_emptyimpl.cpp
- vnext/Shared/Shared.vcxitems
Currently the fabric APIs are not part of the winmd published for win32.  This means that when swapping between the dll built with fabric and without requires a rebuild in Office - which makes the barrier for testing much higher.
With this change, the interface will be included in the win32 dll, even when not building with UseFabric.  This allows us to take the same build of Office and just replace the dll to be able to start testing fabric.
> [Win32] Always include fabric in win32 interface

- change/react-native-windows-941d3b7e-ef0f-4505-bab1-8848552defd6.json
- vnext/Microsoft.ReactNative/IReactNotificationService.cpp
Clang doesn't seem to infer the generic type argument. Making it explicit fixes the issue.
> Make IReactNotificationSubscription template explicit

- change/react-native-windows-6dfacc4e-2515-4030-9e63-9ed1789f5f8c.json
- vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.h
- vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Make ScrollView and ActivityIndicator not focusable by default as this was an inadvertent change made at some point after RNW 0.68.
In #11032 there was a change which made all ControlViewManager subclasses focusable by default. ScrollViewManager and ActivityIndicatorViewManager are two of those view managers, but both of those should not be focusable by default. Previously (e.g. in RNW 0.68) ScrollView and ActivityIndicator were not focusable by default.
Make ScrollView and ActivityIndicator not focusable by default.
Before all ScrollView components have a tab stop by default:
https://github.com/microsoft/react-native-windows/assets/359157/6f975c85-58ac-4358-ae8a-b37d041d238e
Before all ActivityIndicator components have a tab stop by …
> Make ScrollView and ActivityIndicator not focusable by default

- change/react-native-windows-9bada428-fb94-4baf-8e6f-c00637c09a13.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
Adding accent and system ui element colors. If XAML is loaded, we fall back to Paper/XAML brushes. 
Next iteration will add color cache and redraw when system colors change while app is running.
> [Fabric] Add basic PlatformColor support

- change/react-native-windows-bd63ab24-bc97-4f58-9566-b4f9ffa47214.json
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/StructInfo.h
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
- New feature
Get StructInfo<T>::FieldMap is initialized when the binary is loading, it would heavily affect performance when a binary has many modules. It should be initialized only at the first accessing.
Change `StructInfo<T>::FieldMap` to a function and perform lazy initialization inside.
N/A
Tested in `Microsoft.ReactNative.IntegrationTests`
> Get StructInfo<T>::FieldMap lazy initialized

- .ado/templates/run-compliance-prebuild.yml
- change/@office-iss-react-native-win32-e33cc16a-01b8-485d-b3dc-017ba9f1c528.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [Win32] [0.71] Add missing eventPhase on INativeKeyboardEvent

- .ado/templates/run-compliance-prebuild.yml
Current publish builds are failing a guardian check, but the build is not publishing the guardian logs, which makes it hard to work out what the actual break is.
> Publish Guardian Artifacts to help diagnose guardian breaks

- change/react-native-windows-init-af32cca8-44f8-41f9-8da0-93bbd2510923.json
- packages/react-native-windows-init/src/Cli.ts
The current react-native-windows-init script does not work inside a monorepo that uses workspaces because 
the `npm config get registry` command is not supported in workspaces.
This PR wraps the `execSync('npm config get registry')` call into a try catch so errors related to `ENOWORKSPACES` get ignored, defaulting `NPM_REGISTRY_URL` to `http://registry.npmjs.org`
Run cli locally inside a repo that uses workspaces
> [react-native-windows-init] Fix cli to work with workspaces

- change/react-native-windows-c0c1e5ac-9cf9-4281-9dd3-8e7f939c2bd4.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Adds borders to TextInput
Resolves #11573
https://github.com/microsoft/react-native-windows/assets/42554868/9588e170-a841-4c30-ac2b-f649efb7237a
tested locally
> [Fabric] Add borders to TextInput

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
This PR backports #11725 to 0.72.
> [0.72] Upgrade to BinSkim@4

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
This PR backports #11725 to 0.71.
> [0.71] Upgrade to BinSkim@4

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
This PR backports #11725 to 0.70.
> [0.70] Upgrade to BinSkim@4

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
This PR backports #11725 to 0.69.
> [0.69] Upgrade to BinSkim@4

- packages/@rnw-scripts/eslint-config/eslintrc.js
- packages/@rnw-scripts/eslint-config/package.json
- yarn.lock
This PR upgrades the dependency as it was re-named upstream.
Closes #11742
Changed the dependencies in `@rnw-scripts/eslint-config`'s package.json.
N/A
Ran `yarn lint` and saw no changes.
> [0.72] Migrate eslint-config from `@react-native-community` to `@react-native`

- change/@react-native-windows-codegen-ff424731-8dc6-4b44-a5d1-85240605b704.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts
- packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
- packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts
- packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
- yarn.lock
0.71.3 is used in devmain, but a new version of rnw/codegen is needed.
Port @react-native-windows/codegen to 0.71-stable
> [0.71] Port @react-native-windows/codegen to 0.71-stable

- change/react-native-windows-fae51559-4d2b-4ea7-bfa4-81a7a18a3108.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
Fixes the y-position of TextInput's caret when located within a ScrollView. The ScrollViewComponent adds extra space via the getClientRect after TextInput gets initially drawn. This uses the correct RECT that is set when TextInput is drawn.
Resolves #11486
Before
https://github.com/microsoft/react-native-windows/assets/42554868/75771d62-2545-4500-b854-fca3f3144c78
After
https://github.com/microsoft/react-native-windows/assets/42554868/7f8412e2-c488-4bc9-a9dc-4fedd011f60a
Tested locally
> [Fabric] Fix y-position of TextInput's caret

- change/@office-iss-react-native-win32-30310027-6d38-47eb-8a79-91a241429ff5.json
- packages/@office-iss/react-native-win32/.flowconfig
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewAccessibility.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Text/Text.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Text/TextProps.win32.js
Adds a few more aria alias for some additional accessibility props that we've added to win32.
> [win32] Add support for more aria props

- change/react-native-windows-651cbfc9-a4b2-454f-b132-80635ca04776.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Changed logic in FrameworkElementViewManager for setting 'collapsed' accessibility state so that collapsed is not set to true by default when expanded is false.
Resolves [#11734]
Checks to see if the expanded property is null i.e not set by the component. If so, sets collapsed to false instead of defaulting to true when expanded is false. If property is not null, then performs check and sets collapsed property based on value.
Tested locally on RNTester Button page in playground. Seems to be performing as desired there - Narrator no longer making 'collapsed' announcement on buttons and UIA tree reflects this with the ExpandCollapsed property being of LeafNode instead of collapsed. Tested on Buttons and Touchable components in the …
> Changed logic for setting collapsed property to true

- change/react-native-windows-e197677d-0e5d-43f3-87fe-94970b0c6521.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Backporting #11756 into 0.71
Changed logic in FrameworkElementViewManager for setting 'collapsed' accessibility state so that collapsed is not set to true by default when expanded is false.
Resolves [#11734]
Checks to see if the expanded property is null i.e not set by the component. If so, sets collapsed to false instead of defaulting to true when expanded is false. If property is not null, then performs check and sets collapsed property based on value.
Tested locally on RNTester Button page in playground. Seems to be performing as desired there - Narrator no longer making 'collapsed' announcement on buttons and UIA tree reflects this with the ExpandCollapsed property being of LeafNode instead of collapsed. Tested on Buttons and …
> [0.71] Changed logic for setting collapsed property to true

- change/@office-iss-react-native-win32-f40b1260-f10a-4a63-92f2-1b97efa0662f.json
- change/@react-native-windows-cli-85d7c36c-8164-484e-a503-a2aeea0d65ea.json
- change/@react-native-windows-codegen-be75ae98-1ec1-49ba-8cd9-20604693288d.json
- change/@react-native-windows-find-repo-root-00f0827f-505c-4e55-a8a0-f00df8dd4785.json
- change/@react-native-windows-fs-996f94b5-fb2d-4fe0-b273-9000b36fcbef.json
- change/@react-native-windows-package-utils-3d9ba78b-9864-4b2f-8323-a2935547372b.json
- change/@react-native-windows-telemetry-0673ff30-f39e-4aeb-bdea-391a70bc60e4.json
- change/react-native-windows-01b8a6cb-d629-4574-a77e-e871ce29dd57.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
Promote 0.71 to legacy in preparation for 0.72 promotion to latest.
> Promote 0.71 to legacy

- change/react-native-windows-9dd9ab69-35af-4ed6-b752-8660632e6fc6.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
Fix fetch failing with certain custom user agents.
Previously in PR https://github.com/microsoft/react-native-windows/pull/10279 there was a fix to skip user agent HTTP header validation, but then we lost that fix in https://github.com/microsoft/react-native-windows/pull/10534. This PR re-adds that fix.
As we did previously, skip user agent HTTP header validation.
Made a fetch request with header `'User-Agent': "CustomAgent [CustomAgentData/1;MoreCustomAgentData/2]"`.
Before it fails:
After it succeeds:
I used the following test case for screenshots above: https://github.com/lyahdav/react-native-windows/commit/c4e4bd87298d7111f8b2740f426da044cfc8ed12
> Fix fetch failing with certain custom user agents

- change/react-native-windows-c7574db8-26ae-4cd1-b76c-b9c712abc2bb.json
- vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.cpp
This bug was discovered while testing SampleAppCpp, and causes the app to crash after loading the bundle from metro.
Fix crash.
Replace call to `promise.Resolve(nullptr)` with `promise.Resolve("")`.
N/A
Verified SampleAppCpp can now launch.
> Fix AV in LinkingManagerModule when resolving promise with nullptr

- change/react-native-windows-9dd4df7c-d51b-4cc3-9da4-0be4e2ff6e8c.json
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Modules/BlobModule.h
- vnext/Shared/Modules/CxxModuleUtilities.cpp
- vnext/Shared/Modules/CxxModuleUtilities.h
- vnext/Shared/Modules/IWebSocketModuleContentHandler.h
- vnext/Shared/Modules/WebSocketModule.cpp
- vnext/Shared/Modules/WebSocketTurboModule.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Implements `REACT_MODULE` variant of `WebSocket`.
In the long term, we want all modules to be `REACT_MODULE`.
Blob-related modules are not essential for all React Native scenarios.
Thus, we should be able to lazy-load them as turbo-modules instead of instantiating them by default with every React instance.
- Defined `Microsoft::React::WebSocketTurboModule`.
- Added the following methods to `Microsoft::React::IWebSocketModuleContentHandler`:
- `ProcessMessage(std::string &&message, winrt::Microsoft::ReactNative::JSValueObject &params)`
- `ProcessMessage(std::vector<uint8_t> &&message, winrt::Microsoft::ReactNative::JSValueObject &params)`
Addresses #11790
Note, the TurboModule variant is currently not enabled. This PR only …
> Define WebSocket TurboModule

- .vscode/launch.json
This PR changes the launch config for VS Code so we can attach to an in-repo app with direct debugging through Metro.
Tested working with e2e-test-app with Hermes enabled.
> Fix VS Code Direct Debug config

- .ado/jobs/desktop.yml
BinSkim has been throwing warnings for Desktop ever since the upgrade to BinSkim@4. Particularly this is from scanning the Hermes and V8 dlls.
However both are sourced from their own Microsoft-owned repos and only consumed here via published NuGets. BinSkim should be running on those repos (if required) not here in RNW.
This PR updates the pipeline to only test the binaries built by this pipeline.
> Fix BinSkim warnings for Desktop

- .ado/jobs/desktop.yml
This PR backports #11816 to 0.72.
BinSkim has been throwing warnings for Desktop ever since the upgrade to BinSkim@4. Particularly this is from scanning the Hermes and V8 dlls.
However both are sourced from their own Microsoft-owned repos and only consumed here via published NuGets. BinSkim should be running on those repos (if required) not here in RNW.
This PR updates the pipeline to only test the binaries built by this pipeline.
> [0.72] Fix BinSkim warnings for Desktop

- change/react-native-windows-3c713eb8-d78f-4c25-99c0-77f22815766f.json
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
We display some error UI for an unimplemented view. If that unimplemented view has children we can just ignore them, no need to assert.
> [Fabric] No need to assert when an unimplemented view has children added to it

- .ado/jobs/macos-tests.yml
While generally the macos CI task completes well before its timeout, I hit a case where it just took longer than usual.
Ex: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=470103&view=logs&jobId=b8115773-854b-5a24-9853-4feb4834ad88&j=b8115773-854b-5a24-9853-4feb4834ad88
I dont see much harm in bumping the timeout some, since its by far not one of the longest tasks.
> Bump macos timeout

- change/react-native-windows-9f19f41a-f08e-48ba-becf-7867ac8521f5.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
When keyboarding around, if focus moves to a component outside of the current viewport of a scrollview, it should scroll into view.
> [Fabric]: Scroll Scrollviews to bring focused items into view

- change/react-native-windows-d66c1eef-4346-43c7-8451-78ebe39f062b.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/ExperimentalFeatures.props
Fixes local building of Desktop solution.
Local clones of this repository will fail to build the `ReactWindows-Desktop.sln` solution.
This happens because of a missing property required to compile Fabric/Composition empty implementations (i.e. `vnext\Microsoft.ReactNative\Fabric\Composition\CompositionRootView_emptyimpl.cpp`).
Set MSBuild property `IncludeFabricInterface` to `true` by default for project `React.Windows.Desktop`.
Build solution locally.
> Default IncludeFabricInterface to true

- change/@react-native-windows-cli-8ea2e77c-918e-4240-bec3-52c37a4d6a94.json
- change/@react-native-windows-codegen-ca21b1e7-110a-4564-827c-6138fa6852b3.json
- packages/@react-native-windows/cli/src/codegen.ts
- packages/@react-native-windows/codegen/Document.md
- packages/@react-native-windows/codegen/src/Cli.ts
- packages/@react-native-windows/codegen/src/generators/AliasGen.ts
- packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
- packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts
- packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
- packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts
- packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
- packages/@react-native-windows/codegen/src/index.ts
Some people are using turbo module in devmain without using the codegen, and already have `std::wstring` everywhere. We have to support this so that to replace these code to generated code little by little.
Add cppStringType option to @rnw/codegen. Cli will ensure that the value is either `std::string` (default) or `std::wstring`.
Manual tested and see output files do get `std::wstring`.
> Add cppStringType option to @rnw/codegen

- change/react-native-windows-892e60c4-d492-4ae4-b4a9-6bef92849776.json
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
> [0.71] Fix warning compiler may not enforce left-to-right evaluation order in braced initializer list

- change/@react-native-windows-cli-f40b1069-5931-47af-94ce-0c0c056f6d1f.json
- change/@react-native-windows-codegen-14224062-151e-446d-a3a2-1107be08b0c4.json
- packages/@react-native-windows/cli/src/codegen.ts
- packages/@react-native-windows/codegen/src/index.ts
The previous pull request allow `@rnw/codegen` to generate `std::wstring` instead of `std::string` via command-line argument. This pull request add the corresponding entry in `package.json`.
Manually tested
> Add configConfig.windows.cppStringType in package.json for @rnw/codegen

- NuGet.Config
- change/react-native-windows-bfb79e47-04d8-4f4e-a72f-26b1621873d2.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
CG is failing builds due to multiple nuget feeds in nuget.config.
Resolves #11557
> CG: Move to single nuget source

- change/react-native-windows-ccec3086-548e-40b6-a95d-41c1ca26caff.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
`REACT_MODULE` instantiate a function to a global linked list. Such function calls `winrt::Microsoft::ReactNative::MakeModuleProvider`, forcing its implementation to load at binary startup. When auto registration is not in use, such work is unnecessary.
Added `REACT_MODULE_NOREG`.
- Microsoft.ReactNative.IntegrationTests
- Microsoft.ReactNative.Cxx.UnitTests
> Add REACT_MODULE_NOREG which is REACT_MODULE but without auto registration

- change/react-native-windows-34eb3554-b2c4-4faa-bfe8-1ce06c659aa3.json
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
> Fix warning compiler may not enforce left-to-right evaluation order in braced initializer list

- package.json
- yarn.lock
This PR updates:
* `tough-cookie` to `4.1.3`
> [0.69] Component Governance for 7/11/23

- change/@react-native-windows-cli-4c7dac7a-f8f1-4115-8416-0f071e245477.json
- packages/@react-native-windows/cli/src/codegen.ts
Before this pull request, `@rnw/cli` calls `@rnw/codegen` and write all generated C++ files to `codegen` folder. But in devmain we have a default list of writable folders names which doesn't include `codegen`. And I believe allowing users to choose a name is necessary, even if we could workaround the issue in devmain.
In `package.json`
```json
"codegenConfig": {
"name": "SampleApp",
"type": "modules",
"jsSrcsDir": "src",
"windows": {
"namespace": "SampleLibraryCodegen",
"outputDirectory": "dist" // new configuration
}
},
```
Manual tested
> @rnw/cli add package.json:codegenConfig.windows.outputDirectory

- change/react-native-windows-ea809b99-bf6d-4902-9c4f-5b35c6a7996f.json
- vnext/Shared/Modules/FileReaderModule.cpp
Fixes FileReader turbo module's argument handling.
Invoking `FileReaderTurboModule::ReadAs*` will trigger an invalid pointer error and crash the host process.
Interprets the `data` `JSValue` argument as `JSValueObject`.
Manual testing in a custom React Native Gallery instance.
> Use correct data types in FileReaderTurboModule::ReadAs*

- change/react-native-windows-ed4b1594-95cb-4689-a8de-053a7e2e31dc.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
Add Control Type information to UIA tree to improve accessibility information. 
- Added update for control type information upon fast refresh. 
- Added ability to specify for Text and Edit control types.
- Added DefaultControlType property to all core components to give components a default role. Previously all controls defaulted to Group control type. Now controls default to the following types:
| Component | Control Type |
| -- | -- | 
| View/View-based Controls (Pressable, Touchable*) | Group |
| Button | Button |
| Text | Text |
| Image | Image | 
| Switch | Button | 
| ScrollView | ScrollBar |
| TextInput | Edit | 
| ActivityIndicator | ProgressView | 
Tested all controls and confirmed correct types appear in …
> [WIP] Add Control Type Information to UIA Tree

- package.json
- yarn.lock
This PR updates:
* `tough-cookie` to `4.1.3`
> [0.70] Component Governance for 7/11/23

- change/react-native-windows-94dfd5a6-f3d9-472b-b3f9-a1d25de3296b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Add colored emojis to TextInput and Text in Fabric
Resolves #11764
Added flags to both textinput and text
> [Fabric] Add colored emojis to TextInput and Text

- change/react-native-windows-1c549950-1146-4bb2-b48f-ed2c578f8237.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/HttpModule.cpp
- vnext/Shared/Modules/HttpModule.h
- vnext/Shared/Networking/DefaultBlobResource.cpp
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/OInstance.cpp
Under certain conditions (i.e. setting `UseWebDebugger` to `false`, Blob method `addNetworkingHandler` would be call prematurely.
Resolves #11439
If the Blob module HTTP resource dependency is not initialized when `addNetworkingHandler` is called, expose the underlying Blob resource using the property bag and re-invoke that Blob method once the HTTP resource is ready.
Applied changes to sample MSRN apps (i.e. `react-native-gallery`).
> Attempt AddNetworkingHandler if HTTP module was not ready

- change/react-native-windows-a293bfbd-cd92-48c4-8758-bcff78656d4a.json
- vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
CppWinRT >= 2.0.230524.3 no longer expose the `WINRT_IMPL_LoadLibraryW` method for loading libraries, instead preferring a new `WINRT_IMPL_LoadLibraryExW`. See https://github.com/microsoft/cppwinrt/pull/1293.
This PR fixes our usage of `WINRT_IMPL_LoadLibraryW` by detecting newer versions of CppWinRT and using the new API when available.
Customers who tried to specify newer versions of CppWinRT hit build errors due to the use of the deprecated API.
Closes #11795
Created a macro to re-define the old API which calls the new API with the same behavior, as seen in the PR which deprecated the API in the first place.
N/A
Verified able to build against the latest [Microsoft.Windows.CppWinRT …
> Enable using newer CppWinRT versions that use WINRT_IMPL_LoadLibraryExW

- .ado/jobs/e2e-test.yml
- packages/e2e-test-app/test/__snapshots__/ViewComponentTest.test.ts.snap
Added work around from #10982 into the e2e-test pipeline to get updated snapshots
Before this change, you could not update the snapshots via the pipeline, this allows the pipeline to publish new snapshots
Clear the jest cache before trying to update the snapshots
**Before**
**After**
Tested via pipline
No
> Fix updating snapshot tests on pipeline

- .ado/jobs/e2e-test.yml
- packages/e2e-test-app-fabric/package.json
- yarn.lock
Add Jest Snapshot tests on Fabric to CI. Tests will now run, and the snapshots will be published as an artifact to improve debuggability. CI behavior should match what occurs for E2E testing on Paper. 
Updated e2etest:updateSnapshots script to perform correct command for updating snapshots. Upgraded version of @rnx-kit/cli to resolve bug in package where additional command arguments were not being properly ported to Jest. 
> Add Fabric Snapshot Tests to CI

- change/react-native-windows-8d9e88e3-ce8b-46b7-a11e-af04d9f3d59d.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Shared/OInstance.cpp
- vnext/overrides.json
- vnext/src/IntegrationTests/FetchTest.js
Allows disabling the Blob module in Desktop apps.
Host apps that override the RNW-provided HTTP module will encounter issues if they don't provide Blob support, due to the inter-dependency between both modules.
Introduces runtime option `Blob.DisableModule`.
Added `RNTesterIntegrationTests::Fetch`.
> Allow disabling Blob Cxx module

- change/react-native-windows-8d9e88e3-ce8b-46b7-a11e-af04d9f3d59d.json
- change/react-native-windows-ee3c2acb-502a-473c-9908-7cb9d170678f.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Shared/OInstance.cpp
- vnext/overrides.json
- vnext/src/IntegrationTests/FetchTest.js
> [0.71] Allow disabling Blob Cxx module

- change/react-native-windows-7ea54908-7e23-47a6-ab07-01bb80c23987.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/src/Libraries/NativeComponent/BaseViewConfig.windows.js
Use new upstream TopClick type instead of the Windows-specific TopClick type we originally implemented. This change results in Windows matching the Win32/iOS/Android behavior. Code now registers onClick as a bubbling event.
> Use Upstream TopClick Type Instead of Windows-Specific Type

- change/@react-native-windows-cli-89b5d265-8b1d-40b6-9cda-1449d039d1b2.json
- change/@react-native-windows-telemetry-39db57fb-a779-4bd5-93bd-edfa4aed719b.json
- change/react-native-windows-init-632430bc-c96b-4bf3-b20e-26f62b73e43f.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
- packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts
- packages/@react-native-windows/telemetry/src/index.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts
- packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
- packages/react-native-windows-init/src/Cli.ts
Node's `process.arch` and `os.arch()` methods both return the architecture that the node binaries were built for, not the architecture of the machine they're running.
This can cause issues with the various hardware virtualization layers, specifically when running 32-bit Node on 64-bit machines.
Closes: #11977
We keep hitting issues when users run the 32-bit Node on 64-bit Windows configuration.
Closes: #11977
This PR:
* Updates and exports the `deviceArchitecture()` API in the `@react-native-windows/telemetry` library, which now correctly detects when x86 Node is being used on an x64 machine
* Adds and exports a new `nodeArchitecture()` method, which is also now recorded in telemetry
* Updates the `react-native-windows-init` and …
> Properly detect the correct machine architecture in CLI

- change/react-native-windows-a293bfbd-cd92-48c4-8758-bcff78656d4a.json
- vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
This PR backports #11953 to RNW 0.72.
CppWinRT >= 2.0.230524.3 no longer expose the `WINRT_IMPL_LoadLibraryW` method for loading libraries, instead preferring a new `WINRT_IMPL_LoadLibraryExW`. See https://github.com/microsoft/cppwinrt/pull/1293.
This PR fixes our usage of `WINRT_IMPL_LoadLibraryW` by detecting newer versions of CppWinRT and using the new API when available.
Customers who tried to specify newer versions of CppWinRT hit build errors due to the use of the deprecated API.
Closes https://github.com/microsoft/react-native-windows/issues/11795
Created a macro to re-define the old API which calls the new API with the same behavior, as seen in the PR which deprecated the API in the first place.
N/A
Verified able to build …
> [0.72] Enable using newer CppWinRT versions that use WINRT_IMPL_LoadLibraryExW

- change/@react-native-windows-cli-89b5d265-8b1d-40b6-9cda-1449d039d1b2.json
- change/@react-native-windows-telemetry-39db57fb-a779-4bd5-93bd-edfa4aed719b.json
- change/react-native-windows-init-632430bc-c96b-4bf3-b20e-26f62b73e43f.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
- packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts
- packages/@react-native-windows/telemetry/src/index.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts
- packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
- packages/react-native-windows-init/src/Cli.ts
This PR backports #11978 to RNW 0.72.
Node's `process.arch` and `os.arch()` methods both return the architecture that the node binaries were built for, not the architecture of the machine they're running.
This can cause issues with the various hardware virtualization layers, specifically when running 32-bit Node on 64-bit machines.
Closes: #11977
We keep hitting issues when users run the 32-bit Node on 64-bit Windows configuration.
Closes: #11977
This PR:
* Updates and exports the `deviceArchitecture()` API in the `@react-native-windows/telemetry` library, which now correctly detects when x86 Node is being used on an x64 machine
* Adds and exports a new `nodeArchitecture()` method, which is also now recorded in telemetry
* Updates the …
> [0.72] Properly detect the correct machine architecture in CLI

- change/@office-iss-react-native-win32-43b80e6f-96e4-479c-b4d7-46c1fb056647.json
- packages/@office-iss/react-native-win32/metro.config.js
- packages/@office-iss/react-native-win32/metroShortPathAssetDataPlugin.js
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/react-native.config.js
- packages/@office-iss/react-native-win32/saveAssetPlugin.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/assetPaths.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/resolveAssetSource.win32.js
> [0.72] Add saveAssetPlugin to fix long path assets

- .gitignore
- NuGet.Config
- change/react-native-windows-14a87dda-f285-4cd4-8a0f-b5aa9543cb9f.json
- change/react-native-windows-bfb79e47-04d8-4f4e-a72f-26b1621873d2.json
- packages/e2e-test-app/.npmrc
- packages/e2e-test-app/windows/NuGet.Config
- packages/integration-test-app/windows/NuGet.Config
- packages/sample-apps/.npmrc
- packages/sample-apps/windows/NuGet.Config
- vnext/.npmrc
- vnext/Desktop.ABITests/NuGet.Config
- vnext/Desktop.DLL/NuGet.Config
- vnext/Desktop.IntegrationTests/NuGet.Config
- vnext/Desktop.UnitTests/NuGet.Config
- vnext/Desktop/NuGet.Config
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/NuGet.Config
- vnext/ReactCommon.UnitTests/NuGet.Config
This PR backports PRs #11548 and #11855 to 0.71.
Resolves Secure Supply Chain warnings.
To meet compliance requirements.
Closes https://github.com/microsoft/react-native-windows/issues/11209
Closes https://github.com/microsoft/react-native-windows/issues/10374
* Removed invalid `nuget.config` configurations
* Removed unnecessary `.npmrc` files
* Temporarily left nuget.org feed in config (tracking: https://github.com/microsoft/react-native-windows/issues/11557)
N/A
N/A
CG is failing builds due to multiple nuget feeds in nuget.config.
Resolves #11557
> [0.71] Fix Secure Supply Chain compilance issues

- change/@react-native-windows-cli-321ad683-84dc-4ae2-bf92-5d21bde36768.json
- packages/@react-native-windows/cli/src/codegen.ts
- packages/sample-apps/package.json
The default value should be `false`.
> Fix codegenConfig.windows.separateDataTypes default value

- .ado/jobs/desktop.yml
This PR backports #11816 to 0.71.
BinSkim has been throwing warnings for Desktop ever since the upgrade to BinSkim@4. Particularly this is from scanning the Hermes and V8 dlls.
However both are sourced from their own Microsoft-owned repos and only consumed here via published NuGets. BinSkim should be running on those repos (if required) not here in RNW.
This PR updates the pipeline to only test the binaries built by this pipeline.
> [0.71] Fix BinSkim warnings for Desktop

- packages/e2e-test-app/package.json
- yarn.lock
This PR updates e2e-test-app to use `react-native-xaml@^0.0.76`.
To make sure we're on the latest RNX.
Updates e2e-test-app to use `react-native-xaml@^0.0.76`.
N/A
Verified the app started
> Update e2e-test-app to RNX v0.0.76

- change/react-native-windows-78dd7222-aaf1-4762-984e-be7cb6c503c5.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
Text components were showing in the accessibility tree but not with any value. This change has `UIA_NamePropertyId` default to the text value but can be overriden by `accessibilityLabel`. 
Text components were showing in the accessibility tree but not with any value.
Resolves #12030
Added a virtual `DefaultAccessibleName()` that enables individual Fabric components to provide a fallback if `accessibilityLabel` isn't specified. Then `ParagraphComponentView` overrides this to provide its string value.
|--------|--------|
| ![image](https://github.com/microsoft/react-native-windows/assets/26607885/4f95ce31-d0e4-40fe-aa4d-b2e1bb0f7178)| …
> Fabric Text components use their text value as the accessibility name by default

- change/react-native-windows-9fc1928b-a45e-406c-96d8-6f034b72083d.json
- vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
There are three tests in `Desktop.Integration`'s `HttpResourceIntegrationTests` which verify that requests against a server that requires a `User-Agent` will succeed with the header present and fail when it's missing.
To do this we're using a standard unauthenticated GitHub API endpoint.
However, we can also hit rate limiting on this endpoint, causing the tests to fail. This PR improves the stability of those tests by instead hitting an API with the same Header requirement, but without rate limiting.
Stop good PRs from failing due to rate limiting causing tests to fail sporadically.
Instead of hitting random GitHub API endpoints (and getting caught in unauthenticated rate limiting), instead change to calling the `/rate_limit` API, which …
> Point Desktop.IntegrationTests::HttpResourceIntegrationTests to a non-rate limited API

- change/react-native-windows-3f730a0d-eb08-4507-891a-a3662c57a804.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Note: this is the same change that was made in https://github.com/microsoft/react-native-windows/pull/12036, which was reverted here: https://github.com/microsoft/react-native-windows/pull/12057
Add accessibilityHint support and information to UIA Tree HelpText property for improved accessibility information.
Added code to update HelpText UIA field with property value passed in to the accessibilityHint prop. Previously, when the accessibilityHint prop was populated, the HelpText field in the UIA tree would remain empty.
Before: 
After:
As can be seen the HelpText property is updated within the UIA tree when setting the accessibilityHint prop
Tested that HelpText UIA field is not populated when accessibilityHint is set before …
> [Fabric] Add accessibilityHint support to UIA tree

- change/@office-iss-react-native-win32-7fd6b7f9-9ded-4985-87b5-70b02f87b6c1.json
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/Button.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewAccessibility.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewAccessibility.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/Image.win32.js
> [0.72] Add aria-required and aria-multiselectable to accessibilityState on win32

- change/@office-iss-react-native-win32-7fd6b7f9-9ded-4985-87b5-70b02f87b6c1.json
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/Pressable/Pressable.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewAccessibility.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewAccessibility.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/Image.win32.js
> [0.71] Add aria-required and aria-multiselectable to accessibilityState on win32

- change/react-native-windows-06fa53f8-8874-4937-a1cc-2fc3b025dc0a.json
- vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
- vnext/IntegrationTests/TestRunner.cpp
While trying to integrate the latest RN code (see PR #11970) the `RNTesterIntegrationTests` in `React.Windows.Desktop.IntegrationTests` kept hanging and timing out.
The root issue (TBD) was a `JSError` being thrown by Chakra when the test bundle (ex. `DummyTest`) was loaded from Metro. However the bundle was loaded asynchronously, which caused that error to be swallowed and never reported. Furthermore, not knowing that the bundle load had failed, the test continued onward and attempted to start loading the app with `AppRegistry.runApplication()` (which also failed silently) and finally proceeded to wait indefinitely for the JS component to render and fire the `TestModule.markTestPassed(true)`.
To address this, this PR changes the tests to set a reasonable 30s timeout for waiting for the …
> Prevent Desktop.IntegrationTests from hanging forever

- change/@office-iss-react-native-win32-fe0fc9d1-3124-4ae6-b15a-7c456cee835d.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/assetPaths.js
assetPaths.js is imported by saveAssetPlugin.js which is loaded by the bundler as a node JS file.  So it need to be free of flow annotations, otherwise it'll fail to run.
> [Win32] Remove flow usage from saveAssetPlugin codeflow

- change/react-native-windows-4240d9b5-be72-42a8-8e2a-c71d5a1ff72b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Fixes issue where TextInput would crash when the app is minimized.
Resolves #12040
Excludes invalidating the drawingSurface if the app is minimized. Finds out if the app is minimized by calculating if the content width is less than the borders/padding (ie there's no content).
Tested with playground
no
> [Fabric] Fix textinput crashing when app is minimized

- change/react-native-windows-3adee0f5-93e2-4451-bc8a-967121f90520.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
We are seeing crashes on quit when the blur command is called roughly around the same time that the React instance is being shut down. It's likely because the result of tryGetXamlRoot is null.
This change falls back on the GetFocusedElement() overload without any parameters if the XamlRoot is null, as supplying a null parameter will result in a NPE.
It's a tricky race condition to repro, but I did validate that passing a null XamlRoot value to `FocusManager::GetFocusedElement(XamlRoot)` will throw an exception.
Fix for NPE when blur command is received while React instance is shutting down.
> Fix bug when blur command received on node without XamlRoot

- change/react-native-windows-335edf82-6b7e-4ed7-abbe-f639eb36e524.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.h
- yarn.lock
By using `runtimeclass` in `CompositionSwitch` we prevent apps from being able to provide their own implementation of the `CompositionSwitcher`, which defeats its purpose.
> [Fabric] Remove runtime classes in CompositionSwitcher

- change/react-native-windows-ec2cdeb2-afb4-4f37-9956-6004de7e1a72.json
- change/react-native-windows-ecffcdea-9308-4776-838d-e7e504c267da.json
- vnext/Microsoft.ReactNative/CoreApp.cpp
- vnext/Test/HttpServer.cpp
- vnext/Test/HttpServer.h
> [0.72] Test HttpServer build fix

- change/react-native-windows-630e2ba2-a26a-4722-b93c-bfb489443e93.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.Cxx/ReactHandleHelper.h
- vnext/Microsoft.ReactNative.Cxx/ReactNonAbiValue.h
- vnext/Microsoft.ReactNative.Cxx/ReactNotificationService.h
- vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactNotificationService.cpp
- vnext/Microsoft.ReactNative/ReactApplication.cpp
- vnext/Microsoft.ReactNative/ReactApplication.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
- vnext/Microsoft.ReactNative/ReactInstanceSettings.h
- vnext/Microsoft.ReactNative/ReactNativeHost.h
- vnext/Microsoft.ReactNative/ReactRootView.cpp
- vnext/Microsoft.ReactNative/ReactRootView.h
- vnext/Microsoft.ReactNative/ReactSupport.h
- vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.h
- vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.cpp
- vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.h
- vnext/Microsoft.ReactNative/XamlHelper.cpp
- vnext/Microsoft.ReactNative/XamlHelper.h
When linking in WinAppSDK, there is a namespace conflict with winrt::Microsoft::Windows and winrt::Windows, which causes various build errors.
This makes our code more explicitly use winrt::Windows where appropriate.
Also modified the fabric color.cpp to always use winrt::Windows::UI, not winrt::Microsoft::UI even when USE_WINUI3 is set, since the ViewManagement functionality does not exist in Microsoft::UI.
> Be more explicit when using winrt::Windows types, to avoid conflicts with WinAppSDK

- change/react-native-windows-aab669fd-e811-4fa5-82fe-d73ba879b7a5.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Finish implementing backfaceVisibility and transform for other components in Fabric (Text, Image, TextInput, ScrollView, ActivityIndicator, Switch)
Resolves #11753
Extracted logic from View Component to Base Component.
Without backfaceVisibility='hidden'
With backfaceVisibility='hidden'
tested locally
no
> [Fabric] Enable backfaceVisibility and transform prop for all Fabric Components

- change/@office-iss-react-native-win32-e8c0b2fd-503a-492b-a0e8-9bea3e698b51.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/resolveAssetSource.win32.js
The asset path handling is trimming an extra character off the path of assets assuming that its a '/'.  In metro this is always true, but for other bundlers it may not be.  This aligns the logic with the other code paths.
> [Win32] Webpack assets do not prefix paths with /, which causes a lost char in asset path

- change/@office-iss-react-native-win32-e8c0b2fd-503a-492b-a0e8-9bea3e698b51.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/resolveAssetSource.win32.js
> [0.72] [Win32] Webpack assets do not prefix paths with /, which causes a lost char in asset path

- change/@office-iss-react-native-win32-e8c0b2fd-503a-492b-a0e8-9bea3e698b51.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/resolveAssetSource.win32.js
Port https://github.com/microsoft/react-native-windows/pull/12119 to 0.72
> [0.71] [Win32] Webpack assets do not prefix paths with /, which causes a lost char in asset path

- change/react-native-windows-1a194256-b950-463f-acfa-3fc056fb0276.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
ViewManagers have access to the ReactContext, which enabled a bunch of functionality and data passing scenarios.
Fabric view components should also have access to the ReactContext.
> [Fabric] Custom native components should have access to the ReactContext

- change/react-native-windows-59c4c93d-b696-4ed2-ad29-ce2c7aa0c3ca.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Adds support for cursorColor
component parity
added Color to CompCaretVisual (this should also help when implementing selectionColor)
https://github.com/microsoft/react-native-windows/assets/42554868/ff2bbbbe-b1e4-4e62-9d00-6a654f1a9bbb
tested locally
no
> [Fabric] Add Textinput's cursorColor

- change/@react-native-windows-codegen-8ccd3fe9-4d54-4b37-9276-ba4fbfa7ecd9.json
- packages/@react-native-windows/codegen/src/index.ts
Saw these when trying to run a script which does `yarn build` in RNW fork on Linux server. May be more issues here (didn't test after making this fix). I know RNW yarn build is tested continuously on macOS (which is not case sensitive), so build should otherwise be relatively POSIX-y clean.
> Fix some incorrectly cased requires

- change/react-native-windows-5e8ea709-c53b-4959-9915-6bae7aeecb09.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/CompositionContext.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHelpers.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Currently fabric runs against System Composition.  With this change when USE_WINUI3 is enabled, fabric can also target lifted Composition.
> [Fabric] Enable fabric usage against lifted comp, or system comp

- change/react-native-windows-bc016154-a9c1-4dcd-8367-781644093aaa.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Makes TextInput's caret lose visibility when focus is lost.
Resolves #12125
Set visibility to false when focus is lost
https://github.com/microsoft/react-native-windows/assets/42554868/e8734a4c-f131-4977-b0f7-261bed706a7d
tested locally
no
> [Fabric] Fix Textinput's caret on focus lost

- .ado/jobs/cli-init.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- change/@react-native-windows-cli-e83c269b-fa39-4421-be79-1ea0195ca4ec.json
- change/react-native-windows-7cd4367c-e7a0-4840-aa19-893c27796f6f.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- vnext/templates/cpp-app/template.config.js
Adds the usage of our new `init-windows` command, with the new fabric-based `cpp-app` template, to our CI, so we don't break it as we make changes.
We're still making (breaking) changes to the Composition surface area, so we want to make sure that changes made to the in-repo fabric apps also get reflected in the new app template.
Modifies our existing CLI test workflows to optionally use the new command instead. Also makes some changes to how the init code reads files recursively, which wasn't working in CI.
N/A
Verified the workflows ran.
> [Fabric] Add `react-native initWindows --template cpp-app` to CI

- change/react-native-windows-bae3e528-c28a-4a7a-a119-2b91ceb4ec86.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
Set the UIA Name property on a TextInput component to match the value of the `placeholder` property on the TextInput.
Following the guidelines in the [Edit](https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-supporteditcontroltype) control type documentation, which is the control type for TextInput, the Name property should be set by a static text label, or by the application developer (which is when `accessibilityLabel` is set). In the event that there is no accessibilityLabel property set, the name value defaults to the placeholder text. If there is no accessibilityLabel or placeholder property set, then the UIA Name property will be left unpopulated.
The documentation also says that when a placeholder prop is set, the …
> Set UIA Name and HelpText properties on TextInput to match placeholder prop value

- packages/@react-native-windows/tester/src/js/examples/View/ViewExample.windows.js
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/e2e-test-app/test/__snapshots__/ViewComponentTest.test.ts.snap
Removed accessibilityRole prop from View example which was causing an exception
Allow Accessibility Insights to work on the View example page.
Removed invalid accessibilityRole prop on the View example page. Previously `accessibilityRole` was set to 'View' which is not a valid role type, and was causing an error in the Fabric code when trying to evaluate the control type.
Ran Accessibility Insights for Windows on the View example page.
No
> Fixed incorrect accessibilityRole value breaking Accessibility Insights in RNTester View example page

- change/react-native-windows-58b41525-866f-4ad8-963c-cfa92497c7ac.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
ScrollView does not respond to keyboard commands (page up, page down, home, end, or arrow keys).
Also fixes an issue where the scrollTo command would not scale the target location for scale factor, and ensures that scrollwheel handling chains through multiple scrollviews correctly.
Resolves #12076 and #12074
> [Fabric] Add keyboard handlers to ScrollView

- change/react-native-windows-521af409-3887-4e28-a380-e8689c109448.json
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
This change is only for RNW for desktop. It does not affect RNW for UWP.
In Office we have issues with the new V8 Node-API for some RN instances.
In this PR we add ability to switch between V8 JSI and the V8 Node-API.
It must simplify adoption of the new API.
The V8 API type is controlled by the new `JSIEngineV8NodeApi` property.
When it is true, we use the V8 Node-API, otherwise by default we use the non-ABI safe V8 JSI.
The code is tested in Office, and it works as expected.
> [0.71] Switch between V8 JSI and V8 Node-API

- change/react-native-windows-a292054c-e016-4f31-bb25-3808d092176b.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
- Conditionally register WebSocket Cxx module
- Change files
Allow using the Cxx WebSocket module instead of its TurboModule variant.
Using the WebSocket TurboModule could lead to a memory leak on application shutdown.
This issue is currently under investigation.
- Define enum entry `facebook::react::DevSettings::useWebSocketTurboModule`.
- Conditionally register WebSocket Cxx module based on React context's `UseWebSocketTurboModule` property.
> Conditionally register WebSocket Cxx module

- .ado/jobs/playground.yml
It looks the the method used for detecting VS used in this job no longer works consistently (maybe a Windows or VS update)? Replacing with the more reliable `vswhere.exe`
To improve the debug test job reliability.
Replace `Get-CimInstance MSFT_VSInstance` with `vswhere.exe`.
N/A
N/A
> [0.72] Fix Playground Debug Test Pipeline

- change/react-native-windows-0d984d7b-b9bc-4673-859b-ba694d9ba669.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
Adding PointerEntered and PointerExited events for fabric.
> [Fabric] Add native PointerEntered+PointerExited events

- change/react-native-windows-62e7496f-cd8d-49bb-8775-c127c760d022.json
- packages/playground/Samples/nativeFabricComponent.tsx
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHelpers.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
- The AutomationProvider was not providing an appropriate bounding rect when hosted in an island, causing the coordinates provided to UIA to be incorrect.
- Fixed issue where pointer/key events for custom components were unusable.
- Fixed issue where Microsoft/WindowsCompositionContext would return an invalid pointer for InnerCompositor.
- Fixed issue where CompositionEventHandler would not unregister from island events when destroyed.
- Minor cleanup of playground code from feedback on previous PR.
- Extended playground custom component to use pointer events
> [Fabric] Fix offset for automation provider when running in islands

- change/react-native-windows-06a66b00-cc43-451b-9087-1b0c52b44ab4.json
- vnext/.flowconfig
- vnext/Microsoft.ReactNative/Utils/ImageUtils.h
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
- vnext/Shared/OInstance.cpp
- vnext/overrides.json
- vnext/src/Libraries/Image/resolveAssetSource.windows.js
`Image.resolveAssetSource` has two different code paths - one for resolving assets from the packager server when running in standard debug builds and one for resolving assets when the JS package is pre-bundled.
Previously, we were not providing the bundle root path to the `SourceCodeModule` for pre-bundled apps, and it was up to each individual native module and view manager that depends on resolving asset paths with `Image.resolveAssetSource` to replace `file://` with the bundle root path pulled from the InstanceSettingsSnapshot.
Even after fixing the issue with `SourceCodeModule`, there is still one more …
> Fixes issues with packaged asset resolution

- .ado/jobs/playground.yml
- change/@office-iss-react-native-win32-b7b34581-dc70-4c9f-ad39-0795f687aff8.json
- change/react-native-windows-5b11cf36-5886-40ca-9aa8-5ae262e7fdf3.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
This PR updates RNW 0.72 to use RN 0.72.6.
Keep up with latest RN.
Upgrade react-native dependency to 0.72.6
N/A
N/A
> Integrate RN 0.72.6

- change/react-native-windows-646abbfc-a05b-44db-a498-bf96a28aa1c7.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
Changes Switch's thumb to use composition animations and adds animation for path
First part of #12188, still need to animate thumb increasing in size on hover
Add thumb visual to CompositionContextHelper
Before (switch's are styled differently so color is different!)
https://github.com/microsoft/react-native-windows/assets/42554868/b41bd96c-98c2-4a99-b0f1-7f4cea0f600c
After
https://github.com/microsoft/react-native-windows/assets/42554868/fce699ae-929b-48f6-bf5a-d076260711eb
tested locally on both devbox and laptop to check sizing!
no
> [Fabric] Change Switch thumb to use composition animations

- change/react-native-windows-eb48950f-48ba-4e28-b8a9-93a2ce7e2282.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
We now use the winrt/Windows.Storage.h header in the initialization of Hermes (not just V8), so this header needs to be imported unconditionally.
Fixes compilation of Microsoft.ReactNative without USE_V8 compile constant
>  Move winrt/Windows.Storage.h include out of USE_V8 conditional

- .ado/jobs/e2e-test.yml
- packages/e2e-test-app-fabric/jest.config.js
This PR fixes the E2E Test App Fabric jobs in CI:
* Stop testing Fabric with Chakra (it's unsupported)
* Enable testing the x86 build in CI
The Fabric E2E tests were passing in PR but failing in CI.
Resolves #12251
Add a filter to the pipeline job matrix to stop testing Fabric with Chakra (it's unsupported)
Modify the jest config to allow for a environment variable to specify builds other than x64/Release
N/A
Verified the new config works.
> Fix Fabric E2E test

- change/react-native-windows-19511fcc-25bf-46e4-815a-99c1bcca18f0.json
- change/react-native-windows-a292054c-e016-4f31-bb25-3808d092176b.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
> [0.72] Conditionally register WebSocket Cxx module

- .ado/jobs/e2e-test.yml
- change/@react-native-windows-automation-0463e716-dca8-42f8-af1d-e1aff0fac0e9.json
- packages/@react-native-windows/automation/src/AutomationEnvironment.ts
- packages/e2e-test-app-fabric/jest.config.js
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.vcxproj
This PR backports PR #12253 and a small supporting part of #12254.
This PR fixes the E2E Test App Fabric jobs in CI:
* Stop testing Fabric with Chakra (it's unsupported)
* Enable testing the x86 build in CI
The Fabric E2E tests were passing in PR but failing in CI.
Resolves #12251
Add a filter to the pipeline job matrix to stop testing Fabric with Chakra (it's unsupported)
Modify the jest config to allow for a environment variable to specify builds other than x64/Release
N/A
Verified the new config works.
> [0.73] Fix Fabric E2E test

- change/@office-iss-react-native-win32-c8f05d48-2e06-40a5-a678-84a890bf527f.json
- change/@rnw-scripts-eslint-config-07a27c62-5b09-4435-ba2f-b47a2811a718.json
- change/react-native-windows-a4303d58-1520-4375-b661-e3df9c0dfd9f.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
- packages/@rnw-scripts/eslint-config/eslintrc.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
- vnext/src/Libraries/Components/TextInput/TextInput.windows.js
- vnext/src/Libraries/Components/View/View.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
It's generally good practice to use `===` when comparing values in JavaScript (other than null checks), so this change adds that to the eslint config.
This change also cleans up a miscellaneous unused variable in Pressable.windows.js.
Wait for GitHub lint checks.
> Adds `eqeqeq` to eslint configuration and a few other lint fixes

- change/react-native-windows-8295ceba-97f3-4570-afc5-ffa8b10c51d1.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp
Previous logic was only handling fetching images from web locations (or the bundler)
> [Fabric] Add support for loading image files from local files

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/cli-init.yml
- .ado/stages.yml
- .ado/templates/react-native-debug-info.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/verdaccio-start.yml
- .ado/templates/verdaccio-stop.yml
Backport PR #12213 into 0.73
PR #12183 show-horned a new variable and branching path in our existing `cli-init.yml` CI job to support the new `react-native init-windows` command.
However, this makes the pipeline hard to parse and maintain. This PR factors out the new new project path into a separate set of jobs, so we can leave the "old" pipeline as-is, run both for now, but have and easier time updating the new one (and eventually just delete the old one when it's no longer necessary).
To make the new new project CI easier to maintain and drift from the old new project CI.
Created a new `cli-init-windows.yml` job, which calls a new "template-focused" `react-native-init-windows.yml` template, and also factored out code common to …
> [0.73] Refactor `init-windows` CI jobs

- change/react-native-windows-5d9952b2-0b6d-4246-a1ec-994f54168545.json
- vnext/Shared/Modules/BlobCollector.cpp
- vnext/Shared/Modules/BlobCollector.h
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Allows disposing of unused Blob data when JS garbage collection takes place.
Continuous instantiation of `Blob` JavaScript objects can lead to memory leaks because the disposal of those objects does not trigger the deallocation of the blob data on the native side (see `IBlobPersistor`).
- See https://github.com/facebook/react-native/pull/24745
- See https://github.com/jurocha-ms/Repro/tree/blobmemleak/ReactNative/fetchwinleak
For further context:
- https://github.com/facebook/react-native/pull/24405
- https://github.com/facebook/react-native/pull/24767
- https://github.com/facebook/react-native/issues/39441
- https://github.com/facebook/react-native/issues/23801
- https://github.com/facebook/react-native/issues/24654
- Define …
> Implement BlobCollector

- change/react-native-windows-c4c4d87a-92df-4bee-b696-1445c7e5d6c7.json
- vnext/template/metro.config.js
- vnext/template/metro.devMode.config.js
- vnext/templates/cpp-app/metro.config.js
This PR applies the changes we need to an app's metro config on top of a more recent snap of the default metro config for an RN app.
- 
To fix new apps not loading because of a badly configured bundle.
Resolves: #12268
Coped the current RN template metro.config.js and applied our changes.
N/A
Verified a new app loads correctly
Update app template's metro config with latest upstream changes
> Update app template's metro config with latest upstream changes

- change/@office-iss-react-native-win32-c40abe5d-af56-493a-ae49-34214d035a10.json
- change/react-native-windows-e9beb7b0-e993-4305-9ea8-d1a5292b9149.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/tester/package.json
- vnext/package.json
This PR fixes the peer-dependency versions for RN to require 0.72.6 (which was missed in the last integrate).
Make sure folks don't have a bad combination of versions.
Updated package.json files.
N/A
N/A
> [0.72] Fix peer dependencies for react-native

- change/react-native-windows-8d563e33-0333-4262-8dab-f291bbfb06c4.json
- vnext/PropertySheets/WinUI.props
You can't mix WinUI 2 and WinUI 3 in the same process, so just to be safe, RNW implements a guard (see PR #5290) which will cause an explicit crash if you try, in case an end developer does so unintentionally.
This PR adds an msbuild prop `DisableXamlGuard` which, when set to true, will remove this guard in the RNW code.
Some customers want to experiment with mixing WinUI 2 and WinUI 3 in the same process, so exposing this property unblocks their experiments.
Related: #10131
Added a new `DisableXamlGuard` prop to `WinUI.props` and, if it's set to true, define the `DISABLE_XAML_GUARD` constant which will ifndef out the guard in the code.
N/A.
Verified I could still build and run an app with the guard missing.
Should this change …
> Expose DisableXamlGuard property to allow mixing of WinUI 2/3

- change/@rnw-scripts-create-github-releases-4e22ce8d-fcb7-4bbc-93a0-3ac00645ae61.json
- packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
This PR fixes an issue with the create-github-releases script that we need to get 0.73 to publish correctly.
Unblock 0.73 publish
Don't publish GH releases if the semver prerelease tag is anything but the word preview.
N/A
N/A
> Fix @rnw-scripts/create-github-releases

- .ado/jobs/e2e-test.yml
This PR disables the E2EFabric tests from running in CI/PR. The app will still build.
The tests are flaky and blocking 0.73 stuff.
Commented out the e2e test command after the build.
N/A
N/A
> [0.73] Disable E2EFabric tests

- change/react-native-windows-4a09e136-8bbd-4b99-95ab-fdaed43e9292.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
- vnext/Microsoft.ReactNative/Views/PopupViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
We are seeing some issues with pointer event handling in Flyouts in XAML Islands apps. It appears that part of the issue has to do with the coordinate spaces not exactly lining up. It is too difficult to reason about the coordinate spaces when there are minor differences in measurement behavior. The coordinate spaces for TouchEventHandler and UIManager.measure need to line up exactly for Pressable to work as expected (as Pressable calls UIManager.measure to ensure the pointer is still in the hit box after a pointerMove event occurs).
TouchEventHandler transforms the RoutedPointerEventArgs pointer position to …
> Simplify Flyout and Popup coordinate spaces

- .ado/publish.yml
This PR adds `npx beachball check` to the Publish pipeline to prevent attempting to publish with invalid changefiles present.
We accidentally published `react-native-windows@0.73.0` instead of `react-native-windows@0.73.0-preview.3` because a bad change file was present and beachball will still try to do what you asked for even if it's not expected.
Added a `npx beachball check` to the publish pipeline and explicitly fail if a bad change-file is detected.
N/A
Verified that this would have detected the bad change file and prevented the bad publish.
> Add Beachball Check to publish.yml

- .ado/publish.yml
- change/@react-native-windows-automation-0463e716-dca8-42f8-af1d-e1aff0fac0e9.json
This PR backports #12293 to 0.73.
This PR adds `npx beachball check` to the Publish pipeline to prevent attempting to publish with invalid changefiles present.
We accidentally published `react-native-windows@0.73.0` instead of `react-native-windows@0.73.0-preview.3` because a bad change file was present and beachball will still try to do what you asked for even if it's not expected.
Added a `npx beachball check` to the publish pipeline and explicitly fail if a bad change-file is detected.
N/A
Verified that this would have detected the bad change file and prevented the bad publish.
> [0.73] Add Beachball Check to publish.yml

- .ado/publish.yml
- .ado/templates/msbuild-sln.yml
- .ado/templates/publish-build-artifacts.yml
- .ado/templates/upload-build-logs.yml
This PR migrates our publish.yml on top of the required 1ES Pipeline Template, including some minor refactors to some template files to prevent them from conflicting with how the 1ES templates work.
Compliance push.
Refactors the pipeline to be passed to the template, and added parameters to our templates that publish build artifacts to allow the publish to op-out, and let the 1ES template do that publish.
Verified that the pipeline runs successfully.
Converted publish.yml ADO pipeline to extend the v1/1ES.Official.PipelineTemplate.yml template
> Convert publish.yml to extend 1ES PT

- change/react-native-windows-740eb7f7-da15-4ae8-9c1e-9cff8011ca94.json
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewEventEmitter.cpp
When copying code from our fork of react-native-windows, this generated code signature leaked by mistake. This change removes it.
> Remove generated signature from file

- .ado/publish.yml
CodeQL triples build times when it runs and therefore recommends you triple your timeout. Moving to the 1ES PT where we're forced to run CodeQL (and control how often it decides to do so), we need to increase our job timeouts.
First time running a real main publish with the 1ES template got canceled due to a timeout.
Added timeouts.
N/A
We did this for the (no longer needed?) compliance pipeline.
> Increase publish build timeout to handle CodeQL overhead

- .ado/jobs/linting.yml
> Increase timeout to account for 1ES pipeline anti-malware scan sometimes taking a while

- change/react-native-windows-c060b99f-d2ee-460d-9ba1-c681a5405039.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
Changes the switch's thumb to increase in size onPointerHover
Resolves #12188
https://github.com/microsoft/react-native-windows/assets/42554868/e30490ac-de4c-41c3-be3b-bf3537ab59ae
Paper
https://github.com/microsoft/react-native-windows/assets/42554868/08cbd371-e1dc-47f3-ab41-47e2347b431b
Fabric
https://github.com/microsoft/react-native-windows/assets/42554868/cb95964b-ce84-4d6f-901f-167713c1fd5d
tested locally
no
> [Fabric] Add animation on Switch's thumb onHover

- change/react-native-windows-74a46a91-683f-450c-a550-5b42f7213e0c.json
- vnext/Directory.Build.props
- vnext/Folly/TEMP_UntilFollyUpdate/ConstexprMath.h
- vnext/Folly/TEMP_UntilFollyUpdate/concurrency/CacheLocality.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
- vnext/Folly/TEMP_UntilFollyUpdate/hash/Hash.h
- vnext/Folly/TEMP_UntilFollyUpdate/lang/SafeAssert.h
- vnext/Folly/cgmanifest.json
This bumps Folly to 2023.10.16.00, which picks up fixes made to C++ 20 on MSVC.
This also cherry-picks https://github.com/facebook/folly/commit/e65afc941aa4e4985ac63350755d705e40bbaa32 which fixes some strict MSVC warnings seen in a new code, and one of the existing patches.
We can remove `ConstexprMath.h`, `CacheLocality.cpp`, and the existing patch for `Hash.h` upon intake of `2023.11.06` when that is pushed.
Folly is still being removed opportunistically from RN. We no longer use folly containers build folly futures on Android/iOS.
> C++ 20: Bump Folly from 2023.03.06 to 2023.10.16.00

- change/react-native-windows-39577653-1e51-4a5f-899b-b34e2da6d70f.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Fixes "[Explicit template specialization cannot have a storage class](https://stackoverflow.com/questions/29041775/explicit-template-specialization-cannot-have-a-storage-class-member-method-spe)" in C++ 20 by moving a function outside of a struct.
> C++ 20: Fix `Explicit template specialization cannot have a storage class`

- change/react-native-windows-a9c0f898-04a7-44ef-9a6d-cab3625ade84.json
- vnext/Mso/src/debugAssertApi/debugAssertApi.cpp
This API was deprecated in C++ 17, and removed from C++ 20. Replace it with placement new.
> C++ 20: Replace Usage of `std::allocator::construct()`

- change/react-native-windows-c64047dc-de68-4470-93bb-27e900f3696c.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Folly/Folly.vcxproj
- vnext/FollyWin32/FollyWin32.vcxproj
- vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/PropertySheets/ReactCommunity.cpp.props
- vnext/ReactCommon/ReactCommon.vcxproj
This sets a couple new preprocessor conditions:
1. `FOLLY_CFG_NO_COROUTINES` to prevent types like `folly::optional` from bringing in Folly's coroutine stack when Folly detects C++ 20 coroutines as available.
2. `_SILENCE_CXX20_U8PATH_DEPRECATION_WARNING`: Because the deprecation came before a suitable replacement API. This is more scoped than the `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS` used by `React.Cpp.props`.
> C++ 20: Preprocessor definitions

- change/@react-native-windows-automation-channel-b40845ff-ac08-4250-bba7-6f0d4378f435.json
- change/react-native-windows-d93b5adf-a8b2-4ceb-89f1-aeedd9546d76.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/CppWinrtLessExceptions.h
- packages/integration-test-app/windows/integrationtest/TestHostHarness.h
- packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
These projects make use of ts-specific `std::experimental` coroutine APIs. Bump to C++ 20, and C++ 20 standard coroutines. These both have WinRT binary boundaries, so this should have no interaction with other projects (and should have no impact to MSRN interop.
> C++ 20: Switch AutomationChannel and IntegrationTest to /std:C++20

- change/react-native-windows-e86ad249-f400-44cf-b45f-f726ae7113cc.json
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
`ReactContext` is supposed to be a weak reference to the inner react instance.  But it is currently also holding a reference onto the `ReactPropertyBag`, which means that `ReactContext` is keeping alive a lot more than it should be.
> [0.72] ReactContext should have a weak ref on the PropertyBag

- change/react-native-windows-676c6305-2f32-4911-ae83-3b168ddb3759.json
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
`ReactContext` is supposed to be a weak reference to the inner react instance.  But it is currently also holding a reference onto the `ReactPropertyBag`, which means that `ReactContext` is keeping alive a lot more than it should be.
> ReactContext should have a weak ref on the PropertyBag

- change/react-native-windows-3ff759df-eda0-48ed-8bc0-518bd22e9ae2.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
In some cases, it is possible for the `ReactPropertyBag` to have already been destroyed by the time the App gets the `InstanceDestroyed` event.  This can make cleanup code fail.
Hold a ref to the PropertyBag while firing the InstanceDestroyed event.
> Keep propertyBag alive for duration of InstanceDestroyed event

- change/react-native-windows-1fca69d4-5eb2-4787-91ff-91a19b4fbad9.json
- vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp
- vnext/Microsoft.ReactNative/ReactPointerEventArgs.h
- vnext/Microsoft.ReactNative/ReactPointerEventArgs.idl
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Adds property to ReactPointerEventArgs to allow view managers to capture the pointer while still allowing RN to emit events to JS. XAML only allows capturing the pointer on PointerPressed, so this would allow, for example, a view manager that supports custom native drag behaviors that have a threshold for action (and when that threshold is not exceeded,
the gesture is handled by RN).
> Adds option to allow ViewManagers to capture pointer

- .ado/jobs/cli-init.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-b478dee5-f5a0-4257-96b1-c3cd1ce241f0.json
- change/react-native-windows-199ec877-3e4a-4205-bdf0-60a698957050.json
- packages/@react-native-windows/cli/src/commands/config/configUtils.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/e2e-test-app/windows/ExperimentalFeatures.props
- packages/integration-test-app/windows/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/TestBundle.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Common.props
- vnext/PropertySheets/JSEngine.props
- vnext/metro.config.js
- vnext/templates/cpp-app/windows/ExperimentalFeatures.props
- vnext/templates/old/generateWrapper.js
- vnext/templates/old/uwp-cpp-lib/template.config.js
This PR backports #12321 to 0.73.
This PR makes Hermes the default JS engine for RNW going forward.
For now, this is still managed by setting the `<UseHermes>` MSBuild property. However, if the property is not explicitly set, the default value in `JSEngine.props` will now be `true` instead of `false`.
The property will remain exposed (and now set to `true`) in project's `ExperimentalFeatures.props` files. This will be done for new projects created with the `npx react-native-windows-init` command targeting versions with this change. (Use or omission of the `--useHermes` flag will no longer be recognized at project creation time). Hermes will also be the default for projects created with the new `npx react-native init-windows` CLI command.
Current users attempting to *upgrade* their …
> [0.73] Make Hermes the default JS engine

- change/react-native-windows-07408f27-e6f7-4cda-8f8b-935be0bd6bfe.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
On iOS, various JS-only events are registered on the native ViewManager for View solely for the purpose of allowing these events to flow to ViewProps and be used when considering view flattening: https://github.com/facebook/react-native/blob/b561d46b06a32e3872c4701ebeb325f8231e88dd/packages/react-native/React/Views/RCTViewManager.m#L523-L555
This change adds these event props to ViewViewManager for the same purpose.
Run `Playground-composition.sln`
Use the following example:
```
import React from 'react';
import {AppRegistry, View} from 'react-native';
function Example() {
return (
<View
onTouchStart={() => alert('clicked')}
style={{width: 100, height: 100}}>
<View pointerEvents='none' …
```
> Fix native view config to include Fabric events

- change/react-native-windows-9e40953e-4273-4189-bb0b-62d557460317.json
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
`ReactContext` is supposed to be a weak reference to the inner react instance.  But it is currently also holding a reference onto the `ReactPropertyBag`, which means that `ReactContext` is keeping alive a lot more than it should be.
> [0.73] ReactContext should have a weak ref on the PropertyBag

- change/react-native-windows-aeaa392d-12c1-43af-8980-02dfd8e6d4f3.json
- vnext/templates/cpp-app/template.config.js
- vnext/templates/templateUtils.js
Adds the functionality for apps created with the new cpp-app template to run `yarn windows`, as an alias for `react-native run-windows`, similar to the old template.
To do this, I've created a new `templateUtils` module for shared template config code, with a new `updateProjectPackageJson()` method to make it easy for templates to inject items into a project's package.json file (in this case, a new `scripts` entry).
Adds a useful feature of the old templates to the new template
See above.
N/A
Verified creating a new project works.
The new Fabric app template now supports `yarn windows` as an alias to `react-native run-windows`
> Fabric: Add windows script to new cpp-app template

- change/react-native-windows-766f6cc5-f66b-4147-9bd6-bcf8c9897469.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/Shared.vcxitems.filters
Prevent memory leaks by untracking responses managed by a custom response handler.
HTTP responses are not releasing their allocated resources when processed by a response handler (i.e. `BlobModuleResponseHandler`).
Explicitly untrack the response's resources when processed by a response handler.
> Untrack HTTP responses when processed by IResponseHandler

- change/react-native-windows-86ce2be3-b89f-4ddb-9476-45f3d6c9cd21.json
- vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
- vnext/Microsoft.ReactNative/JSDispatcherWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Cherry pick PR #12385
While investigating memory leaks in RNW code I saw that we almost never delete objects from the JSI long lived object collection.
In this PR we release JSI long-lived objects as soon as we finish using them.
After this change, the list of long-lived objects is regularly cleaned.
> [0.72] Release long lived JSI objects ASAP

- change/react-native-windows-9db342c6-2185-414b-9bcb-90e6b7f5dcb7.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/SchedulerSettings.cpp
- vnext/Microsoft.ReactNative/SynchronousEventBeat.cpp
- vnext/Microsoft.ReactNative/SynchronousEventBeat.h
Clean code is nice.
A copyright header here, a new line there, and a simplified lambda capture. This is a grab bag of things that were missed when integrating RuntimeScheduler.
GitHub Actions has this covered.
> Minor cleanup of recent RuntimeScheduler integration

- change/react-native-windows-f607455e-1870-4fd5-81f5-94717effb241.json
- vnext/Directory.Build.props
- vnext/PropertySheets/Warnings.props
- vnext/fmt/cgmanifest.json
MSVC is deprecating stdext::checked_array_iterator which fmt was using and caused build breaks when we updated to VS 17.8. 
Resolve #12407 
Updating to fmt 10.1.0 since it removes all stdext::checked_array_iterator references. (fmtlib/fmt#3540)
Also removing current workaround of silencing the warning. 
fmt.vcxproj now builds with VS 17.8
Update fmt version from 8.0.0 to 10.1.0
> Update fmt version to 10.1.0

- change/react-native-windows-c2347d19-8010-4196-9179-d7b615481b93.json
- vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
- vnext/Microsoft.ReactNative/JSDispatcherWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Cherry pick PR #12385
While investigating memory leaks in RNW code I saw that we almost never delete objects from the JSI long lived object collection.
In this PR we release JSI long-lived objects as soon as we finish using them.
After this change, the list of long-lived objects is regularly cleaned.
> [0.73] Release long lived JSI objects ASAP

- change/@react-native-windows-automation-channel-bae850aa-ef41-4bd0-840b-314b20a2b40a.json
- change/react-native-windows-2fcbda0d-58f8-4b42-af03-b5226ab939d2.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/integration-test-app/windows/integrationtest/packages.lock.json
- packages/playground/CoreApp/packages.lock.json
- packages/playground/windows/PlaygroundNativeModules/packages.lock.json
- packages/playground/windows/playground-composition/packages.lock.json
- packages/playground/windows/playground-win32/packages.lock.json
- packages/playground/windows/playground/packages.lock.json
- packages/sample-apps/windows/SampleAppCPP/packages.lock.json
- packages/sample-apps/windows/SampleAppCS/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCPP/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/Microsoft.ReactNative.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.lock.json
Use Hermes package version 0.1.18.
This version contains memory leak fixes: https://github.com/microsoft/hermes-windows/pull/169
> Change Hermes package version to 0.1.18

- change/react-native-windows-1fccb38f-796b-4d62-8f4c-3c353b147d8f.json
- vnext/Microsoft.ReactNative/AsynchronousEventBeat.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/SynchronousEventBeat.h
Most of ReactCommon and React Native mobile imports RuntimeExecutor.h as #include <ReactCommon/RuntimeExecutor.h>. This just cleans up a few remaining callsites in react-native-windows that uses an inconsistent #include.
Please note, the AdditionalIncludeDirectory is already configured in React.Cpp.props.
As long as builds pass, we're good.
> Include RuntimeExecutor.h consistently

- change/react-native-windows-f6ce9779-80b8-4939-b78b-f28dfa7b0e8c.json
- vnext/Directory.Build.props
- vnext/fmt/cgmanifest.json
MSVC is deprecating stdext::checked_array_iterator which fmt was using and caused build breaks when we updated to VS 17.8.
Updating to fmt 10.1.0 since it removes all stdext::checked_array_iterator references. 
Update fmt version from 8.0.0 to 10.1.0
> [0.72] Update fmt to 10.1.0

- change/react-native-windows-0d50f26a-8d3c-41c4-9796-c73e077e35f4.json
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- vnext/PropertySheets/JSEngine.props
Use Hermes package version 0.1.18.
This version contains memory leak fixes: https://github.com/microsoft/hermes-windows/pull/169
> [0.72] Change Hermes package version to 0.1.18 

- change/react-native-windows-57b4d8bd-9fd4-4950-94fb-fc27f7f8ef15.json
- vnext/Directory.Build.props
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
- vnext/fmt/cgmanifest.json
MSVC is deprecating stdext::checked_array_iterator which fmt was using and caused build breaks when we updated to VS 17.8.
Updating to fmt 10.1.0 since it removes all stdext::checked_array_iterator references. 
Update fmt version from 8.0.0 to 10.1.0
> [0.73] Update fmt to 10.1.0

- .ado/templates/react-native-init-windows.yml
- change/react-native-windows-20088f72-5201-4d7b-96c9-2b522fed786b.json
- vnext/templates/cpp-app/jest.config.windows.js
- vnext/templates/cpp-app/template.config.js
- vnext/templates/templateUtils.js
The upstream RN app template includes a jest test suite (run with `yarn test`) with a default test to render your app JS using the `react-test-renderer`. However, this only tests the iOS version of your app (it forces platform === 'ios') and therefore won't catch if there are issues in your `windows` platform files.
Using `@rnx-kit/jest-preset`, you can run jest tests against any platform via a custom jest config.
This PR adds `@rnx-kit/jest-preset` as a dependency to the new `cpp-app` template, as well as a `jest.config.windows.js` to use it. Furthermore it adds a script so users can run these tests for windows via `yarn test:windows`.
Finally this PR adds running `yarn test:windows` to the PR checks for testing the new app CLI.
Closes #11939
- New feature (non-breaking change which adds …
> Fabric: Enable react-test-renderer tests in the new cpp-app template

- change/react-native-windows-e6a650eb-7ab8-4cf5-b094-4b685648e01a.json
- vnext/Shared/Networking/DefaultBlobResource.cpp
- Check HTTP handler property and value exist
- Change files
Ensure HTTP proxy (handler) is correctly registered by Blob resource after instance reload.
When direct debugging is used instead of web debugging, module initialization happens out of order and HTTP blob responses get mishandled due to the lack of Blob module (and associated resources) setup.
This was partially addressed by #11439.
On React Instance reload, the property bag entries `Http.Proxy` and `Blob.Resource` still exist but their values are no longer valid (they were discarded next to the previous instance's module hierarchy).
Therefore, there is no HTTP proxy that can register the Blob resource nor a Blob resource that can register the HTTP proxy inside their …
> Ensure both property and value exist for Blob's HTTP proxy

- change/react-native-windows-e9e06367-1f4f-4220-883d-fe87a724ef13.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/integration-test-app/windows/integrationtest/packages.lock.json
- packages/playground/CoreApp/packages.lock.json
- packages/playground/windows/PlaygroundNativeModules/packages.lock.json
- packages/playground/windows/playground-composition/packages.lock.json
- packages/playground/windows/playground-win32/packages.lock.json
- packages/playground/windows/playground/packages.lock.json
- packages/sample-apps/windows/SampleAppCPP/packages.lock.json
- packages/sample-apps/windows/SampleAppCS/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCPP/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/Microsoft.ReactNative.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.lock.json
Use Hermes package version 0.1.18.
This version contains memory leak fixes: https://github.com/microsoft/hermes-windows/pull/169
> [0.73] Change Hermes package version to 0.1.18

- change/@office-iss-react-native-win32-108790fb-da57-49ce-a33a-cdd1c01607c8.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Core/ExceptionsManager.win32.js
Allows reporting of errors to native code, even if the logbox was shown.
This allows us better reporting of debug automation issues.
> [0.72] Call exceptions manager even in DEV bundles

- change/react-native-windows-31a36a4a-d57a-4bc4-a0f4-e84d0ec76158.json
- vnext/PropertySheets/Release.props
This PR backports #12313 to 0.73.
This PR enables the `/PROFILE` linker flag so binaries are [vulcan ready](https://eng.ms/docs/products/apiscan/howto/preparinginput/binaries/creating_vulcan_ready_files), and will therefore pass internal compliance requirements.
To pass APIScan.
Added `<Link><Profile>true</Profile><Link>` to `Release.props`.
N/A
N/A
Enabled the `/PROFILE` linker flag for all C++ release binaries
> [0.73] Enable the `/PROFILE` linker flag for all C++ release binaries

- change/react-native-windows-31a36a4a-d57a-4bc4-a0f4-e84d0ec76158.json
- vnext/PropertySheets/Release.props
This PR backports #12313 to 0.72.
This PR enables the `/PROFILE` linker flag so binaries are [vulcan ready](https://eng.ms/docs/products/apiscan/howto/preparinginput/binaries/creating_vulcan_ready_files), and will therefore pass internal compliance requirements.
To pass APIScan.
Added `<Link><Profile>true</Profile><Link>` to `Release.props`.
N/A
N/A
Enabled the `/PROFILE` linker flag for all C++ release binaries
> [0.72] Enable the `/PROFILE` linker flag for all C++ release binaries

- change/react-native-windows-31a36a4a-d57a-4bc4-a0f4-e84d0ec76158.json
- vnext/PropertySheets/Release.props
This PR backports #12313 to 0.70.
This PR enables the `/PROFILE` linker flag so binaries are [vulcan ready](https://eng.ms/docs/products/apiscan/howto/preparinginput/binaries/creating_vulcan_ready_files), and will therefore pass internal compliance requirements.
To pass APIScan.
Added `<Link><Profile>true</Profile><Link>` to `Release.props`.
N/A
N/A
Enabled the `/PROFILE` linker flag for all C++ release binaries
> [0.70] Enable the `/PROFILE` linker flag for all C++ release binaries

- change/react-native-windows-31a36a4a-d57a-4bc4-a0f4-e84d0ec76158.json
- vnext/PropertySheets/Release.props
This PR backports #12313 to 0.71.
This PR enables the `/PROFILE` linker flag so binaries are [vulcan ready](https://eng.ms/docs/products/apiscan/howto/preparinginput/binaries/creating_vulcan_ready_files), and will therefore pass internal compliance requirements.
To pass APIScan.
Added `<Link><Profile>true</Profile><Link>` to `Release.props`.
N/A
N/A
Enabled the `/PROFILE` linker flag for all C++ release binaries
> [0.71] Enable the `/PROFILE` linker flag for all C++ release binaries

- change/react-native-windows-d7fe4f1c-4277-4c6f-bf59-4b12118c130c.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Adds caretHidden to Fabric's TextInput
Component Parity with Paper
Overrides RichEdit controlling the visibility of the caret visual if caretHidden is set to true.
https://github.com/microsoft/react-native-windows/assets/42554868/085cfe07-1837-4f5e-8be2-3a64ba1811f1
tested locally
no
> [Fabric] Add caretHidden to TextInput

- change/react-native-windows-bd63c12c-5336-4f32-a5f0-2f1b5aed9420.json
- packages/e2e-test-app-fabric/test/__snapshots__/HomeUIADump.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- vnext/Microsoft.ReactNative/CompositionRootView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.cpp
- vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.h
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
- vnext/Microsoft.ReactNative/Theme.idl
- vnext/Microsoft.ReactNative/Utils/ThemeUtils.cpp
- vnext/Microsoft.ReactNative/Utils/ThemeUtils.h
- vnext/Shared/Shared.vcxitems
Adds a Theme runtimeclass and ability to provide custom colors.
Adds a Theme property to CompositionRootView to provide native colors for that root view.
Fixes Appearance module to provide theming information without Xaml.
Adds values to built-in theme for dark and high contrast themes.
> [Fabric] Add support for custom themes and support runtime theme change

- .ado/templates/enable-fabric-experimental-feature.yml
Currently the react-native-win32 fabric dll is built without support for WinAppSDK composition. 
This change will only affect the win32 dll.
> Desktop fabric build should build against winappsdk

- change/react-native-windows-16ae9eea-0f37-40b2-91da-33069ca74dd5.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
Use HTTP form data as array.
After adopting the HTTP module spec from react-native\Libraries\Network\NativeNetworkingIOS.js, form data is now provided as a JSArray of JSObjects.
Resolves #12392
Cast and handle request form data as `JSArray`.
See https://github.com/jurocha-ms/Repro/tree/main/ReactNative/formupload
> Use HTTP form data as JSArray

- change/@office-iss-react-native-win32-9be91a2d-db10-4f5b-8cf6-70f220bef704.json
- change/@react-native-windows-cli-28734a9c-b9e7-45cf-8242-21d33915b1df.json
- change/@react-native-windows-codegen-60eef339-adb2-43fb-bb92-29282bc0242e.json
- change/@react-native-windows-find-repo-root-9dd0547c-f5f7-4c8d-b53e-f621edd7f803.json
- change/@react-native-windows-fs-d5ce7d96-66f4-4255-9f74-3a407bda080c.json
- change/@react-native-windows-package-utils-cd0de561-e384-463e-bd6e-d1a2411001cc.json
- change/@react-native-windows-telemetry-a95d5dfc-01f7-4b11-ae12-bffd0612a734.json
- change/react-native-windows-18cd368f-513e-4451-8689-6cecf8043bea.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
Promote 0.72 to legacy so we can promote 0.73 to latest
> Promote 0.72 to legacy

- change/react-native-windows-e48a3cd6-aace-48d4-8b2b-a2b495958ffc.json
- vnext/Desktop.UnitTests/BaseFileReaderResourceUnitTest.cpp
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
- vnext/Shared/BaseFileReaderResource.cpp
- vnext/Shared/Shared.vcxitems.filters
Fixes Base64 encoding used by FileReader.
`FileReader.readAsDataURL` yields incorrect or truncated messages.
Resolves #12484
Appends the necessary `=` character instances to encoded Base64 messages resolved by the `FileReader` module.
Defined test `BaseFileReaderResourceUnitTest::Base64EncodesCorrectly`.
> Fix FileReader Base64 padding

- .ado/jobs/setup.yml
- .ado/publish.yml
This PR fixes the beachball check added in #12293 to actually stop the publish pipeline when errors are detected. Furthermore it adds a parameter to enable this check, default on, but which can be manually disabled when we're trying to promote a release branch (either from latest to legacy, preview to latest, etc).
This PR also adds a version of the check to the standard setup task that instead reports warnings when invalid change files are detected - hopefully this will improve our chances of catching these errors before getting to publish, without having to unduly block CI/PRs.
In publishing 0.73 an (expected) error was detected as the `@office-iss\react-native-win32` package was being promoted. Any error should have caused the …
> Beachball Check should actually stop publish

- change/react-native-windows-eef41231-d0eb-44a9-ac0d-d3905027d8bb.json
- vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp
In this async method in ImageUtils, we should be using co_return. It appears MSVC is a bit more forgiving than clang on this front.
Changes return to co_return in async method.
GitHub CI should tell us if this is okay.
> Switch ImageUtils.cpp to use co_return

- change/react-native-windows-309d1be9-0f85-43eb-9c74-12f0cc98b258.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.h
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/Modules/BlobModule.h
- vnext/Shared/Modules/FileReaderModule.h
- vnext/Shared/Modules/HttpModule.h
- vnext/Shared/Modules/WebSocketTurboModule.h
- vnext/Shared/OInstance.cpp
Normalizes a few react-native-windows #includes to simplify our clang builds. Specifically:
1. All includes of `vnext/codegen` module headers use `codegen/` header namespace.
2. `IReactNotificationService.h` should not use the `Microsoft.ReactNative` header namespace
3. `glog/logging.h` is needed to compile PaperUIManagerModule.h (the `CHECK` callsites)
4. Switch `jsiexecutor/jsireact/JSIExecutor.h` to `jsireact/JSIExecutor.h` to match upstream mobile RN header namespacing expectations.
Built Playground locally, CI checks should cover most configurations
> Normalizes headers for clang builds

- change/@react-native-windows-telemetry-da655939-1091-492d-85c9-068ad5174f5e.json
- packages/@react-native-windows/telemetry/package.json
- yarn.lock
Fixes a build break introduced by #12575 
yarn build is broken with this due to a bug in the package that gets run during codegen
Revert back to the working version.
N/A
Ran yarn build
> Revert back to applicationinsights@2.9.1

- change/@react-native-windows-telemetry-9788bf42-5c81-406e-ba8e-883e7a515d93.json
- packages/@react-native-windows/telemetry/package.json
- yarn.lock
When updating dependencies in main, (see #12575), we found that applicationinsights@2.9.2 breaks our CLI commands.
We aren't actually collecting telemetry so there's no problem with locking the version of this package in this branch for now.
To unblock calls to CLI commands by new projects.
Lock to the current version used by this branch.
N/A
Ran yarn build locally, which calls `codegen-windows` internally.
> [0.73] Lock to applicationinsights@2.7.3 to prevent using newer broken versions

- change/@react-native-windows-telemetry-91382c5a-7bdf-4ec8-995d-eccfef9ae23d.json
- packages/@react-native-windows/telemetry/package.json
- yarn.lock
When updating dependencies in main, (see #12575), we found that applicationinsights@2.9.2 breaks our CLI commands.
We aren't actually collecting telemetry so there's no problem with locking the version of this package in this branch for now.
To unblock calls to CLI commands by new projects.
Lock to the current version used by this branch.
N/A
Ran yarn build locally, which calls `codegen-windows` internally.
> [0.72] Lock to applicationinsights@2.6.0 to prevent using newer broken versions

- change/react-native-windows-cd43f7b4-f22b-4a94-a3fc-784d8abcd991.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
ScrollView should be reporting its current contentOffset to its ShadowNode so that various scroll properties and methods can work correctly on the JS side.
> [Fabric] ScrollViewComponentView should report ContentOffset to its shadownode state

- change/react-native-windows-ca1e0f76-9b50-47ba-b876-2d9f66d25406.json
- vnext/src/Libraries/NewAppScreen/components/DebugInstructions.windows.js
- vnext/src/Libraries/NewAppScreen/components/ReloadInstructions.windows.js
Rather than using absolute imports, modules in react-native use relative imports.
This matches the imports (with the exception of the irrelevant Platform import) from the overridden files in react-native.
> Modules in react-native use relative imports

- change/@office-iss-react-native-win32-4978107b-1f1d-4c70-bc36-d4179876bcbf.json
- change/react-native-windows-6f011f27-f8c7-4f17-9014-8460dcce9596.json
- packages/@office-iss/react-native-win32-tester/NativeComponentExample/js/MyNativeView.js
- packages/@office-iss/react-native-win32-tester/NativeComponentExample/js/MyNativeViewNativeComponent.js
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Color/ColorGradientWin32Example.js
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Pressable/PressableExample.win32.js
- packages/@office-iss/react-native-win32-tester/src/js/examples/PlatformColor/PlatformColorExample.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/StyleSheet/PlatformColorValueTypes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/StyleSheet/PlatformColorValueTypesWin32.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/StyleSheet/PlatformColorValueTypesWin32.js
- packages/@react-native-windows/tester/NativeComponentExample/js/MyNativeView.js
- packages/@react-native-windows/tester/NativeComponentExample/js/MyNativeViewNativeComponent.js
- vnext/src/IntegrationTests/WebSocketBinaryTest.js
- vnext/src/IntegrationTests/WebSocketBlobTest.js
- vnext/src/IntegrationTests/websocket_integration_test_server_binary.js
- vnext/src/IntegrationTests/websocket_integration_test_server_blob.js
- vnext/src/Libraries/Alert/NativeDialogManagerWindows.js
- vnext/src/Libraries/Components/TextInput/WindowsTextInputNativeComponent.js
- vnext/src/Libraries/StyleSheet/PlatformColorValueTypes.windows.js
The upstream license headers switched from:
```
Copyright (c) Facebook, Inc. and its affiliates.
```
To:
```
Copyright (c) Meta Platforms, Inc. and affiliates.
```
This updates all the file overrides with the correct license header.
> Fix license header in file overrides

- change/react-native-windows-c60ee71f-e2dd-4ae4-8f83-46c2acfa1183.json
- vnext/Desktop.UnitTests/ScriptStoreTests.cpp
- vnext/Shared/BaseScriptStoreImpl.cpp
- vnext/Shared/Hasher.cpp
- vnext/Shared/Hasher.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
This backport the change from https://github.com/microsoft/react-native-windows/pull/11780 that already exists in main, 0.71 and 0.73.
We're seeing some crashes that may be caused by corrupt script caches.
Add a checksum to avoid loading a corrupt cache.
> [0.72] Add checksum to ScriptStore cache

- package.json
- yarn.lock
* Updated `postcss`
* Updated `react-devtools-core`
* Updated `get-func-name`
* Updated `@babel/traverse`
* Locked `@babel/core` to 7.23.2 via a resolution.
> [0.72] Component Governance fixes for 16-JAN-24

- change/@react-native-windows-automation-channel-66ab6767-e106-47bd-b699-8e892191c8eb.json
- change/react-native-windows-9c96ab5f-7f4c-47e8-9195-f4ee29175c8f.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/JSEngine.props
- vnext/PropertySheets/React.Cpp.props
Refactors the loading of ExperimentalFeatures.props into React.Cpp.props so every project gets it at the right time in the build parsing.
We use ExperimentalFeatures.props to set global variables that all projects need, so we need to make sure it gets loaded at the right place.
Moved ExperimentaFeatures.props loading into React.Cpp.props. This also exposed a bug where the AutomationChannel project was not using the props and therefore potentially building against a different Windows SDK than the consuming e2e-fabric-app.
N/A
N/A
> Ensure ExperimentalFeatures.props is loaded in all projects

- change/react-native-windows-04c9d96c-59d9-47d2-8bb5-cff09ff7b8a4.json
- vnext/Scripts/rnw-dependencies.ps1
This PR updates the `rnw-dependencies.ps1` script as follows:
- For the `rnwDev` setup, ensures the Windows 11 22000 SDK is installed, as required for some of the new Fabric/Composition apps
- Since the Node LTS package on winget is already on Node 20, and we currently still use Node 18, change the installer to install the exact version we also use in CI, just to reduce new developers getting untested setups
Closes #12443
To help ensure devs had the a working setup.
Added the correct SDK component and changed the WinGetInstall method to allow a specific version number.
N/A
Verified install works
> Update RNW Dependency Script Node.js and Windows SDK versions

- change/react-native-windows-b7c46047-47e0-4c3e-a5bc-0c331d63c024.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
ScrollBars will now shrink down to touch indicators when not in use
Fix minor misalignment of scrollbar arrow buttons in high dpi.
Modified PointerEntered/PointerExited events to not bubble by default, aligning better with WinUI, and being easier to use.
> [Fabric] Add scrollbar show/hide logic

- change/react-native-windows-20feaf3b-ebde-4326-83d1-dc39007bfebf.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Backporting #11756 into 0.72. Potential fix for #12629. 
Changed logic in FrameworkElementViewManager for setting 'collapsed' accessibility state so that collapsed is not set to true by default when expanded is false.
Resolves [#11734]
Checks to see if the expanded property is null i.e not set by the component. If so, sets collapsed to false instead of defaulting to true when expanded is false. If property is not null, then performs check and sets collapsed property based on value.
Tested locally on RNTester Button page in playground. Seems to be performing as desired there - Narrator no longer making 'collapsed' announcement on buttons and UIA tree reflects this with the ExpandCollapsed property being of LeafNode instead of collapsed. …
> [0.72] Changed logic for setting collapsed property to true

- change/react-native-windows-018bcc99-b1e5-44c5-a42f-6c946eaedad5.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
- vnext/templates/cpp-app/windows/MyApp/MyApp.cpp
Currently the default app template and our various fabric apps run layout with 0,0 constraint when the window is minimized.  This change prevents the extra layout.
> [Fabric] Do not run a 0,0 layout when minimizing the window

- change/react-native-windows-f7d7e7a7-210b-4402-b595-5ef83e238f3f.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
Update Switch to have the newer fluent visuals (In particular the change of the thumb to a rounded rectangle rather than an ellipse when in the pressed state)
Also switched switch to use the more generic RoundedRectangleVisual rather than having to have a switch specific visual type in the compositionswitcher.
> [Fabric] Update switch visuals to newer fluent visuals

- change/react-native-windows-da0c1993-6a72-42cd-b8a2-7ebe3cab80fa.json
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
When using input from window messages, events from WM_POINTER* get incorrect positions, which causes scrollbars to not work correctly.  This is due to WM_POINTER events coming in screen coordinates, vs the WM_MOUSE events which come in client coordinates.
> [Fabric] Fix issue causing PointerMove events to have incorrect position when using WM_msg input

- .ado/jobs/cli-init-windows.yml
- .vscode/settings.json
- change/react-native-windows-d83c7f4b-e898-4530-bbc4-027b2cc19b54.json
- vnext/templates/cpp-app/windows/MyApp/MyApp.vcxproj
- vnext/templates/cpp-lib/windows/MyLib/MyLib.vcxproj
This PR fixes up the new `cpp-lib` and `cpp-app` templates to support targeting ARM64, and adds ARM64 builds to the CI/PR matrix.
To enable native builds of ARM64
Closes #12633 
Added the proper configurations to 
N/A
Verified the apps build in CI
Updated the experimental `cpp-lib` and `cpp-app` templates to support targeting ARM64.
> Add ARM64 to new arch templates

- change/react-native-windows-6dacc619-c892-4699-a1c5-699dcb40ed6b.json
- vnext/Shared/JSI/ChakraRuntime.cpp
When Chakra encounters a syntax error, it does not provide line/column numbers, making it hard to determine what went wrong.
This change extracts line/column from the error and appends it to the error message.
| :-: | :-: |
| ![image](https://github.com/microsoft/react-native-windows/assets/4123478/c2f1b1fb-bfa9-43a4-9bc3-1750a6b8383a) | ![image](https://github.com/microsoft/react-native-windows/assets/4123478/956b7a33-ce27-4c98-b845-dbef77a87684) |
Add a valid JS line that Chakra does not recognize at the top of `index.js`, e.g.:
```js
test ??= 1;
```
Include line/column numbers when Chakra encounters a syntax error
> Include line/column numbers on syntax error

- change/react-native-windows-6dacc619-c892-4699-a1c5-699dcb40ed6b.json
- vnext/Shared/JSI/ChakraRuntime.cpp
When Chakra encounters a syntax error, it does not provide line/column numbers, making it hard to determine what went wrong.
This change extracts line/column from the error and appends it to the error message.
Cherry-picks #12644
| :-: | :-: |
| ![image](https://github.com/microsoft/react-native-windows/assets/4123478/c2f1b1fb-bfa9-43a4-9bc3-1750a6b8383a) | ![image](https://github.com/microsoft/react-native-windows/assets/4123478/956b7a33-ce27-4c98-b845-dbef77a87684) |
Add a valid JS line that Chakra does not recognize at the top of `index.js`, e.g.:
```js
test ??= 1;
```
Include line/column numbers when Chakra encounters a syntax error
> [0.72] Include line/column numbers on syntax error

- change/react-native-windows-824d287e-442d-44d6-8e7d-e6f0f6cb3b12.json
- vnext/Microsoft.ReactNative/Composition.Input.idl
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
Adds infra to provide pointer capture to ViewComponents.
Uses that infra to capture pointer input while performing scrollbar thumb drags, which allows the user to not have to keep the pointer within the ScrollView while dragging the scrollbar thumb.
> [Fabric] Capture pointer input during scroll thumb drag

- change/react-native-windows-aa56d537-586f-4d5b-8e8b-4c227f738d1b.json
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.h
Aligns the implementation of `UnimplementedNativeViewComponentView` better with the core implementation.  In particular, making it behave like a normal view, but with an extra overlay displaying the "UnimplementedView" error.  This allows more functionality to work in the case of an unimplemented view for a better developer experience.
> [Fabric] Allow unimplemented native views to have children

- packages/playground/README_composition.md
Add mention of the `-Enterprise` flag for internal developers.
Internal devs use VS Enterprise, and without the flag the script tries to install VS Community.
Updated docs.
N/A
N/A
> Update README_composition.md with Enterprise

- change/react-native-windows-d81c3da7-477e-4def-8b2c-cb306856b83a.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
The scroll thumb will end up slightly offset if the user grabs the scrollthumb and starts moving it before the animation from shy scrollbar to the full scrollbar completed.
The fix is to turn off all thumb animations when moving it through manual scrollbar thumb drag.
> [Fabric] fix visual issue when quickly dragging scrollthumb before it finishes animating in

- change/react-native-windows-ccf12cc0-5edc-4a16-a5a7-7cc0926c46d9.json
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
react-native-windows currently returns an empty object for UIManager::getConstantsForViewManager. This breaks the hasViewManagerConfig checks in JS, which may be used to determine whether a view should attempt to render or not (or to gate a requireNativeComponent call, in the case of DebuggingOverlay). Having this behavior would have prevented the need to introduce the stub DebuggingOverlay view manager.
Fixes bug where hasViewManagerConfig checks may have returned truthy values
> Return null for missing view manager constants

- change/react-native-windows-a0922e31-5eb5-4bcd-ac1d-5586b82479c2.json
- vnext/Mso/future/details/executor.h
This fixes up a clang warning about const qualifiers that have no effect. Since this is already a constexpr, the const qualifier is not needed.
> Cleanup const qualifier on constexpr

- change/react-native-windows-5159d78a-73cf-403d-98ad-9345e6333418.json
- vnext/Microsoft.ReactNative/Base/FollyIncludes.h
- vnext/Microsoft.ReactNative/ReactHost/IReactInstance.h
Updating the casing of various folly includes in react-native-windows to clean up clang warnings related to non-portable includes.
> Fixes clang warnings for non-portable folly includes

- change/react-native-windows-82238772-4d82-4442-8dcf-de8b46c20a75.json
- vnext/Microsoft.ReactNative/Base/CxxReactIncludes.h
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
We see errors like:
```
Views\ShadowNodeBase.h:10:10: error: non-portable path to file '<yoga/Yoga.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
^~~~~~~~~~~~~
<yoga/Yoga.h>
1 error generated.
```
When compiling with clang. This cleans up all the invalid Yoga includes.
> Fix clang warnings for non-portable Yoga includes

- change/@office-iss-react-native-win32-0549a4a8-7591-4366-88c0-2c6b2db77f12.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInputState.win32.js
This brings the logic in TextInputState in alignment with the windows implementation.
> [Win32] view.focus sometimes skips setting focus

- .unbroken_exclusions
The Linting PR CI job is timing out while running the "check web links in .md files" task. 
For some reason unbroken hangs when it gets to the .github/security.md file. 
Neither security.md nor unbroken have changed in several years. Adding it to the exclusion list would unblock CI for now.
> Add unbroken exclusion to unblock CI

- .ado/compliance.yml
- .ado/continuous.yml
- .ado/image/rnw-img-vs2022-node18.json
- .ado/jobs/cli-init.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/node-tests.yml
- .ado/jobs/playground.yml
- .ado/publish.yml
- .ado/templates/prepare-js-env.yml
- .ado/windows-vs-pr.yml
- .unbroken_exclusions
- change/@office-iss-react-native-win32-2a5de4b2-a121-42e6-8388-1f71a7c705af.json
- change/react-native-windows-1d2f797d-2e27-460b-acbb-450fe696a40b.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInputState.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/Win32TextInputNativeComponent.js
- packages/react-native-windows-init/src/Cli.ts
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
Port of #12692 and #11495 to 0.72.
Also bump CI machines to node 18 - since 16 is out of support, and some downstream dependencies have published new versions requiring node 18 which break cli-init tests.
> [0.72] [Win32] view.focus sometimes skips setting focus 

- .ado/continuous.yml
- .ado/publish.yml
Publish appears to break running on node 18.  I moved to 18 primarily for the cli init tests, which publish doesn't run - so this should be fine.
> [0.72] Move publish builds back to node 16

- change/@react-native-windows-fs-00c3c8c9-831c-49c5-ba9d-1649bffe54bf.json
- change/@react-native-windows-telemetry-7d014f54-a40e-4c1a-8c2c-ba9e04d9cedf.json
- change/react-native-windows-init-e2368ae7-35ec-488c-97d3-2731769bc2f1.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/telemetry/package.json
- packages/react-native-windows-init/package.json
- yarn.lock
Fixes `react-native-windows-init` to still work on Node 16.
RNW 0.72 still required Node 16 and so this script still needs to work on Node 16 machines.
Resolves #12711 
Removed the engine requirement on `react-native-windows-init` and the two packages of ours it requires to make sure we never pull in a dependency that requires Node 18.
N/A
N/A
> Ensure react-native-windows-init still works on Node 16

- change/react-native-windows-e5e178ee-29d3-4576-a7a2-9c156569188c.json
- vnext/Common/Utilities.cpp
- vnext/Desktop.UnitTests/UtilsTest.cpp
- vnext/Shared/Modules/FileReaderModule.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
Add missing Standard Libirary includes for compiling Base64 encoding functions.
C++17 won't infer the missing entries automatically.
This would break compilation in non-`main` branches.
Add `winrt/` and `sstream` header includes
> Add missing sstream includes

- .ado/jobs/playground.yml
- change/react-native-windows-40fd0d43-fac7-435f-ab0a-2c0c7e55c981.json
- packages/playground/windows/ExperimentalFeatures.props
- vnext/Scripts/EnableInternalWinAppSDKFeed.ps1
This PR:
1. Removes the hardcoded UseExperimentalWinUI3 == true flag in the Playground Composition project
2. Adds new configurations to the CI matrix to set it to true for Playground Composition
3. Adds a new script to enable access to the internal WinUI3 builds, and runs it if the `EnableInternalWinAppSDKFeed` variable is set
We need to build playground with both the release WinUI and internal experimental versions.
See above.
N/A
N/A
> Add Playground Composition CI Builds with UseExperimentalWinUI3 enabled

- change/react-native-windows-4ed5a244-28e4-46c9-bfb6-e5949f7c3af2.json
- packages/e2e-test-app/windows/RNTesterApp/App.xaml.cs
- packages/sample-apps/windows/SampleAppCS/App.xaml.cs
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/TestReactNativeHostHolder.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative.Managed/ReactSettingsSnapshot.cs
- vnext/Microsoft.ReactNative/DevMenuControl.idl
- vnext/Microsoft.ReactNative/DevMenuControl.xaml
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/template/cpp-app/src/App.cpp
- vnext/template/cs-app/src/App.xaml.cs
Marking the UseWebDebugging APIs as deprecated, and removing the option from the dev menu.  This aligns with what core has done as steps towards removing WebDebugging.
> Deprecate web debugging

- change/react-native-windows-a4bd116e-b944-4372-ad29-cdf37e39b336.json
- vnext/Microsoft.ReactNative/CompositionHwndHost.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.h
CompositionHwndHost which is used internally by LogBox only had an implementation for system composition.
> [Fabric] LogBox crashes when running lifted composition

- change/react-native-windows-e8be0ae0-0b26-45e7-8ec8-ddff443c2546.json
- packages/playground/windows/playground-composition/CustomComponent.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative/ComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
Added ability for 3rd party components to customize MountChildComponentView and UnmountChildComponentView.
Added a new helper ReadProp to allow simple implementation of IComponentProps::SetProp.
> [Fabric] Expose (un)MountChildComponentView to 3P components

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/cli-init.yml
- .ado/jobs/desktop.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/linting.yml
- .ado/jobs/node-tests.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/jobs/setup.yml
- .ado/jobs/universal.yml
- .ado/scripts/setVersionEnvVars.js
- .ado/stages.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/set-appx-platforms.yml
- .ado/templates/set-version-vars.yml
- .ado/windows-vs-pr-secure.yml
This PR adds a `SecurePullRequest` to the `PullRequest` and `Continuous` build environment in our ADO pipelines. This `SecurePullRequest` will be used to enable build configurations that need access to secure resources (such as internal ADO feeds) and will only be run when using `/azp run`
To enable PRs testing against internal nugets.
Resolves #12676
Resolves #12677
See above.
N/A
Verified existing PRs still work
> Add new SecurePullRequest Build Environment in ADO

- packages/@react-native-windows/tester/src/js/examples/View/ViewExample.windows.js
We still have a couple Alert callsites, perhaps in Windows-specific View examples.
> Adds Alert back to ViewExample

- change/react-native-windows-3f32eace-b18b-47b9-bc5d-0a51b9daf1c8.json
- vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Currently UI Dispatcher Queue deadlocks on shutdown if its last reference is released before the last UI task is completed.
The reason is that the UIScheduler waits for a signal that the last Windows UI `DispatcherQueue` task is completed. 
The signal cannot come because the wait happens while the last task is being executed, since the last release happens inside of the last task.
In this PR we:
- address the issue by avoiding the wait if the UIScheduler `AwaitTermination()` is called from UI thread.
- add new unit tests for Serial and UI Dispatcher Queues to test different shutdown conditions.
> Fix UIScheduler deadlock on shutdown

- change/react-native-windows-0a05de02-b6f0-483e-b6f8-9814e25fc011.json
- vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
- vnext/Shared/Shared.vcxitems.filters
Currently UI Dispatcher Queue deadlocks on shutdown if its last reference is released before the last UI task is completed.
The reason is that the UIScheduler waits for a signal that the last Windows UI `DispatcherQueue` task is completed. 
The signal cannot come because the wait happens while the last task is being executed, since the last release happens inside of the last task.
In this PR we:
- address the issue by avoiding the wait if the UIScheduler `AwaitTermination()` is called from UI thread.
- add new unit tests for Serial and UI Dispatcher Queues to test different shutdown conditions.
> [0.73] Fix UIScheduler deadlock on shutdown

- change/react-native-windows-061fcd4e-4f2d-4428-bb66-aba914446681.json
- vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
- vnext/Shared/Shared.vcxitems.filters
Currently UI Dispatcher Queue deadlocks on shutdown if its last reference is released before the last UI task is completed.
The reason is that the UIScheduler waits for a signal that the last Windows UI `DispatcherQueue` task is completed. 
The signal cannot come because the wait happens while the last task is being executed, since the last release happens inside of the last task.
In this PR we:
- address the issue by avoiding the wait if the UIScheduler `AwaitTermination()` is called from UI thread.
- add new unit tests for Serial and UI Dispatcher Queues to test different shutdown conditions.
> [0.72] Fix UIScheduler deadlock on shutdown

- change/react-native-windows-8be51422-0198-43a0-bbab-29659d755e48.json
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.h
Adds onSumbitEditing and clearTextOnSubmit to TextInput
TextInput parity
Adds onSumbitEditing event to TextInput and keeps track of if the shift key is pressed.
https://github.com/microsoft/react-native-windows/assets/42554868/bc25e23c-da05-4759-9d3f-af581f2658b7
tested locally
no
> [Fabric] Add onSubmitEditing and clearTextOnSubmit

- change/react-native-windows-aa8367b6-17de-4644-b985-dfabfe7c393d.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/pch.h
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-composition/pch.h
- vnext/templates/cpp-app/windows/MyApp/MyApp.cpp
- vnext/templates/cpp-app/windows/MyApp/pch.h
- vnext/templates/cpp-lib/windows/MyLib/pch.h
The new cpp-app template (and related apps `playground-composition` and `e2e-test-app-fabric`) were all set with an invalid `BundleRootPath`. This causes the app to throw an error because it can't parse the given path from the URI, furthermore, since it was a URI based on the current working directory, it might not even be the right directory to load the bundle from.
This PR fixes the issue by instead using the correct `file://` URI scheme and also looking for the bundle path relative to the location of the app exe itself. This PR also re-aligns the apps to use the similar instance settings setup of the older UWP app (using both the `BUNDLE` and `_DEBUG` macros appropriately).
Partially resolves #12752
So that release builds work for …
> Fix issue with new arch cpp-app apps not finding the bundle in release builds

- change/react-native-windows-4fa3799d-8c88-4d16-9663-28b1dd4f7b26.json
- vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp
Fixes the loading of images via `file://` URIs, which is what is used for asset files in (unpackaged) Fabric apps.
To fix image loading.
Resolves #12755
The API we use to load the image can support `file://` URI's directly, we were doing a bunch of (now no longer necessary?) path processing that ultimately wasn't working. This change removes that processing.
Before: 
After:
Verified images started loading.
Fixed loading images from `file://` URIs (as used for assets in on-disk bundles)
> Fix loading images from `file://` URIs 

- change/react-native-windows-99c99c3c-c277-47d4-8b96-f85ec2fa4a8a.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
For some legacy internal code paths we require this additional method to be exported.
> [0.73] [NetUI] Export getRuntimeExecutor for internal usage

- change/react-native-windows-7b79ad4a-100c-4545-9114-382ce48e59dd.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/JSI/JSExecutorFactoryDelegate.h
- vnext/Shared/JSI/JSExecutorFactorySettings.cpp
- vnext/Shared/JSI/JSExecutorFactorySettings.h
- vnext/Shared/OInstance.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Some apps may want to bypass the JsiAbiApi altogether (e.g., compiling a custom JS runtime that is not currently supported by react-native-windows).
This change introduces the JSExecutorFactorySettings, which allows you to set a non-ABI JSExecutorFactory instance. It also prefers this option if available over the ABI JSI runtime.
Validated in our app that we are able to inject a non-ABI JSExecutorFactory.
> Adds option to set Non-ABI Runtime instance

- change/react-native-windows-ab0cc492-2a8f-47fe-ac58-d039f0a629c7.json
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- vnext/src-win/Libraries/Components/Pressable/Pressable.windows.js
- vnext/src-win/Libraries/Pressability/Pressability.windows.js
Adds the value of the disabled property to props that are being passed into the Pressable component native code. Additionally, also adds a disabled property check before calling the onKeyDown event handler.
Resolves https://github.com/microsoft/react-native-gallery/issues/364
Resolves https://github.com/microsoft/react-native-gallery/issues/363
Added statement to set Boolean value of prop before passed into Pressable component, and disabled property conditional check to onKeyDown handler.
Tested in RNTester and standalone example Pressable component. 
Sample Pressable component code:
```
<Pressable
accessibilityRole="button"
accessibilityLabel={'example disabled pressable'}
style={{
width: 140,
height: 50,
borderRadius: 2, …
```
> Add disabled property to props being passed into Pressable component

- change/react-native-windows-20bf6698-68e4-4c9f-b7d4-e2a6b667b687.json
- vnext/templates/cpp-app/windows/MyApp/MyApp.cpp
Remove unused globals from Fabric template
There are unused globals in the Fabric template.
We shouldn't have globals if we can't help it. Since these were unused, they were removed.
n/a
n/a
> chore: remove unused globals from Fabric template

- change/react-native-windows-92d439dc-c4c3-4708-894f-c2312a70d71e.json
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
Backports #12799 into 0.73-stable.
Adds the value of the disabled property to props that are being passed into the Pressable component native code. Additionally, also adds a disabled property check before calling the onKeyDown event handler.
Resolves https://github.com/microsoft/react-native-gallery/issues/364
Resolves https://github.com/microsoft/react-native-gallery/issues/363
Added statement to set Boolean value of prop before passed into Pressable component, and disabled property conditional check to onKeyDown handler.
Tested in RNTester and standalone example Pressable component. 
Sample Pressable component code:
```
<Pressable
accessibilityRole="button"
accessibilityLabel={'example disabled pressable'}
style={{
width: 140,
height: …
```
> [0.73] Add disabled property to props being passed into Pressable component

- change/react-native-windows-d9b2af2c-5b3c-4c5a-ba6c-147f72845e47.json
- packages/e2e-test-app-fabric/test/__snapshots__/ViewComponentTest.test.ts.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.cpp
- vnext/Microsoft.ReactNative/Modules/Timing.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Prior to this, there was no UIBatchingQueue being created when in bridgeless mode, which would cause the animation module to crash when used.
Updated snapshots to account for the layout conformance property which works correctly in bridgeless mode
Fixed an issue if you set a ReactViewHost on a CompositionRootView before the ReactHost was loaded
Fixed an issue in the Bridgeless timing module that was causing all timers to immediately fire
Moved some of the JS runtime initialization in bridgeless to be run on the JS thread synchronously to align with how we init it in bridge mode.
Fixed an issue where we wouldn't start the HMRClient in bridgeless mode
Fixed an issue where calls to JSFunctions hit during initialization may not get triggered when the runtime completed its initialization. …
> Add UIBatchingQueue to bridgeless mode

- change/react-native-windows-a60caa73-ecea-4299-a8e8-53287da9c616.json
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/CompositionContext.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
Aligning naming of the system version of CompositionContextHelper with how WindowsAppSDK names APIs that work against the system APIs.  APIs that work against system APIs in windowsAppSDK use a System prefix.  I previously used a Windows prefix to align with the system namespace.
> Rename WindowsCompositionContextHelper -> SystemCompositionContextHelper

- change/react-native-windows-b20ce41b-73cf-4c53-b96a-5bf1118b6135.json
- vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp
- vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.h
- vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.cpp
- vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.h
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- vnext/Microsoft.ReactNative/Views/cppwinrt/DynamicAutomationPeer.idl
In react-native v0.73, the `role` prop was switched from setting its value to `accessibilityRole` to a standalone native prop.
Resolves #11886
This wires up the native prop behavior in the Paper UIManager for react-native-windows.
Uses ARIA role to UIA mappings defined here:
https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-ariaspecification#w3c-aria-role-mapped-to-microsoft-active-accessibility-and-ui-automation
Some ARIA roles are not explicitly defined in the linked document. The remaining mappings were interpolated from other ARIA role mappings (e.g., `term` and `definition` go hand-in-hand, `table` mentions `grid` should be used in some circumstances, `none` and `presentation` are …
> Adds ARIA role support to Paper UIManager

- change/react-native-windows-75e893cc-3425-4200-95f1-84827cb03aa7.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
- vnext/Microsoft.ReactNative/Views/ICompositionRootView.h
- Implement `DebuggingOverlayComponentView` commands which means `react-devtools` can now highlight elements in fabric apps
- Add loading UI for `CompositionRootView`
- Prevent MS.UI.Xaml.dll loading when the app is not otherwise using xaml by adding an addition check in DeviceInfo.
- Fix a leak of a the Visual that was added by `RootComponentView` to the `CompositionRootView`, and never removed which would cause a Visual to be leaked on every instance reload.
> [Fabric] Implement LoadingUI and DebuggingOverlay

- change/react-native-windows-8ec5fa94-501b-40f4-a05c-c7a591e9583f.json
- vnext/Scripts/OfficeReact.Win32.nuspec
- vnext/Shared/DevServerHelper.h
- vnext/Shared/IDevSupportManager.h
- vnext/Shared/WebSocketJSExecutorFactory.h
Cleaning up the #includes to avoid having to bring too many additional headers into Office consumption.
> Minor clean up of headers for Office consumption

- .github/policies/resourceManagement.yml
Updates our bot to add "New Architecture" or "Old Architecture" if it detects a relevant Area being added to an issue/PR. The rule is purely additive: it does not remove any labels.
We're currently using the "Area: Fabric" label as a catch-all for any new architecture / composition / WinAppSDK work, when really it should just be for the UI layer, not everything else.
There are now new "Old Architecture" and "New Architecture" labels, this PR updates our bot to update new issues/PRs with the new labels when a matching category of Area label is applied.
N/A
N/A
> Update bot to Add New/Old Architecture labels if a New/Old Area label is added

- change/react-native-windows-bc10ca83-c1a9-4f4a-ac53-6d54378c3aca.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
- vnext/Shared/Networking/WinRTHttpResource.cpp
Sets HTTP origin URL per filter instance.
A crash can be caused by an inconsistent state when the host app is being shut down and an HTTP request has been scheduled from the JS layer.
This affects the static member `OriginPolicyHttpFilter::s_origin`.
Make the HTTP origin an instance member of `OriginPolicyHttpFilter` so the value will be bound to the filter's life time.
In most cases, this won't add significant memory overhead because the filter's instance (and its members) is a singleton for the owning resource, module, and React instance.
Updated tests `ValidatePreflightResponseHeadersCaseMismatchSucceeds` and `ValidatePreflightResponseMainAndContentHeadersSucceeds`.
> Make HTTP origin value an instance member

- change/@office-iss-react-native-win32-a0faf496-c505-442c-a26f-312be1b9ae7e.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Text/Text.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [0.73] [Win32] TextProps from rn-win32 should include win32 properties

- change/@office-iss-react-native-win32-8d81cf2e-bf87-4fdc-940e-e3a1bdada473.json
- packages/@office-iss/react-native-win32/src/Libraries/Text/Text.d.ts
I missed a property from the type info when forking the text TS type info.
> [0.72] [NetUI] Missed property when adding win32 specific text type info

- change/react-native-windows-2b0ebf99-bb7f-46f5-b276-1944aeafd68e.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Bridgeless code path was missing code to ensure the Hermes inspector connection to metro.
This is part of the fix for #12834.  The app will now show up in the list returned at `http://localhost:8081/json`.  But that doesn't appear to be sufficient for edge to be able to find the instance at `edge://inspect`
> Ensure Hermes Inspector in bridgeless

- change/@react-native-windows-cli-91d05574-6a9e-4835-951a-28821d7838b7.json
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
VS 2022 uses the 64-bit MSBuild by default. It's also what we use in CI when building. For some reason, `run-windows` is still using 32-bit MSBuild, which is unnecessary and puts memory limits on our compilation tasks.
In PR #12798 I'm trying to update our version of CppWinRT, and in some scenarios (namely release fabric builds) we've hit the 32-bit memory limit for linking.
Changed the CLI to use the 64-bit msbuild exe instead of the 32-bit one it was hardcoded to use.
N/A
Verified everything still builds.
The CLI build command `run-windows` now uses the same 64-bit MSBuild VS 2022 uses by default
> Fix `run-windows` to use 64-bit MSBuild (like VS 2022)

- packages/playground/windows/playground-composition/Playground-Composition.cpp
> Enable direct debugging by default in playground composition app

- change/react-native-windows-286662e9-d377-48ce-8d82-95e92de04270.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Modules/Timing.cpp
- vnext/Microsoft.ReactNative/Modules/Timing.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Timer.cpp
- vnext/Microsoft.ReactNative/Timer.h
- vnext/Microsoft.ReactNative/Timer.idl
- vnext/Shared/Shared.vcxitems
New method `Microsoft.ReactNative.ReactCoreInjection.SetTimerFactory` exposed that allows applications to provide a custom timer implementation.  This can be useful when using a custom `ICompositionContext` implementation to run React-Native-Windows in environments which may not have a `Microsoft.UI.Dispatching.DispatcherQueue` running.
Modules requiring native timers should use `Microsoft.ReactNative.Timer.Create(properties)` instead of `Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread().CreateTimer()` to ensure compatibility with applications using custom timers.
> Enable custom timer factory to be provided

- change/react-native-windows-5a089490-fcc0-472b-8823-55b5345df063.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
The current visuals are based on the WinUI 2 visuals.  This updates the visuals to the newer WinUI 3 visuals.
I also fixed an issue where AcitivityIndicator wouldn't scale properly for DPI.
Before:
https://github.com/microsoft/react-native-windows/assets/30809111/b2854b0f-71e4-4094-9933-6cb32952736d
After:
https://github.com/microsoft/react-native-windows/assets/30809111/482c1bcb-9164-4a96-8165-9748330e58f9
> [Fabric] Update ActivityIndicator to newer visuals

- change/react-native-windows-af6a8175-d270-491f-86c3-ee4c84fe4eb5.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextDrawing.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextDrawing.h
- vnext/Shared/Shared.vcxitems
Extract RenderText to a shared function, to allow easier text rendering in places other than ParagraphComponentView.
Fixed up some scaling issues in CompositionRootView's loading UI.
> [Farbic] Extract RenderText into helper function + clean up Loading visuals

- change/react-native-windows-ded8504d-7e64-46ef-9c94-474b8b0b7c61.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
`CompositionRootView::UninitRootView` will currently deadlock if the JS Queue has already been shut down as it requires a task on the JS queue to run before it will continue.
This change modifies the task to set the event being waited on when the task is destroyed.  This means that if the JS queue has already been shut down, the task will be released and `UninitRootView` will continue to run.
> [Fabric] Fix hang on shutdown when JS instance failed to start

- change/react-native-windows-5b3a6677-59a2-42c3-bd99-e6867b16abb8.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
After a dev reload, the ReactRootView is assigned a new root tag. We never evicted the old auto revoker from the m_sizeChangedVector when this occurred, and could lead to attempts to do layout on a stale root tag. This fixes the issue, moving the SizeChanged event revoker data structure to a map, and evicting the listener for the root tag when it is removed.
> Remove previous SizeChanged event listener when reloading the app

- change/react-native-windows-7a71f7ee-8200-414f-a2a3-21c273419000.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Utils/CppWinrtLessExceptions.h
Newer versions of Clang do not support mixing C++20 and std::experimental coroutines. In such cases, we should prefer the coroutine types declared in the std:: namespace.
Wait for CI tests.
> Use std:: coroutines for compatibility with C++20 and Clang 17

- change/react-native-windows-cf526fee-a8ea-4093-a2b9-326406f5c5ac.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
See https://github.com/microsoft/cppwinrt/issues/1393
We need to first convert the WinUI 3 control to IControlProtected to access GetTemplateChild.
Compiled with WinAppSDK and cppwinrt v2.0.240111.5
> Support WinAppSDK + cppwinrt 2.240111.5

- change/react-native-windows-08dee799-0260-4d56-bdca-ad1deebab3bb.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Office's implementation of DrawingSurface has some validation that all references to the RenderTarget are released before EndDraw is called to ensure that no-one draws to the surface outside of the draw.  The AutoDrawHelper should release its ref for similar reasons.
> Release render target before calling enddraw

- change/react-native-windows-05eb8fa4-a08c-474c-8b2d-bdb4f6fc9f6e.json
- vnext/Microsoft.ReactNative/Base/FollyIncludes.h
Clang warns when case sensitivity for header names is not met. This fixes up one of those cases in FollyIncludes.h
> Clang portable header fix

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
- .ado/publish.yml
- change/react-native-windows-2054f9f3-4bfb-45c2-8c07-b7ac052b1922.json
- vnext/Microsoft.ReactNative.CppOnly.slnf
- vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
This PR adds configurations for Microsoft.ReactNative with Fabric enabled to PR, CI, and Publish builds. This change will enable the publishing of new versions of the Microsoft.ReactNative NuGet with the `-Fabric` suffix to differentiate it from the current Paper NuGet.
This replicates the setup that Desktop has, where we create and publish versions of React Native Win32 nugets with the `-Fabric` suffix to indicate those versions are using Fabric.
We want the default new arch, new app / lib experience to *not* build RNW, but instead consume it via NuGets, see #12639. In order to get that started, we'll need the 
Updated CI/PR/Publish configurations.
N/A
Verified new configurations fired off existing tests in PR.
Should this …
> Add builds and nugets for MS.RN Fabric

- .ado/jobs/desktop.yml
Enable deploying the test website on x86 CI environments.
Custom MSBuild logic causes `PlatformTarget` to yield the value `x64` for `dotnet` commands even when the solution was built for `x86`.
This causes IIS not finding the website location at `vnext\target\$(BuildPlatform)\$(BuildConfiguration)...` when `BuildPlatform` is not equal to `x64` and returning HTTP `40x` status errors.
Make IIS use a fixed value for the `BuildPlatform` in the website's location.
Temporarily enabled `x86|Release` in the pull request matrix to ensure the website works as expected.
Disabled before merging.
See https://dev.azure.com/ms/react-native-windows/_build/results?buildId=560987&view=logs&jobId=9424bcb6-bf6e-5e05-97df-1709db307089&j=9424bcb6-bf6e-5e05-97 …
> Enable test website on x86

- .ado/jobs/universal.yml
- change/react-native-windows-4d8d825f-a8b0-4648-8616-b8e262062143.json
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/ReactInstanceSettingsTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
This PR makes Microsoft.ReactNative.IntegrationTests aware of Fabric requirements to use the WinAppSDK `DispatchQueueController`. This PR also fixes both that project and Mso.UnitTests to be able to consume self-contained WinAppSDK so they can run (the tests had code but were technically never exercising it).
Finally this PR also enables a fabric config in PR to make sure we catch test failures like this in the future.
See above.
Resolves #12923 
See above.
N/A
Ran Microsoft.ReactNative.Integration tests locally.
Fixed Microsoft.ReactNative.IntegrationTests and Mso.UnitTests to run with Fabric
> Fixed Microsoft.ReactNative.IntegrationTests and Mso.UnitTests to run with Fabric

- change/react-native-windows-34318f60-875e-4332-8268-b27e579969ca.json
- vnext/src-win/Libraries/Components/View/ViewPropTypes.d.ts
We should not be using TS enums to describe the types of RN.  TS enums are not a type-level extension of JavaScript.
This export aligns how we are exporting EventPhase on windows with how we are doing it on win32
> Rework EventPhase type to avoid using TS enum

- change/react-native-windows-6ffd41f8-bf53-4629-9917-3c2349d77112.json
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.h
Recent integrations started calling TextLayoutManager::measureLines, which causes the basic Text example page to assert.
This is not a complete implementation, #12929 files as additional work needed.
> Partial implementation of TextLayoutManager::measureLines

- .ado/jobs/node-tests.yml
- .ado/stages.yml
The extra node test job was to test node 18 in preparation for moving the whole repo to node 18.  At this point we are running node 18 everywhere else so it's not testing anything new.
> Disable node-tests job for now

- change/react-native-windows-ee9ce75f-9d70-4967-b60c-2d355f0c9d8e.json
- vnext/src/Libraries/Components/View/ViewPropTypes.d.ts
> [0.73] Rework EventPhase type to avoid using TS enum

- change/react-native-windows-91e4571c-cdb6-4c4e-b7f6-d720a005abd1.json
- vnext/Microsoft.ReactNative.Cxx/AutoDraw.h
- vnext/Microsoft.ReactNative.Cxx/CompositionSwitcher.Experimental.interop.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Scripts/OfficeReact.Win32.nuspec
- Unify some DPI drawing logic, which also helps integrate with Office's compositor
- Fix issue where you cannot type in TextInput until switching to another window and back
- Fix issue where tiled images would not draw at the correct size
- Using the mouse scroll wheel on an inner ScrollView would not scroll outer ScrollViews once inner ScrollView reached limit
- KeyUp events in a TextInput would trigger KeyDown events
- TextInput maxLength property was not implemented
- Pressing END in a TextInput would scroll an outer scroll view, when it should just move the cursor within the TextInput
> Unify some DPI drawing logic

- .ado/jobs/e2e-test.yml
The Fabric e2e tests are failing intermittently requiring re-runs to unblock PRs. #12983 will track making the job more stable. In the meantime, reducing the timeout to 35 min to expedite re-runs (the job usually takes 20-25min).
> Change Fabric e2etest timeout from 60 to 35m

- change/@office-iss-react-native-win32-6b1b9c92-50ad-4985-89ba-4f2505aa825c.json
- change/react-native-windows-3701d914-c1cc-48f7-b2ad-e84229318968.json
- packages/@office-iss/react-native-win32/src-win/Libraries/ReactNative/PaperUIManager.win32.js
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Utils/KeyboardUtils.cpp
- vnext/Microsoft.ReactNative/Utils/KeyboardUtils.h
> [0.74] Dont use CoreWindow to determine key state

- change/@office-iss-react-native-win32-6b1b9c92-50ad-4985-89ba-4f2505aa825c.json
- change/react-native-windows-3701d914-c1cc-48f7-b2ad-e84229318968.json
- packages/@office-iss/react-native-win32/src-win/Libraries/ReactNative/PaperUIManager.win32.js
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Utils/KeyboardUtils.cpp
- vnext/Microsoft.ReactNative/Utils/KeyboardUtils.h
- Some of the key handling code was using CoreWindow to determine the key state of left control vs right control.  Rework to use the Islands KeybaordInputSource.
- Fix Win32's PaperUIManger
- Export YGConfigSetErrata method from react-native-win32.dll
- Export QuirkSettings activation factory from react-native-win32.dll
> Dont use CoreWindow to determine key state

- packages/@rnw-scripts/beachball-config/package.json
- packages/@rnw-scripts/beachball-config/src/beachball.config.ts
- yarn.lock
Another CodeQL fix #12704 
`packages/@rnw-scripts/beachball-config/lib-commonjs/beachball.config.js:26:47`
https://codeql.github.com/codeql-query-help/javascript/js-shell-command-constructed-from-input/
> [CodeQL] Unsafe shell command constructed from library input

- change/react-native-windows-b9725ce8-aa24-4cc7-bb58-901190465ffc.json
- vnext/Microsoft.ReactNative.Cxx/AutoDraw.h
This ensures that drawing code is not able to access the D2D device context outside of a BeginDraw/EndDraw pair.
Office internal code enforces that all references to the device context must be released before EndDraw is called.
> Ensure D2D device context is not used outside Begin/End draw

- change/@office-iss-react-native-win32-3df907f2-8166-40fe-840d-a260eed0fd3e.json
- packages/@office-iss/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js
This is a port of a fix already in 0.74 and main.
The PaperUIManger fails with newer native versions of TurboModule code. - This make some prototype work against newer versions of fabric harder.  This JS change is compatible with both matching and newer native bits.
> [0.73] [NetUI] Fix issue using Paper UI manager with newer turbomodule

- change/react-native-windows-73af8adf-3550-45d3-baed-c5e49c135395.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
We were leaking the CompositionRootView and CompositionEventHandler as they both had strong refs on eachother, which was keeping a bunch of objects alive.
> Fix a reference cycle between CompositionRootView and CompositionEventHandler

- .ado/jobs/e2e-test.yml
#12984 changed the Fabric e2etest job timeout from 60min to 35min to allow for faster re-runs when the e2etask got in a bad state that took up the entire 60 min. 35min is fine if the e2etest task succeeds, but if it fails for a legitimate reason, then the job doesn't have enough time to upload the new snapshots.
This change moves the timeout from the job to the task. 
> Add timeout to Fabric e2etest task instead of entire job

- change/react-native-platform-override-aa0ae023-d4d6-436c-bb36-9fa78bbed9af.json
- packages/react-native-platform-override/src/Hash.ts
While SHA-1 is a weak hash algorithm, we're not using it in any kind of encryption manner that would leave data vulnerable if decrypted. We use it as a convenience to map file/directory names that have been forked from upstream and get logged in overrides.json files to be used during our manual integration process. 
#12704 
> [CodeQL] Resolve "Weak hashes" alert

- change/react-native-windows-55134846-d638-4b46-8190-55b23cf11c3d.json
- change/react-native-windows-73af8adf-3550-45d3-baed-c5e49c135395.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/CompositionRootView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Theme.idl
Port #13013 and #13163 to 0.74
> [0.74] Fix reference cycle between CompositionRootView and CompositionEventHandler

- .vscode/settings.json
- change/react-native-windows-f607455e-1870-4fd5-81f5-94717effb241.json
- vnext/Directory.Build.props
- vnext/PropertySheets/Warnings.props
- vnext/fmt/cgmanifest.json
This PR backports #12411 to 0.71.
* update fmt to 10.1.0
* Change files
> [0.71] Update fmt version to 10.1.0

- change/react-native-windows-4bf9ae6c-4aa1-4e1e-a65e-29aa30067d1a.json
- vnext/templates/cpp-lib/example/metro.config.js
There's a typo in the metro.config.js file of the cpp-lib template
> [cpp-lib] Fix typo in metro.config.js

- change/react-native-windows-e43ac1c2-0b09-49f0-9509-e8af020af965.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageResponseImage.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager_emptyimpl.cpp
- vnext/Microsoft.ReactNative/Fabric/ImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.h
- vnext/Microsoft.ReactNative/UriImageManager.idl
- vnext/Shared/Shared.vcxitems
This provides hooks to allow applications to provide custom uri handers for loading images.  This can be used to integrate RN experiences with more custom image solutions.  For you could implement a handler for Uri's like `persona://userId`, which could 
load from a local image cache of user images.   Or `appicon://Play`, to load / render app icons.
This provides similar functionality to `RCTImageURLLoader` on iOS
In Office we make use of similar functionality on our internal RN implementation to render Office icons, and persona images.  This will replace that functionality in the fabric implementation.
There a new API:
`UriImageManager::AddUriImageProvider(settings.Properties(), provider);`
where provider is one of either `IUriImageStreamProvider` which allows the app to return a stream …
> [Fabric] Add ability to provide custom image uri handlers

- change/react-native-windows-ce955011-32e1-433c-af28-17d38a2d6ef2.json
- packages/@react-native-windows/tester/src/js/examples/Image/ImageExample.windows.js
- vnext/Microsoft.ReactNative.Cxx/AutoDraw.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.h
This adds support for base64 encoded images in fabric.  Also handles base64 encoded svg images separately, since wincodec doesn't support that out of the box.
Added additional tests to the Image test page.
> [Fabric] Add support for data: images

- change/@rnw-scripts-integrate-rn-26cec256-11ae-49dd-a99b-8f14f22f8e92.json
- packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
When updating the 0.74 stable branch, the integrate-rn script tried to bump some package versions to ^^0.74.0.  This was caused by core moving their dependencies to be ^ dependencies, and our script always prepending ^.
> UpgradeDependencies script should handle ^ dependencies

- README.md
Documentation only. No product changes.
Readme didn't cover some FAQs around new architecture, and was missing key links to helper repos.
- Add summary of Fabric roadmap with link to pinned issue
- Move Requirements section to be a subsection of "Getting Started"
- Move "Documentation" before "Contributing"
- Flesh out "Examples" section with missing samples repo and gallery repo references
- Tighten up various language
> Update readme with some mention of new architecture

- change/react-native-windows-bcdac51c-fc92-4116-9f26-94a1ffdc0071.json
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/Shared.vcxitems.filters
Changes Hermes package version to 0.1.21
Cherry pick #13207 
The new Hermes version 0.1.21 matches to the code used by RN version 0.74.1:
- Catch up with Hermes changes done in the previous 9 months.
- Fix the debugger experience for 0.74, 0.73, 0.72, and 0.71 by enabling debug info in the JS byte code when the direct debugging is enabled for a RN instance.
> [0.73] Change Hermes package version to 0.1.21 (#13207) 

- change/react-native-windows-30013505-dc60-4d9a-aa8e-83051db839fe.json
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/HermesRuntimeHolder.cpp
Changes Hermes package version to 0.1.21
Cherry pick #13207 
The new Hermes version 0.1.21 matches to the code used by RN version 0.74.1:
- Catch up with Hermes changes done in the previous 9 months.
- Fix the debugger experience for 0.74, 0.73, 0.72, and 0.71 by enabling debug info in the JS byte code when the direct debugging is enabled for a RN instance.
> [0.74] Change Hermes package version to 0.1.21 (#13207)

- change/react-native-windows-2976e0bc-5fc3-4c0a-aa79-12b3577aaff6.json
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/HermesRuntimeHolder.cpp
Changes Hermes package version to 0.1.21
The new Hermes version 0.1.21 matches to the code used by RN version 0.74.1:
- Catch up with Hermes changes done in the previous 9 months.
- Fix the debugger experience for 0.74, 0.73, 0.72, and 0.71 by enabling debug info in the JS byte code when the direct debugging is enabled for a RN instance.
Note that the debugging story is still broken in main. It is going to be addressed in the next version.
>  Change Hermes package version to 0.1.21

- change/react-native-windows-c908b5fb-05b3-4467-b516-200173e732f1.json
- vnext/Scripts/rnw-dependencies.ps1
Started seeing this after a sync to main:
I ran rnw-dependencies.ps1 and noticed it was passing because it only checks that your Node version is >= 18 even though it installs 18.18. 
Updating script to check for 18.18
> Update rnw-dependencies script to check for the correct Node version

- change/react-native-windows-3f992801-4f60-495b-a7e5-9af34020b8f0.json
- vnext/PropertySheets/JSEngine.props
Changes Hermes package version to 0.1.21
Cherry pick #13207 
The new Hermes version 0.1.21 matches to the code used by RN version 0.74.1:
- Catch up with Hermes changes done in the previous 9 months.
- Fix the debugger experience for 0.74, 0.73, 0.72, and 0.71 by enabling debug info in the JS byte code when the direct debugging is enabled for a RN instance.
> [0.71] Change Hermes package version to 0.1.21 (#13207) 

- change/react-native-windows-3f811585-510f-4097-972b-2aa34b14cb56.json
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/playground/windows/playground-composition/CustomComponent.idl
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
Backport #13203 
Expose CompositionContext from CreateCompositionComponentViewArgs
> [0.74] [Fabric] Fix experimental winui3 builds

- change/react-native-windows-4d35cfde-27d7-409c-903e-1e2bec97cb74.json
- vnext/src-win/Libraries/Components/View/View.windows.js
When passing null to the children prop of a view that uses `importantForAccessibility="no-hide-descendents"`, React Native Windows JS code wil crash due to the assumption that in this case, the children must be nonnull. React allows null and undefined on the type `ReactNode`, which is the go to type for declaring the type for the children prop on a component.
This is most likely a rare combination of props, though it is still valid. React.Children.map() has the following type:
`map<T, C>(children: C | readonly C[], fn: (child: C, index: number) => T): C extends null | undefined ? C : Exclude<T, boolean | null | undefined>[];`
The fix proposed is to check for null or undefined before using React.Children.map().
This fixes a crash that my …
> Fixing crash when passing null children to view with no-hide-descendents

- change/react-native-windows-b579c25f-abaa-486e-920f-64f3216eaba7.json
- vnext/Desktop/module.g.cpp
> ViewComponentView should be activatable from rn-win32.dll

- change/@office-iss-react-native-win32-22bcae82-8c54-41e1-88f1-6aeb9deafbe3.json
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/.flowconfig
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/NativeAccessibilityInfoWin32.js
Backport of #12237. 
This change was committed to the main branch around the time the 0.73-stable branch was created so we missed back porting it to 0.73
Adds support for [announceForAccessibilityWithOptions](https://reactnative.dev/docs/0.71/accessibilityinfo#announceforaccessibilitywithoptions) on win32 to enable developers to specify which react native component to send the announcement from using its nativeID.
> [0.73] Add support for announceForAccessibilityWithOptions

- .ado/jobs/e2e-test.yml
#13166 added a timeout to the e2etest run since it can hang forever, but if the task fails and it tries to update the snapshots, that tasks can hang too. 
> Add timeout to Fabric e2etest snapshot update task

- change/react-native-windows-8549cb15-fcb5-48e9-b8bf-8d6e2ae1d896.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/ComponentView.idl
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/FocusManager.idl
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/Shared/Shared.vcxitems
Adding native APIs to support implementation of FURN's FocusTrapZone. And generally expand native focus capabilities.
New static FocusManager runtimeclass::
```
static ComponentView FocusManager.FindFirstFocusableElement(ComponentView searchScope);
static ComponentView FocusManager.FindLastFocusableElement(ComponentView searchScope);
```
New events on ComponentView:
```
event Windows.Foundation.EventHandler<LosingFocusEventArgs> LosingFocus;
event Windows.Foundation.EventHandler<GettingFocusEventArgs> GettingFocus;
event Windows.Foundation.EventHandler<Microsoft.ReactNative.Composition.Input.RoutedEventArgs> LostFocus;
event Windows.Foundation.EventHandler<Microsoft.ReactNative.Composition.Input.RoutedEventArgs> GotFocus;
```
New method on ComponentView:
```
bool TryFocus();
```
> [Fabric] Add various native focus APIs

- change/@office-iss-react-native-win32-2f3250d9-6d3a-44a7-bf44-ad79a1ab1fbc.json
- packages/@office-iss/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js
Fix fallout from #13009.
Basically, trying to get the UIManager to work with both a 0,74 and a 0.73 dll for internal work.  Previous PR made it work with 0.74 dll, but broke it when using a 0.73 dll.
> [0.73] [Win32] Fix PaperUIManager

- .cspell.json
- change/@office-iss-react-native-win32-c19d617e-ea40-47f8-8b84-e955cb6aa24c.json
- change/react-native-windows-c0a19313-151e-4923-99a9-6de723d37dbe.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src-win/Libraries/Core/Devtools/loadBundleFromServer.win32.js
- vnext/Folly/TEMP_UntilFollyUpdate/ConstexprMath.h
- vnext/fmt/TEMP_UntilFmtUpdate/core.h
- vnext/fmt/fmt.vcxproj
- vnext/overrides.json
- vnext/src-win/Libraries/Core/Devtools/loadBundleFromServer.windows.js
Patching fmt CodeQL issues until upstream fix is published and we can consume it. #12702, #12703, #12704
Fmt, folly, and upstream patches
We don't know when fmt will publish next.
Fixed fmt patching. Forked fmt/core.h, folly/ConstexprMath.h and loadBundleFromServer.js with fixes. 
Confirmed node_modules fmt core.h version gets overwritten by the one in TEMP_UntilFollyUpdate on build
> [CodeQL] Patch fmt/core.h, folly/ConstexprMath.h, and loadBundleFromServer.js

- packages/sample-app-fabric/windows/SampleAppFabric/SampleAppFabric.cpp
Due to recent changes on arrange APIs: https://github.com/microsoft/react-native-windows/pull/13269 the sample-app-fabric needs to be adjusted.
no
> Fix build error for sample-app-fabric

- change/react-native-windows-f33cdf8f-4643-430c-8acb-2f41336cca25.json
- vnext/Microsoft.ReactNative/AsynchronousEventBeat.cpp
There is a race condition where on a subsequent `AsynchronousEventBeat::request` call, first it will query `isRequested_`, which is true from the previous run.  Then on a separate thread `AsynchronousEventBeat::induce` runs and sets `isRequested_` to false.
Back on the first thread we call into `EventBeat::request` which would set `isRequested_` back to true, but because we separately queried the value of `isRequested_` back when it was true, the call to `induce` is not run, and `isRequested_` remains stuck true forever, and `induce` is never run again.
But switching to `bool alreadyRequested = isRequested_.exchange(true);` we ensure that this race condition can never happen.
This was semi regularly causing the app to become unresponsive in the playground/E2E apps for me.  It probably …
> AsynchronousEventBeat can get locked where it will not beat anymore

- change/react-native-windows-c33514c0-2412-40ff-b4ad-4739c95260e7.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
- vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UriImageManager.h
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.h
- vnext/Microsoft.ReactNative/HttpSettings.idl
- vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp
- vnext/Microsoft.ReactNative/UriImageManager.idl
- vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp
- vnext/Microsoft.ReactNative/Utils/ImageUtils.h
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
- vnext/Shared/Modules/FileReaderModule.cpp
- vnext/Shared/Modules/WebSocketModule.cpp
- vnext/Shared/Networking/DefaultBlobResource.cpp
- vnext/Shared/Networking/NetworkPropertyIds.cpp
- vnext/Shared/Networking/NetworkPropertyIds.h
- vnext/Shared/Networking/RedirectHttpFilter.cpp
- vnext/Shared/Networking/RedirectHttpFilter.h
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/Networking/WinRTHttpResource.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Port of #13285 to 0.74
Some slight modifications to the original PR to deal with the fact that in 0.74 the fabric code didn't include the ImageErrorInfo struct, or report those errors to JS.
I basically replaced the uses of ImageErrorInfo with a std::string. -- It is not passed to JS in 0.74.
> [0.74] [Fabric] Support blob: images

- change/react-native-windows-19b2b7f6-5882-42a5-8aee-a661b0c11fd2.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Fix incorrect input mapping when forwarding input to richedit.
> [Fabric] Touch pointer moved was being reported to richedit as a pointerup

- change/react-native-windows-919ad7d0-e30c-4007-809b-0156fdf5f7db.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/packages.lock.json
- vnext/ReactCommon.UnitTests/packages.lock.json
Remove OpenSSL NuGet dependency from Desktop LIB and DLL projects.
Package `ReactWindows.OpenSSL.StdCall.Static` is not used anymore by the Desktop DLL.
Remove package reference `ReactWindows.OpenSSL.StdCall.Static` for React.Windows.Desktop and `React.Windows.Desktop.DLL`.
> Remove OpenSSL from Desktop LIB and DLL

- Directory.Build.targets
- change/react-native-windows-c0453516-9b94-4cbc-8aeb-b6ae47ac22ba.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/ExperimentalFeatures.props
Upgrades Windows SDK for Desktop projects to version `10.0.22621.0`.
Building the Desktop DLL on ARM64EC requires a minimum Windows SDK version of `10.0.22000.0`.
Note, version `10.0.22621.0` is now installed by default with the UWP workflow so using it instead of `10.0.22000.0` reduces the number of SDK dependencies installed in the developer machine.
Note, this change is not plainly backported from `main` to reduce impact on consumers of a stable branch.\
At the same time, main consumers of `react-native-win32.dll` currently need to stick with `0.74-stable` **and** they also need `ARM64EC` support.
- Set WinSDK version to `10.0.22621.0` when The `$(SolutionName)` MSBuild variable is set to `ReactWindows-Desktop`.
- Set WinSDK version …
> [0.74] Upgrade Desktop solution/projects to Win SDK 10.0.22621.0

- change/@react-native-windows-cli-5ac25fa2-32bd-477c-a499-01c579f6cd37.json
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- packages/@react-native-windows/cli/src/utils/vsInstalls.ts
Fixes a bug in `run-windows` where we truncate the minimum VS version number so it only allows for one digit minor versions.
We try to detect when building inside a VS command prompt by looking for the `VisualStudioVersion` environment variable. In this way we can make sure to use specific (usually prerelease/preview) versions of VS.
However, we can also set this env variable manually, which I was trying to do. However, there are lots of other places in VS that read this value, and it always expects a major version with a 0 minor version (i.e. `17.0`, `18.0`). When setting `17.11`, (the version I'm trying to test for has fixes to #13339) the code was truncating it to `17.1`. Even fixing the truncation meant that the build would later fail anyway, since it wasn't a  `X.0` number.
So this …
> Added `MinimumVisualStudioVersion` env variable to force `run-windows` to use a particular version of VS installed

- change/react-native-windows-e1112cd5-a192-4668-87a1-f31ef842c4c3.json
- vnext/Scripts/rnw-dependencies.ps1
New installations of Windows 11 come with a version of WinGet that is broken/unable to install dependencies. See https://github.com/microsoft/winget-cli/issues/3832#issuecomment-1872387214 for more information on the issue. 
Resolves #13336
Adjusted the rnw dependencies script to check the version of WinGet installed and make sure it is at least 1.7.11261. If the no version is installed or the version installed is below this version, we should update/install WinGet. Then we can proceed with the rest of the script. 
While working on this bug I also ran into another break in the script. Following script fix in #13211, having Node 20 installed caused the script to incorrectly fail and claim the version on Node installed was not valid. …
> Fix RNW Dependencies Command to Check for Valid WinGet Version

- change/react-native-windows-61ff82f5-fbd8-4104-848d-d56a99f21642.json
- packages/sample-app-fabric/windows/SampleAppFabric.sln
- vnext/Microsoft.ReactNative/packages.lock.json
- Bug fix
Shared.vcxitems is unable to load when SampleAppFabric.sln is launched in Visual Studio.
Resolves #13384 
Update the path in SampleAppFabric.sln
no_
> Fix load failed error for Shared.vcxitems in sample-app-fabric

- change/@react-native-windows-cli-c8cf5aba-fcbc-427e-ab3c-29511f9ab8e9.json
- packages/@react-native-windows/cli/README.md
- packages/@react-native-windows/cli/src/commands/autolinkWindows/autolinkWindows.ts
- packages/@react-native-windows/cli/src/commands/autolinkWindows/autolinkWindowsOptions.ts
- packages/@react-native-windows/cli/src/commands/codegenWindows/codegenWindows.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/commands/runWindows/runWindowsOptions.ts
This PR fixes some typos in the help for RNW CLI commands.
To clarify the CLI command options.
See above.
N/A
Nothing functional was changed.
Fixed typos and improved uniformity of RNW CLI command help text
> Fixed typos and improved uniformity of RNW CLI command help text

- change/react-native-windows-ff4b6ade-2375-4c5c-9c89-b95627166c7b.json
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/algorithm/CalculateLayout.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/config/Config.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/config/Config.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/node/LayoutResults.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/node/LayoutResults.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/node/Node.cpp
- vnext/overrides.json
Currently yoga does not correctly dirty its layout when there is a scale change.  
https://github.com/facebook/yoga/pull/1674 should fix this.  Applying this change for now until we can integrate the fix from upstream.
> [Fabric] Patch yoga to include changes to correctly recalculate layout on scale change

- .ado/templates/react-native-init-windows.yml
Backport https://github.com/microsoft/react-native-windows/pull/13346/commits/7a1577c2b9d473f0e67c97a085cd5a2aa5edf793
Unblock Fabric CLI checks on CI
Change `create-react-native-library` version used in init command part of CLI check.
N/A
N/A
No
> [0.74] Change create-react-native-library version to allow Fabric CLI tests to pass

- .ado/templates/react-native-init-windows.yml
Change version of create-react-native-library to stable version to unblock CI.
Unblock Fabric CLI checks on CI
Change create-react-native-library version used in init command part of CLI check.
N/A
N/A
No
> Change create-react-native-library version to allow Fabric CLI tests to pass

- .ado/templates/react-native-init-windows.yml
create-react-native-library released new unbroken versions! In the new version they also took in this commit: https://github.com/callstack/react-native-builder-bob/pull/572 that adds a new flag we need to set
Resolves #13414
no
> Use latest for create-react-native-library

- change/react-native-windows-0e7a6537-e72d-4a1b-a499-cdbcc09561fb.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
When changing border radius from non-zero to zero the clipping path and relative size adjustment do not get reset to null / 0, causing an incorrect border render.
> [Fabric] Handle changes to BorderRadius

- change/react-native-windows-759b1fea-b751-4ff5-8448-61302a4756e5.json
- vnext/Desktop/module.g.cpp
Runtime classes annoyingly currently need to be manually added to this file to be properly exported to rn-win32.
Add some missing ones.
> [Fabric] [Win32] Add image response APIs to win32 exports

- change/react-native-windows-57c6b08e-a6a6-4d04-a58f-b79dd5b9afcc.json
- vnext/Microsoft.ReactNative/Composition.Input.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Prefer WinAppSDK types in RNW input types:
`Windows.UI.Core.CorePhysicalKeyStatus` -> `Microsoft.UI.Input.VirtualKeyStates`
Also go through our usage of CorePhysicalKeyStatus which is often used to check if a key is down and fix the tests to account for the Locked state, which is currently causing many of our keyboard shortcuts to only work half the time.
> [Fabric] Move to WinAppSDK types for KeyStatus, and ensure usages account for locked flag

- change/react-native-windows-addbcde3-c802-4b1b-b6e6-970118e11819.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/packages.lock.json
Setting the scrollEnabled attribute is not taking any effect on the scrollview visual in fabric.
Resolves #12717 
1. Check for scrollEnabled status before updating the scroll to position.
2. Toggle visualInteractionSourceRedirectionMode based on the scrollEnabled status.
Yes
> Use scrollEnabled flag to enable/disable the ScrollView

- change/react-native-windows-d68e4c7a-72b0-4475-8aea-5b88fa568ee6.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
`ImageComponentView`'s currently have a reference cycle with the `WindowsImageResponseObserver` which caused leaks of every `ImageComponentView`.
This makes the `WindowsImageResponseObserver` have a weak ref to resolve the cycle.
Added some debug code to detect leaks of ComponentView's.  This debug code maybe to too aggressive - we'll see.
-- left the leak detection code #ifdef'd out for now.
> [Fabric] Fix image component reference cycle

- change/react-native-windows-24c5a09a-7492-4f70-9a80-a82c358fb058.json
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
`scheduler.reportMount` call will call into any `UIManagerMountHook` that has been registered with the `UIManager`.  This will include `IntersectionObserver` in the future.  This aligns with code in core version of `didMountComponentsWithRootTag`.  
This also provides a notification to the `ReactNotificationService` at the same time which can be used to track rootview mounts for performance analysis etc.
> [Fabric] call reportMount to implement UIManagerMountHook support

- .ado/jobs/desktop.yml
Temporarily increase the timeout of the Desktop jobs to avoid manual re-runs. 
no
> Increase Desktop job timeouts due to #13442

- change/react-native-windows-b3194f0e-3be5-42d3-a9d7-418966736ad0.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- 
As of today, a simple transformation of a visual using transform prop below is not taking any effect because the parameters are not being used.
transform: [
{ scaleX: 1 },
{ rotate: '45deg' }
],
Resolves #12204
Use resolvetransform method to create a transform matrix of all operations and send it to animation.
After resolvetransform:
{rotate: -45deg}
{rotate: 45deg}
{scale: 2}, {rotate: 45deg}
{scale: 2}, {rotate: 45deg}, {translateX: -10}
yes
> Resolve Transform Matrix before Animation

- change/react-native-windows-24c5a09a-7492-4f70-9a80-a82c358fb058.json
- change/react-native-windows-57c6b08e-a6a6-4d04-a58f-b79dd5b9afcc.json
- change/react-native-windows-63f67386-8c58-4d24-88c1-84e80443b8d4.json
- change/react-native-windows-addbcde3-c802-4b1b-b6e6-970118e11819.json
- change/react-native-windows-b3194f0e-3be5-42d3-a9d7-418966736ad0.json
- change/react-native-windows-d68e4c7a-72b0-4475-8aea-5b88fa568ee6.json
- vnext/Microsoft.ReactNative/Composition.Input.idl
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/src-win/Libraries/Text/Text.windows.js
Port these PRs to 0.74
#13435 
#13427 
#13440 
#13443 
#13450 
#13445
> [0.74] [Fabric] Port various fabric fixes

- change/react-native-windows-57ec7c25-bda3-4d67-92a7-18b67b31fbd0.json
- vnext/Shared/Modules/WebSocketModule.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
There are two bugs at play. This fixes both bugs, allowing headers to be properly used with web socket requests.
Bug #1
In `Libraries/WebSocket/WebSocket.js`, the expected type for `headers` is an object. This is passed down as-is to the native layer in the call `NativeWebSocketModule.connect(url, protocols, {headers}, this._socketId);`. The turbo module implementation attempts to iterative over this box type by using `.AsArray()`, which immediately continues past the for-loop. The result is that any headers passed down from Javascript are ignored.
Bug #2
React Native WebSocket implementations do not put a port on the Origin header when a port is not provided. RNW does, which results in adding a port of 0 to every default Origin header. …
> Updating native WebSocket header logic to match RN

- change/react-native-windows-init-df92456d-ba5e-4a0a-aa54-bf2373b4c9d9.json
- packages/react-native-windows-init/src/Cli.ts
This PR adds version checking to `react-native-windows-init` to give a deprecation warning if the user tries to use it for RNW 0.75 and an error if they use it on a newer version.
We will be deprecating `react-native-windows-init` in favor of newer methods for adding RNW projects.
Resolves #13461
See above.
N/A
Verified I could se the warning/error when using it with 
Add warnings and deprecations for react-native-windows-init
> Add warnings and deprecations for react-native-windows-init

- change/react-native-windows-04d234ac-4d36-4621-aa06-dbc4b67a5e0a.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/PropertySheets/JSEngine.props
Have ARM64EC react-native-win32.dll consume ARM64EC Hermes.
Loading x64 dependencies on ARM64EC processes has a performance overhead.
Stop overriding the `HermesPlatform` MSBuild property when building under ARM64EC.
Hermes should now provide a native ARM64EC variant.
> Don't override Hermes platform for ARM64EC

- .github/ISSUE_TEMPLATE/integration-follow-up.yaml
Adds a new issue template
Integration follow-up issues can be hard to hand-off to the next person. This insures every issue has the right information so we don't have to dig through our repository for when a file is fork or what PR upstream broke us.
Resolves #13337
New issue template
Is there a way to see this change locally? 🤔
no
> Add new issue template for integrations

- change/react-native-windows-bdd93326-988c-4313-b50d-26ae62117088.json
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
On Android and iOS, the `appearanceChanged` global event has an object payload where the updated dark/light string value is nested as a property. On Windows, the color scheme string was the payload.
This makes Windows consistent with iOS and Android.
Fixes the native event payload on Windows for the appearanceChanged event.
> Make appearanceChanged event consistent with Android/iOS

- .ado/templates/react-native-init-windows.yml
create-react-native-library deleted the java-objc template. Doesn't matter which one we use since we're only building windows, so updating it to use kotlin-objc. 
https://github.com/callstack/react-native-builder-bob/pull/601
Changed cli job from `java-objc` to `kotlin-objc`
CI
> Fix Fabric cli CI jobs

- .ado/templates/write-certificate.yml
SFI
Generate the self-signed certs for testing programmatically on the fly, rather than use a fixed one.
no
> Create self-signed certificates programatically rather than from keyvault

- change/react-native-windows-3ffe8770-fba2-4468-a7a7-63d1d7257102.json
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
Opening Alerts and Flyouts crashes on Windows 10 1809 
Resolves #13502
Adds more version checks around uses of XamlRoot, which was added in the next version 19H1. There were a few uses of `is19H1OrHigher`, but not all XamlRoot related code was wrapped.
Fix alerts and flyouts crashing on Windows 10 1809
> Fix Alerts and Flyouts crashing on Windows 10 1809 (RS5)

- change/react-native-windows-47a010c1-a124-470a-8d55-8350642cbff5.json
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.h
- vnext/Microsoft.ReactNative/Fabric/AbiViewShadowNode.cpp
There is a reference cycle between the internal facebook::react::ShadowNode objects and the ABI wrapper.
This replaces the wrappers back ref with a weak_ref, allowing the ShadowNode to be properly released.
> [Fabric] Custom ShadowNodes are never released

- change/react-native-windows-6a82bdc7-fdc0-4d57-bd42-cb297ef7a7ea.json
- vnext/Microsoft.ReactNative/Modules/SampleTurboModule.cpp
- vnext/Microsoft.ReactNative/Modules/SampleTurboModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/TurboModuleManager.cpp
This PR provides a proper implementation of the `SampleTurboModule` module and removes the proxy code in `TurboModuleManager` which instead substituted the old `SampleTurboCxxModule` module.
The APIs of `SampleTurboModule` are starting to deviate from the older `SampleTurboCxxModule`, specifically the addition of new `EventEmitter` members. So it's time we had a "real" implementation of `SampleTurboModule`.
Closes #13531 
See above.
N/A
Verified tests still pass and the new module is being called.
Implement the SampleTurboModule module
> Implement the SampleTurboModule module

- .ado/jobs/playground.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/write-certificate.yml
Previous PR to update CI did not fully work
Thread through the password to the generated certificate and put quotes on the path as that fails in ADO...
Been running CI off a branch ...
> Fix Password passing and path for certs

- change/react-native-windows-3d101ac1-0870-46cc-83de-a30613a5ec98.json
- vnext/Common/Utilities.cpp
> [0.72] Backport CodeQL fix

- change/react-native-windows-0cadc988-653c-4c05-9b8a-4c70eb762be8.json
- vnext/Common/Utilities.cpp
> [0.73] Backport CodeQL fix 

- change/@react-native-windows-codegen-ae4b2a67-9881-42db-ab82-02d7d2374e43.json
- change/react-native-windows-69671805-a682-4e35-8999-c68f20b14b74.json
- packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
- packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
- packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
- packages/@react-native-windows/tester/src/js/examples/TurboModule/SampleTurboModuleExample.windows.js
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.cpp
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
- vnext/Microsoft.ReactNative/IReactModuleBuilder.h
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/Modules/SampleTurboModule.cpp
- vnext/Microsoft.ReactNative/Modules/SampleTurboModule.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/codegen/NativeSampleTurboModuleSpec.g.h
In a recent integration RN core added support for module specs to have `EventEmitters`.  This modifies our REACT_EVENT macro to use the new EventEmitters.  These new EventEmitters work slightly differently than our previous REACT_EVENT macro, and only work on TurboModules. To avoid making the new behavior a breaking change, we will only use the new behavior when the module uses a new REACT_TURBO_MODULE macro instead of REACT_MODULE.  This allows us to also modify the behavior of AddAttributedModules to always register those modules as TurboModules rather than NativeModules.  Which provides a more incremental way of adopting TurboModules than the previous change of a bool param on AddAttributedModules which made all the attributed modules TurboModules.
I also updated the codegen to …
> Add support for turbomodule eventemitters, and codegen

- change/react-native-windows-bc48bd5b-3e22-40db-8384-1b2da3d2d09f.json
- vnext/Microsoft.ReactNative/Modules/StatusBarManager.h
The empty implementation of StatusBarManager here does not run when web debugging, as empty modules are ignored by the web debugging runtime.  This causes a StatusBarManager is missing error when web debugging, which causes the instance to not load.
This will fix #13550 when ported to 0.75
> Enforce StatusBarManger module aligns with Spec

- .ado/image/rnw-img-vs2022-node18.json
- .ado/image/rnw-img-vs2022.json
- .ado/templates/react-native-init-windows.yml
- .ado/windows-vs-pr.yml
- change/@react-native-windows-cli-43e4c71b-04c9-455c-a70d-68bf8968074c.json
- change/react-native-windows-5db66c4d-8de8-4f82-8f09-7feba85c9359.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Scripts/rnw-dependencies.ps1
> Bump minimum VS version to 17.11.0

- .ado/image/rnw-img-vs2022-node18.json
- .ado/image/rnw-img-vs2022.json
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-43e4c71b-04c9-455c-a70d-68bf8968074c.json
- change/react-native-windows-5db66c4d-8de8-4f82-8f09-7feba85c9359.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Scripts/rnw-dependencies.ps1
This PR backports #13455 to 0.75.
Resolves #13374
N/A
> [0.75] Bump minimum VS version to 17.11.0

- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-43e4c71b-04c9-455c-a70d-68bf8968074c.json
- change/react-native-windows-5db66c4d-8de8-4f82-8f09-7feba85c9359.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- packages/@react-native-windows/cli/src/utils/vsInstalls.ts
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Scripts/rnw-dependencies.ps1
This PR backports #13455 to 0.73.
Resolves #13374
N/A
> [0.73] Bump minimum VS version to 17.11.0

- .ado/jobs/desktop.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-43e4c71b-04c9-455c-a70d-68bf8968074c.json
- change/react-native-windows-5db66c4d-8de8-4f82-8f09-7feba85c9359.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Scripts/rnw-dependencies.ps1
This PR backports #13455 to 0.74.
Resolves #13374
N/A
> [0.74] Bump minimum VS version to 17.11.0

- change/react-native-windows-d20c9a86-3c19-4809-aa40-876e3cb7a227.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/Directory.Build.props
- vnext/IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.lock.json
- vnext/ReactCommon/cgmanifest.json
- Update V8-JSI to version 0.71.18
- Update Hermes to version 0.1.27
- Update node-api-jsi to commit  https://github.com/microsoft/node-api-jsi/commit/6506206ee0519da5ab688f6725cfa46441fd8650
 
New versions of V8 has update Node-API version.
New JSI for Node-API reduces memory use.
New Hermes matches to latest changes to JSI and JSI for Node-API.
Only version changes.
> [0.73] Update V8, Hermes, JSI for Node-API versions

- change/react-native-windows-101f1acf-48a6-423a-bad9-80f3fce53796.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.vcxproj
- packages/playground/windows/playground-composition.Package/packages.lock.json
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-composition/Playground-Composition.vcxproj
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- packages/sample-app-fabric/windows/SampleAppFabric/SampleAppFabric.vcxproj
- vnext/templates/cpp-app/windows/MyApp/MyApp.cpp
- vnext/templates/cpp-app/windows/MyApp/MyApp.vcxproj
- vnext/templates/cpp-lib/windows/MyLib/MyLib.vcxproj
WarningLevel is inconsistent across the repo's apps and templates with some using Level4 and others Level3. Setting all of them to Level4. 
CI
> Align <WarningLevel> across apps/templates

- change/react-native-windows-061e13a1-aed7-4c50-b382-f49b0863935b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
Running inspect.exe, or likely a bunch of other accessibility tools causes RNW experiences to crash.
A bad iterator over the children collection would attempt to dereference the end iterator, which throws.
> [Fabric] Fix crash when running inspect

- change/@react-native-windows-cli-a75b6b30-1183-4809-897d-c75d392266ff.json
- change/react-native-windows-0fa120f4-714e-467c-85a9-f1d2acd5b594.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/template/cpp-app/proj/MyApp.sln
- vnext/template/cpp-lib/proj/MyLib.sln
- vnext/template/cs-app/proj/MyApp.sln
- vnext/template/cs-lib/proj/MyLib.sln
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-app/windows/MyApp.sln
- vnext/templates/cpp-lib/template.config.js
- vnext/templates/cpp-lib/windows/MyLib.sln
- vnext/templates/old/generateWrapper.js
Visual Studio solution files cannot use variables in paths to the various project files, and up until now the paths to RNW projects assumed a simple app repo, and were hardcoded to `..\node_modules\react-native-windows\`.
This PR changes the templates for both new and old architecture projects to instead inject the calculated actual path to the RNW package.
**Note:** Node does not "see" symlinks, only their resolved path. So if you're getting RNW via a symlink (say through yarn link) the sln file will hardcode the resolved path at the time of creation.
Some user feedback has indicated that the hardcoded paths did not work for monorepos which may have multiple packages …
> Update templates to calculate rnwPath for *.sln files

- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-43e4c71b-04c9-455c-a70d-68bf8968074c.json
- change/react-native-windows-5db66c4d-8de8-4f82-8f09-7feba85c9359.json
- packages/@react-native-windows/cli/src/healthCheckList.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
- vnext/Scripts/rnw-dependencies.ps1
This PR backports #13455 to 0.72.
Resolves #13374
N/A
> [0.72] Bump minimum VS version to 17.11.0

- change/react-native-windows-dbe41975-86df-4a59-9be8-e2b51b4c50c1.json
- vnext/Desktop/Modules/DesktopTimingModule.cpp
- vnext/Desktop/Modules/DesktopTimingModule.h
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/ReactWindows-Desktop.sln
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
> [0.74] Use Turbo Modules for Desktop instead of CxxModules 

- change/react-native-windows-2a2b1b40-5859-4ef6-9dd5-b48717b71c24.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
See description in issue linked below.
Resolves [issue 13571](https://github.com/microsoft/react-native-windows/issues/13571)
Replace usage of IAppData.TemporaryFolder with GetTempPathW.
Tested change with C2R-installed version of Office client apps (high integrity level) and Centennial-installed version of Office client apps (x86, high and low integrity level).
Should this change be included in the release notes: Probably not, though I'm not sure what determines that - please advise.
> IAppData.TemporaryFolder with GetTempPathW

- change/@react-native-windows-cli-db04fef2-0cc5-477b-ac9a-1aa9f4e4c2ee.json
- change/@react-native-windows-telemetry-ca4bf582-eec5-4ee4-8830-19a6d937a87b.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/e2etest/initWindows.test.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/utils/nameHelpers.ts
- packages/@react-native-windows/telemetry/src/utils/errorUtils.ts
This PR moves all of the logic concerning validating and cleaning project names when creating new projects (via the `init-windows` CLI command or the soon to be deprecated `react-native-windows-init` command) into one shared location with unit tests. It also updates the cleaning logic to handle package scopes (i.e. `@org/package`) and better apply cleaning to packages with hyphens (i.e. `my-package`).
Going forward, when creating (new or old arch) projects with `init-windows`, the flow will still to adhere the following rules:
1. Verify that a string specified with `--name` or `--namespace` is valid, or else error out.
2. If an item isn't specified, do our best to determine the value from `package.json`, etc., and clean that value if necessary.
When using `react-native-windows-init`, …
> Improve new project name(space) validation and cleaning

- change/@react-native-windows-cli-a75b6b30-1183-4809-897d-c75d392266ff.json
- change/react-native-windows-0fa120f4-714e-467c-85a9-f1d2acd5b594.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/template/cpp-app/proj/MyApp.sln
- vnext/template/cpp-lib/proj/MyLib.sln
- vnext/template/cs-app/proj/MyApp.sln
- vnext/template/cs-lib/proj/MyLib.sln
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-app/windows/MyApp.sln
- vnext/templates/cpp-lib/template.config.js
- vnext/templates/cpp-lib/windows/MyLib.sln
- vnext/templates/old/generateWrapper.js
This PR backports #13572 to 0.75.
Visual Studio solution files cannot use variables in paths to the various project files, and up until now the paths to RNW projects assumed a simple app repo, and were hardcoded to `..\node_modules\react-native-windows\`.
This PR changes the templates for both new and old architecture projects to instead inject the calculated actual path to the RNW package.
**Note:** Node does not "see" symlinks, only their resolved path. So if you're getting RNW via a symlink (say through yarn link) the sln file will hardcode the resolved path at the time of creation.
Some user feedback has indicated that the hardcoded paths did not work for monorepos which …
> [0.75] Update templates to calculate rnwPath for *.sln files

- change/react-native-windows-1ebe3d5b-6412-4e8d-9498-191d16d1256c.json
- vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.cpp
Linking.getInitialURL should have been returning null by default.  But the spec until recently specified the return as a string so we could not return null.  I recently submitted a fix to RN to fix the spec file, so now we can return null.
This fixes a yellow box when launching RNTester.
> Linking.getInitialURL should return null by default instead of empty string

- change/@react-native-windows-cli-db04fef2-0cc5-477b-ac9a-1aa9f4e4c2ee.json
- change/@react-native-windows-telemetry-ca4bf582-eec5-4ee4-8830-19a6d937a87b.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/e2etest/initWindows.test.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/utils/nameHelpers.ts
- packages/@react-native-windows/telemetry/src/utils/errorUtils.ts
Backport PR #13566 to 0.75.
This PR moves all of the logic concerning validating and cleaning project names when creating new projects (via the `init-windows` CLI command or the soon to be deprecated `react-native-windows-init` command) into one shared location with unit tests. It also updates the cleaning logic to handle package scopes (i.e. `@org/package`) and better apply cleaning to packages with hyphens (i.e. `my-package`).
Going forward, when creating (new or old arch) projects with `init-windows`, the flow will still to adhere the following rules:
1. Verify that a string specified with `--name` or `--namespace` is valid, or else error out.
2. If an item isn't specified, do our best to determine the value from `package.json`, etc., and clean that value if necessary.
When using …
> [0.75] Improve new project name(space) validation and cleaning

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/universal.yml
- .ado/stages.yml
- .ado/templates/react-native-init-windows.yml
- change/@react-native-windows-cli-bd214a76-535b-4214-aa8d-8e67b0d17c96.json
- change/react-native-windows-ce719e54-ce74-4c70-a78a-f3c5a9576d73.json
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Package.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Package.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.PackageReferences.props
- vnext/Scripts/Microsoft.ReactNative.VersionCheck.targets
- vnext/templates/cpp-app/NuGet_Config
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-app/windows/ExperimentalFeatures.props
- vnext/templates/cpp-app/windows/MyApp.sln
- vnext/templates/cpp-lib/NuGet_Config
- vnext/templates/cpp-lib/example/NuGet_Config
- vnext/templates/cpp-lib/template.config.js
- vnext/templates/cpp-lib/windows/ExperimentalFeatures.props
- vnext/templates/cpp-lib/windows/MyLib.sln
- vnext/templates/templateUtils.js
This PR backports #13338 to 0.75.
This PR updates the `cpp-app` and `cpp-lib` new architecture templates to build against the pre-built `Microsoft.ReactNative` NuGet packages by default.
Building the `Microsoft.ReactNative` native code is very resource-intensive. Pre-building that code makes for much faster builds and greatly improved developer experience. This experience has been experimental and poorly support for Paper for some time now - for the new architecture projects we want using NuGets to be the primary experience from day one.
Resolves #12639
The `cpp-app` and `cpp-lib` new …
> [0.75] Switch New Architecture templates to use prebuilt NuGets

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/universal.yml
- .ado/stages.yml
- .ado/templates/react-native-init-windows.yml
- change/@react-native-windows-cli-bd214a76-535b-4214-aa8d-8e67b0d17c96.json
- change/react-native-windows-ce719e54-ce74-4c70-a78a-f3c5a9576d73.json
- packages/@react-native-windows/cli/src/utils/msbuildtools.ts
- vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Package.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Package.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.PackageReferences.props
- vnext/Scripts/Microsoft.ReactNative.VersionCheck.targets
- vnext/templates/cpp-app/NuGet_Config
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-app/windows/ExperimentalFeatures.props
- vnext/templates/cpp-app/windows/MyApp.sln
- vnext/templates/cpp-lib/NuGet_Config
- vnext/templates/cpp-lib/example/NuGet_Config
- vnext/templates/cpp-lib/template.config.js
- vnext/templates/cpp-lib/windows/ExperimentalFeatures.props
- vnext/templates/cpp-lib/windows/MyLib.sln
- vnext/templates/templateUtils.js
This PR backports #13338 to 0.74.
This PR updates the `cpp-app` and `cpp-lib` new architecture templates to build against the pre-built `Microsoft.ReactNative` NuGet packages by default.
Building the `Microsoft.ReactNative` native code is very resource-intensive. Pre-building that code makes for much faster builds and greatly improved developer experience. This experience has been experimental and poorly support for Paper for some time now - for the new architecture projects we want using NuGets to be the primary experience from day one.
Resolves #12639
The `cpp-app` and `cpp-lib` new …
> [0.74] Switch New Architecture templates to use prebuilt NuGets

- change/react-native-windows-d8175a4a-46c8-40d0-b42b-097f50a633c1.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-composition/Playground-Composition.rc
- packages/playground/windows/playground-composition/resource.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
ScrollViewComponentView's are currently leaking when used.  This fixes the ref cycle between the ScrollView and the ScrollBars.  I also added a new command to playground-composition to unload the instance which helps debug leak issues.
> [Fabric] Fix ScrollViewComponentView object leak

- change/react-native-windows-dd026530-5f0b-4ca5-b43e-a7a6960d7696.json
- packages/@react-native-windows/tester/src/js/examples-win/NativeComponents/CustomXamlComponentWithNativeLayoutNativeComponent.js
- packages/@react-native-windows/tester/src/js/examples-win/NativeComponents/CustomXamlComponentWithYogaLayoutNativeComponent.js
- packages/@react-native-windows/tester/src/js/examples-win/NativeComponents/NativeComponent.windows.js
- packages/@react-native-windows/tester/src/js/examples-win/NativeComponents/NativeComponentYoga.windows.js
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/playground/windows/playground-composition/CustomComponent.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiEventEmitter.h
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.h
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactViewComponentBuilder.idl
- vnext/Shared/Shared.vcxitems
Enable custom components to raise events.
Implement a public EventEmitter class, which can be used to raise events on a component.
Add a builder method to set a updateEventEmitter handler to allow access to the event emitter to custom components.
Removed some unused methods on ComponentView.
Made some trivial methods on ComponentView noexcept.
Added example usage of custom events in playground app.
> [Fabric] Enable implementation of custom events on custom components

- change/react-native-windows-5f99e270-3856-4418-8433-99c1333d8579.json
- vnext/src-win/Libraries/Components/Keyboard/KeyboardExt.tsx
- yarn.lock
Fix supportKeyboard to handle types in latest @types/react package.
> Bump @types/react from 18.3.4 to 18.3.5

- change/@react-native-windows-cli-81405bf2-50e6-426f-8c7a-81c622d5fa43.json
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/utils/build.ts
This PR fixes the two issues with `run-windows --msbuildprops`
1. When passing nothing, the command should not error and exit
2. When the string is parsed into key/value pairs, do not add empty keys to the msbuild command (which will cause msbuild to fail)
Ran into these issues while working on PR #13634, extracted them as general bug fixes here.
See above.
N/A
Verified running `run-windows` with malformed `--msbuildprops` no longer errors.
Fix parsing of empty build props in run-windows
> Fix parsing of empty build props in run-windows

- .ado/templates/msbuild-sln.yml
Fixes the task which checked for changed `packages.lock.json` files so that it actually detects changes in the files.
To get more warnings when a forced NuGet restore has changed the lock file.
Extracted from PR #13634
See above.
N/A
N/A
> Fix msbuild-sln.yml detection of changed packages.lock.json files after build

- .ado/templates/react-native-init-windows.yml
Updates the scripts used by the new templates to use the correct `react-native` dependency instead of using next and then upgrading the version to the correct one manually.
Resolves #13446 
Updated scripts to use `reactNativeDevDependency` instead of `next`.
No
> Update windows init commands to use `--version` flag for `react-native` version

- change/react-native-windows-39577653-1e51-4a5f-899b-b34e2da6d70f.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Cherry pick PR #12328
The RNW MS.RN.Cxx code fails to compile with Clang 19 in Office. The issue is already fixed in the main branch last year.
The original PR description:
Fixes "[Explicit template specialization cannot have a storage class](https://stackoverflow.com/questions/29041775/explicit-template-specialization-cannot-have-a-storage-class-member-method-spe)" in C++ 20 by moving a function outside of a struct.
> [0.73] C++ 20: Fix `Explicit template specialization cannot have a storage class` (#12328)

- .ado/templates/react-native-init-windows.yml
Changed our creation of new RN projects via the CLI to:
* Be verbose for better debugging
* Not automatically install ios pods (we don't need them)
* Not call yarn install (it fails sometimes due to yarn version mismatches, we call `yarn install` later anyway)
* No create a git repo (unnecessary for our tests)
To unblock PRs.
See above.
N/A
Verified commands worked
> Fix CLI init args to prevent non-blocking errors

- .ado/templates/msbuild-sln.yml
- change/@react-native-windows-automation-channel-cdf3494b-8b7b-408b-99bb-5475878c5315.json
- change/react-native-windows-7e8daf8e-8d48-4d74-82ae-ad9be130a75b.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- packages/e2e-test-app-fabric/windows/ExperimentalFeatures.props
- packages/e2e-test-app/windows/ExperimentalFeatures.props
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/ExperimentalFeatures.props
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/playground/windows/ExperimentalFeatures.props
- packages/playground/windows/playground-composition.Package/packages.lock.json
- packages/playground/windows/playground-composition/packages.lock.json
- packages/playground/windows/playground/packages.lock.json
- packages/sample-app-fabric/windows/SampleAppFabric.Package/packages.lock.json
- packages/sample-app-fabric/windows/SampleAppFabric/packages.lock.json
- packages/sample-apps/windows/ExperimentalFeatures.props
- packages/sample-custom-component/windows/SampleCustomComponent/packages.lock.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Directory.Build.props
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative.ComponentTests/packages.lock.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/Mso.UnitTests/packages.lock.json
- vnext/ReactCommon.UnitTests/packages.lock.json
SourceLink is needed to ensure that our NuGet packages have matching source information when symbols are resolved. So we have an `EnableSourceLink` property which tells some of our projects to add source link, and we enable that when doing CI/PR/official builds by setting the property to true when we call msbuild in our pipelines.
This PR makes it so that instead of having to pass that property, the projects themselves automatically build with source link when they need to.
This makes it so that local builds of RNW are closer to the the same nuget restore behavior / packages.lock.json file as when they're built in pipelines.
This is part is working toward resolving #12004 and this functionality was extracted from PR #13634. …
> Automatically set EnableSourceLink for in-repo builds only

- change/react-native-windows-b2ad5990-4475-4b62-9ec8-6ddd45ba06be.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
- Feature
Bring Fabric to API parity with Paper.
This PR adds initial native support for the accessibilityActions and onAccessibilityAction props. In this PR we add support for the "invoke", "scrollIntoView", "setValue", and "toggle" actions. These are actions specific to the Windows platform. This PR also adds support for the "activate" action which is a cross-platform action. 
As we add support for other UIA providers to Fabric, we will be able to expand the list of accessibilityActions we can support. 
Note the onAccessibilityAction event emitter only supports specifying an action name at this time, so for the Windows setValue action, there is currently no way to pass the new value back to the JS. This infrastructure could be added. The code sample …
> [Fabric] Add Support for accessibilityActions and onAccessibilityAction

- change/react-native-windows-35fe2283-4a8f-4316-8159-4f399c3fbe8f.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.h
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
- vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.h
Currently LogBox will create a new window, and never destroy it.
I also deleted some dead code.
> [Fabric] LogBox should destroy its window on instance shutdown

- change/@react-native-windows-cli-81405bf2-50e6-426f-8c7a-81c622d5fa43.json
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/utils/build.ts
This PR backports #13665 to 0.75.
This PR fixes the two issues with `run-windows --msbuildprops`
1. When passing nothing, the command should not error and exit
2. When the string is parsed into key/value pairs, do not add empty keys to the msbuild command (which will cause msbuild to fail)
Ran into these issues while working on PR #13634, extracted them as general bug fixes here.
See above.
N/A
Verified running `run-windows` with malformed `--msbuildprops` no longer errors.
[0.75] Fix parsing of empty build props in run-windows
> [0.75] Fix parsing of empty build props in run-windows

- yarn.lock
> [0.75] Bump serve-static to resolve Component Governance alerts

- change/@react-native-windows-codegen-8d6e2cd0-f94e-4aea-93b7-ac7b5edb0529.json
- change/react-native-windows-53895955-fc85-4bdd-bf07-423af7773f83.json
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- packages/playground/windows/playground-composition.Package/packages.lock.json
- packages/sample-custom-component/codegen/react/components/SampleCustomComponent/MovingLight.g.h
- vnext/Microsoft.ReactNative/ComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/IReactViewComponentBuilder.idl
Adds a FocusNavigationDirection property to LosingFocus and GainingFocus events.  And modifies the HandleCommand methods to allow custom components to override the behavior of built-in commands.
Fixes #13686
> [Fabric] Add FocusNavigationDirection and allow overriding of default command handling

- yarn.lock
> Bump serve-static to resolve Component Governance alerts

- yarn.lock
> [0.72] Bump serve-static to resolve Component Governance alerts

- yarn.lock
> [0.73] Bump serve-static to resolve Component Governance alerts

- .ado/templates/react-native-init-windows.yml
- yarn.lock
> [0.74] Bump serve-static to resolve Component Governance alerts

- change/react-native-windows-34f9da3d-13df-48ee-8489-f8f3de5cb985.json
- vnext/src-win/Libraries/Components/View/View.windows.js
childrenWithImportantForAccessibility  is created in every render and probably used infrequently.
This PR seeks to move it to a standalone function within the file to avoid the cost to create the function over and over.
This should be an extremely minor performance increase.
Moved a function creation out of the rendered View to the file module.
Tested locally in the Xbox app
- Rendered views with no children
- Rendered views with children
- Rendered views with children and the `importantForAccessibility` set to "no-hide-descendants"
Probably not. Not important.
> Moving childrenWithImportantForAccessibility creation out of every View

- change/react-native-windows-9126fadc-f129-4191-92d1-bbfd77422aea.json
- vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp
Add 'link' accessibilityRole to the list of controls that support the invoke provider.
Resolves #13861
Added the 'link' accessibilityRole to list of controls that are supported by the Invoke provider in `DynamicAutomationPeer`.
Tested on a `Pressable` with `accessibilityRole='link'`
Before:
After:
Should this change be included in the release notes: Yes
Add 'link' accessibilityRole to the list of controls that support the invoke provider.
> Add invoke support for 'link' accessibilityRole

- .ado/jobs/playground.yml
- .ado/templates/prepare-build-env.yml
Fixing error blocking PRs due to surprise ADO policy change:
```
Detected characters in arguments that may not be executed correctly by the shell. Please escape special characters using backtick (`). More information is available here: https://aka.ms/ado/75787
```
Unblock pipelines.
Fixed argument escaping.
N/A
N/A
> Fix escaping arguments for PowerShell tasks

- change/@react-native-windows-automation-channel-618f52b6-bbe6-4449-9165-d6a447f0da53.json
- change/react-native-windows-73248300-7bfa-4031-8b40-14125d248e4f.json
- packages/@react-native-windows/automation-channel/package.json
- vnext/package.json
Removes the `packages.lock.json` and `packages.fabric.lock.json` files from our published NPM packages, as customers who choose to build M.RN themselves don't necessarily choose the same dependencies as us (such as SourceLink).
See above.
Resolves #13914 
Added filters to the NPM `package.json` files to exclude these lock files.
N/A
Verified with `npm pack` that new packages do not contain these files.
> Exclude NuGet package lock files from NPM packages

- change/@react-native-windows-automation-channel-618f52b6-bbe6-4449-9165-d6a447f0da53.json
- change/react-native-windows-73248300-7bfa-4031-8b40-14125d248e4f.json
- packages/@react-native-windows/automation-channel/package.json
- vnext/package.json
Removes the `packages.lock.json` and `packages.fabric.lock.json` files from our published NPM packages, as customers who choose to build M.RN themselves don't necessarily choose the same dependencies as us (such as SourceLink).
See above.
Resolves #13914
Added filters to the NPM `package.json` files to exclude these lock files.
N/A
Verified with `npm pack` that new packages do not contain these files.
> [0.76] Exclude NuGet package lock files from NPM packages (#13916)

- change/react-native-windows-8fc62f61-155f-45b2-824c-26d42a3281cb.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
WebDebugging currently crashes due to usage of a TurboModule only module trying to initialize.
> SampleTurboModule only works as a turbomodule, so do not install it when using web debugger

- change/@react-native-windows-cli-e586f288-c915-4e23-905d-df2ae20d6777.json
- change/react-native-windows-10791c91-ee8b-489d-a0d2-a8047ec1cd70.json
- packages/@react-native-windows/cli/src/commands/config/configUtils.ts
- packages/sample-custom-component/windows/SampleCustomComponent/SampleCustomComponent.vcxproj
- vnext/PropertySheets/External/Microsoft.ReactNative.CppLib.props
- vnext/PropertySheets/External/Microsoft.ReactNative.CppLib.targets
- vnext/templates/cpp-lib/windows/MyLib/MyLib.vcxproj
This PR creates new "entry" prop/target imports for C++ libraries that depend on the `UseFabric` property to conditionally import either the old Uwp props/targets or the new Composition props/targets.
This helps enable module projects to support both paper and fabric with the same build files.
Resolves #13928.
Added new imports, updated the `cpp-lib` template and existing sample to load them.
N/A
N/A
Update the `cpp-lib` template project to support importing either paper Uwp or fabric Composition prop/targets
> Update the `cpp-lib` template project to support importing either paper Uwp or fabric Composition prop/targets

- change/@office-iss-react-native-win32-04103371-5032-4d05-a85d-7bba5fc4aa74.json
- change/@react-native-windows-cli-4f0387bb-aa2d-4bf0-806a-0289b589f4a8.json
- change/react-native-windows-6d126775-edc3-4974-b15c-be0a1182faf6.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-app-fabric/package.json
- packages/sample-apps/package.json
- packages/sample-custom-component/package.json
- vnext/package.json
- yarn.lock
Update our dependencies on `@react-native-community/cli` to the correct `15.0.0-alpha.2`.
We somehow missed this, and in causes problems when trying to create new apps, as RNW wants the wrong CLI version, which can cause the new Yarn to just give up on adding RNW to a template.
See above.
N/A
Verified new apps work.
Update our dependencies on `@react-native-community/cli` to the correct `15.0.0-alpha.2`.
> Update to @react-native-community/cli@15.0.0-alpha.2

- change/@office-iss-react-native-win32-04103371-5032-4d05-a85d-7bba5fc4aa74.json
- change/@react-native-windows-cli-4f0387bb-aa2d-4bf0-806a-0289b589f4a8.json
- change/react-native-windows-6d126775-edc3-4974-b15c-be0a1182faf6.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-app-fabric/package.json
- packages/sample-apps/package.json
- packages/sample-custom-component/package.json
- vnext/package.json
- yarn.lock
This PR backports #13951 to RNW 0.76.
Update our dependencies on `@react-native-community/cli` to the correct `15.0.0-alpha.2`.
We somehow missed this, and in causes problems when trying to create new apps, as RNW wants the wrong CLI version, which can cause the new Yarn to just give up on adding RNW to a template.
See above.
N/A
Verified new apps work.
Update our dependencies on `@react-native-community/cli` to the correct `15.0.0-alpha.2`.
> [0.76] Update to @react-native-community/cli@15.0.0-alpha.2

- change/react-native-windows-408fe985-f784-4dff-aed3-9045a0c7a420.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
When removing a ReactNativeIsland the RootComponentView is kept around in the FabricUIManager until the instance is shutdown.  This means if you have a long running instance, and you create/destroy lots of ReactNativeIslands these objects will build up over time.
> Fix RootComponentView leak

- change/react-native-windows-40511e3c-feb7-429f-9b7f-22d0ba2f9dc1.json
- change/react-native-windows-8fc62f61-155f-45b2-824c-26d42a3281cb.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Cherry-picking #13905 and #13911 to 0.76
> [0.76] Backport use a legacy native module binding that always returns null in bridgeless mode

- .ado/publish.yml
- change/react-native-windows-517cb4e7-9eb3-490c-ba03-b7e303394065.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
Office requires a Arm64EC version of the desktop fabric dll.
> [0.74] Build arm64ec platform for desktop fabric dll

- package.json
- yarn.lock
The version of `lage` in the lockfile produces `Error: spawn EINVAL` errors on newer node versions on windows.
> [0.74] Bump lage version to work on newer node versions

- change/@react-native-windows-cli-20847412-8db7-478f-97c3-d42fd0a860a7.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- packages/@react-native-windows/cli/src/e2etest/initWindows.test.ts
Introducing `--list` option to `init-windows` command.
Displays a list of templates available for usage with `init-windows`.
Resolves #13459
- Added `--list` description, in case developers look for command help.
- Created a function to display template key, name and description in a friendly-readable format.
https://github.com/user-attachments/assets/ae57779b-c257-4fe7-be5d-0066b65eed6d
Ran the cli tests locally, with all tests passing after the change.
Should this change be included in the release notes: yes.
Introduced `--list` option to `init-windows` command.
> Introducing `--list` option to `init-windows`

- change/react-native-windows-90ff0c84-8bc7-43c2-b951-b0325fded218.json
- packages/playground/windows/playground-composition.Package/packages.lock.json
- packages/playground/windows/playground-composition/packages.lock.json
- packages/sample-custom-component/windows/SampleCustomComponent/packages.lock.json
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/packages.fabric.lock.json
- vnext/PropertySheets/WebView2.props
- vnext/PropertySheets/WinUI.props
- vnext/ReactCommon.UnitTests/packages.lock.json
This change updates our WinAppSDK package from WinAppSDK 1.5.240227000 to 1.6.240923002.
Note that WinAppSDK 1.6 has a nuget package dependency on WebView2, so this change introduces a dependency on that package as well.
This updates the WinAppSDK package, which brings new bug fixes and features we'll be able to take advantage of later.
I've updated WinUI.props to use the new version, and picked up the packages.lock.json updates made by nuget restore.
I ran playground-composition with the rntester bundle and verified that basic functionality still works.
Should this change be included in the release notes: Yes
"React Native Windows has been updated to build on WinAppSDK 1.6."
> Update WinAppSDK from 1.5 to 1.6 (1.6.240923002)

- change/react-native-windows-7edd982f-196f-4feb-a824-cbf08e0a2c96.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
This hooks up support for a single box-shadow.  If multiple shadows are specified, we ignore all but the first shadow.  If box-shadow is provided, then its value is used instead of the legacy shadow properties.
This is a partial fix for https://github.com/microsoft/react-native-windows/issues/13944
There is another issue where shadows are not correctly showing currently on Views with a border radius. (#14027). That also affects the existing shadow properties.
> Add very basic box-shadow support

- change/react-native-windows-433ea974-44c7-465f-a6e9-1f34927c7217.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
There is a ContentIsland API DepartFocus, which we should be calling to allow the host to move focus outside of the island when focus reaches the end of the ReactNativeIsland.
> Focus should notify island host when tab loop wraps to give host oportunity to take focus

- change/@react-native-windows-cli-e586f288-c915-4e23-905d-df2ae20d6777.json
- change/react-native-windows-10791c91-ee8b-489d-a0d2-a8047ec1cd70.json
- packages/@react-native-windows/cli/src/commands/config/configUtils.ts
- packages/sample-custom-component/windows/SampleCustomComponent/SampleCustomComponent.vcxproj
- vnext/PropertySheets/External/Microsoft.ReactNative.CppLib.props
- vnext/PropertySheets/External/Microsoft.ReactNative.CppLib.targets
- vnext/templates/cpp-lib/windows/MyLib/MyLib.vcxproj
This PR backports #13945 to 0.76.
This PR creates new "entry" prop/target imports for C++ libraries that depend on the `UseFabric` property to conditionally import either the old Uwp props/targets or the new Composition props/targets.
This helps enable module projects to support both paper and fabric with the same build files.
Resolves #13928.
Added new imports, updated the `cpp-lib` template and existing sample to load them.
N/A
N/A
Update the `cpp-lib` template project to support importing either paper Uwp or fabric Composition prop/targets
> [0.76] Update the `cpp-lib` template project to support importing either paper Uwp or fabric Composition prop/targets

- change/react-native-windows-6b83103d-e55d-427a-a482-d2706e24f6a0.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
Currently when tabbing to a component outside the visible viewport we scroll the scrollviewer just enough to being the component into view.  This changes the default to add some additional padding to being the component not completely to the edge of the viewport.
Fixes #14005
> Default scroll to bring a component into view should have padding around the viewport

- .ado/publish.yml
- change/@react-native-windows-cli-a0eba9ea-32a2-43ac-925d-8f7cb0eae5d7.json
- change/react-native-windows-75287088-403a-4dd5-9392-ea74c6da3d3d.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-lib/template.config.js
This PR temporarily disables NuGet code-signing during publish and also forces all new projects to include our public ADO feed which will contain unsigned packages.
See #14030 for why this is necessary.
See above.
N/A
N/A
[0.74] Temporarily disable code-signing of NuGet packages
> [0.74] Temporarily disable code-signing of NuGet packages

- change/react-native-windows-ce27643e-687f-4f35-815b-4e030e9cc358.json
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/BorderPrimitive.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/BorderPrimitive.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/DebuggingOverlayComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Theme.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
The current focus visuals do not pick up the corner radius of the view with focus.  They are also always black.
The new visuals will use two themed colors (generally a black and a white).  The focus visuals will also properly pickup the corner radius from the view with focus.
I've extracted some of the border handling code to allow it to be reused for the focus visuals.  There is still some future optimizations that could be done in the border code.  Ex: when the corners + colors + styles are uniform, we could use a single RoundedRectangleVisual instead of a bunch of smaller visuals. (https://github.com/microsoft/react-native-windows/issues/14007)
> Update focus visuals to use cornerRadius and inner/outer strokes

- .ado/publish.yml
- change/@react-native-windows-cli-a0eba9ea-32a2-43ac-925d-8f7cb0eae5d7.json
- change/react-native-windows-75287088-403a-4dd5-9392-ea74c6da3d3d.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-lib/template.config.js
This PR temporarily disables NuGet code-signing during publish and also forces all new projects to include our public ADO feed which will contain unsigned packages.
See #14030 for why this is necessary.
See above.
N/A
N/A
[0.75] Temporarily disable code-signing of NuGet packages
> [0.75] Temporarily disable code-signing of NuGet packages (#14031)

- .ado/publish.yml
- change/@react-native-windows-cli-a0eba9ea-32a2-43ac-925d-8f7cb0eae5d7.json
- change/react-native-windows-75287088-403a-4dd5-9392-ea74c6da3d3d.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-lib/template.config.js
This PR temporarily disables NuGet code-signing during publish and also forces all new projects to include our public ADO feed which will contain unsigned packages.
See #14030 for why this is necessary.
See above.
N/A
N/A
Temporarily disable code-signing of NuGet packages
> Temporarily disable code-signing of NuGet packages

- change/react-native-windows-76c400e4-4a62-4fcd-95c9-25a19cf51138.json
- vnext/src-win/Libraries/Text/Text.windows.js
Resolved [#14038](https://github.com/microsoft/react-native-windows/pull/13647/files#diff-d34894e1bfca96d4b34d9e6b6694ca7251d087e3fceafcafb52b42ce23a6653c), seems that I missed some PRs while implementing the new optimized Text and left in some dead Windows code that no longer gets used. This PR integrates https://github.com/facebook/react-native/pull/45340/files and https://github.com/facebook/react-native/pull/45345/files and removes an extra flattenStyle being used.
Will need to backport this to 0.76 before the release!
Resolves #14038 
Tested the borders still work on Paper in rntester
no
> Fix Text running flattenStyle multiple times

- .ado/jobs/cli-init-windows.yml
When the CLI CI succeeds, it usually only takes < 20 min. Sometimes it goes up to low 30s, so reducing the timeout from 120 to 40 to increase speed of re-runs.
> Change CLI CI timeouts to 40min

- .ado/jobs/e2e-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/write-certificate.yml
This PR cherry-picks the following certificate-related commits to unblock CI in 0.75:
https://github.com/microsoft/react-native-windows/commit/3a5ca66aab21739e168bd7d236de2f420bf3090c
https://github.com/microsoft/react-native-windows/commit/3534af4fdfb0e5b73b1ecf6b3da6c48f129d008b
https://github.com/microsoft/react-native-windows/commit/5fad854368beb3bee4a1526bb7fc97ad0f7bf8ad
> [0.75] Backport certificate fixes to unblock CI

- change/react-native-windows-154312b4-b03a-41b3-99e3-905475325a8a.json
- vnext/src-win/Libraries/Text/Text.windows.js
Text components rendered in Paper need to have check if the style they are rendering contains border style props. This bug occurs when the passed in style is an array. From what I can tell, this bug has existed for a long time, possibly forever.
[4 Years Ago](https://github.com/microsoft/react-native-windows/commit/946ba7fd7c6304a5bc6d4a1e69375e290ea10eef) This PR fixed borders not rendering for text, but did not address text components with an array of styles.
[3 Years Ago](https://github.com/microsoft/react-native-windows/commit/ee4d83d9a23bd4fcc51d7ccacd72eff493a9742d#diff-5beb08e50a61de475cd20c6e68588ac3a5cd687a971883167fe75fc97a0dbdea) This PR changes naming, but not the logic.
This PR switches the style that is checked for border props from the one that is passed in to the one that …
> Fixing text components not rendering a border with Paper

- change/@react-native-windows-codegen-4ec7c1b2-8541-47d9-a5d0-c245b25fbac1.json
- change/react-native-windows-621a9112-d00c-469f-83a8-ae391abefe18.json
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/sample-custom-component/codegen/react/components/SampleCustomComponent/DrawingIsland.g.h
- packages/sample-custom-component/codegen/react/components/SampleCustomComponent/MovingLight.g.h
- packages/sample-custom-component/windows/SampleCustomComponent/MovingLight.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiComponentDescriptor.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiViewComponentDescriptor.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiViewProps.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
- vnext/Microsoft.ReactNative/IReactViewComponentBuilder.idl
- vnext/Microsoft.ReactNative/ViewProps.idl
When using a custom native component with a custom props object, when the shadownode is cloned, the props object is also cloned.  This cloning was never exposed to the application, so the props object would be empty except for the changed props.
I've added a pointer back to the old props object that is handled out into the users prop creation factory.
I also updated the codegen to automatically generate the cloning functionality.
I verified this using the MovingLight sample.  Currently the test page actually updates all custom properties at the same time, so we never noticed this issue. But by modifying the example page I was able to reproduce the issue, and verified this fixes it.
I originally hit this issue debugging one of the examples in rn-svg which was rendering incorrectly on …
> Fix issue with prop cloning with custom native props

- .ado/jobs/e2e-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/write-certificate.yml
This PR cherry-picks the following certificate-related commits to unblock CI in 0.74:
https://github.com/microsoft/react-native-windows/commit/3a5ca66aab21739e168bd7d236de2f420bf3090c
https://github.com/microsoft/react-native-windows/commit/3534af4fdfb0e5b73b1ecf6b3da6c48f129d008b
https://github.com/microsoft/react-native-windows/commit/5fad854368beb3bee4a1526bb7fc97ad0f7bf8ad
> [0.74] Backport certificate fixes to unblock CI

- .ado/jobs/macos-tests.yml
Updates our macOS testing in CI to the macos-latest VM image.
To unblock CI.
See above.
N/A
Verified tests pass.
> Update macos-tests to macos-latest images to unblock CI

- .ado/jobs/macos-tests.yml
Updates our macOS testing in CI to the macos-latest VM image.
To unblock CI.
See above.
N/A
Verified tests pass.
> [0.76] Update macos-tests to macos-latest images to unblock CI

- .ado/jobs/macos-tests.yml
Updates our macOS testing in CI to the macos-latest VM image.
To unblock CI.
See above.
N/A
Verified tests pass.
> [0.75] Update macos-tests to macos-latest images to unblock CI

- .ado/jobs/macos-tests.yml
Updates our macOS testing in CI to the macos-latest VM image.
To unblock CI.
See above.
N/A
Verified tests pass.
>  [0.74] Update macos-tests to macos-latest images to unblock CI

- .ado/templates/react-native-init-windows.yml
- change/react-native-windows-51a54d64-0977-4db3-9842-2c3face412ef.json
- vnext/PropertySheets/Bundle.Common.targets
- vnext/PropertySheets/Bundle.props
This PR sets a timeout for the bundle command (`npx react-native bundle`) that happens during release builds with `run-windows`. This is because sometimes Metro can hang indefinitely even after it's done, causing the command to not exit, and otherwise hold up a good build from finishing.
The new timeout defaults to 5m (a new app takes ~40s to bundle) but this variable can easily be modified by defining `BundleCommandTimeoutMs` MSBuild property.
For our new project tests, setting the timeout to 1m, so that, in theory, if the bundle actually finished at 40s, then timing out won't block the remainder of the build.
See above.
May help fix some of the times we've seen hanging with …
> Add timeout to JS bundle creation in release builds

- change/react-native-windows-2171471a-2833-423e-bd15-88fb7b6b8adc.json
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/integration-test-app/windows/integrationtest/packages.lock.json
- packages/sample-apps/windows/SampleAppCPP/packages.lock.json
- packages/sample-apps/windows/SampleAppCS/packages.lock.json
- packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
- vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.Dependencies.props
This PR backports #14084 to 0.76.
This PR upgrades the minimum version of `Microsoft.NETCore.UniversalWindowsPlatform` to 6.2.14 for UWP C# projects.
This is long over-due as the latest (and probably last) version of this package hasn't changed in over two years. There's no reason for us to build against an older version. Just as importantly, this brings in a newer version of the .NetNative toolchain, which seems to resolve issues around C# builds hanging at the .NetNative step.
Resolves #14055
Resolves #9194
Resolves #4869
Updated the minimum version of `Microsoft.NETCore.UniversalWindowsPlatform` to 6.2.14 for UWP C# projects. Added new entries to the props that enable C++ apps to consume C# modules to see the latest versions of …
> [0.76] Update to Microsoft.NETCore.UniversalWindowsPlatform 6.2.14

- change/react-native-windows-22ea5da8-4ee5-4ec6-bac3-1c62cabf01f7.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative.Cxx/ComponentView.Experimental.interop.h
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Runtime activation class for Microsoft.ReactNative.Color is not part of the react-native-win32.dll.
> Export MS.RN.Color ctor in Office dll

- change/react-native-windows-22ea5da8-4ee5-4ec6-bac3-1c62cabf01f7.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative.Cxx/ComponentView.Experimental.interop.h
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
> [0.74] Export MS.RN.Color ctor in Office dll

- change/react-native-windows-ad145bca-5a3a-45aa-ab7b-35661aa5fe59.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
Fix issue where on resize, TextInput caret sometimes becomes visible as if it has focus.
> TextInput caret becomes visible on non-focused TextInputs on resize

- change/@react-native-windows-telemetry-4abe7bcd-e858-4ab9-bc9c-3e2fd948acf2.json
- packages/@react-native-windows/telemetry/src/telemetry.ts
Set the telemetry instrumentation key to upload telemetry.
**Resolves #14089**
Currently, the telemetry data goes nowhere.
As the backend is taking shape, we can start to let the data to flow upstream.
Instead of an empty instrumentation key, set the one associated to the RNW telemetry project.
N/A
Ran the telemetry unit tests. Number of telemetry instances is correctly updated to the backend, with little to no delay. Measures are getting updated too with the new data.
Yes
_Enables telemetry collection to monitor RNW reliability, performance, and usage._
> [Telemetry] Enable data uploading

- change/react-native-windows-57b89f93-f274-467b-b4eb-a6a61fd19c46.json
- vnext/TestWebSite/Microsoft.ReactNative.Test.Website.csproj
Bump target .NET version to 8.0 as 7.0 was being marked as deprecated according to CI error messages. 
Unblock CI.
See above.
> Bump .NET Target version in Microsoft.ReactNative.Test.Website.csproj

- change/react-native-windows-4fec92b2-f049-43b1-8e13-d9c351c5511b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
Implements the cursor property on the new arch.
> Implement cursor property

- change/react-native-windows-58d5a889-6e77-4cde-a5d8-76a73e9a3cb7.json
- vnext/Mso.UnitTests/future/futureTest.cpp
Disabling a UT to unblock work until #14114 is fixed
> Disable failing UT

- change/react-native-windows-5f728ab0-c614-4bcd-b89d-0bfa4b9956db.json
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewTraitsInitializer.h
- vnext/src-win/Libraries/Components/View/View.windows.js
Generally, events that bubble on the JS side do not require a stacking context.  But in the case of keyUpEvents/keyDownEvents, those affect the event bubbling on the native side, and so they require a stacking context.
Also modifying the setting of onKeyUp/onKeyDown on view to only be set if the view has keyUpEvents/keyDownEvents or onKeyUp/onKeyDown are set on it, as they will never do anyway if they are both undefined.
> Views with keyUpEvents/keyDownEvents set on them should form a stacking context

- .ado/templates/react-native-init-windows.yml
React-native-create-library [renamed module-new to turbo-module](https://github.com/callstack/react-native-builder-bob/pull/718), this should unblock the failing CI
Should this change be included in the release notes: _indicate no_
> Change module-new to turbo-module in CI

- change/@react-native-windows-codegen-fc9a80b3-b16a-458c-b6e9-230a3d4f14f2.json
- change/react-native-windows-2e9f4c25-c40a-4434-9c2c-0d6672969f47.json
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- packages/sample-custom-component/windows/SampleCustomComponent/codegen/react/components/SampleCustomComponent/DrawingIsland.g.h
- packages/sample-custom-component/windows/SampleCustomComponent/codegen/react/components/SampleCustomComponent/MovingLight.g.h
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactCompositionViewComponentBuilder.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
Adding ability for custom native components to provide a custom UpdateLayoutMetrics method, and to override VisualToMountChildrenInto.
I also did some cleanup of how override methods work to reduce the size of ComponentViews in memory.
Fixes #14172 and #14174.
> Add ability to override UpdateLayoutMetrics and VisualToMountChildrenInto

- change/@react-native-windows-telemetry-990667a5-918a-4348-8861-ce4ad8fc7a47.json
- packages/@react-native-windows/telemetry/src/e2etest/telemetry.test.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
This PR eliminates the risk of writing into undefined struct fields in `trackException()`.
Bug fix
Error telemetry instances were lost when hitting MS Build errors sometimes, plus avoid unnecesssary CLI error noise.
Resolves #14184 
One-line change:
`codedErrorStruct.data[f] = (error as any)[f];`
instead of:
`codedErrorStruct.data.codedError.data[f] = (error as any)[f];`
**Context:**
In error telemetry instances, `codedError` contains relevant information about an exception thrown from the RNW CLI.
There are two ways to populate `codedError`: either a `errorUtils.CodedError` object is passed to `trackException()`, or a MSBuild error was hit, and the `Error` object contains any of the following fields: `errno`, `syscall` or `code`. It's in the second scenario where things go wrong.
In …
> [Telemetry] Bug fix in `codedError.data` from `trackException()`

- change/react-native-windows-87a27036-cad7-4e7e-a5e1-9f1a77329392.json
- vnext/PropertySheets/OutputMSBuildProperties.targets
Add `RnwNewArch` and `UseFabric` properties to MSBuildProperties, indicating if the project is using Paper or Fabric.
By using telemetry data, we want to determine the adoption level of Fabric.
Resolves #14047
Included `RnwNewArch` and `UseFabric` in the properties written into msproperties.g.json (via OutputMSBuildProperties.targets), which are picked up by `run-windows` to pass all the properties as `extraProps` for telemetry logging.
Ran `run-windows` in a debugger and verified that `RnwNewArch` and `UseFabric` are written into msproperties.g.json and they are passed to `Telemetry.trackCommandEvent()`.
No
> [Telemetry] Add `RnwNewArch` to MSBuildProperties

- change/react-native-windows-f2db65c0-87c3-4b5a-812d-750b66220702.json
- vnext/PropertySheets/React.Cpp.props
> Fix calls to std::mutex::lock

- change/react-native-windows-6fdddb9a-d20b-48fd-b2e0-73cb4aab35c5.json
- vnext/PropertySheets/React.Cpp.props
> [0.77] Fix calls to std::mutex::lock

- change/react-native-windows-b297b46d-177c-41f6-b5e2-965e5596d104.json
- vnext/PropertySheets/React.Cpp.props
> [0.76] Fix calls to std::mutex::lock

- change/react-native-windows-063e9dd8-dc0b-4737-99b8-793e5da80a21.json
- vnext/PropertySheets/React.Cpp.props
> [0.74] Fix calls to std::mutex::lock

- change/react-native-windows-3ad43108-ecfc-453c-93a8-4759ba78c932.json
- vnext/PropertySheets/OutputMSBuildProperties.targets
**Backport #14208 to 0.76.**
Add `RnwNewArch` and `UseFabric` properties to MSBuildProperties, indicating if the project is using Paper or Fabric.
By using telemetry data, we want to determine the adoption level of Fabric.
Resolves #14047
Included `RnwNewArch` and `UseFabric` in the properties written into msproperties.g.json (via OutputMSBuildProperties.targets), which are picked up by `run-windows` to pass all the properties as `extraProps` for telemetry logging.
Ran `run-windows` in a debugger and verified that `RnwNewArch` and `UseFabric` are written into msproperties.g.json and they are passed to `Telemetry.trackCommandEvent()`.
No
> [0.76] [Telemetry] Add `RnwNewArch` to MSBuildProperties

- change/@react-native-windows-telemetry-371e0e76-e562-4be7-b257-2ca2afc87270.json
- change/@react-native-windows-telemetry-990667a5-918a-4348-8861-ce4ad8fc7a47.json
- packages/@react-native-windows/telemetry/src/e2etest/telemetry.test.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
**Backports #14191 to 0.76.**
This PR eliminates the risk of writing into undefined struct fields in `trackException()`.
Bug fix
Error telemetry instances were lost when hitting MS Build errors sometimes, plus avoid unnecesssary CLI error noise.
Resolves #14184 
One-line change:
`codedErrorStruct.data[f] = (error as any)[f];`
instead of:
`codedErrorStruct.data.codedError.data[f] = (error as any)[f];`
**Context:**
In error telemetry instances, `codedError` contains relevant information about an exception thrown from the RNW CLI.
There are two ways to populate `codedError`: either a `errorUtils.CodedError` object is passed to `trackException()`, or a MSBuild error was hit, and the `Error` object contains any of the following fields: `errno`, `syscall` or `code`. It's in the second scenario …
> [0.76] [Telemetry] Bug fix in `codedError.data` from `trackException()`

- change/@react-native-windows-telemetry-673ad5b4-2241-4057-9a19-15acccc82774.json
- change/@react-native-windows-telemetry-d7dc63f1-c900-4229-bcb4-8d7cd683293c.json
- packages/@react-native-windows/telemetry/src/e2etest/telemetry.test.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
**Backports #14161 to 0.76**
Expand sanitization checks in telemetry, in this case error telemetry instances (and more specifically, all the string fields in `codedError.data`).
Bug fix.
In telemetry error instances, certain fields may potentially contain file paths. This requires sanitization checks - they already exist for other telemetry fields.
Resolves #14158 
In `Telemetry.trackException()`, take the `codedError` struct (i.e., a struct that contains error information), check each field in the struct if it's a string. If it is, perform sanitization; this will replace any filepaths with `[path]`.
N/A
Added a unit test to verify a codedError.data struct containing:
fieldWithPath - sanitization will modify remove a filepath with `[path]`.
fieldWithNoPath - a string that won't be …
> [0.76] [Telemetry] Expand field sanitization to codedError.data

- change/react-native-windows-94cad441-d079-4e22-bfcc-f2beb900bad1.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
See [P1413 - Deprecate std::aligned_storage and std::aligned_union](https://wg21.link/p1413)  for background.
tl;dr: std::aligned_storage and std::aligned_union are deprecated because the API is error prone. One should just use a std::byte array with the proper alignas attribute.
alignas does not propagate through type alias. In those cases we need to introduce a new type. See
https://developercommunity.visualstudio.com/t/accepts-invalid-alignas-in-alias-decla/1345176
This is currently blocking Office from moving to C++23
> std::aligned_storage is deprecated

- change/react-native-windows-94cad441-d079-4e22-bfcc-f2beb900bad1.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
> [0.74] std::aligned_storage is deprecated

- change/react-native-windows-30444064-215c-45d3-aaa7-9c10ae68e203.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/nativemodule/dom/NativeDOM.cpp
- vnext/Shared/Shared.vcxitems
- vnext/overrides.json
This PR removes all instances where we ignore warning 4244 (loss of data when casting double to int) because BinSkim won't let us pass compliance when that happens.
Compliance, fix publish, see above.
Closes #14251
See above.
N/A
N/A
Stop disabling warning 4244 because BinSkim fails if it sees one
> Stop disabling warning 4244 because BinSkim fails if it sees one

- .ado/release.yml
Created a new release.yml pipeline which is responsible for pushing the final nuget packages to the various ADO/NuGet feeds.
Compliance.
Closes #13904
Exported the existing classic pipeline to yml using the 1ES tooling.
N/A
N/A
> Create RNW NuGet Release yml from classic pipeline

- change/@react-native-windows-telemetry-f67eede7-8e2c-46b7-9ce9-5d664dfcd76e.json
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/nameUtils.test.ts
- packages/@react-native-windows/telemetry/src/utils/nameUtils.ts
Fix to ensure that telemetry package names contain only the following characters: alphanumeric, underscore, dot. Also, make sure it starts with letter, and it has 100 characters or less.
Resolves #14218 
The telemetry backend doesn't like that some of the packages contain characters like `@` and `-`. This is problematic when trying to create dimensions that depend on the version of packages like:
`react-native-windows`
`@react-native-community/cli`
- Added a condition to process package names in case it's not compliant with the rules described previously.
- Introduced a new telemetry helper (nameUtils) with a couple of functions to verify and process package names. Replace all "bad" characters with **underscores**.
N/A
Ran the telemetry …
> [Telemetry] Address package name limitations - Take 2

- change/react-native-windows-30444064-215c-45d3-aaa7-9c10ae68e203.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/nativemodule/dom/NativeDOM.cpp
- vnext/Shared/Shared.vcxitems
- vnext/overrides.json
This PR backports #14258 to 0.77
This PR removes all instances where we ignore warning 4244 (loss of data when casting double to int) because BinSkim won't let us pass compliance when that happens.
Compliance, fix publish, see above.
Closes #14251
See above.
N/A
N/A
Stop disabling warning 4244 because BinSkim fails if it sees one
> [0.77] Stop disabling warning 4244 because BinSkim fails if it sees one

- change/react-native-windows-13eb1f66-5cc6-4b45-b6a5-c924e36107c7.json
- vnext/PropertySheets/React.Cpp.props
> [0.75] Fix calls to std::mutex::lock

- change/@react-native-windows-telemetry-6c5902e1-6010-4dc5-b994-e44525a9aca1.json
- change/@react-native-windows-telemetry-f67eede7-8e2c-46b7-9ce9-5d664dfcd76e.json
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/nameUtils.test.ts
- packages/@react-native-windows/telemetry/src/utils/nameUtils.ts
**Backports #14259 to 0.76.**
Fix to ensure that telemetry package names contain only the following characters: alphanumeric, underscore, dot. Also, make sure it starts with letter, and it has 100 characters or less.
Resolves #14218 
The telemetry backend doesn't like that some of the packages contain characters like `@` and `-`. This is problematic when trying to create dimensions that depend on the version of packages like:
`react-native-windows`
`@react-native-community/cli`
- Added a condition to process package names in case it's not compliant with the rules described previously.
- Introduced a new telemetry helper (nameUtils) with a couple of functions to verify and process package names. Replace all "bad" characters with …
> [0.76] [Telemetry] Address package name limitations - Take 2

- change/react-native-windows-db1edeae-cd39-4b02-9676-e41d36724426.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Office still supports Windows Server 2016 so we need to use run time dynamic linking to call SetThreadDescription
> [0.74] Crash when running RNW on windows server 2016

- .ado/jobs/macos-tests.yml
- change/react-native-windows-fb05b7e7-612e-442e-979c-2811cc3b5a1c.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Folly/TEMP_UntilFollyUpdate/Conv.h
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactCommon.UnitTests/packages.lock.json
> [0.73] Fix calls to std::mutex::lock 

- change/react-native-windows-4c0bcc99-7a7e-47f4-b444-54f041ec6542.json
- change/react-native-windows-5797e623-a2b1-4fee-8558-d92058803600.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.h
Backports #14215 to 0.77.
Update the control type values of components to corresponding accessibilityRole value.
When the `accessibilityRole` property is set on a component, the `controlType` property should be updated to match the corresponding `accessibilityRole` value. Currently, for most components, this was not happening, and was shown in the following bug: 
Add functionality to update corresponding control type value based on components' accessibilityRole value.
Before:
After:
N/A
Update the control type values of components to corresponding accessibilityRole value.
> [0.77] Update ControlType values to match corresponding accessibilityRole values

- change/react-native-windows-5797e623-a2b1-4fee-8558-d92058803600.json
- change/react-native-windows-61c2410d-25ba-411e-b04c-b7a6f3fa4891.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.h
Backports #14215 to 0.76.
Update the control type values of components to corresponding accessibilityRole value.
When the `accessibilityRole` property is set on a component, the `controlType` property should be updated to match the corresponding `accessibilityRole` value. Currently, for most components, this was not happening, and was shown in the following bug: 
Add functionality to update corresponding control type value based on components' accessibilityRole value.
Before:
After:
N/A
> [0.76] Update ControlType values to match corresponding accessibilityRole values

- .ado/templates/enable-fabric-experimental-feature.yml
- change/react-native-windows-e6272cc4-e143-4cf9-98d1-b81bb73e7cb5.json
- change/react-native-windows-ed7b2b09-74fa-4fe0-9de3-57c3ae856148.json
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/PropertySheets/WinUI.props
This fixes the UIA tree when a ReactNativeIsland is embedded inside other UI.
With this change the desktop dll will be built using the experimental WinAppSDK dll, as we are relying on using new APIs in that version of WinAppSDK.
> [0.74] RNIsland UIA fragment root should report parents fragment root

- change/react-native-windows-85407e5a-8b6f-41fe-b146-e73c385e9b34.json
- change/react-native-windows-db1edeae-cd39-4b02-9676-e41d36724426.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Mso.UnitTests/packages.fabric.lock.json
- vnext/PropertySheets/WebView2.props
- vnext/ReactCommon.UnitTests/packages.lock.json
This fixes the UIA tree when a ReactNativeIsland is embedded inside other UI.
With this change the desktop dll will be built using the experimental WinAppSDK dll, as we are relying on using new APIs in that version of WinAppSDK.
> RNIsland UIA fragment root should report parents fragment root

- change/react-native-windows-9fae9acd-d5a6-48d1-9d63-c333ad09ca76.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Null dereference crash when currently focused element gets marked as enableFocusRing=false.  
There is a check that `m_componentHostingFocusVisual` is non-null, but it happens before we call `hostFocusVisual(false)` if enableFocusRing is false.  That call will set `m_componentHostingFocusVisual` to null.
Fix is to check `m_componentHostingFocusVisual` after the call to `hostFocusVisual(false)`.
> Fix crash when currently focused element gets marked as enableFocusRing=false

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/universal.yml
- .ado/publish.yml
- .ado/templates/prep-and-pack-nuget.yml
- .ado/templates/prep-and-pack-single.yml
- .ado/templates/react-native-init-windows.yml
- change/react-native-windows-e2a858e1-d434-4940-89a0-2468df697134.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.PackageReferences.props
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
- vnext/Scripts/Microsoft.ReactNative.VersionCheck.targets
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
- vnext/Scripts/OfficeReact.Win32.nuspec
This PR combines the separate standard (Old Arch, Paper, UWP) versions and the `-Fabric` (New Arch, Fabric, WinAppSDK) `Microsoft.ReactNative` NuGet packages into one hybrid package with both sets of binaries.
It is currently an implementation detail that we have two separate "versions" of Microsoft.ReactNative.dll - one for Old Arch and one for New Arch - same named DLL, but a different API surface. Maintaining two different package versions for these makes it harder for us to do future work for New Arch and still support Old Arch. In particular it's holding back our ability to support C# for New Arch projects.
Resolves #13940
Updated the NuGet creation pipelines and nuspec files to use …
> Merge New and Old Arch Microsoft.ReactNative Nuget packages

- change/react-native-windows-96dd8a87-4b77-4f7e-bf40-fb214350e0f3.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
This change stiches together the UIA tree between a React Native content and a child island it might be hosting.  It also provides initial support for tab navigation into and out of a child island.
Not working yet:
* ElementFromProvider / UIA hit testing doesn't work yet, only tree navigation so far.
This is progress toward the goal of RNW being able to properly host a XamlIsland so a RNW fabric app can use Xaml controls.
When UseWinUI3Experimental, we can traverse the UIA tree downward into Xaml and upward back to RNW:
I've tested this manually using the Playground-Composition app with UseWinUI3Experimental set to true.
> Initial support for UIA and tab navigation for a child Island

- change/react-native-windows-ca3eff01-d91f-4d53-80fe-5ce6cfdf0727.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
Round focus visuals by default to align with fluent design.
Fix issue when the focus visual was nudged to fit into the container, which would cause the inner and outer focus visuals to overlap causing a muddy gray border on the nudged sides.
No rounded focus by default: (and bad bottom edge due to nudging)
Messed up focus visuals when focus visual nudged: (Visual is nudged on top three sides to fit inside a scrollviewer)
Rounded focus visual:
Fixed nudged focus visual: (Visual is nudged on top three sides to fit inside a scrollviewer)
> Round Focus visuals by default, fix nudge rendering

- .ado/jobs/desktop.yml
- .ado/publish.yml
- change/react-native-windows-cee7156d-9d30-4922-a594-c591aa4d568b.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/ExperimentalFeatures.props
- vnext/Scripts/OfficeReact.Win32.nuspec
This PR changes our build system to only build the version of `OfficeReact.Win32` with Fabric enabled.
We are building both versions of Desktop in our CI, but the `-Fabric` version is in fact a strict superset of functionality and the only one that Office uses now.
Changed the default so that Desktop always builds with `RnwNewArch` (and therefore `UseFabric`) enabled. Removed the matrix configurations for DesktopFabric from all CI. Fixed the affected nuspec file. Also fixed Desktop publish to include ARM64EC for Fabric and the an issue caused by #14311.
N/A.
Verified the build works.
> Only build OfficeReact.Win32 with UseFabric enabled

- change/react-native-windows-fb01ddc4-cef6-477e-b91d-7583eeb458b1.json
- vnext/Microsoft.ReactNative/Views/DebuggingOverlayViewManager.cpp
Removes unnecessary call to Super::DispatchCommand, ViewManagerBase will just assert(false) on dispatch command. https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L358. Seemed better just to remove the call incase Meta adds more methods we aren't supporting on Paper.
But let me know if the call is necessary for some reason I'm missing, we could also add a check to ignore the unsupported methods (see previous commit).
react dev-tools will fail because upstream added the methods "highlightTraceUpdates", "highlightElements", and "clearElementsHighlights" and we only added those for Fabric, not Paper. 
Resolves #14298
tested that react devtools works again!
yes - Fixes react …
> Fix react devtools hitting an assert on launch

- change/react-native-windows-6d9f3161-2868-4c4d-a3a1-a49b9eee3d5b.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.cpp
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.h
If you have a turbo module spec that defines a method as taking a string parameter, then you should be able to use an `hstring` on the native side.
Currently the module works correctly when using an `hstring`, but if you use the codegen'd spec to validate that the native TurboModule correctly implements the methods from JS, the build will fail because it does not correctly identify `hstring` as being a valid argument type for a JS string.
As an example the built in Clipboard module is currently using `std::wstring`.  Changing it to `hstring` without this change will cause the build to fail.
> TurboModule spec checking should accept hstring for string arguments

- change/react-native-windows-1a764f45-708e-4478-ad87-e88952413174.json
- vnext/Microsoft.ReactNative/Views/DebuggingOverlayViewManager.cpp
Backport of https://github.com/microsoft/react-native-windows/pull/14320
Removes unnecessary call to Super::DispatchCommand, ViewManagerBase will just assert(false) on dispatch command. https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L358. Seemed better just to remove the call incase Meta adds more methods we aren't supporting on Paper.
But let me know if the call is necessary for some reason I'm missing, we could also add a check to ignore the unsupported methods (see previous commit).
react dev-tools will fail because upstream added the methods "highlightTraceUpdates", "highlightElements", and "clearElementsHighlights" and we only added those for Fabric, not Paper. …
> [0.78] Fix react devtools hitting an assert on launch (#14320)

- change/react-native-windows-fe8c0620-7a2e-4b7d-a20b-91bbc15675cc.json
- vnext/Microsoft.ReactNative/Views/DebuggingOverlayViewManager.cpp
Backport of https://github.com/microsoft/react-native-windows/pull/14320
Removes unnecessary call to Super::DispatchCommand, ViewManagerBase will just assert(false) on dispatch command. https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L358. Seemed better just to remove the call incase Meta adds more methods we aren't supporting on Paper.
But let me know if the call is necessary for some reason I'm missing, we could also add a check to ignore the unsupported methods (see previous commit).
react dev-tools will fail because upstream added the methods "highlightTraceUpdates", "highlightElements", and "clearElementsHighlights" and we only added those for Fabric, not Paper. …
> [0.77] Fix react devtools hitting an assert on launch (#14320)

- change/react-native-windows-efed1837-6111-4f1d-b023-25543bd90757.json
- vnext/Microsoft.ReactNative/Views/DebuggingOverlayViewManager.cpp
Backport of https://github.com/microsoft/react-native-windows/pull/14320
Removes unnecessary call to Super::DispatchCommand, ViewManagerBase will just assert(false) on dispatch command. https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L358. Seemed better just to remove the call incase Meta adds more methods we aren't supporting on Paper.
But let me know if the call is necessary for some reason I'm missing, we could also add a check to ignore the unsupported methods (see previous commit).
react dev-tools will fail because upstream added the methods "highlightTraceUpdates", "highlightElements", and "clearElementsHighlights" and we only added those for Fabric, not Paper. …
> [0.76] Fix react devtools hitting an assert on launch (#14320)

- change/react-native-windows-b37f9813-c7a4-49cd-83a8-808a00b86649.json
- vnext/Scripts/Tfs/Layout-MSRN-Headers.ps1
react-native-windows currently maintains its own forked C++ TurboModule bridging files.
For untouched stuff we copy JSI and TurboModule files from core react-native in `Layout-MSRN-Headers.ps1`.
However, this script misses to copy `Number.h`.
This causes compilation error when trying to import `react/bridging/Bridging.h`, which would be the case for example when using codegen to generate C++ TurboModule (JSI) bindings (note: this is for C++ JSI TurboModules, not react-native-windows's TurboModule system).
```
PS C:\Users\CocoT1\Projects\rn77> yarn example windows
[...]
Time Elapsed 00:00:00.61
✔ Restoring NuGet packages
✔ Auto-linking...
Success: No auto-linking changes necessary. (69ms)
✔ Found Solution: …
```
> Fix Number.h not copied from react-native core

- change/react-native-windows-d345ae30-34cd-425c-97ac-fdf1c22fc508.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/src/js/examples/Modal/ModalOnShow.windows.js
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
Modal accounted for a titlebar height but it doesn't have a titlebar yet. This fixes the height issue and fixes an example in Modal tester where flex makes the modal stretch to the full height of the screen.
tested locally
yes - Fixes Modal giving extra height
> [Fabric] Fix modal height

- change/react-native-windows-c084ae94-ee07-44f4-9f06-077f17355ea0.json
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
When the focused component is removed from the tree it attempts to move focus somewhere else.  If there is no other focusable component, then focus does not get moved, which causes the focus rect to be left in the UI.
> Fix stale focus rects left in UI when last focusable component is removed

- change/react-native-windows-b14f249c-ae04-440c-97dc-bf0831e5d537.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
If the RN instance is already active and a ReactNativeIsland is created with that ReactNativeHost, then there is a brief time between the ReactNativeIsland getting a root tag and when the rootcomponent is created during which an application could call Arrange/Measure on the ReactNativeIsland, and the app will crash.
> Fix issue when calling arrange on an RN Island during load

- change/react-native-windows-b37f9813-c7a4-49cd-83a8-808a00b86649.json
- vnext/Scripts/Tfs/Layout-MSRN-Headers.ps1
Hi. This PR cherry-picks c0be76e207aa68f2ce0d73fa776fe17026a30248 (#14331) into 0.78.
It would be to nice include this one as otherwise JSI/Codegen is broken.
Cheers
Hampus
> [0.78] Fix Number.h not copied from react-native core

- change/react-native-windows-53667472-816f-4d36-b9f3-70b761dd1cf3.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TooltipService.cpp
- The margins on tooltips were not getting scaled correctly for the scale factor, resulting in clipped text at high scale factors.
- Fixed a crash when the tooltip is set to an empty string.
- Tooltips were not respecting the system TextScaleFactor
> Fix tooltips in high dpi

- change/@react-native-windows-codegen-f126650d-d5cd-4a67-a9dd-73f54e0498ef.json
- change/react-native-windows-9737fe71-c849-4e4f-a0ec-ba672ca94168.json
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/codegen/react/components/rnwcore/ActivityIndicatorView.g.h
- vnext/codegen/react/components/rnwcore/AndroidDrawerLayout.g.h
- vnext/codegen/react/components/rnwcore/AndroidHorizontalScrollContentView.g.h
- vnext/codegen/react/components/rnwcore/AndroidProgressBar.g.h
- vnext/codegen/react/components/rnwcore/AndroidSwipeRefreshLayout.g.h
- vnext/codegen/react/components/rnwcore/AndroidSwitch.g.h
- vnext/codegen/react/components/rnwcore/DebuggingOverlay.g.h
- vnext/codegen/react/components/rnwcore/InputAccessory.g.h
- vnext/codegen/react/components/rnwcore/ModalHostView.g.h
- vnext/codegen/react/components/rnwcore/PullToRefreshView.g.h
- vnext/codegen/react/components/rnwcore/SafeAreaView.g.h
- vnext/codegen/react/components/rnwcore/Switch.g.h
- vnext/codegen/react/components/rnwcore/UnimplementedNativeView.g.h
Clang does not allow comparisons of virtual function addresses to be marked as constexpr.  The codegen for components has such statements marked as if constexpr, which will not compile using clang.
The fix I'm making is to just not use constexpr on clang. It'll likely result in slightly larger code on clang.  But most users of the windows codegen are going to be using MSVC, so it's not a big deal.
> Fix build issue building component codegen using clang

- change/react-native-windows-61361492-e98e-45f9-931a-795d9a86919b.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
Currently if a component has a hover state and is at or near the edge of the window, then when the pointer moves out of the window the component may get stuck in the hover state.
The fix is to listen to the ContentIsland's PointerExited event, and properly notify any hovered components that they are no longer hovered.
> Components do not lose hover state if pointer leaves window before it leaves the component

- change/react-native-windows-ca0880f1-4d40-4ab6-9c95-d843aade3939.json
- vnext/Microsoft.ReactNative/Fabric/AbiViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/HostPlatformColor.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/PlatformColorParser.h
In our HostPlatformColor object we had a bool that was representing an undefined color.  There were a couple of places where we were treating this bool as isDefined, instead of isUndefined.  This caused the == operator of Color to return true when comparing any PlatformColors. - Which causes various issues.
With the following component, the text would not change color when pressing the button:
```jsx
const Bootstrap = () => {
const [isHighlight, setIsHighlight] = React.useState(false);
const swapColors = () => {
setIsHighlight(!isHighlight);
};
return (
<View>
<Button title="Press" onPress={swapColors} />
<Text
style={{
color: isHighlight ? PlatformColor('Highlight') : PlatformColor('WindowText'),
}}>
<Text>Text here</Text>
</Text>
</View>
);
};
```
I just removed the whole m_isUndefined …
> Property updates switching between PlatformColors would no-op

- change/@react-native-windows-codegen-f126650d-d5cd-4a67-a9dd-73f54e0498ef.json
- change/react-native-windows-53667472-816f-4d36-b9f3-70b761dd1cf3.json
- change/react-native-windows-9737fe71-c849-4e4f-a0ec-ba672ca94168.json
- change/react-native-windows-ca0880f1-4d40-4ab6-9c95-d843aade3939.json
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative/Fabric/AbiViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TooltipService.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/HostPlatformColor.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/PlatformColorParser.h
- vnext/codegen/react/components/rnwcore/ActivityIndicatorView.g.h
- vnext/codegen/react/components/rnwcore/AndroidDrawerLayout.g.h
- vnext/codegen/react/components/rnwcore/AndroidHorizontalScrollContentView.g.h
- vnext/codegen/react/components/rnwcore/AndroidProgressBar.g.h
- vnext/codegen/react/components/rnwcore/AndroidSwipeRefreshLayout.g.h
- vnext/codegen/react/components/rnwcore/AndroidSwitch.g.h
- vnext/codegen/react/components/rnwcore/DebuggingOverlay.g.h
- vnext/codegen/react/components/rnwcore/InputAccessory.g.h
- vnext/codegen/react/components/rnwcore/ModalHostView.g.h
- vnext/codegen/react/components/rnwcore/PullToRefreshView.g.h
- vnext/codegen/react/components/rnwcore/SafeAreaView.g.h
- vnext/codegen/react/components/rnwcore/Switch.g.h
- vnext/codegen/react/components/rnwcore/UnimplementedNativeView.g.h
Cherry-pick #14397, #14393, #14398 into 0.74
> [0.74] Cherry-pick: High dpi tooltips, platformcolor fix and clang codegen fix

- change/react-native-windows-77840265-2969-48e7-9ab2-ee5877155246.json
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
Fix unstable test Microsoft::React::Test::WinRTWebSocketResourceUnitTest::ConnectSucceeds
The addressed test fails intermittently on CI runs.
Drain/synchronize test DispatchQueue used to emulate the calling thread.
> Prevent race condition in ConnectSucceeds WS unit test

- change/react-native-windows-984ae1a3-5950-4ab1-bebb-44b11bc5b147.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/HostPlatformColor.h
Setting a border color to 'transparent' caused a black border to show up.
There is code that does `if (!borderColor) borderColor = black`.  The bool operator is supposed to check if the color is undefined.  But was also returning false for #00000000.  
I modified the undefined color to have a special token platform color, that way Color::Undefined != Color::Transparent.
I also fixed up an issue in ReactNativeIsland where calling `GetComponentView` on the island before the surface has loaded, would crash.  Now it just returns null.  This was sometimes causing a crash when showing a logbox.
> Fix bool operator on transparent colors returning false

- change/react-native-windows-61268ed7-80f3-488f-a256-b4886d46ab68.json
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/PropertySheets/React.Cpp.props
Allow compiling multiple C++ sources in parallel.
Build times in RNW have jumped to between 35 minutes and over 60 minutes in Continuous Integration.
- Default MSBuild property `MultiProcCL` to `true`.
Initial tests (cached NuGet packages, clean build and target directories) showed the following results on a Windows Dev Box:
- `MultiProcCL = false`: ~37 minutes
- `MultiProcCL = true`: ~6 minutes
About **82%** speed-up.
Should this setting apply to Continuous Integration?\
While it would drastically improve build times, it may compromise predictability and reproducibility of builds.
> Enable parallel C++ compilation

- .editorconfig
- .gitignore
- .prettierignore
- .vscode/settings.json
- Directory.Build.props
- Directory.Build.targets
Allows customizing MSBuild behavior locally through the file system.
Customizing MSBuild logic for local development requires verbose command line tweaking or modifying versioned files.
Allows creating Directory.Build.local.{props,targets} transitory (non-versioned) files.
> Allow non-versioned MSBuild local overrides

- change/react-native-windows-0e5cf153-c8f1-4d45-ab5e-2ae0a2581797.json
- vnext/Scripts/creaternwapp.cmd
- vnext/Scripts/creaternwlib.cmd
This PR imports versions of the `creaternwapp.cmd` and `creaternwlib.cmd` scripts from https://github.com/jonthysell/DevScripts/tree/main/react-native.
To make it easier to create new React Native projects and libraries, we are adding the `creaternwapp.cmd` and `creaternwlib.cmd` scripts to the repository.
Added new scripts to the vnext\Scripts folder
N/A
Verified the scripts still work
> Add creaternwapp.cmd and creaternwlib.cmd scripts

- change/@react-native-windows-automation-c0a9ebab-d210-4090-b544-5ac4c6651079.json
- packages/@react-native-windows/automation/src/AutomationEnvironment.ts
This PR updates the use of `execSync` to `spawnSync` in `@react-native-windows/automation` to avoid potential security vulnerabilities.
There is a CodeQL alert that we're using shell commands unsafely in the automation library to get the name of an appx and then launch it for unit tests.
Closes #14242
Rather than using `execSync`, which is unsafe, we are now using `spawnSync` to execute shell commands in a safer manner.
N/A
I verified that our existing E2E test apps still launch and run as expected with this change.
Replace use of `execSync` with `spawnSync` in `@react-native-windows/automation`
> Replace use of `execSync` with `spawnSync` in `@react-native-windows/automation`

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/desktop.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/universal.yml
- .ado/templates/enable-experimental-winui3.yml
- .ado/templates/enable-fabric-experimental-feature.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/set-experimental-feature.yml
- change/react-native-windows-8c3b9cef-da7b-4f02-9a80-4b1a912d7231.json
- vnext/ExperimentalFeatures.props
- vnext/PropertySheets/WebView2.props
- vnext/PropertySheets/WinUI.props
This PR aims to fix our usage of the Secure PR and/or CI where `UseExperimentalWinUI3` is enabled. This PR standardizes how we enable building with `UseExperimentalWinUI3`.
We are not always building the correct matrix when running Secure PR. Furthermore, we are unnecessarily failing when trying to access internal feeds when we don't need them. The current experimental WinUI3 we're using is in fact publicly available on NuGet.org.
* Created a new ADO pipeline template for enabling UseExperimentalWinUI3 and optionally registering and authenticating to the ProjectReunion feed
* Updated all SecurePR builds to use the new template
* Updated the ADO pipeline for enabling experimental features to be more robust
* Ensure …
> Fix use of ExperimentalWinUI3 in CI / Secure PR

- change/react-native-windows-dee3a16c-0e0f-4af4-b524-b216b0a19255.json
- vnext/src-win/Libraries/Components/Button.windows.js
Without this, Button cannot have support for the Invoke Provider (essential for Accessibility compliance).
https://github.com/microsoft/react-native-gallery/issues/533
- Pass onAccessibilityTap function to the native code
- Add onAccessibilityTap to Button types
Tested locally in playground. 
> Button Should Pass onAccessibilityTap Prop to Native Code

- change/react-native-windows-b86e11e6-8cbc-4602-b53a-e199ce0f6b2e.json
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputShadowNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
Implements basic scrolling within TextInput's.
Note this does not add visible scrollbars.  - But the functionality is much better than without this change, as you can move the cursor around the control to scroll, and layout does not get messed up.
Also includes a minor fixup to the playground app to avoid some flickering on resize when using size to content.
Resolves #14383, #14382, #14380, #14379
Most of the change is telling RichEdit that we support scrolling, and that it should scroll when the cursor moves.  I also put RichEdit into plaintext mode.
> Allow TextInput to scroll

- change/react-native-windows-56f137a7-212a-483c-9771-7bf7c0fad2a8.json
- change/react-native-windows-b25b85e4-b99c-4ba7-92db-ac45afed3cc9.json
- change/react-native-windows-b86e11e6-8cbc-4602-b53a-e199ce0f6b2e.json
- change/react-native-windows-dee3a16c-0e0f-4af4-b524-b216b0a19255.json
- packages/playground/Samples/textinput.tsx
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputShadowNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
- vnext/src-win/Libraries/Components/Button.windows.js
Port #14448, #14407 and #14444 to 0.74
> [0.74] Allow TextInput to scroll

- yarn.lock
Updated the following packages:
* `@babel/runtime@7.27.0`: CVE-2025-27789
* `@babel/helpers@7.27.0`: CVE-2025-27789
To resolve Component Governance alerts.
See above.
N/A
Local build
> [0.78] Update packages for component governance

- packages/e2e-test-app-fabric/test/PressableComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/PressableComponentTest.test.ts.snap
- Testing
Add onHoverIn/Out for Pressable test to expand test coverage for props. 
Add onHoverIn/Out for Pressable test.
> Add onHoverIn/Out Test Example

- change/@office-iss-react-native-win32-5b613811-9db3-472a-8f00-df9930e42014.json
- change/@react-native-windows-cli-15e1bda9-8335-45ad-882e-8dbc494f214c.json
- change/react-native-windows-4f95e690-6339-49ed-95b3-4323ec3f8624.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native/tester/package.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-app-fabric/package.json
- packages/sample-apps/package.json
- packages/sample-custom-component/package.json
- vnext/package.json
- yarn.lock
Part of #14447 to change us from using @react-native-community/cli@15.0.0-alpha.2 to the reccomended version (https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility)
yes
> [0.78] use non-alpha version of @react-native-community/cli

- change/@office-iss-react-native-win32-1f32e075-03c3-4232-9ae9-ca28aa39eaa1.json
- change/@react-native-windows-cli-c1024eab-c1dd-41f1-aeb4-a9fddb1ff67b.json
- change/react-native-windows-4879c892-1776-432b-89eb-868fd1a3dc39.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native/tester/package.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-app-fabric/package.json
- packages/sample-apps/package.json
- packages/sample-custom-component/package.json
- vnext/package.json
- yarn.lock
Part of ##14447 to change us from using @react-native-community/cli@15.0.0-alpha.2 to the reccomended version (https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility)
yes
> [0.77] use non-alpha version of @react-native-community/cli 

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/desktop.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/universal.yml
- .ado/templates/enable-experimental-winui3.yml
- .ado/templates/enable-fabric-experimental-feature.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/set-experimental-feature.yml
- change/react-native-windows-8c3b9cef-da7b-4f02-9a80-4b1a912d7231.json
- vnext/ExperimentalFeatures.props
- vnext/PropertySheets/WebView2.props
- vnext/PropertySheets/WinUI.props
This PR backports #14441 to RNW 0.78.
This PR aims to fix our usage of the Secure PR and/or CI where `UseExperimentalWinUI3` is enabled. This PR standardizes how we enable building with `UseExperimentalWinUI3`.
We are not always building the correct matrix when running Secure PR. Furthermore, we are unnecessarily failing when trying to access internal feeds when we don't need them. The current experimental WinUI3 we're using is in fact publicly available on NuGet.org.
* Created a new ADO pipeline template for enabling UseExperimentalWinUI3 and optionally registering and authenticating to the ProjectReunion feed
* Updated all SecurePR builds to use the new template
* Updated the ADO pipeline for enabling experimental features to be more …
> [0.78] Fix use of ExperimentalWinUI3 in CI / Secure PR

- change/react-native-windows-03816c03-16cc-4afb-94d3-0108b62ed8df.json
- change/react-native-windows-21dbc793-f697-4cf7-b953-f9482a6481f2.json
- vnext/Directory.Build.props
- vnext/Folly/TEMP_UntilFollyUpdate/json.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
- vnext/Folly/cgmanifest.json
This PR bumps Folly to v2024.01.01.00.
Catching up with what upstream is using.
This PR bumps Folly to v2024.01.01.00. It also fixes an issue in Folly and how nugets are published in PR.
Closes #14394
N/A
> [0.74] Bump folly to v2024.01.01.00

- change/react-native-windows-21dbc793-f697-4cf7-b953-f9482a6481f2.json
- change/react-native-windows-f2fa63e6-4162-4d25-95e4-f0811a00225a.json
- vnext/Directory.Build.props
- vnext/Folly/TEMP_UntilFollyUpdate/json.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
- vnext/Folly/cgmanifest.json
This PR bumps Folly to v2024.01.01.00.
Catching up with what upstream is using.
This PR bumps Folly to v2024.01.01.00. It also fixes an issue in Folly and how nugets are published in PR.
Closes #14394
N/A
> [0.75] Bump folly to v2024.01.01.00 

- change/react-native-windows-a6d5e620-66e7-4d2a-8c90-de8920f57845.json
- vnext/Scripts/creaternwapp.cmd
- vnext/Scripts/creaternwlib.cmd
The new `creaternwapp.cmd` and creaternwlib.cmd scripts have an issue where new RN projects won't use the range qualifier in peerDependencies (so you ask for `react-native@^0.74.0` and you get `react-native@0.74.0` even though `react-native@0.74.5` exists).
This PR fixes the script to, when determining which `react` and `react-native` version to use, to look at `react-native-windows`'s devDependency, which is more reliable than the peerDependency.
Unexpectedly having the wrong RN project version causes all sorts of build issues and confusion, and is easy to miss.
See above.
N/A
Verfied it works for new  projects.
> Update creaternw scripts to use RNW devDependencies

- change/react-native-windows-21dbc793-f697-4cf7-b953-f9482a6481f2.json
- change/react-native-windows-c9c75655-093a-46df-b8fc-d59f9ebc572f.json
- vnext/Directory.Build.props
- vnext/Folly/TEMP_UntilFollyUpdate/json.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
- vnext/Folly/cgmanifest.json
This PR bumps Folly to v2024.01.01.00.
Catching up with what upstream is using.
This PR bumps Folly to v2024.01.01.00. It also fixes an issue in Folly and how nugets are published in PR.
Closes #14394
N/A
> [0.76] Bump folly to v2024.01.01.00

- change/react-native-windows-54a72170-7490-4502-8483-62b58bbe76fd.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/playground/Samples/textinput.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Resolves https://github.com/microsoft/react-native-windows/issues/13662 and some part of https://github.com/microsoft/react-native-windows/issues/14380
Support fontFamily in TextInput
https://github.com/user-attachments/assets/5834d969-50a2-414a-b535-64e7b12897d0
https://github.com/user-attachments/assets/13572b60-d530-4d8e-8cf8-e6db7139ce83
If you added tests that prove your changes are effective or that your feature …
> [Fabric] Add Custom Font Family in Text Input

- .ado/templates/react-native-init-windows.yml
- .ado/templates/verdaccio-start.yml
- .ado/templates/verdaccio-stop.yml
- change/react-native-windows-75d0a98d-9db5-4a73-a321-0d0a42767855.json
- vnext/Scripts/creaternwapp.cmd
- vnext/Scripts/creaternwlib.cmd
This PR updates the new project steps in `react-native-init-windows.yml` to use the `creaternwapp.cmd` and `creaternwlib.cmd` scripts instead of calling the steps manually.
The scripts were created to help us tackle the increasingly difficult process of creating new projects (esp. in main) for testing. This PR makes sure that all innovations and fixes in those scripts are also used by our CLI testing.
Removed the new projects tasks and logic from `react-native-init-windows.yml` and instead just call the `creaternwapp.cmd` and `creaternwlib.cmd` scripts. Added a flag to enable using verdaccio (must sometimes be set after project is created) and also moved the configuration for consuming verdaccio into the verdaccio start/stop …
> Use creaternwapp.cmd and creaternwlib.cmd scripts to create new projects in CI

- change/react-native-windows-eed51fa4-43c0-4164-8892-4c3fa0571940.json
- packages/playground/Samples/image.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.h
Implement the onProgress property for the fabric implementation of Image.
Note: At one point there was a TODO for this in our new fabric code.
This property was not available in RNW Paper but could be implemented for Fabric.
See https://reactnative.dev/docs/image#onprogress for details.
Resolves https://github.com/microsoft/react-native-windows/issues/13118 and https://github.com/microsoft/react-native-windows/issues/13752
Added a progress Callback during request start for image downloading …
> [Fabric] Implement onProgress for Image

- change/react-native-windows-99f88013-45df-4134-99df-b0fb86dc5e88.json
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextInputTestPage.tsx
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/playground/Samples/textinput.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputProps.h
Implement the spellCheck property for the fabric implementation of TextInput.
This property was available in RNW Paper via TextInputViewManager.
See https://reactnative.dev/docs/textinput#spellcheck-ios for details.
Implement the autoCorrect property for TextInput in RNW Fabric.
For reference, check the public API documentation: https://reactnative.dev/docs/textinput#autocorrect
Resolves https://github.com/microsoft/react-native-windows/issues/13843 and https://github.com/microsoft/react-native-windows/issues/13134
What changes were made to the codebase to solve the bug, add the functionality, etc. …
> [Fabric] Implement SpellCheck and AutoCorrect for TextInput

- change/react-native-windows-53cc2215-aea1-4487-be63-34056926b427.json
- packages/playground/Samples/scrollViewSnapSample.tsx
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
Implement decelerationRate in ScrollView
Resolves https://github.com/microsoft/react-native-windows/issues/13791
Implement decelerationRate in ScrollView
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.interactions.interactiontracker.positioninertiadecayrate?view=windows-app-sdk-1.6
https://github.com/user-attachments/assets/f22acecf-2f8e-4a3b-8523-150f950bb95c
If you added …
> [Fabric] Implement decelerationRate in ScrollView

- change/react-native-windows-a2bdf157-2fb8-43f8-8541-56ca50021d6c.json
- packages/playground/Samples/scrollViewSnapSample.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
Resolves  https://github.com/microsoft/react-native-windows/issues/13146 and https://github.com/microsoft/react-native-windows/issues/13147
Implement the showsHorizontalScrollIndicator property for the fabric implementation of ScrollView.
This property was available in RNW Paper via ScrollViewManager.
See https://reactnative.dev/docs/scrollview#showshorizontalscrollindicator for details.
Implement the showsVerticalScrollIndicator property for the fabric implementation of ScrollView.
This …
> [Fabric] Implement showsVerticalScrollIndicatorValue and showsHorizontalScrollIndicatorValue for ScrollView

- change/react-native-windows-1dcd74f9-fb9a-4bc3-b8fb-fc5a53c9a661.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-composition/Playground-Composition.rc
- packages/playground/windows/playground-composition/resource.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
- vnext/Microsoft.ReactNative/ReactNativeIsland.idl
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Adds a new SetProperties method to ReactNativeIsland.  This is equivalent to the setAppProperties method here: https://github.com/facebook/react-native/blob/675b51f5628988aece7d3ecbe2ef154645658ec2/packages/react-native/React/Fabric/Surface/RCTFabricSurface.mm#L197
Resolves #14512
Added a menu option in playground to modify the app properties at runtime, which allows the app to modify the initial properties provided to the ReactNativeIsland.
> SetProperties is not exposed on ReactNativeIsland

- change/react-native-windows-2d88d8d6-ef31-45db-a6e4-f51aa3ed5ab0.json
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative.CsWinRT/packages.lock.json
Allow overriding ExperimentalFeatures properties without modifying versioned files.
Properties in ExperimentalFeatures.props are set unconditionally.
This prevents them from being overriden ahead of time by previoulsy imported property files (i.e. Directory.Build.local.props).
Note, properties set in the MSBuild command line always take precedence and are not affected by this issue.
Set all properties in ExperimentalFeatures conditionally (only if a given property hasn't been already set in another properties file).
> Make ExperimentalFeatures overridable through props files

- change/@react-native-windows-cli-7fd60dda-c73f-4b27-83e9-e2fec2b6c1de.json
- packages/@react-native-windows/cli/src/commands/codegenWindows/codegenWindows.ts
Resolves #14387 
Makes a fix to the codegen cli to allow for subpaths in the `jsSrcsDir` option of the codegen config.
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/aae66b5d-6e15-420e-b598-a974f2f53882) | ![image](https://github.com/user-attachments/assets/0c32b0e9-331f-4e0f-80fc-aefcd231955e) |
Locally ran codegen after making the modification inside of `node_modules` of an example project. Would be happy to add a test for this if some guidance were to be provided, as I didn't see any colocated codegen tests nearby.
Should this change be included in the release …
> fix(cli): codegen jsSrcsDir subpath

- change/react-native-windows-eed821fc-4d11-4ca3-a820-682d1aba1977.json
- packages/playground/Samples/image.tsx
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
- vnext/Microsoft.ReactNative/Utils/ImageUtils.h
Implement body in ImageSource property for Image in Fabric.
For reference, check the public API documentation: https://reactnative.dev/docs/image#imagesource
Resolves https://github.com/microsoft/react-native-windows/issues/14543
Implement body in ImageSource property for Image in Fabric.
For reference, check the public API documentation: https://reactnative.dev/docs/image#imagesource
If you added tests that prove …
> [Fabric] Implement Image body in Image Source RequestImage API

- .ado/jobs/playground.yml
- change/react-native-windows-efa98e2b-7308-434d-a16f-77efced3562c.json
- packages/playground/windows/playground-composition/CustomComponent.cpp
- packages/playground/windows/playground-composition/DrawingIsland.cpp
- packages/playground/windows/playground-composition/DrawingIsland.h
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-composition/packages.lock.json
- vnext/ExperimentalFeatures.props
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.h
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/WinUI.props
Updating the WASDK version from 1.7 experimental to a released version.
Mostly this is just removing usages of USE_EXPERIMENTAL_WINUI3.  There are a couple of places where we were using APIs that are still marked as experimental, and so were not part of the final 1.7 release.  In particular ContentIsland.Connected/ContentIsland.Disconnected.
Looking at the usage of these APIs in most normal cases we should be OK without these events. In the edge cases where the wrong thing happens here, there are OnMounted/OnUnmounted APIs exposed on Microsoft.ReactNative.Composition.Experimental.IInternalCompositionRootView which can be called to manually call the code that Connected/Disconnected calls.
What is the motivation for this change? Add a few sentences describing the context and overall goals …
> [0.74] Update WindowsAppSDK version to 1.7.250401001

- change/react-native-windows-38ddfc46-37fc-42ff-90d8-d3f72a15f8a2.json
- packages/playground/Samples/scrollViewSnapSample.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
[Fabric] Implement scrollEventThrottle for ScrollView
Resolves https://github.com/microsoft/react-native-windows/issues/13808
Implement the scrollEventThrottle property for ScrollView in RNW Fabric.
For reference, check the public API documentation: https://reactnative.dev/docs/scrollview#scrolleventthrottle
https://github.com/user-attachments/assets/9fa1d36b-37c5-46b5-85af-37332e085d7e
If you added tests that prove …
> [Fabric] Implement scrollEventThrottle for ScrollView

- .ado/stages.yml
- change/@react-native-windows-cli-274e77bd-2b03-4168-953e-6ad619e120e3.json
- packages/@react-native-windows/cli/src/commands/config/configUtils.ts
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
Updated stages.yml to enable node tests job , uncommented the node tests in stages.yaml so that release as well as continuous pipelines can pickup and test node .
To add node tests in pipeline 
https://github.com/microsoft/react-native-windows/issues/14516
Uncommented the node tests in stages.yaml so that release as well as continuous pipelines can pickup and test node .
no
> Stages.yml is updated to enable node tests job

- change/react-native-windows-cf845cf7-d1f3-4312-b6bf-bfbc99c7eaf6.json
- packages/playground/Samples/index.tsx
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
Core Parity
Refer https://reactnative.dev/docs/activityindicator#hideswhenstopped-ios and https://reactnative.dev/docs/activityindicator#animating
Resolves https://github.com/microsoft/react-native-windows/issues/13743
[Fabric] Implement hidesWhenStopped in ActivityIndicator 
https://github.com/user-attachments/assets/ab8cd809-5ce3-483d-a169-18ceec98a3c0
https://github.com/user-attachments/assets/83c4194b-73ed-4d89-a74 …
> [Fabric] Implement hidesWhenStopped in ActivityIndicator

- change/react-native-windows-16b2c3a5-029f-4454-a2bc-d6a1861a5aab.json
- packages/playground/Samples/text.tsx
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/textlayoutmanager/TextLayoutManager.h
Resolves https://github.com/microsoft/react-native-windows/issues/13829
Related
https://github.com/facebook/react-native/pull/50933
https://github.com/facebook/react-native/issues/50934
[Fabric] Implement minimumFontScale in Text
Refer https://github.com/facebook/react-native/blob/0ad9de86d14a63175029e036af297beaa3b6c743/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L88
Add any relevant screen captures here from before or after your …
> [Fabric] Implement minimumFontScale in Text

- .ado/templates/react-native-init-windows.yml
- change/react-native-windows-ffd49029-f408-419d-85e1-6bdd4b29b3b2.json
- vnext/Scripts/creaternwapp.cmd
- vnext/Scripts/creaternwlib.cmd
This PR fixes the `creaternwapp.cmd` and `creaternwlib.cmd` scripts in CI due to new upstream bugs, but also adds a check to make sure the command isn't run within an existing git repo. The commands for new RN projects are opinionated about how they set up new projects, and can override the settings in existing git repos.
To make sure no one runs these scripts an accidentally messes up their git repo with foreign git hooks, especially *this* repo.
Resolves #14632 
Resolves #14633 
See above.
N/A
Verified the scripts no longer work for creating new projects within this repo.
> Fix creaternwapp.cmd and creaternwlib.cmd

- change/react-native-windows-01615f82-6942-4a39-8608-3e010f4b9009.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/TextInputComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/playground/Samples/textinput.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
New feature.
Implement selectTextOnFocus prop in TextInput. It is implemented in Paper; this PR brings the Fabric implementation.
Resolves #13133 
Created a function that:
- Selects the whole text when the TextInput is focused
- Drops the selection when TextInput loses focus
Text selection will not occur if `clearTextOnFocus` prop is set to `true`. This is purely by design, as the RN documentation doesn't specify what the behavior should be. For reference, if both props are set to true, Android doesn't clear the text on focus and performs the selection, but iOS clears the text input.
Refer https://learn.microsoft.com/en-us/windows/win32/controls/em-setsel
https://github.com/user-attachments/assets/889906f8-c7f2-4ef0-8d70-29eaea46723e
Added e2e tests to TextInputComponentTest and two …
> [Fabric] Implement selectTextOnFocus prop in TextInput

- change/react-native-windows-26d524ee-3303-4cbf-a1d5-2c876d58c088.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
If you have a UIA tool running and set focus to a component before the island, then you get asserts from the CompositionRootAutomationProvider.
This was due to the CompositionRootAutomationProvider never having the island set on it.
> Properly hook up root uia provider to island

- change/react-native-windows-03455d8f-7438-42c3-961f-8250bdfda7ae.json
- change/react-native-windows-85efbfed-f980-402a-b3de-a9d07b97923f.json
- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
- packages/e2e-test-app-fabric/test/__snapshots__/AccessibilityTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewProps.h
- vnext/src-win/Libraries/Components/View/ViewAccessibility.d.ts
- vnext/src-win/Libraries/NativeComponent/BaseViewConfig.windows.js
Implementing two new accessibility props
Resolves [#13348 , #14657 ]
Tested in playground and RN tester App
Implementation of `accessibilityAccessKey` and `accessibilityItemType`
> [Fabric] Implementation of accessibilityAccessKey and accessibilityItemType

- .ado/templates/react-native-init-windows.yml
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
Backporting PR #14678 to RNW 0.77.
Resolves #14677
N/A
> [0.77] Fixing unreferenced parameter warnings as errors in Playground-Composition and elsewhere

- .ado/templates/react-native-init-windows.yml
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
Backporting PR #14678 to RNW 0.78.
Resolves #14677 
N/A
> [0.78] Fixing unreferenced parameter warnings as errors in Playground-Composition and elsewhere

- .ado/templates/react-native-init-windows.yml
- change/@react-native-windows-automation-0671783d-ada6-43fb-9882-81d449c16124.json
- change/@react-native-windows-automation-channel-243f361c-0d3e-471e-a30f-bbaec98e4a20.json
- change/@react-native-windows-automation-commands-638e11af-371a-497c-8d4a-c794b3f6c67b.json
- change/react-native-windows-8a96b809-808a-4cd0-a831-f916f97789ed.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/bridging/CallbackWrapper.h
Backporting PR #14678 to RNW 0.75.
Resolves #14677
N/A
> [0.75] Fixing unreferenced parameter warnings as errors in Playground-Composition and elsewhere

- .ado/templates/react-native-init-windows.yml
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
Backporting PR #14678 to RNW 0.74.
Resolves #14677
N/A
> [0.74] Fixing unreferenced parameter warnings as errors in Playground-Composition and elsewhere

- change/react-native-windows-ffcbc2ee-7f53-4f81-b199-38248cc85503.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
When an island is small, the loading string in the loading bar gets cut off.
Using the new adjustsFontSizeToFit code allows us to easily scale the size of the text to fit in smaller sizes.
> Scale loading bar text when island is super small

- change/react-native-windows-9adb4921-0e07-4622-8839-b36a3e017a3a.json
- vnext/Microsoft.ReactNative/CallInvokerWriter.cpp
- vnext/Microsoft.ReactNative/CallInvokerWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Optimize CallInvokerWriter to avoid writing to a intermediate dynamic object if we can write the data directly into JS.
When I switched TMs from JSDispatcherWriter to CallInvokerWriter I didn't implement the optimization to avoid the dynamic.  This fill in that gap restoring the previous perfomance.
Resolves #14668
> Reenable optimization in TMs to avoid going through a dynamic for callbacks/promises

- .ado/templates/react-native-init-windows.yml
- change/@react-native-windows-automation-0671783d-ada6-43fb-9882-81d449c16124.json
- change/@react-native-windows-automation-channel-243f361c-0d3e-471e-a30f-bbaec98e4a20.json
- change/@react-native-windows-automation-channel-4c7447b5-805b-4261-a652-820c2d3ed0cc.json
- change/@react-native-windows-automation-commands-638e11af-371a-497c-8d4a-c794b3f6c67b.json
- change/react-native-windows-00e3a2ef-4351-4984-8e44-3b509368727f.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/bridging/CallbackWrapper.h
Backporting PR #14678 to RNW 0.76.
Resolves #14677
N/A
> [0.76] Fixing unreferenced parameter warnings as errors in Playground-Composition and elsewhere

- change/react-native-windows-ad718918-4357-4159-a94e-c6d14bb6c3bf.json
- vnext/Microsoft.ReactNative/CallInvokerWriter.cpp
- vnext/Microsoft.ReactNative/CallInvokerWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/Shared/Shared.vcxitems
In some cases, JS code using await will not run the continuation until some other event triggers JS code to run.
Callbacks from TurboModules were running through the JSDispatcher, rather than the CallInvoker. On Paper the JSDispatcher is built on top of CallInvoker, and so calls into a TurboModule callback will trigger continuations after the JS code completes.
In new arch, JS can run in multiple threads, so we should use the CallInvoker to guarantee the callback can safely enter the JS runtime.  But also to ensure that continuations get triggered after the JS code completes.
> [0.74] Fix await on new arch - switching to CallInvoker for TM callbacks

- change/react-native-windows-fc2b9290-c8f1-4b30-88d1-cfb20767315d.json
- vnext/templates/cpp-app/template.config.js
- vnext/templates/cpp-lib/template.config.js
- vnext/templates/old/generateWrapper.js
- vnext/templates/old/uwp-cpp-app/template.config.js
- vnext/templates/old/uwp-cs-app/template.config.js
This PR updates the descriptions for the new project templates to be more user-friendly and informative.
As we are in the process of deprecating and/or changing the defaults for templates, I want to make sure we have clear consistent documentation of what each template looks like.
Updated the descriptions and removed the wrapper code that allowed for the (now removed) old lib templates.
Verified `init-windows --list` works.
Fix descriptions for new project templates
> Fix descriptions for new project templates

- change/react-native-windows-3c8e3cc4-43d0-4278-8808-fef1574c5b17.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
Redbox errors from Transform errors are almost unreadable.  This change make it much easier to read the error. 
Also fixed a crash reloading an already crashed instance.
Reading the JSON with color codes within it is very hard.
> Clean up error messages

- change/@office-iss-react-native-win32-7ff6b9f3-7aac-4292-895e-0e1bf3205653.json
- change/@rnw-scripts-integrate-rn-76872c2b-b189-4a34-8b3d-068d0c640812.json
- change/react-native-windows-6b9d9648-7997-46de-b216-67d2ba2e4ac1.json
- packages/@office-iss/react-native-win32/package.json
- packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts
- vnext/package.json
- yarn.lock
`react-shallow-renderer` was removed upstream in 0.75 (see https://github.com/facebook/react-native/commit/ffc0640bf8fae7c12427b307dffe114212da519a). It is currently causing warnings because RN has moved to React 19:
```
➤ YN0060: │ react is listed by your project with version 19.0.0 (pa7126), which doesn't satisfy what react-shallow-renderer (via react-native-windows) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react is listed by your project with version 19.0.0 (pdb265), which doesn't satisfy what react-shallow-renderer (via react-native-windows) and other dependencies request (but they have non-overlapping ranges!).
```
All references to `react-shallow-renderer` have been removed.
n/a
Tests …
> fix: remove unused `react-shallow-renderer` dependency

- change/react-native-windows-d485bfde-7e07-409b-949c-3c79e2e9c4ed.json
- vnext/templates/cpp-lib/windows/MyLib/MyLib.cpp
- vnext/templates/cpp-lib/windows/MyLib/MyLib.h
As we are creating new documentation for implementing native modules, this PR updates the links used in the `cpp-lib` template.
The old docs may eventually retire and therefore break the links.
See above.
N/A
N/A
Update native module doc links in cpp-lib template
> Update native module doc links in cpp-lib template

- change/react-native-windows-1ff7a358-a5fe-45d6-8df4-ecd913ae9509.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewEventEmitter.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/MouseEvent.h
When moving a pointer from a view with a hover handler, to an empty space within the rootview, or outside of the rootview, the hover would get stuck.
Resolves #14672
Prior to this change we were handling firing the PointerIn/Out/Enter/Leave events from windows platform code in ComponentEventHandler.  Since this code was written, core introduced a PointerEventsProcessor which takes pointermove events from the platform code and does the tracking of which component have hover state, and firing the appropriate JS pointer events.
Since PointerEventsProcessor will handle firing most of the pointer events, we no longer need to in ComponentEventHandler.  However there are some specific cases we need to handle.  In particular when the pointer …
> Pointer events

- .ado/jobs/cli-init-windows.yml
- .ado/jobs/desktop.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/jobs/universal.yml
- .ado/templates/enable-experimental-winui3.yml
- .ado/templates/enable-fabric-experimental-feature.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/upload-build-logs.yml
This PR makes it clearer which property to use with the `.ado/templates/run-windows-with-certificates.yml` and fixes where it was used wrong in `.ado/jobs/integration-test.yml`.
Unbreak CI and prevent future mistakes.
Rename `deployOption` parameter into more understandable `moreRunWindowsArgs` in `.ado/templates/run-windows-with-certificates.yml`
Also fixed issue in  `.ado/jobs/integration-test.yml` to unblock CI.
N/A
Verifying CI
> Rename `deployOption` parameter into more understandable `moreRunWindowsArgs` in `.ado/templates/run-windows-with-certificates.yml`

- change/react-native-windows-68a05a4e-5601-409f-85ce-8bdc6b706608.json
- packages/playground/Samples/image.tsx
- vnext/src-win/Libraries/Image/Image.windows.js
Add aria-level, aria-posinset and aria-setsize in Image
Resolves https://github.com/microsoft/react-native-windows/issues/14722
Add aria-level, aria-posinset and aria-setsize in Image.windows.js, this file is already overridden.
Call Stack:
```
Image.windows.js
ImageComponentView::updateProps
ViewComponentView::updateProps
ComponentView::updateAccessibilityProps
```
Tested in playground
Should this change be included in the release notes: YES
Add a brief summary of the change to use in the release notes for the next release: Add aria-level, aria-posinset and aria-setsize in Image
> Add aria-level, aria-posinset and aria-setsize in Image

- change/@office-iss-react-native-win32-bb0a2f17-47f8-4b3c-a3d5-83f59f87b208.json
- change/react-native-windows-9fe6828d-4ba7-4748-933a-b07d1f404589.json
- packages/@office-iss/react-native-win32-tester/src/js/components/TextWin32Test.tsx
- packages/@office-iss/react-native-win32-tester/src/js/components/ViewWin32Test.tsx
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Theming/ThemingModuleAPI.tsx
- packages/@office-iss/react-native-win32/src-win/Libraries/Components/TextInput/Tests/TextInputTest.tsx
- packages/@office-iss/react-native-win32/src-win/Libraries/Components/Touchable/Tests/TouchableWin32Test.tsx
- packages/@office-iss/react-native-win32/src-win/Libraries/Image/Tests/ImageWin32Test.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Flyout/FlyoutExample.windows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Glyph/GlyphExample.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardExample.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardExtensionExample.windows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardFocusExample.windows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/ControlStyleTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/ImageTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/LoginTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/SelectableTextTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextHitTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextInputTestPage.tsx
- packages/@react-native-windows/tester/src/js/examples-win/Popup/PopupExample.windows.tsx
- packages/@react-native-windows/tester/src/js/examples-win/TransferProperties/TransferPropertiesExample.tsx
- packages/@react-native-windows/tester/src/js/examples-win/XAML/XAMLExample.tsx
- vnext/src-win/Libraries/Components/Keyboard/KeyboardExt.tsx
- yarn.lock
> Update lock file to only bring in @types/react 19 - fix a few type errors from 18=>19 bump

- change/react-native-windows-b47cf142-681b-41f5-8ac6-d07b04f55165.json
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Added support for selectionColor in TextInput component
Added support for selectionColor in TextInput component as part of parity
https://github.com/microsoft/react-native-windows/issues/13132
added the selection color change detection in the updateProps and implemented the selection color handling in the TxGetSysColor method
https://github.com/user-attachments/assets/addf0a79-b011-4d6f-a202-01828926422f
tested in playground
yes
Added support for selectionColor in TextInput component
> Fabric : Added support for selectionColor in TextInput component 

- change/react-native-windows-f5824696-b0ed-4c23-a443-5f00a7ac5569.json
- vnext/Scripts/creaternwapp.cmd
This PR fixes broken PR checks when creating new RN app projects with `@react-native-community/cli`, by trying to find a better template for the base project than the RN community CLI chooses.
When the `@react-native-community/cli init` command is told to make a project with **any** RN version that is a nightly, it ignores that version and assumes the user **always** wants the very latest nightly template form the community instead. But there is no guarantee that this latest nightly template works, and it explicitly doesn't support any RN version other than the very latest nightly.
As our main branch only integrates to the nightly versions from the upstream react-native main branch, and by definition we can't integrate ahead of …
> creaternwapp.cmd: Override RN CLI nightly template

- .ado/jobs/universal.yml
- .gitignore
- Directory.Build.props
- change/react-native-windows-1c48c39f-0038-40a8-a646-b7f2e2f9aa73.json
- packages/e2e-test-app/package.json
- vnext/Directory.Build.props
This PR fixes it so every project in the repo, unless explicitly specified, builds locally **with** the nuget lock files and forced evaluation, but ensures external projects build **without** nuget lock files and forced evaluation.
This is primarily to fix `e2e-test-app` failing to build locally.
Fix `e2e-test-app` not building locally with `run-windows`, and prevent our lock file requirements form leaking outside of the repo.
The published `Directory.Build.props` file will disable using lock files by default, but the unpublished, in-repo `Directory.Build.props` file will enable using lock files by default.
Also, since msbuild from the command line ignores the RestoreForceEvaluate specified anyway, which causes `e2e-test-app` (and any …
> Force all in-repo projects to build locally with RestoreForceEvaluate

- change/@react-native-windows-cli-d1794f85-8985-4fcd-b5c0-50b289c776d9.json
- change/react-native-windows-bd20914d-b8fe-423d-834a-6caf8cb49b9c.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- vnext/templates/cpp-app/template.config.js
- vnext/templates/old/generateWrapper.js
- vnext/templates/old/uwp-cpp-app/template.config.js
This PR changes the default template for `init-windows` to the New Architecture `cpp-app` template.
Starting in RNW 0.80.0, the New Architecture will be the default for new apps.
Resolves #13935
Resolves #14749 
Switched the default from `old\uwp-cpp-app` to `cpp-app` and updated the descriptions of both.
N/A
Verified the default changes when listing the available templates.
Change `init-windows` default new app template to New Architecture
> Change `init-windows` default new app template to New Architecture

- change/@react-native-windows-cli-2c1aab12-ed30-48da-ad94-6a45e37c4a3f.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
This PR fixes the issue where telemetry reports the value of the template before it's calculated.
The template default, when no option was provided, is calculated after telemetry records the value, so it was always blank in such cases.
Resolves #14749
Updated `initWindowsOptions` to include the current template default.
N/A
Verified the value appears in the debugger.
Fix `init-windows` template default not set for telemetry purposes
> [0.77] Fix `init-windows` template default not set for telemetry purposes

- .ado/templates/publish-build-artifacts.yml
- .ado/variables/shared.yml
> Disable SBOM in Non-Production ADO Pipelines

- .ado/templates/publish-build-artifacts.yml
- .ado/variables/shared.yml
This PR backports PR #14775 to RNW 0.79.
Closes #14774
N/A
N/A
> [0.79] Disable SBOM in Non-Production ADO Pipelines

- .ado/templates/publish-build-artifacts.yml
- .ado/variables/shared.yml
This PR backports PR #14775 to RNW 0.75.
Closes #14774
N/A
N/A
> [0.75] Disable SBOM in Non-Production ADO Pipelines

- change/@react-native-windows-cli-34ba2de8-d376-4c25-bc3d-fe3c53f1787c.json
- packages/@react-native-windows/cli/src/commands/config/configUtils.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
This PR adds warnings to the `run-windows` and `init-windows` CLI commands to warn about using old architecture projects.
To warn users that their project is using the old architecture and that they should upgrade to the new architecture, as the old architecture will be deprecated.
Resolves #13936
See above.
N/A
Verified commands show the warning
Add warning to CLI commands about using the old architecture
> Add warning to CLI commands about using the old architecture

- .ado/templates/publish-build-artifacts.yml
- .ado/variables/shared.yml
This PR backports PR #14775 to RNW 0.77.
Closes #14774
N/A
N/A
> [0.77] Disable SBOM in Non-Production ADO Pipelines

- change/@react-native-windows-cli-2c1aab12-ed30-48da-ad94-6a45e37c4a3f.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
This PR fixes the issue where telemetry reports the value of the template before it's calculated.
The template default, when no option was provided, is calculated after telemetry records the value, so it was always blank in such cases.
Resolves #14749
Updated `initWindowsOptions` to include the current template default.
N/A
Verified the value appears in the debugger.
Fix `init-windows` template default not set for telemetry purposes
> [0.79] Fix `init-windows` template default not set for telemetry purposes

- change/@react-native-windows-cli-2c1aab12-ed30-48da-ad94-6a45e37c4a3f.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
This PR fixes the issue where telemetry reports the value of the template before it's calculated.
The template default, when no option was provided, is calculated after telemetry records the value, so it was always blank in such cases.
Resolves #14749
Updated `initWindowsOptions` to include the current template default.
N/A
Verified the value appears in the debugger.
Fix `init-windows` template default not set for telemetry purposes
> [0.78] Fix `init-windows` template default not set for telemetry purposes

- change/@react-native-windows-cli-2c1aab12-ed30-48da-ad94-6a45e37c4a3f.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
This PR fixes the issue where telemetry reports the value of the template before it's calculated.
The template default, when no option was provided, is calculated after telemetry records the value, so it was always blank in such cases.
Resolves #14749
Updated `initWindowsOptions` to include the current template default.
N/A
Verified the value appears in the debugger.
Fix `init-windows` template default not set for telemetry purposes
> [0.76] Fix `init-windows` template default not set for telemetry purposes

- .ado/stages.yml
- .ado/templates/publish-build-artifacts.yml
- .ado/variables/shared.yml
This PR backports PR #14775 to RNW 0.74.
Closes #14774
N/A
N/A
> [0.74] Disable SBOM in Non-Production ADO Pipelines

- change/react-native-windows-82bcd92e-18b7-42d0-b6f0-dc428b565d5d.json
- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
- packages/e2e-test-app-fabric/test/__snapshots__/AccessibilityTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewProps.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewProps.h
- vnext/src-win/Libraries/Components/View/View.windows.js
- vnext/src-win/Libraries/Components/View/ViewAccessibility.d.ts
- vnext/src-win/Libraries/Components/View/ViewPropTypes.windows.js
- vnext/src-win/Libraries/NativeComponent/BaseViewConfig.windows.js
Resolves [#14578 ]
Tested using playground and RNTester
Implementation of accessibilityDescription
> [Fabric] Implementation of accessibilityDescription

- change/react-native-windows-435e1359-4961-4938-9b95-12d1e464146f.json
- vnext/src-win/Libraries/Components/Flyout/Flyout.js
- vnext/src-win/Libraries/Components/Popup/Popup.js
While building an app in the New Architecture template, if you use either `<Flyout />` or `<Popup />` you'll be met with the unsupported Fabric view red box. This error is displayed from RN core.
Additionally, we can display a Metro warning to make the error more clear to the user - that they should be migrating to `<Modal />`
Resolves #14671 
1. Detects if we're running Fabric via `global.nativeFabricUIManager`
2. Outputs a warning via `console.warn` in the contructors of `Flyout` and `Popup`
| Collapsed Warning | Expanded Warning |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/f0dd37d0-3bc3-45f7-ae6b-e96b9a8cabf1) | ![image](https://github.com/user-attachments/assets/da6c5197-1e25-4ae1-9c5a-3d77b351ca9c) …
> fix(new-arch): metro warning for Flyout/Popup

- change/react-native-windows-7172b34b-01bd-4b5b-b79c-df223ff0014c.json
- packages/e2e-test-app-fabric/test/__snapshots__/AccessibilityTest.test.ts.snap
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/AccessibilityProps.cpp
- vnext/overrides.json
To set the control type for all accessibility roles
Resolves #14845
Forked a cpp file react native side
Before:
After:
Before Button's role was set to group , but after overriding it. The role correctly mapped.
> [Fabric] Override accessibilityProps.cpp for resolving sev1 bug in gallery app

- change/@react-native-windows-telemetry-f2d320b6-f694-4695-a650-b3b0c1519a68.json
- packages/@react-native-windows/telemetry/package.json
- yarn.lock
This PR removed the unneeded `@azure/core-auth` dependency from `@react-native-windows/telemetry`.
To unblock broken CI due to the dependency change made by `@azure` packages.
Resolves #14912 
See above.
N/A
Verified our packages still work
Removed unneeded `@azure/core-auth` dependency
> Removed unneeded `@azure/core-auth` dependency

- change/@react-native-windows-telemetry-7094a1dc-6053-4c29-82e3-d4b33c4fc036.json
- packages/@react-native-windows/telemetry/package.json
- yarn.lock
This backports PR #14919 to RNW 0.78.
This PR removed the unneeded `@azure/core-auth` dependency from `@react-native-windows/telemetry`.
To unblock broken CI due to the dependency change made by `@azure` packages.
Resolves #14912
See above.
N/A
Verified our packages still work
Removed unneeded `@azure/core-auth` dependency
> [0.78] Removed unneeded `@azure/core-auth` dependency

- change/react-native-windows-ae44eda2-ce08-4405-916b-db6f08ee6786.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
Implement snapToAlignment property for ScrollView in Fabric
Resolves #13148 
Implement snapToAlignment property for ScrollView in Fabric
https://reactnative.dev/docs/scrollview#snaptoalignment
Refer IOS implementation https://github.com/facebook/react-native/blob/618279508159191f2b11c0b20446f91e82a27abf/packages/react-native/React/Views/ScrollView/RCTScrollView.m#L833
The `snapToAlignment` property was available in RNW Paper via ScrollViewManager but missing from the Fabric implementation, causing a parity gap between the two architectures.
We came up with this implementation to ensure that snap points align correctly within the viewport depending on the desired alignment. Since snap positions are relative to the start edge by …
> [Fabric] Implement snapToAlignment property for ScrollView 

- change/react-native-windows-10692328-3799-41d8-8663-4965fdd044fb.json
- yarn.lock
Updated the following packages:
* 'tar-fs [CVE-2024-12905](https://github.com/advisories/GHSA-8cj5-5rvv-wf4v)
To resolve Component Governance alerts.
(https://github.com/advisories/GHSA-8cj5-5rvv-wf4v)
Local build
> [0.79] Bump tar-fs from 3.0.8 to 3.1.0 for component governance

- change/react-native-windows-b24bafa9-f8e5-4f4b-801d-86e84ba9a69c.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/playground/Samples/textinput.tsx
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputEventEmitter.h
Added support for the scrollEnabled, OnScroll  prop for the TextInput component.
Resolves #13129 , #13130
i)Implemented ScrollEVent Handling for TexInput.
ii)Implemented onScroll Props's Event Emitter
Used the IOS implementation here i.e 
i)If scrollEnabled prop is set to false means , onScroll event won't fire.
ii)If ScrollEnabled set to true means, we can use the keyboard to move up , but onScroll event won't be triggered.
https://github.com/user-attachments/assets/6e15a0ba-dbac-441c-9bd5-c220a2511462
Tested In playground.
Should this change …
> [Fabric] Implementation of scrollEvent Handling and scrollEnabled,OnScroll prop for TextInput

- yarn.lock
Updated the following packages:
compression@1.8.1
on-headers@1.1.0
A bug in on-headers versions < 1.1.0 may result in response headers being inadvertently modified when an array is passed to response.writeHead()
Resolves #15005 
Updated the yarn.lock to point to the new versions.
Steps to upgrade:
1. Delete the older version from yarn.lock file
2. Execute yarn command so it can fetch the new versions.
> Update packages for component governance

- change/react-native-windows-47643b4d-f7e0-4d08-9fa1-f3612b5a39db.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Implement `TxSetCapture` which allows RichEdit to capture the mouse input, so that the user can continue to select text if the mouse leaves the bounds of richedit during the mouse drag gesture.
I also switched scrollview's VisualInteractionSourceRedirectionMode to not redirect scrollwheel input to the compositor, which was stealing it away from other components -causing scrolling not to work.
Resolves #14974
> TextInput should capture mouse on mouse down

- change/react-native-windows-bcf77be5-d1cd-4b1a-9756-3de4607890e5.json
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
Changes made to raise UIA Changed Event if toggle state changes.
Changing toggle doesn't notify the UIA Clients.
Resolves [#14608]
Changes made to notify UIA Clients, if toggle state changes
https://github.com/user-attachments/assets/2aa253ca-bd16-48c7-bc27-c55b7cb4cc04
Tested in Playground.
> [Fabric] Raising UIA Event if Toggle State Changes in Switch Component

- change/react-native-windows-8aaaff79-a2a7-4bd6-af5f-ecee696abe44.json
- change/react-native-windows-a648cb52-86ff-47b1-b2be-04d168a7f110.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
The accessibilityAnnotation property was introduced in RNW. However, we did not implement logic to raise a UIA change event when its values are updated.
The accessibilityAnnotation property was introduced in RNW. However, we did not implement logic to raise a UIA change event when its values are updated.
Resolves [#14999]
Added events for the below properties.
UIA_AnnotationAnnotationTypeIdPropertyId
UIA_AnnotationAnnotationTypeNamePropertyId
UIA_AnnotationAuthorPropertyId
UIA_AnnotationDateTimePropertyId
Developed in mac, Could not able to test.
Developed in mac, Could not able to test.
Added UIA …
> [Fabric] Added UIA Event Triggers for accessibilityAnnotation Property Changes

- change/@react-native-windows-cli-df0889c3-e18b-4f66-82ef-3b55c9294c4b.json
- change/@react-native-windows-telemetry-2e2f5bfc-794a-42c2-8ec0-fccb4e6e19cf.json
- change/react-native-windows-3887e0c3-2833-4287-ae46-2fa1626ae551.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/e2etest/architecturePrompt.test.ts
- packages/@react-native-windows/cli/src/e2etest/initWindows.test.ts
- packages/@react-native-windows/cli/src/utils/architecturePrompt.ts
- packages/@react-native-windows/cli/src/utils/oldArchWarning.ts
- packages/@react-native-windows/cli/src/utils/telemetryHelpers.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
Resolves #15027
Adds a yes/no prompt in init-windows and if user wants new arch then will switch to that instead.
Tested locally
https://github.com/user-attachments/assets/42c4e53a-afaf-4f82-80d3-ef52 …
> Update CLI to show static warning for old architecture in run-windows and interactive prompt for init-windows 

- change/@react-native-windows-cli-df0889c3-e18b-4f66-82ef-3b55c9294c4b.json
- change/@react-native-windows-telemetry-2e2f5bfc-794a-42c2-8ec0-fccb4e6e19cf.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- packages/@react-native-windows/cli/src/commands/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/e2etest/architecturePrompt.test.ts
- packages/@react-native-windows/cli/src/e2etest/initWindows.test.ts
- packages/@react-native-windows/cli/src/utils/architecturePrompt.ts
- packages/@react-native-windows/cli/src/utils/oldArchWarning.ts
- packages/@react-native-windows/cli/src/utils/telemetryHelpers.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
Resolves #15027
Adds a yes/no prompt in init-windows and if user wants new arch then will switch to that instead.
Tested locally
https://github.com/user-attachments/assets/42c4e53a-afaf-4f82-80d3-ef52 …
> [Cherry-pick] Update CLI to show static warning for old architecture in run-windows and interactive prompt for init-windows 

- change/react-native-windows-4046d3e2-cc00-459e-b62d-4489b3ef14d1.json
- change/react-native-windows-b93a8310-8489-4f09-8497-eb5807c505b9.json
- change/react-native-windows-bcf77be5-d1cd-4b1a-9756-3de4607890e5.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionTextRangeProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
- vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
Accessibility fixes cherry picked.
commit ids
https://github.com/microsoft/react-native-windows/commit/dea9967bf2ce3071ee00e35d5f6fd7554d4f0222
https://github.com/microsoft/react-native-windows/commit/b72b6b3ca8e243c25f4963793adfb2da45409cb7
https://github.com/microsoft/react-native-windows/commit/3e8db0cd192b74a23ad8ba4bcac922e04abec808
Made Accessibility Code changes
If you added tests that prove your changes are effective or that your feature works, add a …
> [Cherry pick 14995 15023 15088] Latest Accessibility Fixes for Fabric

- change/react-native-windows-8a4ff7bf-ac06-4eb1-9a58-378dc5d976fa.json
- packages/playground/Samples/scrollViewSnapSample.tsx
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
To fix scrollview recent regression [snapAlignmnet and snapToInterval] and cherry-pick parity [onMomentumScrollBegon and onMomentumScrollEnd]
Cherrypicks 34d1771bd47980c0b5c05172eb63e6f7cab89299
Revert https://github.com/microsoft/react-native-windows/commit/6bd0793c1a9e2afd31ac1f00d3b0eb5bb8138e1f and https://github.com/microsoft/react-native-windows/commit/2cde3f11b7c67db52b6b56203cc3df560ac48ea7
To fix scrollview recent regression and cherry-pick parity
Resolves https://github.com/microsoft/react-native-windows/issues/15171 and https://github.com/microsoft/react-native-windows/issues/15177
> Cherrypick Scrollview parity and revert Scrollview regression PRs for stable 0.80

- .ado/image/rnw-img-vs2022-node18.json
- change/@react-native-windows-cli-cb2e9933-1fce-43c6-97f6-472cab6c074e.json
- change/react-native-windows-fb6c6f15-d1ea-4163-958f-6019b215a52a.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Debug.pubxml
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Release.pubxml
- vnext/Microsoft.ReactNative.Managed.CodeGen/packages.lock.json
- vnext/Scripts/rnw-dependencies.ps1
PR Pipelines are blocked as .NET6 is no longer supported.
Resolves https://github.com/microsoft/react-native-windows/issues/15149
Updated individual projects to net8.0 framework
Ensured all the nuget packages are installed from the pipeline
Ensured net8 artifact is installed on the VM.
All tests are passing on Pipeline
> [0.79-stable] Upgrade dotnet

- .ado/image/rnw-img-vs2022-node18.json
- change/@react-native-windows-cli-8af3b340-b959-4154-9057-6ec040e82150.json
- change/react-native-windows-87037c9a-0b79-4a87-a88a-d99aa9e181c3.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Debug.pubxml
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Release.pubxml
- vnext/Microsoft.ReactNative.Managed.CodeGen/packages.lock.json
- vnext/Scripts/rnw-dependencies.ps1
PR Pipelines are blocked as .NET6 is no longer supported.
Resolves https://github.com/microsoft/react-native-windows/issues/15149
Updated individual projects to net8.0 framework
Ensured all the nuget packages are installed from the pipeline
Ensured net8 artifact is installed on the VM.
All tests are passing on Pipeline
> [0.78] Upgrade to dotnet 8

- yarn.lock
Upgraded following packages
tar-fs from 3.0.9 to 3.1.1 
tar-fs from  2.1.3 to 2.1.4 
Upgraded to tar-fs to fix security vulnerabilities
Resolves #15200 
Updated the yarn.lock to point to the new versions.
Steps to upgrade:
Delete the older version from yarn.lock file
Execute yarn command so it can fetch the new versions.
Should this change be included in the release notes: _indicate :no_
> [0.79] Bump  tar-fs from 3.0.9 to 3.1.1 &  2.1.3 to 2.1.4 for component governance

- change/react-native-windows-0f849b5f-40cc-4647-829d-3358479ea031.json
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/jsi/test/testlib.cpp
Fixes C++ compilation errors in the JSI SetRuntimeData [ JSI : 20 ] test that were causing build failures.
ref for source code :
https://github.com/microsoft/hermes-windows/blob/main/API/jsi/jsi/jsi.cpp#L469
https://github.com/microsoft/hermes-windows/blob/main/API/jsi/jsi/jsi.cpp#L512
commented in integration ref : https://github.com/microsoft/react-native-windows/pull/14991 , hence enabling was important to maintain code sanity .
https://github.com/microsoft/react-native-windows/issues/15134
Fixed UUID namespace and possible data loss in type conversion
Should this change be included in the release …
> [Fix] JSI RuntimeData test compilation errors with UUID namespace and override specifiers

- change/react-native-windows-aca77b5b-e0c0-4051-bb1d-70c3e69bec86.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
Fixing UIA Clipping property for Modal Component.
Cherry-pick cc9d7a0
Bug fix
Will fix the UIA clipping state of Modal Component.
Resolves [microsoft/react-native-gallery/issues/650]
UIA Clipping property for Modal Component is fixed.
> [0.80][Fabric] Fix UIA Clipped Property for Modal Component
