ReactWindows/ReactNative.Tests/Bridge/JavaScriptModuleBaseTests.cs, ReactWindows/ReactNative.Tests/Bridge/JavaScriptModuleRegistryTests.cs, ReactWindows/ReactNative.Tests/Internal/MockInvocationHandler.cs, ReactWindows/ReactNative.Tests/Modules/Core/RCTNativeAppEventEmitterTests.cs, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative.Tests/UIManager/AppRegistryTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/RCTEventEmitterTests.cs, ReactWindows/ReactNative/Bridge/JavaScriptModuleBase.Generated.cs, ReactWindows/ReactNative/Bridge/JavaScriptModuleBase.Generated.tt, ReactWindows/ReactNative/Bridge/JavaScriptModuleBase.cs, ReactWindows/ReactNative/Modules/Core/RCTNativeAppEventEmitter.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/UIManager/AppRegistry.cs, ReactWindows/ReactNative/UIManager/Events/RCTEventEmitter.cs
Additionally, includes unit tests for the current set of core JavaScript modules.
Also refactors the way that implementations of JavaScript modules trigger the invocation, using the CallerMemberNameAttribute to capture the name of the method, rather than passing it in explicitly.
=> Fixes #15 - Adds unit tests to JavaScriptModuleBase

ReactWindows/ReactNative.Tests/Bridge/ReactContextNativeModuleBaseTests.cs, ReactWindows/ReactNative.Tests/Internal/Constants/DictionaryHelpers.cs, ReactWindows/ReactNative.Tests/Internal/JavaScriptHelpers.cs, ReactWindows/ReactNative.Tests/Internal/MockEvent.cs, ReactWindows/ReactNative.Tests/Internal/MockJavaScriptExecutor.cs, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventTests.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative/Bridge/CatalystInstance.cs, ReactWindows/ReactNative/Bridge/IJavaScriptExecutor.cs, ReactWindows/ReactNative/Bridge/NativeModuleBase.cs, ReactWindows/ReactNative/Bridge/Queue/MessageQueueThread.cs, ReactWindows/ReactNative/Bridge/ReactContext.cs, ReactWindows/ReactNative/Bridge/ReactContextNativeModuleBase.cs, ReactWindows/ReactNative/Hosting/Bridge/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Tracing/TraceDisposable.cs, ReactWindows/ReactNative/UIManager/Events/Event.cs, ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative/UIManager/IViewManager.cs, ReactWindows/ReactNative/UIManager/UIImplementation.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.cs, ReactWindows/ReactNative/UIManager/ViewManager.cs, ReactWindows/ReactNative/UIManager/ViewManagerRegistry.cs
Also adds two-phase initialization of the ChakraJavaScriptExecutor so the instance can be created off the JavaScript thread.
Also fixes a bug with the UIManagerModule constants and adds unit tests for custom event types and constant overloading by view managers.
Also adds a simple base interface (IViewManager) for view managers to hold names and constants.
=> Fixes #62 - Adds EventDispatcher

ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative.Tests/UIManager/FrameworkElementExtensionsTests.cs, ReactWindows/ReactNative.Tests/UIManager/PropertySetterTests.cs, ReactWindows/ReactNative.Tests/UIManager/RootViewHelperTests.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative.Tests/UIManager/ViewAtIndexTests.cs, ReactWindows/ReactNative.Tests/UIManager/ViewManagerRegistryTests.cs, ReactWindows/ReactNative.Tests/UIManager/ViewManagersPropertyCacheTests.cs, ReactWindows/ReactNative/IReactInstanceManager.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/UIManager/Animation/AnimationRegistry.cs, ReactWindows/ReactNative/UIManager/FrameworkElementExtensions.cs, ReactWindows/ReactNative/UIManager/IViewManager.cs, ReactWindows/ReactNative/UIManager/JavaScriptResponderHandler.cs, ReactWindows/ReactNative/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative/UIManager/RootViewHelper.cs, ReactWindows/ReactNative/UIManager/RootViewManager.cs, ReactWindows/ReactNative/UIManager/SizeMonitoringFrameLayout.cs, ReactWindows/ReactNative/UIManager/TouchTargetHelper.cs, ReactWindows/ReactNative/UIManager/UIImplementation.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.cs, ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative/UIManager/ViewAtIndex.cs, ReactWindows/ReactNative/UIManager/ViewGroupManager.cs, ReactWindows/ReactNative/UIManager/ViewManager.cs
Remaining TODOs surrounding layout, popup menu, measurement, etc.
=> Towards #70 - Adds implementation for NativeViewHierarchyManager

ReactWindows/ReactNative.Tests/Internal/MockEvent.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventTests.cs, ReactWindows/ReactNative/UIManager/Events/Event.cs, ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.cs
Previously, we relied on the OnBatchComplete method to drain the EventDispatcher. However, this is insufficient, as all dispatched events may not be sourced from a batch of native module calls. For example, events are also dispatched directly from view instances.
=> Fixes #112 - Adds logic to drain Events/EventDispatcher

ReactWindows/ReactNative/Bridge/BridgeBusyEventArgs.cs, ReactWindows/ReactNative/Bridge/BridgeIdleEventArgs.cs, ReactWindows/ReactNative/Bridge/CatalystInstance.cs, ReactWindows/ReactNative/Bridge/IReactBridge.cs, ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs, ReactWindows/ReactNative/Hosting/Bridge/ReactBridge.cs, ReactWindows/ReactNative/ReactNative.csproj
When we have a use case for these events, we can wire them up further.
During implementation, also discovered that the ReactBridge should also flush the JS queue immediately after loading the bundle. Currently, the WebSockets module is activated for debugging purposes immediately after loading the bundle.
=> Fixes #31 - Adds idle/busy events to the CatalystInstance for JavaScript

ReactWindows/ReactNative.Tests/Bridge/CatalystInstanceTests.cs, ReactWindows/ReactNative.Tests/Bridge/Queue/MessageQueueThreadTests.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs, ReactWindows/ReactNative.Tests/Resources/test.js, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, ReactWindows/ReactNative/Bridge/Queue/MessageQueueThread.cs, ReactWindows/ReactNative/Bridge/ReactContext.cs, ReactWindows/ReactNative/ReactInstanceManager.cs
Previously, there were no guarantees on the order of operations between items that may have been enqueued prior to disposal and the disposal itself.
In order for unit tests to behave properly, background threads are not allowed to crash. These changes prevent background threads from crashing by imposing an order of operations on the disposal of message queue threads.
=> Fixes issue with dispose behavior on MessageQueueThread instances.

ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/UIManager/ViewManager.cs, ReactWindows/ReactNative/Views/Scroll/IScrollCommandHandler.cs, ReactWindows/ReactNative/Views/Scroll/ReactScrollViewCommandHelper.cs, ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs, ReactWindows/ReactNative/Views/Scroll/ScrollEventType.cs, ReactWindows/ReactNative/Views/Scroll/ScrollEventTypeExtensions.cs
ScrollView is obviously important for making lists work on RN for UWP.
There's still work to be done around momentum events, horizontal scroll, etc., but this should provide a solid base.
=> Towards #143 - Replaces ListView with ScrollViewer for ReactScrollViewManager

ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs
As it turns out, when you pass a delegate to Chakra to define native functions, make sure you hang on to a reference to that delegate.
The delegates for console.log, console.warn, and console.error were being garbage collected, so when React Native made calls to them, they tried to invoke a delegate that was already garbage collected.
The ChakraJavaScriptExecutor now holds references to these for the entire lifetime of the object.
=> Fixes #224 - ExecutionEngineException no longer occurs

ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative/Chakra/Executor/JavaScriptValueToJTokenConverter.cs, ReactWindows/ReactNative/DevSupport/DebugServerException.cs, ReactWindows/ReactNative/DevSupport/DevServerHelper.cs, ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/DevSupport/StackTraceHelper.cs, ReactWindows/ReactNative/Modules/Core/JavaScriptException.cs
Previously, script exceptions were caught as regular native exceptions.  We're now parsing script exceptions and their stack traces for more detailed information in the RedBox.
=> Improved exception tracking for Chakra.

ReactWindows/js/Utilities/BackAndroid.windows.js
The BackAndroid module provides a JS API for the native DeviceEventEmitter module to hook into back-button presses. This is needed, e.g., for Navigator.
Fixes #246
=> feat(BackAndroid): Add BackAndroid JS module for Windows platform

ReactWindows/ReactNative.Tests/Modules/Storage/AsyncStorageModuleTests.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs
The callbacks for AsyncStorageModule expect two parameters, where the first is the list of errors and the second is the results. Ensure that a null error value is inserted into the callback arguments before the results, or that null is sent when no error occurred.
Fixes #260
=> fix(AsyncStorage): Fixes contract for AsyncStorageModule callbacks

ReactWindows/ReactNative/DevSupport/DevServerHelper.cs, ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/DevSupport/RedBoxDialog.xaml, ReactWindows/ReactNative/DevSupport/StackTraceHelper.cs
Fix a bug in the dev support stack prevented the JavaScript source code information from displaying properly.
=> fix(DevSupport): Display JavaScript source code info in red box

ReactWindows/ReactNative.Tests/Modules/Clipboard/ClipboardModuleTests.cs, ReactWindows/ReactNative/Modules/Clipboard/ClipboardModule.cs
The crash dump exception is HRESULT **0x80070005** - E_ACCESSDENIED
**Clipboard set or get may fail with exception if some other application is holding it.**
If the dispatcher is wrong the exception is  HRESULT **0x80070490**  - Element not found.
For example:
`CoreApplication.GetCurrentView().Dispatcher.RunAsync(CoreDispatcherPriority.Normal, action);`
I had the try - catch previously also on setString.
=> fix(ClipboardModule): ClipboardModule unit tests crash test execution process

ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/js/Components/DrawerAndroid/DrawerLayoutAndroid.windows.js, ReactWindows/js/Components/StatusBar/StatusBarIOS.windows.js, ReactWindows/js/Components/ToolbarAndroid/ToolbarAndroid.windows.js, ReactWindows/js/Components/ViewPager/ViewPagerAndroid.windows.js, ReactWindows/js/Vibration/VibrationIOS.windows.js
Various views have no implementation for UWP, but we need a placeholder module in cases where we use conditional behavior based on the platform.
=> feat(UIExplorer): Adding unimplemented views for UWP

ReactWindows/ReactNative.Tests/Modules/Storage/AsyncStorageModuleTests.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageErrorHelpers.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs, ReactWindows/ReactNative/ReactNative.csproj
The app LocalSettings were not a good option for storing data, as they cap out at a relatively small storage capacity.
Switch to using the local file system as the key value store. Later, we can consider options like SQLite.
Fixes #282
=> fix(AsyncStorageModule): Eliminate size constraint for async local storage

ReactWindows/ReactNative.Tests/Internal/MockReactInstance.cs, ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs, ReactWindows/ReactNative/Modules/Core/Timing.cs
We were running into an issue with setInterval(0) calls from JavaScript modules that were creating too much work on background threads and overloading the JavaScript queue.
By moving the timer elapsed checks to a frame boundary, we ensure that interval timers fire at most once per frame.
Fixes #286
=> fix(Timing): Timers fire on frame boundaries

ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs
For the onLayout event to fire, the UIManager must set the `onLayout` prop to true. This changeset adds a ReactProperty handler for this to the LayoutShadowNode base class.
Fixes #297
=> fix(LayoutShadowNode): Ensure that `onLayout` event fires

ReactWindows/ReactNative/UIManager/RootViewHelper.cs, ReactWindows/ReactNative/Views/Split/ReactSplitViewManager.cs
There seems to be a bug in XAML where the content in SplitView.Pane and SplitView.Content is not directly linked to its parent. This is a shim to ensure this link exists.
Fixes #290
=> fix(SplitViewWindows): Directly map SplitView child to parent

Examples/UIExplorer/UIExplorerList.windows.js, Libraries/Linking/Linking.js, ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Shell/MainReactPackage.cs, ReactWindows/js/Components/Touchable/TouchableNativeFeedback.windows.js
React Native has a module, Linking, that checks for launchability of URIs and launches them accordingly. This changeset adds LauncherWindows, which is analagous to LinkingManagerIOS and IntentAndroid.
We do not yet support the getInitialURL API, but have an open ticket to introduce this feature (#301).
Fixes #299
=> feat(LauncherWindows): Adds LauncherWindows for Linking implementation

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
A typical use case for scroll viewer is to set to a specific offset. This adds the prop to the view manager.
Fixes #320
=> fix(RCTScrollView): Adds missing `contentOffset` prop

Libraries/Text/Text.js, ReactWindows/ReactNative/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactRawTextManager.cs, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactVirtualTextViewManager.cs
Windows was not using virtual nodes for internal spans, causing problems with when things were marked as dirty. Adds platform specific handling to Text.js and deletes hacks to avoid the crashing bug for dirty layouts.
Fixes #289
=> fix(Text): Use virtual nodes for text spans in Windows

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs, ReactWindows/ReactNative/Views/Scroll/ScrollEventType.cs, ReactWindows/ReactNative/Views/Scroll/ScrollEventTypeExtensions.cs
It's useful to know when the user is manipulating the scroll view and no longer manipulating. Using events exposed on the XAML view to add `onScrollBeginDrag` and `onScrollEndDrag` events for ScrollView.
Fixes #332
=> feat(ScrollView): Adds begin and end drag events for ScrollView

ReactWindows/ReactNative/Touch/TouchHandler.cs
We had arbitrarily decided to only support touch, when it's just as easy to support any pointer. Doing that.
Fixes #334
=> feat(TouchHandler): Support click and stylus in addition to touch

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
This is really not a good idea guys. In fact, it's horrible. I'll hardly be able to sleep after this. This is horrible.
To give a rough overview of what's going on here, in XAML, after the ScrollViewer captures the pointer for scrolling, it immediately cancels the pointer that started the scroll in the first place, giving the following sequence of events: topTouchStart -> topTouchCancel -> topScrollBeginDrag -> topScroll -> topScrollEndDrag.
The expectation for React is that the entire sequence will be punctuated with an "endish" (look it up, they use the word in the React code base) touch event so the active responder (in this case, the scroll responder) can be released.
So, to overcome the fact that we don't have an "endish" punctuation, we make one happen, by simulating a touch. I …
=> hack(ScrollView): The most embarassing hack of my life

ReactWindows/.gitignore, ReactWindows/Playground/AppReactPage.cs, ReactWindows/Playground/Playground.csproj, ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs
Currently, the Image API we're using does not support loading images from a file path. You can use something like "ms-appdata:///local", but not "c:\tmp\". This change ensures the bundle path, which is the base path for the local assets, is a URI.
Fixes #338
=> fix(Assets): All assets must be loaded from URI

ReactWindows/ReactNative/Chakra/JavaScriptContext.cs, ReactWindows/ReactNative/Chakra/Native.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Reflection/EnumHelpers.Static.cs, ReactWindows/ReactNative/Reflection/EnumHelpers.cs
To submit apps to the Universal Windows store, they must be compiled using .NET Native. Reflection is crippled in .NET Native, so some things like the EnumHelpers implementation that relies on reflection will not work. Some of the Chakra APIs are also not supported in store apps.
Fixes #215
=> chore(DotNetNative): Enable .NET Native Compilation for apps

ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/UIManager/ShadowNodeRegistry.cs
The progress dialog for requests to the debug service was always related to "fetching the JS bundle", when sometimes the progress dialog represents waiting for connections to the Chrome debugger.
Fixes #310
=> fix(DevSupportManager): Progress dialog message corrected for debugging

ReactWindows/ReactNative/Bridge/ReactInstance.cs
When the dev manager reloads the bundle while the view hierarchy is updating, it may replace the root node in the middle of a view update dispatch operation. To prevent this from happening, the Dispose operation on the ReactInstance is now a blocking operation.
Fixes #266 - Root node collection modified while enumerating
=> fix(ReactInstance): Removing async void Dispose behavior

ReactWindows/ReactNative/DevSupport/DevServerHelper.cs
The timeout on the bundle server connection is really only intended to be for connection time, not for HTTP response time (which can exceed 5 seconds if the file system is particularly slow). Removing the timeout logic altogether as there is no way to set connection timeouts in the current choice of HTTP client API.
Fixes #353 - Bundle server timeout is only meant for connection
=> fix(DevSupportManager): Remove timeout from bundle server HTTP client

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
Android and Windows share the same event sequence for scroll (topScrollBeginDrag -> topScroll -> topScrollEndDrag), and both require a native event flag 'responderIgnoreScroll'.
Fixes #327
=> fix(ReactScrollViewManager): Ensures responder is not attached on scroll event

ReactWindows/ReactNative/Modules/Core/Timing.cs
Previously, the requestAnimationFrame callbacks occured on a tight loop.  Ensuring that only immediate timers callback instantly.
Fixes #394
=> fix(Timing): Fix behavior for `requestAnimationFrame`.

ReactWindows/ReactNative/UIManager/UIManagerModule.cs
Ensure that only the latest window size change event triggers a layout operation.
Fixes #397
=> fix(UIManager): Throttle layout from window size change events

Libraries/WebSocket/WebSocket.js
To reproduce the bug, just close websocket from JavaScript - it will crash on Win. This PR fixes that.
=> Passing status code and reason to WebSocketModule.close on Windows

ReactWindows/ReactNative/DevSupport/DevInternalSettings.cs
Fixes a typo regression caused by https://github.com/ReactWindows/react-native/commit/0f708017cb7d2e21d56f2cdbf4f3edba4ddd1b60#diff-cf97ac74413f23ae8391e25fc59f7faeR40 which causes Release builds to fail.
=> Fixes regression caused by #0f70801

Libraries/WebSocket/WebSocket.js, ReactWindows/ReactNative/Modules/WebSocket/WebSocketModule.cs
**Background**
Trying to use Firebase. I noticed that sockets are connecting, and I always receive first message from the server, but after that server never replies to me.
Created my own Node.js WS server and I noticed that it never receives messages from app, instead it's receiving binary data. So Firebase probably does the same thing and ignores binary messages, even though they contain text.
**Discussion**
This change should make sure that all outgoing messages are sent as Utf8 messages as opposed to binary messages. It seems that binary messages are the default setting.
=> Sending WebSocket messages using Utf8

ReactWindows/ReactNative/DevSupport/DevSupportManager.cs
The WebSocket JS executor was being disconnected before before it was disposed because a new executor would replace it before the dispose operation. Ensuring the new connection only occurs after the previous connection has been disposed.
Fixes #374
=> fix(DevSupport): Prevent WebSocket JS Executor from hanging on reload

ReactWindows/ReactNative/ReactPage.cs
Currently the dev menu & refresh JS hotkeys don't fire always. This fixes that!
Test plan (required)
Held down buttons for 3 seconds to make sure app doesn't crash. Dev menu opens, and Ctrl+R refreshes app with new content.
=> fix dev support hotkeys for Ctrl+R , Shift+F10, Menu.

ReactWindows/ReactNative.Tests/Chakra/Executor/ChakraJavaScriptExecutorTests.cs, ReactWindows/ReactNative.Tests/Internal/JavaScriptHelpers.cs, ReactWindows/ReactNative.Tests/Internal/MockJavaScriptExecutor.cs, ReactWindows/ReactNative/Bridge/IJavaScriptExecutor.cs, ReactWindows/ReactNative/Bridge/IReactBridge.cs, ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs, ReactWindows/ReactNative/Bridge/ReactBridge.cs, ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative/DevSupport/WebSocketJavaScriptExecutor.cs
In order for the server-side symbolicate feature to work, Chakra needs to report the correct source filename.  Threading through the SourceUrl to the RunScript function to ensure this is correct for exceptions.
Fixes #433
=> fix(Symbolicate): Ensures symbolicate feature is working properly

local-cli/generator-windows/templates/proj/MyApp.csproj
Closes #470 with fix to `csproj` file location for ReactWindows
=> fix(CLI) - fix csproj link - Closes Issue #470

ReactWindows/ReactNative/Views/TextInput/ReactTextBox.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
Previously, the native event count was not updated until the TextChanged event fired, which could be interrupted by a previous props update. When this occurred, we could potentially replace the text with the state of a previous event.
Now, the native event count is pre-incremented in th TextChanging event. This seems to resolve the race condition.
Fixes #490
=> fix(TextInput): Fixes race between counter increment and JavaScript props changes

local-cli/runWindows/utils/deploy.js
Makes sure that the app picks up the AppxManifest from the proper config/platform build and adds missing options variable.
=> fix(runWindows): Fixes deployToDesktop method for runWindows CLI

ReactWindows/Playground/App.xaml.cs, ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/DevSupport/DisabledDevSupportManager.cs, ReactWindows/ReactNative/DevSupport/IDevSupportManager.cs, ReactWindows/ReactNative/DevSupport/WebSocketJavaScriptExecutor.cs, ReactWindows/ReactNative/ReactPage.cs, ReactWindows/ReactNative/ReactRootView.cs, local-cli/generator-windows/templates/src/App.xaml.cs, local-cli/runWindows/runWindows.js, local-cli/runWindows/utils/WindowsStoreAppUtils.ps1, local-cli/runWindows/utils/deploy.js
Tools like VS Code need to be able to launch the app from the command line with remote debugging enabled.  This change allows arguments to be passed from powershell to the app and down to the DevSupportManager.
=> feat(runWindows): Adds option to start application with remote debugging

local-cli/runWindows/utils/deploy.js
Ensure the loopback exemption is added for app for access to localhost (i.e., the packager server).
Fixes #515
=> fix(run-windows): Add loopback exemption for desktop apps

local-cli/runWindows/runWindows.js, local-cli/runWindows/utils/build.js, local-cli/runWindows/utils/deploy.js
Removing the AppPackages folder was causing the packager to crash. Avoiding the removal.
Fixes #517
=> fix(run-windows): prevent packager from crashing

ReactWindows/ReactNative/UIManager/UIImplementation.cs
The wrong index is used to fetch a view while walking through the `moveFrom` array.
=> Fix move logic in UIImplementation.ManageChildren

ReactWindows/ReactNative/UIManager/RootViewHelper.cs, ReactWindows/ReactNative/Views/Split/ReactSplitViewManager.cs, ReactWindows/ReactNative/Views/Text/ReactSpanViewManager.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
VisualTreeHelper is able to find the parent dependency object in cases where the FrameworkElement.Parent property may be null. This is a useful way to ensure we can find the RootView for measurement.
Hacking this helper, however, breaks certain views like SplitView, which currently depend on the pointer not being captured by React to close the view when the lightweight Rect layer is overlayed adjacent to the pane. For now, only using the VisualTreeHelper in the root view search case, however we may want to use it more generally and have a better "opt-out" mechanism for view managers like SplitView.
=> fix(RootViewHelper): Use VisualTreeHelper instead of explicit map shim

ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs
Because the subscription to the image events must occur on the dispatcher thread, the native module calls to ImageLoader are by neccessity asynchronous from the subscription to the image. To avoid a race condition where the image reference is disposed before the subscription occurs, this changeset adds a single-assignment disposable wrapper for the subscription.
Fixes #521
=> fix(Image): Fixes race condition for subscribe/dispose

ReactWindows/ReactNative.Tests/Bridge/NativeModuleBaseTests.cs, ReactWindows/ReactNative.Tests/Internal/JavaScriptHelpers.cs, ReactWindows/ReactNative.Tests/Modules/Network/TaskCancellationManagerTests.cs, ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs, ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/Modules/StatusBar/NopStatusBar.cs
Avoid allocating a new task if not necessary.
=> fix(async): Task.FromResult -> Task.CompletedTask where possible

Libraries/Image/Image.windows.js
In JS, the Image's render function was returning null
when it was used inside of a text element.
=> Fix inline images

ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
Inline views get wrapped in an InlineUIContainer.
InlineUIContainers didn't have a tag so when its tag
was attempted to be found (e.g. during destruction), the
app would crash.
To fix this, the tag of the wrapped element is now copied onto
the InlineUIContainer.
=> Fix destruction of inline views

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
When TextInput's multiline prop is true, text that can't fit on the line
should wrap to the next line.
=> Enable text wrapping for TextInput

ReactWindows/ReactNative/Views/TextInput/ReactTextBox.cs
When programmatically giving a TextInput focus, it wasn't rendering
properly (e.g. the focus rect wasn't drawn, the cursor wasn't drawn or it
was drawn in the wrong spot, selected text wasn't highlighted).
It looks like ReactTextBox overrode OnGotFocus but forgot to give
TextBox's handler a chance to run.
=> Fix rendering of TextInput after programmatic focus

Libraries/Text/Text.windows.js, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
This enables developers to configure whether or not Text is selectable.
This feature is already supported by React Native for Android.
=> Add selectable prop to Text component

README.md, local-cli/generator-windows/index.js, local-cli/generator-windows/templates/src/project.json, local-cli/rnpm/windows/README.md, local-cli/rnpm/windows/index.js, local-cli/rnpm/windows/package.json, local-cli/runWindows/runWindows.js, local-cli/runWindows/utils/deploy.js
RNPM has recently moved to react-native, and there have been a few changes to the core behavior.  Making sure our plugin is compatible.
=> fix(RNPM): fix rnpm-plugin-windows to work with react-native-cli

ReactWindows/ReactNative/Views/View/ReactViewManager.cs
I don't know the proper implementation of this method but see below for why I'd like to add this stub. If you know the proper implementation, we can adjust the PR.
Because we didn't have any implementation for View's accessible prop, some
views were considered to be layout-only which weren't layout-only on iOS
and Android. The specific scenario I'm trying to fix is around touchables
(e.g. TouchableWithoutFeedback). I ran into a case where a touchable was
layout-only on Windows. When tapping it, React Native's JS code attempted
to measure the view. React Native was unable to return a result for the
measure request because the view that was being measured was layout-only.
React Native's JS sets accessible to true on touchables. According to the
React Native docs, "by default, all touchable …
=> Provide stub for View's accessible prop

ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/DependencyObjectExtensions.cs, ReactWindows/ReactNative/UIManager/IReactCompoundView.cs, ReactWindows/ReactNative/UIManager/ReactDefaultCompoundView.cs, ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
I would have preferred to make `GetReactTagAtPoint` a polymorphic method so that the code that authors the Text component could also provide an implementation for `GetReactTagAtPoint`. However, because we don't control the source code for `RichTextBlock` and it's sealed, I couldn't find a way to do this.
Perhaps you know of a way?
One other option would be to make `GetReactTagAtPoint` a method of the view manager and `TouchHandler` would have to somehow find the view manager for the view and invoke the method.
Currently, onPress handlers only work on outermost Text components.
This change enables you to place onPress handlers on nested Text
components. For example, this now works:
```
<Text>
<Text onPress={this._handlePress}>Press Me</Text>
</Text>
```
In the fix, we need to manually do …
=> Fix onPress handlers on nested Text components

Libraries/Components/ScrollView/ScrollView.windows.js, ReactWindows/Playground/project.json, ReactWindows/ReactNative.Tests/project.json, ReactWindows/ReactNative/Views/Text/ReactSpanShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative/project.json
The only new changes are the ones in `ScrollView.windows.js` which I ported from https://github.com/facebook/react-native/commit/6603cef95cd30fcc05330707d4ce10a2c4e22046.
A second attempt at updating the css-layout dependency. This commit
includes the changes from these 2 commits:
- 104aa49fc403fd6b05aab474baee90235f8e2c99: Update css-layout dependency
- 45010962406ae050714e001e5096dc734dcb9190: Clean up warnings due to project.json
It also includes a fix for #561 (horizontal scrolling broken) which was
introduced by the previous attempt at upgrading the layout engine.
Facebook already found and fixed this bug in their repo so I imported
their fix: https://github.com/facebook/react-native/commit/6603cef95cd30fcc05330707d4ce10a2c4e22046
The updated version of css-layout includes …
=> Update css-layout dependency

ReactWindows/ReactNative/Touch/TouchHandler.cs
An exception is raised when trying to call
reactView.GetReactCompoundView() when reactView is null. This change moves
this line into the branch where reactView cannot be null.
=> Fix crash in TouchHandler

ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs
Currently, MeasureTextInput crashes when it calls textBlock.Measure with a
negative value for normalizedWidth.
This fixes the bug by ensuring normalizedWidth is at least 0.
Additionally, normalizedWidth's calculation was refactored into a single
assignment to minimize the chances that in the future somebody will use
normalizedWidth before it has been clamped.
=> Make MeasureTextInput robust in small spaces

ReactWindows/ReactNative.Tests/Bridge/Queue/MessageQueueThreadTests.cs, ReactWindows/ReactNative/Bridge/Queue/IReactQueueConfiguration.cs, ReactWindows/ReactNative/Bridge/Queue/MessageQueueThread.cs, ReactWindows/ReactNative/Bridge/Queue/MessageQueueThreadKind.cs, ReactWindows/ReactNative/Bridge/Queue/MessageQueueThreadSpec.cs, ReactWindows/ReactNative/Bridge/Queue/ReactQueueConfiguration.cs, ReactWindows/ReactNative/Bridge/Queue/ReactQueueConfigurationSpec.cs, ReactWindows/ReactNative/Bridge/ReactContext.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.cs, ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs
Text measurement was a bit of a performance bottleneck due to context switching from the native module thread to the dispatcher thread.
Eventually, we may want to implement text measurement that does not invole cloning the RichTextBox (e.g., using DWrite APIs or Win2D), but this is progress for now.
We create the layout thread from a static secondary CoreApplicationView with a Window that is never activated.
=> fix(Text): Add separate layout thread with dispatcher access

ReactWindows/ReactNative/DevSupport/StackTraceHelper.cs
Fixed case when native exceptions are thrown from release builds (where method information may be missing).
Fixes #577
=> fix(StackTraceHelper): RedBox crashes Release builds

local-cli/runWindows/utils/msbuildtools.js
The call of msbuild.exe wasn't done with a properly escaped version of slnFile, so paths including whitespaces resulted in an error. This is fixed by adding quotation marks in front of and at the end of the slnFile.
=> Proper escaption of .sln file in command line args

ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs, ReactWindows/ReactNative/Modules/Core/Timing.cs
The timing module comparison function was not behaving properly because of unchecked arithmetic. Switching the comparison to use the built-in IComparator behavior long values.  Also, adding a unit test to make sure this doesn't happen again.
Fixes #589
=> fix(Timing): Fix comparator for scheduled timers

ReactWindows/ReactNative/DevSupport/ProgressDialog.xaml.cs, ReactWindows/ReactNative/DevSupport/RedBoxDialog.xaml.cs, ReactWindows/ReactNative/Touch/JavaScriptResponderHandler.cs
There's one remaining warning that currently can't be eliminated because it's sourced from generated code.
Warning	CS1591	Missing XML comment for publicly visible type or member 'XamlMetaDataProvider'	react-native-windows\ReactWindows\ReactNative\obj\x86\Debug\XamlTypeInfo.g.cs
Fixes #612
=> chore(MSBuild): Clean up MSBuild warnings

ReactWindows/ChakraBridge/SerializedSourceContext.h
Calling `delete[]` on the source script URI causes an AVE since it is not controlled by this scope.
=> fix(ChakraBridge) - fixes AVE with disposal

package.json
to eliminate npm warnings about a sub-dependency of yeoman-generator having a security vulnerability
=> synchronize yeoman modules with RN upstream

ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
Previously, ImageBrush.Stretch defaulted to Stretch.Fill. A better choice for default behavior is Stretch.UniformToFill.
Fixes #638
=> fix(Image): Change default stretch setting on Image

ReactWindows/ReactNative/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative/DevSupport/DisabledDevSupportManager.cs, ReactWindows/ReactNative/DevSupport/IDevSupportManager.cs, ReactWindows/ReactNative/ReactInstanceManager.cs
If the bundle file was created since the app has been last updated, use the existing bundle, otherwise, get a new bundle.
Fixes #604
=> fix(DevSupport): Adds feature to load existing bundle from cache

ReactWindows/ReactNative/Modules/Clipboard/ClipboardModule.cs
Constructor is marked internal which isn't necessary as the class itself is internal.
=> fix(Clipboard) - removing unnecessary constructor

ReactWindows/ReactNative/UIManager/CSSNodeExtensions.cs, ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs
Padding settings were not accounted for because of the default paddings set for measurement.
Fixes #651
=> fix(TextInput): Enable user padding settings for TextInput.

ReactWindows/ReactNative.Tests/Internal/JavaScriptHelpers.cs
Previously, RunScript expected the complete JavaScript. Now, it expects a file path to load from.
=> test(JavaScriptHelpers): fixes broken unit tests from RunScript changes

ReactWindows/ReactNative.Tests/Modules/Clipboard/ClipboardModuleTests.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs, ReactWindows/ReactNative/ReactInstanceManager.cs
ReactInstanceManager unit tests were broken because of the use of async void and .ConfigureAwait(false) from a recent change (so exceptions are not necessarily thrown back to the caller). Clipboard tests tend to fail because of thread access.
=> test(ReactNative): Fixing broken unit tests

ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxShadowNode.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs
As per #653, adding `borderColor` and `backgroundColor` to the shadow node. Note that `borderRadius` is not supported on the `TextBox` so we cannot support that for UWP.
=> feat(TextInput) - add border and background color to shadow node

ReactWindows/ChakraBridge/ChakraBridge.vcxproj, ReactWindows/ChakraBridge/ChakraBridge.vcxproj.filters, ReactWindows/ChakraBridge/ChakraHost.cpp, ReactWindows/ChakraBridge/ChakraHost.h, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.cpp, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.h, ReactWindows/ChakraBridge/SerializedSourceContext.h, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
Adds back serialization to the ChakraHost with smarter file loading for serialized scripts.
For data, this assumes the binary file already exists:
```txt
** Serialized Native Code **
App Report: private: 49373184, peak private: 49573888, total commit: 128131072
Process Report: private working set: 27676672, total working set: 68775936
Elapsed ms: 1006
App Report: private: 68173824, peak private: 68173824, total commit: 146931712
Process Report: private working set: 43331584, total working set: 84590592
** Unserialized Native Code **
App Report: private: 57757696, peak private: 57757696, total commit: 136007680
Process Report: private working set: 29859840, total working set: 70004736
Elapsed ms: 1346
App Report: private: 71086080, peak private: 78913536, total commit: 149336064
Process …
```
=> fix(ChakraBridge) - add back smarter serialization

ReactWindows/ReactNative/Shell/MainReactPackage.cs, ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative/Views/Slider/ReactSliderChangeEvent.cs, ReactWindows/ReactNative/Views/Slider/ReactSliderCompleteEvent.cs, ReactWindows/ReactNative/Views/Slider/ReactSliderManager.cs
Removes global declaration of the `topSlidingComplete` event in favor of a local declaration of the direct event type in the view manager.
Adds an `Undefined` value for the slider that will reset the value to XAML defaults.
Sets the step value to `Epsilon` (= 0.0001) when set to 0 from React.
cc @souhe
=> fix(Slider): Change default behaviors for Slider

ReactWindows/ReactNative/DevSupport/DevSupportManager.cs
This set of changes ensures that, in case the packager server is not online or otherwise fails, the intermediate bundle file is deleted.  In order to always keep a valid bundle in the LocalState if such a bundle has ever been produced, we use a temporary file and only move it to LocalState once the packager server request succeeds.
Fixes #671
=> fix(DevSupport): Remove cached bundle for failed calls to packager

ReactWindows/ChakraBridge/ChakraBridge.vcxproj
.vcxproj was missing the USE_EDGEMODE_JSRT definition. Added for both of those configurations. cc @mpodwysocki 
Fixes #649, fixes #691
=> fix(ChakraBridge): ChakraBridge build failing for Release|(ARM & x64)

ReactWindows/Playground/AppReactPage.cs
We don't want to disable dev support for all Release builds (the 'Release' configuration still expects to communicate with the bundle server). Instead, we'll just disable it for the ReleaseBundle configuration.
Towards #692
=> fix(Playground): Disable dev support for ReleaseBundle configuration

Libraries/Devtools/setupDevtools.windows.js
Getting a lot of issues filed because of exceptions thrown from WebSocket module. This tend to come from the devtools setup which no one (currently) seems to be using for Windows.  We can delete the added file at some point when devtools should be enabled for Windows.
Fixes #701
=> fix(Devtools): Make devtools a no-op

ReactWindows/ReactNative.Tests/Bridge/ReactInstanceTests.cs, ReactWindows/ReactNative.Tests/Internal/DispatcherHelpers.cs, ReactWindows/ReactNative.Tests/Internal/MockReactInstance.cs, ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, ReactWindows/ReactNative/Bridge/IAsyncCancelable.cs, ReactWindows/ReactNative/Bridge/IAsyncDisposable.cs, ReactWindows/ReactNative/Bridge/IReactInstance.cs, ReactWindows/ReactNative/Bridge/ReactContext.cs, ReactWindows/ReactNative/Bridge/ReactInstance.cs, ReactWindows/ReactNative/IReactInstanceManager.cs, ReactWindows/ReactNative/ReactInstanceManager.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/ReactPage.cs
Basic overview of the deadlock:
1) CSS layout operation in progress
2) Text node measurement started on native module thread
3) ReactContext disposed on dispatcher thread
4) ReactContext disposal blocks on completion of native module thread
5) Native module thread blocks on dispatcher operation for text measurement
6) We have deadlock
The best way to get around this is to not block from the native module thread, but this is a limitation we haven't figured out how to work around yet.  In the meantime, it actually makes sense to make the teardown process for the React context asynchronous, which is what this changeset does.
Fixes #702
=> fix(ReactContext): Dispose path for ReactContext created deadlock

ReactWindows/ReactNative.Tests/Modules/Storage/AsyncStorageModuleTests.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs
The mapping used from key to filename was not used to convert from filename back to key. Additionally, adds some optimizations to reduce allocations for AsyncStorage.
Fixes #724
=> fix(AsyncStorage): ensure getAllKeys from filenames are translated

ReactWindows/ReactNative/Views/TextInput/InputScopeHelpers.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs
PasswordBox only supports 'number-pad' and 'password' (i.e., InputScopeNameValue.NumericPin and InputScopeNameValue.Password).
Fixes #726
=> fix(PasswordBox): Fixes minor bug with keyboard type on PasswordBox

ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/RootViewHelper.cs
Previously, we were only considering the hierarchy from the pointer "OriginalSource" in the pointer events calculations. Unfortunately, this meant that if a transparent overlay with "box-none" or "none" pointer events was set, as is the case for "react-native-drawer", then no alternative targets would be considered. This change uses VisualTreeHelper.FindElementsInHostCoordinates to consider all possible targets.
Fixes #715
=> fix(TouchHandler): Consider all possible views for click target

ReactWindows/ReactNative.Shared/Bridge/Promise.cs, ReactWindows/ReactNative.Shared/Bridge/ReactDelegateFactoryBase.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Tests/Bridge/PromiseTests.cs, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
Using System.Exception.Data IDictionary, users can add arbitrary data to a "userInfo" property on the error object.
Fixes #730
=> feat(Promise): Adding userInfo to reject error object

ReactWindows/ReactNative/Bridge/ReactInstance.cs
JavaScript may call native behaviors prior to the `_bridge` variable being set in `ReactInstance`, which would be invoked in the initial call to `FlushedQueue` following the call to run the bundle.
This change set ensures the `_bridge` is set before the bundle is loaded.
Fixes #744
=> fix(ReactInstance): Set bridge instance before calling LoadScript

ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/RootViewHelper.cs
A recent change to the touch handler to support cases where overlays that did not support any pointer events were used (so the underlying React view that did support pointer events could be reached) ignored the fact that some clicks simply don't belong to the React hierarchy (e.g., native app overlays, as is the case for SplitView).
This change first checks that the original pointer target actually belongs to the React before calculating the target using pointer events logic.
Fixes #746
=> fix(SplitView): Ensure clicking outside SplitView pane closes the pane

ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs
A number of users were seeing AccessViolationExceptions, especially in Release builds, where JS strings were being GC'd prior to use. I suspect this is because we need to increment the ref count of the marshalled arguments so they are not collected before use as call arguments.
Fixes #751
=> fix(ChakraJavaScriptExecutor): Ensure JS arguments are not GC'd

ReactWindows/ReactNative/Views/Text/ReactSpanViewManager.cs
Prior to this change, Images with one <Text> ancestor were supported:
```
<Text>
<Image />
</Text>
```
But Images with multiple <Text> ancestors resulted in an exception:
```
<Text>
<Text>
<Image />
</Text>
</Text>
```
This change fixes the latter scenario.
The problem was that some code assumed that it would only receive Inlines when actually it could also receive UIElements.
=> Enable Images to have muliple <Text> ancestors

ReactWindows/ReactNative/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative/Modules/Core/Timing.cs, ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs
Previously, failures on the CompositionTarget.Rendering event could crash the app. With these changes, each frame callback has an exception handling wrapper.
Fixes #750
=> fix(FrameDispatch): All operations on Rendering event should catch exceptions

ReactWindows/ReactNative/Modules/Image/BitmapImageHelpers.cs, ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/Modules/Image/ImageMetadata.cs, ReactWindows/ReactNative/Modules/Image/ImageStatusEventData.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
Getting null reference exceptions due to a condition where the ImageSource is not always set on the ImageBrush.  Instead, gathering the image metadata directly from the OnLoad event.
=> fix(Image): view.Background.ImageSource is not always valid OnLoad

ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs
Currently, when a bundle has not been created properly using the `react-native bundle` command, an exception along the lines of 'Argument can not be null' is thrown. Now we have a more specific error message along the lines of "Cannot resolve '__fbBatchedBridge' ...".
Fixes #719
=> fix(Chakra): Throw less cryptic error message for invalid bundle

ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Touch/PointerDeviceTypeExtensions.cs, ReactWindows/ReactNative/Touch/TouchHandler.cs
Adds a pointerType field to the native event for the gesture responder handlers. Basically, e.nativeEvent.pointerType is oneOf ["mouse", "pen", "touch"].  I'll need to follow up with documentation and examples for this.
Fixes #772
=> feat(TouchHandler): Add pointerType to event data

ReactWindows/ReactNative.Net46.Tests/Internal/MockInvocationHandler.cs, ReactWindows/ReactNative.Net46.Tests/Internal/MockPromise.cs, ReactWindows/ReactNative.Net46.Tests/Internal/MockReactInstance.cs, ReactWindows/ReactNative.Net46.Tests/Modules/NetInfo/NetInfoModuleTests.cs, ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj, ReactWindows/ReactNative.Net46/Modules/NetInfo/DefaultNetworkInformation.cs, ReactWindows/ReactNative.Net46/Modules/NetInfo/INetworkInformation.cs, ReactWindows/ReactNative.Net46/Modules/NetInfo/NetInfoModule.cs, ReactWindows/ReactNative.Net46/Properties/AssemblyInfo.cs, ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj, ReactWindows/ReactNative.Shared/Bridge/ReactContext.cs
cc: @GantMan @rozele @matthargett
=> feat(Portable): Migrate NetInfo module

ReactWindows/ReactNative/UIManager/BaseViewManager.cs
passing null as testID works well on  iOS so it will be good to support it on Windows instead of just crashing the app
=> Allow testID to be set to null

local-cli/rnpm/windows/package.json, local-cli/rnpm/windows/src/windows.js
Previously, when a version of react-native-windows that matched react-native was not available, a somewhat cryptic dump of all available react-native-windows versions was displayed.  Now, we give a specific message suggesting the version could not be found, what the latest version of react-native-windows is, and a suggestion to upgrade/downgrade to the react-native version that matches.
Fixes #778
=> fix(CLI): Add better error handling for react-native-windows generator CLI

local-cli/rnpm/windows/package.json, local-cli/rnpm/windows/src/windows.js
Adding some console logging to the generator script to make it clear where the app name and version for react-native-windows.
=> fix(CLI): Adding transparency to generator script

ReactWindows/ReactNative/Touch/TouchHandler.cs
When the status bar is visible, the TouchHandler's use of VisualTreeHelper.FindElementsInHostCoordinates does not seem to account for the status bar. This PR adjusts the point based on the status bar occlusion and hides the status bar by default.
Fixes #799
=> fix(TouchHandler): TouchHandler has bug when status bar is visible on mobile

local-cli/.npmignore
The rnpm-plugin-windows module can potentially exist in two places (it can be picked up by node-haste and generates a warning about the existence of multiple modules with the same name).
=> chore(NPM): Add rnpm-plugin-windows code to .npmignore

ReactWindows/ReactNative/Bridge/ReactBridge.cs
Previously, the batch processing step converted the entire list of module IDs and method IDs from the flushed queue into arrays. This involved the allocation of an array. This approach only requires the conversion from a Newtonsoft.Json number (I suspect the internal representation is double) to an integer.
I ran a small test script in a ConsoleApp to ensure this was actually a performance improvement:
```c#
var size = 100;
var repeat = 1000;
var values = Enumerable.Range(0, size);
var json = $"[[{string.Join(",",values)}],[{string.Join(",",values)}],[{string.Join(",", values.Select(_ => "[]"))}]]";
var jarr = JArray.Parse(json);
var x = 0;
GC.Collect();
GC.WaitForPendingFinalizers();
var sw = Stopwatch.StartNew();
for (var i = 0; i < repeat; ++i)
{
var moduleIds = …
```
=> perf(ReactBridge): Minor improvement to batch processing perf

ReactWindows/ReactNative.Shared/Bridge/ReactBridge.cs
Recent change to batched bridge lost behavior to quietly ignore null payloads from the flushed queue.
=> fix(ReactBridge): Add missing case for null batched bridge response

ReactWindows/ReactNative.Shared/UIManager/Events/TouchEventType.cs, ReactWindows/ReactNative.Shared/UIManager/Events/TouchEventTypeExtensions.cs, ReactWindows/ReactNative.Shared/UIManager/RootViewHelper.cs, ReactWindows/ReactNative.Shared/UIManager/RootViewManager.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Shared/UIManager/ViewManager.cs, ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/Views/Flip/ReactFlipViewManager.cs, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative/Views/Picker/ReactPickerManager.cs, ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs, ReactWindows/ReactNative/Views/Slider/ReactSliderManager.cs, ReactWindows/ReactNative/Views/Split/ReactSplitViewManager.cs, ReactWindows/ReactNative/Views/Switch/ReactSwitchManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
A first approach at adding mouseenter/mouseleave events for react-native-windows. We may eventually want to considering adding a specific event plugin for this (to implement behavior like "capture" without "bubbling").
Fixes #775
=> feat(EnterLeave): Adds simplistic approach for adding enter/leave mouse events

ReactWindows/ReactNative.Shared/Animated/FrameBasedAnimationDriver.cs, ReactWindows/ReactNative.Shared/Animated/InterpolationAnimatedNode.cs, ReactWindows/ReactNative/Animated/DiffClampAnimatedNode.cs, ReactWindows/ReactNative/Animated/NativeAnimatedNodesManager.cs, ReactWindows/ReactNative/ReactNative.csproj
Casting to long too early here and dropping some precision, resulting in skipped (not dropped) frames.
=> fix(FrameBasedAnimationDriver): (should) reduce choppiness of animation

ReactWindows/ReactNative.Shared/Bridge/JavaScriptBundleLoader.cs, ReactWindows/ReactNative.Shared/CoreModulesPackage.cs
Apparently PCLStorage fails to resolve the ms-appx:/// URIs.  So, let's not use that.
cc @matthargett
=> fix(JavaScriptBundleLoader): PCLStorage does not work for this

ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxShadowNode.cs
`PasswordBox.Measure(size)` does not result in a value being set for `PasswordBox.DesiredSize` property. The same goes for `TextBox`, which we worked around by measuring a `TextBlock` and including the `TextBox` margin values in the resulting measurement. Making the same change for `PasswordBox`.
Fixes #855
=> fix(TextInput): Perform more accurate measurement for PasswordBox

ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative.Shared/UIManager/Events/IEventDispatcherListener.cs, ReactWindows/ReactNative.Shared/UIManager/Events/RCTEventEmitter.cs, ReactWindows/ReactNative/Animated/EventAnimationDriver.cs, ReactWindows/ReactNative/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative/Animated/NativeAnimatedNodesManager.cs, ReactWindows/ReactNative/ReactNative.csproj
This adds support for `Animated.event` driven natively.
At the moment, it works by providing a mapping between a view tag, an event name, an event path and an animated value when a view has a prop with a `AnimatedEvent` object. Then we can hook into `EventDispatcher`, check for events that target our view + event name and update the animated value using the event path.
For now it works with the onScroll event but it should be generic enough to work with anything.
=> feat(NativeAnimated): Adds support for animated events

local-cli/runWindows/utils/msbuildtools.js
This fixes issue [After creating app packages, react-native run-windows fails with a build error](https://github.com/ReactWindows/react-native-windows/issues/876)
Using run-windows builds the code in debug mode, and is not meant for bundling. If the app has been previously bundled, the build process will attempt to create it.
This change tells msbuild not to create any bundles.
=> Do not create app bundles when using run-windows

ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative.Shared/UIManager/ViewParentManagerExtensions.cs
When using layout animation, dropping a view can be deferred if the delete action is animated with layout animation.
If, while the layout animation is processing, a parent container of the view being animated is also removed, then the animated view will simply be dropped (even though the layout animation is still processing).
To prevent an exception from occurring due to this behavior, the animation end callback for drop layout animations checks first that it is safe to finalize dropping the view.
Fixes #861
=> fix(LayoutAnimation): Ensure view still exists before dropping

ReactWindows/ReactNative.Net46/Touch/TouchHandler.cs
Without a timestamp on each dispatched touch event the javascript debounces them all into oblivion.
=> feat(Shared): Fix touch to allow click-and-drag

ReactWindows/ReactNative/Modules/Image/BitmapImageHelpers.cs, ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative/project.json
Using UWP Community Toolkit ImageCache to implement prefetch capability for react-native Image component.
Fixes #366
=> feat(Image): Add prefetch to ImageLoader module

ReactWindows/ReactNative/Views/Picker/ReactPickerManager.cs
Bug reported where updating the items prop with new values would result in appending rather than replacing items.  Adding a `Clear()` call to ensure correct behavior.
Fixes #911
=> fix(Picker): Clear picker items whenever items props change

ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs
Recent changes to the ReactImageManager and the ImageLoaderModule introduced a bug where local assets were not behaving correctly because they did not work with the ImageCache API from UWP Community Toolkit.  This fix works around that limitation and uses the previous `getSize` implementation approach for non-HTTP assets.
Fixes #930
=> fix(ImageLoader): `getSize` API behavior for local assets

ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared/Chakra/Executor/LogLevel.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
react-native provides a console polyfill if you expose a global function called `nativeLoggingHook` that takes two parameters, a message and a log level.  This polyfill contains logic to format calls to console.table, and also future proofs us for new console methods that are polyfilled.
Fixes #933
=> fix(Console): Leverage existing console polyfill from react-native

ReactWindows/Playground.Net46/index.windows.js, ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative.Net46/Views/Text/ReactTextViewManager.cs
Text still properly clips if you set a width/height smaller than the content, but no longer clips when width/height aren't specifically defined.
=> Fixed issue where text was clipping instead of wrapping

ReactWindows/ReactNative.Shared.Tests/Modules/Network/TaskCancellationManagerTests.cs, ReactWindows/ReactNative.Shared/Modules/Network/TaskCancellationManager.cs
TaskCancellationManager unit tests had assumptions about the ExecuteSynchronously continuation option used internally to the TaskCancellationManager that were invalid. To alleviate this, I've added a return Task to await the actual completion of the wrapped task.
Fixes #947
=> test(TaskCancellationManager): Fix non-deterministic unit tests

ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs
custom fontFamily props were not working in WPF because assets are accessed differently in WPF.  This PR re-arranges the string to be consumed by a URI that can properly access and set the `fontFamily` for text.
=> Font fix for WPF

ReactWindows/ReactNative.Shared/UIManager/ColorHelpers.cs
Color Helpers are useful to third-party libraries, so let's make it public. Simple enough.
=> make color helpers public

ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs
=> Fix incorrect function name for getInitialURL in LauncherModule (#959)

ReactWindows/ReactNative.Net46/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
TextInput height was not set according to the RN layout.
Is the height not set here on purpose, or was it just forgotten ? Setting the height fixed the issue for me. My layout is now consistent on iOS and UWP.
=> Fix TextInput layout not taking height into account

local-cli/rnpm/windows/src/common.js, local-cli/rnpm/wpf/src/wpf.js, package.json
If `https_proxy` or `HTTPS_PROXY` environment variable is set, the fetch function in RNPM Plugin for Universal Windows / Universal Windows WPF will make use of it for making requests.
Solves #879.
=> Added proxy support for requests made by fetch

ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs
When we don't round up the text always gets clipped.
=> fixed text measurement regression

Libraries/Image/Image.windows.js, ReactWindows/ReactNative.Net46/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/project.json
Recent update to the UWP Community Toolkit allows us to cancel prefetch operations. This changeset also adds the ability to query for images on disk, but not yet in-memory.
=> fix(ImageLoader): Adds prefetch cancellation and cache query

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs
UWP implementation will have to be totally different, but for now this addresses the WPF side of #953
=> Re-implemented wpf shadow

local-cli/rnpm/windows/package.json, local-cli/rnpm/windows/src/common.js
Instead of using an ad hoc HTTP approach, we're now consuming the `npm-registry` package, which should hopefully provide more consistent behavior over time.
Fixes #1005
=> fix(CLI): Windows project generator broke due to changes to HTTP registry API

ReactWindows/ReactNative.Shared.Tests/Modules/Network/NetworkingModuleTests.cs
=> fix(NetworkingModuleTests): Replace `GetResults()` with more reliable `AsTask().Result`

ReactWindows/ReactNative/Touch/TouchHandler.cs
A previous change to adjust the touch point for a visible status bar does not seem to be necessary when the device is in landscape orientation.
Fixes #945
=> fix(TouchHandler): touch point offset due to status bar

ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs
iOS and apparently Android in RN support allowFontScaling that can be used to prevent users from changing font scaling in accessibility settings. Ran into this through a customer using ARM device and made a quick fix that seems to work
If something is missing please comment this was made quite quickly.
=> Support allowFontScaling

ReactWindows/Playground.Net46/Playground.Net46.csproj, ReactWindows/Playground.Net46/packages.config, ReactWindows/Playground/project.json, ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj, ReactWindows/ReactNative.Net46.Tests/packages.config, ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj, ReactWindows/ReactNative.Net46/packages.config, ReactWindows/ReactNative.Tests/project.json, ReactWindows/ReactNative/project.json
Facebook.Yoga was throwing an AccessViolationException on ARM devices due to a marshaling error. We added a patch to work around this limitation.
Fixes #1027
=> fix(Yoga): Pointing at patched NuGet package to fix AVE

local-cli/generator-windows/templates/src/project.json
The Facebook.Yoga package reference is not needed, and creates another place that needs to be upgraded each time we upgrade the NuGet package.
=> fix(init): remove Facebook.Yoga package reference

ReactWindows/ReactNative.Net46/Modules/WebSocket/WebSocketModule.cs, ReactWindows/ReactNative.Shared.Tests/Modules/WebSocket/WebSocketModuleTests.cs, ReactWindows/ReactNative/Modules/WebSocket/WebSocketModule.cs
The WebSocketModule was missing the `sendBinary` ReactMethod used to support binary messages.
Fixes #1060
=> feat(WebSocketModule): Adds binary message support to WebSocketModule

ReactWindows/ReactNative/ReactPage.cs
`ReactPage` was missing a `virtual` or `abstract` method that could be overridden to change `RootView.Background`.
It can be used like this, in your `MainPage.cs`:
```c#
using ReactNative.UIManager;
using Windows.UI.Xaml.Media;
// ...
protected override void SetRootViewBackground()
{
RootView.Background = new SolidColorBrush(ColorHelpers.Parse(0xFF123456));
}
```
=> Added the ability to override the root view background

local-cli/generator-windows/index.js, local-cli/generator-windows/templates/proj/MyApp.csproj, local-cli/generator-windows/templates/src/Package.appxmanifest
This PR does the following changes while running `react-native windows` command.
* A new certificate for app signing using `New-SelfSignedCertificate` command will be Generated. 
* If the `New-SelfSignedCertificate` command failed on executing, it will fallback to the pre-existing certificate .
* The `Publisher` property in `Package.appxmanifest` will be Updated to `CN=<current user name>`.
=> Generate self signed Certificate on Initialization

local-cli/rnpm/windows/package.json, local-cli/rnpm/windows/src/common.js
Use the registry uri set in npm config instead of defaulting to the npmjs.org uri in case users are running a private npm registry.
=> fix(rnpm-plugin-windows): use registry uri set in npm config instead of defaulting to npm uri

local-cli/generator-windows/index.js
In some cases, if the windows directory doesn't already exist, the Powershell command won't actually generate the file correctly. cc: @sasivarnan
=> fix(generator): Fix temp cert generator behavior

ReactWindows/ReactNative.Shared/Bridge/NativeModuleBase.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs
This change was previously overlooked. On UWP, expressions are interpreted rather than compiled, so it's actually faster to just use direct reflection.
=> fix(NativeModuleBase): use reflection for UWP

ReactWindows/ReactNative/UIManager/BaseViewManager.cs
The reset logic for the `transform` prop neglected to reset the workaround case of simple translations.
=> fix(BaseViewManager): ensure translation transforms are reset

ReactWindows/ReactNative.Shared/UIManager/ViewManager.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
We needed to include a hack that applied the transform matrices from the center of the view as opposed to from the top left corner of the view. In some cases, this hack was not applied because the width and height of the view had not yet been set by the layout engine. To work around this, we apply the transforms any time the dimensions of the view are updated.
Fixes #1182
=> fix(BaseViewManager): Ensure transform is applied from view center

ReactWindows/ReactNative.Shared/Pooling/ObjectPool.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/YogaNodePool.cs
The shadow view hierarchy allocates and destroys many YogaNodes as React Native views change. This adds a pooling mechanism to reuse YogaNode instances after they've been released.
Fixes #1210
Fixes #71
=> feat(YogaNodePool): Adds pool for YogaNodes

ReactWindows/ReactNative.Shared/Pooling/ObjectPool.cs
YogaNodes are created and destroyed under a single-threaded assumption, so we can use a simpler model without synchronization to improve performance.
=> perf(ObjectPool): Make object pool faster for YogaNode scenario

ReactWindows/ReactNative.Shared/UIManager/ReactShadowNodeVisitor.cs, ReactWindows/ReactNative.Shared/Views/Text/ReactInlineShadowNodeVisitor.cs
The shadow node visitor for measuring text recurses into nested views, when it should bail out at the root embedded view. This change adds a hook to ensure only root nested views in text are used in measurement.
Fixes #1216
=> fix(Text): text inline shadow node visitor recurses too far

ReactWindows/ReactNative/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/project.json
The `SetClipToBounds` property from `WinRTXamlToolkit` is too simple to implement to justify the dependency. Also, the approach that uses dimensions seems to be a bit less complex that relying on both a XAML dependency property and the SizeChanged event.
Fixes #1214
=> fix(BaseViewManager): Remove dependency on WinRTXamlToolkit

Libraries/Components/Picker/PickerWindows.js
Recent refactoring eliminated deprecated `React.PropTypes` in favor of `prop-types` module. This change was overlooked during the refactoring (cc @jmcginty).
Fixes #1220
=> fix(PickerWindows): Fix overlooked change from recent refactoring

ReactWindows/ReactNative/UIManager/BaseViewManager.cs
A recent change to BaseViewManager seems to have broken simple translate transforms. It looks like a UWP bug where subsequent matrices set to an existing MatrixTransform are ignored. This change works around that issue.
Fixes #1225
=> fix(BaseViewManager): fixes simple translate transforms

NuGet.Config, ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj, ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj, ReactWindows/ReactNative.Net46/packages.config, local-cli/generator-wpf/templates/proj/MyApp.csproj, local-cli/generator-wpf/templates/proj/NuGet.Config, local-cli/generator-wpf/templates/proj/packages.config
* We were using a prerelease build from myget.org, which got removed. Now that the relevant nuspec changes are officially released, we should use the official feed anyway.
=> Use official releases of ChakraCore from nuget.org

ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/IReactQueueConfiguration.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/MessageQueueThread.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/MessageQueueThreadKind.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/MessageQueueThreadSpec.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfiguration.cs, ReactWindows/ReactNative.Shared/Bridge/ReactContext.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs, ReactWindows/ReactNative.Tests/Bridge/Queue/MessageQueueThreadTests.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs
Prior to this change, layout was performed on any background thread. Because of this, we had to perform text measurement on the UI thread, which incurred many blocking calls to the UI. This change adds a secondary CoreApplicationView + Dispatcher in UWP and a secondary STA thread in WPF. This thread is characterized as the layout thread, which is only used from the UIManager. All text measurement calls can now be made directly without having to context switch to the main UI thread.
Fixes #106
=> feat(Text): Measure Text on Dispatcher directly

ReactWindows/ChakraBridge/ChakraBridge.vcxproj, ReactWindows/ChakraBridge/ChakraBridge.vcxproj.filters, ReactWindows/ChakraBridge/ChakraHost.cpp, ReactWindows/ChakraBridge/ChakraHost.h, ReactWindows/ChakraBridge/ChakraStringResult.h, ReactWindows/ChakraBridge/JsIndexedModulesUnbundle.cpp, ReactWindows/ChakraBridge/JsIndexedModulesUnbundle.h, ReactWindows/ChakraBridge/JsModulesUnbundle.cpp, ReactWindows/ChakraBridge/JsModulesUnbundle.h, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.h, ReactWindows/ChakraBridge/pch.h, ReactWindows/ReactNative.Shared.Tests/Internal/MockJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared.Tests/ReactNative.Shared.Tests.projitems, ReactWindows/ReactNative.Shared/Bridge/IJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared/Bridge/ReactBridge.cs, ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared/Common/InetHelpers.cs, ReactWindows/ReactNative.Shared/Common/IntegerHelpers.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
Adds unbundle support by adding a check in ChakraJavaScriptExecutor for the UNBUNDLE magic file, and by adding a `nativeRequire` hook to the Chakra runtime to dynamically load files when needed. The intent is that this should reduce app start times by reducing the amount of JavaScript that needs to be initially processed, but it doesn't seem to have much effect on the simple Playground and UIExplorer apps I've tested it on.
Remaining TODO: add unbundle support to NativeJavaScriptExecutor
Depends on facebook/react-native#12423
Fixes #952
=> feat(unbundle): Adds unbundle support to react-native-windows

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs, ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative.Shared/UIManager/Events/IEventDispatcherListener.cs
Native handled events still need to be dispatched to JS in case multiple listeners are attached to the event (e.g., in the case of a ListView with sticky headers).
=> fix(NativeAnimated): Dispatch native handled events to JS

ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/BaseLayoutAnimation.cs
Previously, only update and opacity animations were supported in LayoutAnimation. This change uses ScaleTransform to support scaleXY LayoutAnimation.
Fixes #217
=> feat(LayoutAnimation): Adds scaleXY support for LayoutAnimation

ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/BaseLayoutAnimation.cs, ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/LayoutAnimation.cs, ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/LayoutAnimationController.cs, ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/LayoutCreateAnimation.cs, ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/LayoutUpdateAnimation.cs, ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
A previous change decoupled `overflow: hidden` from the `SizeChanged` event for views. We have to keep this to support clipping on dependent animations (affecting size and position) generated from LayoutAnimation.
Fixes #1236
=> fix(LayoutAnimation): Fix overflow: hidden with LayoutAnimation

Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js, Libraries/Components/FlipViewWindows/FlipViewWindows.windows.js, Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js, Libraries/Components/Picker/PickerWindows.js, Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows.js, Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows.js, Libraries/Components/ScrollView/ScrollView.windows.js, Libraries/Components/SplitViewWindows/SplitViewWindows.windows.js, Libraries/Components/StatusBar/StatusBar.windows.js, Libraries/Components/TextInput/TextInput.windows.js, Libraries/Components/Touchable/TouchableNativeFeedback.windows.js, Libraries/Components/WebView/WebView.windows.js, Libraries/Image/Image.windows.js, Libraries/Text/Text.windows.js
This pull request should account for the changes needed in the Libraries. The RNTester project is not fixed as part of this. I can't clone the submodule - I just don't get how. 
I have forked the react-native-windows project.
I then clone my fork locally and edit. I can't push back my edits for the RNTester though, because it is trying to push to react-native-windows, not my branch. 
Any ideas?
=> Migrate from React.createClass

local-cli/runWindows/utils/deploy.js, local-cli/runWindows/utils/winappdeploytool.js
Passing in `stdio: inherit` prevents the output of executed command from being returned.
=> fix(local-cli): Incorrect usage of execSync.

local-cli/rnpm/windows/src/common.js, local-cli/runWindows/utils/deploy.js, local-cli/runWpf/utils/deploy.js
fix(local-cli): Missing `toString()` and `trim()` calls for specific `execSync()` calls.
Removed unnecessary require.
=> fix(local-cli): Missing toString() and trim() calls.

ReactWindows/ReactNative.Shared/UIManager/ThemedReactContext.cs
Recent API change to ThemedReactContext is missing a generic type constraint.
=> fix(ThemedReactContext): add missing generic constraint

ReactWindows/ReactNative.Shared/Modules/AppState/AppStateModule.cs
The way the JavaScript variable AppState.currentState gets initialized is problematic. It makes an initial asynchronous call to `getCurrentAppState`. The call ends up on the native module queue thread, where it could grab the current app state only to be interrupted by the UI thread running the `OnResume` lifecycle event. At this point, the `OnResume` event can queue a JavaScript call to send the `appStateDidChange` event, which will update `AppState.currentState` in JavaScript. After this, the native module can execute the JavaScript callback with the app state variable it originally captured (`uninitialized`), which will also set the `AppState.currentState` variable. Now the `AppState.currentState` incorrectly reports `uninitialized`.
To work around this, we can queue the call to …
=> fix(AppStateModule): Addressing race condition for AppState.currentState

appveyor.yml, spec/PlaygroundNet46TestSpec.js
Updated appveyor.yml to test with both VS2015 & VS2017 (along with their
respective platform toolsets), all configurations (Debug, DebugBundle,
Release, ReleaseBundle) and all platforms (x86, x64, ARM). However for
CI speed, only three configurations are hardcoded into the matrix. (SEE
COMMENTS).
FIXED: Tests weren't actually running except through OpenCover to record
coverage. Nunit3-console is now running and output tests results in an
AppVeyor-friendly format
Added missing run flow-check (fixes #1204, #1203).
=> fix(react-native-windows): Updated CI configuration.

ReactWindows/ReactNative.Shared/Modules/AppState/AppStateModule.cs
This reverts commit 8440edcd9c10ff100c7a74b59101dbe485ea3fe3. We actually don't need this because https://github.com/facebook/react-native/commit/809f1e97dea85cd259207ed729dcde6ed65a9348 was accepted.
Fixes #1313
=> Revert "fix(AppStateModule): Addressing race condition for AppState.currentState (#1301)"

ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
Prior to this change, the onLayout event fired even when the layout actually stayed the same.
Fixes #1335
=> fix(OnLayoutEvent): Only fire onLayout event when layout changes

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs
ReactAndroid uses the ReactChoreographer to guarantee that frame callbacks throughout the native bridge are executed in a guaranteed order per frame. We had no such ordering guarantees previously, as each component subscribed individually to the CompositionTarget.Rendering event.
Fixes #1323
=> fix(ReactChoreographer): Add guarantees for frame callback hook processing order

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs, ReactWindows/ReactNative.Shared/Animated/PropsAnimatedNode.cs, ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
Because of the batching mechanism built into the UIImplementation, views that are updated by the native animated module may not exist yet by the time the animation frames are processed. Previously, a try/catch block was wrapped around the view update, and exceptions have a considerable overhead. Instead, we first check if the view exists before attempting to update, and return a boolean value signaling whether or not the view was updated.
Breaking Change: UIImplementation API has changed.
=> perf(NativeAnimated): Eliminate exceptions for missing views

appveyor.yml
There was an issue with npm@5.4.0 running some of the post-install scripts that was causing the CI to fail.
Fixes #1315
=> fix(CI): resolve CI blockers using NPM LTS

ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs
=> fix(TextInput): Use Start and End paddings not supported by Yoga

ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
NavigationCompleted event args have a URI property that can be null (e.g., when you use the `NavigateToString` API). This changeset switches to a null propogating method call on the `Uri` property.
=> fix(WebView): Minor bug introduced in WebView

ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs
Only schedule work on the JavaScript queue thread if there are events to process.
Fixes #1356
=> perf(EventDispatcher): Reduce load on JavaScript queue thread

ReactWindows/ReactNative.Shared/Modules/Core/FrameEventArgs.cs
This change helps make minor adjustments to the initial absolute time to better align the absolute frame time with the CompositionTarget relative clock.
=> fix(ReactChoreographer): add self-adjustment to `FrameTime`

ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
Previously, the `IsOnDispatcher` check was for any dispatcher. Now, the dispatcher check is associated with the main window.
Fixes #1371
=> fix(DispatcherHelpers): Ensure correct dispatcher check

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Tests/Internal/DispatcherHelpers.cs, ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs
Various tests relying on CompositionTarget.Rendering behavior have broken since the ReactChoreographer refactoring. This patches those tests.
Fixes #1375
=> test(ReactChoreographer): fix broken tests from ReactChoreographer

ReactWindows/ReactNative.Net46/Modules/Storage/AsyncStorageModule.cs, ReactWindows/ReactNative.Shared/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs, ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative/Modules/DeviceInfo/DeviceInfoModule.cs, ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs, ReactWindows/ReactNative/Modules/Location/LocationModule.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs
Many modules used lifecycle event listener to subscribe / unsubscribe from the CompositionTarget.Rendering event. Since the event does not fire when the app is suspended, unsubscribing is not worth the additional code to maintain.
Fixes #1373
=> refactor(NativeModules): Remove ILifecycleEventListener

ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
DispatcherHelpers was broken on release builds for UWP due to the use of a separate CoreWindow for layout. Instead of trying to compare the dispatchers, this change assumes at least the first call to Dispatcher helpers from a dispatcher thread will be from the main window. DispatcherHelpers is well overdue for a refactoring.
Fixes #1377
=> fix(DispatcherHelpers): Fix broken release builds

ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative.Shared/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs, ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
We can track if any work is needed to be done by the ReactChoreographer. If we simply subscribe to the CompositionTarget.Rendering event all the time, we'll pay a battery life penalty for a small amount of CPU usage constantly. This PR adds a registration mechanism that notifies when callbacks are required.
Fixes #1343
=> fix(ReactChoreographer): Unsubscribe when no callbacks necessary

ReactWindows/ReactNative.Shared.Tests/Modules/Core/JSTimersTests.cs, ReactWindows/ReactNative.Shared/Modules/Core/JSTimers.cs, ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs
This changeset adds `setIdleCallback` support, now that we have a choreographer that can track frame deadlines.
There still seems to be an issue with getting idle callbacks on a regular basis for release builds. E.g., the "background" example in RNTester doesn't seem to fire very often (it only fires if there is at least 5ms of frame time remaining) in release builds (but does okay during Debug).
Fixes #917
=> feat(JSTimers): Add setIdleCallback support

ReactWindows/ReactNative.Shared/Modules/Network/DefaultHttpClient.cs
Although the NetworkingModule was coded to support incremental progress events, the HttpClient being used does not return from `SendRequestAsync` until the request is fully completed. Instead, we use `HttpCompletionOption.ResponseHeadersRead`.
Fixes #1380
=> fix(NetworkingModule): support incremental progress events

ReactWindows/ReactNative.Net46/Modules/DeviceInfo/DeviceInfoModule.cs, ReactWindows/ReactNative/Modules/DeviceInfo/DeviceInfoModule.cs
Refactoring of UIManager logic into DeviceInfoModule broke the dynamic dimensions update feature. This adds the module to the ReactContext lifecycle event listeners so the window size changes will be subscribed to.
Fixes #1384
=> fix(DeviceInfoModule): Ensure window size change events are emitted

ReactWindows/ReactNativeWebViewBridge/MessagePostedEventArgs.cs
MessagePostedEventArgs from WinRT component was not sealed and causing issues for Win App Cert Kit.
Towards #1401
=> fix(WebView): Seal WinRT component type

ReactWindows/ReactNative/project.json
Fix #1401.
More info about the issue [here](https://github.com/phongcao/image-pipeline-windows/issues/5).
=> fix(Image): Update ImagePipeline to v0.0.6 to fix Windows App Certification Kit error.

ReactWindows/ReactNative.Shared.Tests/Modules/Network/NetworkingModuleTests.cs, ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs
Requests without body were erroring because an assertion that the request required a content-type. This change fixes that assertion.
Fixes #1412
=> fix(NetworkingModule): fix bug for requests without body

local-cli/generator-windows/index.js, local-cli/generator-windows/templates/App.windows.js, local-cli/generator-windows/templates/src/MainPage.cs, local-cli/generator-wpf/index.js, local-cli/generator-wpf/templates/App.windows.js, local-cli/generator-wpf/templates/src/AppReactPage.cs
RN v0.49 switched to a single entry point template. This change leverages this single entry point and overrides the App.js template instead.
Fixes #1421
=> fix(Generator): Use index.js entry point for RN v0.49 generator

ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
Some scenarios, like background activation, only have a valid dispatcher on the `CoreApplicationView`, not necessarily on the CoreWindow.
Towards #1268
=> fix(DispatcherHelpers): Remove CoreWindow reference

ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs
Unnecessary call to DispatcherHelpers is used in the ImageLoader module.
=> fix(ImageLoader): remove DispatcherHelpers call

ReactWindows/ReactNative/project.json
Prior to react-native-windows v0.43.4, **ms-appdata** and file URIs are handled internally by [BitmapImage](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage)
```
var image = new BitmapImage();
disposable.Disposable = image.GetUriLoadObservable().Subscribe(
status => OnImageStatusUpdate(view, status.LoadStatus, status.Metadata),
_ => OnImageFailed(view));
image.UriSource = new Uri(source);
imageBrush.ImageSource = image;
```
ImagePipeline v0.0.8 can now handle both of them properly.
- Unit tests for ms-appdata URI [here](https://github.com/phongcao/image-pipeline-windows/commit/a6855b1c7b88e01337a93e30e53dbc007ed3e23f)
- Unit tests for file URI [here](https://github.com/phongcao/image-pipeline-windows/commit/97d97d8b3226bbd1adf8082b751e6dd1b5e40fb3#diff-4c3 …
=> fix(Image): Update ImagePipeline to v0.0.8 which handles ms-appdata and file URIs properly.

ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs, ReactWindows/ReactNative.Shared/Modules/DevSupport/SourceCodeModule.cs, ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs
Remove "RCT" and "RK" prefix from native modules.
=> clean(NativeModules): Remove deprecated naming convention

ReactWindows/ReactNative.Shared/Bridge/Queue/ActionQueueExtensions.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ActionQueueFactory.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/IActionQueueFactory.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
The factory helpers should make it easier to initialize the React instance off-dispatcher thread.
Towards #1288
=> refactor(ActionQueue): Add factory helpers to action queue

ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleRegistryTests.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs, ReactWindows/ReactNative.Shared/Bridge/ReactInstance.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Tests/Bridge/Queue/ActionQueueTests.cs, ReactWindows/ReactNative.Tests/Bridge/ReactInstanceTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, docs/ThreadingModel.md
The ReactInstance notifications for initialization and disposal should be run on the action queue for the native module rather than the dispatcher thread.
Fixes #1433
=> fix(NativeModuleRegistry): Run initialize and dispose on correct queue

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactRootView.cs, ReactWindows/ReactNative.Shared/UIManager/DependencyObjectExtensions.cs
Before being used by React Native, the root view children have to be removed and the associated data (tag and context) have to be cleaned as well. Making sure this is done as the React context is torn down.
=> refactor(RootView): change how root view instances are sanitized

ReactWindows/ReactNative.Net46.Tests/Modules/NetInfo/NetInfoModuleTests.cs, ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative.Net46/ReactPage.cs, ReactWindows/ReactNative.Shared.Tests/Modules/AppState/AppStateModuleTests.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative/Bridge/Queue/LayoutActionQueue.cs
There seems to be a bug in the single process background model for UWP where the CoreApplication.MainView.Dispatcher is no longer accessible after running an async operation. However, if we store the dispatcher in the `OnResume` lifecycle event, we can still have access to it. This change enables the capture of the main view dispatcher and replaces references to the captured instance.
Towards #1268
=> fix(Dispatcher): Store reference to dispatcher for background

ReactWindows/Playground/App.xaml.cs, ReactWindows/ReactNative.Net46/Modules/DeviceInfo/DeviceInfoModule.cs, ReactWindows/ReactNative.Shared/Bridge/IBackgroundEventListener.cs, ReactWindows/ReactNative.Shared/Bridge/ReactContext.cs, ReactWindows/ReactNative.Shared/Common/LifecycleState.cs, ReactWindows/ReactNative.Shared/CoreModulesPackage.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/ReactNativeHostExtensions.cs, ReactWindows/ReactNative/Modules/DeviceInfo/DeviceInfoModule.cs, ReactWindows/ReactNative/UIManager/DisplayMetrics.cs, local-cli/generator-windows/templates/src/App.xaml.cs
We need to enable DeviceInfoModule initialization in the background by zeroing out the main window dimensions and not subscribing to application view events (which are not available in the background). In order to ensure the app receives the events when the app transitions from background to foreground, this changeset adds an `IBackgroundEventListener` that is used by the DeviceInfoModule to subscribe to and unsubscribe from the application view events (and send the latest dimensions when the foreground is entered).
Towards #1268
=> fix(DeviceInfoModule): Support background transition to foreground

ReactWindows/ReactNative.Tests/UnitTestApp.xaml.cs
Many broken unit tests because of DispatcherHelpers.Initialize assumption.
=> test(DispatcherHelpers): Fix broken unit tests from UWP.

Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js, ReactWindows/ReactNative/Modules/AccessibilityInfo/AccessibilityInfoModule.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Shell/MainReactPackage.cs
The event is exposed as highContrastDidChange in AccessibilityInfo. For now
it only tells if high contrast is enabled or disabled in system settings. Later it
can tell what are the chosen high contrast colors: Windows 10 allows to create
custom high contrast themes with user chosen colors.
=> feat(HighContrast): Expose the XAML HighContrastChanged event to JS

ReactWindows/ReactNative/Modules/AccessibilityInfo/AccessibilityInfoModule.cs
Otherwise it may crash with an "Element not found" exception when trying to add a listener to HighContrastChanged.
=> feat(HighContrast): Subscribe to the event on dispatcher thread

.gitignore, CONTRIBUTING.md, README.md, ReactWindows/ChakraBridge/ChakraBridge.vcxproj, ReactWindows/Playground/project.json, ReactWindows/ReactNative.Tests/project.json, ReactWindows/ReactNative/project.json, ReactWindows/ReactNativeWebViewBridge/project.json, appveyor.yml, docs/GettingStarted.md, local-cli/generator-windows/templates/src/project.json
Updating the NuGet package fixes some issues with the dispatcher execution context in the background. In Microsoft.NETCore.UWP 5.x.x, the Dispatcher for the MainView had no execution context, so asynchronous methods would not return on the dispatcher thread.
=> fix(Background): Upgrade to Microsoft.NETCore.UWP 6.0.1

ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs
Cancellation token now throws if requested by the user, rather than swallowing the exception and returning null.
=> test(ReactInstanceManager): Fix broken unit test from cancellation support

ReactWindows/ReactNative.Net46.Tests/Modules/NetInfo/NetInfoModuleTests.cs, ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative.Net46/ReactPage.cs, ReactWindows/ReactNative.Shared.Tests/Modules/AppState/AppStateModuleTests.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Tests/UnitTestApp.xaml.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative/Bridge/Queue/LayoutActionQueue.cs
Reverts Microsoft/react-native-windows#1482
Sorry for the churn, it turns out we do need to cache the `CoreDispatcher` for processes running in the background. This is another reason why we should parameterize the ReactInstance on a dispatcher abstraction a) to support multiple platforms and b) so we don't run into this issue again.
=> Undo "Revert "fix(Dispatcher): Store reference to dispatcher for background (#1454)"

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
ReactChoreographer needs to be reset to ensure that additional operations aren't enqueued on the dispatcher.
Fixes #1474
=> fix(OnSuspend): Reset ReactChoreographer when app suspends

ReactWindows/ReactNative/Modules/AccessibilityInfo/AccessibilityInfoModule.cs
…ackground
Uses the same pattern as DeviceInfoModule to subscribe/unsubscribe from the high contrast event only when the app is running in the foreground.
=> fix(AccessibilityInfo): Do not subscribe to accessibility events in background

ReactWindows/ReactNative.Shared/Bridge/Queue/LimitedConcurrencyActionQueue.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
Switching to the new default ActionQueue for native modules changes the assumption that async continuations are performed on the same thread (which has a nice side effect that allows us to avoid locks in the face of concurrency).
Fixes #1466
=> fix(NativeModulesThread): Revert to limited concurrency approach

ReactWindows/ReactNative.Shared/Bridge/Queue/ActionQueue.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ActionQueueExtensions.cs, ReactWindows/ReactNative.Tests/Bridge/Queue/ActionQueueTests.cs
Small bug fix to guarantee we don't return from `Dispose` until no more actions will be executed (including those currently executing). Also adds unit tests for other expected behaviors.
=> fix(ActionQueue): Dispose bug and unit tests for ActionQueue

ReactWindows/ReactNative/Views/Web/Events/WebViewLoadEvent.cs, ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
Mistakenly set DOM load starting event to `topLoadStart` instead of `topLoadingStart`. The direct events for `WebView` are mapped in the UIManager; the `topLoadStart` event is not mapped for the `WebView` whereas the latter is.
=> fix(WebView): Fix bug with `onLoadingStart` event

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs
Cancellation is not necessary here, and the `AsTask()` conversion causes the UI thread to hang when debugging.
=> fix(DevSupportManager): Remove cancellation from up-to-date bundle check

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative.Shared/DevSupport/DisabledDevSupportManager.cs, ReactWindows/ReactNative.Shared/DevSupport/IDevSupportManager.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
Initial API calls to IStorageItem are hanging, but blocking System.IO calls are not. Changed to System.IO.File APIs (which are blocking, but it's only for debug/dev code); these have an added benefit of being compatible with WPF.
=> fix(DevSupportManager): UWP hanging on IStorageItem APIs

ReactWindows/ReactNative.Net46.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs
This feature is currently only available for Android. For now, we need to add all generic events to each component viewConfig.
=> fix(UIManager): Prematurely stopped adding generic events to viewConfig

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
The default `MinWidth` and `MinHeight` for TextBox is 64 x 32. Overriding these values in the `SetDimensions` method to ensure the `TextBox` abides by the layout specified by Yoga. This is reasonably safe because Yoga has it's own implementation of `minWidth` and `minHeight`.
Fixes #1369
=> fix(TextInput): Override platform defaults for `MinWidth` and `MinHeight`

Libraries/Image/resolveAssetSource.windows.js
In React Native 0.50.*, a recent commit was added to always prepend `file://` to the JS bundle path (https://github.com/facebook/react-native/commit/b89d6c8e046b2166b28f351202be1ac56aa2f55d). This is incorrect behavior for react-native-windows, so overriding the `resolveAssetSource` module to ensure it doesn't happen.
Towards #1492
=> fix(resolveAssetSource): Remove logic that prepends `file://`

ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs
The default `MinWidth` and `MinHeight` for PasswordBox is 64 x 32. Overriding these values in the `SetDimensions` method to ensure the `PasswordBox` abides by the layout specified by Yoga. This is reasonably safe because Yoga has it's own implementation of `minWidth` and `minHeight`.
Fixes #1369
=> fix(PasswordBox): Override platform defaults for `MinWidth` and `MinHeight`

ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
The Background, Foreground, and Border color properties only affects the TextBox at rest, not during pointer over, disabled, or focused. This uses the resources dictionary to override all of these scenarios when the user sets a color. I grabbed the UWP defaults to revert when the user sets the props to null.
Fixes #1004
Fixes #1040
Fixes #1502
=> fix(TextInput): Apply color, background, and borderColor props to all resources

ReactWindows/ReactNative.Shared/UIManager/EdgeSpacing.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs
Padding value was being doubled because it was included in the shadow node measurement as well as Yoga.
Fixes #1400
=> fix(TextInput): fix padding for TextInput

Libraries/Components/TextInput/TextInput.windows.js, ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs
Reverts Microsoft/react-native-windows#1444
This isn't implemented properly. There's a boolean at the root level of a view manager when view managers are responsible for many text inputs. By setting `blurOnSubmit` on one TextInput, you're effectively doing it for all of them with this PR.
=> Revert "implement WPF TextInput blurOnSubmit (#1444)"

ReactWindows/ReactNative.Shared.Tests/Internal/MockPromise.cs, ReactWindows/ReactNative.Shared/Bridge/IPromise.cs, ReactWindows/ReactNative.Shared/Bridge/Promise.cs, ReactWindows/ReactNative.Tests/Modules/Clipboard/ClipboardModuleTests.cs, ReactWindows/ReactNative.Tests/Modules/Image/ImageLoaderModuleTests.cs
With the current Reject implementations, it's challenging to control the `stack` and `userInfo` parameters. To control them, you have to construct an Exception object which is awkward if the error didn't originate as an Exception.
To solve this, a new Reject is exposed which enables the caller to explicitly specify the `stack` and `userInfo` arguments.
An especially useful use case for this Reject variant is when a ReactMethod calls into another process (e.g. a background task) and the other process returns an error. The new version of Reject makes it easy to forward this other process's error to JavaScript while keeping the `stack` and `userInfo` parameters intact.
=> Add Reject impl where all arguments are explicit

ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextBox.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
A setting on a single TextInput has the potential to affect all other TextInput's `onSelectionChange` behavior. This makes the setting local to a single <TextInput/> component.
=> fix(TextInput): Don't set component props to fields on ViewManager

ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextBox.cs
Ensures that size-related updates to the TextInput are only sent when the TextInput has focus.
Fixes #907
=> fix(TextInput): Do not send `onTextChange` event on render

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
Ensure that the blur command, which works by focusing on the current window Frame, does not execute if the TextBox does not currently have focus.
=> fix(TextInput): Do not blur if TextInput not focused

ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs
Ensure that the blur command, which works by focusing on the current window Frame, does not execute if the PasswordBox does not currently have focus.
=> fix(PasswordBox): Do not blur if PasswordBox not focused

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
When `value` or `defaultValue` is set on the TextInput, if the cursor started at the end, it should remain at the end after the text is updated.
Towards #1109
=> fix(TextInput): Ensure cursor stays at end of TextInput

Libraries/Components/TextInput/TextInput.windows.js, ReactWindows/ReactNative.Net46/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/UIManager/LayoutShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextBox.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextChangedEvent.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputContentSizeChangedEvent.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
The best way to support variable size TextInput is with the auto-grow property. This PR updates the JS for the TextInput component and adds the necessary changes to support auto-grow on UWP.
Towards #272
=> fix(TextInput): Support auto-grow for TextInput

ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextBox.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
There seems to be a bug with Yoga that increments the height of an auto-growing TextInput and creates an endless feedback loop. This adds a small hack to ensure that the next `SizeChanged` event is not fired after a `SetDimensions` call.
=> fix(TextInput): workaround for Yoga bug

ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs
There are a few properties that are currently set on `Border`:
- background color
- border color
- border width
- border radius
Since `Canvas` also has the `Background` property, the background
color can be set directly on `Canvas`, thus avoiding the need to create
an extra `Border` element. In cases when this is not possible, i.e. when
there is a non-zero border radius, the background color is transferred
to the inner `Border`.
This change also partially addresses the hit-test problem in WPF: if the
`Canvas` element doesn't have background color, it's not visible in the
hit-test tree. The issue is addressed only partially because once
the background is transferred back to `Border`, the `Canvas` becomes
invisible in the hit-test tree again.
=> feat(Borders): Do not create invisible borders and use Canvas.Background

ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative/project.json
**Improvements**
- Local images are now fetched as [BitmapImage](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage) instead of [WriteableBitmap](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap).
- Supporting fetching images from [FutureAccessList](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions#Windows_Storage_AccessCache_StorageApplicationPermissions_FutureAccessList) (_urn:future-access-list:{GUID}_).
This fixes #1557 #1463 #1492 after landing.
cc @antonkh
=> fix(Image): Update ImagePipeline to v0.1.1.

ReactWindows/ReactNative.Net46/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
DependencyObjectExtensions maintains DependencyObjectData objects attached to each native view. 
There is a ClearData cleanup method that's supposed to be called when a view is destroyed, but the current code doesn't do that.
As a result memory usage increases during the life time of an application.
The fix is to call ClearData from NativeViewHierarchyManager.DropView.
This exposes some cases where some asynchronous completion of an operation initiated by a view happens after the view is unmounted. Added some checks to prevent exceptions in one of these cases.
There may be other cases as well!
A more ideal solution would do the cleanup when the view reaches a reference count of 0, but that would require some major changes of the view lifetime, etc.
=> Fix DependencyObjectData leak

ReactWindows/ChakraBridge/ChakraHost.cpp, ReactWindows/ChakraBridge/ChakraHost.h, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.cpp, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.h, ReactWindows/Playground/MainReactNativeHost.cs, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
Before this change RNW did serialization on the same thread: first it generated
bytecode and saved it to a file, then it loaded the bytecode. Now RNW creates
a background thread where it creates the 2nd JSRT execution context and uses
it to generate the bytecode, while the primary JS thread is loading the raw JS.
The 2nd execution context is necessary because JSRT allows an execution context
to run on one thread at a time (it can jump between threads, but cannot run on
two threads simultaneously).
=> feat(BackgroundSerialization): Generate bytecode in a background thread

Libraries/Components/View/ViewPropTypes.windows.js, ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
This seems to cover all the functionality we require right now, but I was
hoping someone might point me in the right direction of a more general
solution where the tooltip could be composed out of components.
In particular, I'm not sure how to allow a React component to define the
tooltip and pass it to the native side without actually rendering it as part
of the regular RN component tree first. Doing off-screen rendering could
perhaps work, but it puts an unnatural burden on users where they have to
give it a `position: 'absolute'` style etc. It also seems like it would lead
to re-parenting complexities on the native side.
In any case, I'll probably leave such work for the future unless someone
objects.
=> Add simple text tooltips to views.

Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js, Libraries/Components/FlipViewWindows/FlipViewWindows.windows.js, Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js, Libraries/Components/Picker/PickerWindows.js, Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows.js, Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows.js, Libraries/Components/ScrollView/ScrollView.windows.js, Libraries/Components/SplitViewWindows/SplitViewWindows.windows.js, Libraries/Components/StatusBar/StatusBar.windows.js, Libraries/Components/TextInput/TextInput.windows.js, Libraries/Components/Touchable/TouchableNativeFeedback.windows.js, Libraries/Components/WebView/WebView.windows.js, Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.windows.js, Libraries/Image/Image.windows.js, Libraries/Text/Text.windows.js, docs/NativeComponentsWindows.md
RN 0.46.4 uses React 16.0.0-alpha.12 which is currently incompatible with RNW 0.46 because PropTypes (`React.PropTypes`) was moved out of the "react" library and into its own library called "prop-types".
This fixes the issue by cherry-picking the relevant RNW commits which update RNW to consume prop types from the appropriate location. Also cherry-picked a change to migrate away from `React.createClass`.
=> Make RNW 0.46 compatible with RN 0.46.4

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedModule.cs, ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs
It does deactivate it when no animation is active anymore.
Added "ActivateCallback" call to the point where UIBlock objects are sent to operations queue.
Without this fix there are scenarios that are impacted if an active animation takes a
long time.
=> Animation module doesn't activate callback from choreographer.

README.md
Clicking on the link to the React Native documentation resulted in a 404.
=> Fixed link to React Native documentation in Readme

ReactWindows/ReactNative.Shared/Common/LifecycleState.cs, ReactWindows/ReactNative.Shared/Common/LifecycleStateMachine.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs, package.json
Current code had some issues like moving the contexts just into "background" when suspending (on >=RS1 Windows), etc.
Changed the code a little bit for consistency.
- contexts always go through OnResume, OnLeavingBackground, OnEnteredBackground, OnSuspend now, regardless of the OS version
- Renamed the internal Resumed state to Foreground since it better reflects the "running in foreground" state.
=> Fixed lifecycle state machine

ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs
Unlike measure(), measureInWindow() is supposed to return only x, y,
width, height. Technically a breaking change but fixes the API to
match the documentation.
https://facebook.github.io/react-native/docs/direct-manipulation.html#measureinwindowcallback
=> Fix measureInWindow() to invoke the callback with correct arguments

ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs
Occasionally, if you click the root Span inline of the RichTextBlock rendered for the React Native <Text/> component, the app will not find the "tag" that was targeted, and will crash.
Fixes #1622
=> fix(Text): Prevent crashing from touch/click

package.json
Updating to `react-native@0.53.*`, as well as other related dependencies.
=> chore(NPM): update to `react-native@0.53.*`

Libraries/Components/TextInput/TextInput.windows.js, ReactWindows/ReactNative.Net46/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative.Shared/UIManager/Events/KeyEvent.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
I had added KeyDown/Up events to TextInput some time ago, but the correct way would've been to use the already defined onKeyPress.
Reverting the damage and moved to using this existing event.
=> Align TextInput keyboard events to the other platforms.

ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs, ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs
ReactTextInputShadow uses a measure function to compute text size. We also used to piggyback on that callback to retrieve the computed padding (that we do push to the TextBox controls).
The problem is that Yoga refrains from calling the measuring function when it already knows the sizes (usually due to a parent enforcing a particular size irrespective of text content).
I moved the retrieval of computed padding to the "collection of extra data" point.
=> Fixed padding issue in TextInput

FacebookLicense/LICENSE, FacebookLicense/PATENTS, FacebookLicense/README.md, README.md
Some files in react-native-windows are copied over from react-native and modified. These files, except for their modifications that are specific to react-native-windows, are originally provided by Facebook under the BSD-style license and Facebook's grant of patent rights from Facebook's repo.
*Please note* - this is not a change in licensing terms. These terms were already in existence and documented through the file headers of copied source code. This change only serves to provide a specific link to the Facebook licensing terms referenced in certain files in this repository.
=> Accounting for Facebook license and grant of patent rights

ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs
We need to make sure the "elapsed" time grows monotonically across suspend/resume cycles.
(this is a regression from the multi-window support work since I missed this subtlety - https://github.com/Microsoft/react-native-windows/pull/1615)
=> Make choreographer StopWatch a per thread static

ReactWindows/ReactNative/Touch/TouchHandler.cs
Originally only unhandled events were propagated up and pointer events from native components with their own handling where ignored. For example clicks on selectable text were ignored etc so this should fix #564.
=> use AddHandler to register pointer handlers so we also get 'handled' events

.gitattributes
so I don't lose my mind when VS2017 flips the line endings and created a bunch of diff noise.
=> apply consistent whitespace normalization for project files 

ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs
Extended the life of main ReactChoreographer and DispatcherHelpers across the suspend/resume hiatus.
OnSuspend is not something called after all other activity in the process ceased. Various activities continue for a while and nuking and later renewing instances or ReactChoreographer asserts when suspending, affects timers on resuming, etc.... with lots of bad side effects.
I had to tweak tests a little since they are not really independent of each other.
=> Fix crash ("ReactChoreographer needs to be initialized.") on suspend

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
Both showsHorizontalScrollIndicator and showsVerticalScrollIndicator default to true on other RN platforms and that value maps to Auto.
=> Fix "show*ScrollIndicator" defaults

ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs
Previously, setting `borderColor` before `borderWidth` would always
result in a black border, since `GetOrCreateBorder` did not check
if a color had already been set. This meant that views defined, eg,
like this:
```
<View style={{borderColor: 'blue', borderWidth 2}}>
...
</View>
```
Always had a black (default colored) border, instead of the one assigned
by the user.
Verified in RNTester.
=> Apply `borderColor` (if set) on Border creation.

ReactWindows/ReactNativeWebViewBridge/ReactNativeWebViewBridge.csproj
The project was converted to package references in the .csproj, but the project.json reference was not removed.
=> chore(WebViewBridge): remove project.json from .csproj

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs
The DevSupportManager has a Debugger.Break() call. This is not particularly useful because by the time this is hit, we've lost the callstack of the exception (except the stacktrace inside the exception itself). It's not useful for debugging because we can't inspect variables on the stack. Good riddance.
=> fix(DevSupport): Remove Debugger.Break

ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
ReactNative.Net46 was still referencing the Yoga package from NuGet in addition to the submodule.
=> fix(Yoga): remove NuGet Yoga reference

ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation/LayoutAnimationController.cs
Previously, the layout animation controller chose whether to animate using "create" or "update" logic based on the ActualWidth and ActualHeight of the framework element. This is not valid, as some views may have an ActualWidth or ActualHeight before ReactNative sets any dimensions. Instead, we use the view managers GetDimensions API to check if ReactNative has set anything yet.
=> fix(LayoutAnimation): Fix minor bug in LayoutAnimation

local-cli/generator-windows/templates/proj/MyApp.csproj
Issue #1329 was to remove project.json files. I think this is the last one.
Seems to work fine without this.
=> Remove redundant project.json reference

ReactWindows/ReactNative.Shared/UIManager/ViewManager.cs
The `display` prop is considered layout only. When set, it sets the dimensions of all elements in the subtree to zero. If the view is first created with `display: none`, its props aren't updated, because Yoga assumes the initial dimensions are (0, 0, 0, 0). UWP does not have this assumption for some views (like RichTextBlock), so the <Text/> inside a <View/> initially created with `display: none` will be displayed.
There were two options for getting around this:
1. Set the initial dimensions of all views to (0, 0, 0, 0) for consistency with Yoga.
2. Set all FrameworkElements to `view.Visibility = Visibility.Collapsed`
This changeset uses the former option as it may be easier to generalize to any view manager type. Using the latter case might be more performant as it will take the view out …
=> fix(View): Fix for style prop `display: none`

ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
The included version of ImagePipeline already supports passing in a dispatcher to accommodate for multi-window scenarios (in UWP).
=> Use current view's dispatcher when calling ImagePipeline

ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
A recent change (#1704) now calls `SetDimensions` before a tag has been set on the view. The image view manager uses the SetDimensions event to choose the correct image source when multiple URIs used. This change removes the dependency on `GetTag()`.
=> fix(Image): `SetDimensions` should not rely on tag

ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs
This is a small regression from multi window work.
There is an expected race condition for this animation related code path when tags may have been deleted already. Previous code used to check the presence of the view before calling UpdateProperties.
Multi window added the "tag to queue" lookup, so we piggy backed on that one for the check.
Problem is, that lookup checks a different data store, with different item lifetimes. In fact that store is cleanup more lazily, so the window for the tag to exist in the lookup table but not in NativeViewHierarchyManager is wider..
Added back the missing check to prevent app crashing.
=> Correct check for tag presence during synchronous animations

Libraries/ReactNative/requireNativeComponent.windows.js, ReactWindows/ReactNative.Net46.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs
Currently, the constants for each view manager type includes the generic event types. This change enables behavior similar to React Native Android where generic event types are merged with view manager specific event types in JavaScript.
=> perf(UIManagerModule): remove duplicate generic event types

Libraries/ReactNative/UIManager.windows.js, Libraries/ReactNative/requireNativeComponent.windows.js, ReactWindows/ReactNative.Net46.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative.Shared/CoreModulesPackage.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactInstanceManagerBuilder.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementationProvider.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModuleOptions.cs, ReactWindows/ReactNative.Shared/UIManager/ViewManagerRegistry.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs
A significant chunk of app initialization is spent loading constants for view managers, many of which won't be used in the initial screen. This allows React to request view manager config on demand.
=> feat(ViewManager): Lazy load view manager constants

ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleBaseTests.cs, ReactWindows/ReactNative.Shared/Bridge/ReactDelegateFactoryBase.cs
ReactDelegateFactoryBase had stub behavior for native methods that returned tasks. The idea was to automatically convert those native methods to promise method types. We chose not to pursue this because the threading model for native modules is complicated enough without having to worry about guarantees for asynchronous behavior.
=> fix(ReactDelegateFactoryBase): Remove checks for methods that return Task

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueueInstance.cs, ReactWindows/ReactNative.Shared/UIManager/ViewManager.cs, ReactWindows/ReactNative.Shared/Views/Text/ReactRunManager.cs, ReactWindows/ReactNative.Shared/Views/Text/ReactSpanViewManager.cs, ReactWindows/ReactNative.Shared/Views/Text/ReactTextInlineViewManager.cs, ReactWindows/ReactNative/Accessibility/AccessibilityHelper.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
New code does a per batch processing of "dirty nodes" (as far as accessibility properties and tree structure are concerned) starting from roots.
This avoids work done on subtrees that are not added to main tree yet.
We avoid now that NotsupportedException case.
The inputs that "dirty" a node and its ancestors up to root are:
- any change of "importantForAccessibility" and "AccessibilityLabel"
- adding/removing a child
- "element changed" calls from controls that need accessibility re-assessed when some of their properties change (Text control is one of these in the current code)
The output consists of the "AccessibleView" and "Name" automation properties for each control.
=> Refactored AccessibilityHelper to do a top down processing of acc prop changes

ReactWindows/ReactNative.Net46/DevSupport/WebSocketJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared.Tests/Chakra/Executor/ChakraJavaScriptExecutorTests.cs, ReactWindows/ReactNative.Shared.Tests/Internal/MockJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared/Bridge/IJavaScriptExecutor.cs, ReactWindows/ReactNative.Shared/Bridge/ReactBridge.cs, ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs, ReactWindows/ReactNative/DevSupport/WebSocketJavaScriptExecutor.cs
The ReactBridge writes the RN config to a string, but then because of the interface for `IJavaScriptExecutor`, parses it to a JSON data model object, only to immediately re-serialize it. This change removes the parse and re-serialize steps.
=> perf(Bridge): Do not re-parse `__fbBatchedBridgeConfig`

ReactWindows/ReactNative/Accessibility/AccessibilityHelper.cs
We were passing a "hideChildren = true" when we actually wanted to un-hide..
=> Fixed typo in accessibility

ReactWindows/ReactNative.Shared/ReactRootView.cs, ReactWindows/ReactNative/Accessibility/AccessibilityHelper.cs
RS1 is more austere with regards to creating AutomationPeer objects for Canvas (compared to >RS2). Made code resilient to this.
=> Fix accessibility on RS1 machines.

Libraries/Components/FocusableWindows/FocusableWindows.windows.js, ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
To match behavior on Web, the control should not participate in tab stop when `display: none` is set.
Towards #1705
=> fix(FocusableWindows): disable tab stop when `display: none`

ReactWindows/ReactNative.Net46.Tests/Internal/DispatcherHelpers.cs, ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative.Shared/Bridge/Queue/ActionQueueExtensions.cs, ReactWindows/ReactNative.Tests/Bridge/ReactInstanceTests.cs, ReactWindows/ReactNative.Tests/Internal/DispatcherHelpers.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
Previously, to avoid the possibility of continuations being run on the IActionQueue or Dispatcher threads, we did something like:
```
Task.Run(() => taskCompletionSource.SetResult(...))
```
This is unnecessary overhead, when we can simply configure the `TaskCompletionSource<T>` to never inline continuations by using the constructor parameter `TaskCreationOptions.RunContinuationsAsynchronously`.
=> fix(ActionQueue): use TaskCreationOptions.RunContinuationsAsynchronously

ReactWindows/Playground/App.xaml, ReactWindows/Playground/App.xaml.cs, ReactWindows/ReactNative/IReactApplication.cs, ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs, ReactWindows/ReactNative/ReactApplication.cs, ReactWindows/ReactNative/ReactApplicationDelegate.cs, ReactWindows/ReactNative/ReactNative.csproj, local-cli/generator-windows/templates/src/App.xaml, local-cli/generator-windows/templates/src/App.xaml.cs
There are two goals of this base class:
1. Reduce boiler plate in the generated solutions for react-native-windows
2. Manage things like URL activations, lifecycle state subscriptions, etc. from within react-native-windows.
This is only the first step, we will likely also need to create something like a ReactApplicationDelegate, similar to the ReactActivityDelegate to separate these initialization behaviors from a concrete base class as all apps will not be able to use the ReactApplication base class.
=> feat(ReactApplication): Adds Application base class

ReactWindows/ReactNative.Shared/DevSupport/StackTraceHelper.cs, ReactWindows/ReactNative/DevSupport/RedBoxDialog.xaml, ReactWindows/ReactNative/DevSupport/RedBoxDialog.xaml.cs, ReactWindows/ReactNative/DevSupport/SourceInfoVisibilityConverter.cs, ReactWindows/ReactNative/ReactNative.csproj
Setting `needFileInfo` seems to cause a `FileNotFoundException` and hides the original native exception. Disabling for now until this can be resolved.
=> fix(DevSupport): set `needFileInfo` param to false

ReactWindows/ReactNative.Net46/Views/Web/ReactWebViewManager.cs
**Issue description:**
Steps to reproduce the problem:
1. Load “http://google.com” in a Webview
**Example:**
<WebView
onNavigationStateChange={this.onNavigationStateChange}
source={{ uri: “http://google.com”}}
/>
2. Observe - **onNavigationStateChange** is not triggered for redirect URLs (only trigged for https://www.google.com with 204 response and not for any other intermediate redirects/(301,307) URLs)
Here is the chrome browser Network data:
**Expected behaviour:**
I expect onNavigationStateChange trigged for all URL changes. It works this way in iOS and Android.
**Root cause:**
In RN WPF WebBrowser native class implements only **Navigated** and **LoadCompleted** interfaces. Navigated is fired for navigated events, that means it is not fired for redirect URLs.
**Proposed Solution:** …
=> RN WPF Webview: onNavigationStateChange is not triggered for redirect URLs

ReactWindows/ReactNative.Shared/UIManager/Events/EventDispatcher.cs
https://github.com/Microsoft/react-native-windows/pull/1786 introduced a regression in the UWP flavor since "Trace" returns null if no session is active (compared to a dummy object the WPF flavor does).
I could've reused the "dummy" object, but an inline check for null seems better memory consumption wise.
@matthargett FYI.
I'll just fast track this one :)
=> Fix a regression.

ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs
When the `Stopwatch` approach for `ReactChoreographer` was introduced when React Native is in the background, it introduced a bug that stopped using the `RenderingEventArgs.RenderingTime` property.
=> fix(ReactChoreographer): Use `RenderingEventArgs.RenderingTime`

ReactWindows/ReactNative.Net46/Views/Scroll/ReactScrollViewManager.cs, ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs, ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
When the `backgroundColor` is set to `null` or removed from the style props, we can also remove the `Background` property `Brush` object.
Currently, when `backgroundColor` is set to some value, then subsequently set to null, the `Background` property will be set to a transparent brush. This changeset fixes that behavior.
=> fix(View): Remove background brush when possible

ReactWindows/ChakraBridge/ChakraHost.cpp, ReactWindows/ChakraBridge/SerializedSourceContext.h, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
NativeJavaScriptExecutor in "serialized bytes" mode keeps a cache (a file with bin extension) with the precompiled JS bundle.
The format is OS version dependent though, so a failure to run the serialized script should be followed by a second chance attempt to run the original bundle.
=> Fix for NativeJavaScriptExecutor crashing after OS upgrade.

ReactWindows/ReactNative.Shared/Modules/I18N/I18NUtil.cs
A ResourceContext.GetForCurrentView used in i18NUtil fails miserably when the view has no CoreWindow.
We use now a GetForViewIndependentUse that seems to fare better.
=> Fix a crash on start in i18NUtil id allowRTL is set to true (the UWP flavor)

ReactWindows/ReactNative.Net46/Views/Web/ReactWebViewManager.cs
**Issue description:**
Steps to reproduce the problem:
1.      Load “file:///C:/test.html” in a Webview
**Example:**
<WebView
source={{ uri: "file:///C:/test.html”}}
/>
2.  Observe - It throws exception "only http and https schema are allowed". (only worked for http or https URIs)
**Expected behaviour:**
I expect it should load the file scheme URI also (to support loading local files). It works this way in native WPF application as well as in iOS and Android (Also, works in UWP by using these URL scheme: ms-appdata/ms-appx-web).
**Root cause:**
In RN WPF WebBrowser native class: **SetSource** method, **HttpRequestMessage.RequestUri** Property only allows HTTP(s) request and throws exception for file URL schemes.
Whereas, native WPF WebBrowser class perform a File scheme URIs check using …
=> RN WPF Webview: File scheme (file://) URIs are not loaded.

local-cli/runWpf/utils/msbuildtools.js
Close #1823
`execSync` returns `null` when passing `{ stdio: 'inherit' }` (c.f. https://github.com/nodejs/node-v0.x-archive/issues/9265#issuecomment-75768943).
So, this PR adds null check to avoid referring to null.
=> Add null check to deal with the issue occurred by `{ stdio: 'inherit' }`.

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs
Close #1821 
When a WPF app uses `react-navigation`, the conditions `transforms == null` and `_transforms.Length == 0` can hold in the `SetTransform` method.
In this case, `SetProjectionMatrix` method is invoked even though `transforms` is `null`, then `NullPointerException` occurs.
So, this PR changes `SetTransform` method to not invoke `SetProjectionMatrix` method if `_transforms.Remove(view) == false`.
=> Do nothing if a previous transform is not be removed.

ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj, ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
Close #1819 
The reason why the compilation errors occur is that some NuGet dependencies are referred using `..\packages`.
So, this PR replaces `..\packages` with `$(SolutionDir)\packages` to fix the compilation errors.
Please note that I modified `ReactNative.Net46.Tests.csproj` just for the consistency even though `ReactNative.Net46.Tests.csproj` is not related to the compilation errors.
=> Use `$(SolutionDir)\packages` instead of `..\packages`.

ReactWindows/ReactNative/ReactApplication.cs, ReactWindows/ReactNative/ReactApplicationDelegate.cs
Similar to the `getLaunchOptions` in React Native for Android on the `ReactActivityDelegate`, this adds a property that apps can override to send initial props to the React app.
Fixes #1774
=> feat(ReactApplication): Adds `LaunchOptions` property to `ReactApplicationDelegate`

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs
ReactInstanceManager.OnSuspend does a cancel of any pending context initialization operations, said operations ending up with a null context.
We need to reset a flag in that case, otherwise further attempts to create the context will always return null.
=> Fixed a cancellation issue

ReactWindows/ReactNative.Shared/Views/Control/ReactControlManager.cs
This breaks a case where a control with focus is changed to "not keyboard focusable". As a result, in the old code we lose the "lost focus" event.
Some apps may rely on receiving that.
=> Remove optimization that does more harm than good

ReactWindows/ReactNative.Shared/UIManager/LayoutShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/TransformHelper.cs
Using percent style with a decimal value (e.g. '7.8%') throws 'FormatException" in some locales
https://github.com/Microsoft/react-native-windows/issues/1849
=> Adding invariant culture qualifier to all decimal based parsing methods to prevent FormatException

ReactWindows/ReactNative.Net46/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs, ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs
In some scenarios, like multi window scenario, we need to have ability to run on Dispatcher which is associated with view specified by react tag. RunOnDispatcherThread takes action and react tag, tries to find view dispatcher based on reactTag and invokes action there.
=> Adding RunOnDispatcherThread

ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
**Problem:**
When navigating to UriEncoded url - it is decoded by the webView and decoded Uri will be passed back to JS client via `onNavigationStateChange` event. This behavior will trigger React Props update since original Uri might be encoded and Uri.ToString(), that was used before, has been already decoded. It results in extra navigation performed by the webView (page reload)
**Sample:**
JS client requested navigation to https://www.bing.com/entityexplore?q=Restaurants&filters=bar%3A"local"&foo=1&form=CSS4LR where queryParams are  UriComponentEncoded.
However, the callback will be invoked with:
https://www.bing.com/entityexplore?q=Restaurants&filters=bar:"local"&foo=1&form=CSS4LR
where `%3A` was decoded to `:`
Due to design of [Controlled](https://reactjs.org/docs/forms.html) React …
=> Passing original URI string to the NavigationStateChange JS callback

README.md
Just pointing to right place on the page and giving the link the same text as the section it goes to
=> Fix link to system requirements in README.md

ReactWindows/ReactNative.Net46/Views/Web/ReactWebViewManager.cs
Same changes as described and merged [here](https://github.com/Microsoft/react-native-windows/pull/1909) for .NET46
=> Passing original URI in navigationStateChange callback for .NET46

ReactWindows/ReactNative.Net46/Views/Web/ReactWebViewManager.cs, ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
**Problem:**
Due to Connected Components pattern in React - `ReactWebViewManager` might recieve `PropsUpdate` event from React with the same url as it has been already navigated to. In this case webView will start another navigation, which results in web page reload.
**Example:**
- JS trigger openUrl('https://foo.com');
- RNWebViewManager sends onNavigationStateChanged('https://foo.com') callback
- User clicks on the button inside foo.com which navigates him to https://foo.com/bar.
- RNWebViewManager sends onNavigationStateChanged('https://foo.com/bar') callback
- Since url has changed JS code will trigger `React` to update `WebViewManager` by updated props.
=> Here WebViewManager will trigger another navigation to 'https://foo.com/bar' despite the fact that this Url has been just loaded. …
=> WebViewManager: check previousUri before starting new navigation

ReactWindows/ReactNative.Net46/Modules/Storage/AsyncStorageModule.cs, ReactWindows/ReactNative.Shared/Modules/Storage/AsyncStorageHelpers.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs
Issue: As of now AsyncStorageModule does not catch any exceptions from the lower layers and so the caller would not know about those errors and this will most likely result in the app crashing since those exceptions might leak as unhandled exceptions.
Fix: Adding catch blocks at the appropriate places and calling the error callback with the exception details.
=> AsyncStorageModule should propagate the errors from lower layers to the callers

ReactWindows/ReactNative.Shared.Tests/Modules/Network/NetworkingModuleTests.cs, ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs
- Enabled auto redirects for network requests
**Comment:** without this changes every redirected request will be [rejected](https://github.com/Microsoft/SimpleRestClients/blob/43f734945370206b0d03a8ef77c6eeb24de902a3/src/SimpleWebRequest.ts#L676) by `SimpleWebRequest` JS module.
- Fixed response.url that will be send back to `SimpleWebRequest` JS module
**Comment:** in most of the cases, such as auth stories we are interested in "final" url after all redirections because this url will contain `a token` or any other parameter we need to use later. That is why it is important to return full url back to the JS XmlHttpRequests module.
Example: for url = http://foo.com/api?status=ok&code=bar
`Uri.AbsolutePath:` /api
`Uri.AbsoluteUri:` http://foo.com/api?status=ok&code=bar
=> [NetworkingModule]: enabled auto-redirects. Fixed response sent to SimpleWebClient

ReactWindows/ReactNative.Shared.Tests/Internal/MockReactInstance.cs, ReactWindows/ReactNative.Shared/Bridge/IReactInstance.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs, ReactWindows/ReactNative.Shared/Bridge/ReactInstance.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Tests/Bridge/ReactInstanceTests.cs, ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs
Change Summary:
Changed ReactInstance.Initialize to ReactInstance.InitializeAsync which awaits for Initialization of modules
Swap the call order of ReactInstance.Initialize and ReactInstance.InitializeBridgeAsync
Updated the test code to reflect the new signatures
Problem this solves:
When the modules are initialized, they may start calling JSModules right away (potentially in another thread). So we need to ensure that the bridge is initialized before the modules are initialized.
Further, once ReactInstance.Initialize returns, the caller, naturally, assumes that the ReactInstance is initialized and so is free to start using RNModules, but the RNModules may still be executing their Initialization code on the RNModule thread. We now ensure that ReactInstance.InitializeAsync returns only …
=> Ensuring that ReactInstance Initialize returns only after initialization of modules is complete

ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs, ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
When bridge is disposed, any synchronous hook call returns a null that crashes a later piece of code that tries to dereference it.
We're fixing by treating this case. The return value may still be incorrect as far as the calling function expects, but we're disposing anyway.
=> Prevent crash on dev reload

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs, ReactWindows/ReactNative.Shared/Animated/TrackingAnimatedNode.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
This "every platform has its own implementation in random languages for common code" approach has its drawbacks.. Sometime a "tracking a value" native animation showed up in RN, and we were left behind.
=> Implement "tracking" native animation, fixes crash in RNTester

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactRootView.cs, ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Tests/Internal/DispatcherHelpers.cs, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative.Tests/ReactRootViewTests.cs, ReactWindows/ReactNative.Tests/Resources/mwtest.js
1. Sometimes JS tried to create views before the parent root view has been added to shadow tree. This is due to UIManagerModule.AddMeasuredRootView being a "fire and forget" method. We made this an awaitable asynchronous function, so now AppRegistry.runApplication is only called after the measured root view addition completed.
2. Back to back "create/remove" root view operations had some corner cases (trying to remove a root view when its tag hasn't been set yet, or trying to remove a root view that is still waiting for measuring to occur)
Fixed those.
3. Added a stress UT.
=> Multi window race condition fixes

ReactWindows/ReactNative/ReactNative.csproj
Fixes an app fail fast in some memory configurations.
=> ImagePipeline version bump to 0.1.7

ReactWindows/ChakraBridge/NativeJavaScriptExecutor.cpp, ReactWindows/ChakraBridge/NativeJavaScriptExecutor.h
Cache heavily used JS method references for better speed and memory consumption in the Native executor.
(inspired by a more or less similar fix in the Chakra executor)
=> Cache heavily used JS method references in Native executor

ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
A subtle bug had been introduced with the delegated shadow nodes:
We piggyback on ReactShadownNode.HasNewLayout to compute/cache the "has new layout" from the delegated shadow node, as part of processing  ReactShadownNode.HasUpdates.
Relying on method with side effect proved to be bad choice, HasNewLayout can be easily shortcut if _nodeUpdated is true (HasUpdates => _nodeUpdated || HasNewLayout || IsDirty)
The fix moves the relevant code to an independent step.
=> Bug fix for delegated shadow nodes

ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleBaseTests.Generated.cs, ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleBaseTests.cs, ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleWrapperBaseTests.cs, ReactWindows/ReactNative.Shared/Bridge/CompiledReactDelegateFactory.cs, ReactWindows/ReactNative.Shared/Bridge/INativeMethod.cs, ReactWindows/ReactNative.Shared/Bridge/IReactDelegateFactory.cs, ReactWindows/ReactNative.Shared/Bridge/InvokeCallback.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleBase.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleWrapperBase.cs, ReactWindows/ReactNative.Shared/Bridge/ReactDelegateFactoryBase.cs, ReactWindows/ReactNative.Shared/Bridge/ReactInstance.cs, ReactWindows/ReactNative.Shared/Bridge/ReflectionReactDelegateFactory.cs, ReactWindows/ReactNative.Shared/CoreModulesPackageWrapper.cs, ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
IReactInstance exposes a lot of functionality that is only relevant to the native bridge, not necessarily to native modules. This change limits the API exposure of INativeModules to only invoking JS callbacks.
=> refactor(INativeModule): remove IReactInstance coupling

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs, ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
Using `IsHitTestVisible`, we can limit the conditions where we need to use `VisualTreeHelper` to only those instances where the first React view in the hit test uses `pointerEvents: box-none`. This should be a reasonably rare case, and can be avoided altogether if you never use a border brush on a view with `pointerEvents: box-none`. Given that any view in a subtree with `pointerEvents: none` at the root will no longer register as the `OriginalSource` for the `PointerRoutedEvent`, we now only need to check whether any parent of the `OriginalSource` applies the `pointerEvents: box-only` to take over as the pointer target.
cc @rigdern
=> perf(TouchHandler): Improve the performance of touch

ReactWindows/Playground/Playground.csproj, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNativeWebViewBridge/ReactNativeWebViewBridge.csproj, local-cli/generator-windows/templates/proj/MyApp.csproj
We haven't been rigorous about ensuring that any APIs from RS1 that are used have protected by ApiInformation checks. As such, moving the minimum target to RS1.
=> fix(ReactNative): Update minimum UWP target to RS1

ReactWindows/ReactNative.Shared/ReactRootView.cs
A corner case exists when all these are true:
- A root view is created and its adding to React instance is deferred for when the measuring happens.
- More than one MeasureOverride happen in a quick sequence
- The second (for ex.) MeasureOverride is executed before the first one completed the "reactInstanceManager.AttachMeasuredRootViewAsync(this)". 
The end result is the *this ReactRootView being added more than once. Results are catastrophic.
Fixed by correctly taking a snapshot/resetting the flag before any asynchronous operation is launched.
=> Fix race condition that can trigger the duplicate registration of a root view

ReactWindows/ReactNative.Shared/ReactRootView.cs
TouchHandler classes have a Dispose method that unsubscribes the instances from touch events.
This method is not currently called.
The fix adds the call to ReactRootView.StopReactApplicationAsync. It addresses a race condition that was exacerbated by a bug in our application (app closed the root view on click):
- application calls ReactRootView.StopReactApplicationAsync
- around that time, user clicks the area
- some events (like capture lost, etc.) may get dispatched to TouchHandler after the root view has lost its custom properties (tag, react context)
- the code in TouchHandler crashes when trying to execute _view.GetReactContext().
=> Dispose TouchHandler on ReactRootView.StopReactApplication*

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
Some time ago the handling of _hasStartedCreatingInitialContext was fixed to take into account failure scenarios (when the returning context is null). For some reason this tweak was not done in RecreateReactContextAsync.
Perhaps this is due to the name of the variable ending up not being very correct anymore.. Due to the serialization done by the awaitable lock, _hasStartedCreatingInitialContext == true means context exists, and _hasStartedCreatingInitialContext == false that it doesn't.
So a call of RecreateReactContextAsync that fails moves ReactInstanceManager into an unrecoverable state (_hasStartedCreatingInitialContext remains true, whereas context remains null).
The fix tries to address this issue.
=> Fix flag handling in RecreateReactContextAsync

package.json
React Native 0.57 [will let out-of-tree platforms register themselves](https://github.com/facebook/react-native/commit/03476a225e012a0285650780430d64fc79674f0f) using a "haste" key under the "rnpm" key in package.json. This pull will let react-native-windows get picked up by the React Native bundler.
Right now against 0.57 a complete bundle is not yet possible - the bundler sees the files with the `.windows.js` suffix, but because RNWindows is currently meant for RN 0.55 the structure is slightly different and some files are missing, e.g.:
```
Error: Unable to resolve module `ViewContext` from `{snipped}/node_modules/react-native-windows/Libraries/Image/Image.windows.js`: Module `ViewContext` does not exist in the Haste module map
```
=> Register react-native-windows as an out-of-tree platform

ReactWindows/ReactNative.Net46/Touch/TouchHandler.cs, ReactWindows/ReactNative.Net46/UIManager/UIViewOperationQueue.cs, ReactWindows/ReactNative.Shared.Tests/Bridge/NativeModuleWrapperBaseTests.cs, ReactWindows/ReactNative.Shared/Bridge/INativeModule.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleBase.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs, ReactWindows/ReactNative.Shared/Bridge/NativeModuleWrapperBase.cs, ReactWindows/ReactNative.Shared/Bridge/ReactInstance.cs, ReactWindows/ReactNative.Shared/Modules/Core/IReactChoreographer.cs, ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs, ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs, ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs, ReactWindows/ReactNative.Shared/ReactRootView.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs, ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueueInstance.cs, ReactWindows/ReactNative.Tests/Bridge/ReactInstanceTests.cs, ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs, ReactWindows/ReactNative/Modules/Location/LocationModule.cs, ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs, ReactWindows/ReactNative/Touch/TouchHandler.cs
Fixed the cleanup/leaks of the 2 "recreate react context" scenarios:
- signing out
- reload JS (CTRL/R, etc)
For all cases (single/multi window) made sure:
- all view/view manager state is cleaned by making sure the usual NativeViewHierarchy.DropView code paths are called for al cases
- keep touch handlers disabled during the limbo phase
For multi window we correctly destroy the old choreographers so new ones can take their place.
All JS root view apps are restarted after a "recreate react context". If the fresh JS app can't support these re-appearing ghost root views, it's that app's responsibility to close the secondary top level windows.
Note: this includes Eric Rozell's "asynchronous module dispose" commit: rozele@f67fc1b
=> Multi window support for context re-creation and other fixes

ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems, ReactWindows/ReactNative.Shared/Views/Text/ReactTextBlockSelectionEvent.cs, ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj, ReactWindows/ReactNative.Tests/Views/Text/ReactTextViewManagerTests.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
This will expose selection from RichTextBlock. When selection occurs, the code parses the content and builds a text string equivalent of the content (with certain assumptions). This is intended to allow for partial select/copy/paste functionality. Unit tests were also added.
=> Expose selection from RN.Text

docs/GettingStarted.md
The current documentation has a step that generates errors _on purpose_. This is disruptive to the learning process, regardless of the fact that the following step(s) should you how to continue.
This current version is ill-conceived documentation-design for anyone that doesn't follow documentation to the letter; many developers skim documentation. Injecting error-prone steps is just not good to do because of this, as it will then cause said skimmers to then try to troubleshoot _your_ documentation, assuming it's broken/outdated; an all too common occurrence.
This change will have you running the app without injecting error-prone steps, and will likely help close and prevent some of the dupes that keep cropping up due to this current documentation.
=> Improved tutorial flow

Libraries/Components/View/PlatformViewPropTypes.windows.js, ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative.Shared/UIManager/Events/TouchEventType.cs, ReactWindows/ReactNative.Shared/UIManager/Events/TouchEventTypeExtensions.cs, ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs, ReactWindows/ReactNative.Shared/UIManager/ViewExtensions.cs, ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs, ReactWindows/ReactNative/Touch/TouchHandler.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs
1. Added "mouse move" support.
2. Change "mouse enter/leave/over/out" to rely mainly on "mouse move" events rather than on UIElement.PointerEnered/Exited. The latter are fired when OS decides the pointer enter/left what it thinks is the hit target, but that is wrong in some scenarios like "box-none" views overlapping non-related views.
The new mechanism basically makes all events consistent with the target resolution offered by the TouchHandler.GetReactViewTarget.
=> [UWP] Added mouse move support and fixes some mouse enter/leave scenarios

ReactWindows/ReactNative.Tests/Views/Text/ReactTextViewManagerTests.cs, ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs
There was a bug in the parsing logic (in cases multiple level of embedded <Spans>) and as fixing of the bug also a simplification could be done to the parsing logic.
Test case was added to check for this situation.
=> Fix a bug in and simplify rich text block content parsing.

ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs, ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
Fixed error processing in CallOnDispatcher. The method is of a "Task<something>" type, so it shouldn't spill exceptions. Both types of results (successful and failure) have to be passed back in the Task.
=> Small fix on exception propagation in DispatcherHelpers Call* helper

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
Sometimes when using CTRL/R to reload the bundle some spurious restart of the app can happen on top of the expected one.
@rigdern  tracked the issue to a code path (HandleReloadJavaScript) that doesn't update _hasStartedCreatingInitialContext flag accordingly, and he also pointed out that the flag was redundant since _currentReactContext is always set under the awaitable lock, so its null or non-null state clearly point to whether the context is (not) present. 
Removed the flag, and that fixes the bug as well.
=> Fix for spurious app refresh during development

ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs
createTimer can be called before the native Timing module was initialized due to the way RNW initialization works.
The fix makes the reference to the JSTimers module initialized on demand.
=> Protect against early calls to Timers module

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs
Both ProgressDialog and RedBox can trigger crashes when main view has no CoreWindow that is supposed to parent them.
This change fixes avoids the crashes by checking the existence of that said object before doing anything dialog box related.
=> Harden dev dialog boxes for background activation scenarios

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
We move from the OnLoaded mechanism to a better trick: using an intermediary Border as Content for the purpose of "hiding" keyboard events.
Cc: @zholobov
=> Fix ScrollViewer crash when parent view is collapsed

Libraries/Text/Text.windows.js, ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj, ReactWindows/ReactNative.Net46/Shell/MainReactPackage.cs, ReactWindows/ReactNative.Net46/Views/Text/ReactSimpleTextViewManager.cs, ReactWindows/ReactNative.Net46/Views/Text/ReactTextCompoundView.cs, ReactWindows/ReactNative.Shared/UIManager/RootViewHelper.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Shell/MainReactPackage.cs, ReactWindows/ReactNative/Views/Text/ReactSimpleTextShadowNode.cs, ReactWindows/ReactNative/Views/Text/ReactSimpleTextViewManager.cs
Simple text, i.e., text with only a single raw text node as a child (or an array with one raw text child), can be transformed into a TextBlock with a Text property, instead of a RichTextBlock with a Paragraph of Inlines. This change detects in the React Native Text node has a single raw text child/array element, and if so, uses the RCTSimpleText native component.
Fixes #1252
=> Add option to use TextBlock for simple text, take 2

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative.Shared/DevSupport/DisabledDevSupportManager.cs, ReactWindows/ReactNative.Shared/DevSupport/IDevSupportManager.cs, ReactWindows/ReactNative.Shared/Modules/Core/ExceptionsManagerModule.cs, ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative/ReactNative.csproj, ReactWindows/ReactNative/Shell/MainReactPackage.cs, ReactWindows/ReactNative/Views/Modal/ReactModalHostView.cs, ReactWindows/ReactNative/Views/Modal/ReactModalShadowNode.cs, ReactWindows/ReactNative/Views/Modal/ReactModalViewManager.cs, docs/CoreParityStatus.md
My first stab at creating a modal implementation #618
=> Basic implementation of RCTModalHostView

ReactWindows/ReactNative/ReactRootViewExtensions.cs
When clicking on ALT GR, following AcceleratorKeyActivated events are thrown:
e.VirtualKey: Control and e.EventType: KeyDown
e.VirtualKey: Menu and e.EventType: KeyDown
e.VirtualKey: Control and e.EventType: SystemKeyUp
e.VirtualKey: Menu and e.EventType: KeyUp
This triggers the dev menu when inserting some special chars as "@" on non US keyboards
When clicking on Y key, following events are thrown:
e.VirtualKey: Y and e.EventType: KeyDown
e.VirtualKey: F10 and e.EventType: Character
e.VirtualKey: Y and e.EventType: KeyUp
This sometimes triggers the dev menu, as Y triggers an F10 Character
This PR prevents unwanted dev menu triggering
=> Do not open dev menu on ALT GR and Y key press

ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs
Currently, the `LauncherModule` stores the activation URL as a static which never gets cleared (`s_activatedUrl`). This means that if the JavaScript engine is rebooted for some reason, the app will likely handle the activation URL again. For example, if in debug mode a developer reloads the JS, the app's JS will treat this as a protocol activation. This also affects production scenarios in which the app recreates the ReactContext.
Given the current interface of `LauncherModule`, I couldn't find a clean solution to this problem. See the comment in `SetActivatedUrl` for details about the solution.
=> Prevent activation URL from persisting across resets of the ReactContext

docs/RunningOnDeviceWindows.md
Per #1421, rename index.windows.js to index.js in the react-native bundle command line.
=> Fix bundle command

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
A recurring condition that seems to be happening more with recent RN versions is TextInput.selection being pass a "null" object.
I couldn't find/trace this in the JS counterpart, I wonder whether there's some property cleaning done by RN or something similar.
Nevertheless, both the iOS and Android implementations have an "if" to bail out in this case.
=> Harden selection property for null

ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs
This pull request contains fix for Authorization header having double quotes, and will also take care of other different types of Authorization header. 
Modified File count: 1
File Name: NetworkingModule.cs, 
Added logic to add header of any kind without neglecting double quotes  inside switch case block of ApplyHeader method.
@rozele Please review
=> Fix for #2040, #782, #1542

ReactWindows/ReactNative/ReactRootViewExtensions.cs
For Windows 10 VM on Parallels on Mac with touchbar, we need to detect SystemKeyDown in addition to KeyDown events.
Fixes #2045
=> Support Dev Options Menu on Windows 10 VM

ReactWindows/ReactNative/Modules/DeviceInfo/DeviceInfoModule.cs, ReactWindows/ReactNative/UIManager/DisplayMetrics.cs
We need to calculate display metrics before running the JS bundle, in order for things like `StyleSheet.hairlineWidth` and other style-related settings that are initialized from the `Dimensions` module. This change also checks to make sure a CoreWindow exists on the MainView, so we can continue to support background mode.
Fixes #1986, #2020
=> Ensure the initial display metrics are set.

ReactWindows/ReactNative.Shared/DevSupport/DevInternalSettings.cs, ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs, ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
Now RNW remembers what value you were using for the "Start/Stop JS Remote Debugging" flag in the debug menu (shift+f10) across launches of the app. This is useful for debugging JavaScript during app activation scenarios (e.g. receiving a push notification).
Note that this doesn't fully solve the problem. `ReloadJavaScriptInProxyModeAsync` shows a progress dialog when loading the JS but you can't do this during a background activation scenario because there's no UI. The result is the attempt to show the progress dialog throws and RNW fails to boot.
=> Persist JavaScript debugging flag across launches

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs, ReactWindows/ReactNative.Net46/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative.Net46/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs, ReactWindows/ReactNative.Shared/UIManager/LayoutShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs, ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs, ReactWindows/ReactNative.Shared/UIManager/YogaNodePool.cs, ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs, ReactWindows/ReactNative/UIManager/BaseViewManager.cs, ReactWindows/ReactNative/Views/Image/ReactImageManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxManager.cs, ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
Specifically, this forks from facebook/yoga@006f646, and adds some fixes we had previously put in the ReactWindows/yoga@vprev branch.
This also includes some additional fixes to Yoga (e.g., the YogaConstants incorrectly defined `Undefined` as `NaN` rather than a very large number). This also adds `Start` and `End` props for `margin`, `padding`, and `position`.
Also, iOS and Android use the "legacy" stretch behavior option for Yoga, which allows all containers to use the maximum space, as opposed to the minimum space allowed (i.e., similar to an implied `alignSelf: 'stretch'`). This change exposes that API to react-native-windows and ensures each shadow node sets the config value.
Fixes #2012
=> fix(Yoga): Update Yoga version and use legacy stretch behavior

RNWCPP/Desktop.UnitTests/EmptyUIManagerModule.cpp, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.arm.def, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x64.def, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x86.def, RNWCPP/Universal.SampleApp/HostingPane.xaml.cpp, RNWCPP/include/ReactUWP/Views/ViewManagerBase.h
Add additional exports so folly dynamic asDouble/asInt/asBool/asString can be referenced outside
improves what you can do with custom viewmanagers: https://github.com/Microsoft/react-native-windows/issues/2102
minor cleanup:
1. EmptyUIManagerModule is linking fine with current exports, bring back commented out code
1. Tweaked an include in ViewManagerBase.h so include\ReactWindowsCore doesn't need to be on the include list to consume it (just \include and \include\ReactUWP)
=> Folly export fixes, minor cleanups

RNWCPP/.npmignore, RNWCPP/Libraries/Components/DatePicker/DatePickerIOS.uwp.js, RNWCPP/Libraries/Components/DatePickerAndroid/DatePickerAndroid.uwp.js, RNWCPP/Libraries/Components/DatePickerMacOS/DatePickerMacOS.uwp.js, RNWCPP/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.uwp.js, RNWCPP/Libraries/Components/MaskedView/MaskedViewIOS.uwp.js, RNWCPP/Libraries/Components/Navigation/NavigatorIOS.uwp.js, RNWCPP/Libraries/Components/Picker/PickerAndroid.uwp.js, RNWCPP/Libraries/Components/Picker/PickerIOS.uwp.js, RNWCPP/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.uwp.js, RNWCPP/Libraries/Components/ProgressViewIOS/ProgressViewIOS.uwp.js, RNWCPP/Libraries/Components/SafeAreaView/SafeAreaView.uwp.js, RNWCPP/Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.uwp.js, RNWCPP/Libraries/Components/StatusBar/StatusBarIOS.uwp.js, RNWCPP/Libraries/Components/TabBarIOS/TabBarIOS.uwp.js, RNWCPP/Libraries/Components/TabBarIOS/TabBarItemIOS.uwp.js, RNWCPP/Libraries/Components/TextInput/TextInput.uwp.js, RNWCPP/Libraries/Components/TextInput/TextInputState.uwp.js, RNWCPP/Libraries/Components/TimePickerAndroid/TimePickerAndroid.uwp.js, RNWCPP/Libraries/Components/ToastAndroid/ToastAndroid.uwp.js, RNWCPP/Libraries/Components/ToolbarAndroid/ToolbarAndroid.uwp.js, RNWCPP/Libraries/Components/View/PlatformViewPropTypes.uwp.js, RNWCPP/Libraries/Components/ViewPager/ViewPagerAndroid.uwp.js, RNWCPP/Libraries/Components/WebView/WebView.uwp.js, RNWCPP/Libraries/Image/Image.uwp.js, RNWCPP/Universal.SampleApp/index.uwp.js, RNWCPP/package.json, RNWCPP/rn-cli.config.js, RNWCPP/src/Libraries/Components/CalendarView/CalendarView.tsx, RNWCPP/src/Libraries/Components/DatePicker/DatePicker.tsx
Removes the legacy @providesModule comment at the top of many of the modules.  This is no longer needed since RN 0.57.
Also a couple of small fixups from the package rename
=> No need to use @providesModule anymore

RNWCPP/ReactUWP/Utils/ValueUtils.cpp
#2116
- Loading Universal.SampleApp\index.uwp, number of solid color brushes created reduced from 63 to 19.
- Upon unloading and loading the same bundle a second time, verified that weak references fail to resolve, thus the SolidColorBrushes are getting released when they are no longer referenced beyond the cache.
=> Add cache to SolidColorBrushFrom()

RNWCPP/Chakra/ChakraExecutor.h, RNWCPP/Chakra/ChakraValue.h, RNWCPP/Libraries/Components/TextInput/TextInput.uwp.js, RNWCPP/Libraries/Components/WebView/WebView.uwp.js, RNWCPP/Libraries/Image/Image.uwp.js
PropTypes are in the process of being removed, so removing some of them ahead of 58 to make 58 merge easier.
Also stop using noncopyable, as its been deleted in 58
It appears that the only remaining changes would be to update versions of
react-native, react and fbjs in package.json.
Note this doesn't update folly, which did happen in 58 RN.  Although it appears that it runs with the old version, so that may not block things.
=> Changes to prepare for RN58

RNWCPP/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, RNWCPP/Desktop.DLL/packages.config, RNWCPP/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, RNWCPP/Desktop.IntegrationTests/packages.config, RNWCPP/Desktop/React.Windows.Desktop.vcxproj, RNWCPP/Desktop/packages.config, RNWCPP/IntegrationTests/React.Windows.IntegrationTests.vcxproj, RNWCPP/IntegrationTests/packages.config, RNWCPP/ReactCommon/ReactCommon.vcxproj, RNWCPP/ReactWin32SandboxSample/ReactWin32SandboxSample.vcxproj, RNWCPP/ReactWin32SandboxSample/packages.config
I think this dependency can just be removed.  It isn't used in windows, and I dont think will affect our internal builds.  #2169
=> Remove JSCTemp dependency

RNWCPP/ReactUWP/Modules/DevSupportManagerUwp.cpp
* Fixes a lock where trying to download the bundle with httpClient.GetBufferAsync blocks the UI thread, and the UI thread blocks the download from ever completing
* Fixes issue #2210
=> Stop DevSupportManager::DownloadFromAsync from blocking the UI thread

RNWCPP/.ado/evergreen.js, RNWCPP/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, RNWCPP/Desktop.DLL/packages.config, RNWCPP/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, RNWCPP/Desktop/React.Windows.Desktop.vcxproj, RNWCPP/Desktop/packages.config, RNWCPP/ReactCommon/ReactCommon.vcxproj, RNWCPP/ReactCommon/packages.config, RNWCPP/Shared/CMakeLists.txt, RNWCPP/Shared/OInstance.cpp, RNWCPP/Shared/sources.inc, RNWCPP/V8Inspector/V8Inspector.vcxproj
Remove need for V8 nuget for public consumption.
This removes the blocking part of #2153 .
=> Allow V8 to not be required for VS project

RNWCPP/ReactWindowsCore/Modules/UIManagerModule.cpp
We've been running into a crash here, where a view is being asked to update after it was removed from the tree.  
While we're also looking at fixing the js where setNative from something holding an element past their life on screen appear to be the trigger, native can protect itself from crashing.  Android implementation does have a null check in their implementation, looks like ios/Mac doesn't need one due to ObjC nil object behavior handling calls to nil objects as just returning nil
=> add null check in UIManager::updateView

RNWCPP/ReactUWP/Utils/LocalBundleReader.cpp
see: https://github.com/Microsoft/react-native-windows/issues/2232
loading the js bundle needed to be able to wake up the UI thread to continue.  In detachRoot we block the UI thread waiting for the js thread to clear -- but if the js thread is still loading that file it will deadlock.
fix changes this function to resume on the background thread avoiding the hang.
I was able to test back to back calls of attachRoot, detachRoot no longer hang.
BUT if you call them from the same ui batch you will crash when we try to remove a root view of -1 when the root view create wasn't done yet.  As long as these requests queued up separately by the dispatcher you're fine which I tested.  It IS allowed to call detach->attach back to back in the same batch (live reload does this), just not …
=> Fix deadlock when calling detach before attach has finished

RNWCPP/ReactUWP/Base/UwpReactInstance.cpp
This fixes potential crashes when creating the instance fails and something like a native module tries to call into it.
This is possible right now if you start the sample app without the packager running, press 'load' so you end up a the red error screen, then minimize the window.  AppState tries to fire an event which runs into null objects inside of m_instanceWrapper.
=> check isInError before calls to instanceWrapper

RNWCPP/ReactUWP/Views/ViewControl.cpp, RNWCPP/ReactUWP/Views/ViewViewManager.cpp, RNWCPP/ReactUWP/Views/ViewViewManager.h, RNWCPP/include/ReactUWP/Views/ShadowNodeBase.h
2 changes:
1) Hook up more AccessibilityRole values.  These are matching win32 though perhaps 'Header' should map to UIA Header instead of Text
2) add focusIn/Out events which are bubbling focus events matching web
-- this is the more time critical change for one of our projects to be able to detect when focus is in a touchable.  Right now touchable doesn't expose the onFocus/onBlur direct events so you can't detect if you're focused.
=> add more accessiblilityRole support on View.  add focusIn/Out events to View

RNWCPP/ReactUWP/Modules/NetworkingModule.cpp
Adding ability to send multipart requests using the FormData object from JS. fetch/XHRRequests can now accept FormData payloads with either a string or a uri. String FormDataValue will result in a text part of the multi-part payload, while a uri to a local file will include that file's contents in its multipart section of the request. 
This implementation is similar to the [iOS](https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTNetworking.mm)/[Android](https://github.com/facebook/react-native/blob/81fcaa151df4f81e1751719173376bebedb42f36/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java) FormData handling in react-native.
=> Adding multipart FormData functionality to UWP NetworkingModule

RNWCPP/ReactUWP/Views/ViewViewManager.cpp, RNWCPP/ReactUWP/Views/ViewViewManager.h
When I added bubbling focusIn/out that started generating some exceptions from checking code because we started declaring onFocus as both bubbling and direct.
This changes onFocus/onBlur from View to just be bubbling and remove the direct code.  The registration on topFocus/topBlur is in viewmanagerbase in the set of standard event types.
now that focus/blur is bubbling we don't need focusIn/out
=> fix focus event errors being reported.

RNWCPP/.ado/windows-vs-pr.yml, RNWCPP/README.md, RNWCPP/ReactWindows-UWP.sln
This adds a copy of the ReactWindows solution without the Win32 projects so that 3rd party developers can build RNWCPP. 
#2170 and #2154
=> Add UWP only solution

RNWCPP/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp, RNWCPP/Desktop/WebSocket.cpp, RNWCPP/Desktop/WebSocket.h, RNWCPP/WindowsSampleCSharpApp/WindowsSampleCSharpApp.csproj
BaseWebSocket::m_writeRequests gets elements emplaced in the main thread, while dequeuing happens in the background thread. This could lead to race conditions.
This change ensures both reads and writes happen only in the background (IO context) thread without locking.
=> Enqueue outgoing messages in background thread.

RNWCPP/Libraries/Components/TextInput/TextInput.uwp.js, RNWCPP/Libraries/Components/TextInput/TextInputState.uwp.js
Apply react-native 58 changes to TextInput files.
the only changes we NEED are TextInputState to fix yellowbox warnings coming from using UIManager.[viewtype]
win32 will need to apply some similar change to TextInputState.js in Microsoft/react-native
=> merge TextInput changes from 58 to uwp forked files

RNWCPP/CopyHeaders.inc, RNWCPP/Desktop.DLL/react-native-win32.oss.x64.def, RNWCPP/Desktop.DLL/react-native-win32.oss.x86.def, RNWCPP/Desktop.DLL/react-native-win32.x64.def, RNWCPP/Desktop.DLL/react-native-win32.x86.def, RNWCPP/Desktop.DLL/react-native-win32.x86sdx.def, RNWCPP/ReactWin32.nuspec
Since unicode.h was removed from RN58, this exports a replacement.
=> Export UnicodeConversion.h

RNWCPP/.ado/windows-vs-pr.yml, RNWCPP/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
In order to enable or disable unreliable tests without making code changes (and thus, pull requests), we should annotate problematic tests so they can be filtered out by the Azure DevOps build task.
Currently, VSTest doesn't support filtering by custom arbitrary attributes (See https://github.com/Microsoft/vstest/issues/1763), so we use the `Owner` attribute as follows:
```
vstest.host.exe <path\to\Test.dll> /TestCaseFilter:Owner!=Unstable
```
=> Set filtering metadata for RNTesterIntegrationTests::WebSocket

RNWCS/ReactWindows/ChakraBridge/CallSyncHandler.h, RNWCS/ReactWindows/ChakraBridge/ChakraHost.cpp, RNWCS/ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs, RNWCS/ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
All view managers in React Native should be loaded with `UIManager.getViewManagerConfig()`, which internally will attempt to load native view manager constants [here](https://github.com/facebook/react-native/blob/d9a82221a457fe4d4e9dda73bb5680024e704e92/Libraries/ReactNative/UIManager.js#L33-L39) via a sync native method. There is a try/catch around this block because many JS-only modules will result in a native exception.
Because we were not propagating this native exception, it was resulting in an app crash rather than a caught JS exception. This change ensures that native exceptions are propagated from sync native methods in both variants of the JavaScript executor in the C# solution.
Fixes #1883
=> fix(NativeModules): Propagate exceptions in sync native methods

RNWCPP/package.json, RNWCPP/yarn.lock
```
eb5ca7d16 Applying package update to 0.58.6-microsoft.27
7042cdba5 Fix c4244 (#49)
```
=> Update to react-native@0.58.6-microsoft.27

RNWCS/ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs, RNWCS/ReactWindows/ReactNative.Shared/Animated/SubtractionAnimatedNode.cs, RNWCS/ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
iOS and Android implemented 'subtraction' for NativeAnimated in [this](https://github.com/facebook/react-native/commit/4906f8d28cdbaf1b432494b473a4c61c1e193881) commit. This change adds the subtraction node type to `react-native-windows`.
Fixes #2300
=> feat(NativeAnimated): Adds 'subtraction' node type

RNWCPP/local-cli/generator-windows/templates/App.windows.js, RNWCPP/local-cli/generator-windows/templates/app.windows.bundle
App suggests editing "index.windows.js" to get started, but the file name is "app.windows.js"
=> Update CLI template to match file name

RNWCPP/local-cli/runWindows/utils/msbuildtools.js
VS 2019 is not currently supported by the CLI, so we should ignore it if it is installed.
=> Exclude VS 2019 from MSBuild path search

RNWCPP/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp
with 0.58 a 5th arg now exists and this very noisy assert fires on every level of the callstack
quick fix is update the assert, longer term we can make use of the new parameter (I am forgetting now, i think its parameters or something)
=> update ExceptionManagerModule assert for 0.58 compat

RNWCPP/.ado/publish.yml, RNWCPP/.ado/updateVersion.js
Since we're now publishing directly to the public NPM feed, we can remove the office registry code. Also renamed publish.js since all it does now is update the package version and tag the commit.
=> Clean up publish tasks

RNWCPP/README.md, RNWCPP/docs/GettingStarted.md
Separating out Getting started into a sub-doc and updating the landing ReadMe file for RNWCPP with updates upon completion of Milestone 1.  Fixes #2105 
We can do a subsequent wider update to the master readme and consolidate docs between RNWCS and RNWCPP after merging rnwcpp-preview to master.
=> Commiting updates to docs upon end of Milestone 1

README.md
Minor tweaks to landing page readme:
1) Updated blurb about where the C++ implementation lives to point a sub-directory instead of rnwcpp-preview branch.
2) Fixed path for install instructions to include rnwcs directory.
=> minor tweaks to readme

RNWCPP/ReactUWP/Views/TouchEventHandler.cpp
This assert is currently being hit on every touch event. I believe this need to hit only when the pointerId is not std::nullopt.
=> Fixing assert in TouchEventHandler

RNWCPP/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp
We have a project that uses the latest native code with 0.57 based JS at the moment, temporarily updating this assert so we don't crash on exception handling with that project.
Maybe should update some of this assert code to be under ifdef debug since it seems to fire in ship builds too
=> update ExceptionsManagerModule assert to work with 57

RNWCPP/docs/releases.md
Port of #2344 to point to master instead of rnwcpp-preview
=> Fix releases broken link

RNWCPP/Desktop.DLL/react-native-win32.x64.def, RNWCPP/Desktop.DLL/react-native-win32.x86.def, RNWCPP/Desktop/msoFolly.h, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.arm.def, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x64.def, RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x86.def, RNWCPP/Universal.SampleApp/HostingPane.xaml.cpp
1. We use a wrapper msoFolly.h to suppress warnings around including the folly headers.
with the recent folly upgrade we're seeing this warning (which we treat as error) in many projects, add 4324 (structure was padded due to alignment specifier) to the warnings we suppress
2. Need to add an additional export for using operator[]'str' with a const folly::dynamic
=> fixes for new folly consumption

RNWCPP/Desktop.UnitTests/CMakeLists.txt
Missing cmakelist addition to correct upstream uptake of LayoutAnimation changes.
=> add layoutanimationtests to cmake unit tests

RNWCPP/package.json, RNWCPP/yarn.lock
```
9ac211631 Applying package update to 0.58.6-microsoft.31
a9a1962d5 Fixing devmain build break for droid 64 bit platforms (#56)
d95b02e19 Applying package update to 0.58.6-microsoft.30
18ff6d411 Building RN droid for 64 bit plats (#54)
```
=> Update to react-native@0.58.6-microsoft.31

RNWCPP/package.json, RNWCPP/yarn.lock
```
83de24139 Applying package update to 0.58.6-microsoft.34
ea4aa0454 Cross platform/engine/storage abstraction for original and prepared scripts (#55)
b981b8310 Applying package update to 0.58.6-microsoft.33
2ff9a7936 Bump version to match published version
1ddb201d9 More publish fixes
3a2f8cfac Update publish logic
e2b196ee1 More publish updates
db2b3c0e6 Dont republish on package.json changes
f0fba6f19 Prepare publish script for work in fb59merge
```
=> Update to react-native@0.58.6-microsoft.34

RNWCPP/ChakraCoreShim/ChakraCoreShim.vcxproj, RNWCS/local-cli/generator-wpf/templates/proj/MyApp.csproj
=> Update version of ChakraCore in sample

RNWCS/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js, RNWCS/Libraries/Components/Button.windows.js, RNWCS/Libraries/Components/FocusableWindows/FocusableWindows.windows.js, RNWCS/Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js, RNWCS/Libraries/Components/Picker/Picker.windows.js, RNWCS/Libraries/Components/Picker/PickerWindows.js, RNWCS/Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows.js, RNWCS/Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows.js, RNWCS/Libraries/Components/ScrollView/ScrollView.windows.js, RNWCS/Libraries/Components/SplitViewWindows/SplitViewWindows.windows.js, RNWCS/Libraries/Components/StatusBar/StatusBar.windows.js, RNWCS/Libraries/Components/TextInput/TextInput.windows.js, RNWCS/Libraries/Components/View/PlatformViewPropTypes.windows.js, RNWCS/Libraries/Experimental/SwipeableRow/SwipeableRow.windows.js, RNWCS/Libraries/Image/Image.windows.js, RNWCS/Libraries/Text/Text.windows.js, RNWCS/Libraries/Text/TextPropTypes.windows.js, RNWCS/package.json
A few deprecations and refactorings caused issues with the upgrade to 0.58. This was all the changes to JS necessary to get RNTester working.
=> chore(NPM): Updates JS modules to match RN 0.58 

vnext/package.json, vnext/yarn.lock
```
47dd25684 Applying package update to 0.58.6-microsoft.36
52bb7ce8d Fixes for devmain (#58)
e4e31a0ff Applying package update to 0.58.6-microsoft.35
d8ef2252d Add fabric to published branches
```
=> Update to react-native@0.58.6-microsoft.36

vnext/package.json, vnext/yarn.lock
```
ddd8b89b5 Applying package update to 0.58.6-microsoft.37
5cd586234 Add RCTSRWebSocket.h to the Copy Headers phase. (#61)
```
=> Update to react-native@0.58.6-microsoft.37

vnext/package.json, vnext/yarn.lock
```
4c79d7cfd Applying package update to 0.58.6-microsoft.38
3b7bdd3ca Internal build updates
```
=> Update to react-native@0.58.6-microsoft.38

vnext/package.json, vnext/yarn.lock
```
f6c76d9f8 Applying package update to 0.58.6-microsoft.39
caa76f6e0 Fix incorrect warning supression
```
=> Update to react-native@0.58.6-microsoft.39

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Modules/DevSupportManagerUwp.cpp, vnext/ReactUWP/Views/ReactControl.cpp, vnext/Shared/OInstance.cpp
These are changes to address:
https://github.com/microsoft/react-native-windows/issues/2431
where if you had a typo in your js, we didn't show an error and a second reload would hang the app.
We will now download js before starting web debugging (web debugging asks the debugger to download the js too, but when there are errors it doesn't send any response on the socket).  This more closely matches what ios/Android does (we don't have progress UI yet like they do).
Our download js code wasn't sending back the error text if there was an error, just an exception would fire.  Changed our download code to be able to report the error string back so you can see what line/character triggered the error . (your cmd prompt packager probably also told you).
In our error displaying logic, add text …
=> Improve js download error handling

vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Desktop/LegacyWebSocket.cpp, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/msoFolly.h, vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj, vnext/PropertySheets/Warnings.props, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactWindowsCore/UnicodeConversion.cpp, vnext/Universal.IntegrationTests/RNTesterIntegrationTests.cpp, vnext/Universal.SampleApp/MainPage.xaml.cpp, vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj
add permissive- to our options in warnings.props so stricter C++ conformance is enabled by default.  Previously we only had it enabled in the ReactUWP folder.
With a few related build config changes:
* /cx projects require 2phase turned off, our sample app and test project have cx enabled right now
* turned off for the Desktop folder, @JunielKatarn to followup on fixing the boost socket integration
The fixes needed were mostly in test code.
I brought in one fix from my VS2019 pull request that is still in progress.
Also this adds a warning disable in msoFolly.h requested by office engineering working on compiler upgrades and hitting this warning in folly usage.
=> Enabling further C++ strict conformance (/permissive-)

vnext/package.json, vnext/yarn.lock
```
01e2686e7 Applying package update to 0.58.6-microsoft.41
e64070a37 Rename misnamed file
6816c3c95 Applying package update to 0.58.6-microsoft.40
a1a6e4862 Added canBecomeKeyView override to RCTScrollView (#60)
```
=> Update to react-native@0.58.6-microsoft.41

vnext/package.json, vnext/yarn.lock
```
b74fd447c Applying package update to 0.58.6-microsoft.42
23df4d499 Internal build logic update
```
=> Update to react-native@0.58.6-microsoft.42

vnext/rn-cli.config.js
A better fix for #2448 , which will just tell the user what they need to do when they hit that case.  Instead of hiding it in a troubleshooting doc.
=> Check build has happened before running bundler

vnext/package.json, vnext/yarn.lock
```
4e841abc5 Applying package update to 0.58.6-microsoft.44
98d09810d Merge branch 'publish-temp-1557780649132'
1e6ff2899 Separate V8 code from the core JSI library (#64)
6b436b7e4 Applying package update to 0.58.6-microsoft.43
b12a2109c Deleting empty files for now, as they confuse our sync to internal (#63)
```
=> Update to react-native@0.58.6-microsoft.44

vnext/package.json, vnext/yarn.lock
```
7b572245f Applying package update to 0.58.6-microsoft.45
0de1126cd Fix Office droid build (#65)
```
=> Update to react-native@0.58.6-microsoft.45

vnext/ReactWindowsCore/DevSettings.h
DevSettings.h shouldn't require that people include <vector> first.
=> Header should include all its reqs

vnext/Chakra/ChakraCoreDebugger.h, vnext/Chakra/ChakraExecutor.cpp, vnext/Chakra/ChakraExecutor.h, vnext/Chakra/ChakraInstanceArgs.h, vnext/ReactWindowsCore/DevSettings.h, vnext/Shared/OInstance.cpp
When direct debugging is enabled and using the ChakraCore JavaScript engine, allow the debugger to show console output. This is done by patching global.console with a console object which calls the original console object as well as the ChakraCore debugger console object.
=> Chakracore debugger console redirection support

vnext/ReactWindows-CopyToStaging.bat
PRs 2461 & 2428 added jsi files to be copied in CopyHeaders.inc
2428 added inc/jsi to be part of the .nuspec file but didn't update the staging script that goes with the nuspec.
This updates the staging script and includes all the files that CopyHeaders.inc has for jsi.  Our internal nuget packages has been broken since 2428.
=> fix nuget packaging

vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactCommon/nov8.cpp
We don't want to fork the .def file between GitHub and the Office build system, so just add a dummy implementation for makeV8Runtime, until we figure out how to properly integrate V8 in the MsBuild build system.
=> Add v8runtime export to the def file

vnext/ReactWin32.nuspec, vnext/ReactWindows.nuspec
IUIManger.h is required for usages of the platform with custom UIManger implementations.
=> Add IUIManager.h to nuget

vnext/package.json, vnext/yarn.lock
```
f4d8fb6da Applying package update to 0.58.6-microsoft.46
8a1b08448 Workaround crash during layout on macOS when a large number of flex (#69)
```
=> Update to react-native@0.58.6-microsoft.46

vnext/package.json, vnext/yarn.lock
```
148ebdeb3 Applying package update to 0.58.6-microsoft.47
dd28949a9 RCTWebViewManager.m was missing from the macOS target (#70)
3e493bfed Merge branch 'publish-temp-1557956704598'
14729eddc Removing Chakra specific hack from JSIExecutor (#66)
```
=> Update to react-native@0.58.6-microsoft.47

current/README.md, vnext/README.md
The image used in both readmes is in a parent folder that is not being published. Switched the path to the full github url. 
The other relative links in the readmes are also broken. I believe this might also fix those.
=> Readme path updates

vnext/ReactUWP/CMakeLists.txt, vnext/Universal.UnitTests/CMakeLists.txt, vnext/Universal.UnitTests/React.Windows.Universal.UnitTests.vcxproj, vnext/include/CppWinRTIncludes.h
1) fix the universal.unittest build which is not enabled by default.  There is an assumption of PCH coming from shared which wasn't true for this project with the new scrollview code (controls.primitives.h being included)
2) fix the winrt cmake builds to also use the shared pch.  We'll probably turn off the cmake build soon but right now this blocks auto integrate from github to internal.
3) use forward slash in includes, OACR will flag that
=> Fix Unittest build, internal build fixes

vnext/package.json, vnext/yarn.lock
```
d0e507f91 Applying package update to 0.58.6-microsoft.48
ae2677e22 This change updates react dependencies (#67)
```
=> Update to react-native@0.58.6-microsoft.48

vnext/ReactUWP/Views/FlyoutViewManager.cpp
The XAML Flyout has a default MaxWidth/MaxHeight of 456/758. This size is too restrictive for RNW. This change sets the max width/height of the flyout to an arbitrarily large size. This will allow RNW consumers to set their own limits.
=> Fixing sizing issues with Flyout (WI: 3362439)

vnext/Shared/OInstance.cpp
set native module info when using web debugging.
alternatively we should suppress creating the jsiRuntimeHolder when web debugging (in uwpreactinstance)
=> fix for running in web debugging mode

.ado/publish.yml, .ado/templates/npm-install-and-build.yml, .ado/templates/prep-and-pack-nuget.yml, .ado/templates/publish-build-artifacts-for-nuget.yml, .ado/templates/stop-packagers.yml, .ado/templates/vs-build.yml, .ado/updateVersion.js, .ado/windows-vs-pr.yml
We've been hitting a bunch of breaks lately where the nuget cannot be build, but we dont find out until the change is checked in and the publish build fails.
This will add validation to PRs to verify that the nuget can be packed.  This also cleans up a bunch of the duplication within the build tasks by moving various logic to shared build templates.
=> Verify nuget can be packed during PR

vnext/ReactUWP/Polyester/IconViewManager.cpp, vnext/ReactUWP/Views/DatePickerViewManager.cpp, vnext/ReactUWP/Views/FlyoutViewManager.cpp, vnext/ReactUWP/Views/PopupViewManager.cpp, vnext/ReactUWP/Views/TextInputViewManager.cpp, vnext/ReactUWP/Views/TextViewManager.cpp, vnext/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp, vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
This fixes the ExceptionManagerModule that had a bunch of INT64 checks to allow any number.  With JSI nothing will be an int, everything numeric is a double.
Fixes all the remaining viewmanagers with isInt references, only minor one left checks both isint and isdouble.
Across the repo the only other isInt is in sandbox that someone in win32 should update and test.
getConstantsForViewManager in non-jsi mode is called with a string that is an array with a string in it, e.g. "['Text']".  In JSI Mode it comes in as an array, added code to handle both cases.
=> JSI compat fixes

vnext/Chakra/ChakraExecutor.cpp, vnext/Chakra/ChakraJsiRuntime.cpp, vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/include/ReactUWP/IReactInstance.h
This change makes it possible to debug script when we're using inproc Chakra.  Once this flag is on, you can attach or start debugging with the full VisualStudio.  (haven't tried to see how VSCode would work yet)
I've had this locally for awhile, useful when web debugger behavior is different from inproc.
(this arg is forwarded from devSettings to chakra instance inside existing code for win32 in oinstance.cpp)
=> add DirectDebugging option for uwp Chakra

vnext/ReactUWP/Modules/NetworkingModule.cpp, vnext/ReactUWP/Views/ImageViewManager.cpp
fixes #2466 
Changing this to TryAppendWithoutValidation seems like the most developer friendly fix for this issue.
=> Fix to allow authorization header to be added.

vnext/package.json, vnext/yarn.lock
```
769569d42 Applying package update to 0.58.6-microsoft.49
4535e574e Update publish logic
c195fcacd Merge branch 'publish-temp-1558101878534'
7cce20ef0 Temp fix for comments crash (#68)
```
=> Update to react-native@0.58.6-microsoft.49

vnext/package.json, vnext/yarn.lock
```
c732d4818 Applying package update to 0.58.6-microsoft.51
d8ce49375 Fix a crash that can occur in UIGraphicsEndImageContext if UIGraphics… (#71)
03149424e Applying package update to 0.58.6-microsoft.50
3a48fce10 Verify android nuget during pr (#72)
```
=> Update to react-native@0.58.6-microsoft.51

.ado/templates/prep-and-pack-nuget.yml, vnext/.npmignore, vnext/ReactUwp.nuspec, vnext/ReactWindows-CopyToStaging.bat, vnext/ReactWindows-CopyToStaging2.bat, vnext/ReactWindows-TestNuspec.bat, vnext/ReactWindows-UWP.sln, vnext/ReactWindows.sln
This will allow us to rev the UWP version independently of the win32 version.
Once UWP is using this nuget, we'll remove the uwp bits from the win32 nuget.
=> Create a separate uwp nuget

vnext/ReactUWP/Views/FlyoutViewManager.cpp
Currently, setting IsLightDismissalEnabled to false in the Flyout doesn't block light dismiss when the App loses focus. 
This behavior is due to the XAML implementation of the light dismiss logic in the Flyout/Popup code. The loss of focus by the Flyout bypasses the code path that would normally raise the 'Closing' event where we would have had the chance to 'cancel' the dismissal. 
Keith Melmon:
"When the window is being deactivated, we iterate through all open Popups and dismiss any Popup that is light dismiss enabled.  This is different from the light dismiss logic that runs when you click inside the window, which will only attempt to close the top-most open Popup – this code path goes through the extra step of raising the Closing event."  
Luckily though, Keith also provided a …
=> Flyout dismissal

vnext/package.json, vnext/yarn.lock
```
46afff897 Applying package update to 0.58.6-microsoft.54
e64310bec Remove accidental debug code (#75)
b6da98af4 Applying package update to 0.58.6-microsoft.53
e0e026d24 Include more files in droid nuget (#74)
a7418337e Applying package update to 0.58.6-microsoft.52
a8d2cd712 Include built binaries in droid nuget (#73)
```
=> Update to react-native@0.58.6-microsoft.54

vnext/ReactUWP/Modules/NativeUIManager.cpp, vnext/ReactUWP/Views/ViewManagerBase.cpp
This is fixing a regression from the perf changes in https://github.com/microsoft/react-native-windows/commit/60aebbe985c7f29d23bf2eaed249535087cfcd3c  (where we don't call SetLayoutProps on every element in every update anymore).
With self layout elements, we clear the width/height when measuring.  In incremental update items are usually still measured but if the values are the same as before, SetLayoutProps isn't called now.  This fix puts back whatever width/height was there before the clear to maintain previous layout.
Alternatively we could mark self measure nodes as always dirty in self measure, in the case where things DO update we are doing more work now, but in the incremental case this is probably preferred (and we don't want to generate extra onLayout events)
Also, updated our …
=> Self layout elements not always visible after an update

vnext/package.json, vnext/yarn.lock
```
6c7522deb Applying package update to 0.58.6-microsoft.55
0804147ad Changed the showsVerticalScrollIndicator and showsHorizontalScrollIndicator default values on macOS to match iOS and Android. (#77)
```
=> Update to react-native@0.58.6-microsoft.55

vnext/Chakra/ChakraJsiRuntime.cpp, vnext/Chakra/ChakraJsiRuntime.h, vnext/Chakra/ChakraJsiRuntime_core.cpp, vnext/Chakra/ChakraJsiRuntime_edgemode.cpp
A quick and dirty refactoring/code-movement to avoid the class hierarchy in ChakraJsiRuntime implementations. This is to achieve the following,
1. Mark ChakraJsiRuntime as final so that compiler can de-virtualize many calls when possible.
2. In future, many extensions to the runtime implementation can be made gracefully using decorators.
=> ChakraJsiRuntime debugger refactoring

vnext/local-cli/runWindows/utils/msbuildtools.js
VS 2019 changed the msbuild location. Updating path in msbuildtools.js
=> Update msbuildtools.js with VS 2019 path

vnext/package.json, vnext/yarn.lock
```
5285cbf21 Applying package update to 0.58.6-microsoft.58
02ce26f29 Adding back the Accessibility Actions that were mistakenly remove in … (#81)
5fe9c4f8d Applying package update to 0.58.6-microsoft.57
5315faf9a Using optimized V8 bins (#78)
```
=> Update to react-native@0.58.6-microsoft.58

vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj
This allows pdb rewrites to other paths without having to completely rebuild the pdb.  (Internal build system does this)
=> PDBs should be created with -minpdbpathlen:256

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj.filters, vnext/ReactUWP/Views/Impl/ScrollViewUWPImplementation.cpp, vnext/ReactUWP/Views/Impl/ScrollViewUWPImplementation.h, vnext/ReactUWP/Views/Impl/SnapPointManagingContentControl.cpp, vnext/ReactUWP/Views/Impl/SnapPointManagingContentControl.h, vnext/ReactUWP/Views/ScrollContentViewManager.cpp, vnext/ReactUWP/Views/ScrollContentViewManager.h, vnext/ReactUWP/Views/ScrollViewManager.cpp
2 sets of changes:
1. Add a ScrollContentView component type.  In the fb59merge branch of react-native I've already removed the 'uwp' condition we had in there which would create a View instead of a ScrollContentView as other platforms do -- removing one of the reasons 'uwp' needs the microsoft/react-native fork.  It is maybe possible to move some of ScrollView's code into here but I did not to keep it simple -- RN on iOS and Android have very little in their scrollcontentview to validate things or handle special platform differences for horiz/vert.
2. In stepping through the various ScrollView code I found some bugs and simplifications to make:
* There were 2 memory leaks from use of operator new without releasing, fixed one place to use a smartpointer and hide the ctor, the other one is …
=> ScrollContentView and ScrollView cleanup

vnext/ReactWindowsCore/DevServerHelper.h
We have been adding this to get source maps working with a project we made from the c# template (well started with the c# template then replaced the app project with c++/winrt).
=> enable inline source maps

vnext/ReactUWP/Views/ReactControl.cpp
(fix race condition with AttachRoot + DetachRoot)
Currently AttachRoot can be called from a background thread (in theory) and it queues up the work that needs to be done on a ui thread.  This can cause problems when used with DetachRoot, which does not queue work on the ui thread - it just runs code immediately.  If detach is called before Attach's deferred work runs, we will crash detaching (trying to find a rootview of -1).   OneNote team has hit this internally where they use a different UI thread dispatching layer whose timing isn't the same as standard (combines things together aggressively), where it is hard to workaround the timing crash.
Looking back in the history we did this a very long time ago when live reload would be invoked from a background thread.  Since then the live …
=> require AttachRoot to be called from UI thread

README.md, vnext/README.md, vnext/docs/GettingStarted.md
Committing minor changes to master readme and vnext Getting started pages for updates related to 
- RS2 version support (#2366)
- troubleshooting updates (related to #2515)
- pointer to Parity status doc for vnext (#2233 )
=> Minor readme updates

vnext/package.json, vnext/yarn.lock
```
197c4fca0 Applying package update to 0.58.6-microsoft.59
25ab1a468 param requires double quotes instead of single (#82)
```
=> Update to react-native@0.58.6-microsoft.59

.ado/evergreen.yml, .ado/publish.yml, .ado/windows-vs-pr.yml, vnext/package.json, vnext/tslint.json, vnext/yarn.lock
=> Update typescript version to 3.5.1

current/local-cli/rnpm/windows/index.js, current/local-cli/rnpm/windows/package.json, current/local-cli/rnpm/windows/src/common.js, current/local-cli/rnpm/windows/src/windows.js, vnext/local-cli/generate-windows.js, vnext/local-cli/generator-windows/index.js
The CLI is currently attempting to install pre-release versions of react-native-windows, and because "vnext" > "rc" in terms of semver, it's always picking up the vnext version.
This change assumes that all current versions will be tagged with `current-<major>.<minor>`, and if no version with such a tag exists for the corresponding react-native version, then we error out.
This installer plugin is becoming a bit overcomplicated. We should consider a rewrite within the next few months.
=> fix(CLI): Ensure CLI downloads current version

.ado/windows-vs-pr.yml
=> move UWP PRs to hosted machines

.ado/windows-vs-pr.yml, vnext/NuGet.NoOffice.Config, vnext/ReactWindows-UWP.sln
=> Dont require office feed for UWP CI loop

vnext/ReactUWP/Views/FlyoutViewManager.cpp
The generic XAML Flyout has a default padding of 
<Thickness x:Key="FlyoutContentThemePadding">12,11,12,12</Thickness>.
We need to override this for RNW. RNW consumers can set their own padding on any embedded content if they need to.
=> Removing default padding on FlyoutPresenter

vnext/package.json, vnext/yarn.lock
```
e89924237 Applying package update to 0.58.6-microsoft.60
2b384a865 Pick up setUpGlobals.js change from https://github.com/facebook/react-native/commit/bccc92dfdd2d85933f2a9cb5c8d1773affb7acba#diff-3d750d038ea035cc40dd893c3a39e315 (#83)
```
=> Update to react-native@0.58.6-microsoft.60

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Modules/NetworkingModule.cpp
using FormData to send files currently asserts that .get() is called and blocking the UI thread.
Move networkingModule to run as a background thread native module -- the actual network request was async before but the prep code that processed the folly dynamic data was UI thread
tested existing network send requests that don't use formdata and our app that is using it, both working fine.
=> fixes to FormData network support

vnext/ReactUWP/Views/FlyoutViewManager.cpp
When the flyout is in Light-dismiss disabled mode, the FlyoutPresenter element remains on the screen after the Flyout is 'closed'. The element disappears after any subsequent user action (it's in light-dismiss mode), but it's very ugly. 
The problem is that in certain scenarios (including this one), the view containing the flyout is dropped before the 'IsOpen' property of the Flyout is updated. This blocks the XAML Flyout from ever getting a chance to clean itself up. 
My fix overrides the onDropViewInstance for the FlyoutShadowNode and calls Hide() on the internal flyout object. 
(WI: 3391070)
=> Cleaning up XAML Flyout when shadow node view is dropped.

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/include/ReactUWP/IReactInstance.h
Allow apps to easily toggle jit and set a debug host. Debug host setting makes remote device (xbox) debugging easier, min bar for #2403
=> Add enableJit and debug host to ReactInstanceSettings

vnext/Desktop.UnitTests/UnicodeConversionTest.cpp, vnext/ReactWindowsCore/unicode.cpp
The functions under facebook::react::unicode all throw when they encounter invalid Unicode characters. This PR changes them so that they replace the invalid character(s) with U+FFFD.
=> Do not let functions under facebook::react::unicode throw upon invalid Unicode characters.

.ado/updateVersion.js, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters, vnext/Desktop.DLL/Version.rc, vnext/package.json, vnext/yarn.lock
=> Add version information to react-native-win32.dll

.ado/bumpFileVersions.js, .ado/publish.yml, .ado/updateVersion.js, .ado/versionUtils.js
Currently the dll will get built with the previous build number, since the slice builds dont have the changes done by the npm publish slice.
=> Ensure dll gets updated version before build

vnext/include/ReactUWP/IReactInstance.h
Include via "" instead of <>, so include/reactuwp doesn't have to be on the include list
(found upgrading nuget in devmain)
=> Fix new include, restoring expected paths for nuget consumption

vnext/package.json, vnext/yarn.lock
```
cb636bb61 Applying package update to 0.58.6-microsoft.63
7153afe91 Bump package version
823530693 Rojain/droidpublish (#86)
862667fdd Applying package update to 0.58.6-microsoft.61
1b28f7e8b Rojain/jsc (#84)
```
=> Update to react-native@0.58.6-microsoft.63

vnext/ReactUWP/CMakeLists.txt, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj.filters, vnext/ReactUWP/Utils/AccessibilityUtils.cpp, vnext/ReactUWP/Views/FrameworkElementViewManager.cpp, vnext/include/ReactUWP/Utils/AccessibilityUtils.h, vnext/include/ReactUWP/Views/FrameworkElementViewManager.h, vnext/src/RNTester/AccessibilityExample.tsx
* Added mapping of accessibilityLiveRegion property to AutomationLiveSetting
* Added announce when accessibilityLabel or accessibilityLiveRegion changes
* Issue #2124
=> Implemented accessibilityLiveRegion

vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
This fixes a few issues we noticed getting People card to production where there was duplicated info in the tree, and help text not in the right place.  Fixes 3 things:
1. When transferring, clear the old properties.  In the case of View converting itself to a Control, the 'oldView' continues to exist but has been wrapped by a contentcontrol.  leaving the accessibilityname, etc meant it was set on 2 elements in the tree
2. HelpText not getting transferred
3. make the old view not accessible after transfer.  (#1 is not really necessary with this change)
=> accessibility fixes for <View>

.ado/windows-vs-pr.yml, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj, vnext/IntegrationTests/TestInstance.h, vnext/Scripts/preInstall.js, vnext/Universal.IntegrationTests/React.Windows.Universal.IntegrationTests.vcxproj, vnext/Universal.IntegrationTests/UniversalTestRunner.cpp, vnext/yarn.lock
This adds an extra slice to the CI loop that validates a build using the standard react-native package (**facebook/react-native**) instead of the **microsoft/react-native** version.
I bumped the version of folly that we download in this case to include a couple of PRs I send them for folly to work on windows without having to fork it.
As of this PR i should be possible to run react-native-windows without using the **microsoft/react-native** fork.  However, doing so will likely result in a loss of functionality, as we added some functionality such as mouse events directly to view in **microsoft/react-native**.  Until that functionality is in **facebook/react-native**, using the unforked version may stop that functionality from working.
In addition currently the jsi bridge only works when …
=> Validate build against non forked RN

vnext/ReactUWP/Utils/LocalBundleReader.cpp
Avoid round trip from utf8 -> utf16 -> utf8
Using the ReadTextAsync function will internally convert a utf8 file to utf16, but we need a utf8 string to match the interface.
Using file buffers and streams avoids the overhead of the character conversions. Just read the utf8 file into a utf8 buffer.
On Xbox this saves about 60ms of CPU time.
=> LocalBundleReader.cpp perf improvement.

vnext/package.json, vnext/yarn.lock
```
506d07191 Applying package update to 0.59.0-microsoft.2
77f2be40a Adding logging support for droid and logging failure message (#87)
```
=> Update to react-native@0.59.0-microsoft.2

.ado/evergreen.js, vnext/package.json, vnext/yarn.lock
```
f88b82e24 Applying package update to 0.59.0-microsoft.4
881a64175 Merge branch 'publish-temp-1560803506372'
eb1617de0 Remove references to RCTTabBar from CMake definitions
fbd42ab84 Applying package update to 0.59.0-microsoft.3
b86c177c7 Update cmake logic for latest yoga files.
```
=> Update to react-native@0.59.0-microsoft.4

vnext/ReactUWP/Views/FlyoutViewManager.cpp
We recently added support to Flyouts for horizontal and vertical offsets from the target element. 
However, the code relied on API's that were only introduced in RS5 (FlyoutShowOptions, and FlyoutBase::ShowAt with options). 
This change conditions the support for offsets on the existence of the FlyoutShowOptions type.
(WI: 3432947)
=> Conditioning support for Flyout offsets on RS5+

vnext/package.json, vnext/yarn.lock
```
e095e9c52 Applying package update to 0.59.0-microsoft.5
4a211cc13 Check nativeCallSyncHook on both dev and ship (#92)
```
=> Update to react-native@0.59.0-microsoft.5

vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/Directory.Build.targets, vnext/Scripts/OpenSSL.nuspec, vnext/Scripts/OpenSSL.targets
Published package [ReactWindows.OpenSSL.StdCall.Static](https://www.nuget.org/packages/ReactWindows.OpenSSL.StdCall.Static/1.0.2-p.1), compatible with ReactWindows's compiler flags.
This change updates the dependency to the new package that can be easily maintained and packaged using the NUSPEC and TARGETS scripts included in this PR.
=> Update OpenSSL NuGet dependency.

vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/ViewManagerBase.cpp
Don't set layout props if they haven't changed. (Setting them calls InvalidateArrange)
Also don't call into JS if the layout props haven't changed.
Move constructing the Image requests to worker thread.
=> Reduce onLayoutCalls (native to JS). Move Image download setup to worker 

vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/Image/ReactImageBrush.cpp, vnext/ReactUWP/Views/Image/ReactImageBrush.h, vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj, vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj.filters, vnext/Universal.SampleApp/image.uwp.js
- Added a sample that sets an Image's resizeMode from the selected Picker value
- Fixed an issue where images weren't centered after switching back from 'repeat'
- Fixed an issue where the image wasn't updating when switching the source.
=> Added image sample and fixed a couple bugs

vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config
Version 0.0.0.36 is built with the latest compiler toolset `14.16.x`.
This prevents linker errors with the equivalent Visual Studio release.
=> Update ChakraCore Debugger to 0.0.0.36.

vnext/ReactUWP/Views/Image/ReactImage.cpp
- Remove `m_brush->Source(surface);` from `ReactImage::Source`
- Capture `surface` in a lambda passed to `LoadCompleted` in order to keep it from being destructed until being assigned to the ReactImageBrush
As it stands, switching the source of an Image between large images causes noticeable flashes while the image loads (gif at 2x slowdown to make it more obvious):
This is occurring because of the time it takes to load and decode these images. If the CompositionSurfaceBrush's surface is set to a LoadedImageSurface while it's still decoding, the surface is cleared. This change makes it so that the surface isn't set until the image is already decoded, so switching is smooth:
I'm inexperienced with both UWP and modern C++, so I'm very open to suggestions on a better way to do this.
=> Delay setting ReactImageBrush source until image has actually loaded

.ado/bumpFileVersions.js, .ado/publish.yml, .ado/templates/prep-and-pack-nuget.yml, .ado/templates/vs-build.yml, .ado/updateVersion.js, .ado/windows-vs-pr.yml, vnext/ReactUwp.nuspec, vnext/ReactWin32.nuspec, vnext/package.json
Changes how some version numbers get passed around during publish, and includes the commitId and repo information inside the nuget.
=> Add commit Id to nuget packages

vnext/ReactUWP/Views/ViewViewManager.cpp
I found this with windbg and !idallocs provided by the UIExtensions.
Internal to Microsoft you should be able to open windbg, attach to a running React Native Windows App and use the command !idallocs, if it does not get the ui extensions automatically for you, then you probably need to update your debuggers.
Before this fix you could see the number of Windows_UI_Xaml!CPanel objects increasing as you visit more pages. 
Using the !xamlTree debugger extensions you can see that some of the panels have no children, and their parent is a border. This made the leak pretty easy to pinpoint.
After this fix I am able to Go back and forth between pages (starting and ending on the same page), and see that the number of Windows_UI_Xaml!CPanel objects in the heap remains constant.
=> Fix Memory Leak in ViewViewManager

vnext/ReactUWP/Views/Image/ImageViewManager.cpp, vnext/ReactUWP/Views/Image/ImageViewManager.h, vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/Image/ReactImage.h
This addresses two separate (but similar) memory leaks.
1. Reference Cycle Between CLoadedImageSurface and the LoadedEvent Handler.
This is addressed by using an auto-revoker.
Before this change you could observe the number of CLoadedImage objects increasing on the heap.
With !find you could see that the Handler is keeping the Surface.
2. ReferenceCycle between ImageViewManager and ReactImage caused by the OnLoadEnd event.
This can be solved by un-registering the event handler from the ShadowNode.
You can see the number of ReactImages on the heap continuing to grow.
Looking at what references the Image you can see it is the handler.
After these changes you can see the number of ReactImage objects and CLoadedImageSurface objects remains constant while navigating between pages (start and …
=> Fix memory leaks in ReactImage

vnext/package.json, vnext/yarn.lock
```
536eed3ab Applying package update to 0.59.0-microsoft.6
53753d082 Nanava/configurejs (#93)
```
=> Update to react-native@0.59.0-microsoft.6

vnext/package.json, vnext/yarn.lock
```
fb8100d0a Applying package update to 0.59.0-microsoft.7
ceb544d1e Updating RNTester bundle for RN59 (#95)
```
=> Update to react-native@0.59.0-microsoft.7

vnext/ReactUWP/Views/TextInputViewManager.cpp
We need to ensure that the TextInput blur command, which works by focusing on the current window Frame, does not execute if the TextBox does not currently have focus.
We were doing this in 'current', but we lost that check in the C#->CPP transition in 'vnext'.
See 
https://github.com/microsoft/react-native-windows/pull/1529
Without this check, we mess up native XAML's focus management. In the specific scenario that triggered this investigation, the extra focus change was moving the focus out of the flyout containing the TextInput that just lost focus, which then triggered XAML to dismiss the flyout even though the user had just clicked on the flyout.
=> TextInput: Don't blur if not focused (WI: 3249010)

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Modules/AppThemeModuleUwp.cpp, vnext/ReactUWP/Modules/AppThemeModuleUwp.h, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj.filters, vnext/ReactWindowsCore/Modules/AppThemeModule.cpp, vnext/ReactWindowsCore/Modules/AppThemeModule.h, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj.filters, vnext/Universal.SampleApp/App.xaml, vnext/src/Libraries/Modules/AppTheme/AppTheme.tsx, vnext/src/Libraries/Modules/AppTheme/AppTheme.uwp.ts, vnext/src/index.ts, vnext/src/index.uwp.ts
This module exposes the app's current theme (dark/light) as a property and allows the user to subscribe to theme change events. 
Sample usage:
`import { AppTheme } from 'react-native-windows'`
```
state = {
currentTheme: AppTheme.currentTheme
}
componentDidMount() {
AppTheme.addListener('appThemeChanged', this.onAppThemeChanged);
}
componentWillUnmount() {
AppTheme.removeListener('appThemeChanged', this.onAppThemeChanged);
}
onAppThemeChanged = (event) => {
const currentTheme = AppTheme.currentTheme;
this.setState({currentTheme});
};
render() {
return (
<Button title='click me' color={this.state.currentTheme === 'dark' ? 'grey' : 'orange'}></Button>
);
}
```
=> Add AppTheme module

vnext/ReactUWP/Modules/LinkingManagerModule.cpp
1. canOpenurl should succeed with false when you can't, instead of erroring (which was actually generating a js error)
2. in openUrl, call the error callback properly, error callbacks that are promises must contain code and message or the js side throws exceptions on expected data in the error
(I couldn't actually get openUrl to fail without adding additional local changes for launcher options, so maybe the error path can't actually be hit)
=> Linking module fixes

vnext/src/Libraries/Modules/AppTheme/AppTheme.uwp.ts
- Added isAvailable property to AppTheme
- Conditionally export MissingNativeAppThemeShim as AppTheme if RTCAppTheme module is not available
=> Add MissingNativeAppThemeShim

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Base/UwpReactInstance.h, vnext/ReactUWP/Views/Image/ImageViewManager.cpp, vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/Image/ReactImage.h, vnext/ReactWindowsCore/DevSettings.h, vnext/Shared/OInstance.cpp, vnext/include/ReactUWP/IReactInstance.h
Currently, RNW is configured to always load bundles using the "ms-appx:///Bundle/" URI and root path. There are some scenarios where this hardcoded value does not work; for example, when the bundle resides in an optional package, the URI needs to include the PFN.
This PR adds an option for developers to specify their own root path for bundle loading.
- DevSettings and ReactInstanceSettings now contain new fields for specifying the use of a custom path and the custom path itself.
- UwpReactInstance now contains a new helper to return the root path to classes that don't have references to DevSettings
- OInstance and ReactImage both use the custom root path when available.
=> Adding support for setting a custom root path for bundle loading

vnext/Playground/NuGet.Config
Solves the packages relative path issue when running sample apps from `ReactWindows.sln` or `Playground\Playground.sln`.
=> Added NuGet.config for Playground.

vnext/ReactUWP/Views/ViewManagerBase.cpp
https://github.com/microsoft/react-native-windows/issues/2660
I didn't track down the exact problem, but especially with centered content/text we're seeing truncated values getting used to calculate layout that cause unwanted truncation.  Rounding up in measure fixes these
=> Fix occasional text clipping

vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/Image/ReactImage.h, vnext/Universal.SampleApp/index.uwp.js
Adds simple base64 image decoding support, 
based on react-native-windows current's code here:
https://github.com/microsoft/react-native-windows/blob/48a23b5181c7e91c1ec243c9556a6e81351a8927/current/ReactWindows/ReactNative.Net46/Modules/Image/BitmapImageHelpers.cs#L36
=> add base64 image support

vnext/ReactUWP/Modules/Animated/AnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/AnimationDriver.h, vnext/ReactUWP/Modules/Animated/NativeAnimatedNodeManager.cpp
If animation manager manually shuts down / drops animations before they complete, we currently crash in the Completed notification looking at freed memory.  We have some things in a flyout animating that get manually shut down as the flyout closes that are crashing with animated now existing (I think before just some debug message was being shown about animated not being implemented)
This probably was working before we removed the shared_ptr types that would keep some stuff alive.
Fix - manually revoke (since the auto revoker was noted as not working)
Also fix make_unique code in animated to not do an extra copy.  Discovered when I tested auto_revoker it wouldn't compile because there is no copyctor for auto_revoker.
=> fix Animated shutdown crash

vnext/package.json, vnext/yarn.lock
```
ea965d655 Applying package update to 0.59.0-microsoft.8
d0c0bb191 Nanava/configurejs (#96)
```
=> Update to react-native@0.59.0-microsoft.8

vnext/.editorconfig, vnext/Folly/Folly.vcxproj, vnext/IntegrationTestScripts/IntegrationTests.njsproj, vnext/Playground/Playground/Playground.csproj, vnext/PropertySheets/React.Cpp.props, vnext/docs/GettingStarted.md, vnext/local-cli/generator-windows/templates/proj/MyApp.csproj
After commit ( 6c5ede477ea364a4c72de80f21959f3c42851082 ), The MSVC `PlatformToolset` (and thus, the compiler version) is set depending on the Visual Studio version as follows:
- v141 (compiler version 14.16.27023) for Visual Studio 2017
- v142 (compiler version 14.21.27702) for Visual Studio 2019
Continuous Integration and Deployment (CI/CD) for react-native-windows is don using the v141 toolset.
This will lead to continuous compiling and linking issues due compiler versions used to build certain dependencies, like `ChakraCore.Debugger`:
```
LINK : fatal error C1047: The object or library file 'packages\ChakraCore.Debugger.0.0.0.36\lib\x64\Release\ChakraCore.Debugger.ProtocolHandler.lib' was created with an older compiler than other objects; rebuild
```
While dependencies could be …
=> Enforce correct platform toolset

vnext/Desktop.UnitTests/EmptyUIManagerModule.cpp, vnext/Desktop/Executors/WebSocketJSExecutor.cpp, vnext/Desktop/Sandbox/NamedPipeEndpoint.cpp, vnext/Desktop/Sandbox/SandboxBridge.cpp, vnext/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp, vnext/ReactUWP/Modules/Animated/AnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp, vnext/ReactUWP/Modules/Animated/StyleAnimatedNode.cpp
The ones I am actually blocked on are in the Animation files, that getInt() even of a whole number throws in JSI mode, since all numbers are doubles.
I searched for all getInt and fixed some others to be asInt to match how react internally handles some places that must be ints (how our sandbox stuff works)
=> more getInt fixes for JSI mode

vnext/PropertySheets/DynamicLibrary/Debug.props
Debug dlls in the nuget package are not debuggable right now
this sets the full debug flags that we have in ship
=> Use full pdbs in debug

vnext/ReactUWP/Modules/NetworkingModule.cpp
We had a brief period of time today with an invalid cert on a server we connect to.
When that happened we were crashing in NetworkingModule - the response was null in this case instead of having some error code.
I tried to see what happens with no network at all, but it doesn't get this far (may be another bug that the timeout is too long) and was fine
=> add error handling in NetworkingModule

vnext/package.json, vnext/yarn.lock
```
855ac4820 Applying package update to 0.59.0-microsoft.11
3432672db Yoga: call getMeasure even when YGMeasureModeExactly (#100)
```
=> Update to react-native@0.59.0-microsoft.11

.ado/windows-vs-pr.yml, .vscode/settings.json, vnext/docs/GettingStarted.md, vnext/just-task.js, vnext/src/RNTester/AccessibilityExample.tsx, vnext/src/RNTester/DatePickerExample.uwp.tsx, vnext/src/RNTester/FlyoutExample.uwp.tsx, vnext/src/RNTester/GlyphExample.tsx, vnext/src/RNTester/KeyboardExample.tsx, vnext/src/RNTester/KeyboardExtensionExample.uwp.tsx, vnext/src/RNTester/KeyboardFocusExample.uwp.tsx, vnext/src/RNTester/PickerUWPExample.tsx, vnext/src/RNTester/PopupExample.uwp.tsx, vnext/src/RNTester/ThemingExample.uwp.tsx
- Update some imports to handle new file layout.
- Add test to CI loop to verify that the RNTester bundle is buildable
- Update GettingStarted doc to reflect new location of RNTester
- Updated CI loop to specify 0.59 version when doing CLI test
- Updated GettingStarted doc to let people know they need to specify 0.59 when creating a new app
=> Fix RNTester bundle

vnext/ReactUWP/Views/FlyoutViewManager.cpp
When multiple flyouts are overlapping, XAML shadow rendering doesn't use the right z-order.  The result is very noticeable. As a workaround for this problem, I disable theme shadows when more than 1 flyout is open.
At some point we can consider a fix that retains theme shadows in this scenario by exposing depth properties to the app, but this will be more complex for app devs for limited benefit.
=> Workaround for overlapping flyout shadows

vnext/package.json, vnext/yarn.lock
```
29798b2af Applying package update to 0.59.0-microsoft.12
2556f0ed5 Rojain/executorflowfix (#103)
```
=> Update to react-native@0.59.0-microsoft.12

vnext/ReactUWP/Views/FlyoutViewManager.cpp
Issue: The Flyout container doesn't resize correctly in the "Full" placement view. 
Fix: Set the correct width and height when the layout happens.
=> Flyout container size fix for full view

vnext/ReactUWP/Views/KeyboardEventHandler.cpp, vnext/ReactWindows-UWP.sln, vnext/include/ReactUWP/Views/KeyboardEventHandler.h, vnext/src/Libraries/Components/Keyboard/KeyboardExtProps.ts, vnext/src/RNTester/KeyboardExtensionExample.uwp.tsx
Fix #2679
For the HandledKeyboardEvent, key is renamed to code.
For the native keyboard event, we raise both key and code.
the code follows [uievents-code](https://www.w3.org/TR/uievents-code/)
=> implement keyboard code

vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Modules/DevSupportManagerUwp.cpp
There is currently a window of time between starting the instance and when a root view attaches to it, where we can miss live reload requests.  Once a request has come in, we stop polling for more reload requests and the app is stuck in a 'will never reload' state.  In practice, we hit this 100% of the time with haul when making the first request - it takes a long time where we have a blocking download in init, and we process the reload request quickly enough after that, that it comes in before we've registered for reload notifications.
I have 2 changes here, either one would fix the bug I'm seeing, I could leave either out if there is a preference:
(1) [uwpreactinstance.cpp] Mark the instance as needs reload (we already have a flag and methods, that were unused, I looked back in the …
=> Fix for immediate live reload

vnext/ReactUWP/Views/FlyoutViewManager.cpp
The FlyoutPresenter property, IsDefaultShadowEnabled, is only available on 19h1.  My previous workaround for the flyout shadow rendering problem wasn't conditionalized for that. This change adds a check for the existence of that property before allowing the workaround.
=> Conditionalize the flyout shadow rendering fix to existence of property

vnext/ReactUWP/Views/FlyoutViewManager.cpp
The FlyoutPresenter applies a theme-based default border that is inappropriate for RNFW. This change disables that default border so that the RN consumer can control their own content.
=> Disable default border on flyouts

vnext/package.json, vnext/yarn.lock
```
c3d63f251 Applying package update to 0.59.0-microsoft.14
db15d249a cache path added (#98)
e1d0925e4 Applying package update to 0.59.0-microsoft.13
f4bf4a922 Remove bit specification from nodeType_ in YGNode.h (#104)
```
=> Update to react-native@0.59.0-microsoft.14

vnext/package.json, vnext/yarn.lock
```
e014f589d Applying package update to 0.59.0-microsoft.15
846049b6f Rojain/fix59 (#108)
```
=> Update to react-native@0.59.0-microsoft.15

vnext/src/Libraries/AppTheme/AppTheme.ts
ran into errors with NativeEventEmitter in a crossplat project that was importing a react-native-windows component (but not actually hitting any code that used RNW js), but because AppTheme is included by index.ts and always constructs a global class, it is always running.
Updated based on the fallback code in AppTheme.uwp.ts
=> update AppTheme stub for non-windows

vnext/ReactUWP/Modules/Animated/ValueAnimatedNode.cpp
add nullcheck
I checked all the other Get*AnimatedNode functions and everything else is already checking
=> Animation crash fix

vnext/package.json, vnext/yarn.lock
```
7f1b95247 Applying package update to 0.59.0-microsoft.16
05c907ed6 Rojain/fix59 (#109)
```
=> Update to react-native@0.59.0-microsoft.16

.clang-format, vnext/Universal.UnitTests/App.xaml.cpp, vnext/Universal.UnitTests/MainPage.xaml.cpp, vnext/Universal.UnitTests/Tests/StringConversionTests_Universal.cpp
This makes it so pch.h is always at the top and cppwinrt generated files get moved to below the "main" header.
File: Foo.cpp
```cpp
#include pch.h
#include Foo.h
#include Foo.g.cpp
```
=> clang-format: add rule for pch.h and generated files

vnext/Universal.SampleApp/HostingPane.xaml, vnext/Universal.SampleApp/HostingPane.xaml.cpp, vnext/Universal.SampleApp/HostingPane.xaml.h
We have a handful of small sample apps in the repo that can be loaded by our Universal SampleApp.
In preparation for adding potentially more (and making it easier to load the existing ones) I've changed the text boxes at the top of the app to combo boxes and have added every existing sample in the repo.
The combo boxes are still editable if for whatever reason you want to manually specify a specific path.
=> Updated SampleApp with drop-down of available samples

vnext/package.json, vnext/src/Libraries/Components/Button.uwp.js, vnext/src/Libraries/Components/Button.windesktop.js, vnext/src/Libraries/Components/ScrollView/ScrollView.windesktop.js, vnext/src/Libraries/Components/TextInput/TextInput.windesktop.js, vnext/src/Libraries/YellowBox/UI/YellowBoxList.windesktop.js, vnext/yarn.lock
Button was modified in MS/RN for uwp.  That change should be in RNW so that it works without MS/RN.
Also added stubs for various components for windesktop.
These changes will allow removal of some changes in the MS/RN fork, for further alignment with RN.
https://github.com/microsoft/react-native/pull/111 - This is the PR that will remove changes in the MS/RN fork
=> Reduce changes needed for uwp in fork

vnext/ReactUWP/Modules/Animated/AnimationDriver.cpp
When StopAnimation runs instead of full completion, 2 things were happening -
1) the RemoveActiveAnimation wasn't happening in this path
2) we would endCallback, but then often the endCallback would be called a second time if the animation completed.  If you call the same callback twice the js side throws on the second one.  Added code to unregister the completion token.
=> StopAnimation fixes

vnext/ReactUWP/Polyester/ButtonViewManager.cpp, vnext/ReactUWP/Polyester/ButtonViewManager.h, vnext/ReactUWP/Polyester/ContentControlViewManager.cpp, vnext/ReactUWP/Polyester/ContentControlViewManager.h, vnext/ReactUWP/Views/ViewViewManager.cpp, vnext/ReactUWP/Views/ViewViewManager.h
https://github.com/microsoft/react-native-windows/issues/2783
This fixes some fallout of the auto_revoker changes recently made.  We can't use auto_revoker in a ViewManager, must be done in ShadowNode.  This moves ViewViewManager things to ViewShadowNode and ButtonViewManager to a new ButtonShadowNode.
For View - I also moved the accessibility event being registered for so all callers of DispatchEvent could be in the shadownode.
ViewShadowNode is getting pretty big as a class with all inline functions, should probably do a followup checkin that fixes that and moves the rest of the ViewViewManager into the shadownode (basically - updateproperties)
For Button - (while this control will get deleted soon, keeping it functional) it's base class was already creating a shadownode that wasn't in …
=> Fix Focus/Blur events, bring back space/enter handling temporarily

current/local-cli/runWindows/runWindows.js, current/local-cli/runWindows/utils/deploy.js, current/local-cli/runWpf/runWpf.js, current/local-cli/runWpf/utils/deploy.js
There is currently a problem with packager.bat for starting the react-native server. This change addresses that issue until targeting a version with react-native PR #25517.
=> Patch for run-windows command

vnext/ReactUWP/Views/Image/ReactImage.cpp
this change:
https://github.com/microsoft/react-native-windows/commit/08aaf1895e95873fe7a755d2d60d1928bb3777a4#diff-123785e2fea604498e13edd8bfd21628 from @Thristhart 
introduced a weak reference with the LoadCompleted event.  The problem is it gets the weak ref from a background thead after the download and the reactImage instance may have been freed already. 
This moves getting the weakptr to before any switch to a coroutine thread happens
--
Scenario wise we are hitting this when going to a screen with a bunch of images being downloaded, if you navigate away so all those Image elements are destructed, we crash in a weakref dtor with invalid heap free stuff happening
=> fix timing crash in ReactImage

blog/Roadmap2019.md, vnext/docs/ParityStatus.md
NetInfo module has been updated to support react native windows - current version as of [v3.2.0](https://github.com/react-native-community/react-native-netinfo/releases/tag/v3.2.0). Marking that column for "current version status" as completed.
Also updated broken link in roadmap blog
=> Updating parity of NetInfo module

vnext/ReactUWP/Modules/ImageViewManagerModule.cpp, vnext/ReactUWP/Modules/NativeUIManager.cpp, vnext/ReactUWP/Views/WebViewManager.cpp
This fixes a few things I ran into trying out the samples in microsoft/react-native-adaptivecards and microsoft/AdaptiveCards/source/community/react-native  with vnext.
* providing numbers as strings for some flex properties
* requesting ImageSize on inline image data was crashing as we tried to download with that as a uri
* use of webview source:html and no uri would throw unrecoverable exception.  fail more gracefully
fixes https://github.com/microsoft/react-native-windows/issues/2836
=> Adaptive cards compat

change/react-native-windows-2019-07-30-22-39-57-flyout_background_fix.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
- If the flyout's child element has border radius, the flyout container is visible at the corners with a default background color (shade of grey). Fixing that by setting the background color to transparent by default.
- Also, refactored the presenter code to reuse it in SetLayoutProps for full placement mode.
- Tested this change in the playground app.
=> Update flyout container background color to transparent

change/react-native-windows-2019-08-02-07-32-57-users-stecrain-fixImageOnLoad.json, vnext/ReactUWP/Views/Image/ImageViewManager.cpp, vnext/ReactUWP/Views/Image/ImageViewManager.h
Fixes #2855 
I introduced this regression while fixing a memory leak in PR #2667 
Sorry about breaking it :( 
The test cases are covered by RNTester, but I didn't compare RNTester before and after my changes.
Current RNTester coverage of this will add a green checkmark when the even fires, but there isn't an indication when the even fails to fire.
=> Fix Image OnLoad never firing

change/react-native-windows-2019-08-01-15-19-17-switchprops.json, vnext/ReactUWP/Views/SwitchViewManager.cpp, vnext/ReactUWP/Views/TextInputViewManager.cpp
#2140 
- Adding support for thumbColor and trackColor to switch: since XAML does not have corresponding color brush properties on ToggleSwitch control, we have to be creative: find the child shapes and change the fill color in the code. I choose the timing of Loading event fired to do so, this happens right after ToggleSwitch added to the tree and measure called for the first time. 
- Also found two bugs in TextInputViewManager while playing with it as learning examples, the PlaceHolderTextColor was not applied correctly due to casting the object to ITextBlock6 instead of ITextBox6. (typo?).  Second issue is that the ViewChanging event was hooked up at wrong time, during view creation the template has not been applied and GetTemplateChild will return null, so fix it by moving the event …
=> New switch props (thumbColor and trackColor), and fix bugs found in TextInputViewManager

change/react-native-windows-2019-07-31-12-56-17-touchableFocusFixes.json, vnext/src/Libraries/Components/Touchable/TouchableHighlight.uwp.js, vnext/src/Libraries/Components/Touchable/TouchableOpacity.uwp.js, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.uwp.js, vnext/src/RNTester/KeyboardFocusExample.uwp.tsx
onFocus / onBlur are not working for uwp Touchables.
To fix this I added a binding for onFocus/onBlur.  In TVos where they also have onfocus/onblur they do this a little differently in they apply a component via mixin that then enables the touchableHandleFocus/touchableHandleBlur methods to be invoked.
Also I noticed that TouchableWithoutFeedback was not forked for uwp and didn't have the keyboard space/enter/gamepad key events hooked up.  I forked from microsoft/react-native, applied those changes and this focus/blur fix.
For testing I added some example code in our KeyboardFocusExample showing focus'ing touchables (well the ones that support .focus()) and the events.  
@licanhua - In trying it out I couldn't actually focus the checkbox and some other items, if that worked before its not …
=> Touchable focus event fixes

change/react-native-windows-2019-08-02-14-43-08-missing_win7_deps.json, change/react-native-windows-extended-2019-08-02-14-43-08-missing_win7_deps.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
The addition of a C++/WinRT-based ABI has created dependencies on DLLs that are absent on Win7, causing react-native-win32.dll load failures. This change is a short-term workaround that switches these DLLs from being eagerly- to delay-loaded, enabling use of react-native-win32.dll as long as the C++/WinRT ABI is not being used.
This change is intended to be followed by a long-term solution that should allow the use of the C++/WinRT ABI on Win7.
=> Delay-load dependencies absent on Win7

.ado/evergreen.js, .ado/evergreen.yml, .ado/setRNVersion.js
Old logic wasn't updating all packages, and hadn't been updated since the repo moved to yarn/lerna
=> Update evergreen to bump all packages

change/playground-2019-08-04-21-58-38-auto-update-versions059.0microsoft.33.json, change/react-native-windows-2019-08-04-21-58-36-auto-update-versions059.0microsoft.33.json, change/react-native-windows-extended-2019-08-04-21-58-37-auto-update-versions059.0microsoft.33.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
15fe5c973 Applying package update to 0.59.0-microsoft.33
70ecb1f87 Publish update
58e28996e Skip half published version
```
=> Update to react-native@0.59.0-microsoft.33

change/react-native-windows-2019-08-04-21-55-43-morejsi.json, vnext/ReactUwp.nuspec, vnext/ReactWin32.nuspec, vnext/layoutFilesForNuget.bat
Latest sync of react-native, includes more jsi headers, which should be included as part of the nuget.
=> Include additional jsi headers in nuget

change/react-native-windows-2019-08-02-15-28-12-TextTrim.json, change/react-native-windows-extended-2019-08-02-15-28-12-TextTrim.json, vnext/ReactUWP/Views/TextViewManager.cpp
#2849 
The default wrapping used for TextBlock in RNW is wrapping. When numberOfLines is set to 1, we should set wrapping to none, to have proper trimming/ellipsis for single line text.
=> Fix text trmming issue for single line text

change/react-native-windows-2019-08-05-11-48-15-auto-update-versions059.0microsoft.34.json, change/react-native-windows-extended-2019-08-05-11-48-16-auto-update-versions059.0microsoft.34.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
10db60ebd Applying package update to 0.59.0-microsoft.34
15101b6f5 Fixing folly related build failures (#125)
```
=> Update to react-native@0.59.0-microsoft.34

change/react-native-windows-2019-08-06-00-52-28-auto-update-versions059.0microsoft.35.json, change/react-native-windows-extended-2019-08-06-00-52-29-auto-update-versions059.0microsoft.35.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
44a997235 Applying package update to 0.59.0-microsoft.35
928a60f4f Stop defining UIView and UIScrollView on macOS for Xcode 11 compatibility (#127)
```
=> Update to react-native@0.59.0-microsoft.35

change/react-native-windows-2019-08-06-15-54-50-auto-update-versions059.0microsoft.36.json, change/react-native-windows-extended-2019-08-06-15-54-51-auto-update-versions059.0microsoft.36.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
f8f9d7150 Applying package update to 0.59.0-microsoft.36
4ded2e53e Rojain/c++stlrevert (#128)
```
=> Update to react-native@0.59.0-microsoft.36

change/react-native-windows-2019-08-06-20-37-26-auto-update-versions059.0microsoft.37.json, change/react-native-windows-extended-2019-08-06-20-37-27-auto-update-versions059.0microsoft.37.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
c4c1adf15 Applying package update to 0.59.0-microsoft.37
2a08f2d64 Ensure npm tar file is included in final build artifact
```
=> Update to react-native@0.59.0-microsoft.37

change/react-native-windows-2019-08-07-15-50-50-auto-update-versions059.0microsoft.38.json, change/react-native-windows-extended-2019-08-07-15-50-51-auto-update-versions059.0microsoft.38.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
2c52bb06e Applying package update to 0.59.0-microsoft.38
917be36bb Update cmake build for jsi file moves (#130)
```
=> Update to react-native@0.59.0-microsoft.38

change/react-native-windows-2019-08-06-15-37-15-issue2894.json, vnext/src/Libraries/Components/Touchable/TouchableHighlight.uwp.js, vnext/src/Libraries/Components/Touchable/TouchableOpacity.uwp.js, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.uwp.js, vnext/src/Libraries/Components/View/ViewWindowsProps.ts, vnext/src/RNTester/AccessibilityExample.tsx
* Adding accessibilityPosInSet and accessibilitySizeOfSet props to ViewWindows and Touchables, #2894
=> Adding RNW accessibility extensions to RNW ViewProps

change/react-native-windows-2019-08-08-09-42-24-usejunc.json, packages/playground/postinstall.js, vnext/docs/BuildingRNW.md
When trying to enlist in RNW on a new machine I hit an issue where windows doesn't allow users to create symlinks without elevating, which would block non-admins from being able to correctly run the playground app.
This switches to use junctions on windows machines, which are able to be created by non-admins.
=> Use junctions instead of symlinks on windows

change/react-native-windows-2019-07-31-16-18-01-ScrollViewerLayoutbug.json, change/react-native-windows-extended-2019-08-02-13-57-41-ScrollViewerLayoutbug.json, vnext/ReactUWP/Modules/NativeUIManager.cpp, vnext/ReactUWP/Modules/NativeUIManager.h, vnext/ReactUWP/Views/PickerViewManager.cpp, vnext/ReactUWP/Views/ShadowNodeBase.cpp, vnext/include/ReactUWP/Views/ShadowNodeBase.h
Moving the spot fix introduced by https://github.com/microsoft/react-native-windows/pull/2584 to NativeUIManager's UpdateExtraLayout method so that it can be applied to any control introduced to the tree in case similar bugs would be introduced by controls other than ScrollViewer/Picker. UpdateLayout will now be run on controls at the time that DoLayout is called from onBatchComplete. This should allow the controls to evaluate their final size before the rest of the layout is finished.
=> Scroll viewer layoutbug

change/react-native-windows-2019-08-08-12-17-05-hit-test-bug.json, vnext/ReactUWP/Views/TouchEventHandler.cpp, yarn.lock
Fix for #2903 
Hit-testing is incorrect when FlowDirection is set to RTL on the root of the XAML tree. 
This is due to us using TransformToVisual incorrectly - it should be TransformToVisual(nullptr) to transform to Window coordinates.
=> Fix RTL hit test bug

change/react-native-windows-2019-08-07-12-42-49-andrewh-DebuggingFixes.json, packages/playground/Samples/index.tsx, vnext/ReactUWP/Views/ViewManagerBase.cpp
2 minor changes:
1. In playground/Samples/Index . when it was ported to TS the view hierarchy was broken slightly so things are being stacked into columns instead of rows, so you can't see all the UI and some things are just broken.
2. in debug set the Tag as the Name
Not sure if this is useful to others, but I keep debugging things our app and I know the Tag id and want to look it up with the live visual tree.  For example the last case, I was seeing something getting focused unexpectedly and then focus was immediately moved somewhere else.  I couldn't see or know what the focused thing was other than knowing its ID via messagespy events.
=> Fix Sample/Index layout, set Tag to Name in debug

change/react-native-windows-2019-08-09-05-59-55-auto-update-versions059.0microsoft.40.json, change/react-native-windows-extended-2019-08-09-05-59-56-auto-update-versions059.0microsoft.40.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
2c2ac65b9 Applying package update to 0.59.0-microsoft.40
50dd558c7 Rojain/droidnuget (#135)
1512d0f65 Applying package update to 0.59.0-microsoft.39
0785bf81b Replace unique_ptrs in ScriptStore.h with shared_ptrs. (#132)
```
=> Update to react-native@0.59.0-microsoft.40

change/react-native-windows-2019-08-09-12-02-28-scriptstorefixes.json, vnext/ReactUWP/Utils/UwpPreparedScriptStore.cpp, vnext/ReactUWP/Utils/UwpPreparedScriptStore.h, yarn.lock
Fixing the break introduced by this PR: https://github.com/microsoft/react-native/pull/132
=> Update UwpPreparedScriptStore to use shared_ptrs

change/react-native-windows-2019-08-08-19-39-16-appThemeTypingFixes.json, vnext/src/Libraries/AppTheme/AppTheme.ts, vnext/src/Libraries/AppTheme/AppTheme.uwp.ts, vnext/src/Libraries/AppTheme/AppThemeTypes.ts, vnext/src/RNTester/AccessibilityExample.tsx, vnext/src/RNTester/ThemingExample.uwp.tsx
some small changes around AppTheme I noticed while integrating it into our app.
currentTheme exposed as a string, updated that the type will always be 'light' or 'dark'.
fixed the examples to take the right types/don't use any.  It was unclear if we want the examples to read the apptheme or read the event props - are we guaranteed the apptheme getter will have been notified first so that is safe?
=> update typing, examples for AppTheme

change/react-native-windows-2019-08-07-11-10-11-switch_shimmy_fix.json, vnext/src/Libraries/Components/Switch/Switch.uwp.tsx, vnext/src/Libraries/Components/Switch/SwitchProps.ts, vnext/src/index.uwp.ts
If you click on a Switch component to toggle it, you can see it "shimmy" back and forth once before settling. The Switch ends up toggling three times every time it's invoked.
The Switch component is a JS-controlled component. It's designed such that only the JS should be able to dictate what value it should be set to. In theory, invoking the toggle switch XAML control directly should fire a valueChanged event to the component so that it knows that the switch was pressed, but not actually change the value on the switch itself. The RN JS layer (the layer that connects the Switch component to its native counterpart) prevented the native switch from toggling to the new value by explicitly setting the switch to this.props.value. It also forwarded the event along to the component, which then …
=> Fix excessive toggles on the Switch component

change/react-native-windows-2019-08-10-19-34-13-auto-update-versions059.0microsoft.41.json, change/react-native-windows-extended-2019-08-10-19-34-14-auto-update-versions059.0microsoft.41.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
456718032 Applying package update to 0.59.0-microsoft.41
1b8721792 apple: fix timing issue crash in executeApplicationScript (#134)
```
=> Update to react-native@0.59.0-microsoft.41

change/react-native-windows-2019-08-12-18-55-52-auto-update-versions059.0microsoft.42.json, change/react-native-windows-extended-2019-08-12-18-55-54-auto-update-versions059.0microsoft.42.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
349719e51 Applying package update to 0.59.0-microsoft.42
d414abf04 Changing the signature of this method to match its counterpart on Fac… (#133)
```
=> Update to react-native@0.59.0-microsoft.42

change/react-native-windows-2019-08-13-00-47-14-auto-update-versions059.0microsoft.43.json, change/react-native-windows-extended-2019-08-13-00-47-16-auto-update-versions059.0microsoft.43.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
c7c4e265c Applying package update to 0.59.0-microsoft.43
bb62f8a00 Reduce differences between our folly and facebook folly (#138)
adc492dd8 Remove some final uses of uwp (#137)
bed45253b remove accessibility props that are no longer valid. (#136)
```
=> Update to react-native@0.59.0-microsoft.43

change/react-native-windows-2019-08-13-12-04-16-nocustomcli.json, vnext/local-cli/generator-windows/index.js
The cli.js script just forwards on to normal react-native now.
So we should just have the start command match a normal non-windows project.
`yarn start` will now just call `react-native start`
=>  Change windows template to not use cli wrapper

change/react-native-windows-2019-08-15-18-57-52-master.json, vnext/ReactUWP/Modules/NativeUIManager.cpp
This change:
https://github.com/microsoft/react-native-windows/pull/2859
accidentally deleted a bit of code that runs DoExtraLayoutPrep().
This change restores that bit of code.
=> restore accidental delete

change/react-native-windows-2019-08-15-11-19-01-upfolly.json, vnext/Desktop/msoFolly.h, vnext/Folly/Folly.vcxproj, vnext/FollyWin32/FollyWin32.vcxproj, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/PropertySheets/ReactPackageDirectories.props, vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def, vnext/layoutFilesForNuget.bat, yarn.lock
There are no outstanding reasons we need a fork of folly on windows.
This removes the usage of the forked version of folly, and bumps the version to latest.
=> Update to latest folly - and stop using forked folly

change/react-native-windows-2019-08-15-13-06-30-flyout-shadow-fix2.json, change/react-native-windows-extended-2019-08-15-13-06-30-flyout-shadow-fix2.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
This is an improved fix for the overlapping shadow rendering problem previously fixed by  
https://github.com/microsoft/react-native-windows/pull/2733
Rather than disabling the theme shadows completely once multiple flyouts are open, we instead apply an elevation translation to the FlyoutPresenter derived from the count of open flyouts. This allows the theme shadows to remain in their original state while no longer exhibiting the weird background.
(WI: 3485699)
=> Flyout shadow fix2

change/react-native-windows-2019-08-13-12-59-23-cknestri-UpdatePlacementMapping.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
The Flyout control on pre-RS5 only supports placement of "top", "bottom", "right", "left" and "full".  If the caller tries to set something not supported - like "top-edge-aligned-left" - it simply sets a default placement of "right".  This change allows us to provide a slightly better experience and simply convert the placement type to the closest primary placement position.  For example, if attempting to set "top-edge-aligned-left", it will ignore the "left" portion  of the placement and instead use "top".
=> Update Flyout Placement Mapping For Pre-RS5

packages/microsoft-reactnative-sampleapps/package.json, yarn.lock
This fixes the versions getting out of sync and breaking `yarn start`.
=> Fixed versions of rn, rnw in package.json

.ado/setRNVersion.js, change/react-native-windows-extended-2019-08-16-18-25-17-rnwefirst.json, packages/react-native-windows-extended/windows/react-native-windows-extended.vcxproj
Playground depends on `react-native-windows-extended`, which uses folly.
The first time you build, `react-native-windows-extended` fails to find some folly headers because it hasn't been downloaded yet.
The second time you build it succeeds, because the `ReactUWP` project depends on folly and that build will download the headers.
The fix is to have `react-native-windows-extended` properly declare that folly needs to be built first.
=> Playground solution failed to build first time

change/react-native-windows-2019-08-19-14-08-46-EditJSIEngineOverride.json, vnext/ReactWindowsCore/DevSettings.h, vnext/Shared/OInstance.cpp
Currently, whether Chakra or ChakraCore is used for ChakraJsiRuntime is controlled by a compiled time flag. We will be separating them into two separated Runtimes. Add another value to JSIEngineOverride to prepare for this.
=> Add ChakraCore to JSIEngineOverride.

change/react-native-windows-2019-08-19-22-43-52-liveReloadQueueFix.json, vnext/ReactUWP/Views/ReactControl.cpp, vnext/ReactUWP/Views/ReactControl.h
The ui messagequeue now requires it only be used from the jsThread.
Live reload & instance errors queue from other threads which assert (and crash when no debugger is attached) in debug builds
Remove usage of DefaultNativeMessageQueueThread in ReactControl to avoid this, use a coredispatcher instance directly
=> Live reload fix

.github/workflows/pr.yml
Creating an initial github action workflow to be able to test if it can work for us.
This initial version tries to duplicate some of the jobs that the current azure pipeline does.  -- It doesn't fully duplicate them all yet.  I also had trouble getting the matrix strategy to work properly, so that will need to be fixed before this can be turned on for real.
After check-in, I'll want to verify that this action runs correctly on PRs from forks in addition to PRs within the repo. -- And then maybe we can start moving the official checks to this, and deprecate the azure dev ops definition.
=> Initial github action workflow for CI

change/react-native-windows-2019-08-20-18-51-35-abitest-vs2019-build-fix.json, vnext/Desktop.ABITests/NativeTraceEventTests.cpp
Fix React.Windows.Desktop.ABITest.vcxproj build failure when building with VS2019.
=> Minor Fix For VS2019 Build

change/react-native-windows-2019-08-20-14-12-15-ViewFocusClickFixes.json, vnext/ReactUWP/Views/ViewViewManager.cpp
2 changes:
1. our Focus, Blur events are firing extra times when you have nested touchables.  
That makes it hard to track what has focus.  I added code to check if we're the originalsource for the focus/lostfocus event and only then dispatch the event to js.
On the JS side focus/blur events bubble so for this nested case we still need to look at the target of the event or use stopPropagation but at least its possible to tell what the actual target is now
2. remove the temporary code I had added back for space/enter handling.  We've now updated all the js components to have the keyboard event based touchable press logic.
=> View focus fixes, remove click fallback

change/react-native-windows-2019-08-21-15-13-45-DisableBatchingMessageQueueThread.json, vnext/Shared/OInstance.cpp
Commit 0280b5e74c1cfae3487bb1c6cb64b45213805860 adds a use of dynmaic_cast (to a BatchingMessageQueue) in OInstance.cpp. We cannot use dynamic_cast on Win32. While we figure out the long term solution, let's use a macro guard to disable said code for Win32.
=> Disable dynmaic_casting to BatchingMessageQueueThread on Win32

change/react-native-windows-2019-08-21-13-38-20-NetworkErrorReporting.json, vnext/ReactUWP/Modules/NetworkingModule.cpp
https://github.com/microsoft/react-native-windows/issues/2954
If an exception occurs in co_await or later, the outer catch() isn't getting anything due to the async thread continuing on.  Wrapping everything in another try / catch gets us the error.
Alternatively, making the existing call synchronous (adding .get()) also starts catching errors but we don't want to block the messagequeue
=> report more Networking errors to js

change/react-native-windows-2019-08-22-19-38-20-auto-update-versions059.0microsoft.49.json, change/react-native-windows-extended-2019-08-22-19-38-22-auto-update-versions059.0microsoft.49.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
65c6d97f3 Applying package update to 0.59.0-microsoft.49
ee48a7a48 Create github actions for android PR (#145)
1aee404ee Merge branch 'publish-temp-1566494281057'
00f196d64 Applying package update to 0.59.0-microsoft.48
60512ac2e Update main.workflow
dec6d4602 Update main.workflow
a59a4ebff Applying package update to 0.59.0-microsoft.47
5bff60fe0 ios 13 semantic and dynamic color support (#105)
03af69f29 Applying package update to 0.59.0-microsoft.46
0ecf30e5e Update main.workflow
df7a3068d Start github actions ci (#141)
87cef595f Reverting back to gnustl (#144)
49cb1d8f1 Applying package update to 0.59.0-microsoft.45
102128eec Using libcpp to build RN (#143)
3483c5ea2 Applying package …
```
=> Update to react-native@0.59.0-microsoft.49

change/react-native-windows-2019-08-23-13-55-55-HaulPollingExceptions.json, vnext/ReactUWP/Modules/DevSupportManagerUwp.cpp, vnext/ReactUWP/Modules/WebSocketModuleUwp.cpp, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj.filters, vnext/ReactUWP/Utils/CppWinrtLessExceptions.h
When using haul as your packager, frequent hresult exceptions are thrown.
We had this problem before with the react devtools trying to open socket connections and failing where I put in a workaround to use cppwinrt in a slightly manual way to not throw exceptions.  Haul usage is similarly noisy and annoying.  Actually we have a check around this error condition already because live reload would stop working when we got one of these errors, which we handle specifically - now we can handle that error without an internal exception being thrown.
This moves that helper code to a header and using it in another place.  For some reason haul returns these errors where when I use metro it seems to return more valid http results.
=> reduce Haul polling exceptions

change/react-native-windows-2019-08-28-17-21-55-auto-update-versions059.0microsoft.69.json, change/react-native-windows-extended-2019-08-28-17-21-57-auto-update-versions059.0microsoft.69.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
8d53a8ade Applying package update to 0.59.0-microsoft.69 ***NO_CI***
b769136cf Clearing the old systrace plumbing to make way for improved one (#149)
```
=> Update to react-native@0.59.0-microsoft.69

change/react-native-windows-2019-08-28-21-28-43-auto-update-versions059.0microsoft.70.json, change/react-native-windows-extended-2019-08-28-21-28-45-auto-update-versions059.0microsoft.70.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
d740554be Applying package update to 0.59.0-microsoft.70 ***NO_CI***
73a8a7e6d fix yellow box style in win32 (#150)
```
=> Update to react-native@0.59.0-microsoft.70

change/react-native-windows-2019-08-27-12-05-40-enable-windowsbrush-nonsolidcolor.json, vnext/ReactUWP/Utils/ValueUtils.cpp, vnext/include/ReactUWP/Utils/ValueUtils.h
The existing windowsbrush syntax (added by #2705) lets react look up and use XAML `SolidColorBrush` resources as colors and background colors. This PR refactors this to enable any brush resources, like `LinearGradientBrush` or `AcrylicBrush`.
This is accomplished by pulling the resource lookup logic into a function that returns `Brush` rather than `SolidColorBrush`, and casting that brush to `SolidColorBrush` in the scenarios where only SolidColor is allowed.
=> Allow windowsbrush: color syntax to use non-SolidColor brushes

change/react-native-windows-2019-08-29-17-25-49-users-ngbu-fix_touchableOpacity_doubleclick.json, vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
onPress event was being called twice due to onKeyUp calling `touchableHandlePress()` instead of `touchableHandlePressOut()`.
With these changes, onKeyUp and onKeyDown events will call the corresponding `touchableHandleActivePressOut` and `touchableHandleActivePressIn` event handlers and also pass the PressEvent value. 
Previously, the onPress event would be fired twice every time a touchableOpacity element was pressed because the onKeyUp event was calling the onClick event handler `touchableHandleActivePress`, which happens to call the passed in onPress event handler.
=> Fix double onPress issue in touchableOpacity

change/react-native-windows-2019-08-30-11-04-44-users-ngbu-fix_touchable_doubleClick.json, vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
Similar to PR: #3042 , Fix calling onPress twice in touchableHighlight and touchableWithoutFeedback.
=> Fix calling onPress twice in touchableHighlight and touchableWithoutFeedback

change/react-native-windows-2019-08-30-08-13-54-users-stecrain-scrollViewFocus.json, vnext/ReactUWP/Views/Impl/SnapPointManagingContentControl.cpp
Addresses #2939
Setting IsTabStop false helps to prevent lots of strange behavior with dpad navigation on Xbox
=> Mark SnapPointManagingContentControl IsTabStop = False

change/react-native-windows-2019-09-02-20-05-46-auto-update-versions059.0microsoft.72.json, change/react-native-windows-extended-2019-09-02-20-05-47-auto-update-versions059.0microsoft.72.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
aa695884d Applying package update to 0.59.0-microsoft.72 ***NO_CI***
5eea8000c Fix regression caused by PR https://github.com/microsoft/react-native/pull/146. (#152)
```
=> Update to react-native@0.59.0-microsoft.72

change/react-native-windows-2019-09-03-20-41-23-auto-update-versions059.0microsoft.73.json, change/react-native-windows-extended-2019-09-03-20-41-25-auto-update-versions059.0microsoft.73.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
f990028a2 Applying package update to 0.59.0-microsoft.73 ***NO_CI***
041a12d39 Update react-native PR build pipeline to use macOS Mojave agents and XCode 11 beta (#153)
aa695884d Applying package update to 0.59.0-microsoft.72 ***NO_CI***
5eea8000c Fix regression caused by PR https://github.com/microsoft/react-native/pull/146. (#152)
```
=> Update to react-native@0.59.0-microsoft.73

change/react-native-windows-2019-08-30-22-07-10-user-savatia-vscode-debugging.json, vnext/local-cli/runWindows/utils/commandWithProgress.js
By default, ora uses [process.stderr](https://github.com/sindresorhus/ora#stream) as the output stream, however,the VS Code debugger uses [stdout](https://github.com/microsoft/vscode-react-native/blob/13a9942728c2e3d62b3a5353d0a74b05cd2c8919/src/common/outputVerifier.ts#L32) to match success patterns. Hence the output is never verified and the debugger fails to start (#2875).
=> Changed deploy output to use StdOut

current/docs/GettingStarted.md
Because React-native 0.60 is released but not supported by React Native Windows, we need to manually set the version number in the command `react-native init` to use a supported version.
If the version isn't explicitly set, `react-native windows` will fail with the following error message: 
```
error Unrecognized command "windows".
info Run "react-native --help" to see a list of all available commands.
```
=> Update GettingStarted.md (current) to update react-native init command

change/react-native-windows-2019-09-05-02-38-17-HEAD.json, change/react-native-windows-extended-2019-09-04-17-03-52-testdll-def-CreateStringResponseBody.json, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x64.def, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x86.def
DEF files for Desktop test DLL missed symbol for helper function `Microsoft::React::Test::CreateStringResponseBody`.
=> Update CreateStringResponseBody symbol in test DLL.

change/react-native-windows-2019-09-05-14-52-58-a11yAsDouble.json, vnext/ReactUWP/Views/FrameworkElementViewManager.cpp, yarn.lock
JSI makes all dynamic numbers doubles, so we can't use getInt - we have to asDouble and cast it to int.
=> Fix issue with using getInt instead of asDouble for JSI

change/react-native-windows-2019-09-04-12-52-15-SecureTextEntry.json, packages/E2ETest/app/Consts.ts, packages/E2ETest/app/LoginTestPage.tsx, packages/E2ETest/reports/appium.txt, packages/E2ETest/wdio/pages/LoginPage.ts, packages/E2ETest/wdio/test/login.spec.ts, packages/playground/Samples/textinput.tsx, packages/playground/windows/playground/HostingPane.xaml.cpp, vnext/ReactUWP/Views/ControlViewManager.cpp, vnext/ReactUWP/Views/FrameworkElementViewManager.cpp, vnext/ReactUWP/Views/ShadowNodeBase.cpp, vnext/ReactUWP/Views/TextInputViewManager.cpp, vnext/ReactUWP/Views/TextInputViewManager.h, vnext/include/ReactUWP/Views/ControlViewManager.h, vnext/include/ReactUWP/Views/FrameworkElementViewManager.h, vnext/include/ReactUWP/Views/ShadowNodeBase.h, vnext/include/ReactUWP/Views/ViewManagerBase.h, yarn.lock
We need to be able to dynamically creating/mapping view for the TextInput shadow node on the fly, TextBox object when SecureTextEntry is false/default or to PasswordBox object when SecureTextEntry is true. Normally each ShadowNode maps 1-1 to a view object in the tree, so added support to replace and reparent the new view object. 
Also in the swapping process, the properties needs to be transffered from the old view to new view too, so extended function TransferProperties to support individual view manager specific actions: e.g. TextBox.Text <=> PasswordBox.Password.
TextInputShadowNode is also modified to know if it is working with TextBox or PasswordBox, to work with different events as well as properties.
=> Support dynamic swapping TextBox/PasswordBox view for SecureTextEntry 

.ado/windows-vs-pr.yml, .github/workflows/pr.yml, change/react-native-windows-2019-09-06-16-39-05-user-savatia-cli-bundle-rename.json, vnext/.eslintignore, vnext/Microsoft.ReactNative/ReactInstanceCreator.cpp, vnext/local-cli/generator-windows/index.js, vnext/local-cli/generator-windows/templates/index.windows.bundle, vnext/local-cli/generator-windows/templates/index.windows.js, vnext/local-cli/generator-windows/templates/src/MainPage.xaml.cs
Changed the CLI bundle name from app.bundle to index.bundle so that VS Code can find the bundle and prewarm the cache.
Fix #2901
=> Change the CLI bundle name index.bundle (vnext)

change/react-native-windows-2019-09-10-10-21-46-SecureEntryTestFix.json, packages/E2ETest/wdio/pages/LoginPage.ts, packages/E2ETest/wdio/test/login.spec.ts, vnext/ReactUWP/Views/ControlViewManager.cpp
The test failure is caused by Automation properties not transferred between TextBox and PasswordBox when switching secureTextEntry on/off. The TransferProperties() virutal function should be called from TextInputViewManager class, then ControlViewManager class then FrameworkElementViewManager Class. When I addressed the last PR comment, a mistake was made so the call ended at ControlViewManager and the automation properties are not transferred (by FrameworkElementViewManager ).
=> Fix Login E2E test failure

change/react-native-windows-2019-09-10-14-48-28-fix-touchable-onkeyup-press.json, vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js, vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
As of v140, there were duplicate `onPress` events firing for keyboard/controller presses on Touchable*s. 
#2968 removed the native `onPress`, but unfortunately #3042 and #3049 removed the JS ones (not realizing that the native ones had already been removed.)
This PR brings back the JS `onPress` calls.
Verified using the Playground app and RNTester.
=> Fix onPress not firing for Touchable* keyboard events

change/react-native-windows-2019-09-11-17-37-20-auto-update-versions059.0microsoft.77.json, change/react-native-windows-extended-2019-09-11-17-37-22-auto-update-versions059.0microsoft.77.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
54fa12764 Applying package update to 0.59.0-microsoft.77 ***NO_CI***
e4bc81bf0 Trigger RNW's update RN build on publish
2ac75400c Move publishing back to Azure Dev Ops ***NO_CI*** (#158)
```
=> Update to react-native@0.59.0-microsoft.77

.ado/windows-vs-pr.yml, change/react-native-windows-2019-09-12-19-04-27-itfilter-enableall.json, vnext/Scripts/IntegrationTests.ps1, vnext/Scripts/UnitTest.ps1
PR builds are run in Windows images using Visual Studio 2017.
The pre-installed VSTest lacks filtering capabilities to exclude specific tests from running.
This change installs the 2019 VSTest tool and enables most Desktop integration tests that were until now excluded.
=> Enable most desktop integration tests.

change/react-native-windows-2019-09-11-10-32-12-addcommand.json, packages/E2ETest/package.json, vnext/local-cli/runWindows/runWindows.js
Fix #3021
Handy command to only build the app or only deploy the app.
```
yarn run buildapp
yarn run buildbundleapp
yarn run deployapp
yarn run deploybundleapp
yarn run test
yarn run testspec wdio\test\login.spec.ts
```
=> add more scripts to package.json in e2e

change/react-native-windows-2019-09-13-09-58-36-didatst1.json, vnext/local-cli/generator-windows/templates/proj/MyApp.csproj, yarn.lock
#2986 
According to VS2019 [post](https://developercommunity.visualstudio.com/content/problem/664223/uwp-app-doesnt-compile-in-vs-2019-162-because-of-c.html), we need to add PackageCertificatePassword attribute to csproj, in order to avoid the build issue caused by password protected temp pfx file.
=> Add PackageCertificatePassword to MyApp.csproj file

change/react-native-windows-2019-09-16-21-01-08-auto-update-versions059.0microsoft.82.json, change/react-native-windows-extended-2019-09-16-21-01-10-auto-update-versions059.0microsoft.82.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
c3bd68be7 Applying package update to 0.59.0-microsoft.82 ***NO_CI***
6589faa78 The Release target was missing MACOSX_DEPLOYMENT_TARGET causing it default to macOS 10.15 which when executed on os's prior to 10.15 causes the _objc_opt_new symbol to be called which is not present in the older systems' dylibs (#160)
bec5acbff Revert "Update package.json version"
0c6334f8f Update package.json version
0600fbb40 Applying package update to 0.59.0-microsoft.81 ***NO_CI***
be78aa3a0 Adding the destructor for the InspectorInterface, in order to fix the build error. (#156)
```
=> Update to react-native@0.59.0-microsoft.82

change/react-native-windows-2019-09-11-12-49-37-flyout-shadow-fix-4.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
In the last episode of the flyout shadow fix, the fix for the following bug, 
_"Flyout shadows cause an incorrect background color where Flyouts overlap."_
(#3022), did not get into RNW correctly. (See #2933 for original issue)
I mistakenly closed my branch before the fix was completed even though everything was all good to go! In any case, since then, we discovered that the existing tracking of open flyouts was not completely correct. This updated fix resolves that issue (by only updating the counter and 'hiding' the flyout when the flyout state _actually_ changes).
=> Flyout shadow fix

.ado/shouldSkipPRBuild.ps1, .ado/windows-vs-pr.yml, change/react-native-windows-2019-09-17-11-09-33-docsskipci.json, vnext/Scripts/Tfs/Start-TestServers.ps1
Ports over the logic in WinUI where we skip the CI builds for *.md files.
Fixes #3147 , #3146
=> Skip CI builds for documentation changes

change/react-native-windows-2019-09-18-10-27-56-HEAD.json, vnext/PropertySheets/React.Cpp.props, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/packages.config, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/packages.config
1. Moving to newer version of V8+JSI binary,  based on V8 v7.8. 
2. Enabling  the experimental pointer compression feature in V8 for 64-bit.
3. Many more configuration and instrumentation options.
2. Potential fix for the shutdown crash in devmain.
3. Enabling iterator debugging in debug builds so that we can remove a hack in our build script.
=> Refreshing V8 bits and a few fixes

change/react-native-windows-2019-09-17-09-54-48-didarnw2.json, packages/playground/Samples/textinput.tsx, vnext/ReactUWP/Views/TextInputViewManager.cpp, vnext/ReactUWP/Views/TextInputViewManager.h
For #3080:
Map keyboardType to inputscope of TextBox and PasswordBox respectively.
=> Support keyboardType for TextInput

change/react-native-windows-2019-09-24-14-05-30-statusbarmgr.json, vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Modules/StatusBarModule.cpp, vnext/ReactUWP/Modules/StatusBarModule.h, vnext/ReactUWP/ReactUWP.vcxproj
StatusBar.js assume that there is a StatusBarManager native module, and that it has a HEIGHT property.
<StatusBar> is used in the NewAppScreen experience that is part of the new react-native init app, so this causes new apps to crash.
=> Create stub StatusBarManager to avoid crash in NewAppScreen

.ado/templates/e2e-test-job.yml
Sometime WinAppDriver failed to launch the app, and it failed with `Original error: Failed to locate opened application window with appId: ReactUWPTestApp_kc2bncckyf4ap!App, and processId: 4120`
ms:waitForAppLaunch may help with this problem but the official WinAppDriver is not shipped yet.
This change workaround the problem by making the app launched before WinAppDriver created the new session.
=> Workaround to avoid WinAppDriver error: 'Failed to locate opened application window with appId'

change/react-native-windows-2019-09-19-17-00-18-updatetestdoc.json, vnext/docs/E2ETest.md
Fix part of #3136
Make bundle server and chrome window as manual step.
I tried some solution like downloading app/index.ts, and it's still not reliable. so make customer to manually start them.
=> update E2E test document

change/react-native-windows-2019-09-25-14-28-07-remove-v8-from-rncommon.json, vnext/ReactCommon/ReactCommon.vcxproj
We removed v8.h from the v8jsi nuget. Hence we need to remove the v8 related files from ReactCommon.vcxproj to ensure that things build when USE_V8 is defined.
=> Remove v8 related files from ReactCommon.vcxproj.

packages/E2ETest/windows/ReactUWPTestApp.sln
E2ETest solution don't have reference to react-native-windows-extended project.
=> remove react-native-windows-extended from E2ETest solution

.ado/publish.yml, .github/workflows/publish.yml, change/react-native-windows-2019-09-25-14-58-40-npmtagging.json, package.json, vnext/package.json, yarn.lock
Currently beachball is told to publish all packages in the repo using the @vnext npm tag.  (Note beachball doesn't run against the react-native-windows current version)
This change picks up a new version of beachball which allows us to have react-native-windows publish as vnext, but the rest of the packages publish as latest as normal.
(We hit an issue with the 0.60 release where when running the getting started steps, and old version of the rnpm package was getting installed because updates to it were being published as vnext not as latest).
=> Only publish react-native-windows using vnext tag

change/react-native-windows-2019-09-24-14-50-43-flyout-focus-fix.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
This fix needs to go to 0.59-vnext-stable, so that it can be picked up in our app (it's beta blocking)
See vnext PR https://github.com/microsoft/react-native-windows/pull/3192 for details.
=> (0.59-vnext-stable): Pointer events don't transfer focus to the Flyout on Open (Issue #3154)

change/react-native-windows-2019-09-24-14-50-43-flyout-focus-fix.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
In a previous fix, we set the AllowFocusOnInteraction property to false for the Flyout and its FlyoutPresenter to prevent some undesirable flyout dismissal problems.  See [https://github.com/microsoft/react-native-windows/pull/2817](https://github.com/microsoft/react-native-windows/pull/2817)
Unfortunately, that fix causes the focus to not transfer into any of the Flyout child elements when activated by a mouse/touch event.  The reason for this is that XAML makes a decision on whether or not to update the Focus element upon opening the flyout. If the action is due to a mouse/touch event and the AllowFocusOnInteraction property is set false on the Flyout, then the flyout doesn't update the Focus element. 
_(from %SDXROOT%\onecoreuap\windows\dxaml\xcp\components\focus\inc\FocusSelection.h)_ …
=>  Pointer events don't transfer focus to the Flyout on Open (Issue #3154)

change/react-native-windows-2019-09-27-16-18-29-follypatch.json, vnext/Folly/Folly.vcxproj, vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
The latest version of MSVC breaks folly.
This PR will fix folly, at which point we can update to the latest version of folly.
https://github.com/facebook/folly/pull/1234
But until then, this allows RNW to build using the latest compiler.
=> Workaround folly break until folly PR lands

.ado/templates/e2e-test-job.yml
For unknown reason, Instead of webdriver.git in package.json, the standard webdriver in WebDriverIO is used, and it cause the test fail on PR #3282. 
This fix removes the workaround before 'yanr install', then apply the workaround dynamic. So it would only have one copy of webdriver.
Also print Appium.txt when test failed.
=> Apply dynamic patch for WebDriverIO in pipeline and print appium.txt when test fail

change/react-native-windows-extended-2019-10-01-16-16-58-rnw-extended-version.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json
This commit accidentally bumped the react-native-windows-extended version to 0.61. 
https://github.com/microsoft/react-native-windows/commit/79285030542fe4164b699299142c87e48ec6f5eb#diff-ce8da290799a236b6b3e17528c87cca9
Changing it back to 0.60 so it matches react-native-windows. When we move to react-native 0.61, we will need to manually change react-native-windows-extended to 0.61.1 as 0.61 has already been published.
=> Align rnw-extended version number with rnw

change/react-native-windows-2019-10-03-09-55-39-deviceInfoUpdate.json, vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactUWP/Base/UwpReactInstance.h, vnext/ReactUWP/EndPoints/dll/react-native-uwp.oss.x64.def, vnext/ReactUWP/EndPoints/dll/react-native-uwp.oss.x86.def, vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def, vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86.def, vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86sdx.def, vnext/ReactUWP/Modules/DeviceInfoModule.cpp, vnext/ReactUWP/Modules/DeviceInfoModule.h, vnext/Universal.UnitTests/Tests/CreateModulesTests.cpp, vnext/src/Libraries/Utilities/Dimensions.windows.js, yarn.lock
#2470 
- Currently DeviceInfo is reporting CoreWindow's bounds for the window dimension, this update change it and hook up with the root element's size instead.
- When root element size changes, we should fire event to app to update the dimensions. This functionality is also added in this change. I tested with the RNTester;s Dimensions.jst and the update events worked fine.
- Additionally, the screen dimension reported was overwritten with window dimension in React Native, this is apple's behavior. We should adopt Android's behavior(user whatever reported by the native module) instead, so I also add a dimensions.windows.js for RNW.
=> Device info update

.ado/templates/e2e-test-job.yml, .ado/windows-vs-pr.yml
During code review of the initial setup of this, it was suggested to switch to using stages for the build, to reduce the number of places the conditions would be used.  This had an unfortunate side-effect of breaking the whole thing as the variables are only accessible within a single stage.
This puts the CI back into a single stage, so that the logic should work correctly.
=> Fix logic to skip CI on md changes

change/react-native-windows-2019-10-07-13-38-26-jsi-packagebump.json, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/packages.config, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/packages.config, vnext/Shared/OInstance.cpp
The JSI code path is still disabled by default; this change updates the packages to the latest versions and fixes a small bug in the JSI path.
=> Bump V8 and Hermes package versions

change/react-native-windows-2019-10-07-15-34-20-0.59-vnext-stable.json, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/packages.config, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/packages.config
The JSI code is still disabled by default; this just ports the change from master to 0.59.
=> Bump Hermes package version in the 0.59 branch

change/react-native-windows-2019-10-07-19-41-01-fixutassemblies.json, vnext/Scripts/IntegrationTests.ps1, vnext/Scripts/UnitTest.ps1
Avoid string array parsing conflicts in UnitTests.ps1 by explicitly grouping Assemblies argument concatenation between parentheses.
=> Fix UT script assemblies defaults.

change/react-native-windows-2019-10-08-09-49-20-users-stecrain-chakra-core-uwp.json, vnext/.npmignore, vnext/JSI/Desktop/JSI.Desktop.vcxproj, vnext/PropertySheets/React.Cpp.props, vnext/ReactUWP/ReactUWP.vcxproj
The refactor of JSI into separate projects had the unfortunate consequence of breaking this build flag to use ChakraCore with UWP.
Also adding a variable to allow building with PlatformToolset specified by the App.
=> Re-Add config options to optionally use ChakraCore in UWP

.ado/templates/e2e-test-job.yml
We didn't have good way to catch the crashes in build machine. Here I check if TestApp is running before starting E2E testing. Provide 'TestApp is not running' when test app is not running like crashed.
=> check if testapp is running

change/react-native-windows-2019-10-10-15-18-19-popup-shadow-fix.59.json, vnext/ReactUWP/Utils/Helpers.cpp, vnext/ReactUWP/Utils/Helpers.h, vnext/ReactUWP/Views/FlyoutViewManager.cpp, vnext/ReactUWP/Views/PopupViewManager.cpp, vnext/src/RNTester/FlyoutExample.windows.tsx
The overlapping Flyout shadow problem (https://github.com/microsoft/react-native-windows/pull/2733) also occurs with Popups. 
This is occuring in our app now when we integrated a component using a Popup into one of our Flyouts (See image below).
This means that we need to have the Flyout shadow fix extended to include Popups.
This PR does that by adding the Translation workaround from the FlyoutShadowNode to the PopupShadowNode and changes the tracking of open flyouts from the manual tracking code to a utility function using the XAML VisualTreeHelper::GetOpenPopups.
The PR also adds an embedded Popup to the RNTester app's Flyout example for more complexity.
=> (0.59) Extend overlapping Flyout shadow fix to cover Popups

change/react-native-windows-2019-10-11-10-01-03-hiddenCursor.json, packages/playground/Samples/textinput.tsx, vnext/ReactUWP/Views/TextInputViewManager.cpp, yarn.lock
#3087 
- The solution is not optimal, rather a hacking where we walk down the tree, find the caret element(shape) and make it transparent. 
- Current solution only support one way property change, meaning setting it to false. Toggle the property back to true is not supported, because the hacking solution gets complicated and XAML does not expose composition mode DestInvert(original composition mode set internally on caret) in public API.
- There is a feature request to add a public API to support caretHidden on XAML's text control, we should remove this hacking solution and use that new API when available.
=> Support caretHidden for TextInput

change/rnpm-plugin-windows-2019-09-24-09-54-53-issue3102.json, current/local-cli/rnpm/windows/src/wpf.js
A recent change to the `windows` command (4ff550e) specified the correct pre-release tag to install from (i.e., "rc" or stable) when running `react-native windows`. This change introduces the same logic for the `wpf` command.
Fixes #3102
=> Updates logic for `wpf` command to install correct dependency

current/Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js
Having issue when setting "autofocus" props to true for React Native Text Input will cause an error where this.requestAnimationFrame is not a function.
=> Remove "this" from this.requestAnimationFrame from PasswordBoxWindows

change/react-native-windows-2019-10-15-21-28-00-auto-update-versions060.0microsoft.7.json, change/react-native-windows-extended-2019-10-15-21-28-01-auto-update-versions060.0microsoft.7.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
147d30865 Applying package update to 0.60.0-microsoft.7 ***NO_CI***
adf59b9c4 RCTBackedTextInputViewProtocol and RCTBackedTextInputDelegate weren't getting built into the RCTTextLibrary, which is necessary for Polyester (#174)
ae7549cc2 Applying package update to 0.60.0-microsoft.6 ***NO_CI***
93b3e6e75 Use $buildNumber$ token for NuGet (#172)
```
=> Update to react-native@0.60.0-microsoft.7

change/react-native-windows-2019-10-15-17-00-10-popup-shadow-fix.json, vnext/ReactUWP/Utils/Helpers.cpp, vnext/ReactUWP/Utils/Helpers.h, vnext/ReactUWP/Views/FlyoutViewManager.cpp, vnext/ReactUWP/Views/PopupViewManager.cpp, vnext/src/RNTester/FlyoutExample.windows.tsx
This fix, https://github.com/microsoft/react-native-windows/pull/3388, was merged into 0.59-vnext-stable, but also needs to be in master.  This PR does just that.
=> (Forward port) Extend overlapping Flyout shadow fix to Popups

change/react-native-windows-2019-10-17-22-02-26-auto-update-versions060.0microsoft.8.json, change/react-native-windows-extended-2019-10-17-22-02-28-auto-update-versions060.0microsoft.8.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
b50dcb1ad Applying package update to 0.60.0-microsoft.8 ***NO_CI***
ae3428e72 Adding metro-config dependency (#176)
```
=> Update to react-native@0.60.0-microsoft.8

.ado/VSComponentList.ps1, .ado/templates/e2e-test-job.yml, .ado/windows-vs-pr.yml, change/react-native-windows-2019-10-15-18-17-54-v141path.json, vnext/local-cli/runWindows/utils/build.js, vnext/local-cli/runWindows/utils/msbuildtools.js
This change removes the hardcoded path to C:\Program Files (x86)\ ... where we go look for v141 tool. This addresses #3430 and #3435
=> Don't hardcode the path to v141 platform toolset

README.md, vnext/docs/GettingStarted.md, vnext/docs/win10compat.md
Adds back compat details for vNext in Win10 versions and other related changes in Getting started guide and readme to point to this file.
=> Adding Win10Compat matrix

change/react-native-windows-2019-10-22-00-08-35-auto-update-versions060.0microsoft.9.json, change/react-native-windows-extended-2019-10-22-00-08-37-auto-update-versions060.0microsoft.9.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
295e4fa98 Applying package update to 0.60.0-microsoft.9 ***NO_CI***
4af7d60da Add back jseConfigParams changes (#178)
```
=> Update to react-native@0.60.0-microsoft.9

change/react-native-windows-2019-10-21-18-46-29-calculatedanimation.json, vnext/ReactUWP/Modules/Animated/CalculatedAnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/CalculatedAnimationDriver.h, vnext/ReactUWP/Modules/Animated/DecayAnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/DecayAnimationDriver.h, vnext/ReactUWP/Modules/Animated/SpringAnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/SpringAnimationDriver.h, vnext/ReactUWP/ReactUWP.vcxproj
This reimplements Decay animations and creates a base class CalculatedAnimation that factors the logic that used to be in SpringAnimation so that it can be used by DecayAnimation. The formula for decay animation was wrong; in reality a decay animation has an exponential decay. This animation cannot be expressed as a cubic bezier curve so instead we use keyframes like Spring animation does (which has a neg-exponential component too). This addresses #3481 (and #3477 )
=> CalculatedAnimation

.ado/windows-vs-pr.yml, change/react-native-windows-2019-10-22-15-00-16-azure-pipelines.json, vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp, vnext/IntegrationTests/TestRunner.cpp
This PR is attempted to but will not completely fix bug #3444.
From what I see, problem is timeout in 'Run Desktop Integration Tests', and here are some possible reasons:
1. app crashes because of assert command
2. app crashes in RunTest
3. test case is waiting for metro bundle's response
4. when one of the tests fail, the test doesn't continue and I don't know which test is still running.
I'm trying to:
1. add blame flag for vstest, and expect it provides information like: `The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
RNTesterIntegrationTests::IntegrationTestHarness`
2. RunConfiguration.TestSessionTimeout=120000 to avoid wait for ever
3. try...catch...exception and convert the exception to test failure with the …
=> Add more logs and attempt to fix CI Loop instability: Build and Pack NuGet randomly fails

change/react-native-windows-2019-10-23-19-30-05-auto-update-versions060.0microsoft.11.json, change/react-native-windows-extended-2019-10-23-19-30-07-auto-update-versions060.0microsoft.11.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
291a1a290 Applying package update to 0.60.0-microsoft.11 ***NO_CI***
484b8439b fix publish
1f2edb5ce Applying package update to 0.60.0-microsoft.10 ***NO_CI***
d7cf27236 Publish fix
41baf57bb Fix publish
ba1b2e9a9 Add support for registering custom fonts by family+weight (#179)
```
=> Update to react-native@0.60.0-microsoft.11

README.md
* `[Windows 10 Compatibility]` link is broken on paragraph 54
* Compatability or Compatibility
=> Update URLs on React documentation

vnext/docs/NativeModules.md, vnext/docs/NativeModulesAdvanced.md, vnext/docs/ViewManagers.md
This change modifies and expands upon the documentation for Native Modules and View Managers.
The content is broken up into three pages:
1) View Managers
2) Native Modules
3) Native Modules (advanced topics)
=> Native Module/View Manager Docs

change/react-native-windows-2019-10-22-10-51-44-user-savatia-wiki-update.json, vnext/docs/ConsumingRNW.md
Updated the Docs to show how developers can use VS Code to run their application.
FIX #3455
=> Update VS Code debugging docs

change/react-native-windows-2019-10-24-11-39-55-ccdbg-0.0.0.41.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI.Desktop.UnitTests/packages.config, vnext/JSI/Desktop/JSI.Desktop.vcxproj, vnext/JSI/Desktop/packages.config
Version `0.0.0.41` includes a full PDB, solving in-place conversion that could hang deployment of build / test jobs in dependant projects.
=> Upgrade to ChakraCore.Debugger 0.0.0.41

change/react-native-windows-2019-10-24-17-13-17-x86runwindows.json, vnext/local-cli/runWindows/utils/msbuildtools.js
=> Run-windows fails on x86 machines

.ado/windows-vs-pr.yml
Disable debug flavor of desktop Integration testing #3519
For reference, here is a list of failed build jobs in the last few days:
https://dev.azure.com/ms/react-native-windows/_build?definitionId=210&_a=summary
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44326
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44320
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44318
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44286
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44254
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44178
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=44151
https://dev.azure.com/ms/react-native-windows/_build/results?bu …
=> Disable unstable debug flavor of desktop Integration testing

change/react-native-windows-2019-10-25-19-47-32-auto-update-versions060.0microsoft.12.json, change/react-native-windows-extended-2019-10-25-19-47-34-auto-update-versions060.0microsoft.12.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
b5e80390a Applying package update to 0.60.0-microsoft.12 ***NO_CI***
932a2b80c Copy over ios/mac header files that polyester references to fix the 0.60 merg… (#181)
```
=> Update to react-native@0.60.0-microsoft.12

change/react-native-windows-2019-10-25-12-57-29-users-stecrain-fixChakraPerf.json, vnext/JSI.Desktop.UnitTests/JsiRuntimeUnitTests.cpp, vnext/JSI/Shared/ChakraRuntime.cpp
getPropertyNames was refactored to take advantage of javascript so that all property names up the prototype chain (this matches the hermes behavior).
When looking into page nav performance in the app I am working on I noticed getPropertyNames was showing up as much more expensive than in the past, also quite a bit more recycler thread activity.
With the JS implementation of getPropertyNames the duration from by button press to xaml beginning layout is 2.2 seconds.
Swapping back to a native implementation reduced the time from button press to xaml layout to 1 second, as overall gain of 1.2 seconds for the scenario.
CPU samples in getPropertyNames dropped from 615 to 25
=> ChakraRuntime swap back to native implementation for getPropertyNames

change/react-native-windows-2019-10-26-01-48-30-auto-update-versions060.0microsoft.13.json, change/react-native-windows-extended-2019-10-26-01-48-32-auto-update-versions060.0microsoft.13.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
4e1e54177 Applying package update to 0.60.0-microsoft.13 ***NO_CI***
0c567f65b align with ios here and copy these to the same location on mac (#182)
```
=> Update to react-native@0.60.0-microsoft.13

change/react-native-windows-2019-10-25-19-39-55-remoteDbg.json, packages/playground/windows/playground/HostingPane.xaml.cpp, packages/playground/windows/playground/MainPage.xaml.cpp, packages/playground/windows/playground/MainPage.xaml.h, packages/playground/windows/playground/Package.appxmanifest, packages/playground/windows/playground/pch.h, vnext/ReactUWP/ABI/Instance_rt.cpp, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj.filters
Now you can pass  the hostname:port of a running metro bundler instance and it will connect correctly
Fixes #3534
=> Fix remote debugger for Playground app

change/react-native-windows-2019-10-28-14-38-36-jsiwithoss.json, package.json, vnext/ReactCommon/ReactCommon.vcxproj, vnext/Scripts/useUnForkedRN.js, vnext/package.json
There is more to do here, but we should try to get rid of all the OSS_RN #defines, and get alignment between the fork and non-fork -- at which point we can stop using the fork altogether.
=> Include JSI even when building against OSS RN

change/react-native-windows-2019-10-29-13-55-40-noRS5crash.json, vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp, vnext/ReactUWP/Views/ExpressionAnimationStore.cpp, vnext/ReactUWP/Views/ReactControl.cpp, vnext/ReactUWP/Views/ReactControl.h
Some animations are sensitive to the center point of the element (e.g. rotation, scale). We were using 0.5*ActualSize to determine the center point. However this facade property was only added in 19h1 so it Comp crashed in RS5 when trying to parse an expression animation that references ActualSize.
This change makes it so we fallback to using CenterPoint instead if ActualSize isn't available.
Fixes #2996
=> Fix crash in RS5 due to missing facade property

change/react-native-windows-2019-10-21-16-17-09-action.json, packages/E2ETest/app/AccessibilityTestPage.tsx, vnext/ReactUWP/ABI/idl/AccessibilityAction.idl, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/Views/DynamicAutomationPeer.cpp, vnext/ReactUWP/Views/DynamicAutomationPeer.h, vnext/ReactUWP/Views/DynamicAutomationProperties.cpp, vnext/ReactUWP/Views/DynamicAutomationProperties.h, vnext/ReactUWP/Views/FrameworkElementViewManager.cpp, vnext/ReactUWP/Views/ViewManagerBase.cpp, vnext/ReactUWP/Views/ViewViewManager.cpp, vnext/ReactUWP/Views/cppwinrt/AccessibilityAction.idl, vnext/ReactUWP/Views/cppwinrt/DynamicAutomationPeer.idl, vnext/ReactUWP/Views/cppwinrt/DynamicAutomationProperties.g.h, vnext/ReactUWP/Views/cppwinrt/winrt/impl/react.uwp.0.h, vnext/ReactUWP/Views/cppwinrt/winrt/impl/react.uwp.2.h, vnext/ReactUWP/Views/cppwinrt/winrt/react.uwp.h
fix #2765
add new AccessibilityActions: invoke, addToSelection, removeFromSelection, select, toggle, expand and collapse.
The following tasks are not in the scope of this PR, but they are related.
1. I did the test manually. Expect automation when #3473 is delivered.
2. The typescript for AccessiblityAction is not ready yet, and expect it be delivered in #3474
3. I applied a workaround in ABI/idl/AccessibilityAction, and it should be removed when implementing #2455
=> Implement AccessibilityActions

change/react-native-windows-2019-10-28-15-00-40-EnableIntegrationTestHarness.json, vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
Test is disable when investigating #3444, re-enable it.
=> Enable IntegrationTestHarness 

change/react-native-windows-2019-10-28-17-52-55-user-asklar-perspective.json, vnext/ReactUWP/Views/ReactControl.cpp
We need to set a perspective to match React Native's perspective, otherwise we get an orthographic projection
Fixes #3093
=> Set a default 3D perspective

change/react-native-windows-2019-10-31-17-50-35-auto-update-versions060.0microsoft.14.json, change/react-native-windows-extended-2019-10-31-17-50-36-auto-update-versions060.0microsoft.14.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
37cb19c8c Applying package update to 0.60.0-microsoft.14 ***NO_CI***
7c119ba8f Console.assert doesn't exist in the simulator, so this will always re… (#184)
```
=> Update to react-native@0.60.0-microsoft.14

change/react-native-windows-2019-10-31-23-56-14-user-asklar-callbacks.json, vnext/ReactUWP/Modules/Animated/AnimationDriver.cpp, vnext/ReactUWP/Modules/Animated/AnimationDriver.h, vnext/ReactUWP/Modules/Animated/NativeAnimatedNodeManager.cpp, vnext/ReactUWP/Modules/Animated/NativeAnimatedNodeManager.h, yarn.lock
After enabling native animations, Outlook is running into cases where a "finished animation" callback is called more than once. Looking at the code it's pretty clear this is because when stopping an animation, we call it with completed=false, and then try to mark the animation as completed but that function call tries to call the callback again with completed=true this time.
Fixes #2981
=> Call native animation callbacks only once

change/react-native-windows-2019-11-01-13-56-29-moveScriptStore.json, vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h, vnext/JSI/Shared/ChakraRuntime.cpp, vnext/JSI/Shared/ChakraRuntimeArgs.h, vnext/JSI/Shared/JSI.Shared.vcxitems, vnext/JSI/Shared/JSI.Shared.vcxitems.filters, vnext/JSI/Shared/RuntimeHolder.h, vnext/JSI/Shared/ScriptStore.h, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactCommon/ReactCommon.vcxproj.filters, vnext/ReactUWP/Utils/UwpPreparedScriptStore.h, vnext/ReactUWP/Utils/UwpScriptStore.h, vnext/ReactWindowsCore/BaseScriptStoreImpl.h, vnext/ReactWindowsCore/ChakraRuntimeHolder.h, vnext/Shared/OInstance.cpp
This PR moves ScriptStore and RuntimeHolder from RN to RNW. See also https://github.com/microsoft/react-native/pull/185.
=> Move ScriptStore and RuntimeHolder from RN to RNW.

change/react-native-windows-2019-11-01-22-33-42-auto-update-versions060.0microsoft.15.json, change/react-native-windows-extended-2019-11-01-22-33-43-auto-update-versions060.0microsoft.15.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
3c4fb8565 Applying package update to 0.60.0-microsoft.15 ***NO_CI***
bce68a390 Remove RuntimeHolder and ScriptStore. (#185)
```
=> Update to react-native@0.60.0-microsoft.15

change/react-native-windows-2019-11-06-04-25-44-auto-update-versions060.0microsoft.16.json, change/react-native-windows-extended-2019-11-06-04-25-46-auto-update-versions060.0microsoft.16.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/Chakra/ChakraExecutor.cpp, vnext/Chakra/ChakraExecutor.h, vnext/Chakra/ChakraHelpers.cpp, vnext/Chakra/ChakraInstanceArgs.h, vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp, vnext/Desktop/Executors/WebSocketJSExecutor.cpp, vnext/Desktop/Executors/WebSocketJSExecutor.h, vnext/Desktop/Sandbox/SandboxJSExecutor.cpp, vnext/Desktop/Sandbox/SandboxJSExecutor.h, vnext/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp, vnext/ReactUWP/Executors/WebSocketJSExecutorUwp.h, vnext/ReactWindowsCore/DevSettings.h, vnext/Shared/OInstance.cpp, vnext/package.json, yarn.lock
We're going to move to a new design for bytecode caching/prepared scripts when moving to JSI. In the meantime, we can reuse most of the existing ChakraExecutor bytecode and script versioning logic. Pass this association in as a map to DevSettings instead of piping it through each call.
This is pretty quick and dirty since we plan to jettison the ChakraExecutor stack soon.
=> Move bytecodeFilename and scriptVersion Determination to the Executor

change/react-native-windows-2019-11-05-08-53-09-JSI_REF.json, change/react-native-windows-extended-2019-11-05-17-48-17-JSI_REF.json, change/rnpm-plugin-windows-2019-11-05-17-48-17-JSI_REF.json, change/rnpm-plugin-wpf-2019-11-05-17-48-17-JSI_REF.json, vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI/Desktop/JSI.Desktop.vcxproj, vnext/JSI/Universal/JSI.Universal.vcxproj, vnext/PropertySheets/React.Cpp.props, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactCommon/ReactCommon.vcxproj.filters, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactUWP/packages.config, vnext/ReactWindowsCore/HermesRuntimeHolder.h, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/ReactWindowsCore/V8JSIRuntimeHolder.h, vnext/ReactWindowsCore/packages.config, vnext/V8Inspector/V8Inspector.vcxproj
This change will enable the following,
1. Centralized control of V8 and Hermes package versions
2. Allowing RNW to consume alternate JSI headers and sources. Currently, we include the JSI source along with the V8 and Hermes packages .. This change will ensure that we use the right version of JSI source when consuming these packages.
=> Allowing RNW to refer to alternate JSI truths

change/react-native-windows-2019-11-06-16-45-50-vmcommands.json, packages/microsoft-reactnative-sampleapps/index.windows.js, packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/DebugConsole.h, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.h, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/DebugHelpers.cpp, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/DebugHelpers.h, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj.filters, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/CustomUserControlViewManagerCS.cs, vnext/Microsoft.ReactNative.SharedManaged/AttributedViewManager.cs, vnext/Microsoft.ReactNative/ABIViewManager.cpp, vnext/Microsoft.ReactNative/IViewManager.idl, vnext/Microsoft.ReactNative/ReactSupport.cpp, vnext/docs/NativeModules.md, vnext/docs/ViewManagers.md
* Added command to CustomUserControlViewManagerCPP, #3600
* Added support for simpler C# view manager commands signatures
* Added support for object properties for view managers, #3613
* Added documentation for C++ view manager
* Added documentation for ViewManager commands, #3599
=> ViewManager Command Updates

.ado/templates/e2e-test-job.yml, .ado/windows-vs-pr.yml
A temporary workaround for #3611
currently the official nodejs is 12, but we have problem to work with it.
Force to use nodejs 10 in pipeline.
=> Use node10

.ado/shouldSkipPRBuild.ps1
Fixes (#3427 ) 
Whitelists .png/.gif/.jpeg file types for CI build.
=> Skips CI build for gif/png/jpeg (#3427)

change/react-native-windows-2019-11-11-12-58-16-flyout-centering-workaround.2.json, vnext/ReactUWP/Views/FlyoutViewManager.cpp
When using FlyoutPlacementMode::Full on a Flyout with an embedded Picker, the flyout is not centered correctly.  This issue is described in https://github.com/microsoft/react-native-windows/issues/2969.
This PR resolves the problem for flyouts with fixed size content by adjusting the flyout presenter max size settings (FlyoutShadowNode::AdjustDefaultFlyoutStyle) to match the content prior to layout (eg prior to the call to FlyoutViewManager::SetLayoutProps). 
This will unblock those scenarios while the work on a more exhaustive fix proceeds.
=> Workaround for flyout centering problem

change/react-native-windows-2019-11-12-01-54-17-auto-update-versions060.0microsoft.20.json, change/react-native-windows-extended-2019-11-12-01-54-19-auto-update-versions060.0microsoft.20.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
c164770cd Applying package update to 0.60.0-microsoft.20 ***NO_CI***
dac509cd7 Add a mac test plan to improve our confidence in fixes going into RN moving forward. Check for safe memory usage and concurrency problems (#190)
c610b2e93 Applying package update to 0.60.0-microsoft.19 ***NO_CI***
b917a64fe Enable mac yml tests (#189)
03e2b9974 Applying package update to 0.60.0-microsoft.18 ***NO_CI***
1694a6fa8 Preparing work for adding JSI and TurboModule to ReactCommon in Microsoft/react-native-windows (#191)
55c5835fe Applying package update to 0.60.0-microsoft.17 ***NO_CI***
ea7767a21 Add memory management and concurrency tests plans to our fork of Reac… (#186)
```
=> Update to react-native@0.60.0-microsoft.20

change/react-native-windows-2019-11-07-15-51-09-master.json, vnext/Desktop/DevSupportManager.cpp
This function will currently catch all exceptions and return their message as valid Javascript. This causes havock later. E.g. running RNTester tests without a server will fail, with an Executor being told to load the JS string "Connection refused". We should throw as early as possible instead of propagating the error to a later hard-to-debug point.
=> Do not eat exceptions in DevSupportManager::GetJavaScriptFromServer

.lintstagedrc.json, package.json, packages/scripts/formatFiles.js, yarn.lock
Rules are based on formatFiles.js script. A directory exclusion was part of the script where the directory doesn't seem to exist, so this was removed. Tested we format .cpp and .h files in root and vnext directory, and verified we do not format files ending with .g.h or .g.cpp.
=> Use "lint-staged" to run clang-format as pre-commit hook

change/react-native-windows-2019-11-14-09-55-26-sticky.json, packages/playground/Samples/view.tsx, vnext/ReactUWP/Views/ViewPanel.cpp
#3549 
#3488 
#3661 
RNW implementation of ViewPanel sometimes create outer border instead of using the inner border, for example when round corner border is requested. This is causing noticeable layout issue especially when border size is large. RN's yoga layout sets the Top/Left for each children, but Yoga has no notion of outer border(in its view, border is always part of the view instead of parent of view), and its placement logic includes the border size. So we need to compensate the outer border size when ViewPanel is arranging its children, by deducting the border size from the Top and Left.
When testing, I also found children clipping issue when outer border is present, so fix that too.
=> Fix ViewPanel layout issue when outer border exists

change/react-native-windows-2019-11-21-00-39-16-auto-update-versions060.0microsoft.23.json, change/react-native-windows-extended-2019-11-21-00-39-18-auto-update-versions060.0microsoft.23.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
66f182eec Applying package update to 0.60.0-microsoft.23 ***NO_CI***
4d057af9c Revert an RTL change we made that FB fixed at a lower level, making this obsolete. This file now aligns with what FB has in their repo (#194)
```
=> Update to react-native@0.60.0-microsoft.23

change/react-native-windows-2019-11-20-15-34-16-master.json, vnext/ReactUWP/Base/UwpReactInstance.cpp
`AsyncStorageModule` uses `AsyncStorageManager`, which uses `KeyValueStorage`, which uses `StorageFileIO`, which uses `Windows.Storage.StorageFile`, which can only be used from processes with package identity (either UWP apps, or Desktop Bridge apps packaged in an MSIX).
Without this change, creating an instance of `UwpReactInstance` from a classic desktop app would cause an exception to be raised & terminate the app. With it, classic desktop apps can create an instance of `UwpReactInstance`, although `asyncStorage` won't work.
@dotnetjunky, can you please verify that, with this change, your unpackaged version of TodoFeed works correctly?
=> Don't add asyncStorage module to nativeModules if ReactUWP is running without package identity

change/react-native-windows-2019-11-15-16-31-57-keyboardDismissMode.json, vnext/ReactUWP/Utils/Helpers.cpp, vnext/ReactUWP/Utils/Helpers.h, vnext/ReactUWP/Views/KeyboardEventHandler.cpp, vnext/ReactUWP/Views/ReactControl.cpp, vnext/ReactUWP/Views/SIPEventHandler.cpp, vnext/ReactUWP/Views/SIPEventHandler.h, vnext/ReactUWP/Views/ScrollViewManager.cpp
#3068 
-Hook up property keyboardDismissMode in ScrollViewManager.
-When manipulation starts and if keyboardDismissMode is on-drag, issue TryHide though SIP event handler.
- Some tweak to SIP Event Handler code to be able to share in the RNW's code base, and call GetForUIContext instead of GetForCurrentView on newer build.
=> Support ScrollView keyboardDismissMode

change/react-native-windows-2019-11-22-11-19-51-revert-3665-keyboardDismissMode.json, vnext/ReactUWP/Utils/Helpers.cpp, vnext/ReactUWP/Utils/Helpers.h, vnext/ReactUWP/Views/KeyboardEventHandler.cpp, vnext/ReactUWP/Views/ReactControl.cpp, vnext/ReactUWP/Views/SIPEventHandler.cpp, vnext/ReactUWP/Views/SIPEventHandler.h, vnext/ReactUWP/Views/ScrollViewManager.cpp
Reverts microsoft/react-native-windows#3665
It crashed in latest inside build and have problem to GetForUIContext
```
if (Is19H1OrHigher()) {
// 19H1 and higher supports island scenarios
auto uiElement(xamlView.as<winrt::UIElement>());
m_coreInputView = winrt::CoreInputView::GetForUIContext(uiElement.UIContext());
} else {
m_coreInputView = winrt::CoreInputView::GetForCurrentView();
}
```
=> Revert "Support ScrollView keyboardDismissMode"

change/react-native-windows-2019-12-01-22-55-26-auto-update-versions060.0microsoft.24.json, change/react-native-windows-extended-2019-12-01-22-55-28-auto-update-versions060.0microsoft.24.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
eab20d458 Applying package update to 0.60.0-microsoft.24 ***NO_CI***
fe9ccbcbc Tomun/fixflow (#196)
3707a293f Stop beachball from publishing internally (#195)
```
=> Update to react-native@0.60.0-microsoft.24

current/docs/GettingStarted.md
To install a yarn package globally, the keyword `global` has to immediately follow `yarn` as per :https://yarnpkg.com/lang/en/docs/cli/global/
`yarn add global XXXX` won't install anything globally,
`yarn global add XXXX` will install the XXXX package globally, I just switched them to fix that command.
=> Update GettingStarted.md - fixed yarn command

.ado/templates/e2e-test-job.yml, .ado/windows-vs-pr.yml, change/react-native-windows-2019-12-03-13-48-52-enable-cfg-0.59.json, vnext/PropertySheets/React.Cpp.props
- Enable CFG by default for 0.59 release builds.
- react-native-cli does not work with node 12 right now. In master, we downgrade to node 10 before running PR tasks. This PR changes the 0.59 branch to match master's behavior.
=> Port Important Changes in master to 0.59

change/react-native-windows-2019-12-05-18-09-22-auto-update-versions060.0microsoft.26.json, change/react-native-windows-extended-2019-12-05-18-09-24-auto-update-versions060.0microsoft.26.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
99e819f63 Applying package update to 0.60.0-microsoft.26 ***NO_CI***
b6790b6d5 Adding the new jsiinspector shared module to the nuget package exported to office (#200)
d9a25c2d0 Applying package update to 0.60.0-microsoft.25 ***NO_CI***
e4db078ce Removed geolocation targets from nuspec as they are not longer in the repo.  Added <repository type="git" url="$repoUri$" commit="$commitId$" /> which is needed to record the relevent meta data about the publish.   Removed an obsolete comment. (#197)
```
=> Update to react-native@0.60.0-microsoft.26

vnext/docs/CONTRIBUTING.md
=> Minor grammatical corrections.

change/react-native-windows-2019-12-06-17-40-22-auto-update-versions060.0microsoft.28.json, change/react-native-windows-extended-2019-12-06-17-40-24-auto-update-versions060.0microsoft.28.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
8048a04db Applying package update to 0.60.0-microsoft.28 ***NO_CI***
c214b0ba3 Add 0.59-stable branch to PR build trigger (#202)
95c7e0fd9 Applying package update to 0.60.0-microsoft.27 ***NO_CI***
39ce8a726 Use $buildNumber$ token for NuGet (#198)
```
=> Update to react-native@0.60.0-microsoft.28

change/@office-iss-react-native-win32-2019-12-12-21-10-06-auto-update-versions060.0microsoft.31.json, change/react-native-windows-2019-12-12-21-10-06-auto-update-versions060.0microsoft.31.json, change/react-native-windows-extended-2019-12-12-21-10-07-auto-update-versions060.0microsoft.31.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-win32/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
```
7abd5c4cc Applying package update to 0.60.0-microsoft.31 ***NO_CI***
1f7dacc98 manually update our xcschemes to have our build action entries for dependent libraries (#207)
7fb5723a9 Applying package update to 0.60.0-microsoft.30 ***NO_CI***
45554f8ec Avoid throwing exceptions from native modules when the host activity … (#201)
a65c7af60 Adding the new jsiinspector shared module to the nuget package exported to office (#203)
0782a6eaf Applying package update to 0.60.0-microsoft.29 ***NO_CI***
9bd79f3b0 redo broken dependencies for the publish targets that sdx-platform needs to succeed (#206)
e4ffca271 Add 0.59-stable branch to PR build trigger (#202) (#204)
```
=> Update to react-native@0.60.0-microsoft.31

change/react-native-windows-2019-12-12-16-22-29-instanceSettings.json, vnext/Microsoft.ReactNative/ReactInstanceCreator.h
#3610 Update instance settings when user toggles debugger settings in debugger menu.
=> Fix toggle debugger setting issue with ReactApplication

change/react-native-windows-2019-12-13-11-33-23-PCHDelete.json, vnext/Directory.Build.targets
Will help on #3197 and fix #3620
cppwinrt generated huge .pch. This is an example to remove them from pipeline.
I didn't apply them to projects in packages. If we still see disk usage issue, we can apply it too.
ideas are from: https://github.com/microsoft/terminal/blob/a3f3cc823c786d7a217632b03f3cb9af83faeb6d/src/common.build.post.props#L42-L62
=> Delete .pch after build on pipeline

packages/microsoft-reactnative-sampleapps/.gitignore
Avoid untracked Bundle folder like below
```
PS D:\repo\react-native-windows> git status
On branch gitignore
Untracked files:
(use "git add <file>..." to include in what will be committed)
packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/Bundle/
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/Bundle/
```
=> ignore Bundle folder in sampleapps

change/react-native-windows-2019-11-25-11-54-34-updatedoc.json, vnext/docs/ConsumingRNW.md
=> Update document for removing ReleaseBundle and DebugBundle

change/rnpm-plugin-windows-2019-12-16-13-38-43-nugetver.json, current/local-cli/rnpm/windows/src/common.js
Fix #2808
For `expo init` and `expo eject` project, name is existing in app.json other than package.json.
Example output
```
D:\repo\AwesomeProject>react-native windows --template vnext
Reading application name from package.json...
Reading application name from app.json...
Reading react-native version from node_modules...
```
=> CLI reads name from app.json if it doesn't exist in package.json

.ado/windows-vs-pr.yml
Currently we have more than 20 parallel jobs, This will help to reduce the number of parallel jobs.
We don't need to build all the flavors for RNWUniversalPR because publish pipeline will redo anything.
This change exclude React.UWP from the nuspec in PR pipeline, and it still be able to catch the bugs which is caused by missing files which nuget required.
=> reduce build flavors for RNWUniversalPR 

.ado/windows-vs-pr.yml, .vscode/settings.json, change/@office-iss-react-native-win32-2019-12-18-14-17-59-fixupwin32.json, change/react-native-windows-2019-12-18-14-17-59-fixupwin32.json, packages/react-native-win32/.gitignore, packages/react-native-win32/README.md, packages/react-native-win32/docs/api/react-native-win32.md, packages/react-native-win32/docs/api/react-native-win32.touchablewin32.md, packages/react-native-win32/index.d.ts, packages/react-native-win32/index.js, packages/react-native-win32/index.js.map, packages/react-native-win32/just-task.js, packages/react-native-win32/package.json, packages/react-native-win32/src/Libraries/Components/Touchable/TouchableWin32.tsx, vnext/Shared/OInstance.cpp
Also included a couple of minor fixes from the initial react-native-win32 checkin.
=> SourceCode module should provide scriptURL when running livereload without webdebugger

change/react-native-windows-2019-12-20-12-01-31-0.59-vnext-stable.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def
This is needed for testability (internal CR using it out now). It's not ideal to add more exports, but we will always have to have some between instance interfaces. This is currently targeting 0.59-stable, with the intent to cherry pick into master right after.
=> Export ability to query names of loaded native modules

.ado/templates/e2e-test-job.yml, change/react-native-windows-2019-12-30-12-16-46-bundlecrash.json, vnext/PropertySheets/Bundle.Cpp.targets, vnext/PropertySheets/Bundle.targets
Fix #3810 
For the new project, Bundle\index.windows.bundle doesn't exist and it's not counted into `<None>` and `<Content>` when build the project.
Delay the injection until MakeBundle target is executed.
=> Add InjectBundleContent target

change/react-native-windows-2020-01-03-14-45-45-fix-subchannel-animation-reference.json, vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
Fixes #3493 
A copy/paste error meant that the wrong animation was being started for scaleX and scaleY animations.
=> Call StartAnimation on m_scaleCombined for ScaleX / ScaleY animations

packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
The Name property in the current Cpp sample library is kind of misleading: people would think that is the way to override the native module name. 
Update the sample to show the correct way to override: through the second parameter of REACT_MODULE.
=> Update SampleModuleCpp library to show how to override module name

change/react-native-windows-2020-01-07-16-17-58-image-svg.json, packages/playground/Samples/Microsoft-Logo.svg, packages/playground/Samples/image.tsx, vnext/ReactUWP/Views/Image/ReactImage.cpp, vnext/ReactUWP/Views/Image/ReactImage.h
#3573 
See here for the svg properties supported:
https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support
We don't currently have a good way to get the width and height off of the svg file, so for now you will need to set those through the Image's style. For the same reason, resizeMode is also not currently supported when using an svg as source.
=> Image - basic svg support

change/@office-iss-react-native-win32-2020-01-07-20-46-51-defork.json, change/react-native-windows-2020-01-07-13-47-46-defork.json, change/react-native-windows-2020-01-07-20-46-51-defork.json, change/react-native-windows-extended-2020-01-07-20-46-51-defork.json, packages/E2ETest/package.json, packages/microsoft-reactnative-sampleapps/package.json, packages/playground/package.json, packages/react-native-win32/.gitignore, packages/react-native-win32/package.json, packages/react-native-windows-extended/package.json, vnext/.gitignore, vnext/ReactCommon/ReactCommon.vcxproj, vnext/Scripts/copyRNLibraries.js, vnext/package.json, yarn.lock
1. Do some refactoring of copyRNLibraries.js to make it a bit less messy, and to allow some more flexibility.
2. Tell copyRNLibraries.js to copy a few headers to a jsireact folder to mimic BUCK build logic
3. Configure MSBuild to look in newly added WorkingHeaders directory
4. Add WorkingHeaders to gitignore
5. Update Microsoft RN version
6. Remove conditional compilation of JSI files on non-OSS RN, which we should no longer need
=> Header Refactoring Around jsireact to Unblock ms/rn

change/@office-iss-react-native-win32-2020-01-13-11-32-57-updaterex.json, packages/react-native-win32/package.json, yarn.lock
Updates rex-win32 to a version that doesn't crash running RNTester.
=> Update rex-win32 to fix boot of RNTester

Directory.Build.props, change/react-native-windows-2020-01-14-00-16-18-defork.json, change/react-native-windows-extended-2020-01-14-00-16-18-defork.json, packages/playground/windows/playground/Playground.vcxproj, packages/react-native-windows-extended/windows/react-native-windows-extended.vcxproj, vnext/Common/Common.vcxproj, vnext/DeforkingPatches/README.md, vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI/Desktop/JSI.Desktop.vcxproj, vnext/JSI/Universal/JSI.Universal.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/ReactPackageDirectories.props, vnext/PropertySheets/ReactPatches.targets, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/Scripts/Tfs/Layout-Headers.ps1, vnext/Scripts/copyRNLibraries.js, vnext/Universal.IntegrationTests/React.Windows.Universal.IntegrationTests.vcxproj, vnext/Universal.UnitTests/React.Windows.Universal.UnitTests.vcxproj, vnext/V8Inspector/V8Inspector.vcxproj
As part of the efforts to move off of microsoft/react-native, we're aiming to
consume facebook/react-native directly and then apply a set of Windows specific
patches. This change gives us a mechanism to do this patching.
We opt to fully modify React Native sources instead of manipulating
files/includes with build logic. This helps with header resolution and keeps
the rest of the build mostly unaware of the patching. Patching is done in the
projects intermediate output directory. This has a number of benefits but has
the unfortunate property that we will do patching separately for each vcxproj,
and have copies of patched react native for each. Some of this overhead is
mitigated by only copying C++ source files. Avoiding this would likely mean
outputting to a non-build directory or making …
=> Add React Native Source Patching Infrastructure

change/react-native-windows-2020-01-14-17-58-37-openssl-1.1.1d.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj, vnext/Desktop.Test.DLL/packages.config, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI.Desktop.UnitTests/packages.config, vnext/Scripts/OpenSSL.nuspec, vnext/Scripts/OpenSSL.targets, vnext/Scripts/Tfs/Layout-Headers.ps1, vnext/Test/React.Windows.Test.vcxproj, vnext/Test/packages.config
See https://www.openssl.org/blog/blog/2018/09/11/release111/
- Upgrading to the latest/current LTS. Current version 1.0.2 stopped being supported in 2020.
- TLS 1.3 support
- Updated cypher algorithm support
- **Drop reliance on heap walking for entropy** (random number generation).
=> Upgrade to OpenSSL 1.1.1d

change/react-native-windows-2020-01-14-17-58-20-openssl-1.1.1d-v0.59.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj, vnext/Desktop.Test.DLL/packages.config, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI.Desktop.UnitTests/packages.config, vnext/Scripts/OpenSSL.nuspec, vnext/Scripts/OpenSSL.targets, vnext/Scripts/Tfs/Layout-Headers.ps1, vnext/Test/React.Windows.Test.vcxproj, vnext/Test/packages.config
See https://www.openssl.org/blog/blog/2018/09/11/release111/
- Upgrading to the latest/current LTS. Current version 1.0.2 stopped being supported in 2020.
- TLS 1.3 support
- Updated cypher algorithm support
- **Drop reliance on heap walking for entropy** (random number generation).
=> [v0.59] Upgrade to OpenSSL 1.1.1d

change/react-native-windows-2020-01-15-20-42-29-master.json, vnext/Scripts/Tfs/Layout-Headers.ps1
CI machines pass an environment variable as a custom build property to
MSBuild in order to change intermediate build directory. Rely on this
environment variable if set.
=> Fix Layout-Headers on CI machines

.ado/windows-vs-pr.yml, change/react-native-windows-2020-01-15-22-58-18-master.json, vnext/Scripts/Tfs/Layout-Headers.ps1
Continue from #3887
Add a missing directory separator that wasn't in the env variable. ~Add
LayoutHeaders to a build flavor in the PR matrix so we can find this
earlier.~ (see update below)
=> Fix Layout-Headers for Publish Try 2

.ado/templates/e2e-test-job.yml, .ado/variables/vs2017.yml, .ado/variables/vs2019.yml
* Updating VS2019 VMs config to match VS2017 VM config for build output
* Setting runCodesignValidationInjection: false
=> Fix CI out of disk space issues, issue #3908

change/react-native-windows-2020-01-21-11-30-55-stubs.json, vnext/stubs/unistd.h
We're going to remove the OSS_RN preprocessor definition. In the world
of building against facebook/react-native we will always need this stub
for now. Remove the OSS_RN check, along with a comment which isn't
accurate. (We build multiple files including unistd.h still).
=> Remove OSS_RN Specialization in unistd.h Stub

change/react-native-windows-2020-01-21-11-07-50-warnings.json, vnext/ReactCommon/ReactCommon.vcxproj
microsoft/react-native has a couple of fixes for integer conversion
warnings. It's not worth bringing this over as patches when we move
to facebook/react-native. Add specific supressions to the affected
files. We should upstream fixes eventually if they have not been fixed
in facebook master.
Validated we build when using open source react native.
=> Remove OSS_RN Specific Warnings

change/react-native-windows-2020-01-22-14-20-29-fix-reactpackagedirs.json, vnext/PropertySheets/ReactPackageDirectories.props
For whatever reason, on my machine, when `$([MSBuild]::NormalizeDirectory()` is called on these relative paths, it normalizes them using `%system32%` as the root. Weird.
I'm reasonably sure there's no need to call `NormalizeDirectory()`; my local builds definitely work fine without it. Guess we'll see what the PR CI loops do!
=> Don't call NormalizeDirectory on YogaDir and ReactNativeDir

change/react-native-windows-2020-01-22-16-03-11-follywarnings.json, vnext/Folly/Folly.vcxproj, vnext/FollyWin32/FollyWin32.vcxproj
We always donwload Folly. Do not show a warning when doing so, and do
not reference microsoft/react-native which will be retired soon. Ensure
we download Folly before building FollyWin32, since we do not have that
explicit dependency right now.
Tested by building FollyWin32 after removing the node_modules .folly
directory. We still get all the warnings from unzipping, which we will
have to live with until upgrading our tooling to a newer MSBuild.
=>  Update Folly Build Logic

change/react-native-windows-2020-01-22-19-17-54-master.json, vnext/DeforkingPatches/ReactCommon/cxxreact/NativeToJsBridge.h, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/React.Cpp.props, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactUWP/ReactUWP.vcxproj, vnext/ReactWindowsCore/ReactWindowsCore.vcxproj, vnext/Shared/OInstance.cpp, vnext/Universal.IntegrationTests/UniversalTestRunner.cpp
1. Update NativeToJSBridge.h with a fix that was incorporated into
Facebook master instead of our current fix.
2. Remove `ENABLE_NATIVE_SYSTRACE_TO_ETW`. We don't check it in RNW or
micosoft/react-native.
3. Remove conditional definition of `ENABLE_ETW`_TRACING for non-OSS React
Native. We can build it just fine, since the patch we had was to fix an
error exposed when `WITH_FBSYSTRACE` is defined.
4. Enable `ENABLE_JS_SYSTRACE_TO_ETW` in patched OSS RN
5. Consolidate preprocessor definitions to React.cpp.props.
`WITH_FBSYSTRACE` is checked in Facebook headers, meaning projects
including Facebook headers that didn't copy the definitions may get
mismatched headers. We should expose the definition to more projects to
prevent this.
6. Remove conditional compilation of logMarker, since it …
=> Logging and Tracing OSS_RN Removal 

.ado/templates/e2e-test-job.yml, .ado/windows-vs-pr.yml
Fix #3953. This is not a perfect solution which would delete the android folder on C drive this project doesn't need, but it introduced 6 minutes more to E2E test pipeline.
=> Enable e2e-test-job

.github/ISSUE_TEMPLATE/react-native-windows--vnext--bug-report.md
Customer reported the build error of `react-native run-windows`, but most of time, it's not enough for troubleshooting. asking for it in bug template.
=> Asking for 'react-native run-windows --logging' for build error

change/react-native-windows-2020-01-28-15-57-10-master.json, vnext/DeforkingPatches/ReactCommon/yoga/yoga/YGStyle.h, vnext/PropertySheets/React.Cpp.props
CLI projects use upstream React Native. A Yoga issue with MSVC around enum bitfields was documented to be fixed in 0.60.2 (facebook/react-native@a7e4ce0) but we still seem to run into issues. Keep the preprocessor definition to disable them.
We seem to still need the definition regardless. Make sure we define it. This is added pretty globally, since it affects headers that can be included across the solution.
=> Fix Crash When Running CLI Projects

change/react-native-windows-2020-01-28-20-28-04-0.59-vnext-stable.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj, vnext/Desktop.Test.DLL/packages.config, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI.Desktop.UnitTests/packages.config, vnext/Test/React.Windows.Test.vcxproj, vnext/Test/packages.config
Updates the OpenSSL static library to be linked into the React Windows Desktop DLL.
See introduced  changes:
https://github.com/jurocha-ms/openssl/compare/6539cd3069a8148c36cb187b7e62722971db34a9...jurocha-ms:bd711e537cc6afab0c295ad81d9728ec7ee6c51d
=> Upgrade OpenSSL NuGet to 1.1.1 d.3

change/@office-iss-react-native-win32-2020-01-29-14-19-59-animated-interpolation.json, change/react-native-windows-2020-01-29-22-33-01-animated-interpolation.json, packages/react-native-win32/.flowconfig, packages/react-native-win32/src/Libraries/Animated/src/nodes/AnimatedInterpolation.win32.js, vnext/.flowconfig, vnext/src/Libraries/Animated/src/nodes/AnimatedInterpolation.windows.js, vnext/src/Libraries/Color/NativeOrDynamicColorType.windows.js
react-native win32 may use non-integer color types. Bring in the
microsoft/react-native version of AnimatedInterpolation that knows how
to deal with this. Upstreaming is tracked by #3984
=> Add Overrides for AnimatedInterpolation and NativeOrDynamicColor

change/react-native-windows-2020-01-29-12-59-19-kinhln-chakra-error.json, vnext/Shared/OInstance.cpp
When there is a JS error, it's useful to see the callstack in the native host app. I'm appending the callstack to the default error message when reporting the error to the host app.
=> Add callstack to the error message when a JS error occurs.

change/react-native-windows-2020-01-30-09-32-57-didaReactContext.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h, vnext/Microsoft.ReactNative/IReactContext.cpp, vnext/docs/NativeModulesSetup.md
- ReactContext.DispatchEvent should support null input for eventDataArgWriter instead of crash, when event has no data payload.
- Add a writer helper function for export custom direct event type constants.
=> Simple fix to IReactContext.cpp and add a writer helper function for direct event type constant

change/@office-iss-react-native-win32-2020-01-30-14-09-45-looser-resolution.json, change/react-native-windows-2020-01-30-14-09-45-looser-resolution.json, change/react-native-windows-extended-2020-01-30-14-09-45-looser-resolution.json, packages/react-native-win32/package.json, packages/react-native-windows-extended/package.json, vnext/package.json
Internally, we will have some xplat Javascript that declares the
microsoft version of react-native as a dependency. This JS will be stuck
on 0.60 for some time, as we depend on MacOS support. This will keep us
on a stable branch of react-native-windows as it moves to 0.61.
Loosen peer dependency requirements of react-native-windows to allow
prerelease versions of react-native beyond a specific microsoft
version. This should allow us to rev sdx-platform to newer versions
without changing react-native-windows.
Confirmed that the setRNVersion script used by evergreen won't overwrite
this structure, since it just does a regex replace of
"0.x.x-microsoft.x".
=> Allow Any Prerelease Version of 0.60 as Peer Dependency

.ado/publish.yml
We forked a stable version of 0.60, but are not yet quite on 0.61. Avoid
publishing from our master branch until we're on 0.61 to avoid version
collisions from changes in 0.60-stable and changes in master on 0.60.
Disable publishing on some old branches while we're here that haven't
been updated for a while and nobody should be adding new changes to.
=> Publish changes for 0.60-stable instead of master

change/rnpm-plugin-windows-2020-01-30-13-37-04-npmcli.json, current/local-cli/rnpm/windows/package.json, current/local-cli/rnpm/windows/src/common.js, current/local-cli/rnpm/windows/src/windows.js
Fixes #3862
rnpm-plugin-windows was using a dependency that it wasn't declaring.  Rather than having rnpm declare a specific react-native-community\cli dependency, which can cause issues since different RN versions require different versions of the CLI.  I changed the dependency to use another package.
This also changes the CLI to only prompt the vnext/legacy prompt when used against RN 0.59.  Since thats the only version that has a good legacy and vnext version.
If the user it using >=0.60 we will automatically use the vnext version.
=> rnpm-plugin-windows fails when using npm

change/react-native-windows-2020-01-30-21-53-47-MS_Fix_Mso_UnitTest_Release.json, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
It fixes compile break in Release mode caused by wrong PCH creation configuration.
=> Fix Mso.UnitTest project for Release mode

change/@office-iss-react-native-win32-2020-01-31-02-51-25-flow-suppressions.json, change/react-native-windows-2020-01-31-02-51-25-flow-suppressions.json, packages/react-native-win32/.flowconfig, vnext/.flowconfig
For where we really, really, don't care. One category is schema files that aren't bundled. Another is deprecated JS that doesn't use Flow.
=> Add Flow Check Suppressions

change/react-native-windows-2020-01-31-11-55-07-exportloadscript.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def
Export loadScriptFromString from react-native-win32
=> Add missing export needed for react-native-win32

change/react-native-windows-2020-01-31-17-25-09-exportgetmoduleregistry.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def
Another method that office is using that needs to be exported so we can ingest latest version of react-native-win32.
=> Export Instance->getModuleRegistry from react-native-win32.dll

.ado/windows-vs-pr.yml
We must be able to run unit tests in vnext CI loops.
Currently we cannot compile our unit tests for x86 because VS lib files for GTest use cdecl calling conventions while our code is compiled with stdcall calling conventions. As a result we see a lot of linker errors. But we can compile our tests for x64.
The issue is that our CI loop does not compile x64 code...
In this change we are enabling the x64debug configuration that should allow us to start running unit tests.
=> Enable X64Debug CI configuration

change/react-native-windows-2020-02-06-14-30-19-MS_CppWinRT_HeapEnforcement.json, vnext/Microsoft.ReactNative/ABICxxModule.cpp, vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
This is to address issue https://github.com/microsoft/react-native-windows/issues/3807.
Previously the ReactRootView was created using std::make_shared and I guess it was the main reason to disable the C++/WinRT check that all C++/WinRT objects are allocated on the heap instead of stack.
The ReactRootView behavior was changed in https://github.com/microsoft/react-native-windows/pull/4022 . We do not use the old ReactRootView from ReactUWP anymore and instead ReactRootView is a pure XAML control, while the other part that we named ReactRootControl is not C++/Winrt based.
In this change:
- We removed the C++/WinRT heap enforcement suppression from project files.
- Fixed code that stopped to compile due to the heap enforcement. These were most probably bugs that would show only for …
=> Enable C++/WinRT heap enforcement

change/react-native-windows-2020-02-06-17-37-00-master.json, vnext/Chakra/ChakraNativeModules.cpp, vnext/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp, vnext/ReactWindowsCore/Modules/UIManagerModule.cpp, vnext/ReactWindowsCore/ShadowNodeRegistry.cpp
- Compilation fails with Clang as certain imports are missing
- I assume those are pre-defined when using MSVC
- #include <sstream> is needed for std::stringstream stream;
- #include <glog/logging.h> is needed for CHECK() MARCO
=> Fix compilation errors with LLVM9.0.1/clang due to missing #includes

change/react-native-windows-2020-02-06-10-15-05-accessibilityLiveRegionFix.json, vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
Fix for #3783.
Enables screen reader announcements when using an accessibilityLiveRegion. FrameworkElementViewManager already has code for handling an accessibilityLiveRegion announcement, but is currently filtering it out due to GetNativeProps not having an entry for it. This change adds that to the list of native props so that the existing code that responds when the accessibilityLiveRegion changes actually executes.
The existing code in question is in the same file under this if statement:
`else if (propertyName == "accessibilityLiveRegion")`
=> Enable screen reader announcements for accessibilityLiveRegion

.ado/windows-vs-pr.yml
This is an attempt to enable running unit tests for Universal x64 Debug configuration.
In this change I only add a test for Microsoft.ReactNative.Cxx.UnitTests.
If it works then more unit tests are going to be added.
=> Run Universal x64Debug unit tests

packages/react-native-win32/proposals/FocusTracking.md
Adding a proposal to react-native-win32 for focus tracking
Tracking focus in a more comprehensive way cleans up a lot of problems are partners have.. Putting this here, trying to get in the habit of keeping proposals here.
=> Add focus tracking proposal

packages/playground/windows/playground/App.xaml, yarn.lock
=> Set playground to use Light app theme

change/react-native-windows-2020-02-11-12-03-45-touchable-focus-blur-events.json, packages/E2ETest/app/Consts.ts, packages/E2ETest/app/TextInputTestPage.tsx, packages/E2ETest/wdio/pages/TextInputTestPage.ts, packages/E2ETest/wdio/test/testInput.spec.ts, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
Fixes #3927. 
TextInput's onFocus and onBlur callbacks are not functioning, this is because we [wrapped RCTTextInput in a TouchableWithoutFeedback](https://github.com/microsoft/react-native-windows/blob/master/vnext/src/Libraries/Components/TextInput/TextInput.windows.js#L1013-L1025), and onFocus onBlur were [overridden by TouchableWithoutFeedback](https://github.com/microsoft/react-native-windows/blob/master/vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js#L345-L346).
To fix this we should let [OVERRIDE_PROPS](https://github.com/kaiguo/react-native-windows/blob/38bc6cad5c3cdd7d1e00ac0e3a7185e12a2fa381/vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js#L313-L316) do the work and just copy the rest of the children props to parent.
=> Let children onFocus onBlur events in TouchableWithoutFeedback pass through to parent

change/react-native-windows-2020-02-11-10-24-03-MS_AsyncMethod_Tests.json, packages/microsoft-reactnative-sampleapps/index.windows.js, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h, packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs, vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueReaderTest.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h, vnext/Microsoft.ReactNative.Cxx/Crash.h, vnext/Microsoft.ReactNative.Cxx/JSValue.h, vnext/Microsoft.ReactNative.Cxx/JSValueTreeWriter.cpp, vnext/Microsoft.ReactNative.Cxx/JSValueTreeWriter.h, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h, vnext/Microsoft.ReactNative.Cxx/ModuleMemberRegistration.h, vnext/Microsoft.ReactNative.Cxx/NativeModules.h, vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp, vnext/Microsoft.ReactNative.Cxx/ReactPromise.h, vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs, vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs, yarn.lock
This PR addresses issue https://github.com/microsoft/react-native-windows/issues/4046
The question was if the native module methods support asynchronous code.
The issue was that previously we had a bug that JSValue writer was created on call stack and was crashing for asynchronous code. It was fixed by PR https://github.com/microsoft/react-native-windows/pull/4045 . In This PR I wanted to add unit tests that verify that. The C# tests were simple, but for C++ we had to do more changes:
- Enable use of co-routines and thus allow fire_and_forget method return type.
- Change implementation of ReactPromise to allow it to be copied to a different thread.
- Change test mock environment to enable use of  the async code
=> Added async code to native module test methods

change/react-native-windows-2020-02-07-15-55-25-ScrollIndicatorFix.json, vnext/ReactUWP/Views/ScrollViewManager.cpp
Fix for #4060 
The behavior of the horizontal and vertical scroll bars was to always be visible. This changes that so that they are visible automatically when required, but are not shown when not required based on the size of the content in the scrollview.
=> Fix scroll indicators being shown when not required

change/react-native-windows-2020-02-12-11-56-02-MS_FixDevMenu.json, vnext/Microsoft.ReactNative/ABICxxModule.cpp, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/Modules/AppStateData.cpp, vnext/Microsoft.ReactNative/Modules/AppStateData.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Microsoft.ReactNative/Threading/BatchingQueueThread.cpp, vnext/Mso/src/dispatchQueue/looperScheduler.cpp, vnext/ReactUWP/Base/CoreNativeModules.cpp, vnext/ReactUWP/Base/CoreNativeModules.h, vnext/ReactUWP/Base/UwpReactInstance.cpp, vnext/ReactWindowsCore/IUIManager.h, vnext/ReactWindowsCore/Modules/UIManagerModule.cpp, vnext/ReactWindowsCore/Modules/UIManagerModule.h
As a part of implementing new ReactNativeHost I have broke the dev menu and live reload functionality: https://github.com/microsoft/react-native-windows/issues/4072.
The initial fix was easy: in ReactNativeHost.cpp we just had to copy previously missed settings EnableDeveloperMenu and UseLiveReload. But after that we started to see more issues mostly because the new ReactInstance is managed in a background thread instead of UI thread. To address these issues we also had to:
- Make sure that we do not capture 'this' in ABICxxModule.
- Create new safer AppState component that subscribes to and unsubscribes from events in UI thread. The new AppState can be created in a background thread now.
- Remove std::terminate from BatchingQueueThread::quitSynchronous - it is called from the OInstance …
=> Fixed Developer menu and Live Reload

change/react-native-windows-2020-02-13-08-27-44-master.json, vnext/PropertySheets/React.Cpp.props
Issue #4099 showed a user unable to build due to MSVC interpreting source code using the Simplified Chinese character set. This is due to MSVC behavior of interpreting source files using the user's locale-defined character set if a BOM isn't present. This change instructs MSVC to fall-back to UTF-8 instead.
I wasn't able to locally reproduce the issue with changing Windows settings to simplified Chinese as a default, so I'm not sure which locale factors lead to determining chosen character set. This fix should theoretically avoid the issue entirely though.
Validated we can build the Universal solution. Will rely on CI to catch anything else.
See https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2019 for more context
=> Force Interpretation of Code as UTF-8 When no BOM Present

change/react-native-windows-2020-02-14-12-49-08-deps-openssl-revertto102p.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj, vnext/Desktop.IntegrationTests/packages.config, vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj, vnext/Desktop.Test.DLL/packages.config, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/packages.config, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/packages.config, vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj, vnext/JSI.Desktop.UnitTests/packages.config, vnext/Test/React.Windows.Test.vcxproj, vnext/Test/packages.config
Current fork of version `1.1.1d` is not yet stable.
See #4096 for follow-up.
=> Downgrade OpenSSL to version 1.0.2p

change/react-native-windows-2020-02-18-17-30-23-networking-assert.json, vnext/ReactUWP/Modules/NetworkingModule.cpp
Workaround for #2460 while we implement the param.
=> Remove useIncrementalUpdates assert from Networking module

README.md
This channel doesn't seem to exist in the linked Discord anymore.
I'm not sure the right replacement, but #react-native (which does exist) seems reasonable enough.
=> Remove reference to #react-native-platforms

.ado/npmAddUser.js, .ado/templates/react-native-init.yml, .ado/verdaccio/config.yaml, .ado/waitForVerdaccio.js, .ado/windows-vs-pr.yml, change/react-native-windows-2020-02-19-16-14-22-verdaccio.json
Fixes #3846 
We've said we needed proper publish validation for a while, and there was a recent break in publishing that would have been caught by this.
Also in the process of this work, I notice that we actually have not been testing init at all with the 0.61 update, as the init test was testing that you could init a new 0.60 project.  -- Kind of crazy that that was working using react-native 0.60, and react-native-windows 0.61.  -- But that speaks as much to the need to expand the testing on the init project as anything else (ideally we'd add E2E testing on the init'd project.. but thats out of scope for this change)
=> Use verdaccio to validate react native init

change/react-native-windows-2020-02-19-17-21-37-MS_NoEmptyModule.json, vnext/Microsoft.ReactNative/ABICxxModule.cpp, vnext/Shared/OInstance.cpp
This PR addresses one of the most common issues developers see when JS code calls wrong C++ module method. 
Modules without constants and methods are returning empty configuration from the module registry. Then, the code in OInstance.cpp was not adding module with empty configuration to the configArray. Since native modules are invoked by the array index, the mismatch between module list in the ModuleRegistry and the configArray sent to JS engine causes wrong native module be invoked.
To fix the issue we changed code in OInstance.cpp to match RCTObjcExecutor.mm where nullptr is added to configArray for empty configs.
=> Avoid having native modules without methods

change/react-native-windows-2020-02-19-10-20-40-storagefix.json, vnext/ReactWindowsCore/AsyncStorage/KeyValueStorage.cpp, vnext/ReactWindowsCore/AsyncStorage/KeyValueStorage.h, vnext/Shared/AsyncStorage/StorageFileIO.cpp, vnext/Shared/AsyncStorage/StorageFileIO.h
#3579 
#3392 
Issue #1:  After storage file is updated, the content of the change does not gets flushed to disk until fclose is called. flocse only happens when asyncStorage module is released. This can leads to data loss or corruption, for example app is shutdown abnormally. To fix it, we call fflush every time after updates are made.
Issue #2: There is a 30 seconds wait for each key value pair I/O operation on the the async load of the storage file content. One of the error path of load throws exception but does not set the load complete event which can cause I/O operation to stuck until 30 seconds wait timed out. We should also set the load complete event before throwing the exception.
Issue #3 The asyncStorage module has a behavior where multiple updates to same key are all written to …
=> Fix some reliability isssues for current AsyncStorage implementation

change/react-native-windows-2020-02-07-15-55-25-ScrollIndicatorFix.json, vnext/ReactUWP/Views/ScrollViewManager.cpp
To bring this into the 0.60 branch.
=> Fix scroll indicators being shown when not required (#4061)

change/react-native-windows-2020-02-11-12-03-45-touchable-focus-blur-events.json, packages/E2ETest/app/Consts.ts, packages/E2ETest/app/TextInputTestPage.tsx, packages/E2ETest/wdio/pages/TextInputTestPage.ts, packages/E2ETest/wdio/test/testInput.spec.ts, vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
To bring this into the 0.60 branch.
=> Let children onFocus onBlur events in TouchableWithoutFeedback pass through to parent (#4078)
