ReactWindows/ReactNative.Tests/Bridge/CatalystInstanceTests.cs
ReactWindows/ReactNative.Tests/Bridge/Queue/MessageQueueThreadTests.cs
ReactWindows/ReactNative.Tests/Internal/AssertEx.cs
ReactWindows/ReactNative.Tests/Internal/DispatcherHelpers.cs
ReactWindows/ReactNative.Tests/Internal/MockCatalystInstance.cs
ReactWindows/ReactNative.Tests/Internal/MockJavaScriptExecutor.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Bridge/CatalystInstance.cs
ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
ReactWindows/ReactNative/Bridge/ICatalystInstance.cs
ReactWindows/ReactNative/Bridge/Queue/MessageQueueThreadExtensions.cs
ReactWindows/ReactNative/Properties/AssemblyInfo.cs

Currently requires InternalsVisibleTo, we should go back and make this public and add doc comments (see #21).

Fixes #20 - adds unit tests for CatalystInstance

---

ReactWindows/ReactNative.Tests/Bridge/JavaScriptModuleRegistryTests.cs
ReactWindows/ReactNative.Tests/UIManager/Events/RCTEventEmitterTests.cs
ReactWindows/ReactNative/CoreModulesPackage.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/UIManager/Events/RCTEventEmitter.cs
ReactWindows/ReactNative/UIManager/Events/TouchEventType.cs
ReactWindows/ReactNative/UIManager/Events/TouchEventTypeExtensions.cs
ReactWindows/ReactNative/UIManager/PointerEvents.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.cs

Some remaining TODOs include integrating the constants from the view managers, and further investigation on how to include other features available in Android.

Fixes #32 - Adds UIManagerModule constants

---

ReactWindows/ReactNative.Tests/Hosting/Bridge/ReactBridgeTests.cs
ReactWindows/ReactNative/Bridge/CatalystInstance.cs
ReactWindows/ReactNative/Bridge/NativeModuleRegistry.cs
ReactWindows/ReactNative/Hosting/Bridge/ReactBridge.cs
ReactWindows/ReactNative/UIManager/OnLayoutEvent.cs
ReactWindows/ReactNative/UIManager/RootViewManager.cs
ReactWindows/ReactNative/UIManager/UIImplementation.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

The UI operations are queued up until all calls from the native modules thread have finished executing (so they can potentially be optimized into fewer calls). This changeset wires up the OnBatchComplete event from the ReactBridge and also implements a few of the remaining UIImplementation TODOs.
There are still TODOs surrounding measurement, layout and animation.

Towards #70 - Finishes up some of the UIImplementation and wires up OnBatchComplete

---

ReactWindows/ReactNative.Tests/Modules/Toast/ToastNotificationTests.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Modules/Toast/ToastHelper.cs
ReactWindows/ReactNative/Modules/Toast/ToastModule.cs
ReactWindows/ReactNative/ReactNative.csproj

adding ToastModule with tests

---

ReactWindows/ReactNative.Tests/Internal/MockCallback.cs
ReactWindows/ReactNative.Tests/Modules/AppState/AppStateModuleTests.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Modules/AppState/AppStateModule.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs

Emits events to JavaScript when the app is suspended / moved to background mode.

Fixes #131 - Adds AppStateModule

---

ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs
ReactWindows/ReactNative.Tests/Modules/Network/NetworkingModuleTests.cs
ReactWindows/ReactNative.Tests/Modules/Network/TaskCancellationManagerTests.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Collections/JObjectExtensions.cs
ReactWindows/ReactNative/Modules/Network/DefaultHttpClient.cs
ReactWindows/ReactNative/Modules/Network/HttpContentHeaderData.cs
ReactWindows/ReactNative/Modules/Network/HttpContentHelpers.cs
ReactWindows/ReactNative/Modules/Network/IHttpClient.cs
ReactWindows/ReactNative/Modules/Network/NetworkingModule.cs
ReactWindows/ReactNative/Modules/Network/TaskCancellationManager.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/UIManager/LayoutAnimation/LayoutAnimation.cs

Networking module currently supports string payloads and gzip, with options to send requests and cancel.
Still remaining work on file-based payloads, multi-part formdata, and cookies.

Fixes #180 - Adds NetworkingModule

---

ReactWindows/ReactNative.Tests/Internal/MockPromise.cs
ReactWindows/ReactNative.Tests/Modules/NetInfo/NetInfoModuleTests.cs
ReactWindows/ReactNative.Tests/Modules/Network/NetworkingModuleTests.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Bridge/ReactDelegateFactoryBase.cs
ReactWindows/ReactNative/Modules/NetInfo/DefaultNetworkInformation.cs
ReactWindows/ReactNative/Modules/NetInfo/IConnectionProfile.cs
ReactWindows/ReactNative/Modules/NetInfo/INetworkInformation.cs
ReactWindows/ReactNative/Modules/NetInfo/NetInfoModule.cs
ReactWindows/ReactNative/ReactNative.csproj

Currently, we are mimicking the iOS behavior for the NetInfoModule. Eventually, we can add other Windows specific features in the same way Android has.

Fixes #179 - Adds NetInfo module.

---

packager/blacklist.js
packager/react-packager/src/Resolver/index.js
website/server/extractDocs.js

Adds Windows features to the following:
- blacklist.js
- resolver/index.js
- extractDocs
No breaking changes

feat(add Windows support)

---

Libraries/Components/ScrollView/ScrollView.js
ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
ReactWindows/ReactNative/Views/View/ReactViewManager.cs

There is an issue with scroll view where the container view was being collapsed by the optimizer. Ensure the 'collapsable' property is picked up.
Fixes #143

fix(RCTScrollView): Fix vertical scrolling behavior for RCTScrollView

---

ReactWindows/Playground/App.xaml.cs
ReactWindows/ReactNative/ReactInstanceManager.cs
ReactWindows/ReactNative/ReactPage.cs

Native back press behavior is now wired up to exit the app.
Fixes #267

fix(BackAndroid): Exit app when back pressed

---

Examples/UIExplorer/UIExplorerApp.windows.js
Examples/UIExplorer/UIExplorerHeaderWindows.js
Libraries/react-native/react-native.js
Libraries/react-native/react-native.js.flow
ReactWindows/Playground/AppReactPage.cs
ReactWindows/ReactNative.Tests/UIManager/UIManagerModuleTests.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs
ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
ReactWindows/ReactNative/Views/Split/Events/SplitViewClosedEvent.cs
ReactWindows/ReactNative/Views/Split/Events/SplitViewOpenedEvent.cs
ReactWindows/ReactNative/Views/Split/ReactSplitViewManager.cs
ReactWindows/js/Components/DrawerAndroid/DrawerLayoutAndroid.windows.js
ReactWindows/js/Components/SplitViewWindows/SplitViewWindows.android.js
ReactWindows/js/Components/SplitViewWindows/SplitViewWindows.ios.js
ReactWindows/js/Components/SplitViewWindows/SplitViewWindows.windows.js

SplitViewWindows is a similar control to the DrawerLayoutAndroid, it's a pull-out context menu. Some of the events and properties are different, so we went for a different component name altogether.
Fixes #184

feat(SplitViewWindows): Adds SplitViewWindows view manager

---

ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs
ReactWindows/ReactNative/Modules/StatusBar/StatusBarModule.cs
ReactWindows/ReactNative/UIManager/BorderedContentControl.cs
ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
ReactWindows/ReactNative/Views/Text/FontStyleHelpers.cs
ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs
ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs
ReactWindows/ReactNative/Views/View/ReactViewManager.cs

Fixes up miscellaneous spots where nulled out properties can be set correctly or more concisely.
Fixes #293

fix(ViewProps): Ensure nulled out props are set correctly

---

Examples/UIExplorer/FlipViewWindowsExample.windows.js
Examples/UIExplorer/UIExplorerList.windows.js
Libraries/react-native/react-native.js
Libraries/react-native/react-native.js.flow
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/UIManager/BaseViewManager.cs
ReactWindows/ReactNative/Views/Flip/ReactFlipViewManager.cs
ReactWindows/js/Components/FlipViewWindows/FlipViewWindows.android.js
ReactWindows/js/Components/FlipViewWindows/FlipViewWindows.ios.js
ReactWindows/js/Components/FlipViewWindows/FlipViewWindows.windows.js

FlipView is useful for flipping through images. It's analogous to AndroidViewPager.
Fixes #188

feat(FlipViewWindows): Adds FlipViewWindows module for paging views

---

ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs

The EventDispatcher currently eagerly enqueues work on the JavaScript thread, which can be too busy. By dequeueing the events on the render event, we ensure the events are drained only as quickly as the frame rate allows.
Fixes #330

perf(EventDispatcher): Drain EventDispatcher on global render event

---

ReactWindows/Readme.md

This looks awesome - good work guys! :)

Fixed Readme's clone URL

---

ReactWindows/ReactNative.Tests/UIManager/PropertySetterTests.cs
ReactWindows/ReactNative.Tests/UIManager/ReactStylesDiffMapTests.cs
ReactWindows/ReactNative/UIManager/Annotations/ReactPropAttribute.cs
ReactWindows/ReactNative/UIManager/Annotations/ReactPropBaseAttribute.cs
ReactWindows/ReactNative/UIManager/Annotations/ReactPropGroupAttribute.cs
ReactWindows/ReactNative/UIManager/BaseViewManager.cs
ReactWindows/ReactNative/UIManager/BorderExtensions.cs
ReactWindows/ReactNative/UIManager/BorderedViewParentManager.cs
ReactWindows/ReactNative/UIManager/ColorHelpers.cs
ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs
ReactWindows/ReactNative/UIManager/NativeViewHierarchyOptimizer.cs
ReactWindows/ReactNative/UIManager/PropertySetter.cs
ReactWindows/ReactNative/UIManager/ReactShadowNode.cs
ReactWindows/ReactNative/UIManager/ReactStylesDiffMap.cs
ReactWindows/ReactNative/UIManager/ReactStylesDiffMapExtensions.cs
ReactWindows/ReactNative/Views/Flip/ReactFlipViewManager.cs
ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
ReactWindows/ReactNative/Views/Split/ReactSplitViewManager.cs
ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs

When a prop is not set, the native stack should default to a given value.
Fixes #325

fix(PropertySetter): Fixes default value behavior for property setter.

---

packager/react-packager/src/Resolver/index.js

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
(You can skip this if you're fixing a typo or adding an app to the Showcase.)
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.
**Test plan (required)**
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Make sure tests pass on both Travis and Circle CI.
**Code formatting**
Look around. Match the style of the rest of the codebase. See also the simple [style …

fix(Resolver) - fix path issues for Windows users

---

Examples/UIExplorer/UIExplorerList.windows.js
Examples/UIExplorer/XHRExample.windows.js
ReactWindows/ReactNative/Modules/Network/NetworkingModule.cs

Timeout is now wired up using a cancellation token (no native behavior for timeout in the HttpClient).
Fixes #382

fix(NetworkingModule): Adds timeout behavior to NetworkingModule

---

ReactWindows/ReactNative.Tests/Modules/Toast/ToastNotificationTests.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Modules/Toast/ToastHelper.cs
ReactWindows/ReactNative/Modules/Toast/ToastModule.cs
ReactWindows/ReactNative/ReactNative.csproj

Reverts ReactWindows/react-native#400

Revert "refactor(Toast): Deleting the toast module"

---

Examples/UIExplorer/ProgressBarWindowsExample.windows.js
Examples/UIExplorer/UIExplorerList.windows.js
Libraries/react-native/react-native.js
Libraries/react-native/react-native.js.flow
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/Views/Progress/ProgressBarShadowNode.cs
ReactWindows/ReactNative/Views/Progress/ReactProgressBarViewManager.cs
ReactWindows/js/Components/ProgressBarWindows/ProgressBarWindows.android.js
ReactWindows/js/Components/ProgressBarWindows/ProgressBarWindows.ios.js
ReactWindows/js/Components/ProgressBarWindows/ProgressBarWindows.windows.js

Includes options to set the color and switch between determinate and indeterminate progress.
Fixes #185

feat(ProgressBarWindows): Adds ProgressBarWindows to React Native

---

ReactWindows/ReactNative/DevSupport/DevInternalSettings.cs

fixes #408
`DevSupport` could probably use some tests. I can add those to this ticket or PR them separately. Either is fine with me.

Default Inspector mode to false on app start and don't save in LocalSettings

---

Examples/UIExplorer/ListViewWindowsExample.windows.js
Examples/UIExplorer/UIExplorerList.windows.js

We weren't able to use the ListView example due to the missing RecyclerViewBackedScrollViewManager, which is still missing. Working around that for now.

feat(UIExplorer): Adding ListView example for Windows UIExplorer

---

ReactWindows/js/Network/XMLHttpRequest.windows.js

Latest base class pre-computes 'useIncrementalUpdates'.

fix(XMLHttpRequest): Update XHR to use latest features from base class

---

ReactWindows/ReactNative/Modules/Network/NetworkingModule.cs

Adds basic form data string handling

feature(Networking) - Add basic formdata handling

---

Libraries/Components/TextInput/TextInput.windows.js

Typo in platform check was causing an exception in the minified bundle. This fixes that.
Fixes #440

fix(TextInput): Fixes platform check

---

README.md

Adds a quick link to the Code of Conduct

fix(readme) - Add CoC link

---

.editorconfig

Closes #468 by adding `.editorconfig`

feat(EditorConfig) - closes Issue #468

---

.editorconfig
.eslintignore
.eslintrc

Closes #469 by adding `.eslintrc` and `.eslintignore` as noted from React-Native.

feat(ESLint) - add ESLint - Closes Issue #469 

---

ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.cs

Adds feature to update the dimensions when the window size changes.
Fixes #466

feat(Dimensions): Update dimensions when window size / orientation changes

---

local-cli/generator-windows/templates/proj/MyApp.csproj

Fixes #470 again with the extra `../` removed

fix(CLI) - fixes Issue #470 again

---

ReactWindows/ReactNative/Modules/NetInfo/DefaultNetworkInformation.cs

Was debugging, hibernated my machine, resumed, and found the app stuck in the debugger on this line.

Fix null deref in NetInfo

---

ReactWindows/ReactNative/UIManager/BorderedViewParentManager.cs
ReactWindows/ReactNative/UIManager/ViewProps.cs

fix(RCTView): Add support for specific border radius corners

---

Libraries/StyleSheet/processTransform.windows.js
ReactWindows/ReactNative/UIManager/BaseViewManager.cs

- Scale
- Translate
- Rotation
Fixes #441

fix(BaseViewManager): Add support for transform animation

---

local-cli/generate-windows.js
local-cli/generator-windows/index.js
local-cli/rnpm/windows/index.js
local-cli/rnpm/windows/package.json
local-cli/rnpm/windows/src/windows.js

Some minor linting issues fixed

fix(CLI) - linting

---

ReactWindows/ReactNative/UIManager/NativeViewHierarchyManager.cs
ReactWindows/ReactNative/UIManager/UIImplementation.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

Here's the documentation for this method: http://facebook.github.io/react-native/releases/0.29/docs/nativemethodsmixin.html#measureinwindow
And here's the Android implementation: https://github.com/facebook/react-native/blob/5189c94a6e876ef5274b22c083034a561ef3d5e8/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#L572-L601

Implement UIManager.measureInWindow

---

ReactWindows/Playground/AppReactPage.cs
ReactWindows/ReactNative/Modules/Location/LocationModule.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs

Adds geolocation capabilities to ReactWindows.
Fixes #49

feat(Geolocation): Adds LocationObserver module

---

ReactWindows/Playground/project.json
ReactWindows/ReactNative.Tests/project.json
ReactWindows/ReactNative/project.json

Updates to use the latest Rx.NET versions (3.x)

Update to use latest Rx packages. Also needed UWP/Json update to match

---

ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/UIManager/LayoutAnimation/LayoutAnimationController.cs
ReactWindows/ReactNative/UIManager/LayoutAnimation/LayoutCreateAnimation.cs
ReactWindows/ReactNative/UIManager/LayoutAnimation/LayoutDeleteAnimation.cs
ReactWindows/ReactNative/UIManager/NativeViewHierarchyManager.cs
ReactWindows/ReactNative/UIManager/ViewParentManagerExtensions.cs

In cases where you want to fade out views or otherwise animate the layout operation that removes a view from the hierarchy, this change makes that possible.
Fixes #508

feat(LayoutAnimation): Adds delete animations for layout

---

ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs

Adds missing null check for injected JavaScript being set to null for WebView.
Fixes #573

fix(WebView): Fix issue when injected JavaScript is set to null

---

ReactWindows/ReactNative/Modules/Network/NetworkingModule.cs
ReactWindows/ReactNative/UIManager/LayoutAnimation/LayoutAnimationController.cs
ReactWindows/ReactNative/UIManager/ViewParentManagerExtensions.cs
ReactWindows/ReactNative/Views/Picker/ReactPickerManager.cs
ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs
ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs

JToken.Value<T> has to compare on typeof(T), where as JObject.GetValue and JArray.this[] will just return the JToken, which is what we want where we've replaced the usage of Value<T>.

fix(JSON): Replace JToken.Value<T> where appropriate

---

ReactWindows/ReactNative/DevSupport/DevServerHelper.cs

fix(DevSupport): terminate live reload poller immediately when disabled.

---

ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs

Previously used blocking calls to perform them in a lock { } scope. Replacing the lock with SemaphoreSlim, which supports async.
Fixes #598

perf(AsyncStorage): replace blocking filesystem calls with async

---

ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
ReactWindows/ReactNative/ReactNative.csproj

Adds a bridge for the `ChakraBridge` to act as an `IJavaScriptExecutor` interface.

feat(ChakraBridge) - Add native interface for IJavaScriptExecutor

---

ReactWindows/ChakraBridge/ChakraHost.cpp

Fixes logging with conditional switching based upon type to decide whether to use `JSON.stringify` to `Object.prototype.toString` calls

fix(ChakraBridge) - fixing logging

---

ReactWindows/ChakraBridge/ChakraBridge.vcxproj

fix(ChakraBridge) - add JSRT_EDGEMODE to all platforms

---

ReactWindows/ReactNative/Animated/DecayAnimationDriver.cs
ReactWindows/ReactNative/Animated/NativeAnimatedNodesManager.cs
ReactWindows/ReactNative/ReactNative.csproj

feat(DecayAnimation): Adds decay animation driver

---

ReactWindows/ChakraBridge/ChakraBridge.vcxproj
ReactWindows/ChakraBridge/ChakraBridge.vcxproj.filters
ReactWindows/ChakraBridge/ChakraHost.cpp
ReactWindows/ChakraBridge/JsStringify.cpp
ReactWindows/ChakraBridge/JsStringify.h
ReactWindows/ChakraBridge/asprintf.cpp
ReactWindows/ChakraBridge/asprintf.h

Adds better console logging with recursive fixes, plus no longer relies on `JSON.stringify` which is error prone with recursive objects.  Closes #626.

fix(ChakraBridge) - console logging fixes

---

ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs
ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs
ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs

fix(BundleLoader) - use file locations instead of loading scripts directly

---

ReactWindows/ChakraBridge/NativeJavaScriptExecutor.cpp
ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
ReactWindows/ReactNative/ReactInstanceManager.cs

Use serialized scripts when possible.  Closes #585

perf(ChakraBridge) - use serialized scripts

---

ReactWindows/ReactNative.Tests/Modules/Clipboard/ClipboardModuleTests.cs
ReactWindows/ReactNative.Tests/Modules/Clipboard/MockClipboardInstance.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/Modules/Clipboard/ClipboardInstance.cs
ReactWindows/ReactNative/Modules/Clipboard/ClipboardModule.cs
ReactWindows/ReactNative/Modules/Clipboard/IClipboardInstance.cs
ReactWindows/ReactNative/ReactNative.csproj

Creates a testable Clipboard module which will help close #262

fix(Clipboard) - add interface/facade for testability

---

ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/UIManager/UIManagerModule.Constants.cs
ReactWindows/ReactNative/Views/Slider/ReactSliderChangeEvent.cs
ReactWindows/ReactNative/Views/Slider/ReactSliderCompleteEvent.cs
ReactWindows/ReactNative/Views/Slider/ReactSliderManager.cs
ReactWindows/ReactNative/Views/Slider/ReactSliderShadowNode.cs

It has all not 'IOS only' props from http://facebook.github.io/react-native/docs/slider.html. The only difference is event handlers argument. For IOS and Android it is only value, here it's whole `event` object with value field. 
#373

feat(slider) - adding slider manager

---

ReactWindows/ReactNative/DevSupport/DevSupportManager.cs

fix(DevSupport): Ensure red box is closed before opening dev options menu

---

local-cli/generator-windows/templates/proj/MyApp.sln
package.json

Adding ChakraBridge native source and updating package.json to include the source files in NPM.
Fixes #669

fix(CLI): Ensure generated .sln includes ChakraBridge

---

ReactWindows/ChakraBridge/.npmignore
ReactWindows/ReactNative/.npmignore

chore(NPM): Adds .npmignore files for Windows builds

---

Libraries/Utilities/Platform.windows.js

fix(Platform): Adds 'select' helper to Platform for UWP.

---

ReactWindows/ReactNative/UIManager/BaseViewManager.cs

Adds implementation of 'testID' prop, mapping it to the automation ID for the XAML dependency object.
Fixes #717

fix(BaseViewManager): Adds testID native prop

---

ReactWindows/ReactNative.Shared.Tests/ReactNative.Shared.Tests.csproj

fix(tests): Quick fix to ensure all tests are run for Debug configurations.

---

local-cli/generator-windows/templates/src/MainPage.cs

fix(BundleConfig): MainPage.cs should disable dev options for ReleaseBundle config

---

ReactWindows/ReactNative/Views/Image/ReactImageLoadEvent.cs
ReactWindows/ReactNative/Views/Image/ReactImageManager.cs

Adds expected parameters to event data for image OnLoad event.
Fixes #754

fix(Image): Add width/height/url to OnLoad event

---

ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs

Using the IsEnabled property disabled touch in addition to scroll.  We'll need to keep some state about the current horizontal scroll status, but we can easily work around this by just disabling horizontal and vertical scroll.
Fixes #764

fix(ScrollView): 'scrollEnabled' prop should only disable scroll, not touch

---

ReactWindows/ReactNative/UIManager/BaseViewManager.cs

fix(Accessibility): Turns out accessibilityLabel should not be null either.

---

ReactWindows/ReactNative.Tests/Bridge/NativeModuleBaseTests.cs

test(Promise): fix broken test for Promise.

---

ReactWindows/ReactNative.Shared.Tests/Bridge/ReactBridgeTests.cs

Recent regression of ReactBridge when JavaScript returned a null flushed queue. This test should catch that in the future. cc @matthargett

test(ReactBridge): Adds unit test for recent regression

---

ReactWindows/ReactNative.Shared/Bridge/JavaScriptBundleLoader.cs
ReactWindows/ReactNative.Shared/DevSupport/DevInternalSettings.cs
ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs
ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs
ReactWindows/ReactNative.Shared/UIManager/RootViewManager.cs

cc @matthargett @GantMan @kevinvangelder

chore(Warnings): cleaning up some warnings for .NET 4.6 build

---

Libraries/Components/ScrollView/ScrollView.windows.js
ReactWindows/ReactNative/Views/Scroll/ReactScrollViewManager.cs

feat(ScrollView): Adds min/maxZoomScale to ScrollView

---

Libraries/Components/ScrollView/ScrollView.windows.js

fix(ScrollView): fix issue with scroll view not scrolling

---

ReactWindows/ReactNative/UIManager/BaseViewManager.cs

When a ScrollViewer is placed in the context of a Matrix3DProjection (which is how translate animations are achieved in React Native), the touch-based and touchpad scrolling behaviors stop functioning.
This PR works around that by using a simple RenderTransform for common cases of matrix projections, like simple XY translations, in which scrolling still works.
Fixes #873

hack(BaseViewManager): Workaround for ScrollViewer in Matrix3DProjection

---

ReactWindows/ReactNative.Shared/Bridge/NativeModuleBase.cs

chore(NativeModuleBase): Clean up unused static in NativeModuleBase

---

Libraries/Components/Button.windows.js

Using default Windows style, only foreground text is controllable.  Background color is fixed at transparent black.
Fixes #909

feat(Button): Add Windows styles for Button

---

ReactWindows/ReactNative/Modules/Image/BitmapImageHelpers.cs
ReactWindows/ReactNative/Views/Image/ReactImageManager.cs

Recent change to introduce caching for network images also broke image requests from local bundle.
Fixes #925

fix(Image): Fix bundled assets for Images

---

ReactWindows/ReactNative.Net46/ReactPage.cs
ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
ReactWindows/ReactNative.Shared/ReactRootView.cs
ReactWindows/ReactNative/ReactPage.cs

Added ability to pass in initialProps as JObject from ReactPage instance. This allows you to pass properties from native to React native.

Add InitialProps to ReactPage

---

ReactWindows/ReactNative.Net46.Tests/UIManager/UIManagerModuleTests.cs
ReactWindows/ReactNative.Net46/UIManager/UIManagerModule.cs

Closes #965.
Unfortunately this solution is pretty brittle but seems to be the best solution the interwebz have to offer.

[WPF] Fixed issue where reported dimensions mistakenly included window chrome

---

ReactWindows/ReactNative/UIManager/UIManagerModule.cs

Useful event for tracking when the app is in portrait vs. landscape mode.
Fixes #989

fix(UIManager): Adds event for `namedOrientationDidChange`

---

local-cli/runWindows/utils/deploy.js

fix(runWindows): fixes issue with spaces in path

---

ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs

fix(Padding): copy paste error for vertical padding

---

ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs
ReactWindows/ReactNative.Shared/UIManager/EdgeSpacing.cs
ReactWindows/ReactNative.Shared/UIManager/EpsilonEqualityComparer.cs
ReactWindows/ReactNative.Shared/UIManager/LayoutShadowNode.cs
ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs
ReactWindows/ReactNative.Shared/UIManager/ReactShadowNodeExtensions.cs
ReactWindows/ReactNative.Shared/Views/Text/ReactInlineShadowNodeVisitor.cs
ReactWindows/ReactNative.Shared/Views/TextInput/ReactPasswordBoxShadowNode.cs
ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextInputShadowNode.cs
ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs

feat(Style): Adds percent style support

---

docs/PerformanceProfilingWindows.md

This is just initial version of the document.
I see there is an option to configure profiling inside of app config.
I didn't try that yet.
Would update instructions as soon as that would work for me.

initial version of performance profiling document

---

ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs

borderLeftWidth and borderRightWidth props are useless

bugs fixed: borderLeftWidth and borderRightWidth props are useless

---

docs/RunningOnDeviceWindows.md
local-cli/generator-windows/index.js
local-cli/generator-windows/templates/_gitignore
local-cli/generator-windows/templates/ra_gitignore

Add instructions to create the directory for release bundles. Also added instructions for creating an app package and uploading to the store (took me quite a while to find.)

Generate windows/myapp/ReactAssets/.gitignore, so that the directory always exists

---

ReactWindows/ReactNative.Net46/Views/Picker/ReactPickerManager.cs

Copied fix from #914 to WPF implementation.
Upstream merge: https://github.com/Microsoft/react-native-windows/pull/1122

Merge  fix #914 to WPF to 0.42 stable

---

ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyOptimizer.cs
ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs

With these view props missing from the layout-only list, extra views are being created that are truly layout-only.

fix(ViewProps): Update layout-only view props

---

docs/RunningOnDeviceWindows.md

Is this the intended address for changing dev server IP address for running in Xbox?

Dev Server IP address Link

---

README.md

fix(Docs): Examples/UIExplorer -> RNTester

---

appveyor.yml

There seem to be connectivity issues between the AppVeyor datacenter and NuGet, the workaround is discussed here:
http://help.appveyor.com/discussions/problems/7087-nuget-timeouts-since-yesterday

fix(CI): temporary patch for appveyor.yml

---

ReactWindows/ReactNative.Shared/UIManager/BorderedViewParentManager.cs
ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs

There's no need for this prop to be on a base class, it should be tied directly to View so no other classes inherit it by mistake.

fix(View): The collapsable prop is specific to View

---

Libraries/Components/FlipViewWindows/FlipViewWindows.windows.js
Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js
Libraries/Components/Picker/PickerWindows.js
Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows.js
Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows.js
Libraries/Components/SplitViewWindows/SplitViewWindows.windows.js
Libraries/Components/TextInput/TextInput.windows.js
Libraries/Components/WebView/WebView.windows.js
Libraries/Image/Image.windows.js
docs/NativeComponentsWindows.md

This fixes the View.propTypes warning in #1189

Change View.propTypes to ViewPropTypes to support React Native v44

---

local-cli/generate-windows.js
local-cli/generator-windows/index.js
local-cli/generator-wpf/index.js
local-cli/rnpm/windows/index.js
local-cli/rnpm/windows/src/windows.js
local-cli/rnpm/windows/src/wpf.js
local-cli/rnpm/wpf/index.js
local-cli/rnpm/wpf/src/wpf.js
local-cli/runWindows/runWindows.js
local-cli/runWindows/utils/build.js
local-cli/runWindows/utils/deploy.js
local-cli/runWindows/utils/msbuildtools.js
local-cli/runWindows/utils/winappdeploytool.js
local-cli/runWpf/runWpf.js
local-cli/runWpf/utils/build.js
local-cli/runWpf/utils/deploy.js
local-cli/runWpf/utils/msbuildtools.js

Added the --verbose option which will now pipe the output of all spawned or executed commands.
Fixes #1184

feat(react-native-cli): Added --verbose option (#1184)

---

ReactWindows/ReactNative.Shared/Animated/NativeAnimatedNodesManager.cs

This resolves a race condition where the NativeAnimatedModule may attempt to update a node that has not yet been created.
Fixes #1239

fix(NativeAnimated): Fixes native animated crash

---

.flowconfig
ReactWindows/ReactNative.Shared.Tests/Modules/Core/JSTimersTests.cs
ReactWindows/ReactNative.Shared.Tests/ReactNative.Shared.Tests.projitems
ReactWindows/ReactNative.Shared/CoreModulesPackage.cs
ReactWindows/ReactNative.Shared/Modules/Core/JSTimers.cs
ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs
ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
ReactWindows/ReactNative.Tests/Modules/Core/TimingTests.cs
Releases.md
package.json

Will also push the branch itself once the changes below have been reviewed.

Releasing 0.47-stable branch

---

local-cli/runWindows/utils/build.js
local-cli/runWindows/utils/msbuildtools.js

Verbosity change introduced a null pointer exception. This covers the exceptions I was able to find. cc @sayar

fix(CLI): fix crash from switch to stdio: inherit

---

local-cli/runWindows/utils/deploy.js
local-cli/runWpf/utils/deploy.js

fix(CLI): point CLI at correct path for packager launch script

---

local-cli/runWindows/utils/build.js
local-cli/runWindows/utils/msbuildtools.js
local-cli/runWpf/utils/build.js
local-cli/runWpf/utils/msbuildtools.js

Added support for VS2017 without requiring any modifications for VS2015.

fix(local-cli): Updated for VS2017

---

ReactWindows/Playground.Net46/App.xaml.cs
ReactWindows/ReactNative.Net46/ReactPage.cs
ReactWindows/ReactNative.Shared/Bridge/ReactContext.cs
ReactWindows/ReactNative.Shared/Common/LifecycleState.cs
ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
ReactWindows/ReactNative.Tests/ReactInstanceManagerTests.cs
ReactWindows/ReactNative/ReactPage.cs
local-cli/generator-wpf/templates/src/App.xaml.cs

This change uses the same methods to change the lifecycle state in the ReactInstanceManager as ReactAndroid.

fix(LifecycleState): Add stronger guarantees about the LifecycleState state machine

---

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs

[wpf]new feature/add SetOverflow in BaseViewManager

[wpf]new feature/add SetOverflow in BaseViewManager

---

ReactWindows/ReactNative.Shared.Tests/UIManager/ShadowNodeRegistryTests.cs
ReactWindows/ReactNative.Shared/UIManager/ShadowNodeRegistry.cs

Various reports of an InvalidOperationException occurring sporadically on app start have been filed (#1326, #266). It seems that this is related to the enumeration of root nodes tags in a dictionary from a KeyCollection while the dictionary is being updated. This PR copies the keys to a list (we reuse the list to reduce heap impact) to get around the exception (at least until a better architecture for this shadow node registry is proposed).
Fixes #1326 
Fixes #266

fix(ShadowNodeRegistry): thread safety issue in ShadowNodeRegistry

---

ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueue.cs

Rather than guessing how much time is left in the frame, use the absolute time.
Fixes #1343

fix(UIViewOperationQueue): use frame time to execute non-batched operations

---

Libraries/Components/WebView/WebView.windows.js
ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.Constants.cs
ReactWindows/ReactNative.sln
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/Views/Web/Events/MessageEvent.cs
ReactWindows/ReactNative/Views/Web/Events/WebViewLoadEvent.cs
ReactWindows/ReactNative/Views/Web/Events/WebViewLoadingErrorEvent.cs
ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs
ReactWindows/ReactNativeWebViewBridge/MessagePostedEventArgs.cs
ReactWindows/ReactNativeWebViewBridge/Properties/AssemblyInfo.cs
ReactWindows/ReactNativeWebViewBridge/ReactNativeWebViewBridge.csproj
ReactWindows/ReactNativeWebViewBridge/WebViewBridge.cs
ReactWindows/ReactNativeWebViewBridge/project.json
local-cli/generator-windows/templates/proj/MyApp.sln

Allows communication between the React Native Web View and the React Native JS runtime with the WebView bridge.
Fixes #987

feat(WebView): Adds `postMessage` callback and `injectJavaScript` command

---

ReactWindows/ReactNative/Views/Web/ReactWebViewManager.cs

This prevents the UI thread from being held up by injected JavaScript, etc.
Fixes #1382

fix(WebView): Use separate thread from UI for WebView

---

ReactWindows/ReactNative.Net46/Views/Scroll/ReactScrollViewManager.cs

props to support:
- horizontal
- contentOffset
Also fix `scrollEnabled={false}` will hide scroll bar issue.

Add more WPF ScrollView supported props

---

ReactWindows/ReactNative/project.json

fix(Image): Update ImagePipeline to v0.0.4 to support VS2017.

---

ReactWindows/ReactNative.Shared.Tests/Modules/Network/NetworkingModuleTests.cs
ReactWindows/ReactNative.Shared/Modules/Network/HttpContentHelpers.cs
ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs

Previously, we only had support for local file URI and string HTTP request bodies. This change adds support for base64 body as well.
Fixes #1391

feat(NetworkingModule): Adds support for base64 request body

---

scripts/bump-oss-version.js

For some reason on Windows we have to explicitly convert the output of `cat(...).replace(...)` to a ShellString, and we also don't have `grep` on Windows, so removing the check for now (which doesn't actually check that everything updates, only that package.json does, which means you really should check the result anyway).

fix(Scripts): Fix bump-oss-version scripts

---

ReactWindows/ChakraBridge/ChakraBridge.vcxproj
ReactWindows/Playground/Playground.csproj
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative/ReactNative.csproj
local-cli/generator-windows/templates/proj/MyApp.csproj

Update all projects to target 10.0.14393.0.

fix(API): update to Anniversary Update

---

ReactWindows/ReactNative.Net46/Modules/DeviceInfo/DeviceInfoModule.cs
ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
ReactWindows/ReactNative.Net46/UIManager/DisplayMetrics.cs
ReactWindows/ReactNative.Shared/CoreModulesPackage.cs
ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
ReactWindows/ReactNative/Bridge/Queue/LayoutActionQueue.cs
ReactWindows/ReactNative/Modules/DeviceInfo/DeviceInfoModule.cs
ReactWindows/ReactNative/ReactNative.csproj
ReactWindows/ReactNative/UIManager/DisplayMetrics.cs

Remove requirement that CoreModulesPackage must be created on dispatcher thread.
Towards #1288

refactor(CoreModulesPackage): Enable initialization off-dispatcher

---

ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs

When no CoreWindow is available, the CompositionTarget.Rendering function does not tick. The original plan was to use DispatcherTimer to tick in the background, but it seems to also be tied to the activation of the CoreWindow. Instead, we use a regular Timer and queue an action onto the Dispatcher.
Fixes #1472

feat(ReactChoreographer): Allow simulation in the background

---

ReactWindows/ReactNative.Net46.Tests/Modules/NetInfo/NetInfoModuleTests.cs
ReactWindows/ReactNative.Net46/Bridge/DispatcherHelpers.cs
ReactWindows/ReactNative.Net46/ReactPage.cs
ReactWindows/ReactNative.Shared.Tests/Modules/AppState/AppStateModuleTests.cs
ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs
ReactWindows/ReactNative.Shared/ReactInstanceManager.cs
ReactWindows/ReactNative.Tests/UnitTestApp.xaml.cs
ReactWindows/ReactNative/Bridge/DispatcherHelpers.cs
ReactWindows/ReactNative/Bridge/Queue/LayoutActionQueue.cs

This reverts commit c47b95c87af5c142e4bb2ccc156eea53e0906fa9.

Revert "fix(Dispatcher): Store reference to dispatcher for background (#1454)

---

ReactWindows/ReactNative.Shared/ReactInstanceManager.cs

Suspending the ReactInstanceManager shuts down the DispatcherHelpers and the ReactChoreographer. We need to cancel any pending operations to create ReactContext in case a suspend operation comes in while the application is starting up (a common case when running in the background).
Fixes #1479

fix(ReactInstanceManager): Cancel CreateReactContextAsync OnSuspend

---

ReactWindows/ReactNative/DevSupport/WebSocketJavaScriptExecutor.cs

When the WebSocketJavaScriptExecutor is disposed, some tasks may be waiting still for responses from the WebSocket. For now, send null to any pending task.
Fixes #1494

fix(WebSocketJavaScriptExecutor): Clear out pending tasks on dispose

---

ReactWindows/ReactNative.Net46/UIManager/BaseViewManager.cs

Clone of #1202 for WPF fix of #1182

fix(BaseViewManager): Ensure transform is applied from view center (WPF)

---

ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs

Allow programmatic selection of text via `selection` prop.

feat(TextInput): Add `selection` prop support

---

docs/GettingStarted.md

Typo - Minor fixes

---

appveyor.yml

skip Network unit tests during coverage as well to avoid CI flakiness

---

local-cli/runWindows/runWindows.js
local-cli/runWindows/utils/deploy.js
local-cli/runWpf/runWpf.js
local-cli/runWpf/utils/deploy.js

Added --no-packager flag to 'react-native run-windows'
Consistently with other platforms CLI

Added --no-packager flag to 'react-native run-windows'

---

ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyOptimizer.cs
ReactWindows/ReactNative.Shared/UIManager/ReactShadowNode.cs

A particular layout update may be missing due to optimizations.

Fixing a layout manager issue affecting layout only nodes transitioning to full.

---

ReactWindows/ReactNative.Tests/UIManager/Events/EventDispatcherTests.cs

I promised I would remove this bogus test.

Removed a test that's not valid anymore.

---

ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueueInstance.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

Fixed some XML comments

---

package.json

Increase version to 0.54.0-rc to prepare for MIT licensed code. Also updating other react-native dependencies.

chore(NPM): update to `react-native@0.54.0-rc`

---

local-cli/generator-windows/templates/proj/MyApp.sln

The command was generating an invalid `.sln` file given the recent changes to Yoga.

fix(CLI): fix `react-native windows` command

---

ReactWindows/ReactNative/ReactNative.csproj

updated imagepipeline nuget version to get 'redirect' fix in

bump image pipeline to 0.1.4

---

ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs

I wonder why was this using GetFileFromApplicationUriAsync API in the first place. Also this should probably also support FutureAccessList URIs - cc @antonkh .

fix uri upload on uwp

---

package.json

fix(NPM): relax dependency versions for react-native

---

ReactWindows/ReactNative.Net46/Views/Scroll/ReactScrollViewManager.cs

Fixed typo that went unnoticed for a long time

---

ReactWindows/ReactNative.Shared/UIManager/BorderExtensions.cs
ReactWindows/ReactNative.Shared/UIManager/BorderedCanvas.cs
ReactWindows/ReactNative.Shared/Views/View/ReactViewManager.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative.Tests/UIManager/BorderedCanvasTests.cs

added protected methods to set/get background brush of BorderedCanvas for derived classes to use. This is for react-native-linear-gradient which is going to inherit from ReactViewManager.

added protected methods to set/get background brush of BorderedCanvas

---

ReactWindows/ChakraBridge/CallSyncHandler.h
ReactWindows/ChakraBridge/ChakraBridge.vcxproj
ReactWindows/ChakraBridge/ChakraBridge.vcxproj.filters
ReactWindows/ChakraBridge/ChakraHost.cpp
ReactWindows/ChakraBridge/ChakraHost.h
ReactWindows/ChakraBridge/FlushQueueImmediateHandler.h
ReactWindows/ChakraBridge/NativeJavaScriptExecutor.cpp
ReactWindows/ChakraBridge/NativeJavaScriptExecutor.h
ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj
ReactWindows/ReactNative.Net46.Tests/Resources/immediate.js
ReactWindows/ReactNative.Net46/DevSupport/WebSocketJavaScriptExecutor.cs
ReactWindows/ReactNative.Shared.Tests/Bridge/ReactBridgeTests.cs
ReactWindows/ReactNative.Shared.Tests/Internal/MockJavaScriptExecutor.cs
ReactWindows/ReactNative.Shared/Bridge/IJavaScriptExecutor.cs
ReactWindows/ReactNative.Shared/Bridge/ReactBridge.cs
ReactWindows/ReactNative.Shared/Chakra/Executor/ChakraJavaScriptExecutor.cs
ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
ReactWindows/ReactNative.Tests/Resources/immediate.js
ReactWindows/ReactNative/Chakra/Executor/NativeJavaScriptExecutor.cs
ReactWindows/ReactNative/DevSupport/WebSocketJavaScriptExecutor.cs

Reference:
https://github.com/facebook/react-native/blob/8e85bf84e8139caebc79d2034313ff0f4c936bea/ReactCommon/cxxreact/JSCExecutor.cpp#L636

Implement FlushQueueImmediate callback from RN Android

---

ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs

This path adds the content type entity header to HTTP header which was previously missing

Set content type based on user preferences or storage meme type

---

Libraries/Components/FocusableWindows/FocusableWindows.windows.js
ReactWindows/ReactNative/Accessibility/AccessibilityTrait.cs
ReactWindows/ReactNative/Accessibility/DynamicAutomationPeer.cs

Few accessibility related updates:
1. Add AccessibilityLabel to FocusableWindows so that application code can set it
2. Remove some code in FocusableWindows that copies properties downstream that apparently is not needed anymore
3. Add support for ListItem trait to handle list items for accessibility.

Accessibility updates: label, listItem and trait.

---

ReactWindows/ReactNative/Accessibility/AccessibilityHelper.cs
ReactWindows/ReactNative/UIManager/BaseViewManager.cs

I'll look into adding test for this - wasn't able to quickly find.

Fix #1828 crash when Visibility is changed to Collapsed on a view.

---

ReactWindows/ReactNative/ReactNative.csproj

https://github.com/phongcao/image-pipeline-windows/tree/gif-decoder

bump fresco.imagepipeline module for git decoder fix

---

ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs
ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs
ReactWindows/ReactNative.Shared/Views/Text/ReactSpanViewManager.cs

This PR does not address Issue #1784 , which is still relevant.  This PR simple fixes mistakes in the method's WPF facing code.

Fix WPF implementation of HasUpToDateBundleInCache

---

ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

The two dictionaries in UIViewOperationQueue (reactTagToOperationQueue and _dispatcherToOperationQueueInfo) are mainly accessed from the layout manager thread. Yet there are cases when main UI thread is involved (for native animations and lifecycle events).
Adding a lock (rather than more memory consuming concurrent dictionaries) to protect these.

Harden the UIViewOperationQueue structures

---

ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

There's a deadlock scenario. Rather than patching, I'm reverting and taking a second look.

Revert "Harden the UIViewOperationQueue structures"

---

windows/RNTester/RNTesterApp.csproj

This fixes building issues for **DebugBundle** and **ReleaseBundle** configurations.

fix(RNTester): update project file for DebugBundle and ReleaseBundle configuration

---

Libraries/Alert/Alert.windows.js
ReactWindows/ReactNative.Net46/UIManager/UIViewOperationQueue.cs
ReactWindows/ReactNative.Shared/Modules/Dialog/DialogModuleHelper.cs
ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
ReactWindows/ReactNative/Modules/Dialog/DialogModule.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

Added optional parameter rootViewHint (a numeric react tag) to Alert.alert.
RNTester will be updated separately

Added multi-window support to alerts

---

js/AlertExample.js
windows/RNTester/RNTesterApp.csproj

Added "rootViewHint" to the Alert calls in AlertExample.js.
Also fixed some small issues in RNTester.csproj file.

Multi Window Alert support tests

---

ReactWindows/ReactNative.Shared/UIManager/ViewProps.cs

Fixed prop parsing (I think the code followed a wishful thinking)

Fixed prop parsing

---

js/PointerEventsExample.js

1. Added handlers for mouse enter/leave/over/out
2. Added overlapped element to test the "pass through" mouse scenarios
Didn't add "mouse move" as part of this PR (though I tested manually) due to the sheer amount of noise generated..

RNTester pointerevents tests changes

---

ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs
ReactWindows/ReactNative.Shared/ReactNative.Shared.projitems
ReactWindows/ReactNative.Shared/Views/TextInput/ClearButtonModeType.cs
ReactWindows/ReactNative.Shared/Views/TextInput/ReactTextBox.cs
ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs

This is a revival of https://github.com/Microsoft/react-native-windows/pull/1874.
I'll send an RNTester PR shortly.

Implement clearButtonMode prop, granting control over the 'X' button in text input boxes

---

ReactWindows/ReactNative.Net46/UIManager/UIViewOperationQueue.cs
ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs
ReactWindows/ReactNative/Modules/Dialog/DialogModule.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs

Unify the not yet released UIImplementation.RunOnDispatcherThread with the IUIBlock based one, by making the latter multi window aware.

Make appendUIBlock multi window aware

---

ReactWindows/ReactNative.Net46/Shell/MainReactPackage.cs
ReactWindows/ReactNative.Net46/Views/Image/ReactImageManager.cs
ReactWindows/ReactNative.Net46/Views/Text/ReactTextShadowNode.cs
ReactWindows/ReactNative.Shared/Modules/I18N/I18NModule.cs
ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyManager.cs
ReactWindows/ReactNative.Shared/UIManager/ShadowNodeRegistry.cs
ReactWindows/ReactNative.Shared/UIManager/UIImplementation.cs
ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs
ReactWindows/ReactNative.Shared/UIManager/UIViewOperationQueueInstance.cs
ReactWindows/ReactNative/Shell/MainReactPackage.cs
ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs
ReactWindows/ReactNative/Views/Image/ReactImageManager.cs
ReactWindows/ReactNative/Views/Text/ReactTextShadowNode.cs

We rely on Xaml FlowDirection rather than on the Yoga based flipping.
We also support changing the direction on the fly.
Various peculiarities/details can be found in the comments throughout the PR.

Fixed RTL support

---

ReactWindows/ReactNative.Shared/Modules/I18N/I18NModule.cs
ReactWindows/ReactNative/Views/Image/ReactImageManager.cs

Forgot to add this in the previous commit.

RTL support: event and dynamic property to support on the fly changes

---

ReactWindows/ReactNative.Shared/Modules/Core/ReactChoreographer.cs

An accessor that can be used to access a ReactChoreographer pertaining to a particular top level window.
Can be used to hook custom animations/etc into the correct choreographer.

Per instance ReactChoreographer accessor

---

ReactWindows/ReactNative/Views/Text/ReactSimpleTextViewManager.cs

Added the "simple text" counterpart of the #1951.

Added selection change support to simple text control

---

Libraries/Text/Text.windows.js
Libraries/Text/TextPropTypes.windows.js
ReactWindows/ReactNative/Views/Text/ReactSimpleTextViewManager.cs
ReactWindows/ReactNative/Views/Text/ReactTextViewManager.cs

This allows the disabling of the OS provided default context menu for selectable Text elements.

Added disableContextMenu property to UWP flavor of Text

---

local-cli/generator-windows/index.js

[#2056] - create windows folder before generating a self-signed certificate / local-cli

---

RNWCPP/.ado/windows-vs-pr.yml
RNWCPP/CHANGELOG.json
RNWCPP/CHANGELOG.md
RNWCPP/CopyHeaders.inc
RNWCPP/Desktop/WebSocket.cpp
RNWCPP/ReactUWP/ReactUWP.vcxproj
RNWCPP/ReactUWP/ReactUWP.vcxproj.filters
RNWCPP/ReactUWP/Views/ControlViewManager.cpp
RNWCPP/ReactUWP/Views/FrameworkElementViewManager.cpp
RNWCPP/ReactUWP/Views/ViewViewManager.cpp
RNWCPP/Scripts/cli.js
RNWCPP/include/ReactUWP/Views/ControlViewManager.h
RNWCPP/package.json
RNWCPP/src/RNTester/AccessibilityExample.tsx
RNWCPP/src/RNTester/KeyboardExample.tsx
RNWCPP/src/RNTester/RNTesterList.uwp.ts

Update to latest, this seems to fix resolving react-native in npm install - 0.57.0-microsoft.1 is working

rnwcpp preview update 2019 03 08

---

RNWCPP/.ado/publish.js
RNWCPP/package.json

Following the naming scheme outlined here: #2101

Rename RNWCPP package

---

README.md

Fixes #2049 
(Creating PR on behalf of @rozele )

Updates README with repo status information

---

.github/CODEOWNERS

Added CODEOWNERS file for RNWCPP PRs (#2167)

---

RNWCPP/package.json

Update to react-native@0.57.0-microsoft.7

---

.github/ISSUE_TEMPLATE/RNWCPP.md

Removing auto-assign in order to facilitate triage

Updating issue template for RNWCPP

---

RNWCPP/package.json

Update typescript version to 3.3.3

---

RNWCPP/docs/BRANCH_SETUP.md
RNWCPP/docs/CONTRIBUTING.md

Basic copy of contrib docs from some of our other repos

---

RNWCPP/ReactUWP/ABI/idl/sources

Fixup build files for devmain build

---

RNWCPP/package.json

Update to react-native@0.57.0-microsoft.11

---

RNWCPP/package.json

Applying package update to 0.57.0-vnext.19

---

RNWCPP/ReactUWP/Views/ViewPanel.cpp
RNWCPP/ReactUWP/Views/ViewPanel.h

Minor code cleanup in ViewPanel.

---

RNWCPP/package.json

Update to react-native@0.57.0-microsoft.12

---

RNWCPP/.ado/windows-vs-pr.yml

Added two tasks to verify we can generate a bundle and then delete it.

Add create bundle task to build definition

---

RNWCPP/docs/releases.md

Releases file for rnwcpp versioning

---

RNWCPP/ReactWin32.nuspec
RNWCPP/ReactWindows-CopyToStaging.bat

Changes to enable building one of our internal projects with nuget instead of full source drop

add additional files to nuget package to build reactNativeHost

---

RNWCPP/package.json

Update to react-native@0.58.6-microsoft.17

---

RNWCPP/ReactUWP/Polyester/ButtonViewManager.cpp
RNWCPP/ReactUWP/Polyester/HyperlinkViewManager.cpp
RNWCPP/ReactUWP/Utils/PropertyUtils.h
RNWCPP/ReactUWP/Views/CheckboxViewManager.cpp
RNWCPP/ReactUWP/Views/ControlViewManager.cpp
RNWCPP/ReactUWP/Views/DatePickerViewManager.cpp
RNWCPP/ReactUWP/Views/ImageViewManager.cpp
RNWCPP/ReactUWP/Views/ImageViewManager.h
RNWCPP/ReactUWP/Views/PickerViewManager.cpp
RNWCPP/ReactUWP/Views/ScrollViewManager.cpp
RNWCPP/ReactUWP/Views/ShadowNodeBase.cpp
RNWCPP/ReactUWP/Views/SwitchViewManager.cpp
RNWCPP/ReactUWP/Views/TextInputViewManager.cpp
RNWCPP/ReactUWP/Views/ViewManagerBase.cpp
RNWCPP/ReactUWP/Views/ViewViewManager.cpp
RNWCPP/ReactUWP/Views/WebViewManager.cpp
RNWCPP/include/ReactUWP/Views/ControlViewManager.h
RNWCPP/include/ReactUWP/Views/ShadowNodeBase.h
RNWCPP/include/ReactUWP/Views/ViewManagerBase.h

Reduce and rationalize some header file includes related to ShadowNodeBase & ViewManagerBase. Reduces dependencies for build.

---

RNWCPP/package.json

Update to react-native@0.58.6-microsoft.19

---

RNWCPP/package.json

Update to react-native@0.58.6-microsoft.20

---

RNWCPP/package.json

Update to react-native@0.58.6-microsoft.21

---

RNWCPP/dirs

Internal build def update

---

RNWCPP/.ado/publish.js
RNWCPP/dirs
RNWCPP/package.json

Attempt to get publish to be more robust

---

RNWCPP/ReactUWP/Views/ActivityIndicatorViewManager.cpp
RNWCPP/Universal.SampleApp/index.uwp.js

#2110 
This change adds the color property to the ActivityIndicator component.

[ActivityIndicator] Map color property to Control.Foreground

---

RNWCPP/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp

Disable RNTesterIntegrationTests.WebSocket.

---

RNWCPP/Chakra/ChakraValue.h
RNWCPP/Chakra/Utf8DebugExtensions.cpp
RNWCPP/Desktop.DLL/react-native-win32.oss.x86.def
RNWCPP/Desktop.DLL/react-native-win32.x64.def
RNWCPP/Desktop.DLL/react-native-win32.x86.def
RNWCPP/Desktop.DLL/react-native-win32.x86sdx.def
RNWCPP/ReactCommon/ReactCommon.vcxproj
RNWCPP/ReactCommon/ReactCommon.vcxproj.filters
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.arm.def
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.oss.arm.def
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.oss.x64.def
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.oss.x86.def
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x64.def
RNWCPP/ReactUWP/EndPoints/dll/react-native-uwp.x86.def
RNWCPP/ReactWindows-CopyToStaging.bat
RNWCPP/ReactWindows.nuspec
RNWCPP/ReactWindowsCore/UnicodeConversion.cpp
RNWCPP/Universal.SampleApp/HostingPane.xaml.cpp
RNWCPP/package.json

Update to react-native@0.58.6-microsoft.22

---

RNWCPP/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
RNWCPP/Desktop.DLL/packages.config
RNWCPP/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
RNWCPP/Desktop.IntegrationTests/packages.config
RNWCPP/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
RNWCPP/Desktop.UnitTests/packages.config
RNWCPP/Desktop/React.Windows.Desktop.vcxproj
RNWCPP/Desktop/packages.config
RNWCPP/ReactWin32SandboxSample/ReactWin32SandboxSample.vcxproj
RNWCPP/ReactWin32SandboxSample/packages.config

Update ChakraCore version

---

RNWCS/local-cli/rnpm/windows/src/windows.js

Changed url to proper repo

---

RNWCPP/.ado/evergreen.js
RNWCPP/.ado/windows-vs-pr.yml
RNWCPP/.npmrc
RNWCPP/README.md
RNWCPP/Scripts/postInstall.js
RNWCPP/Scripts/preInstall.js
RNWCPP/Scripts/replaceRNDependency.js
RNWCPP/package.json

Point react-native fork dependency to github tar

---

RNWCS/local-cli/rnpm/windows/src/windows.js

Update CLI to react-native's fork URL

---

RNWCPP/.ado/evergreen.js
RNWCPP/package.json
RNWCPP/yarn.lock

Update to react-native@0.58.6-microsoft.23

---

RNWCPP/.npmignore

Remove projects needed for CLI from .npmignore

---

RNWCPP/win32/sources

Sync from internal

---

RNWCPP/.ado/evergreen.js
RNWCPP/package.json
RNWCPP/yarn.lock

Automatic update to latest version published from @Microsoft/react-native

Update to react-native@0.58.6-microsoft.24

---

RNWCPP/package.json
RNWCPP/yarn.lock

Automatic update to latest version published from @Microsoft/react-native

Update to react-native@0.58.6-microsoft.25

---

RNWCPP/package.json
RNWCPP/yarn.lock

Automatic update to latest version published from @Microsoft/react-native

Update to react-native@0.58.6-microsoft.26

---

RNWCPP/.npmignore
RNWCPP/Scripts/preInstall.js

Update npmignore and preinstall for CLI

---

RNWCPP/Directory.Build.props
RNWCPP/Scripts/launchPackager.bat
RNWCPP/local-cli/generator-windows/templates/proj/MyApp.csproj
RNWCPP/local-cli/generator-windows/templates/proj/MyApp.sln
RNWCPP/local-cli/index.js
RNWCPP/local-cli/runWindows/runWindows.js
RNWCPP/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
RNWCPP/local-cli/runWindows/utils/build.js
RNWCPP/local-cli/runWindows/utils/checkRequirements.js
RNWCPP/local-cli/runWindows/utils/deploy.js
RNWCPP/local-cli/runWindows/utils/msbuildtools.js
RNWCPP/local-cli/runWindows/utils/version.js
RNWCPP/local-cli/runWindows/utils/winappdeploytool.js
RNWCPP/package.json
RNWCPP/yarn.lock
RNWCS/local-cli/rnpm/windows/src/windows.js

to run: 
same steps as before, but project creation changed to the line below, where --windowsVersion is teh version of react-native-windows package
react-native windows --template vnext --windowsVersion 0.58.0-vnext.31 --verbose

cli that works with published packages

---

RNWCPP/Scripts/postInstall.js

Update postinstall script to work with CLI

---

RNWCPP/.ado/publish.yml

Add npm publish to public feed

---

RNWCPP/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
RNWCPP/Desktop.DLL/packages.config
RNWCPP/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
RNWCPP/Desktop.IntegrationTests/packages.config
RNWCPP/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
RNWCPP/Desktop.UnitTests/packages.config
RNWCPP/Desktop/React.Windows.Desktop.vcxproj
RNWCPP/Desktop/packages.config
RNWCS/ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
RNWCS/ReactWindows/ReactNative.Net46/packages.config
RNWCS/local-cli/generator-wpf/templates/proj/packages.config

Update version of ChakraCore

---

RNWCPP/local-cli/generator-windows/index.js

Fixes project creation.

---

RNWCPP/ReactUWP/Modules/NativeUIManager.cpp
RNWCPP/ReactUWP/Views/FrameworkElementViewManager.cpp
RNWCPP/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp
RNWCPP/Universal.SampleApp/flexbox.uwp.js

* Added support for percentages for flexBasis in NaitveUIManager
* Added flexBasis examples in flexbox.uwp.js
* Fixed bug in CreateExceptionInfo
* Implemented zIndex in FrameworkElementViewManager

Implemented missing layout properties, #2143

---

RNWCPP/Desktop.DLL/react-native-win32.oss.x64.def
RNWCPP/Desktop.DLL/react-native-win32.x64.def
RNWCPP/Desktop.DLL/react-native-win32.x86sdx.def

Add YGUnitToString symbol to def files

---

RNWCPP/ReactWindowsCore/CMakeLists.txt

new file LayoutAnimation.cpp is missing, causing linker errors

fix CMake build

---

README.md
current/README.md
vnext/README.md
vnext/docs/releases.md

Submitting a README file for `current` and a few other refactoring in other files to pick up these changes.

README for `current`

---

vnext/docs/GettingStarted.md

Adding manual install steps and steps for running sample apps through cloning repo.

Updating Getting Started (vnext)

---

vnext/CopyHeaders.inc
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/ReactUWP/EndPoints/dll/sources
vnext/sources.inc

Fix up build logic used for internal build

Internal build changes

---

vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.DLL/packages.config
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/packages.config
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/packages.config

Updating chakracore debugger to the lastest version

updating chakracore debugger

---

vnext/Desktop/WebSocket.cpp

Be specific about which string_view

---

vnext/Desktop.DLL/react-native-win32.x86sdx.def
vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86sdx.def

Fix x86 cmake build break caused by commit 2dd1b43860edeba7a321f02eab1f6ee15771711c.

---

.ado/evergreen.js
.github/CODEOWNERS
.gitmodules
README.md
current/README.md
current/docs/CONTRIBUTING.md
current/docs/GettingStarted.md
current/docs/RunningOnDeviceWindows.md
current/docs/SetupTroubleshooting.md
vnext/README.md
vnext/docs/BRANCH_SETUP.md
vnext/docs/CONTRIBUTING.md
vnext/docs/GettingStarted.md
vnext/include/ReactWindowsCore/unicode.h

Also updated a bunch of references from the old github Microsoft org to microsoft.

unicode.h uses stdexcept but doesn't include it

---

current/package.json
vnext/package.json

#2439 
npm uses this property to replace relative hyperlinks in readmes.

Add/update repository properties in package.jsons

---

vnext/ReactWin32.nuspec

Include IWebSocket.h in nuget

---

vnext/Chakra/ChakraJsiRuntime.cpp
vnext/Chakra/ChakraJsiRuntime.h
vnext/Desktop.IntegrationTests/ChakraJSIRuntimeHolder.cpp
vnext/Desktop.IntegrationTests/ChakraJSIRuntimeHolder.h
vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj.filters
vnext/ReactUWP/Base/ChakraJSIRuntimeHolder.cpp
vnext/ReactUWP/Base/ChakraJSIRuntimeHolder.h
vnext/ReactUWP/Base/UwpReactInstance.cpp
vnext/ReactUWP/ReactUWP.vcxproj
vnext/ReactUWP/ReactUWP.vcxproj.filters
vnext/ReactUWP/Utils/PropertyUtils.h
vnext/ReactUWP/Utils/ValueUtils.cpp
vnext/Shared/OInstance.cpp

We had already made most of the ground works required for enabling JSI workflow. This change switches the instanc to use the JSI workflow.

Switching UWP react native instance to use JSI

---

vnext/Desktop.IntegrationTests/CMakeLists.txt
vnext/ReactUWP/CMakeLists.txt

Adding a couple of missing files to CMakeLists.

Fixing cmake build after JSI switch

---

vnext/ReactUWP/Views/TextInputViewManager.cpp

copy paste error of some sorts in my perf & consistency change: https://github.com/microsoft/react-native-windows/commit/60aebbe985c7f29d23bf2eaed249535087cfcd3c

fix TextInput

---

vnext/ReactWindowsCore/dirs

add back dir I accidentally removed

internal build Fix

---

vnext/docs/ParityStatus.md

This status doc is an attempt at a clean, easy-to-read core parity status sheet. Information is presented in tables, broken up between components and modules and focused on the set of lean core items.
Fixes #2233

Core Parity Status Article

---

vnext/ReactWin32.nuspec
vnext/ReactWindows-CopyToStaging2.bat

Couple of extra files needed to move win32 to using the nuget

Add files needed for win32 nuget

---

vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/PropertySheets/DynamicLibrary/Release.props
vnext/package.json

Generate full debugging info in the pdbs

---

vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Folly/Folly.vcxproj
vnext/FollyWin32/FollyWin32.vcxproj
vnext/ReactCommon/ReactCommon.vcxproj
vnext/ReactUWP/EndPoints/dll/react-native-uwp.arm.def
vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def
vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86.def
vnext/Universal.SampleApp/HostingPane.xaml.cpp

Export dynamic::get_ptr

---

vnext/proposals/active/readme.md
vnext/proposals/archive/readme.md
vnext/proposals/readme.md

PR for adding new proposal processes related files and folder structures.

Adding proposal process files

---

current/local-cli/runWindows/utils/msbuildtools.js

Fix for #2420 - "Current" edition

[Current] Update msbuildtools.js with VS 2019 path

---

vnext/Folly/Folly.vcxproj
vnext/ReactCommon/ReactCommon.vcxproj
vnext/ReactUWP/ReactUWP.vcxproj
vnext/ReactWindowsCore/ReactWindowsCore.vcxproj

Fix nuget packages path

---

vnext/ReactUWP/Views/FrameworkElementViewManager.cpp

https://github.com/microsoft/react-native-windows/commit/6b27800bb2176e6939cc40116d539bea9853e1e7

port to 58: accessibility fixes for <View> to not have duplicate accessibility

---

vnext/ReactUwp.nuspec
vnext/ReactWin32.nuspec

Expose C++ types for LayoutAnimations so they can be used by the native platform.
Small alphabetization changes in the nuspec as well.

Add LayoutAnimation.h to nuget package spec

---

current/local-cli/rnpm/windows/package.json

semver.minUpdate was added in 5.7.0, so we need to update to at least that.

[CLI] Update to compatible version of semver

---

vnext/PropertySheets/React.Cpp.props

Use the same language standard for both Universal and Desktop variants.

Use C++ 2017 for Desktop projects.

---

vnext/package.json

"npm run watch" or "yarn watch" will automatically build typescript changes when you save.

Change watch script to use tsc directly

---

vnext/.editorconfig
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Directory.Build.props
vnext/Directory.Build.targets
vnext/Folly/Folly.vcxproj
vnext/FollyWin32/FollyWin32.vcxproj
vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
vnext/PropertySheets/React.Cpp.props
vnext/ReactCommon/ReactCommon.vcxproj
vnext/ReactUWP/ReactUWP.vcxproj
vnext/ReactWindows.sln
vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
vnext/Universal.IntegrationTests/React.Windows.Universal.IntegrationTests.vcxproj
vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj
vnext/Universal.UnitTests/React.Windows.Universal.UnitTests.vcxproj

- Remove redundant property and flag declarations.
- Fix Visual Studio IDE compatibility issue with x86 (Win32) builds.

Clean up MSBuild files

---

vnext/ReactUWP/Views/ViewManagerBase.cpp

back out onlayout noise reduction

---

current/ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
current/ReactWindows/ReactNative.Net46/packages.config
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.DLL/packages.config
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/packages.config
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop.UnitTests/packages.config
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/packages.config

Updating ChakraCore to version 1.11.10

---

.ado/publish.yml
.ado/updateVersion.js
.ado/versionUtils.js
vnext/ReactUWP/ReactUWP.vcxproj
vnext/ReactUWP/ReactUWP.vcxproj.filters
vnext/ReactUWP/Version.rc

Copies the win32 logic for version.rc and updating the file in the ado scripts

add version resource to react.uwp.dll

---

vnext/package.json
vnext/yarn.lock

```
b087e2fbf Applying package update to 0.59.0-microsoft.10
fba922e98 Added RN60 values for accessibilityRole and accessibilityStates (#99)
040cfd7c2 Applying package update to 0.59.0-microsoft.9
5d438bd67 remove duplicate file buid from build def (#101)
```

Update to react-native@0.59.0-microsoft.10

---

current/ReactWindows/Playground.Net46/App.config
current/ReactWindows/ReactNative.Net46.Tests/ReactNative.Net46.Tests.csproj
current/ReactWindows/ReactNative.Net46.Tests/app.config
current/ReactWindows/ReactNative.Net46.Tests/packages.config
current/ReactWindows/ReactNative.Net46/ReactNative.Net46.csproj
current/ReactWindows/ReactNative.Net46/app.config
current/ReactWindows/ReactNative.Net46/packages.config
current/ReactWindows/ReactNative/ReactNative.csproj

Updates to the latest version of Rx.Net

---

current/metro.config.js

fix(Metro): fixes hasteImpl path for v59

---

vnext/src/RNTester/FlyoutExample.uwp.tsx

This change adds some useful complexity to the Flyout example in the RNTester app.  For instance, I embedded a Picker in the Flyout and I enabled a nested Flyout to be launched from within the existing Flyout.

Flyout test

---

vnext/ReactUWP/Modules/DeviceInfoModule.cpp

Use Window::Current to get the window width/height

---

change/react-native-windows-2019-07-24-17-18-13-gettingstartedformatting.json
vnext/docs/GettingStarted.md

The indention of some of the getting started docs were confusing to readers.
Also publishing a change file for #2822 so it gets published (It went in before change file validation was part of CI)

Update formatting in GettingStarted doc

---

vnext/Universal.SampleApp/HostingPane.xaml.cpp
vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj
vnext/Universal.SampleApp/React.Windows.Universal.SampleApp.vcxproj.filters
vnext/Universal.SampleApp/calculator.uwp.js
vnext/docs/GettingStarted.md

* Added calculator.uwp.js sample app
* Updated UniversalS.ampleApp project with js files
* Updated GettingStarted to reflect the combobox change

Added Calculator sample to Universal.SampleApp

---

.ado/publish.yml

Move publish pipeline to public pool

---

.ado/windows-vs-pr.yml
package.json
yarn.lock

Update version of beachball to a version that provides an option to customize the string outputted when the build fails to find a required change file.

Provide more helpful instructions on how to generate change file

---

change/react-native-windows-2019-08-05-09-33-28-moreexport.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def

Put back a couple of win32 dll exports

---

change/react-native-windows-2019-08-08-16-46-21-viewacc.json
vnext/src/Libraries/Components/View/ViewAccessibility.uwp.js
vnext/src/Libraries/DeprecatedPropTypes/DeprecatedViewAccessibility.uwp.js

* This fixes the warnings when setting accessibilityRoles to list or listitem.

Added list, listitem roles to ViewAccessibility.uwp.js

---

change/react-native-windows-2019-08-10-21-53-58-runWindowsFormat.json
vnext/local-cli/runWindows/runWindows.js
vnext/local-cli/runWindows/utils/build.js
vnext/local-cli/runWindows/utils/commandWithProgress.js
vnext/local-cli/runWindows/utils/deploy.js
vnext/local-cli/runWindows/utils/msbuildtools.js
vnext/local-cli/runWindows/utils/winappdeploytool.js
vnext/package.json
yarn.lock

Currently the run-windows command appears to hang for a long period of time while its building, and its not obvious that anything is happening.
This change adds some progress UI to the command so that its easier to see whats going on.

Improve UI of run-windows command

---

change/react-native-windows-2019-08-19-11-07-16-andrewh-msofollyupdate.json
vnext/Desktop/msoFolly.h

add warning 4127 to disable list (conditional expression is constant).
soon this file won't be in RNW, but until that change in devmain happens putting this in...

Add new warning to MsoFolly.h

---

.ado/evergreen.js
.github/workflows/evergreen.yml
.github/workflows/pr.yml

Start evergreen script

---

.ado/setVersionEnvVars.js
.github/workflows/publish.yml
change/react-native-windows-2019-08-23-21-20-05-fixchangelog.json
vnext/CHANGELOG.md

Fix change log formatting

---

change/react-native-windows-2019-08-24-05-33-46-auto-update-versions059.0microsoft.67.json
change/react-native-windows-extended-2019-08-24-05-33-48-auto-update-versions059.0microsoft.67.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json
yarn.lock

```
ffdf6bf9e Applying package update to 0.59.0-microsoft.67 ***NO_CI***
041fb2303 update react-native-windows on publish
0afcec7e1 Applying package update to 0.59.0-microsoft.66 ***NO_CI***
e9832f344 update publish
439cb9436 Applying package update to 0.59.0-microsoft.65 ***NO_CI***
08bcd9dd0 update publish
6da09af0e update publish
ee312617d Applying package update to 0.59.0-microsoft.64 ***NO_CI***
30a6b397f update publish
5be571af4 update publish
d4f7f8c2e Merge branch 'publish-temp-1566592026049'
9cf077687 Applying package update to 0.59.0-microsoft.63 ***NO_CI***
c41ee614a update publish
72d6c35df Applying package update to 0.59.0-microsoft.62 ***NO_CI***
b4a323770 Applying package …
```

Update to react-native@0.59.0-microsoft.67

---

.ado/windows-vs-pr.yml
.github/workflows/pr.yml
change/react-native-windows-2019-08-27-16-33-11-vsgoogleut.json
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/JSI.Desktop.UnitTests/packages.config
vnext/Scripts/IntegrationTests.ps1

Use `Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn` to reduce third-party depdendency footprint, and closely reflect out of the box VS Google Test projects.

Use package Microsoft Google Test package

---

.github/ISSUE_TEMPLATE/react-native-windows--vnext--bug-report.md
.github/ISSUE_TEMPLATE/react-native-windows--vnext--feature-request.md

Remove [BUG] and [PROPOSAL] prefixes. These exist as labels.

Update issue templates

---

.github/workflows/pr.yml

Fix typo in .github/workflows/pr.yml

---

change/react-native-windows-2019-09-03-10-08-01-htpiv-fix-consistent-this.json
vnext/src/RNTester/AlertExample.windows.tsx

This makes ESLint happy so `yarn build` in vnext runs without warnings.

Change `_this` to `that` to match ESList consistent-this rules.

---

.ado/publish.yml
.ado/setVersionEnvVars.js
.github/workflows/publish.yml

Move publish build to Azure Dev Ops

---

.ado/windows-vs-pr.yml

merge E2E job to windows-vs-pr.yml

---

.ado/publish.yml

Run Desktop and Universal Publish builds in parallel.

[DRAFT] Fix Publish definition

---

.ado/publish.yml
.ado/templates/e2e-test-job.yml
.ado/windows-vs-pr.yml

Ensure `.ado` contents are identical.

Sync pipelines scripts with latest master

---

packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json

Ensures latest version is `0.59-vnext.191`.

Bump up to latest published version.

---

change/react-native-windows-2019-09-27-16-38-47-backport-0.59-publishfix5.json
change/react-native-windows-extended-2019-09-27-16-38-47-backport-0.59-publishfix5.json

Add missing change files

---

.ado/windows-vs-pr.yml
change/react-native-windows-2019-09-30-17-01-19-59pr.json
change/react-native-windows-extended-2019-09-30-17-01-19-59pr.json
vnext/Scripts/Tfs/Layout-Headers.ps1

Enable PR verification against 0.59-vnext-stable branch

---

change/react-native-windows-2019-10-01-13-20-27-BorderRadiusFix-Branch.json
change/react-native-windows-extended-2019-10-01-13-20-27-BorderRadiusFix-Branch.json
vnext/ReactUWP/Utils/PropertyUtils.h
vnext/ReactUWP/Views/ViewViewManager.cpp

Fix borderRadius property updates.

---

change/react-native-windows-2019-10-03-17-04-51-updatern.json
change/react-native-windows-extended-2019-10-03-17-04-51-updatern.json
packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json
yarn.lock

Update to react-native@0.60.0-microsoft.3

---

change/react-native-windows-2019-10-03-16-35-26-delayloadcd.json
package.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj

Delay load ChakraCore.Debugger.DLL

---

change/react-native-windows-2019-10-04-15-51-01-jsi-v8upgrade.json
vnext/ReactUWP/ReactUWP.vcxproj
vnext/ReactUWP/packages.config
vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
vnext/ReactWindowsCore/packages.config
vnext/Shared/OInstance.cpp

- Update the package version of V8 to 0.1.4;
- Also fixes a small bug in V8 / Hermes (which are turned off by default);

Update V8JSI package version

---

change/react-native-windows-2019-10-06-16-38-36-chakraheaders.json
vnext/Scripts/Tfs/Layout-Headers.ps1

Include some chakra headers in win32 nuget

---

vnext/README.md

(Also testing the CI look to validate markdown changes skip most of the CI)

Update version number in vnext\README.md

---

change/react-native-windows-2019-10-09-03-35-04-auto-update-versions060.0microsoft.5.json
change/react-native-windows-extended-2019-10-09-03-35-06-auto-update-versions060.0microsoft.5.json
packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json

```
45f88420d Applying package update to 0.60.0-microsoft.5 ***NO_CI***
fa774e30e Fix typo (#171)
25fab075e Applying package update to 0.60.0-microsoft.4 ***NO_CI***
7316be1e6 Remove merge conflict artifacts (#170)
```

Update to react-native@0.60.0-microsoft.5

---

change/react-native-windows-2019-10-02-15-46-17-ForeverRepeatingAnimations.json
vnext/ReactUWP/Modules/Animated/DecayAnimationDriver.cpp
vnext/ReactUWP/Modules/Animated/FrameAnimationDriver.cpp
vnext/ReactUWP/Modules/Animated/SpringAnimationDriver.cpp

Add support for forever animations.

---

change/react-native-windows-2019-10-09-17-44-22-user-savatia-debugger-waiting-page.json
vnext/ReactUWP/Base/UwpReactInstance.cpp
vnext/ReactUWP/Base/UwpReactInstance.h
vnext/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp
vnext/ReactUWP/Executors/WebSocketJSExecutorUwp.h
vnext/ReactUWP/Modules/DevSupportManagerUwp.cpp
vnext/ReactUWP/Views/ReactControl.cpp
vnext/ReactUWP/Views/ReactControl.h
vnext/ReactWindowsCore/DevSettings.h
vnext/include/ReactUWP/IReactInstance.h

Create a page which displays the "Connecting to remote debugger" message while the VS Code debugger attempts to connect to the debugger proxy socket.
FIX: #3179

[VS Code] Create a "Connecting to remote debugger" page

---

.ado/e2e-test.yml
.ado/evergreen.yml
.ado/publish.yml
.ado/templates/build-rnw.yml
.ado/templates/e2e-test-job.yml
.ado/windows-vs-pr.yml
change/react-native-windows-2019-10-10-19-40-16-azure-pipes-uwptov141-0.59.json
current/local-cli/runWindows/utils/msbuildtools.js
packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleApp.vcxproj
vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
vnext/docs/GettingStarted.md
vnext/local-cli/runWindows/utils/msbuildtools.js

[0.59] Use v141 for Universal builds.

---

.ado/templates/build-rnw.yml
.ado/templates/e2e-test-job.yml
change/react-native-windows-2019-10-11-01-10-39-lintfixmsbuildjs-0.59.json
current/local-cli/runWindows/utils/msbuildtools.js
vnext/local-cli/runWindows/utils/msbuildtools.js

Fixes Publish definition.
See #3393

[0.59] Add missing ; to msbuild arg statement.

---

.ado/templates/build-rnw.yml
.ado/templates/e2e-test-job.yml
.ado/templates/react-native-init.yml
change/react-native-windows-2019-10-10-21-54-36-lintfixmsbuildjs.json
current/local-cli/runWindows/utils/msbuildtools.js
vnext/local-cli/runWindows/utils/msbuildtools.js

Add missing ; to msbuild arg statement.

---

change/react-native-windows-2019-10-14-15-48-03-adam-newexcep.json
vnext/Desktop/JSBigStringResourceDll.cpp
vnext/Desktop/Sandbox/SandboxJSExecutor.cpp
vnext/ReactUWP/Modules/Animated/NativeAnimatedNodeManager.cpp

You shouldn't new up exceptions in c++.  
#3364 
This likely a small memory leak.

Don't new up C++ exceptions

---

change/react-native-windows-2019-10-14-16-10-56-measureInWindow.json
packages/E2ETest/app/Consts.ts
packages/E2ETest/app/DirectManipulationPage.tsx
packages/E2ETest/app/TestPages.ts
packages/E2ETest/wdio/pages/DirectManipulationPage.ts
packages/E2ETest/wdio/pages/HomePage.ts
packages/E2ETest/wdio/test/DirectManipulation.spec.ts
vnext/IntegrationTests/TestInstance.cpp
vnext/IntegrationTests/TestInstance.h
vnext/ReactUWP/Modules/NativeUIManager.cpp
vnext/ReactUWP/Modules/NativeUIManager.h
vnext/ReactWindowsCore/INativeUIManager.h
vnext/ReactWindowsCore/IUIManager.h
vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
vnext/ReactWindowsCore/Modules/UIManagerModule.h
vnext/docs/api/react-native-windows.iviewwindowsprops.md

implement measureInWindow

---

packages/playground/README.md
vnext/docs/GettingStarted.md

Update Playground readme

---

change/react-native-windows-2019-10-31-14-49-39-nitFixes.json
vnext/JSI/Shared/ChakraRuntime.cpp
vnext/JSI/Shared/ChakraRuntime.h

I accidentally checked in #3568 before addressing all nit comments. This PR contains some small renaming and best practice changes.

Fix some nit suggestions from PR #3568.

---

change/react-native-windows-2019-11-05-13-01-59-viewmanager3565.json
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.h
vnext/Microsoft.ReactNative.SharedManaged/AttributedViewManager.cs
vnext/Microsoft.ReactNative/ABIViewManager.cpp
vnext/Microsoft.ReactNative/ABIViewManager.h
vnext/Microsoft.ReactNative/IViewManager.idl

This makes it easier to only implement the ViewManager features you need.

VM: Split up IViewManager into optional interfaces #3565

---

change/react-native-windows-2019-11-08-15-42-24-nmsetupdocs.json
packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
vnext/docs/GettingStarted.md
vnext/docs/NativeModules.md
vnext/docs/NativeModulesAdvanced.md
vnext/docs/NativeModulesSetup.md
vnext/docs/ProjectStructure.md
vnext/docs/ViewManagers.md
vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.sln
vnext/local-cli/generator-windows/templates/cs/proj/MyApp.sln

* Added NativeModuleSetup.md, #3623
* Added link to new guide in NativeModules.md, ViewManagers.md
* Updated ProjectStructure.md with Microsoft.ReactNative projects
* Removed PropertySheets in SampleApps and CLI solutions

Native Module Setup Guide

---

change/react-native-windows-2019-11-11-13-36-35-nmdocfixes.json
vnext/docs/NativeModules.md
vnext/docs/NativeModulesAdvanced.md
vnext/docs/NativeModulesSetup.md
vnext/docs/ViewManagers.md

In following the docs to build the Native Modules samples, found some issues that needing addressing.

Native Module doc fixes.

---

change/react-native-windows-2019-11-19-21-29-44-auto-update-versions060.0microsoft.21.json
change/react-native-windows-extended-2019-11-19-21-29-45-auto-update-versions060.0microsoft.21.json
packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json

```
2ab4c5b2d Applying package update to 0.60.0-microsoft.21 ***NO_CI***
6190bbcfe Remove deleted file from cmake build def (#192)
```

Update to react-native@0.60.0-microsoft.21

---

change/react-native-windows-2019-11-20-17-48-58-auto-update-versions060.0microsoft.22.json
change/react-native-windows-extended-2019-11-20-17-48-59-auto-update-versions060.0microsoft.22.json
packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-extended/package.json
vnext/package.json

```
530240041 Applying package update to 0.60.0-microsoft.22 ***NO_CI***
a330e8a59 Change projectRoot for internal yarn migration (#193)
```

Update to react-native@0.60.0-microsoft.22

---

.lintstagedrc.json
package.json
packages/scripts/formatFiles.js
yarn.lock

It's output seems to not always agree with yarn format. Disable it
temporarily to investigate what's going wrong.

Directly run "yarn format" as pre-commit hook instead of using lint-staged

---

vnext/docs/ParityStatus.md

Marking text component parity as complete

---

change/react-native-windows-2019-12-20-12-33-14-master.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def

Export ability to query names of loaded native modules (master branch)

---

change/react-native-windows-2020-01-07-15-23-05-netnativeissues.json
packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/Properties/Default.rd.xml
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CircleViewManagerCPP.h
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.h
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/ReactPackageProvider.cpp
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/CustomUserControlViewManagerCS.cs
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
vnext/Microsoft.ReactNative.SharedManaged/AttributedViewManager.cs
vnext/Microsoft.ReactNative.SharedManaged/ReactPackageBuilderExtensions.cs
vnext/Microsoft.ReactNative/ABIViewManager.cpp
vnext/Microsoft.ReactNative/ABIViewManager.h
vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
vnext/Microsoft.ReactNative/IViewManager.idl
vnext/Microsoft.ReactNative/ViewManagersProvider.cpp
vnext/docs/NativeModulesSetup.md
vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.sln
vnext/local-cli/generator-windows/templates/cs/proj/MyApp.sln
vnext/local-cli/generator-windows/templates/cs/src/Properties/Default.rd.xml

* Fixed issue with reacontcontext getting optimized away, #3770
* Removing ReactUWP from CLI template and native module setup docs, issue #3839

Fixing bugs when using .NetNative

---

change/react-native-windows-2020-01-08-15-45-49-nmobjectevents.json
vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs

Added unit tests for Events with JSValue args

---

change/react-native-windows-2020-01-13-09-59-10-fixrntester.json
vnext/src/RNTester/js/RNTesterApp.windows.tsx
vnext/src/RNTester/js/RNTesterList.windows.ts

Fixes RNTester pages

---

change/react-native-windows-2020-01-16-17-55-30-openssl-1.1.1d_2.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.DLL/packages.config
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/packages.config
vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
vnext/Desktop.Test.DLL/packages.config
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop.UnitTests/packages.config
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/packages.config
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/JSI.Desktop.UnitTests/packages.config
vnext/Test/React.Windows.Test.vcxproj
vnext/Test/packages.config

Upgrade to OpenSSL NuGet 1.1.1d.2

---

change/react-native-windows-2020-01-16-17-55-23-openssl-1.1.1d-v0.59_2.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.DLL/packages.config
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/packages.config
vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
vnext/Desktop.Test.DLL/packages.config
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop.UnitTests/packages.config
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/packages.config
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/JSI.Desktop.UnitTests/packages.config
vnext/Test/React.Windows.Test.vcxproj
vnext/Test/packages.config

[v0.59] Upgrade to OpenSSL NuGet 1.1.1d.2

---

.ado/windows-vs-pr.yml

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=60011&view=logs&jobId=a27d21fd-a31d-5038-a902-0ee58cd3b281&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=6750b87c-c5d0-5ba3-de8e-6dea356eee8d 
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=59770&view=logs&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=7b7d0d63-12e1-5775-f391-1b5cc927ea74

Disable E2E test

---

change/react-native-windows-2020-01-29-15-06-51-0.59-vnext-stable.json

Trigger new package version for #3978

---

.ado/windows-vs-pr.yml

Enable the PR Pipeline for 0.60-stable

---

change/react-native-windows-2020-01-24-13-20-31-appearance.json
vnext/ReactUWP/Base/UwpReactInstance.cpp
vnext/ReactUWP/Base/UwpReactInstance.h
vnext/ReactUWP/Modules/DeviceInfoModule.cpp
vnext/ReactUWP/Modules/DeviceInfoModule.h

Cherry-pick f707d2178a57d8f6375a954d827b243c3b031d08 from master.

cherry-pick DeviceInfo fix

---

vnext/docs/NativeModules.md
vnext/docs/NativeModulesSetup.md

Recently went through the native module setup process, fixing a few minor issues in the doc.

Update native module docs

---

change/@office-iss-react-native-win32-2020-02-04-11-24-03-a11yinfowin32v60.json
packages/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
packages/react-native-win32/src/Libraries/Components/UnimplementedStubs/AccessibilityInfo.win32.ts
packages/react-native-win32/src/RNTester/APIExamples/AccessibilityExampleWin32.tsx

Adds AccesibilityInfo for use in Office

Add AccessibilityInfo NativeModule to react-native-win32 (0.60-stable)

---

change/@office-iss-react-native-win32-2020-02-04-14-59-09-Picker.json
packages/react-native-win32/.flowconfig
packages/react-native-win32/src/Libraries/Components/Picker/Picker.win32.tsx
packages/react-native-win32/src/RNTester/js/RNTesterList.win32.ts

This is a cherry-pick for commit 5c288b63bdade1bbeb2fa26e188c8febe4bb990a from the `master` branch.

Implement Picker component (#4028)

---

.ado/shouldSkipPRBuild.ps1
change/react-native-windows-2020-02-10-18-38-20-docs-61.json
vnext/docs/ConsumingRNW.md

Update ConsumeRNW.md with 0.61 info

---

change/@office-iss-react-native-win32-2020-02-11-16-36-54-exportpersonacoin.json
packages/react-native-win32/etc/react-native-win32.api.md
packages/react-native-win32/src/Libraries/react-native/react-native-implementation.win32.ts
packages/react-native-win32/src/Libraries/react-native/typings-main.ts

PersonaCoin is not being exported from react-native-win32

---

change/@office-iss-react-native-win32-2020-02-11-16-44-13-expcoin.json
packages/react-native-win32/etc/react-native-win32.api.md
packages/react-native-win32/src/Libraries/react-native/react-native-implementation.win32.ts
packages/react-native-win32/src/Libraries/react-native/typings-main.ts
yarn.lock

Export PersonaCoin from react-native-win32

---

change/@office-iss-react-native-win32-2020-02-11-21-58-23-fixcoin.json
packages/react-native-win32/etc/react-native-win32.api.md
packages/react-native-win32/src/Libraries/PersonaCoin/PersonaCoin.tsx
packages/react-native-win32/src/Libraries/react-native/react-native-implementation.win32.ts

Do not use default export to export PersonaCoin, and export PersonCoinTypes correctly

---

change/react-native-windows-2020-02-04-18-42-20-user-kaiguo-add-measurelayout.json
packages/E2ETest/app/Consts.ts
packages/E2ETest/app/DirectManipulationPage.tsx
packages/E2ETest/wdio/pages/DirectManipulationPage.ts
packages/E2ETest/wdio/test/DirectManipulation.spec.ts
vnext/IntegrationTests/TestInstance.cpp
vnext/IntegrationTests/TestInstance.h
vnext/ReactUWP/Modules/NativeUIManager.cpp
vnext/ReactUWP/Modules/NativeUIManager.h
vnext/ReactWindowsCore/INativeUIManager.h
vnext/ReactWindowsCore/IUIManager.h
vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
vnext/ReactWindowsCore/Modules/UIManagerModule.h

Fix #3805.
Added measureLayout implementation which is currently missing.

Implement measureLayout

---

.github/ISSUE_TEMPLATE/react-native-windows--vnext--module-request.md

Adding a standardized template for tracking modules that don't yet have RNW support but are requested.

Add module request issue template

---

change/react-native-windows-2020-02-14-12-49-08-deps-openssl-revertto102p.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
vnext/Desktop.DLL/packages.config
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/packages.config
vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
vnext/Desktop.Test.DLL/packages.config
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop.UnitTests/packages.config
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/packages.config
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/JSI.Desktop.UnitTests/packages.config
vnext/Test/React.Windows.Test.vcxproj
vnext/Test/packages.config

* Downngraded OpenSSL to 1.0.2-p.2.
* Change files

Downgrade OpenSSL to version 1.0.2p (#4105)

---

change/react-native-windows-2020-02-14-16-56-53-users-aschultz-build.json
vnext/PropertySheets/ReactPackageDirectories.props
vnext/ReactUWP/ReactUWP.vcxproj

Fix for NormalizePath resolving IntDir based on current working directory

---

change/react-native-windows-2020-02-06-10-15-05-accessibilityLiveRegionFix.json
vnext/ReactUWP/Views/FrameworkElementViewManager.cpp

To bring this into the 0.60 branch.

Enable screen reader announcements for accessibilityLiveRegion (#4043)

---

current/docs/CoreParityStatus.md

CoreParityStatus.md: fixed last row rendering

---

change/react-native-windows-2020-02-25-17-28-33-minor-fix.json
vnext/ReactUWP/Views/ShadowNodeBase.cpp

PR #4169 got auto merged before I saw the [last comment](https://github.com/microsoft/react-native-windows/pull/4169#discussion_r384085795). Very minor updates to address the comment.

Minor update for #4169

---

change/react-native-windows-2020-02-18-17-30-23-networking-assert.json
change/react-native-windows-2020-02-25-11-16-19-networkingmodulefix.json
vnext/ReactUWP/Modules/NetworkingModule.cpp

Porting down NetworkingModule fixes

---

README.md

Updated the React Native Website URL

---

change/react-native-windows-2020-02-25-11-32-44-tabindex.json
change/react-native-windows-2020-02-27-11-28-17-textinput.tabindex.json
vnext/ReactUWP/Views/ControlViewManager.cpp
vnext/ReactUWP/Views/TextInputViewManager.cpp
vnext/ReactUWP/Views/ViewViewManager.cpp

Cherry-pick tabIndex fixes from master

---

packages/override-tools/src/Manifest.ts
packages/override-tools/src/test/Manifest.test.ts
packages/override-tools/src/test/MockFileRepository.ts

Add UTs for recently added Manifest APIs. Normalize paths and do deep clones in more places for robustnes.

Add more manifest unit tests

---

README.md

This link is referencing a file that does not exist.

fix broken link for 'Windows 10 Compatability'

---

change/react-native-windows-2020-03-06-10-21-43-fixincludefilters.json
vnext/include/Include.vcxitems.filters

Minor change to fix a filter file, so VS doesn't do the wrong thing.

Clean up vnext/include/Include.vcxitems.filters

---

change/react-native-windows-2020-03-06-17-26-22-add-helpers.json
vnext/Microsoft.ReactNative.Cxx/JSValueXaml.h
vnext/Microsoft.ReactNative/XamlHelper.cpp
vnext/Microsoft.ReactNative/XamlHelper.h
vnext/Microsoft.ReactNative/XamlHelper.idl

Adding 2 more helpers in XamlHelper, which will be used in community modules.

Add more helpers in XamlHelper

---

vnext/README.md

- Removed vnext mentions
- Updated links to rnw website and getting started pages
- Cleaned up general format
- Linked to landing page README
- Addresses issue #4191 and #4264

Update to vnext subfolder README.md file

---

change/react-native-windows-2020-03-18-11-51-07-fix-event-emitter-typing.json
vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.ts
yarn.lock

Supersedes #4323.
Additionally fixes incorrect usage due to previous incorrect definition.

[typings] Update RN types and fix related type usage.

---

.ado/publish.yml
.ado/windows-vs-pr.yml

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#wildcards documents the ability to use wildcards when specifying branches to include for triggers. Using them means we don't need to make changes to CI logic when branching to a stable release (and the headache of figuring out which branch the changes go in).

Use Wildcards for PR and Publish Triggers of Stable Branches

---

change/react-native-windows-2020-03-20-14-50-01-master.json
vnext/Desktop/packages.config
vnext/JSI.Desktop.UnitTests/JsiRuntimeUnitTests.cpp
vnext/PropertySheets/React.Cpp.props
vnext/ReactWindowsCore/packages.config

Update to the latest V8 package which include version 8.1 of V8, the latest JSI headers from Hermes master and a few bug fixes.

Update V8 package

---

change/react-native-windows-2020-03-24-11-22-29-acoates-loadfix.json
vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp

Cherry-pick #4402 into 0.61 (Do not enter loaded state when an error occurs during web bundle loadJSBundles )

---

change/@office-iss-react-native-win32-2020-03-28-15-37-50-tsupd.json
change/react-native-windows-2020-03-28-15-37-50-tsupd.json
change/react-native-windows-init-2020-03-28-15-37-50-tsupd.json
packages/E2ETest/package.json
packages/override-tools/package.json
packages/react-native-win32/package.json
packages/react-native-windows-init/package.json
vnext/package.json
vnext/src/Libraries/Components/Keyboard/KeyboardExt.tsx
yarn.lock

Update typescript version to 3.8.3

---

change/react-native-windows-2020-03-31-09-49-09-fix-asmw32-multiremove.json
vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.cpp
vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.h
vnext/ReactWindowsCore/ReactWindowsCore.vcxproj

1. Respond to feedback from Vladimir in PR #4456 that was accidentally not applied before merging
2. Fix a dumb bug in multiRemove; I forgot to bind the query parameters so nothing ever gets removed actually.

Fix asmw32 multiremove

---

.ado/setVersionEnvVars.js

Handle publishing versions without pre-release versions

---

.vscode/launch.json
change/@office-iss-react-native-win32-2020-04-03-08-40-03-win32sm.json
packages/react-native-win32/package.json

Generate sourcemap for offline RNTester bundle in win32

---

packages/playground/README.md

Minor formatting proposals

---

change/react-native-windows-2020-04-06-10-11-22-master.json
vnext/Desktop/packages.config
vnext/PropertySheets/React.Cpp.props
vnext/ReactWindowsCore/packages.config

Latest version includes Control Flow Guard (CFG) turned on for release builds and a bunch of warnings fixed / re-enabled.

Update V8 package version

---

.ado/templates/prepare-env.yml
.ado/variables/vs2019.yml

windows-2019 VMs were updated, fixing the CI with select changes from commit dd225633351d3119731b9b07ebbf4bc638e9e2d4

Fixing CI for 60-stable

---

.ado/templates/e2e-test-job.yml

This task takes some ~6 min and does not appear to be necessary anymore.

Remove 'Delete Android SDK' from E2ETest

---

change/react-native-windows-2020-04-11-00-42-10-winrtws-0.61.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
vnext/Desktop/BeastWebSocketResource.cpp
vnext/Desktop/BeastWebSocketResource.h
vnext/Desktop/Executors/WebSocketJSExecutor.cpp
vnext/Desktop/Executors/WebSocketJSExecutor.h
vnext/Desktop/Modules/WebSocketModule.cpp
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/React.Windows.Desktop.vcxproj.filters
vnext/Desktop/WebSocketResourceFactory.cpp
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/ReactWindows-Desktop.sln
vnext/ReactWindowsCore/IWebSocketResource.h
vnext/ReactWindowsCore/Modules/WebSocketModule.h
vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
vnext/ReactWindowsCore/WinRTWebSocketResource.h
vnext/Shared/OInstance.cpp

Ports new WebSocketResource implmentation from `master` branch.

[0.61] Implement WinRTWebSocketResource

---

change/react-native-windows-2020-04-14-22-41-42-PasswordBoxBug.json
packages/playground/Samples/textinput.tsx
vnext/ReactUWP/Modules/NativeUIManager.cpp
vnext/ReactUWP/Views/ShadowNodeBase.cpp
vnext/include/Include.vcxitems.filters

cherry-pick 5ec607d93ba3daf586ed07cf9f18f65ba6262683 from master

Password box bug (#4607)

---

.ado/templates/prep-and-pack-nuget.yml

This will give us more info to address #3889

Add nuget pack logging to figure out why we fail when we do

---

change/@office-iss-react-native-win32-2020-04-27-09-42-09-uprex.json
packages/react-native-win32/package.json
yarn.lock

Update rex-win32 version to something more recent

---

package.json
yarn.lock

Fixes husky missing error

---

change/react-native-windows-2020-04-30-16-10-37-master.json
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/CustomUserControlViewManagerCS.cs
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
vnext/Microsoft.ReactNative.SharedManaged/ReactContextGenerator.cs
vnext/Microsoft.ReactNative.SharedManaged/ReactSyncMethodInfo.cs

Minor cleanup: Remove unused namespace from C# files

---

change/react-native-windows-2020-05-01-15-34-56-master.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj

Port the same change from master

Delay load ChakraCore.dll (0.60)

---

.ado/templates/react-native-init.yml

Kill verdacio server before uploading logs and name artifact by job

---

change/react-native-windows-2020-05-01-15-34-56-master.json
vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj

Delay load ChakraCore.dll (0.61)

---

change/react-native-windows-2020-05-05-17-17-21-dontDeleteInstalledNuget.json
vnext/local-cli/runWindows/utils/build.js

Skip deleting nuget.exe if we didn't download it ourselves

Don't delete nuget.exe if using locally-installed (e.g. chocolatey)

---

change/react-native-windows-2020-05-05-22-41-31-msbuilt.json
vnext/local-cli/runWindows/utils/msbuildtools.js

[Trivial] Fix typo in msbuildtools.js

---

change/react-native-windows-2020-05-06-14-46-56-Issue4792.json
vnext/Microsoft.ReactNative.IntegrationTests/TestBundle.targets

Fix publish pipeline

---

change/react-native-windows-2020-05-07-17-34-52-master.json
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleLibraryCS.csproj
vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj

Set C# langversion of templates back to 7.3 from 8.0

---

change/react-native-windows-2020-05-13-12-53-42-hook-lifecycle-events.json
change/react-native-windows-2020-05-13-12-53-42-remove-unused-lifecycle-events.json
vnext/Microsoft.ReactNative/ReactApplicationDelegate.cpp
vnext/Microsoft.ReactNative/ReactNativeHost.cpp
vnext/Microsoft.ReactNative/ReactNativeHost.h
vnext/Microsoft.ReactNative/ReactNativeHost.idl

Remove those unused callbacks to avoid future confusion.

Remove unused life cycle event callbacks in ReactNativeHost

---

change/react-native-windows-2020-05-08-17-28-25-winui3AppTemplateCPP_2.json
change/react-native-windows-init-2020-05-08-17-28-25-winui3AppTemplateCPP_2.json
packages/react-native-windows-init/src/Cli.ts
vnext/ReactWindows-Universal.sln
vnext/local-cli/generate-windows.js
vnext/local-cli/generator-windows/index.js
vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
vnext/local-cli/generator-windows/templates/cpp/proj/packages.config
vnext/local-cli/generator-windows/templates/cpp/src/pch.h

winui3 option for app project template (and update C++ template)

---

change/react-native-windows-2020-05-14-13-47-03-4881.json
vnext/local-cli/runWindows/utils/deploy.js

Some projects have target instead of bin folders

---

change/react-native-windows-2020-05-18-17-40-44-master.json
vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
vnext/local-cli/generator-windows/templates/cs/proj/MyApp.sln
vnext/local-cli/generator-windows/templates/cs/src/App.xaml.cs

Update the react-native-windows-init template to use the managed library the default (instead of the shared csproj file).

---

.ado/templates/react-native-init.yml
.gitignore

Update CI pipeline to upload msbuild binary log file

---

change/react-native-windows-2020-05-21-10-41-46-master.json
packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleLibraryCS.csproj
vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj

Standardize version of Microsoft.NETCore.UniversalWindowsPlatform to 6.2.9

---

change/react-native-windows-2020-05-21-12-12-34-master.json
vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj

Remove unneeded reference form Microsoft.ReactNative.Managed

---

docs/contributing.md

Add info about yarn format to contribution docs.

---

.ado/publish.yml
.ado/templates/prepare-env.yml
.ado/templates/react-native-init.yml
.ado/templates/yarn-install.yml
.ado/windows-vs-pr.yml
packages/E2ETest/wdio/test/testInput.spec.ts

Not ideal, but nor is us having such a high failure rate on the current E2E tests.

Attempt to fix intermittent failures in E2E tests

---

change/react-native-windows-2020-05-28-13-51-33-longpaths.json
vnext/Scripts/rnw-dependencies.ps1

Add support for long paths to rnw-dependencies.ps1

---

change/react-native-windows-2020-05-28-13-03-51-issue5041.json
vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj

Fixes CLI C# app not deploying

---

.ado/templates/e2e-test-job.yml
packages/E2ETest/app/Consts.ts
packages/E2ETest/app/TextInputTestPage.tsx
packages/E2ETest/run_wdio.js
packages/E2ETest/wdio.conf.js
packages/E2ETest/wdio/pages/BasePage.ts
packages/E2ETest/wdio/pages/TextInputTestPage.ts
packages/E2ETest/wdio/test/testInput.spec.ts
packages/E2ETest/windows/ReactUWPTestApp/App.xaml

[Work in progress, will keep running CI to see if this helps things any]
- Moved creation of errorShots directory to be part of the E2E script, so that error screenshots can be properly created when running the tests locally
- Forced the app to run in light mode so that the tests pass locally when run on a machine that's in dark mode
- Modified the TextInput test to view more events, since the order of the events is not guaranteed, and was causing some failures.

More attempts at making E2E test more reliable

---

docs/contributing.md

Add info about yarn api in contributing.md

---

change/react-native-windows-2020-06-01-16-06-42-master.json
packages/E2ETest/app/ImageTestPage.tsx
packages/E2ETest/run_wdio.js
packages/E2ETest/wdio/pages/BasePage.ts
packages/E2ETest/wdio/test/Image.spec.ts
packages/E2ETest/wdio/test/login.spec.ts
vnext/local-cli/runWindows/utils/build.js
vnext/local-cli/runWindows/utils/winappdeploytool.js
vnext/src/RNTester/js/RNTesterApp.windows.js
vnext/src/RNTester/js/examples/View/ViewExample.windows.js

> Note: Did not fix every one. There were a few in the controls section that I wasn't sure about if they would affect the behavior.

Code Cleanup: Some low hanging fruit lint fixes

---

change/react-native-windows-2020-06-05-15-09-16-installMSBLV.json
vnext/Scripts/rnw-dependencies.ps1

Add the log viewer as a dependency in rnw-dependencies

Install MSBuild structured log viewer

---

change/react-native-windows-2020-05-29-12-49-23-proxy_prop.json
vnext/Microsoft.ReactNative/ReactApplication.cpp
vnext/local-cli/runWindows/runWindows.js
vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
vnext/local-cli/runWindows/utils/deploy.js

Implement --remote-debugging flag in CLI

---

yarn.lock

[0.61] Bump beachball from 1.31.0 to 1.31.1 (#4988)

---

docs/managedCodeGen.md

Add documentation page for Managed CodeGen for Native Modules

---

.ado/windows-vs-pr.yml
change/react-native-windows-2020-06-11-13-06-37-msrncxxnuget.json
vnext/Scripts/Microsoft.ReactNative.nuspec
vnext/Scripts/ReactWin32.nuspec
vnext/Scripts/Tfs/Layout-Headers.ps1

[0.62] Add Microsoft.ReactNative.Cxx to the nuget package 

---

packages/E2ETest/app/Consts.ts
packages/E2ETest/app/TextInputTestPage.tsx
packages/E2ETest/wdio/pages/TextInputTestPage.ts
packages/E2ETest/wdio/test/testInput.spec.ts
packages/playground/windows/playground/MainPage.cpp

Another try at fixing textinput e2e test

---

change/react-native-windows-2020-06-11-02-43-42-rnwdep0611.json
vnext/Scripts/rnw-dependencies.ps1

Add more required workloads for VS for rnw-dependencies

---

change/react-native-windows-2020-06-16-22-18-15-pull_request.json
vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp

- Apply Method and m_field casing to `SampleTurboModule` members.

Apply compatible casing on SampleTurboModule members

---

.ado/windows-vs-pr.yml

Reenable WebSocket tests in PR

---

.ado/templates/yarn-install.yml

Update midgard-yarn to later version and give it a private yarn cache

---

.ado/templates/build-rnw.yml

Improve msbuild logging for universal and desktop build

---

change/react-native-windows-2020-06-26-10-31-10-master.json
vnext/Scripts/rnw-dependencies.ps1

Add Enterprise vs2019 support to rnw-dependencies

---

.ado/publish.yml
.ado/setVersionEnvVars.js
.ado/templates/prep-and-pack-nuget.yml
.ado/templates/react-native-init.yml
.ado/windows-vs-pr.yml
.github/workflows/pr.yml
.github/workflows/publish.yml
change/react-native-windows-2020-06-26-12-02-44-master.json
change/react-native-windows-init-2020-06-26-12-02-44-master.json
docs/managedCodeGen.md
docs/react-native-windows-init.md
packages/react-native-windows-init/src/Cli.ts
vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
vnext/Microsoft.ReactNative.Managed.CodeGen/App.cs
vnext/PropertySheets/ManagedCodeGen/Microsoft.ReactNative.Managed.CodeGen.targets
vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
vnext/local-cli/generate-windows.js
vnext/local-cli/generator-windows/index.js

 Fix casing typos in NuGet and MSBuild

---

.github/workflows/pr.yml
change/@office-iss-react-native-win32-2020-06-26-19-29-32-master.json
change/react-native-windows-2020-06-26-19-29-32-master.json
change/react-native-windows-init-2020-06-26-19-29-32-master.json
docs/react-native-windows-init.md
packages/react-native-win32/README.md
packages/react-native-windows-init/README.md
vnext/.flowconfig
vnext/Microsoft.ReactNative.Cxx/NativeModules.h
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
vnext/Microsoft.ReactNative/ReactHost/React.h
vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
vnext/Microsoft.ReactNative/ReactInstanceSettings.h
vnext/Mso/debugAssertApi/debugAssertDetails.h
vnext/Scripts/Install-WindowsSDKISO.ps1
vnext/Shared/DevSettings.h
vnext/local-cli/config/configUtils.js
vnext/local-cli/config/dependencyConfig.js
vnext/local-cli/config/projectConfig.js
vnext/local-cli/runWindows/runWindows.js
vnext/local-cli/runWindows/utils/autolink.js
vnext/local-cli/runWindows/utils/commandWithProgress.js
vnext/react-native.config.js
vnext/src/Libraries/Components/View/ViewWindows.tsx
vnext/src/RNTester/js/examples-win/DatePicker/DatePickerExample.windows.tsx
vnext/src/RNTester/js/examples-win/Picker/PickerWindowsExample.tsx
vnext/src/RNTester/js/utils/RNTesterList.windows.ts
vnext/src/typings-index.ts

After PR #5358 more casing inconsistencies were discovered. This PR addresses the next batch.

 Fix a few more casing typos

---

change/react-native-windows-2020-06-29-23-23-34-tm-logbox.json
vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp

- Migrate 'LogBox' to turbo module
- Not tested yet

Migrate 'LogBox' to turbo module

---

change/react-native-windows-2020-06-30-12-42-24-tm-im.json
vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp

- Migrate 'I18nManager' to turbo module

Migrate 'I18nManager' to turbo module

---

change/react-native-windows-2020-06-30-12-41-13-tm-di.json
vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp

- Migrate 'DeviceInfo' to turbo module

Migrate 'DeviceInfo' to turbo module

---

.ado/windows-vs-pr.yml

Disable XHRSample Integration test in the Desktop version

---

.ado/windows-vs-pr.yml
.unbroken_exclusions
docs/react-native-windows-init.md

Update link in react-native-windows-init.md to index.ts and enable unbroken in PR

---

.ado/templates/prep-and-pack-single.yml
.ado/windows-vs-pr.yml

Fix publish build and no need to clone repo for publish nuget.

---

change/react-native-windows-2020-07-07-16-42-02-5179.json
vnext/local-cli/src/runWindows/utils/commandWithProgress.ts
vnext/local-cli/src/runWindows/utils/deploy.ts

Deploy dependent framework packages when registering from layout

---

.ado/setVersionEnvVars.js

Update Publish pipeline to report RNW Version published

---

change/react-native-windows-2020-07-08-19-00-08-ms-rnw-staging.json
vnext/Desktop/ABI/TestController.cpp
vnext/Desktop/ABI/TestController.h
vnext/Desktop/React.Windows.Desktop.vcxproj

Adding copyright notice (previous CR feedback); using <DependentUpon/> elements to create view similar to UWP project

CR feedback, project hygiene

---

change/react-native-windows-2020-07-09-10-31-29-wackOn62.json
vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj

Pass WACK on 62

---

packages/playground/windows/playground-win32/Playground-Win32.cpp

Adjust island window size for title bar/menu bar and scrollbar

---

change/react-native-windows-2020-07-08-00-29-11-desktop-featuregate.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
vnext/Desktop/FeatureGate.cpp
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/React.Windows.Desktop.vcxproj.filters
vnext/Desktop/WebSocketResourceFactory.cpp
vnext/Shared/FeatureGate.h
vnext/Shared/Shared.vcxitems
vnext/Shared/Shared.vcxitems.filters

Adds the ability to set an arbitrary flag (set by a string key) to affect runtime behavior in a Desktop React instance.

[Desktop] Add arbitrary global flag setting functions

---

.ado/templates/prep-and-pack-nuget.yml
change/react-native-windows-2020-07-09-13-58-33-master.json
vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
vnext/Scripts/Microsoft.ReactNative.Cxx.targets
vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
vnext/Scripts/Microsoft.ReactNative.nuspec
vnext/Scripts/PublishNugetPackagesLocally.cmd
vnext/Scripts/Tfs/Layout-Headers.ps1
vnext/local-cli/src/generator-windows/index.ts
vnext/local-cli/templates/cpp/proj/MyApp.sln

Create nuget package for Microsoft.ReacNative.Cxx

---

change/react-native-platform-override-2020-07-10-19-05-02-not-same.json
packages/react-native-platform-override/src/Cli.ts
packages/react-native-platform-override/src/Override.ts
packages/react-native-platform-override/src/ValidationStrategy.ts
packages/react-native-platform-override/src/test/ValidationStrategy.test.ts

Add Validation That Patch/Derived Overrides Aren't Identical to Their Originals

---

change/react-native-windows-2020-07-14-17-18-50-imageDebug.json
vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp

This adds some logging to identify what images are not being loaded and why

Add Image load debugging output

---

change/react-native-windows-2020-07-16-11-21-25-effects-midl.json
vnext/Microsoft.ReactNative/Views/Image/Effects.h
vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
vnext/Microsoft.ReactNative/Views/cppwinrt/DynamicAutomationPeer.idl
vnext/Microsoft.ReactNative/Views/cppwinrt/Effects.idl
vnext/Microsoft.ReactNative/Views/cppwinrt/ViewPanel.idl

Switch Effects.idl to MIDL 3.0

---

change/react-native-windows-2020-07-16-16-42-08-abi-safety.json
vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
vnext/Desktop.ABITests/RedBoxTests.cpp
vnext/Desktop/ABI/TestController.cpp
vnext/Desktop/ABI/TestController.h
vnext/Desktop/ABI/TestController.idl
vnext/Desktop/React.Windows.Desktop.vcxproj
vnext/Desktop/React.Windows.Desktop.vcxproj.filters
vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
vnext/Microsoft.ReactNative/RedBox.cpp
vnext/Microsoft.ReactNative/RedBoxErrorFrameInfo.cpp
vnext/Microsoft.ReactNative/RedBoxErrorFrameInfo.h
vnext/Microsoft.ReactNative/RedBoxErrorInfo.cpp
vnext/Microsoft.ReactNative/RedBoxErrorInfo.h

Add RedBox objects, tests

---

change/react-native-windows-2020-07-20-09-14-24-master.json
vnext/Scripts/rnw-dependencies.ps1

Update rnw-dependencies.ps1 to support grouping of requirements to hndle different use cases

---

change/react-native-windows-2020-07-18-12-45-50-patch-1.json
vnext/Scripts/rnw-dependencies.ps1

Dependencies installer: display expected answers and default one

---

change/react-native-windows-2020-07-20-10-14-08-master.json
vnext/Scripts/rnw-dependencies.ps1

This is useful to have on the build agents so we can capture ETW traces to diagnose issues.

Add windows adk to machine setup script

---

change/react-native-windows-2020-07-16-16-42-08-abi-safety.json
vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
vnext/Desktop.ABITests/ReactNonAbiValueTests.cpp
vnext/Desktop/ABI/TestController.cpp
vnext/Desktop/ABI/TestController.h
vnext/Desktop/ABI/TestController.idl

Add ReactNonAbiValue test

---

change/react-native-windows-2020-07-20-13-48-13-image-tintcolor.json
packages/playground/Samples/image.tsx
vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
vnext/Microsoft.ReactNative/Views/Image/Effects.h
vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
vnext/Microsoft.ReactNative/Views/Image/Microsoft.UI.Composition.Effects_Impl.h
vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.h
vnext/Microsoft.ReactNative/Views/cppwinrt/Effects.idl

[Image] Implement tintcolor

---

packages/E2ETest/wdio/pages/HomePage.ts
packages/E2ETest/wdio/test/AAA_SmokeTest.spec.ts

Fixes an instability in the smoke test.

fix smoke test

---

change/react-native-windows-2020-07-22-14-39-04-master.json
change/react-native-windows-2020-07-23-17-36-11-0.62-stable.json
vnext/Desktop.DLL/packages.config
vnext/Desktop/packages.config
vnext/JSI.Desktop.UnitTests/packages.config
vnext/PropertySheets/React.Cpp.props
vnext/ReactWindowsCore/V8JSIRuntimeHolder.cpp

This new version is built on V8 version 8.4. Also includes some improvements to the inspector (direct debugging) implementation.

Update V8 package version (0.62)

---

change/react-native-windows-2020-07-26-11-19-38-glyph-cut-off.json
vnext/src/RNTester/js/examples-win/Glyph/GlyphExample.tsx

Ticket: https://github.com/microsoft/react-native-windows/issues/4467

Added fixed emSize to cut-off glyph

---

.ado/templates/yarn-install.yml

Includes a fix for more gracefully handling timeouts during NPM post-install steps.

Use newer version of midgard-yarn

---

packages/playground/windows/playground/Playground.vcxproj

Don't run autolinking for the playground app

---

change/@react-native-windows-cli-2020-08-04-13-53-11-master.json
change/react-native-windows-2020-08-04-13-53-11-master.json
packages/@react-native-windows/cli/templates/cs/proj/MyApp.csproj
packages/@react-native-windows/cli/templates/cs/proj/MyApp.sln
packages/@react-native-windows/cli/templates/cs/src/App.xaml.cs
packages/@react-native-windows/cli/templates/cs/src/ReactPackageProvider.cs
packages/E2ETest/windows/ReactUWPTestApp.sln
packages/E2ETest/windows/ReactUWPTestApp/App.xaml.cs
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/ReactPackageProvider.cs
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/ReactPackageProvider.cs
packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleLibraryCS.csproj
vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.cs
vnext/Microsoft.ReactNative.Managed.CodeGen/ReactNativeNames.cs
vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
vnext/PropertySheets/ManagedCodeGen/Microsoft.ReactNative.Managed.CodeGen.targets
vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.targets
vnext/package.json

[0.63] Make C# CodeGen the default (#5630)

---

.github/security.md

See information [about github security policies](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository)
Also see related changes in Microsoft repos like [this change](https://github.com/microsoft/microsoft-ui-xaml/pull/1312).
This security.md is the exact same content as used on our [other](https://github.com/microsoft/terminal/blob/master/SECURITY.md) [repos](https://github.com/microsoft/AdaptiveCards/blob/main/SECURITY.MD).

Add repository security policy

---

.ado/templates/react-native-init.yml

Fix condition in react-native-init yaml script

---

change/react-native-windows-2020-08-11-18-16-13-master.json
vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
vnext/Scripts/Microsoft.ReactNative.nuspec
vnext/Scripts/OfficeReact.Win32.nuspec

Update nuget pkgs for nuget.org compliance

---

change/react-native-windows-2020-08-11-18-16-13-master.json
vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
vnext/Scripts/Microsoft.ReactNative.nuspec
vnext/Scripts/OfficeReact.Win32.nuspec

[0.63] Update nuget pkgs for nuget.org compliance (#5696)

---

change/react-native-windows-2020-08-13-11-55-12-0.63-webSocketTeardownCrash.json
vnext/Shared/Executors/WebSocketJSExecutor.cpp
vnext/Shared/Executors/WebSocketJSExecutor.h

[0.63] Web socket teardown crash

---

change/react-native-windows-2020-08-13-11-37-00-webSocketTeardownCrash.json
vnext/Shared/Executors/WebSocketJSExecutor.cpp
vnext/Shared/Executors/WebSocketJSExecutor.h

Web socket teardown crash

---

change/react-native-windows-2020-08-13-11-22-51-devsupportmanagerCast.json
vnext/Shared/DevSupportManager.cpp

Remove reinterpret_cast in DevSupportManager

---

change/react-native-windows-2020-08-13-22-05-20-0.63-crashViewViewManager.json
vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp

[0.63] Fix crash in ViewViewManager

---

change/@react-native-windows-cli-2020-08-18-14-40-14-autolinking.json
packages/@react-native-windows/cli/src/config/configUtils.ts
packages/@react-native-windows/cli/src/config/dependencyConfig.ts
packages/@react-native-windows/cli/src/config/projectConfig.ts
packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts

This PR ports #5772 into 63 to fix autolinking.

[0.63] Fixing config and autolinking (#5772)

---

change/@office-iss-react-native-win32-2020-08-18-16-33-02-sourcemap.json
change/@office-iss-react-native-win32-2020-08-18-16-33-02-sourcemap63.json
packages/react-native-win32/.npmignore

[0.63] [Win32] Publish TS files in src as they are referenced in sourcemaps

---

change/react-native-windows-2020-08-24-18-13-47-master.json
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructOneArgParamReturnVoid--Async.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructOneArgParamReturnVoid--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructParamReturnVoid--Async.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructParamReturnVoid--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGenTestBase.cs
vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
vnext/Microsoft.ReactNative.Managed/JSValueWriter.cs
vnext/Microsoft.ReactNative.sln

[0.63] Fix C# interop serialization for JsValueObject (#5826)

---

change/react-native-windows-2020-08-27-17-58-46-dropviewmaster.json
vnext/Shared/Modules/UIManagerModule.cpp
vnext/Shared/ShadowNodeRegistry.cpp
vnext/Shared/ShadowNodeRegistry.h
yarn.lock

This is the master version of #5854

[master] Drop left over shadow nodes in uimanager dtor

---

change/@office-iss-react-native-win32-2020-09-01-13-52-33-logboxstyle63.json
packages/react-native-win32/overrides.json
packages/react-native-win32/package.json
packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorStackFrame.win32.js
packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxStyle.win32.js
yarn.lock

[Win32] [0.63] A couple of minor style changes in LogBox to avoid win32 asserts

---

change/react-native-windows-2020-09-08-12-00-06-fixbuild.json
vnext/ReactWindowsCore/ShadowNodeRegistry.cpp
vnext/ReactWindowsCore/ShadowNodeRegistry.h

[0.62] Fix build break hit in publish builds

---

change/@react-native-windows-cli-2020-09-13-13-43-52-cli_9_13.json
packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts

fix ts warning

---

change/react-native-windows-2020-09-13-13-39-02-CppAppConsumeCSharpModule.json
vnext/PropertySheets/CppAppConsumeCSharpModule.props
vnext/PropertySheets/CppAppConsumeCSharpModule.targets

Use Program Files (x86) to locate UWP SDK props/targets

---

change/@react-native-windows-cli-2020-09-13-15-27-17-yarnWorkaround.json
packages/@react-native-windows/cli/src/runWindows/runWindows.ts

Yarn workaround

---

change/react-native-windows-2020-09-15-11-20-37-follyUpdate-0.62.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Desktop.UnitTests/EmptyUIManagerModule.cpp
vnext/Folly/Folly.vcxproj
vnext/Folly/Folly.vcxproj.filters
vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
vnext/IntegrationTests/TestInstance.cpp
vnext/PropertySheets/ReactDirectories.props
vnext/ReactUWP/EndPoints/dll/react-native-uwp.arm.def
vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def
vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86.def
vnext/ReactUWP/Views/ViewManagerBase.cpp
vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
vnext/ReactWindowsCore/Utils.cpp
vnext/Scripts/Tfs/Layout-Headers.ps1

[0.62] Folly update 0.62

---

change/react-native-windows-2020-09-15-11-10-44-follyUpdate-0.63.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Desktop.UnitTests/EmptyUIManagerModule.cpp
vnext/Directory.Build.props
vnext/Folly/Folly.vcxproj
vnext/Folly/Folly.vcxproj.filters
vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
vnext/IntegrationTests/TestInstance.cpp
vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
vnext/Scripts/Tfs/Layout-Headers.ps1
vnext/Shared/Modules/UIManagerModule.cpp
vnext/Shared/Utils.cpp

[0.63] Port Folly update

---

change/react-native-windows-2020-09-15-14-05-23-master.json
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj

Update Nuget packages for Roslyn and some test projects

---

change/react-native-windows-2020-09-17-20-39-35-master.json
vnext/Scripts/rnw-dependencies.ps1

Auto-accept git license in rnw-dependencies install script

---

change/react-native-windows-2020-09-14-23-19-19-folly_string_view.json
vnext/Folly/Folly.vcxproj

Use string_view in Folly

---

change/@office-iss-react-native-win32-2020-09-21-03-02-57-63-typings.json
change/react-native-windows-2020-09-21-03-02-57-63-typings.json
docs/api/react-native-windows.dayofweek.md
docs/api/react-native-windows.ipickeritemdata.md
docs/api/react-native-windows.ipickeritemdata.textcolor.md
packages/E2ETest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-win32/package.json
vnext/etc/react-native-windows.api.md
vnext/package.json
vnext/src/Libraries/Components/Picker/PickerWindows.tsx
yarn.lock

Upgrade react-native Typings

---

change/react-native-windows-2020-09-23-13-32-51-fixbuild.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/IntegrationTests/TestInstance.cpp
vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj

Port of #6051 to master branch

Fixups from folly update

---

change/react-native-windows-2020-09-24-13-22-45-flyoutDismissIslands.json
vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp

Flyouts should dismiss when their island changes if they are light dismissable

---

packages/IntegrationTest/tests/InteropCSModuleTests.tsx
packages/IntegrationTest/tests/index.ts
packages/IntegrationTest/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
packages/IntegrationTest/windows/InteropTestModuleCS/Properties/AssemblyInfo.cs
packages/IntegrationTest/windows/InteropTestModuleCS/ReactPackageProvider.cs
packages/IntegrationTest/windows/InteropTestModuleCS/TestModuleCS.cs
packages/IntegrationTest/windows/integrationtest.sln
packages/IntegrationTest/windows/integrationtest/App.cpp
packages/IntegrationTest/windows/integrationtest/integrationtest.vcxproj

Add integration test for C# Interop

---

change/react-native-windows-2020-09-29-08-56-05-master.json
docs/testing-nuget-packages.md
packages/E2ETest/windows/ReactUWPTestApp/Package.appxmanifest
packages/IntegrationTest/windows/integrationtest/Package.appxmanifest
packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/Package.appxmanifest
packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/Package.appxmanifest
packages/playground/windows/Playground-win32 (Package)/Package.appxmanifest
packages/playground/windows/playground/Package.appxmanifest
vnext/Chakra/ChakraHelpers.cpp
vnext/JSI.Desktop.UnitTests/ChakraCoreRuntimeUnitTests.cpp
vnext/JSI.Desktop.UnitTests/JsiRuntimeUnitTests.cpp
vnext/JSI.Desktop.UnitTests/JsiRuntimeUnitTests.h
vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
vnext/JSI/Shared/ChakraRuntime.cpp
vnext/Microsoft.ReactNative.Managed.UnitTests/Package.appxmanifest
vnext/Shared/AsyncStorage/StorageFileIO.cpp
vnext/Shared/etw/react_native_windows.man

 Remove Microsoft user names from source code

---

package.json
yarn.lock

Fixed component covernance alert with bl@3.0.1 resolution

---

change/react-native-windows-2020-10-01-15-10-51-actualsize.json
packages/IntegrationTest/tests/MountComponentTests.tsx
packages/IntegrationTest/tests/SampleTests.tsx
vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp

Image - fix pre-1903 crash when loading certain images

---

change/react-native-windows-2020-10-05-12-09-22-master.json
vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj

Update System.Private.Uri version for C# codegen

---

README.md

Just a small & simple PR to keep website and platform naming consistent.

Readme: fix macOS and website naming

---

docs/e2e-testing.md

Update url to `Consts.ts` in `e2e-testing.md`

---

change/@react-native-windows-cli-2020-10-16-09-03-48-master.json
packages/@react-native-windows/cli/src/config/projectConfig.ts
packages/@react-native-windows/cli/src/runWindows/runWindows.ts
packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts

Reverting at the request to hash out scenario's in more detail.

Pr revert #6232

---

change/react-native-windows-2020-10-19-09-20-38-master.json
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGenTestBase.cs

Improve unittest message to update LKG's

---

change/react-native-windows-2020-10-16-11-14-51-acoates-syncfuncfix.json
vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
vnext/Microsoft.ReactNative.Cxx/NativeModules.h
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--NoParamReturnInt--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--OneParamReturnInt--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ThreeParamReturnInt--Sync.lkg
vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
vnext/Microsoft.ReactNative.Managed.UnitTests/NoAttributeNativeModuleTest.cs
vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
vnext/Microsoft.ReactNative.Managed/ReactSyncMethodInfo.cs

Sync native module functions are wrapping the result in an array, which it shouldn't

---

change/react-native-windows-2020-10-22-11-54-02-PR-FixUnitTests.json
vnext/JSI/Shared/ChakraRuntime.cpp
vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
vnext/Microsoft.ReactNative/TurboModulesProvider.cpp

Due to some recent changes a number of unit tests are failing in Visual Studio for the Microsoft.ReactNative.sln solution.
It was surprising to see that three test projects are got excluded from the CI.
In this PR we fix the unit tests.
In the follow up PR I will add them to CI to prevent the same issues in future.

Fix failing unit tests

---

change/react-native-windows-2020-10-26-13-35-51-createuiman.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def

[Win32] Export createUIManagerModule that takes a uiQueue

---

change/react-native-windows-2020-10-26-12-21-08-animreloadfix2.json
vnext/Microsoft.ReactNative/INativeUIManager.h
vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.h
vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp

Follow up from #6289
These additional changes were found during partner testing of the fix against 0.63.

Fixes for crash on reload

---

change/react-native-windows-2020-10-26-13-33-16-uimanager63.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def

[0.63] [Win32] Export createUIManagerModule that takes a uiQueue

---

.ado/templates/react-native-init.yml
.ado/verdaccio/config.yaml

Fixes #6313
These are some of the reccomened solutions from the commentary in #6313. There are a couple more tweaks we can try, but these should hopefully alleviate Verdaccio issues.

More Permissive Retry Logic for Verdaccio

---

packages/playground/metro.config.js

ACoates added a custom metro config for Playground which attempts to resolve source files for react-native-windows, which are normally moved to a new target location during the build. RNTester sources were moved to their own package, and were not being included by the custom metro config. This change updates the metro config to allow it to look in arbitray "dev packages" where it will prefere JS sources in src instead of the root. @react-native-windows/tester is included as a dev package to let its sources be resolved.
Validated modifying src files in vnext and @react-native-windows/tester and observed we see fast refresh.

Extend Playground Metro Config to Allow Live Reload of RNTester Changes

---

README.md

Fix link to RN website

---

change/react-native-windows-577ea17d-36ca-43ab-af0f-ad8fc3785587.json
vnext/Scripts/OfficeReact.Win32.nuspec

Fix one more file that was moved for Nuget Packing of Win32 version or RNW

---

change/react-native-windows-30ac28be-eaef-4db2-a499-f51829f1b87d.json
vnext/Scripts/rnw-dependencies.ps1

[Fix PR] Update dependencies script to support new ADO images that don't have node 12

---

change/react-native-windows-a9e67774-3a7f-4de3-94c2-855154ee0ce1.json
vnext/Shared/AsyncStorage/AsyncStorageManager.cpp

Don't return an error if AsyncStorage is empty

---

change/@react-native-windows-telemetry-a669eadd-47ff-43ed-a809-893ce003b71e.json
packages/@react-native-windows/telemetry/src/telemetry.ts
packages/@react-native-windows/telemetry/src/test/sanitize.test.ts

Remove roleInstance property from CLI telemetry

---

change/@react-native-windows-telemetry-ae35bf38-2b39-4a08-b826-5a527b3b8301.json
packages/@react-native-windows/telemetry/src/telemetry.ts

[CLI] Make comparison of microsoft.com domain case-insensitive for telemetry purposes

---

change/@react-native-windows-cli-1f2b01ad-b55e-4589-b852-101ea9e81fe5.json
change/@react-native-windows-telemetry-2020-11-09-01-02-17-silenceWarnAI.json
change/react-native-windows-init-c8db854d-d6e4-49a8-a3bd-c5fe0ed5427b.json
packages/@react-native-windows/cli/src/index.ts
packages/@react-native-windows/cli/src/runWindows/runWindows.ts
packages/@react-native-windows/telemetry/src/index.ts
packages/@react-native-windows/telemetry/src/telemetry.ts
packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
packages/react-native-windows-init/src/Cli.ts

Delay-create the connection to appinsights

---

change/@react-native-windows-cli-a2c0ebaa-14b0-44e8-b4c3-3a543476d0bd.json
change/@react-native-windows-telemetry-0146fb5b-3dfe-45c7-aa18-4ea82551fc47.json
change/react-native-windows-init-3e04664a-9f9c-48e7-b832-19498ec8f559.json
packages/@react-native-windows/cli/src/index.ts
packages/@react-native-windows/cli/src/runWindows/runWindows.ts
packages/@react-native-windows/telemetry/src/telemetry.ts
packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
packages/react-native-windows-init/src/Cli.ts

Disable telemetry in CI

---

change/react-native-windows-a9e67774-3a7f-4de3-94c2-855154ee0ce1.json
vnext/Shared/AsyncStorage/AsyncStorageManager.cpp

[0.63] Backport async storage inconsistency fix

---

change/react-native-windows-1989fdf5-7168-4255-84d4-19d192a473bf.json
vnext/Scripts/rnw-dependencies.ps1

Fixes #6512 (breaking change from ADO)

Allow using NodeJS 14 in 0.63 

---

Directory.Build.targets
change/react-native-windows-b8dbda54-a2f3-42a1-b0bd-9c56a21014e1.json
vnext/Directory.Build.props
vnext/Directory.Build.targets
vnext/Microsoft.ReactNative.Managed/JSValue.cs

Fix managed nuget to have ref assembly marked AnyCpu

---

change/react-native-windows-2020-11-13-08-40-27-desktopexport.json
vnext/Desktop.DLL/react-native-win32.x64.def
vnext/Desktop.DLL/react-native-win32.x86.def
vnext/Scripts/OfficeReact.Win32.nuspec

Add win32 exports required for internal usage

---

.ado/publish.yml
.ado/templates/prepare-env.yml
.ado/templates/react-native-init.yml
.ado/windows-vs-pr.yml
change/react-native-windows-2020-11-13-08-47-42-0.62-stable.json
vnext/local-cli/runWindows/utils/build.js

[0.62] port nuget 5.8.0 fix to 0.62

---

.ado/templates/prep-and-pack-nuget.yml
change/react-native-windows-2020-11-13-10-57-08-master.json
vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
vnext/Scripts/Tfs/Layout-Headers.ps1

Update Managed ref assemblies to be AnyCpu

---

change/react-native-windows-2020-11-15-20-13-18-master.json
vnext/Scripts/OfficeReact.Win32.nuspec

Fix Publish pipeline due to moved callinvoker file

---

change/react-native-windows-2020-11-16-08-23-41-master.json
vnext/Scripts/OfficeReact.Win32.nuspec

Fix publish pipeline for viewmanager.h

---

.ado/templates/prep-and-pack-nuget.yml

Update Nuget publish to not overwrite the created anycpu version

---

change/react-native-windows-dea2927a-a5e6-4784-a71a-14e423a40d2e.json
vnext/Microsoft.ReactNative.Cxx/UI.Xaml.Controls.h
vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp

Degrade CornerRadius in RS4 #6551 #6544

[0.63] port CornerRadius fix to 0.63

---

packages/@react-native-windows/tester/package.json
packages/E2ETest/package.json
packages/IntegrationTest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
vnext/package.json

Manual version bump as publish failed previously

---

.ado/templates/react-native-init.yml
change/react-native-windows-0045baf0-e7aa-4b28-871d-fd6f08e80dce.json
vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj

Fix 2 typos

---

change/react-native-windows-44049f16-420d-4e0f-b7a5-3ae812c31972.json
packages/playground/windows/playground/packages.config
vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
vnext/Microsoft.ReactNative/XamlView.cpp
vnext/Microsoft.ReactNative/packages.config
vnext/PropertySheets/WinUI.props
vnext/template/cpp-app/src/pch.h
vnext/template/cpp-lib/src/pch.h

Move to WinUI 3.0 preview 3

---

change/react-native-windows-1aac7b87-16f0-4567-a57a-4e0b5ec8b55b.json
vnext/Microsoft.ReactNative.Cxx/StructInfo.h

Follow-up on microsoft/react-native-windows-samples#332

Amend doc for REACT_STRUCT.

---

change/@react-native-windows-cli-23db3b86-8039-40ed-b29d-be96b1e8718b.json
change/react-native-windows-init-ca9b9927-7215-44e3-ba38-ca84e3441642.json
packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
packages/react-native-windows-init/src/Cli.ts

Update cli telemetry defaults

---

change/@react-native-windows-cli-23db3b86-8039-40ed-b29d-be96b1e8718b.json
change/react-native-windows-91d7f4ff-c8d8-44a0-815c-937f108994e2.json
change/react-native-windows-f13d8d0e-a58a-4fae-981d-f677627c032d.json
change/react-native-windows-init-ca9b9927-7215-44e3-ba38-ca84e3441642.json
packages/@react-native-windows/cli/CHANGELOG.json
packages/@react-native-windows/cli/CHANGELOG.md
packages/@react-native-windows/cli/package.json
packages/@react-native-windows/tester/package.json
packages/E2ETest/package.json
packages/IntegrationTest/package.json
packages/microsoft-reactnative-sampleapps/package.json
packages/playground/package.json
packages/react-native-windows-init/CHANGELOG.json
packages/react-native-windows-init/CHANGELOG.md
packages/react-native-windows-init/package.json
vnext/CHANGELOG.json
vnext/CHANGELOG.md
vnext/package.json

Running beachball 'bump'

---

change/react-native-windows-2020-09-13-16-16-58-no-timing-aseert.json
change/react-native-windows-2020-10-02-12-58-35-remove-other-timingmodule-assert.json
vnext/Microsoft.ReactNative/Modules/TimingModule.cpp

[0.63] Backporting TimingModule assert removals

---

change/react-native-windows-99027820-65f4-41ab-a0b3-bc58c04b9c75.json
vnext/ReactCommon/ReactCommon.vcxproj

Fix multicore build, missing dependency on Folly

---

change/react-native-platform-override-aaad62eb-415d-4d87-9019-01d3e743d512.json
packages/react-native-platform-override/src/Hash.ts
packages/react-native-platform-override/src/ValidationStrategy.ts
packages/react-native-platform-override/src/test/Hash.test.ts
packages/react-native-platform-override/src/test/ValidationStrategy.test.ts

Use whitespace insensitive compare for identical override detection

---

change/react-native-windows-a206e50b-eb3d-4f1e-bb61-35d4d333e417.json
change/react-native-windows-b31b0d4b-c43f-464a-8b7c-a276c8be541b.json
vnext/Shared/Modules/UIManagerModule.cpp

Cherry pick the following PR from master:
- Fix destruction of UIManager in UI thread (#6680)

[0.63] Fix destruction of UIManager in UI thread (#6680)

---

change/@office-iss-react-native-win32-91e06e85-4251-45c4-97a7-5a34dda4e0f2.json
packages/react-native-win32/overrides.json
packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
packages/react-native-win32/src/index.win32.js

* Adding Polite/Aggressive Focus APIs
* Adding FocusManager API for polite/aggresive focus for win32
Co-authored-by: samuelfreiberg <Samuel.Freiberg@microsoft.com>
Co-authored-by: Nick Gerleman <nick@nickgerleman.com>

[0.64] Win32 Polite/Aggressive Focus API (#6711)
