microsoft/react-native-windows

- change/react-native-windows-2020-02-20-17-38-43-FixNoPackageProvider.json
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
The `ReactNativeHost.PackageProvider` property creates collection on demand. But if we never touched that property, then the internal field m_packageProviders is null and we see a crash if application does not provide any custom packages.
In this PR we add a simple check if m_packageProviders is null to avoid the runtime crash.
> Fix ReactNativeHost without package providers

- change/react-native-windows-2020-02-14-16-56-53-users-aschultz-build.json
- vnext/PropertySheets/ReactPackageDirectories.props
- vnext/ReactUWP/ReactUWP.vcxproj
To bring this into the 0.60 branch.
> Fix for NormalizePath resolving IntDir based on current working directory (#4108)

- change/react-native-windows-2020-02-21-14-55-06-FixReactPromise.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
In C++ coroutines preserve current function callstack when the function is suspended with the co_await operator. It creates an interesting issue with parameter passing: any parameter passed by reference may cause a crash if accessed after resuming. See for details: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency (Parameter-passing section.) 
In our unit tests we had to copy Mso::ReactPromise and callbacks to ensure that we can call them safely after co_await. But, when developers write code, it is too easy to make such mistake.
In this PR we are adding a check that causes a compile-time error if parameters are not passed by value to a coroutine. We have updated our test native module coroutines to pass parameters by value instead of by reference.
> Force coroutine method parameters pass by value

- change/react-native-windows-2020-02-24-11-56-09-fix-transform.json
- packages/E2ETest/app/Consts.ts
- packages/E2ETest/app/TestPages.ts
- packages/E2ETest/app/TransformTestPage.tsx
- packages/E2ETest/wdio/pages/HomePage.ts
- packages/E2ETest/wdio/pages/TransformTestPage.ts
- packages/E2ETest/wdio/test/TransformTest.spec.ts
- vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
- vnext/ReactUWP/Views/ShadowNodeBase.cpp
Fixes #4077.
The `g_HasActualSizeProperty` was not properly initialized which leads to a wrong code path when [creating center vector](https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Views/ExpressionAnimationStore.cpp#L49-L51). Moving the initialization to ShadowNodeBase so that we can have the correct value ready before the checks.
> Fix transform center point

- change/react-native-windows-2020-02-24-12-16-25-mqtdec.json
- vnext/ReactWindowsCore/IUIManager.h
Currently IUIManager.h causes undefined identifier errors when included without including MessageQueueThread.h first.
> Declare MessageQueueThread in header that uses it

- change/react-native-windows-2020-02-25-11-16-19-networkingmodulefix.json
- vnext/ReactUWP/Modules/NetworkingModule.cpp
Fix #4174 
- Add locking around modifications to m_requests map.
> Fix concurrency issue in NetworkingModule

- change/@office-iss-react-native-win32-2020-02-27-05-32-05-missing-license.json
- packages/react-native-win32/package.json
Yarn gives us warnings about this is we do `yarn list`.  Add the missing license.
> Add missing license to react-native-win32

- change/@office-iss-react-native-win32-2020-02-27-10-11-57-generate-patches.json
- change/react-native-windows-2020-02-27-10-11-57-generate-patches.json
- packages/override-tools/package.json
- packages/override-tools/src/Cli.ts
- packages/override-tools/src/GitReactFileRepository.ts
- packages/override-tools/src/Manifest.ts
- packages/override-tools/src/PackageUtils.ts
- packages/override-tools/src/scripts/generateManifest.ts
- packages/react-native-win32/src/overrides.json
- vnext/src/overrides.json
- yarn.lock
Add partially complete override manifests for RNW and react-native-win32. These were generated using a tool to determine the simple cases of patching or derived files. This is incomplete and will require some manual fixup.
> Add partial generated override manifests

- change/react-native-windows-2020-02-27-11-28-17-textinput.tabindex.json
- vnext/ReactUWP/Views/TextInputViewManager.cpp
Currently all TextInputs get tab focus last so we should to set the default tabIndex to 0.
> TextBox should have a default tabIndex of 0

- change/react-native-windows-2020-02-25-11-32-44-tabindex.json
- vnext/ReactUWP/Views/ControlViewManager.cpp
- vnext/ReactUWP/Views/ViewViewManager.cpp
> Set IsTabStop to false when tabIndex is negative

- change/react-native-windows-2019-12-09-11-51-33-WebSocketConnectError.json
- vnext/ReactUWP/Modules/WebSocketModuleUwp.cpp
variable hr is initialised both inside and outside the try/catch block, meaning that outside of the try/catch, hr is always S_OK -- removed duplicate variable initialisation to ensure that WebSocket.onerror is correctly called when a socket fails to connect
> Fix error handling in WebSocket.connect

- change/react-native-windows-2020-02-29-10-23-04-runWindowsHoist.json
- vnext/local-cli/runWindows/utils/deploy.js
I don't think the current react-native-cli supports having react-native hoisted, but newer versions do, and so we should ensure that our code doesn't assume that react-native-windows isn't hoisted too, ready for that.
This fixes a couple of places in run-windows code that assume that react-native-windows wasn't hoisted.
> Fix a couple of places in run-windows that has incorrect assumptions on install layout

- change/react-native-windows-2020-02-29-07-53-40-nicedevmenu.json
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
- vnext/ReactUWP/Views/ReactControl.cpp
Now that the dev menu has options for direct debugging and remote debugging, adding some more information to the menu options so users know what they do.
(Also spruced up the visuals some)
> Add descriptions to dev menu items

- packages/override-tools/src/Manifest.ts
- packages/override-tools/src/test/Manifest.test.ts
This is a continuation from the last change that was auto-merged before I had a chance to fix a UT issue around adding to an existing manifest. Fix the UT issue to ensure our tests to add overrides are accurate, and add some logic to avoid manifest duplicates in general.
> Override Manifest Duplicate and UT Handling Fixes

- change/react-native-windows-2020-03-04-11-59-23-events.json
- vnext/local-cli/config/projectConfig.js
- vnext/react-native.config.js
#2853 
"react-native config" command gathers platform config information for project and dependencies, it is used later for "auto-linking" between app project and  native module projects.
Right now, if you run "react-native config" command, it returns config info for iOS and Android but null for windows. This change adds some support for project config for windows, more to come later for native module's dependencies config. We may also need to tweak on what config info is needed too at later time depending on what auto-linking's requirements.
example output:
"windows": {
"sourceDir": "c:\\rnw61\\windows",
"projectSolution": "c:\\rnw61\\windows\\rnw61.sln",
"projectName": "rnw61",
"cppProjFile": "c:\\rnw61\\windows\\rnw61\\rnw61.vcxproj",
"csProjectFile": null
}
> Support poject config for RNW when running "react-native config"

- change/react-native-windows-2020-03-03-19-44-38-win32_winnt.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/Test/React.Windows.Test.vcxproj
- vnext/V8Inspector/V8Inspector.vcxproj
Minor change.
Even though Microsoft Docs claim macros `_WIN32_WINNT` and `WINVER` are equivalent, MSBuild explicitly requests to set `_WIN32_WINNT` to set the minimum target Desktop version:
```
Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
- add -D_WIN32_WINNT=0x0501 to the compiler command line; or
- add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
Generating Code...
```
> Define _WIN32_WINNT instead of WINVER.

- change/react-native-windows-2020-03-04-16-35-45-ViewPanelImportFix.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
- vnext/include/ReactUWP/Utils/PropertyUtils.h
This change moves the line `#include <Views/ViewPanel.h>` from PropertyUtils.h to FrameworkElementViewManager.cpp.
FrameworkElementViewManager was making use of ViewPanel.h by importing it indirectly through PropertyUtils.h. Since PropertyUtils.h does not have a dependency on ViewPanel.h, it is being removed and placed into FrameworkElementViewManager.cpp directly.
> Move ViewPanel import from PropertyUtils to FrameworkElementViewManager

- change/react-native-windows-2020-03-05-09-29-39-MS_ModuleRegistration.json
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.cpp
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
- vnext/Microsoft.ReactNative.SharedManaged/ReactModuleInfo.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactPackageBuilderExtensions.cs
- vnext/include/Include.vcxitems.filters
Currently we only provide capability to register all registered attributed native modules. In some scenarios there is a need to pick only specific modules by name. In this PR we are adding a new TryAddAttributedModule that tries to add attributed modules with specified name into an IReactPackageBuilder. This method returns true in case of success and false if module was not found by name.
> Added TryAddAttributedModule method

- change/react-native-windows-2020-03-04-16-35-45-ViewPanelImportFix.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
- vnext/include/ReactUWP/Utils/PropertyUtils.h
Brings the change made in #4236 into the 0.60-stable branch.
> Move ViewPanel import from PropertyUtils to FrameworkElementViewManager (#4236)

- .ado/windows-vs-pr.yml
Too many of our pipelines begin with "Verify" and this name is getting verbose/inaccurate/hard to find. Rename the pipeline to "Extra Checks".
> Rename "Verify change files, lint, and test" to "Extra Checks"

- change/react-native-windows-2020-03-06-09-06-45-autolink2.json
- vnext/local-cli/config/dependencyConfig.js
- vnext/local-cli/config/projectConfig.js
- vnext/react-native.config.js
#2853 
Dependency config checks each installed native module location and emits the config information which will be used for auto-linking. Along with project config, we will be using them to update solution/project file and code gen headers. 
Example output from RNV community module for windows platform:
"windows": {
"sourceDir": "c:\\rnw612\\node_modules\\react-native-video\\windows",
"packageIDL": "c:\\rnw612\\node_modules\\react-native-video\\windows\\ReactNativeVideoCPP\\ReactPackageProvider.idl",
"packageName": "ReactNativeVideoCPP",
"cppProjFile": "c:\\rnw612\\node_modules\\react-native-video\\windows\\ReactNativeVideoCPP\\ReactNativeVideoCPP.vcxproj",
"csProjectFile": null,
"projGUID": "{765365e4-9553-4900-9f69-e26d4309c8da}"
}
> Support dependency config for RNW when running "react-native config"

- change/react-native-windows-2020-03-06-15-18-23-noglobalrn.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
- vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
- vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj
The current default template has VS trigger a bundle command that only works if you have react-native installed globally. -- which also means that it maybe triggering the bundle command from a different version of react-native than the one the project is using.
The command should instead use the version of react-native that is locally installed.
> Release build fails if you dont have react-native globally installed

- change/react-native-windows-2020-03-06-15-28-57-noloadingship.json
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
- vnext/Microsoft.ReactNative/Views/ReactRootControl.h
Fixes: #4252 
Basically apps in release mode shouldn't show the green loading bar, or red box error UI. -- This aligns with react-native on android/iOS.
> Dont show loading bar in release apps

- change/react-native-windows-2020-03-06-15-06-46-MS_FixJSValue.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/pch.h
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.h
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative.Cxx/JSValueTreeReader.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValue.cs
- vnext/local-cli/generator-windows/templates/cpp/src/pch.h
This PR addresses issue https://github.com/microsoft/react-native-windows/issues/4181 that says that `JSValue::Double()` function has an unexpected behavior comparing with the `folly::dynamic::asDouble()` function. Though the `JSValue::Double()` was intended to behave as `folly::dynamic::getDouble()`, the issue brings a very important feedback:
- current API is not intuitively understood
- it is difficult to use when we need to convert values to a specific type
- it is difficult/inefficient to use when we want to work with typed values because functions silently return some default value instead of returning an error.
In this PR:
- We deprecate all functions that access typed values: `JSValue::Object()`, `JSValue::Array()`, `JSValue::String()`, `JSValue::Boolean()`, `JSValue::Int64()`, …
> Deprecate JSValue typed value access functions

- change/react-native-windows-2020-03-06-17-27-30-native-manifest.json
- packages/override-tools/src/Cli.ts
- packages/override-tools/src/scripts/generateManifest.ts
- vnext/DeforkingPatches/overrides.json
- vnext/package.json
Also make some visual tweaks to how we print errors so that separation between manifests is less confusing.
> Add Override Manifest for Native Code

- change/react-native-windows-2020-03-07-06-25-07-fix-etw.json
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/tracing/fbsystrace.h
Addresses #4245, During deforking work I left a build logic typo which caused SystraceSection to noop. When trying to re-enable in deforked React Native, we end up having a compile error since stock Facebook code will pass doubles as an arg to SysTraceSection, and we will internally only accept string.
This was fixed in microsof/react-native by commenting out the SystraceSection call that passed a double. A real solution is to allow our implementation of FbSystraceSection to accept non-string args and convert to strings, as Facebook's seemingly does.
- Add a SFINAE based overload for non-string-like types to call std::to_string on them
- Move functions to be private instead of public
Still need a plan to validate this. Any recommendations @mganandraj @stecrain ?
> Fix Support For SystraceSection

- change/react-native-windows-2020-03-07-06-25-07-fix-etw.json
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/tracing/fbsystrace.h
* Fix Support For SysTraceSection
Addresses #4245, During deforking work I left a build logic typo which caused SysTraceSection to noop. When trying to reenable in deforked React Native, we end up having a compile error since stock Facebook code will pass doubles as an arg to SysTraceSection, and we will internally only accept string.
This was fixed in microsof/react-native by commenting out the SysTraceSection call that passed a double. A real solution is to allow our implementation of FbSystraceSection to accept non-string args and convert to strings, as Facebook's seemingly does.
- Use type traits to call std::to_string on args not convertible to string
- Move functions to be private instead of public
Still need a plan to validate this.
* Simplify things a bit
* Solely rely on …
> [Cherry-Pick] Fix Support For SystraceSection (#4267)

- change/react-native-windows-2020-03-09-16-23-48-stripchalk.json
- vnext/Microsoft.ReactNative/RedBox.cpp
This aligns with a similar change that was made in Android/iOS: https://github.com/facebook/react-native/pull/24662
This greatly increases the readability of certain kinds of errors.
> Strip out color code characters from redbox error message

- change/react-native-windows-2020-03-10-22-14-59-reloadcrashes.json
- vnext/ReactUWP/Modules/TimingModule.cpp
- vnext/ReactUWP/Modules/TimingModule.h
- vnext/ReactWindowsCore/tracing/tracing.cpp
Timers use the CompositionTarget::Rendering event, which is async, and can fire even after its been unregistered.  This would cause random crashes during instance shutdown if there were any outstanding JS timers-- So I changed the event handler to use a weak_ptr and verify the object is still around before trying to fire timers.
The systrace impl was accessing an object that is supposed to be protected by a mutex outside of the mutex. -- Moved the mutex guard to cover the object access.
> Fix crash in timers during instance shutdown, and in systrace

- packages/override-tools/package.json
- packages/override-tools/src/ActionQueue.ts
- packages/override-tools/src/Cli.ts
- packages/override-tools/src/FileRepository.ts
- packages/override-tools/src/GitReactFileRepository.ts
- packages/override-tools/src/Manifest.ts
- packages/override-tools/src/ManifestData.ts
- packages/override-tools/src/OverrideFileRepositoryImpl.ts
- packages/override-tools/src/OverrideUpgrader.ts
- packages/override-tools/src/scripts/generateManifest.ts
- packages/override-tools/src/test/Manifest.test.ts
- packages/override-tools/src/test/MockFileRepository.ts
- packages/override-tools/tsconfig.json
- yarn.lock
Extend `override-tools` with commands to perform three-way merge on out-of-date overrides. Commands are added to do both automatic resolution, along with generation of partially merged files with conflict markers that can be merged using tools like VSCode:
The state of three-way-merge libraries is poor, so we end up abusing our scratch Git repo to do this. This ends up being relatively simple and reliable, although not particularly performant.
> Add Tooling to Manually or Automatically Update Overrides

- .ado/templates/e2e-test-job.yml
- .ado/variables/vs2019.yml
- .ado/windows-vs-pr.yml
The windows-2019 VMs only include enough VS 2019 to build popular project types. We need to make sure the components we need are installed.
> Fix missing msbuild for 2019 VMs

- change/react-native-windows-2020-03-11-12-43-39-FixJSValueIndex.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.h
Previously we have added new JSValueObject operator[] that could help access items in case if JSValueObject is const. But this new operator prohibits access to the base std::map mutating operator[].
In this PR, we are adding the mutating operator[] to JSValueObject and adding unit tests to verify the usage.
> Fixed JSValueObject operator[]

- change/react-native-windows-2020-03-12-10-45-38-add-cli.js.json
- vnext/local-cli/cli.js
Added cli.js file in local-cli folder.
For some reason we had to call `node node_modules/react-native-windows/local-cli/cli.js start` instead of `react-native start` to make the bundler work correctly for community module sample app. Possibly because @react-native-community/cli changes its behavior based on the path it's being invoked.
> Add cli.js

- change/react-native-windows-2020-03-16-16-20-55-ScrollViewFix.json
- vnext/ReactUWP/Views/ScrollViewManager.cpp
Currently, the default TabIndex for ScrollViewers is the maximum integer. This means that content inside of ScrollViewers will be last in keyboard navigation order. The expected behavior is that the user can keyboard navigate in XAML tree order. This change sets the default TabIndex value for ScrollViewers to 0 so that their contents can be accessed in tree order.
> Set TabIndex to 0 for ScrollViewers

- change/react-native-windows-2020-03-16-16-38-42-MS_FixTestCheck.json
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters
- vnext/Mso.UnitTests/future/promiseGroupTest.cpp
- vnext/Mso.UnitTests/future/promiseTest.cpp
- vnext/Mso.UnitTests/future/testCheck.h
- vnext/Mso.UnitTests/motifCpp/motifCppTest.cpp
- vnext/Mso/motifCpp/motifCppTest.h
- vnext/Mso/motifCpp/testCheck.h
For C++ unit tests we use the Mso subset of Motif tests that are based on GTest in our open source implementation that we use in RNW. A good unit test must report accurate test failure information such as:
- the file and a line of code;
- what expression failed and why.
Unfortunately, the `TestAssert::AreEqual`-like function calls do not provide such information, unlike the macros used in GTest. To address this limitation, the testCheck.h file has a number of macros such as `TestCheck` and `TestCheckEquals` that can capture the important test failure information.
The issue was that their implementation was based on the `TestAssert::AreEqual`-like functions and it was losing all the important information.
In this change we fix the testCheck.h macros to be able to report error location and …
> Improve unit test error messages in testCheck.h

- change/react-native-windows-2020-03-17-09-47-45-PickerFix.json
- vnext/ReactUWP/Views/PickerViewManager.cpp
Currently, the default TabIndex for Pickers is the maximum integer. This means that Pickers will be last in keyboard navigation order. The expected behavior is that the user can keyboard navigate in XAML tree order. This change sets the default TabIndex value for Pickers to 0 so that their contents can be accessed in tree order.
This is the same as #4328 but for Pickers.
> Set TabIndex to 0 for Pickers

- change/react-native-windows-2020-03-18-12-05-40-issue4295.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Before it returned `m_options.LegacySettings.BundleRootPath`.
While that value gets whatever was sent into it, during any of the many setting-copying operations , we also copy the value into `m_bundleRootPath`. However we also (in several different places) check if the value is empty first, in which case, we save `"ms-appx:///Bundle/"` into `m_bundleRootPath` instead, which is actually what is necessary for bundled assets to load properly from within a published package.
Fixes issue #4295 by checking `m_bundleRootPath` first, but really this is just another symptom of #4354.
> Fix ReactInstanceWin::GetBundleRootPath

- change/react-native-windows-2020-03-18-10-57-47-MS_FixJSValueCS.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
- vnext/.editorconfig
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.h
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/JSValueTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative.SharedManaged/AttributedViewManager.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValue.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueGenerator.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueReader.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueTreeReader.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueTreeWriter.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueWriter.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueWriterGenerator.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactConstantProvider.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactModuleInfo.cs
In PR https://github.com/microsoft/react-native-windows/pull/4260 we have changed C++ JSValue implementation to deprecate methods that access typed values stored in JSValue because of their unclear semantic and replaced them with `TryGetXXX` methods that return specified type and `AsXXX` methods that do JavaScript-like conversion. 
In this PR we are completing the set of changes that originally started to address issue https://github.com/microsoft/react-native-windows/issues/4181. In this PR we do the following changes:
- Updated C# JSValue implementation to match changes to C++ JSValue.
- All JavaScript-like conversions are now named `AsJSString`, `AsJSBoolean`, and `AsJSNumber` methods. They match to the JavaScript `String()`, `Boolean()`, and `Number()` methods.
- The `AsXXX` …
> Changed C# JSValue to match C++ JSValue

- current/ReactWindows/Playground/Playground.csproj
- current/ReactWindows/ReactNative.Tests/ReactNative.Tests.csproj
vcurrent still exists in the 60 stable branch, and has a Playground app, its certificate just expired.
We don't need to sign this package, turning this off.
> turn off signing on Playground vcrurrent

- change/react-native-windows-2020-03-21-08-39-47-MS_LinkingModule.json
- packages/microsoft-reactnative-sampleapps/index.windows.js
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/Package.appxmanifest
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/Package.appxmanifest
- vnext/Microsoft.ReactNative/ReactApplication.cpp
- vnext/Microsoft.ReactNative/ReactApplication.h
- vnext/ReactUWP/Modules/LinkingManagerModule.cpp
- vnext/ReactUWP/Modules/LinkingManagerModule.h
In RNW we already had Linking module implemented. The part that was missing is the implementation of the `getInitialURL()` method and raising events when application is asked to navigate to new a URL.
In this PR we are implementing the missing functionality:
- `ReactApplication` is changed to show RN UI on protocol activation and to notify  `LinkingManagerModule` about new URL activations.
- The sample applications are changed to respond to `rn-sample-app-cpp:` and `rn-sample-app-cs` protocols.
- Sample JS file changed to log the initial URL and subscribe to Open URL notifications and show them in the log.
To manually test the new functionality, developers can call run window `Win+R` and type there `rn-sample-app-cpp:Hello` or some other URL that uses the `rn-sample-app-cpp:` or …
> Implemented Linking module protocol activation

- change/react-native-windows-2020-03-23-11-27-39-playground3738.json
- vnext/ReactUWP/Views/Image/ReactImage.cpp
Rather than crashing the entire app if the image uri is invalid (not actually a uri), just don't set the source.
Fixes issue #3738
> Fixed crash when trying to load invalid image uri

- .gitignore
- change/react-native-windows-2020-03-23-20-55-53-winapi_ws_0.60_changegate.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/Mso/debugAssertApi/debugAssertApi.h
- vnext/Mso/debugAssertApi/debugAssertDetails.h
- vnext/Mso/src/debugAssertApi/debugAssertApi.cpp
- vnext/ReactWindows-Desktop.sln
- vnext/ReactWindowsCore/IWebSocketResource.h
- vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
- vnext/ReactWindowsCore/WinRTWebSocketResource.h
See #4330.
Use an `Mso::DispatchQueue` to avoid race conditions on background WebSocket writes.
> Ensure sequential writes in WinRTWebSocketResource

- change/react-native-windows-2020-03-23-14-20-35-acoates-loadcrash.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
In the code path where we try to load the bundle from a bundle server, but the server isn't running, the instance currently gets an error back in loadBundle, but then still puts the instance into a loaded state afterwards.  This leaves the instance in a loaded state, but with no JS loaded.  Which causes crashes in various native modules when they try to call into the instance.
I also changed the fast refresh call to check for error state before being called. -- I think there is a deeper issue of potential lost JS calls from native modules, as callJSFunction checks for the loaded state, otherwise drops the call.  But if a native module was to make a call while the instance is in the loading state, I think it should probably be queued up for later delivery once the instance loads?  (Not …
> Do not enter loaded state when an error occurs during web bundle loadJSBundles

- change/rnpm-plugin-windows-2020-03-23-15-44-43-cli-versions.json
- packages/rnpm-plugin-windows/src/common.js
- packages/rnpm-plugin-windows/src/windows.js
- packages/rnpm-plugin-windows/src/wpf.js
Add special rules for the master template to rnpm-plugin-windows to allow 0.0.0 versions of React Native Windows to match to non 0.0.0 versions of React Native, while we're not caught up yet.
Do not force the "vnext" tag for 0.61 builds without a template. We also rewrite some of the fuzzy logic added in #2559, which was allowing prereleases to be matched when we didn't force a tag. We didn't run into this in 0.59 or 0.60 given forcing vnext or legacy.
Part of the master logic was tested end-to-end in the 0.62 branch, but I plan to revalidate before checkin. Behavior was tested for different versions of RN by using the "--windowsVersion" flag to simulate different installed RN versions, and observing the package we try to install. Will verify this works as expected in 0.61-stable before …
> Teach React Native CLI about master and 0.61 versions

- change/react-native-windows-2020-03-24-20-28-28-winapi_ws_0.60_sharedwsr.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
- vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
- vnext/Desktop/Executors/WebSocketJSExecutor.cpp
- vnext/Desktop/Executors/WebSocketJSExecutor.h
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/ReactWindowsCore/IWebSocketResource.h
- vnext/ReactWindowsCore/WebSocketModule.h
- vnext/Shared/OInstance.cpp
See #4330 .
Changes `IWebSocketResource::Make` to return `std::shared_ptr` to ensure its lifetime when ran asynchronously.
> [0.60] Make IWebSocketResource as shared_ptr

- change/rnpm-plugin-windows-2020-03-24-23-34-25-fix-cli.json
- packages/rnpm-plugin-windows/src/windows.js
This fixes a small regression that came in with:
https://github.com/microsoft/react-native-windows/pull/4403
With this change you can no longer install react-native-windows with --windowsVersion file:<path>
This change fixes that.
> Small CLI fix

- change/react-native-windows-2020-03-25-16-16-54-HEAD.json
- vnext/ReactWindowsCore/V8JSIRuntimeHolder.cpp
- vnext/ReactWindowsCore/V8JSIRuntimeHolder.h
The V8 JSI inspector supports only limited scenarios, will always break on first line and will crash the process on detach.
This is just an early preview to enable basic debugging and profiling of the V8JSI runtime.
> Enable basic V8 direct debugging

- change/react-native-windows-2020-03-25-20-43-02-FixReactEvent.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactContextExtensions.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactEventInfo.cs
In the previous implementation of REACT_EVENT we only supported one argument for event handlers. It seemed to be the most common case. According to the issue #4401, the ReactNative events could support a variadic set of arguments 0..n. In this PR we are addressing this issue for C++ and C# code.
New unit tests are added to verify new scenarios.
Minor related change: start using C++17 folding expressions instead of array initializers to implement variadic argument reading/writing.
Closes #4401
> Allow NativeModules event handlers to have 0..n arguments

- change/react-native-windows-2020-03-26-09-13-41-certtimeout.json
- vnext/local-cli/generator-windows/index.js
Fixes #3930 
Another attempt at ensuring that project init doesn't hang.  #4423 helped on my local machine at least.  But user feedback is that that didn't prevent all the hangs.  -- So I'm adding a 15 second timeout to the certificate generation.  If it timesout it will fallback to the placeholder cert, as it does on other failures, or when generating from a non-windows box.
> Add timeout to certificate generation on project init

- change/react-native-windows-init-2020-03-26-12-07-31-newerrn.json
- packages/react-native-windows-init/src/Cli.ts
With the publication of RN 0.62, we now get into a case where there isn't a matching version of RNW for the latest RN.
This PR improves the error message when you install RN 0.62 and try to init RNW:
```
>npx react-native init myproject
>cd myproject
>npx react-native-windows-init
No compatible version of react-native-windows found.
The latest supported version is react-native-windows@0.61.0.
Please modify your application to use react-native@^0.61 or another supported version of react-native and try again.
```
> Provide better feedback when RN version has no matching RNW version

- .ado/templates/react-native-init.yml
- change/@office-iss-react-native-win32-2020-03-23-16-12-52-master-versioning.json
- change/react-native-windows-2020-03-23-16-12-52-master-versioning.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/package.json
- vnext/package.json
This change will start publishing our master branch using the 0.0.0 versioning scheme (with the next release being 0.0.0-master.1). 0.61 has been forked to stable, so it makes sense to do this now to avoid overlapping beta and stable releases.
> Publish Master Using "0.0.0-master.x" Version Scheme

- change/react-native-windows-2020-03-26-10-10-33-MS_NoAttributeModuleTests.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/ModuleMemberRegistration.h
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistry.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/NoAttributeNativeModuleTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactCallback.cs
This is an initial step to implement several important scenarios:
- Implement TurboModule code generation where module bindings are generated in a separate file based on Flow module spec, while the TurboModule is just a plain class that satisfies to the generated bindings.
- Fix .Net Native issue where our current reflection and dynamic code generation does not work and makes C# less performant and attractive. The plan is to generate NativeModule bindings similar to what we have in the new test NoAttributeNativeModuleTest.cs. We will need to do it for NativeModules, Views, and data serialization.
- Support NativeModule development where developers do not want to use custom attributes and prefer specifying bindings outside of modules.
While the three scenarios above are different, they …
> Added tests for NativeModule registration without custom attributes

- .ado/templates/react-native-init.yml
- packages/microsoft-reactnative-sampleapps/index.windows.js
- packages/microsoft-reactnative-sampleapps/myComp.js
This moves our CI task to use the new method of creating a new app. 
OLD:
```cmd
npx react-native init <myproject> --version 0.61.5
cd <myproject>
yarn add rpnm-react-native-windows
npx react-native windows
```
NEW:
```cmd
npx react-native init <myproject> --version 0.61.5
cd <myproject>
npx react-native-windows-init
```
> Use new init package instead of legacy rnpm one in CI

- .ado/publish.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- .github/workflows/pr.yml
Even the legacy CLI doesn't seem to rely on `v${branch}` tags (or current ore master), and they trample over anything we set in package.json. Stop tagging these so we an clean up npm tags.
While we're here, we try to inject the current branch name into more brachball logic in CI so we can avoid more changes while branching to stable releases.
Will cherry-pick this into 0.60-stable and 0.61-stable once in master.
> Do Not Override NPM Tag Based on Branch Name

- change/react-native-windows-2020-03-27-11-52-38-dd.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
- vnext/ReactWindowsCore/DevSettings.h
- vnext/Shared/OInstance.cpp
This was caused by a bad hook up the UI buttons, where the break at next statement and direct debugging callback were both hooked up to the direct debugging button.
Currently either webdebugging or livereload are the conditions to get the bundle from the metro server.  We should include fastRefresh in that logic.
Direct Debugging is fundamentally incompatible with remote debugging.  Previously the user had to manually disable one before enabling the other.  This PR toggles the other one for you.
> Some Direct Debugging fixes

- .ado/publish.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
* Do not Override NPM Tag Based on Branch Name
Even the legacy CLI doesn't seem to rely on `v${branch}` tags (or current ore master), and they trample over anything we set in package.json. Stop tagging these so we an clean up npm tags.
While we're here, we try to inject the current branch name into more brachball logic in CI so we can avoid more changes while branching to stable releases.
Will cherry-pick this into 0.60-stable and 0.61-stable once in master.
* Try massaging PR target branch var for Beachball
* Echo CI info
* Use System.PullRequest.TargetBranch without massaging
> [0.61] Do Not Override NPM Tag Based on Branch Name (#4434)

- change/react-native-windows-2020-03-27-17-22-39-remove-blank-lines.json
- vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
- vnext/local-cli/generator-windows/templates/cpp/src/App.h
- vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.cpp
- vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.h
Too many blank lines in the generated files, cleaning up.
> Remove extra blank lines in windows generator templates.

- change/@office-iss-react-native-win32-2020-03-30-16-03-07-disallow-pre61.json
- change/react-native-windows-2020-03-30-16-03-07-disallow-pre61.json
- packages/react-native-win32/package.json
- vnext/package.json
Beachball behavior without this change is to add to the prerelease section to our version if we backport a change from master. E.g. "0.61.0-0". This is dangerous given the workflow of cherry-picking already committed changes.
This change ends up leading Beachball to effectively no-op during publish. ideally this would instead be a human readable error. This is tracked as an issue at https://github.com/microsoft/beachball/issues/301
> Explicitly disallow prerelease changes in 0.61-stable

- change/react-native-windows-2020-03-10-22-14-59-reloadcrashes.json
- vnext/ReactUWP/Modules/TimingModule.cpp
- vnext/ReactUWP/Modules/TimingModule.h
- vnext/ReactWindowsCore/tracing/tracing.cpp
* Fix crash in timers during instance shutdown
* Fix crash in systrace
* Change files
> [0.60] Fix crash in timers during instance shutdown, and in systrace (#4291)

- change/react-native-windows-2020-03-30-10-57-30-winrt-async-asmw32.json
- vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.cpp
- vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.h
- vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
Make AsyncStorageModuleWin32 actually async using C++/WinRT & VC++'s supprt for coroutines.
Note that, since there is only one SQLite DB connection, there is only one SQLite statement executing at a time; this module provides asynchronous execution, but no parallelism. Tasks are executed in the order in which they are scheduled on the JS thread.
> Make AsyncStorageModuleWin32 actually async

- .ado/publish.yml
- .ado/windows-vs-pr.yml
- change/@office-iss-react-native-win32-2020-03-27-15-10-36-no-tag-60.json
- change/react-native-windows-2020-03-27-15-10-36-no-tag-60.json
- packages/react-native-win32/package.json
- vnext/package.json
* Do not Override NPM Tag Based on Branch Name
Even the legacy CLI doesn't seem to rely on `v${branch}` tags (or current ore master), and they trample over anything we set in package.json. Stop tagging these so we an clean up npm tags.
While we're here, we try to inject the current branch name into more brachball logic in CI so we can avoid more changes while branching to stable releases.
Will cherry-pick this into 0.60-stable and 0.61-stable once in master.
* Try massaging PR target branch var for Beachball
* Echo CI info
* Use System.PullRequest.TargetBranch without massaging
> [0.60] Do Not Override NPM Tag Based on Branch Name (#4434)

- .ado/publish.yml
- .ado/templates/build-rnw.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-03-31-10-16-02-msbuildx64.json
- packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj
* Removed x86 override for msbuild tasks in CI, publish
* Switch from MSBuild to VSBuild
* Added `<AppxGeneratePrisForPortableLibrariesEnabled>false</AppxGeneratePrisForPortableLibrariesEnabled>` to C# app projects to fix build issues with msbuild x64
* Added `/p:AppxGeneratePrisForPortableLibrariesEnabled=false` for testcli build task
> Update MSBuild ADO Tasks to use MSBuild x64

- change/react-native-windows-2020-03-31-20-25-48-FixNewProjectBuild.json
- vnext/Directory.Build.props
When we create a new project using the 'react-native init' we have a build error.
It says that it cannot find Microsoft.ReactNative.winmd file.
The issue was that the target destination of this file is reported as a relative path instead of an absolute one. This is because the $(ReactNativeWindowsDir) variable is not initialized since the Directory.Build.props file from our repo root folder is not deployed.
In this PR we ensure that we properly initialize the $(ReactNativeWindowsDir) before it is used for the build and target folder creation. It fixes the issue with the new project builds.
> Fix new project build

- change/react-native-windows-2020-04-01-05-05-07-FixMsoTest.json
- vnext/Mso.UnitTests/future/arrayViewTest.cpp
Mso ArrayView unit test was failing because it was using a reference to a temporary variable. The test is fixed by making sure that temporary is not destroyed while used.
> Fixed Mso test crash

- change/react-native-windows-2020-04-01-13-40-22-devtoolscrash.json
- vnext/ReactUWP/Modules/NativeUIManager.cpp
This currently makes using the react-devtools inspector very challenging, as if you click on any component that is not backed by a framework element you crash the app.
With this fix, you can happily click around the inspector crash free.
> Fix crash when calling measure on non-framework element

- change/react-native-windows-2020-04-03-04-48-03-ReactImage.cpp.patch.json
- vnext/ReactUWP/Views/Image/ReactImage.cpp
Does not follow specification: https://en.cppreference.com/w/cpp/language/coroutines
Does not compile with Clang 9.0.1 or with Clang 10.0.0
```
stderr: react-native-windows\vnext\ReactUWP\Views\Image\ReactImage.cpp:120:14: error: no viable conversion from returned value of type 'winrt::Windows::Storage::Streams::InMemoryRandomAccessStream' to function return type 'winrt::IAsyncOperation<winrt::InMemoryRandomAccessStream>'
return co_await GetImageStreamAsync(source);
^~~~~~~~
cppwinrt/winrt_generated_filesWindows#header-mode-symlink-tree-only,headers\winrt/impl/Windows.Foundation.1.h:46:36: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'winrt::Windows::Storage::Streams::InMemoryRandomAccessStream' to 'const …
```
> Fix co_routine in ReactImage.cpp

- change/react-native-windows-2020-04-03-03-58-46-ValueUtils.cpp.patch.json
- vnext/ReactUWP/Utils/ValueUtils.cpp
Does not compile with Clang 9.0.1 or with Clang 10.0.0
```
stderr: react-native-windows\vnext\ReactUWP\Utils\ValueUtils.cpp:201:27: error: qualified reference to 'duration' is a constructor name rather than a type in this context
return winrt::TimeSpan::duration(dur);
````
Compiles with Clang 9.0.1
Compiles with VS 2019
> Fix calling winrt::TimeSpan constructor in ValueUtils.cpp

- change/react-native-windows-2020-04-03-03-53-34-LocationObserverModule.cpp.patch.json
- vnext/ReactUWP/Modules/LocationObserverModule.cpp
Does not follow specification: https://en.cppreference.com/w/cpp/language/coroutines
Does not compile with Clang 9.0.1 or with Clang 10.0.0
```
react-native-windows\vnext\ReactUWP\Modules\LocationObserverModule.cpp:106:10: error: no viable conversion from returned value of type 'winrt::Windows::Devices::Geolocation::Geoposition' to function return type 'winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Devices::Geolocation::Geoposition>'
return location;
^~~~~~~~
cppwinrt/winrt_generated_filesWindows#header-mode-symlink-tree-only,headers\winrt/impl/Windows.Foundation.1.h:46:36: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'winrt::Windows::Devices::Geolocation::Geoposition' to 'const …
```
> Fix co_routine in LocationObserverModule.cpp

- change/react-native-windows-2020-04-03-03-43-11-FrameworkElementViewManager.cpp.patch.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
Does not compile with Clang 9.0.1 or with Clang 10.0.0
```
react-native-windows\vnext\ReactUWP\Views\FrameworkElementViewManager.cpp:41:8: error: class template specialization of 'json_type_traits' must occur at global scope
struct json_type_traits<winrt::react::uwp::AccessibilityAction> {
^
buck-out/gen/ec45211b/third-party/microsoft-fork-of-react-native/react-native-windows_MicrosoftReactNativeWindows#private-headers,windows-x86_64\Utils/PropertyHandlerUtils.h:55:8: note: explicitly specialized declaration is here
struct json_type_traits;
^
react-native-windows\vnext\ReactUWP\Views\FrameworkElementViewManager.cpp:57:8: error: class template specialization of 'json_type_traits' must occur at global scope
struct json_type_traits<winrt::IVector<winrt::react::uwp::AccessibilityAction>> {
^ …
```
> Fix template specialization error in FrameworkElementViewManager.cpp

- .ado/publish.yml
- .ado/setVersionEnvVars.js
- .ado/templates/build-rnw.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-03-26-09-13-41-certtimeout.json
- change/react-native-windows-2020-03-27-11-52-38-dd.json
- change/react-native-windows-2020-03-31-10-16-02-msbuildx64.json
- change/react-native-windows-2020-03-31-20-25-48-FixNewProjectBuild.json
- change/react-native-windows-2020-04-01-13-40-22-devtoolscrash.json
- packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
- vnext/Directory.Build.props
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/ReactWindowsCore/DevSettings.h
- vnext/Shared/OInstance.cpp
- vnext/local-cli/generator-windows/index.js
- vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj
This backports the following changes:
- Fix crash when calling measure on non-framework element #4473
- Fix new project build #4469
- Update MSBuild ADO Tasks to use MSBuild x64 #4462
- Some Direct Debugging fixes #4440
- Add timeout to certificate generation on project init #4430
- Handle publishing versions without pre-release versions #4489
> Backport various fixes to 0.61

- change/react-native-windows-2020-04-03-04-18-37-JSValueReader.h.patch.json
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
I have spent quite some time on this but I can't make it compile with Clang 9.0.1 or Clang 10.0.0 as a static assert prevents compilation.
```
In file included from react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers\NativeModules.h:8:
react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers/JSValueReader.h:160:5: error: static_assert failed "Unsupported char type"
static_assert(false, "Unsupported char type");
^             ~~~~~
1 error generated.
```
This happens on https://github.com/microsoft/react-native-windows/blob/react-native-windows_v0.60.0-vnext.133/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h - but it seems the same code is still in master
The problem happens here > …
> Make JSValueReader.h compile with Clang [RFC]

- .ado/templates/prep-and-pack-nuget.yml
- change/react-native-windows-2020-04-03-10-25-19-pubmsrn.json
- change/react-native-windows-init-2020-04-03-14-01-06-pubmsrn.json
- packages/react-native-windows-init/src/Cli.ts
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
- vnext/Scripts/Tfs/Layout-Headers.ps1
- vnext/local-cli/generator-windows/index.js
- vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.sln
- vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.vcxproj
- vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.vcxproj.filters
First couple of steps of moving towards DLL consumption.
NOTE: This will not start publishing that nuget on the public feed.
> Beginings of Microsoft.ReactNative nuget

- change/react-native-windows-2020-04-03-13-24-27-winapi_ws_0.60-modulesharedref.json
- vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/ReactWindowsCore/Modules/WebSocketModule.h
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
See #4330 .
Ensures `Instance` referenced by `WebSocketModule` stays valid.
> [0.60] Ensure React Instance reference lifetime in WebSocketModule

- change/react-native-windows-2020-04-03-16-53-54-fix-publish-61.json
- vnext/Directory.Build.props
This change ended up causing patched react native to land outside of the intermediate build directory, causing publish to fail. Revert it, since we seemed to not need it earlier (I think build logic after the branch changed where we defined ReactNativeWindowsDir). react-native-init CI will confirm whether this is okay to check in. Will need to follow-up to make sure publishing starts working after.
> Revert #4487 in 0.61-stable

- change/react-native-windows-2020-04-03-16-21-58-fix-publish.json
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- packages/playground/windows/playground/Playground.vcxproj
- vnext/Directory.Build.props
- vnext/PropertySheets/ReactDirectories.props
- vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
#4469 reordered build logic to define ReactNativeWindowsDir before it was seemingly used. This actually made it so we no longer correctly put patched react native sources in the right intermediate build output directory, since we don't define IntDir before including directory logic.
Seemingly the previous documented assumption was that we should define ReactNativeWindowsDir before including ReactPackageDirectories.props. This is oddd/error prone. This change combines logic so we can correctly interleave dependencies. It has the side effect of forcing anything including ReactPackageDirectories to include out intermediate output dir. This should only affect ReactUwp projects, which we will no longer be supporting for 0.62.
We can't actually test that this fixes publish because of #3889, but …
> Clean Up Directory Logic to Fix Publish

- .ado/templates/react-native-init.yml
- change/react-native-windows-2020-04-06-19-51-02-no-specialize.json
- vnext/PropertySheets/ReactDirectories.props
This should be as close as possible to what users run. Use the default IntDir in this job (Hopefully we shouldn't run into disk space issues with a single slice).
Fix some normalization behavior which seems to cause midl to fail due to having a directory traversal in one of its arguments.
> Directory Logic and CI Fixes

- .ado/templates/prepare-env.yml
- .ado/variables/vs2019.yml
* windows-2019 VMs were updated, fixing the CI with select changes from commit dd225633351d3119731b9b07ebbf4bc638e9e2d4 to fix E2ETest
> Fixing CI for 61-stable

- change/react-native-windows-2020-04-07-11-51-26-user-dzunisanindlhovu-windows-placeholderforeground-passwordbox.json
- vnext/ReactUWP/Views/TextInputViewManager.cpp
Added updates to TextInputViewManger for PasswordBox so that placeholderTextColor has and effect on PasswordBox - this is for TextInput with secureTextEntry=true
fixes: https://github.com/microsoft/react-native-windows/issues/4476
> placeholderTextColor for secureTextEntry=true on TextInput

- .ado/templates/prepare-env.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-04-06-15-55-46-winapi_ws_0.60-weakInstance.json
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Capture a weak reference to the Instance in the WebSocket resource's callback lambda and bail if it's not available.
> [0.60] Prevent reference cycles between WebSocketModule and React Instance.

- .ado/publish.yml
- .ado/templates/prep-and-pack-nuget.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-04-07-14-22-47-pubmsrn2.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
- vnext/Scripts/Tfs/Layout-Headers.ps1
Currently nuget creation isn't really getting any test coverage during PRs.  This should get them building again.
Also moved the logic for the experimental nuget init package to the x86 debug build, since that is the quicker of the slices.
> Rework more publish logic - produce nugets in PRs

- change/react-native-windows-2020-04-09-16-51-25-wsmodule_unittests.json
- change/react-native-windows-2020-04-09-16-51-56-wsmodule_unittests.json
- vnext/Desktop.UnitTests/InstanceMocks.cpp
- vnext/Desktop.UnitTests/InstanceMocks.h
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
- vnext/Desktop.UnitTests/WebSocketMocks.cpp
- vnext/Desktop.UnitTests/WebSocketMocks.h
- vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/ReactWindowsCore/Modules/WebSocketModule.h
- Add initial set of tests for class `WebSocketModule`.
- Define mocking support types.
> Enable WebSocketModule unit tests

- change/react-native-windows-2020-04-09-18-29-29-hardcode-beast-ws-0.60.json
- vnext/Desktop/Modules/WebSocketModule.cpp
Temporarily force usage of `BeastWebSocketResource`.
Follow up in #4559.
> [0.60] Hardcode Beast WebSocket resource in WebSocket module.

- .gitignore
- change/react-native-windows-2020-04-08-19-30-11-fork-localCLI.json
- vnext/local-cli/runWindows/runWindows.js
- vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
- vnext/local-cli/runWindows/utils/build.js
- vnext/local-cli/runWindows/utils/commandWithProgress.js
- vnext/local-cli/runWindows/utils/deploy.js
- vnext/local-cli/runWindows/utils/msbuildtools.js
- Surface msbuild errors (shows as undefined right now)
- downloading nuget with Invoke-WebRequest will usually take a long time because of the PS progress bar (which sadly gets updated for every byte), so I'm disabling the progress bar (it only takes a second to download when the progress bar is turned off)
- retry once if nuget failed since if you cancel at just the right time, you could end up with a truncated nuget.exe and are wedged unless you know which file to delete. Learned that the hard way.
- factor out calling onto powershell functions
- we were not exposing whether the function failed or not
> Improve inner loop and error reporting (local CLI)

- change/react-native-windows-2020-04-09-21-13-41-wsrc_openfails_nochangestate.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Setting this may prevent `PerformClose` from getting called, which leads to a hang.
> Don't set readyState on connection error

- change/react-native-windows-2020-04-09-21-13-37-wsrc_openfails_nochangestate-0.60.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
> [0.60] Don't set readyState on connection error

- change/react-native-windows-2020-04-10-16-49-23-redbox.json
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
- vnext/local-cli/runWindows/utils/commandWithProgress.js
- Improve RedBox ux. Shows formatted error message and stack trace
- Don't require elevation if dev mode is already on (we only need to elevate to turn on Dev Mode). 
New redbox (we can now select text for easy copy/paste):
> Improve redbox formatting and inner loop experience

- packages/playground/windows/playground/MainPage.cpp
In a rewrite from codereview I had a typo where the FastRefresh setting was based on the Break On First line checkbox instead of the fast refresh one.
> Fix fast refresh in playground app

- change/react-native-windows-2020-04-13-09-02-10-no-folly-suppress.json
- vnext/Folly/Folly.vcxproj
After upgrading to v142 build tools we no longer see MSBuild throwing up while unzipping files. Remove ContinueOnError from the build task.
> Remove Folly Unzipping ContinueOnError

- change/react-native-windows-2020-04-13-19-04-08-PasswordBoxFix.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
It looks like the headers from include\ReactUWP\Views were overlooked when the Microsoft.ReactNative project was created.  The projects build but intellisense doesn't work from CLI apps.
This change is just adding the missing headers.
> Add missing headers to Microsoft.ReactNative project

- change/react-native-windows-2020-04-14-16-58-37-consistency-in-instructions.json
- vnext/local-cli/generator-windows/index.js
Very minor change to bring this in line with upstream instructions, which always prefix `react-native` with `npx`. E.g. https://github.com/react-native-community/cli/blob/04537d5693e6780c3f177fa5bfe21109b6b80fb3/packages/cli/src/commands/init/printRunInstructions.ts#L29
PS: Wasn't sure if this needed a changelog entry, mostly because of the notion of it requiring a “pre-release”, which felt unnecessary to me 🤷‍♂️
> Consistency [with upstream] in instructions

- change/react-native-windows-2020-04-14-22-41-42-PasswordBoxBug.json
- packages/playground/Samples/textinput.tsx
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/ReactUWP/Views/ShadowNodeBase.cpp
- vnext/include/Include.vcxitems.filters
This fixes a bug in TextInput.  If you don't specify a height and also set secureTextEntry = true, the PasswordBox ends up with a 0 height.
The bug was caused by some missing logic in the code that swaps the TextBox out for a PasswordBox.  This code replaces the backing XAML element, but forgot to notify the UIManager which maintains a mapping from ShadowNode => XAML element.  Thus, after the swap, bad stuff happens in layout, causing us to push a 0 height into the PasswordBox.
The fix is straightforward - after swapping the control, notify the UIManager so it can update its mapping to the new XAML element.
Also changed our existing Playground test page to not specify a height, this exposes the issue.
> Password box bug

- change/react-native-windows-2020-04-15-00-20-55-sbp.json
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
When using web debugging and/or live reload, source bundle is obtained from the packager.
The source url for the bundle is `http://{HOST}:{PORT}/{NAME}{EXTENSION}?platform={PLATFORM}` where:
```
{HOST} = "localhost",
{PORT} = "8081",
{NAME} = "index.{PLATFORM}" where {PLATFORM} = "ios", "android", "win32", etc.
{EXTENSION} = ".bundle"
```
Currently, the `NAME` field is named `SourceBundlePath`, which incorrectly implies file path. This CR renames it to `SourceBundleName`.
(There seems to be a typo in `RedBox.cpp`. Also fixed that.)
> Rename DeveloperSettings.SourceBundlePath -> SourceBundleName

- README.md
This PR is updates/changes to the main REAMDE file on the landing page of the RNW repo.
> Updates to main README

- change/react-native-windows-2020-04-15-15-25-43-AccessibilityState.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
- vnext/src/Libraries/Components/View/ReactNativeViewViewConfig.windows.js
- vnext/src/RNTester/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
Fixes #4042 
In version 0.61, accessibilityState was introduced and accessibilityStates was marked as deprecated.
In version 0.62, accessibilityStates was removed.
This change implements accessibilityState and removes accessibilityStates.
The change is straightforward - instead of an array, the property is an object with fields.
> Implement accessibilityState

- change/react-native-windows-2020-04-15-15-25-43-AccessibilityState.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
- vnext/src/RNTester/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
cherry-pick of 9718f847a204dc971e5ea2e239ffb688db282c73 into 0.61-stable
> Implement accessibilityState (#4617)

- change/react-native-windows-2020-04-16-17-40-26-removeAccessibilityStates.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
Fixes #4593
Now that we have finished implementing AccessibilityState, and backported to 0.61, this change finally removes the AccessibilityStates API which was deprecated and is no longer part of the RN API.
> Remove AccessibilityStates

- change/react-native-windows-2020-04-17-02-58-34-khosany-exceptionsmanager.json
- vnext/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp
A crash is happening on line 114 because we are receiving a callstack from the JS side where the filename is null. Actual callstack contains some internal code, so I am not sharing here.
Fix is to return "<Unknown>" in that case.
This change is going to 0.60-stable only as this code is gone in newer branches.
> Fixing ExceptionsManagerModule

- package.json
- yarn.lock
I don't think this fully works correcty, and unlike lint-staged, `yarn format` has a pretty significant latency. Remove the hook for now.
> Remove Clang Format Pre-Commit Hook

- change/react-native-windows-2020-04-17-10-57-52-x64releaseyoga.json
- packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRegularBorder.json
- packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRoundBorder.json
- vnext/ReactCommon/ReactCommon.vcxproj
Fixes #4122 
There seems to be an issue with the v142 compiler bits which causes the code generated around CompactValue.isUndefined to not always return the correct value.
Using fp:Strict within yoga.cpp works around the issue. 
An alternative would be to fork CompactValue, and add pragma's to enable strict just around that. -- Or wait for a compiler fix. We should look at disabling this change on compiler updates to see if the compiler issue has been fixed.
> Fix issue with yoga in X64 Release builds

- change/react-native-windows-init-2020-04-20-13-55-48-tagininit.json
- packages/react-native-windows-init/src/Cli.ts
We had code to try to support npm tags for the --version parameter on `react-native-windows-init`, and are even using it in our CI loops to installed the test version.  But there appears to be a difference in behavior between npmjs.org and verdaccio which causes it to work when running against verdaccio  but it still doesn't work against npmjs.org.
This should enable instructions to run against latest master to be:
```cmd
npx react-native init <myproj> --template react-native@^0.62
cd <myproj>
npx react-native-windows-init --version master
```
> react-native-windows-init should support npm tags for --version parameter

- change/react-native-windows-2020-04-21-09-24-21-Fix_REACT_STRUCT_inline_issue.json
- vnext/Microsoft.ReactNative.Cxx/StructInfo.h
The changes is targeting the 0.61-stable branch. It is already fixed in master in PR #4656.
This PR Closes #4631.
The issue is that the `REACT_STRUCT` implements a `GetStructInfo` function and it does not have the `inline` keyword. It causes a linker error if a header file with such `REACT_STRUCT` code is included in multiple .cpp files.
In this PR we add the missing `inline` keyword to fix the issue.
> Added inline to REACT_STRUCT's GetStructInfo to use in header files

- change/react-native-windows-2020-04-21-09-35-21-devtoolsfix.json
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
This is the fall out from this commit that was part of 0.62
https://github.com/facebook/react-native/commit/e7f6210d5d417c5b6d4ba7f5cf96b40dbf70b9cd
> Opening the devmenu should attempt to connect to dev tools

- change/react-native-windows-2020-04-21-14-06-12-master.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/ReactUWP/Modules/DevSupportManagerUwp.cpp
- vnext/ReactUWP/Modules/DevSupportManagerUwp.h
- vnext/Shared/OInstance.cpp
The packager implements a websocket that allows apps to be recieve commands from the packager.  Two obvious commands are 'reload' and 'show devmenu'.
This PR makes the instance connect to this websocket and see the commands.  It hooks up reload.  The dev menu command is left as a todo for now, as the dev menu is currently tied to the root view, which is probably incorrect and will require some more refactoring.
> Hitting 'r' in the packager should reload the instance

- change/react-native-windows-2020-04-22-08-27-16-pubrel.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
I accidently had the release and debug bits overwrite each other in the nuspec.  This fixes the nuget to publish both ship and debug, and modifies the default project to use the debug dll when building debug.
> Microsoft.ReactNative Nuget only contains debug bits

- change/react-native-windows-2020-04-22-16-22-32-direction-rtl.json
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/include/ReactUWP/Utils/PropertyUtils.h
- vnext/src/RNTester/js/examples/RTL/RTLExample.windows.js
- vnext/src/overrides.json
Fixes #4668 
Fixes #4646 
Fixes #4645 
Fixes #4499 
This change fixes multiple RTL related issues.  At the most basic level, our implementation of direction == 'rtl' was incorrect.  The problem here was that we would do two things:
1) Yoga would see the direction == 'rtl' and do layout in an RTL fashion.  This results in absolute positions in a "flipped" coordinate space, which we would then push into XAML.
2) We also mapped the direction property to the XAML FlowDirection property and set this on the backing XAML element.  When FlowDirection == RightToLeft, XAML flips everything.
These two cancel each other out in the most basic scenario (a container with children stacked horizontally), so you'd end up with an LTR layout instead of RTL.
Also, there was code in place which tried to …
> Fixup direction == 'rtl'

- change/react-native-windows-2020-04-23-08-43-34-fix-build.json
- vnext/ReactUWP/Modules/DevSupportManagerUwp.h
This is causing failures in publish and locally. Possibly a silent merge conflict that got past CI?
> Fix Build Break Due To Missing Include in DevSupportManagerUwp

- change/react-native-windows-2020-04-23-11-35-11-MS_FixDotNetNative.json
- vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs
The investigation has shown that the .Net Native does not allow to have a parameter passed as 'ref' in a dynamically generated lambda. It was causing a crash when we generate ReadValue lambda to read custom class or struct where we pass the type by 'ref'.
In this PR we work around this issue by having a different delegate signature used for generating custom class reader. It uses return value instead of 'ref' parameter.
This change only affect the internal implementation of the Microsoft.ReactNative.SharedManaged code. There are no changes in user code required.
Closes #3838
> Fixed .Net Native crash for custom struct deserialization

- change/react-native-windows-2020-04-24-00-38-58-cli_sln.json
- vnext/local-cli/runWindows/runWindows.js
- vnext/local-cli/runWindows/utils/build.js
I ran into this trying to use the CLI on Playground which has 2 SLN (UWP and Win32)
Detect when we have more than one SLN as it may not be obvious to the user. 
Add --sln option to CLI.
> CLI behaves erratically when there is more than one SLN file

- change/react-native-windows-2020-04-24-01-46-24-cli_deployFromLayout.json
- vnext/local-cli/runWindows/utils/deploy.js
In Debug builds we should just use appx layout registration instead of installing APPX. This speeds up the CLI loop for debug and lets you rebuild without having to reinstall the app.
Fixes: #4673
> Deploy from layout in Debug builds

- change/react-native-windows-2020-04-24-16-02-17-4700.json
- vnext/ReactUWP/Views/ActivityIndicatorViewManager.cpp
> Fix typo causing activity indicators to be sad and colorless

- change/react-native-windows-2020-04-24-19-55-04-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/packages.config
Disable copying V8 dll to target output for UWP projects; we need a clearer way to distinguish uwp vs. win32 in the build system but this will do for now to unblock #4475
> Disable copying V8 dll to target output for UWP projects

- change/react-native-windows-2020-04-24-14-23-47-fix-textinput-brush-update.json
- vnext/ReactUWP/Utils/ResourceBrushUtils.cpp
Fixes #4193.
We are hitting [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/26118890) in xaml TextBox, which causes a crash when updating border or foreground while they use the same brush.
Creating a new brush for text border as a temporary workaround.
> Fix a crash when setting border/foreground color on TextInput

- change/react-native-windows-2020-04-24-19-55-04-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/packages.config
Backport of same change from master
> Disable copying V8 dll to target output for UWP projects (61)

- change/react-native-windows-2020-04-26-08-36-51-MS_Cxx_ReactContext.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
As we work on the C++ TurboModules, we want this design to be applicable for the generic C++ code and not just C++/WinRT. During the latest TurboModule design review with @acoates-ms he has noticed that the only required use of the C++/WinRT interfaces in the user-written TurboModule code is the new `Initialize` method with the `REACT_INIT` attribute. In all other places we already use abstractions such as `ReactConstantProvider`, `ReactPromise`, `ReactError`, etc.
In this change we add the new `ReactContext` into the `Microsoft.ReactNative.Cxx` shared code:
- It wraps up the `IReactContext`
- It adds convenience templated methods that directly accept JS function or event arguments. Internally they create the `JSValueArgWriter` delegate with help of the new `MakeJSValueArgWriter` method. …
> Added C++ ReactContext for Module Initialize method

- change/react-native-windows-2020-04-27-20-28-42-fix-peerdependency.json
- packages/E2ETest/package.json
- vnext/package.json
- yarn.lock
We updated react-native to 0.62.2 (which has a peer dependency of react 16.11.0), but our react version is still on 16.9.0, updating to 16.11.0.
> Update react version

- change/react-native-windows-2020-04-28-10-19-13-master.json
- vnext/.npmignore
This saves approximate 1.5 Mb in the final published package.
> Exclude test projects and proposals from being published in the npm package

- .ado/windows-vs-pr.yml
The build numbers in the [PR validation on Azure Devops](https://dev.azure.com/ms/react-native-windows/_build?definitionId=210&_a=summary) were numbered like `20200428..4` with two dots. This PR removes one of the dots, so new builds will be numbered like `20200428.5`
> Update version number of the Azure DevOps PR validation step

- change/react-native-windows-2020-04-27-16-11-30-allowRTL.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/ReactUWP/Base/CoreNativeModules.cpp
- vnext/ReactUWP/Base/CoreNativeModules.h
- vnext/ReactUWP/Base/UwpReactInstance.cpp
- vnext/ReactUWP/Modules/I18nModule.cpp
- vnext/ReactUWP/Modules/I18nModule.h
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/ReactWindowsCore/Modules/I18nModule.cpp
- vnext/include/ReactWindowsCore/II18nModule.h
Fixes #4684 
Fixes #4676 
Fixes #4670 
This change adds support for auto-detecting we're in an RTL locale, and flipping the FlowDirection on root view(s) to RightToLeft.  It also adds support for two i18nManager APIs:
forceRTL:  Used for testing, forces the framework into RTL mode even on LTR locales
allowRTL:  When set true, the auto-detection logic runs and flips the root into RTL in RTL locales.  The default value is true, same as the other platforms.
Note that if you toggle the primary language, you must restart the app for changes to be applied.  This is consistent with other platforms.
Tested this change out in the RTLExample page in RNTester which has a control to toggle forceRTL.
> Auto-detect RTL locale and apply to root view

- change/react-native-windows-2020-04-24-19-55-04-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/packages.config
Backport the same change from master
> Disable copying V8 dll to target output for UWP projects (60)

- change/react-native-windows-codegen-2020-04-29-06-16-44-uptsgen.json
- packages/react-native-windows-codegen/package.json
- yarn.lock
We were using some codegen code from RN 0.61 - this updates to to align with RN 0.62
> Update tscodegen to version based on 0.62

- change/react-native-windows-2020-04-29-10-09-33-tryUninstall2.json
- vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
Try uninstalling without elevation in case since it is not needed for layout installs (debug).
Fixes #4744
> Remove unnecessary CLI elevation

- change/react-native-windows-2020-04-29-03-21-18-testhook.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/TestHook.cpp
- vnext/Microsoft.ReactNative/TestHook.h
- vnext/Microsoft.ReactNative/getLayoutProps.ps1
- vnext/ReactUWP/ReactUWP.vcxproj
- vnext/ReactUWP/ReactUWP.vcxproj.filters
- vnext/ReactUWP/TestHookMock.cpp
- vnext/ReactUWP/Views/ViewManagerBase.cpp
- vnext/include/ReactUWP/Views/ViewManagerBase.h
> Refactor TestHook out of ViewManagerBase and special case layout properties

- change/react-native-windows-2020-04-29-18-21-26-4749.json
- vnext/local-cli/runWindows/runWindows.js
- vnext/local-cli/runWindows/utils/deploy.js
Opts .net projects out of the install from layout logic since that's broken as per #4749 (this isn't specific to RNW, as I can repro this with a plain C# UWP app)
> .net projects need more work to build a package layout

- change/react-native-windows-2020-04-29-02-59-44-yellowbox.json
- vnext/ReactUWP/Polyester/IconViewManager.cpp
- vnext/ReactUWP/Views/ShadowNodeBase.cpp
- vnext/include/ReactUWP/Views/ShadowNodeBase.h
> Expose YellowBox functionality to native code

- change/@office-iss-react-native-win32-2020-04-29-23-49-30-version-fixes.json
- change/react-native-windows-2020-04-29-23-49-30-version-fixes.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/package.json
- vnext/package.json
- yarn.lock
1. Use looser peer dependencies on React Native. 0.61 specified 0.61.5 explicitly, but based on recent discussion we want to allow patch releases of RN to work on any RNW version. Allow prerelease versions as well for any special forks, etc.
2. Fixup React Version everywhere. I missed upgraded React dependencies during the 0.62 upgrade. This was fixed in vnext and e2etest with #4734 but other packages were not updated. Update everything here.
> Package Version Fixes

- change/react-native-windows-2020-04-30-08-22-39-MS_RemoveReactAppRefCountHack.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
- vnext/Microsoft.ReactNative/ReactApplication.cpp
- vnext/Microsoft.ReactNative/ReactApplication.h
- vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
If user code directly inherits from the XAML `Application` class then it works just fine.
The issue is that if we inherit our `ReactApplication` from the XAML `Applicaiton`, and then user code inherits from the `ReacApplication`, then the C++/WinRT current COM aggregation fails to work correctly and we have a crash.
To work around the crash we have added the following lines to the user `App` constructor:
```C++
App::App() noexcept {
....
// This works around a cpp/winrt bug with composable/aggregable types tracked
// by 22116519
AddRef();
m_inner.as<::IUnknown>()->Release();
}
```
It was good for a quick workaround while we worked on the `ReactApplication` prototype, but in the long run this code has no place in user applications, especially the Windows bug number that has no meaning for …
> Removed the ref count work around from classes derived from ReactApplication

- .ado/templates/react-native-init.yml
We have seen random package restore failures in the CI for testing 'init' the packages are restored via a test server ([verdaccio](https://verdaccio.org/)). This adds a step in the [PR validation pipeline](https://dev.azure.com/ms/react-native-windows/_build?definitionId=210&_a=summary) to upload the verdaccio.log file (as configured in the [verdaccio yaml config file](https://github.com/microsoft/react-native-windows/blob/master/.ado/verdaccio/config.yaml))
> Add a step in CI to upload verdaccio logs to diagnose package restore failures

- change/react-native-windows-2020-05-01-15-34-56-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
For the win32 binary, delay load ChakraCore.dll to avoid paying the memory mapping cost if you're using a different engine.
> Delay load ChakraCore.dll

- change/react-native-windows-2020-04-29-09-45-05-master.json
- vnext/local-cli/runWindows/utils/msbuildtools.js
This fixes #4654 by adding [`/maxCpuCount`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019) through [msbuildtools.js](https://github.com/microsoft/react-native-windows/blob/master/vnext/local-cli/runWindows/utils/msbuildtools.js)
The bug is worried about missing dependencies but from testing it seems fine. And unfortunately there is almost no perf-gain either.
I tested on a 48-thread machine (2 x E5-2687W) with 64Gb ram and NVME SSD using:
1. `npx react-native init projectName --version ^0.62.2`
1. `cd projectName`
1. `npx react-native-windows-init --overwrite`
1. `npx react-native run-windows`
1. Close all opened windows
1. Open VS 2019 Developer prompt
1. `cd windows`
1. Run the commands below and record time elapsed
1. 00:02:51.80
1. …
> Add parallel MsBuild support (/m) when building the generated solution.

- change/react-native-windows-2020-04-30-12-57-06-fix-apppackage-path.json
- vnext/local-cli/runWindows/utils/deploy.js
The deploy script couldn't find the app package when `react-native run-windows` specifies a `--root` argument since it's searching for the hard coded windows folder.
Joining `options.root` with the existing search path to fix the issue.
> Fix appPackage path in deploy.js

- change/react-native-windows-2020-05-05-08-23-01-promptyes.json
- vnext/local-cli/generator-common/index.js
I just failed to correctly init a windows RN app because I typed 'yes' to overwrite the metro config, instead of 'y'.  
This makes 'yes' be treated the same way as 'y'.
Long term, I'd like to unify on the prompt we use in react-native-windows-init, but that call is async, and would require more refactoring of the template code.
> Treat yes the same as y in template overwrite prompt

- change/react-native-windows-init-2020-05-05-12-50-32-cli.json
- packages/react-native-windows-init/src/Cli.ts
For testing local changes to the template, its useful to be able to specify a filepath to a local react-native-windows package to use as a template.
With this you can now do something like:
```cmd
npx react-native init myProject --template react-native@^0.62
cd myProject
npx react-native-windows-init --version file:d:\repos\react-native-windows\vnext
```
Note that yarn does a copy of all the files under vnext to install react-native-windows.  Unlike when the package has been published, this will include all the native built files which would normally be excluded by npmignore.  Its probably better to clean your native built bits before running this command.
> Support --version file:<path> for running init against local changes

- change/react-native-windows-2020-05-06-05-03-56-no-fh4.json
- vnext/PropertySheets/React.Cpp.props
V142 Build tools turn on FH4 (CxxFrameHandler4) by default. This reduces the size of EH maps, but leads to incompatibility with code compiled using older toolsets. This is an issue for cosnumers that are not yet on Microsoft.ReactNative,
Disable FH4 until consumers (i.e. Office) are on an ABI-safe API or are updated.
Microsoft.ReactNative.dll x64 Release Size:
Before: 2,139 KB
After: 2,294 KB
Removal tracked by #4804
> Disable CxxFrameHandler4 

- change/react-native-windows-2020-05-05-19-47-51-dontBundleDuringIntellisense.json
- vnext/PropertySheets/Bundle.Common.targets
Fixes #4777 
the VS UI will hang when switching configuration to Release, because the Release build runs the bundler, and we run a build for Intellisense. However we don't need the bundler to run during intellisense so adding a check to exclude this task if either: running in VS and not running in VS "Build Project" mode (the condition is a little weird because it's negated).
> Don't bundle during intellisense

- change/react-native-windows-2020-05-04-19-05-45-OC-4133953-pwrav.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Resume point in `WinRTWebSocketResource::PerformWrite` is represented as a functor when awaited by the member `Mso::DispatchQueue`.
Such functor is currently implicitly created within `resume_on_queue::await_suspend` in the stack.
This change makes the functor a member variable so no stack allocations happen within `await_suspend`.
See https://devblogs.microsoft.com/oldnewthing/20191209-00/?p=103195
Note: work in progress.
> Ensure WebSocket write lifetime

- change/@office-iss-react-native-win32-2020-05-06-14-34-01-fixfast.json
- change/react-native-windows-2020-05-06-14-34-01-fixfast.json
- packages/E2ETest/metro.config.js
- packages/microsoft-reactnative-sampleapps/metro.config.js
- packages/playground/metro.config.js
- packages/react-native-win32/metro-react-native-platform.js
- packages/react-native-win32/metro.config.js
- vnext/local-cli/generator-windows/templates/metro.config.js
- vnext/metro-react-native-platform.js
- vnext/metro.config.js
Fixes #4779 
The reason fast refresh wasn't working is that fast refresh requires a custom implementation of require to be used within the bundle.  That implementation of require expects a custom property 'Refresh' to be set on it.  That variable is set by 'setupReactRefresh', which is one of the things that InitializeCore does.
The solution to allow metro to work on all platforms at once caused the default config of metro to not run InitializeCore before other modules.
This happened because the default react-native config of metro uses a full path to react-native's InitializeCore to tell metro to require that module before the main entry file of the apps.  Metro silently ignores paths in getModulesRunBeforeMainModule that are not part of the bundle. Since we use InitializeCore from …
> Ensure InitializeCore is run before app code

- change/@office-iss-react-native-win32-2020-05-07-09-53-55-renamerepo.json
- change/react-native-windows-2020-05-07-09-53-55-renamerepo.json
- change/react-native-windows-extended-2020-05-07-09-53-55-renamerepo.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/package.json
- packages/react-native-windows-extended/package.json
- vnext/package.json
- yarn.lock
> The react-native repo was renamed, this fixes the 0.60 branch to handle that

- change/react-native-windows-2020-05-06-21-22-41-OC-4133953-pwrav-60.json
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/ReactWindowsCore/Modules/WebSocketModule.h
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
- vnext/ReactWindowsCore/WinRTWebSocketResource.h
Backport of #4790
Resume point in `WinRTWebSocketResource::PerformWrite` is represented as a functor when awaited by the member `Mso::DispatchQueue`.
Such functor is currently implicitly created within `resume_on_queue::await_suspend` in the stack.
This change makes the functor a member variable so no stack allocations happen within `await_suspend`.
See https://devblogs.microsoft.com/oldnewthing/20191209-00/?p=103195
> [0.60] Ensure WebSocket write lifetime

- change/react-native-windows-2020-05-07-18-29-02-enable-binaryws.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
`SendBinary` was incorrectly enqueuing messages as non-binary.
> Correct WebSocket binary message tagging

- change/react-native-windows-2020-05-07-16-53-49-splitRWC.json
- packages/playground/windows/playground-win32.sln
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/JSI/Desktop/JSI.Desktop.vcxproj
- vnext/Microsoft.ReactNative.sln
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindows-Desktop.sln
- vnext/ReactWindows-Universal.sln
- vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj
- vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj.filters
- vnext/ReactWindowsCore/ReactWindowsCore.vcxitems
- vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
- vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
- vnext/ReactWindowsCore/packages.config
Today when you create a RNW app you get a copy of RNW source under node_modules, which you build. Currently, RNW references both V8 and Hermes nuget packages. These packages take up 1.6 GB of disk space and are not going to be used by 99% of apps. 
When V8 and Hermes support was added in March, the original intent had been that these should be optional - Tudor had added a Condition attribute to the package. However, packages.config does not support this syntax or conditionals in general, so this attribute is wholly ignored. From the PR description it seems also that only Win32 was tested.
This change splits ReactWindowsCore into a desktop flavor which maintains usage of V8 (and can enable Hermes if needed) and a non-desktop flavor that does not have this dependency. As a result, RNW …
> Remove V8 and Hermes by default

- change/@office-iss-react-native-win32-2020-05-07-14-18-13-clifeedback.json
- change/react-native-windows-2020-05-07-14-18-13-clifeedback.json
- packages/react-native-win32/metro-react-native-platform.js
- vnext/metro-react-native-platform.js
In https://github.com/react-native-community/cli/pull/1115 some minor code review feedback slightly modified the metro config.  I want our local copy that we are using until the CLI has this logic to match the CLI version as much as possible to catch issues, so I'm applying those changes here too.
> Align local metro config with future CLI changes

- change/react-native-windows-2020-05-07-18-50-32-enable-binaryws-62.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
`SendBinary` was incorrectly enqueuing messages as non-binary.
Backport of #4829
> [0.62] Correct WebSocket binary message tagging

- change/react-native-windows-2020-05-07-18-34-56-OC-4133953-pwrav-61.json
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Backport of #4790 and #4829
Resume point in `WinRTWebSocketResource::PerformWrite` is represented as a functor when awaited by the member `Mso::DispatchQueue`.
Such functor is currently implicitly created within `resume_on_queue::await_suspend` in the stack.
This change makes the functor a member variable so no stack allocations happen within `await_suspend`.
See https://devblogs.microsoft.com/oldnewthing/20191209-00/?p=103195
> [0.61] Ensure WebSocket write lifetime

- .ado/windows-vs-pr.yml
During the 0.61 timeframe, CI changes were added to use PR target branch in beachball scripts to avoid needing to manually change CI scripts when branching. Experimental Nuget work added a new usage without injecting PR target branch. This currently leads to CI failures when adding new changes to the 0.62 branch.
Make sure to use the right branch here.
> Ensure Beachball Uses The Right Branch for Experimental NuGet PR Tests

- packages/E2ETest/run_wdio.js
I'm going to break up my RNTester visual test PR (#4699) into independent pieces because it's too massive otherwise.
This part deals with improving run_wdio to report failed tests to the console, with stacks.
Fixes #4845.
> Improve run_wdio to print out failed tests

- change/react-native-windows-2020-04-29-15-37-41-imageonload.json
- vnext/ReactUWP/Views/Image/ReactImage.cpp
- vnext/ReactUWP/Views/Image/ReactImage.h
- Fire onLoad event when a bitmap image is opened so consumers can trigger other actions to happen afterwards
> Fire onLoad event when a bitmap image is opened

- change/react-native-windows-2020-05-11-11-06-42-FixReactContext.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/pch.h
The `ReactContext` had its copy and move assignment operators deleted by compiler.
The issue was that the `m_handle` was using `const IReactContext` instead of `IReactContext`.
In this PR we fix the issue and add unit tests for other `ReactContext` usage scenarios.
There are some other minor changes:
- Fixed IntelliSense issues in JSValueWriter.h.
- Removed NativeModules.h from pch.h to improve compilation speed. Otherwise, any change in Microsoft.ReactNative.Cxx code was invalidating the pch file and causing a full rebuild of Mso and other files in the Microsoft.ReactNative.IntegrationTests project.
> Fixed ReactContext copy/move semantic

- change/react-native-windows-2020-05-12-18-57-59-UnsafePropertyId.json
- vnext/Microsoft.ReactNative.Cxx/BoxedValue.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
The ReactPropertyBag allows storing only WinRT types. It can be useful to pass values across ABI boundary. In some cases we want to store non-WinRT types that local only to the native module.
In this change we add ability to store non-WinRT types in the ReactPropertyBag with help of BoxedValue wrapper.
> Allow storing non-WinRT types in ReactPropertyBag

- change/react-native-windows-2020-05-12-11-18-16-MS_UIQueue.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
- packages/playground/windows/playground-win32.sln
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/AppStateData.cpp
- vnext/Microsoft.ReactNative/Modules/AppStateData.h
- vnext/Microsoft.ReactNative/ReactApplication.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/RedBox.h
- vnext/Microsoft.ReactNative/RedBoxHandler.cpp
- vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
- vnext/Mso/dispatchQueue/dispatchQueue.h
- vnext/Mso/src/dispatchQueue/queueService.cpp
- vnext/Mso/src/dispatchQueue/queueService.h
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
- vnext/ReactUWP/Base/UwpReactInstance.cpp
- vnext/ReactUWP/Modules/AppearanceModule.cpp
- vnext/ReactUWP/Modules/AppearanceModule.h
- vnext/ReactUWP/ReactUWP.vcxproj.filters
The CoreDispatcher is a UWP-only implementation of a queue running on top of a window message handler. The newer Windows versions have new DispatcherQueue that works for UWP and Win32 applications.
In this PR we change the Mso::DispatchQueue to use the new DispatcherQueue instead of CoreDispatcher.  It enables use of the UI Mso::DispatchQueue implementation on Win32 platforms.
We had to change use of the UI Mso::DispatchQueue in our code to accommodate the DispatcherQueue restriction that it cannot be globally discovered in the application. Instead, we must create it in the ReactApplication and pass through the ReactNativeHost.InstanceSettings().Properties() to other components and native modules.
After this change we do not see the Playground Win32 crash at the startup.
> Use DispatcherQueue instead of CoreDispatcher for Mso::DispatchQueue

- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-05-11-17-22-16-rnw-dependencies.json
- docs/building-rnw.md
- vnext/Scripts/rnw-dependencies.ps1
We've had a number of people run into trouble trying to get set up. 
This script helps a contributor get a working environment on Windows.
This could be later folded into react-native doctor when we support it.
Fixes #4335 and I believe #4523 too.
> RNW dependencies

- vnext/Scripts/rnw-dependencies.ps1
> support running rnw-dependencies from web

- change/react-native-windows-2020-05-13-12-47-43-tabfocus-fix.json
- vnext/ReactUWP/Views/ControlViewManager.cpp
- vnext/ReactUWP/Views/ViewViewManager.cpp
Fixes #4703 
This fixes a regression that came in with this change:
https://github.com/microsoft/react-native-windows/pull/4180
this change introduced a convention that setting tabIndex = -1 makes the control no longer tab focusable.  This stomps over the behavior of the acceptsKeyboardFocus prop, making it not work correctly anymore.
This fix reverts that behavior.  To achieve this behavior, customers should set acceptsKeyboarFocus = false.  Note that this property will become deprecated and replaced by focusable.
> BugFix:  fix default tabindex stomping over acceptsKeyboardFocus

- change/react-native-windows-2020-05-13-14-16-07-rnw-dep-dontexit.json
- vnext/Scripts/rnw-dependencies.ps1
don't exit the powershell session and pause for keyboard input if interactive
> Update rnw-dependencies 

- change/@office-iss-react-native-win32-2020-05-12-21-44-51-accessibilityLabeledBy.json
- packages/react-native-win32/etc/react-native-win32.api.md
- packages/react-native-win32/package.json
- packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
- packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
- packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
- vnext/src/Libraries/Components/View/ReactNativeViewViewConfig.windows.js
Enable referential accessibility props accessibilityLabeledBy and accessibilityDescribedBy for Win32.
Also rewrites ViewWin32 from a class component to a function component, as generally virtuous and simplifying the life cycle (useLayoutEffect) insertion handling the referential props.
> ViewWin32 Accessibility: labeledBy, describedBy

- packages/playground/windows/playground/MainPage.cpp
The playground app does not use ReactApplication, and so its required that it provides a UIDispatcher as part of the instance settings.  - This was missed as part of #4877 
This gets playground booting again.
> Fix Playground app crash on instance load

- change/react-native-windows-2020-05-14-00-25-43-rnw-dep-winappdriver.json
- vnext/Scripts/rnw-dependencies.ps1
Don't install this one from choco as we need an exact version match. appium-windows-driver checks the checksum of WAD.
See \node_modules\appium-windows-driver\build\lib\installer.js
> Install exact version of WinAppDriver

- change/react-native-windows-2020-05-15-03-01-54-justMyXaml.json
- vnext/Scripts/JustMyXaml.ps1
Provide a script to easily turn off/on VS 2019's new feature "Just my XAML" since it hides programmatically created XAML elements from the Live Visual Tree.
> JustMyXaml.ps1

- change/react-native-windows-2020-05-15-14-54-00-jsxCrash.json
- vnext/ReactUWP/Views/ViewViewManager.cpp
- vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
Fixes #4918 
If the jsx is not valid we may end up trying to add something that isn't a UIElement (but a DependencyObject, like a Span) to an items Children collection, which will cause a E_NOINTERFACE exception. This is eventually caught by facebook's code and they `std::terminate()` / `abort()`.
Instead, skip adding the node and show a yellowbox and appropriate debug output.
> Prevent hard crash on invalid jsx (button inside text e.g.)

- change/react-native-windows-2020-05-15-21-43-34-MS_FixReactContext2.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
In this PR we fix the ReactContext CallJSFunction and EmitJSEvent functions.
There were the following issues:
- Cannot pass move-only values. It is fixed by capturing arguments by reference in MakeJSValueArgWriter.
- Cannot pass lambda for JSValueArgWriter argument. It is fixed by adding special MakeJSValueArgWriter overload and removed the ReactContext overloads for JSValueArgWriter parameter.
Added new unit tests to make sure that the ReactContext CallJSFunction and EmitJSEvent functions work correctly.
> Fixed ReactContext CallJSFunction and EmitJSEvent

- packages/override-tools/src/OverridePrompt.ts
After reported issues I recently moved `override-tools` to use `inquirer` instead of `prompts` for asking for override details. During validation I missed that we now assign an issue number to be text instead of a parsed integer. This propagates to the manifest when adding a new issue number, leading to an assumed invalid manifest.
Make sure we treat the issue number as integral when returning it. Additionally make sure to specify radix while parsing in all places.
Validated integral issues are added to the manifest instead of strings.
> Ensure Override Prompts Create Integral Issue Numbers

- change/react-native-windows-2020-05-17-09-26-39-MS_CallbackMultiArgs.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/NoAttributeNativeModuleTest.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative.SharedManaged/JSValueGenerator.cs
- vnext/Microsoft.ReactNative.SharedManaged/ReactMethodInfo.cs
The fix is related to the issue #4789. 
In our C# native module implementation we previously supported callbacks with only one argument in native modules. The C++ native modules already support callbacks with 0..n arguments.
In this PR we:
- Implemented support for callbacks with 0..n arguments in C#.
- Added unit tests for callbacks with 0..n arguments to C++ and C# code.
> Add support for 0..n args in native module callbacks

- change/react-native-windows-2020-05-18-02-05-00-chpurrer-rnw-clang-fixes.json
- vnext/Microsoft.ReactNative.Cxx/JSValue.h
- vnext/ReactUWP/Utils/ValueUtils.cpp
Right now the code does not compile with Clang 10.0.0
These changes should make it work on MSVC and Clang
Built on a local repository using BUCK with Clang
> Fix compile errors with Clang 10.0.0

- change/@office-iss-react-native-win32-2020-05-18-08-22-44-61-no-latest.json
- change/react-native-windows-2020-05-18-08-22-44-61-no-latest.json
- packages/react-native-win32/package.json
- vnext/package.json
Change the branch dist tag in preparation to move 0.62 to latest. This naming convention is somewhat ugly but matches what we've used for past branches. It is not currently possible to publish the package without a dist-tag, which would be preferable (beachball defaults to latest).
> Publish 0.61 as "v0.61-stable" instead of "latest"

- change/react-native-windows-2020-05-17-10-26-45-pressability-kbd.json
- vnext/src/Libraries/Pressability/Pressability.windows.js
- vnext/src/overrides.json
Fixes #4598
This change reenables touchables to be activated by keyboard/Gamepad. The implementation is mostly stolen from the previous that was used for Touchable. This doesn't participate in the input state machine, as its coupled to touch input. This means we don't get things like long-press detection (whether we want that is questionable), but we do still get feedback for key-in and key-out.
We should do something better when we upstream keyboard behavior to do proper integration into the Pressability state machine, but this is invasive enough that we shouldn't fork this.
Validated Spacebar and enter functionality with various touchables.
> Implement Keyboarding/Gamepad Activation for Pressability 

- change/react-native-windows-2020-05-20-12-14-56-certVS.json
- vnext/local-cli/runWindows/utils/Add-AppDevPackage.ps1
- vnext/local-cli/runWindows/utils/deploy.js
Fixes #4836 
Works around a regression in app packaging introduced in VS 16.5 which will be fixed in 16.7. For the time being, shipping a private copy of Add-AppDevPackage that has the fix for the issue.
> Work around regression in app packaging in VS 16.5-16.6

- change/react-native-windows-2020-04-24-14-23-47-fix-textinput-brush-update.json
- vnext/ReactUWP/Utils/ResourceBrushUtils.cpp
Brings the change made in #4708 into the 0.60-stable branch.
> Fix a crash when setting border/foreground color on TextInput (#4708)

- change/react-native-windows-2020-05-20-21-06-50-MS_FixVS16_6_build.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
The build in VS 16.6.0 is failing with linker errors that debug database is corrupted.
This PR has a temporary workaround where we replace the /ZI flag with /Zi that fixes the build.
We can rollback this change later when VS is fixed.
But for now this PR could unblock us to use the new VS version.
> Fixed Microsoft.ReactNative build in VS 16.6.0

- change/react-native-windows-2020-05-21-00-35-00-animation-bug.json
- vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
Fixes #4312 
xbox folks ran into this animation bug where the component stays stuck invisible.  I root-caused this back to a dirty flag issue in XAML.  I filed this bug for us to fix the XAML bug in WinUI 3.0:
https://github.com/microsoft/microsoft-ui-xaml/issues/2511
Meanwhile this change works around the XAML bug in a very non-invasive way.  We can force the XAML element to render by "poking" one of the properties that dirties it for render (then set it back to whatever it was).  Once dirtied, the XAML render walk will put the visuals back into the tree and the element will become visible again.
> Fix animation bug

- .gitignore
- change/react-native-windows-2020-05-21-08-23-39-preProcessTarget.json
- packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
- packages/playground/windows/playground/Playground.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/local-cli/runWindows/utils/msbuildtools.js
Deploy is needed for Debug builds of playground and e2etest
Add Preprocess target to M.RN since that's just generally useful
dont overwrite build logs when deploying
> Add preprocess target to M.RN and missing deploy target in playground, don't overwrite msbuild.binlog on deploy

- change/react-native-windows-2020-05-21-09-08-39-master.json
- vnext/PropertySheets/Bundle.Common.targets
- vnext/PropertySheets/Bundle.Cpp.targets
- vnext/PropertySheets/Bundle.props
- vnext/PropertySheets/Bundle.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
- vnext/PropertySheets/ReactPatches.targets
> Fix spacing and extra dot in copyright of the property sheets

- change/react-native-windows-2020-05-20-15-15-21-master.json
- vnext/ReactUWP/Views/TouchEventHandler.cpp
Closes #4566 
#2752 Discusses full mouse support. This PR is to mitigate the unexpected firing of identical onPress events for all mouse buttons.
Caveat - this approach results in the "Ended a touch event which was not counted in `trackedTouchCount`." warning being logged for all clicks other than the left mouse ones - open to suggestions of other ways to do this. 
I've tested that this doesn't break touch events (using my Surface laptop). Pen follows the same logic.
> Only emit click events for left mouse button

- change/react-native-windows-2020-05-21-16-35-04-doubleBuild.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
- vnext/local-cli/runWindows/utils/deploy.js
The fix for #4945 introduced an issue that manifests as projects not being able to be built more than once (or without a Clean pass).
The issue is that we Import the AppxRecipe file which has a bug in that the `ResolvedSDKReference` items are expected to have an `OriginalItemSpec` attribute in them, but they aren't being produced as such. When the build runs after we've built once already, we import these items from the appxrecipe, which lack this attribute, and the build breaks.
The fix is to only do the import conditional on a new variable which gets set by the CLI on deploy. The Deploy target is made conditional on this variable too.
> App projects only builds from clean (i.e. the first time only)

- change/react-native-windows-2020-05-21-13-01-25-WeakModule.json
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
This change is to address a customer need to be able to get a `std::weak_ptr` to a native module in case if the module must subscribe to some events. Since, a native module lifetime is bound to the React instance lifetime, we cannot use `this` pointer and we better use the `std::weak_ptr<T>`.
In this PR we enable the native modules to be inherited from the `std::enable_shared_from_this<T>` that allows use of the `weak_from_this()` function to get `std::weak_ptr<T>` to the module.
To support the new functionality we are doing the following changes:
- Introduce a mechanism for a module to associate a custom factory function with a module type.
- In case if custom factory is not provided then we offer two default native module factories:
- `MakeDefaultReactModuleWrapper` - the default …
> Implemented support for native module std::weak_ptr

- change/react-native-windows-2020-05-21-22-04-55-PR-FixInstanceLoading.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
This change is to address the issue #4923.
The crash was caused by React Instance not setting HasError state on error.
Since the state was as if the instance loaded correctly, it was causing crashes when code continues execution.
In this PR we are addressing the issue by setting the HasError state on error.
> Fix ReactInstance error state to avoid crashes

- packages/E2ETest/.eslintignore
- packages/E2ETest/app/ControlStyleTestPage.tsx
- packages/E2ETest/app/DirectManipulationPage.tsx
- packages/E2ETest/app/ImageTestPage.tsx
- packages/E2ETest/app/TestApp.tsx
- packages/E2ETest/app/TextInputTestPage.tsx
- packages/E2ETest/app/TransformTestPage.tsx
- packages/E2ETest/app/UnknownPage.tsx
- packages/E2ETest/wdio.conf.js
- packages/E2ETest/wdio/pages/BasePage.ts
- packages/microsoft-reactnative-sampleapps/.eslintignore
Fixes #4935
eslint will be default ignore node_modules. Custom ignore files adding node_modules is uneeded, but in E2ETest the file seemingly by design disables linting. We see some linting errors as well that nedeed fixing beyond formatting.
Fix that and get things formatted correctly.
// eslint-disable-next-line no-undef added for a couple of globals
> Remove unneeded or undesirable eslint suppressions

- change/react-native-windows-2020-05-21-13-07-11-independent_hostname_and_port.json
- packages/microsoft-reactnative-sampleapps/codegen/NativeMyModuleSpec.g.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/include/ReactUWP/IReactInstance.h
Addresses #2586.
Adds new settings `SourceBundleHost` (defaults to `localhost`) and `SourceBundlePort` (defaults to `8081`) to specify hostname and port. If `DebugHost` is set, these settings are ignored.
> Allow developers to independently set hostname and port.

- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
I was not able to load the SampleAppCpp because of misising nuget packages.
I assume that it is caused by updating to VS 16.6.0 and removing VS 2017 from my machine.
In this PR we are updating the SampleAppCpp project file to use newer versions of the packages.
Since it is sample project change only. It seems that no change file creation required.
> Fix loading SampleAppCpp in VS 16.6.0

- change/react-native-windows-2020-05-26-13-47-12-pull_request.json
- vnext/Microsoft.ReactNative/JsiReader.cpp
- vnext/Microsoft.ReactNative/JsiReader.h
- vnext/Microsoft.ReactNative/JsiWriter.cpp
- vnext/Microsoft.ReactNative/JsiWriter.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- Create `JsiReader` and `JsiWriter` for interface `IJSValueReader` and `IJSValueWriter`.
- Try to keep exactly the same behavior as `DynamicReader` and `DynamicWriter`, with a little change, because JSI doesn't support `int64_t`, and doesn't differentiate integer and double.
- The code is not tested, I will finish the unit test in another pull request after I figure out how to run dynamic and jsi in ComponentTests.
- Before `ReactHost`, `ABICxxModule` and `ABIViewManager` have a turbo module version, `JsiReader` and `JsiWriter` will not be called in the project.
> Create JSI implementation for IJSValueReader and IJSValueWriter

- change/react-native-windows-2020-05-28-09-47-11-master.json
- vnext/Directory.Build.props
This change makes it a lot easier when building from a shell inside common text editors like VsCode. They will allow one to click on the files in the terminal and jump to the file and line,column of the error. 
For example here is a screenshot of the Terminal inside VsCode on an artificially introduced C# error:
Of course this also helps when building from command line. This has no effect on the visual studio error list.
> Update shared props to have csc emit absolute paths on errors and warnings

- change/react-native-windows-2020-05-28-14-57-30-pull_request.json
- vnext/Microsoft.ReactNative.ComponentTests/CommonReaderTest.h
- vnext/Microsoft.ReactNative.ComponentTests/DynamicReaderTest.cpp
- vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
- Test cases added to Microsoft.ReactNative.ComponentTests
- Test cases executed by writing thing to the writer, and then read them out of the reader
- `Dynamic*` and `Jsi*` execute exactly the same set of test cases, to ensure that they behaves the same to each other.
> Add test cases for (Dynamic|Jsi)(Reader|Writer)

- change/react-native-windows-2020-05-28-23-34-14-projectImports.json
- packages/E2ETest/metro.config.js
- packages/microsoft-reactnative-sampleapps/metro.config.js
- packages/playground/metro.config.js
- vnext/local-cli/generator-windows/templates/metro.config.js
Fixes #5033 - at least the ProjectImports.zip part :)
Grab yourselves a chair because this is a doozy.
We've seen intermittent reports of Metro bundler hitting file-in-use errors on `msbuild.ProjectImports.zip` and similar. However there are no such files... WTH is going on and who is creating these files?!
We invoke MSBuild with the `/bl` flag to produce binary logs that we can inspect should something go wrong while building. These binary logs include all the commands that the build ran as well as all of the project files, props, targets, etc. that were imported. You can control whether the imported files are included in the `.binlog` file by choosing whether you want to `Embed` the imports (this is the default), create a separate zip file (`ZipFile`) or not include the imports at all …
> Block all ProjectImports.zip files

- .ado/variables/vs2019.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-05-20-12-14-56-certVS.json
- change/react-native-windows-2020-05-20-21-06-50-MS_FixVS16_6_build.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/playground/windows/playground-win32.sln
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/ReactUWP/ReactUWP.vcxproj
- vnext/local-cli/runWindows/utils/Add-AppDevPackage.ps1
- vnext/local-cli/runWindows/utils/deploy.js
This change cherry-picks 16.6 related fixes into 0.62-stable. Not all of these have yet gone through triage, but from earlier discussion it sounded like we saw 16.6 issues as critical, and we are currently unable to run PR validation for the branch. Eventually we may want to pin the branch to 16.5 for unrelated reasons around FH4.
> Cherry-Pick VS 16.6 Related Changes into 0.62-stable

- .ado/templates/e2e-test-job.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-01-16-47-14-master.json
- vnext/local-cli/runWindows/runWindows.js
- vnext/local-cli/runWindows/utils/build.js
- vnext/local-cli/runWindows/utils/deploy.js
- vnext/local-cli/runWindows/utils/msbuildtools.js
This change adds a new optional commandline option to `run-windows` to specify where the build logs should be saved. This change updates our CI to take advantage of this to store the logs in a specific directory that gets uploaded to an artifact after the build so it can be used for investigations.
> Allow paremeterization of buildLogDirectory for msbuild task when using run-windows

- change/react-native-windows-2020-06-02-09-55-24-FixReload.json
- packages/playground/windows/playground.sln
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactHost/React_Win.h
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
- vnext/ReactUWP/Views/ViewManagerBase.cpp
- vnext/include/ReactUWP/IReactInstance.h
Current ViewManagers hold to a weak pointer to the ReactInstance. They decide if it is safe continue or not based on the instance still being present. The issue is that during reload the instance can be already unloaded and to have an invalid state. In this change we expose IsLoaded method to communicate that instance is valid to be used.
It is all temporary and relatively fragile. We need to find a more permanent solution where the ReactInstance is immutable until it is destroyed.
> Fix ReloadInstance crash caused by unloaded instance

- change/react-native-windows-2020-06-02-11-56-08-packaging-61.json
- vnext/local-cli/runWindows/utils/Add-AppDevPackage.ps1
- vnext/local-cli/runWindows/utils/deploy.js
Backporting #4958
Since we changed pipeline images since 0.61, I'm going to assume that if CI builds we're good to go :)
> workaround for UWP Packaging VS 16.5-16.6 regression backport to 0.61

- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-02-20-32-51-reenabledeskits.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp
- vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
- vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
A couple integration tests started failing with very high frequency after the latest [CI VM](https://github.com/actions/virtual-environments/blob/win19/20200531.1/images/win/Windows2019-Readme.md) upgrade:
- `RNTesterIntegrationTests::AsyncStorage`
- `RNTesterIntegrationTests::IntegrationTestHarness`
This change selectively excludes those tests from running, allowing the rest of the tests to be validated in the CI loops.
> Re-enable most Desktop integration tests

- .ado/windows-vs-pr.yml
The Yarn install step is taking about 7.5 minutes from time to time. This does not leave enough time for the other steps like linting.
> Extend timeout for 'Extra Checks' in PR validation

- change/react-native-windows-2020-06-04-13-09-07-master.json
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Debug.pubxml
- vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Release.pubxml
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
* Deploy codegen tool as standalone app, so the netcore runtime doesn't thave to be installed.
*  Fix SampleApp's run-windows. There was an error due to path issues.
* Add Deploy target to codegen project as an extra defense in case it gets looped into deployment by the solution build.
>  Fix SampleApp run-windows with deploy

- change/react-native-windows-2020-06-04-08-40-37-clang_build.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
For IsVoidResult() clang complains that the symbols is already defined.
For ForEachMember clang cannot resolve the template unless explicitly specified in the call and requires the size type to be size_t instead of int.
> Fix compile errors for clang in NativeModules.h - IsVoidResult and ForEachMember  

- change/react-native-windows-2020-06-04-13-42-36-pull_request_jsd.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
JSI requires API to be called on the same thread that running the JavaScript engine. Users need to call JSI when implementing a turbo module. Currently `IReactContext` has only `UIDispatcher`, it becomes a blocker.
Add this API to enable this scenario.
> Expose JSDispatcher on IReactContext

- change/react-native-windows-2020-06-01-15-09-20-pull_request.json
- packages/playground/README.md
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.cpp
- vnext/Microsoft.ReactNative/Modules/ClipboardModule.h
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp
- vnext/Microsoft.ReactNative/ReactPackageBuilder.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/Microsoft.ReactNative/TurboModulesProvider.h
- Add `AddTurboModule` to `IReactPackageBuilder.idl`.
- Pass it all the way to `facebook::react::CreateReactInstance` in `ReactInstanceWin`.
- `Clipboard` registers itself as a turbo module instead of a native module, only when web debugger is disabled.
- `TurboModulesProvider` has limited functionalities, which only satisfy `Clipboard` module's need.
- `Clipboard` module is updated to run Clipboard functions in UI thread.
- `Clipboard` is updated to run `ReactPromise` in Javascript Engine's thread.
> Expose turbo module registry API

- change/react-native-windows-2020-06-05-17-10-24-devmenudevsup.json
- packages/playground/windows/playground/MainPage.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
Fallout from #5115.  The devmenu is currently showing up even when DeveloperSupport is set to false.
(Also changing the playground app to always have DeveloperSupport turned on)
> DevMenu should only show up when DeveloperSupport is on

- change/react-native-windows-2020-06-05-21-41-46-RemoveLegacySettings.json
- packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/include/ReactUWP/IReactInstance.h
This PR is to simplify settings for ReactNative instance. Here we remove the `react::uwp::ReactInstanceSettings` struct which was used for the ReactUWP implementation before. After this change we initialize `ReactOptions` directly from the `ReactInstanceSettings`.
> Remove legacy react::uwp::ReactInstanceSettings struct

- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-05-20-16-51-FixIntegrationTest.json
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
One of the `Microsoft.ReactNative.IntegrationTests` is broken by a recent change.
In this PR we fix the broken test by updating the `DevManu.cpp` code to account for non-existing `CoreWindow` and `CoreDispatcher`. We are also adding the `Microsoft.ReactNative.IntegrationTests` to the CI to verify them for each PR.
> Add Integration tests to CI

- change/react-native-windows-2020-06-06-07-10-00-uselegacystretch.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/QuirkSettings.cpp
- vnext/Microsoft.ReactNative/QuirkSettings.h
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/ReactUWP/Modules/NativeUIManager.h
The following UI lays out differently in react-native-windows than on android/iOS.  This difference is due to android/iOS configuring yoga to "useLegacyStretchBehaviour".
This change aligns the yoga config of react-native-windows to match the other platforms.  -- However, I also added a property to the PropertyBag that can be added to restore the previous behavior.  This should allow apps to keep the current behavior until they can fix any issues with moving to the same layout config as the other platforms.
```jsx
<View
style={{
flex: 1,
}}>
<View
style={{
flexDirection: 'row',
alignItems: 'center',
}}>
<View
style={{
flexDirection: 'row',
alignItems: 'center',
// flex: 1, // RNW requires this or the two boxes will be flush together, not flush to left/right edges of screen
}}>
<View …
```
> Fix difference in layout algorithm between windows and other platforms

- change/react-native-windows-2020-06-05-17-57-31-animationLowerThanRS5.json
- vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
Fixes #5132 (turns a crash into a no-op).
We use XAML APIs that aren't available below RS5, and we say so in our docs, but we still crash. Let's not crash and instead no-op.
> Native Animations shouldn't crash on RS3-RS4

- change/react-native-windows-2020-06-08-21-53-49-5153.json
- vnext/local-cli/runWindows/utils/commandWithProgress.js
Fixes #5153 
Igor ran into an issue while making a change, where we were failing to run the `Start-Locally` cmdlet but the failure was not being treated as an error by the CLI. This fix addresses this for the scope of `runPowerShellScriptFunction`.
> Fail on PowerShell exceptinos

- change/react-native-windows-2020-06-08-13-24-45-nested_onPress.json
- vnext/ReactUWP/Views/FlyoutViewManager.cpp
- vnext/ReactUWP/Views/PopupViewManager.cpp
- vnext/ReactUWP/Views/TouchEventHandler.cpp
- vnext/ReactUWP/Views/TouchEventHandler.h
RNW nested  \<Text> tag translation uses a combination of XAML Run and Span elements, which get added to the collection of Inline elements of the resulting TextBlock and recursively its children Spans, while following these rules:
1. the outermost \<Text> becomes the parent XAML TextBlock
2. each piece of the string content of a \<Text> on a given level becomes a XAML child element of type Run 
3. each nested \<Text> becomes a XAML Span child element, appended to the InlineCollection of its parent, becoming a sister element on the same level as the Run elements.
For example, the JSX code on the left, produces the XAML tree on the right:
```
<Text>                 //<TextBlock>
"outer" {X}            //<Run> <Run>
<Text>                  //<Span>
"inner_1" {Y}            //<Run> <Run> …
```
> Fix - onPress callback not working for nested <Text> elements

- change/react-native-windows-2020-06-09-15-04-44-pull_request.json
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
- Add a new js bundle to require a turbo module from the native side and call a function
- Implement the turbo module and a test in IntegrationTests
- More tests will be added in the future to cover complete signatures
> Call turbo module in IntegrationTests

- .ado/templates/prepare-env.yml
CI currently installs RN globally.  This should not be needed, wastes CI time, and actually creates a potential of testing incorrect bits.
> We shouldn't ever need to install RN globally

- yarn.lock
> [0.62] Bump beachball from 1.31.0 to 1.31.1 (#4988)

- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-06-20-24-10-master.json
- change/react-native-windows-init-2020-06-06-20-24-10-master.json
- packages/react-native-windows-init/src/Cli.ts
- vnext/local-cli/generator-windows/index.js
- vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
- vnext/local-cli/generator-windows/templates/cpp/src/App.h
- vnext/local-cli/generator-windows/templates/cpp/src/MainPage.cpp
- vnext/local-cli/generator-windows/templates/cpp/src/MainPage.h
- vnext/local-cli/generator-windows/templates/cpp/src/MainPage.xaml
- vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.cpp
- vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.h
The `react-native-windows init` template generation had a bug where namespaces weren't properly accounted for in the cpp project.
This PR takes the x86 slice of the init tests and forces the cpp and the cs language versions to have a namespace.
>  Fix support for `--namespace` on react-native-windows init for cpp

- change/react-native-windows-2020-06-11-17-03-06-master.json
- vnext/metro.config.js
Periodically there is a locking issue when building `vnext/Microsoft.ReactNative.sln` when building with flag `/bl`. This flag tells msbuild to construct  a detailed binary log. As it is constructing the log it is creating a .zip file to contain all the build specs. In the solution the IntegrationTest project runs the metro bundler. This one tries to open the .zip file and gets a file access violationand fails the build.
This change adds it to the metro config's exclusion list so it won't try to read that zip file.
> Fix file lock issue with MSBuild's `/bl` flag and the metro bundler

- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-11-13-06-37-msrncxxnuget.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/ReactWin32.nuspec
- vnext/Scripts/Tfs/Layout-Headers.ps1
Long term native dependencies should come from the nuget, not the npm package.  This allows devs working on other platforms within cross platform packages to not have to download the native windows dependencies until they want to build windows.  Currently the native dependencies are part of the NPM package, which will have to continue to be the case until we can move to a binary distribution model.  But part of moving to a binary distribution model will be having a complete nuget for native consumption.
Stella recently tried to use only the nuget distribution and hit issues with writing custom native modules. This adds Microsoft.ReactNative.Cxx to the nuget -- which should unblock them.
> Add Microsoft.ReactNative.Cxx to the nuget package

- change/react-native-windows-2020-06-10-15-33-28-pull_request.json
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- `REACT_SYNC_METHOD`
- `REACT_CONSTANT`
- Add test cases to Microsoft.ReactNative.IntegrationTests
- `OneCallback` and `TwoCallbacks` for `REACT_METHOD`
> Implement SyncMethod and Constant for TurboModule

- change/react-native-windows-2020-06-10-20-32-34-logbox.json
- packages/playground/Samples/rntester.tsx
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.h
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/ReactUWP/Modules/NativeUIManager.cpp
- vnext/ReactWindows-Desktop.sln
Logbox is a replacement of the YellowBox UI, used to display warnings.  It is currently available by calling 
```js
require('react-native').unstable_enableLogBox();
```
but it will be enabled by default in 0.63.
LogBox works by creating an additional ReactRootView, so it will provide some good test coverage of multi root view scenarios.  I also fixed an issue with layout when there are multiple rootviews, where we would attempt to layout a bunch of elements before they had layout run on them.
> Implement Logbox module

- change/react-native-windows-2020-06-12-10-45-34-PR-BackportCallJSQueue.json
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Backporting to 0.62 part of the PR #5071 where we implement CallJSFunction calls queuing.
Native modules are initialized while the JS bundle is loaded.
They can start calling back to JS engine right after they are initialized.
Previously if calls are made before the JS is loaded, then they were discarded.
In this change we queue them up and send after the JS bundle finished to load.
It is the second attempt - the previous PR #5189 had too many commits in the list and it was closed without merge.
> [0.62] Cherry pick PR #5071 for CallJsFunction queuing

- change/react-native-windows-2020-05-13-12-47-43-tabfocus-fix.json
- vnext/ReactUWP/Views/ControlViewManager.cpp
- vnext/ReactUWP/Views/ViewViewManager.cpp
Fixes #4703
This fixes a regression that came in with this change:
#4180
this change introduced a convention that setting tabIndex = -1 makes the control no longer tab focusable. This stomps over the behavior of the acceptsKeyboardFocus prop, making it not work correctly anymore.
This fix reverts that behavior. To achieve this behavior, customers should set acceptsKeyboarFocus = false. Note that this property will become deprecated and replaced by focusable.
> [0.61] Cherry-pick PR #4893 for tab-focus bug #4703

- change/react-native-windows-2020-06-15-12-36-45-border-black.json
- vnext/ReactUWP/Utils/ResourceBrushUtils.cpp
- vnext/ReactUWP/Views/ViewPanel.cpp
- vnext/include/ReactUWP/Utils/PropertyUtils.h
- vnext/include/ReactUWP/Utils/ResourceBrushUtils.h
Fixes #4682
On other platforms, borders draw a solid color (black) by default if no brush color is specified.  On Windows, we are drawing transparent.
This change fixes the mismatch by using a default brush when no brush color is specified.  The default brush will be a theme brush that draws black on light theme, and white on dark theme.
A couple optimizations:
1 - the brush is cached in a per-UI-thread singleton class, as looking up the theme resource isn't free
2 - the default brush is only set if the border has thickness, to avoid the cost of setting a brush in the case where nothing draws
> Use default brush for borders

- .github/CODEOWNERS
1. Added a react-native-windows-backport-triage group with permissions to approve changes going into stable branches
2. Added wildcard enforcement to stable branches to require code owner sign off
3. Swap react-native-windows-write for eact-native-windows-backport-triage in branches where we want to enforce a triage approver has signed off on changes going into the branch
> [0.61] Enforce Triagers Review Changes Going into Stable Branches

- .github/CODEOWNERS
1. Added a react-native-windows-backport-triage group with permissions to approve changes going into stable branches
2. Added wildcard enforcement to stable branches to require code owner sign off
3. Swap react-native-windows-write for eact-native-windows-backport-triage in branches where we want to enforce a triage approver has signed off on changes going into the branch
> [0.60] Enforce Triagers Review Changes Going into Stable Branches

- .ado/templates/react-native-init.yml
- change/@office-iss-react-native-win32-2020-06-15-14-59-13-master-to-canary.json
- change/react-native-windows-2020-06-15-14-59-13-master-to-canary.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/package.json
- vnext/package.json
Fixes #4963
Will update docs and try to get the master dist-tag removed after. This would break anyone trying to use a caret version to update our master builds since we jumped backwards alphabetically semver-wise, but that was already unsupported and a very bad idea.
> Rename "master" packages to "canary"

- change/react-native-windows-2020-06-15-18-01-44-master.json
- vnext/.eslintignore
- vnext/.flowconfig
The target folder in vnext contains the build output from the windows modules. It also contains the unittest temp locatoins. These can frequently generate long paths. It seems that flow.exe is not compiled with long path support for windows and fails on those folders. Eslint also throws a bunch of warnings about the long paths if it encounters them.
> Don't `eslint` nor `flow check` the target folder

- change/react-native-windows-2020-06-15-17-03-11-pull_request.json
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- Turbo module enables `REACT_METHOD` for Callback and TwoCallbacks.
- I think the design of `MethodReturnType` needs to be changed after we totally drop native module, because the current signature cannot describe all kinds of functions that turbo module allows.
- There are conversions doing `(jsi::Value*, size_t) <--> jsi::Array)` for function arguments. It can be removed by changing `JsiReader` and `JsiWriter`. I will do this in another pull request.
> Implement REACT_METHOD + Callback/TwoCallbacks for turbo module

- change/react-native-windows-2020-06-16-14-33-30-PR-NativeModule_JSQueue.json
- vnext/Microsoft.ReactNative/NativeModulesProvider.cpp
- vnext/Microsoft.ReactNative/NativeModulesProvider.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
This PR addresses the issue #5211.
The NativeModules 2.0 are the native module implementation on top of the ABI-safe API.
Unlike the usual ReactNative native modules, they did not have ability to associate a message queue with them and always run on a special background serial queue. As we moving towards the TurboModules implementation that always run on JS queue, we change the NativeModules 2.0 to always run on the JS queue too. This way the NativeModules 2.0 and the upcoming TurboModules will have exactly the same threading model: run native code on the JS queue. 
Closes #5211
> Run NativeModules 2.0 in JS thread

- .ado/publish.yml
- .ado/templates/build-rnw.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-06-16-16-10-02-0.61-stable.json
- vnext/PropertySheets/React.Cpp.props
> [0.61] Disable V8 globally; turn it on only for Desktop builds

- change/react-native-windows-2020-06-16-23-39-51-pull_request_2.json
- vnext/Microsoft.ReactNative.ComponentTests/CommonReaderTest.h
- vnext/Microsoft.ReactNative.ComponentTests/JsiArgumentReaderTest.cpp
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
- vnext/Microsoft.ReactNative/JsiReader.cpp
- vnext/Microsoft.ReactNative/JsiReader.h
- vnext/Microsoft.ReactNative/JsiWriter.cpp
- vnext/Microsoft.ReactNative/JsiWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- `JsiReader` accepts `jsi::Value*, size_t` in constructor
- `JsiWriter` added `AccessResultAsArgs` for array root object
- Added test cases for above changes
- `TurboModulesProvider` uses above new API to eliminate unnecessary jsi object construction and copying
> Optimize TurboModulesProvider to not performing unnecessary (Value*, size_t) <--> Array conversions

- change/react-native-windows-2020-06-17-19-10-13-master.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
When building a project without building the solution the property SolutionDir is not defined. We do manually define it in our Directory.Build.props file, but that is only included by `Microsoft.Common.props` which is imported by `Microsoft.Cpp.Default.props`.
Therefore this change moves that import to after the common props. I tested locally by adding cpp files to VS and remove and add nuget packages and VS surprisingly seems happy and doesn't break at having the import a little lower.
> Fix building vcxproj files outside of solution

- change/react-native-windows-init-2020-06-17-19-17-04-master.json
- packages/react-native-windows-init/src/Cli.ts
> This change is only intended for developers working on react-native-windows, it is not intended
for end-developers 'using' react-native-windows.
The script for generating the templates is picked from the local\cli folder as defined in the react-native-windows package that the common-cli script install.
So to test any changes there one has to link the version you are using. The common
feature for this is [`npm link`](https://docs.npmjs.com/cli/link) or [`yarn link`](https://classic.yarnpkg.com/en/docs/cli/link/).
This allows one to 'register' their local dev enlistment as a package and use it from a test project.
Steps to test:
1. From [react-native-windows] enlistment
1. `yarn build`
This updates any built files (like ts to js etc.)
1. `pushd vnext && yarn link`
The react-native-windows …
> Update react-native-windows-init to support 'linking' the react-native-windows package for development

- .ado/windows-vs-pr.yml
Tests run consistently in development machines.
They should be stable to run in the CI environment.
> Re-enable Desktop integration tests in Debug

- .vscode/settings.json
- change/react-native-windows-2020-06-22-08-35-37-master.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNonAbiValueTests.cpp
- vnext/Mso.UnitTests/errorCode/maybeTest.cpp
- vnext/Mso.UnitTests/future/arrayViewTest.cpp
- vnext/Mso.UnitTests/future/futureFuncTest.cpp
- vnext/Mso.UnitTests/future/futureTestEx.cpp
- vnext/Mso.UnitTests/future/promiseGroupTest.cpp
- vnext/Mso.UnitTests/future/promiseTest.cpp
- vnext/Mso.UnitTests/future/whenAllTest.cpp
This PR fixes some of the warnings that are gumming up our CI results page. This PR particularly addresses the signed int vs unsigned int comparison warnings in our unit tests in the x86 builds.
> Fix warnings of signed/unsigned comparison mismatches on x86 builds

- change/react-native-windows-init-2020-06-22-09-35-38-master.json
- packages/react-native-windows-init/src/Cli.ts
> Prevent --useWinUI3 and --experimentalNugetDependency from being used at the same time in react-native-windows-init

- change/react-native-windows-2020-06-19-13-28-45-ms-rnw-staging.json
- vnext/Desktop.ABITests/MemoryTrackerTests.cpp
- vnext/Desktop.ABITests/NativeLogEventTests.cpp
- vnext/Desktop.ABITests/NativeTraceEventTests.cpp
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.cpp
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj.filters
- vnext/Desktop/pch.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/MockReactPackageProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/NativeModulesProvider.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.h
- vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp
- vnext/Microsoft.ReactNative/ReactPackageBuilder.h
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/RedBox.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Incremental change to share more code in the ReactNativeHost::ReloadInstance() execution path between the UWP and the Win32 DLL. This change does not yet allow to execute JS code through the Win32 C++/WinRT ABI; complexity in the instance management will probably require a few more incremental changes before this goal can be achieved.
> Share ReactNativeHost::ReloadInstance impl between UWP and Win32

- change/react-native-windows-2020-06-21-16-56-44-FixCSNullRef.json
- vnext/Microsoft.ReactNative.Managed/JSValueReaderGenerator.cs
When we implement a C# ReactNative application in 0.61 or 0.62 we are getting a runtime error for the  property read `propertySetter.IsPublic` when the `propertySetter` is null. 
In this PR we fix the issue by checking the `propertySetter` null value first.
> Fix JSValueReaderGenerator runtime error for read-only properties

- change/react-native-windows-2020-06-23-00-34-32-winui3preview1.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
Follow up from PR #5260 , make use of versions defined in WinUI.props for C# projects.
> C# projects to use XAML version from WinUI.props

- .ado/windows-vs-pr.yml
It turns out that when vstest has test assemblies of two different frameworks, it simply will succeed not running a single test :(
This PR splits out the tests for UAP and for NetCore into separate test runs to ensure we are actually running the unittests in CI.
> Split out UnitTests for managed code

- change/react-native-windows-init-2020-06-23-18-14-45-yarninit.json
- packages/react-native-windows-init/src/Cli.ts
Fixes #5296 
`yarn add react-native-windows@^0.62.0-0` seems to fail depending on the exact contents of package.json.  This changes the init script to manually add the dependency to package.json, then run `yarn` instead of using `yarn add`
> Fix issue running react-native-windows-init with yarn

- packages/playground/windows/playground/MainPage.cpp
- packages/playground/windows/playground/MainPage.h
- packages/playground/windows/playground/Package.appxmanifest
Fixes #5112.
To remote debug the Playground app follow the steps in the wiki: https://github.com/microsoft/react-native-windows/wiki/VS-Remote-Debugging
Don't forget to open the port on the host machine.
This implementation is based on #3535.
Limitations:
- There is no way to specify only the hostname or only the port, you have to specify both.
- Not sure what I am missing but running `yarn change` gives me the following error so I couldn't update the changelog:
> Fix remote debugging with web debugging in Playground.

- change/react-native-platform-override-2020-06-25-20-31-44-platform-override-lib.json
- packages/react-native-platform-override/package.json
Right now lib-commonjs isn't published in the public NPM package due to being in the gitignore. This makes it unusable outside of the repo. Package only the entry-point and built libs.
> Ensure lib-commonjs is packaged into react-native-platform-override

- .ado/templates/yarn-install.yml
- change/react-native-windows-2020-06-25-13-28-13-sourceBundleSettings.json
- vnext/IntegrationTests/TestRunner.cpp
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
- vnext/Microsoft.ReactNative/ReactInstanceSettings.h
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/ReactWindowsCore/DevServerHelper.h
- vnext/ReactWindowsCore/DevSettings.h
- vnext/ReactWindowsCore/DevSupportManager.cpp
- vnext/ReactWindowsCore/DevSupportManager.h
- vnext/ReactWindowsCore/IDevSupportManager.h
- vnext/Shared/OInstance.cpp
- yarn.lock
Fixes #5203 
We have two settings on the instance settings.  We have DebugHost which is a string of format <host>:<port> which specifies the location of the packager.  We also have SourceBundleHost and SourceBundlePort, which is essentially the same thing, split out as two properties.
Internally we are inconsistent on which of these properties we use, which leads to issues like #5203, where some features dont work properly unless you set both of these properties to the same thing.   This change modifies the settings object so that setting DebugHost stores the data in the SourceBundleHost and SourceBundlePort property.  Thus preventing the settings from getting out of sync.  I also went through and ensured that we are using a shared source for the default values, as some of those values …
> Unify storage for sourceBundleHost/Port and debugHost

- change/react-native-windows-2020-06-26-12-03-46-fixhmr.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Fallout from my previous PR #5203
> Fix empty host getting passed to HMR client when SourceBundleHost not specified

- .ado/publish.yml
We have a lot of versions with a single commit. Do a weekly rollup to avoid the current version spam we have.
Using a weekly rollup:
- We would have seen 7 preview releases of 0.62 instead of 17
- We would have seen 9 patch releases of 0.61 instead of 14
> Do weekly rollup of stable branches

- change/react-native-platform-override-2020-06-26-02-58-50-repo-scripts.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-platform-override/CHANGELOG.json
- packages/react-native-platform-override/CHANGELOG.md
- packages/react-native-platform-override/package.json
- packages/react-native-win32/package.json
- vnext/package.json
Beachball published a new verison of react-native-platform override but failed to publish. It didn't update the repo for the former change, so we need to do this manually to avoid trying to re-publish.
> Manually bump react-native-platform-override and deps

- change/react-native-windows-2020-06-26-15-45-16-master.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
> Fix build errors for codegen unittest project when building in VS2019

- change/react-native-windows-2020-06-28-11-36-54-StopGeneratingTestFiles.json
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
Every time we compile our solution we see two header files being generated for IJSValueReader and IJSValueWriter in the Microsoft.ReactNative.ComponentTests project folder. It is clearly something wrong with the C++/WinRT settings that cause the extra files being generated. In this PR we are changing the order on entries in the Microsoft.ReactNative.ComponentTests.vcxproj to match the Microsoft.ReactNative.Cxx.UnitTests.vcxproj. After this change we do not see the extra files being generated anymore.
> Stop generating extra files in MS.RN.ComponentTests

- change/@office-iss-react-native-win32-2020-06-29-13-50-34-tm-migrate.json
- change/react-native-windows-2020-06-29-12-14-42-tm-migrate.json
- packages/react-native-win32/src/Libraries/Alert/Alert.win32.js
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/src/Libraries/Alert/Alert.windows.js
- Extract module registration as a new method
- Migrate "Alert" to turbo module
> Migrate "Alert" to turbo module

- change/react-native-windows-2020-06-29-17-13-10-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
These were introduced initially with PR #2867. The comment states it was for Win7. Since Win7 is no longer supported and it seems there is no code that uses it (hence the warnings:)
```
##[warning]LINK(0,0): Warning LNK4199: /DELAYLOAD:api-ms-win-core-winrt-error-l1-1-0.dll ignored; no imports found from api-ms-win-core-winrt-error-l1-1-0.dll
##[warning]LINK(0,0): Warning LNK4199: /DELAYLOAD:api-ms-win-core-winrt-error-l1-1-1.dll ignored; no imports found from api-ms-win-core-winrt-error-l1-1-1.dll
##[warning]LINK(0,0): Warning LNK4199: /DELAYLOAD:api-ms-win-core-winrt-string-l1-1-0.dll ignored; no imports found from api-ms-win-core-winrt-string-l1-1-0.dll
```
> Remove delayload dependencies on some winrt apisets, to reduce warning count

- change/react-native-windows-2020-06-29-23-03-19-tm-devsettings.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- Migrate 'DevSettings' to turbo module
- Unable to test in playground because
- add menu is not implemented
- reload crashes when web debugger is not checked, regardless if 'DevSettings' is registered as either a native module or a turbo module, so this issue is not related to turbo module
- at least native methods are called
> Migrate 'DevSettings' to turbo module

- change/react-native-windows-2020-06-29-23-55-00-tm-const.json
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- `REACT_CONSTANT` and `REACT_CONSTANT_PROVIDER` in turbo module is only for migrating native modules
- When these macros are used, `getConstants` functions will be added to the turbo module
- If `REACT_METHOD` or `REACT_SYNC_METHOD` is defined using the name `getConstants`, adding constants will crash
> Implement REACT_CONSTANT as getConstants sync method for turbo module

- change/react-native-windows-2020-06-29-13-30-32-master.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/AutolinkedNativeModules.g.cpp
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
- packages/playground/windows/playground-win32/AutolinkedNativeModules.g.cpp
- packages/playground/windows/playground/AutolinkedNativeModules.g.cpp
- packages/playground/windows/playground/Playground.vcxproj
- vnext/Common/Common.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/JSI/Desktop/JSI.Desktop.vcxproj
- vnext/JSI/Universal/JSI.Universal.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
- vnext/Mso.UnitTests/object/objectRefCountTest.cpp
- vnext/Mso.UnitTests/object/objectWithWeakRefTest.cpp
- vnext/Mso/motifCpp/motifCppTest.h
- vnext/Mso/object/make.h
- vnext/PropertySheets/React.Cpp.props
- vnext/local-cli/generator-windows/index.js
- vnext/local-cli/runWindows/utils/autolink.js
We still have ~80 warnings in our CI Ouptut. This addresses:
* Linker Warnings for using both LTCG and Incremental
* Compiler warnings about define and then undefined WinRtLeanAndMean
* Compiler warnings about for unreacheable code
> Fix various compiler warnings

- change/react-native-windows-2020-06-30-12-50-33-tm-as.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- Migrate 'AppState' to turbo module
> Migrate 'AppState' to turbo module

- .ado/windows-vs-pr.yml
We have custom conditions on all of our jobs that check if the `Setup` step determines if we can skip the PR validation.
The side effect is that the default check (if the dependencies succeeded) is not executed. So when a build step fails (say Desktop X86Release) it will still kick off `RNWNugetPR` and `CliInitExperimental` steps which will invariably fail because the dependencies are not complete.
This PR adds the extra checks back, so that the failures we see show up are the actual first failures. This should also make the experience when we 'rerun' steps better as they list of jobs that github extracts form azure devops will not include the failed step that still needs to be rescheduled. We'll get the yellow ball instead of the red x reflecting the actual status sooner.
> Azure Pipelines: Don't run jobs if the dependencies haven't passed

- .ado/variables/vs2019.yml
Performing the recursive directory search in the existing script can take between 2 and 3 minutes, with this changes it is down to 1 second!
This updated script takes advantage of knowing that the dll is only in the root folder, so we list all directories in the extension folder and then filter it to the one which has the testadapter dll.
> Speed up finding Google TestAdapter extension in VS folder

- change/react-native-windows-2020-07-01-01-14-21-null-safety.json
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- vnext/local-cli/.npmignore
- vnext/local-cli/src/config/configUtils.ts
- vnext/local-cli/src/config/dependencyConfig.ts
- vnext/local-cli/src/config/projectConfig.ts
- vnext/local-cli/src/generator-common/index.ts
- vnext/local-cli/src/generator-windows/index.ts
- vnext/local-cli/src/runWindows/runWindows.ts
- vnext/local-cli/src/runWindows/runWindowsOptions.ts
- vnext/local-cli/src/runWindows/utils/autolink.ts
- vnext/local-cli/src/runWindows/utils/build.ts
- vnext/local-cli/src/runWindows/utils/checkRequirements.ts
- vnext/local-cli/src/runWindows/utils/commandWithProgress.ts
- vnext/local-cli/src/runWindows/utils/deploy.ts
- vnext/local-cli/src/runWindows/utils/msbuildtools.ts
- vnext/local-cli/src/runWindows/utils/vstools.ts
- vnext/local-cli/src/runWindows/utils/winappdeploytool.ts
- vnext/local-cli/tsconfig.json
This change continues the TS work, and brings the CLI close to the level of strictness of other TS projects in the repo. The main change here is around the strictNullChecks rule, where we will now see compile time failures if null can be propagated when not declared.
A couple strategies were taken to fix these:
- Fix up types or init ordering to make it easy to reason about nullability
- Throw exceptions where we used to previously propagate unchecked null values
- Mark some things as allowed to be dull
- Add a smattering of the "!" operator to assert to the compiler that we know something is not null
There were a couple of other quick fixes around not publishing unneeded sources, not coercing object to strings that we log, and ensuring the RunWindows BuildArch is exact.
> Enforce null/undefined safety for the CLI

- change/react-native-windows-2020-06-21-00-49-44-xamlGuard.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/XamlLoadState.cpp
- vnext/Microsoft.ReactNative/XamlLoadState.h
Fixes #5214 
This adds a mechanism to ensure we only load one of these options:
- System XAML
- System XAML + WinUI 2.x (but only one version of WinUI 2.x)
- WinUI 3
> Implement XAML version load guard

- change/nuget-exe-2020-07-02-03-17-13-better-nuget.json
- change/react-native-windows-2020-07-02-03-17-13-better-nuget.json
- packages/nuget-exe/.gitignore
- packages/nuget-exe/just-task.js
- packages/nuget-exe/package.json
- vnext/local-cli/src/runWindows/runWindows.ts
- vnext/local-cli/src/runWindows/utils/build.ts
- vnext/package.json
Fixes #5404
The nuget.exe CLI tool is not provided as part of a Visual Studio installation, and we cannot use the MSBuild built-in functionality without PackageReference. We used to have logic in run-windows to download a NuGet binary if one isn't present, or try to find one if not installed.
We can leverage npm to ensure we have a working version of NuGet instead. This change adds some build logic to publish NuGet to the NPM registry and ensure react-native-windows downloads the NuGet package during installation.
> Include "nuget.exe" as Package Dependency of react-native-windows

- change/react-native-windows-2020-07-01-20-53-19-master.json
- vnext/package.json
I did a search for any file with import or require of flow that would hit this folder and found none.
I did a search in *.*proj, *.props and *.targets as well as common script files and could not find a reference to this folder.
Therefore I am confident this folder is not needed to be shipped within the react-native-windows npm package.
Closing #4810
> Fix #4810: Remove the /vnext/etc/react-native-windows.api.md file from the shipping npm package

- .ado/templates/react-native-init.yml
- change/react-native-windows-2020-06-24-08-27-10-fix-nuget.json
- vnext/local-cli/generate-windows.js
- vnext/local-cli/runWindows/utils/build.js
* Try to Fix CI NuGet Errors
This change makes us use a deterministic NuGet binary that we always download. We remove the NuGetPath option which isn't exposed as a CLI option, and don't trust any local NuGet exe because we can't guarantee version. Instead of wrapping the entire logic in a recursive retry when downloading the binary, we isolate retries to just downloading the binary itself. We remove some of the blanket catches, command output parsing, and delegation to PowerShell instead of JS functions that were somehow leading to executing the whole command when trying to locate it?
Haven't tested locally. Will tell what CI thinks.
* Change files
* Rename changelog entry
* Close the write stream
* Https
* Make sure both streams finish sucessfully
* Update netcore version as azure devops …
> [0.62] Fix run-windows NuGet Errors in CI By Using Deterministic Binary (#5330) (and fix experimentalNuGet react-native-windows-init)

- .ado/windows-vs-pr.yml
This test started failing consistently.
Disabling while the test runner gets rewritten.
> Disable RNIntegrationTests::Logging

- change/@office-iss-react-native-win32-2020-07-06-17-39-31-unix-path-manifests.json
- change/react-native-platform-override-2020-07-06-17-39-31-unix-path-manifests.json
- change/react-native-windows-2020-07-06-17-39-31-unix-path-manifests.json
- packages/react-native-platform-override/src/Override.ts
- packages/react-native-platform-override/src/test/Override.test.ts
- packages/react-native-win32/overrides.json
- vnext/overrides.json
We internally keep normalized paths for overrides, but this ends up being a bit confusing in contrast to Unix style globs, and ideally the serialized path representation should be constant. Normalize to Unix style paths.
> Normalize override manifests to unix paths

- change/react-native-platform-override-2020-07-06-18-11-21-more-timeout.json
- packages/react-native-platform-override/jest.e2e.config.js
- packages/react-native-platform-override/just-task.js
These tests touch the network and have some variability. A recent CI run showed a test timing out. Increase the timeout, and enable verbose logging so we can see how long individual tests are taking (some seem to take much longer on CI than locally).
> Increase Timeout for react-native-platform-override e2etest

- change/react-native-windows-2020-07-01-20-42-11-master.json
- vnext/package.json
I did a search for any file with `import` or `require` of flow that would hit this folder and found none.
I did a search in *.*proj, *.props and *.targets as well as common script files and could not find a reference to this folder.
Therefore I am confident this folder is not needed to be shipped within the react-native-windows npm package.
> Fix #4809: Remove the /flow folder from the shipping npm package

- .ado/templates/react-native-init.yml
- change/react-native-windows-2020-07-07-11-27-33-experimental-nuget.json
- change/react-native-windows-init-2020-07-07-11-27-33-experimental-nuget.json
- docs/testing-nuget-packages.md
- packages/react-native-windows-init/src/Cli.ts
- vnext/local-cli/src/generate-windows.ts
- vnext/local-cli/src/generator-windows/index.ts
This flag was originally called "experimentalNugetDependency". Capitalization of this flag changed to "experimentalNuGetDependency", which broke its usage in 0.62. 0.62 was updated to the new capitalization, but the change was then later reverted to "experimentalNugetDependency", breaking its usage in 0.62 again.
Keep the naming that the most recent version of 0.62 expects.
> Revert to new experimentalNuGetDependency Naming

- change/react-native-windows-2020-07-07-11-46-41-lessredboxthrow.json
- vnext/Microsoft.ReactNative/RedBox.cpp
Currently when we hit a redbox error that is just a plain string, an exception is thrown as we attempt to parse the string as JSON.
In addition to being an annoying exception that causes the debugger to break when you have break on exceptions on, it also can cause the app to crash depending on the string.
This change avoids the attempted parse unless the string starts with a {, which it will in the case of metro errors which is what the code is trying to determine.
> Dont try to parseJson unless redbox error starts with {

- change/react-native-windows-2020-07-07-15-33-54-no-windesktop.json
- vnext/overrides.json
windesktop stubs are noisy for three-way merge since they often remove the entire file. Don't bother trying to merge them, since they're going away soon and the bar is to keep CI passing.
> Disable Override Validation for windesktop JS

- .ado/setVersionEnvVars.js
> Set the build number instead of tag in the publish

- change/react-native-windows-2020-07-07-17-23-33-ms-rnw-staging.json
- vnext/Desktop.ABITests/Application.manifest
- vnext/Desktop.ABITests/DynamicReaderWriterTests.cpp
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop/ABI/TestController.cpp
- vnext/Desktop/ABI/TestController.h
- vnext/Desktop/ABI/TestController.idl
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj.filters
- vnext/Desktop/module.g.cpp
DynamicReader and DynamicWriter components are already being built into the Win32 DLL; this change adds tests for them. As DynamicReader and DynamicWriter can normally not be activated, this change adds a helper component ('Microsoft.Internal.TestController') that allows us to create these components for test purposes. Once the ABI has been fully built up, we should be able to test these components in different ways. At this point, the Microsoft.Internal.TestController component can be removed again.
> Add DynamicReader, DynamicWriter tests [Core DLL]

- jest.config.js
Current behavior of running Jest from the Repo root is to enumerate quite a few tests in different packages, which then fail, as some aren't Jest tests and others need configuration. We test packages independently using Lerna already, so the main case where this comes up is if someone uses the Jest VS Code plugin with the repo open. I spend some time trying to coerce the Jest multi-project options to work correctly, but couldn't get reasonable behavior out of it. Instead we now print a warning and don't try to run anything.
> Don't try to run Jest Tests From the Repo Root

- change/react-native-windows-2020-07-08-13-10-31-deploy2.json
- vnext/local-cli/src/runWindows/utils/deploy.ts
Repo:
```
npx react-native init myapp --template react-native@^0.62
cd myapp
npx react-native-windows-init
yarn windows --release --arch x64
```
Result:
Cannot deploy the app -- cannot find AppxManifest.xml
The logic in the run-window CLI code to find the manifest is looking at various locations that we've used within RNW, but doesn't look at the default location that VS projects build to.  This code change adds the default location to the list of places it looks for it.
> run-windows cannot find built app with default init app

- packages/playground/windows/playground-win32/Playground-Win32.cpp
- packages/playground/windows/playground-win32/Playground-Win32.rc
- packages/playground/windows/playground-win32/resource.h
With this change you can now hit Ctrl-N to open new playground-win32 windows (new thread, new react host/instance) and hit Ctrl-O to open samples in them.
> Add multi-window/thread support to Playground-Win32

- change/react-native-windows-2020-07-09-16-24-07-ms-rnw-staging.json
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop.ABITests/ReactModuleBuilderTests.cpp
- vnext/Desktop/ABI/TestController.cpp
- vnext/Desktop/ABI/TestController.h
- vnext/Desktop/ABI/TestController.idl
An IReactModuleBuilder implementation had already been built into the Win32 DLL; this change simply adds tests to ensure that it can get exposed through the C++/WinRT ABI.
> Add ReactModuleBuilder tests

- change/react-native-windows-2020-07-09-01-14-31-ws-noexcept.json
- vnext/Desktop.UnitTests/WebSocketMocks.cpp
- vnext/Desktop.UnitTests/WebSocketMocks.h
- vnext/Desktop/BeastWebSocketResource.cpp
- vnext/Desktop/BeastWebSocketResource.h
- vnext/Shared/IWebSocketResource.h
- vnext/Shared/WinRTWebSocketResource.cpp
- vnext/Shared/WinRTWebSocketResource.h
`IWebSocketResource` implementations are already expected to signal error conditions through the provided error handler.
We should assure no exceptions will be thrown by this interface.
> Make IWebSocketResource methods noexcept

- change/react-native-windows-2020-07-09-19-01-16-abi-safety.json
- change/react-native-windows-2020-07-09-19-16-26-ms-rnw-staging.json
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop.ABITests/ReactPackageBuilderTests.cpp
- vnext/Desktop/ABI/TestController.cpp
- vnext/Desktop/ABI/TestController.h
- vnext/Desktop/ABI/TestController.idl
An IReactPackageBuilder implementation had already been built into the Win32 DLL; this change simply adds tests to ensure that it can get exposed through the C++/WinRT ABI.
> Add ReactPackageBuilder tests

- change/react-native-platform-override-2020-07-09-23-08-06-less-flakey.json
- packages/react-native-platform-override/jest.e2e.config.js
- packages/react-native-platform-override/just-task.js
Fixes #5471
Run react-native-platform-override tests sequentially to avoid saturating too many resources at once, and give an even more liberal timeout. Locally, running sequentially with a clean scratch repo does increase e2e test time from 40s to 60s.
> Try to work around Pipelines Network Flakiness Causing Test Timeouts

- change/react-native-windows-2020-07-08-13-10-31-deploy2.json
- vnext/local-cli/runWindows/utils/deploy.js
> [0.62] run-windows cannot find built app with default init app (#5466)

- change/react-native-windows-2020-07-10-14-20-55-ms-rnw-staging.json
- vnext/Desktop.ABITests/Application.manifest
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop.ABITests/ReactDispatcherTests.cpp
- vnext/Desktop/React.Windows.Desktop.vcxproj
This change exposes the ReactDispatcherHelper class through the ABI of the Win32 DLL and adds tests for an IReactDispatcher implementation it creates.
> Add ReactDispatcher tests

- change/react-native-windows-2020-07-10-00-43-28-islandsCompositor.json
- packages/playground/windows/playground-win32/Playground-Win32.cpp
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Views/ExpressionAnimationStore.cpp
- vnext/Microsoft.ReactNative/Views/ExpressionAnimationStore.h
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.h
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
- vnext/Microsoft.ReactNative/XamlView.cpp
- vnext/Microsoft.ReactNative/XamlView.h
This change switches RNW to use the compositor from the XamlRoot instead of using the one from the current Window object since there won't be one in islands scenarios. This has a couple of interesting consequences:
- you can only get the xamlroot for an object once it has entered the tree so getting the xamlroot and the compositor need to be deferred
- still want to use system xaml's window compositor since system xamlroot doesn't have a compositor asociated with it.
> Use XamlRoot's compositor on WinUI3

- change/react-native-windows-2020-07-13-15-28-45-ms-rnw-staging.json
- vnext/Desktop.ABITests/Application.manifest
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
The Win32 DLL was already being build with the IReactNotificationService (RNS) interface definition and and implementation thereof; this change uses a test shared with the UWP DLL to demonstrate that the RNS implementation in the Win32 DLL is usable.
> Add ReactNotificationService test

- change/react-native-windows-2020-07-13-19-23-54-ms-rnw-staging.json
- vnext/Desktop.ABITests/Application.manifest
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
The Win32 DLL was already being build with an ReactInstanceSettings implementation; this change uses a test shared with the UWP DLL to demonstrate that the implementation in the Win32 DLL is usable.
> Add ReactInstanceSettings tests

- .ado/templates/react-native-init.yml
Ealier I tried to use variables to not have to duplicate entire tasks based on certain conditions. @NickGerleman discovered that this doesn't always works. My hypothesis is that azure devops treats all variables globally, so when one job sets it, the other jobs see it immediately and they are not scoped to a job and/or the dependency graph... 
Therefore returning to duplicating the steps. 
This change does use `${{ if` rather than the `condition: ` field so the non executed path won't show up in the logs.
> Fix #5469: Don't rely on variables for conditonal logic AzureDevops Pipelines

- change/react-native-windows-2020-07-14-14-02-41-ms-rnw-staging.json
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
- vnext/Desktop.ABITests/ReactPackageProviderTests.cpp
The Win32 DLL was already being build with the IReactPackageProvider interface definition; this change adds a test to demonstrate that user code can implement that interface and register the respective implementation.
> Add ReactPackageProvider tests

- change/react-native-windows-2020-07-14-21-46-53-deskit-usedll.json
- vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- Allows having general integration and ABI tests in one project.
- Reduces build artifacts size by ~150 MB.
> Have Desktop integration tests use DLL instead of static linking

- .ado/publish.yml
- .ado/templates/e2e-test-job.yml
- .ado/templates/prep-and-pack-nuget.yml
- .ado/templates/publish-build-artifacts-for-nuget.yml
- .ado/templates/react-native-init.yml
This shaves about ~7 minutes of the download in the publish nuget phase.
I unfortunatley wasn't able to use the new one in the upload as it complains about the artifact already existing. The old one seems to support merging. I tried looking at the code for the upload, but there are too many wrappers and too much difference in the code to quickly determine this. I'll keep this on the backlog to investigate or when I get a chance to chat with someone from the devops team.
See https://github.com/MicrosoftDocs/azure-devops-docs/issues/2341 for details on difference between the old and new.
> Update artifact publish and download to the newer versions.

- change/@office-iss-react-native-win32-2020-07-16-08-40-50-bumprex.json
- packages/react-native-win32/package.json
- yarn.lock
Bumping to a version that has the alert module registered, so rex-win32 doesn't crash on boot
> [Win32] Bump rex-win32 version

- .ado/templates/build-rnw.yml
- change/react-native-windows-2020-07-15-21-24-35-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.DLL/packages.config
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj.filters
- vnext/Desktop/packages.config
- vnext/Directory.Build.props
- vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/packages.config
This change adds the nuget dependencies for sourcelink. What these packages do is adding a few targets that run during the build and produce a `myproj.sourcelink.json` file with something like:
```json
{"documents":{"Z:\\src\\react-native-windows\\*":"https://raw.githubusercontent.com/microsoft/react-native-windows/447f92738afcf6b3ccc567419455dd562f67c387/*"}}
```
which is then passed to all tools like cl.exe, link.exe, csc.exe etc and they will enrich the PDB with this information so that when this PDB is used on a machine without an enlistment that the file is downloaded from github.
See [SourceLink](https://github.com/dotnet/sourcelink/) for more technical details
It is unfortunate that UWP `.vcxproj` does not support `PackageRefernce` yet and is still on the old packages.config with …
> Enabling SourceLink support.

- change/react-native-windows-2020-07-16-16-31-04-master.json
- vnext/Scripts/rnw-dependencies.ps1
To support the new agents, this has to be patched since our CI is configured to use 64bit msbuild.
> Add fix for msbuild long paths in machine setup script

- change/react-native-windows-2020-07-16-17-09-31-deployPS.json
- vnext/local-cli/powershell/WindowsStoreAppUtils.ps1
- vnext/local-cli/src/runWindows/utils/deploy.ts
Fixing a few issues with the deploy from layout codepath
- we were using the script path instead of the manifest path (i.e. add-appxpackage.ps1 instead of appxmanifest.xml) to parse XML
- PWSH 7 has added some types to its baseline like the system.io.compression namespace but those need to be explicitly imported in windows powershell
> Fix layout deploy

- packages/E2ETest/metro.config.js
- packages/microsoft-reactnative-sampleapps/metro.config.js
- packages/playground/just-task.js
- packages/playground/metro.config.js
- packages/playground/package.json
Currently in the playground/E2E app some of the images on the RNTester image page, and within the logbox experience do not show up when debugging.   This is due to an issue with metro not able to handle assets that are located outside of the app's package folder, which is often the case in monorepos.
This change applies a workaround that the community uses for this case, which fixes this images within our repo.  Hopefully this is something we can look into fixing in metro in the future.
See  https://github.com/facebook/metro/issues/290#issuecomment-526774959
> Workaround for metro monorepo asset issues

- change/react-native-windows-2020-07-21-00-03-28-preview2.json
- packages/playground/windows/playground/Playground.vcxproj
- packages/playground/windows/playground/packages.config
- vnext/Microsoft.ReactNative.Cxx/UI.Text.h
- vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/WinUI.props
Moving nuget packages to preview 2 and adding a couple of properties that the VSIXs added in preview 2.
Turns out my xaml load guard caught a bug :)  we were using `Windows::UI::Text::FontWeights` instead of `Microsoft::UI::Text::FontWeights` which resulted in loading WUX.dll just to get a struct, so I fixed that.
> Move WinUI 3 to Preview 2

- change/react-native-windows-2020-07-21-01-18-27-perThreadCompositor.json
- vnext/Microsoft.ReactNative/Modules/Animated/AdditionAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/ModulusAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/MultiplicationAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/SubtractionAnimatedNode.cpp
- vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp
- vnext/Microsoft.ReactNative/ReactRootView.cpp
- vnext/Microsoft.ReactNative/XamlView.cpp
- vnext/Microsoft.ReactNative/XamlView.h
This is in advance of WinUI 3 / islands work, basically keep a reference to the per-thread compositor and use it instead of the current Window compositor (since that won't exist in WinUI 3).
Fixes #5498
> Use per-thread compositor

- .ado/templates/e2e-test-job.yml
- change/react-native-windows-2020-07-21-19-02-11-rntester-fix1.json
- packages/E2ETest/wdio/test/AAA_SmokeTest.spec.ts
- vnext/src/RNTester/js/utils/RNTesterList.windows.ts
This change moves the E2E test pages to the bottom of the RNTester list, to be less disruptive to folks.
> E2ETest small tweak

- change/react-native-windows-2020-07-21-19-54-05-master.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
PR #5184 Added the Microsoft.ReactNative.Cxx code to unblock an internal
Microsoft team. PR #5483 introduced a proper nuget package for this. 
Therefore this PR is removing the temporary workaround. 
If you depended on this, please update your project to take a dependency 
on the Microsoft.Reactnative.Cxx nuget package.
> Stop placing Microsoft.ReactNative.Cxx in the Microsoft.ReactNative nuget package

- change/react-native-windows-2020-07-23-13-43-02-fix62targets.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
This change adds the "Deploy" target to Microsoft.ReactNative.Uwp.CppApp.targets  and Microsoft.ReactNative.Uwp.CSharpApp.targets .
This change also adds the "Private" flag to the M.RN project reference for libs, which was missing and causes problems when trying to consume the modules in your app.
Closes #5581
> [0.62] Fixed external targets for apps and libs

- change/react-native-windows-2020-07-27-11-50-28-master.json
- vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
- vnext/PropertySheets/ManagedCodeGen/Microsoft.ReactNative.Managed.CodeGen.targets
This updates the targets for C# codegen to use the proper item vs property settings for msbuild task outputs.
Note: this does not affect the nuget version since that is a separate targets file.
> Update codegen targets for source mode to use property instead of items

- change/@rnw-scripts-create-github-releases-2020-07-28-07-39-21-draft-notes.json
- packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
We want to add manually curated notes before notifications with release notes are sent out. Tell the robots to create these as draft releases to give an opportunity for us to add our own notes first.
Manually tested the change locally. Need to spend some time making this more testable once we have UTs hooked up everywhere.
> Create release notes for first preview + stable release as a draft

- change/react-native-windows-2020-07-29-13-39-44-packagecon.json
- vnext/Desktop/pch.h
- vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp
- vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/DevSupportManager.cpp
- vnext/Shared/DevSupportManager.h
- vnext/Shared/IDevSupportManager.h
- vnext/Shared/Modules/ExceptionsManagerModule.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/PackagerConnection.cpp
- vnext/Shared/PackagerConnection.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Before this, if two instances were run against the same package server then the first one would be able to connect to the packager and receive reload commands.  But the second one would not be able to connect since the socket would already be in use.
You can hit this today in the playground-win32 app by opening a 2nd window running an instance in both windows.  When you hit 'R' in metro to reload the instances, only one of them will reload.
This PR changes it so that we can share a connection to the packager when multiple instances are run in the same app.  Which means in the above scenario both instances will reload.
This change also hooks up support for handling the DevMenu command from the packager, which will now correctly show the DevMenu when you hit 'D' in metro.
> Share packager connection between instances to same packager

- change/react-native-windows-init-2020-07-28-10-12-52-master.json
- packages/react-native-windows-init/src/Cli.ts
Fixes bug where the -usedevMode for react-native-init did not include adding the dependency to package.json.
This at the same time adds support for not passing a version and inferring it from the linked pacakge.
> Fix devmode for react-native-windows-init to add the package to packages.config as well

- change/react-native-windows-2020-07-31-21-11-13-deployDeps-62.json
- vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
- vnext/local-cli/runWindows/utils/deploy.js
Backporting the fix to #5500 to 0.62 as there have been a number of folks who hit this problem (we've been telling them to F5 in VS once to get bootstrapped, but this should work out of the box)
> [0.62] Install framework package dependencies 

- change/react-native-windows-2020-08-01-16-32-46-accvalue-crash.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Using Chakra, in AccessibilityExample we see the dynamic for min represented as a double (0.00000) and crash with a folly TypeError since we enforce the folly::dynamic value is an integer.
We're converting to a double anyway, so we instead rely on built-in folly type conversion instead of trying to coerce the value to an int to convert into a double again. (i.e. asDouble will convert an int to a double as well).
Note that we still see issues with the AccessibilityExample page that need to be addressed.
Will cherry-pick this into 0.63-stable.
> Fix Crash Using accessibilityValue Outside of Web Debugging

- change/react-native-windows-2020-08-03-16-13-47-tooltip.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
We currently put all tooltips in a textblock which is unnecessary and moreover breaks word wrapping logic
Fixes #5625
> Fix word-wrapping behavior of tooltips

- change/react-native-windows-2020-08-01-16-32-46-accvalue-crash.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
* Fix Crash Using accessibilityValue Without Web Debugging
Existing code will crash with a folly TypeError since we enforce the folly::dynamic value is an integer. Using Chakra, in AccessibilityExample we see the dynamic for min represented as a double (0.00000) and crash.
We're converting to a double anyway, so we instead rely on builtin folly type converstion instead of trying to coerce the value to an int to convert into a double again.
Note that we still see issues with the AccessibilityExample page.
* Change files
> [0.63] Fix Crash Using accessibilityValue Outside of Web Debugging (#5619)

- change/react-native-windows-2020-08-03-08-49-30-configbundler.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Views/ConfigureBundlerDlg.cpp
- vnext/Microsoft.ReactNative/Views/ConfigureBundlerDlg.h
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/Microsoft.ReactNative/Views/DevMenu.h
This aligns with the option provided in the iOS devmenu which allows developers to modify the remote host/port of the packager that the app should talk to at runtime.
> Add option to devmenu to configure bundler

- change/react-native-windows-2020-08-04-10-25-43-tooltip-0.63.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Related: #5625 
Ports #5626 to 0.63-stable
> [0.63] Fix word-wrapping behavior of tooltips

- change/react-native-windows-2020-08-03-22-04-44-simplify-ws-factory.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
- vnext/Desktop.UnitTests/UtilsTest.cpp
- vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
- vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
- vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
- vnext/Desktop/BeastWebSocketResource.h
- vnext/Desktop/HttpResource.cpp
- vnext/Desktop/Modules/WebSocketModule.cpp
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/Shared/IWebSocketResource.h
- vnext/Shared/Modules/WebSocketModule.h
- vnext/Shared/Utils.cpp
- vnext/Shared/Utils.h
The constructor of `Windows.Networking.Sockets.MessageWebSocket` may throw on abnormal but possible conditions (i.e. Windows.Networking.dll failing to load).
This change handles any construction-time exception and fails gracefully reporting the error to the JavaScript layer.
> Handle MessageWebSocket constructor exceptions

- change/react-native-windows-2020-08-05-12-35-53-viewManagerCore.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj.filters
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
- vnext/Microsoft.ReactNative/IViewManagerCore.idl
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
Split IViewManager into core and ui-dependent parts to remove dependency on XAML from Core projects
Fixes #5640
> View manager core

- .github/ISSUE_TEMPLATE/bug-report.md
We don't use the globally installed CLI anymore so we should use npx to run react-native
> Use npx to run react-native

- .github/ISSUE_TEMPLATE/bug-report.md
```
> npx react-native -v
error: unknown option `-v'
> npx react-native --version
4.10.1
```
> Issue Template: Should be --version, not -v

- change/react-native-windows-2020-08-07-00-19-17-transparency-fix.json
- packages/E2ETest/wdio/test/VisitAllPages.spec.ts
- vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.h
Fixes #5094
If a View has no background brush set, it doesn't hit-test in XAML.  However the expected behavior in RN is the opposite.  This means RN components won't respond to mouse events unless they have a background set.
This change automatically detects when a View has mouse event handlers registered and in that case sets a transparent background.  I also added an optimization that made this change simpler:  ViewManagerBase now calls a virtual OnPropertiesUpdated after all properties have been processed, which gives the view manager a chance to make a decision after all properties have been settled.
> Allow transparent Views to hit-test when mouse events are registered

- change/@react-native-windows-cli-2020-08-04-13-53-11-master.json
- change/react-native-windows-2020-08-04-13-53-11-master.json
- packages/@react-native-windows/cli/templates/cs/proj/MyApp.csproj
- packages/@react-native-windows/cli/templates/cs/proj/MyApp.sln
- packages/@react-native-windows/cli/templates/cs/src/App.xaml.cs
- packages/@react-native-windows/cli/templates/cs/src/ReactPackageProvider.cs
- packages/E2ETest/windows/ReactUWPTestApp.sln
- packages/E2ETest/windows/ReactUWPTestApp/App.xaml.cs
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/ReactPackageProvider.cs
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/ReactPackageProvider.cs
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleLibraryCS.csproj
- vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.cs
- vnext/Microsoft.ReactNative.Managed.CodeGen/ReactNativeNames.cs
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
- vnext/PropertySheets/ManagedCodeGen/Microsoft.ReactNative.Managed.CodeGen.targets
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.targets
- vnext/package.json
This change contains the following:
* It makes C# compile time CodeGen the default. Initial assumption was to ship the binary distribution where it is default, but that has been postponed to 0.64
* This fixes a problem with the Xaml designer where it sometimes gave compile errors because it didn't like the generated C# file being added dynamically by MsBuild during the build. To make this more robust I changed the strategy to have a partial class that is part of the repo and the other partial part is generated. This will also make the documentation easier to write for people that want to go back to the previous style of analysis.
* Update the samples with C# in our repo to use the same pattern as the init template.
> Make C# CodeGen the default

- .ado/templates/e2e-test-job.yml
- .ado/windows-vs-pr.yml
I did another survey of the uploads and added retrycount to all uploads that will run where there is a failure, will run when a job is retried. 
I have left the uploads where it is the last step in the pipeline to not have a retrycount since it cannot get into the bad state on retry.
> Add retry count to the artifactupload steps to support retries

- change/react-native-windows-2020-08-07-02-41-33-transparent-tweak.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.h
This is a small tweak to PR #5659 which added a static SolidColorBrush.  Static DO's aren't safe in general because they can't be shared across XAML instances, which can happen in a multi Core-Window application.  
The change is very straightforward - just changes to a member variable.  The object is still shared across all views in a single instance.
> Small tweak to #5659

- change/react-native-windows-2020-08-07-09-24-14-reloadtext.json
- vnext/Microsoft.ReactNative/RedBox.cpp
Fixes #5655 
The reload button on RedBox currently says "Reload (NYI)".  The button has since been implemented.
> Fix label of RedBox reload button

- change/react-native-windows-2020-08-09-05-01-47-textTransform.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Utils/TransformableText.h
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
- vnext/src/RNTester/js/examples-win/Text/TextExample.windows.tsx
Implement the `textTransform` prop: none/lowercase/uppercase/capitalize
The prop has some interesting behavior that requires us to differentiate between `none` and `undefined` namely that nested `<Text>` elements will inherit their parent `textTransform` if they don't have one defined themselves.
This is clunkier than I'd like it to be because of the ordering of operations between:
- Creating a view
- Setting its `text` property
- Setting its or its parent `textTransform` property
- Adding the view to its parent's tree
The ordering makes it necessary for us to keep state and calculate things instead of doing the transform in-place when setting the text or transform.
Added an RNTester section in the `<Text>` page which I copied from the iOS/Android examples.
> Implement textTransform

- change/react-native-windows-2020-08-11-06-11-05-remove-fh4.json
- vnext/PropertySheets/React.Cpp.props
Fixes #4804
This hasn't worked since VS 16.6 and all consumers should now be on V142. Remove flags to disable FH4.
> Remove compiler flags disabling FH4

- change/react-native-windows-2020-08-11-23-19-31-imageBrushCompositor.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.h
Fixed #5700 
It turns out the assumptions we had about ordering of when an image brush is created vs. when the image is added to layout (and therefore when the compositor is set) were wrong and things can happen out of order. Opting to use the thread compositor instead which is guaranteed to be set and valid as long as there is a `ReactRootView`.
> Fix crash due to missing Image brush compositor

- change/react-native-windows-2020-08-12-04-26-05-fix-yellowbox.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
When standing up the TextInput RNTester page I ran into ViewManagerBase assertions related to trying to embed Text elements inside of TextInput. To avoid debug assertions which may break tests, I implemented child manipulation functions in TextInputShadowNode to Yellowbox instead. One of the functions implemented was removeAllChildren, which seems to be called in cases where there were no children to begin with. This leads to seeing "Nested elements in TextInput are currently unsupported on Windows" in some cases where we shouldn't.
ViewManagerBase doesn't assert when the default removeAllChildren is called, and we shouldn't either.
> Fix Errant "Nested elements in TextInput are currently unsupported on Windows" Yellowbox Warnings

- change/@react-native-windows-cli-2020-08-13-11-25-40-lessautolinkchecks.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Since we run auto-linking at the start of `run-windows` there's no reason to run the check during the build.
Closes #5304
> Disable autolinking check in msbuild when using `react-native run-windows`

- change/react-native-windows-2020-08-13-11-05-38-wininetErrors.json
- vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
I commented about this in PR #5610 and followed up offline. Wininet errors strings are not normally resolved by cppwinrt since they require knowing they are wininet errors and cppwinrt doesn't do that: https://github.com/microsoft/cppwinrt/issues/710
This change adds the code to the web socket module to print out the right string, instead of "The text associated with this error code could not be found".
Fixes #5720
> Print out debug Wininet errors

- change/react-native-windows-2020-08-13-11-26-05-crashViewViewManager.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Fixes #5721
There are cases (read: race conditions) in which the m_view will not be a `ContentControl` but a `Microsoft.ReactNative.ViewPanel`
> Fix crash in ViewViewManager

- change/@react-native-windows-cli-2020-08-13-11-25-40-lessautolinkchecks.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Porting #5719 into 0.63.
Since we run auto-linking at the start of `run-windows` there's no reason to run the check during the build.
Closes #5304
> [0.63] Disable autolinking check in msbuild when using `react-native run-windows`

- change/react-native-windows-2020-08-13-16-50-11-master.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.DLL/packages.config
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/JSI.Desktop.UnitTests/packages.config
- vnext/JSI/Desktop/JSI.Desktop.vcxproj
- vnext/JSI/Shared/ScriptStore.h
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/React.Cpp.props
The new 0.3.3 package version includes (preliminary) uwp binaries as well.
> Bump V8 package version

- change/react-native-windows-2020-08-13-21-08-10-hyperlinkTooltip.json
- vnext/Microsoft.ReactNative/Polyester/HyperlinkViewManager.cpp
Followup to #5626 - make sure hyperlinks use string tooltips instead of a textbox so that word-wrapping works as expected
> Hyperlink tooltips

- change/react-native-windows-2020-08-14-09-57-33-fix-touchable-mouse.json
- packages/E2ETest/wdio/test/VisitAllPages.spec.ts
- packages/playground/windows/playground/MainPage.xaml
- vnext/.flowconfig
- vnext/overrides.json
- vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
- vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
- vnext/src/Libraries/Types/CoreEventTypes.windows.js
- vnext/src/RNTester/js/examples-win/Mouse/MouseExample.windows.js
- vnext/src/RNTester/js/utils/RNTesterList.windows.ts
Fixes #5715
See issue for some discussion. Pointer handling in RNW is something of a mess right now, but we need to preserve existing compatibility after conflicting mouse handling changes for Pressability changes were introduced. Fixup MouseEvent typings, add raw MouseEvent handlers to Pressability, and hook those to Touchables to allow previous behavior. We will need to reconcile this with other platforms eventually.
I don't hook this up to Pressable. This leaves it impossible to add hover styling to Pressable, but I would rather we wait until we have a more generalized solution for MouseEvents before forking more component APIs we will need to worry about breaking later.
Moved a mouse sample that existed in Playground to RNTester to try to catch mouse regressions in the future. …
> Restore Previous Behavior Allowing onMouseEnter and onMouseLeave on Touchables

- change/react-native-windows-2020-08-14-09-57-33-fix-touchable-mouse.json
- packages/playground/windows/playground/MainPage.xaml
- vnext/.flowconfig
- vnext/overrides.json
- vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
- vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
- vnext/src/Libraries/Types/CoreEventTypes.windows.js
- vnext/src/RNTester/js/examples-win/Mouse/MouseExample.windows.js
- vnext/src/RNTester/js/utils/RNTesterList.windows.ts
* Restore Previous Behavior Allowing onMouseEnter and onMouseLeave on Touchables
See issue for some discussion. Pointer handling in RNW is something of a mess right now, but we need to preserve existing compatibility after conflicting Pressability changes were introuced. Fixup MouseEvent typings, add raw MouseEvent handlers to Pressability, and hook those to Touchables to allow previous behavior. We will need to reconcile this with other platforms eventually.
I don't hook this up to Pressable. This leaves it impossible to add hover styling to Pressable, but I would rather we wait until we have a more generalized solution for MouseEvents before forking more component APIs we will need to worry about breaking later.
Moved a mouse sample that existed in Playground to RNTester to try to catch …
> [0.63] Restore Previous Behavior Allowing onMouseEnter and onMouseLeave on Touchables (#5736)

- change/react-native-windows-2020-08-14-09-57-33-fix-touchable-mouse.json
- packages/playground/windows/playground/MainPage.xaml
- vnext/.flowconfig
- vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
- vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
- vnext/src/Libraries/Types/CoreEventTypes.windows.js
- vnext/src/RNTester/js/examples-win/Mouse/MouseExample.windows.js
- vnext/src/RNTester/js/utils/RNTesterList.windows.ts
- vnext/src/overrides.json
* Restore Previous Behavior Allowing onMouseEnter and onMouseLeave on Touchables
Fixes #5715
See issue for some discussion. Pointer handling in RNW is something of a mess right now, but we need to preserve existing compatibility after conflicting Pressability changes were introuced. Fixup MouseEvent typings, add raw MouseEvent handlers to Pressability, and hook those to Touchables to allow previous behavior. We will need to reconcile this with other platforms eventually.
I don't hook this up to Pressable. This leaves it impossible to add hover styling to Pressable, but I would rather we wait until we have a more generalized solution for MouseEvents before forking more component APIs we will need to worry about breaking later.
Moved a mouse sample that existed in Playground to RNTester to …
> [0.62] Restore Previous Behavior Allowing onMouseEnter and onMouseLeave on Touchables (#5736)

- packages/playground/windows/playground/MainPage.cpp
The playground app allows manually entering an app name in the combobox but it doesn't handle it correctly (the app crashes when trying to cast the hstring to a combobox item).
> [Playground] Allow entering freeform app name

- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
Right now we publish NuGet packages to a test feed in RNWNugetPR using the current NPM version, then download that in react-native-init tests. NPM versions might have changed since the initial NuGet package creation if a new NPM version has been published since then.
This change makes it so that NuGet packages are packed to the local test feed after JS publish in react-native-init tests. This should ensure NPM versions match, and lets us avoid trying to match NPM versions in the earlier NuGet PR.
This shouldn't extend the critical path, and actually now lets us start init tests before the desktop PR has finished and also to download/pack a bit less in react-native-init PRs.  Note that we keep the existing NuGet packing step in PR, since it will have desktop coverage that init tests won't.
> Ensure PR Nuget and NPM Test Versions Match

- change/react-native-windows-2020-08-17-13-49-27-fix-62-ci.json
- vnext/src/overrides.json
Fallout from my last change. Extra Checks was seeing repeated timeouts due to Network Issues, so I pushed the PR in without it passing after locally validating. Looks like I missed something, since 0.62 didn't exempt examples-win from override validation and I didn't add it to the 0.62 manifest.
> Fix CI for 0.62-stable

- change/react-native-windows-2020-08-18-12-18-07-master.json
- vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/OfficeReact.Win32.nuspec
Update nuspec copyright header to use xml entity as some of the powerhell processing we do messed up the encoding
> Update nuspec copyright header to use xml entity

- change/@react-native-windows-cli-2020-08-18-14-40-14-autolinking.json
- packages/@react-native-windows/cli/src/config/configUtils.ts
- packages/@react-native-windows/cli/src/config/dependencyConfig.ts
- packages/@react-native-windows/cli/src/config/projectConfig.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
This fix restores the original logic for config and autolinking, which were changed in the conversion to TS, which broke both.
Closes #5771
> Fixing config and autolinking

- change/react-native-windows-2020-08-18-21-02-07-iwscallconv.json
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/Shared/IWebSocketResource.h
On x86, the default/implicit calling convention is `__stdcall`.
An ARM64 application consuming `react-native-win32.dll` may face linking errors when invoking `IWebSocketResource::Make` (ARM64 seems to expect `__cdecl` by default).
> Use explicit calling convention for IWebSocketResource::Make

- change/@office-iss-react-native-win32-2020-08-18-16-33-02-sourcemap.json
- packages/react-native-win32/.npmignore
The sourcemap files currently point to files in src, which are not part of the published package, which makes for a poor debugging experience.
> [Win32] Publish TS files in src as they are references in sourcemaps

- change/react-native-windows-2020-08-17-10-34-34-removeconfig62.json
- vnext/local-cli/config/dependencyConfig.js
- vnext/local-cli/config/projectConfig.js
The react-native config implementation introduced in RNW 0.61 does not
properly handle when userConfig is explicitly null. This can cause
errors when projects use null (correctly) to prevent the config from
running.
Closes #5752
> [0.62] Update react-native config to handle (userConfig === null)

- change/react-native-windows-2020-08-18-12-19-10-0.63-stable.json
- vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/OfficeReact.Win32.nuspec
Update nuspec copyright header to use xml entity as some of the powerhell processing we do messed up the encoding
This is the backport of change: #5765
> [0.63] Update nuspec copyright header to use xml entity

- .ado/windows-vs-pr.yml
- change/@react-native-windows-cli-2020-08-19-14-49-47-mp.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
- packages/@react-native-windows/cli/src/runWindows/utils/build.ts
- packages/@react-native-windows/cli/src/runWindows/utils/checkRequirements.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
This would be used by winui3 builds to hopefully reduce the occurrence of compiler out of heap space problems
> Add --singleproc option to run-windows

- change/react-native-windows-2020-08-19-23-14-35-openssl-1.0.2p.5.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.DLL/packages.config
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.IntegrationTests/packages.config
- vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
- vnext/Desktop.Test.DLL/packages.config
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/packages.config
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
- vnext/JSI.Desktop.UnitTests/packages.config
- vnext/NuGet.Config
- vnext/Scripts/OpenSSL.nuspec
- vnext/Scripts/OpenSSL.targets
- vnext/Test/React.Windows.Test.vcxproj
- vnext/Test/packages.config
- Installs the NuGet dependency from React Native's public repo (instead of nuget.org).
- Updates the OpenSSL NuGet package.
- Adheres to NuGet conventional structure.
- Adds license reference.
- Adds source repository information.
- Note: New package version supports ARM64.
> Upgrade to OpenSSL 1.0.2p_5

- change/react-native-windows-2020-08-18-21-02-07-iwscallconv.json
- change/react-native-windows-2020-08-19-23-34-08-revert-5778-iwscallconv.json
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/Shared/IWebSocketResource.h
Reverts microsoft/react-native-windows#5778
The reason Office is hitting the calling convention problem seems to stem from the fact that they are building a native ARM64 DLL and using an x86 react native DLL, which is not supported. After consulting with the CHPE team, it turns out you have to match the architecture of all binaries running on ARM64: either they're all ARM64-native or they're all CHPE (x86-on-arm64), you can't mix and match.
In the original PR I had asked why was IWebSocketResource special that it was triggering this. It turns out that it isn't :) and after speaking with Julio it looks like the fix just kicks the ball forward and you get a different linker error.
So long story short, the previous fix is not needed/correct, and there's an action item on Office/Julio to …
> Revert "Use explicit calling convention for IWebSocketResource::Make"

- .ado/SetupLocalDumps.cmd
- .ado/templates/e2e-test-job.yml
- .ado/templates/prepare-env.yml
we are seeing some builds fail with no error message which hints at cl.exe crashing so I'm setting up collecting cl.exe crash dumps
> set up collecting crash dumps for cl.exe in CI

- .ado/templates/react-native-init.yml
We've seen sporadic reliability issues downloading upstream packages through Verdaccio, and haven't been able to determine the root cause. We currently proxy both "react-native init" and "react-native-windows-init" through Verdaccio, even though we only need to use it for the latter. This change sets our npm proxy only after "react-native init" is run to shift more of package installation off of the proxy, hopefully improving reliability.
This doesn't address the root cause at all, which is still unknown.
> Don't Proxy NPM Registry for "react-native init"

- change/@office-iss-react-native-win32-2020-08-20-13-20-19-integrate-5-28.json
- change/react-native-windows-2020-08-20-13-20-19-integrate-5-28.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/.flowconfig
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- packages/react-native-win32/src/Libraries/Image/Image.win32.js
- vnext/.flowconfig
- vnext/JSI/Shared/ChakraRuntime.cpp
- vnext/JSI/Shared/ChakraRuntime.h
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/overrides.json
- vnext/package.json
- vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
- vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
- vnext/src/Libraries/Image/Image.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
- yarn.lock
This is the next available build, as it looks like upstream nightly publish was temporarily broken. Nothing too interesting here from scanning through commits.
A new native component prop was aded to RCTImage on iOS (and was present before on Android) for passing tag information from Image components in a React context to the native image loader, but the JS APIs aren't exposed publicly, so this is seemingly Facebook internal and not worth implementing.
NativeModulePerfLogger was renamed to BridgeNativeModulePerfLogger. We don't set a sink for this logging yet (nor does public RN seemingly), and most events are logged by shared C++ code we're using already, so there isn't much to do here either apart from changing the file we compile.
A mechanical interface change was made to jsi::runtime …
> Integrate 5/28 Nightly RN Build 

- vnext/proposals/active/keyboard-reconcile-desktop.md
Adding the doc to the repo for broader review and tracking. 
This addresses the PM design/POR part of #4346
> Create Reconcile keyboarding in desktop proposal doc

- .ado/windows-vs-pr.yml
- change/@react-native-windows-cli-2020-08-20-15-53-42-single-proc-mem.json
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Building projects in parallel seems to increase the likeliehood of compiler OOM errors without dramatically impacting performace (See #4739). We're seeing OOM issues frequently with run-windows in CI. Change default behavior to build a single project at a time on machines that have <16 GB of memory. Not that this will still let individual CL processes use multiple cores, so we still do get some parallelism.
There doesn't seem to be an equivalent way to change the default for Visual Studio (from what I can tell default it to disable parallel project builds already).
> Default run-windows to disabling parallel MSBuild When Machine Has <=16GB of Memory

- change/react-native-windows-2020-08-24-18-13-47-master.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructOneArgParamReturnVoid--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructOneArgParamReturnVoid--Sync.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructParamReturnVoid--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseStructParamReturnVoid--Sync.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGenTestBase.cs
- vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
- vnext/Microsoft.ReactNative.Managed/JSValueWriter.cs
- vnext/Microsoft.ReactNative.sln
Fixes #5617 
This PR addresses 2 issues dicovered through the associated bug.
* There was no direct serialization for JsValueObject
* The C# codegen assumed people used the interface IReactPromise and not the instance struct.
> Fix C# interop serialization for JsValueObject

- change/react-native-windows-2020-08-24-13-14-55-logbox.json
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/ReactWindowsCore/IRedBoxHandler.h
- vnext/ReactWindowsCore/Modules/ExceptionsManagerModule.cpp
Partial cherry pick internals of support for ExceptionsManager.reportException.  This is used for logbox support which is off by default in 0.62.  This doesn't change the external interface of 0.62, or add support for LogBox externally.
It does enable win32 to provide a implementation of the LogBox native module and allow users turn on logbox using unstable_enableLogBox which will improve the experience for win32, which didn't have a good Redbox implementation.
> [Win32] Enable logbox support on 0.62 with experimental flag

- change/react-native-windows-2020-08-20-18-09-50-disable3D.json
- vnext/Microsoft.ReactNative/ReactRootView.cpp
- vnext/Microsoft.ReactNative/ReactRootView.h
- vnext/Microsoft.ReactNative/ReactRootView.idl
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
Some controls like `InkCanvas` do not work in environments where a 3D transform is present. RNW adds a `PerspectiveTransform3D` at the root in order to achieve a projective perspective look during rotations (the default for XAML is orthographic). This PR adds an API to turn off the perspective transform which enables controls like `InkCanvas` to work and receive input.
Fixes #5773
> Add API to enable non-3D controls

- change/@react-native-windows-cli-2020-08-25-14-33-38-archDeploy.json
- packages/@react-native-windows/cli/powershell/WindowsStoreAppUtils.ps1
Fixes #5793 
When determining which dependent framework packages to install we weren't filtering the list based on architecture, so if we were trying to install an x86 app and depend on a package that we only have the x64 version installed, we would report the package as installed and the app deploy would then fail since it depends on the x86 package.
> Fix deploy bug when framework packages are installed but not for all archs 

- change/react-native-windows-2020-08-25-14-42-13-archDeploy-0.62.json
- vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1
> [0.62] Fix deploy bug when framework packages are installed but not for all archs

- change/@office-iss-react-native-win32-2020-08-26-03-46-19-fix-touchablewin32-recurse.json
- packages/react-native-win32/src/Libraries/Components/Touchable/TouchableWin32.tsx
onResponderGrant's currentTarget type changed from a react tag to host component. The target is untyped, but we were assuming it was a react tag and calling UIManager.measure on it. This ends up now trying to serialize a cyclical structure instead of a number, and infinitely recurses.
Call findNodeHandle to preserve previous semantics.
Effects NetUI 0.63 + master. Does not effect react-native-windows
> Fix TouchableWin32 Infinite Recursion on Click

- change/react-native-windows-2020-08-26-09-05-25-hardengetnui.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
I hit a crash on reload.  Couldn't hit it again, but the crash was caused by this function as called from PreviewKeyboardEventHandlerOnRoot.  PreviewKeyboardEventHandlerOnRoot correctly handles the null return, so this should prevent this crash.
> Harden ReactInstanceWin::NativeUIManager to return null when instance is being torn down

- change/react-native-windows-2020-08-27-07-37-21-fix-toast-activation.json
- vnext/Microsoft.ReactNative/ReactApplication.cpp
Clicking on a Toast notification should start the application. This change does that, but I'm not sure if other `ActivationKind`s need the same treatment or if/how to write a test for this change.
> Start application when activated by ToastActivation

- change/@react-native-windows-cli-2020-08-27-11-37-29-csharpmodulefix.json
- change/react-native-windows-2020-08-27-11-37-29-csharpmodulefix.json
- packages/@react-native-windows/cli/templates/cpp/proj/MyApp.sln
- packages/@react-native-windows/cli/templates/cs/proj/MyApp.sln
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
- vnext/PropertySheets/CppAppConsumeCSharpModule.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
Right now C++/WinRT apps have a hard time consuming C# WinRT libraries from source. We fixed this in our SampleAppCpp in order to load SampleLibraryCS, but those fixes were not put into the template for the benefit of all apps.
This PR moves the fix into new `CppAppConsumeCSharpModule.(props|targets)` files. Since the fix involves importing a ton of other props/targets, and we don't want to risk breaking existing C++ apps who have no need of consuming C#-based native modules, the changes are behind a new property `ConsumeCSharpModules`.
So if you have a C++/WinRT RNW app (the default) and need to consume C# native module, you can set `<ConsumeCSharpModules>true</ConsumeCSharpModules>` in your app project.
This PR also fixes up the template solution files to include the projects they were …
> Fixed templates so C++ apps can consume C# native modules

- .ado/templates/prep-and-pack-nuget.yml
- change/react-native-windows-2020-08-26-14-38-45-master.json
- docs/testing-nuget-packages.md
- vnext/Scripts/Microsoft.ReactNative.Cxx.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.targets
- vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
- vnext/Scripts/Microsoft.ReactNative.Managed.targets
- vnext/Scripts/Microsoft.ReactNative.VersionCheck.targets
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
- vnext/Scripts/PublishNugetPackagesLocally.cmd
- vnext/Scripts/Tfs/Layout-Headers.ps1
This will add a targets file: Microsoft.ReactNative.VersionCheck.targets
to all nuget packages. When evaluated in msbuild it will perform a check
to see if the specified version of the react-native-windows package matches
the current nuget package.
It is challenging with a mix of `PackageReference` and `packages.json` (UWP doesn't support the former yet)
to consistenly figure out the version number from within the nuget package itself.
It would involve walking the parent folder looking for nuspec or npkg files and reverse engineering
the version number from the nupkg filename. In the nuspec case (PackageReference) it is simple as you just need to
parse the nusepc file. In the UWP case, it is complicated since there is no nuspec file by default, on a nupkg file.
The issue with that is that …
> Add verification to ensure nuget and npm version match.

- change/@react-native-windows-cli-2020-08-27-11-37-29-csharpmodulefix.json
- change/react-native-windows-2020-08-27-11-37-29-csharpmodulefix.json
- packages/@react-native-windows/cli/templates/cpp/proj/MyApp.sln
- packages/@react-native-windows/cli/templates/cs/proj/MyApp.sln
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
- packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
- vnext/PropertySheets/CppAppConsumeCSharpModule.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
This change backports #5851 to 0.63
Original PR: 
Right now C++/WinRT apps have a hard time consuming C# WinRT libraries from source. We fixed this in our SampleAppCpp in order to load SampleLibraryCS, but those fixes were not put into the template for the benefit of all apps.
This PR moves the fix into new `CppAppConsumeCSharpModule.(props|targets)` files. Since the fix involves importing a ton of other props/targets, and we don't want to risk breaking existing C++ apps who have no need of consuming C#-based native modules, the changes are behind a new property `ConsumeCSharpModules`.
So if you have a C++/WinRT RNW app (the default) and need to consume C# native module, you can set `<ConsumeCSharpModules>true</ConsumeCSharpModules>` in your app project.
This PR also fixes up the template …
> [0.63] Fixed templates so C++ apps can consume C# native modules

- change/react-native-windows-2020-08-27-14-35-27-fixrefresh.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
The bundle path for non- index bundles wasn't getting passed through correctly.  This was causing fast refresh to not work in the platground app.
I'm going to do some testing on 0.63 to see if this needs backporting.
> Fix fast refresh

- change/react-native-windows-2020-08-27-15-14-10-hardengetui63.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
> [0.63] Harden ReactInstanceWin::NativeUIManager to return null when instance is being torn down

- change/@office-iss-react-native-win32-2020-08-26-03-46-19-fix-touchablewin32-recurse.json
- packages/react-native-win32/src/Libraries/Components/Touchable/TouchableWin32.tsx
* Fix TouchableWin32 Infinite Recursion on Click
Seems this made it into 0.63. onResponderGrant's currentTarget type changed from a react tag to host component. The target is untyped, but we were assuming it was a react tag and calling UIManager.measure on it. Call findNodeHandle when we get the event to convert to react tag.
* Change files
> [0.63] Fix TouchableWin32 Infinite Recursion on Click (#5846)

- packages/playground/windows/playground/HostingPane.xaml.cpp
Even with VS 2017, we can't seem to build Playground in 0.61 due to missing headers. Not sure if we built playground in CI at the time, or had a different environment.
Fix the build, so we can use 0.61 to test reproing issues.
> Fix Building Playground in 0.61 

- change/react-native-windows-2020-08-27-15-10-24-fixrefresh63.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Porting #5860 to 0.63
This fixes fast refresh. -- The source URL wasn't getting past correctly to the instance when the entry file wasn't "index".
> [0.63] Fix fast refresh

- change/react-native-windows-2020-08-31-14-37-14-pr-FixBug.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Sync.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Sync.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Sync.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ZeroArgTaskOfReadOnlyListOfString--Async.lkg
- vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
- vnext/Microsoft.ReactNative.sln
The fix for #5617 introduced a regression. The fix for that issue updated the code
to allow for all derived types of `IReactPromise<T>`. In this exapmle the C# compiler
found an assignability conversion between `IReadOnlyList<string>` and `IReactPromise<T>`.
Which resulted in invalid generated code that doesn't compile.
This fix was in hindsight also not the correct fix since the codegen (jsut like the
reflection based code) passes ReactPromise<T> instance. So the only two valid types
should be `IReactPromise<T>` or `ReactPromise<T>`. Which is what this fix puts in.
Fixes #5870
> Fix 5870: In C# CodeGen, don't check for inheritance, but do explicit type checks

- change/react-native-windows-2020-08-26-19-52-57-dropview.json
- vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
- vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
- vnext/ReactWindowsCore/ShadowNodeRegistry.cpp
- vnext/ReactWindowsCore/ShadowNodeRegistry.h
Office E2E Automation is running into a failure during shutdown caused by rapidly spinning up & shutting down some react-native UI.  What's happening is some Views get created, but the batch to add them to the ui tree never completes.  Usually the removeAllRootView call is sufficient to tear down the UI, but since the shadow nodes finished their batch, they're not parented to the root view.  This iterates through all shadow node left in the registry after removing the root view and explictly calls DropView on them so they can clean up their resources.
> [0.60] DropViews still in ShadowNode registry during UIManager dtor

- change/@office-iss-react-native-win32-2020-09-01-06-04-23-integrate-6-18.json
- change/react-native-windows-2020-09-01-06-04-23-integrate-6-18.json
- packages/E2ETest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/.flowconfig
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- packages/react-native-win32/src/Libraries/Components/SafeAreaView/SafeAreaView.win32.js
- vnext/.flowconfig
- vnext/ReactCopies/RNTester/js/examples/Image/ImageExample.js
- vnext/overrides.json
- vnext/package.json
- vnext/src/Libraries/Components/SafeAreaView/SafeAreaView.windows.js
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/3346ac7f9...b095432e6
This week brings in a change to imageLoad event structure, that we previously brought into our own native code prematurely (whoops). Tracked with #5896
Some stuff that doesn't affect us includes Fabric VM changes, some shared instance refactoring, changes around legacy bytecode bundles we never tried to support, and work to load split bundles for development that we're not trying to follow yet.
facebook/react-native@76fe94e fixes codegen support for $ReadOnly and will likely need to be picked up soon in react-native-tscodegen for flow-types of internal interfaces.
Validated we can launch XAML + NetUI Testsers, that ImageLoad event in RNTester show URLs correctly.
----
- On `Image`, `onLoad` event objects' …
> Integrate 6/18 Nightly RN Build

- .ado/templates/prep-and-pack-nuget.yml
- .ado/windows-vs-pr.yml
The nuget being published for internal use only includes some of the platform/release/debug combinations.
> [0.62] Internal nuget is missing slices

- yarn.lock
Reverts microsoft/react-native-windows#5876
> Revert "Bump beachball from 1.35.3 to 1.35.4"

- change/react-native-windows-2020-09-08-18-00-31-rnwdeps-nochrome.json
- vnext/Scripts/rnw-dependencies.ps1
Now Chrome is optional (we'll use Edge if that's the default) so don't require it in rnw-dependencies.ps1
Also don't exit the PS session upon success, let the user do that so that it doesn't close the window out from under them
> Make Chrome install optional in rnw-dependencies.ps1

- change/react-native-windows-2020-09-08-23-00-18-fix-uwp-websocket-close.json
- vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
The arguments for WebsocketModule were wrong on UWP. Fix that, and start firing closed events like we should. This is enough to get websocket integration tests passing.
This should all eventually be replaced by the new WebSocketResource code once we don't need to touch it as much.
>  Fix Closing a UWP WebSocket

- change/react-native-windows-2020-08-31-17-06-38-apptheme-warnonce.json
- change/react-native-windows-2020-09-08-15-37-07-apptheme.json
- vnext/etc/react-native-windows.api.md
- vnext/src/Libraries/AppTheme/AppTheme.ts
* yellowbox AppTheme
* Change files
* move warnOnce to currentTheme usage
* only show yellowbow if we have a subscriber
* ran yarn api
* Revert "Bump beachball from 1.35.3 to 1.35.4 (#5876)"
This reverts commit 95935e008621778dbcec01363602c19abc060632.
> Deprecate AppTheme by adding yellowbox warning (#5889)

- change/react-native-windows-2020-09-10-23-42-42-wsexecutor-retry.json
- vnext/Shared/Executors/WebSocketJSExecutor.cpp
We will often see "Prepare JS runtime timed out, Executor instance is not connected to a WebSocket endpoint." in cases where we start an app directly after starting Metro, and the bundler is still taking time to initialize.
Increase the retry count.
> Increase WebSocketJSExecutor Retry Count

- change/react-native-windows-2020-09-11-16-46-06-loadofflineafterfailure.json
- vnext/Shared/DevSupportManager.cpp
- vnext/Shared/DevSupportManager.h
- vnext/Shared/IDevSupportManager.h
- vnext/Shared/OInstance.cpp
- vnext/Shared/OInstance.h
Load a RN app with settings that will attempt to get the bundle from a bundle server.  (Ex FastRefresh on), without a bundle server running.  Then open the debug menu and turn off fast refresh, which will cause RN to try to load a local bundle.  Even if the local bundle exists, the rootview will fail to attach to the instance.
This is due to an error state maintained in DevSupportManager.  This error state is set when we fail to load a bundle from a bundle server, but it only reset when we make another attempt to the bundle server.  If we instead use a local bundle, the error state was never reset, and root views would fail to attach.  The change is to move the error state to the instance.
>  Fix issue loading offline bundle after failing to load from packager

- .github/ISSUE_TEMPLATE/community-module-support-request.md
- .github/ISSUE_TEMPLATE/feature-request.md
New github repos are populated with a defualt "enhancement" label.
We have used "Proposal" in our repo.
Aligning to the standard label  will help our unified SLA toolchain.
When this change is in I'll rename the label on the repo and update the bot to match.
The samples repo already uses the standard "bug"/"enhacement"/"question" labels, so no update needed there.
> Update to standard github label: "enhancement"

- change/react-native-windows-2020-09-11-16-19-12-ws-noconcqueue.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
- vnext/Desktop.UnitTests/WebSocketMocks.cpp
- vnext/Desktop.UnitTests/WebSocketMocks.h
- vnext/Desktop/BeastWebSocketResource.cpp
- vnext/Desktop/BeastWebSocketResource.h
- vnext/Shared/IWebSocketResource.h
- vnext/Shared/WinRTWebSocketResource.cpp
- vnext/Shared/WinRTWebSocketResource.h
`WinRTWebSocketResource` already uses an write-enqueuing mechanism via `Mso::DispatchQueue`.
This allows enqueuing the message payload as an argument of the `PerformWrite` coroutine.
The thread-safe container `concurrency::concurrent_queue` `m_writeQueue` is redundant and should be dropped.
- Updates `IWebSocketResource::Send` to use r-value args instead of `const &`.
- Relevant test: `WebSocketIntegrationTest::SendConsecutive`.
> Drop PPL concurrent_queue usage in WinRTWebSocketResource

- change/@react-native-windows-cli-2020-09-11-19-25-55-previewVS.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Fixes #5900 
This adds a fallback to try VS Preview installs if we couldn't find any non-prerelease bits
> Enable using VS previews in run-windows

- change/react-native-windows-2020-09-14-14-45-14-fastrefreshplayground.json
- packages/playground/metro.config.js
- vnext/.flowconfig
- vnext/etc/react-native-windows.api.md
- vnext/overrides.json
- vnext/src/Libraries/Components/DatePicker/DatePickerProps.ts
- vnext/src/RNTester/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
- vnext/src/RNTester/js/examples-win/AsyncStorage/AsyncStorageExampleWindows.tsx
- vnext/src/RNTester/js/examples-win/CustomView/CustomViewExample.windows.tsx
- vnext/src/RNTester/js/examples-win/DatePicker/DatePickerExample.windows.tsx
- vnext/src/RNTester/js/examples-win/FastText/FastTextExample.windows.tsx
- vnext/src/RNTester/js/examples-win/Flyout/FlyoutExample.windows.tsx
- vnext/src/RNTester/js/examples-win/Glyph/GlyphExample.tsx
- vnext/src/RNTester/js/examples-win/Keyboard/KeyboardExample.tsx
- vnext/src/RNTester/js/examples-win/Picker/PickerWindowsExample.tsx
- vnext/src/RNTester/js/examples-win/Popup/PopupExample.windows.tsx
- vnext/src/RNTester/js/examples-win/Text/TextExample.windows.tsx
- vnext/src/RNTester/js/examples-win/TransferProperties/TransferPropertiesExample.tsx
- vnext/src/RNTester/js/examples/TextInput/TextInputExample.windows.js
- vnext/src/RNTester/js/utils/RNTesterList.windows.js
Fixes #5968
The current workflow for testing changes internal to react-native-windows is annoying since you can't edit the files in vnext/src directly and have the instance reload.  Instead you must run `yarn build`, and then likely restart metro / the app since one of the other stops working during the churn of `yarn build`.
This fix adds a custom resolver to the playground app's `metro.config.js`, which will resolve files from `vnext/src` if they exist.  Thus allowing full fast refresh and reload scenarios to work within RNTester for the playground apps.
I didn't do this for E2E tests or Integrations tests, since I feel like those are less likely to be used in this way, but it wouldn't be hard to extract this logic to a new shared package if we want to have it in more places.  (Its only …
> Enable reload while editing of files in vnext/src

- change/react-native-windows-2020-09-14-12-27-48-follyUpdate.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Desktop.UnitTests/EmptyUIManagerModule.cpp
- vnext/Directory.Build.props
- vnext/Folly/Folly.vcxproj
- vnext/Folly/Folly.vcxproj.filters
- vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
- vnext/IntegrationTests/TestInstance.cpp
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
- vnext/Scripts/Tfs/Layout-Headers.ps1
- vnext/Shared/Modules/UIManagerModule.cpp
- vnext/Shared/Utils.cpp
Update to 2020.09.14.00
Fixes #5987 
Includes fixes for a number of issues:
- Parametrized folly version across the repo
- Folly removed `ColdClass`
- Folly changed the signature of the `assertionFailure` function
- Folly added a type `tag` which creates duplicate definitions in files that have a variable with that name and use `using namespace folly`
- VS 16.8 removed intrinsics that were added in 16.3, but the new folly version check only works for 16.8+ which is not out yet. I am fixing that in the folly repo as https://github.com/facebook/folly/pull/1450
- For the time being until we take a new folly drop, I'm resuscitating a Target that will override the file we need in order to fix the intrinsics issue.
- Updated `Layout-Headers.ps1` to use the version from Directory.Build.props …
> Ingest a new version of Folly, add folly changes to prevent VS 16.8 from breaking the build

- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-09-16-16-20-52-deskit-reenablelogging.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
This test was failing consistently and got disabled because the messages coming from the JS runtime for WARN, ERROR and TRACE changed their format from plain string to stack trace:
https://developer.mozilla.org/en-US/docs/Web/API/Console/trace
This change uses string matching for those three log types to remove the false negatives from the affected test.
> Reenable RNTesterIntegrationTests::Logging

- change/react-native-windows-2020-09-16-10-05-25-tm-files.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.Cxx/README.md
- vnext/Microsoft.ReactNative/JsiReader.cpp
- vnext/Microsoft.ReactNative/JsiReader.h
- vnext/Microsoft.ReactNative/JsiWriter.cpp
- vnext/Microsoft.ReactNative/JsiWriter.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/Microsoft.ReactNative/TurboModulesProvider.h
- vnext/Shared/TurboModuleRegistry.h
- Make `REACT_MODULE` usable for macOS (co-op with https://github.com/microsoft/react-native-macos/pull/599 ).
- In this change, comments are added to involved files to tell developers that, they need to take care about macOS from now on.
- In order to do this, react-native-macos needs to use some files from react-native-windows.
- For development convenience, these files are duplicated in react-native-macos.
- After the porting is done, I will make another change to eliminate the duplication. Files will be shared from one single source.
This change also fixes a few issues:
- Workaround XCode compiler issue
- optional<T>::value() is missing (it is added in macOS 10.14, but it is required to support 10.13)
- hash<pair<T, U>> is missing (same reason)
- lambda cannot capture objects that …
> Port REACT_MODULE() from react-native-windows to react-native-macos (2/4)

- change/react-native-windows-2020-09-16-22-48-43-codespacesDeps.json
- vnext/Scripts/rnw-dependencies.ps1
> Fix rnw-dependencies to work in cases where the VS installer is present but no VS 2019 installation is

- change/react-native-windows-2020-09-20-06-37-45-core-js-modules.json
- vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
- vnext/Microsoft.ReactNative/Base/CoreNativeModules.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
- vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.h
We invoke modules provided by the NativeModulesProvider on the JS thread as of RNW 0.63. We still invoke core modules on either the UI thread (ReactUwp style) or an arbitrary background thread via `MakeSerialQueueThread()`. Invoke non-UI thread modules on the JS thread to align behavior with non-core modules.
There's also a bit of renaming here, since the previous differentiation of `messageQueue` and `uiMessageQueue` made it unclear that both point towards the UI thread, and that `messageQueue` wasn't the usual native module queue.
> Run Non-UI-Thread Core Modules on the JS Thread 

- packages/IntegrationTest/windows/integrationtest/ExceptionInfo.h
- packages/IntegrationTest/windows/integrationtest/TestCommandListener.h
- packages/IntegrationTest/windows/integrationtest/TestHostHarness.cpp
- packages/IntegrationTest/windows/integrationtest/TestHostHarness.h
- packages/IntegrationTest/windows/integrationtest/TestTransaction.cpp
- packages/IntegrationTest/windows/integrationtest/TestTransaction.h
- packages/IntegrationTest/windows/integrationtest/integrationtest.vcxproj
- packages/IntegrationTest/windows/integrationtest/integrationtest.vcxproj.filters
RN will sometimes fail to prettify stack information with source map information. In this case, the RedboxHandler never sees a call to update error information. We don't have a great signal of when this fails, so this change alters logic so that a timeout will show exception information if we have an unresolved exception pending.
Validated cases around:
- Tests passing
- Badly behaved tests calling testPassed multiple times not leaking
- Live reload editing tests
- Exceptions where resolution succeeds
- Exceptions where resolution fails
> Ensure Integration Tests Show Exceptions When Source Resolution Fails

- change/react-native-platform-override-2020-09-21-14-32-23-override-locks.json
- packages/react-native-platform-override/src/Cli.ts
Fixes #6055 
Fallout from #5980. `yargs` accepts promise-returning async command handlers, and we were relying on that previously. Revert the addition of the void operator and suppress warnings stemming from incorrect typings.
> Fix react-native-platform-override CLI Locking Issues

- change/react-native-windows-2020-09-20-07-06-28-too-long-timer.json
- vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
Fixes #6031
The UWP implementation of TimingModule took quite a bit from the Desktop TimingModule. One bit is ensuring that timers fire at least 16ms apart to prevent frequent wakeups. This has an impact on desktop, which uses kernel timers, but doesn't do anything useful on UWP, since we wake every frame to evaluate timers.
Remove the logic, since it has the potential to add delay and doesn't seem to serve its intended purpose.
>  Don't Elongate Frame-Based Timers

- packages/IntegrationTest/README.md
- packages/IntegrationTest/TestInstructions.tsx
- packages/IntegrationTest/index.js
- packages/IntegrationTest/index.tsx
- packages/IntegrationTest/package.json
- packages/IntegrationTest/runner/lib/BaseTest.ts
- packages/IntegrationTest/tsconfig.json
- packages/IntegrationTest/windows/integrationtest/MainPage.cpp
- yarn.lock
We were previously loading the iOS IntegrationTestApp component, which is missing our custom tests, doesn't play nice with dark mode, and has some other issues. Add a custom view instead telling people how to run the tests.
Also update the RN version of IntegrationTest which got left behind after a merge.
> Show a custom view when using integration tests

- packages/IntegrationTest/tests/MountComponentTests.tsx
- packages/IntegrationTest/tests/index.ts
Playing with capabilities of Instance driven testing, these tests create new RN components, wait for native to render, ask native to measure them, then fail the test if the component doesn't take screen-space.
> Add integration tests to mount and measure components

- change/react-native-windows-2020-09-18-22-49-20-alertTracking.json
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
> Alert should track its xamlroot's size

- change/react-native-windows-2020-09-21-12-28-47-tm-files.json
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
In the current implementation, when ReactPromise::Resolve is called, the created array is passed to JSI instead of the only element in that array, causing type mismatch.
> Handle ReactPromise return value correctly

- .ado/windows-vs-pr.yml
I've seen a couple of PRs fail this task due to timeouts.  As the repo is getting larger, the sync + lint times are getting longer.
> Increase timeout on JS Checks CI task

- change/react-native-windows-2020-09-23-11-08-48-0.62minorfolly.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Folly/Folly.vcxproj
- vnext/Folly/Folly.vcxproj.filters
- vnext/PropertySheets/ReactDirectories.props
- vnext/ReactUWP/EndPoints/dll/react-native-uwp.arm.def
- vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def
- vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86.def
- vnext/ReactWindowsCore/Utils.cpp
Updating folly for a patch release was more than we should have been changing.  -- And it broke some internal consumption.
This puts folly back to the version it was before, but still adds the one patch file on top which will allow folly to continue to build when VS 16.8 is released.
> [0.62] Revert folly back to 2019.09.30.00 with patch file for compiler fix

- change/react-native-windows-2020-09-21-11-57-18-fix63.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
The updated folly version requires an additional export to be able to use folly outside the dll. -- With the desktop dll and integration tests we use folly outside the core dll, so this function needs to be exported.
Also adds a missing source file needed to build Microsoft.ReactNative.ComponentTests debug|x64.
> [0.63] Fix build

- change/react-native-platform-override-2020-09-23-03-59-58-less-diff.json
- packages/react-native-platform-override/src/GitReactFileRepository.ts
Fixes #5898
Was lucky enough to get into a state where running react-native-platform-overrides would reproduce the issue end-to-end. Git fails to apply a patch stating "error: xxxx: does not match index", referring to files outside of the target file. Files outside of the target show as changed due to Unix file permissions we don't really care about.
This change:
1. Disables core.filemode for the scratch repo since it shouldn't matter
2. Makes it so that we only generate a patch against the target file instead of the whole working tree
Validated we pass end-to-end tests evaluating override validation + upgrading. In my current machine state, we deterministically pass with either change, and deterministically fail without.
> Ignore filemode for react-native-platform-override Scratch Repository

- change/@react-native-windows-cli-2020-09-23-04-17-20-more-jest.json
- change/@rnw-scripts-just-task-2020-09-23-04-17-20-more-jest.json
- change/react-native-windows-codegen-2020-09-23-04-17-20-more-jest.json
- change/react-native-windows-init-2020-09-23-04-17-20-more-jest.json
- package.json
- packages/@react-native-windows/cli/.vscode/launch.json
- packages/@react-native-windows/cli/jest.config.js
- packages/@react-native-windows/cli/package.json
- packages/@rnw-scripts/just-task/just-task.js
- packages/react-native-windows-codegen/.vscode/launch.json
- packages/react-native-windows-codegen/jest.config.js
- packages/react-native-windows-codegen/package.json
- packages/react-native-windows-init/.vscode/launch.json
- packages/react-native-windows-init/jest.config.js
- packages/react-native-windows-init/package.json
This change configures the above packages so that unit tests and end to ends tests can be run and debugged by placing jest tests in either `src/test` or `src/e2etest`. Docs coming soon on the differences between these.
Validated tests are picked up by yarn test, unit tests are automatically run by VS Code, e2etests aren't automatically run but can be debugged in-UI.
This also changes some top-level lerna scripts to allow scripts to be run in non-topological order since they have already been built.
> Zero-Config Tests for CLI, react-native-windows-init, react-native-windows-codegen

- change/@office-iss-react-native-win32-2020-09-23-07-23-03-platform-version.json
- change/react-native-windows-2020-09-23-07-23-03-platform-version.json
- packages/IntegrationTest/tests/PlatformTests.ts
- packages/IntegrationTest/tests/index.ts
- packages/react-native-win32/src/Libraries/Utilities/NativePlatformConstantsWin.js
- packages/react-native-win32/src/Libraries/Utilities/Platform.win32.js
- vnext/Shared/Modules/PlatformConstantsModule.cpp
- vnext/Shared/Modules/PlatformConstantsModule.h
- vnext/src/Libraries/Utilities/NativePlatformConstantsWin.js
- vnext/src/Libraries/Utilities/Platform.windows.js
Fixes #4176
When implementing PlatformConstants I originally took the route of not providing a version, since Windows likes to hide it. Version is officially part of typings though, and it seems some code will be unhappy if its undefined. With this change, we provide UniversalApiContract as a proxy of "what native functionality is available", similar to how Android Platform versions work.
This module is shared between desktop/XAML, which has some special considerations. Namely when running on Windows < 10, we should just return 0 for API contract.
Added integration tests to validate this is working correctly.
> Supply UniversalApiContract for Platform.Version

- change/@react-native-windows-cli-2020-09-23-19-35-29-master.json
- change/react-native-windows-2020-09-23-19-35-29-master.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
- packages/E2ETest/run_wdio.js
- vnext/Scripts/PublishNugetPackagesLocally.cmd
This change adds the -NoProfile option to powershell invocations from build scripts. 
This makes these build scripts more robust as user install extensions will not be loaded automatically giving a minor perf improvement but more importnatly promotes reliable reproducable builds as user installed extensions can't cause the scripts to fail or worse alter the output unexpectedly.
> Add `-NoProfile` option to powershell invocations

- .ado/templates/integration-test-job.yml
- .ado/templates/prepare-env.yml
- .ado/windows-vs-pr.yml
- change/@rnw-scripts-take-screenshot-2020-09-24-01-00-03-integration-test-ci.json
- packages/@rnw-scripts/take-screenshot/.eslintrc.js
- packages/@rnw-scripts/take-screenshot/.gitignore
- packages/@rnw-scripts/take-screenshot/bin.js
- packages/@rnw-scripts/take-screenshot/just-task.js
- packages/@rnw-scripts/take-screenshot/package.json
- packages/@rnw-scripts/take-screenshot/src/takeScreenshot.ts
- packages/@rnw-scripts/take-screenshot/tsconfig.json
- packages/IntegrationTest/runner/lib/IntegrationTestRunner.ts
- packages/IntegrationTest/tests/MountComponentTests.tsx
- packages/IntegrationTest/tests/SampleTests.tsx
- packages/IntegrationTest/windows/integrationtest/App.cpp
- packages/IntegrationTest/windows/integrationtest/TestHostHarness.cpp
- packages/IntegrationTest/windows/integrationtest/TestHostHarness.h
- packages/IntegrationTest/windows/integrationtest/integrationtest.vcxproj
- yarn.lock
This change enables the new tests to run in CI. In this process we found a few issues with both RNW and the framework. For the framework, we fixup an issue where we accidentally run code on the wrong thread (and add thread checks), add some clearer error messages, and add a specific error message if the instance fails to load instead of timing out.
Apart from built-in measures to show signal for when things go wrong, we add a utility to screenshot the CI desktop and run it before and after tests. We also upload crash dumps, and CI built symbols on failure for cases where we see native crashes.
- **Debug vs Release:** We run the debug build of the app to help catch extra assertions and build a binary who should be easier to debug if failures show up. Things are quick enough that there …
> Enable new Integration Test Framework in CI

- change/@react-native-windows-cli-2020-09-22-11-08-10-pascalcasefix.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
When adding the `--projectType lib` to `react-native-windows-init`, I had to handle the case that the naming of new projects is looser for `create-react-native-module` than for `react-native init`.
I added logic to convert the incoming new project name and namespace to pascalCase for all new projects (app or lib). This will break some cases for each that I didn't test before.
I've reverted the logic for new apps (so no net behavior change) and changed the logic for new libs to match `create-react-native-module`, ie, using PascalCase, not camelCase.
> Fix casing rules for new projects names for `react-native-windows-init`

- .ado/VSComponentList.ps1
- .ado/templates/integration-test-job.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2020-09-24-09-10-11-master.json
- vnext/Microsoft.ReactNative/getLayoutProps.ps1
- vnext/Scripts/IntegrationTests.ps1
- vnext/Scripts/Tfs/Install-VSFeatures.ps1
- vnext/Scripts/Tfs/Start-TestServers.ps1
- vnext/Scripts/rnw-dependencies.ps1
Without this flag PowerShell relies on IE to perform downloads. On server images with IE security enhancements this will fail unless they are disabled....
> Add -UseBasicParsing to all powershell Invoke-WebRequest calls to avoid dependency on IE

- .ado/windows-vs-pr.yml
The test was re-enabled due to the wrong assumption that the CI failure’s root cause was the same as the recently fixed Logging test.
The test should stay disabled as per #5059.
Closes #6113.
> Disable AsyncStorage test

- change/react-native-windows-2020-09-25-14-02-31-fix-second-oncreate.json
- vnext/Microsoft.ReactNative/ReactApplication.cpp
When OnCreate is called via OnActivate on an already-running instance,
the Host should not be reloaded so we don't lose the native modules.
> Fix second oncreate

- packages/IntegrationTest/windows/integrationtest/TestHostHarness.cpp
- packages/IntegrationTest/windows/integrationtest/TestHostHarness.h
Fixes #6108
We added thread checks to TestHostHarness which has UI thread affinity. This led to crashes on test timeout instead of a graceful error message, stemmed from our timeout coroutine being resumed on a different thread. Rethread after resuming the coroutine.
> Rethread After Resuming Timeout Coroutine

- change/react-native-windows-2020-09-27-10-42-45-reduce-pch.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Pch/pch.h
We see frequent OOM issues compiling our PCH due to its size. This change removes some of the heavier headers that are included in the PCH to get around XAML codegen issues and instead injects forced header inclusion into the CLCompile items used by XAML codegen. This is quite dirty, but should significantly reduce the increased OOM issues seen since adding these headers.
Goes from 1024MB to 869MB for normal builds
Goes from 1006 to 740MB for WinUI3 builds
> Reduce Microsoft.ReactNative PCH By 155MB-260MB

- .ado/templates/react-native-init.yml
For the integration test job I discovered we get  more reliable builds if we do build-work when daemons are not active. For react-native-init tests, we don't need Verdaccio by the time we're ready to build, so we can kill it to reclaim a bit of memory.
Testing locally, Verdaccio without any packages seems to use ~50MB while idle, which is enough to be worth reclaiming, but less than I had hoped for. Not sure if the number would be different when packages are present.
> Free Up Some Memory for react-native-init CI Jobs

- change/@react-native-windows-cli-2020-09-28-00-39-44-fix-node14.json
- packages/@react-native-windows/cli/package.json
- yarn.lock
run-windows prints out a large number of warnings on Node 14:
```
$ react-native run-windows
√ Auto-linking...
Success: No auto-linking changes necessary. (181ms)
(node:10936) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10936) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:10936) Warning: Accessing …
```
> Fix run-windows Warnings Using Node 14

- change/react-native-windows-2020-09-27-07-13-43-remove-debug-backbutton.json
- vnext/Microsoft.ReactNative/ReactApplication.cpp
When discussed internally, we thought this was confusing. These were carryovers from legacy, with the back button especially odd since we had it before we had a BackHandler. Removing both the debugger only back button, and debugger only frame counter that are automatically added.
> Remove Special UI When Debugger Attached

- change/@office-iss-react-native-win32-2020-09-28-19-25-36-integrate_7_7.json
- change/react-native-windows-2020-09-28-19-25-36-integrate_7_7.json
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- vnext/ReactCopies/RNTester/js/examples/View/ViewExample.js
- vnext/overrides.json
- vnext/package.json
- vnext/src/RNTester/js/examples/View/ViewExample.windows.js
- yarn.lock
Not much happening in this one - only had to reconcile ViewExample.windows.js - upstream added an example of using 'display': none, which created a conflict with the tooltip example below it. Could use a confirmation that the tooltip example should stay, It's annotated with: "// ]TODO(macOS ISS#2323203)" but I don't know how to locate the issue number (we make several references to it across the repo, btw).
- Remove CameraRoll from React Native ([824d3a9770](https://github.com/facebook/react-native/commit/824d3a977057b336d81237ec3cec3a49a9d5e34d) by [@seanyusa](https://github.com/seanyusa))
- `getRectWithAttributedString()` aims to get the rect of the fragment with embedded link, which is necessary when building the `accessibilityElement`. In this function, we first enumerate …
> Integrate RN 7/7 nightly build.

- packages/playground/Samples/rntester.tsx
I've been hitting issues in RNTester where vscode is doing something to files that I have open which causes metro to think those files have changed.  When this happens with most react-native[-windows] files it causes RNTester to crash the instance while doing a FastRefresh of most of the components of react-native.  (This usually shows up as an error `nativeFabricUIManager not defined`)
It turns out most of RN core is not fast refresh safe and assumes changes that reach the boundary of react-native will reach the boundary of the app and trigger full reloads.
RNTestApp exports a single ReactComponent, so react sees it as a Fast Refresh boundary.  If Samples/rntester.tsx imports only RNTestApp, then all edits of any file will bubble up the refresh dependencies into RNTesterApp, which will …
> Fix issues that cause fast refresh issues in playground app

- .ado/windows-vs-pr.yml
Hit a timeout here on one of my jobs, where we seemed to get a machine with slow network conditions (slow yarn install + apply template). We also seem to have regressed native build time with PCH size reduction efforts as well, though this is bringing back in line with the stability vs time tradeoff we had earlier in 0.63.
Increase the timeout of the test job.
> Increase react-native-init CI timeout

- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
After removing some added headers to the PCH we're seeing non-WinUI3 builds are stable again. WinUI3 builds, despite having a smaller PCH, seem to still be effected by OOM issues compiling individual translation units. Investigation is possibly needed as to why these jobs specifically are using more memory. We might be able to just ignore this until we have a new pool.
Converting the WinUI3 jobs to warnings in the meantime. This creates some risk of lost coverage, but in most cases where we would break the WinUI3 build, seeing all jobs fail would be a good indicator, and customers aren't using WinUI3 yet.
> Convert WinUI3 Build Failures to Warnings

- .ado/variables/vs2019.yml
We've been seeing intermittent errors doing a NuGet restore due to the credential provider timing out. Reccomendations online are to increase the default 5s timeout to something longer.
See
- https://developercommunity.visualstudio.com/content/problem/1014284/nuget-restore-fails-due-to-credentialprovidermicro.html
- https://github.com/microsoft/artifacts-credprovider/issues/192
Hopefully fixes #6131
> Increase NuGet Credential Provider Timeout

- .ado/windows-vs-pr.yml
The last change added the flag to the matrix, but we weren't passing from the matrix to a template parameter.
Annoyingly everything in the matrix is exposed as a runtime string, so we cannot simply convert to boolean before passing to the init template, since runtime expressions are limited to conditions and variables. Switching to loosely typed parameters, I saw all sorts of weird behavior going from Matrix to parameter. Separating out the WimUI3 builds into a separate job and keeping strongly typed parameters seems to be a less fragile path.
Validated we get expected results by artificially creating build failures in the pipeline.
> Fix react-native-init Job continueOnBuildError

- change/react-native-platform-override-2020-09-30-17-46-03-extra-git-error-handing.json
- packages/react-native-platform-override/src/GitReactFileRepository.ts
We get confusing errors if we get into a state where we try to patch a file that doesn't exist. Add some checks for some clearer ones.
> Add some extra error handling to GitReactFileRepository

- change/react-native-windows-2020-09-30-09-05-50-syncplaygroundsettings.json
- packages/E2ETest/windows/ReactUWPTestApp/App.xaml.cs
- packages/IntegrationTest/windows/integrationtest/App.cpp
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
- packages/playground/windows/playground/MainPage.cpp
- packages/playground/windows/playground/MainPage.xaml
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/ReactApplication.idl
- vnext/Microsoft.ReactNative/ReactHost/IReactInstance.h
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactHost/React_Win.h
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
- vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/Views/DevMenu.cpp
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
- vnext/Shared/Shared.vcxitems.filters
- vnext/template/cpp-app/src/App.cpp
- vnext/template/cs-app/src/App.xaml.cs
Expose some getters for examining the instance settings from react context.  This is useful if users want to be able to conditionally change behavior when using web debugging.  In particular I'm using in the playground app to change the apps theme to light theme when using web debugger, since that's what the JS code will think the theme is, and helps keep the native / JS UI in alignment.
> Expose getters for some instance settings on reactcontext

- change/react-native-windows-2020-10-02-00-03-14-HEAD.json
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
When calling `ReactNativeHost::ReloadInstance()`, `ReactPackageProvider`s are not reiterated and thus not calling `AddAttributedModules()`. As a consequence, the native modules that were loaded the first time the app was loaded, no longer "exist" after a reload.
> Fix native modules not being re-initialized on reload

- change/react-native-platform-override-2020-10-01-19-45-20-override-diff.json
- packages/react-native-platform-override/README.md
- packages/react-native-platform-override/src/Api.ts
- packages/react-native-platform-override/src/Cli.ts
- packages/react-native-platform-override/src/DiffStrategy.ts
- packages/react-native-platform-override/src/GitReactFileRepository.ts
- packages/react-native-platform-override/src/Override.ts
- packages/react-native-platform-override/src/UpgradeStrategy.ts
- packages/react-native-platform-override/src/e2etest/Api.test.ts
- packages/react-native-platform-override/src/e2etest/DiffStrategy.test.ts
This can be convenient to quickly discover what we changed in certain files, which often aren't consistently annotated where we have forked code.
Will add e2etests before merging.
Example usage:
>  Add command to diff overrides

- change/react-native-windows-2020-10-02-11-24-41-imagecrash.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
> Fix pre-1903 crash when loading certain images

- change/@office-iss-react-native-win32-2020-10-02-12-44-11-integrate-8-19.json
- change/@rnw-scripts-integrate-rn-2020-10-02-12-44-11-integrate-8-19.json
- change/react-native-windows-2020-10-02-12-44-11-integrate-8-19.json
- packages/@rnw-scripts/integrate-rn/src/integrateRN.ts
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/423155127...f8e5423c8
This is two days from current, but the last build before RNTester is moved to its own package, which I want to do by itself. This is the first build where Core started moving dev dependencies out of the react-native package into a "repo-config" metapackage.
The "repo-config" package was designed in such a way where syncing it doesn't make sense in our repo, and after that change, some devDependencies started moving back to the RN package. It does create unexpected errors for our integration script which expects the RN package to have dev dependencies, but instead we just do nothing if there is anything missing for now.
> Integrate 8/19 Nightly RN Build

- change/react-native-windows-2020-10-02-12-58-35-remove-other-timingmodule-assert.json
- vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
TimingModule methods are dispatched to the UI thread. The instance/Module may be gone by the time its methods are processed in the UI queue. We removed an assertion that an instance is available on render callback, but there is a second assertion on method call as well. Remove the assertion.
> Remove the other TimingModule Assertion

- packages/playground/windows/playground/MainPage.cpp
> Fix resetting of playground comboboxes upon load

- package.json
- yarn.lock
The version of Hermes used by RN 0.63 up to recent RN nightlies is vulerable to CVE-2020-1912, which shows up in component governance alerts. We don't actually use the npm package binary in any way, so this change pins a newer version of Hermes until we integrate the 9/17 Nightly RN build that will be part of RN 0.64.
> Force hermes-engine 0.70

- change/react-native-windows-2020-10-06-11-02-39-master.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
I noticed when testing PR #6184 that the unittest project had to be updated too. I thought I pushed new changes to the PR but perhaps I didn't or mistyped the branch name.
This change addressed that.
> Update System.Private.Uri version for C# codegen for unittest

- change/@office-iss-react-native-win32-2020-10-05-13-03-34-noinstallrex.json
- packages/react-native-win32/package.json
- yarn.lock
The rex testapp for win32 isn't needed except for people manually testing the office platform.  Removing it from the yarn workspace, and rely on npm to install it as needed when run manually.
> Most people do not need rex, do not install it for everyone using the RNW repo

- change/react-native-windows-2020-10-02-23-12-32-HEAD.json
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
When calling `ReactNativeHost::ReloadInstance()`, `ReactPackageProvider`s are not reiterated and thus not calling
`AddAttributedModules()`. As a consequence, the native modules that were loaded the first time the app was loaded, no longer "exist" after a reload.
> [0.63] Fix native modules not being re-initialized on reload (#6159)

- .ado/windows-vs-pr.yml
- .unbroken_exclusions
- change/react-native-windows-2020-10-07-16-06-16-master.json
- vnext/.gitignore
- vnext/LICENSE
- vnext/just-task.js
- vnext/package.json
The most common failure we have in this test are:
a) Missing Change File
b) Linting errors
This PR moves the link checks to the end of this job to ensure we get a failure signal as fast as possible.
> Change order of JavaScript tests to get failures earlier

- change/react-native-windows-2020-10-09-13-04-00-folly6212.json
- vnext/Scripts/Tfs/Layout-Headers.ps1
* Updated the Layout-Headers.ps1 script to trim the folly version string
it extracts from Directory.Build.props
Closes #6212
> Fixed missing folly headers on publish

- change/react-native-windows-2020-10-12-14-52-23-cpp-csharp.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
- vnext/PropertySheets/CppAppConsumeCSharpModule.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
This change backports (part of) #5851 to 0.62.
It does not update the apps in the repo, only adds the props/targets to unblock customers with C# modules who need to support 62.
Original PR:
Right now C++/WinRT apps have a hard time consuming C# WinRT libraries from source. We fixed this in our SampleAppCpp in order to load SampleLibraryCS, but those fixes were not put into the template for the benefit of all apps.
This PR moves the fix into new CppAppConsumeCSharpModule.(props|targets) files. Since the fix involves importing a ton of other props/targets, and we don't want to risk breaking existing C++ apps who have no need of consuming C#-based native modules, the changes are behind a new property ConsumeCSharpModules.
So if you have a C++/WinRT RNW app (the default) and need to consume …
> [0.62] Fixed templates so C++ apps can consume C# native modules #5851

- change/@react-native-windows-cli-2020-10-12-16-26-22-master.json
- packages/@react-native-windows/cli/src/config/projectConfig.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
There were 2 problems:
###autolink
Auto-Linking was picking up the wrong path, when a custom `react-native.config.js` configures the windows folder with the users code in a different location.
This PR ensures that the custom sourcePath property is copied to the final configuration so it works.
###app deployment
App deployment hardcoded in a bunch of places to optoins.root\windows. This change updates the code to pass the windowsRoot which is where the native app code lives.
> Fix project config and package deploy to support the windows code in a different location

- packages/react-native-win32-tester/src/js/examples/PlatformColor/PlatformColorExample.win32.js
PlatformColor test page doesn't include win32 platform or win32 color options
> Add win32 as a valid platform to platformcolorexample.win32

- change/react-native-windows-2020-10-19-13-20-12-fixSwitchEvents.json
- vnext/Microsoft.ReactNative/Views/SwitchViewManager.cpp
- vnext/Microsoft.ReactNative/Views/SwitchViewManager.h
The switch was generating spurious events as a result of setValue command being called by the JS after the first switch event and before the props had been changed by the app. This resulted in the switch not changing state
> Fix switch events

- change/@office-iss-react-native-win32-2020-10-19-05-08-08-no-issue-schema.json
- change/react-native-platform-override-2020-10-19-05-08-08-no-issue-schema.json
- change/react-native-windows-2020-10-19-05-08-08-no-issue-schema.json
- packages/@react-native-windows/tester/overrides.json
- packages/react-native-platform-override/src/Override.ts
- packages/react-native-platform-override/src/OverrideFactory.ts
- packages/react-native-platform-override/src/Serialized.ts
- packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/overrides.json
- packages/react-native-platform-override/src/scripts/generateManifest.ts
- packages/react-native-platform-override/src/test/Manifest.test.ts
- packages/react-native-platform-override/src/test/Serialized.test.ts
- packages/react-native-win32-tester/overrides.json
- packages/react-native-win32/overrides.json
- vnext/overrides.json
Most types of overrides require an issue number. This is done on the schema level, and is done inconsistently per-type, where some allow no issues or LEGACY_FIXME, where others allow none. This was done to add barriers to forking, but ends up being a bit too broad/heavy-handed, and the differences between requirements of override types is confusing.
This changes makes the schema uniform, dropping the special LEGACY_FIXME issue and universally allowing missing issues.
To guide engineers to the right path, we still do require issues depending on types in the override prompt, but these can be altered manually.
>  Drop Issue Requirement from Override Manifest Schema Validation

- package.json
- yarn.lock
This change just adds resolutions to pass component governance.
Not sure if this will actually work.
Closes #6266
Closes #6267
> Add yargs-parser and node-fetch resolutions to pass component governance

- change/react-native-windows-2020-10-20-09-06-20-fix-redbox-logbox-actualsize.json
- vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
ActualSize was added to UIElement in 19H1, but is being used in native code for Logbox/legacy redbox. This will also cause integration tests to crash on redbox, since they're running on debug build on Windows Server 2019.
Replace usages with ActualHeight/ActualWidth.
Initial thoughts are to not backport this, since it's dev only and has existed for a couple of versions.
>  Fix Crash when Logbox shown on pre-19H1

- change/react-native-windows-2020-10-20-09-59-36-FixDefaultJSQueue.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Surprisingly, we had a bug that all NativeModules 2.0 use UI queue to run their code. We call NativeModules 2.0 the native modules that run on top of the ABI safe API in the ReactNative for Windows.
In this change we switch them to use the JS queue as it supposed to be.
> Make native modules to use JS queue

- change/react-native-windows-2020-10-20-16-28-00-FixEmitJSEvent.json
- packages/microsoft-reactnative-sampleapps/index.windows.js
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
This change is to fix the bug in ReactContext::EmitJSEvent where the event arguments were unnecessary wrapped into an array.
As a part of this change we adding functions to the sample project to verify that ReactContext::EmitJSEvent works for C++ and C# code.
The bug was only in the C++ version of ReactContext::EmitJSEvent. The C# version is working correctly.
> Fix ReactContext::EmitJSEvent arg passing

- change/react-native-windows-2020-10-20-17-25-59-dimsfix.json
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
Fixes #6269
This regression crept in when DeviceInfoModule was migrated to the new module system.  Super simple bug:  when the dimensions change, we update everything but forget to fire the change event.  This fix adds the missing line of code.
You can verify the scenario in the already existing Dimensions RNTester page.  We'll want to eventually add an automated test for this, but that can be done later.
Note that this fix also requires https://github.com/microsoft/react-native-windows/pull/6285.  Any app with a Dimensions listener will throw a redbox when the window is resized without that fix.  Will wait for that fix before submitting this.
> Bugfix:  Dimensions never fires change events

- change/react-native-windows-2020-10-08-15-56-54-enable_presaability_onFocus.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- packages/playground/Samples/view.tsx
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/overrides.json
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
- vnext/src/Libraries/Components/TextInput/TextInput.windows.js
- vnext/src/Libraries/Components/TextInput/TextInputState.windows.js
- vnext/src/Libraries/Components/TextInput/WindowsTextInputNativeCommands.windows.js
- vnext/src/Libraries/Components/TextInput/WindowsTextInputNativeComponent.js
Closes #5589 
Enable onFocus/onBlur callbacks on the Pressable component.
Allow calling .focus()/.blur() to move focus to or away from Pressable elements.
Forking Pressable.js until I upstream this change to RN.
Added PressableFocusCallbacks() to the list of examples for Pressable. You can click on a button to move focus to a Pressable, and see log being printed in console in the onFocus() callback; tabbing away from it results in onBlur() getting invoked - also visible in browser console.
You may notice that all invocations of .focus()/.blur() go through TextInputState.js, which stores a ComponentRef to the currently focused element. This is because there's a hard-coded call to it in **react-native-renderer/src/ReactFabricHostConfig.js**
(See: …
> Implement focus/blur functionality on Pressable.

- change/react-native-windows-2020-10-23-00-31-23-taborder-fix.json
- vnext/Microsoft.ReactNative/Views/PickerViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Fixes #6181 
This issue was discovered by Facebook.  With a simple setup like this:
```
function ScrollViewBugExample() {
return (
<View>
<Button title="Button 1" />
<ScrollView>
<Button title="Button 2" />
</ScrollView>
<Button title="Button 3" />
</View>
);
}
```
the tab order goes in the reverse order from what you would expect (Button 3 => Button 2 => Button 1, oops!  should be Button 1 => Button 2 => Button 3)
The issue here was caused by a simple bug in RNW code - we're setting the TabIndex on ScrollViewer to 0.  This is not the default tab index in XAML, which is max int.  Thus when XAML's FocusManager goes through the search algorithm, it compares max int to 0 and this throws off the algorithm.
The fix is simple:  Don't bother setting a TabIndex on ScrollViewer.  It is ALREADY …
> Fix default tab order for ScrollView + a couple other controls

- change/react-native-windows-2020-10-23-12-24-25-exportcreateUIMan.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
Currently only the deprecated `createUIManagerModule` method is exported, so we cannot switch over to using the newer one in Office.
> [0.62] [Win32] Export createUIManagerModule that takes a uiQueue

- change/react-native-windows-2020-10-23-17-54-31-rnwDepsCheckDontElevate.json
- vnext/Scripts/rnw-dependencies.ps1
> Don't require elevating when only checking RNW dependencies

- change/react-native-windows-2020-10-21-14-32-36-highlight_feature.json
- packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
- vnext/Microsoft.ReactNative/Utils/ValueUtils.h
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
- vnext/src/Libraries/Text/Text.windows.js
RNW represents nested \<Text> components as a tree structure of XAML Run and Span elements.. The TextBlock (TB) doesn't have a backgroundColor prop that RN does, but portions of its contents can be highlighted using its Highlighters() element collection, each consisting of a color and a set of text ranges. 
The TextBlock tree gets constructed in a bottom-up fashion by appending Run elements and nested Spans, and the offsets of the different elements from the TextBlock's beginning are not known in advance; therefore information about whether a given Span (i.e. nested \<Text>) is highlighted needs to be cached and propagated up the tree. When all Run and Span elements are created, they get appended to the TB from left to right. Whenever a Run is added, we can keep track of its end position; …
> Implement backgroundColor prop for Text.

- change/@office-iss-react-native-win32-2020-10-27-13-09-58-viewintexterrors.json
- change/react-native-windows-2020-10-27-13-09-58-viewintexterrors.json
- packages/@react-native-windows/tester/src/js/components/RNTesterExampleList.windows.js
- packages/react-native-win32/src/Libraries/Components/View/View.win32.js
- packages/react-native-win32/src/Libraries/Image/Image.win32.js
- vnext/.gitignore
- vnext/overrides.json
- vnext/src/Libraries/Components/View/View.windows.js
- vnext/src/Libraries/Image/Image.windows.js
Fixes #4927
Currently we display a yellowbox from native when a view is put inside a text component.  But it doesn't provide any context to the user of where in their UI the issue is.
This change adds code on the JS side which will provide a redbox with the complete component tree of where the error is occurring.
> Better error handling of Views inside Text components

- .ado/templates/macos-tests-job.yml
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/Consts.ts
- packages/E2ETest/.eslintrc.js
- packages/E2ETest/run_wdio.js
- packages/E2ETest/wdio.conf.js
- packages/E2ETest/wdio/pages/BasePage.ts
- packages/E2ETest/wdio/pages/HomePage.ts
- packages/E2ETest/wdio/test/DirectManipulation.spec.ts
- packages/E2ETest/wdio/test/Image.spec.ts
- packages/E2ETest/wdio/test/TransformTest.spec.ts
- packages/E2ETest/wdio/test/VisitAllPages.spec.ts
- packages/E2ETest/wdio/test/controlStyle.spec.ts
- packages/E2ETest/wdio/test/login.spec.ts
- packages/E2ETest/wdio/test/testInput.spec.ts
An upcoming RNTester change removes the back button. E2ETest relies on this as a signal that a test page has been loaded, so we need to replace it with something else. In this case we use the absence of the RNTesterList search box. Note that a search box may still be present, but will have a different test id than the RNTesterList one.
Now that we have visual separation between component examples and API examples, we update HomePage to let it know the difference instead of keeping that logic just in the VisitAllPages test. Doing this led to some discoveries that led to quite a bit of house-cleaning.
Verified everything runs locally, and that artificially created tree dump failures show correctly.
> Allow E2ETest to Work Without Back Button (And lots of cleanup)

- change/react-native-platform-override-2020-10-27-13-13-55-better-monorepo-validation.json
- packages/react-native-platform-override/src/Cli.ts
If multiple packages have override validation errors, we currently print errors of each type per-package. This change makes it so that we instead group by type, which cleans up the output.
Validated by artistically creating validation errors in multiple packages, since we don't have tests for the CLI interface layer.
> Better Override Validation Messages When Errors Exist in Multiple Packages

- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/Consts.ts
- packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextBackgroundColorTestPage.tsx
- packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
- packages/E2ETest/wdio/pages/TextBackgroundColorTestPage.ts
- packages/E2ETest/wdio/test/TextColorBackground.spec.ts
- packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/TextColorBackground.json
- packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
Follow-up PR to #6300 adding a tree dump test, building on the extensions to the xamltreedump library.
> Add treedump test for TextBlock.TextHighlighters

- change/react-native-windows-2020-10-29-09-49-44-template-inline-requires.json
- vnext/template/metro.config.js
We have a custom Metro config that replaces the default used by core, in order to work around MSBuild related issues, The MSBuild related issues will be going away eventually so we don't need to do this.
RN 0.64 defaults inlineRequires to true, but our template Metro config hasn't been updated to do this. Update our template.
> Update Template Metro Config to Enable Inline Requires By Default

- change/@react-native-windows-cli-2020-10-29-15-59-32-fix-inquirer.json
- packages/@react-native-windows/cli/src/generator-common/index.ts
Fixes #6380
During project initialization, we prompt to ask users whether to replace certain files, like the default metro config. We used to have a custom prompt to do this, but replaced it with Inquirer in 0.63. A typo + lack of type safety from inquirer means that  regardless of user response, we treat `shouldReplace` as undefined which is coerced to false.
Validated the stock metro config is correctly replaced after the change.
> Fix Generator Failing to Overwrite Template Files

- change/react-native-windows-2020-10-29-12-55-29-uimaneager.json
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
If the native side finishes loading and attempts to register the root view before the UIManager is initialized then in ReactInstanceWin::AttachMeasuredRootView we'd end up notifying JS that the rootViewTag is -1, which would end crash later when UI attempts to add UI to node -1.
Fixes #6368
Filed #6377 to track how to do needsEagerInit more generically.
> Eagerly initialize UIManager

- change/@react-native-windows-cli-2020-10-29-15-59-32-fix-inquirer.json
- packages/@react-native-windows/cli/src/generator-common/index.ts
* Fix Generator Failing to Overwrite Template Files
Fixes #6380
During project initialization, we prompt to ask users whether to replace certain files, like the default metro config. We used to have a custom prompt to do this, but replaced it with Inquirer in 0.63. A typo + lack of type safety from inquirer means that we  regardless of user response, we treat `shouldReplace` as undefined which is coerced to false.
Validated the stock metro config is correctly replaced after the change.
* Change files
> [0.63] Fix Generator Failing to Overwrite Template Files (#6382)

- change/react-native-windows-2020-10-30-10-59-47-master.json
- vnext/Scripts/OfficeReact.Win32.nuspec
#6268 changed the location of the header file to be included in the win32 nuget package. We seem to lack coverage in PR validation. This fixes the nuspec file to point to the new path.
> Fix desktop publish

- change/react-native-windows-2020-11-02-10-56-27-PR-ReactNativeHostFromContext.json
- packages/microsoft-reactnative-sampleapps/index.windows.js
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
- vnext/Microsoft.ReactNative/Modules/DevSettingsModule.cpp
- vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.cpp
- vnext/Microsoft.ReactNative/ReactNativeHost.h
- vnext/Microsoft.ReactNative/ReactNativeHost.idl
For CodePush native module we need ability to reload React instance after the new bundle is loaded.
It means that a native module must have access to the ReactNativeHost.
Unfortunately, we cannot expose it from the IReactContext because it created a circular import dependency among IDL files.
In this PR we do the next best thing: add static `ReactNativeHost::FromContext` to acquire `ReactNativeHost` from the `IReactContext`.
Internally we store a weak pointer to `ReactNativeHost` inside of the Context Properties. When we retrieve the `ReactNativeHost`, we try to resolve the weak pointer. It may happen that `ReactNativeHost::FromContext` returns null if the `ReactNativeHost` is already deleted.
The Sample project changed to show how to use the new method to reload React instance.
> Add ReactNativeHost::FromContext method

- .ado/templates/prep-and-pack-nuget.yml
- change/react-native-windows-2020-10-30-11-37-43-master.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
- vnext/Scripts/PublishNugetPackagesLocally.cmd
- vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
NuGet defines a layout semantic for UWP projects. CSharp projects use the directory
convention which is to copy all dll's and pdb recursivley under the 'native' folder
This means that if we have native\release\foo.dll and native\debug\foo.dll
UWP will try to copy both versions of foo.dll to the output app and will
collide. Cpp projects don't have this problem because they don't support Nuget
properly, and require the producing nuget package to ship a targets file
that overrides the behavior manually where we accounted for.
This change drops including the debug bits in Microsoft.ReactNative.
Just like the Microsoft.ReactNative.Managed package if a debug slice is build for a
platform without a release versions, that debug version will be included.
Closing #6375
> Update Microsoft.ReactNative Nuget Package to support layout convention

- change/react-native-windows-31052f2c-0c3c-42b8-9716-47c62e1560ff.json
- vnext/Shared/Modules/NetworkingModule.cpp
fixes #6407
the same as https://github.com/microsoft/react-native-windows/pull/6414 but against the main branch
> [main] Set `Content-Length` on the content object and not on the request.

- .ado/templates/prep-and-pack-nuget.yml
- change/react-native-windows-3211a5cf-8ed3-47dd-bfa1-8c52882632ea.json
- vnext/Scripts/Microsoft.ReactNative.nuspec
- vnext/Scripts/Microsoft.ReactNative.targets
- vnext/Scripts/PublishNugetPackagesLocally.cmd
- vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
NuGet defines a layout semantic for UWP projects. CSharp projects use the directory
convention which is to copy all dll's and pdb recursivley under the 'native' folder
This means that if we have native\release\foo.dll and native\debug\foo.dll
UWP will try to copy both versions of foo.dll to the output app and will
collide. Cpp projects don't have this problem because they don't support Nuget
properly, and require the producing nuget package to ship a targets file
that overrides the behavior manually where we accounted for.
This change drops including the debug bits in Microsoft.ReactNative.
Just like the Microsoft.ReactNative.Managed package if a debug slice is build for a
platform without a release versions, that debug version will be included.
> [0.63] Update Microsoft.ReactNative Nuget Package to support layout convention (#6381)

- change/@react-native-windows-cli-7e62c157-c852-4a1e-b408-b1215790f7c6.json
- packages/@react-native-windows/cli/powershell/WindowsStoreAppUtils.ps1
When WindowsTargetPlatformMinVersion is set to >10.0.17134.0, a .msix is output instead of .appx. This causes CheckIfNeedInstallCertificate() to fail since it only looks for .msix.
> fix(cli): Also look for .msix* extensions in CheckIfNeedInstallCertificate

- change/@react-native-windows-telemetry-8939f9d3-227e-4c1d-a8ff-77767de329e4.json
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
- yarn.lock
- sanitize non-project root paths
- map things like appdata/localappdata back to "[appdata]" etc.
follow up to #6403
> Improve path telemetry sanitization

- change/react-native-windows-2020-08-03-16-13-47-tooltip.json
- vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
* Use string object for tooltips instead of textblocks since that breaks wordwrap etc
* Change files
* box hstring
> [0.62] Fix word-wrapping behavior of tooltips (#5626)

- change/@react-native-windows-cli-59008ac8-ff8a-45af-a889-1ef869803be6.json
- change/react-native-windows-0e3c72b2-c464-4a57-a02c-e8c1f3ee5830.json
- change/react-native-windows-init-d324dc3a-e64d-44b2-9227-76b94e4a1bbd.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/index.ts
- packages/react-native-windows-init/src/Cli.ts
- vnext/template/metro.devMode.config.js
Fixes #5605
`--useDevMode` operates using `yarn link`, which symlinks the `react-native-windows` directory in node_modules. This confuses Metro, which doesn't understand symlinks, and doesn't know how to find modules hoisted above `react-native-windows`.
Copy a custom metro config when using `--useDevMode` so we can bundle in the symlinked environment.
Validated creating a new app, validating we have the devmode config, then launching the app.
Note that we still run into cross-package asset issues, where we're missing an image from the new app screen. This isn't super needed for the new app screen, but maybe something we should fix as well.
> Fix Bundling With "react-native-windows-init --useDevMode" 

- change/react-native-windows-2020-11-03-18-19-29-fix-content-length.json
- vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp
fixes #6407
I made it similarly to `Content-Encoding`. I'm open for suggestions if something else needs to be adjusted here.
> [0.63] Set Content-Length on the content object and not on the request itself.

- change/react-native-windows-9310cb02-467c-4f9a-9aae-0d74ea7dc001.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
If placed inside a ScrollView, TextInput requires the height prop to be provided in order to appear on the screen - fixing this by forcing a XAML layout run before Yoga layout happens; verified in Playground\TextInput
Detailed explanation in #2642 
Based on fix from PR react-native-windows/pull/2859.
Fixes  #5686 Related #5437
> Fix TextInput not rendering sometimes

- change/@react-native-windows-cli-2020-11-10-10-54-55-CItel-0.63.json
- change/@react-native-windows-telemetry-2020-11-10-10-54-55-CItel-0.63.json
- packages/@react-native-windows/cli/src/index.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
- packages/react-native-windows-init/src/Cli.ts
We currently exclude AzureDevOps/GH actions, this change extends that exemption to CircleCI and Travis, and any other system that sets `CI=true`
Fixes #6477
> [0.63] Disable telemetry in other CI systems

- .ado/templates/e2e-test-job.yml
WinAppDriver 1.2 is being deployed across the MS hosted pool. appium-windows-driver is tied to a specific version of WinAppDriver, failing if a hash is mismatched. The latest current available package supports 1.2rc.
Uninstall WinAppDriver 1.2.1 if installed and instead install WinAppDriver 1.1 for now
See #6393 for details
> Replace WinAppDriver 1.2.1 with WinAppDriver 1.1

- .ado/publish.yml
- .ado/templates/prepare-env.yml
- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-4dacc674-7590-486d-8603-e83505ab6301.json
- change/@react-native-windows-cli-c270659d-5e61-4b4f-9fe6-c95c2b7d5ee4.json
- change/nuget-exe-531f8eeb-8a3a-4c50-b2e3-b4847e21de93.json
- change/nuget-exe-807cc9de-9a9e-4b72-82d5-2eaed832859c.json
- lage.config.js
- packages/@react-native-windows/cli/package.json
- packages/nuget-exe/just-task.js
- packages/nuget-exe/package.json
This PR updates the nuget version used to build this repo during CI, as well as the nuget version customers use when they build their projects via the react-native-cli.
> Update to nuget 5.8.0 as earlier versions have compatibility bugs with VS 16.8 and later

- change/react-native-windows-061ca216-e9e4-40f7-ac44-e00e60862e93.json
- vnext/Microsoft.ReactNative/DocString.h
- vnext/Microsoft.ReactNative/DocString.idl
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
This change adds a custom WinRT attribute so that types, methods, structs, properties, etc. can be documented inline with the IDL definition. 
The string content used in the IDLs are picked up by a separate tool (winmd2markdown) and is only added to the Microsoft.ReactNative.winmd file in Debug builds.
To add a description to a WinRT method/type/member, in the corresponding IDL you can now do:
```diff
+#include "DocString.h"
... // other stuff
+ DOC_STRING("This is an enum")
enum JSIEngine {
Chakra = 0,
Hermes = 1,
V8 = 2
};
```
similarly
```diff
+#include "DocString.h"
... // other stuff
[default_interface]
[webhosthidden]
+ DOC_STRING("foo bar")
runtimeclass ReactRootView : XAML_NAMESPACE.Controls.Grid {
```
> Enable documenting WinRT API inline

- change/@react-native-windows-cli-edfb8099-c06e-41ab-a9c1-7c2385019025.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
When the user encounters an error, if running with `--verbose` we can print out the sessionId so that if they decide to file a bug, they can provide the session id so that we can look up the telemetry to help us investigate and hopefully unblock them more easily.
> Print out sessionId if verbose

- Directory.Build.targets
- change/react-native-windows-b8dbda54-a2f3-42a1-b0bd-9c56a21014e1.json
- vnext/Directory.Build.props
- vnext/Directory.Build.targets
- vnext/Microsoft.ReactNative.Managed/JSValue.cs
This PR adds extra targets to check if `yarn install` has run before building msbuild.
This step is incremental and will run a dummy `yarn install` command with offline and an empty cache to check if something needs updating...
The msbuild step is incremental, the first run takes ~2.8 seconds:
An example incremental step takes ~1.5 seconds:
This time is all because I added tracking for package.json files and the glob takes a long time... MsBuild has a [workitem](https://github.com/dotnet/msbuild/issues/2000) to make globbing faster.
> Add MsBuild targets to check that developers have run yarn install before building  

- .ado/templates/e2e-test-job.yml
WinAppDriver 1.2 is being deployed across the MS hosted pool. appium-windows-driver is tied to a specific version of WinAppDriver, failing if a hash is mismatched. The latest current available package supports 1.2rc.
Uninstall WinAppDriver 1.2.1 if installed and instead install WinAppDriver 1.1 for now
See #6393 for details
> [0.63] Replace WinAppDriver 1.2.1 with WinAppDriver 1.1 (#6502)

- .ado/templates/e2e-test-job.yml
WinAppDriver 1.2 is being deployed across the MS hosted pool. appium-windows-driver is tied to a specific version of WinAppDriver, failing if a hash is mismatched. The latest current available package supports 1.2rc.
Uninstall WinAppDriver 1.2.1 if installed and instead install WinAppDriver 1.1 for now
See #6393 for details
> [0.62] Replace WinAppDriver 1.2.1 with WinAppDriver 1.1 (#6502)

- change/@react-native-windows-cli-2020-09-28-00-39-44-fix-node14.json
- packages/@react-native-windows/cli/package.json
- yarn.lock
* Fix run-windows Warnings Using Node 14
run-windows prints out a large number of warnings on Node 14:
```
$ react-native run-windows
√ Auto-linking...
Success: No auto-linking changes necessary. (181ms)
(node:10936) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10936) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:10936) Warning: Accessing non-existent property 'dirs' of module exports inside circular …
```
> [0.63] Fix run-windows Warnings Using Node 14 (#6116)

- change/@react-native-windows-telemetry-a022baa7-25bb-4626-9461-00b50b4d62f8.json
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
- paths with forward slashes (which might be present in some exceptions thrown inside nodejs) should still be anonymized
- extends path anonymization to file shares (e.g. `\\server\share\dir`)
- remove cpu/thread numbers from error messages since that's not useful and makes clustering harder
- parse out error codes when possible
> Improvements to telemetry logic

- change/@react-native-windows-cli-63a88995-cd00-4c15-8f81-7366247a68ad.json
- packages/@react-native-windows/cli/src/e2etest/projects/BarPackage/package.json
- packages/@react-native-windows/cli/src/e2etest/projects/FooPackage/package.json
- packages/@react-native-windows/cli/src/e2etest/runWindows.test.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
This lets us pivot on projects, helping us to answer questions like "how many project using RNW exist" or "How long does it take for projects to adopt a new version".
The project name could contain confidential information/PII, so we put it through a cryptographically strong irreversible hash to prevent the possibility leaking it.
Validated through automated tests + CI doing run-windows in init tests.
>  Collect anonymized project name

- change/react-native-windows-af66f506-7c5a-4ccb-ba10-2ba824bb8074.json
- vnext/Microsoft.ReactNative/DocString.h
- vnext/Microsoft.ReactNative/DocString.idl
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/IReactPackageProvider.idl
- vnext/Microsoft.ReactNative/IReactPropertyBag.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
- vnext/Microsoft.ReactNative/ReactApplication.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/ReactNativeHost.idl
- vnext/Microsoft.ReactNative/RedBoxHandler.idl
- vnext/Microsoft.ReactNative/XamlUIService.idl
Builds upon #6506 
Fixes #6509
Moves the documentation text from samples onto the winmd so there is one source of truth and it makes it clear what APIs are still undocumented.
Added another attribute to signify default value for a property.
Also added some docs for things we had // style comments, now those will show up in the winmd and be interpreted as part of the native API generation pass.
> Embed docs in winmd

- change/@rnw-scripts-promote-release-9a8b047d-00a8-4a96-875d-31968fd0a4f6.json
- packages/@rnw-scripts/promote-release/src/promoteRelease.ts
Fixes #5616
There are packages like react-native-windows-init that we publish only from our master branch. Publishing outside of our master branch would break both PR and publish pipelines in our master branch, along with creating confusion. The lack of guardrails for this is an especially sharp edge, as bumps to the react-native-windows version will now bump react-native-windows-init, as the latter takes a devDependency on the former to use its typings.
This change prevents the wrong thing from happening by marking most packages as private in stable branches.
Validated by locally running the script and inspecting results.
> Mark packages published from master as private when cutting branch

- change/react-native-windows-dea2927a-a5e6-4784-a71a-14e423a40d2e.json
- vnext/Microsoft.ReactNative.Cxx/UI.Xaml.Controls.h
- vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
When I ported RNW to WinUI3 I wrongly changed a cast from IControl7 to Control. CornerRadius only works on RS5 so trying to access the property on RS4 will crash the app. 
Fixes #6544
> Degrade CornerRadius in RS4

- change/react-native-windows-f97e6ea8-db5f-4659-9224-a77e2c3fadd4.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
While implementing #6220 I made a typo and missed an outer if-statement, which results in both focus and blur commands invoking "focus".
> fix ViewViewManager command typo

- change/react-native-windows-a6aebc81-adec-4938-a41a-28b6ce245133.json
- vnext/src/index.windows.js
You will be warned when using Picker, but not PickerWIndows, or will be warned when using DatePickerIOS, but not DatePicker. Point folks towards the community module before these are removed, if they're using the Windows variant directly.
These are not yet removed as of 0.64, so we should have at least a release of warning.
> Add Yellowbox warnings for Windows Variants of Lean Core Components

- .ado/windows-vs-pr.yml
NuGet generation in CI is dependent on a single job creating and uploading shared headers for all NuGet packages. This job requires doing the build, but seemingly cannot be done by multiple machines, as they would upload overlapping artifacts.
This is currently done in PR by one of the UWP build steps. Ensure these are completed before packing the desktop NuGet package to avoid the race condition.
We should consider splitting out desktop and UWP NuGet generation artifacts in the future to avoid tying them together in this way. I spent a bit of time looking for cleaner fixes, but there likely isn't anything too much better we can do without structural changes.
> Wait until UWP Jobs are Finished Before Desktop Packing

- change/react-native-windows-6336eb07-86e6-461a-a24c-79311b382c98.json
- vnext/Shared/Executors/WebSocketJSExecutor.cpp
`WebSocketJSExecutor::ConnectAsync` does not handle errors arising from `m_socket.ConnectAsync(uri)`.
This change uses the no-exception coroutine adapter to handle errors using the `ErrorCode` function from `IAsyncAction`.
Closes #6569.
> Use lessthrow_await_adapter in WebSocketJSExecutor::ConnectAsync

- .ado/templates/publish-build-artifacts-for-nuget.yml
- change/react-native-windows-ad5982b9-fb47-405a-9abd-6ee2b6d23e72.json
- vnext/Scripts/PublishNugetPackagesLocally.cmd
- vnext/Scripts/Tfs/Layout-Headers.ps1
Unfortunatley there is no good way to the Publish pipeline this other than through checking in via PR. So attempting another fix because the Paths in the Publish jobs are not the same as the build machines.
> Update Nuget publish to not overwrite the created anycpu version

- change/react-native-windows-588ea8f6-b37e-4b9f-8452-a2d02804859d.json
- vnext/template/cpp-lib/proj/MyLib.vcxproj
- vnext/template/cs-lib/proj/MyLib.csproj
This update to the lib templates helps fix the issue where native module repos also have example apps in their codebase, and two copies of M.RN get restored and built against.
When setting for `ReactNativeWindowsDir`, we start searching for RNW based on the location of the project file and looking upwards for node_modules/react-native-windows. In the case of a regular app repo with  a single root package.json, where every native module is under the app's node_modules, the app and native module projects all find the same version.
In other repo layouts, we run into cases with multiple package.json files, and where the app is lower in the folder hierarchy than the native module it's consuming (such as an example app within a native module repo, as per issue #6576). You can then up with …
>  Update lib template to default prefer RNW dir of consuming app

- change/react-native-windows-e6f9e1a2-9958-4c28-af55-80100258ac48.json
- vnext/JSI/Shared/ChakraRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.IntegrationTests/AddValues.js
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
- vnext/Microsoft.ReactNative/JsiApi.idl
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
This PR adds ability to use JSI in NativeModules in case if it is executed in an JS engine that implements JSI.
When we use Web Debugging, there is no JSI and the new `ExecuteJsi` method does nothing.
The new `ReactContext::ExecuteJsi` takes as a parameter a lambda that has `facebook::jsi::Runtime&` argument.
Inside of this lambda we can run any code that uses the `facebook::jsi::Runtime&`.
The code is always run in the `JSDispatcher`. 
- If we are already in the `JSDispatcher` thread, then the code is executed synchronously.
- If we are in a different thread, then the lambda is posted to be executed in `JSDispatcher`.
This is an example of usage taken from the ReactNativeHostTests.cpp:
```C++
reactContext.ExecuteJsi([&](facebook::jsi::Runtime &rt) {
auto eval = …
```
> Add ReactContext::ExecuteJsi method to use JSI in NativeModules

- .ado/publish.yml
Have the universal x64/release build do the header layouts, rather than the x64/debug one. Since we use x64/release as the default for nuget packages.
> Have the universal x64/release build do the header layouts.

- change/react-native-windows-3460da96-2737-4874-8f5a-a79d89eb0942.json
- vnext/Microsoft.ReactNative/Views/ViewPanel.cpp
- vnext/Microsoft.ReactNative/Views/ViewPanel.h
Fixes #6586
This fixes a long standing bug in layout that was discovered recently in RNTester.  This recent bug fix exposed the bug:
https://github.com/microsoft/react-native-windows/pull/6451
The bug is straightforward.  In ViewPanel we do this to invalidate for arrange when top/left changes:
```
/*static*/ void ViewPanel::SetTop(xaml::UIElement const &element, double value) {
element.SetValue(TopProperty(), winrt::box_value<double>(value));
element.InvalidateArrange();
}
```
The call to element.InvdliateArrange() is the bug.
This is making the assumption that the ViewPanel is responsible for positioning itself.  This isn't correct.  It is the parent's responsibility for positioning its children.  Thus we are invalidating the wrong element.  We should invalidate the parent, not …
> Fix invalidation bug

- change/react-native-windows-47f0ee14-4ccf-47a3-98c0-c2d982c53259.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
While looking at memory usage for my App I noticed that the number of CPanels identified by !idallocs kept increasing without going down. The number of CPanel objects in the !idallocs dump did not match the printout from !xamlstats.
With this change everything matches up again! Same number of CPanels on the heap as their are in the tree :)
> Fix CPanel leak when a transform is applied

- change/react-native-windows-31c93351-ecbc-4fe1-9d24-98219e03f248.json
- vnext/Microsoft.ReactNative.IntegrationTests/TestBundle.targets
> Don't run test bundling when doing intellisense builds in VS

- change/react-native-windows-2c7c8288-f17e-42f0-b803-1449fea26904.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
- vnext/PropertySheets/RequireSolution.targets
This adds a new target to be included by external apps and libs, which will throw an error if they attempt to build without a solution file.
Closes #6581
> Add error for users who try to build apps/libs via project instead of solution

- change/react-native-windows-98d06b6c-abde-4e6a-9d1e-a910ca14bc4b.json
- packages/playground/windows/playground-win32.sln
- packages/playground/windows/playground/MainPage.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApi.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/Microsoft.ReactNative.Cxx/ReactContext.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
- vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
In this PR we refactor changes that were introduced to ReactContext API during the 0.64 development.
The goal is to simplify the ReactContext  and to allow non-JSI based JS engine API to be used in future.
- A number of new `IReactContext` properties were extracted into a new `IReactSettingsSnapshot` interface and added `IReactContext::SettingsSnapshot` property to reference them.
- The `IReactContext::JsiRuntime` was replaced with  `IReactContext::JSRuntime` that has type `Object`. It should allow us to replace the JS Engine API with a an `IUnknown`-based implementation and avoid a hard dependency on the experimental JSI ABI implementation which we plan to remove in favor of another interface.
- The `ReactContext::ExecuteJsi` member function is removed and replaced with a standalone …
> Refactor ReactContext API

- docs/building-rnw.md
This pull request fixes the issue #6625 with monorepo page not found.
---
The monorepo details page for RNW leads currently to the 404 result, while the *monorepo.md* page is available in the docs.
Changes provided in this PR fix this issue by converting the capital letter used for the *monorepo.md* page in the *building-rnw.md* page source code.
Please see the commit message for more details in case of any doubts or questions.
---
Change has been tested and verified locally.
> Monorepo page capital letter fix in building-rnw page

- change/react-native-windows-init-8de4ce60-313c-4b58-aa80-92eb307869e9.json
- packages/react-native-windows-init/src/Cli.ts
Fixes #6610
I missed during eslint rule enabling that we were converting user exit codes from integers back to the original strings when sending to telem. This change makes us send the string instead of int for telem to keep schema consistency (although a larger telem payload).
Instead of the enum method of object access to integer, then reverse mapping from ordinal back to string, we just pass the string as a union type and convert to int from the map in the place where we set process exit code.
> set strings for telem exit codes

- change/react-native-windows-34026362-bdf7-4921-9cb1-90b87780623e.json
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
The new ExecuteJsi function fails in BabylonNative code because there is a bug getting the ABI-safe JSI runtime for host functions and host objects.  In this PR we fix the issue by properly mapping the ABI-safe JSI runtime with the internal one it contains.
> Fix getting JsiRuntime for host functions

- change/@react-native-windows-cli-4be26f48-0076-4686-9fb4-6fe14a114393.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
This pull request fixes #6281 
Changes introduced in this PR provide the project with enhanced error printed when generating a self-signed certificate fails for any reason. The timeout set for generating the self-signed certificate is removed.
---
The implementation of this fix contains two main changes:
* Remove the *timeout* set for a powershell command creating the self-signed certificate.
This allows any machine to generate the self-signed certificate no matter how slow it is (please see the linked issue).
Another idea was to make this timeout value configurable, but in the end it would just reduce the comfort of creating the RNW project, as the timeout would be one of the arguments, or it would be default
(leaving it as default would require changing the value, but to which value …
> Self-signed certificate - timeout error fix

- change/react-native-windows-71860b92-7530-44e6-9d99-c06cb3814d8e.json
- vnext/ReactCommon/ReactCommon.vcxproj
> [0.64] Fix multicore build, missing dependency on Folly

- change/react-native-windows-f13d8d0e-a58a-4fae-981d-f677627c032d.json
- packages/@react-native-windows/tester/package.json
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- vnext/package.json
- yarn.lock
A beachball update made our nightly publish go off the rails and release "0.0.0". Revert the beachball update and reset versions so that we continue the canary series.
> Fix react-native-windows version

- change/@react-native-windows-cli-051559ce-5052-441b-8929-549d53999890.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
- packages/react-native-windows-init/src/Cli.ts
This PR backports #6669 to 0.64.
> [0.64] Update cli telemetry defaults

- change/@react-native-windows-cli-a3d1917f-fa0d-4a55-9567-add8fe505b93.json
- packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
- packages/react-native-windows-init/src/Cli.ts
This PR backports #6669 to 0.63.
> [0.63] Update cli telemetry defaults

- change/react-native-windows-2020-12-04-12-29-09-62updatev8.json
- vnext/Desktop.DLL/packages.config
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/V8JSIRuntimeHolder.cpp
- vnext/ReactWindowsCore/V8JSIRuntimeHolder.h
- vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
Update V8 to the latest package version (includes V8 version 8.7);
Properly pass through the debuggerBreakOnNextLine engine option to V8;
> [0.62] Update V8 package version

- change/@rnw-scripts-integrate-rn-1b0001cc-2902-477a-ba81-ec722cdb5fed.json
- packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts
- packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
As part of integrating a new release of react-native we run an algorithm to synchronize dependencies, peer dependencies, and devDependencies across the repo. Part of this involves updating any peer dependencies to react-native that would be broken by a new version. We do that only if the existing peer dependency is unsatisfied by the new version.
The semver package has some surprising behavior when testing satisfaction of wildcard peer dependencies, where it does not count any prerelease build as satisfying it. This leads to us to try to bump the wildcard semver and fail if we encounter it.
Special case wildcard when doing semver satisfaction checks.
> Fix dependency syncing for wildcard peer dependencies

- change/@rnw-scripts-create-github-releases-71c0b2d9-e2d4-44aa-a2dd-23463d22f3a3.json
- change/@rnw-scripts-integrate-rn-264060b3-e018-4fe5-a23c-114e2b493cc5.json
- change/@rnw-scripts-promote-release-886c8d49-5a3c-4360-be9b-280c4e982782.json
- change/@rnw-scripts-take-screenshot-53b0d611-b841-40ef-8fcf-99cd5486db3b.json
- change/react-native-platform-override-d4f4757d-82bb-4069-afa7-7e34d653dd28.json
- change/react-native-windows-codegen-ec623ba9-5181-402f-aaee-a3c7a750dff5.json
- change/react-native-windows-init-5af39e72-8d77-4cea-a8ff-e96edda20a54.json
- packages/@rnw-scripts/create-github-releases/package.json
- packages/@rnw-scripts/integrate-rn/package.json
- packages/@rnw-scripts/promote-release/package.json
- packages/@rnw-scripts/take-screenshot/package.json
- packages/react-native-platform-override/package.json
- packages/react-native-windows-codegen/package.json
- packages/react-native-windows-init/package.json
- packages/react-native-windows-init/src/Cli.ts
Fixes #6631
When cutting an unreleased version we may not have an available npm package. We can link a local unreleased package, but doing a yarn install will complain if the version is not found in the npm registry. This change modified useDevMode logic to instead specify a wildcard version, which keeps yarn happy with the linked but unreleased version.
> Allow unreleased RNW versions with react-native-windows-init --useDevMode

- .ado/jobs/cli-init.yml
- .ado/jobs/desktop.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/nuget-desktop.yml
- .ado/jobs/universal.yml
- .ado/publish.yml
- .ado/templates/build-rnw.yml
- .ado/templates/e2e-test-job.yml
- .ado/templates/prepare-env.yml
- .ado/templates/publish-build-artifacts-for-nuget.yml
- change/react-native-windows-da27daf1-4c02-4914-a570-789b03ec2bcf.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/ReactCommon/ReactCommon.vcxproj
This PR updates the PR validation step for the 'Universal' build.
* It splits out the Build and the Test steps.
* It runs the Build phase on the new windevbuild agents and the tests on the old Hosted agents
*  While for universal alone overall it would probably be faster to run the test at the same time as the build, but the build now runs on the windevbuild agents which don't support UI tests.  So overall the build completes faster
* To run tests as soon as the build unblocks this change uses Azure Devops templating infrastructure to expand the build matrix rather than the build-in matrix expansion. which would only start the first test after the last build completes. This injects a step 'UniversalBuild' to allow other jobs to wait on this one.
This allows the nuget tests to wait un just …
> Split out Universal build in Build and Test

- change/react-native-windows-a206e50b-eb3d-4f1e-bb61-35d4d333e417.json
- vnext/Desktop/Modules/UIManagerModule.cpp
This PR is to augment the fix in PR #6321 where we wanted to make that the `UIManager` is destroyed from UI thread.
We are still getting reports that code crashes because the `UIManager` is destroyed in a background thread.
It happens because in the code below the `m_uiQueue` is already stopped and as a result we still destroy the `UIManager` in a BG thread instead of UI queue.
```C++
m_uiQueue->runOnQueue([manager = std::move(m_manager)]() {});
```
To address this issue we must take the underlying DispatchQueue which is not affected by the MessageQueueThread stop condition and use it to destroy the `UIManager`:
```C++
std::static_pointer_cast<Mso::React::MessageDispatchQueue>(m_uiQueue)
->DispatchQueue()
.Post([manager = std::move(m_manager)]() noexcept {});
```
The fix must be …
> Fix destruction of UIManager in UI thread

- change/react-native-windows-dc57cc91-1d10-4457-b1fc-56069b55edff.json
- packages/E2ETest/windows/ReactUWPTestApp/TreeDumpControlViewManager.cs
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
- vnext/Microsoft.ReactNative/XamlView.h
Fixes #6682 
the Tag property is available on FrameworkElement, so when the app has elements that are not FE like hyperlinks (which are UIElements but not FE), we crash
> Touch event crash

- change/react-native-windows-5e214434-8983-474c-8d79-cae036a5fc24.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
Current implementation of JSI ABI has issues where the host object and host function do not behave correctly if `facebook::jsi::Object` or `facebook::jsi::Function` are cloned. In this PR we are changing how the mapping for host objects and functions work.
The ReactNativeHostTests is updated with the scenario that was failing before, but passes with this PR. All other JSI tests are passing too.
> Fix getting host objects and functions in JSI ABI

- change/@react-native-windows-cli-f2b98d50-5bed-4a85-abfd-c8a0cabcf7ee.json
- packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Fixes #6102 
This requires a fix to VS's DeployAppxRecipe.exe that I'm waiting to get serviced so marking this as draft for now
Update: VS is fixing the tool in 16.9 P2
> Use new command-line tool for appx deployment

- change/react-native-windows-34026362-bdf7-4921-9cb1-90b87780623e.json
- change/react-native-windows-5e214434-8983-474c-8d79-cae036a5fc24.json
- change/react-native-windows-a206e50b-eb3d-4f1e-bb61-35d4d333e417.json
- vnext/Desktop/Modules/UIManagerModule.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
The PR cherry picks 3 PRs from master to 0.64-stable:
- Fix getting host objects and functions in JSI ABI (#6693)
- Fix destruction of UIManager in UI thread (#6680)
- Fix getting JsiRuntime for host functions (#6644)
> [0.64] Cherry pick JS ABI and UI Manager destruction fixes

- change/react-native-windows-0f6efe1f-8377-4920-9644-b25e46538084.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueReaderTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
- vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
This pull request fixes #6166
The `winrt::hstring` is now handled separately when performing read/write operations on JS<->Native values passing.
---
This pull request implements the ReadValue and WriteValue functions as a separate overloads.
The benefit of this approach is that when passing the `winrt::hstring` value it is considered directly as this type, so there's no conversion required.
Without those overloads, the templated functions would catch the `is_convertible` and would pass it as the `std::string` or `std::wstring` which would cause yet another conversions after selecting and entering the overloaded constructor of `winrt::hstring`.
Changes introduced in this PR are:
* add `WriteValue` overloaded functions for both `winrt::hstring` and `winrt::param::hstring`
Even if using …
> Reader/Writer for winrt::hstring

- change/react-native-windows-92856720-40ea-4e20-ac14-b1c0178f1ba0.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Fixes #6738 
In #6268 we accidentally dropped the `topMouseLeave` event's registration in ViewManagerBase.cpp, which led to it missing in the ViewConfig in JS. 
Verified in Chrome debugger that the 'Unsupported top level event type..' exception is longer thrown from ReactNativeRenderer-dev.js@2426
> Fix RedBox on topMouseLeave event.

- change/react-native-platform-override-2020-12-11-15-19-22-master.json
- packages/react-native-platform-override/package.json
File `packages\react-native-platform-override\src\FileSearch.ts` imports `@rnw-scripts/package-utils` but didn't declare a package dependency. This cased a random failure in the MacOs Tests
>  Fix missing dependency / race condition in pacakge.json

- .ado/publish.yml
Since we sometimes end up in a bad state where either git is missed or npm is already done... This allows us to manually schedule these in the future and configure the run to skip either `npm publish` or `git push`. 
The options will show up here:
> Allow git and npm publish to be skipped when manually publishing bits

- change/react-native-windows-92856720-40ea-4e20-ac14-b1c0178f1ba0.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Cherry-pick #6739 
* Fix RedBox on topMouseLeave event.
* Change files
* make event array constexpr
Co-authored-by: Igor Klemenski <igklemen@microsoft.com>
> Cherry-pick: Fix RedBox on topMouseLeave event. (#6739)

- change/react-native-windows-a3ba06da-a261-42a2-be5d-9b023d3493f9.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApi.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.idl
This is to address an issue in the ABI-safe JSI implementation:
- When we run `ExecuteJsi` we are getting new instances of `facebook::jsi::Runtime`.
The source of the issue is that the ownership of `JsiAbiRuntime`, which is a thin wrapper around the ABI-safe interface, was not well defined. In the current implementation it is held on the callstack. If some other component keeps the provided instance, it may experience crashes. The issue was identified by N-API implementation on top of JSI from the BabylonNative project. This implementation needs to keep the `Runtime` inside of the `napi_env`.
In this PR we address the issue by keeping the `JsiAbiRuntime` inside of the `context.Properties()`. We use a property name derived from the current DLL handle. It allows each native module DLL to …
> Fix facebook::jsi::Runtime lifetime for ABI JSI

- change/react-native-windows-136ae86b-5757-4cb4-8cec-a50da19528c3.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/src/Libraries/Components/Button.windows.js
Fixes #6200 
The tabIndex prop needs to be forwarded to the underlying TouchableHighlight in order to make its way to ViewViewManager, which implements it. 
Also had to change the JSValueType that is expected from Double to Int64 for it to work.
Tested locally running:
```
<Button title="button 1" {...{tabIndex: 1}} />
<Button title="button 3" {...{tabIndex: 3}} />
<Button title="button 2" {...{tabIndex: 2}} />
```
> Add tabIndex property for Button

- change/react-native-windows-a3ba06da-a261-42a2-be5d-9b023d3493f9.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApi.h
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.idl
Cherry pick the #6745 from master branch: Fix facebook::jsi::Runtime lifetime for ABI JSI
The #6745 description:
This is to address an issue in the ABI-safe JSI implementation:
- When we run `ExecuteJsi` we are getting new instances of `facebook::jsi::Runtime`.
The source of the issue is that the ownership of `JsiAbiRuntime`, which is a thin wrapper around the ABI-safe interface, was not well defined. In the current implementation it is held on the callstack. If some other component keeps the provided instance, it may experience crashes. The issue was identified by N-API implementation on top of JSI from the BabylonNative project. This implementation needs to keep the `Runtime` inside of the `napi_env`.
In this PR we address the issue by keeping the `JsiAbiRuntime` inside of the …
> [0.64] Fix facebook::jsi::Runtime lifetime for ABI JSI (#6745)

- package.json
- yarn.lock
Jest requires node-notifier, but they haven't taken a fix that we could update to.
Closes #6752
> Force node-notifier resolution to ^9.0.0, fixes #6752

- change/react-native-windows-6b0a9e7b-b179-4854-91fa-a1752c5c89b7.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
#6652 
Setting accessibility props will make a ContentControl which will have keyboard focus on by default even if IsFocusable is set to false. To fix this, we need to also set the IsTabStop property on the ContentControl so that it isn't able to receive keyboard focus.
> Fix: Control with "AccessibilityRole" automatically get tab focus no matter the value of focusable prop

- change/react-native-windows-9b1e075e-6ff9-424b-99f6-d9bc58c34f86.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Fixes #6101 
RN v64 introduces two new events to TextInput - PressIn and PressOut - which get triggered when the user touches/clicks on the TextInput, and releases the click, respectively.
Need to use `UIElement.Addhandler(..., true)` in order to be able to listen for `PointerPressed/Released` events on the `TextBox` - they're marked as handled by one of its internal components.
As a side note, the RN commit only included JS code, which means Windows is actually ahead of RN Core in terms of native implementation.
> Add onPressIn/onPressOut Textinput events

- change/@office-iss-react-native-win32-358d7e11-56fa-4d83-a480-524e5e3648f3.json
- packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backports [#6743 ](https://github.com/microsoft/react-native-windows/pull/6743) to 0.64
> [0.64] Add target annotation prop to AccessibilityAnnotationInfo (#6743)

- .ado/publish.yml
The error from ADO was:
```
/.ado/publish.yml (Line: 80, Col: 20): Unrecognized value: 'succeeded'. Located at position 5 within expression: and(succeeded(), not(parameters.skipGitPush), ne(variables['Build.SourceBranchName'], 'master')). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```
> Fix publish pipeline due to ADO not recognizing `succeeded()` from template expression

- change/@react-native-windows-cli-ce9bd95b-9609-4aa9-8cc1-aac2b148ea3b.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Fixes #6769
When vswhere is missing (or we fail to find msbuild tools), we fail to print an error message before exiting
> Print error message when vswhere/msbuild tools are missing

- change/@react-native-windows-cli-55162ecb-57f9-4f08-b45f-a6e00b71a23b.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Fixes #6769
When vswhere is missing (or we fail to find msbuild tools), we fail to print an error message before exiting
> [0.64] Print error message when vswhere/msbuild tools are missing

- change/@react-native-windows-cli-2020-12-18-04-39-09-vswhere-0.63.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Fixes #6769 
When vswhere is missing (or we fail to find msbuild tools), we fail to print an error message before exiting
> [0.63] Print error message when vswhere/msbuild tools are missing

- .gitignore
- change/@react-native-windows-cli-3b609198-fa72-476b-943b-df441c5784d6.json
- change/react-native-windows-b973e5dc-d862-4a91-8e81-e846331c5c82.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- vnext/Scripts/rnw-dependencies.ps1
We keep getting reports from folks who hit build issues that turn out to be due to them not running the dependencies script.
When building fails, check whether rnw-dependencies has been run. Update the script to leave a sentinel file behind so we can check it. Also plan to submit whether the sentinel is there in telemetry.
Also move node to use LTS version (currently 14).
> Check deps when builds fail

- docs/contributing.md
Updated Contributing Guidelines for yarn change. Update mentioned in #6789. Branch specification is a new requirement.
> Update Contributing Guidelines for yarn change

- change/@react-native-windows-cli-688ad427-1729-4f61-96fd-f3479242c0e0.json
- change/react-native-windows-81f7cb8b-957a-4231-b298-4f325b9cbfe9.json
- packages/@react-native-windows/cli/src/generator-common/index.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- vnext/template/.clang-format
- vnext/template/cpp-app/src/App.cpp
- vnext/template/cpp-app/src/App.h
- vnext/template/cpp-app/src/MainPage.cpp
- vnext/template/cpp-app/src/MainPage.h
- vnext/template/cpp-app/src/ReactPackageProvider.cpp
- vnext/template/cpp-app/src/ReactPackageProvider.h
- vnext/template/cpp-lib/src/ReactNativeModule.h
- vnext/template/cpp-lib/src/ReactPackageProvider.cpp
- vnext/template/cpp-lib/src/ReactPackageProvider.h
This PR ports #6768 to 0.64.
* Moves the line ending normalization used by autolinking into the main cli generation, to prevent creating mixed LF and CRLF files
* Updates autolinking code to exactly match new project code, so running autolinking on a fresh cli project produces 0 changes
* Fixed the removal of the clang-format guards from the template files to prevent creating mixed LF and CRLF files
Closes #6766
Closes #6767
> [0.64] Fix newline issues in new cli project generated files (#6768)

- change/@react-native-windows-cli-2020-12-29-11-44-02-newlinefixes63.json
- packages/@react-native-windows/cli/src/generator-common/index.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- packages/@react-native-windows/cli/templates/.clang-format
- packages/@react-native-windows/cli/templates/cpp/src/App.cpp
- packages/@react-native-windows/cli/templates/cpp/src/App.h
- packages/@react-native-windows/cli/templates/cpp/src/MainPage.cpp
- packages/@react-native-windows/cli/templates/cpp/src/MainPage.h
- packages/@react-native-windows/cli/templates/cpp/src/ReactPackageProvider.cpp
- packages/@react-native-windows/cli/templates/cpp/src/ReactPackageProvider.h
This PR ports #6768 to 0.63.
* Moves the line ending normalization used by autolinking into the main cli generation, to prevent creating mixed LF and CRLF files
* Updates autolinking code to exactly match new project code, so running autolinking on a fresh cli project produces 0 changes
* Fixed the removal of the clang-format guards from the template files to prevent creating mixed LF and CRLF files
Closes #6766
Closes #6767
> [0.63] Fix newline issues in new cli project generated files (#6768)

- package.json
- yarn.lock
Appium support brings in axios. Appium support *has* updated to ^0.21.1 in their master, but have not published the fix.
We can remove this resolution if we remove Appium.
Closes #6702
> Add resolution for axios@^0.21.1 to pass CG

- change/react-native-windows-ac778b2a-4dd4-46a3-ab77-fd7c7e5fb99f.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/Microsoft.ReactNative.Cxx/ReactCommon/TurboModuleUtils.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactCommon/TurboModuleUtils.h
- vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.cpp
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj.filters
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/JSI/ChakraJsiRuntime_edgemode.cpp
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/Scripts/Tfs/Layout-Headers.ps1
In this PR we enable support for C++ TurboModules as they defined in react-native package.
The C++ TurboModules  use JSI and we can enable their support based on our ABI-safe JSI implementation.
The only additional code that we needed to add is the ABI-safe wrapper for CallInvoker and ABI-safe registration of TurboModules.
The TurboModules can use the same base types as in the react-native package.
Though we had to do a small fix to the TurboModuleUtils.h to avoid unnecessary dependency on Folly.
We have added new JsiTurboModuleTests to test the use of the TurboModules.
It shows that the TurboModule must be inherited from the `facebook::jsi::TurboModule` and registered using the Package provider that might look as in the test:
```C++
struct MySimpleTurboModulePackageProvider
: …
```
> Enable support for C++ TurboModules

- package.json
- yarn.lock
Backporting #6810 to 0.64.
Appium support brings in axios. Appium support has updated to ^0.21.1 in their master, but have not published the fix.
We can remove this resolution if we remove Appium.
Closes #6702
> [0.64] Add resolution for axios@^0.21.1 to pass CG (#6810)

- change/@rnw-scripts-create-github-releases-5d3d6d63-eea1-443f-b040-18292eab4ff7.json
- packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
We seem to not be creating releases when we should be sometimes. It's hard to understand why with current logging (running theory is a race on tag creation).  Add some logging.
No need to backport this to branches doing releases (stable branches) since they always run the latest published script.
> Add some more logging to release creation script

- change/react-native-windows-ac778b2a-4dd4-46a3-ab77-fd7c7e5fb99f.json
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/JSI/Universal/ChakraJsiRuntime_edgemode.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/Microsoft.ReactNative.Cxx/ReactCommon/TurboModuleUtils.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactCommon/TurboModuleUtils.h
- vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.cpp
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj.filters
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/JsiApi.cpp
- vnext/Microsoft.ReactNative/JsiApi.h
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
- vnext/Scripts/Tfs/Layout-Headers.ps1
Cherry pick the #6804 from master branch: Enable support for C++ TurboModules
The #6804 description:
In this PR we enable support for C++ TurboModules as they defined in react-native package.
The C++ TurboModules  use JSI and we can enable their support based on our ABI-safe JSI implementation.
The only additional code that we needed to add is the ABI-safe wrapper for CallInvoker and ABI-safe registration of TurboModules.
The TurboModules can use the same base types as in the react-native package.
Though we had to do a small fix to the TurboModuleUtils.h to avoid unnecessary dependency on Folly.
We have added new JsiTurboModuleTests to test the use of the TurboModules.
It shows that the TurboModule must be inherited from the `facebook::jsi::TurboModule` and registered using the Package …
> [0.64] Enable support for C++ TurboModules (#6804)

- change/react-native-windows-a63e7858-8496-49aa-9f5a-6e48db31dd50.json
- vnext/PropertySheets/Bundle.props
* Specify full path when bundling
* Change files
* .
* Change files
* PR fb
Co-authored-by: Alexander Sklar <asklar@winse.microsoft.com>
> [0.64] Bundle in solution dir (#6736)

- change/@react-native-windows-cli-74f5405f-0058-4b85-903d-1d2043b285a2.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
PR feedback from https://github.com/microsoft/react-native-windows/pull/6809#discussion_r551517453
> Print cwd if generator cannot detect project package

- .ado/jobs/jschecks.yml
- package.json
- yarn.lock
The latest version 1.0.25 of unbroken ironically broke itself :)
We should have never depended on an implicit declared version in our CI. This changes makes the version pinned and tracked.
I'm putting in version 1.0.24 since that one works for now. 
Dependabot will help us keep it updated via a properly validated PR step.
> Fix version of unbroken to fix builds

- change/@office-iss-react-native-win32-99cda2a6-29a2-4c95-b366-77c8052b91b5.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.d.ts
- packages/react-native-win32/src/typings-index.ts
Adding a Typescript declaration file for the FocusManager API.
> Adding Typescript declaration file for FocusManager API

- change/@office-iss-react-native-win32-0d8d6c5c-d153-432d-aa59-dac541419b81.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.d.ts
- packages/react-native-win32/src/typings-index.ts
Adding a Typescript declaration file for the FocusManager API.
Backporting to 0.64
> [0.64] Adding Typescript declaration file for FocusManager API (#6834)

- change/@office-iss-react-native-win32-2021-01-07-15-23-04-0.62-exportPlatformColor.json
- packages/react-native-win32/etc/react-native-win32.api.md
- packages/react-native-win32/just-task.js
- packages/react-native-win32/src/Libraries/StyleSheet/NativeOrDynamicColorType.win32.d.ts
- packages/react-native-win32/src/index.win32.ts
- packages/react-native-win32/src/overrides.json
- packages/react-native-win32/src/typings-index.ts
Missing export for the backported win32 PlatformColor function, to give access to system colors such as those provided by high contrast themes.
> [0.62] export win32 PlatformColor function for system colors access

- change/react-native-windows-0702e81f-38d9-4c98-9040-a29aec2eaa58.json
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Fix #6715 
**_Why_**
The issue is a bug with the textDecorationLine prop for the Text component where the UI is failing to display the correct styling. When the textDecorationLine prop is set to ‘underline’, an underline appears. But if the prop is then set to ‘none’ or even removed entirely, the underline still persists. This buggy behavior also happens for the other values for this prop, ‘line-through’ and ‘underline-line-through’. Another instance of buggy behavior is when the textDecorationLine prop is initially set to ‘underline’, an underline appears. But if the prop is then set to ‘line-through’, the underline still persists along with the strikethrough.
**_What_**
Turns out buggy behavior in RNW is the result of a bug in XAML, where updates to the textDecorationLine prop are …
> Add Workaround for XAML Bug with textDecorationLine

- change/react-native-windows-2020-10-20-17-25-59-dimsfix.json
- change/react-native-windows-2021-01-12-15-06-36-backport-bugfix-dimension_never_fires_change_events.json
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
This pull request fixes #6689 
These changes provide the fix already implemented in PR #6286 but instead of applying the dependency changes (please see #6285) it uses the `CallJSFunction()` as a direct replacement for `EmitJSEvent()` method.
Such workaround has already been discussed in #6286 conversation and the example of an implementation has been presented already in issue #5951.
---
Changes implemented in this pull request are:
* Directly cherry-pick the original fix
NOTE: Due to the branch implementing the changes has been deleted after the merge, there was no possibility to cherry-pick only the commit applying fix for `DeviceInfoModule`. So the *change/* files has also been cherry-picked, but were further removed when generating the proper change files.
* Apply the workaround for …
> [0.63] Backport of bugfix for window dimensions fixed values

- change/react-native-windows-cc93ff7b-a218-4493-a198-f166cb586fc4.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
In v0.63 setting `View.borderRadius` causes narrator to set its focus on the entire app windows, instead of the View in question. 
In `FrameworkElementViewManager::TransferProperties()`, if `oldView == newView`, then
```cpp
xaml::Automation::AutomationProperties::SetAccessibilityView(newView, accessibilityView);
xaml::Automation::AutomationProperties::SetAccessibilityView(oldView, winrt::Peers::AccessibilityView::Raw);
```
results in the value being overwritten incorrectly. Reversing these 2 operations fixes the problem, and doesn't change anything if `oldView != newView`.
Issue doesn't occur in 0.64, though, despite this code being identical.
Fixes #6706
> [0.63] Reverse order of AccessibilityView in TransferProperties().

- change/@rnw-scripts-integrate-rn-8c70f5f7-2ccb-4c2f-bfe3-bcb5a8b5d176.json
- packages/@rnw-scripts/integrate-rn/src/integrateRN.ts
- packages/@rnw-scripts/integrate-rn/src/logger.ts
- packages/@rnw-scripts/integrate-rn/src/test/logger.test.ts
This adds a flag to the RN integration script to generate a markdown report with status of checks. This will be used for automated integration as the body of pull requests created by the bot.
We additionally automate the addition of a URL in reports to show new commits since last integration.
Added some simple UTs for the logger and manually validated against an integration.
> Allow Integration Script to Output Markdown

- change/react-native-windows-2612cd0f-8728-4026-a242-1ace7bb1bf67.json
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.cpp
It is a small change to comment out unused parameter.
> Fix unused parameter warning in AbiCallInvoker

- change/react-native-windows-91a8b6fc-6cd9-4917-909b-3657b2292dee.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
This is a "cosmetic" change in Microsoft.ReactNative.Cxx project.
We fix the location of the CallInvoker.h in the visual tree in the Visual Studio - no functional changes.
It is moved to the "TurboModule" folder along with other TurboModule related files.
Note, that the CallInvoker.h is referenced from the RN code. It is not part of RNW code.
> Move CallInvoker.h to TurboModule filter folder

- change/react-native-windows-0709cf0f-ae36-4a73-8ff8-0ab2dfb0a87c.json
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
In this PR we update the doc comments in `IReactNotificationService.idl`.
There are no any functional changes.
> Updated doc comments in IReactNotificationService.idl

- change/react-native-windows-4c6173d5-34ac-4bd7-b040-a5412e7e16fd.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSValue.h
In this PR we are adding `JSValue` constructors for `std::optional<T>` and `std::nullopt_t`.
They are convenient to use with `ReactPropertyBag`, `ReactNotificationService`, and other classes that return `std::optional<T>` which we then want to assign to `JSValue`.
The `std::nullopt_t` or empty `std::optional<T>` will result in creation of `JSValue::Null`.
For non-empty `std::optional<T>` the result will depend on the type `T`.
> Add JSValue constructor for std::optional<T>

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
- .ado/publish.yml
- .ado/templates/build-rnw.yml
- .ado/templates/prepare-env.yml
`yarn install` now requires Python. Our publish only does partial environment setup compares to PR pipelines. Do the full setup to align them and prevent publish failures.
This adds about 30-45 seconds to publish time.
This change additionally removes the `yarnBuildCmd` parameter that was being used to differentiate between `build` and `buildci`, as `yarn buildci` no longer exists.
> Setup full env in publish

- .ado/jobs/desktop.yml
- change/react-native-windows-3ea3aaf3-7dcc-4fe3-a0dd-4428730bb709.json
- vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/ReactWindows-Desktop.sln
- vnext/Shared/Modules/WebSocketModule.cpp
- vnext/Shared/WinRTWebSocketResource.cpp
- vnext/src/IntegrationTests/WebSocketBinaryTest.js
- vnext/src/Libraries/Utilities/HMRClient.windesktop.js
See React Native's JavasCript WebSocket spec:
```
constructor(
url: string,
protocols: ?string | ?Array<string>,
options: ?{headers?: {origin?: string, ...}, ...},
)
...
```
Current `WebSocketModule` implementation expects an object (similar to options), which will crash if a scalar or array of strings is passed.
This change:
- Fixes the `folly::dynamic` argument handling.
- Enhances existing JavaScript-driven validation to cover this use case (currently not part of CI).
- Re-enables Desktop integration tests for both native and JavaScript coverage (may scale down due to registered bundling issues).
Requesting backport down to `0.62` due to this being a crash-inducing bug.
> Parse WebSocket connect protocols as array

- change/react-native-windows-f75ccf0a-9fa8-45f5-b596-88461d774a72.json
- vnext/Microsoft.ReactNative.Cxx/ReactNotificationService.h
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
- vnext/Microsoft.ReactNative/IReactNotificationService.cpp
- vnext/Microsoft.ReactNative/IReactNotificationService.h
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
This PR addressed the issue described in #6836 and #6840.
The `ReactNotificationService` is used to send notifications between native modules, and between native modules and the app.
To provide automatic unsubscription on instance unload for all subscriptions created in native modules, we have implemented parent-child relationship between the `ReactNotificationService` ("parent") created in `ReactNativeHost::InstanceSettings` and in the `ReactContext` ("child"). The issue was that while notifications from the "child" service is propagated to the "parent", there was no mechanism to propagate them from the "parent" to "children".
In this PR we fix the issue. While we keep the same parent-child relationship, we change the way the notifications are sent and how we subscribe to them:
- All …
> Fix ReactNotificationService for notifications between app and modules

- change/@rnw-scripts-create-github-releases-1c5f008e-3d42-4be3-add5-f455c3feea81.json
- packages/@rnw-scripts/create-github-releases/package.json
- packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
- yarn.lock
We're going to be adding more code that uses the GitHub API. This increase in usage makes it worth using GitHub's official API library instead of rolling our own REST code. This allows some benefits such as built-in typing, automatic errors, plugins to retry on failure, etc. Use this in the release creation script instead of using node-fetch directly.
The dependency is heavy enough to not make sense in this isolated use-case, but makes more sense with icreases usage in future repo tooling.
> Use octokit instead of raw GitHub REST APIs

- change/react-native-windows-cb6bdb02-00b3-447c-9f28-0a37b02e9b70.json
- vnext/Scripts/rnw-dependencies.ps1
Looks like I had forgotten to push this commit when fixing the python dep.
Fixes #6876
> [missed commit] Python dependency in rnw-dependencies

- .ado/jobs/universal.yml
- change/@rnw-scripts-create-github-releases-1c5f008e-3d42-4be3-add5-f455c3feea81.json
- change/react-native-windows-3ea3aaf3-7dcc-4fe3-a0dd-4428730bb709.json
- change/react-native-windows-663c5c20-08c0-4b23-8377-318ae421cce4.json
- change/react-native-windows-ad05eec2-7e56-4a04-a9e1-e9669b578b51.json
- change/react-native-windows-af8b02f2-8ac4-4496-9215-1af4253e4ed5.json
- change/react-native-windows-cb6bdb02-00b3-447c-9f28-0a37b02e9b70.json
- change/react-native-windows-f75ccf0a-9fa8-45f5-b596-88461d774a72.json
- packages/@react-native-windows/tester/CHANGELOG.json
- packages/@react-native-windows/tester/CHANGELOG.md
- packages/@react-native-windows/tester/package.json
- packages/@rnw-scripts/create-github-releases/CHANGELOG.json
- packages/@rnw-scripts/create-github-releases/CHANGELOG.md
- packages/@rnw-scripts/create-github-releases/package.json
- packages/E2ETest/CHANGELOG.json
- packages/E2ETest/CHANGELOG.md
- packages/E2ETest/package.json
- packages/IntegrationTest/CHANGELOG.json
- packages/IntegrationTest/CHANGELOG.md
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/CHANGELOG.json
- packages/microsoft-reactnative-sampleapps/CHANGELOG.md
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/CHANGELOG.json
- packages/playground/CHANGELOG.md
- packages/playground/package.json
- vnext/CHANGELOG.json
- vnext/CHANGELOG.md
- vnext/Scripts/rnw-dependencies.ps1
- vnext/package.json
The codegen project requires .net core 3.1 which was installed with VS when installing ".net desktop development", but 16.8 changes the default to .NET Core 5. 
Fixes #6511
> Install .net core 3.1

- package.json
- yarn.lock
This version of Beachball will create chagelog entries for bumps of package dependencies. This is reflected for CLI updates as "Bump @react-native-windows/cli to foo" instead of omitting the cause of a change.
See https://github.com/microsoft/react-native-windows/issues/6523
> [0.64] Bump Beachball to 1.49.0

- .github/CODEOWNERS
As we approach release, we're tightening the bar for changes to be merged into the 0.64-stable branch. Require that PRs merged into the branch are looked at by triage approvers.
> Enforce triage for changes going into 0.64-stable

- .ado/publish.yml
- .ado/templates/yarn-install.yml
- change/react-native-windows-08284e22-e5ed-45af-b5f5-056623065466.json
- packages/@react-native-windows/bot-coordinator/.eslintrc.js
- packages/@react-native-windows/bot-coordinator/.funcignore
- packages/@react-native-windows/bot-coordinator/.gitignore
- packages/@react-native-windows/bot-coordinator/.vscode/launch.json
- packages/@react-native-windows/bot-coordinator/HeartbeatFunction/function.json
- packages/@react-native-windows/bot-coordinator/HeartbeatFunction/index.ts
- packages/@react-native-windows/bot-coordinator/HeartbeatFunction/readme.md
- packages/@react-native-windows/bot-coordinator/host.json
- packages/@react-native-windows/bot-coordinator/jest.config.js
- packages/@react-native-windows/bot-coordinator/just-task.js
- packages/@react-native-windows/bot-coordinator/local.settings.example.json
- packages/@react-native-windows/bot-coordinator/package.json
- packages/@react-native-windows/bot-coordinator/proxies.json
- packages/@react-native-windows/bot-coordinator/tsconfig.json
- vnext/Scripts/rnw-dependencies.ps1
- yarn.lock
This change adds a new package for the bot coordinator, adapting a template function app to engineering systems in our repo. Right now it does very little, and it mostly just structure and deployment.
Deployment of the function app is tied to nightly publish, partially for ease of use, but also to ensure changes to monorepo packages are reflected. Azure credentials are tied as a service connection to Pipelines, only for explicitly authorized pipelines (i.e. publish).
Validated building/running the function app locally. Have tested bits of the deploy, but not everything end to end. That might need some iteration based on how Azure Pipelines likes it, but its job is independent of the rest of publish so it shouldn't degrade it (apart from potential YAML parse errors).
> Stand up Bot Coordinator Azure Function 

- .ado/publish.yml
- change/@rnw-scripts-create-github-releases-db60a644-c294-4dc0-8fd6-58148494ab59.json
- packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
The release creation script works by finding locally published git tags (such as one just created by beachball) without an associated GitHub release, then creating a release if changelog information can be determined.
Creating release notes for all missing tags is useful as release notes will self-correct if a single job failed, and missing notes can be quickly fixed if issues arise. It also means a tag cannot opt-our of having release notes though.
Before automating release note creation, we removed many old tags that we didn't want to show up in the releases view. These are still present on many local machines though, and at one point were pushed back to the repository, seemingly erroneously.
GitHub's API will not check validity of tags, so it is possible to run the script locally and …
> Add warning to release creation script when publishing multiple releases

- .ado/publish.yml
- .ado/templates/react-native-init.yml
Fixes #6907
Fixes #6632
Beachball changed behavior of the publish command to keep git state the same as pre-publish. This was by-design, but breaks our scripts which assume we have new version numbers along with new changelog entries.
This change runs git pull after publish, which *should* preserve previous behavior.
> Pull after Beachball publish

- .ado/publish.yml
- .ado/templates/yarn-install.yml
- change/@react-native-windows-bot-coordinator-ae22026d-9e8f-47fd-8d12-2746c66d3a84.json
- packages/@react-native-windows/bot-coordinator/package.json
Pipeline logic in bot deployment wasn't quite correct, which isn't super unexpected. This change fixes a couple of issues before trying to test deployement again.
1. Setting variables for the yarn install template only in the case of frozenLockfile: true, can create ordering issues
2. Powershell scripts with pipe characters on the wrong line
We also declare the bot coordinator as a public package so that beachball will warn if it depends on a private package (as those cannot work outside the monorepo).
> Try to fix bot deployment

- change/react-native-windows-aa0093e6-70a0-4e91-a8dd-33a085d891c7.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
We'll want to make our logic more resilient to VS changes so we don't have to keep adding new versions but I want to unblock folks today, so pushing this fix out the door now and we can do the longer term thing separately :)
Fixes #6924 for the current version. Will file a new issue to track the longer term solution.
> Update "consume C# module" to support new .net native versions

- .ado/publish.yml
Danny added parameters to avoid publishing NPM packages or pushing git commits. This adds a similar flag for skipping Azure Functions deployment.
> Add parameter to not deploy bots on dry runs

- change/react-native-windows-2021-01-22-13-43-17-jest63.json
- vnext/package.json
These files make it much easier to setup jest tests running for react-native-windows.
> [0.63] react-native-windows package should include jest preset/setup files

- change/react-native-windows-2021-01-22-13-53-12-jest64.json
- vnext/package.json
These files make it much easier to setup jest tests running for react-native-windows.
> [0.64] react-native-windows package should include jest preset/setup files

- change/react-native-windows-4227d9cf-19b4-4f5a-8170-0ea553f63dc9.json
- vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
This module is being initialized on a non-XAML thread, but it is setting up PLM handlers to notify when the app switches between being on the background/foreground. Fix it by posting the work to register to the ui thread, then jumping to the JS thread when setting the current state to notify JS.
These events were broken once before and fixed in #6500 but it looks like the tests may not have caught this new break.
Fixes #6943
> Fix AppState handlers not firing

- packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
fix a trailing comma bug in json arrays
Fixes #6944
> Update XamlTreeDump dependency to 1.0.6 

- change/react-native-windows-4227d9cf-19b4-4f5a-8170-0ea553f63dc9.json
- vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
> [0.64] Background/Foreground app state handlers should be registered from the xaml thread

- change/react-native-windows-2021-01-25-11-23-29-appstate-0.63.json
- vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
- vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
> [0.63] Background/Foreground app state handlers should be registered from the xaml thread

- change/@rnw-scripts-create-github-releases-765556a8-2f59-4d64-a09b-5744c6a267a9.json
- change/@rnw-scripts-format-files-35cf3696-d0d2-4f22-a102-fbbb1107be9d.json
- change/@rnw-scripts-integrate-rn-2a4c8845-1d05-42e5-af93-04db70cb2fdf.json
- change/@rnw-scripts-promote-release-bd579eb8-bef3-4ae6-b031-9a844133555a.json
- change/@rnw-scripts-take-screenshot-012d98b3-d17e-4ff0-a3ba-6ffe056580b1.json
- change/react-native-platform-override-66d1f409-77b7-4783-96b7-cd40cdbbef78.json
- change/react-native-windows-38b27314-e544-4861-865c-1506fb830205.json
- change/react-native-windows-codegen-cf62f93a-3a2f-428b-83b0-e4d6d5428752.json
- change/react-native-windows-init-214ab6e8-12d9-46b4-9bf0-9fc92f8851e0.json
- packages/@rnw-scripts/create-github-releases/bin.js
- packages/@rnw-scripts/create-github-releases/package.json
- packages/@rnw-scripts/format-files/bin.js
- packages/@rnw-scripts/format-files/package.json
- packages/@rnw-scripts/integrate-rn/bin.js
- packages/@rnw-scripts/integrate-rn/package.json
- packages/@rnw-scripts/promote-release/bin.js
- packages/@rnw-scripts/promote-release/package.json
- packages/@rnw-scripts/take-screenshot/bin.js
- packages/@rnw-scripts/take-screenshot/package.json
- packages/react-native-platform-override/bin.js
- packages/react-native-platform-override/package.json
- packages/react-native-windows-codegen/bin.js
- packages/react-native-windows-codegen/package.json
- packages/react-native-windows-init/bin.js
- packages/react-native-windows-init/package.json
- vnext/package.json
- vnext/react-native.config.js
- yarn.lock
This change makes our bin stubs load `source-map-support` to show TypeScript stack traces on exception. It internally works by registering its own uncaught exception handler, and mutating the Error object. This is a small dependency, so we're able to use it in production as well as development.
> Show TS Stack Traces on Uncaught CLI Exception

- change/react-native-windows-6b0a9e7b-b179-4854-91fa-a1752c5c89b7.json
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
* In Xaml, IsTabStop makes a control be able to receive focus or not so we also need to set it when IsFocusable is set.
* Change files
> [0.64] Fix: Control with "AccessibilityRole" automatically get tab focus no matter the value of focusable prop (#6728)

- change/react-native-windows-0553c349-bdaf-4bcc-ad68-074f1f4f5d7a.json
- vnext/Folly/Folly.vcxproj
- vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.cpp
- vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
- vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactNativeHeaders.h
- vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
- vnext/Mso/comUtil/qiCastCore.h
- vnext/Mso/debugAssertApi/debugAssertApi.h
- vnext/Mso/object/queryCast.h
- vnext/PropertySheets/Warnings.props
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/Shared/DevSupportManager.cpp
- vnext/Shared/Executors/WebSocketJSExecutor.h
- vnext/Shared/Modules/NetworkingModule.cpp
- vnext/Shared/Modules/SourceCodeModule.h
Removes some "disable warnings" that are not needed. These warnings are required per SDL.
- C4018 - 'expression' : signed/unsigned mismatch
- C4146 - unary minus operator applied to unsigned type, result still unsigned
- C4995 - 'function': name was marked as #pragma deprecated
> Restore some SDL warnings (first pass)

- change/react-native-windows-2f9e933a-0ef8-4ee6-af39-dd343420ccab.json
- vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
Root control uses an RS4+ only API, causing crashes at startup on RS3 and below.
Followup fixes #5132
> Fix startup crash on RS3

- .ado/templates/react-native-init.yml
This saves several 1-2 minutes of the critical path our our CLI tests by skipping npx installing react-native again and makes it use the version already downloaded by midgard-yarn and installed locally.
I tried to find npx equivalent in yarn, there are a few but they wouldn't work out of the box with midgard-yarn...
> Speed up react-native init in CLI tests

- docs/e2e-testing.md
#6947 removed consts.ts. This made the external link validation fail causing a constant warning on the JavaScript checks.
> Update e2e docs for external link

- change/react-native-windows-083f1165-a2b7-4be3-8e8b-522983f37163.json
- vnext/Microsoft.ReactNative/ABIViewManager.cpp
- vnext/Microsoft.ReactNative/ABIViewManager.h
- vnext/Microsoft.ReactNative/IViewManager.idl
Currently custom view manager have to have their size specified directly on them.  Internally we have some logic to ensure that native layout is run on native controls, but community/custom view manger have no way to opt into that logic.
This adds a new interface that custom viewmanagers can implement, `IViewManagerRequiresNativeLayout`.  This interface contains a single boolean property `RequiresNativeLayout`.  If the viewmanager returns true for this property, then we will do what we do internally to ensure native layout gets run.
Fixes #6411.
> Allow custom view managers to be able to trigger our logic to run native layout

- change/react-native-windows-93385742-18a3-4c29-b83b-1b87733bb4ce.json
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.h
- packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
- vnext/template/cpp-app/src/App.cpp
- vnext/template/cpp-app/src/App.h
- vnext/template/cs-app/src/App.xaml.cs
This PR contains only changes to samples and new project templates. No core code changes.
When an application is activated using a link we currently see a dark screen because the app does not navigate to the `MainWindow`. We have all the required wiring inside of the `ReactApplication`, but it is not clear what needs to be done in the application to make it work.
In this PR we update our sample apps and new project templates to have the `OnActivated` method overwritten that navigates to the `MainWindow` when the activation is done against a newly launched app.
> Fix deep linking activation

- .ado/jobs/cli-init.yml
We should not run out of memory for these builds anymore, so make then required to avoid accidentally sneaking in breaks.
Fixes #6129
> Make hermes and WinUI3 checks required again now that we have better agents.

- .ado/jobs/universal.yml
> Remove 20 sec from critical path to not clone repo in 'synchronization' job.

- change/react-native-windows-d1742e8e-85f4-4dc4-a93c-5d9f3948f50e.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
**tl; dr;** We have a typo that breaks the Switch component, and here's a fix.
Currently, the Switch component doesn't work - toggling it doesn't result in the `onChange` callback being invoked.
I debugged it and found out that deep in the `ReactNativeRenderer` the event listener for the `topChange` event in the `bubbled` phase of capture was not getting located. Tracing it all the way up through the construction of the `ViewConfig`, and then across the bridge to `OInstance` and the `remoteModuleConfig` object, I noticed that we corrupt the `customBubblingEventTypes` object that gets passed on to the `ReactNativeViewConfigRegistry` - the `phasedRegistrationNames` field contained ['captured', 'cap**bubbled**tured'], which produced a cascading error and the onChange callback was not …
> [FIX] Switch component not working.

- change/@office-iss-react-native-win32-2752f0fe-6159-4841-9de3-9ace95e0097b.json
- change/react-native-windows-d2033839-e93f-48a0-81fc-c30b6a012c07.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32-tester/overrides.json
- packages/react-native-win32-tester/package.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Integrating the new RC bits into 0.64-stable. No file conflicts, but we do get some important JS platform updates.
Command: `yarn integrate-rn 0.64.0-rc.3`
> [0.64] Integrate react-native 0.64.0-rc.3

- change/react-native-windows-00d11bb8-8263-4188-af57-f438d1ab587b.json
- vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
By default, XAML enables both vertical and horizontal scrolling for the native `ScrollViewer`. 
The `scrollToEnd` method relies on checking whether horizontal scrolling is enabled to know if 'end' means 'bottom' or 'right'.
Setting horizontal scrolling to disabled by default - can be enabled with the 'horizontal` RN prop.
> Fix ScrollToEnd for vertical <ScrollView>.

- .ado/jobs/integration-test.yml
Tests running are conditioned on  `$(NoDeployOption)` being an empty string. String interpolation into above commands shows it is an empty string. Was not correctly accessing runtime variables it looks like.
> Integration Test App Not Running in CI

- change/@react-native-windows-cli-577379f2-2f69-4382-ae0f-f986dd33a54d.json
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Partial fix for #6941
Mechanism testing for dependencies is unreliable, so this error message is often incorrect. Soften language to imply suggestion instead of root cause. New for 0.65, so no need to backport.
> Better dependency warning on run-windows build error

- package.json
- yarn.lock
There was a change to how the Refresh method is registered that was a spanning change between RN and metro.
https://github.com/facebook/react-native/commit/306edff62c5af8997a9760c2b7b7f600ced5510e
https://github.com/facebook/metro/commit/144830b35871c99263378792d4514a5d54600109
We have picked up the RN side of that change, but not the metro side.  Unfortunately we get our version of metro from @react-native-community/cli, which hasn't been updated yet.  So until that is updated, we can force our repo to use a newer version of metro locally, so that refresh continues to work.
> Bump version of metro to fix fast refresh

- change/react-native-windows-a5f6672e-a543-4e67-912f-d0b401953d2d.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
Make sure all FB code uses the same flags to improve build parallelism.
This is because msbuild has to invoke different cl.exe invocations for each 
set of flags and msbuild inside a project is single threaded. 
So if each of the following 4 cpp files had different flags overall would be:
(#otherFiles * costPerFile / #cores) + (4 * costPerFile)
with this it would be:
(#otherFiles * costPerFile / #cores) + (4 * costPerFile / #cores)
given each cpp file is 15-20 seconds on a build agent, 
this should save ~45 seconds of build time.
> Improve compile time by increasing paralelism

- change/@react-native-windows-cli-8b43c495-33e7-4911-a6ee-aa9451b43017.json
- packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
- packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Fixes #7081 by moving most file operations to be async
> Make most autolink FS operations async

- .ado/windows-vs-pr.yml
Since this is a common thing folks forget, let's perform the change file check earlier to save resources and fail early if someone forgot to run `yarn change`
> Early change check in PR validation

- change/@rnw-scripts-jest-debug-config-8b535a05-86da-456e-aaf3-598af0fe44e8.json
- packages/@rnw-scripts/jest-debug-config/jest.debug.config.js
Fixes #7096
Updated in e2e config and unittest config, but not debug config used by VSCode.
> Do not try to execute snapshots in Jest debug config

- change/react-native-windows-7dad67fd-f462-4483-9c48-ce1cd160f497.json
- vnext/template/cs-app/src/AutolinkedNativeModules.g.cs
> Fixed typo in template which breaks C# autolinking

- change/@react-native-windows-cli-2021-02-11-09-44-26-autolinktypo63.json
- packages/@react-native-windows/cli/templates/cs/src/AutolinkedNativeModules.g.cs
Backporting #7102 to 0.63.
Closes #7097
> [0.63] Fixed typo in template which breaks C# autolinking

- change/react-native-windows-2dead2dd-8acc-4a17-a3f2-7e3091cde5ad.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
When modifying the contents of a `TextInput` programmatically, the cursor position gets moved to the front, which is the default behavior of XAML. Overriding it to enable dynamic re-write scenarios - eg. auto-capitalize, removing forbidden characters etc..
Fixes #6786
> [FIX] Cursor resetting in TextInput

- change/react-native-windows-9b1e075e-6ff9-424b-99f6-d9bc58c34f86.json
- packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Events added in RN 0.64, need to cherry-pick
> [0.64] Add onPressIn/onPressOut Textinput events #6754

- yarn.lock
It seems there was a semantic conflict in the yarn.lock file edits form the last 3 dependabot merges I did in the morning...
I noticed that several PR builds started failing early in the setup phase....
This PR fixes the lock file.
> Fix Yarn.lock

- change/react-native-windows-2021-02-16-10-55-56-follyarm64.json
- vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
There is an issue consuming the win32 dll internally, due to some issue with linking only on arm64 release builds.
There is an issue tracking the issue here:
https://developercommunity2.visualstudio.com/t/arm64-release-error-lnk2040-relocation-pageoffset/1338200
In the meantime, this avoid the specific export that's causing the issue.
For reviewers: starting line 1097 is where the fix is
> [0.63] Workaround arm64 compiler bug for internal consumption

- .ado/templates/react-native-init.yml
- change/@react-native-windows-cli-a9518dc5-9d31-4eae-931e-055d46bedb85.json
- change/react-native-windows-249bff49-d0fc-49e3-a4fb-fec202c395ae.json
- packages/@react-native-windows/cli/src/healthChecks.ts
- packages/@react-native-windows/cli/src/index.ts
- vnext/Scripts/rnw-dependencies.ps1
- vnext/react-native.config.js
Running `react-native doctor` installs the dependencies for react-native android, and when on a mac for react-native iOS.
This PR makes it so that running `react-native doctor` in a project that is using `react-native-windows` on a windows machine will help users install the dependencies needed for `react-native-windows`.
The output of running `react-native doctor` will looks something like this:  (The react-native-windows section is added by this PR)
```
E:\Repos\react-native-windows2\packages\playground>npx react-native doctor
Windows
✓ Free space on E: > 15 GB
✓ Installed memory >= 16 GB
✓ Windows version > 10.0.16299.0
✓ Developer mode is on
✓ Long path support is enabled
✓ Choco
✓ git
✓ Visual Studio >= 16.5 with UWP and Desktop/C++
✓ NodeJS 12, 13 or 14 installed
✓ Chrome
✓ Yarn
✓ …
```
> Integrate rnw-dependencies into react-native doctor

- change/@react-native-windows-cli-280a57c0-befb-4056-8cbf-0e2417f689a9.json
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
If the autolinking check fails, the error should include the proper command to fix it.
Closes #6761
> Fixes autolink check error to include command to fix it

- .ado/jobs/jschecks.yml
- .ado/templates/compute-beachball-branch-name.yml
- .ado/templates/react-native-init.yml
- .ado/variables/vs2019.yml
- .ado/windows-vs-pr.yml
It turns out that during the variable expansion the PR branch variables are not properly populated yet...
This change updates the yaml to extract the branch name to just before we need it.
> Fix branch name problem with beachball

- change/@react-native-windows-cli-4dcf4d3c-2602-4173-a389-5f1f0392e66a.json
- packages/@react-native-windows/cli/powershell/Add-AppDevPackage.ps1
The Hosted agents add _work to the agent path i.e `d:\a\_work\1\s` vs `d:\a\1\s` caused max path issue for the unittest project when switching.
> Avoid MaxPath issue with telemetry in UnitTest project

- change/react-native-windows-bac296d9-c8c9-452c-861e-6e9a1fa7872a.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
When we work in the samples app solution and edit Microsoft.ReactNative files we see a build issue where the  DevMenuControl.xbf cannot be copied to the App package because there is a version conflict between the version produced by the  Microsoft.ReactNative project and the C++ native module project that tries to copy the old version of the same DevMenuControl.xbf file.
The issue exists only for the incremental builds and seems to be caused by a bug in XAML Build logic that does not update the XBF files in child projects correctly. The issue seems to be related only to C++ DLL projects. The C# DLL projects do not cause the same issue.
Because of this issue we must to do a full rebuild every time we change any Microsoft.ReactNative files.
In this PR we fix this issue by forcing the C++ …
> Fix DevMenuControl.xbf copy conflict

- change/@react-native-windows-cli-574dfc33-3d0e-4e33-9f03-16ee0384aead.json
- packages/@react-native-windows/cli/src/config/configUtils.ts
- packages/@react-native-windows/cli/src/config/dependencyConfig.ts
- packages/@react-native-windows/cli/src/config/projectConfig.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Fixes #7164
We were erroneously using the assembly name as a project name, which will be different for C# projects that get --namespace passed to init. Also updating the deploy code to use the earlier version of VS that supports the VS deploy tool
> Fix projectName issue with C# projects and deploy tool version check

- change/react-native-windows-b7f2b1f4-dbd1-4e33-9d88-554afde1b11a.json
- vnext/Scripts/OfficeReact.Win32.nuspec
Adding RuntimeExecutor.h to the office win32 nuget: required for internal consumption of react-native-win32.
> Include RuntimeExecutor.h in nuget

- change/react-native-windows-c597c4ed-90a3-4cbe-81a9-2a9c993edcde.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
As reported in #7172, the native event payload does not contain the
pixel width and height of the image in standard cases (that use
BitmapImage). The issue was that the metadata for width and height sent
in the event was not updated until the XAML ImageSource.ImageOpened
event fired, and the onLoad event itself was triggered by the
BitmapImage.ImageOpened event. The BitmapImage.ImageOpened event will
always fire before it's parent ImageSource.ImageOpened event, thus the
event emitted to React Native would never have up-to-date information on
the image size.
This commit moves the logic to update the image size metadata from the
ImageSource.ImageOpened event to the BitmapImage.ImageOpened event.
Fixes #7172
> Fixes missing image size in Image onLoad event

- change/react-native-windows-2dead2dd-8acc-4a17-a3f2-7e3091cde5ad.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
* Fix cursor resetting in TextInput.
* Change files
* Do no preserve selection, just cursor.
Co-authored-by: Igor Klemenski <igklemen@microsoft.com>
> [0.64] [FIX] Cursor resetting in TextInput (#7056)

- change/react-native-windows-aee3f006-7675-42fc-932f-445f1f54a976.json
- vnext/Scripts/OfficeReact.Win32.nuspec
Adding RuntimeExecutor.h to the office win32 nuget: required for internal consumption of react-native-win32.
> [0.64] Include RuntimeExecutor.h in nuget

- docs/e2e-testing.md
- docs/managedCodeGen.md
When the sample apps project was renamed in #7003 , it broke all releases CI because we have markdown docs that point to the code in master. Since the path changed, the links got broken which causes CIs to break due to the now broken link.
> Fix links in markdown docs in 0.64

- change/react-native-windows-91ae018b-5e13-44ec-8d2a-0105ccd5303b.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
This change adds a counter to ensure that only the latest prop value for
image source will be used in the ReactImage::SetBackground method and
also prevents a bug where the ImageBrush opacity gets stuck at zero by
checking that the URI has actually changed.
Fixes #7191
Fixes #7192
> Fixes race conditions for ReactImage

- change/react-native-windows-923d9c58-108f-4eb0-9f78-dfa4daabec03.json
- vnext/Microsoft.ReactNative/XamlUIService.cpp
Some events e.g. Loaded do not have a sender, so we crash trying to get the Tag from the null view
> Fix DispatchEvent for events that don't have a sender

- change/react-native-windows-923d9c58-108f-4eb0-9f78-dfa4daabec03.json
- change/react-native-windows-a032e591-3908-4bf5-90a6-4b8972478e89.json
- vnext/Microsoft.ReactNative/XamlUIService.cpp
Reverts microsoft/react-native-windows#7207
Going to try a different approach for now
> Revert "Fix DispatchEvent for events that don't have a sender"

- change/jest-environment-winappdriver-6f4a1d63-2951-4e4a-a78d-18f76018c64e.json
- docs/e2e-testing.md
- packages/jest-environment-winappdriver/README.md
Documenting the `testEnvironmentOptions.winAppDriverBin` property - used when WinAppDriver is not located under the path we hardcode.
> Update e2e doc with info about configuring WinAppDriver path

- change/react-native-windows-29f65fa8-43ca-4485-9da4-0168ac84cd17.json
- vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
Resolve #5908 
**_Why_**
announceForAccessibility method in the AccessibilityInfo module failed to announce messages.
**_What_**
The API for the method does not include a reference to a RN component as a parameter but Windows requires an element to announce from. The previous implementation tried to pass in Xaml::Window::Content into FrameworkElementAutomationPeer::FromElement to create an automation peer, but this approach always resulted in the peer being null and no announcement could be made. 
Altered the code such that a Xaml Control (TextBlock) is passed into FrameworkElementAutomationPeer::FromElement instead. This caused the peer returned to be non-null and the announcement could be fired.
**_Testing_**
Created an RNW app and altered Microsoft.ReactNative inside of tester app with …
> Fix announceForAccessibility

- .ado/templates/build-rnw.yml
- .ado/templates/prep-and-pack-single.yml
The microsoft ADO instance maintains two different tasks named NuGetCommand. This means pipelines running on that ADO instance need the unique GUID to identify it.
Part of #5540.
> Update NuGetCommand@2 with workaround for microsoft ADO

- change/react-native-windows-529f30ae-e99b-41c4-8da5-fd63deb8c688.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
There is a [bug](https://github.com/microsoft/Win2D/issues/809) in GaussianBlurEffect from Win2D that causes images to disappear when moving the app between screens. Since the ReactImageBrush always created the GaussianBlurEffect (even when `blurRadius` was 0) whenever `resizeMode=repeat` or `tintColor` was used on the Image, this meant that Images that only used `resizeMode` or `tintColor` suffered from the same bug.
This change ensures that GaussianBlurEffect is only used when the `blurRadius` prop is non-zero.
Fixes #7205
> Narrow fix for tintColor and repeat images

- change/react-native-windows-2021-03-01-10-44-41-fix-unloading.json
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
This adds `ReactViewHost::PostInQueue` method that *safely* calls the callback as long as the `ReactViewHost` is still alive. It was unsafe before as it would capture the raw `this` pointer, which could result in a crash (I was able to observe this).
However, for *unloading* the view, we actually want to capture the `ReactViewHost` strongly to ensure that it gets fully detached from the `ReactHost` and that `AppRegistry.unmountApplicationComponentAtRootTag()` is called.
> Ensure root views are properly unloaded

- change/react-native-windows-96f79fad-22cc-49c2-a3a1-7727f3903e48.json
- vnext/Scripts/rnw-dependencies.ps1
The recent changes to our test infrastructure require WinAppDriver version >= 1.2.1, but this new requirement was not added to the requirements script
Fixes #7223
> Update WinAppDriver version requirement

- change/react-native-windows-c5698690-4198-40b4-8676-9fc490f8f49d.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Previously, scroll events on TextInput mapped to `onOnScroll`. The
correct event name is `onScroll`. This fixes that.
Fixes #7258
> Fixes registration name for TextInput onScroll

- packages/e2e-test-app/windows/ReactUWPTestApp/MainPage.xaml.cs
- packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
The new version of the library includes support for dumping attached properties, which we need.
> Bump version of XamlTreeDump library

- change/react-native-windows-97d7ac05-284f-40fe-9829-493043e1988b.json
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
While making the change to filter out right button clicks, it was only applied to `PointerPressed` while `PointerReleased` was omitted. This results in a warning being produced on subsequent RMB clicks.
Closes #7269
> Fix cursor warning when right clicking

- docs/e2e-testing.md
Fixes #7266
Fixes #7240
This documents how you can run a single test from E2ETest, with restriction. Fixing the restriction is tracked by https://github.com/microsoft/react-native-windows/issues/7272
> Fix documentation for running a single E2ETest Test

- change/react-native-windows-66a7a026-2973-48ac-ad29-9153ea483a8b.json
- vnext/Scripts/rnw-dependencies.ps1
Removing outdated comment about Appium from the dependency script. We're already not installing Appium, WinAppDriver is properly included there.
Closes #6676
> Remove stale Appium comment

- change/react-native-windows-2021-03-04-18-44-45-0.63-stable.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
The name export is being exported as CODE rather than DATA. This breaks CHPE/Arm64X linking. Any exports of DATA removes the ability to delayload the library.
> [0.63] Avoid exporting data as that breaks delay loading

- change/react-native-windows-b4e6adb2-e454-4bfe-9455-8bc887380703.json
- vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
- vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h
Addresses a bug raised in https://github.com/microsoft/react-native-windows/pull/7260#discussion_r587943444
> Avoid re-registering render callbacks when coalescing single element queue

- change/react-native-windows-init-ff672186-e7d4-4afc-a426-920010c7da26.json
- packages/react-native-windows-init/src/Cli.ts
> Added 0.64+ to projectType flag for react-native-windows-init cli

- .ado/publish.yml
This should prevent publish from failing due to our nuget multifeed issues.
> Add NugetSecurityAnalysisWarningLevel=warn for publish.yml

- change/react-native-windows-97d7ac05-284f-40fe-9829-493043e1988b.json
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Backporting the warning fix to 0.64.
* Fix right click warning.
* Change files
Co-authored-by: Igor Klemenski <igklemen@microsoft.com>
> [0.64] Fix cursor warning when right clicking (#7278)

- change/react-native-windows-00b73d31-195e-4e20-97d3-444d09a770eb.json
- vnext/Desktop.UnitTests/MemoryMappedBufferTests.cpp
Desktop solution fails to build on Visual Studio `16.9.0` with the current master as follows:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): error C2220: the following warning is treated as an error [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
```
> Disable warning 4103 in MemoryMappedBufferTests.cpp

- change/react-native-windows-13f152f1-ba5d-438b-ae7c-56187ed56783.json
- vnext/Scripts/rnw-dependencies.ps1
- VS Enterprise
- require 18362 sdk
- add cppwinrt vsix for rnw dev
> Fix rnw-dependencies.ps1

- .ado/publish.yml
This should prevent publish from failing due to our nuget multifeed
issues.
> [0.64] Add NugetSecurityAnalysisWarningLevel=warn for publish.yml

- change/react-native-windows-560f15c9-e411-419e-8d58-46cdcbb247ef.json
- vnext/Microsoft.ReactNative/ABIViewManager.cpp
- vnext/Microsoft.ReactNative/IViewManagerCore.idl
> Enable view managers to be notified about JS event handler attach/detach

- .ado/templates/build-rnw.yml
- .ado/templates/prep-and-pack-single.yml
This PR backports #7238 to 0.63.
The microsoft ADO instance maintains two different tasks named NuGetCommand. This means pipelines running on that ADO instance need the unique GUID to identify it.
Part of #5540.
> [0.63] Update NuGetCommand@2 with workaround for microsoft ADO (#7238)

- .ado/templates/build-rnw.yml
- .ado/templates/prep-and-pack-single.yml
The microsoft ADO instance maintains two different tasks named NuGetCommand. This means pipelines running on that ADO instance need the unique GUID to identify it.
Part of #5540.
> [0.64] Update NuGetCommand@2 with workaround for microsoft ADO (#7238)

- change/react-native-windows-58079bd4-79e5-455a-a510-7b6beb15e66b.json
- vnext/src/Libraries/Components/TextInput/TextInputState.windows.js
Given JS state is async from native state, it is possible that a control
may lose native focus, but the TextInputState module that manages focus
for TextInput components may not yet have received the event, and as a
result may ignore commands to focus the TextInput. This change removes a
check from TextInputState that would prevent focus commands from
executing.
Fixes #7303
> Fixes case where focus commands may be ignored

- .ado/publish.yml
- .ado/templates/build-rnw.yml
- .ado/templates/e2e-test-job.yml
- .ado/templates/prep-and-pack-nuget.yml
- .ado/templates/react-native-init.yml
- .ado/windows-vs-pr.yml
- change/react-native-windows-2021-03-09-10-04-18-compiler60.json
- vnext/Folly/Folly.vcxproj
- vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
Latest MSVC versions break 0.60 folly. This patches folly to allow them to be used with newer MSVC builds.
> [0.60] Support newest MSVC versions

- change/react-native-windows-00b73d31-195e-4e20-97d3-444d09a770eb.json
- change/react-native-windows-7fe6b7ea-630a-4f0e-bf79-394a1ddb0f0a.json
- vnext/Desktop.UnitTests/MemoryMappedBufferTests.cpp
> [0.64] Disable warning 4103 in MemoryMappedBufferTests.cpp

- change/react-native-windows-65cb61de-5d53-4917-8d6e-b50d3b506a93.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj.filters
- vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
The React instance notifications (`InstanceCreated`, `InstanceLoaded`, and `InstanceDestroyed`) introduced in 0.64 version are raised on a dispatcher thread that is used internally for synchronizing ReactHost and ReactInstanceWin components. While it works, it makes it difficult to use in the code because this dispatcher is not exposed to the public API and users must always redirect it to JS nor UI dispatchers. Such asynchronous redirection may cause unexpected issues in instance unload scenarios.
E.g. it is the the root cause of the issue #7305 where it is impossible to correctly destroy the JSI Runtime when a React instance is reloaded.
In this PR we change these notifications to be always raised in the JSDispatcher thread. This way the notifications are following the native module …
> Raise Instance notifications in JSDispatcher thread

- change/react-native-windows-65cb61de-5d53-4917-8d6e-b50d3b506a93.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.js
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj.filters
- vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
Cherry pick PR #7356.
Original description:
The React instance notifications (`InstanceCreated`, `InstanceLoaded`, and `InstanceDestroyed`) introduced in 0.64 version are raised on a dispatcher thread that is used internally for synchronizing ReactHost and ReactInstanceWin components. While it works, it makes it difficult to use in the code because this dispatcher is not exposed to the public API and users must always redirect it to JS nor UI dispatchers. Such asynchronous redirection may cause unexpected issues in instance unload scenarios.
E.g. it is the the root cause of the issue #7305 where it is impossible to correctly destroy the JSI Runtime when a React instance is reloaded.
In this PR we change these notifications to be always raised in the JSDispatcher thread. This way the …
> [0.64] Raise Instance notifications in JSDispatcher thread (#7356)

- change/react-native-windows-2fe5aef3-7497-4418-8cf6-038834f023b1.json
- vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
- vnext/Microsoft.ReactNative/XamlUIService.cpp
- vnext/Microsoft.ReactNative/XamlUIService.h
- vnext/Microsoft.ReactNative/XamlUIService.idl
- vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js
#7220 added functionality to announceForAccessibility which worked for UWP apps. New changes allow for method to work for apps using XAML Islands. Note: apps using XAML Islands must now set/specify an AccessibleXamlRoot in order for announceForAccessibility to work. AccessibleXamlRoots must be able to create an automation peer or need to set AutomationProperties::LandmarkTypeProperty() to 80002.
> Add Functionality to announceForAccessibility to Support Xaml Islands

- change/react-native-windows-b3c2f4a8-d704-4a38-b837-993459d15495.json
- vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
As stated in issue #7283, the cursor position changes seem to be somewhat different on each platform. Since we're already adding code in react-native-windows to change the Windows default cursor positioning behavior, we might as well make it a bit more consistent with other platforms. The change here matches the behavior on iOS, macOS and Web (so it's only different from Android, which seems to keep cursor position relative to the TextInput value length constant).
Fixes #7283
> Change TextInput cursor behavior

- yarn.lock
This PR updates the version of node-notifier we use to pass CG.
> [0.64] Upgrade to node-notifier@8.0.2

- .ado/jobs/universal.yml
Leverage the fatter PCH file to improve compile times.
For the Universal build this saves 3 minutes. 
I only enabled it for Universl for now since that is on the critical path.
CI validation will still build without the flag.
> Enable RNW_FASTBUILD for PR validation

- .ado/publish.yml
This PR backports #6705 into 0.64-stable.
> [0.64] Allow git and npm publish to be skipped when manually publishing bits (#6705)

- .ado/publish.yml
This PR backports #6774 to 0.64.
> [0.64] Fix publish pipeline due to ADO not recognizing `succeeded()` from template expression (#6774)

- change/react-native-windows-03e0841c-eea4-4548-912a-5ca9abe8284d.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
The AzDO agents now include VS with uwp 6.2.11, not 6.2.10; the codegen integration tests had a strict version dependency, relaxing it.
> Fix build for codegen test on new agents

- change/react-native-windows-2a59f263-f757-4309-93ae-257a58fa468a.json
- vnext/src/Libraries/ReactNative/PaperUIManager.windows.js
Fixes #7295.
There is some debug code used to detect deprecated properties - https://github.com/facebook/react-native/blob/e68cf7cee9d36271a1d3899fecff817304bb8bdc/Libraries/Utilities/deprecatedPropType.js#L26
Part of that code will call `UIManager.hasViewManagerConfig` for View/Image (since they have the deprecatedPropType set).  This function should return false, but in the process it calls into `UIManager.getViewManagerConfig`.  This is protected by a null check of `UIManager.getViewManagerConfig`.  
Ideally we'd be able to have the web debugging version of UIManager not provide that method, but without manually implementing the module instead of using the macros, I dont see a good way to have the module provide difference methods in webdebugging vs non-webdebugging.  Instead, I've …
> Get constants for view manager throws

- .ado/windows-vs-pr.yml
I've noticed that frequently contributers that don't primary work in our repo miss running `yarn change` and we have to explain it.
This hopefully will put the error more front and center and make it more self-serve for our contributors.
and
> Improve error message for forgetting to run `Yarn change`

- change/@react-native-windows-cli-8bc4d332-33c7-4e49-860e-3d7dab8011a3.json
- packages/@react-native-windows/cli/package.json
- yarn.lock
Bumping the xmldom dependency in react-native-windows\cli to mitigate security vulnerability CVE-2021-21366. master has already been updated. See #7412 for corresponding PR for 0.63.
> [0.64] Bump xmldom to 0.5.0.

- change/react-native-windows-e0a73f29-3f67-499f-953d-3427552c2bad.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/IReactPackageProvider.idl
- vnext/Microsoft.ReactNative/IReactPropertyBag.idl
- vnext/Microsoft.ReactNative/JsiApi.idl
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/Microsoft.ReactNative/ReactApplication.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/ReactNativeHost.idl
- vnext/Microsoft.ReactNative/ReactRootView.idl
- vnext/Microsoft.ReactNative/RedBoxHandler.idl
- vnext/Microsoft.ReactNative/XamlHelper.idl
- vnext/Microsoft.ReactNative/XamlUIService.idl
In this PR we update contents and formatting of the DOC_STRINGs in IDL files.
They are used to generate docs for the ABI-safe API docs.
The PR covers changes to the following files:
- IReactContext.idl
- IReactDispatcher.idl
- IReactModuleBuilder.idl
- IReactNonAbiValue.idl
- IReactNotificationService.idl
- IReactPackageBuilder.idl
- IReactPackageProvbider.idl
- IReactPropertyBag.idl
- JsiApi.idl
- QuirkSettings.idl
- ReactApplication.idl
- ReactInstanceSettings.idl
- ReactNativeHost.idl
- ReactRootView.idl
- RedBoxHandler.idl
- XamlHelper.idl
- XamlUIService.idl
> Updates to documentation in IDL files

- .ado/templates/react-native-init.yml
Fixes #7419 
The 0.20.0 version of create-react-native-module which was just published contains breaking changes
> Update option name due to breaking change in create-react-native-module

- change/react-native-windows-885d112a-fe20-474d-8ac2-06adf41cdf0d.json
- vnext/Desktop/BeastWebSocketResource.cpp
Prevents a compilation error after the upgrade to VS 16.9.
> Make BaseWebSocketResource destructor noexcept

- change/react-native-windows-e8fc0ecf-f569-432a-a940-79548093f13f.json
- vnext/Folly/Folly.vcxproj
Sometimes downloading Folly in CI is failing due to network flakiness, add some retry logic
> Add retries to Folly download

- .ado/templates/react-native-init.yml
> [0.64] Fix CI due to breaking change in create-react-native-module

- change/react-native-windows-e728b500-ee03-4b06-924f-c68a28f5f091.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/PropertySheets/React.Cpp.props
- vnext/PropertySheets/WinUI.props
Fixes #7414 
This change enables an app to use ExperimentalFeatures.props (or another props file that gets loaded early enough) to override WindowsTargetPlatformVersion and WinUI2xVersion/WinUI3Version
> Enable apps to override WinUI and SDK version for RNW framework projects

- change/@react-native-windows-cli-e1331b3e-2da8-4116-aeee-f13557233b15.json
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
- packages/@react-native-windows/cli/src/e2etest/dependencyConfig.test.ts
- packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/.gitignore
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/react-native.config.js
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/windows/ExperimentalFeatures.props
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/windows/IndirectDependency/IndirectDependency.vcxproj
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/windows/WithIndirectDependency.sln
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/windows/WithIndirectDependency/WithIndirectDependency.vcxproj
- packages/@react-native-windows/cli/src/e2etest/projects/WithIndirectDependency/windows/WithIndirectDependency/packages.config
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Fixes #7437 
The following check incorrectly marks a project with `directDependency: false` as invalid:
```ts
itemsToCheck.forEach(item => {
dependencyIsValid = !!(dependencyIsValid &&
item in project &&
project[item] &&
!project[item].toString().startsWith('Error: '));
});
```
Adding some basic tests to ensure the indirect dependency is captured as valid
> Autolinking doesn't add a project marked as a non-direct dependency

- change/@react-native-windows-cli-d0076a39-a34a-488b-990f-f2622a21750d.json
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
> [0.64] Autolinking doesn't add a project marked as a non-direct dependency

- change/@react-native-windows-cli-e8a45edf-cfc4-4a35-9121-5f3088d8799b.json
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Fixes #7440 
The globbing we had for finding appxmanifest/recipes would find and favor the wrong architecture if more than one has been built
> Fix deployment of x64 apps when they've also been already built for x86

- change/@react-native-windows-cli-7995510b-9839-4382-b2f4-2e6ebe444f00.json
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
> [0.63] Autolinking doesn't add a project marked as a non-direct dependency

- change/@react-native-windows-cli-0feca964-7b3e-404c-8e51-364f88390786.json
- change/react-native-windows-c082b40c-f14b-48a1-b788-08264f8c0382.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/template/shared-app/src/MainPage.xaml
In react-native-community/cli#1370 the CLI was
changed in a way that can produce different values for the project name
(name in package.json) and the main component name (name in app.json).
Historically, sometimes older templates didn't set name in the
package.json at all, instead using app.json. So our CLI was written to
accomodate that logic (load name from package.json if possible, then
fallback to app.json). Either way, we use that single value everywhere
in our template, for file and varaible names.
This PR updates our template to use the value in app.json, if possible,
to set the component name to load. This matches the behavior on iOS and
and Android.
Closes #7451
> Fix app template to use app.json's name for main component name

- change/@react-native-windows-cli-4be2d5ca-e277-4951-82bf-da53ce53d4de.json
- change/react-native-windows-49f20f25-562a-474d-a144-4ca4afc65f68.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/template/shared-app/src/MainPage.xaml
[0.64] Fix app template to use app.json's name for main component name (#7464)
This PR backports #7464 to 0.64.
In react-native-community/cli#1370 the CLI was
changed in a way that can produce different values for the project name
(name in package.json) and the main component name (name in app.json).
Historically, sometimes older templates didn't set name in the
package.json at all, instead using app.json. So our CLI was written to
accomodate that logic (load name from package.json if possible, then
fallback to app.json). Either way, we use that single value everywhere
in our template, for file and varaible names.
This PR updates our template to use the value in app.json, if possible,
to set the component name to load. This matches the behavior on iOS and
and Android.
Closes #7451
> [0.64] Fix app template to use app.json's name for main component name (#7464)

- change/@react-native-windows-cli-2021-03-24-14-50-09-appjson63.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/templates/shared/src/MainPage.xaml
This PR backports #7464 to 0.63.
In react-native-community/cli#1370 the CLI was
changed in a way that can produce different values for the project name
(name in package.json) and the main component name (name in app.json).
Historically, sometimes older templates didn't set name in the
package.json at all, instead using app.json. So our CLI was written to
accomodate that logic (load name from package.json if possible, then
fallback to app.json). Either way, we use that single value everywhere
in our template, for file and varaible names.
This PR updates our template to use the value in app.json, if possible,
to set the component name to load. This matches the behavior on iOS and
and Android.
Closes #7451
> [0.63] Fix app template to use app.json's name for main component name (#7464)

- change/react-native-windows-5eed73aa-6cf2-4940-9e6e-d2ae1d5b0740.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Yoga sometimes sets `hasNewLayout` on nodes even when their layout has not changed. One common case where this occurs is in lists. Any time the scroll content container of a list is dirtied, even for something that does not affect it's dimensions, all elements in the list go through a layout pass and set `hasNewLayout` (*only when using default align behavior, which  is `alignItems: 'stretch'` for the container and `alignSelf: 'auto'` for the list items*). This change at least reduces the number of events sent to JS when layout has not really changed, though a more effective fix would be to have Yoga be a little smarter about when to layout. If you're interested, here's where Yoga decides to update layout on all stretch aligned children of a parent container: …
> Suppress onLayout event when layout has not changed

- change/react-native-windows-04fae67d-8f70-40ea-a1f6-119f6f7134ff.json
- vnext/Scripts/Microsoft.ReactNative.targets
This change is necessary to work around a bug in mdmerge.
The scenario is as follows:
- native module/view manager references nuget
- app references nuget and also references native module project
You get an mdmerge error because there are two instantiations of the M.RN types (MDM2009). Same bug as microsoft/cppwinrt#452
The fix is to ensure that copy local is false which is achieved via the `Private` attribute.
> Enable modules to consume NuGet package

- change/@office-iss-react-native-win32-b242d66c-aec8-416c-9627-bfbad81339b1.json
- change/react-native-windows-1e08502b-2b0f-460c-8875-7512862d716b.json
- packages/react-native-win32/package.json
- vnext/package.json
We actually require a change that happened in the final release of react-native, so bumping our peerDependency to reflect that.
> [0.64] Bump peer dependency to require non-rc version of react-native

- change/react-native-windows-2021-03-25-11-59-48-appstatechangeFix.json
- vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
This fix is in RNW64, but is not currently in RNW63.
https://github.com/microsoft/react-native-windows/pull/6500/
Fix AppStateModule::GetCurrentAppState from returning undefined
Also relevant:
https://github.com/microsoft/react-native-windows/issues/6482
> [0.63] Fix AppStateModule::GetCurrentAppState from returning undefined

- change/react-native-windows-dcbf0582-57f0-4850-9088-108360f8205f.json
- vnext/Shared/JSI/ChakraRuntime.cpp
- vnext/Shared/JSI/ChakraRuntime.h
Fixes #7488 
The `getOwnPropertyDescriptor` trap will enable enumerating properties so that methods like `JSON.stringify` or iterations like `for ... in` work with JSI objects.
Below is an image where a native hostobject returning a property is correctly shown via `JSON.stringify` in an alert.
> Implement JSI getOwnPropertyDescriptor

- change/react-native-windows-a1ef06ee-6340-494c-bcec-f6cf094f4c70.json
- vnext/JSI/Shared/ChakraRuntime.cpp
- vnext/JSI/Shared/ChakraRuntime.h
Fixes #7488 (backport to 0.64)
Without this fix, apps cannot enumerate JSI object properties
> [0.64] getOwnPropertyDescriptor missing implementation

- change/react-native-windows-c07dd628-fa24-4ff3-967e-d2ba099bd9b5.json
- change/react-native-windows-e728b500-ee03-4b06-924f-c68a28f5f091.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/PropertySheets/React.Cpp.props
- vnext/PropertySheets/WinUI.props
> [0.64] Enable apps to override WinUI and SDK version for RNW framework projects 

- change/react-native-windows-c7f8bf18-e09f-40e2-b3a6-6c1b1c388391.json
- packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
- vnext/src/Libraries/Components/Pressable/Pressable.windows.js
- vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
- vnext/src/Libraries/Pressability/Pressability.windows.js
Currently, the `onKeyDown|Up` properties only respond to pressing `Space/Enter/GamepadA`, and do so by firing `onPress|(in|out)` events. 
Adding support for invoking the `onKeyDown|Up` callbacks, if provided. Preserving the current behavior by executing it conditionally, if `preventDefault()` wasn't called on the event. 
https://user-images.githubusercontent.com/12816515/111390420-ef58d400-866f-11eb-816b-fe7e69c1390f.mp4
Fixes #7185
> Add onKeyDown/onKeyUp to Pressable.

- change/react-native-windows-17601253-734e-444b-b719-89f09535cfd0.json
- change/react-native-windows-e0a73f29-3f67-499f-953d-3427552c2bad.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
- vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/IReactPackageProvider.idl
- vnext/Microsoft.ReactNative/IReactPropertyBag.idl
- vnext/Microsoft.ReactNative/JsiApi.idl
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/Microsoft.ReactNative/ReactApplication.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.h
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/ReactNativeHost.idl
- vnext/Microsoft.ReactNative/ReactRootView.idl
- vnext/Microsoft.ReactNative/RedBoxHandler.idl
- vnext/Microsoft.ReactNative/XamlHelper.idl
- vnext/Microsoft.ReactNative/XamlUIService.idl
Cherry pick PR #7393
Partially cherry pick PR #7481 that fixes some typos and links in the IDL docs.
The original PR #7393 description:
In this PR we update contents and formatting of the DOC_STRINGs in IDL files.
They are used to generate docs for the ABI-safe API docs.
The PR covers changes to the following files:
- IReactContext.idl
- IReactDispatcher.idl
- IReactModuleBuilder.idl
- IReactNonAbiValue.idl
- IReactNotificationService.idl
- IReactPackageBuilder.idl
- IReactPackageProvbider.idl
- IReactPropertyBag.idl
- JsiApi.idl
- QuirkSettings.idl
- ReactApplication.idl
- ReactInstanceSettings.idl
- ReactNativeHost.idl
- ReactRootView.idl
- RedBoxHandler.idl
- XamlHelper.idl
- XamlUIService.idl
Closes #7434
> [0.64] Updates to documentation in IDL files (#7393)

- package.json
- yarn.lock
There is a security vulnerability in xmldom versions below 0.5.0. This PR adds a yarn resolution to force xmldom to be at 0.5.0.
The dependency chain that brings in the vulnerable xmldom is as follows: react-native@0.0.0-d477f8011 -> @react-native-community/cli-platform-ios@^5.0.1-alpha.0 -> xcode@^2.0.0 -> simple-plist@^1.0.0 -> plist@^3.0.1 -> xmldom "0.1.x. So bumping the xmldom used here would require considerable work, which is why we use yarn resolution here.
> Force xmldom to version ^0.5.0.

- package.json
- yarn.lock
There is a security vulnerability in xmldom versions below 0.5.0. This PR adds a yarn resolution to force xmldom to be at 0.5.0.
The dependency chain that brings in the vulnerable xmldom is as follows: react-native@0.0.0-d477f8011 -> @react-native-community/cli-platform-ios@^5.0.1-alpha.0 -> xcode@^2.0.0 -> simple-plist@^1.0.0 -> plist@^3.0.1 -> xmldom "0.1.x. So bumping the xmldom used here would require considerable work, which is why we use yarn resolution here.
Backport of #7514.
> [0.63] Force xmldom to version ^0.5.0.

- change/react-native-windows-477fa69f-8746-46c3-8a5d-0847b9e41add.json
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
- vnext/Microsoft.ReactNative/XamlView.h
This reverts commit 7d293b35946f417e3928811c53c9707c953335c7.
https://github.com/microsoft/react-native-windows/pull/6692 fixed a crash we experienced in the e2e app when clicking on the test result hyperlink (a `TextBlock` created outside of RNW, which didn't have a Tag, and our hit test crashed when trying to access the TagProperty which wasn't there.)
However, this broke the entire hit testing algorithm for nested Text elements - the added check for whether an element was a `FrameworkElement` before calling el.GetValue(TagProperty) skips the iteration over `Inline` elements of a `Span` in a `TextBlock`, because they're not FE.
Instead, using `ReadLocalValue` since it returns `UnsetValue` in case a dependency property is not present on an element.
> Restore nested press events in Text, and prevent crash.

- .ado/publish.yml
It's possible that our internal ADO doesn't even see the cron schedule for our stable branches because it doesn't support wildcards.
Trying to see if this fixes it - plus, we'll have more control over which branches get automatically published.
> Remove the *-stable branch filter from publish.yml

- change/react-native-windows-8168ecc3-8f90-47c9-8ff0-bfe30f1d2ba7.json
- packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
- vnext/Microsoft.ReactNative/Utils/TextTransform.h
- vnext/Microsoft.ReactNative/Utils/TransformableText.h
- vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/RawTextViewManager.h
- vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/TextViewManager.h
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
This change includes a number of fixes to the approach to textTransform. There were 4 issues with the previous textTransform approach that this diff solves:
1. The textTransform prop was only applied to the parent TextBlock when it had a single raw text child
2. The textTransform prop on a virtual text Span only recursed one level
3. The one-level textTransform approach had a bug where the last raw text value overwrote all Run text values (#7534)
4. The textTransform prop did not update correctly when changed
Rather than holding state in the TransformableText struct, this change keeps the originalText state exclusively in RawTextShadowNode, and only when a parent VirtualTextShadowNode or TextShadowNode has a textTransform setting (that is not "none" or undefined). The …
> Fixes textTransform recursion

- change/react-native-windows-0ab53fc0-24ac-4a26-bb0c-fae123303cc9.json
- packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
- vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
After fixing issues with textTransform, 278a3c13 introduced a bug where updates to a raw text node can overwrite the TextBlock parent if it has only a single Span child inline. This change ensures we check that the updated raw text Run is indeed the direct child of a TextBlock.
> Fixes bug where raw text update overwrites all text

- change/react-native-windows-843fc71e-c555-4165-bb7c-8b9230109b8e.json
- vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
We have a short list of brush colors we allow, and if the requested PlatformColor value is not in the list we fall back to asking the app's resources for it and we expect the value to be a brush. However, some of these values will just be Color values.
When using ` style = {{ color: PlatformColor("SystemChromeAltLowColor") }} ` , we crashe because this is an `IReference<Color>` not a `Brush`.
> Fix PlatformColor when using color names
