microsoft/react-native-windows

- change/@office-iss-react-native-win32-16aa1605-e207-4545-b716-7ce7beb61eb7.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
- packages/react-native-win32/src/index.win32.js
* Adding Polite/Aggressive Focus APIs
* Adding FocusManager API for polite/aggresive focus for win32
Co-authored-by: samuelfreiberg <Samuel.Freiberg@microsoft.com>
Co-authored-by: Nick Gerleman <nick@nickgerleman.com>
> [0.63] Win32 Polite/Aggressive Focus API (#6711)

- change/@office-iss-react-native-win32-2020-12-14-13-44-42-master.json
- packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
- packages/react-native-win32/src/index.win32.ts
- packages/react-native-win32/src/overrides.json
> [0.62] Win32 Polite/Aggressive Focus API

- change/react-native-windows-2d953fa7-7efa-42d8-8c53-2abf0a22be62.json
- packages/playground/windows/NuGet.Config
- vnext/NuGet.Config
- vnext/template/shared-app/proj/NuGet.Config
- vnext/template/shared-lib/proj/NuGet.Config
> Make package config more strict

- change/react-native-windows-d6c9a08e-e237-4a66-8d4b-97a3a6726877.json
- packages/playground/windows/NuGet.Config
- vnext/NuGet.Config
- vnext/template/shared-app/proj/NuGet.Config
- vnext/template/shared-lib/proj/NuGet.Config
> [0.64] Make package config more strict

- change/@react-native-windows-cli-2020-12-18-10-46-33-master.json
- change/react-native-windows-2020-12-18-10-46-33-master.json
- packages/@react-native-windows/cli/templates/shared/proj/NuGet.Config
- packages/playground/windows/NuGet.Config
- vnext/NuGet.Config
> [0.63] Make package config more strict

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/macos-tests.yml
> Remove fetch depth 1 as Lage does git some history operations and will fail otherwise

- change/react-native-windows-2020-12-18-10-52-40-master.json
- current/NuGet.Config
- current/local-cli/generator-wpf/templates/proj/NuGet.Config
- vnext/NuGet.Config
> [0.60] Make package config more strict

- Directory.Build.targets
> Add retry options to the copy to increase reliability

- Directory.Build.props
- Directory.Build.targets
- change/react-native-windows-9edf6a5f-06e1-45a2-ac83-c0adfd7d0f8f.json
- vnext/Directory.Build.props
> Don't do js up to date checks for design builds

- change/@react-native-windows-cli-771ccdc5-e8df-4e39-b201-aacf74cc5b68.json
- change/@react-native-windows-telemetry-8bacf3a1-1e38-4adb-b3d0-2152754a36d3.json
- change/react-native-windows-init-6488e8ef-b5c8-43ce-ac17-484b2484321a.json
- packages/@react-native-windows/cli/src/config/configUtils.ts
- packages/@react-native-windows/cli/src/generator-common/index.ts
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- packages/@react-native-windows/cli/src/index.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- packages/@react-native-windows/cli/src/runWindows/utils/build.ts
- packages/@react-native-windows/cli/src/runWindows/utils/checkRequirements.ts
- packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
- packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
- packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
- packages/@react-native-windows/cli/src/runWindows/utils/winappdeploytool.ts
- packages/@react-native-windows/telemetry/src/CodedError.ts
- packages/@react-native-windows/telemetry/src/index.ts
- packages/@react-native-windows/telemetry/src/telemetry.ts
- packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
- packages/react-native-windows-init/src/Cli.ts
This change introduces `CodedError` and integrates it with our telemetry library. This enables collecting a known set of values rather than potentially logging error strings from msbuild etc. It also enables separating information that is ok to show on the console vs. information that is ok to send through telemetry.
> Introduce structured errors type

- change/react-native-windows-4b3bffd5-1b12-4096-abe8-77b4b8661b2e.json
- change/react-native-windows-fdde5da2-dd4d-4c29-bda1-d26df017ec45.json
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
- vnext/Shared/WinRTWebSocketResource.cpp
> [0.64] Show HRESULT code on WebSocket errors

- package.json
- yarn.lock
> Bump unbroken version from 1.0.25 to 1.0.27

- change/react-native-windows-2021-01-04-18-07-20-GSX-4360428-wshresult-0.63.json
- change/react-native-windows-4b3bffd5-1b12-4096-abe8-77b4b8661b2e.json
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
- vnext/Shared/WinRTWebSocketResource.cpp
> [0.63] Show HRESULT code on WebSocket errors

- change/react-native-windows-2021-01-04-18-15-01-GSX-4360428-wshresult-0.62.json
- change/react-native-windows-4b3bffd5-1b12-4096-abe8-77b4b8661b2e.json
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
- vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
> [0.62] Show HRESULT code on WebSocket errors

- change/react-native-windows-0c8e83d5-c412-4160-a228-ee77ca677b2b.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
Fix #6217 
**_Why_**
YGValueOrDefault function with NativeUIManager crashes when input value is not in an expected format. Issue requested an error message replace the crash behavior for a better dev experience. Conversation within the issue also requested that a separate error message be displayed if the 'pt' or 'px' unit was specified in the input value to tell the user to replace with an integer value instead. 
**_What_**
Behavior matches that of iOS and Android where the following value formats are allowed:
10 - integer
'10%' - string with %
Behavior matches that of iOS and Android where the following value formats are **not** allowed and will trigger a Red Box Error:
'10pt' - string with pt
'10px' - string with px
'10' - string
**_How_**
Altered ShadowNodeBase to add a RedBox API so …
> #6217 : Add Clearer Error Msg for YGValues

- change/@office-iss-react-native-win32-dc19d42b-381d-4cd5-85d9-8c5675fb14f7.json
- change/react-native-windows-f354429c-9afd-4c81-afb2-dfdfe7ffa4c9.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32-tester/overrides.json
- packages/react-native-win32-tester/package.json
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- packages/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
- packages/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
- vnext/overrides.json
- vnext/package.json
- vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js
- vnext/src/Libraries/Network/RCTNetworkingWinShared.js
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/d3a3ce857...deda35134
Mechanical changes only. 1/8 includes MSVC fixes, but also includes some Pressable changes that will require more changes on our side.
> Integrate 1/7 Nightly RN Build

- Directory.Build.targets
> Disable yarn up to date checks in CI validation

- change/react-native-windows-ad05eec2-7e56-4a04-a9e1-e9669b578b51.json
- vnext/Scripts/rnw-dependencies.ps1
PR #6636 added a yarn install time dependency on Python.
Fixes #6876
> Add Python to dependencies script

- docs/bots/Backport and Integration Bots.md
Copying from an internally distributed Word document for further comment and archival. Internal information removed.
> Dump bot dev doc into the repo

- change/react-native-windows-aa0093e6-70a0-4e91-a8dd-33a085d891c7.json
- change/react-native-windows-bcffaeda-e396-4cde-a322-4945bd30759e.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [0.64] Update "consume C# module" to support new .net native versions

- change/react-native-windows-a0fec909-50f5-46d5-abc1-2f3b3aefc9f8.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [0.63] Update "consume C# module" to support new .net native versions

- change/react-native-windows-2021-01-22-13-51-14-jest.json
- vnext/package.json
These files make it much easier to setup jest tests running for react-native-windows.
> react-native-windows package should include jest preset/setup files

- change/@react-native-windows-cli-b59881ef-6a52-419e-a249-8cdb8b2d5c06.json
- change/react-native-windows-a33aaaa5-9bb9-465b-94b9-299644fec9a0.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
Pulling this change in to get a corresponding Hermes version to upstream.
Fixes #6838
> [0.64] Update V8 and Hermes package versions (#6917)

- change/react-native-windows-2021-01-22-14-27-31-0.63-stable.json
- vnext/Desktop.DLL/packages.config
- vnext/PropertySheets/React.Cpp.props
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
New package is built with V8 version 8.9
> [0.63] Update V8 package version

- change/@office-iss-react-native-win32-4979418e-e00e-4c34-bc45-964da24e1f94.json
- change/react-native-windows-8f5458a7-23e8-48ac-874c-834025b9728a.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/E2ETest/package.json
- packages/IntegrationTest/package.json
- packages/microsoft-reactnative-sampleapps/package.json
- packages/playground/package.json
- packages/react-native-win32-tester/overrides.json
- packages/react-native-win32-tester/package.json
- packages/react-native-win32/.flowconfig
- packages/react-native-win32/flow-typed/npm/promise_v8.x.x.js
- packages/react-native-win32/overrides.json
- packages/react-native-win32/package.json
- vnext/.flowconfig
- vnext/ReactCopies/IntegrationTests/LayoutEventsTest.js
- vnext/ReactCopies/IntegrationTests/TimersTest.js
- vnext/Shared/OInstance.cpp
- vnext/flow-typed/npm/promise_v8.x.x.js
- vnext/overrides.json
- vnext/package.json
- vnext/src/babel-plugin-codegen/index.js
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/6fd684150...c66aa8abc
Fully automatic, no real interesting commits.
> Integrate 1/21 Nightly RN Build

- change/react-native-windows-d53c18dd-9f5f-4679-9440-69b17e4456af.json
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
> Use lifted DispatcherQueue

- change/react-native-windows-461b0b90-c6db-43f0-964f-377036442424.json
- vnext/Microsoft.ReactNative.Managed/ReactContext.cs
> Remove usage of deprecated API

- change/react-native-windows-9ff89c91-1136-41b4-a8bd-f8bca90118db.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
This PR contains doc comment changes for `IJSValueReader` and `IJSValueWriter`.
There are no functional changes.
The corresponding docs repo PR: https://github.com/microsoft/react-native-windows-samples/pull/357
> [Doc] Update doc comments for IJSValueReader and IJSValueWriter

- packages/README.md
> Add README to packages directory

- change/react-native-windows-2021-01-25-18-15-16-0.62-stable.json
- vnext/Desktop.DLL/packages.config
- vnext/Desktop/packages.config
- vnext/JSI.Desktop.UnitTests/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
This backports the V8 package update which includes version 8.9 of V8
> [0.62] V8 package update

- change/@office-iss-react-native-win32-1abdd812-0554-42ef-be8c-7d52c884783f.json
- packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
* Add accessibilityDescription prop to config file
* Change files
> [0.62] Add accessibiltyDescription prop to View config  (#6970)

- change/@office-iss-react-native-win32-1abdd812-0554-42ef-be8c-7d52c884783f.json
- packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
* Add accessibilityDescription prop to config file
* Change files
> [0.64] Add accessibiltyDescription prop to View config  (#6970)

- .ado/jobs/cli-init.yml
- .ado/jobs/universal.yml
- .ado/variables/vs2019.yml
> Update CLI steps to use private 4 core agent pool

- change/react-native-windows-86019e9d-819a-4c5c-ace1-9c995444df70.json
- vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.cpp
>  AllAnimations only exists on RS5

- change/react-native-windows-6afc98ef-6d70-4f4d-9fcb-85784bfdfc82.json
- vnext/template/cs-app/src/App.xaml.cs
> Fix template for WinUI3 C# App by expanding namespace of argument in AppOnActivated

- change/@office-iss-react-native-win32-1abdd812-0554-42ef-be8c-7d52c884783f.json
- packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
* Add accessibilityDescription prop to config file
* Change files
> [0.63] Add accessibiltyDescription prop to View config  (#6970)

- .ado/jobs/desktop.yml
Desktop builds seem to be currently on the critical path, so hoping to shave off a few more minutes on overage of our Pr validation
> Migrate desktop build to better agents

- change/react-native-windows-df0a05f5-87f4-41ae-a165-0a455e0278fa.json
- vnext/Shared/tracing/tracing.cpp
> Initialize ETW provider only once

- .ado/templates/yarn-install.yml
> Bump midgard-yarn

- change/react-native-windows-7534745f-9f5e-4da9-8f97-bcc1125f57ad.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Cherry-pick of #7061 
Fixes #7057
> [0.64] Fix the Switch component

- yarn.lock
Updating pathval to resolve security vulnerability.
Closes #6979
> Update pathval to 1.1.1

- change/react-native-windows-785074ae-3954-43ad-ba5e-3748ce89c855.json
- vnext/Microsoft.ReactNative/ABIViewManager.cpp
- vnext/Microsoft.ReactNative/ABIViewManager.h
- vnext/Microsoft.ReactNative/IViewManager.idl
> [0.64] Allow custom view managers to be able to trigger our logic to run native layout

- .ado/jobs/cli-init.yml
- .ado/jobs/desktop.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/nuget-desktop.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/jobs/universal.yml
> Stop running ARM validation in PR, it is still validated in CI

- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
THe CLI tests have been successful on the new agents, expanding to other long pole work.
> Expand usage of better agents in validation

- change/react-native-windows-72d98117-3a3c-4581-8a20-f710c8890699.json
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
Found an old enlistment where I updated some docs that never made it into the react-native-windows-samples repo.  
Not sure the best way to verify what these docs markdown looks like.  -- But figure its better with something than nothing.
> Minor doc update

- change/@react-native-windows-cli-511afd68-8e89-4c3c-b42d-d94ebb98f5d7.json
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
> Fix indentation on AutolinkedNativeModules.g.targets

- change/@react-native-windows-cli-d560e28e-3435-4742-9cdd-fb9c81be8183.json
- change/react-native-windows-0e74e256-80a2-43d5-8cf9-9872a209075f.json
- packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
- packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
- packages/playground/windows/Playground-win32 (Package)/Playground-win32 (Package).wapproj
- packages/playground/windows/playground/packages.config
- vnext/Microsoft.ReactNative/XamlView.cpp
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/WinUI.props
> Update WinUI 3 to Preview 4

- change/@react-native-windows-cli-447231bd-7fc0-40af-8fd3-fc4cc93c6733.json
- packages/@react-native-windows/cli/src/config/configUtils.ts
- packages/@react-native-windows/cli/src/config/dependencyConfig.ts
- packages/@react-native-windows/cli/src/config/projectConfig.ts
- packages/@react-native-windows/cli/src/runWindows/runWindows.ts
- packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
- packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
- packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Fixes #7162. Also adding a fix for #7164 for 0.64 (will fix it in master using that bug)
> [0.64] Port deployment changes (use DeployAppRecipe in CLI)

- change/react-native-windows-04fe1c3d-2a12-4e8d-a788-d8b9acab1db0.json
- vnext/Shared/Executors/WebSocketJSExecutor.cpp
> Fix WebSocketJSExecutor crash

- change/@react-native-windows-cli-da7e3b1b-b355-47f3-ac10-44a00c0fd093.json
- packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
> Solutions with Any CPU projects get wrongly autolinked

- change/react-native-windows-ee1c3de0-f55d-4e41-b8eb-ee207275d2de.json
- packages/playground/Samples/image.tsx
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
> [Image] add svg data uri support

- change/react-native-windows-ee1c3de0-f55d-4e41-b8eb-ee207275d2de.json
- packages/playground/Samples/image.tsx
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
* [Image] add svg data uri support
* Change files
* formatting
* Update packages/playground/Samples/image.tsx
* PR feedback
Co-authored-by: Alexander Sklar <asklar@microsoft.com>
> [0.64] [Image] add svg data uri support (#7198)

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
FiIled issue #7261 to track turning it back on.
> Temporarily disable CG on PR/CI

- change/react-native-windows-7abcb8aa-50a6-40b6-9a5a-e17677e2bdba.json
- change/react-native-windows-923d9c58-108f-4eb0-9f78-dfa4daabec03.json
- packages/e2e-test-app/windows/ReactUWPTestApp/AutolinkedNativeModules.g.targets
- vnext/Microsoft.ReactNative/XamlUIService.cpp
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/runtimeexecutor/ReactCommon/RuntimeExecutor.h
- vnext/overrides.json
This breaks with MSVC 16.9
Fixes #7247
> runtimeExecutor discards std::thread ctor

- .ado/windows-vs-pr.yml
Filed issue #7261 to track turning it back on.
> [0.64] Temporarily disable CG on PR/CI

- change/react-native-windows-04ac2b06-039a-423c-af36-e8d00d6866a1.json
- vnext/JSI/Shared/ChakraRuntime.cpp
> [0.64] Remove HostObject Jsi exceptions

- change/react-native-windows-b281f453-7a97-4544-81e3-b1a1dd93ce1b.json
- vnext/Shared/JSI/ChakraRuntime.cpp
#5710 added a couple of exceptions that are blocking some partners. Removing them in the meantime to unblock them until we understand why this code is being executed better.
> Remove HostObject Jsi exceptions

- change/react-native-windows-8ca60002-6df1-4469-897a-8c8d042c448f.json
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/runtimeexecutor/ReactCommon/RuntimeExecutor.h
> [0.64] runtimeExecutor discards std::thread ctor

- change/@react-native-windows-cli-7acd994f-3013-46a4-ba8d-83ed7b864d10.json
- packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
> [0.64] Fix autolinking for solutions that have 'Any CPU' projects

- change/react-native-windows-f5d9cbbf-3492-4995-b9fb-c995019ae848.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
Backport #6891 to 0.64 to generate the updated docs
> [0.64] Backport IJSValueReader/IJSValueWriter docs to 0.64

- change/react-native-windows-319707ea-206f-44ae-a849-d12574f2b011.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
This will be rebased on top of https://github.com/microsoft/react-native-windows/pull/7308
> [0.64] Clarify some API docs 

- change/react-native-windows-319707ea-206f-44ae-a849-d12574f2b011.json
- change/react-native-windows-d67e55dd-0364-4967-b689-a5ea88430e62.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactNotificationService.idl
- vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
> Doc improvements

- .ado/publish.yml
This should prevent publish from failing due to our nuget multifeed
issues.
> [0.63] Add NugetSecurityAnalysisWarningLevel=warn for publish.yml

- change/node-rnw-rpc-3924b3a6-5f1f-43da-ab9a-67dd03e5ef2d.json
- change/react-native-windows-5366eee7-dea6-43e7-bca3-48ad36ecd5e5.json
- packages/@react-native-windows/tester/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/node-rnw-rpc/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/package.json
> Beachball sync

- change/react-native-windows-a537dfa1-1200-41e7-add4-81130e198ccd.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
> More doc formatting

- change/react-native-windows-c1da70c2-1880-4789-97f4-349ddec7b248.json
- vnext/Microsoft.ReactNative/IJSValueReader.idl
- vnext/Microsoft.ReactNative/IJSValueWriter.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
> [0.64] port doc formatting fix

- .ado/publish.yml
> [0.64] Fix codesign parameter passing

- .ado/publish.yml
> [0.64] Fix codesign parameters 2

- .ado/publish.yml
> Fix codesign parameter passing

- change/react-native-windows-a27fc5d4-c7b6-4ca9-8b02-26521cc3a3c3.json
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
> Minor docs update for ReactDispatcherHelper

- change/react-native-windows-3c0bb7fd-5e3c-4138-8f7a-f9e36d18e768.json
- vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
- vnext/Microsoft.ReactNative/TestHook.cpp
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/Microsoft.ReactNative/XamlLoadState.cpp
- vnext/Shared/Modules/AsyncStorageModuleWin32.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/cdebug.cpp
- vnext/include/Shared/cdebug.h
> Fix issues when compiling with C++20

- .ado/jobs/cli-init.yml
- .ado/jobs/universal.yml
> Fix CI loop

- .ado/publish.yml
> Enable symbol upload on Publish

- .ado/templates/build-rnw.yml
- .gitignore
- change/react-native-windows-17601253-734e-444b-b719-89f09535cfd0.json
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
- vnext/Microsoft.ReactNative/IReactPropertyBag.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/XamlUIService.idl
Fixes some typos in the docs, and adds a task in CI to generate the docs so we can validate no broken links during PR.
> 0.65 docs, generate docs in CI

- .ado/jobs/integration-test.yml
> Stop running integration tests when the build failed

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
Clean-up for #7544. From backporting (#7548) looks like the nuget.config files alone are enough to fix the issue we were hitting here.
> CI Fix Cleanup

- change/@react-native-windows-cli-526e0024-8869-425b-865a-74c10913a04f.json
- packages/@react-native-windows/cli/src/generator-windows/index.ts
> Always write nuget.config in init CLI

- change/react-native-windows-2852a1ac-d875-4239-88da-42a85bd02951.json
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
> fix filter project merge

- README.md
Porting #7596 to 0.64 to propogate changes to npm page readme.
> [0.64] README update for `good first issue` label

- change/react-native-windows-d0c003c6-f96a-494c-9336-23b946d53683.json
- vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
- vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
- vnext/PropertySheets/React.Cpp.props
> Add missing include folder to fix CI

- change/react-native-windows-3db98399-3dfa-4e81-83ff-3d300267ac38.json
- vnext/Folly/Folly.vcxproj
- vnext/fmt/fmt.vcxproj
* Generate cgmanifest.json for downloaded folly
* Generate cgmanifest.json for downloaded fmt
Closes #7704
> Generate cgmanifest.json for downloaded source dependencies

- change/react-native-windows-a4cdfcef-6797-4350-8fe7-23b7e482f48e.json
- vnext/Microsoft.ReactNative/Fabric/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ImageComponentView.h
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
> Fabric: Add support for Image events, blurRadius and tintColor

- change/@react-native-windows-cli-1d17e77d-7451-4e75-a262-2bd32cc8e120.json
- packages/@react-native-windows/cli/README.md
> Adding the useWinUI3 and useHermes tag in the Readme

- .ado/continuous.yml
- .ado/integrate-rn.yaml
- .ado/publish.yml
- .ado/windows-vs-pr.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- README.md
- change/@rnw-scripts-promote-release-88b19d76-15eb-4c7f-9900-85ae25f4b5df.json
- change/react-native-windows-134e4457-80ac-403b-bfa3-6631ba19f340.json
- docs/branch-setup.md
- docs/contributing.md
- docs/e2e-testing.md
- docs/managedCodeGen.md
- docs/monorepo.md
- packages/@react-native/tester/js/examples/Animated/AnimatedGratuitousApp/AnExSlides.md
- packages/@rnw-scripts/promote-release/src/promoteRelease.ts
- packages/README.md
- packages/e2e-test-app/README.md
- vnext/proposals/readme.md
> Prepare files for default branch rename

- package.json
- yarn.lock
> Update lage and beachball

- .ado/continuous.yml
- .ado/integrate-rn.yaml
- .ado/publish.yml
- .ado/windows-vs-pr.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- README.md
- change/@rnw-scripts-promote-release-88b19d76-15eb-4c7f-9900-85ae25f4b5df.json
- change/react-native-windows-1163fc79-b78d-4894-bc30-3265516d2241.json
- change/react-native-windows-134e4457-80ac-403b-bfa3-6631ba19f340.json
- docs/branch-setup.md
- docs/contributing.md
- docs/e2e-testing.md
- docs/managedCodeGen.md
- docs/monorepo.md
- package.json
- packages/@rnw-scripts/promote-release/src/promoteRelease.ts
- packages/README.md
- packages/e2e-test-app/README.md
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
- vnext/proposals/readme.md
- yarn.lock
[CI is hitting Warning C4127](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fms%2Freact-native-windows%2F_build%2Fresults%3FbuildId%3D169980%26view%3Dresults&data=04%7C01%7Cagnel%40microsoft.com%7C32243c7c90524fc8c9bd08d91ed4df9e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637574721893454388%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fYa7QCpOebcbcL3MEeK4sgdx3vCFVQV2MbJ7EY2MouU%3D&reserved=0)(conditional expression is constant) which is treated as an error -- needs change in ToAscii.h(215) to fix so I'm adding a forked file for now. I will put in a change in Folly to get rid of the fork going forward.
> ToAscii.h Fork Unblocking CI Failure

- package.json
- yarn.lock
> [0.65] Bump Lage and Beachball

- .ado/continuous.yml
> Setup CI for 0.65-stable

- change/react-native-windows-c3f548e1-9d33-4062-99f0-0ffdfee52aa9.json
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
> [0.65] ToAsii.h Fork Unblocking CI Failure 

- package.json
With the recent renaming of the main branch, we should also set the default branch name in package.json so we don't need to run:
```
yarn change -b main
```
> Add beachball branch config to package.json

- change/@rnw-scripts-promote-release-11f45716-5bfb-4d7c-b934-8467f17a53bf.json
- packages/@rnw-scripts/promote-release/src/promoteRelease.ts
> Update promoterelease to stamp beachball branch configuration

- change/react-native-windows-9448e377-f259-4f02-a265-9ef112855aec.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [CI Break] Support UWP 2.2.12

- change/react-native-windows-db5b74d5-5b43-482f-9799-0130d9f4504c.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [0.65] [CI Break] Port #7840

- change/react-native-windows-9448e377-f259-4f02-a265-9ef112855aec.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [0.64] [CI Break] Port #7840

- change/react-native-windows-9448e377-f259-4f02-a265-9ef112855aec.json
- vnext/PropertySheets/CppAppConsumeCSharpModule.props
> [0.63] [CI Break] Update .net UWP package versions

- .ado/templates/build-rnw.yml
> Use 0.65 version for winmd API docs

- .ado/templates/prepare-env.yml
> [0.65] Add UWP sdk version diagnostics to prepare-env

- change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
- vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
> [0.65] Fix JSValue memory leak in move constructor (#7859)

- change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
- vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
> [0.64] Fix JSValue memory leak in move constructor (#7859)

- change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json
- vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
> [0.64] Add error message when an exception happens in a native module (in Debug)

- change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json
- vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
> [0.65] Add error message when an exception happens in a native module (in Debug)

- change/react-native-windows-afc90ab9-a345-490e-a27c-7f2092a8773d.json
- packages/@react-native/repo-config/package.json
- packages/@react-native/tester/package.json
- vnext/package.json
- yarn.lock
> [0.64] Bump ws dependency

- .ado/templates/build-rnw.yml
> [0.65] Upgrade to winmd2md 0.1.13

- .ado/templates/build-rnw.yml
> Upgrade to winmd2md 0.1.13

- change/react-native-windows-2021-06-03-16-51-38-0.63-stable.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/React.Cpp.props
- vnext/Shared/V8JSIRuntimeHolder.cpp
> [0.63] V8 package update

- change/react-native-windows-2021-06-04-13-48-46-0.65-stable.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.config
- vnext/Shared/V8JSIRuntimeHolder.cpp
> [0.65] V8 Package Update

- package.json
- yarn.lock
Resolves CG alert for [CVE-2020-28469](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28469)
> CG: Add resolution for glob-parent@^5.1.2

- change/react-native-windows-99fbdd24-e0f4-4e20-8475-ec69a95664e8.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
> [0.64] V8 Package Update

- change/react-native-windows-e043a173-5e1e-43a9-848f-294995f0009a.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
- vnext/Shared/JSI/ChakraRuntime.cpp
- vnext/Shared/JSI/ChakraRuntime.h
The PR fixes the following issues:
- Failing new JSI test for the error handling - fix in Chakra JSI and ABI JSI implementations
- Managed code generation tests that required update to WinRT package versions - thank you @dannyvv for the help with it!
> Fix Microsoft.ReactNative unit tests

- package.json
- packages/@react-native/tester/package.json
- yarn.lock
I was selective the last time #7885 and set each dependency individually, but the remaining ones are now also hitting CG.
> Further ws updates to pass CG

- package.json
- packages/@react-native/tester/package.json
- yarn.lock
This PR backports #8007 to 0.65.
> [0.65] Further ws updates to pass CG

- change/react-native-windows-8d2272f9-2d73-4871-a7f4-ced1c2c6f30b.json
- vnext/Shared/Threading/BatchingQueueThread.cpp
- vnext/Shared/Threading/BatchingQueueThread.h
> Intermittent deadlock when reloading multiple times rapidly

- yarn.lock
Reverts microsoft/react-native-windows#7948
There is an issue with beachball that I still need to investigate. Holding off on upgrading for now...
> Revert "📦 Bump beachball from 2.4.0 to 2.6.1"

- package.json
- packages/@react-native/repo-config/package.json
- packages/@react-native/tester/package.json
- yarn.lock
This PR backports #8007 to 0.64.
> [0.64] Further ws updates to pass CG

- change/react-native-windows-579009de-3c14-4ece-ae61-ea5f5f8aef5a.json
- vnext/Directory.Build.props
- vnext/PropertySheets/Autolink.props
> Fix msbuild as more cases of *Undefined* are popping up

- change/react-native-windows-e515567c-07b2-4a7f-ba29-966aa5512168.json
- vnext/Directory.Build.props
Mix of Backport of #8055 and forward port of #7918
> [0.63] Fix msbuild as more cases of *Undefined* are popping up

- packages/playground/windows/playground-win32/Application.manifest
> make playground win32 use comctl v6

- .ado/templates/publish-build-artifacts-for-nuget.yml
> Fix parallel flag in pipelines yaml

- change/react-native-windows-2021-06-21-19-27-18-mmap-catchjsiexc-0.63.json
- change/react-native-windows-63ea3a71-e181-4a1e-a183-141818f55403.json
- vnext/Shared/BaseScriptStoreImpl.cpp
> [0.63] Have script store return nullptr on facebook::jsi::JSINativeException

- change/react-native-windows-095b7890-3b57-4d96-b136-df628a94aadd.json
- change/react-native-windows-63ea3a71-e181-4a1e-a183-141818f55403.json
- vnext/Shared/BaseScriptStoreImpl.cpp
> [0.64] Have script store return nullptr on facebook::jsi::JSINativeException

- change/react-native-windows-2c413a21-105e-4d75-881d-50912cd24ace.json
- change/react-native-windows-63ea3a71-e181-4a1e-a183-141818f55403.json
- vnext/Shared/BaseScriptStoreImpl.cpp
> [0.65] Have script store return nullptr on facebook::jsi::JSINativeException

- .ado/publish.yml
- change/jest-environment-winappdriver-5494a7a8-d87b-443b-b3ec-4f6da8751e5a.json
- change/node-rnw-rpc-440ea60e-b70d-45a8-a582-ffca5545b622.json
- change/react-native-windows-59917df8-86a0-4d7b-904b-b8a138b7d92d.json
- change/react-native-windows-ddd0873a-3e92-4489-8bf4-d6e41276bfd4.json
- packages/@react-native-windows/tester/CHANGELOG.json
- packages/@react-native-windows/tester/CHANGELOG.md
- packages/@react-native-windows/tester/package.json
- packages/e2e-test-app/CHANGELOG.json
- packages/e2e-test-app/CHANGELOG.md
- packages/e2e-test-app/package.json
- packages/integration-test-app/CHANGELOG.json
- packages/integration-test-app/CHANGELOG.md
- packages/integration-test-app/package.json
- packages/jest-environment-winappdriver/CHANGELOG.json
- packages/jest-environment-winappdriver/CHANGELOG.md
- packages/jest-environment-winappdriver/package.json
- packages/node-rnw-rpc/CHANGELOG.json
- packages/node-rnw-rpc/CHANGELOG.md
- packages/node-rnw-rpc/package.json
- packages/playground/CHANGELOG.json
- packages/playground/CHANGELOG.md
- packages/playground/package.json
- packages/sample-apps/CHANGELOG.json
- packages/sample-apps/CHANGELOG.md
- packages/sample-apps/package.json
- vnext/CHANGELOG.json
- vnext/CHANGELOG.md
- vnext/package.json
> Fix publish for Reunion

- change/react-native-windows-a48eb1a2-d8f1-4896-9025-0d370d9ded5f.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.config
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
> V8 Package Version Update

- change/react-native-windows-e8bc1569-ee5f-4959-9d6c-919be9388b49.json
- vnext/Microsoft.ReactNative.ProjectReunion/nuget/Microsoft.ReactNative.ProjectReunion.local.nuspec
- vnext/Microsoft.ReactNative.ProjectReunion/nuget/nuget_pack.cmd
> Local reunion nuget

- change/@office-iss-react-native-win32-c8620725-c50c-4b3b-9033-09bfcdc6607b.json
- packages/@office-iss/react-native-win32/package.json
> Bump rex-win32 to latest

- change/@office-iss-react-native-win32-85ebdd63-c97d-4582-86d4-dfa7b7ab00c3.json
- change/react-native-windows-616acf0c-8693-442b-aa4f-edc2553ed716.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Lists/__tests__/VirtualizedList-test.js
- packages/@office-iss/react-native-win32/src/Libraries/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap
- vnext/overrides.json
- vnext/src/Libraries/Lists/__tests__/VirtualizedList-test.js
- vnext/src/Libraries/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap
This merges in the changes from https://github.com/facebook/react-native/pull/31401 into our repo, since they have not been merged upstream yet.
These files can be set to be immutable copies of upstream code again once the changes are merged upstream.
> Add new VirtualizedList Tests from RN Core PR

- change/react-native-windows-e156dd93-0557-4836-a384-edb29ecac96e.json
- vnext/Microsoft.ReactNative/ReactRootView.cpp
Adds a progress ring, updates font/colors
> Update "Loading bundle" UI

- change/react-native-windows-de1752b0-dbd2-4922-a3f9-5d34d99c5e26.json
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
- vnext/Microsoft.ReactNative/Modules/AlertModule.h
> [0.65] Allow multiple calls to alert 

- change/react-native-windows-f6515af1-8691-48f1-899b-558df1fea435.json
- vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
- vnext/Microsoft.ReactNative/Modules/AlertModule.h
> [0.64] Allow multiple calls to alert

- change/react-native-windows-b7db929b-8aa9-43a8-9770-c46a8a6ad8cb.json
- vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
> [0.65] fix exceptions / bad condition in DisconnectFromView

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/variables/vs2019.yml
> Enable interactive tests on more powerfull agents

- .ado/jobs/universal.yml
> Use better pool for Universal Tests

- yarn.lock
Reverts microsoft/react-native-windows#8265
> Revert "📦 Bump beachball from 2.4.0 to 2.6.3"

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/jobs/universal.yml
- .ado/templates/prep-and-pack-nuget.yml
- .ado/variables/vs2019.yml
- change/react-native-windows-cc6b9293-23e0-4735-b163-bc6d05190dd1.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
- vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
> Move from windevpool to rnw-pool for universal and medium pool now suports interactive

- package.json
- yarn.lock
Waiting on bugs to be resolved, and do not want dependabot to prompt to update until they are.
> Park Beachball at 2.4.0

- change/react-native-windows-1d46b7ec-b5d7-48a6-8d89-3fcb84bb0ece.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
> Suppress warnings of unused variables in FaceBook code

- .ado/jobs/project-reunion.yml
- .ado/publish.yml
> Disable warnAsError for projectReunion in publish as well

- change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json
- vnext/Shared/Executors/WebSocketJSExecutor.cpp
- vnext/Shared/Executors/WebSocketJSExecutor.h
Port #8344 to 0.65.
Fixes #8325
> [0.65] Fix issue using react-native-debugger with react-native-windows (#8344)

- change/react-native-windows-bab3d697-7bb6-4b12-8af1-a9c0bfa1517e.json
- vnext/Microsoft.ReactNative.Cxx/JSValueXaml.h
> Add some jsvalue reader helpers for more xaml types

- change/@react-native-windows-codegen-02f90f2b-4769-435b-b35c-f09ec0b1a8d7.json
- change/react-native-windows-08b90f74-4260-454b-bf87-f2eccc345bef.json
- packages/@react-native-windows/codegen/src/Cli.ts
- vnext/just-task.js
> Do not write codegen files if the contents have not changed, as this breaks incremental builds

- change/react-native-windows-8288a621-ac24-4906-b19c-7d66308c0b23.json
- vnext/Microsoft.ReactNative/QuirkSettings.cpp
- vnext/Microsoft.ReactNative/QuirkSettings.h
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/Microsoft.ReactNative/ReactRootView.cpp
Feedback from @asklar on #8365.
> Rename API for changing BackHandler behavior

- change/react-native-windows-c8f0f74c-1b7f-4844-9573-de482ae55063.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
- vnext/Mso/src/eventWaitHandle/eventWaitHandleImpl_win.cpp
Fixes up a few issues with headers that cause clang builds to fail.
> Fixes various issues related to clang compile

- change/@office-iss-react-native-win32-f3b2f8f5-ff18-4ba8-a2f1-6cf7c10bf851.json
- change/@react-native-windows-cli-5fb3ab9d-1622-4a58-9d1c-c77820aaf6c7.json
- change/@react-native-windows-find-repo-root-0d5f7f32-7736-4770-9a3f-bebc420f23e9.json
- change/@react-native-windows-package-utils-bbf72786-6ac7-43fa-b7f1-0f84c1f489ca.json
- change/@react-native-windows-telemetry-05c4f5f7-25fb-460b-8fec-d20d84d4cc6b.json
- change/react-native-windows-3a3312f5-9c39-43ba-b54b-39fc44f45b36.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- packages/react-native-win32/package.json
- vnext/package.json
> Promote 0.64 from latest to legacy

- package.json
- yarn.lock
> Bump xmldom and tar for Component Governance

- .ado/publish.yml
> Move publish pipeline to private 1ES Agent pools

- .ado/publish.yml
> [0.64] Update publish pipeline to use hosted agents

- .ado/publish.yml
> [0.65] Update publish pipeline to use hosted agents

- change/react-native-windows-1a3ee341-b9ff-4dc7-b456-2ca73d935491.json
- vnext/.editorconfig
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.config
- vnext/Shared/DevSettings.h
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
- vnext/Shared/OInstance.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
> [0.65] Consume Node-Api V8 JSI Runtime

- packages/playground/Samples/accessible.tsx
**_Why_**
Upgrade contents of accessible.tsx sample to contain AccessibilityInfo APIs' setAccessibilityFocus and announceForAccessibility.
> Upgrade accessible.tsx Contents

- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityInfoExample.js
**_What_**
Upgrade AccessibilityInfo page in RNTester to include example of setAccessibilityFocus API. Update announceForAccessibility example.
> Upgrade AccessibilityInfo Examples in RNTester

- change/react-native-windows-3a67ace6-bef6-4d76-b8a7-36d5c51604db.json
- vnext/Folly/Folly.vcxproj
> [0.65] Fix race condition when building customer projects

- change/react-native-windows-dc161fbd-a211-4a9a-9fae-a6e9428ee13b.json
- vnext/Folly/Folly.vcxproj
> [0.66] Fix race condition when building customer projects

- change/@rnw-scripts-promote-release-b733b042-b3f6-4301-b418-3bdeeff9d7f1.json
- packages/@rnw-scripts/promote-release/src/promoteRelease.ts
> Create change files against main branch when cutting preview

- change/react-native-windows-7a05383a-8c03-4a46-a949-0b615e1ff5b5.json
- vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
- Added announce when accessibilityState changes
- Tested locally using Narrator
- Resolves https://github.com/microsoft/react-native-windows/issues/8491.
> Announce when accessibilityState Changes.

- change/react-native-windows-9381161a-95c4-4408-bdc1-d49f11d246be.json
- packages/e2e-test-app/metro.config.js
- packages/integration-test-app/metro.config.js
- packages/playground/metro.config.js
- packages/sample-apps/metro.config.js
- vnext/template/metro.config.js
- vnext/template/metro.devMode.config.js
> Fix EBUSY race conditions between metro bundler and msbuild

- change/jest-environment-winappdriver-5d33e3fd-3415-43dc-90a8-e27ef375c6c6.json
- change/jest-environment-winappdriver-6975ecb3-44a8-41c7-923d-4a8960cbe67f.json
- change/node-rnw-rpc-be74ebeb-f50e-4c02-9205-471b71a2124b.json
These packages have all been removed/renamed. Remove the changefiles for them, which will otherwise stick around without a use.
> Remove Stale changefiles

- change/react-native-windows-6217c8e9-598f-4790-97a6-061731aa53ad.json
- packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
- packages/integration-test-app/windows/integrationtest/packages.config
- packages/playground/packages.config
- packages/playground/windows/playground-win32/packages.config
- packages/playground/windows/playground/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
`git cherry-pick f908c461b` .. 'f908c461b` is already merged to main branch.
> Bump hermes to v0.9

- change/@office-iss-react-native-win32-5003eafb-93b1-4736-88d7-a0e9f1e8e58e.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
I will backport this to .65/.64/.63
> [0.65] Adding Accessibility Prop accessibilityItemType on ViewWin32

- change/react-native-windows-fd27c38b-c51f-401d-8da7-5cd45d56730b.json
- vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
- vnext/src/Libraries/Components/Flyout/FlyoutProps.ts
Adds option to configure `FlyoutBase::ShowMode` to `FlyoutViewManager`.
Co-authored-by: Mykola Lando <lando.koljaka@gmail.com>
> Adds showMode prop to FlyoutViewManager

- change/@office-iss-react-native-win32-4fd27bb9-3004-4b9a-8a87-a52c34939d5a.json
- change/react-native-windows-f40c6052-dede-4f5c-8e57-bb43903e5e6c.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/RedBox.h
- vnext/Microsoft.ReactNative/RedBoxHandler.cpp
- vnext/Shared/Threading/MessageDispatchQueue.cpp
- vnext/Shared/Threading/MessageDispatchQueue.h
> Allow injection of custom UI thread

- change/@office-iss-react-native-win32-419d2688-29c4-4ddb-b200-adb30a8bd823.json
- change/@react-native-windows-automation-channel-c819e994-7759-4409-8866-f5a66c423535.json
- change/@react-native-windows-virtualized-list-decfd30b-da1b-4397-858c-cd743bcdae44.json
- change/react-native-windows-98ae5140-34fb-451c-a6fb-874c1a205fb8.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native-windows/virtualized-list/overrides.json
- packages/@react-native-windows/virtualized-list/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/a8ac5ea32...d40cb0e1b
Nothing interesting in this batch.
> Integrate RN nightly build 9/9.

- change/react-native-windows-1ec9d3b9-8e14-45d8-a311-d1f74ae3a7fe.json
- change/react-native-windows-8061c4c0-22d1-4a30-9f8f-8f35cb50b230.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
- vnext/Shared/Shared.vcxitems
> [0.66] Migrate NodeApiJsiRuntime from V8-JSI

- change/react-native-windows-66f1ce15-8452-4057-ba04-5cef036f0545.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
- vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
- vnext/Shared/Shared.vcxitems
> [0.65] Migrate NapiJsiRuntime from V8-JSI

- change/react-native-windows-dc0f8218-b16e-4473-a064-8a553c3c0d57.json
- vnext/JSI/Desktop/JSI.Desktop.vcxproj
- vnext/JSI/Shared/NapiJsiV8RuntimeHolder.cpp
- vnext/JSI/Shared/NapiJsiV8RuntimeHolder.h
- vnext/JSI/Universal/JSI.Universal.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/Shared.vcxitems
> [0.64] Migrate NapiJsiRuntime from V8-JSI

- change/react-native-windows-2021-09-20-19-03-24-napi-jsrit-63.json
- vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
- vnext/JSI/Desktop/JSI.Desktop.vcxproj
- vnext/JSI/Shared/NapiJsiV8RuntimeHolder.cpp
- vnext/JSI/Shared/NapiJsiV8RuntimeHolder.h
- vnext/JSI/Universal/JSI.Universal.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
> [0.63] Migrate NapiJsiRuntime from V8-JSI

- change/@office-iss-react-native-win32-9279048f-7928-49c6-ae78-ae5378e1537a.json
- change/react-native-windows-091153ee-a74e-46a6-8d02-9ad77cdb8a56.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/RedBox.h
- vnext/Microsoft.ReactNative/RedBoxHandler.cpp
- vnext/Shared/Threading/MessageDispatchQueue.cpp
- vnext/Shared/Threading/MessageDispatchQueue.h
> [0.65] Allow injection of custom UI thread

- change/@office-iss-react-native-win32-a461254c-d2b9-4893-ae69-57fbc558eb4f.json
- change/@react-native-windows-automation-channel-d21fd796-8af5-49c4-b84d-4ca17909a0cf.json
- change/@react-native-windows-virtualized-list-d03d37ad-c0b3-419f-9a9c-f6979f844151.json
- change/react-native-windows-8cb024a9-5330-4bcc-8e60-274c3592a9f9.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native-windows/virtualized-list/overrides.json
- packages/@react-native-windows/virtualized-list/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/js/examples/ActionSheetIOS/ActionSheetIOSExample.js
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/Samples/text.tsx
- packages/playground/package.json
- packages/playground/windows/playground/packages.config
- packages/sample-apps/package.json
- vnext/codegen/NativeActionSheetManagerSpec.g.h
- vnext/overrides.json
- vnext/package.json
- vnext/src/Libraries/Components/Button.windows.js
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/fa768df2a...d3c7e2018
Changes to Note:
- accessibilityHint now passed through Button: https://github.com/facebook/react-native/commit/be5372801a3ac3ae0f1df76c33f8b5f96ea68828
- Can now specify metro server programmatically: https://github.com/facebook/react-native/commit/e2b5b6504cb4dee8f2ec67f1d3a410801e1ca09a
> Integrate RN Nightly Build 9/23

- change/@office-iss-react-native-win32-c80359d6-c738-46e1-b957-d03af3a7c010.json
- change/react-native-windows-a1fb1831-9868-4e91-ac12-d215ad6b98c2.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
- vnext/Microsoft.ReactNative/IReactDispatcher.h
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
- vnext/Microsoft.ReactNative/ReactCoreInjection.h
- vnext/Microsoft.ReactNative/ReactCoreInjection.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
- vnext/Microsoft.ReactNative/RedBox.cpp
- vnext/Microsoft.ReactNative/RedBox.h
- vnext/Microsoft.ReactNative/RedBoxHandler.cpp
- vnext/Shared/Threading/MessageDispatchQueue.cpp
- vnext/Shared/Threading/MessageDispatchQueue.h
> [0.66] Allow injection of custom UI thread

- change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json
- vnext/Shared/Executors/WebSocketJSExecutor.cpp
- vnext/Shared/Executors/WebSocketJSExecutor.h
> [0.64] Fix issue using react-native-debugger with react-native-windows

- change/react-native-windows-972337b2-df10-4a11-a15e-0421f523944e.json
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
Feedback from previous change in TestReactNativeHostHolder : https://github.com/microsoft/react-native-windows/pull/8719#discussion_r717821628_
> Cleanup of TestReactNativeHostHolder API

- change/react-native-windows-aa558e27-c76b-4b78-a3d5-e04cdd114b77.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
- vnext/ReactCommon.UnitTests/packages.config
- Upgrade ReactNative.V8Jsi.Windows to 0.65.5
- Change files
> Upgrade V8 to version 9.5

- .github/CODEOWNERS
> Enforce 0.66 Triage Requirement

- change/react-native-windows-2021-09-28-18-59-44-v8-9.5-63.json
- vnext/Desktop.DLL/packages.config
- vnext/Microsoft.ReactNative.ComponentTests/packages.config
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/React.Cpp.props
Backport of #8735
- Upgrade ReactNative.V8Jsi.Windows to 0.63.17
- Change files
> [0.63] Upgrade V8 to version 9.5

- change/react-native-windows-94332748-eadb-40c5-8001-3923131cfc96.json
- vnext/Microsoft.ReactNative/IReactDispatcher.cpp
This has been pretty useful for us to get details out of minidumps. This is just a draft, perhaps there's a better way to get the error details.
> Logs exception from IReactDispatcher callback

- change/@react-native-windows-cli-7dc180ee-6e42-4d53-9929-daf1622c8bb2.json
- packages/@react-native-windows/cli/src/healthChecks.ts
- packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
- packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
> Use full path to powershell

- change/react-native-platform-override-2ceb8de7-5beb-42a6-a02a-26caa4ec3c19.json
- packages/react-native-platform-override/src/GitReactFileRepository.ts
> Teach integration tooling about new nightly pattern

- change/@office-iss-react-native-win32-5941e74c-2b39-4f46-bac8-8e316faa7af0.json
- change/@react-native-windows-automation-channel-c2c29940-ed68-4e57-98d2-6767a270b007.json
- change/@react-native-windows-virtualized-list-45a88752-9559-4c8a-9dcf-0298db46dee4.json
- change/react-native-windows-819f83c2-95f1-4abd-b594-e9df1a39446a.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native-windows/virtualized-list/overrides.json
- packages/@react-native-windows/virtualized-list/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- vnext/src/Libraries/Components/View/ReactNativeViewViewConfig.windows.js
- vnext/src/Libraries/Text/Text.windows.js
- vnext/src/babel-plugin-codegen/GenerateViewConfigJs.js
- yarn.lock
Commits: https://github.com/facebook/react-native/compare/e1b698c5f...eccbf9b5c
- https://github.com/facebook/react-native/commit/8fcc2fa31ab2763e218b489fc59d69fb7050b69e#diff-02e1c05c8af62a0d1e4e0be198579201e1630a993929c198eb4416a9aaa04ece replaced our forked version
> Integrate 10/21 Nightly RN Build

- .ado/jobs/playground.yml
Clean up conditionals to reduce duplication of the playground yaml.
> Cleanup conditionals of playground yaml

- .ado/publish.yml
Missed replacing a "project" with "solution" in publish pipeline of recent changes.
> Fix building desktop in publish

- .ado/jobs/integration-test.yml
> Reenable Integration Test App X64WebDebug

- .ado/jobs/cli-init.yml
> Temporarily use medium pool for low-resource jobs

- .ado/jobs/cli-init.yml
> Add more NuGet validation to CI pipeline

- .ado/publish.yml
> fix desktop publish typo

- change/@office-iss-react-native-win32-c738962f-151a-4e5e-a805-db5e73f40dda.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
> [0.67] Add `enableFocusRing` to RNWin32

- change/@office-iss-react-native-win32-c738962f-151a-4e5e-a805-db5e73f40dda.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
> [0.66] Add `enableFocusRing` to RNWin32

- change/@office-iss-react-native-win32-c738962f-151a-4e5e-a805-db5e73f40dda.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
> [0.65] Add `enableFocusRing` to RNWin32

- change/react-native-windows-9b2706c2-7d16-4f19-ab52-e0a686081711.json
- packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/integrationtest/packages.config
- packages/playground/windows/playground-win32/packages.config
- packages/playground/windows/playground/packages.config
- packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
- packages/sample-apps/windows/SampleAppCS/packages.lock.json
- vnext/Desktop/packages.config
- vnext/Microsoft.ReactNative/packages.config
- vnext/PropertySheets/JSEngine.props
> Bumping Hermes to v0.10

- .ado/templates/react-native-init.yml
This reverts commit 7e947034a41171619b331e665558b5a418fa4040.
Fixes #9261
> Reenable Tests for `react-native doctor`

- vnext/CHANGELOG.json
- vnext/CHANGELOG.md
Fix changelog files. Somehow an invalid json file ended up in the changes folder. This resulted in a duplicate change description and an invalid url `[Object object] (user@microsoft.com)` which is failing the CI at the moment.
The json file was also missing the commit id.
This change adds the proper information back.
> [0.67] Fix CI: update invalid changelog file.

- change/@react-native-windows-codegen-b38d03b4-1d88-4bdb-bccf-60fd1dce0bee.json
- change/@react-native-windows/fs-a94faf16-47da-4af9-9665-41b8a756267f.json
- packages/@react-native-windows/codegen/Document.md
`packages\@react-native-windows\codegen\Document.md`
> Add document for Turbo Module codegen

- change/react-native-windows-5af3db60-0ec1-4a05-805e-0b0193498c7a.json
- change/react-native-windows-f9d6ddce-6909-439b-b4b7-0e8a541240c4.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
> [0.64] Replace __APPLE__ with __clang__ where applicable

- change/react-native-windows-50600557-a3cd-481c-8991-01a803894add.json
- change/react-native-windows-f9d6ddce-6909-439b-b4b7-0e8a541240c4.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
> [0.66] Replace __APPLE__ with __clang__ where applicable (#9461)

- change/react-native-windows-5742b31c-adda-4f16-b922-7a4b5e938474.json
- change/react-native-windows-f9d6ddce-6909-439b-b4b7-0e8a541240c4.json
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
> [0.67] Replace __APPLE__ with __clang__ where applicable (#9461)

- .ado/publish.yml
- .ado/templates/publish-build-artifacts.yml
- .vscode/settings.json
Add SBom Manifest Generation
This is a compliance requirement
Changed the publish pipeline definitions to cover all shipped bits.
N/A: Will have to see if publish pipeline passes with this change..
> Add SBom Manifest Generation

- change/react-native-windows-cc5dfce1-10f6-42ee-987f-5e563817b6bd.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
> [0.67] Use temporary folder to store V8 JS bytecode

- change/react-native-windows-0a5c7c4e-e5d0-4577-91f3-173b5feb3003.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
> [0.66] Use temporary folder to store V8 JS bytecode

- .ado/jobs/macos-tests.yml
Add variable so mac image applies compliance tasks.
> Make mac compliant

- .ado/jobs/linting.yml
Update pipelines to ensure we run cred scan
Needed for compliance
> Enable credscan

- .ado/publish.yml
Add credscan to publish pipeline as well
Compliance
Enabled CredScan on PR pipeline first on previous to ensure we were clean.
> Add CredScan to release

- change/react-native-windows-dd1c0040-3af3-4c0c-9d53-cf1eb31930a0.json
- vnext/Microsoft.ReactNative/IViewManager.idl
- Documentation Update
Add API documentation for new interface. Adjust method description.
> Update OnDropViewInstance API Doc

- change/react-native-windows-46c4c194-e6d8-4663-8da2-3ab232b384a6.json
- vnext/Microsoft.ReactNative/IViewManager.idl
- Documentation
Backport #9627 to 0.68
Add API documentation for new interface. Adjust method description.
> [0.68] Update OnDropViewInstance API Doc

- change/react-native-windows-34090dc6-d476-438d-afee-8299ac07d43d.json
- change/react-native-windows-fe9965b7-8e26-4928-b2d8-7453a5738923.json
- vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
- vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
> [0.68] Set ResolveNuGetPackages in external props

- change/react-native-windows-2144dfb3-3e5a-460b-9527-f29e451addb4.json
- vnext/PropertySheets/PackageVersionDefinitions.props
> [0.68] Enable version checks in IDL files

- change/@rnw-scripts-integrate-rn-779c47ee-e8f0-4e4c-8bf2-4f53a2f933dc.json
- packages/@rnw-scripts/integrate-rn/package.json
- packages/@rnw-scripts/integrate-rn/src/test/logger.test.ts
- packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts
- packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
> Fixup peerDependencies when going from preview to latest

- change/@office-iss-react-native-win32-a85261a9-39b9-450e-a0a4-dec422d4459a.json
- change/@react-native-windows-cli-0cc06e51-8792-40de-a3e1-a45ce7d7028b.json
- change/@react-native-windows-codegen-58bbaa6e-ea03-466e-b376-c668b7906bbd.json
- change/@react-native-windows-find-repo-root-07bff48a-d7d4-49bd-ada5-bbc87d763143.json
- change/@react-native-windows-package-utils-4a9efa2d-a8af-42cc-bef0-e49b066d043b.json
- change/@react-native-windows-telemetry-a7a57af8-60e1-4c8a-9f61-46a3f9c8878c.json
- change/@react-native-windows-virtualized-list-8f42adc3-eb04-4a73-9280-bbf744110eb9.json
- change/react-native-windows-e13a628c-5365-49bf-b5fe-0d7cae56a377.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- packages/@react-native-windows/virtualized-list/package.json
- vnext/package.json
> Move 0.67 to Legacy

- change/@office-iss-react-native-win32-0727ff8a-f99d-4323-98ce-0464885b233c.json
- change/@react-native-windows-virtualized-list-34ce311f-c75a-4194-870c-a7fb122d0221.json
- change/react-native-windows-29aa5766-238b-4658-8a37-8aa286b2a46a.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native-windows/virtualized-list/overrides.json
- packages/@react-native-windows/virtualized-list/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
- Integration
Integrate 0.68.0.
> Integrate 0.68.0 Stable

- change/@office-iss-react-native-win32-0727ff8a-f99d-4323-98ce-0464885b233c.json
- change/@office-iss-react-native-win32-dcb5e4a1-76af-46dc-ac00-6177d51be1c1.json
- change/@react-native-windows-cli-710a1e99-9d44-4bce-b886-a14b76fe34a6.json
- change/@react-native-windows-codegen-8f821766-2cd1-49a3-9673-ceaccf231f11.json
- change/@react-native-windows-find-repo-root-fef6284d-f274-4e62-95ec-30e153e7c30b.json
- change/@react-native-windows-fs-0a134925-f2c8-4d1a-801a-9b842abb8e11.json
- change/@react-native-windows-package-utils-54653f88-3eef-40c9-9cf6-be0e17cf16c2.json
- change/@react-native-windows-telemetry-32dce4bf-1cdf-4dc9-8df8-22d194971b32.json
- change/@react-native-windows-virtualized-list-34ce311f-c75a-4194-870c-a7fb122d0221.json
- change/@react-native-windows-virtualized-list-ffbd4ed0-4438-407d-aaf6-bb9e8d0d2f6b.json
- change/node-rnw-rpc-6fae19ab-7d3e-488e-83c6-cb979474aebb.json
- change/react-native-windows-29aa5766-238b-4658-8a37-8aa286b2a46a.json
- change/react-native-windows-9361f0a8-1232-49d4-9748-4287a91db698.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- packages/@react-native-windows/virtualized-list/package.json
- vnext/package.json
> Promote 0.68 to Latest

- change/react-native-windows-36fd6f7c-9773-4ab0-8927-b164153478dd.json
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/cdebug.cpp
- vnext/include/Shared/cdebug.h
Simplify cdebug, removes an unnecessary dynamic initializer
> [Perf] simplify cdebug, removes an unnecessary dynamic initializer

- change/react-native-windows-73626f69-9b5c-4bcc-bf4a-2bffdfab80b6.json
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp
- vnext/Shared/OInstance.cpp
> [0.68] Enable loading the bundle from an embedded resource via resource://moduleName/resourceId

- change/react-native-windows-502521d2-2bf0-4423-8d9c-0a79dbfa01b3.json
- vnext/Chakra/ChakraValue.cpp
Fixes a CodeQL bug https://task.ms/39437178
> Terminate if a Chakra JS object cannot be created

- change/react-native-windows-91963646-c015-49a5-87cc-d174fa06e010.json
- vnext/Microsoft.ReactNative/IReactDispatcher.idl
This is a follow up change requested in https://github.com/microsoft/react-native-windows/pull/9900
This change updates comments for better readability.
N/A
N/A
N/A
> Update comments in IReactDispatcher.idl

- change/react-native-windows-b0106b4b-bdcf-4369-a0fc-060d702c7342.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
> [0.69] Expose LoadingState on ReactContext

- change/react-native-windows-48cb9d1d-48bd-4997-b425-b576e6f72e2f.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
> [0.68] Expose LoadingState on ReactContext

- change/react-native-windows-562754ad-2fa6-471f-b04d-5cabf2739c81.json
- vnext/Chakra/ChakraHelpers.cpp
- vnext/Chakra/ChakraPlatform.cpp
- vnext/Chakra/ChakraValue.h
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
- vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Utils/Helpers.cpp
- vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
- vnext/Shared/JSI/ChakraRuntime.cpp
This PR resolves various (internally tracked) bugs filed by CodeQL static code analysis:
* Resolves [39437135](https://microsoft.visualstudio.com/OS/_workitems/edit/39437135)
* Resolves [39437136](https://microsoft.visualstudio.com/OS/_workitems/edit/39437136)
* Resolves [39437143](https://microsoft.visualstudio.com/OS/_workitems/edit/39437143)
* Resolves [39437145](https://microsoft.visualstudio.com/OS/_workitems/edit/39437145)
* Resolves [39437152](https://microsoft.visualstudio.com/OS/_workitems/edit/39437152)
* Resolves [39437155](https://microsoft.visualstudio.com/OS/_workitems/edit/39437155)
* Resolves [39437164](https://microsoft.visualstudio.com/OS/_workitems/edit/39437164)
* Resolves [39437165](https://microsoft.visualstudio.com/OS/_workitems/edit/39437165)
* Resolves …
> Resolving CodeQL warnings 5/25/22

- change/react-native-windows-48cb9d1d-48bd-4997-b425-b576e6f72e2f.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
- vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
- vnext/Microsoft.ReactNative/IReactContext.cpp
- vnext/Microsoft.ReactNative/IReactContext.h
- vnext/Microsoft.ReactNative/IReactContext.idl
> [0.66] Expose LoadingState on ReactContext

- .lgtm.yml
Adds a new `.lgtm.yml CodeQL` configuration file.
CodeQL tries to classify code that it shouldn't care about (test code, external code, etc.) but it doesn't do a good job in our repo, which causes a bunch of unnecessary CodeQL alerts.
Related: #9960
This PR adds a CodeQL configuration file which properly classifies some (mostly test) file paths. This should reduce the noise in the alerts.
> Add CodeQL .lgtm.yml configuration file

- yarn.lock
> [0.66] Resolving CG alerts 6/1/2022

- package.json
- yarn.lock
> [0.64] Resolving CG alerts 6/1/2022

- yarn.lock
> [0.65] Resolving CG alerts 6/1/2022

- change/react-native-windows-afc24edc-bdf4-45c3-8166-f645792f51ca.json
- packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
- packages/playground/windows/playground-win32/Playground-win32.vcxproj
- packages/playground/windows/playground-win32/packages.config
- packages/playground/windows/playground/packages.config
- packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
- vnext/PropertySheets/JSEngine.props
- vnext/Shared/InspectorPackagerConnection.cpp
- vnext/Shared/InspectorPackagerConnection.h
New package version fixes a few Hermes bugs (see hermes-windows PR for details: https://github.com/microsoft/hermes-windows/pull/103)
Bump Hermes NuGet package version
Minimal manual testing (Playground boots).
> Bump Hermes package version

- change/@office-iss-react-native-win32-f5f90702-fc69-43a3-b513-f67034afa4fd.json
- change/@react-native-windows-virtualized-list-627af75f-174d-49ca-a6fb-4511f8c52225.json
- change/react-native-windows-04a07b37-8b42-42d7-a2a2-d5ccc0615ab7.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native-windows/virtualized-list/overrides.json
- packages/@react-native-windows/virtualized-list/package.json
- packages/@react-native/repo-config/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
- Integration
No changes of note.
> Integrate 0.69.0-rc.6

- change/react-native-windows-d0b46459-5370-47eb-9a2c-9c46738403cb.json
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/YGValue.h
- vnext/overrides.json
> [0.66] Fix ARM64 layout issues

- change/react-native-windows-a8df45ea-26f4-44f5-9b82-712c9aad497e.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Shared/OInstance.cpp
> [0.66] Enable Blob module with runtime option

- .gitignore
- change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
> [0.67] Fix ExecuteJsi on instance shutdown

- .gitignore
- change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
> [0.68] Fix ExecuteJsi on instance shutdown

- .gitignore
- change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
> [0.69] Fix ExecuteJsi on instance shutdown

- change/react-native-windows-03c56ba5-1de6-4f15-968b-e1e2afb78063.json
- change/react-native-windows-1653495d-e9db-497e-a6e2-bb5fbcc05317.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/OInstance.cpp
> [0.67] Enable Blob module with runtime option

- .gitignore
- change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
- vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
- vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
- vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
- vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
> [0.66] Fix ExecuteJsi on instance shutdown

- change/react-native-windows-9a673fa6-eb87-4922-97bd-f82452505453.json
- vnext/Microsoft.ReactNative/IReactContext.idl
- vnext/Microsoft.ReactNative/IViewManager.idl
- vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
- Documentation Update
Typos in API Docs
Backport #10190 to 0.69
> [0.69] Update API Docs

- change/react-native-windows-3d4bf4d5-6fad-4d59-bc5e-2387ce0fdef5.json
- package.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- yarn.lock
> [0.67] CG updates for 6/28/22

- change/react-native-windows-78674cf9-6396-441e-bf59-d5f0cd4f2aac.json
- package.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- yarn.lock
> [0.66] CG updates for 6/28/22

- change/react-native-windows-b239012b-a060-41d6-9c2b-88f52bfd7e41.json
- package.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- yarn.lock
> [0.65] CG updates for 6/28/22

- change/react-native-windows-3f168ded-c8d2-4ad9-89db-457a4ca04fa8.json
- package.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- yarn.lock
> [0.64] CG updates for 6/28/22

- change/react-native-windows-45866773-3818-4b68-b400-e7a0ece48718.json
- package.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- yarn.lock
> [0.68] CG updates for 6/28/22

- change/react-native-windows-a1c5b546-123a-467b-af09-b6e523f36db9.json
- vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- yarn.lock
> [0.69] CG updates for 6/28/22

- packages/@rnw-scripts/beachball-config/src/beachball.config.ts
Currently beachball only checks for the presence of change files, and validates the `type` fields, but not the `comment` string. Invalid comment values (such as non-strings, which sometimes happens) mean the change is skipped with a warning (potentially meaning the right version bump doesn't happen).
Even if the string is valid, we don't want comments that are empty or just whitespace.
This PR updates our beachball config to validate the comments in the change files. Comments must be a defined string that are not empty or whitespace.
Closes #10333
> Require beachball change files to have a valid comment string

- change/react-native-windows-2b9efe2b-f4fe-4ba0-aab6-3b25289be552.json
- vnext/Directory.Build.props
- vnext/Folly/cgmanifest.json
Updating Folly to align with RN core: https://github.com/facebook/react-native/commit/68f3a42fc7380051714253f43b42175de361f8bd
> Update Folly to v2021.07.22.0

- .ado/jobs/macos-tests.yml
- .unbroken_exclusions
> [0.70] Backport #10440 & #10444

- .ado/jobs/macos-tests.yml
- .unbroken_exclusions
> [0.69] Backport #10440 & #10444

- .ado/jobs/macos-tests.yml
- .unbroken_exclusions
> [0.68] Backport #10440 & #10444

- .ado/jobs/macos-tests.yml
- .unbroken_exclusions
> [0.67] Backport #10440 & #10444

- .ado/jobs/macos-tests.yml
- .unbroken_exclusions
> [0.66] Backport #10440 & #10444

- change/react-native-windows-cb076a1b-e4cb-40ad-a74d-f7b826107a3d.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/Threading/BatchingQueueThread.cpp
> [0.69] Allow batches to complete during load

- change/react-native-windows-ac0793f7-dae5-4086-850c-2ede09044870.json
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Port https://github.com/microsoft/react-native-windows/pull/10471 to 0.68
> [0.68] Fix crash creating InstanceSettings on Windows 8.1

- change/react-native-windows-ac0793f7-dae5-4086-850c-2ede09044870.json
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
> [0.70] Fix crash creating InstanceSettings on Windows 8.1

- change/react-native-windows-ac0793f7-dae5-4086-850c-2ede09044870.json
- vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Port https://github.com/microsoft/react-native-windows/pull/10471 to 0.69
> [0.69] Fix crash creating InstanceSettings on Windows 8.1

- change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
> [0.67] Fixes bug introduced by pointerEvents change

- change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Port https://github.com/microsoft/react-native-windows/pull/10498 to 0.68
> [0.68] Fixes bug introduced by pointerEvents change 

- change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Port https://github.com/microsoft/react-native-windows/pull/10498 to 0.69
> [0.69] Fixes bug introduced by pointerEvents change

- change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json
- change/@office-iss-react-native-win32-dfa02c3b-6bc4-4966-8eab-dec1bdaa3fc1.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
> [0.68] [RN Win32] Backport accessibility access key win32

- change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Port https://github.com/microsoft/react-native-windows/pull/10498 to 0.70
> [0.70] Fixes bug introduced by pointerEvents change

- change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json
- change/@office-iss-react-native-win32-b89a8ae7-e8bb-4ce4-ac95-b7ecf6ba88ca.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
> [0.70] [RN Win32] Backport accessibility access key win32

- change/react-native-windows-0ebecccb-b382-467f-9c94-9b2da2b97381.json
- change/react-native-windows-63ed688a-573c-4dc1-99de-f69d6f650838.json
- vnext/Scripts/OfficeReact.Win32.nuspec
- vnext/Shared/Networking/OriginPolicy.h
> [0.70] Export OriginPolicy.h to NuGet package

- change/react-native-windows-63ed688a-573c-4dc1-99de-f69d6f650838.json
- change/react-native-windows-79697891-81e0-4356-a57d-9bc688a37e8f.json
- vnext/Scripts/OfficeReact.Win32.nuspec
- vnext/Shared/Networking/OriginPolicy.h
> [0.69] Export OriginPolicy.h to NuGet package

- change/react-native-windows-63ed688a-573c-4dc1-99de-f69d6f650838.json
- change/react-native-windows-7c032593-da35-422c-8411-bd922871b137.json
- vnext/Scripts/OfficeReact.Win32.nuspec
- vnext/Shared/Networking/OriginPolicy.h
> [0.68] Export OriginPolicy.h to NuGet package

- change/react-native-windows-468f909f-2dc6-4f36-9aa3-12197f7559ad.json
- vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
- vnext/Microsoft.ReactNative/Base/CoreNativeModules.h
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
- vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Make appearance module use codegen spec file and be a turbomodule
> Move Appearance to TurboModule

- change/react-native-windows-a912b218-3e03-4b76-8b54-d9cd603a29c0.json
- change/react-native-windows-fe91be36-714d-421e-a49f-92e619873986.json
- vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/RedirectHttpFilter.cpp
- vnext/Shared/Shared.vcxitems.filters
> [0.70] Set User-Agent header in Origin Policy filter

- change/react-native-windows-a912b218-3e03-4b76-8b54-d9cd603a29c0.json
- change/react-native-windows-e9126ab9-769d-4af3-9c11-c3a5043e9237.json
- vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/RedirectHttpFilter.cpp
- vnext/Shared/Shared.vcxitems.filters
> [0.68] Set User-Agent header in Origin Policy filter

- change/react-native-windows-8769dfac-39b4-4cfc-88ae-91a5456390a2.json
- change/react-native-windows-b7b41b5d-bb81-4afb-9bad-df2adf65518c.json
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.68] Set Origin HTTP header during CORS

- change/react-native-windows-449be090-5a44-4889-ab07-0d5be2bd88c3.json
- change/react-native-windows-8769dfac-39b4-4cfc-88ae-91a5456390a2.json
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.70] Set Origin HTTP header during CORS

- change/react-native-windows-4090a69c-674e-42d3-a643-39ec206c7c00.json
- change/react-native-windows-8769dfac-39b4-4cfc-88ae-91a5456390a2.json
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.69] Set Origin HTTP header during CORS

- change/@react-native-windows-virtualized-list-ee65ac06-b7a0-4d3f-ab30-125692090e9d.json
- change/react-native-windows-7dddf547-aeee-49ee-8b09-ad91a21dbaec.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
- vnext/Directory.Build.props
- vnext/Folly/Folly.vcxproj
- vnext/Folly/Folly.vcxproj.filters
- vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
- vnext/Folly/TEMP_UntilFollyUpdate/lang/SafeAssert.h
- vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
> Update to folly 2022.11.07

- change/react-native-windows-45082565-4f32-499f-acd3-ecd7c71a43ae.json
- vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
0.71 brings in new support for `rowGap`, `columnGap` and `gap` flex properties.  This hooks up the new properties.
Verified the new gap test on the ViewExample test page in RNTester
> Implement rowGap, columnGap and gap flex properties

- change/react-native-windows-00b587ec-6a97-4334-b5eb-18d571ce94d8.json
- change/react-native-windows-77be59f2-bcaa-426d-9d27-b1b89d80207b.json
- vnext/Shared/Modules/HttpModule.cpp
- vnext/Shared/Networking/IHttpResource.h
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/Networking/WinRTHttpResource.h
> [0.71] Implement HTTP incremental updates

- change/react-native-windows-02bc19fb-606a-49b9-b555-145c15e79849.json
- change/react-native-windows-d6242db3-26c5-4dc5-a10d-c7440a682961.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.71] Test Access-Control-Request-Headers

- change/react-native-windows-02bc19fb-606a-49b9-b555-145c15e79849.json
- change/react-native-windows-52945ab1-3039-4dfd-944a-7dd398602d34.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
> [0.70] Test Access-Control-Request-Headers

- change/react-native-windows-129c1704-256e-40c9-9ba0-5e88391a0656.json
- change/react-native-windows-4559f97f-bb39-4fe8-a1a9-c3e950ae966e.json
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Backport of #10278
Backport of #11031
> [0.68] Fix compiler issue for older versions of C++/WinRT

- change/react-native-windows-b23dc862-597b-4f85-a0e1-d8972cd1d250.json
- vnext/src/Libraries/NativeComponent/BaseViewConfig.windows.js
> [0.71] Do not conditionally ignore event props (#11059)

- change/react-native-windows-4ee72dd6-75dd-4374-b814-1f3946a0e6d1.json
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
- vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
> [Image][0.71] Fix svg rendering

- change/react-native-windows-277cff43-6a02-4796-80c4-5d13ae258468.json
- vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ControlViewManager.h
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
- vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Fix bug in new Accessible/Focusable code to handle disabled switch case. Refactor control code to match refactor in View code for accessible/focusable adjustment. 
View Control 
** with pressable
|old focusable|old accessible|new focusable|new accessible|expected|actual|
|-|-|-|-|-|-|
|❌|✅|✅|✅|✅|✅|
|✅|❌|✅|✅|✅|✅|
|❌|❌|✅|✅|✅|✅|
|✅|✅|❌|✅|❌|❌|
|✅|❌|❌|✅|❌|❌|
|❌|❌|❌|✅|❌|❌|
|✅|✅|✅|❌|❌|❌|
|❌|✅|✅|❌|❌|❌|
|❌|❌|✅|❌|❌|❌|
|✅|✅|❌|❌|❌|❌|
|✅|❌|❌|❌|❌|❌|
|❌|✅|❌|❌|❌|❌|
**without pressable
|old focusable|old accessible|new focusable|new accessible|expected|actual|
|-|-|-|-|-|-|
|❌|✅|✅|✅|✅|✅|
|✅|❌|✅|✅|✅|✅|
|❌|❌|✅|✅|✅|✅|
|✅|✅|❌|✅|✅|✅|
|✅|❌|❌|✅|✅|✅|
|❌|❌|❌|✅|✅|✅|
|✅|✅|✅|❌|✅|✅|
|❌|✅|✅|❌|✅|✅|
|❌|❌|✅|❌|✅|✅|
|✅|✅|❌|❌|❌|❌| …
> Fix Control Bug Accessible/Focusable Adjustment Code

- change/react-native-windows-48ba39dc-ea15-4e83-b76e-80afc2f808ef.json
- change/react-native-windows-566e71d3-0d9f-403d-9817-c2c8f9e4cab7.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
> [0.71] Allow disabling static graph restore under VS

- change/react-native-windows-48ba39dc-ea15-4e83-b76e-80afc2f808ef.json
- change/react-native-windows-4c5246df-32eb-43c7-98bb-cb5f656b671c.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
> [0.70] Allow disabling static graph restore under VS

- change/react-native-windows-48ba39dc-ea15-4e83-b76e-80afc2f808ef.json
- change/react-native-windows-c6a14e9f-726b-48c7-b6a0-9962e8f8a8fa.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
> [0.69] Allow disabling static graph restore under VS

- change/react-native-windows-48ba39dc-ea15-4e83-b76e-80afc2f808ef.json
- change/react-native-windows-8103806d-4bb2-410b-8069-41763615cb43.json
- vnext/Directory.Build.props
- vnext/PropertySheets/NuGet.Cpp.props
> [0.68] Allow disabling static graph restore under VS

- change/react-native-windows-29c1ada7-831c-4f42-b009-09403fc246d4.json
- vnext/Shared/tracing/tracing.cpp
see [PR 11255](https://github.com/microsoft/react-native-windows/pull/11255)
> Backport ETW initialization fix to 0.68

- change/react-native-windows-29c1ada7-831c-4f42-b009-09403fc246d4.json
- vnext/Shared/tracing/tracing.cpp
see [PR 11255](https://github.com/microsoft/react-native-windows/pull/11255)
> Backport ETW initialization fix to 0.69

- change/react-native-windows-29c1ada7-831c-4f42-b009-09403fc246d4.json
- vnext/Shared/tracing/tracing.cpp
see [PR 11255](https://github.com/microsoft/react-native-windows/pull/11255)
> Backport ETW initialization fix to 0.71

- yarn.lock
> fix lock file

- yarn.lock
> [0.68] Component Governance Updates for 3/13/23

- yarn.lock
> [0.70] Component Governance Updates for 3/13/23

- yarn.lock
> [0.71] Component Governance Updates for 3/13/23

- change/react-native-windows-7f362cee-b1e5-48ae-80f4-893a406c40b3.json
- packages/e2e-test-app/package.json
- vnext/Microsoft.ReactNative/RedBox.cpp
- yarn.lock
> [0.71] Fix RedBox Dismiss

- change/@office-iss-react-native-win32-4e4c5d54-7364-4499-8466-1a18b13452f9.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> Minor TS type updates

- change/react-native-windows-1553bce1-d853-42d0-9bac-508954aba2ba.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Modules/BlobModule.h
> [0.71] Use Boost GUID generator (#11470)

- change/react-native-windows-c89d9e91-bbd2-4321-a828-dea393861a32.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Modules/BlobModule.h
> [0.70] Use Boost GUID generator (#11470)

- change/react-native-windows-d17db012-6372-4c12-9759-b7cb10528dc1.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Modules/BlobModule.h
> [0.69] Use Boost GUID generator (#11470)

- change/react-native-windows-11865dea-8398-4e1a-a61a-810a133391ee.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Modules/BlobModule.h
> [0.68] Use Boost GUID generator

- change/react-native-windows-785599c9-0d7d-4f39-a0d0-cc175e5c7b84.json
- vnext/Directory.Build.props
- vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
- vnext/Folly/TEMP_UntilFollyUpdate/hash/Hash.h
- vnext/Folly/cgmanifest.json
> Update folly to 2023.03.06.00

- change/@react-native-windows-cli-3fa82ba4-66aa-4ba2-8038-a1eb08ec5bd2.json
- change/react-native-windows-8263fffc-aa20-4e7e-873b-b503e49fd78c.json
- packages/@react-native-windows/cli/src/e2etest/healthChecks.test.ts
- packages/@react-native-windows/cli/src/healthCheckList.ts
- packages/@react-native-windows/cli/src/healthChecks.ts
- vnext/Scripts/rnw-dependencies.ps1
Port https://github.com/microsoft/react-native-windows/pull/11550 to 0.68
> [0.68] Avoid having to launch PowerShell for every react-native config query

- change/@react-native-windows-cli-d62d51ec-8edf-4361-bf8b-e25db14f66bf.json
- change/react-native-windows-d2f50e69-fdc8-498a-b3f6-f2304dc06f25.json
- packages/@react-native-windows/cli/src/e2etest/healthChecks.test.ts
- packages/@react-native-windows/cli/src/healthCheckList.ts
- packages/@react-native-windows/cli/src/healthChecks.ts
- vnext/Scripts/rnw-dependencies.ps1
> [0.72] Avoid having to launch PowerShell for every react-native config query

- change/@react-native-windows-cli-985bac64-01e4-4652-b9b9-3f2d116a52c7.json
- change/react-native-windows-b7765292-b2c6-4eae-962e-23b7fc15d0e8.json
- packages/@react-native-windows/cli/src/e2etest/healthChecks.test.ts
- packages/@react-native-windows/cli/src/healthCheckList.ts
- packages/@react-native-windows/cli/src/healthChecks.ts
- vnext/Scripts/rnw-dependencies.ps1
> [0.71] Avoid having to launch PowerShell for every react-native config query

- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
> [0.72] Component Governance 5/8/23

- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
> [0.71] Component Governance 5/8/23

- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
> [0.70] Component Governance 5/8/23

- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
> [0.69] Component Governance 5/8/23

- package.json
- packages/@rnw-scripts/doxysaurus/package.json
- yarn.lock
> [0.68] Component Governance 5/8/23

- change/react-native-windows-3ef19692-9e5c-436c-8efe-c0555e8cfd84.json
- vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/src/Libraries/Components/TextInput/TextInput.windows.js
- vnext/src/Libraries/Components/View/View.windows.js
> [0.72] Allow apps to provide accessibility information on non-focusable components

- change/react-native-windows-3ef19692-9e5c-436c-8efe-c0555e8cfd84.json
- vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
- vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- vnext/src/Libraries/Components/TextInput/TextInput.windows.js
- vnext/src/Libraries/Components/View/View.windows.js
> [0.71] Allow apps to provide accessibility information on non-focusable components

- change/react-native-windows-73fc6145-5b3c-4a35-af6f-c4efb5e8dcf0.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
Adding export for yoga gap setting to allow hookup inside office, and another export required for office use
> [Win32] Export yoga gap function

- change/react-native-windows-73fc6145-5b3c-4a35-af6f-c4efb5e8dcf0.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
> [0.71] [Win32] Export yoga gap function

- change/react-native-windows-73fc6145-5b3c-4a35-af6f-c4efb5e8dcf0.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
> [0.72] [Win32] Export yoga gap function

- change/@office-iss-react-native-win32-200bafc5-42f1-4687-97e7-4bae2324768c.json
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [0.71] [Win32] Export ITouchableWin32State

- change/@office-iss-react-native-win32-5622f0ff-223a-4260-b511-1fb075b2bf33.json
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [0.72] [Win32] Export ITouchableWin32State

- change/@office-iss-react-native-win32-1ee3bf3e-9277-451b-94ed-06d007ae1d7b.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [Win32] Add missing eventPhase on INativeKeyboardEvent

- change/@office-iss-react-native-win32-5d871315-b856-4ab7-938a-acfff441b310.json
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [Win32] Export ITouchableWin32State

- change/@office-iss-react-native-win32-eefb624d-6244-4273-8725-9f03183f4c0d.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/platform-types.d.ts
> [Win32] [0.72] Add eventPhase to IHandledKeyboardEvent

- .ado/templates/run-compliance-prebuild.yml
- change/@office-iss-react-native-win32-14bcdf28-5c19-4ff0-b78f-af9fdfa5b1eb.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/src/js/components/TextWin32Test.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
> [0.71] [Win32] Fix various text properties not being forwarded to native

- change/@office-iss-react-native-win32-79e9528f-5ae2-4fab-8f90-89ee3c25a001.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/src/js/components/TextWin32Test.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
> [Win32] Fix various text properties not being forwarded to native

- change/@office-iss-react-native-win32-abd12dab-70d6-4d8b-b7a4-2a7a2941161e.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/src/js/components/TextWin32Test.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
> [0.72] [Win32] Fix various text properties not being forwarded to native

- .ado/jobs/desktop.yml
- .ado/jobs/universal.yml
> Upgrade to BinSkim@4

- change/@rnw-scripts-eslint-config-2110c758-0964-47eb-a6ec-6d9fafd81a44.json
- packages/@rnw-scripts/eslint-config/eslintrc.js
- packages/@rnw-scripts/eslint-config/package.json
- yarn.lock
This PR upgrades the dependency as it was re-named upstream.
Closes #11742
Changed the dependencies in `@rnw-scripts/eslint-config`'s package.json.
N/A
Ran `yarn lint` and saw no changes.
> Migrate eslint-config from `@react-native-community` to `@react-native`

- change/@office-iss-react-native-win32-b00d591d-1ee9-4f53-a774-5b1674db73ba.json
- change/@react-native-windows-cli-85d36273-b7ae-4dcb-b608-09ac65652ee4.json
- change/@react-native-windows-codegen-52f823eb-8f2e-41a2-acb7-d13f16a9022a.json
- change/@react-native-windows-find-repo-root-80c3577a-87ce-4929-b078-270260eb88a8.json
- change/@react-native-windows-fs-136d7fed-bc03-46b6-9b6a-88ee09cfbd7f.json
- change/@react-native-windows-package-utils-7a690b50-b762-4110-8843-0880b5698f6d.json
- change/@react-native-windows-telemetry-95aa9b8a-4159-4f05-8bec-18ae08d64270.json
- change/react-native-windows-9af92351-d11f-4090-96f7-7a2c1ae5511d.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> Promote 0.72 to latest

- change/react-native-windows-54b226a7-3cc1-45be-b3d3-36069d8a3cf6.json
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
> [Fabric] Fix crash in certain unmount scenarios

- change/react-native-windows-7c3c8c8c-1d88-48f5-b978-74334be019e8.json
- vnext/package.json
> [0.72] Update files property to ensure TS types are published

- change/react-native-windows-ccec3086-548e-40b6-a95d-41c1ca26caff.json
- change/react-native-windows-fb4b5a1f-4c40-4b9d-9ba4-1876ea7e2614.json
- vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
- vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
- vnext/Microsoft.ReactNative.Cxx/NativeModules.h
- vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
Patch https://github.com/microsoft/react-native-windows/pull/11849 to 0.71
> Patch REACT_MACRO_NOREG to 0.71

- .github/pull_request_template.md
- Template Change
Currently the release notes process is done by manually scanning the PR's of the release and summarizing the changes found in the PR description. Help improve this process by writing out if the change should be included in the release notes and what the changelog entry should be. This way the author of the change can best describe to customers what has changed with this commit, and there is a lighter load on the release driver.
> Adjust PR Template to Include Changelog Section

- change/react-native-windows-1c549950-1146-4bb2-b48f-ed2c578f8237.json
- change/react-native-windows-43607961-c50e-495c-9c7a-1369930f4120.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/HttpModule.cpp
- vnext/Shared/Modules/HttpModule.h
- vnext/Shared/Networking/DefaultBlobResource.cpp
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/OInstance.cpp
> [0.72] Attempt AddNetworkingHandler if HTTP module was not ready (#11926)

- change/react-native-windows-52b290c1-4b76-4b4a-8b6a-dcff9868c844.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Shared/Modules/HttpModule.cpp
- vnext/Shared/Modules/HttpModule.h
- vnext/Shared/Networking/DefaultBlobResource.cpp
- vnext/Shared/Networking/WinRTHttpResource.cpp
- vnext/Shared/OInstance.cpp
> [0.71] Attempt AddNetworkingHandler if HTTP module was not ready (#11926)

- change/react-native-windows-5e0c771d-4dcd-4764-9f7a-e9cd0a69b5a9.json
- change/react-native-windows-8d9e88e3-ce8b-46b7-a11e-af04d9f3d59d.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Shared/OInstance.cpp
- vnext/overrides.json
- vnext/src/IntegrationTests/FetchTest.js
> [0.72] Allow disabling Blob Cxx module

- change/@office-iss-react-native-win32-43b80e6f-96e4-479c-b4d7-46c1fb056647.json
- packages/@office-iss/react-native-win32/metro.config.js
- packages/@office-iss/react-native-win32/metroShortPathAssetDataPlugin.js
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/react-native.config.js
- packages/@office-iss/react-native-win32/saveAssetPlugin.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/assetPaths.js
- packages/@office-iss/react-native-win32/src/Libraries/Image/resolveAssetSource.win32.js
> [0.71] Add saveAssetPlugin to fix long path assets

- change/@react-native-windows-cli-321ad683-84dc-4ae2-bf92-5d21bde36768.json
- packages/@react-native-windows/cli/src/codegen.ts
- packages/sample-apps/package.json
> [0.72] Fix codegenConfig.windows.separateDataTypes default value

- change/react-native-windows-3830c060-3a1d-4649-b97e-65f622437cc1.json
- vnext/PropertySheets/JSEngine.props
Update V8 JSI package to 0.71.8.
It contains PR https://github.com/microsoft/v8-jsi/pull/182 that fixes loading complex JS files.
It is to address issues with using V8 in RNW in Office apps.
> [0.71] Update V8 JSI version to 0.71.8

- change/@office-iss-react-native-win32-7fd6b7f9-9ded-4985-87b5-70b02f87b6c1.json
- change/@office-iss-react-native-win32-fe0fc9d1-3124-4ae6-b15a-7c456cee835d.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/assetPaths.js
> [Win32] [0.71] Remove flow usage from saveAssetPlugin codeflow

- change/@office-iss-react-native-win32-7fd6b7f9-9ded-4985-87b5-70b02f87b6c1.json
- change/@office-iss-react-native-win32-fe0fc9d1-3124-4ae6-b15a-7c456cee835d.json
- packages/@office-iss/react-native-win32/src/Libraries/Image/assetPaths.js
> [Win32] [0.72] Remove flow usage from saveAssetPlugin codeflow

- change/react-native-windows-5ecc024e-105e-4c8a-8085-ac9fe01a0ea8.json
- change/react-native-windows-fd1cdcfd-4d35-4bb4-a0b8-f13250055796.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
> [0.72] Skip networking Cxx modules if turbo modules are requested

- change/react-native-windows-532659c2-9d36-450b-9774-db0290b72b20.json
- change/react-native-windows-5ecc024e-105e-4c8a-8085-ac9fe01a0ea8.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
> [0.71] Skip networking Cxx modules if turbo modules are requested

- change/react-native-windows-3f4b160f-4cfd-46cf-9d96-fe93592551af.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
Adds ActivityIndicator animating property
Reach component parity
Hides the m_visual when animating='true'
https://github.com/microsoft/react-native-windows/assets/42554868/2050756a-311a-4e69-8ed1-e5baa58ca506
Tested locally
no
> [Fabric] Adds ActivityIndicator animating property

- .editorconfig
- change/@office-iss-react-native-win32-b62a33bd-f233-44b0-be24-cfff8997a9f2.json
- change/react-native-windows-82518cbe-9af2-452c-b142-d450aacb1d1f.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
- vnext/.editorconfig
> [0.71] Have RCTNetworking.win32 fork RCTNetworking.ios

- .editorconfig
- change/@office-iss-react-native-win32-35ea91eb-4df0-41a8-bbcd-f9d7e927286c.json
- change/react-native-windows-c4b46a5c-3a02-4820-83b2-4b50f7c278fb.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
- vnext/.editorconfig
> [0.72] Have RCTNetworking.win32 fork RCTNetworking.ios

- change/react-native-windows-c3729e7b-702d-42ef-aa91-3783268371d2.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/PropertySheets/JSEngine.props
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/Shared/HermesRuntimeHolder.cpp
- vnext/Shared/InspectorPackagerConnection.h
- vnext/Shared/JSI/V8RuntimeHolder.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/SafeLoadLibrary.cpp
- vnext/Shared/SafeLoadLibrary.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
PR #12143 : Update V8 JSI version to 0.71.8 and new Hermes API
PR #12211 : Switch between V8 JSI and V8 Node-API
> [0.72] Cherry pick PRs #12143 #12211 

- change/react-native-windows-a292054c-e016-4f31-bb25-3808d092176b.json
- change/react-native-windows-ea22f19f-53f4-456d-aeba-7ebaee3a4e2d.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
> [0.71] Conditionally register WebSocket Cxx module

- change/@rnw-scripts-eslint-config-219bbb7e-14f5-42cd-bcf2-23f365225f84.json
- change/react-native-windows-6af84fcc-5034-47ad-958a-13a386f5e752.json
- change/react-native-windows-init-9963797e-f8f5-4463-80a3-ad75f9f183a4.json
- packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExampleMultiPartFormData.js
- packages/@rnw-scripts/eslint-config/eslintrc.js
- packages/@rnw-scripts/eslint-config/package.json
- packages/playground/Samples/image.tsx
- packages/playground/Samples/index.tsx
- packages/react-native-windows-init/src/Cli.ts
- vnext/src/IntegrationTests/WebSocketBinaryTest.js
- vnext/src/IntegrationTests/WebSocketBlobTest.js
- yarn.lock
This PR adds the `@microsoft/eslint-plugin-sdl` plugin to our shared eslint config, to make sure that all of our packages meet our SDL security requirements.
This PR also fixes any outstanding issues flagged by the plugin.
Compliance.
Resolves #11743
Added a dependency on `@microsoft/eslint-plugin-sdl` and included the required config in our config.
N/A
Ran yarn lint
> Add `@microsoft/eslint-plugin-sdl` to `@rnw-scripts/eslint-config`

- change/react-native-windows-8c05985b-a36b-47a9-8e1d-15c3e73e131b.json
- vnext/Microsoft.ReactNative/packages.lock.json
Reverted unintended changes to `package.lock.json` committed in the [09/25 Integration](https://github.com/microsoft/react-native-windows/pull/12220).
> Reverted package.lock changes from 09/25 Integration

- change/@office-iss-react-native-win32-22bcae82-8c54-41e1-88f1-6aeb9deafbe3.json
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/.flowconfig
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/NativeAccessibilityInfoWin32.js
> [0.72] Add support for announceForAccessibilityWithOptions 

- change/@office-iss-react-native-win32-22bcae82-8c54-41e1-88f1-6aeb9deafbe3.json
- packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
- packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
- packages/@office-iss/react-native-win32/.flowconfig
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.d.ts
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
- packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/NativeAccessibilityInfoWin32.js
> [0.71] Add support for announceForAccessibilityWithOptions 

- change/react-native-windows-5d9952b2-0b6d-4246-a1ec-994f54168545.json
- change/react-native-windows-9c737b5d-11f5-41a6-9fdf-e29b2c7c0162.json
- vnext/Shared/Modules/BlobCollector.cpp
- vnext/Shared/Modules/BlobCollector.h
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
> [0.73] Implement BlobCollector

- change/react-native-windows-097e5d2f-9d66-45b1-be82-d94fad723fcf.json
- change/react-native-windows-5d9952b2-0b6d-4246-a1ec-994f54168545.json
- vnext/Shared/Modules/BlobCollector.cpp
- vnext/Shared/Modules/BlobCollector.h
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
> [0.71] Implement BlobCollector

- change/react-native-windows-5d9952b2-0b6d-4246-a1ec-994f54168545.json
- change/react-native-windows-8036b88d-3957-4d10-a466-ae3f555f4e5a.json
- vnext/Shared/Modules/BlobCollector.cpp
- vnext/Shared/Modules/BlobCollector.h
- vnext/Shared/Modules/BlobModule.cpp
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
> [0.72] Implement BlobCollector

- change/react-native-windows-069b839c-e203-4b45-8fb4-154253091ab3.json
- vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp
Follow up to https://github.com/microsoft/react-native-windows/pull/12264, to simplify the code.
> Minor codereview feedback cleanup

- change/react-native-windows-31d244cb-456f-4fe8-89e4-2506b9aa095d.json
- packages/e2e-test-app-fabric/test/visitAllPages.test.ts
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative/AsynchronousEventBeat.cpp
- vnext/Microsoft.ReactNative/AsynchronousEventBeat.h
- vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/QuirkSettings.cpp
- vnext/Microsoft.ReactNative/QuirkSettings.h
- vnext/Microsoft.ReactNative/QuirkSettings.idl
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/SchedulerSettings.cpp
- vnext/Microsoft.ReactNative/SchedulerSettings.h
- vnext/Microsoft.ReactNative/SynchronousEventBeat.cpp
- vnext/Microsoft.ReactNative/SynchronousEventBeat.h
- vnext/Shared/Shared.vcxitems
> Install runtime scheduler

- change/react-native-windows-5d484961-48b1-4a0c-b38f-813f9587a87c.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/PropertySheets/JSEngine.props
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactCommon.UnitTests/packages.lock.json
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/uimanager/UIManagerBinding.cpp
- vnext/Shared/HermesRuntimeHolder.cpp
- vnext/Shared/JSI/V8RuntimeHolder.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/SafeLoadLibrary.cpp
- vnext/Shared/SafeLoadLibrary.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
PR #12143 : Update V8 JSI version to 0.71.8 and new Hermes API
PR #12211 : Switch between V8 JSI and V8 Node-API
> Cherry pick PRs #12143 #12211 

- .ado/jobs/linting.yml
- change/react-native-windows-948c4c23-83ed-474f-9940-28edf5a5c120.json
- change/react-native-windows-c3729e7b-702d-42ef-aa91-3783268371d2.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
- vnext/Microsoft.ReactNative/ReactHost/React.h
- vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/PropertySheets/JSEngine.props
- vnext/PropertySheets/React.Cpp.props
- vnext/ReactCommon.UnitTests/packages.lock.json
- vnext/ReactCommon/ReactCommon.vcxproj
- vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/uimanager/UIManagerBinding.cpp
- vnext/Shared/HermesRuntimeHolder.cpp
- vnext/Shared/JSI/V8RuntimeHolder.cpp
- vnext/Shared/OInstance.cpp
- vnext/Shared/SafeLoadLibrary.cpp
- vnext/Shared/SafeLoadLibrary.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
- vnext/Shared/V8JSIRuntimeHolder.cpp
- vnext/Shared/V8JSIRuntimeHolder.h
PR #12143 : Update V8 JSI version to 0.71.8 and new Hermes API
PR #12211 : Switch between V8 JSI and V8 Node-API
> [0.73] Cherry pick PRs #12143 #12211

- change/react-native-windows-49a257cd-bf7b-481e-8cf8-844a5d96da23.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
> [0.72] Keep propertyBag alive for duration of InstanceDestroyed event

- change/react-native-windows-2722b4db-77f6-4d6f-b63f-39a6e48f2c9e.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Port https://github.com/microsoft/react-native-windows/pull/12364 to 0.73
> [0.73] Keep propertyBag alive for duration of InstanceDestroyed event

- change/react-native-windows-9961dec7-20c7-47ea-adf2-3bc6b6b97d2b.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
> [0.72] Untrack HTTP responses when processed by IResponseHandler (#12378)

- change/react-native-windows-b63c563c-f799-428d-8342-f251874d2006.json
- change/react-native-windows-e6a650eb-7ab8-4cf5-b094-4b685648e01a.json
- vnext/Shared/Networking/DefaultBlobResource.cpp
> [0.73] Ensure both property and value exist for Blob's HTTP proxy

- change/react-native-windows-09e34054-bddd-43f2-ba3c-ceee73b81fdb.json
- change/react-native-windows-e6a650eb-7ab8-4cf5-b094-4b685648e01a.json
- vnext/Shared/Networking/DefaultBlobResource.cpp
> [0.72] Ensure both property and value exist for Blob's HTTP proxy

- change/@office-iss-react-native-win32-19b48264-64cf-49f7-86e5-a03ad0d3adcf.json
- change/react-native-windows-a3cf3091-3449-4036-8541-1a61b2843dbc.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
https://github.com/facebook/react-native/compare/v0.73.0-rc.4...v0.73.0-rc.5
Integration
no
> [0.73] Integrate RN 0.73.0-rc.5

- change/@office-iss-react-native-win32-e3813bd9-a9cb-4b28-8c2f-b6d1358a3049.json
- change/react-native-windows-fd888f4c-2795-4383-829d-04e7e553dd45.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/playground/windows/playground/packages.lock.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Integrate [0.73.0-rc.6](https://www.npmjs.com/package/react-native/v/0.73.0-rc.6)
https://github.com/facebook/react-native/compare/v0.73.0-rc.5...v0.73.0-rc.6
Integration
tested playground locally
no
> [0.73] Integrate RN rc-6

- change/@office-iss-react-native-win32-fb87a5e3-75e1-41b9-bc1e-75d5d1b91a05.json
- change/react-native-windows-66469eaa-73f4-4d87-8f6d-0e6ced5140db.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
https://github.com/facebook/react-native/compare/v0.73.0-rc.6...v0.73.0-rc.8
Integration
> [0.73] Integrate RC8

- change/react-native-windows-0bee4757-1155-4cc8-acbf-daa5c35b9ed4.json
- change/react-native-windows-16ae9eea-0f37-40b2-91da-33069ca74dd5.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
> [0.73] Use HTTP form data as JSArray (#12506)

- change/react-native-windows-16ae9eea-0f37-40b2-91da-33069ca74dd5.json
- change/react-native-windows-e863bd3d-a8d0-4a69-a098-e58557c77bc4.json
- vnext/Shared/Networking/WinRTHttpResource.cpp
> [0.72] Use HTTP form data as JSArray (#12506)

- change/react-native-windows-b0f6c82f-5705-494d-b815-65d0e32b8682.json
- vnext/Desktop.UnitTests/BaseFileReaderResourceUnitTest.cpp
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
- vnext/Shared/BaseFileReaderResource.cpp
> [0.73] Fix FileReader Base64 padding (#12522)

- change/react-native-windows-7b06fe5d-31c3-4fbf-9f17-de1c6cb85bf4.json
- vnext/Desktop.UnitTests/BaseFileReaderResourceUnitTest.cpp
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
- vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
- vnext/Shared/BaseFileReaderResource.cpp
> [0.72] Fix FileReader Base64 padding (#12522)

- packages/e2e-test-app-fabric/README.md
- Documentation update
Documenting E2E Testing infrastructure and how-to steps.
> Update Link to E2E Testing Documentation for Fabric 

- change/react-native-windows-ba0e5d44-3f62-41c2-84a3-0169e5ed2a2b.json
- vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Backport of https://github.com/microsoft/react-native-windows/pull/12278
yes
> [0.73] Fix event dispatch names for momentum scroll (#12278)

- change/react-native-windows-bf6c22c5-997f-4ebe-a669-6ed02bbbb343.json
- vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Backport of https://github.com/microsoft/react-native-windows/pull/12278
resolves #12549
yes
> [0.72] Fix event dispatch names for momentum scroll (#12278)

- .github/workflows/similarIssues.yml
Creates a new GitHub action that makes a bot that will automatically comment on new issues letting them know about similarly titled issues using AI. Comments will look like this:
https://github.com/microsoft/terminal/issues/16482#issuecomment-1867797451
The advantage is that users will be able to find related issues faster, and be able to resolve themselves quicker, with you as a maintainer having to close out less issues. 
Add a GitHub Action.
Screenshot of the bot in action:
No testing required for this specific repo
No
> Create Similar Issues Bot

- yarn.lock
* Updated `postcss`
* Updated `react-devtools-core`
> [0.73] Component Governance fixes for 16-JAN-24

- change/react-native-windows-d67bc50f-c862-4016-9a02-2a1e3dca673e.json
- vnext/Microsoft.ReactNative/ComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/AbiCompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UiaHelpers.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.h
Exposes basic tree access to the public API of the native UI tree.
> [Fabric] Expose public APIs to navigate native UI tree

- change/@react-native-windows-automation-channel-5cecf6fb-d7f5-4343-bf9d-0678500cb2ca.json
- change/react-native-windows-db739b1d-8924-4611-8815-846f83dee53c.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/ReactCommon/cgmanifest.json
- vnext/Shared/Shared.vcxitems.filters
Updating a couple of files that are out of date in the repo and get generated when rebuilding.
> Bump out of date generated files

- .unbroken_exclusions
- packages/playground/README_composition.md
Quick description of how to run the playground-composition app.
> Add readme file for playground-composition

- change/@react-native-windows-cli-9c435bb2-7093-40f2-90fd-248ba7d9549a.json
- change/react-native-windows-ff4eb7c1-41b5-4b37-80af-614ecc10ccf3.json
- packages/@react-native-windows/cli/src/commands/healthCheck/healthCheckList.ts
- vnext/Scripts/rnw-dependencies.ps1
On VS 2022 version 17.8.7, there is a consistent build error when trying to deploy RNW applications through VS 2022 - this error seems to have been resolved on VS 2022 version 17.9.0. This PR updates the min version of VS 2022 to check for in the dependency script to avoid this error being hit on the older version.
Avoid future build errors for new RNW users.
Error shown when building application on 17.8.7:
```
√ Building Solution
√ Starting the React-Native Server
√ Enabling Developer Mode
ERROR: ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at …
```
> Update min VS version in RNW dependency script

- change/react-native-windows-4cae17d6-1f2a-4ce2-b5e5-a68eb7e7f00d.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
> [0.73] Omit trailing slash in Origin header

- change/react-native-windows-90589a96-220b-4960-b974-b71ccff43cac.json
- change/react-native-windows-d32f2db0-c67b-4072-8101-c20adb49f267.json
- vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
- vnext/Shared/Networking/OriginPolicyHttpFilter.h
> [0.72] Omit trailing slash in Origin header

- change/react-native-windows-0570ab61-c735-445a-96bc-807b0ac5f69d.json
- vnext/Desktop.DLL/react-native-win32.x64.def
- vnext/Desktop.DLL/react-native-win32.x86.def
> [NetUI] Export getRuntimeExecutor for internal usage

- change/react-native-windows-179ea4bc-b24d-456c-97b5-e80b301fc16f.json
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/HostPlatformViewTraitsInitializer.h
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/components/view/WindowsViewEvents.h
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
- vnext/src-win/Libraries/NativeComponent/BaseViewConfig.windows.js
- Better align native and JS view configs
- Fix intermittent failure in TextInput E2E test
- Remove unnecessary calls to unmountComponentAtNode
> Better align native and JS view configs

- change/@react-native-windows-automation-channel-1da444f5-c281-4a41-85c8-5ea64afb3b76.json
- change/react-native-windows-2ded6fa0-41f2-4987-825e-67d0e19b9cef.json
- packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric.Package/packages.lock.json
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
- packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
- packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
- packages/playground/windows/playground-composition/Playground-Composition.cpp
- packages/playground/windows/playground-win32/packages.lock.json
- packages/playground/windows/playground/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
- vnext/Microsoft.ReactNative.Managed/packages.lock.json
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/WinUI.props
> Bump WindowsAppSDK version to 1.5.240227000

- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/src/js/examples/Image/ImageExample.windows.js
- packages/e2e-test-app-fabric/test/ImageComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/ImageComponentTest.test.ts.snap
- Additional Testing
Increase testing coverage of RNW Fabric. 
https://github.com/microsoft/react-native-windows/issues/11422
https://github.com/microsoft/react-native-windows/issues/11281
Add visual snapshot tests for image component
> Add Visual Snapshot Tests for Image Component

- change/react-native-windows-cb387bc4-0e9f-418b-bbf5-dc96833f9921.json
- vnext/metroShortPathAssetDataPlugin.js
- vnext/overrides.json
- vnext/saveAssetPlugin.js
- vnext/src-win/Libraries/Image/AssetSourceResolver.windows.js
- vnext/src-win/Libraries/Image/assetPaths.js
- vnext/src-win/Libraries/Image/resolveAssetSource.windows.js
Port of #11839 from @office-iss/react-native-win32 to react-native-windows.
> Reduce usage of long paths in assets which can cause long path issues

- change/react-native-windows-91e4571c-cdb6-4c4e-b7f6-d720a005abd1.json
- vnext/Microsoft.ReactNative.Cxx/AutoDraw.h
- vnext/Microsoft.ReactNative.Cxx/CompositionSwitcher.Experimental.interop.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/Scripts/OfficeReact.Win32.nuspec
> [0.74] Unify some DPI drawing logic

- change/@react-native-windows-cli-038fd909-4fdd-44ae-a311-6214f3ab8212.json
- change/react-native-platform-override-942b2a40-c27a-471d-8859-ea551997cb51.json
- change/react-native-windows-e72f64ee-447b-4a0b-acab-5b07024716f2.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindows.ts
- packages/react-native-platform-override/src/Hash.ts
- vnext/Common/Utilities.cpp
Fixes for some of the CodeQL issues tracked here: #12701 #12704 
CodeQL found some issues in our C++ and JS code. 
> CodeQL fixes

- .ado/stages.yml
Backport https://github.com/microsoft/react-native-windows/pull/12945 to 0.73
> [0.73] Backport "Disable node-tests job for now #12945"

- change/@office-iss-react-native-win32-ce60bd38-0b6b-4767-81ba-e49fa9f07d73.json
- change/@react-native-windows-cli-3009859e-7b88-41a2-aac0-f3c181ac6beb.json
- change/@react-native-windows-codegen-853af205-2f3e-4bbf-987f-1328bbce7789.json
- change/@react-native-windows-find-repo-root-5828ae25-e6fe-439d-a8a3-5c26816f3e6a.json
- change/@react-native-windows-fs-ff1086d1-cd68-40c9-958b-ebceaac9205d.json
- change/@react-native-windows-package-utils-6efcb457-15f2-4c67-a65a-e82cf2bd411c.json
- change/@react-native-windows-telemetry-81974089-289f-4772-b337-97078f7b5d22.json
- change/react-native-windows-97de82d1-6c86-4801-a21d-7f39c4e48224.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.73] Promote 73 to legacy

- change/@office-iss-react-native-win32-15a0ac88-2693-4283-be7a-983f985bdd22.json
- change/@react-native-windows-cli-34870f57-f9be-4b9f-aa24-c129c36b4bda.json
- change/@react-native-windows-codegen-7181e231-0790-4b50-8c12-738a1047bd2d.json
- change/@react-native-windows-find-repo-root-f4dbc65d-56e5-4e60-bf35-3a18426f182e.json
- change/@react-native-windows-fs-015bc389-e696-43e9-8ae7-83e37d59e543.json
- change/@react-native-windows-package-utils-7276bf56-8e7a-4a28-a7f1-5db2ab3e25eb.json
- change/@react-native-windows-telemetry-ffb034e0-8318-4a0e-a6c4-4301886b118c.json
- change/react-native-windows-6ed92e99-06b8-4e70-92b6-06ec465c0840.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.74] Promote 74 to latest

- change/@office-iss-react-native-win32-6b1b9c92-50ad-4985-89ba-4f2505aa825c.json
- change/react-native-windows-3701d914-c1cc-48f7-b2ad-e84229318968.json
- change/react-native-windows-91e4571c-cdb6-4c4e-b7f6-d720a005abd1.json
Missed these change files, fixes them to "patch" since 0.74 is promoted to latest!
> [0.74] Fix changefiles

- change/@office-iss-react-native-win32-8d29d8e3-d406-4dcd-894c-79e5e3bb38db.json
- change/react-native-windows-986295a0-cbb8-412f-b82b-06e6d1d2fc77.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Part of #13184, making sure all stable branch are up-to-date with latest changes from upstream
https://github.com/facebook/react-native/compare/v0.73.6...v0.73.8
None, mostly ios/andriod fixes
Integration
> [0.73] Integrate 0.73.8

- change/@react-native-windows-automation-commands-8efb4ec6-5444-4510-9e8a-2f6e003f55fb.json
- change/react-native-windows-8549cb15-fcb5-48e9-b8bf-8d6e2ae1d896.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/ComponentView.idl
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/FocusManager.h
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/FocusManager.idl
- vnext/Shared/Shared.vcxitems
> [0.74] [Fabric] Add various native focus APIs

- change/react-native-windows-0e7a6537-e72d-4a1b-a499-cdbcc09561fb.json
- change/react-native-windows-759b1fea-b751-4ff5-8448-61302a4756e5.json
- vnext/Desktop/module.g.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
> [0.74] Port fixes

- change/@office-iss-react-native-win32-2d31aa67-ede5-4121-a95f-49e06bc9cec6.json
- change/react-native-platform-override-77ef9896-f6ff-43b2-a7ba-be92a933e696.json
- change/react-native-windows-8c39cd89-3598-4782-9889-f7397326f7b8.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-apps/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Upgrade RNW from RN 0.72.14 to 0.72.15.
To catch up with latest 0.72 and 
See above.
N/A
N/A
Upgrading from RN 0.72.14 to 0.72.15.
> [0.72] Integrate RN 0.72.15

- .ado/templates/prep-and-pack-single.yml
This PR upgrades our CI for codesigning to the latest ESRP task to meet with security requirements.
> SFI: Upgrade to EsrpCodeSigning@5

- Directory.Build.targets
- change/react-native-windows-2a78b4e0-57d6-488b-bd3c-2673c1720389.json
- vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/ExperimentalFeatures.props
> [0.73] Upgrade Desktop solution/projects to Win SDK 10.0.22621.0

- .ado/jobs/desktop.yml
- .ado/jobs/nuget-desktop.yml
- change/react-native-windows-29a5fd44-3ee5-4e8f-acda-3e5dd0384a97.json
- change/react-native-windows-3373c57a-968b-415a-b009-f41accdeaf78.json
- vnext/Scripts/OfficeReact.Win32.nuspec
> [0.75] Update Desktop NUSPEC to use ARM64EC

- .ado/publish.yml
Backport of 5d81068c9220b5a2d3d6441c1c0c24fc4afb555e
> [0.74] Fix Desktop NuGet slices for ARM64EC publish

- .ado/publish.yml
Backport of 5d81068c9220b5a2d3d6441c1c0c24fc4afb555e
> [0.73] Fix Desktop NuGet slices for ARM64EC publish

- change/react-native-windows-04d234ac-4d36-4621-aa06-dbc4b67a5e0a.json
- change/react-native-windows-3bfe3447-806c-446c-a4d9-117b71cec5ea.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/PropertySheets/JSEngine.props
> [0.75] Don't override Hermes platform for ARM64EC #13490

- change/react-native-windows-04d234ac-4d36-4621-aa06-dbc4b67a5e0a.json
- change/react-native-windows-731ad482-e98d-4ae4-85f3-6c348f5a3810.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop/packages.lock.json
- vnext/PropertySheets/JSEngine.props
> [0.74] Don't override Hermes platform for ARM64EC #13490

- .ado/templates/react-native-init-windows.yml
> [0.75] Backport #13506 - Fix Fabric cli CI jobs 

- change/react-native-windows-47a010c1-a124-470a-8d55-8350642cbff5.json
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.h
- vnext/Microsoft.ReactNative/Fabric/AbiViewShadowNode.cpp
> [0.75] [Fabric] Custom ShadowNodes are never released

- change/react-native-windows-47a010c1-a124-470a-8d55-8350642cbff5.json
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.cpp
- vnext/Microsoft.ReactNative/Fabric/AbiShadowNode.h
- vnext/Microsoft.ReactNative/Fabric/AbiViewShadowNode.cpp
> [0.74] [Fabric] Custom ShadowNode's are never released

- change/react-native-windows-0ee3e7ef-c980-49c3-b4b8-447a7050c339.json
- vnext/Common/Utilities.cpp
> [0.74] Backport CodeQL fix

- change/react-native-windows-d6d68656-5e3d-4020-9cd6-703ed3f87bfa.json
- vnext/Microsoft.ReactNative/Modules/StatusBarManager.h
Backport #13556. Should fix web debugging :)
> [0.75] Backport Enforce StatusBarManger module aligns with Spec #13556

- change/react-native-windows-be508141-7939-463a-a027-7f989fb15b27.json
- vnext/Microsoft.ReactNative/Modules/StatusBarManager.h
Backport https://github.com/microsoft/react-native-windows/pull/13556. Should fix web debugging :)
> [0.74] Backport Enforce StatusBarManger module aligns with Spec #13556

- change/@office-iss-react-native-win32-22faa574-2122-48d1-84a4-95848967b869.json
- change/@react-native-windows-cli-7f74f938-d514-441a-952d-62b470ea7915.json
- change/@react-native-windows-codegen-c16b2fb7-7307-4cda-9eb7-9f5b252ae609.json
- change/@react-native-windows-find-repo-root-fa648df6-5b8b-4a9e-acf6-a8aabd5f7356.json
- change/@react-native-windows-fs-11e071d6-ebc8-4e3e-bea8-b82d45b9c47b.json
- change/@react-native-windows-package-utils-7a1cf2f4-0db4-429e-8dbd-4670289d7bd6.json
- change/@react-native-windows-telemetry-235f7191-dae7-4580-ab3c-c0d0135b0b8d.json
- change/react-native-windows-f1053f18-8ec5-4b93-b45a-0d624b1980a8.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
Part of 0.75 release, promotes 0.74 to legacy.
> [0.74] Promote 0.74 to Legacy 

- change/react-native-windows-dbe41975-86df-4a59-9be8-e2b51b4c50c1.json
- vnext/Desktop/Modules/DesktopTimingModule.cpp
- vnext/Desktop/Modules/DesktopTimingModule.h
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/ReactWindows-Desktop.sln
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
>  [0.75] Use Turbo Modules for Desktop instead of CxxModules

- change/react-native-windows-dbe41975-86df-4a59-9be8-e2b51b4c50c1.json
- vnext/Desktop/Modules/DesktopTimingModule.cpp
- vnext/Desktop/Modules/DesktopTimingModule.h
- vnext/Desktop/React.Windows.Desktop.vcxproj
- vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
- vnext/ReactWindows-Desktop.sln
- vnext/Shared/DevSettings.h
- vnext/Shared/OInstance.cpp
Port https://github.com/microsoft/react-native-windows/pull/13265 to main
> Use Turbo Modules for Desktop instead of CxxModules

- change/react-native-windows-2a2b1b40-5859-4ef6-9dd5-b48717b71c24.json
- vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
> [0.74] replace IAppData.TemporaryFolder with GetTempPathW

- change/@react-native-windows-cli-7e4d9c41-7fb9-4982-85d7-d002ddf15806.json
- change/@react-native-windows-codegen-1eb465fe-90fa-470c-b464-b3826e2da150.json
- change/react-native-windows-21e0dde1-5046-445c-8025-7cd5440d1af2.json
- change/react-native-windows-a5988a0a-5c91-4849-8751-5264d7e94249.json
- packages/@react-native-windows/cli/src/commands/codegenWindows/codegenWindows.ts
- packages/@react-native-windows/codegen/src/Cli.ts
- packages/@react-native-windows/codegen/src/generators/AliasManaging.ts
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- packages/@react-native-windows/codegen/src/generators/PropObjectTypes.ts
- packages/@react-native-windows/codegen/src/index.ts
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/CustomComponent.cpp
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
- vnext/just-task.js
Port #13640 and #13329 to 0.75
> [0.75] [Fabric] Add native component codegen

- change/@react-native-windows-cli-7e4d9c41-7fb9-4982-85d7-d002ddf15806.json
- change/@react-native-windows-codegen-1eb465fe-90fa-470c-b464-b3826e2da150.json
- change/react-native-windows-21e0dde1-5046-445c-8025-7cd5440d1af2.json
- change/react-native-windows-a5988a0a-5c91-4849-8751-5264d7e94249.json
- packages/@react-native-windows/cli/src/commands/codegenWindows/codegenWindows.ts
- packages/@react-native-windows/codegen/src/Cli.ts
- packages/@react-native-windows/codegen/src/generators/AliasManaging.ts
- packages/@react-native-windows/codegen/src/generators/GenerateComponentWindows.ts
- packages/@react-native-windows/codegen/src/generators/PropObjectTypes.ts
- packages/@react-native-windows/codegen/src/index.ts
- packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp
- packages/playground/windows/playground-composition/CustomComponent.cpp
- vnext/Microsoft.ReactNative/CompositionComponentView.idl
- vnext/Microsoft.ReactNative/Fabric/ComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/ComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
- vnext/Microsoft.ReactNative/IReactCompositionViewComponentBuilder.idl
- vnext/Shared/Shared.vcxitems.filters
- vnext/just-task.js
Port https://github.com/microsoft/react-native-windows/pull/13640 and https://github.com/microsoft/react-native-windows/issues/13329 to 0.75
> [0.74] [Fabric] Add native component codegen

- change/react-native-windows-61e991a4-b01f-44ee-a7a3-43a6d7f79eb1.json
- vnext/Microsoft.ReactNative/Composition.Input.idl
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
Enable touch scrolling in ScrollView's
Fixes #13297
> [Fabric] Enable ScrollView touch scrolling

- .ado/templates/msbuild-sln.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
This PR backports #13669 and #13684 to 0.75
> Backport ADO fixes to 0.75

- .ado/publish.yml
- .ado/templates/configure-git.yml
- .ado/templates/set-version-vars.yml
> Attempt to fix publish by splitting up the publish jobs

- .ado/publish.yml
> [0.75] Update to publish pipeline

- .ado/jobs/cli-init-windows.yml
- .prettierignore
- change/@office-iss-react-native-win32-c783da71-36f4-4fb3-9c19-dd1e588105a4.json
- change/react-native-windows-011daa16-04a9-4b25-99ad-36a33887e763.json
- packages/@office-iss/react-native-win32/.eslintignore
- packages/e2e-test-app-fabric/test/TextInputComponentTest.test.ts
- vnext/.eslintignore
Fix ignore files and update cli timeout.
> Fix ignore files and update cli timeout

- change/react-native-windows-1fcd0c1f-ea81-47bf-a71e-8e0ebc4a0268.json
- change/react-native-windows-76c400e4-4a62-4fcd-95c9-25a19cf51138.json
- vnext/src-win/Libraries/Text/Text.windows.js
Backport https://github.com/microsoft/react-native-windows/pull/14041 into 0.76-stable
> [0.76][Backport] Fix Text running flattenStyle multiple times #14041

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/templates/react-native-init-windows.yml
Fix CI to correctly enable/disable hermes.
Accurate testing.
Fixed the task that set the UseHermes experimental prop.
N/A
Verified UseHermes set to true now.
> Fix UseHermes to mean UseHermes

- .ado/jobs/e2e-test.yml
- .ado/jobs/integration-test.yml
- .ado/templates/react-native-init-windows.yml
This PR backports #14071 to 0.76.
Fix CI to correctly enable/disable hermes.
Accurate testing.
Fixed the task that set the UseHermes experimental prop.
N/A
Verified UseHermes set to true now.
> [0.76] Fix UseHermes to mean UseHermes

- change/@office-iss-react-native-win32-b88ff79f-6028-4a3a-b096-90f3f561b520.json
- change/@react-native-windows-cli-423faf45-179f-4b9e-bb62-c68a001f84eb.json
- change/@react-native-windows-codegen-7d11f216-b0df-4314-913e-e8e9745d93b6.json
- change/@react-native-windows-find-repo-root-3fb937f0-a5c8-4c8d-9184-e0a5c6f89e4d.json
- change/@react-native-windows-fs-f4d0ef18-5595-497a-9c6c-eda9bd070b63.json
- change/@react-native-windows-package-utils-739aefe1-176d-4148-a7b8-6d26cf6c62a0.json
- change/@react-native-windows-telemetry-83fcd0ce-213d-404a-a357-8a149a5c1722.json
- change/react-native-windows-df518eee-4731-47aa-8305-ad1c42bd45ef.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.75] Promote 75 to legacy

- change/@office-iss-react-native-win32-64e06243-e1b5-49e2-9304-50e2e7d6b73f.json
- change/@react-native-windows-cli-55aae996-9f4e-42f9-b467-710a0d76e030.json
- change/@react-native-windows-codegen-19f19965-2583-427b-bdd7-a25d6ad1a9a2.json
- change/@react-native-windows-find-repo-root-8b1b63ba-4c52-4027-8b33-6dbcc98964ec.json
- change/@react-native-windows-fs-7898594e-a567-43a1-91de-2eca824c0f9d.json
- change/@react-native-windows-package-utils-db669443-a6ff-4b6f-9f3b-4380207bae89.json
- change/@react-native-windows-telemetry-2dc2f58e-4343-45e6-a0cc-a955193e8882.json
- change/@react-native-windows-telemetry-9e13a791-aacf-48af-9071-5bb2ffcebebd.json
- change/react-native-windows-1f9353e8-818c-4f9e-ab37-6f9021bb9ff7.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.76] Promote 76 to latest

- change/react-native-windows-42cade43-cd57-4cd5-97d3-2a35b924d78f.json
- change/react-native-windows-ad145bca-5a3a-45aa-ab7b-35661aa5fe59.json
- packages/e2e-test-app-fabric/test/__snapshots__/ButtonComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/HomeUIADump.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/PressableComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/ScrollViewComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/TouchableComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/ViewComponentTest.test.ts.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/BorderPrimitive.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/BorderPrimitive.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/UnimplementedNativeViewComponentView.cpp
- vnext/TestWebSite/Microsoft.ReactNative.Test.Website.csproj
Port #14091 and #14093 to 0.74
> [0.74] Fix focus visuals being obscured by adjacent views

- change/react-native-windows-31db428a-029b-4735-94f6-2c4368b9bda6.json
- change/react-native-windows-4fec92b2-f049-43b1-8e13-d9c351c5511b.json
- change/react-native-windows-58d5a889-6e77-4cde-a5d8-76a73e9a3cb7.json
- change/react-native-windows-e6508963-e86e-45b4-86e5-3f82b548e2f7.json
- packages/@react-native-windows/tester/src/js/examples/Modal/ModalPresentation.windows.js
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/Modal/WindowsModalHostViewComponentView.h
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
- vnext/Mso.UnitTests/future/futureTest.cpp
- vnext/overrides.json
- vnext/src-win/Libraries/Modal/Modal.windows.js
Cherrypick #14126, #14153, #14141 and #14109
> [0.74] Cursor support 

- .ado/jobs/cli-init-windows.yml
This PR attempts to fix the Secure PR pipeline.
Secure PR pipeline hasn't been used in a while.
Added a sanity paper new app build to the secure pr matrix.
N/A
Verified secure PR ran.
> Add a sanity paper build to secure pr configuration

- change/@office-iss-react-native-win32-62bf54b8-7e51-4823-be67-c091c297c01d.json
- change/@react-native-windows-cli-f3b8992e-f176-41d0-add0-ad230df5c7a5.json
- change/@react-native-windows-codegen-3e0aa0f7-7393-4ed0-ba2c-106faf189d33.json
- change/@react-native-windows-find-repo-root-2c23985b-ba98-4874-bd5d-f03afe6c67df.json
- change/@react-native-windows-fs-2e3bd5bf-3945-4fbe-adbb-6b6de76c3e2f.json
- change/@react-native-windows-package-utils-c3866477-cf20-4236-8961-a319ad74a7d9.json
- change/@react-native-windows-telemetry-1c9486e8-40f2-4ba6-a896-6052c7936309.json
- change/react-native-windows-4860c6e3-5b4a-45b2-accc-b6e0cbe88e0f.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.76] Promote 76 to legacy

- change/@office-iss-react-native-win32-9f6e1233-bafa-485e-b05d-1b0f98028c6c.json
- change/@office-iss-react-native-win32-f698a75b-2c71-4b6b-8020-23b1ecd84b59.json
- change/@react-native-windows-cli-722c444e-8e18-44b6-ba8f-01c70a818faf.json
- change/@react-native-windows-codegen-a3c1a2cf-785a-42a6-bd04-9b9c9550f281.json
- change/@react-native-windows-find-repo-root-38c3009e-fca9-48e2-baa8-6ced1e6de605.json
- change/@react-native-windows-fs-13a279ad-8895-440d-b70d-bd11d1f12430.json
- change/@react-native-windows-package-utils-555d2cb3-23b0-407c-8cb3-dd02e54fc31f.json
- change/@react-native-windows-telemetry-e8ff0c1b-ca70-4c93-a1fc-dea4a6dd3668.json
- change/react-native-windows-3e306a4d-b4ee-44d4-a057-6c7570ec06c8.json
- change/react-native-windows-6690dcc6-ea77-4e70-ae68-a5cf333f0aa2.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.77] Promote 0.77 to latest

- change/react-native-windows-51d9d649-258a-4b5f-9052-b30f390b76c0.json
- packages/playground/windows/playground-composition.Package/packages.lock.json
- packages/playground/windows/playground-composition/packages.lock.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ContentIslandComponentView.cpp
- vnext/Microsoft.ReactNative/packages.lock.json
- vnext/PropertySheets/WinUI.props
> [0.74] Bump to using WASDK 1.7 experimental 3

- change/@office-iss-react-native-win32-8d029fc0-83ee-4167-97e4-6255f45b1ca6.json
- change/react-native-windows-1f915c2f-4fc6-44c3-93bb-56c88eae00e1.json
- packages/@office-iss/react-native-win32-tester/overrides.json
- packages/@office-iss/react-native-win32-tester/package.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/automation-channel/package.json
- packages/@react-native-windows/tester/overrides.json
- packages/@react-native-windows/tester/package.json
- packages/@react-native/monorepo/overrides.json
- packages/@react-native/tester/overrides.json
- packages/@react-native/tester/package.json
- packages/e2e-test-app-fabric/package.json
- packages/e2e-test-app/package.json
- packages/integration-test-app/package.json
- packages/playground/package.json
- packages/sample-app-fabric/package.json
- packages/sample-apps/package.json
- packages/sample-custom-component/package.json
- vnext/overrides.json
- vnext/package.json
- yarn.lock
Integrate 0.78-rc4 (also the golden rc)
https://github.com/facebook/react-native/compare/v0.78.0-rc.3...v0.78.0-rc.4
> [0.78] Integrate 0.78-rc4

- .ado/templates/react-native-init-windows.yml
Fixes pipeline hitting a timeout
> [0.78] Increase bundle timeout

- .ado/templates/react-native-init-windows.yml
- change/@office-iss-react-native-win32-180a798f-3ded-4ed9-a85e-5c841acd3c8b.json
- change/@react-native-windows-cli-90d9d9d5-7f9c-472d-91d0-63391467995f.json
- change/@react-native-windows-codegen-93724621-56d5-41c0-b1f7-6be62c48490d.json
- change/@react-native-windows-find-repo-root-b06d4bdc-cac5-4578-9f12-5778cae65d48.json
- change/@react-native-windows-fs-a4c273de-e4e3-44b6-a480-8da7526c78fd.json
- change/@react-native-windows-package-utils-7682784b-d4da-40d4-bb06-918c57cbb17d.json
- change/@react-native-windows-telemetry-cc04da3e-c755-4ec0-9a8f-0cd42c6a2462.json
- change/react-native-windows-525e6762-fab8-4894-ba87-884b54a05395.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
Part of 78 release, promote 77 to legacy
> [0.77] Promote 0.77 to legacy

- .ado/jobs/desktop.yml
- change/@office-iss-react-native-win32-b9e6c7f5-1b5d-47ba-aaf3-c1ee07027b02.json
- change/@office-iss-react-native-win32-f3e90f45-e642-41c4-8de7-728809df3d37.json
- change/react-native-windows-392cca54-70c5-47ed-b84e-8405ffa3022f.json
- change/react-native-windows-77840265-2969-48e7-9ab2-ee5877155246.json
- change/react-native-windows-87907f23-bcef-4534-bcad-d60a91b87d2a.json
- packages/@office-iss/react-native-win32/package.json
- vnext/Desktop.ABITests/packages.lock.json
- vnext/Desktop.DLL/packages.lock.json
- vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
- vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
- vnext/Desktop.IntegrationTests/packages.lock.json
- vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
- vnext/Desktop.UnitTests/packages.lock.json
- vnext/Desktop/WebSocketResourceFactory.cpp
- vnext/Mso.UnitTests/packages.fabric.experimentalwinui3.lock.json
- vnext/ReactCommon.UnitTests/packages.lock.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
- vnext/TestWebSite/Facebook/React/Test/RNTesterIntegrationTests.cs
- vnext/TestWebSite/Microsoft.ReactNative.Test.Website.csproj
- vnext/TestWebSite/Microsoft/React/WebSocketTests.cs
- vnext/TestWebSite/Microsoft/React/WebSocketUtils.cs
- vnext/TestWebSite/Program.cs
- vnext/overrides.json
- vnext/package.json
- vnext/src-win/IntegrationTests/WebSocketMultipleSendTest.js
- yarn.lock
> [0.78] Refactor WebSocket resource class

- change/react-native-windows-58317a4c-c02e-4a5b-8cba-ed78a9e4fa26.json
- change/react-native-windows-77840265-2969-48e7-9ab2-ee5877155246.json
- vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
> [0.74] Prevent race condition in ConnectSucceeds WS unit test

- change/react-native-windows-56f137a7-212a-483c-9771-7bf7c0fad2a8.json
- change/react-native-windows-61361492-e98e-45f9-931a-795d9a86919b.json
- change/react-native-windows-984ae1a3-5950-4ab1-bebb-44b11bc5b147.json
- packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
- vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/HostPlatformColor.h
Cherrypick #14375, #14352 and #14413
> [0.74] Cherry pick changes

- .ado/release.yml
> Remove checkout from release pipeline

- packages/@react-native-windows/tester/src/js/examples/Image/ImageExample.windows.js
- packages/e2e-test-app-fabric/test/ImageComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/ImageComponentTest.test.ts.snap
- E2E Test Cases
Added missing style test cases for image
Resolves some part of https://github.com/microsoft/react-native-windows/issues/11281
**PROPS STATUS FOR IMAGE**
| Test Description | Status (Paper) | Status (Fabric) | Notes
| -- | -- | -- | --
| Style –   borderBottomColor | Not Implemented | <ul><li>[x] Completed</li></ul>
| Style –   borderBottomEndRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[x] Completed</li></ul>
| Style –   borderBottomStartRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[x] Completed</li></ul>
| Style –   borderBottomWidth | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[x]  Completed</li></ul>
| Style –   borderEndColor | Not Implemented | <ul><li>[x] Completed</li></ul>
| Style –   borderLeftColor | Not Implemented | <ul><li>[x] …
> Add E2E Image Style Pending Test Cases

- change/react-native-windows-2936f6eb-3bf6-498e-9099-202818e8cd17.json
- change/react-native-windows-8116549e-1a74-4523-8d96-8fb30f2d5ad3.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
> [0.76] Enforce SendPendingMessages in dispatch queue

- change/react-native-windows-2936f6eb-3bf6-498e-9099-202818e8cd17.json
- change/react-native-windows-52cd998c-8088-47a2-a61c-dc1ae1511b8d.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
> [0.78] Enforce SendPendingMessages in dispatch queue

- change/react-native-windows-2936f6eb-3bf6-498e-9099-202818e8cd17.json
- change/react-native-windows-b340ab45-4e2d-4b6b-81c7-7a8a6671be80.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
> [0.77] Enforce SendPendingMessages in dispatch queue

- change/react-native-windows-2936f6eb-3bf6-498e-9099-202818e8cd17.json
- change/react-native-windows-6f4e9bef-61a1-4cd8-b632-f4142ed302d7.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
> [0.74] Enforce SendPendingMessages in dispatch queue

- change/react-native-windows-2936f6eb-3bf6-498e-9099-202818e8cd17.json
- change/react-native-windows-a5dacef6-cba1-4249-b739-e16181cf4b79.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
> [0.75] Enforce SendPendingMessages in dispatch queue

- change/react-native-windows-17b0a7f2-3a73-40cf-9fb1-2a99ef16d226.json
- vnext/Microsoft.ReactNative/Fabric/ImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/ImageRequestParams.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
- vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.h
- vnext/Shared/Shared.vcxitems
- vnext/Shared/Shared.vcxitems.filters
Upstream implemented a new ImageManager::requestImage function (currently added as a stub method in our ImageManager.cpp) that we should be tracking to implement.
It also introduced a file called [ImageRequestParams.h](https://github.com/facebook/react-native/pull/47723/files#diff-9a93924193537d0e493c42162e26db6bd740a7a85ed357605c3f7a7ba107e0a1) which we will need to create aswell (currently just brought in their implementation as an override to fix import statements)
https://github.com/microsoft/react-native-windows/pull/14214
https://github.com/facebook/react-native/pull/47723 …
> [Fabric] Add ImageRequestParams for Image Component

- change/react-native-windows-7291aa87-457c-43d8-8f82-b2fedf913592.json
- vnext/Microsoft.ReactNative/CompositionSwitcher.idl
- vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
- vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
Implement maximumZoomScale and minimumZoomScale in ScrollView
Resolves https://github.com/microsoft/react-native-windows/issues/13153 ,  https://github.com/microsoft/react-native-windows/issues/13799 and https://github.com/microsoft/react-native-windows/issues/13139
Implement maximumZoomScale and minimumZoomScale in ScrollView
Implement the minimumZoomScale property for the fabric implementation of ScrollView.
This property was available in RNW Paper via ScrollViewManager.
See …
> [Fabric] Implement zoomScale, maximumZoomScale and minimumZoomScale in ScrollView

- change/react-native-windows-78019c69-0a87-4e59-b322-769bd55568e2.json
- change/react-native-windows-7a8fab5c-c63c-41d1-bef8-f3db56d78637.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
> [0.78] Implement WebSocket resource task sequencer

- change/react-native-windows-78019c69-0a87-4e59-b322-769bd55568e2.json
- change/react-native-windows-890d5e58-3b82-4251-82c1-2cd85a36f761.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
> [0.77] Implement WebSocket resource task sequencer

- change/react-native-windows-78019c69-0a87-4e59-b322-769bd55568e2.json
- change/react-native-windows-c43f132c-c1c0-4f5f-aaf3-26b2bc62a9fb.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
> [0.76] Implement WebSocket resource task sequencer

- change/react-native-windows-65df7e28-08b8-40a0-967b-6ba071cb7fcb.json
- change/react-native-windows-78019c69-0a87-4e59-b322-769bd55568e2.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
> [0.75] Implement WebSocket resource task sequencer

- change/react-native-windows-1957e4cc-78a3-4ee5-b1d4-84289638b23f.json
- change/react-native-windows-78019c69-0a87-4e59-b322-769bd55568e2.json
- vnext/Shared/Networking/WinRTWebSocketResource.cpp
- vnext/Shared/Networking/WinRTWebSocketResource.h
> [0.74] Implement WebSocket resource task sequencer

- packages/@react-native-windows/tester/src/js/examples/Touchable/TouchableExample.windows.js
- packages/e2e-test-app-fabric/test/TouchableComponentTest.test.ts
- packages/e2e-test-app-fabric/test/__snapshots__/TextComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/TouchableComponentTest.test.ts.snap
- packages/e2e-test-app-fabric/test/__snapshots__/snapshotPages.test.js.snap
- Testing
New architecture should reach 100% testing coverage. 
https://github.com/microsoft/react-native-windows/issues/12466
- TouchableOpacity should fire action upon press.
- TouchableOpacity should fire action upon onPressIn.
- TouchableOpacity should not be interactable when disabled.
E2E Test app tests.
> Add Functional Touchable* Tests

- change/react-native-windows-4e06df5c-549e-4b50-a7d7-d541d9f5bf08.json
- vnext/Microsoft.ReactNative/Fabric/Composition/ReactNativeIsland.cpp
> [0.76] Fix initialProps

- .ado/jobs/desktop.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/stages.yml
- .ado/templates/react-native-init-windows.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/write-certificate.yml
This PR cherry-picks (parts of) the following commits to unblock CI in 0.73:
* https://github.com/microsoft/react-native-windows/commit/3a5ca66aab21739e168bd7d236de2f420bf3090c
* https://github.com/microsoft/react-native-windows/commit/3534af4fdfb0e5b73b1ecf6b3da6c48f129d008b
* https://github.com/microsoft/react-native-windows/commit/5fad854368beb3bee4a1526bb7fc97ad0f7bf8ad
* https://github.com/microsoft/react-native-windows/commit/b563af70ec4e953654881677ce06e31a0fd7b990
* https://github.com/microsoft/react-native-windows/commit/4dc7e13a5de99b95f76c058f43474dccded41ac5
> [0.73] Fix CI ***NO_CI***

- .ado/jobs/desktop.yml
- .ado/jobs/e2e-test.yml
- .ado/jobs/macos-tests.yml
- .ado/jobs/playground.yml
- .ado/jobs/sample-apps.yml
- .ado/stages.yml
- .ado/templates/react-native-init.yml
- .ado/templates/run-windows-with-certificates.yml
- .ado/templates/write-certificate.yml
- change/react-native-windows-d2569c0d-f6e9-490b-9885-d60db7d45397.json
- vnext/Folly/TEMP_UntilFollyUpdate/Conv.h
- vnext/PropertySheets/React.Cpp.props
This PR cherry-picks (parts of) the following commits to unblock CI in 0.72:
* https://github.com/microsoft/react-native-windows/commit/3a5ca66aab21739e168bd7d236de2f420bf3090c
* https://github.com/microsoft/react-native-windows/commit/3534af4fdfb0e5b73b1ecf6b3da6c48f129d008b
* https://github.com/microsoft/react-native-windows/commit/5fad854368beb3bee4a1526bb7fc97ad0f7bf8ad
* https://github.com/microsoft/react-native-windows/commit/b563af70ec4e953654881677ce06e31a0fd7b990
* https://github.com/microsoft/react-native-windows/commit/4dc7e13a5de99b95f76c058f43474dccded41ac5
* https://github.com/microsoft/react-native-windows/commit/ac3fb0736115294088207980c644ed32a5782607
> [0.72] Fix CI ***NO_CI***

- change/react-native-windows-5703a6a9-97cc-48bb-b2d3-95a626c17fa1.json
- vnext/stubs/glog/logging.h
> Fix unreferenced parameter warning in glog stub

- change/react-native-windows-ab2e6413-5ba1-44e3-8e92-007ed300d1d3.json
- vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
Backport https://github.com/microsoft/react-native-windows/pull/14716
> [0.79] Backport "Fix blob module in paper (#14716)"

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
- .github/ISSUE_TEMPLATE/integration-follow-up.yaml
- .github/ISSUE_TEMPLATE/missing-api.yaml
This PR cleans up our existing GitHub issue templates to remove prompts for unnecessary information while also making some prompts required and harder to ignore, to reduce the amount of time we send back issues for more information.
This PR also adds a new "Missing API" template to capture when expected React Native APIs aren't present on Windows.
See above.
See above.
N/A
N/A
> Update GitHub issue templates

- change/@office-iss-react-native-win32-8b573c7e-74a7-4ecf-bfb6-f1b04ad01c70.json
- change/@react-native-windows-cli-a8b91e8b-d7cf-4ecb-8ba7-fef0ac962c7d.json
- change/@react-native-windows-codegen-0acd30f6-20ad-421a-9168-085211710875.json
- change/@react-native-windows-find-repo-root-1454aba5-6093-4fbe-8c74-3bd0c4c28938.json
- change/@react-native-windows-fs-d6313b2a-7aaf-4875-beb2-935e5c2c1bc7.json
- change/@react-native-windows-package-utils-2220a78c-df69-4d1e-8c16-d9b3830f0527.json
- change/@react-native-windows-telemetry-b26bbf2e-09dd-408b-9f2c-dcc05a76d138.json
- change/react-native-windows-a6d91914-2404-4aa3-8293-42ab5a4f7d7c.json
- packages/@office-iss/react-native-win32/package.json
- packages/@react-native-windows/cli/package.json
- packages/@react-native-windows/codegen/package.json
- packages/@react-native-windows/find-repo-root/package.json
- packages/@react-native-windows/fs/package.json
- packages/@react-native-windows/package-utils/package.json
- packages/@react-native-windows/telemetry/package.json
- vnext/package.json
> [0.78] Promote 0.78 to legacy

- change/react-native-windows-cc8b0e86-24d1-43aa-aa15-6acabf669ade.json
- vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
> [0.78] Remove .. usage in relative include

- change/@office-iss-react-native-win32-bb6fa6c4-c41b-4046-b2ae-85ecf4c26fa5.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src-win/Libraries/LogBox/UI/LogBoxInspectorSourceMapStatus.win32.js
Remove usage of Animated in LogBox
> [0.78] [win32] Remove usage of Animated in LogBox

- change/@office-iss-react-native-win32-5cee5130-421d-42b2-bb6a-1f5a1767fa2b.json
- packages/@office-iss/react-native-win32/overrides.json
- packages/@office-iss/react-native-win32/src-win/Libraries/LogBox/UI/LogBoxInspectorSourceMapStatus.win32.js
> [win32] Remove usage of Animated in LogBox 

- change/@rnw-scripts-generate-release-notes-d4a4f9cb-19ee-4dac-a467-95b8a8365643.json
- packages/@rnw-scripts/generate-release-notes/ReadMe.md
- packages/@rnw-scripts/generate-release-notes/generate-release-notes.js
Updates documentation and ReadMe for release notes creation
Resolves -
Updates documentation and ReadMe for release notes creation
N/A
N/A
Add a brief …
> Update ReadMe for Release Notes Generation Script

- .github/copilot-instructions.md
Resolves #14958
Added a new instructions file for copilot
N/A
N/A
> Create .github/copilot-instructions.md file for React Native Windows with PR workflow commands

- .github/workflows/update-issue-remaining-days.yml
- Automation (AI changes or Github Actions to reduce effort of manual tasks)
To reduce manual effort
Resolves #15024
Added a github action workflow for https://github.com/orgs/microsoft/projects/183
N/A
N/A
Should this change be included in the release notes: …
> Add automation script to update Remaining days to 0 whenever an issue is closed

- change/@react-native-windows-cli-ad8ed85a-451b-47d6-a259-31f85bf5072d.json
- change/react-native-windows-de92b10b-43d7-4e24-9d2e-f19b6b396aa8.json
- packages/@react-native-windows/cli/src/commands/initWindows/initWindowsOptions.ts
- vnext/templates/cpp-app/template.config.js
- vnext/templates/old/generateWrapper.js
- vnext/templates/old/uwp-cpp-app/template.config.js
Cherrypicks https://github.com/microsoft/react-native-windows/pull/15085 to stable branch
-----------------------------------------------------------------------------------------------------
Reverts microsoft/react-native-windows#15011
Re-apply 270f785bd1e6b65671866b48a196a5cbc51f0ca7
> [Cherry-pick] Revert and Reapply PRs with respect to fabric default in 0.80
