package.json, yarn.lock
handlebars before v4.7.7 are vulnerable to Remote Code Execution (RCE) when selecting certain compiling options to compile templates coming from an untrusted source. This PR bumps the version of handlebars we use to 4.7.7 using yarn resolutions. We have to use yarn resolutions because the root dependency for handlebars, just-scripts, has not yet been updated to use handlebars v4.7.7.
=> Bump handlebars to 4.7.7.

package.json, yarn.lock
There is a security vulnerability in xmldom versions below 0.5.0. This PR adds a yarn resolution to force xmldom to be at 0.5.0.
The dependency chain that brings in the vulnerable xmldom is as follows: react-native@0.0.0-d477f8011 -> @react-native-community/cli-platform-ios@^5.0.1-alpha.0 -> xcode@^2.0.0 -> simple-plist@^1.0.0 -> plist@^3.0.1 -> xmldom "0.1.x. So bumping the xmldom used here would require considerable work, which is why we use yarn resolution here.
Backport of #7514.
=> [0.64] Force xmldom to version ^0.5.0.

change/react-native-windows-a3b2efc1-a095-4e99-be23-627563c4674c.json, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
Some warnings were disabled in #6984, they can be reenabled thanks to a fix upstream: https://github.com/facebook/react-native/pull/31002.
Closes #6986.
=> Removing some disable warnings due to fix in RN 

package.json, yarn.lock
handlebars before v4.7.7 are vulnerable to Remote Code Execution (RCE) when selecting certain compiling options to compile templates coming from an untrusted source. This PR bumps the version of handlebars we use to 4.7.7.
Backport of #7583.
=> [0.63] Bump handlebars to 4.7.7.

package.json, yarn.lock
I used yarn resolutions to bump the version of handlebars in #7583 . This is actually unnecessary and this PR removes the resolution usage.
=> Remove unnecessary use of yarn resolution.

package.json, yarn.lock
handlebars before v4.7.7 are vulnerable to Remote Code Execution (RCE) when selecting certain compiling options to compile templates coming from an untrusted source. This PR bumps the version of handlebars we use to 4.7.7.
Backport of #7583.
=> [0.64] Bump handlebars to 4.7.7.

README.md
`Good First Task` label was recently changed to [`good first issue`](https://github.com/microsoft/react-native-windows/labels/good%20first%20issue) to match GitHub's preferences. This updates a link in README to reflect that change.
=> README update for `good first issue` label

change/react-native-windows-1fda6013-a5ec-4ebc-8298-dfeab73f228a.json, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
Fixes #7576 (backport of #7577 to 0.64)
=> [0.64] Enable any platform color to be used in PlatformColor()

change/react-native-windows-f78483b0-732a-44b0-98f4-7becc372e8e3.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Shared/BatchingMessageQueueThread.h, vnext/Shared/Threading/BatchingQueueThread.cpp, vnext/Shared/Threading/BatchingQueueThread.h
Fixes #7543.
When running in release mode, we run a bunch of native modules as JSI modules.  When making a call from JS -> Native using a native module, this triggers a new UI batch.   When going through a JSI module, this doesn't happen.  
This change causes any call to BatchingMessageQueueThread to cause a new batch to happen.
=> Calling UIManager.dispatchViewManagerCommand doesn't trigger a UI update

.ado/templates/build-rnw.yml, .ado/windows-vs-pr.yml, change/@react-native-windows-cli-c72ce637-d6f6-44cc-ab0d-4cdac7419cea.json
This PR adds auto-generating the WinRT API docs in CI so they can be plopped over on the website repo (it will show up in the build's artifacts)
=> [0.64] Generate WinRT docs in CI

change/react-native-windows-f78483b0-732a-44b0-98f4-7becc372e8e3.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Shared/BatchingMessageQueueThread.h, vnext/Shared/Threading/BatchingQueueThread.cpp, vnext/Shared/Threading/BatchingQueueThread.h
Port of #7575 to 0.64
This fixes some cases where UI updates are not reflected immediately due to a queue not getting flushed when it should.
=> [0.64] Calling UIManager.dispatchViewManagerCommand should trigger updates

change/react-native-windows-d484dd4c-0884-428b-9f78-a4e81ae18e7e.json, vnext/Microsoft.ReactNative/Modules/ReactRootViewTagGenerator.h, vnext/ReactCommon/ReactCommon.vcxproj, vnext/Shared/DevSupportManager.cpp
Re-enabling some SDL warnings that are required per SDL. Thanks to a fix [upstream](https://github.com/facebook/react-native/pull/31002), these are no longer needed.
=> Restore Some SDL Warnings

change/react-native-windows-4ce5570d-3577-4e55-9aff-a07ec887c09f.json, vnext/Mso/cppExtensions/autoRestore.h, vnext/Mso/debugAssertApi/debugAssertDetails.h, vnext/Mso/motifCpp/motifCppTest.h, vnext/Mso/smartPtr/smartPointerBase.h, vnext/Shared/Executors/WebSocketJSExecutor.cpp
Re-enabling some warnings that are required per SDL - going towards #6918. C4996, C4700, and C4611 were no longer needed. C4244 fixed with an explicit static cast to int. 
The only remaining suppressions blocking us from SDL compliance are coming from folly(4244 and 4267 being set off from ToAscii.h), which I will address next.
=> Restoring warnings for SDL compliance

change/react-native-windows-5eed73aa-6cf2-4940-9e6e-d2ae1d5b0740.json, change/react-native-windows-e07fd82b-045a-44b9-a416-642e23b1ff67.json, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
* Suppress onLayout event when layout has not changed
Yoga sometimes sets `hasNewLayout` on nodes even when their layout has
not changed. One common case where this occurs is in lists. Any time the
parent container of a list is dirtied, even for something that does not
affect it's dimensions, all elements in the list go through a layout
pass and set `hasNewLayout`. This change at least reduces the number of
events sent to JS when layout has not really changed, though a more
effective fix would be to have Yoga be a little smarter about when to
layout. If you're interested, here's where Yoga decides to update layout
on all stretch aligned children of a parent container:
https://github.com/facebook/yoga/blob/master/yoga/Yoga.cpp#L3104-L3107
iOS and Android already do this, so this change …
=> [0.64] Suppress onLayout event when layout has not changed (#7470)

change/react-native-windows-b3c2f4a8-d704-4a38-b837-993459d15495.json, change/react-native-windows-f478c436-a66f-4944-b578-80fea3b12488.json, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
* Change TextInput cursor behavior
As stated in issue #7283, the cursor position changes seem to be
somewhat different on each platform. Since we're already adding code in
react-native-windows to change the Windows default cursor positioning
behavior, we might as well make it a bit more consistent with other
platforms. The change here matches the behavior on iOS, macOS and Web
(so it's only different from Android, which seems to keep cursor
position relative to the TextInput value length constant).
Fixes #7283
* Change files
Closes #7608
=> [0.64] Change TextInput cursor behavior (#7285)

change/react-native-windows-049db1de-5833-4cb0-a208-fec0fa53e060.json, packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js, vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp, vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.h, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp, vnext/src/Libraries/Components/TextInput/TextInput.windows.js
This change adds two new props and a new behavior for multiline TextInput.
New props:
1. `clearTextOnSubmit`: similar to `clearTextOnFocus`, except that it clears out the TextInput whenever the `onSubmitEditing` event would be dispatched.
2. `submitKeyEvents`: registers a set of key down events that will trigger `onSubmitEditing` for multiline TextInput.
New behavior:
Previously, `onSubmitEditing` would never fire when `multiline={true}` for a TextInput. Now, `onSubmitEditing` may fire for a multiline TextInput if a key down event matching the configuration in `submitKeyEvents` is observed.
Fixes #7330
=> Adds declarative props to clear/submit TextInput

.ado/jobs/desktop.yml, .ado/jobs/universal.yml
This change re-enables the CG checks for CI/PR builds. The builds won't
fail on an alert, but the alerts will be raised so we can work to fix
them before a release.
Closes #7261
=> Re-enabling CG checks in CI/PR

.ado/windows-vs-pr.yml
This change re-enables the CG checks for PR builds. The builds won't
fail on an alert, but the alerts will be raised so we can work to fix
them before a release.
Closes #7261
=> [0.64] Re-enabling CG checks in PR

change/react-native-windows-1a01dcab-b7ee-4d5c-8afd-b230de0b44ce.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp, vnext/Microsoft.ReactNative/ReactApplication.cpp, vnext/Microsoft.ReactNative/RedBox.cpp
This introduces some changes required for Reunion:
- removed app lifecycle events (Suspending/UnhandledException)
- ensure we call EnsureCoreWebView2 before we show the error text in RedBox (filed a doc bug too since this isn't documented)
=> Reunion prep

change/react-native-windows-a83fe313-38da-4b46-a583-6f8346f1d41b.json, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
The 'autoFocus' feature is a useful way to ensure the TextInput gets focus as soon as it comes into view. This change implements autoFocus by storing a boolean in the shadow node and calling Control::Focus on the TextBox or PasswordBox in the Loaded event. FocusState::Keyboard is used because this is the same state the [UIManager uses](https://github.com/microsoft/react-native-windows/blob/2c5ba22a3cfa4447dd227b4f7274c882e1786fed/vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp#L1103).
See https://reactnative.dev/docs/textinput#autofocus
Fixes #2198
=> Adds 'autoFocus' prop to TextInput

packages/e2e-test-app/windows/ReactUWPTestApp/MainPage.xaml
Fixes #7130
Should lead to test stability when the window is resized.
=> Set Fixed RootView Width in E2ETest

change/@rnw-scripts-integrate-rn-1b977494-5cfd-40f4-b3cd-937b35bd3e6d.json, packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts, packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
Fixes #7485
RN prereleases can contain breaking changes. Make sure to update the peerDependency if we take in a new one, to ensure users see warnings if they include too old a version.
=> Bump RN peerDependency whenever it is prerelease

change/@office-iss-react-native-win32-66cdc8c8-5b8e-4fa6-a5e1-8d56ed4177d9.json, change/react-native-windows-9f1234cc-6092-4410-96b3-e5c042444d04.json, packages/@office-iss/react-native-win32/package.json, packages/e2e-test-app/package.json, packages/integration-test-app/package.json, packages/playground/package.json, packages/sample-apps/package.json, vnext/package.json, yarn.lock
Fixes #7467
No need to backport since we do not export these types. Only use them as an internal devDependency.
=> Update to latest @types/react-native

.ado/jobs/desktop.yml, .ado/jobs/universal.yml, .ado/publish.yml, .ado/templates/component-governance.yml
This PR consolidates some of the logic for running the Component Governance task into `templates\component-governance.yml`.
Specifically, the logic that, if EnableCodesign == true, CG must fail the job if there are any alerts. FYI, in our whole ecosystem of pipelines, EnableCodesign should only be true in the Publish pipeline against stable branches.
This PR also adds a CG check _before_ beachball bump in Publish, so the publish can be aborted without publishing to NPM and GitHub.
=> Moved Component Governance task into template

change/@react-native-windows-cli-21b8c27c-4f1b-459e-a14e-52a01774729b.json, change/react-native-windows-286084fd-2a87-474f-9806-269f85faf51e.json, packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap, vnext/template/shared-app/proj/ExperimentalFeatures.props
These links don't work until 0.65 is published. We might be able to do permalinks for this later (esp with docusaurus V2) but for now, remove the version.
=> Remove version from ExperimentalFeatures.props links 

change/react-native-windows-743fdc9e-558b-4827-9385-81d7b9fb9a41.json, vnext/template/shared-app/proj/ExperimentalFeatures.props
These links don't work until 0.65 is published. We might be able to do permalinks for this later (esp with docusaurus V2) but for now, remove the version.
Fixes #7427
=> [0.64] Remove version from ExperimentalFeatures.props links

change/react-native-windows-49eeaa07-349c-4d1f-8915-608df3e8bc01.json, vnext/PropertySheets/Autolink.props, vnext/PropertySheets/Bundle.Common.targets
Fixes #7597
We're passing raw strings into the exec string for running commands from MSBuild. Paths with spaces will be interpreted as multiple CLI args. Wrap paths in quotes to fix paths with spaces.
=> Fix MSBuild Bundling When Path Contains Spaces

.ado/publish.yml, .ado/templates/component-governance.yml, .ado/windows-vs-pr.yml
This PR backports #7686 to 0.64.
Original message:
This PR consolidates some of the logic for running the Component Governance task into `templates\component-governance.yml`.
Specifically, the logic that, if EnableCodesign == true, CG must fail the job if there are any alerts. FYI, in our whole ecosystem of pipelines, EnableCodesign should only be true in the Publish pipeline against stable branches.
This PR also adds a CG check _before_ beachball bump in Publish, so the publish can be aborted without publishing to NPM and GitHub.
=> [0.64] Moved Component Governance task into template (#7686)

change/@office-iss-react-native-win32-5bc205b1-20a9-4f4b-8adb-032b9febbebd.json, change/react-native-windows-75512eb9-5b0d-4789-b68e-6c0358fb8aee.json, packages/@office-iss/react-native-win32/overrides.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js, vnext/overrides.json, vnext/src/Libraries/Components/View/View.windows.js
Fixes #5843
It's been two versions since yellowbox and one since redbox. Remove the forking to catch users using the unsupported prop.
=> Remove Forking Due to "acceptsKeyboardFocus" Invariant Checks

packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx, packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
Recent [change](https://github.com/microsoft/react-native-windows/pull/7683) to set a fixed width for RootView in E2E fixes the inconsistency for width in CI vs local -- closes #7589.
=> Visual tests: snapshot update accounting for fix in width inconsistency. 

.ado/publish.yml
I think this needs to be in place _before_ we create the 0.65-stable branch, otherwise the scheduler won't pick it up.
=> Prep for 0.65 by adding 0.65-stable to publish scheduled branch filter

packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
Added examples to RNTester:
- Created a new example showing how to use a combination of `onKeyDownCapture` and `e.stopPropagation()` to intercept routed React events - details in the example description;
=> Add onKeyDownCapture examples to RNTester.

change/react-native-windows-cb98b272-df33-4b32-b571-f8796d620d35.json, vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
At least on the keyboard I tested on, virtual key 192 maps to `Backquote`, which is already configured on L367. Seems like this may have been included by mistake.
=> Remove incorrect mapping from virtual key 192

change/react-native-windows-41786510-3be7-441f-81e2-882e46ed5bf7.json, packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Since the default LineStackingStrategy for XAML TextBlock uses`LineStackingStrategy::MaxHeight`, when the <Text> `lineHeight` prop is set to a value smaller than the calculated max height for the text, it is ignored.
Setting LineStackingStrategy to `LineStackingStrategy::BlockLineHeight` enables `lineHeight` settings smaller than the font height, and has identical behavior when the `lineHeight` value is larger than the max font height.
Fixes #7695
=> Allow `lineHeight` settings less than font height

change/react-native-windows-a94bcf82-c2c3-467a-b720-c0903f97cbd9.json, vnext/Folly/Folly.vcxproj, vnext/Folly/TEMP_UntilFollyUpdate/dynamic.cpp, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Adds two forked folly files in order to re-enable C4244 and C4267 warning suppressions. I opened a [PR in folly](https://github.com/facebook/folly/pull/1565) to address this from there, and will add an issue to track updating folly and removing these files. 
Closes #6918.
=> SDL Compliance Completion

change/react-native-windows-4062d121-1aa5-49ae-b74c-861571c1fcd5.json, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
Fixes #7640 
The brush cache was keeping weak pointers to the brushes it returned. However upon a theme change, XAML will recreate the theme brushes in the Application resources, but those were not being transferred back onto the app's UI elements.
The fix is to listen for theme events and shuttle the color values for `SolidColorBrush` instances between the new values and the values we have in the cache (which are what the UI will use).
We have to do this ourselves as opposed to relying on XAML to propagate the brushes, because the UI elements are all created dynamically and can't use the markup `ThemeResource` construct.
With this change, an element that uses PlatformColor( ... ) with a Brush name that is a solid color, will correctly update upon a theme refresh. If the brush is not a …
=> Update PlatformColor brushes upon theme change

.ado/publish.yml
If the last commit was from the React-Native-Windows Bot and includes `***NO_CI***` in the subject line, throw an error so the pipeline stops before wasting time building, or worse, trying to publish.
Closes #7547
=> Add check to cancel publish if the last commit was itself a publish

change/react-native-windows-9aaace3c-20a8-4c24-90b2-d777742f65ba.json, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp, vnext/src/Libraries/Components/TextInput/TextInput.windows.js
Port #7658 to 0.64
This issue affects some basic functionality of TextInput, so should be backported to 0.64.
=> [0.64] Controlled TextInput doesn't work most of the time

.ado/publish.yml
This PR backport #7716 to 0.64.
If the last commit includes `***NO_CI***` in the subject line, throw an error so the pipeline stops before wasting time building, or worse, trying to publish.
Closes #7547
=> [0.64] Add check to cancel publish if the last commit was itself a publish (#7716)

change/react-native-windows-e84bc040-e439-490a-9ecc-25bbfc3bace2.json, packages/sample-apps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp, vnext/Microsoft.ReactNative.Cxx/ReactContext.h, vnext/Microsoft.ReactNative/XamlUIService.cpp
Current `ReactContext::DispatchEvent` method in `Microsoft.ReactNative.Cxx` C++ helper classes project has a bug that it wraps up arguments into an array. It make it impossible to use for the custom view implementation. It is a lower impact change because all current custom view implementations use the `IReactContext` interface as it was shown in our C++ library samples project. Also, we have deprecated the `IReactContext::DispatchEvent` method in 0.64. At some point we must deprecate the `ReactContext::DispatchEvent` method as well, but for now we just fix it until we have a helper class for the `XamlUIService`.
These PR has the following changes:
- Fixed `ReactContext::DispatchEvent` and changed it to use the `XamlUIService::DispatchEvent`.
- Improved the `XamlUIService::DispatchEvent` …
=> Fix ReactContext::DispatchEvent

change/react-native-windows-2237dc3b-a41e-4123-82db-f5b24fbba30b.json, packages/playground/windows/playground/packages.config, vnext/src/Libraries/Components/Button.windows.js
**_Why_**
Current styling for button control matches android styling. Adjustments here alter styling so that it will match WinUI/MUX button styling.
**_What_**
- Adjusted Button's background color, text color, disabled background color, and disabled text color.
- Needed to create a separate return for the WinUI/MUX case, since adjustments to underlayColor and styles were needed to match styling for pressed Button state. 
Note: Unable to match styling to exactly match  Button due to RNW styling constraints. Missing styling includes: Button Animations.
Note: Current available brushes follow the coloring of v2.5, will automatically upgrade to 2.6 coloring when RNW runs on v2.6.
Note: The coloring of the Button control is different for MUX 2.5 vs WinUI 2.5. Right now playground uses MUX 2.5 …
=> Update Button Styling for Windows

change/react-native-windows-60609fec-a316-43d0-b789-deb31e09b2f7.json, packages/e2e-test-app/test/LegacyTextInputTest.test.ts, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Previously, TextInputViewManager subscribed to two events to implement `onChangeText`:
1. TextChanging - used to increment a native counter to ensure JS changes to text do not overwrite native changes to text.
2. TextChanged - used to emit the `onChangeText` event and surprisingly also incremented the native counter.
Additionally, the view manager subscribed to SelectionChanged to emit the `onSelectionChange` event.
In XAML, the sequence of native events is as follows:
1. TextChanging
2. SelectionChanged
3. TextChanged
Since we emit the event that ultimately triggers `onChangeText` via the TextChanged native event, this means that we actually receive the cursor position change before the text change. This is different from other React Native platforms and makes it more difficult to …
=> Emit TextInput onChangeText before onSelectionChange

change/react-native-windows-04a0b9fb-d242-443b-9ec6-9cc2870bbe85.json, vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
In `RawTextViewManager::NotifyAncestorsTextChanged` there's a while loop that goes up the parent tree of a `RawTextShadowNode`, when a leaf text value gets updated.
We can break out of this loop, once we have reached the parent `<Text>`, i.e. the XAML TextBlock, rather than traversing all the way up to the react root node.
(We enter this condition on line 71: `if (!std::wcscmp(nodeType, L"RCTText"))`.)
=> Optimize textTransform parent traversal.

change/react-native-windows-802ab7c2-4c7e-4d56-90f9-818472447a8c.json, vnext/Microsoft.ReactNative/Fabric/ViewComponentView.cpp, vnext/Microsoft.ReactNative/Fabric/ViewComponentView.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp, vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp, vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.h, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.h, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
This adds support for View.opacity and View.borderRadius properties.
The opacity change is pretty simple.
Hooking up borderRadius was more work though.  Panel which is what view is implemented on doesn't support borderRadius properties, so to implement borderRadius ViewPanel adds a border element around the panel element.  To get this to properly inject in the UI tree requires logic outside of ViewPanel.  In paper this is done inside the ViewManager.  -- that code is pretty hard to shared between the view manager and the fabric viewcomponent.  So there is some duplication of the logic.   I did extract the TransferProperties function at least.
=> Fabric: Add support View.opacity and View.borderRadius

change/react-native-windows-17c03193-3fbf-480e-ae5a-0fdc80198079.json, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
A fix for transitive winmd dependencies for C++/WinRT apps was also applied to C# apps, which causes runtime errors when consuming transitive dependencies such as Microsoft.UI.Xaml.Markup.
Closes #7764
=> Fix transitive dependencies for C# nuget-based apps

change/react-native-windows-04b9c2df-23f5-477f-a5ba-82830126ca11.json, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
This PR backports #7786 to 0.64.
A fix for transitive winmd dependencies for C++/WinRT apps was also
applied to C# apps, which causes runtime errors when consuming
transitive dependencies such as Microsoft.UI.Xaml.Markup.
Closes #7764
=> [0.64] Fix transitive dependencies for C# nuget-based apps #7786

change/@rnw-scripts-create-github-releases-66a4f00b-4060-4b68-af9d-db87150537ff.json, packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
Fixes #7429
Still needs testing, but this should lead to release notes linking to the much more detailed, intitial curated notes. The latest version of this tool is automatically pulled in by older branches, so no need to backport.
=> Link to curated release notes in patch release notes

change/react-native-windows-b9691dda-2b02-4670-a043-8ecd90525929.json, vnext/Microsoft.ReactNative/Fabric/ActivityIndicatorComponentView.cpp, vnext/Microsoft.ReactNative/Fabric/ImageComponentView.cpp, vnext/Microsoft.ReactNative/Fabric/ParagraphComponentView.cpp, vnext/Microsoft.ReactNative/Fabric/ViewComponentView.cpp, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.h, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Float.h, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/conversions.h, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/platform/cxx/react/renderer/graphics/Color.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Utils/ValueUtils.h, vnext/overrides.json
This overrides the implementation of the native fabric Color object to add support for PlatformColor.
The Color object is already platform specific with a different implementation on ios than on android.
=> [Fabric] Add support for PlatformColor

change/react-native-windows-e5ae44de-62f6-4114-8c1d-028cf9ca9fd2.json, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
The `eventName` parameter is std::move'd into the BatchedEvent object that gets enqueued. As such, the event removal test `evt.eventName == eventName` was always false because `eventName` had been moved.
=> Fixes bug in BatchingEventEmitter

change/react-native-windows-802e1a1f-0feb-43da-ac1c-e81018aa3e62.json, vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
The default value of this is true in core -- we should align.
=> I18n.AllowRTL should default to true

change/@office-iss-react-native-win32-7c50c1a8-c6c6-44d4-bdb1-2d906f8cf9cc.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Adding the `accessibilityControls` to ViewWin32. This prop acts as [aria-controls ](https://www.w3.org/TR/wai-aria-1.1/#aria-controls). 
This prop is needed for a new Win32 JS Control being developed, Live Persona Picker (People Picker). This JS LPP component is a dropdown list that displays after a user types '@' in a textbox. This will be used for WIn32, and thus, we need to send this prop over the bridge so the Native side can set the ControllerForSource object on both (Textbox+LPP) components. 
This ControllerForSource object is needed because when scrolling through the LPP list, focus isn't actually on the list, it's on the textbox, so how will a screen reader know what to read? This allows the screen reader to subscribe to events on the list. See more about [ControllerFor here. …
=> Adding Accessibility Prop on ViewWin32

change/react-native-windows-e7751624-0752-4e22-9095-937978ff2335.json, packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextBackgroundColorTestPage.tsx, packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx, packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/TextColorBackground.json, packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj, packages/E2ETest/windows/ReactUWPTestApp/TreeDumpControlViewManager.cs, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Backport: Fix Text.BackgroundColor overwriting foreground. (#7707)
* Change files
* Fix Text.BackgroundColor overwriting foreground prop.
* Update snapshot.
* fix optional param.
Co-authored-by: Igor Klemenski <igklemen@microsoft.com>
=> [0.64] Fix Text.Color not working with backgroundColor

change/react-native-windows-7120ebe6-957e-4ec9-84db-a461cf12802b.json, packages/@react-native/tester/js/examples/PanResponder/PanResponderExample.js, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
This change adds event coalescing to onTouchMove events. The previous implementation of BatchingEventEmitter expected a view tag and event name to perform coalescing. This change generalizes the batching event emitter to accept a coalescing key instead, which simply concatenates the event name and the view tag in the case of ScrollViewViewManager and the event name and the pointer ID in the case of TouchEventHandler. This change also modified the signature of Emit(Coalescing)JsEvent to accept a folly::dynamic rather than a JSValue, as the arguments sent to the `RCTEventEmitter.receiveTouches` JS function do not exactly match the arguments sent to `RCTEventEmitter.receiveEvent`.
Fixes #7276
=> Adds event coalescing to TouchEventHandler

.ado/templates/prepare-env.yml
Adding the UWP versions to the diagnose machine info, so it will be easier to see find new versions deployed on the vm's.
=> Add UWP sdk version diagnostics to prepare-env

change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json, vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
The `JSValue` move constructor did not call the destructors for Object, Array, and String types. As a result, some collection artifacts were not correctly destroyed. They were most probably used only for debugging.
The fix is simple: call the `other` destructor in the move constructor. After the call the `other` becomes a `JSValue::Null` value.
Thanks a lot to @OleksandrDorosh who found and  reported the issue!
Fixes #7827
=> Fix JSValue memory leak in move constructor

change/react-native-windows-226e1de5-e19b-44dc-a44a-cd8bc20fd68c.json, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props
Hermes inspector was broken with Hermes v0.8 package as some changes were not correctly integrated from 0.7 branch. We've fixed it in the latest Hermes 0.8 package. This PR bumps the version of Hermes package used in RNW.
=> Fixing inspector with Hermes v0.8

change/react-native-windows-51bbc131-2b1c-465c-b2a8-b06ce1e6b002.json, vnext/Directory.Build.targets
Fixes #7866
Discovered this logic, which paves our PCH's after build, specifically when running on CI machines (`Condition="'$(AGENT_ID)' != ''"`)
This was added when our specific infra was running into file-size issues with E2ETest, and a second VS toolset. It is really specific to what our environment was seeing, and really shouldn't be run on every user build.
We've since then alleviated our own CI setup issues, and reduced our disk footprint on PCHs and other binaries. Removing this logic unless we see new disk space issues.
=> Native build logic shouldn't delete PCH on build for all CI machines

change/react-native-windows-226e1de5-e19b-44dc-a44a-cd8bc20fd68c.json, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props
This is cherry-picking the commit that has already gone into main branch.
* Hermes inspector was broken on Hermes v0.8 package as some changes were not correctly migrated from 0.7 branch.
* Change files
=> [0.65] Fixing inspector with Hermes v0.8 (#7852)

.ado/jobs/playground.yml
**_What_**
Fix Error in CI Pipeline for Playground "Set Up Certificate Task". Change in #7743 did not contain quotes around secret leading to syntax error when Continuous pipeline was run.
=> Fix Error in CI Pipeline for Playground Set Up Certificate Task

change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json, vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
Fixes #7871 
Today when a native module calls an API that expects to be called on the UI thread, from the JS thread, an exception is raised and the app is forcefully terminated. This is because native module methods are `noexcept`.
This change adds some guardrails for developers to indicate what the issue was, and points them to our new documentation about posting work to the UI dispatcher.
=> Provide error message when an unhandled exception occurs in a native method (in Debug)

change/react-native-windows-51bbc131-2b1c-465c-b2a8-b06ce1e6b002.json, vnext/Directory.Build.targets
* Native build logic shouldn't delete PCH's on all CI machines
Fixes #7866
Discovered this logic, which paves our PCH's after build, specifically when running on CI machines (`Condition="'$(AGENT_ID)' != ''"`)
This was added when our specific infra was running into file-size issues with E2ETest, and a second VS toolset. It is really specific to what our environment was seeing, and really shouldn't be run on every user build.
We've since then alleviated our own CI setup issues, and reduced our disk footprint on PCHs and other binaries. Removing this logic unless we see new disk space issues.
* Change files
=> [0.65] Native build logic shouldn't delete PCH on build for all CI machines (#7874)

change/react-native-windows-fb507b4a-50b0-480f-bf49-e8ad0ca6f888.json, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Shared/Modules/WebSocketModule.cpp, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
Exceptions on member construction (i.e. `m_uri`) were crashing the host process due to public `WinRTWebSocketResource` constructors being marked as `noexcept`.
This change removes the `noexcept` qualifier from those constructors, allowing the eventual `winrt::hresult_error` exceptions to be correctly handled by the owning object (i.e. `WebSocketModule`).
This change is critical to correctly handle corner cases like extraneous or empty strings passed to the WebSocket connection URL so backports down to `0.63-stable` are requested.
**Note** the modified APIs are not exposed to the export layer, so this change should be transparent to any consuming application.
=> Allow propagating WinRTWebSocketResource constructor exceptions

change/react-native-windows-528a6d68-44a6-40ab-8e25-63b25356b527.json, change/react-native-windows-fb507b4a-50b0-480f-bf49-e8ad0ca6f888.json, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Shared/Modules/WebSocketModule.cpp, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
=> [0.65] Allow propagating WinRTWebSocketResource constructor exceptions

change/react-native-windows-6ba7b85f-119d-450d-a7e6-4aebe3e23210.json, change/react-native-windows-fb507b4a-50b0-480f-bf49-e8ad0ca6f888.json, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Shared/Modules/WebSocketModule.cpp, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
=> [0.64] Allow propagating WinRTWebSocketResource constructor exceptions

.ado/jobs/playground.yml
**_Why_**
CI Pipeline is failing for playground Win32 build with error "appx cannot be uploaded because package cannot be found". 
**_What_**
VS build for playground Win32 configuration does not produce an Appx package. Added a new variable to playground pipeline to specify which builds should run the task to upload their Appx. All Universal configurations will upload. All Win32 configurations will not. 
Fixes #7907
=> Specify Upload Appx Conditions for Playground Pipeline

change/react-native-windows-01520e78-9cae-47fe-b603-eea26db815fa.json, packages/playground/windows/playground/MainPage.cpp, vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp, vnext/Microsoft.ReactNative/QuirkSettings.cpp, vnext/Microsoft.ReactNative/QuirkSettings.h, vnext/Microsoft.ReactNative/QuirkSettings.idl, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactRootView.cpp, vnext/Microsoft.ReactNative/ReactRootView.h, vnext/Microsoft.ReactNative/ReactRootView.idl, vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp, vnext/Microsoft.ReactNative/Views/PopupViewManager.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
Make Fabric a per RootView setting.  This is how core works, and enables apps to more incrementally opt into Fabric in more complex brownfield apps.
This also fixes some issues where in playground you'd hit crashes switching back and forth between fabric and paper.
=> Make Fabric a per RootView setting

change/@rnw-scripts-create-github-releases-fd7dd57a-2910-4fdf-9e9f-a2e271f970eb.json, packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
Regression from a previous change. Leads to failure to create automated releases for previews.
=> Fix GitHub Release Generation for Previews

change/react-native-windows-fbd04605-ccd9-4478-80a6-f7040fa55702.json, vnext/Shared/DevSupportManager.cpp, vnext/Shared/DevSupportManager.h, vnext/Shared/OInstance.cpp, vnext/Shared/tracing/tracing.cpp, vnext/Shared/tracing/tracing.h
Currently any non-web debugging instance will set the JS variable `__RCTProfileIsProfiling` to true, which disables a bunch of logic on the JS side, including some debug checks and enabling hot reload. (Fast refresh)
Fixes #7845 
The important RN code that uses the variable for enabling/disabling fastrefresh:
https://github.com/facebook/react-native/blob/70da64094608f5f2e3c554ed719e9aad624e3459/Libraries/Core/setUpBatchedBridge.js#L43
=> Do not mark instance as IsProfiling when using fastrefresh

.ado/jobs/playground.yml
**_Why_**
Stale task left in playground pipeline during work of #7743. Task is unneeded and causes all builds to use WinUI3, generating errors during WACK test task.
**_What_**
Remove task from pipeline.
Fix #7935
=> Remove Bad Task in Playground Pipeline

change/react-native-windows-9566a736-184e-4f8f-bb18-95eefbad34a3.json, vnext/Desktop.UnitTests/ScriptStoreTests.cpp, vnext/Shared/BaseScriptStoreImpl.cpp
We have seen unexpected crashes in Office when using the memory map-based JSI Buffer, when trying to create the prepared script file handle:
```C++
std::unique_ptr<void, decltype(&CloseHandle)> fileHandle{
CreateFile2(filename, GENERIC_READ, FILE_SHARE_READ, OPEN_EXISTING, nullptr /* pCreateExParams */), &CloseHandle};
if (fileHandle.get() == INVALID_HANDLE_VALUE) {
```
To mitigate this, the feature will be scaled back and require the consumer to set the `JSI.MemoryMappedScriptStore` runtime option to enable it.
=> Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer

.ado/jobs/playground.yml
Currently it is easy to break WACK and then we are left to try to figure out which change did it. Running WACK should be fast and this will help us avoid WACK regressions.
=> Run WACK validation in PR

change/react-native-windows-4b3e136e-d3d6-42fc-9751-a22cff274ac5.json, vnext/src/Libraries/Components/Button.windows.js, yarn.lock
**_Why_**
Color extracted from Windows brush ButtonBackgroundPointerOver from MUX fails to only collects the color value and not the opacity value. This is because the ButtonBackgroundPointerOver brush uses "color" and "opacity" keys to define itself rather than a "ResourceKey". See [here](https://github.com/microsoft/microsoft-ui-xaml/blob/f06843042e7c3f29ae7bee8e941c93ad15030bad/dev/CommonStyles/Button_themeresources_v1.xaml#L23) for source. This results in the wrong color displayed during a button's hover state for apps using MUX. 
**_What_**
Add logic to specify opacity of View during hover state. Note this produces a Button that does not perfectly match the Windows styling, as it fades the button title as well as the button background. However, this code change is temporary, as it …
=> Update Button Hover Color 

change/@office-iss-react-native-win32-2021-06-02-16-38-58-logboximg63win32.json, packages/react-native-win32/overrides.json, packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
Replace usage of png files in LogBox for arrow keys with simple text components.
Currently having images from react-native internally causes some issues, which means these images do not show up and reduce the functionality of LogBox. -- Plus its silly to ship pngs when a simple unicode character will do.
=> [0.63] [Win32] Use text instead of images for LogBox arrows

change/react-native-windows-f28c18d4-b45b-47e2-95d9-3cd9b7154fb8.json, vnext/Microsoft.ReactNative/QuirkSettings.idl
`QuirkSettings` is going to have on going breaking changes in it.  So we should just mark the whole thing as experimental.
=>  Mark QuirkSettings as Experimental

change/react-native-windows-0a2a2995-f550-4706-8ac1-70eb087324c2.json, vnext/Microsoft.ReactNative/QuirkSettings.idl
`QuirkSettings` is going to have on going breaking changes in it. So we should just mark the whole thing as experimental.
Fixes #7945
=> [0.65] Mark QuirkSettings as Experimental

change/react-native-windows-2021-06-04-13-24-10-fg-mmap-63.json, change/react-native-windows-9566a736-184e-4f8f-bb18-95eefbad34a3.json, vnext/Desktop.UnitTests/ScriptStoreTests.cpp, vnext/Shared/BaseScriptStoreImpl.cpp
Backport of #7943 has been approved.
=> [0.63] Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer

change/react-native-windows-2021-06-04-11-17-50-textInputEventOrder.json, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
When creating logic for submitting editing, apps may wish to use the current state of the text set by the `onChange` event rather than the text passed through by the `onSubmitEditing` event, especially if it's a controlled component where JS may modify the text in the `onChange` event. The recent change to emit `onChange` events in the `TextBox.TextChanging` event rather than the `TextBox.TextChanged` event cause the `onChange` event to fire synchronously when the `TextBox.Text` value is cleared, and the `onChange` event was arriving before `onSubmitEditing`.
=> Emit `onSubmitEditing` before clearing text

change/react-native-windows-9566a736-184e-4f8f-bb18-95eefbad34a3.json, change/react-native-windows-b7cfbe58-72d2-4c5f-9a33-bf6e94ba0e1d.json, vnext/Desktop.UnitTests/ScriptStoreTests.cpp, vnext/Shared/BaseScriptStoreImpl.cpp
Backport of #7943 has been approved.
=> [0.65] Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer

change/react-native-windows-08e7832e-1f46-4a9b-9666-19f820b7d2cd.json, vnext/src/Libraries/Components/Button.windows.js
**_Why_**
Color extracted from Windows brush ButtonBackgroundPointerOver from MUX fails to only collects the color value and not the opacity value. This is because the ButtonBackgroundPointerOver brush uses "color" and "opacity" keys to define itself rather than a "ResourceKey". 
**_What_**
Add logic to specify opacity of View during hover state. Note this produces a Button that does not perfectly match the Windows styling, as it fades the button title as well as the button background. However, this code change is temporary, as it won't be needed when RNW moves to MUX2.6. 
Port #7938 to 0.65.
=> [0.65] Update Button Hover Color

.github/CODEOWNERS
Setting GitHub to require triage two weeks after we cut the branch and sent out reminders.
=> [0.65] Require Triage Starting 6/4

package.json, yarn.lock
Backport of #7965 to 0.65.
Resolves CG alert for CVE-2020-28469.
=> [0.65] CG: Add resolution for glob-parent@^5.1.2

package.json, yarn.lock
Backport of #7965 to 0.64.
Resolves CG alert for CVE-2020-28469.
=> [0.64] CG: Add resolution for glob-parent@^5.1.2

packages/playground/windows/playground-win32/Application.manifest
Recently the SDK version was updated to 19041, with it we updated the win32 app's maxversiontested. However there is a bug in the OS app activation will fail if maxversiontested > current, so keeping 18362 so this app can run on 19h1. 
Fixes #7976
=> Fix activation of xaml islands app in 18362

change/@react-native-windows-cli-85ae69ed-4113-468c-85b6-9e610f051b75.json, packages/@react-native-windows/cli/src/config/dependencyConfig.ts, packages/@react-native-windows/cli/src/config/projectConfig.ts
This PR adds a check to project and dependency config to bail when not
running on windows, since we assume non-windows machines don't need the
windows config information.
Closes #7979
=> Disable project/dependency config when not running on windows

.ado/jobs/universal.yml, change/react-native-windows-701bd979-0064-4bf6-821a-188c704345a3.json
@vmoroz Discovered that we were not running the unittests for the C# CodeGen tool in Pr or CI.
After investigation it seems I made a mistake when factoring the yaml and use 'X64' instead of 'x64' for the build platform. Yaml string compare is case sensitive by default, so the condition to run the tests was never met.
After this we should also report code coverage reports again for the netcore code.
=> fix pipeline casing of x64/x86 as yaml string compare is case sensitive

.ado/jobs/desktop.yml, .ado/jobs/universal.yml, .ado/templates/discover-google-test-adapter.yml, .ado/variables/vs2019.yml, change/react-native-windows-a2012f47-540f-47ef-ac49-b4d8666dbc86.json
I can't believe VsTest SUCCEEDS if it doesn't find any tests :(
=> Re-enable Cpp UnitTests using GoogleTestAdapter

change/react-native-windows-846102b7-d6a2-4c67-a0d1-a9f6cb4daee3.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Shared/OInstance.cpp
Currently when the bundle file doesn't exist, the instance just ends up in a blank state.
Several changes:
- handle winrt exceptions on bundle load to our error handler, where it was previously only handling std::exceptions.
- Forward instance load errors to the standard error handler which will display a redbox.
- Also one of the error handling methods in ReactInstance was not calling into redbox and some other error handling logic, these errors would be suppressed from users, and the instance wouldn't be put into an error state.
Now loading attempting to load an instance with a missing bundle will display redbox / call the users redbox callbacks.
=> Better reporting of failures to load the bundle file

change/react-native-windows-f41aeaf8-aa9a-469b-89a5-c1eeaf7ce92a.json, vnext/Shared/Modules/WebSocketModule.cpp
Minor optimization.
Minimizes conversions when catching/reporting an instance of `winrt::hresult_error` as `std::string`.
Instead of assembling a `wstringstream` and converting it to `std::string`, this change only converts `winrt::hresult_error::message()` to `std::string`, and assembles the rest of the message using `std::stringstream`.
=> Reduce string conversions when reporting hresult_error

package.json, yarn.lock
=> [0.64] Update ejs to pass CG

packages/playground/windows/playground-win32/Playground-win32.vcxproj
Playground code was changed to use Hermes but the win32 solution wasn't updated to use the props/targets and copy the hermes DLL to the app folder, which results in a crash when we try to delayload hermes.dll when disabling web debugging in playground-win32.
Fixes #8022
=> Fix playground-win32 delay-loading Hermes

change/react-native-windows-503903d7-2bfe-4626-9861-291a470f0ec5.json, packages/playground/windows/playground/MainPage.cpp, vnext/Microsoft.ReactNative/ReactApplication.cpp, vnext/Microsoft.ReactNative/ReactApplication.h, vnext/Microsoft.ReactNative/ReactApplication.idl, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp
These two properties have been marked deprecated for a while, and were in fact documented to be removed in 0.65.
=> Remove JavaScriptMainModuleName and DebugHost

.ado/jobs/e2e-test.yml, .ado/jobs/playground.yml, .ado/jobs/sample-apps.yml, .ado/templates/cleanup-certificate.yml, .ado/templates/run-windows-with-certificates.yml, .ado/templates/setup-certificate.yml
**_Why_**
Request in #7743 to extract certificate setup to a template file to reduce code repetition. 
**_What_**
Added three template files, one for executing the run-windows command under the new pipeline conditions which contains the logic for check which buildEnvironment it is to know if certificates can be accessed, one for setting up a certificate, and one for remove the certificate.
=> Add Templates for Certificate Retrieval in Pipeline

.ado/jobs/desktop.yml
=> Disable arm64 unit test on desktop builds in CI

change/react-native-windows-b0a5a498-4f12-447c-97cd-82b3d28ccb4e.json, packages/playground/windows/playground/MainPage.cpp, packages/playground/windows/playground/MainPage.h, packages/playground/windows/playground/MainPage.xaml, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h
`TurboModulesProvider` was caching `TurboModules`, but since it is an object on `ReactOptions` not tied directly to an instance, these `TurboModules` could stick around after an instance is shutdown.  An easy repo would be to hit the unload button in the playground app and see that none of the `TurboModules` destructors run until you hit load again.
This would also happen when reloading the instance through metro, where the same `ReactOptions` object was used for the reload.
There is no need for `TurboModulesProvider` to cache the TurboModules, since they are cached internal to the instance in `TurboModuleManager`.  So this was an unnecesary caching.
=> TurboModules might be kept alive by RNH when instance is shutdown

.ado/templates/setup-certificate.yml
**_Why_**
Change in #8015 had a bug which resulted in the CI build failing once the change was merged into main. 
**_What_**
Fixed setup-certificate template to retrieve the certificate secrets correctly, so that pfx files can be generated.
=> Fix CI Break to Retrieve Certificate Data Correctly

change/react-native-windows-cb6f7ebc-0410-4d3e-9840-b160e5f8f554.json, vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h, vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp, vnext/Microsoft.ReactNative/Modules/Animated/StyleAnimatedNode.cpp, vnext/Microsoft.ReactNative/Modules/Animated/TransformAnimatedNode.cpp
This pull request fixes #6430 
It creates new enumeration value that indicates whether unsupported facade type is specified.
---
This fix delivers new facade type: `FacadeType::None` which indicates that a given type is not supported by the framework. It avoids a crash because if `None` is noticed the animation is just not started and further processing is omitted.
The usage of this type is to first get the result of `StringToFacadeType()` method, and only then check it against the `None` value to see whether an existing and supported value is used.
Another change is to modify the default return value of `FacadeType`, which was previously set to `progress` and now it's `None` instead of throwing an assert.
---
These changes were tested on the real example application given in the original …
=> Avoid crash when unsupported facade is given - `react-native-paper` button fix

.ado/jobs/playground.yml
**_Why_**
Change in #8015 had a bug which resulted in the CI build failing for Release Playground once the change was merged into main.
**_What_**
Fixed Playground VSBuild source to specify the certificate correctly.
=> Fix CI Break to Specify Playground Certificate Correctly

change/react-native-windows-2021-06-16-18-11-51-0.63-stable.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/React.Cpp.props, vnext/Shared/V8JSIRuntimeHolder.cpp, vnext/Shared/V8JSIRuntimeHolder.h
This includes the fix for x86 builds and addition of the `debuggerRuntimeName` argument.
=> [0.63] V8 package update

change/react-native-windows-c45458c5-46d6-4759-a42d-9c38edb2c0da.json, vnext/Directory.Build.props
Mix of Backport of #8055 and forward port of #7918
=> [0.64] Fix msbuild as more cases of *Undefined* are popping up

change/@react-native-windows-cli-bb7e2de4-5a44-4dc8-9eda-d4528ae003da.json, packages/@react-native-windows/cli/src/config/configUtils.ts, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Best-effort autolinking - if a module was built without the standard module project template, use it for autolinking anyway
Fixes #8047
=> Autolink best effort

packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
=> Reorder RNTester multicolumn example to be inside the group of flatlist examples

change/react-native-windows-af57ea20-4d70-48cb-99f9-559acce12fa6.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Backporting #7363 by request. Expected to fix react-navigation's issue [#9109](https://github.com/react-navigation/react-navigation/issues/9109) for a team currently on 0.63 (in the process of upgrading to 0.64).
=> [0.63] Fix XAML Visibility for `display:none`

change/react-native-windows-c609b529-2e4e-4b5a-8b30-1d3567f739f6.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Backporting #7363 by request. Expected to fix react-navigation's issue [#9109](https://github.com/react-navigation/react-navigation/issues/9109) for a team currently on 0.63 (in the process of upgrading to 0.64).
=> [0.64] Fix XAML Visibility for `display:none`

change/react-native-windows-init-9d0bb145-b388-4dbb-a904-d1723ccf6382.json, packages/react-native-windows-init/src/Cli.ts
Currently Hermes is not supported for C# apps, so we should block it in the CLI.
=> Block creating C# apps with Hermes

change/react-native-windows-63ea3a71-e181-4a1e-a183-141818f55403.json, vnext/Shared/BaseScriptStoreImpl.cpp
Expected error conditions such as prepared script cache not (yet) existing were not handled, crashing the host process.
This change returns `nullptr` on memory-mapped buffer creation for subsequent handling by the JS engine.
Requesting backport to unblock Office feature.
=> Have script store return nullptr on facebook::jsi::JSINativeException

packages/e2e-test-app/jest-resolver.js, packages/e2e-test-app/jest.config.js, packages/e2e-test-app/jest.setup.js, packages/e2e-test-app/package.json, packages/e2e-test-app/test/framework/Navigation.ts, packages/e2e-test-app/test/visitAllPages.test.ts
Fixes #7726
We have a UIA-based test which navigates back and forward from each RNTester example. The list of examples cannot be populated by the UI, and is currently hardcoded. The source of truth, RNTesterList in RNTester, loads quite a bit of RN with it.
A previously discussed approach was to relay loaded data from the RN application process to the test runner. This change goes with a simpler approach, of making the test runner act more like RN. That includes Metro's Babel transformations, Windows platform resolution logic, and global setup. We can mostly rely on existing react-native UT infrastructure to automate most of this.
This loads enough of the environment to allow successfully loading all RNTester example modules, letting us poke at its data.
=> Tie visitAllPages Test to RNTesterList

change/react-native-windows-56b9c874-cffa-4b25-8e10-8414939d84c3.json, vnext/ExperimentalFeatures.props, vnext/Microsoft.ReactNative.ProjectReunion/Microsoft.ReactNative.ProjectReunion.csproj, vnext/Scripts/Microsoft.ReactNative.ProjectReunion.nuspec
reunion packages are using 18362 as the base SDK version. We recently updated RNW's SDK version to be 19041 (#7779). 
This change special cases the reunion projection project to use the older version so that RNW can be used in reunion apps all the way down to 17763.
Edit: because of a bug, we can't use 17763, see microsoft/ProjectReunion#921 - so I'm using 18362 for now.
=> Rewind SDK version for reunion

.ado/publish.yml, .ado/templates/component-governance.yml
We are working internally to better clarify our policies and improve our tooling around Component Governance and code signing of native binaries.
In the meantime, we are removing the restriction that CG must be strictly "completely clean" in order to codesign our native nuget packages.
=> Remove rule that CG must pass for code signing

change/@react-native-windows-cli-35e87e87-c745-44ad-8f4c-2b38f9b46108.json, packages/@react-native-windows/cli/src/config/dependencyConfig.ts, packages/@react-native-windows/cli/src/config/projectConfig.ts
This PR makes sure that raw paths specified in a react-native.config.js
are normalized when config is run, before the result is passed up to
whichever CLI command called for it.
Closes #7979
=>  Normalize paths provided by react-native.config.js

.ado/publish.yml, .ado/templates/component-governance.yml
This PR backports #8028 to 0.64.
We are working internally to better clarify our policies and improve our tooling around Component Governance and code signing of native binaries.
In the meantime, we are removing the restriction that CG must be strictly "completely clean" in order to codesign our native nuget packages.
=> [0.64] Remove rule that CG must pass for code signing

.ado/publish.yml, .ado/templates/component-governance.yml
This PR backports #8028 to 0.65.
We are working internally to better clarify our policies and improve our tooling around Component Governance and code signing of native binaries.
In the meantime, we are removing the restriction that CG must be strictly "completely clean" in order to codesign our native nuget packages.
=> [0.65] Remove rule that CG must pass for code signing

change/react-native-windows-e70a0776-a0e9-4343-a7fc-4afa6ee8df4e.json, vnext/template/cs-app/src/App.xaml.cs
=> Removed Microsoft.ReactNative.Manager.ReactPackageProvider registration from C# template

change/@react-native-windows-cli-d720ea1c-57b4-4909-9483-55a540f9e192.json, packages/@react-native-windows/cli/src/config/configUtils.ts, packages/@react-native-windows/cli/src/config/dependencyConfig.ts, packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap, packages/@react-native-windows/cli/src/e2etest/dependencyConfig.test.ts, packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpApp/react-native.config.js, packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppApp/react-native.config.js
=> Detect whether a project file is a dynamic library

change/@react-native-windows-telemetry-1c876c23-73f0-4104-9f34-5a7301d31e1c.json, packages/@react-native-windows/telemetry/src/test/sanitize.test.ts, yarn.lock
Lockfile deduplication previously caused test failures due to UTs inspecting the exact values of stacks (see #7903). Disabling the test for now, since it is not accurate to current dependencies delivered to users.
=> Deduplicate lockfile

change/react-native-windows-2021-06-28-15-49-47-0.63-stable.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/React.Cpp.props, vnext/Shared/OInstance.cpp
If USE_V8 is set (desktop), then default to using V8 instead of the pre-JSI Chakra executor.
=> [0.63] Use V8 by default in desktop (if enabled)

package.json, yarn.lock
This PR updates normalize-url to clear out a dependabot alert:
https://github.com/microsoft/react-native-windows/security/dependabot/yarn.lock/normalize-url/open
=> Security: update normalize-url to 4.5.1

change/@office-iss-react-native-win32-dae076bd-42e8-4b4c-a2ff-5a92e477bc03.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
When I added the AccessibilityControls prop in a PR last month to ViewWin32, I did not add it to the config file. This caused a logbox error on the Native side for RN SDXs using the View because the properties didn't match up.
=> Adding AccessibilityControls prop to ViewWin32 config

change/react-native-windows-dc38be40-2c3f-4b74-8f0e-98b90d52fe01.json, vnext/Microsoft.ReactNative/XamlView.cpp
Creating an unnecessary Compositor instance adds significant overhead. We're not doing anything with this instance, so it basically spends time creating a compositor instance then immediately tearing it down. This change reduced time spent in dcomp nearly 100% (overall, we were spending 11% of time on this call in the app scenario and removing this line brings it down to 0%).
=> Remove unnecessary line from GetCompositor

change/react-native-windows-2dfe1a4c-812a-4651-9c97-bf5a4522ae0c.json, vnext/src/Libraries/Components/Button.windows.js
**_Why_**
Recent upgrade of RNW to MUX2.6 caused a second shift in button styling. A couple of small tweaks were needed here to match the styling of the XAML button.
**_What_**
- Added border color and width to Button.
- Removed workaround in place for WinUI2.5 ButtonBackgroundPointerOver brush.
- Added button title color change with change in states.
=> Adjust Button Styling Following Upgrade to WinUI2.6

change/react-native-windows-fe3d1400-2d6f-4ccd-9a42-7e56656d6f10.json, vnext/src/Libraries/Components/Button.windows.js
**_Why_**
Recent upgrade of RNW to MUX2.6 caused a second shift in button styling. A couple of small tweaks were needed here to match the styling of the XAML button.
**_What_**
Added border color and width to Button.
Removed workaround in place for WinUI2.5 ButtonBackgroundPointerOver brush.
Added button title color change with change in states.
Backport #8148 to 0.65.
=> [0.65] Adjust Button Styling Following Upgrade to WinUI2.6

change/@office-iss-react-native-win32-2021-07-03-12-41-38-sammy-0.63_ViewWin32Config_Backport.json, packages/react-native-win32/docs/api/react-native-win32.basepropswin32.md, packages/react-native-win32/etc/react-native-win32.api.md, packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Backporting changes from [#7796](https://github.com/microsoft/react-native-windows/pull/7796) and [#8126 ](https://github.com/microsoft/react-native-windows/pull/8126). 
These changes add the AccessibilityControls prop on ViewWin32.
=> [0.63] Backporting AccessibilityControls prop on ViewWin32

change/@office-iss-react-native-win32-ab588088-9d63-4f25-b0da-123dfa0d64fd.json, packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Backporting changes from [#7796](https://github.com/microsoft/react-native-windows/pull/7796) and [#8126 ](https://github.com/microsoft/react-native-windows/pull/8126). 
These changes add the AccessibilityControls prop on ViewWin32.
=> [0.64] Backporting AccessibilityControls prop on ViewWin32

.ado/jobs/desktop.yml, change/@office-iss-react-native-win32-e08e70eb-e50d-452b-9414-a3980e22a905.json, change/react-native-windows-26a7dc77-a8eb-4dcf-9963-5acdcc5e06d3.json, packages/@office-iss/react-native-win32/overrides.json, packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx, packages/@office-iss/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/module.g.cpp, vnext/Microsoft.ReactNative/IReactContext.cpp, vnext/Microsoft.ReactNative/IReactContext.h, vnext/Microsoft.ReactNative/IReactContext.idl, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/ReactCoreInjection.cpp, vnext/Microsoft.ReactNative/ReactCoreInjection.h, vnext/Microsoft.ReactNative/ReactCoreInjection.idl, vnext/Microsoft.ReactNative/ReactHost/JSCallInvokerScheduler.h, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactContext.h, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/RedBox.cpp, vnext/Microsoft.ReactNative/RedBox.h, vnext/Microsoft.ReactNative/RedBoxHandler.cpp, vnext/Scripts/OfficeReact.Win32.nuspec, vnext/Scripts/Tfs/Layout-Headers.ps1
This change brings us much closer to aligning the API usage of Office with our public API 
Adds ReactInstanceWin and some remaining instance management code to the office dll.
Expands the winrt APIs that are included in the office dll.
Adds some new winrt APIs that are required to plug-in a different UI platform implementation.  In particular `ReactViewOptions` `IReactViewInstance` `IReactViewHost` and `ReactCoreInjection`.  Where `ReactCoreInjection` provides the entry point to be able to plug-in a custom ViewHost implementation when not using the XAML rootview.
Also added APIs to allow external dlls to post to the batching UI queue, and to get notified of a batch complete.  These are required for a custom UIManager implementation outside of the core dll.
Made changes to …
=> Add hooks to allow instance to be usable with pluggable UI platforms

change/react-native-windows-1c57a8ec-8618-42b7-84a2-d786d50b5108.json, packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js, packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js, packages/@react-native/tester/js/examples/TextInput/TextInputSharedExamples.js, vnext/src/Libraries/Components/Pressable/Pressable.windows.js, vnext/src/Libraries/Components/TextInput/TextInput.windows.js, vnext/src/Libraries/Components/View/View.windows.js, vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
The `key(Down|Up)Events` props control whether the event handling should be left exclusively to the JS, or at least the native processing should stop at the native control emitting it. This is to match this behavior on the JS side, by hooking into the `onKeyDown|Capture` callback and using event.stopPropagation() on the keys specified in `keyDownEvents`.
The change is in `View` and so works for `Pressable` too. I've made sure that the existing hooks in `Pressable`, which special-case `Space` continue to work with this.
Closes #5822
=> Call event.stopPropagation() with keyDownEvents specified.

change/react-native-windows-8cc2d5c9-9a96-49cd-9235-6d0679ed92e4.json, vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp, vnext/proposals/active/keyboard-reconcile-desktop.md
In order to better support perf testing metrics for events driven by either pointer events or keyboard events (e.g., triggered by Pressable, which can be triggered by either keyboard or pointer), this adds a timestamp property to the native event data for `onKeyDown` and `onKeyUp`.
Ideally this would use a native timestamp from the KeyRoutedEventArgs to get the actual time the key event occurred, but this is a sufficient approximation absent a XAML API to retrive this.
We use `GetTickCount64()` because that matches the behavior for the PointerRoutedEventArgs.
Fixes #8004
=> Adds timestamp to onKeyUp/Down events

change/react-native-windows-296a5268-bc99-4005-884c-1196ca4b8bac.json, vnext/Microsoft.ReactNative/Modules/AlertModule.cpp, vnext/Microsoft.ReactNative/Modules/AlertModule.h
ContentDialog / MessageDialog only allows one active dialog per thread. This means that if JS calls `alert(...)` while there is a dialog already showing, it will crash the app. A better approach is to batch pending alert requests in a queue. When one alert is dismissed, we check if there is another one pending and dispatch that one.
Fixes #7297
=> Allow multiple calls to alert

change/react-native-windows-97eb0bc5-471b-4848-bdf8-edd943238c00.json, vnext/Microsoft.ReactNative/Modules/TimingModule.cpp, vnext/Microsoft.ReactNative/Modules/TimingModule.h
The CompositionTarget::Rendering event burns a lot of CPU. For long running interval timers that fire infrequently, using this event for the timer implementation is overkill. This change checks the period of the timer, and uses the CompositionTarget::Rendering callback for period == 1ms (which is typical of requestAnimationFrame requests) and for everything else, uses a dispatcher timer that updates it's tick to the next due time each time a timer fires.
Fixes #6032
=> Use DispatcherTimer unless animation frame needed

.ado/publish.yml
This PR backport #7716 to 0.63.
If the last commit includes `***NO_CI***` in the subject line, throw an
error so the pipeline stops before wasting time building, or worse,
trying to publish.
Closes #7547
=> [0.63] Add check to cancel publish if the last commit was itself a publish (#7716)

.ado/publish.yml
The OfficeReact nuget was updated to include some more files, however
those files are not being uploaded to the build artifacts during
publish, which causes the nuget pack/publish to fail.
Closes #8228
=> Add React.Windows.Desktop\** to published build artifacts

.ado/publish.yml
This PR backports #8230 to 0.65.
The OfficeReact nuget was updated to include some more files, however
those files are not being uploaded to the build artifacts during
publish, which causes the nuget pack/publish to fail.
Closes #8228
=> [0.65] Add React.Windows.Desktop\** to published build artifacts

.ado/publish.yml
This PR backports #8230 to 0.64.
The OfficeReact nuget was updated to include some more files, however
those files are not being uploaded to the build artifacts during
publish, which causes the nuget pack/publish to fail.
Closes #8228
=> [0.64] Add React.Windows.Desktop\** to published build artifacts

change/react-native-windows-b7db929b-8aa9-43a8-9770-c46a8a6ad8cb.json, vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
DisconnectFromView can be called on an view that has no connected tag.
Also fix exceptions to be thrown by value as the rest of the code expects them to be
Fixes #8219
=> Fix DisconnectFromView when the view is already disconnected

.ado/jobs/cli-init.yml, change/@react-native-windows-cli-b2e5b36c-d2d6-4430-8f08-cf531309f36a.json, change/react-native-windows-5322b3cd-1801-49f7-b5b3-9bff23f0985b.json, change/react-native-windows-init-e6c57d75-3fb7-4abd-8797-c86fc26b340f.json, packages/@react-native-windows/cli/src/generator-windows/index.ts, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, packages/react-native-windows-init/src/Cli.ts, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/Bundle.props, vnext/PropertySheets/JSEngine.props
This change updates the hermes nuget package reference in RNW to the latest one which is C# project friendly. This change is already submitted to the 0.65-stable branch.
=> Consuming new UWP friendly Hermes package

docs/e2e-testing.md, packages/e2e-test-app/package.json
Updating the command for building test app as the current one fails with the following error:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\M
icrosoft.AppXPackage.Targets(3449,5): error APPX0101: A signing key is required in order to package this project
. Please specify a PackageCertificateKeyFile or PackageCertificateThumbprint value in the project file. [C:\repo
s\a-rnw\packages\e2e-test-app\windows\ReactUWPTestApp\ReactUWPTestApp.csproj]`
=> Fix e2e-test-app yarn windows script 

change/react-native-windows-5830b316-e89e-464a-bf98-f63ef2d6485b.json, packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/PropertySheets/Bundle.props, vnext/PropertySheets/External/Microsoft.ReactNative.Common.props, vnext/PropertySheets/JSEngine.props, vnext/PropertySheets/React.Cpp.props, vnext/ReactCommon/ReactCommon.vcxproj, vnext/Shared/OInstance.cpp, vnext/Shared/Shared.vcxitems
This PR has the same changes as in the PR that's proposed to 0.65-stable branch : https://github.com/microsoft/react-native-windows/pulls
This change ensures hermes integration is built into UWP binary distributed packages ..
The existing msbuild property useHermes has the following effects,
Enable hermes sources and nuget packages into the build scripts
define USE_HERMES macro which adds the 'hermes case" into the dynamic switches in the code.
set JSEngine.Hermes as default value in ReactInstanceSettings.JSIEngineOverride
We want to include hermes integration into binary distributions so that the clients can opt to use hermes. But we don't yet want to make hermes the default. Hence we are introducing a new msbuild property includeHermes.
Also, this change make chakra dependency delay …
=> Including hermes by default in binary distributions

change/react-native-windows-8e5fe054-f8cb-424f-b89a-818edcb03446.json, packages/playground/windows/playground/App.xaml, vnext/Microsoft.ReactNative/ReactRootView.cpp
Looks like we can use the WinUI 2.x ProgressRing which has the updated visuals. Updating Playground to bring in the WinUI 2 resources too (which are part of the app template)
=> Use WinUI 2.x ProgressRing instead of XAML ProgressRing

change/react-native-windows-5e29bef1-d45a-490a-8073-a2818fd7c102.json, vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp, vnext/Microsoft.ReactNative/Views/cppwinrt/DynamicAutomationPeer.idl
https://github.com/facebook/react-native/commit/da899c0cc4372830e5ca053a096b74fff2a19cb8 added a Toggle Button accessibility role for Android, in iOS this gets treated same as accessibilityRole="button". This PR adds ToggleButton role to rnw, and since there's no equivalent AutomationControlType, it also gets treated same as accessibilityRole="button". 
Fixes #7856.
=> Add Support For "togglebutton" accessibilityRole 

.ado/jobs/playground.yml, .ado/templates/build-rnw.yml, .ado/templates/run-windows-with-certificates.yml, .ado/variables/vs2019.yml
The MSBuild base intermediate build directory (`vnext/build`) was overrode to circumvent a drive space limitation in the previous CI vm images used.
The currently used VM pools don't have this limitation, making that setting unnecessary.
=> Drop BaseIntDir setting from CI

docs/e2e-testing.md
Fixes #7272
Jest CLI params for test selection are a bit funky. Update docs to make them clearer, and show how you can run from package root.
=> Update instructions for running a single E2E test

change/react-native-windows-0083fc4b-cb06-46b1-b965-f826cc669832.json, vnext/Microsoft.ReactNative/IReactContext.idl, vnext/Microsoft.ReactNative/IReactPropertyBag.idl, vnext/Microsoft.ReactNative/JsiApi.idl, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
A whole bunch of APIs were marked as going to be removed in 0.65, but were not removed. Update the docs to a label which will stay correct.
=> "0.65" -> "Future Version" in deprecation warnings

change/react-native-windows-0083fc4b-cb06-46b1-b965-f826cc669832.json, vnext/Microsoft.ReactNative/IReactContext.idl, vnext/Microsoft.ReactNative/IReactPropertyBag.idl, vnext/Microsoft.ReactNative/JsiApi.idl, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
A whole bunch of APIs were marked as going to be removed in 0.65, but were not removed. Update the docs to a label which will stay correct.
Fixes #7486
=> [0.65] "0.65" -> "Future Version" in deprecation warnings

change/@react-native-windows-cli-f7148586-13ff-456d-8981-5dfe310c2e37.json, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts, packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Fixes #6214
Release builds do not use the bundle server. Don't launch it unless explicitly requested.
=> Do not start packager for run-windows release builds

change/react-native-windows-236d6752-8db9-4928-8195-abd089164605.json, vnext/src/Libraries/AppTheme/AppTheme.ts
The shim returned `any` for `addListener`,  which broke typings for non-deprecated pattern of unsubsribing from the listener via calling `remove()` on the subscription returned by `addListener`.
`AppTheme` is always provided by the UWP ReactNativeHost, and we do not special case other modules in the same way for when an NM isn't present, so I just removed the shim, since the NM is always available. TS can then infer the correct subscription type from NativeEventEmitter.
=> Remove AppTheme Shim

change/react-native-windows-d97dc1fe-0a82-4894-9183-bbfeef3d6d65.json, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h, vnext/Microsoft.ReactNative/Views/RefreshControlManager.cpp, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp, vnext/Microsoft.ReactNative/Views/ScrollViewManager.h, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
Another view that is apt to fire rapidly (especially in window resizing scenarios) is `onLayout`. This change introduces the batching event emitter for ViewManagerBase for use with onLayout events.
=> Coalesce RN View onLayout events

change/react-native-windows-f2e41904-62cd-41a4-af8e-b661bff3adf8.json, vnext/Folly/Folly.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon/ReactCommon.vcxproj
=> Fix warning of double-importing ExperimentalFeatures.props

.ado/jobs/project-reunion.yml, .ado/templates/build-rnw.yml, change/react-native-windows-49a918d2-853a-457e-9d6b-2b643b1ff6c4.json, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
This does not enable it in project reunion yet.  #8312 Tracks enabeling this.
=> Enable WarnAsError for builds in PR, CI and publish

packages/playground/windows/playground/MainPage.cpp, packages/playground/windows/playground/MainPage.h, packages/playground/windows/playground/MainPage.xaml
This is the first step in working around some XAML bugs when the OS is set to light mode but a XAML parent element is set to dark. This will allow us to expose those bugs and then prove we've fixed them.
Here's how the Playground window looks when dark theme is selected:
And here's how it looks in light theme:
CC @acoates-ms since this touches some theme logic from https://github.com/microsoft/react-native-windows/pull/6135.
=> Add theme picker to Playground app

change/react-native-windows-58d8e333-eb08-4d83-b99a-746ae45d9055.json, vnext/proposals/active/scroll-anchoring.md
Given a number of known limitations to the `inverted` prop on `VirtualizedList` for desktop platforms, this proposal breaks out a few key features of list inversion and proposes alternative APIs for View and ScrollView that make list inversion possible.
=> Proposal to support props for scroll anchoring

packages/playground/windows/ExperimentalFeatures.props, packages/playground/windows/playground-win32/Playground-Win32.cpp, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground-win32/packages.config
Fixes #8329 
Recently I made a change to the dev menu control, where I added usage of a WinUI 2.6 ProgressRing. All of the apps we enable devs to build, are UWP, and playground-win32 is the one example that isn’t. The UWP app templates that we ship with RNW, include the WinUI 2.6 dependency and all is well.
However, in the case of islands, the app started to crash because the it suddenly didn’t know what a MUX.ProgressRing was.
Below are the steps I had to take to get things to a working state and the reasons behind them being needed:
1) Reference the WinUI 2.x prerelease package. Release packages use the framework package (as opposed to carrying the DLLs) and do not have in-app support. Unpackaged apps cannot see framework packages*, so they need the DLL to be next to the exe / in the …
=> Fix usage of WinUI in unpackaged xaml islands app

change/@office-iss-react-native-win32-d41fc6e3-bacd-45af-a63e-3f7b91a45bda.json, change/react-native-windows-7013c272-48ae-4a55-b5db-f6b2795c585e.json, packages/@office-iss/react-native-win32/jest.config.js, packages/@office-iss/react-native-win32/package.json, packages/e2e-test-app/jest.config.js, packages/e2e-test-app/package.json, vnext/jest.config.js, vnext/package.json, yarn.lock
`@rnx-kit/jest-preset` has a simpler implementation of the path filter in `@rnx-kit/jest-resolver` (and `@rnw-scripts/jest-out-of-tree-resolver` before that), using the `moduleNameMapper` option to redirect `react-native` to `react-native-windows` instead.
Like its predecessors, it can also detect that it's being used inside an out-of-tree platform package and configure `jest-haste-map` to pick up the appropriate file extensions.
=> Replace @rnx-kit/jest-resolver with @rnx-kit/preset

change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json, vnext/Shared/Executors/WebSocketJSExecutor.cpp, vnext/Shared/Executors/WebSocketJSExecutor.h
`react-native-debugger` has a slightly different implementation of the debugger WS protocol that is used by the standard `http://localhost:8081/debugger-ui/`.  In particular it queues up any method requests until after the `executeApplicationScript` call.
`react-native-windows` currently makes a call to `flushedQueue` before the call to `executeApplicationScript`.  The normal debugger ui responds with an error to this call.  `react-native-debugger` doesn't respond, as its queued up until the `executeApplicationScript` call.  Unfortunately `react-native-windows` waits on the response to the `flushedQueue` call before it'll make the `executeApplicationScript` call, so we end up in a hung state.
As it turns out the call to `flushedQueue` is only needed when there are TurboModules running. …
=> Fix issue using react-native-debugger with react-native-windows

change/react-native-windows-293eabba-6085-43a4-be7c-e378f031d190.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/Utils/Helpers.cpp, vnext/Microsoft.ReactNative/Utils/Helpers.h, vnext/Microsoft.ReactNative/Utils/XamlIslandUtils.cpp, vnext/Microsoft.ReactNative/Utils/XamlIslandUtils.h, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
As reported in https://github.com/microsoft/microsoft-ui-xaml/issues/5341, the singleton TextCommandBarFlyout for the XAML TextBox and TextBlock components are limited to one window. When the flyout opens on a different window after already being opened on another, the first window the flyout was opened on gets focus, and the flyout is immediately closed. This change creates a TextCommandBarFlyout per TextInput native view and per selection TextBlock native view.
Additionally, it includes logic to work around an issue with the Proofing sub-menu flyout, which crashes due to an animation bug on Windows 10 versions lower than 21H1.
=> Work around XAML Islands issues with TextCommandBarFlyout

change/react-native-windows-42e33449-db1e-4403-ab06-0213eea7ea90.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueReaderTest.cpp, vnext/Microsoft.ReactNative.Cxx/JSValueXaml.h
Add a couple of simple tests for the JSValue reader tests for xaml/winrt types (thickness, corner radius, uri)
=> Add Xaml type js reader unit test

.ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/templates/set-experimental-feature.yml, packages/e2e-test-app/windows/ExperimentalFeatures.props
This expands E2ETest coverage to include Hermes support. This shares the same logic as we used for doing Hermes release integration tests. E2E YAML is moved to template-time matrix form instead of previous runtime matrix form, along with adding some more flavors to our more comprehensive nightly CI runs.
Checked that (the C# based) E2E Test App already contains the Hermes PackageReference in the user project.
=> Run E2E Test App Against Both Chakra and Hermes

change/react-native-windows-9fa432a3-64da-497e-8f46-b276ea85891a.json, vnext/Microsoft.ReactNative/QuirkSettings.cpp, vnext/Microsoft.ReactNative/QuirkSettings.h, vnext/Microsoft.ReactNative/QuirkSettings.idl, vnext/Microsoft.ReactNative/ReactRootView.cpp
=> Add QuirkSettings::SetEnableBackHandler to opt out of BackHandler functionality

change/react-native-windows-9327e4f0-c4f9-4c6a-b2cc-25c0ecf9e89a.json, vnext/Microsoft.ReactNative/Modules/AlertModule.cpp, vnext/Microsoft.ReactNative/Modules/AlertModule.h, vnext/src/Libraries/Alert/Alert.windows.js
Sets the default button to `Primary` when a positive button is specified, `Secondary` when a negative button is specified but not a positive button, or falls back on the `Close` (neutral) button.
Co-authored-by: Mykola Lando <lando.koljaka@gmail.com>
=> Sets the default button for the ContentDialog

change/react-native-windows-6bd5ecf8-9e67-49a6-8b65-ea0d5f53e42b.json, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
Sets color to Transparent when prop is explicitly set to null. Setting the color to Transparent will set the A value to 0, which will allow us to switch from a ReactImageBrush to a standard bitmap. It will also remove the tint effect from the CompositionEffect for images that use either repeat resizeMode or blurRadius.
=> Clear tintColor when prop set to null

change/react-native-windows-65c127f0-920a-4ead-9f78-28f9aefd9aa6.json, vnext/Shared/Modules/NetworkingModule.cpp
Allow customization of User-Agent header string for apps built on react-native-windows.
=> Skip user agent HTTP header validation

.ado/image/rnw-pool.json, change/react-native-windows-508a0db3-8e5b-4a1b-9d80-fee68a18cf72.json, vnext/Scripts/rnw-dependencies.ps1
This change checks in the configuration file we use for our hosted pool images.
Since there is no prescribed tool for the windows ADK yet, this changes makes that step optional.
=> Updates to support private image

change/react-native-windows-e95ae09a-3ccc-4ae3-a539-086bd5ad1e6d.json, vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp, vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.h
This change ensures that the NativeAnimatedNodeManager still exists before attempting to call the `DoCallback` instance method on AnimationDriver from the CompositionScopedBatch::Completed callback.
Co-authored-by: Mykola Lando <lando.koljaka@gmail.com>
=> Prevent crash in AnimationDriver when RN instance destroyed

change/@office-iss-react-native-win32-a2bf706d-8737-4b7b-9cc4-5849dbefaf02.json, change/react-native-windows-51809f92-5a38-4f18-8302-ac6a93f8589e.json, packages/@office-iss/react-native-win32/metro.config.js, packages/e2e-test-app/metro.config.js, packages/sample-apps/metro.config.js, vnext/metro.config.js
This has been the default behavior since 0.64, and our template was updated, but some of the metro configurations in our repo are on the old behavior. Enable inlineRequires everywhere. The most significant affected being e2e-test-app.
=> Enable inlineRequires for all projects

package.json, yarn.lock
* Bumps jszip to 3.7.1
* Bumps tar to 4.4.17
* Bumps xmldom to 0.7.0
=> [0.64] Component Governance fixes

change/react-native-windows-d47189e2-4652-42e1-bb0f-ca9d4b18768d.json, patches/@react-native-picker+picker+1.16.5.patch, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/template/cpp-lib/proj/MyLib.vcxproj
Fixes #8430
Newer versions of the Windows SDK by default produce WinMDs that may not be able to be referenced when using an older Windows SDK. This change disables the new feature to allow existing community modules targeting an older Windows SDK to consume the MSRN WinMDs.
=> Exclude WinMD AttributeNameAttribute

change/react-native-windows-57b2d9fa-1663-4577-b3bf-4e684b970508.json, packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx, packages/e2e-test-app/test/__snapshots__/TextComponentTest.test.ts.snap, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/Utils/ShadowNodeTypeUtils.h, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Utils/ValueUtils.h, vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.h, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
There were two issues with the Text backgroundColor prop:
1. Changes to the backgroundColor prop on virtual text nodes did not update their corresponding TextHighlighters
2. Changes to the underlying text did not update the TextHighlighter ranges
This change forces a refresh of all TextHighlighters any time:
1. A raw text node changes text value
2. A virtual text node is added or removed from the text tree
3. A virtual text or root text node updates its backgroundColor prop
TODOs:
Fixes #7568
Fixes #7569
Fixes #8407
=> Fixes issues with Text backgroundColor

change/react-native-windows-b4f125ea-015b-4c96-a89a-906de480fe68.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Fix for #8441. Skip processing of "extra layout" nodes that were removed from the tree before DoLayout has had a chance to process them.
=> Fix crash in NativeUIManager when processing extra layout nodes

change/react-native-windows-9824cf9a-62b1-400e-b905-e9fb51a82809.json, vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
=> Support 'focusable' prop on all ControlViewManager-derived components

change/react-native-windows-569ef05e-75d4-4af7-9197-8ebc3dca1c37.json, vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
=> Fix crash in KeyboardEventHandler.cpp when handling undefined keyDownEvents prop

package.json, yarn.lock
This was added a while back after a patch release meant that built-in RN code was no longer clean. They've I think since fixed this, and linting now passes. Removing the resolution (and doing some lockfile deduplication).
=> Remove eslint-plugin-react-hooks Resolution

package.json, yarn.lock
This PR backports #8462 to 0.65.
Bumps xmldom and tar.
=> [0.65] Bump xmldom and tar for Component Governance

change/node-rnw-rpc-a7d877a2-4952-4c54-9d0b-71c29f1a8383.json, change/react-native-windows-b229cc41-28f9-4cc4-95f5-206ba16cd941.json, packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj, packages/node-rnw-rpc/windows/NodeRpc/NodeRpc.vcxproj, packages/playground/windows/playground/Playground.vcxproj, packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj, packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props, vnext/template/cpp-app/proj/MyApp.vcxproj, vnext/template/cpp-lib/proj/MyLib.vcxproj
Fixes #8443
External property sheets are managed by the react-native-windows npm package instead of the template. This means that a single version defined by the react-native-windows npm package will be included for any community modules.
Set WindowsSdkVersion there instead of in the template so that it stays in sync with the host app. The current way of overriding SDK version in ExperimentalFeatures.props will still work because it is imported first.
=> Set Shared WindowsTargetPlatformVersion in External Property Sheets

change/react-native-windows-dba9665a-a1e1-4b98-824c-21504ac6d547.json, vnext/template/cs-lib/proj/MyLib.csproj, vnext/template/shared-lib/proj/ExperimentalFeatures.props
Already fixed in main, this partially backports #8402 / #8428  to 0.65
Fixes #8467
=> [0.65] Use app's ExperimentalFeatures.props in library project

change/react-native-windows-24c06f48-422a-4110-8886-448345a95f36.json, vnext/.editorconfig, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop.DLL/packages.config, vnext/JSI/Desktop/JSI.Desktop.vcxproj, vnext/JSI/Desktop/packages.config, vnext/JSI/Shared/JSI.Shared.vcxitems, vnext/JSI/Shared/JSI.Shared.vcxitems.filters, vnext/JSI/Shared/NapiJsiV8RuntimeHolder.cpp, vnext/JSI/Shared/NapiJsiV8RuntimeHolder.h, vnext/JSI/Universal/JSI.Universal.vcxproj, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/PropertySheets/React.Cpp.props, vnext/Shared/DevSettings.h, vnext/Shared/OInstance.cpp
=> [0.64] Consume Node-Api V8 JSI Runtime

packages/playground/windows/playground-win32/Playground-Win32.cpp
Per #7290 these changes are required. I confirmed that the Playground-win32 announceForAccessibility example now works with this change.
=> Fix AccessibilityInfo.announceForAccessibility not working in playground-win32 solution

change/react-native-windows-57b2d9fa-1663-4577-b3bf-4e684b970508.json, change/react-native-windows-d5ee9be9-4beb-4ab9-897d-f9fe3808d36b.json, packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx, packages/e2e-test-app/test/__snapshots__/TextComponentTest.test.ts.snap, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/Utils/ShadowNodeTypeUtils.h, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Utils/ValueUtils.h, vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.h, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
There were two issues with the Text backgroundColor prop:
Changes to the backgroundColor prop on virtual text nodes did not update their corresponding TextHighlighters
Changes to the underlying text did not update the TextHighlighter ranges
This change forces a refresh of all TextHighlighters any time:
A raw text node changes text value
A virtual text node is added or removed from the text tree
A virtual text or root text node updates its backgroundColor prop
TODOs:
Pass inherited foreground color down so virtual text highlighters apply the correct foreground color
Update snapshots since highlighter approach has changed
Produce a before and after video to ensure RNTester TextExample still works as expected
Add examples to RNTester to toggle background colors on RCTText and RCTVirtualText …
=> [0.65] Fixes Issues with Text backgroundColor

change/react-native-windows-7bd134b0-fc4f-4916-b38f-ca8f29e8b4fb.json, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp
This functionality is available in the lower levels of the APIs that Office uses today, but to move to the higher level APIs Office will need them exposed through the IDL too.
This is the current LoggingCallback used, which will continue to be the default:
https://github.com/microsoft/react-native-windows/blob/ac25661d077eb4d4728042486c60341e6a5984d7/vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp#L712
=> Allow override of global.nativeLoggingHook

change/react-native-windows-7bd134b0-fc4f-4916-b38f-ca8f29e8b4fb.json, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp
#8497 port to 0.65
Needed for Office integration with ABI interface.
=> [0.65] Allow override of global.nativeLoggingHook

change/react-native-windows-f9440adc-f697-40d9-99c3-495aaf01ab8f.json, vnext/Microsoft.ReactNative/ReactCoreInjection.cpp, vnext/Microsoft.ReactNative/ReactCoreInjection.h, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactRootView.cpp, vnext/Microsoft.ReactNative/ReactRootView.h
=> [0.65] Pass JSValueArgWriter around instead of immediately converting to dynamic

change/react-native-windows-a8b5bad4-4783-4c5f-a6f4-c227c9b6c8d9.json, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Related to: https://github.com/microsoft/react-native-windows/issues/8452
When accessibilityRole is set to "header" in RN-core, the native values that are updated (Heading for Android and accessibilityTrait for iOS) are the same values that used by screen readers to determine if some text is a heading. On Windows, screen readers check the UIA Heading Level to determine if something is a heading -- this PR sets the UIA Heading Level to a default level 2 whenever accessibilityRole="header" in Text. This will match the behavior in RN-core, although we might want to create a windows-specific prop down the road to allow for control over the exact heading level passed to UIA. 
Also included is an update to automationProperties.localizedControlTypeProperty when setting accessibilityRole in Text …
=> Add support for UIA accessibility headings

change/jest-environment-winappdriver-6023bd5e-c1ba-4c1d-8400-91294717852e.json, packages/e2e-test-app/jest.config.js, packages/jest-environment-winappdriver/README.md, packages/jest-environment-winappdriver/src/WinAppDriverEnvironment.ts
WinAppDriver expects an app passed to it as either a package family name, or a path to an exe. Package family names are confusing to work with, so instead use a package identity and do the conversion ourselves.
=>  Use Package Identity Name Instead of Package Family Name for Testing

docs/e2e-testing.md, packages/e2e-test-app/.eslintrc.js, packages/e2e-test-app/jest.setup.js, packages/e2e-test-app/test/DisplayNoneTest.test.ts, packages/e2e-test-app/test/LegacyControlStyleTest.test.ts, packages/e2e-test-app/test/LegacyImageTest.test.ts, packages/e2e-test-app/test/LegacyLoginTest.test.ts, packages/e2e-test-app/test/LegacyTextInputTest.test.ts, packages/e2e-test-app/test/TextComponentTest.test.ts, packages/e2e-test-app/test/framework/AutomationClient.ts, packages/e2e-test-app/test/framework/Navigation.ts, packages/e2e-test-app/test/framework/index.ts
WebDriverIO exposes a whole webdriver client, with loads of functionality that doesn't work or make sense on a desktop app. This facade exposes the bits that are supported by WinAppDriver, in an easier API. It also lets us potentially decouple from WebDriverIO if we want to move to a differnt WebDriver client.
Currently being done in the test app, but will be extracted to a separate package after to allow use in apps outside the repo.
=> Add AutomationClient and AutomationElement Facade

change/react-native-windows-84b1ca2a-3a6d-4c8f-b45f-e1d680f4fd3c.json, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Backporting #8516 through 0.64 by request.
=> [0.64] Add support for UIA accessibility headings

change/react-native-windows-b83fcd10-3cb3-45f2-b7a8-a893a5305f4e.json, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Backporting #8516 through 0.64 by request.
=> [0.65] Add support for UIA accessibility headings 

packages/e2e-test-app/package.json, packages/playground/package.json, packages/sample-apps/package.json, yarn.lock
Playground, E2E and samples are using a really old babel-preset.
=> Bump the version of metro-react-native-babel-preset

change/@react-native-windows-codegen-967f1b7b-9b13-42dd-9e2c-5878d2033ecf.json, change/react-native-windows-6d7508de-686f-443e-a500-fd6df3e799a8.json, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts, packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts, packages/@react-native-windows/codegen/src/generators/ParamTypes.ts, packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts, vnext/Microsoft.ReactNative.Cxx/StructInfo.h, vnext/codegen/NativeAlertManagerSpec.g.h, vnext/codegen/NativeAnimatedModuleSpec.g.h, vnext/codegen/NativeAnimatedTurboModuleSpec.g.h, vnext/codegen/NativeDeviceInfoSpec.g.h, vnext/codegen/NativeDialogManagerAndroidSpec.g.h, vnext/codegen/NativeExceptionsManagerSpec.g.h, vnext/codegen/NativeImageEditorSpec.g.h, vnext/codegen/NativePushNotificationManagerIOSSpec.g.h
From react-native 0.64, react-native-codegen allows defining aliases for object literal types. This change reflect it on the codegen.
~~I don't know why `Microsoft.ReactNative.sln` still compiles as these new structs are used in the spec but implementations are not changed.~~
It is interesting that no module implementations are using `REACT_STRUCT` except `Alert` and `DeviceInfo`. `Alert` doesn't check the spec class when registering. `DeviceInfo` doesn't contain constants in the spec. I will fix them in separate commits.
=> Generate aliased struct for turbo module

change/@react-native-windows-cli-dc9b1092-11ab-4867-8616-1ffbef340913.json, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
We do not want to launch the packager by default in release builds because the application is already bundled. Logic is present to avoid launching, conditioning on release mode, or if  ``--packager`` is specified.
Commander has some special handling around negation parameters. For a positive parameter, like `--foo`, the option will be set to undefined ifa default not present. If it is `--no-foo`, then `foo` will be set to true instead of undefined.
This effectively means there is not a way to test for `--packager` vs the absence of `--no-packager`, so the previous logic always assumed the user was explicitly asking for a packager.
This change moves the logic to instead launch the packer when the following conditions are met:
1. `--no-packager` is not set
2. `--no-launch` is not set
3. …
=> Fix logic to avoid launching packager

change/react-native-windows-63c7eafa-0398-42ec-a2db-6dc37804f31a.json, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
See details of bug in #8525. Calling UpdatePointersInViews in the OnPointerConcluded callback fixes the issue.
Fixes #8525
=> Fire onMouseEnter/Leave events on pointer concluded

change/react-native-windows-9c592c92-59e0-41c3-b4ad-717dc10aa396.json, vnext/Folly/Folly.vcxproj
Our CI has caught 2 runs where metro was trying to read folly.zip file while it was being downloaded.
This change moves the zip file into the intermediate msbuild output folder rather than the node_modules folder where Metro bunderl is snooping around.
=> Fix race condition when building customer projects

packages/playground/Samples/accessible.tsx, packages/playground/Samples/rntester.tsx, packages/playground/Samples/ticTacToe.tsx, packages/playground/just-task.js, packages/playground/tsconfig.json
Fixes #8416
RNTester already type-checking as it does a build instead of transform
=> Typecheck Playground Samples

change/react-native-windows-288a5f41-0865-467a-83c0-2e53f5f0ede5.json, vnext/package.json
The only changes being made/accepted to 0.63 are for internal office usage, pending react-native-macos updates. Stop tagging new 0.63 release, so that patches stop showing up in the releases view.
=> Stop Tagging 0.63 Builds

change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json, packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
This PR fixes autolinking to properly handle modifying solution files
that have LF line endings (which can happen when cloning a repo that
didn't maintain the CRLF we use in our template).
Closes #8530
=> Fix autolinking to support solution files using LF instead of CRLF

change/@office-iss-react-native-win32-6c132fce-6826-4199-99d7-2fd4111db44c.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
I will backport this to .65/.64/.63
**[UIA_ItemTypePropertyID](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids)** - 
Identifies the ItemType property, which is a text string describing the type of the automation element.
ItemType is used to obtain information about items in a list, tree view, or data grid. For example, an item in a file directory view might be a "Document File" or a "Folder".
When ItemType is supported, the string must match the application UI language or the operating system default UI language.
=> Adding Accessibility Prop accessibilityItemType on ViewWin32

change/@office-iss-react-native-win32-2f74a1fc-d190-4395-a600-69abbc3095ab.json, change/react-native-windows-84f792cf-76b2-4a3a-bff8-2915916225ad.json, packages/react-native-win32/src/Libraries/Components/View/View.win32.js, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx, vnext/Microsoft.ReactNative/IReactDispatcher.cpp, vnext/Microsoft.ReactNative/IReactDispatcher.h, vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp, vnext/Microsoft.ReactNative/Modules/AppearanceModule.h, vnext/Microsoft.ReactNative/ReactCoreInjection.cpp, vnext/Microsoft.ReactNative/ReactCoreInjection.h, vnext/Microsoft.ReactNative/ReactCoreInjection.idl, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/RedBox.cpp, vnext/Microsoft.ReactNative/RedBox.h, vnext/Microsoft.ReactNative/RedBoxHandler.cpp, vnext/Shared/Threading/BatchingQueueThread.cpp, vnext/Shared/Threading/BatchingQueueThread.h, vnext/Shared/Threading/MessageDispatchQueue.cpp, vnext/Shared/Threading/MessageDispatchQueue.h
Currently bad things happen if someone tries to set a custom implementation of IReactDispatcher to InstanceSettings.UIDispatcher.
This fixes an assumed cast to an internal object, and replaces it with a small internal interface that we can QI for.  If that interface exists we will use that internally.  Otherwise, we can implement that interface on top of an app provided IReactDispatcher.
Making this PR against 0.64 since I'm testing it against a 0.64 providing an custom IReactDispatcher internally.  We will need this backported to 0.64 anyway for Office's effort to get onto the public ABI.
Note, I am also backporting #8026 since I hit that issue while testing this.
=> [0.64] Allow injection of custom UI thread

change/@react-native-windows-codegen-ceaa24ec-f953-49ad-aab9-0ef29c09f64b.json, change/react-native-windows-2780fd2a-4fc6-4e8d-9675-2113fbcc7575.json, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts, packages/@react-native-windows/codegen/src/generators/ParamTypes.ts, packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts, vnext/codegen/NativeActionSheetManagerSpec.g.h, vnext/codegen/NativeAppearanceSpec.g.h, vnext/codegen/NativeAsyncLocalStorageSpec.g.h, vnext/codegen/NativeAsyncSQLiteDBStorageSpec.g.h, vnext/codegen/NativeDevLoadingViewSpec.g.h, vnext/codegen/NativeIntentAndroidSpec.g.h, vnext/codegen/NativeJSCHeapCaptureSpec.g.h, vnext/codegen/NativeJSCSamplingProfilerSpec.g.h, vnext/codegen/NativeSegmentFetcherSpec.g.h, vnext/codegen/NativeStatusBarManagerAndroidSpec.g.h, vnext/codegen/NativeStatusBarManagerIOSSpec.g.h, vnext/codegen/NativeUIManagerSpec.g.h, vnext/codegen/NativeWebSocketModuleSpec.g.h
Use `std::optional<T>` where nullable types are used in turbo module specs.
=> Generate nullable type for turbo module

change/@react-native-windows-automation-82f03b0b-cdd1-4c44-b4c4-11eec17ef46b.json, packages/@react-native-windows/automation/README.md, packages/@react-native-windows/automation/src/AutomationEnvironment.ts
Fixes #8570
Win32 or unpackaged apps may need to be launched with specific args when running a test app, e.g. for FURN + rex scenarios. This can be passed via WinAppDriver capability, but is awfully hidden, requiring scouring WinAppDriver issues or source code. Expose it as a high-level option instead.
=> Expose launch args as high level automation option 

change/react-native-windows-85928af6-903b-4435-b317-7e7fde3dfc54.json, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
**_Why_**
Current implementation of setAccessibilityFocus method resulted in no action. Request to backport from partner. 
**_What_**
The RN setAccessibilityFocus API is intended to force the narrator focus to a specific element and then trigger narrator to announce that element.
**_How_**
Added source code to the sendAccessibilityEvent method inside PaperUIManager. New source code identifies the new element to focus on via its reactTag, focuses the element, and raises an automation event to alert narrator of the focus change. The RN setAccessibilityFocus API now calls the native method.
**_Testing_**
Tested by modifying a page in the playground app to call setAccessibilityFocus following the press of a button. The focus target was a second button. With narrator on, the first button was …
=> [0.64] Add Functionality to setAccessibilityFocus Method

change/@react-native-windows-codegen-4fdc254b-a8bb-45fa-a4cc-df410c4a2137.json, change/react-native-windows-6d6555c7-4800-429b-ba40-8dd3b679a2b4.json, packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts, packages/@react-native-windows/codegen/src/generators/ParamTypes.ts, packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts, vnext/codegen/NativeAlertManagerSpec.g.h, vnext/codegen/NativeAnimatedModuleSpec.g.h, vnext/codegen/NativeAnimatedTurboModuleSpec.g.h, vnext/codegen/NativeAsyncLocalStorageSpec.g.h, vnext/codegen/NativeAsyncSQLiteDBStorageSpec.g.h, vnext/codegen/NativeBlobModuleSpec.g.h, vnext/codegen/NativeDialogManagerAndroidSpec.g.h, vnext/codegen/NativeExceptionsManagerSpec.g.h, vnext/codegen/NativeImageLoaderAndroidSpec.g.h, vnext/codegen/NativeImageLoaderIOSSpec.g.h, vnext/codegen/NativePermissionsAndroidSpec.g.h, vnext/codegen/NativePushNotificationManagerIOSSpec.g.h, vnext/codegen/NativeSettingsManagerSpec.g.h, vnext/codegen/NativeUIManagerSpec.g.h, vnext/codegen/NativeVibrationSpec.g.h, vnext/codegen/NativeWebSocketModuleSpec.g.h
Generate `std::vector<T>` for array types in turbo modules. For array that doesn't have an element type in the spec, `React::JSArrayValue` is used.
=> Generate `std::vector<T>` for array types in turbo modules

change/react-native-windows-b3faee3f-5f44-4ab0-8532-681cc91ef447.json, packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props
This PR bumps the hermes package to align with OSS v0.9.0.
No functional changes are expected.
=> Bump hermes to v0.9

change/@office-iss-react-native-win32-2021-09-02-12-08-11-sammy-63_A11yItemType.json, packages/react-native-win32/docs/api/react-native-win32.basepropswin32.md, packages/react-native-win32/etc/react-native-win32.api.md, packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
I will backport this to .65/.64/.63
=> [0.63] Adding Accessibility Prop accessibilityItemType on ViewWin32

change/@office-iss-react-native-win32-b5400f80-1f0f-427d-b146-eccde1f97d33.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backporting changes from #7796 and #8126 .
I will backport this to .66/.65/.64/.63
UIA_ItemTypePropertyID -
Identifies the ItemType property, which is a text string describing the type of the automation element.
ItemType is used to obtain information about items in a list, tree view, or data grid. For example, an item in a file directory view might be a "Document File" or a "Folder".
When ItemType is supported, the string must match the application UI language or the operating system default UI language
=> [0.66] Adding Accessibility Prop accessibilityItemType on ViewWin32

change/@office-iss-react-native-win32-8ddaf053-3177-44c4-96d4-011a8d19342e.json, packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
I will backport this to .65/.64/.63
=> [0.64] Adding Accessibility Prop accessibilityItemType on ViewWin32

change/@react-native-windows-codegen-35c7ec51-4ff3-4dfc-abd9-4a23a2e988d5.json, change/react-native-windows-ea9cb68a-e7bd-4c3f-91c0-2bd67f436916.json, packages/@react-native-windows/codegen/src/generators/AliasGen.ts, packages/@react-native-windows/codegen/src/generators/AliasManaging.ts, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts, packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts, packages/@react-native-windows/codegen/src/generators/ParamTypes.ts, packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts, vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp, vnext/Microsoft.ReactNative/Modules/AppStateModule.h, vnext/codegen/NativeAccessibilityManagerSpec.g.h, vnext/codegen/NativeActionSheetManagerSpec.g.h, vnext/codegen/NativeAppStateSpec.g.h, vnext/codegen/NativeAsyncLocalStorageSpec.g.h, vnext/codegen/NativeAsyncSQLiteDBStorageSpec.g.h, vnext/codegen/NativeFrameRateLoggerSpec.g.h, vnext/codegen/NativeImageEditorSpec.g.h, vnext/codegen/NativeImagePickerIOSSpec.g.h, vnext/codegen/NativeImageStoreIOSSpec.g.h, vnext/codegen/NativeNetworkingIOSSpec.g.h, vnext/codegen/NativePushNotificationManagerIOSSpec.g.h, vnext/codegen/NativeShareModuleSpec.g.h, vnext/codegen/NativeStatusBarManagerIOSSpec.g.h, vnext/codegen/NativeWebSocketModuleSpec.g.h
- Anonymous objects are replaced with `REACT_STRUCT`, `React::JSValueObject` will not be used anymore.
- Anonymous objects could appear in in anonymous objects and aliased objects, the order in the header is important.
- Names for a anonymous object show the location where it is used, e.g.:
- MODULESPEC_METHOD_ARGUMENT
- ALIASEDSTRUCT_FIELD
- etc
- `AppState` is updated to match the updated `NativeAppStateSpec`
=> Generate anonymous objects for turbo module

change/react-native-windows-397fc10d-00fc-436e-acbb-457e1ce17b5e.json, vnext/src/Libraries/Components/View/ViewWindowsProps.ts
This provides better type information for some of the additional properties that we've added to view in react-native-windows.
These properties are available by using `import {ViewWindows} from 'react-native-windows'` instead of `import {View} from 'react-native'`
=> Provide more TS type information for ViewWindows

change/@react-native-windows-cli-351665bb-29ec-4fb8-93fa-fa627d7d4d18.json, packages/@react-native-windows/cli/src/healthChecks.ts
Health check code doesn't handle paths with spaces.
Fixes #7597
=> Health check code doesn't handle paths with spaces

change/@react-native-windows-cli-6c46e85a-7b25-4067-971c-737433a62ced.json, packages/@react-native-windows/cli/src/e2etest/autolink.test.ts, packages/@react-native-windows/cli/src/e2etest/runWindows.test.ts, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts, packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Commander (the library used by the RN CLI to define/parse CLI args) does
not support setting defaults for boolean flags. All such options are
resolved to either `true` (if present) or `undefined` (if specified in
the --no-flag format and present).
This PR was extracted from PR #8253, and cleans up the CLI options to
not specify defaults for boolean flags, as they are ignored by Commander
and are therefore potentially misleading. The RunWindowsOptions and
AutoLinkOptions interfaces have been updated to reflect these changes,
and tests were added to make sure we don't set useless defaults in the
future.
This PR also fixes the formatting of autolink.test.ts, which did not
have the proper copyright header and therefore was not being checked by
eslint.
Closes #8630
=> Fixed CLI options defaults

.ado/publish.yml, .ado/templates/prep-and-pack-nuget.yml, .ado/templates/prep-and-pack-single.yml, change/react-native-windows-4ba0a096-3ae5-48d9-92c2-9ef0966f6f61.json, vnext/Scripts/PublishNugetPackagesLocally.cmd
This PR start us generating symbol packages for our nugets, in order to reduce the bandwidth and disk space costs of developers who don't debug our code.
For the moment this will only affect the daily main/canary nugets, so we can work out any publishing kinks (and dev dev setup instructions) before enabling in other branches.
Closes #6011
=> Enable publishing NuGet symbol packages

packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityInfoExample.js
Adding an example of using `accessibilityInfo.setAccessibilifyFocus` with TouchableWithoutFeedback components as it's a bit of a trickier use case.
=> Add accessibilityInfo example to RNTester 

change/react-native-windows-9991abee-8b19-4ff1-a209-7478d569bfe2.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, yarn.lock
**_Why_**
Integration from core #8535 broke Fast Refresh functionality on Windows.
**_What_**
Break came from change in HMRClient.js in https://github.com/facebook/react-native/commit/f085e09be5a148065d286ba3950324dc9e44b7f6. Default value used for Metro scheme was changed to 'http' from 'ws'. Updated Windows HMRClient instance which relied on default 'ws' scheme value. Fast Refresh functionality restored. 
Fixes #8608
=> Restore Fast Refresh Functionality

change/react-native-windows-c815a24d-e3b1-4071-8f69-3461f31545ed.json, vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
When someone sets `pointerEvents="none"` on a View component, we currently set `IsHitTestVisible` to false on the ViewPanel instance. If the user has done something that forces the ViewPanel to be replaced by a ViewControl, we will not have set `IsHitTestVisible` on the ViewControl and will not also transfer that property if `pointerEvents="none"` is set before the transfer occurs. This change ensures IsHitTestVisible is always set on the correct view.
Fixes #8531
=> Ensures IsHitTestVisible is set on correct view

change/react-native-windows-83a35785-ab50-466c-80bd-5e9937041fe5.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
**_Why_**
Integration from core #8535 broke Fast Refresh functionality on Windows.
**_What_**
Break came from change in HMRClient.js in facebook/react-native@f085e09. Default value used for Metro scheme was changed to 'http' from 'ws'. Updated Windows HMRClient instance which relied on default 'ws' scheme value. Fast Refresh functionality restored.
Backport #8635 to 0.66
=> [0.66] Restore Fast Refresh Functionality

change/react-native-windows-926ba5d6-6de7-4b3a-82ff-44117751b1ba.json, vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp, vnext/src/Libraries/Components/Flyout/FlyoutProps.ts
Adds the ability to set the `FlyoutBase::ShouldConstrainToRootBounds` property in the `FlyoutViewManager`.
Co-authored-by: Liron Yahdav <lyahdav@fb.com>
=> Adds shouldConstrainToRootBounds prop to Flyout

change/react-native-windows-671c670f-d58d-436a-877e-0a6e3107b87e.json, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Fixing a break in TextViewManager from a PR conflict:
-  PR checks for https://github.com/microsoft/react-native-windows/pull/8454 were run before https://github.com/microsoft/react-native-windows/pull/8516 was merged in & both made changed to the same file.
=> Fix TextViewManager from a PR conflict

packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardExample.tsx
In order to test `tabIndex`, a component must be focusable. In the keyboarding example page we use TouchableHighlight in the tabIndex example, this adds an onPress() function to those components to make them focusable and make the example functional.
=> [RNTester] Fix tabIndex Example

.ado/publish.yml
This PR changes the publish pipeline to start codesigning daily main
release builds, so they can start to be published to Nuget.org. This
PR also enables symbol packages for all release builds.
This is a continuation of the work started in PR #8626 for issue #6011.
This also sets the groundwork to be able to resolve issue #8529.
=> Enable codesigning in main, enable symbol packages for everyone

change/react-native-windows-94cfe0bf-1f44-4ee0-9e13-50c52c85610d.json, vnext/Shared/HermesSamplingProfiler.cpp, vnext/Shared/Utils.cpp, vnext/Shared/Utils.h
Essentially, we are adding a new function to fetch the application data directory which works with both packaged and unpackaged apps, and consuming it in Hermes sampling profiler.
This change needs to be ported to RN66.
=> Issue#8397: Hermes profiler needs more work to function in win32 unpackaged apps

change/react-native-windows-e5514276-02c7-4ebb-bece-2744e53be34b.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp, vnext/Microsoft.ReactNative.Cxx/NativeModules.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
- Add REACT_GET_CONSTANTS to turbo module
- It requires a function returning a `REACT_STRUCT` decorated struct, fields become constants
- Update Microsoft.ReactNative.CxxUnitTests
- Update Microsoft.ReactNative.IntegrationTests
- **Type checking not included in this PR**
=> Add REACT_GET_CONSTANTS to turbo module

change/react-native-windows-6e731943-941d-4e37-8582-1a0d32e94184.json, vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
**_Why_**
When a native animation is rendered which uses interpolation with clamping, the animation has buggy visual behavior. Animation does not perform as expected.
**_What_**
Clamping logic incorrect. Sets clamped value to input range instead of output range for left and right extrapolation. Edited clamping logic to correct behavior. 
Fixes #7214
=> Fix Bug in Native Animation Interpolation Clamping

change/react-native-windows-8490e8f1-dbb7-4010-8f94-062a27aa2994.json, vnext/Microsoft.ReactNative.sln
ComponentTest doesn't build in any flavor, see #8673.
It _was_ building for x64 debug until recent changes caused a new build
break that _only_ gets hit in publish (the only place we build x64
debug).
This PR disables the project all up to unblock publish until we can
decide what to do with the project.
Closes #8671
=> Disable broken x64 debug build of ComponentTest

change/@react-native-windows-cli-cd23fb1b-e116-44b4-a453-217abeecdedd.json, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
when `projectName` is specified in the `windows` config block and
more than one `AppxManifest.xml` is found, `projectName` should be
used to disambiguate as intended. this works when called from
`deployToDesktop`, but `deployToDevice` does not currently pass the
overridden `projectName` to `getAppxManifestPath`.
add a `projectName` parameter to `getAppxManifest` and modify
`getAppxManifest` to pass the argument along to
`getAppxManifestPath` instead of `undefined`.
=> fix(deploy): broken projectName override for deployToDevice

change/react-native-windows-2021-09-21-14-02-03-fix-arm64-layout.json, vnext/DeforkingPatches/ReactCommon/yoga/yoga/YGValue.h, vnext/overrides.json
The commit message pretty much says it all - Yoga is using NAN, which happens to be defined in such a way that, if you:
1. Compile with /fp:strict (which do due to #4122; this should be fixed. I'll be making a new issue for that later today).
2. Set the rounding mode to round down
Then NAN is not a not-a-number value, but instead a plain old 0! Since YGUndefined is used for the unconstrained dimension in a flexbox layout, this goes... _very_ wrong.
=> [0.63] Fix ARM64 layout issues in Office

change/react-native-windows-49aea85f-c897-49b0-83d2-ef8204b4c65f.json, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
Fix minor grammar error.
Clarify that JSIEngineOverride will be ignored while the web debugger is being used, since the browser responsible for debugging must use its own engine to debug correctly.
=> Update JSIEngineOverride doc_string

.ado/publish.yml, .ado/templates/prep-and-pack-nuget.yml, .ado/templates/prep-and-pack-single.yml, change/react-native-windows-9b7711a1-087c-4e91-aa59-f72cf6689f5d.json, vnext/Scripts/PublishNugetPackagesLocally.cmd
This PR stops the creation of symbol packages, as implemented by PRs #8626 and #8658.
Unfortunately the E2E of publishing and consuming such packages was not
viable.
=> Revert creation of symbol packages, main codesign

.github/ISSUE_TEMPLATE/config.yml
This was removed in the previous change to [move to issue forms](https://github.com/microsoft/react-native-windows/pull/8639), but I found out how to add just a simple link to the list so that we can direct people to Discussions.
=> Bring back Questions list item via config.yml link

.ado/templates/setup-certificate.yml
**_Why_**
Restore CI Build. #8672 missing one line change needed to successfully retrieve certificate data to sign CLI tester build.
=> Restore CI Build

change/react-native-windows-00365c35-3f39-4262-9631-ae26ee94631b.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp, vnext/Microsoft.ReactNative.Cxx/NativeModules.h
When constants are required in a module, the following code could be added to the spec to enforce type checking:
```c++
struct MyTurboModuleSpec : winrt::Microsoft::ReactNative::TurboModuleSpec {
static constexpr auto constants = std::tuple{
TypedConstant<MyTurboModuleConstants1>{0},
TypedConstant<MyTurboModuleConstants2>{1},
};
template <class TModule>
static constexpr void ValidateModule() noexcept {
constexpr auto constantCheckResults = CheckConstants<TModule, MyTurboModuleSpec>();
REACT_SHOW_CONSTANT_SPEC_ERRORS(
0,
"MyTurboModuleConstants1",
"    REACT_GET_CONSTANTS(GetConstants1) MyTurboModuleConstants1 GetConstants1() noexcept {/*implementation*/}\n"
"    REACT_GET_CONSTANTS(GetConstants1) static MyTurboModuleConstants1 GetConstants1() noexcept {/*implementation*/}\n"); …
```
=> Add CheckConstants<TModule, TModuleSpec> for REACT_GET_CONSTANTS

change/@react-native-windows-automation-0bb4044e-9656-4374-9679-1a1c6e2c6e3f.json, packages/@react-native-windows/automation/.eslintrc.js, packages/@react-native-windows/automation/src/index.ts
This is a high-level type that can be useful to use as a return type for helpers in app-code. Export it from the @react-native-windows/automation entry-point.
=> Export AutomationElement type

change/react-native-windows-cfcd8b42-ad9b-49b8-9bb5-28f8a60c27d3.json, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Mso/future/futureWinRT.h
=> [0.66] ReactNativeHost ReloadInstance and UnloadInstance actions do not always complete

change/react-native-windows-cfcd8b42-ad9b-49b8-9bb5-28f8a60c27d3.json, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Mso/future/futureWinRT.h
=> [0.65] ReactNativeHost ReloadInstance and UnloadInstance actions do not always complete

change/react-native-windows-cfcd8b42-ad9b-49b8-9bb5-28f8a60c27d3.json, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Mso/future/futureWinRT.h
=> [0.64] ReactNativeHost ReloadInstance and UnloadInstance actions do not always complete

change/react-native-windows-2021-09-27-19-45-59-v8jsi-0.63.16.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.ComponentTests/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/React.Cpp.props
**NOT a backport**
- Upgrade to V8-JSI 0.63.16
The V8-JSI verison deployed in Office differs from the one in this branch.
=> [0.63] Upgrade V8-JSI to 0.63.16

change/@react-native-windows-codegen-6c4bbd11-6b44-4efd-a05f-f9c8dd4cee28.json, change/react-native-windows-b42a7122-6b6e-4976-8994-ea45fecb435c.json, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts, packages/@react-native-windows/codegen/src/generators/ValidateConstants.ts, packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts, vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp, vnext/Microsoft.ReactNative/Modules/AppStateModule.h, vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp, vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.h, vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp, vnext/Microsoft.ReactNative/Modules/I18nManagerModule.h, vnext/codegen/NativeAppStateSpec.g.h, vnext/codegen/NativeBlobModuleSpec.g.h, vnext/codegen/NativeDeviceInfoSpec.g.h, vnext/codegen/NativeDialogManagerAndroidSpec.g.h, vnext/codegen/NativeI18nManagerSpec.g.h, vnext/codegen/NativeJSDevSupportSpec.g.h, vnext/codegen/NativePlatformConstantsAndroidSpec.g.h, vnext/codegen/NativePlatformConstantsIOSSpec.g.h, vnext/codegen/NativePlatformConstantsWinSpec.g.h, vnext/codegen/NativeSampleTurboModuleSpec.g.h, vnext/codegen/NativeSettingsManagerSpec.g.h, vnext/codegen/NativeSourceCodeSpec.g.h, vnext/codegen/NativeStatusBarManagerAndroidSpec.g.h, vnext/codegen/NativeStatusBarManagerIOSSpec.g.h, vnext/codegen/NativeToastAndroidSpec.g.h
- Update `GenerateNM2.ts` to create constant spec for turbo modules
- Move `REACT_CONSTANT` and `REACT_CONSTANT_PROVIDER` to `REACT_GET_CONSTANTS`
- AppStateModule
- I18nManagerModule
- DeviceInfoModule
=> Check constants in generated turbo module specs

.ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/templates/react-native-init.yml, change/react-native-windows-e156f81a-530f-4f46-8d56-42ecd56d221d.json, packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/Scripts/Tracing/Stop-Tracing.ps1
This change has
1. Consume new hermes package which loads icu.dll from Windows for local aware code, instead of the Win-NLS based implemented in which we have discovered bugs last week.
2. Enabling tracing in the CI jobs. This will help us better diagnose CI failures in future.
=> Make hermes consume icu.dll in Windows for local aware functions

change/react-native-windows-aaade5cd-5bf8-4e76-8a0f-ebf880e356b1.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative/ABIViewManager.cpp, vnext/Microsoft.ReactNative/ABIViewManager.h, vnext/Microsoft.ReactNative/IViewManager.idl, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp, vnext/Microsoft.ReactNative/ReactPointerEventArgs.h, vnext/Microsoft.ReactNative/ReactPointerEventArgs.idl, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.h, vnext/Microsoft.ReactNative/Views/ViewManagerBase.h, vnext/Microsoft.ReactNative/XamlView.h
Closes #8499
Currently, there is no way for ViewManagers to capture the pointer to perform it's own pointer event handling. This change introduces a new interface, `IViewManagerWithPointerEvents`, so third party modules can be notified when the ReactRootView receives pointer events. The behavior is as follows:
`ViewManagerBase` adds a virtual method:
`OnPointerEvent(object sender, ReactPointerEventArgs args)`
We have a `ReactPointerEventArgs` wrapper around `PointerRoutedEventArgs` that view managers can use to:
1. Call `PreventDefault` to suppress the corresponding React event from being emitted
2. Call `ReleaseCapture` to force the TouchEventEmitter to release pointer capture (triggering an `onTouchCancel` event to React Native)
3. Update the `Target` property to refine for hit testing …
=> Adds hook for view managers to capture pointer events

change/@react-native-windows-cli-fa19ef9a-896c-4af1-b889-400f32f2bd31.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/cli/src/config/configUtils.ts, packages/@react-native-windows/cli/src/e2etest/autolink.test.ts, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts, yarn.lock
Since version 0.7.0, xmldom is published to npm as @xmldom/xmldom and no longer as xmldom, because the package owners are no longer able to publish xmldom. See https://github.com/xmldom/xmldom/issues/271 for more information.
We need to upgrade our xmldom dependencies to mitigate CVE-2021-32796. See https://github.com/advisories/GHSA-5fg8-2547-mr8q. This issue was partially mitigated by commit bfc26ac38b14ddeb0c195e69faa22b0826727221, but that commit did not bump the version of xmldom used by @react-native-windows/cli. This PR does do. We would also need to backport this all the way back to 0.63 to mitigate security component governance alerts in internal dependent repos.
=> Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.

change/@react-native-windows-cli-2021-09-29-12-53-42-0.63-bump-pkg.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/cli/src/config/configUtils.ts, yarn.lock
Back port of 58c1fb59eaebbf496915921062540b963aff3685.
=> [0.63] Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.

change/@react-native-windows-cli-e0d819d2-894d-4c90-a47c-ec995d3cb9c5.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/cli/src/config/configUtils.ts, yarn.lock
=> [0.64] Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.

change/@react-native-windows-cli-904024e0-eb85-4b6b-b76e-32b697944ca5.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/cli/src/config/configUtils.ts, packages/@react-native-windows/cli/src/e2etest/autolink.test.ts, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts, yarn.lock
=> [0.65] Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.

change/@react-native-windows-cli-113a1b37-9c7d-4898-a6f1-770ddf115b6d.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/cli/src/config/configUtils.ts, packages/@react-native-windows/cli/src/e2etest/autolink.test.ts, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts, yarn.lock
=> [0.66] Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.

.ado/jobs/nuget-desktop.yml, .ado/jobs/project-reunion.yml, .ado/publish.yml, .ado/templates/prepare-env.yml, .ado/templates/react-native-init.yml
**_Why_**
NugetToolInstaller step of pipeline has been failing on and off for the last week.
**_What_**
Moved to NugetToolInstaller v1 from v0 in pipeline following suggestion in thread [here](https://developercommunity.visualstudio.com/t/DotNetTool-task-fails-randomly-with-ERR/1541538?space=21&q=nuget+download+tool&sort=newest). Since this buggy behavior is not consistent. Unclear if this change has resolved the issue, but will monitor over the coming weeks and see if behavior improves.
=> Upgrade NugetToolInstaller Instances to v1

change/react-native-windows-59521771-6e91-4fab-8b3b-3311d3dae8b7.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props
Backport of #8735
- Upgrade ReactNative.V8Jsi.Windows to 0.64.27
- Change files
=> [0.64] Upgrade V8 to version 9.5

change/react-native-windows-2ef55695-7158-4402-9b1c-3d457cb80f3c.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config
Backport of #8735
- Upgrade ReactNative.V8Jsi.Windows to 0.65.5
- Change files
=> [0.65] Upgrade V8 to version 9.5

change/react-native-windows-6a7327b1-a0a5-4a1a-b32d-fac4378feb1f.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config
Backport of #8735
- Upgrade ReactNative.V8Jsi.Windows to 0.65.5
- Change files
=> [0.66] Upgrade V8 to version 9.5

change/react-native-windows-90f786a3-38e1-415b-bfd8-2473d3bab6ec.json, vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp, vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp, vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
ImageLoader is currently implemented using a cxxmodule.  This replaces that implementation with a TurboModule that is type checked against the native spec.
=> Switch ImageLoader to be a codegen'd turbomodule

change/react-native-windows-b49059c5-b0c3-467a-a1aa-fbe285cb5fff.json, vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.h, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Adds functionality for box-only and box-none via OnPointerEvent callback 
This change checks if the React node has `pointerEvents="box-only"` or `pointerEvents="box-none"` set. If the node is `box-only`, it updates the `ReactPointerEventArgs.Target` view to itself (preventing children from becoming the hit test target for the React pointer event. If the node is `box-none` and the current `ReactPointerEventArgs.Target` value is the current view, it sets the target to `null`, forcing the `TouchEventHandler` to choose an ancestor as the hit target.
https://user-images.githubusercontent.com/1106239/131200698-1bf38123-33ea-49af-8aff-a2f0942d3193.mp4dfs
Fixes #8496
=> Fixes bugs for pointerEvents prop

.ado/jobs/cli-init.yml, .ado/jobs/sample-apps.yml, .ado/templates/react-native-init.yml, .ado/templates/run-windows-with-certificates.yml, change/@react-native-windows-cli-5cfe030a-4c31-41aa-9c38-1f9c624e5e4a.json, packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts, packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
This PR changes the CLI to always deploy from layout if:
- passed `--deploy-from-layout` (to force it) OR
- the build had `AppxSigningEnabled` missing or set to false OR
- the build had `PackageCertificateFile` not set
Alternatively, you can say we only try to deploy via package if BOTH
`AppxSigningEnabled` is set to true AND `PackageCertificateFile` is set.
Closes #8773
=> CLI: Default to deploy by layout

.ado/jobs/cli-init.yml, .ado/jobs/desktop.yml, .ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/jobs/jschecks.yml, .ado/jobs/playground.yml, .ado/jobs/project-reunion.yml, .ado/jobs/sample-apps.yml, .ado/jobs/universal.yml, .ado/publish.yml, .ado/variables/vs2019.yml
We will be creating multiple versioned images in the future for RNW. We currently associate to an image by picking pool, but would rather not need a pool for every image we have.
This uses pool demands to allow us to override the image used by a pool supporting multiple images. This should allow us to create an image for each branch without needing a separate pool for each.
Internal folks can see https://eng.ms/docs/cloud-ai-platform/developer-services/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/demands for details.
Validated that changing the value exhibits behavior of different images I created.
=> Allow Setting Managed Image Independently of Pool

.ado/jobs/playground.yml, .ado/templates/build-rnw.yml, change/react-native-windows-6e463863-71ac-46eb-a69c-d91fc6d7cec5.json, vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
Make all vsbuild tasks multicore builds, we run on 4 or 8 core boxes, silly to still be doing single-threaded builds.
Improve performance of our PR and CI validations
=> Make all msbuild in PR and CI multicore builds

change/@react-native-windows-cli-da13474f-cd34-41ae-94d0-2fa8c9bf4d78.json, packages/@react-native-windows/cli/README.md, packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
x64 is likely more important than x86 for most, and @dannyv discovered the x86 build will also build x64 due to AppX targets (looking at that separately).
This causes the CLI to build x64 by default on x64 machines, and ARM64 by default on ARM64 machines.
=> Default `run-windows` to building system architecture

.ado/jobs/playground.yml
https://github.com/microsoft/react-native-windows/pull/9004 accidentally changed `restoreNugetPackages: false` to `restoreNugetPackages: true`. Revert that change, to unblock validation.
=> Fix playground PR

.github/dependabot.yml
Dependabot can open up to 10 PRs at once, which can starve CI resources.
This change reduces the number of open PRs to 5.
=> Reduce dependabot "open-pull-requests-limit"

.ado/publish.yml
A recent change nicely split up our prepare scripts.
But to build rnw, we need to run at least 'yarn install' so that we can find the folly version to download from github in the publish pipeline...
At the moment this does more than it needs to as it also runs `yarn build` which technically isn't needed in the publish phase. But this is just to unblock the publish pipeline for the canary builds.
None, will check if the publish pipline succeeds after merging...
=> Fix Publish pipeline

.ado/continuous.yml, .ado/jobs/setup.yml, .ado/stages.yml, .ado/windows-vs-pr.yml
CI is failing after my recent changes due to differences between setup phases.
This change consolidates the setup job into a single sequence, to ensure changes happen in unison, and to allow us to get further in CI.
=> Share setup job between PR and CI

.ado/jobs/nuget-desktop.yml, .ado/jobs/project-reunion.yml, .ado/publish.yml, .ado/templates/prep-and-pack-nuget.yml, .ado/templates/react-native-init.yml
I switched from publishing build artifacts to publishing pipeline artifacts. This seems to change behavior to no longer allow overlapping artifact names, where the previous allowed them so long as there were not overlapping files within the artifact.
Artifacts are already partitioned in PR, but are still shared in publish. This change makes it so Desktop, MSRN, and Reunion are separate artifacts in publish as well.
This also reminded me that Reunion has a different version of MSRN, which isn't an issue with segregated NuGet creation in PR, but needs special attention in CI.
=> Segregate artifacts in publish

.ado/jobs/cli-init.yml, .ado/templates/prepare-build-env.yml, change/react-native-windows-df7a4350-83c2-46df-995f-2de1f60a9e70.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/FastBuild.targets
We have an option to use larger PCH's which can dramatically speed up build time on high end machines. It causes build instability on machines with less memory though (e.g. hosted agents, or 8c/16T 32GB systems). The larger PCH is opt-in via environment variable because of this. Not all users with powerful machines will know the variable exists, and may not be using the optimally sized PCH for their build setup. 
This change enables dynamic selection of PCH size based on available system memory. This is done via adding the `RNW_FASTBUILD` preprocessor definition based on a memory-per-thread (how much memory will a cl process get) threshold.
Large PCH saw issues with previous hosted machines, which were 3.5GB per thread. New machines have 8GB per thread, and do not see issues. Enable using …
=> Automatically Use Large PCH on Machines With >7GB per Thread

.ado/templates/publish-build-artifacts.yml
Azure pipelines allows re-running an already completed job. The pipeline artifacts between attempts are shared. Subsequent build artifacts may collide with each other, causing failure to upload pipeline artifacts.
Attempts run against the same set of source code. Our binaries are not yet fully deterministic from source, but should be similar enough to allow a "pick any" scheme of binaries from different attempts.
This change skips publishing binary artifacts if they were already published by a past attempt. It is not conveniently possible to test for the existence of an artifact, so we instead just allow the intermediate artifact publish to fail, and emit a warning instead of stopping the build.
=> Permit failure to publish intermediate build artifact

.ado/jobs/jschecks.yml, .ado/jobs/setup.yml, .ado/publish.yml, .ado/templates/react-native-init.yml
Beachball added a new `--verbose` option that improves diagnostics. 
Leverage the flag in rnw's PR/CI/CD scripts
=> Leverage new --verbose flag of beachball in CI/CD

beachball.config.js, package.json, yarn.lock
MSBuild version stamping is triggered by hooking into beachball. Right now we hook into prepublish, then modify Git history. This change uses a newly introduced hook to instead stamp versions during the bump phase.
=> Use beachball bump hook for version stamping

.ado/publish.yml, .ado/templates/react-native-init.yml, change/react-native-windows-d76f4c73-02fd-48c6-84ef-ed292bceefb1.json
PR errors seem to imply Beachball publish behavior has changed, to leave updated package.json files and changelogs after the publish command is completed.
We previously had code which added a commit to the beachball temporary branch. I think this may have also commited the bumped files, hiding the change from us. #9062 removed code which injected the commit, which means we now see bumped files in the directory tree after publish. This breaks the bump step, which assumes the project files are unbumped.
This removes the step to bump, since we should now have bumped artifacts already.
PR will let us know if fix attempt is successful. Will monitor that RN version reported by env vars if correctly bumped.
=> Fix Beachball Errors in Init Tests

change/react-native-windows-3b12d628-e43a-4181-8e8e-a9ab87d07b25.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets, vnext/PropertySheets/FixupRoslynCscWarnings.targets
We use RoslynCodeTaskFactory to compile inline C# in our MSBuild scripts and execute it with .Net Core. When running under ARM64, `DotNetSdk_LibraryPath_arm64 = C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\arm64` is added to the `csc` library path, but is unused, and not actually present by default. This generates compiler warnings, failing the build with MsBuildWarnAsErrorArgument, despite creating a succesful assembly. This also affects our ARM64 NuGet packages, which run inline C# as part of their targets. We were not testing these in CI though.
Fixes #9063
This change alters the environment to supress the warning, allowing our CI tasks with `/warnaserror` to pass.
Validated locally that the warning is no longer present …
=> Fix Warnings from RoslynCodeTaskFactory in C++ Projects Building ARM64

change/react-native-windows-f0084024-b791-4e76-a6ba-cdef4c805415.json, packages/@react-native-windows/tester/src/js/examples-win/Mouse/MouseExample.windows.js, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
When `onMouseEnter` or `onMouseLeave` is set, react-native-windows sets a transparent background by default on a View if it has no other background. Since we were setting the `Panel::Background` property directly instead of using the `ViewPanel::ViewBackground` property, the transparent background could be cleared out after being set. This change ensures that the transparent background is set even if a border is applied.
Resolves #9034
Switched from using `Panel::Background` to `ViewPanel::Background` for default Transparent SolidColorBrush when mouse events registered.
Before:
https://user-images.githubusercontent.com/1106239/139733354-ab0f7bcc-d400-494d-a78e-921c2ce47afd.mp4
After: …
=> Fixes default background for mouse events with border

.ado/jobs/setup.yml
We are seeing issues again with Beachball hanging with missing changefiles. Fail the job if Beachball hangs.
=> Add timeout to Setup Step

change/@react-native-windows-automation-c32fc21b-3839-4bbe-b34b-0af4877b105f.json, docs/e2e-testing.md, packages/@react-native-windows/automation/README.md, packages/@react-native-windows/automation/package.json, packages/@react-native-windows/automation/src/AutomationEnvironment.ts, packages/e2e-test-app/jest.debug.config.js, packages/e2e-test-app/package.json, yarn.lock
It is not easy to debug native code being called by `e2e-test-app`, since it is not easy to attach a debugger while the app is being started, restarted, manipulated.
Resolves #7224
Adds "break on start" to UI automation infrastructure. Callable using `yarn e2etest:debug` from e2e-test-app.
Validated locally that the test is paused with the native app open before hitting enter, and that the test resumes after.
=> Add e2etest:debug (`@react-native-windows/automation` option `breakOnStart`)

change/react-native-windows-ca2dbe30-182a-42fa-8afb-2ee4b327e019.json, vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj, vnext/Shared/OInstance.cpp
ChakraCore support has been dropped. Only System Chakra is still used.
- Short-circuit ChakraCore to Chakra
- Delete remaining references to JSI.ForceSystemChakra
=> Remove JSI.ForceSystemChakra runtime option

change/@office-iss-react-native-win32-c738962f-151a-4e5e-a805-db5e73f40dda.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Adding the `enableFocusRing` prop for RNWin32's View.
To enable using native to implement focus visuals while giving clients the flexibility to use JS to implement focus visuals if necessary. This brings the platform closer to alignment with RNW and RNMacOS behavior, and allows us to stage the change in a way which minimizes current clients using RNWin32.
This change will be backported back to 0.64 so that it can be consumed by Office.
Added `enableFocusRIng` prop to the typing for ViewWin32. Also added `enableFocusRing` to the list of `validAttributes`.
Without focus:
With focus (visuals from native):
Added a test for the ViewWin32 test on the react-native-win32 tester app.
_Optional_: Ran test against local changes to native. …
=> Add `enableFocusRing` to RNWin32 

change/react-native-windows-b73de70e-deb8-4965-b68d-d923af8e564e.json, vnext/Shared/OInstance.cpp
Fixes a crash in win32 as fallout from #9094.
JSBigFileString::fromPath is stubbed out in win32, we should be using FileMapped files to load the bundle instead.
=> [0.64] Fix crash loading bundle in win32

change/@office-iss-react-native-win32-3442d9c5-966e-4f0c-9ae5-5e779e1edc4a.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
Fix test case that I forgot to change and checked in as part of #9110 
One of the test cases I added for enableFocusRing is supposed to test it in the false case, but I accidentally set it to true
Change to test to set enableFocusRing to false for the relevant test
Tested app locally
=> Fix `ViewWin32` test for `enableFocusRing`

change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json, packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
This PR backports #8587 to 0.66.
This PR fixes autolinking to properly handle modifying solution files
that have LF line endings (which can happen when cloning a repo that
didn't maintain the CRLF we use in our template).
Closes #8530
What changes were made to the codebase to solve the bug, add the functionality, etc. that you specified …
=> [0.66] Fix autolinking to support solution files using LF instead of CRLF

change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json, packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
This PR backports #8587 to 0.65.
This PR fixes autolinking to properly handle modifying solution files
that have LF line endings (which can happen when cloning a repo that
didn't maintain the CRLF we use in our template).
Closes #8530
What changes were made to the codebase to solve the bug, add the functionality, etc. that you specified …
=> [0.65] Fix autolinking to support solution files using LF instead of CRLF

package.json, yarn.lock
Add resolution for z-schema to address CVE-2021-3765 in validator. 
z-schema is used by rush which is a dependency of lage which we use as a dev-dependnecy. 
So this should not be executed in this repo anyway."
=> Add dependency resolution to address CVE-2021-3765 in validator

change/react-native-windows-a3e7fa27-57ec-4eb0-b036-c7da150c5239.json, vnext/Shared/OInstance.cpp
Fixes a crash in win32 as fallout from #9094.
JSBigFileString::fromPath is stubbed out in win32, we should be using FileMapped files to load the bundle instead.
Forward-port of #9116.
=> Fix crash loading bundle in win32

change/react-native-windows-63383496-65ba-4bbd-8fbe-ae1663fea35c.json, vnext/Shared/OInstance.cpp
=> [0.67] Fix crash loading bundle in win32

change/react-native-windows-4a6967e7-18f0-4732-878f-4858417b5dd7.json, vnext/Shared/OInstance.cpp
=> [0.66] Fix crash loading bundle in win32

change/react-native-windows-ac49a748-6516-4a80-8251-89f2de56b5d1.json, vnext/Shared/OInstance.cpp
=> [0.65] Fix crash loading bundle in win32

change/@office-iss-react-native-win32-c738962f-151a-4e5e-a805-db5e73f40dda.json, packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js, packages/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx, packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backport of #9110 and #9114 for Office.
=> [0.64] Add `enableFocusRing` to RNWin32

change/react-native-windows-24e6fa5c-585c-4ab0-8b32-13b19646a7f3.json, vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props, vnext/PropertySheets/React.Cpp.props
Many projects incode `React.Cpp.props`, making it unnecessary to define `WindowsTargetPlatformVersion` or `WindowsTargetPlatformMinVersion`.
=> Remove redundant WindowsTargetPlatformVersion declarations

.ado/variables/vs2019.yml
The `windevbuildagents` pool is being retired soon and we shouldn't be running anything on it.
If you added tests that prove your changes are effective or …
=> [0.65] Change AgentPool.Large to rnw-pool-8

change/react-native-windows-bb5ddd31-2e47-4031-b9da-27d8ec921ec8.json, vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.h, vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp, vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h
Native animations must fire completion callbacks when they finish.
Resolves  #9157
The AnimationDrivers were being stored as unique_ptrs, but internally use a weak_ptr to handle completion callbacks. When attempting to convert the weak_ptr to a shared_ptr, the conversion would always return an empty pointer because the constructor was not called from a shared_ptr.
This changes the NativeAnimatedNodeManager to hold shared_ptrs to AnimationDrivers to ensure that callbacks fire when the composition scoped batch completes for the animation.
Here's a recording to contrast with the "before" video in the linked issue:
https://user-images.githubusercontent.com/1106239/142242239-d8f9751f-80b9-4ee0-8589-38a660b0a9e5.mp4
=> Ensure native animations fire completion callbacks

change/@react-native-windows-telemetry-2b84c3a1-6327-4e87-9833-c8a67256ca07.json, packages/@react-native-windows/telemetry/src/telemetry.ts
We need a way to be able to specify different setup strings and proxy servers for the telemetry. We can do this in code, but that's not always an option, for example in the case of `react-native-windows-init` which is called by using npx.
Adding these environment variable overrides will help us test the telemetry system before (and after) we go live and turn it on.
Example:
```cmd
set RNW_TELEMETRY_SETUP=12345678-abcd-abcd-abcd-1234567890ab
set RNW_TELEMETRY_PROXY=http://localhost:8888
```
Closes #9166
=> Add environment variable overrides to specify telemetry setup string and proxy

.ado/jobs/universal.yml
It looks like we had to do some directory swapping magic when using the old windev build agents so the test tasks could find the binaries. That's no longer required now that we're off that pool.
Also apparently the new pool doesn't have all of the dependencies to build/test RNW 0.65? So changing the dependency check to install those missing bits.
=> Fix 0.65 CI

change/@react-native-windows-telemetry-733c82bd-37df-4935-a8fd-9f0ef10dad8d.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts, yarn.lock
Some tests were checking for the presence of npm/yarn before checking
its version. Since we almost always have those installed, I rearranged
the tests to look for the version first, and only if it returns null do
I check to confirm the tool is indeed missing.
Closes #9183
=> Fix telemetry unit test timeouts

change/react-native-windows-a114d733-624e-4270-b49c-6d6f005bc5e8.json, packages/@react-native-windows/tester/src/js/examples-win/Mouse/MouseExample.windows.js, vnext/.flowconfig, vnext/Microsoft.ReactNative/Views/Text/TextHitTestVisitor.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp, vnext/overrides.json, vnext/src/Libraries/Components/View/ReactNativeViewAttributes.windows.js
Any view can subscribe to `onTouchStart` / `onTouchEnd` / etc., as well as `pointerEvents`, but not every view can register for `onMouseEnter` / `onMouseLeave`, which feels inconsistent.
Additionally, the `onMouseEnter` / `onMouseLeave` approach on react-native-macos allows arbitrary views to register for these events, so this makes things more consistent across RN Desktop platforms.
Resolves #9054
This change allows arbitrary views (all core views, even virtual text nodes, and third-party view managers) to register to receive `onMouseEnter` and `onMouseLeave` events. This is particularly useful for text and third-party view managers and more consistent with the `onMouseEnter` / `onMouseLeave` …
=> Allow arbitrary views to register onMouseEnter/Leave

.ado/jobs/cli-init.yml
Fixes #9079
Validated with _7_  PR runs.
https://github.com/microsoft/react-native-windows/pull/9145 bumped the CLI package version, which should theoretically fix the EPERM issues we were seeing (with https://github.com/react-native-community/cli/pull/1495).
Reenable the lower resource hardware that was running into isues with EPERM.
=> Reenable low-resource builds

change/@react-native-windows-telemetry-59ec6aad-e0df-4b25-9435-3e02e2d6296b.json, packages/@react-native-windows/telemetry/src/telemetry.ts, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
Sometimes when running `react-native-windows-init` for a version of RNW prior to the telemetry refactor, an old 'generate-windows' even gets fired from the old cli module, and gets picked up by the new telemetry.
This PR adds a filter to only allow the new events that were defined in the refactor.
Closes #9179
=> Block old telemetry events from firing

.ado/jobs/universal.yml, change/react-native-windows-6ee7207e-33bb-4654-9f55-1a007584f2a0.json, vnext/Scripts/rnw-dependencies.ps1
This PR backports part of #8343 so that CI can build RNW 65 on our private machines.
=> [0.65] Make ADK dependency optional in dependency script

change/@react-native-windows-telemetry-2bc4bbb3-d817-4598-86cc-786b31a14866.json, packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts, packages/@react-native-windows/telemetry/src/test/sanitizeUtils.test.ts, packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
When calling `npx react-native-windows-init`, npx installs files into the users AppData folder, which we completely anonymize. This PR changes our sanitization to check if it's an npm package we own first, before checking if it's under AppData.
One new test added for this scenario, one test modified to expect this new behaviour, the rest of the tests still pass.
Closes #9180
=> Fix telemetry path sanitization to handle our packages in the npx cache

yarn.lock
Fixes security vulnerability CVE-2021-3918.
Fixes security vulnerability CVE-2021-3918.
Fixes security vulnerability CVE-2021-3918.
Update version of jsprim to get updated json-schema
=> CG: Update version of jsprim to get updated json-schema

yarn.lock
This PR backports #9207 to 0.67.
Fixes security vulnerability CVE-2021-3918.
=> [0.67] CG: Update version of jsprim to get updated json-schema

.ado/jobs/desktop.yml, .ado/jobs/project-reunion.yml, .ado/jobs/universal.yml
CG can't run during PRs because the author doesn't have permission
to connect to the CG service. For this reason we only get (and track)
alerts from CI and Publish. So right now were wasting anywhere from
1-3 minutes running CG in PRs.
This PR fixes that, and also moves CG to run after the code has built.
We were (in universal and reunion) instead running during the test
phase, which operates on downloaded artifacts and not the complete
original build output, which is necessary (by policy) for using CG.
Closes #9208
=> Update Component Governance to only run when needed

package.json, yarn.lock
This PR backports CG fixes #9207, #8859 and #8662 to 0.66.
* Update version of jsprim to get updated json-schema 
* Bump ansi-regex 5.0.0 to 5.0.1
* Bump tmpl from 1.0.4 to 1.0.5
=> [0.66] Backporting CG fixes

.ado/jobs/desktop.yml, .ado/jobs/project-reunion.yml, .ado/jobs/universal.yml
This PR backports #9215 to 0.67.
CG can't run during PRs because the author doesn't have permission
to connect to the CG service. For this reason we only get (and track)
alerts from CI and Publish. So right now were wasting anywhere from
1-3 minutes running CG in PRs.
This PR fixes that, and also moves CG to run after the code has built.
We were (in universal and reunion) instead running during the test
phase, which operates on downloaded artifacts and not the complete
original build output, which is necessary (by policy) for using CG.
Closes #9208
=> [0.67] Update Component Governance to only run when needed

change/react-native-windows-d97a7383-5070-4493-9ce2-305b9f6430a9.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Several native modules are currently hooked up in a way that causes them to queue up on the batching UI queue, even though they do not need to.  This can cause some modules to be slower than they need to be.  For example Websocket ends up posting its tasks to the UI queue, then the actual module will trigger async tasks on a background thread.  This increases the delay on websocket responses.
Internally, as part of moving Office to use code more in alignment with react-native-windows, I hit some issues with internal unit tests that break due to this.  In Office we've been running these modules on a background queue for years.
=> Some native modules are hitting the UI queue unnecessarily

change/react-native-windows-59359221-7fe0-4ed1-8380-000be6c2162b.json, vnext/.eslintignore, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/SyntaxError.js, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Mso/future/futureWinRT.h
- The async task returned by ReactHost.ReloadInstance() reports success, even if the bundle failed to load.
- The InstanceLoaded event has args that would report Failed() == false, even if the bundle failed to load.
Some error cases were not properly being reported up the to the application.
Fixing several places where future continuations were not bubbling errors up.
Added some UTs.
Two to test the value of the Failed property on InstanceLoadedEventArgs.
And one that tests the async task of ReloadInstance does not succeed.  (there is already one to test the success case)
=> ReloadInstance async task and InstanceLoaded event were not correctly reporting failures

change/react-native-windows-ffc796ec-456f-4aeb-9c7f-7603c237f26b.json, vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
When using a non-xaml UI implementation, the DetachViewInstance method does not get forwarded to the UI implementations.  This is required for Office to switch to using the RNW ABI.
=> Hook up DetachViewInstance method for custom UI implementations

change/react-native-windows-385ca057-498f-49e9-97b7-8961b3304e68.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
The InstanceCreated event can be used to augment the JS environment for all JS code.  So it needs to be triggered before any platform JS code is run. Using m_jsMessageThread instead of jsDispatchQueue avoids waiting for the JSCaller which can delay the event until after certain JS code has already run.
We need this to be able to consistently inject the platform bundles in Office.
=> InstanceCreated should fire before any JS code is run

change/react-native-windows-2d8a6176-a34a-4e44-a438-340cb7c3edd0.json, vnext/Shared/OInstance.cpp
Remove a bunch of logic that would look for a bundle at a bunch of different paths, while also making it hard to specify certain bundle paths.  This logic is only used in the desktop dll, and is not currently being used by office.  However, this code path will be used by Office when we switch to using the RNW ABI, so replacing the legacy bundle search code with logic much closer to the UWP logic.
Required for Office to move to the RNW ABI.
=> Remove legacy logic to find win32 bundle

change/react-native-windows-364ebba2-c500-41cd-87b0-cebc1bec0f6d.json, vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
We query for scalar values from the ValueAnimatedNode PropertySet but
then never use them. This change deletes these unused values.
=> Removes unused calls from NativeAnimated

change/react-native-windows-6643f7ba-6b50-4635-8d5b-2a631d41f5aa.json, packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj, packages/integration-test-app/windows/integrationtest/packages.config, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, vnext/Desktop/packages.config, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props
This change bring Hermes 0.10 into RNW 0.67
Essentially: `git cherry-pick 8fd1aae2335105fe28fa954536572f9d7fbb9372`
New Hermes version with Perf fixes
New Hermes version with Perf fixes
=> Hermes10 067

.ado/jobs/e2e-test.yml, change/@react-native-windows-automation-channel-b8c714c3-918d-4a57-ab51-ee7db0b831b9.json, change/@react-native-windows-cli-78d2c82c-1ee1-46c2-816a-32e57b886e94.json, change/react-native-windows-140f39a2-cef7-48cf-aeff-f57b8037b8e3.json, packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj, packages/@react-native-windows/cli/src/runWindows/utils/build.ts, packages/e2e-test-app/packages.config, packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground/Playground.vcxproj, packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj, packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj, vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj, vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.Common.props, vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props, vnext/PropertySheets/React.Cpp.props
This change introduces a shared `props` file to allow setting C++ NuGet depedency versions on a single place.
- Defines vnext\PropertySheets\External\Microsoft.ReactNative.Cpp.Dependencies.props
- Defines MSBuild property CppWinRTVersion
- Imports Microsoft.ReactNative.Cpp.Dependencies.props within React.Cpp.props and Microsoft.ReactNative.Common.props
=> Centralize CppWinRT version setting

change/react-native-windows-8058cea3-1388-4535-9689-7c2adc2c16e3.json, vnext/Microsoft.ReactNative/Modules/Animated/DecayAnimationDriver.cpp
- Cleanup dead code
It looks like we used to previously pull the start value on the fly and then later changed CalculatedAnimatedDriver to store the starting value in `m_startValue` and migrated to using that in DecayAnimationDriver in #3482.
Removes dead code for computing the startValue.
Decay animations still work:
https://user-images.githubusercontent.com/1106239/145284090-a2752865-b5c5-4af9-8cd7-d8ee3c52e531.mp4
=> Cleans up unused code from DecayAnimationDriver

change/react-native-windows-0d6139ae-27ea-40de-9914-b6b801e8fb03.json, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/JSEngine.props
Fixes #8824
This prevents automatic inclusion of Hermes into linked DLL when NuGet package targets are included. This avoids warnings when also using the HermesShim, and makes failure to go through HermesShim a link-time error (in release builds) instead of a WACK failure caught in CI.
=> Enable HermesNoLink

.ado/jobs/jschecks.yml, .ado/jobs/macos-tests.yml
Node16 fails  the codegen task in react-native-windows proejct during `yarn build`:
```
d:\src\r2\vnext> npx --no-install @react-native-windows/codegen --files Libraries/**/*Native*.js --namespace Microsoft::ReactNativeSpecs --libraryName rnwcore
npm ERR! canceled
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dannyvv\AppData\Local\npm-cache\_logs\2021-12-14T06_34_56_144Z-debug-0.log
```
The images have been updated to use node16 by default, so the CI is failing..
This change 'pins' node14 for our older branches.
=> [0.66] Force Node 14, as Node 16 fails codegen task of react-native-windows

.ado/jobs/jschecks.yml, .ado/jobs/macos-tests.yml
Node16 fails  the codegen task in react-native-windows proejct during `yarn build`:
```
d:\src\r2\vnext> npx --no-install @react-native-windows/codegen --files Libraries/**/*Native*.js --namespace Microsoft::ReactNativeSpecs --libraryName rnwcore
npm ERR! canceled
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dannyvv\AppData\Local\npm-cache\_logs\2021-12-14T06_34_56_144Z-debug-0.log
```
The images have been updated to use node16 by default, so the CI is failing..
This change 'pins' node14 for our older branches.
=> [0.65] Force Node 14 in build, as Node 16 fails codegen task of react-native-windows

change/react-native-windows-857f8e44-c7be-4025-827d-902572d0c205.json, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
Currently, the asynchronous callback for incoming WebSocket messages is defined in a member function and registered as follows:
```
m_socket.MessageReceived({this, &WinRTWebSocketResource::OnMessageReceived});
```
This will make access to `WinRTWebSocketResource`'s callbacks invalid if the class instance has already been destroyed.
This change prevents an access violation during `IMessageWebSocket::MessageReceived` by keeping a strong reference to the `WinRTWebSocketResource` instance, moving the definition from a member method to a capturing lambda:
```
m_socket.MessageReceived(
[self = shared_from_this()](IWebSocket const &sender, IMessageWebSocketMessageReceivedEventArgs const &args) {
...
```
See https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events#delegate-typ …
=> Use shared pointer in WebSocket MessageReceived

change/react-native-windows-56c880d7-2062-4dd3-828a-a054307770a4.json, change/react-native-windows-857f8e44-c7be-4025-827d-902572d0c205.json, change/react-native-windows-e21dbe3d-18ab-42a0-a4a3-f96fb8c0997f.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp, vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp, vnext/Desktop.UnitTests/BaseWebSocketTests.cpp, vnext/Desktop.UnitTests/WebSocketMocks.cpp, vnext/Desktop.UnitTests/WebSocketMocks.h, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp, vnext/Desktop/BeastWebSocketResource.cpp, vnext/Desktop/BeastWebSocketResource.h, vnext/Desktop/WebSocketResourceFactory.cpp, vnext/Microsoft.ReactNative/Modules/CreateModules.cpp, vnext/Shared/IWebSocketResource.h, vnext/Shared/InspectorPackagerConnection.cpp, vnext/Shared/Modules/WebSocketModule.cpp, vnext/Shared/Modules/WebSocketModule.h, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
- Avoid capturing raw `this` pointer in WebSocket module (#9247)
- Use shared pointer in WebSocket MessageReceived (#9293)
=> [0.67] Avoid capturing raw this pointer in WebSocket module

change/react-native-windows-73930e56-06d0-4c76-ba71-fa122944bbd3.json, change/react-native-windows-857f8e44-c7be-4025-827d-902572d0c205.json, change/react-native-windows-e21dbe3d-18ab-42a0-a4a3-f96fb8c0997f.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp, vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp, vnext/Desktop.UnitTests/BaseWebSocketTests.cpp, vnext/Desktop.UnitTests/WebSocketMocks.cpp, vnext/Desktop.UnitTests/WebSocketMocks.h, vnext/Desktop.UnitTests/WebSocketModuleTest.cpp, vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp, vnext/Desktop/BeastWebSocketResource.cpp, vnext/Desktop/BeastWebSocketResource.h, vnext/Desktop/WebSocketResourceFactory.cpp, vnext/Microsoft.ReactNative/Modules/CreateModules.cpp, vnext/Shared/IWebSocketResource.h, vnext/Shared/InspectorPackagerConnection.cpp, vnext/Shared/Modules/WebSocketModule.cpp, vnext/Shared/Modules/WebSocketModule.h, vnext/Shared/WinRTWebSocketResource.cpp, vnext/Shared/WinRTWebSocketResource.h
- Avoid capturing raw `this` pointer in WebSocket module (#9247)
- Use shared pointer in WebSocket MessageReceived (#9293)
=> [0.66] Avoid capturing raw this pointer in WebSocket module

Directory.Build.targets
- Use ItemGroup to print Vars properties
Trivial change for build debugging purposes only.
Upgrades the custom `Vars` target to use collections of MSBuild items instead of manually adding a new `Message` task for each MSBuild property to print.
- Informational
Adding new properties to the `Vars` target resulted in a lot of boilerplate code.
=> Categorize Vars target's items

change/@react-native-windows-telemetry-90748cb8-547c-4e1c-ba61-57a8df530393.json, change/react-native-windows-init-0a3d283c-7dc5-4965-9de9-97362a1466ed.json, packages/@react-native-windows/telemetry/src/telemetry.ts, packages/react-native-windows-init/src/Cli.ts
In order to find the versions of NPM packages, the telemetry code uses
node's require logic to find the package's package.json file.
However this means if the packages are not present, then node's resolver
cache will be populated with a false. This causes a problem if you
later install that package during the process (which is what we do with
react-native-windows-init) and try to require it - node will say it's
not there. This breaks creating new projects as node says it can't see
the newly installed react-native-windows/cli.
We were already "refreshing" the versions after we install RNW anyway,
since we know we're potentially changing them. This PR updates
react-native-windows-init to not try to get the versions at all until
after the new project generation has happened.
Closes #9271
=> Update when telemetry populates NPM package versions

CONTRIBUTING.md, README.md
This adds a CONTRIBUTING.md file to the root of the repo to follow GitHub's convention for specifying contribution guidelines. 
Format & content are heavily borrowed from our friends at [Terminal](https://github.com/microsoft/terminal/blob/main/CONTRIBUTING.md). 
This aims to replace the ["Contributing to Microsoft/react-native-windows"](https://github.com/microsoft/react-native-windows/wiki#contributing-to-microsoftreact-native-windows) wiki page by providing more comprehensive and rnw-specific information as well as linking to other docs which can otherwise be fairly difficult to find and piece-together.
In part addresses https://github.com/microsoft/react-native-windows-samples/issues/95. 
We'd like to make it easier to onboard to RNW as a contributor which will be helpful as a …
=> Adding a CONTRIBUTING file 

change/react-native-windows-f6c9b8a9-e496-4be1-a2a5-ad3a4a9bece8.json, vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp, vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp, vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.cpp
In the RN Animated API, the offset value should not change unless explicitly set by the user (or extract offset / flatten offset is called on the value node). In the previous composition implementation for NativeAnimated, the offset property in the CompositionPropertySet was animated, meaning if the user specified an offset value, its initial value was assumed to be zero for the spring and decay drivers, and more problematically, the animation needed to implicitly flatten the offset at the end of the animation.
Resolves  #9256
This change keeps a fixed offset during animations and instead animates the raw value.
RNTester animations still …
=> Animate value property rather than offset

change/react-native-windows-e28e82a4-9e7a-45c8-bb89-3010b55711b4.json, vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.cpp
When attempting to use `Animated.divide`, the app crashes in the base constructor for `ValueAnimatedNode` as it expects that the node config has an initial `value` and `offset` provided.
Resolves #9280
This change just uses the correct base constructor overload for the `DivisionAnimatedNode` and adds a missing `+` operator from the animation expression.
Tested a simple change in RNTester that introduced an innocuous `Animated.divide` node that divides the value by `1`. Before, the app crashed. Now the app no longer crashes.
=> Fixes crash when using `Animated.divide`

change/react-native-windows-94a433f4-aa44-431d-a5a5-322479b41c9d.json, vnext/Microsoft.ReactNative/XamlView.cpp, vnext/Microsoft.ReactNative/XamlView.h
There is a race condition on XAML Islands where the TLS compositor may not be set at the time we use it (e.g., for NativeAnimatedModule) if ReactRootView::Loaded has not yet fired.
Previously, there was an unnecessary conditional check if the app was running in a XAML Islands context, forcing XAML Islands to use the compositor stored in TLS.
This was not necessary, and causes a race condition where the compositor may not actually be set at the time it is needed (e.g., if you attempt to start a native animation in the first render pass).
This change merges the two GetCompositor overloads, and just sets a default value of null for the view in case we call the GetCompositor method with 0 arguments.
Ran RNTester NativeAnimated and Image …
=> Use Window::Current compositor on XAML Islands

.ado/templates/react-native-init.yml, change/react-native-windows-init-c07e0f56-99eb-4348-ba02-eb2da1977f88.json, packages/react-native-windows-init/src/Cli.ts, packages/react-native-windows-init/src/e2etest/cli.test.ts
A bug was introduced in #9174 which breaks specifying the `--version` option when calling react-native-windows-init. All boolean options now have defined defaults (we even test for it) but that means the `useDevMode` option is set to false instead of undefined. `useDevMode` conflicts with the `version` option, so if it's defined, even as false, yargs will complain if you try to specify a version.
The fix is to make useDevMode an optional boolean, with a default of undefined.
This also fixes our PR pipeline which should have caught this bug in the first place and failed the checks.
Closes #9342 
A bug was introduced in #9174 which breaks specifying the `--version` option when calling react-native-windows-init. All boolean options now have defined defaults (we even test for it) but that …
=> Fix `--version` option in react-native-windows-init

change/react-native-windows-332a5dcc-33ef-464e-b057-72cece380c6f.json, vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.cpp
Fixes #9253
The base constructor call in `DiffClampAnimatedNode` calls the `ValueAnimatedNode` overload that passes in the config, which
assumes that the initial `"value"` and `"offset"` properties are available in the config map. Similar to other `ValueAnimatedNode`
derived classes, `DiffClampAnimatedNode` should use the constructor overload for `ValueAnimatedNode` that does not pass the `config` map.
Before:
https://user-images.githubusercontent.com/1106239/145267696-ebc080af-1798-413e-8c2c-7e39b8ff6ddb.mp4
After:
https://user-images.githubusercontent.com/1106239/145267341-70bcd329-e73e-4a75-b702-071e741c3083.mp4
=> Fixes crash when creating DiffClampAnimatedNode

change/react-native-windows-dc6afdfd-5d3f-41ff-8cbc-3ac0ad348203.json, vnext/Microsoft.ReactNative/ABIViewManager.cpp, vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.h, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.h, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp, vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Currently, we mark a node dirty any time **any** prop is updated on a RN native view. In core at least, we really only need to do this for self-measuring views (Text and TextInput).
Where this causes the greatest concern is for RNW users that are forced to use the JS animation driver, either due to bugs in the NativeAnimated module or to animate props not supported by the NativeAnimated module (e.g., https://github.com/microsoft/react-native-windows/issues/3283). The JS driver aspires to fire at 60Hz, but obviously would not hit that mark because it's not a truly native animation. Even still, we should attempt to do as little work as possible.
This change narrows which props we mark the …
=> Reduce scope of marking YogaNode dirty

change/react-native-windows-13c812ce-c9cc-409b-94eb-467c8a6ddc80.json, vnext/Scripts/OfficeReact.Win32.nuspec, vnext/Scripts/Tfs/Layout-MSRN-Headers.ps1
Adding the codegen's spec files into the office nuget.  This will allow Office to use the spec files to get type verification on core TurboModules implemented within Office.
=> Publish codegen spec files into win32 nuget

packages/playground/windows/playground/MainPage.xaml
The new architecture is incompatible with web debugging, so we will be wanting to move users over to direct debugging. This also fixes longstanding inconsistencies between debug and release builds. ChakraUwp had issues around dev experience, e.g. symbolification, and debug experience. Hermes is now set up to support inspector, and DevTools integration.
Default playground to use direct debugging, to help us dogfood it before we switch over the default for users.
Playing with RNTester and comparing overall performance to web debugging. The optimized debug build I used felt a little slow but was not significantly worse than web debugging. This will also see long-term improvement with both NAPI work, where we may be able to use Hermes release-mode binaries.
=> Default `playground` to direct debugging

change/@react-native-windows-cli-2ad609f4-0c3c-44d4-8e13-4ecfd456a97b.json, change/react-native-windows-ee44eaf2-859d-439a-8bc3-589c7b0f4a19.json, packages/@react-native-windows/cli/src/generator-windows/index.ts, vnext/template/shared-app/proj/NuGet.Config
This PR changes the template for new projects to only include the ADO NuGet feed if the project is created against master/canary builds.
It's technically a security vulnerability to have more than one NuGet feed in a projects NuGet.config file. In fact, Microsoft ADO pipelines auto-inject a task that will fail a job if multiple feeds are detected.
In the past we needed this functionality to make sure that projects that wanted to consume our experimental NuGet packages could get them from our ADO feed, since they weren't available on NuGet.org. Now however our stable release packages are published to NuGet.org and so the ADO feed is only necessary to consume/test our daily/master/canary builds.
Resolves #8529
This PR changes our new …
=> Remove ADO NuGet feed from config for new projects

change/@react-native-windows-cli-2e64e8b9-4efb-4a44-a73d-3964c5bbea3b.json, change/react-native-windows-43c5ac53-664f-46ea-9e13-4278d5eff38f.json, packages/@react-native-windows/cli/src/generator-windows/index.ts, vnext/template/shared-app/proj/NuGet.Config
This PR backports #9385 to 0.67.
This PR changes the template for new projects to only include the ADO NuGet feed if the project is created against master/canary builds.
It's technically a security vulnerability to have more than one NuGet feed in a projects NuGet.config file. In fact, Microsoft ADO pipelines auto-inject a task that will fail a job if multiple feeds are detected.
In the past we needed this functionality to make sure that projects that wanted to consume our experimental NuGet packages could get them from our ADO feed, since they weren't available on NuGet.org. Now however our stable release packages are published to NuGet.org and so the ADO feed is only necessary to consume/test our daily/master/canary builds.
Resolves …
=> [0.67] Remove ADO NuGet feed from config for new projects

change/react-native-windows-6aef389f-13f4-4dba-ad02-0e7eb18adf64.json, vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
There was a superfluous conditional check on the deferred animation ID for a given value node. This check was not required as we already assume in many other places that each value node can have either an active animation, a deferred animation, or neither, so we know if we're stopping an animation that the deferred animation tag must match the animation being stopped. 
Removes the conditional check and adds an assert instead.
RNTester > NativeAnimated examples run in Debug without failing the assert.
=> Removes unnecessary conditional from NativeAnimatedNodeManager

packages/playground/windows/playground/MainPage.xaml
Several of the controls in the playground app are disabled on boot.  If you check and uncheck webdebugging, they would be enabled.  But they should be enabled on boot.  This was fallout from the change in default state away from using webdebugging.  The default state of these controls should have been updated at the same time.
=> Playground controls disabled on boot

change/react-native-platform-override-52d0e542-568b-4b4a-b83f-e67962dd6fb6.json, packages/react-native-platform-override/src/GitReactFileRepository.ts
Integrating new stable branch builds of RN produces an error in the form of `trying to write non-commit object <hash> to branch <branch>`.  This is due to a switch from "lightweight" git tags, to "annotated" git tags, which do not allow the previous syntax we were using for shallow fetching into a new branch. 
Update the syntax to create the branch from FETCH_HEAD, instead of the tag refspec.
Locally tested integrating 0.67.1. End to end tests exist that will exercise this logic for older versions.
=> Fix integration by tag of newer RN Builds

change/react-native-windows-1ead6568-96c1-4cee-88a8-c9c273cbe5d9.json, vnext/.eslintignore, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/SyntaxError.js, vnext/Microsoft.ReactNative/ReactCoreInjection.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Mso/future/futureWinRT.h, vnext/Shared/OInstance.cpp
Better reporting of failures to load the bundle file (#8018)
Some native modules are hitting the UI queue unnecessarily (#9124)
ReloadInstance async task and InstanceLoaded event were not correctly reporting failures (#9224)
Hook up DetachViewInstance method for custom UI implementations (#9226)
InstanceCreated should fire before any JS code is run (#9228)
Remove legacy logic to find win32 bundle (#9225)
=> [0.66] Backport some important fixes to 0.66

change/react-native-windows-8dceffc6-04bc-4bc3-9d5c-9835ae7f8a9c.json, vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.cpp, vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h, vnext/Microsoft.ReactNative/JsiApi.cpp, vnext/Microsoft.ReactNative/JsiApi.h, vnext/Microsoft.ReactNative/ReactHost/ReactContext.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Shared/ChakraRuntimeHolder.cpp, vnext/Shared/ChakraRuntimeHolder.h, vnext/Shared/DevSettings.h, vnext/Shared/HermesRuntimeHolder.cpp, vnext/Shared/HermesRuntimeHolder.h, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h, vnext/Shared/JSI/RuntimeHolder.h, vnext/Shared/OInstance.cpp, vnext/Shared/V8JSIRuntimeHolder.cpp, vnext/Shared/V8JSIRuntimeHolder.h
Hermes inspector is not starting when Hermes engine is used.
The check to start the hermes inspector assumed the jsiEngineOverride field to be set in the devSetting.
But, the field won't be set when using the override jsi runtime provided by the host.
Fixing the direct debugging when Hermes engine is used.
Resolves [#9407](https://github.com/microsoft/react-native-windows/issues/)
The fix requires us to dynamically inspect the jsi runtime instance to find the engine type. This change adds
a field into the runtime holder implementation to explicitly provide the runtime type.
One alternative solution is to use RTTI which is not enabled in RNW builds.
Another alternative is to use the jsi::Runtime::description() value. We can't easily use …
=> Hermes inspector is not starting when Hermes engine is used

change/@office-iss-react-native-win32-4fc6c3b1-a2ce-4bc8-83a4-935d9f9acf6f.json, packages/react-native-win32/src/Libraries/Components/View/View.win32.js
#9350 made usages of `acceptsKeyboardFocus` an error instead of a warning.  -- This restores it back to a warning.
=> [0.64] Do not throw error on deprecated `acceptsKeyboardFocus` property usage 

change/react-native-windows-8a1ddf14-de89-4434-9dc7-81bb20402521.json, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Force clear the uimodule pointer in the UIDispatcher thread to ensure the UIManager Module is destroyed on the UI thread.
Resolves #8317
=> UI Manager module is not being destroyed on the UI thread

change/@react-native-windows-cli-ea061697-b24d-4b3f-adc6-252bb52bd67a.json, packages/@react-native-windows/cli/src/config/dependencyConfig.ts
C# projects using `OutputType` `Library` are no longer able to be autolinked with 0.66. This allows them to be discovered and linked once again.
Resolves [https://github.com/microsoft/react-native-windows/issues/9420]
Added `library` as type of module that can be autolinked.
=> Allow OutputType `Library` to be autolinked for C# native modules

change/react-native-windows-98e7ec7d-e4f1-4295-a50e-58d8bab9a679.json, packages/sample-apps/windows/SampleAppCS/packages.lock.json, packages/sample-apps/windows/SampleLibraryCS/packages.lock.json, vnext/Directory.Build.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Common.targets
Restore ability to switch platforms within Visual Studio.
Fix dependency restoration from within Visual Studio.
- Bug fix
Follow up on #8195.
There are developer experience regressions introduced by usage of `PackageReference` C++ dependencies when building exclusively with the Visual Studio IDE.
Resolves #9424
Resolves #9436
- Implicitly restore VCXPROJ when using Visual Studio
- Don't use RestoreUseStaticGraphEvaluation when dealing with `packages.config`
Using a clean clone and a completely empty user NuGet cache (`globalPackagesFolder`):
- Run `yarn; yarn build`.
- Open solution `packages\sample-apps\windows\SampleApps.sln`.
- Wait for solution to load.
- Switch the platform to `x86`.
- Build solution.
Using a clean clone and a completely empty user NuGet cache …
=> Fix VS hang when switching Platform within IDE

change/react-native-windows-98c19395-026b-4bf1-9a08-1dc416a5a6b2.json, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
=> [0.67] UI Manager module is not being destroyed on the UI thread

change/react-native-windows-2c7c5197-58c8-4868-b554-c2801540c955.json, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
=> [0.66] UI Manager module is not being destroyed on the UI thread

change/react-native-windows-b50197bd-a2bb-423e-a088-a65afa8f7969.json, vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp
There was a minor bug in the CalculationAnimationDriver that accounted for the value node offset when getting the start value for the animation. Animation drivers should always start from the raw value.
The fixes to change from animating the offset property to the value property (#9302) missed a minor bug in CalculatedAnimationDriver, where we start the animation from the `Value` of the animated value node rather than the `RawValue`. This generally won't cause any bugs for animations that do not use the `Offset` property (via `setOffset`), as in those cases `Value` == `RawValue`.
Re-ran RNTester NativeAnimated scenarios and they work as before (no change). Also verified that the native animation behavior …
=> Use raw value for CalculatedAnimationDriver

change/react-native-windows-0642e501-eb2a-4df5-91d4-ba64dd5b0aaa.json, vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
Looks like a minor bug where only the raw value animation was stopped when a node was detached from the interpolation animated node. Not sure if interpolation animated nodes are ever actually re-used, so probably doesn't manifest in any real bugs, but it's probably good to stop the correct animations anyway.
Re-ran RNTester > Native Animated examples - interpolation examples still behave correctly.
=> Stop both raw value and offset animation

packages/playground/README.md
**_Why_**
Playground Readme currently does not include mention of Playground-win32 leaving knowledge of RNW with XAML Islands sample to only be known through word of mouth. 
**_What_**
Update Readme in `./packages/playground` directory to include description of Playground-win32 and steps to build/edit the application.
Fixes #8649
=> Update Playground Readme to Include Playground-win32

change/react-native-windows-50d42888-74d9-4ac0-ad8f-60e874390f4b.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def
Add additional exports for react-native-win32.dll required for Office.
=> [0.66] [NetUI] Add additional exports for react-native-win32.dll

.github/ISSUE_TEMPLATE/bug-report.yaml
Adding VS 2022 as an option for Visual Studio Version.
=> Update Issue Template to include option for VS2022

change/react-native-windows-8dceffc6-04bc-4bc3-9d5c-9835ae7f8a9c.json, change/react-native-windows-ff1c1368-6245-4003-8937-fb5ab3a17c76.json, vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.cpp, vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h, vnext/Microsoft.ReactNative/JsiApi.cpp, vnext/Microsoft.ReactNative/JsiApi.h, vnext/Microsoft.ReactNative/ReactHost/ReactContext.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Shared/ChakraRuntimeHolder.cpp, vnext/Shared/ChakraRuntimeHolder.h, vnext/Shared/DevSettings.h, vnext/Shared/HermesRuntimeHolder.cpp, vnext/Shared/HermesRuntimeHolder.h, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h, vnext/Shared/JSI/RuntimeHolder.h, vnext/Shared/OInstance.cpp, vnext/Shared/V8JSIRuntimeHolder.cpp, vnext/Shared/V8JSIRuntimeHolder.h
* Fixing hermes inspector [#9407](https://github.com/microsoft/react-native-windows/issues/)
The check to start the hermes inspector assumed that the jsiEngineOverride field to be set in the devSetting.
But, the field won't be set when using the override jsi runtime provided by the host.
The fix requires us to dynamically inspect the jsi runtime instance to find the engine type. This change adds
a field into the runtime implementation to explicitly provide the runtime type.
One alternative solution is to use RTTI which is not enabled in RNW builds.
Another alternative is to use the jsi::Runtime::description() value. We can't easily use this field as the usage of it is restricted to JS thread.
* Change files
* Incorporating feedbacks
* Fixing desktop build
* Fixing build break in Desktop …
=> [0.66] Hermes inspector is not starting when Hermes engine is used (#9426)

change/react-native-windows-cd6b59e4-a2d9-492a-b011-e534519b7714.json, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
We fire `onMouseEnter/Leave` from `UpdatePointersInViews`, which historically was suppressed on `PointerMove` because we wanted to prevent `onMouseMove` from firing while the pointer was down. Since we no longer have `onMouseMove` behavior in react-native-windows, this change ensures that `onMouseEnter` / `onMouseLeave` (and thus hover states) update regardless of the pointer being up or down.
Resolves #9171
Always call `UpdatePointersInViews` from `OnPointerMoved` even if there is an active pointer.
https://user-images.githubusercontent.com/1106239/142494799-7bcdbe11-e5c0-4efc-a8b9-a51bdff3cc43.mp4
=> Fixes onMouseEnter/Leave to fire when pointer down

change/@react-native-windows-cli-46d66f80-8f36-4e1f-aa9e-fbb83eda5a5b.json, packages/@react-native-windows/cli/src/generator-windows/index.ts
If there is an existing project that react-native-init is going to overwrite, reuse the old projectGUID instead of generating a new one.
Resolves #8621
TLDR - creating a new projectGUID can create issues when upgrading lib projects by creating unnecesary changes in the project and solution file.
Checks if we're overwriting a project file, extracts the projectGUID and uses that in the template
Tested locally if projectGUID gets overwritten or not
=> React-native-windows-init reuses existing projectGUIDs by default

change/@react-native-windows-codegen-fabf9411-e605-4506-8bec-969f10262da4.json, packages/@react-native-windows/codegen/Document.md
This PR fixes some known issues mentioned in [the last PR](https://github.com/microsoft/react-native-windows/pull/9433), which was merged before I addressed all review comments.
Then document fix affects only one file `packages\@react-native-windows\codegen\Document.md`, no code is changed.
=> Fix TurboModule codegen document

.ado/jobs/integration-test.yml
This configuration has been a little bit flakey, seeming to be due to some timing issues. We're trying to move away from web debugging, so it isn't worth too much time for any new development to it. It is still essential we catch regressions to it in the meantime. As a compromise, this change enables it only in rolling builds.
=> Move web debugging integration-test-app to CI only

.ado/publish.yml
0.68 logs appear to show beachball resetting state after publish, on whatever version it uses. This adds back a step to pull latest changes after publish.
=> Attempt to fix versioning off-by-one issue

packages/playground/windows/playground-win32/Playground-win32.vcxproj
Get ABI crashing failures when running playground-win32 due to mismatched hermes version.
=> Version of hermes used in playground-win32 is incorrect

change/react-native-windows-29044745-85ed-49fc-9fb2-1056b5f77d22.json, vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
Newer versions of fabric require `toolbox.backgroundExecutor` to be set.  Previously it was behind a feature flag.
Fixing an error `Cannot find single active touch`, which was being fired becuase the touch end event was including the touch that just ended in the active touch array.
Gets fabric able to run RNTester again
=> Couple of fixes to get fabric running again

change/react-native-windows-a2ac0b37-db86-4647-8a15-ca57d4b9e08a.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Stop exporting data blocks from react-native-win32.dll.  These are unsupported, and do not work in arm64.  This reintroduces a minor change in folly that we have in 0.64.
=> [0.66] [NetUI] Stop exporting data blocks from react-native-win32.dll

.ado/compliance.yml
This PR creates an initial "stub" compliance pipeline for our repo that just builds Universal x64 Release. I need a file to target in order to set up the ADO side while I work through each of the compliance related tasks that need to be added.
Part of #9507
=> Initial Compliance Pipeline Stub

change/react-native-windows-aa5ba522-5922-4c4c-8d70-dfdb18b69cca.json, packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj, packages/e2e-test-app/windows/RNTesterApp/packages.lock.json, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj, packages/sample-apps/windows/SampleAppCS/packages.lock.json, vnext/PropertySheets/JSEngine.props
Bringing in new Hermes version, which includes updated security flags for SDL compliance.
Manual runs with the new Hermes binary pass JSITests.
=> Bump Hermes version to 0.11

change/react-native-windows-ed74409e-c94a-4998-8f2e-7b0ff6441ca8.json, packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj, packages/e2e-test-app/windows/RNTesterApp/packages.lock.json, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/packages.config, packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj, packages/sample-apps/windows/SampleAppCS/packages.lock.json, vnext/PropertySheets/JSEngine.props
Bringing in new Hermes version, which includes updated security flags for SDL compliance.
=> [0.68] Bump Hermes version to 0.11

package.json, yarn.lock
* Updates node-fetch to 2.6.7
* Updates shelljs to 0.8.5
* Updates nanoid to 3.2.0
=> [0.67] CG fixes for node-fetch, shelljs, nanoid

package.json, yarn.lock
* Updates node-fetch to 2.6.7
* Updates shelljs to 0.8.5
* Updates nanoid to 3.2.0
=> [0.66] CG fixes for node-fetch, shelljs, nanoid

.ado/jobs/desktop.yml
Re-enables test `RNTesterIntegrationTests::WebSocket`.
- Tests coverage
Limitations by older Azure-provided VM images made some networking tests hang.
Re-enables the JavaScript-driven test, which passes consistently on development machines.
=> Re-enable WebSocket RNTester integration test

change/@react-native-windows-cli-3aac23ad-e95a-4369-b241-c4fea1afcb7a.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
This PR backports #9522 to 0.67.
This addresses a perf regression in autolinking when there are no dependencies to link.
Resolves #9518
Instead of checking whether the dependencies cache is empty, check whether it was instantiated.
| -: | -: |
| 22488ms | 3561ms |
=> [0.67] fix(cli): fix cache not being used when there are no dependencies

change/@react-native-windows-cli-401a1aee-fc62-4128-b881-42b970e6102e.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
This PR backports #9522 to 0.68.
This addresses a perf regression in autolinking when there are no dependencies to link.
Resolves #9518
Instead of checking whether the dependencies cache is empty, check whether it was instantiated.
| -: | -: |
| 22488ms | 3561ms |
=> [0.68] fix(cli): fix cache not being used when there are no dependencies

change/@react-native-windows-cli-3aac23ad-e95a-4369-b241-c4fea1afcb7a.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
This PR backports #9522 to 0.66.
This addresses a perf regression in autolinking when there are no dependencies to link.
Resolves #9518
Instead of checking whether the dependencies cache is empty, check whether it was instantiated.
| -: | -: |
| 22488ms | 3561ms |
=> [0.66] fix(cli): fix cache not being used when there are no dependencies

change/react-native-windows-cb00141f-f6a2-4c19-955d-ea1325bc8a33.json, vnext/react-native.config.js
We ship compiled JavaScript to end-users running the CLI. We use
"source-map-support" to install a sourcemap-aware exception handler, so that
stack traces shown to end-users (and included in our issues), resolve
correctly to the TS sources. Resolution is only done when an exception occurs,
but there is some initial overhead to installing the exception handler.
We want to do this before our code is hooked, to ensure the handler is
installed, but doing this as part of global initialization adds a cost to
anyone who depends on `react-native-windows`, and parses their
`react-native.config`, regardless of whether they call the functions. We
delay installing the support from require-time, to function invocation time,
which should catch most cases without the penalty to other platforms.
This …
=> Lazy Install `sourcemap-support` when `react-native-windows` config is hooked

.ado/templates/e2e-test-job.yml
This PR fixes the hangs/timeout for the E2E test run in  e2e-test-job.yml.
The version of wdio used in 0.64 requires Node 12. See
https://github.com/webdriverio/webdriverio/issues/6113
=> [0.64] Fix E2ETest app hanging during PR/CI

package.json, yarn.lock
* Updates node-fetch to 2.6.7
* Updates shelljs to 0.8.5
* Updates axios to 0.21.4
* Updates lodash to 4.17.21
* Updates y18n to 4.0.3
* Updates follow-redirects to 1.14.8
* Updated validator to 13.7.0
=> [0.64] CG fixes for node-fetch, shelljs, and more

change/react-native-windows-5e2cc7a5-b37d-49cc-b01b-c3669a0686c3.json, vnext/Mso/dispatchQueue/dispatchQueue.h
Fixes #9559 
VS 17.1 introduces stricter requirements on `static_assert`, which are causing a build break in the M.RN project. This fixes the previously invalid C++ code.
=> MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early

change/react-native-windows-25e9c3ca-7257-4815-931b-f339b9e70b3c.json, vnext/Shared/Modules/PlatformConstantsModule.cpp
The PlatformConstants module crashes when trying to work out the osVersion when running on Windows 8.1.
This prevents Office from using the NativeModule.
Add a Windows > 10 version check before calling ApiInformation::IsApiContractPresent which was introduced in Win10.
=> Crash when getting Platform.osVersion on Windows 8.1

yarn.lock
Somehow I aligned the versions of node-fetch in #9543 without bumping the actual version.
=> [0.65] CG: Update node-fetch to 2.6.7

change/react-native-windows-2345d670-7aa7-4de1-91e0-692025d93223.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
`flexWrap: "wrap-reverse"` style property makes react-native-windows apps crash.
Resolves [#9569: Using flexWrap: "wrap-reverse" on a View component makes the app crash](https://github.com/microsoft/react-native-windows/issues/9569)
Add `wrap-reverse` value to `NativeUIManager`.
After adding this value, I verified that the `wrap-reverse` behavior worked properly.
=> Add wrap-reverse to flex wrap options

change/react-native-windows-d48d7a10-2970-40aa-9ee8-b874def5fff2.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h, vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs, vnext/Microsoft.ReactNative/IReactContext.cpp, vnext/Microsoft.ReactNative/IReactContext.h, vnext/Microsoft.ReactNative/IReactContext.idl, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactContext.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Shared/OInstance.cpp
Give applications the ability to control the InlineSourceMap property value.
We are currently hardcoding this to false for Hermes, because back in 2020 Hermes was choking with any inline source map larger than a few kilobytes. Things appear to work much better now, so the property will default to true, and -with this change- can be overridden by individual apps if needed.
Addresses the source map concern in #9407.
=> [0.68] Expose InlineSourceMap property

change/react-native-windows-d48d7a10-2970-40aa-9ee8-b874def5fff2.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h, vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs, vnext/Microsoft.ReactNative/IReactContext.cpp, vnext/Microsoft.ReactNative/IReactContext.h, vnext/Microsoft.ReactNative/IReactContext.idl, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactContext.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Shared/OInstance.cpp
Give applications the ability to control the InlineSourceMap property value.
We are currently hardcoding this to false for Hermes, because back in 2020 Hermes was choking with any inline source map larger than a few kilobytes. Things appear to work much better now, so the property will default to true, and -with this change- can be overridden by individual apps if needed.
Addresses the source map concern in #9407.
=> [0.67] Expose InlineSourceMap property

change/@react-native-windows-codegen-c2c652de-c0b5-4c7e-9655-56a42b7088a1.json, packages/@react-native-windows/codegen/src/Cli.ts, packages/@react-native-windows/codegen/src/generators/GenerateTypeScript.ts
Add TypeScript turbo module definition as new codegen target.
It is not triggered in `yarn build` in this repo.
The final goal is to bring type safety to `ISS/Rex.ts`. and `ISS/Rex.cpp` This would done in multiple changing to both repos.
New features are added to `@react-native-windows/codegen`:
- `--ts`: Print TypeScript turbo module definition from flow, default to `false` for backward compabitility
- `--outdir`: Change the output directory, default to `codegen` for backward compatibility
Facebook's turbo module codegen front-end doesn't support `Int64`, which could create problems as we need it. As JavaScript cannot actually store an `Int64`, maybe the native module should be changed to use string instead.
Import statements …
=> Add TypeScript turbo module definition as new codegen target

change/react-native-windows-c97075bb-08ca-40dd-a2f9-21d8605d9b7e.json, vnext/Shared/Modules/PlatformConstantsModule.cpp
=> [0.68] Crash when getting Platform.osVersion on Windows 8.1

change/react-native-windows-daade875-fb12-466a-977d-34ee3c6b8f76.json, vnext/Shared/Modules/PlatformConstantsModule.cpp
=> [0.66] Crash when getting Platform.osVersion on Windows 8.1

change/react-native-windows-f76676c9-d827-4411-9408-671efc9dbeac.json, vnext/Shared/Modules/PlatformConstantsModule.cpp
=> [0.67] Crash when getting Platform.osVersion on Windows 8.1

change/react-native-windows-0b30a99b-f579-48be-9dd3-fcbae6d5bd54.json, vnext/Microsoft.ReactNative/Fabric/ComponentViewRegistry.cpp, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp, vnext/Microsoft.ReactNative/XamlUIService.cpp, vnext/Microsoft.ReactNative/XamlView.h
We are making some incorrect assumptions about where UI elements come from (we expect RNW to be responsible for all of the XAML UI in a scene). Therefore we expect that the `Tag` will be set, and not only that, that it will be an int, and that it will represent a react tag.
This works fine for a pure RNW app. When hosting non-RNW content, e.g. when adding AdaptiveCards, this assumption breaks down, as AC will set its own WinRT object as the XAML element's Tag.
Resolves #9560 
Centralize getting/setting the tag to one single place. 
In the future we can change this logic to make the assumption less flimsy. For example, we still assume that if it is an int, it will be a react tag. We could do the same as what …
=> Fix tag handling for foreign UI elements

change/react-native-windows-d91b29f6-0fd4-4087-bc9e-ad1385fd4673.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/JsiWriter.cpp, vnext/Microsoft.ReactNative/JsiWriter.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Cherry pick PR #9595
In NativeModules 2.0 we can complete Promises in async methods from any thread.
They use `DynamicWriter` to serialize result value to `folly::dynamic` which then is serialized to a JSI value in JS dispatcher.
But the C++ TurboModules which are based on the NativeModules 2.0 cannot complete Promises from any thread because they use the `JsiWriter` that must be always invoked from the JS dispatcher.
In this PR we fix this issue to keep the TurboModules behavior consistent with the NativeModules 2.0 and to allow Promises to be completed from any thread.
To address this issue, the new `JSDispatcherWriter` is added internally to the `Microsoft.ReactNative` project.
This class wraps both `JsiWriter` and the …
=> [0.68] Enable TurboModule Promise completion from any thread (#9595)

change/react-native-windows-259159fd-d65e-4319-82fe-7b4b570b6104.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/JsiWriter.cpp, vnext/Microsoft.ReactNative/JsiWriter.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Cherry pick PR #9595
In NativeModules 2.0 we can complete Promises in async methods from any thread.
They use `DynamicWriter` to serialize result value to `folly::dynamic` which then is serialized to a JSI value in JS dispatcher.
But the C++ TurboModules which are based on the NativeModules 2.0 cannot complete Promises from any thread because they use the `JsiWriter` that must be always invoked from the JS dispatcher.
In this PR we fix this issue to keep the TurboModules behavior consistent with the NativeModules 2.0 and to allow Promises to be completed from any thread.
To address this issue, the new `JSDispatcherWriter` is added internally to the `Microsoft.ReactNative` project.
This class wraps both `JsiWriter` and the …
=> [0.67] Enable TurboModule Promise completion from any thread (#9595)

change/react-native-windows-b38f3f2f-4014-40fd-8c40-6134c3630c30.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/JsiWriter.cpp, vnext/Microsoft.ReactNative/JsiWriter.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Cherry pick PR #9595
In NativeModules 2.0 we can complete Promises in async methods from any thread.
They use `DynamicWriter` to serialize result value to `folly::dynamic` which then is serialized to a JSI value in JS dispatcher.
But the C++ TurboModules which are based on the NativeModules 2.0 cannot complete Promises from any thread because they use the `JsiWriter` that must be always invoked from the JS dispatcher.
In this PR we fix this issue to keep the TurboModules behavior consistent with the NativeModules 2.0 and to allow Promises to be completed from any thread.
To address this issue, the new `JSDispatcherWriter` is added internally to the `Microsoft.ReactNative` project.
This class wraps both `JsiWriter` and the …
=> [0.66] Enable TurboModule Promise completion from any thread (#9595)

change/react-native-windows-fe9965b7-8e26-4928-b2d8-7453a5738923.json, vnext/PropertySheets/External/Microsoft.ReactNative.Common.props, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
Set MSBuild property `ResolveNuGetPackages` to `false` for projects consuming MSRN.
External projects will fail to build due to `PackageReference` on C++ not being compatible with property `ResolveNuGetPackages`.
Resolves #9512
Sets MSBuild property `ResolveNuGetPackages` to `false`. See `vnext\PropertySheets\External\Microsoft.ReactNative.Common.props`.
=> Set ResolveNuGetPackages in external props

change/react-native-windows-ce41eed2-2de5-43a0-9d29-b100a2d39d30.json, vnext/Scripts/rnw-dependencies.ps1
The rnw-dependencies script doesn't currently handle multiple side-by-side VS installs, nor does it check prerelease as a fallback.
Resolves #9260
=> Dependencies script checks for multiple VS installs

change/@react-native-windows-cli-5c176e39-baa5-4bfb-818a-da9b3c8d1720.json, packages/@react-native-windows/cli/src/runWindows/runWindows.ts
This PR creates some new RunWindows phases and updates when/how they're
set.
The phases did not include `Build` which seems like a big hole, or the new `RestorePackagesConfig` step that was added. It also always changed the phase to `FindSolution` when no solution was found.
=> Update how RunWindows phases are reported

.gitignore, change/@react-native-windows-cli-bfddb2a2-3f9f-4251-932f-84c3a4dd88d2.json, change/react-native-windows-ce55d8f0-2ae7-4fde-b722-58bec7970aa3.json, packages/@react-native-windows/cli/powershell/Eval-MsBuildProperties.ps1, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts, packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets, vnext/PropertySheets/OutputMSBuildProperties.targets
This PR adds certain values of important MSBuild properties to the telemetry of `run-windows`.
Resolves #9165
There are some key MSBuild properties that would make it easier for us to debug and troubleshoot build problems if we knew their values.
Resolves #9165
A new OutputMSBuildProperties.targets file to run before Build, which outputs the properties we want to capture to a JSON file, to be consumed by run-windows and reported.
If the file can't be found, a new Eval-MsBuildProperties.ps1 script is added which loads the Microsoft.Build.dll and uses it to correctly process the build tree and get the correct value of specified properties. It's slow but should work even if the build fails.
There is a new wrapper method in …
=> Capture MSBuild properties in telemetry

change/@react-native-windows-cli-5c176e39-baa5-4bfb-818a-da9b3c8d1720.json, packages/@react-native-windows/cli/src/runWindows/runWindows.ts
This PR backports #9630 to 0.68.
This PR creates some new RunWindows phases and updates when/how they're set.
The phases did not include Build which seems like a big hole, or the new RestorePackagesConfig step that was added. It also always changed the phase to FindSolution when no solution was found.
=> [0.68] Update how RunWindows phases are reported

.gitignore, change/@react-native-windows-cli-bfddb2a2-3f9f-4251-932f-84c3a4dd88d2.json, change/react-native-windows-ce55d8f0-2ae7-4fde-b722-58bec7970aa3.json, packages/@react-native-windows/cli/powershell/Eval-MsBuildProperties.ps1, packages/@react-native-windows/cli/src/runWindows/runWindows.ts, packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts, packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets, vnext/PropertySheets/OutputMSBuildProperties.targets
This PR backports #9470 to 0.68.
This PR adds certain values of important MSBuild properties to the telemetry of `run-windows`.
There are some key MSBuild properties that would make it easier for us to debug and troubleshoot build problems if we knew their values.
Resolves #9165
A new OutputMSBuildProperties.targets file to run before Build, which outputs the properties we want to capture to a JSON file, to be consumed by run-windows and reported. We set up a callback to load this file at the end of the command.
Also, this PR contains Eval-MsBuildProperties.ps1 script which loads the Microsoft.Build.dll and uses it to correctly process the build tree and get the correct value of specified properties. It's slow but should work …
=> [0.68] Capture MSBuild properties in telemetry

change/react-native-windows-202e71fb-d2d3-431c-a1bd-53c82a6e6037.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/ReactApplication.cpp, vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp, vnext/Microsoft.ReactNative/ReactHost/CrashManager.h, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Shared/DevSettings.h, vnext/Shared/HermesRuntimeHolder.cpp, vnext/Shared/HermesRuntimeHolder.h, vnext/Shared/HermesShim.cpp, vnext/Shared/HermesShim.h, vnext/Shared/JSI/RuntimeHolder.h
Note: this is being resubmitted since the [original PR](https://github.com/microsoft/react-native-windows/pull/9150) was lost due to accidental fork cleanup.
We want to make runtime crashes more actionable by recording additional data with Windows Error Reporting which can be requested along crash reports and dumps for analysis.
* Add a CrashManager that calls into crashHandler functions exposed by the ReactInstances. Implement crashHandler for ReactInstance that forwards to JSIRuntimeHolder; the Hermes JSIRuntimeHolder calls into the Hermes VM crashHandler to record some additional details at the time of the crash (such as callstack and addresses of heaps)
* Replaced the Hermes runtime with one that registers additional details …
=> Implement crash management

change/react-native-windows-687e3d6c-ef99-43b7-b957-b429aa764e9c.json, vnext/Shared/OInstance.cpp
When creating new React instances using Hermes with the direct debugging option turned on, the inspector from the previous engine would not get shut down, leading to an accumulation of debug targets in debug clients (see Screenshots for an example).
Change condition in InstanceImpl dtor to match the condition in InstanceImpl ctor.
Accumulation of debug targets in Chrome Inspect window 
Manually tested the change using RNW Playground app and Chrome Inspect page.
=> stop inspector when destructing instance

Directory.Build.props, Directory.Build.targets, change/react-native-windows-60d16274-555b-4c37-aaa3-738a6f44be49.json, vnext/Directory.Build.props, vnext/Directory.Build.targets
Scope down `PackageReference` usage to project that will actually need it.
Usage of `PackageReference` added some overhead to builds under Visual Studio due to its lack of official support.
Closes #9475.
Mitigates #9619.
- Sets `PackageReference`-specific items (`ProjectCapability Include="PackageReferences"`) only when the C++ project actually declares package references.
- Runs de ad-hoc call to the `Restore` target only when `PackageReference` is present.
=> Scope down usage of PackageReference

change/react-native-windows-202e71fb-d2d3-431c-a1bd-53c82a6e6037.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/ReactApplication.cpp, vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp, vnext/Microsoft.ReactNative/ReactHost/CrashManager.h, vnext/Microsoft.ReactNative/ReactHost/React.h, vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp, vnext/Microsoft.ReactNative/ReactInstanceSettings.h, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Shared/DevSettings.h, vnext/Shared/HermesRuntimeHolder.cpp, vnext/Shared/HermesRuntimeHolder.h, vnext/Shared/HermesShim.cpp, vnext/Shared/HermesShim.h, vnext/Shared/JSI/RuntimeHolder.h
We want to make runtime crashes more actionable by recording additional data with Windows Error Reporting which can be requested along crash reports and dumps for analysis.
* Add a CrashManager that calls into crashHandler functions exposed by the ReactInstances. Implement crashHandler for ReactInstance that forwards to JSIRuntimeHolder; the Hermes JSIRuntimeHolder calls into the Hermes VM crashHandler to record some additional details at the time of the crash (such as callstack and addresses of heaps)
* Replaced the Hermes runtime with one that registers additional details (memory blocks, metadata) with Windows Error Reporting to have them available in case of a crash
* Add a EnableDefaultCrashHandler property on the instance …
=> [0.68] Implement crash management

.ado/templates/yarn-install.yml, package.json
This triggers an incremental build when running `yarn` or `yarn install` from the repo root, to eliminate the need for an extra command. We have some optimizations in our pipelines to not do full builds, so we opt out of this behavior there and keep existing build logic.
=> Automatically build on `yarn install`

change/@office-iss-react-native-win32-456d474d-1335-4afa-b705-2469b8b42cd5.json, change/@react-native-windows-codegen-2bef1ea6-91e9-49fa-a257-8ecd899309a9.json, change/react-native-windows-b4b1577a-81c5-4a47-88ae-181bc9bf38e2.json, packages/@office-iss/react-native-win32/package.json, packages/@react-native-windows/codegen/src/Cli.ts, packages/@react-native-windows/codegen/src/generators/GenerateTypeScript.ts, packages/e2e-test-app/package.json, packages/integration-test-app/package.json, packages/playground/package.json, packages/sample-apps/package.json, vnext/package.json, yarn.lock
`TurboModule` and `TurboModuleRegistry` has been added to `@types/react-native` 0.66.17, fix codegen accordingly.
1. Generate TypeScript code that imports `TurboModule` and `TurboModuleRegistry` directly from react-native.
2. If the input flow spec uses `TurboModuleRegistry.get<Spec>` instead of `getEnforcing`, the generated code does that too.
1. This is a temporary implementation until such information is added to the schema in facebook/react-native
Here are test cases that **are not included in this PR**
1. [Rex.js](https://github.com/ZihanChen-MSFT/react-native-windows/blob/tm-rex-sample/vnext/src/Libraries/Utilities/Rex.js) -> [RexSpec.g.ts](https://github.com/ZihanChen-MSFT/react-native-windows/blob/tm-rex-sample/vnext/codegen-rex/RexSpec.g.ts)
2. …
=> Fix turbo module codegen to generate correct import statement and registration

change/react-native-windows-5c80c286-c4d1-403d-bbf4-848681cecf12.json, vnext/PropertySheets/CppAppConsumeCSharpModule.props
This PR adds the latest versions of .NET Native packages and UWP Core Runtime SDK installed with VS 2022.
This is necessary to build the SampleApp in VS 2022.
=> Update CppAppConsumeCSharpModules.props for VS2022

packages/sample-apps/windows/SampleAppCPP/App.xaml, packages/sample-apps/windows/SampleAppCS/App.xaml
Starting in RNW 0.66 (#8245) we changed from using a WUX::ProgressRing to a MUX::ProgressRing that we load into the UI when a bundle is being loaded from metro. This requires that the MUX resources are loaded in the App.xaml. This change was made for Playground, and always been present in the template for new apps, but was never made for the sample apps under `packages/sample-apps`.
Closes #9671
=> Fix Sample Apps crash when loading the bundle

change/react-native-windows-1de81d27-2dc7-4a31-914e-572cdf8c1945.json, vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp, vnext/Microsoft.ReactNative/Views/ViewPanel.cpp, vnext/Microsoft.ReactNative/Views/ViewPanel.h
This switches the existing ViewPanel custom DependencyProperties for Top/Left with Canvas's own.
This is part 1 of 3 of getting us off of a custom panel. There should be a small (negligible?) perf improvement from this.
Resolves #9632 
Ran RNTester, no changes observed, as expected.
=> Use Canvas.Top and Left instead of custom DependencyProperties

packages/sample-apps/windows/SampleAppCPP/App.xaml, packages/sample-apps/windows/SampleAppCS/App.xaml
This PR backports #9676 to 0.68.
Starting in RNW 0.66 (#8245) we changed from using a WUX::ProgressRing to a MUX::ProgressRing that we load into the UI when a bundle is being loaded from metro. This requries that the MUX resources are loaded in the App.xaml. This change was made for Playground, and always been present in the template for new apps, but was never made for the sample apps under `packages/sample-apps`.
Closes #9671
=> [0.68] Fix Sample Apps crash when loading the bundle

packages/sample-apps/windows/SampleAppCPP/App.xaml, packages/sample-apps/windows/SampleAppCS/App.xaml
This PR backports #9676 to 0.67.
Starting in RNW 0.66 (#8245) we changed from using a WUX::ProgressRing to a MUX::ProgressRing that we load into the UI when a bundle is being loaded from metro. This requries that the MUX resources are loaded in the App.xaml. This change was made for Playground, and always been present in the template for new apps, but was never made for the sample apps under `packages/sample-apps`.
Closes #9671
=> [0.67] Fix Sample Apps crash when loading the bundle

packages/sample-apps/windows/SampleAppCPP/App.xaml, packages/sample-apps/windows/SampleAppCS/App.xaml
This PR backports #9676 to 0.66.
Starting in RNW 0.66 (#8245) we changed from using a WUX::ProgressRing to a MUX::ProgressRing that we load into the UI when a bundle is being loaded from metro. This requries that the MUX resources are loaded in the App.xaml. This change was made for Playground, and always been present in the template for new apps, but was never made for the sample apps under `packages/sample-apps`.
Closes #9671
=> [0.66] Fix Sample Apps crash when loading the bundle

CONTRIBUTING.md
Adding a quick overview of how backporting works to CONTRIBUTING.md, so we can tag issues such as https://github.com/microsoft/react-native-windows/issues/9155 with `help wanted` or `good first issue` and have some guidance to reference on how to get that done.
=> Adding to Contributing docs

.vscode/extensions.json
We run prettier through ESLint. Remove the reccomendation to install the prettier plugin for gthe repo
=> Remove prettier extension reccomendation

change/react-native-windows-317164cb-1054-481e-9319-53a5d609ce51.json, vnext/Shared/HermesShim.cpp
If ReactNative / HermesRuntime is being initialized simultaneously from multiple threads, we can end up in EnsureHermesLoaded concurrently and use uninitialized function pointers.
Resolves (internal 37798610)
Use std::call_once to ensure we can't call into the method concurrently from separate threads.
=> Safe re-entrancy for EnsureHermesLoaded

change/react-native-windows-084dc412-a417-4d9e-833a-113946a147ae.json, vnext/Shared/HermesShim.cpp
If ReactNative / HermesRuntime is being initialized simultaneously from multiple threads, we can end up in EnsureHermesLoaded concurrently and use uninitialized function pointers.
Resolves (internal 37798610)
Use std::call_once to ensure we can't call into the method concurrently from separate threads.
=> [0.68] Safe re-entrancy for EnsureHermesLoaded

change/react-native-windows-d29a2bab-2467-4365-80e2-a3265a695786.json, vnext/Shared/HermesShim.cpp
If ReactNative / HermesRuntime is being initialized simultaneously from multiple threads, we can end up in EnsureHermesLoaded concurrently and use uninitialized function pointers.
Resolves (internal 37798610)
Use std::call_once to ensure we can't call into the method concurrently from separate threads.
=> [0.67] Safe re-entrancy for EnsureHermesLoaded

change/react-native-windows-ab3ebecb-a61b-4e1f-abd4-379c7d6a81c8.json, vnext/Shared/HermesShim.cpp
If ReactNative / HermesRuntime is being initialized simultaneously from multiple threads, we can end up in EnsureHermesLoaded concurrently and use uninitialized function pointers.
Resolves (internal 37798610)
Use std::call_once to ensure we can't call into the method concurrently from separate threads.
=> [0.66] Safe re-entrancy for EnsureHermesLoaded

change/react-native-windows-2bf487b3-ad01-47f4-a8ca-d446525207d1.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Now that PackageReference is being used WebView2 package version specification and reference is needed. This is implicitly done by importing the WinUI package via PackageReference. 
Remove lingering import of WebView2.props.
Note: Apps using community modules, or apps created prior to v0.68 may still need the WebView2 package specified in their packages.config file.
Resolves #9618
Remove explicit references/import of WebView2 package.
=> Update WebView2 Package Import Following PkgRef Support

change/react-native-windows-2bf487b3-ad01-47f4-a8ca-d446525207d1.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
* Update WebView Pkg Dep Following Pkg Ref
* Change files
Now that PackageReference is being used WebView2 package version specification and reference is needed. This is implicitly done by importing the WinUI package via PackageReference.
Remove lingering import of WebView2.props.
Note: Apps using community modules, or apps created prior to v0.68 may still need the WebView2 package specified in their packages.config file.
Resolves https://github.com/microsoft/react-native-windows/issues/9618
Remove explicit references/import of WebView2 package.
Backport #9706 to 0.68.
=> [0.68] Update WebView2 Package Import Following PkgRef Support

change/react-native-windows-9233768b-4345-43af-8035-08c54dbaa6af.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
@dmachaj  spotted this today and this seemed like low hanging fruit to go after (thanks David!!)
Moves some libraries like UIAutomationCore, the WER APIset and some file stuff out to delayload (only used by asyncstorage).
With this I saw a reduction of 1.3 MB in private working set in the example app in react-native-xaml
Slightly improves memory usage for RNW Apps
=> Move some libraries to delayload

change/react-native-windows-fc114619-d2a7-443e-bd71-404237757294.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
=> [0.68] Port Delayload fixes

change/react-native-windows-bdc169c1-d4e0-4cd0-a9f0-a05e51c840ca.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
=> [0.67] Port Delayload fixes

change/react-native-windows-75461af6-8aa8-4ca9-8277-9e541ff6ffc3.json, vnext/PropertySheets/PackageVersionDefinitions.props
The version macros don't work in IDL files; this is because the preprocessor macros for MIDL and for the C++ compiler are defined separately.
Needed for doing version checks in modules like react-native-webview (when adding support for WebView2)
=> Enable version checks in IDL files

change/react-native-windows-c61cf00d-7e3b-4feb-86c3-41f2502f5435.json, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
This guards against cancelations and "bad image" errors that can occur when trying to set an image's source
https://task.ms/38489209
=> Guard against crashes due to cancelations and other errors from BitmapSource/SvgImageSource SetSourceAsync

change/react-native-windows-d82b05f8-153c-45d6-9c66-71225d0144c9.json, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
=> [0.68] Guard against crashes due to cancelations and other errors from BitmapSource/SvgImageSource SetSourceAsync

change/react-native-windows-1283c81d-6092-427c-a19e-de1521c037e7.json, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
=> [0.67] Guard against crashes due to cancelations and other errors from BitmapSource/SvgImageSource SetSourceAsync

change/react-native-windows-c85f8920-99c5-46dc-94a4-32e2144cb016.json, vnext/Shared/DevSupportManager.cpp
DevSupportManager crashes in unpackaged apps trying to start the Hermes inspector, because it tries to get the package identity.
=> DevSupportManager crashes in unpackaged apps

change/react-native-windows-8a5e8b21-c7ab-4640-badb-cd9cabcd2ad7.json, change/react-native-windows-8c4bdb9b-4524-4bef-8b96-75ec3f73f6f9.json, vnext/Mso/dispatchQueue/dispatchQueue.h
=> [0.66] MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early

change/react-native-windows-dd2c94b5-db93-43d7-8c63-9f6932774c39.json, vnext/Mso/dispatchQueue/dispatchQueue.h
=> [0.67] MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early

docs/e2e-testing.md
Add link to API documentation for WebDriverIO and specifies that "yarn start" is needed to run any e2e-test loc
While working through theses docs, I pulled up the wrong WebDriverIO documentation and it took a while to find the right one.
=> Add link to e2e-testing doc and small fix

packages/@react-native-windows/tester/src/js/examples-win/Mouse/MouseClickExample.windows.js, packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js, packages/e2e-test-app/test/MouseClickTest.test.ts
Adds page to RN-testers to test basic mouse-click functionality on intended components. Tests that Primary, Auxiliary, and Secondary clicks work on a View but **only** primary clicks work on a button.
Currently we have no tests for Auxiliary or Secondary clicks.
Added page to RN-tester so as click-events for windows grow and develop, so can the test page. 
https://user-images.githubusercontent.com/42554868/159086657-0472a6fe-e9b5-4af3-85ac-63cbaddcea07.mp4
Tested locally
=> Adds mouse-click events e2e tests

packages/@rnw-scripts/create-github-releases/package.json, packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts, packages/@rnw-scripts/promote-release/package.json, packages/@rnw-scripts/promote-release/src/promoteRelease.ts, packages/react-native-platform-override/package.json, packages/react-native-platform-override/src/GitReactFileRepository.ts, yarn.lock
This PR backports #9709 to 0.66.
There is a CG alert for older versions of simple-git.
While there is not specific remediation at this time, we're very far
behind and the newest version has a fix, so presumably getting up to
date is in our best interest.
See: https://nvd.nist.gov/vuln/detail/CVE-2022-24433
=> [0.66] Security: Update simple-git dependency to 3.3.0

change/react-native-windows-4221e184-d6c7-49d8-9c92-8ce786a85e4c.json, vnext/Shared/DevSupportManager.cpp
When reading the JS bundle from metro, we read the response as a `uint8_t` buffer, then copy it byte by byte to a std::string.
This gets expensive quickly. The stock hello world app's bundle is about 15.3 MB. On my PC, the string copy takes ~890ms.
Since uint8_t has the same size as char, we can cut some corners and avoid the copy altogether. This takes the copy from the buffer to 15 ms.
tl;dr: This shaves almost a second off of the boot path (in dev mode).
Also replacing some `stringstream` usage with `format` since the latter is slow.
=> Eliminate a whole-bundle string copy

change/react-native-windows-73626f69-9b5c-4bcc-bf4a-2bffdfab80b6.json, vnext/Microsoft.ReactNative/ReactInstanceSettings.idl, vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp, vnext/Shared/OInstance.cpp
Enable loading the JS bundle from an embedded resource via a `resource://moduleName/resourceId` URI.
This is already something that the desktop DLL does albeit through a different codepath so I don't want to touch that for the time being. Once this change goes in, maybe Office can move to this as a standard approach so we don't have to have two copies of essentially the same code.
With the emphasis in non-UWP / WinAppSDK apps moving forward, it will be necessary to be able to load the bundle in other ways that aren't necessarily MRT / MRTCore.
Fixes #9769
=> Enable loading the bundle from an embedded resource via resource://moduleName/resourceId

change/react-native-windows-a8ae532b-cf51-4163-9351-660a49956641.json, vnext/Microsoft.ReactNative.Cxx/XamlUtils.h
This change prevents loading XAML just to check if we are running inside of a XAML app. Today this would be a tax on non-XAML endpoints (NetUI? and win32).
This change shrinks the app's memory usage since loading XAML brings in a whole bunch of DLLs, allocates, etc.
Overall there's about a **6 MB private working set drop** 🥳.
A XAML app requires XAML to have been loaded, so check if XAML has been loaded already before even querying whether the app is a xaml app.
Name | Working set (memory) | Memory (active private working set) | Memory (private working set) | Memory (shared working set)
-- | -- | -- | -- | --
Baseline | 139444 | 111536 | 111536 | 27908
With change | 139000 | 104980 | 104980 | 34020
=> [Win32] Don't load XAML if we are checking if we are a XAML app

change/@react-native-windows-telemetry-b9507482-ef51-4a3c-b217-6a53d40e0bb4.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/telemetry/src/telemetry.ts, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts, yarn.lock
This PR disables the ApplicationInsights (AI) internal logging. We used to enable it during our tests to get more info, but all this logging happens on a background thread which interferes with the tests exiting cleanly and clutters up the test output.
This PR also removes the CorrelationIDManager workaround (to kill its background thread) since issue https://github.com/microsoft/ApplicationInsights-node.js/issues/833 was fixed and it no longer runs indefinitely.
This PR also disables AI's StatsBeat - yet another source of unnecessary background threads which interfere with our tests.
=> Stop Telemetry background threads running after test completion

change/react-native-windows-c6313129-5ecd-4713-a7e6-f1a0996e742e.json, vnext/Scripts/rnw-dependencies.ps1
Fixes #9807 
When hitting some recoverable error conditions (e.g. no retail VS found), we error out because of missing a set of quotes around a string output.
=> Fix error output in rnw-dependencies.ps1

packages/@rnw-scripts/create-github-releases/package.json, packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts, packages/@rnw-scripts/promote-release/package.json, packages/@rnw-scripts/promote-release/src/promoteRelease.ts, packages/react-native-platform-override/package.json, packages/react-native-platform-override/src/GitReactFileRepository.ts, yarn.lock
This PR backports #9709 to 0.65.
There is a CG alert for older versions of simple-git.
While there is not specific remediation at this time, we're very far
behind and the newest version has a fix, so presumably getting up to
date is in our best interest.
See: https://nvd.nist.gov/vuln/detail/CVE-2022-24433
=> [0.65] Security: Update simple-git dependency to 3.3.0

change/@react-native-windows-telemetry-32822618-c317-4ef4-b236-2f800ce4fcee.json, packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts, packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts
This PR temporarily disables some of the telemetry tests as reported by https://github.com/microsoft/react-native-windows/issues/9820.
=> Disable unstable telemetry tests 

change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters, vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp, vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Fix Sequential Mso DispatchQueue deadlock on shutdown
@acoates-ms has reported an issue that we have a deadlock when Mso sequential DispatchQueue based on thread pool is shutting down. The source of the issue is that the scheduler class waits for thread pool work to finish in the destructor, and if the dispatch queue or the scheduler class is being destroyed from the thread pool task itself, then we are getting a deadlock:
- the scheduler class destructor waits for thread pool task to finish;
- the thread pool task waits on the scheduler class to complete destruction.
To fix the issue we are introducing `ThreadPoolSchedulerWinContext` class that tracks current `ThreadPoolSchedulerWin` instance used by current thread. The …
=> Fix Sequential Mso DispatchQueue deadlock on shutdown

change/react-native-windows-e4a169a0-4037-4919-a48d-70460a7a3a0f.json, vnext/Shared/DevSupportManager.cpp, vnext/Shared/DevSupportManager.h, vnext/Shared/HermesRuntimeHolder.cpp, vnext/Shared/HermesRuntimeHolder.h, vnext/Shared/IDevSupportManager.h, vnext/Shared/JSI/RuntimeHolder.h, vnext/Shared/OInstance.cpp
- Bug fix 
Prior to this change, debugger front ends (e.g. Flipper, Chrome Inspect) would loose the connection to the Hermes engine upon reload. Also, several object (DevSettings, HermesRuntimeHolder, HermesRuntimeImpl ...) would get leaked across reloads. 
Resolves
- https://github.com/microsoft/react-native-windows/issues/9181
- https://github.com/microsoft/react-native-windows/issues/9824
- keep InspectorPackagerConnection instance across reloads
- break circular reference between DevSettings and HermesRuntimeHolder
=> Keep debugger connection across Hermes reloads, prevent memory leaks

change/react-native-windows-7261b40e-9c20-4f47-a91d-4552206adf06.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp, vnext/overrides.json, vnext/src/Libraries/StyleSheet/processTransform.windows.js
There is an if(android || ios) statement in core that makes the transform property behave differently in core than in windows.  In order to use the fabric props and conversions for transform, we need windows to behave more like android/ios.
Deforking of bahavior.  Filed #9797 and opened https://github.com/facebook/react-native/pull/33579 to remove this forked file.
=> Modify transform code to allow fabric usage of transform

package.json, packages/@rnw-scripts/format-files/package.json, packages/@rnw-scripts/integrate-rn/package.json, packages/react-native-platform-override/package.json, yarn.lock
This PR (partially) backports #9837 to 0.68.
This PR updates our dependencies on async to `async@^3.2.3` and/or `async@^2.6.4`.
A resolution is used for `**/clang-format/async` to get the new version of async without the new behavior changes by updating clang-format itself.
=> [0.68] CG: Update async to resolve CVE-2021-43138

package.json, packages/@rnw-scripts/format-files/package.json, packages/@rnw-scripts/integrate-rn/package.json, packages/react-native-platform-override/package.json, yarn.lock
This PR (partially) backports #9837 to 0.65.
This PR updates our dependencies on async to `async@^3.2.3` and/or `async@^2.6.4`.
A resolution is used for `**/clang-format/async` to get the new version of async without the new behavior changes by updating clang-format itself.
=> [0.65] CG: Update async to resolve CVE-2021-43138

.ado/jobs/node-tests.yml, change/@react-native-windows-telemetry-97ad5a9e-21cc-4617-8d2a-cee091607fd5.json, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts, packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts
This PR re-enables the telemetry tests disabled by #9823, and setting the concurrency in ADO to 1.
The issue is that running our tests in parallel in ADO (via `lage`) causes too many tests to run at once, so the async tests sometimes get stuck when calling out to external tools.
This adds 1-2min to the node tests job, but it's not a bottleneck.
Closes #9820
=> Re-enable telemetry tests

change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Fix JSI implementation for Node-API and update v8jsi to 0.65.11
Node-API does not specify explicitly calling conventions for functions.
It is typically not an issue when code is compiled with the default calling conventions, but `react-native-win32.dll` is compiled with `__stdcall` calling conventions while the `v8jsi.dll` is with the `__cdecl` calling conventions.
As a result, using the Node-API function is not ABI-safe.
Foreseeing this issue, we explicitly marked all Node-API functions as `__cdecl`, but we forgot to decorate with the `__cdecl` the function pointer types. As a result, we see crashes in x86 environment when we create host functions or host objects.
To fix the issue we updated the Node-API definitions and recompiled the …
=> [0.66] Fix JSI implementation for Node-API and update v8jsi to 0.65.11

change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters, vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp, vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Cherry pick PR #9818
Original PR description:
Fix Sequential Mso DispatchQueue deadlock on shutdown
@acoates-ms has reported an issue that we have a deadlock when Mso sequential DispatchQueue based on thread pool is shutting down. The source of the issue is that the scheduler class waits for thread pool work to finish in the destructor, and if the dispatch queue or the scheduler class is being destroyed from the thread pool task itself, then we are getting a deadlock:
- the scheduler class destructor waits for thread pool task to finish;
- the thread pool task waits on the scheduler class to complete destruction.
To fix the issue we are introducing `ThreadPoolSchedulerWinContext` class that tracks current `ThreadPoolSchedulerWin` …
=> [0.68] Fix Sequential Mso DispatchQueue deadlock on shutdown

change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters, vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp, vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Cherry pick PR #9818
Original PR description:
Fix Sequential Mso DispatchQueue deadlock on shutdown
@acoates-ms has reported an issue that we have a deadlock when Mso sequential DispatchQueue based on thread pool is shutting down. The source of the issue is that the scheduler class waits for thread pool work to finish in the destructor, and if the dispatch queue or the scheduler class is being destroyed from the thread pool task itself, then we are getting a deadlock:
- the scheduler class destructor waits for thread pool task to finish;
- the thread pool task waits on the scheduler class to complete destruction.
To fix the issue we are introducing `ThreadPoolSchedulerWinContext` class that tracks current `ThreadPoolSchedulerWin` …
=> [0.67] Fix Sequential Mso DispatchQueue deadlock on shutdown

yarn.lock
* Update to `moment@2.29.3` for CVE-2022-24785
=> [0.64] CG Fixes for 4/18/2022

yarn.lock
* Update to `moment@2.29.3` for CVE-2022-24785
=> [0.65] CG Fixes for 4/18/2022

yarn.lock
=> [0.68] CG fixes for 4/18/2022

change/react-native-windows-07a91306-5a2e-4459-b70b-ce9761c3ac91.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
This PR adds UIA events when accessibilityState has changed which will ensure that accessibility clients like Narrator can announce these types of changes to the user. 
Resolves: #8491 
Added peer.RaisePropertyChangedEvent() calls when selected, disabled, checked, or expanded state has changed. 
Here's an example that togggles Expand/Collapse state, highlighted portion is what Narrator announces when the touchable is clicked.
```js
<TouchableHighlight
style={styles.item}
accessibilityLabel="Group Expand Collapse Button"
accessible={true}
accessibilityRole="none"
accessibilityState={{expanded: this.state.displayText}}
onPress={() => {
this.setState({displayText: !this.state.displayText});
}}>
<Text style={styles.text}>Group …
```
=> Narrator announces changes to accessibilityState

yarn.lock
* Update to `moment@2.29.3` for CVE-2022-24785
=> [0.66] CG Fixes for 4/18/2022

yarn.lock
* Update to `moment@2.29.3` for CVE-2022-24785
=> [0.67] CG Fixes for 4/18/2022

change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj, vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters, vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp, vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Cherry pick PR #9818
Original PR description:
Fix Sequential Mso DispatchQueue deadlock on shutdown
@acoates-ms has reported an issue that we have a deadlock when Mso sequential DispatchQueue based on thread pool is shutting down. The source of the issue is that the scheduler class waits for thread pool work to finish in the destructor, and if the dispatch queue or the scheduler class is being destroyed from the thread pool task itself, then we are getting a deadlock:
- the scheduler class destructor waits for thread pool task to finish;
- the thread pool task waits on the scheduler class to complete destruction.
To fix the issue we are introducing `ThreadPoolSchedulerWinContext` class that tracks current `ThreadPoolSchedulerWin` …
=> [0.66] Fix Sequential Mso DispatchQueue deadlock on shutdown

change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9867
Original description:
Fix JSI implementation for Node-API and update v8jsi to 0.65.11
Node-API does not specify explicitly calling conventions for functions.
It is typically not an issue when code is compiled with the default calling conventions, but `react-native-win32.dll` is compiled with `__stdcall` calling conventions while the `v8jsi.dll` is with the `__cdecl` calling conventions.
As a result, using the Node-API function is not ABI-safe.
Foreseeing this issue, we explicitly marked all Node-API functions as `__cdecl`, but we forgot to decorate with the `__cdecl` the function pointer types. As a result, we see crashes in x86 environment when we create host functions or host objects.
To fix the issue we updated …
=> [0.67] Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)

change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/PropertySheets/JSEngine.props, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9867 
Original description:
Fix JSI implementation for Node-API and update v8jsi to 0.65.11
Node-API does not specify explicitly calling conventions for functions.
It is typically not an issue when code is compiled with the default calling conventions, but `react-native-win32.dll` is compiled with `__stdcall` calling conventions while the `v8jsi.dll` is with the `__cdecl` calling conventions.
As a result, using the Node-API function is not ABI-safe.
Foreseeing this issue, we explicitly marked all Node-API functions as `__cdecl`, but we forgot to decorate with the `__cdecl` the function pointer types. As a result, we see crashes in x86 environment when we create host functions or host objects.
To fix the issue we updated …
=> [0.68] Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)

change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/PropertySheets/JSEngine.props, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9867
Original description:
Fix JSI implementation for Node-API and update v8jsi to 0.65.11
Node-API does not specify explicitly calling conventions for functions.
It is typically not an issue when code is compiled with the default calling conventions, but `react-native-win32.dll` is compiled with `__stdcall` calling conventions while the `v8jsi.dll` is with the `__cdecl` calling conventions.
As a result, using the Node-API function is not ABI-safe.
Foreseeing this issue, we explicitly marked all Node-API functions as `__cdecl`, but we forgot to decorate with the `__cdecl` the function pointer types. As a result, we see crashes in x86 environment when we create host functions or host objects.
To fix the issue we updated …
=> Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)

change/@react-native-windows-cli-9b90ea8d-57a8-49b1-a2c3-1dbf5dc120bc.json, change/@react-native-windows-telemetry-576950f0-e0ad-4946-afbd-7def82c5885b.json, packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts, packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts, packages/@react-native-windows/telemetry/src/telemetry.ts, packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts, packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts, packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts, packages/@react-native-windows/telemetry/src/utils/errorUtils.ts, packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
This PR makes several changes so that the reported CLI telemetry meets ApplicationInsights (AI)'s server-side requirements:
* Ensures that reported errors have a defined, non-empty error message, to pass AI schema validation
* Fixes MSBuild error parsing not running during `run-wiundows`, now we extract the actual error codes, not the process exit code
* Updates `RNWCLI.CodedError` schema to better reflect what is being returned
* Adds `deviceArchitecture`, `devicePlatform`, and `sampleRate` as explicit properties, since otherwise AI strips them
* Command `extraProps` are now stored in their own field as an object, rather than injected as peers with the other properties, to make server-side processing easier and enable future extensions
* `isTest` boolean property is now included all the …
=> Telemetry updates to meet server-side requirements

change/@react-native-windows-cli-fbe2ed4a-2420-408e-9c0a-ec10c517eb0a.json, change/@react-native-windows-telemetry-b37e2a4f-8e7a-4dba-8658-480455e84792.json, packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts, packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts, packages/@react-native-windows/telemetry/src/telemetry.ts, packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts, packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts, packages/@react-native-windows/telemetry/src/test/telemetry.test.ts, packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts, packages/@react-native-windows/telemetry/src/utils/errorUtils.ts, packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
This PR backports #9873 to 0.68.
This PR makes several changes so that the reported CLI telemetry meets ApplicationInsights (AI)'s server-side requirements:
* Ensures that reported errors have a defined, non-empty error message, to pass AI schema validation
* Fixes MSBuild error parsing not running during `run-wiundows`, now we extract the actual error codes, not the process exit code
* Updates `RNWCLI.CodedError` schema to better reflect what is being returned
* Adds `deviceArchitecture`, `devicePlatform`, and `sampleRate` as explicit properties, since otherwise AI strips them
* Command `extraProps` are now stored in their own field as an object, rather than injected as peers with the other properties, to make server-side processing easier and enable future extensions
* `isTest` boolean …
=> [0.68] Telemetry updates to meet server-side requirements

change/react-native-windows-d5714a62-4b4a-4f7f-b763-fffe99ce60b4.json, vnext/src/Libraries/Components/TextInput/TextInput.windows.js
TextInput accessible and focusable prop behavior should match that of iOS and Android. The behavior should be that the prop value passed to the native is true unless the prop value is specified as false. Thus, we should pass in the adjusted accesssible/focusable value and not the original prop value. 
Match TextInput accessible and focusable prop behavior to that of iOS and Android.
=> Fix Focusable/Accessible Prop Behavior for TextInput

.ado/jobs/node-tests.yml, change/@react-native-windows-telemetry-4f2dfd2c-bd77-4c67-8079-427bb5d099ff.json, packages/@react-native-windows/telemetry/src/e2etest/telemetry.test.ts
This PR:
* Removes yarn test concurrency limiter in ADO
* Moves telemetry.test.ts into an e2etest folder
=> Fix telemetery e2e tests

change/@react-native-windows-telemetry-b387b859-9502-40a1-bbb5-b00c1584501f.json, packages/@react-native-windows/telemetry/src/e2etest/telemetry.test.ts
This PR backports #9889 to 0.68.
This PR:
* Moves telemetry.test.ts into an e2etest folder
=> [0.68] Fix telemetry e2e tests

CONTRIBUTING.md
CI has warnings because of some of the links to the GitHub Docs site. A fix was made in unbroken (https://github.com/asklar/unbroken/pull/35) but this PR also updates the links.
=> Fix links to GitHubDocs

change/react-native-windows-0177fe7f-ddf1-4c12-a7e5-88d0680f2e7f.json, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Desktop/pch.h, vnext/ExperimentalFeatures.props, vnext/Microsoft.ReactNative/Fabric/ComponentViewRegistry.cpp, vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp, vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp, vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/platform/cxx/react/renderer/graphics/Color.h, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Shared/Shared.vcxitems, vnext/Shared/Shared.vcxitems.filters
This moves the fabric core cpp files to `Shared.vcxitems` which allows the win32 dll to share the files.  Still behind the `UseFabric` experiment, so its turned off by default.  -  I also sprinkled a few `#ifdef CORE_ABI`'s to allow the desktop dll to build when `UseFabric` is turned on, which is now a one word change in `vnext/ExperimentalFeatures.props`
This will make future changes bringing fabric to the desktop dll much smaller.
=> Move fabric code to shared project

change/react-native-windows-a3a1d3b3-3f08-4da5-aa47-b8ff802be8c0.json, vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Add missing `template` keywords in `NativeModules.h` to make clang happy. Devmain requires NativeModules.h to be compatible with msvc and clang if we want to introduce turbo module there.
Related PRs:
[For 0.66-stable](https://github.com/microsoft/react-native-windows/pull/9903)
[For 0.67-stable](https://github.com/microsoft/react-native-windows/pull/9904)
[For 0.68-stable](https://github.com/microsoft/react-native-windows/pull/9905)
[For main](https://github.com/microsoft/react-native-windows/pull/9906)
=> [0.66] Fix clang-check errors in NativeModules.h

change/react-native-windows-36e61759-a423-47ff-adce-3b8845d7c1bc.json, vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Add missing `template` keywords in `NativeModules.h` to make clang happy. Devmain requires NativeModules.h to be compatible with msvc and clang if we want to introduce turbo module there.
Related PRs:
[For 0.66-stable](https://github.com/microsoft/react-native-windows/pull/9903)
[For 0.67-stable](https://github.com/microsoft/react-native-windows/pull/9904)
[For 0.68-stable](https://github.com/microsoft/react-native-windows/pull/9905)
[For main](https://github.com/microsoft/react-native-windows/pull/9906)
=> [0.67] Fix clang-check errors in NativeModules.h

change/react-native-windows-ecc4fc50-974b-4a75-b8ef-2f18e1aabc05.json, vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Add missing `template` keywords in `NativeModules.h` to make clang happy. Devmain requires NativeModules.h to be compatible with msvc and clang if we want to introduce turbo module there.
Related PRs:
[For 0.66-stable](https://github.com/microsoft/react-native-windows/pull/9903)
[For 0.67-stable](https://github.com/microsoft/react-native-windows/pull/9904)
[For 0.68-stable](https://github.com/microsoft/react-native-windows/pull/9905)
[For main](https://github.com/microsoft/react-native-windows/pull/9906)
=> [0.68] Fix clang-check errors in NativeModules.h

change/react-native-windows-49693198-37f8-41ce-a678-bf4756dcaf0e.json, vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Add missing `template` keywords in `NativeModules.h` to make clang happy. Devmain requires NativeModules.h to be compatible with msvc and clang if we want to introduce turbo module there.
Related PRs:
[For 0.66-stable](https://github.com/microsoft/react-native-windows/pull/9903)
[For 0.67-stable](https://github.com/microsoft/react-native-windows/pull/9904)
[For 0.68-stable](https://github.com/microsoft/react-native-windows/pull/9905)
[For main](https://github.com/microsoft/react-native-windows/pull/9906)
=> Fix clang-check errors in NativeModules.h

change/react-native-windows-75d3cf97-675c-4257-b49c-bcc7bfbd0e27.json, vnext/Shared/DevSupportManager.cpp
Ports #9756 to 0.68
Fixes an issue in DevSupport manager where we crash trying to set up the inspector
=> [0.68] Avoid crashing when running unpackaged apps

change/react-native-windows-12b8ebce-b24a-4945-aabb-3021ecb46003.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h
=> [0.68] Built in turbomodules should not override app provided versions

change/react-native-windows-4e0e762e-ea7f-458b-93c2-533b3fa3a806.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Port #9504 to main.  -- Eventually folly usage will be removed entirely from Office, but in the meantime putting this in main so I dont have to port it to every stable branch when importing into Office.
=> Stop exporting data blocks from react-native-win32.dll

packages/@rnw-scripts/metro-dev-config/metro.dev.config.js
Integration tests are failing because there are two versions of
`metro-runtime` used in our repo (0.67.0 and 0.70.1), mirroring the setup
of `react-native`.
We are using the `@rnx-kit/metro-plugin-duplicates-checker` package
which will cause a bundle operation to fail if duplicate packages are
detected. This causes the integration tests to time-out as they try to
create the bundle and keep getting errors.
This PR adds `metro-runtime` to the list of packages to ignore
duplicates.
Resolves #9929
=> Ignore duplicate metro-runtime verions in dev metro-config

.ado/templates/react-native-init.yml, .ado/templates/run-windows-with-certificates.yml
This PR disables bundling when running the CLI tests temporarily, until https://github.com/react-native-community/cli/pull/1605 gets resolved and published.
Closes https://github.com/microsoft/react-native-windows/issues/9939
=> Fix issue with CLI tests failing in PRs

change/@office-iss-react-native-win32-75b311de-fa52-43c2-b047-d5ebb530fa48.json, change/react-native-windows-92a206ee-c911-489b-89a7-a5857370a307.json, packages/@office-iss/react-native-win32/package.json, packages/e2e-test-app/package.json, packages/integration-test-app/package.json, packages/playground/metro.config.js, packages/playground/package.json, packages/sample-apps/package.json, vnext/package.json, yarn.lock
This PR backports https://github.com/microsoft/react-native-windows/pull/9946 to 0.69.
This PR:
* Bumps our yarn.lock to use the latest community cli and metro plugin
* Bumps our packages to align to the newest version of metro
* Fixes playground's custom metro resolver to work with the new metro
Closes https://github.com/microsoft/react-native-windows/issues/9944
=> [0.69] Upgrade to @react-native-community/cli@8.0.0-alpha.6 

change/@react-native-windows-codegen-6a977a7a-80c1-49a4-9390-31345030db9b.json, packages/@react-native-windows/codegen/src/Cli.ts, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
Devmain is still in 0.66, this version lacks of some new features in turbo module specs. In order to make `RNW/codegen` development easy, `RNW/codegen` will have some features to make generated code compatible with old turbo module specs, instead of porting compatible changes of`RNW/codegen` back to old versions.
`--methodonly` is one of them, which skip all constant type-safety validation in specs, such validation is introduced in 0.68.
[Here](https://github.com/ZihanChen-MSFT/react-native-windows/commit/dda0aafc76ebef3d0221bee8b04b35c47bedea4e) is a test case (not included in this PR) about what will happen when using `--methodonly`.
=> Add --methodonly  to RNW/codegen

.ado/templates/react-native-init.yml, change/@office-iss-react-native-win32-8c3a049d-265c-4c97-8797-4a58274e66b7.json, change/react-native-windows-a25b692a-2335-4dda-89f4-d3a086f93053.json, packages/@office-iss/react-native-win32/package.json, packages/e2e-test-app/package.json, packages/integration-test-app/package.json, packages/playground/metro.config.js, packages/playground/package.json, packages/sample-apps/package.json, vnext/package.json, yarn.lock
This PR:
* Bumps our yarn.lock to use the latest community cli and metro plugin
* Bumps our packages to align to the newest version of metro
* Fixes playground's custom metro resolver to work with the new metro
* Re-enables bundling in our CI
Closes #9944
=> Upgrade to @react-native-community/cli@8.0.0-alpha.6

.ado/jobs/cli-init.yml, .ado/stages.yml, .ado/templates/react-native-init.yml, change/react-native-windows-a9ac003c-8ce9-4352-8f70-6d8caa7793e3.json, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems, vnext/Scripts/Tfs/Layout-MSRN-Headers.ps1, vnext/template/cs-app-WinAppSDK/proj/NuGet.Config
The `Microsoft.ReactNative.Cxx.vcxitems` project is used in two places - from within the file structure of the RNW package (in this repo, or via npm) and also within the `Microsoft.ReactNative.Cxx` NuGet package, which has a different (flattened) file structure.
In addition, certain files were not included in the NuGet package, which would break C++ apps building against the binaries.
This PR updates the `Layout-MSRN-Headers.ps1` script to copy the missing files, and updates the `Microsoft.ReactNative.Cxx.vcxitems` project to use the correct paths in both use cases.
This PR also fixes a bug in the pipelines that caused the CLI tests creating new apps against the NuGets from being run, which would have caught this bug.
Fixing the pipeline bug also has the side effect of actually running …
=> Fix Microsoft.ReactNative.Cxx nuget package missing files

change/react-native-windows-9193a9f7-cac3-4657-b640-ac468b782823.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
The logging function tries to calculate the length of the buffer using a function that takes varargs instead of va_list.
=> Fix crash when enabling Yoga logging

change/react-native-windows-b0c290d3-c8b2-4afe-82b3-2c1aa7a5741c.json, vnext/Mso/src/dispatchQueue/looperScheduler.cpp
Fix the run loop in loopScheduler.cpp
In my previous pull request here: https://github.com/microsoft/react-native-windows/pull/9900, I found that I unexpectedly changed the scoping on some of the run loop code. This pull request fixes that.
The scoping of the while loop in looperScheduler::RunLoop
To test that we can subscribe to the notification, I added …
=> Fix the run loop

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
However since we get non-dismissible alerts that the components are unsupported by CG.
=> Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-b32aaa98-0ab9-47f9-a39f-4371bf2c8bdf.json, vnext/Shared/RuntimeOptions.cpp, vnext/Shared/RuntimeOptions.h
After these changes and additional changes to Office code related to the `IWebSocketResource` namespace changes, I could compile and run the Office code.
=> [0.66] Fix RuntimeOptions for RNW Desktop

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
This PR backports #10011 to 0.69.
However  we get non-dismissable alerts that the components are unsupported by CG.
=> [0.69] Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
This PR backports #10011 to 0.68.
However we get non-dismissable alerts that the components are unsupported by CG.
=> [0.68] Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
This PR backports #10011 to 0.67.
However we get non-dismissable alerts that the components are unsupported by CG.
=> [0.67] Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
This PR backports #10011 to 0.66.
However we get non-dismissable alerts that the components are unsupported by CG.
=> [0.66] Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/fmt/fmt.vcxproj
This PR backports #10011 to 0.65.
However we get non-dismissable alerts that the components are unsupported by CG.
=> [0.65] Change CG registration for folly and fmt from `other` to `git`

change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
The `NapiJsiV8RuntimeHolder` is wrapping up provided `PreparedScriptStore` instance into the ABI-safe …
=> [0.66] Support PreparedScriptStore for V8 Node-API

change/react-native-windows-b32aaa98-0ab9-47f9-a39f-4371bf2c8bdf.json, vnext/Shared/RuntimeOptions.cpp, vnext/Shared/RuntimeOptions.h
Cherry pick PR #10016. Original PR description:
After these changes and additional changes to Office code related to the `IWebSocketResource` namespace changes, I could …
=> [0.67] Fix RuntimeOptions for RNW Desktop (#10016)

change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/PropertySheets/JSEngine.props, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9995. Original PR description:
The `NapiJsiV8RuntimeHolder` is wrapping up provided …
=> [0.68] Support PreparedScriptStore for V8 Node-API (#9995)

change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json, vnext/Desktop.DLL/packages.config, vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/Microsoft.ReactNative/packages.config, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/packages.config, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9995. Original PR description:
The `NapiJsiV8RuntimeHolder` is wrapping up provided …
=> [0.67] Support PreparedScriptStore for V8 Node-API (#9995)

change/react-native-windows-b32aaa98-0ab9-47f9-a39f-4371bf2c8bdf.json, vnext/Shared/RuntimeOptions.cpp, vnext/Shared/RuntimeOptions.h
Cherry pick PR #10016. Original PR description:
After these changes and additional changes to Office code related to the `IWebSocketResource` namespace changes, I could …
=> Fix RuntimeOptions for RNW Desktop (#10016)

change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/PropertySheets/JSEngine.props, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9995. Original PR description:
The `NapiJsiV8RuntimeHolder` is wrapping up provided …
=> Support PreparedScriptStore for V8 Node-API (#9995)

change/react-native-windows-b32aaa98-0ab9-47f9-a39f-4371bf2c8bdf.json, vnext/Shared/RuntimeOptions.cpp, vnext/Shared/RuntimeOptions.h
Cherry pick PR #10016. Original PR description:
After these changes and additional changes to Office code related to the `IWebSocketResource` namespace changes, I could …
=> [0.69] Fix RuntimeOptions for RNW Desktop (#10016)

change/react-native-windows-b32aaa98-0ab9-47f9-a39f-4371bf2c8bdf.json, vnext/Shared/RuntimeOptions.cpp, vnext/Shared/RuntimeOptions.h
Cherry pick PR #10016. Original PR description:
After these changes and additional changes to Office code related to the `IWebSocketResource` namespace changes, I could …
=> [0.68] Fix RuntimeOptions for RNW Desktop (#10016)

change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/PropertySheets/JSEngine.props, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Cherry pick PR #9995. Original PR description:
The `NapiJsiV8RuntimeHolder` is wrapping up provided …
=> [0.69] Support PreparedScriptStore for V8 Node-API (#9995)

.ado/compliance.yml, .ado/config/CredScanSuppressions.json, .ado/config/PoliCheckExclusions.xml, .ado/jobs/linting.yml, .ado/publish.yml
This PR adds the PoliCheck and CredScan config files to prevent them
from checking the wrong files.
=> Add PoliCheck and CredScan config files

NuGet.Config, change/react-native-windows-e24cec68-175e-4980-ac12-788e91464627.json, packages/e2e-test-app/windows/NuGet.Config, packages/integration-test-app/windows/NuGet.Config, packages/playground/windows/NuGet.Config, packages/sample-apps/windows/NuGet.Config, vnext/NuGet.Config
This PR updates all used NuGet.Config files to reduce the number of warnings produced by the Secure Supply Chain Analysis task. This does not completely address them however.
Related issues: https://github.com/microsoft/react-native-windows/issues/9992, https://github.com/microsoft/react-native-windows/issues/9993, https://github.com/microsoft/react-native-windows/issues/9996, https://github.com/microsoft/react-native-windows/issues/9997
=> Update NuGet config files to reduce Secure Supply Chain Analysis warnings

.ado/templates/component-governance.yml, yarn.lock
* Filtering out `node_modules/react-native/template` from scan
=> [0.68] Resolving CG alerts 6/1/2022

.ado/templates/component-governance.yml, yarn.lock
* Filtering out `node_modules/react-native/template` from scan
=> [0.67] Resolving CG alerts 6/1/2022

.ado/jobs/cli-init.yml, .ado/jobs/desktop.yml, .ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/jobs/sample-apps.yml, .ado/jobs/universal.yml
This PR expands the matrix of build configurations for PRs by adding the
combinations that run in CI. This is to prevent PRs from passing and
then immediately failing in CI and/or publishing and breaking the stable
branch.
Related: #8851
=> [0.68] Run more checks against stable branch PRs

.ado/jobs/cli-init.yml, .ado/jobs/desktop.yml, .ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/jobs/sample-apps.yml, .ado/jobs/universal.yml
This PR expands the matrix of build configurations for PRs by adding the
combinations that run in CI. This is to prevent PRs from passing and
then immediately failing in CI and/or publishing and breaking the stable
branch.
Related: #8851
=> [0.67] Run more checks against stable branch PRs

.ado/jobs/cli-init.yml, .ado/jobs/desktop.yml, .ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/jobs/playground.yml, .ado/jobs/sample-apps.yml, .ado/jobs/universal.yml
This PR expands the matrix of build configurations for PRs by adding the
combinations that run in CI. This is to prevent PRs from passing and
then immediately failing in CI and/or publishing and breaking the stable
branch.
Related: #8851
=> [0.66] Run more checks against stable branch PRs

.ado/jobs/cli-init.yml, .ado/jobs/desktop.yml, .ado/jobs/e2e-test.yml, .ado/jobs/integration-test.yml, .ado/jobs/playground.yml, .ado/jobs/sample-apps.yml, .ado/jobs/universal.yml
This PR expands the matrix of build configurations for PRs by adding the
combinations that run in CI. This is to prevent PRs from passing and
then immediately failing in CI and/or publishing and breaking the stable
branch.
Related: #8851
=> [0.65] Run more checks against stable branch PRs

change/react-native-windows-ea378e65-3e8c-4b6e-a90b-d9b4d862ed17.json, vnext/stubs/double-conversion/double-conversion.h
The current stub implementation we have for double-conversion is using strtod / stod which performs float/double conversions in a locale-dependent manner. This doesn't work for reading a number from json in locales that use different digit separators (e.g. in German you'd write "1,5"  instead of "1.5", so when we try to parse a json value via folly (which uses double-conversion), we error out when we find the . as it is not a valid separator).
Apps should work in all locales :)
Resolves [to be filed]
This uses `from_chars` which uses the C locale and in addition is a lot faster than strtod
=> Fix floating point conversions in non en-US locales

change/react-native-windows-d0b46459-5370-47eb-9a2c-9c46738403cb.json, vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/YGValue.h, vnext/overrides.json
Port #8676 to main.
There was a hope to avoid this fork in main, with #8725, but that ended up hitting the original issue of why we turned on strict mode in the first place.  I'd rather get a fix in so that we dont ship this issue again in upcoming releases.  When we get a fix for the strict mode, we could remove this patch.
=> Fix ARM64 layout issues

change/react-native-windows-d4179584-e159-44b9-b6fe-c1f4c00e8004.json, vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp, vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json, vnext/Microsoft.ReactNative.Managed/packages.lock.json, vnext/Shared/OInstance.cpp
Do not add BlobModule nor FileReaderModule to the default CxxModule list when running a UWP MSRN instance.
Undefined object sharing behavior in UWP (as opposed to Desktop) will cause a malfunction of HTTP/fetch workflows due to a misconfigured Blob module.
Resolves #10036
- Conditionally compile the code that adds `BlobModule` and `FileReaderModule` to the default modules' list in the `InstanceImpl` class.
- Defined `Blob.EnableModule` runtime option.
=> Do not use Blob/FileReader modules in UWP

change/react-native-windows-1653495d-e9db-497e-a6e2-bb5fbcc05317.json, vnext/Shared/Networking/WinRTHttpResource.cpp, yarn.lock
- Use logical OR to assert HTTP responseType
Trivial change. Debug-only.
Use logical OR to assert HTTP responseType
Assert (debug-only) that ensures the correct response types in HTTP resource uses a bit-wise OR instead of the expected logical OR `||`.
=> Use logical OR to assert HTTP responseType

change/react-native-windows-53a5b9fa-249c-4cf1-bf1f-f18b7d6be767.json, vnext/template/metro.devMode.config.js
When calling `react-native-windows-init --useDevMode`, it created metro config similar to the ones used by packages within the RNW monorepo. However, that config is only useful when running init to create new test apps within this repo, which is a rare occurrence.
This PR changes the dev mode metro config to instead work when testing how the CLI commands work while creating new projects outside of the repo, which is much more useful.
Closes #9691
This fixes the issue with metro not working when testing a new app created using `--useDevMode`.
This PR changes the dev mode metro config to instead work when testing how the CLI commands work while creating new projects outside of the repo, which is much more useful.
Tested locally that …
=> Fixed metro config when using `--useDevMode`

change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
=> Fix use of [[maybe_unused]] attribute

change/react-native-windows-3db31062-b08b-44b3-8158-a73f139c1714.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Fixes #10111
As reported in #10111, float4x4's operator* does not produce the same output as expected on other RN platforms. 
Resolves #10111
This change ports the logic from RN's MatrixMath.js to ensure multiplication of transforms produces the same result on Windows as on iOS and Android.
|Before|After|iOS|
|----|----|----|
|<img width="322" alt="image" src="https://user-images.githubusercontent.com/1106239/173636752-c2a0bec0-2021-4e60-a565-660e0bf57ce1.png">|<img width="352" alt="image" …
=> Fix matrix multiplication logic for transforms

change/react-native-windows-3db31062-b08b-44b3-8158-a73f139c1714.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Backporting #10112 into v0.69.
As reported in #10111, float4x4's operator* does not produce the same output as expected on other RN platforms. 
Resolves #10111 
This change ports the logic from RN's MatrixMath.js to ensure multiplication of transforms produces the same result on Windows as on iOS and Android.
|Before|After|iOS|
|----|----|----|
|<img width="322" alt="image" src="https://user-images.githubusercontent.com/1106239/173636752-c2a0bec0-2021-4e60-a565-660e0bf57ce1.png">|<img width="352" alt="image" src="https://user-images.githubusercontent.com/1106239/173637740-9cc6a26e-d1e5-43f0-a35a-eb3f05671894.png">|<img width="424" alt="Screen Shot 2022-06-14 at 1 04 06 PM" …
=> [0.69] Fix matrix multiplication logic for transforms (#10112)

change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
=> [0.69] Fix use of [[maybe_unused]] attribute (#10103)

change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
=> [0.68] Fix use of [[maybe_unused]] attribute (#10103)

change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
=> [0.67] Fix use of [[maybe_unused]] attribute (#10103)

change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json, vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
=> [0.66] Fix use of [[maybe_unused]] attribute (#10103)

.ado/publish.yml
Manually install .net as needed by ESRP
Fix pipeline
.Net 5 is EOL so requires manual force install required by ESPR
=> Install .net 5 for ESRP

.gitignore, change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h, vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp, vnext/Microsoft.ReactNative.Cxx/ReactPromise.h, vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
(This is @vmoroz 's  PR #10148 but he is going to be oof, we need this change but the pipeline is failing due to linting, and I don't have permissions to update his fork, so sending this as a separate PR :) )
Do not crash process in `ExecuteJsi` function when React instance is already shutdown.
Instead, we do not execute the provided code.
The success or failure condition can be reported using optional `ReactPromise` parameter.
There was a crash report from a partner team that the `ExecuteJsi` method sometimes causes a crash.
The investigation has shown that the root cause of issue is that React instance is being destroyed and the underlying JS engine is not available anymore. In such case, the `GetOrCreateContextRuntime` function is …
=> Fix ExecuteJsi on instance shutdown

change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
While validating dependencies during autolinking, we threw a misleading error message in one very specific case of a module being misconfigured, but otherwise just logged the validation failure and move on.
This PR changes the behavior such that autolinking just logs the validation failure in all cases.
I recognize that we may *want* to throw errors and alert the user, but I think adding new errors is a breaking behavior change that users might not appreciate. I want this PR to be non-breaking and backportable (at least to 0.68), and I've opened #10013 to track how we might introduce that breaking behavior more thoughtfully.
=> Update autolinking to not error if a dependency is misconfigured

change/@office-iss-react-native-win32-d14f43ea-5d87-42e6-ac59-932aaee0dd9e.json, packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx, packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js, packages/@office-iss/react-native-win32/package.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backport of #9902
To allow developers to use listitem accessibilityRole in previous versions.
=> [0.68] Add listitem accessibility role and accessibilityControls test example

change/react-native-windows-88b0da78-0c4c-43a0-b3b6-63ed97519d68.json, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Clang doesn't like backslashes in includes.
Changes  backslash in include to forwardslash.
N/A
RNW still compiles.
=> Minor fix for clang compile

change/react-native-windows-0eabcbbe-3124-42fe-b30b-356332950c73.json, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/CompactValue.h, vnext/overrides.json
Stop compiling yoga.cpp with /fp:strict. Doing so caused layout issues
if Yoga code ran with the processor's rounding mode set to round down,
due to NAN being defined in math.h as:
```
(float)(INFINITY * 0.0f)
```
Which macro-expands to:
```
(float)(((float)(1e+300 * 1e+300)) * 0.0f)
```
Which evaluates as follows:
```
(float)(((float)(inf.double)) * 0.0f)
(float)(FLT_MAX * 0.0f) // Casting an infinite double to a float yields
// FLT_MAX!
(float)0.0f
```
Oops. Also, /fp:strict is slightly more pessimistic & slower... not that
anyone should be running Yoga layout in a tight loop or anything! But
free perf is always nice.
I manually inspected the disassembly code that was identified as causing …
=> [0.67] Stop using /fp:strict to build yoga.cpp

change/react-native-windows-3f7196aa-b677-4cfd-8417-61aafaf0a51e.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Clang fails to disambiguate the ReactContext namespace for the field used on the ReactInstance.
Fully qualifies the ReactContext namespace for ReactInstanceWin.
react-native-windows still compiles in Visual Studio and works correctly.
=> Disambiguate ReactContext in ReactInstanceWin

change/react-native-windows-0eabcbbe-3124-42fe-b30b-356332950c73.json, change/react-native-windows-93991d79-32d9-4ddb-b3e1-41652af70870.json, vnext/ReactCommon/ReactCommon.vcxproj, vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/CompactValue.h, vnext/overrides.json
Stop compiling yoga.cpp with /fp:strict. Doing so caused layout issues
if Yoga code ran with the processor's rounding mode set to round down,
due to NAN being defined in math.h as:
```
(float)(INFINITY * 0.0f)
```
Which macro-expands to:
```
(float)(((float)(1e+300 * 1e+300)) * 0.0f)
```
Which evaluates as follows:
```
(float)(((float)(inf.double)) * 0.0f)
(float)(FLT_MAX * 0.0f) // Casting an infinite double to a float yields
// FLT_MAX!
(float)0.0f
```
Oops. Also, /fp:strict is slightly more pessimistic & slower... not that
anyone should be running Yoga layout in a tight loop or anything! But
free perf is always nice.
I manually inspected the disassembly code that was identified as causing …
=> [0.69] Stop using /fp:strict to build yoga.cpp

change/@office-iss-react-native-win32-822aa9aa-dd03-47cc-9641-5a714c0f13bb.json, change/@react-native-windows-cli-afcd1c6f-ef03-4e9b-80f9-73fd869ba11c.json, change/@react-native-windows-codegen-bab7238d-4bb2-4dac-9dc8-5fe4fbc66cc8.json, change/@react-native-windows-find-repo-root-725be6a3-dd4d-4879-b338-31471f1eda57.json, change/@react-native-windows-fs-ee682c2e-b200-4951-abe9-db240ba9b1b0.json, change/@react-native-windows-package-utils-c3004455-1999-4e4e-b24d-b4cc5905ecc7.json, change/@react-native-windows-telemetry-45267e5b-6d12-4c3d-ba08-b7a02e502bb5.json, change/@react-native-windows-virtualized-list-b915c21f-52f5-4a10-8548-d9388cd41c81.json, change/react-native-windows-63c2a80d-0da8-4078-bde7-e0a6d8310a19.json, packages/@office-iss/react-native-win32/package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/codegen/package.json, packages/@react-native-windows/find-repo-root/package.json, packages/@react-native-windows/fs/package.json, packages/@react-native-windows/package-utils/package.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/virtualized-list/package.json, vnext/package.json
- Release Cycle
Promote 0.68 to Legacy
=> Promote 0.68 to Legacy

change/@react-native-windows-cli-3f8700bf-ee14-4a3e-82b6-873d10aa6fc0.json, packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
The default cmd.exe is not in utf8 mode when launched from node. When run-windows is run, the vswhere command fails when their are unexpected characters in the description. We need a workaround to standardize the characters before vswhere is run.
Resolves #10034
=> Fix UTF8 Bug in vswhere Command

change/react-native-windows-ed697687-b653-4c00-a2ea-341bcc4bae8e.json, packages/playground/Samples/image.tsx, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
Resolves #10177 
Image uses ColorSourceEffect to implement tintColor which takes in a Windows::UI::Color and does not know about XAML brushes. This change adds PlatformColor support for when the windowsbrush being used is a SolidColorBrush that we can extract the color from.  
Manually tested and added case to the playground's Image page.
=> Add partial PlatformColor support for Image's tintColor

change/react-native-windows-f312927e-5f5d-4689-a6d1-6f9281409c06.json, vnext/Microsoft.ReactNative.Cxx/AppModelHelpers.h, vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Shared/Utils.cpp
There were a few places trying to do the same thing, so centralize them.
Also, discovered a bug where getting the app folder in packaged was never doing the right thing...
=> Centralize getting package identity and fix a bug getting app folder

change/react-native-windows-f2020c58-e8e2-4364-a3a9-619e3cd68c88.json, vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
The AlertModule assumes the Alert is the only active item in the PopupRoot, which may not be the case if any other flyouts or popups are being shown while the alert is being built.
This change fixes that assumption by searching for the correct dialog / smoke screen element rather than assuming the smoke screen and dialog are at index 0 and 1.
=> Fixes issue when alert is not only descendant of PopupRoot

change/react-native-windows-9f3d191c-3b3f-458a-8add-28df22e2531d.json, vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj, vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj, vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json, vnext/Microsoft.ReactNative.Managed/packages.lock.json
This PR updates our usage of Newtonsoft.Json to 13.0.1 to resolve two CG
alerts: WS-2022-0161 and GHSA-5crp-9r3c-p9vr
=> CG: Update Newtonsoft.Json to 13.0.1

change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
This PR backports #10014 to 0.69.
While validating dependencies during autolinking, we threw a misleading error message in one very specific case of a module being misconfigured, but otherwise just logged the validation failure and move on.
This PR changes the behavior such that autolinking just logs the validation failure in all cases.
I recognize that we may *want* to throw errors and alert the user, but I think adding new errors is a breaking behavior change that users might not appreciate. I want this PR to be non-breaking and backportable (at least to 0.68), and I've opened #10013 to track how we might introduce that breaking behavior more thoughtfully.
=> [0.69] Update autolinking to not error if a dependency is misconfigured

change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json, packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
This PR backports #10014 to 0.68.
While validating dependencies during autolinking, we threw a misleading error message in one very specific case of a module being misconfigured, but otherwise just logged the validation failure and move on.
This PR changes the behavior such that autolinking just logs the validation failure in all cases.
I recognize that we may *want* to throw errors and alert the user, but I think adding new errors is a breaking behavior change that users might not appreciate. I want this PR to be non-breaking and backportable (at least to 0.68), and I've opened #10013 to track how we might introduce that breaking behavior more thoughtfully.
=> [0.68] Update autolinking to not error if a dependency is misconfigured

change/react-native-windows-b064d013-f809-4f41-8d4f-6427c428618a.json, vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp, vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
- N/A (code cleanup)
We only depend on the IRandomAccessStream interface at call sites where the image stream is used, so no need to return the specific InMemoryRandomAccessStream implementation detail.
Rather than using the concrete `InMemoryRandomAccessStream` type for the ReactImage helper methods, switching to the `IRandomAccessStream` interface. We fork this code to add webp support and changing to this interface keeps the diff smaller.
Images still work as expected in RNTester.
=> Use interface for ReactImage memory streams

change/react-native-windows-f17abf92-78b7-416e-866a-5637f77ac23e.json, vnext/PropertySheets/Release.props
As part of an EIM initiative, did a compiler options pass for recommended flags to reduce binary size. We are mostly good; this adds the three we were missing. 
Minor savings since we had the majority set up already, but did slightly decrease binary size:
Microsoft.ReactNative.dll: 2,869,248 bytes -> 2,865,152 bytes (-4,096) 
.pdb: 113,397,760 bytes -> 113,364,992 bytes (-32,768)
Comparing through SizeBench, biggest impact was on the .rdata section. 
Internal link for recommended flags [here](https://www.osgwiki.com/wiki/Compiler_and_linker_flags_recommended_for_binary_size#MSBuild_equivalents).
=> Additional compiler & linker flags for binary size 

.ado/jobs/playground.yml, packages/debug-test/DebuggingFeatures.test.ts, packages/debug-test/MetroAutomation.ts, packages/debug-test/PlaygroundAutomation.ts, packages/debug-test/TestLog.ts, packages/debug-test/Utilities.ts
I previously added a couple of debug feature tests (packages\debug-test). So far, they required manual execution (and are thus useless except to those that are aware of their existence). This change executes these tests as part our ADO pipelines.
- modify test TS code to successfully execute on ADO agents, chiefly by adding more sync points between test code and UI of test host app (Playground)
- add ADO steps in YAML to execute tests as part of the pipeline
- add ADO steps to publish test logs and screenshots to aid failure investigation 
n/a
- run abbreviated ADO pipeline (https://dev.azure.com/ms/react-native-windows/_build?definitionId=267) to ensure resonable success rate of the tests
=> Run debug feature tests in ADO pipelines

change/react-native-windows-1e527570-f5d5-4193-a6b8-dc4eb1571f33.json, vnext/Microsoft.ReactNative/GlyphViewManager.cpp, vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
I assume that because we may not be using the same PCH, this causes the build to fail. Adding headers used in BatchingEventEmitter and GlyphViewManager to fix this.
=> Explicitly add headers for clang build

change/react-native-windows-1a39d1a9-7548-4b2b-956e-d684a2eace90.json, vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj, vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json, vnext/Microsoft.ReactNative.Managed/packages.lock.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
At a partner's request, enable the `WinUI` NuGet package to be conditionaly imported.
A partner consumer of MSRN needs to use teir own source variant of WinUI.
`PackageReference` will not work with a non-NuGet dependency.
For all instances of `PackageReference` importing WinUI, add the condition of new MSBuild property `OverrideWinUIPackage` to not be set to `true`.
=> Import WinUI package only if OverrideWinUIPackage is not set to "true"

change/react-native-windows-42dec614-af90-4b29-b8c7-f266415ea240.json, vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp, vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp, vnext/Shared/Networking/IHttpResource.h, vnext/Shared/Networking/WinRTHttpResource.cpp
Implements client-side timeout for HTTP requests.
Resolves #9538
- `Microsoft::React::WinRTHttpResource`\
Windows.Web.Http APIs do not provide a timeout mechanism.\
Using "co-routine competing" explained in https://devblogs.microsoft.com/oldnewthing/20220415-00/?p=106486 relying on `winrt::resume_after` to signal the timeout based on the value passed from JavaScript.
Added tests:
- `HttpResourceIntegrationTest::TimeoutFails`
- `HttpResourceIntegrationTest::TimeoutSucceeds`
=> Implement HTTP client timeout

change/react-native-windows-0440ff4e-5b47-4657-acb1-939f8568d6eb.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
=> [0.69] Import WinUI package only if OverrideWinUIPackage is not true

change/@react-native-windows-telemetry-731eae08-aad0-4223-98a0-59137f9c271d.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts, yarn.lock
This PR backports #10139 to 0.68.
Previously, we used the `node-machine-id` package to get a unique,
stable device id. However, that id cannot be correlated with any other
telemetry.
This PR removes the dependency on `node-machine-id` and instead gets a
more useful, unique device id (the same as you'll see in Settings >
System > About).
=> [0.68] Update source of DeviceID for telemetry

change/@react-native-windows-telemetry-731eae08-aad0-4223-98a0-59137f9c271d.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts, yarn.lock
This PR backports #10139 to 0.69.
Previously, we used the `node-machine-id` package to get a unique,
stable device id. However, that id cannot be correlated with any other
telemetry.
This PR removes the dependency on `node-machine-id` and instead gets a
more useful, unique device id (the same as you'll see in Settings >
System > About).
=> [0.69] Update source of DeviceID for telemetry

change/react-native-windows-29f353b2-b099-47fe-ba94-0a0f91672af7.json, vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
When transferring properties in the FrameworkElementViewManager, we were testing whether the result of `DP::ReadLocalValue` was null before clearing the property on the old view and transferring the property to the new view.
`ReadLocalValue` actually returns `DP::UnsetValue`, not nullptr, so this check has been faulty and unnecessarily transfers unset values. This commit switches the conditional to test for UnsetValue instead of null.
=> Check for DP::UnsetValue() rather than nullptr

change/react-native-windows-2e859e4c-95bd-4d4c-a348-0957d6a5e79d.json, vnext/stubs/double-conversion/double-conversion.h
Backporting #10058 into 0.69
Resolves #10272
The current stub implementation we have for double-conversion is using strtod / stod which performs float/double conversions in a locale-dependent manner. This doesn't work for reading a number from json in locales that use different digit separators (e.g. in German you'd write "1,5"  instead of "1.5", so when we try to parse a json value via folly (which uses double-conversion), we error out when we find the . as it is not a valid separator).
Apps should work in all locales :)
This uses `from_chars` which uses the C locale and in addition is a lot faster than strtod
=> [0.69] Fix floating point conversions in non en-US locales

change/react-native-windows-81fdd983-b7d9-4e03-9175-a9545a5e8599.json, vnext/stubs/double-conversion/double-conversion.h
Backporting #10058 into 0.68
Resolves #10272
The current stub implementation we have for double-conversion is using strtod / stod which performs float/double conversions in a locale-dependent manner. This doesn't work for reading a number from json in locales that use different digit separators (e.g. in German you'd write "1,5"  instead of "1.5", so when we try to parse a json value via folly (which uses double-conversion), we error out when we find the . as it is not a valid separator).
Apps should work in all locales :)
This uses `from_chars` which uses the C locale and in addition is a lot faster than strtod
=> [0.68] Fix floating point conversions in non en-US locales

change/@office-iss-react-native-win32-6203522e-a1d1-4c7c-8abd-058880715a24.json, change/react-native-windows-710a5094-3190-497d-94e5-1b58d8ec27ae.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js, vnext/src/Libraries/Components/View/View.windows.js
Backporting #9898 to resolve #9977. Tested with an example app to confirm fix.
Implement importantForAccessibility="no-hide-accessibility". When specified on a view-based component should remove accessibility for the element itself and its descendants.
Resolves #5113
Recursively apply accessible={false} prop to children of view-based component.
Attempted implementation used by Garrison team but it was not sufficient for Desktop, as focusable elements were still focusable even after being removed from the UIA tree.
Tested in playground with multiple configurations of nested components.
=> [0.68] Implement importantForAccessibility="no-hide-accessibility"

change/@office-iss-react-native-win32-66e95e8b-c77f-4122-bcbb-fcb1e6ce5077.json, change/react-native-windows-93fc478e-4970-43db-9342-1f0e9aa42483.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js, vnext/src/Libraries/Components/View/View.windows.js
Backporting #9898 to resolve #9977. Tested with an example app to confirm fix.
Implement importantForAccessibility="no-hide-accessibility". When specified on a view-based component should remove accessibility for the element itself and its descendants.
Resolves #5113
Recursively apply accessible={false} prop to children of view-based component.
Attempted implementation used by Garrison team but it was not sufficient for Desktop, as focusable elements were still focusable even after being removed from the UIA tree.
Tested in playground with multiple configurations of nested components.
=> [0.67] Implement importantForAccessibility="no-hide-accessibility"

change/react-native-windows-4559f97f-bb39-4fe8-a1a9-c3e950ae966e.json, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
In older versions of cppwinrt, the header generated for Windows.Foundation.Collections.h do not include the begin and end methods for `IIterable`.
This just switches the logic for compatibility with older versions of cppwinrt. Note, it may also include a bug fix where a comma separator is not emitted between headers from the request header collection and headers from the content header collection.
=> Fix compiler issue for older versions of C++/WinRT

change/react-native-windows-ac8e48c4-1cf1-4db8-bb98-ba177bf7a5c1.json, vnext/Shared/OInstance.cpp
For side-loaded or unpackaged apps built with React Native, it's not a guarantee that the JS bundle will be in an ASCII path. For example, if the bundle is installed into the %LOCALAPPDATA% folder, it's possible that this path contains UTF-8 characters for the user name. `fs::path` does not support UTF-8 characters.
This change switches to u8path in case there are UTF-8 characters in the path where the bundle is located.
=> Use u8path for bundle loading

change/react-native-windows-dd0c144f-9d1d-455c-b871-a45c09942d29.json, vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/CompactValue.h
1. memcpy is declared in `<cstring>`; add that include to make sure
CompactValue.h is self-contained
2. asFloat does not work correctly when __cpp_lib_bit_cast is true; an
old version of the input parameter's name is used accidentally. Since
this is conditionally compiled code that is only enabled for C++20,
and C++20 is not yet used in the RNW project, this does not currently
break anything, but fixing it now is still a good idea.
What is the motivation for this change? Add a few sentences describing the …
=> Two small fixes:

change/@rnw-scripts-doxysaurus-13ba6601-91c6-4360-80cd-7b98e4e90bce.json, packages/@rnw-scripts/doxysaurus/src/doxysaurus.ts
Doxysaurus' `Logger.writeLog` expects a string message, but in the case
of logging errors, doxysaurus can pass caught exceptions of the `Error`
type, which causes the logging itself to fail and give an unrelated
error, hiding the original error.
This PR fixes the issue by making sure that caught `Error`s are passed
in string form to the `Logger.writeLog` API.
=> Fix doxysaurus error logging to handle Error objects

change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json, packages/@rnw-scripts/doxysaurus/package.json, packages/@rnw-scripts/doxysaurus/src/doxygen.ts, yarn.lock
=> CG updates for 7/25/22

change/react-native-windows-14e96a89-26af-4535-b3d9-517842df1df6.json, vnext/Shared/OInstance.cpp
Converting the u8path back to a string causing character encoding issues. Since we pass std::strings around for bundle loading, we need to extract the generic_u8string from the fs::u8path.
Switches from std::filesystem::u8path::string to std::filesystem::u8path::generic_u8string to extract the correctly encoded data from the u8path.
Confirmed on v0.68 that this resolves the issue rather than v0.63 😬.
=> Additional fix required for UTF-8 characters in bundle path

change/react-native-windows-4e0e762e-ea7f-458b-93c2-533b3fa3a806.json, vnext/Desktop.DLL/react-native-win32.x64.def, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp, vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Port https://github.com/microsoft/react-native-windows/pull/9504 to 0.68. -- Stop exporting data blocks from react-native-win32.dll. These are unsupported, and do not work in arm64
=> [0.68] Stop exporting data blocks from react-native-win32.dll

change/react-native-windows-cd8eaf8d-1ab0-463a-9f8c-3efd78aa308d.json, vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp
We occasionally see a crash when the ViewPanel is null while running DynamicAutomationPeer::GetContentName. While we don't have a consistent repro, this change mitigated the issue. My guess is that there is some edge case where the ViewControl can be unmounted, calling `removeAllChildren`, which cleans up the `ViewPanel`, but somehow the automation peer still holds a reference to the ViewControl and tries to do work.
This change has been in production in Messenger Desktop for more than a month and no new instances are coming from this line in versions where the fix has deployed.
=> Fix crash in DynamicAutomationPeer::GetContentName

change/react-native-windows-8f7a774e-310a-4df6-9266-1173ee277b01.json, vnext/Microsoft.ReactNative/Views/Text/TextTransformParentVisitor.h
The textTransform logic is designed in a way that inherited transforms work properly. To accomplish this, when any change is made to raw text, it traverses its parent tree to find the first inherited transform.
When the raw text node is first created, it does not find any parent, so it uses the default initialized state value for textTransform in the TextTransformParentVisitor. Depending on compiler settings, this is not always 0 / undefined.
This change ensures the textTransform parent state is always set to Undefined.
=> Initialize TextTransformParentVisitor state

change/react-native-windows-1e43cf9b-edff-4998-83e5-74d1fc046cf5.json, vnext/Shared/Modules/FileReaderModule.cpp
Adds `#include <sstream>` to fix clang compile issue for std::ostringstream.
=> Adds header to fix clang build in FileReaderModule

change/react-native-windows-f6aa6009-1b42-488a-a477-5bb800e19895.json, vnext/Mso/src/memoryApi/memoryApi.cpp
Fixes clang compile issue for debug builds.
=> Adds windows.h include to memoryApi.cpp

.ado/publish.yml, change/@rnw-scripts-create-github-releases-d11e1dcc-5c40-4505-bf1a-5a7c149f5114.json, change/react-native-windows-bc36feae-f0a1-49ed-a2db-08c5a0377d44.json, packages/@rnw-scripts/beachball-config/src/beachball.config.ts, packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts, vnext/package.json
Years ago the RNW repo published new package revisions for every commit to the repo. Beachball's default is to create a new git tag for every package revision. This led to a Git tag, for every package, for every commit. GitHub previously included every tag  as an indivdual release in its "Releases" view. This drowned out the public-facing release notes, leading to a change to only tag package revisions where release notes were wanted.
GitHub has changed their UI, to no longer include tags in the "Releases" view. A current example where there are many tags but no releases is https://github.com/microsoft/fluentui-react-native/releases. This decoupling allows walking back …
=> Restore Git Tags for Canaries

change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json, packages/@rnw-scripts/doxysaurus/package.json, packages/@rnw-scripts/doxysaurus/src/doxygen.ts, yarn.lock
This PR:
* Updated to `moment@2.29.4`.
=> [0.65] CG updates for 7/25/22

change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json, packages/@rnw-scripts/doxysaurus/package.json, packages/@rnw-scripts/doxysaurus/src/doxygen.ts, yarn.lock
This PR:
* Updated to `moment@2.29.4`.
=> [0.66] CG updates for 7/25/22

change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json, packages/@rnw-scripts/doxysaurus/package.json, packages/@rnw-scripts/doxysaurus/src/doxygen.ts, yarn.lock
This PR:
* Updated to `moment@2.29.4`.
=> [0.67] CG updates for 7/25/22

change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json, packages/@rnw-scripts/doxysaurus/package.json, packages/@rnw-scripts/doxysaurus/src/doxygen.ts, yarn.lock
=> [0.68] CG updates for 7/25/22

change/react-native-windows-898d69e8-a95e-4148-96d5-b1ade9bc89fc.json, vnext/Desktop.DLL/react-native-win32.x86.def, vnext/Scripts/Tfs/Layout-Desktop-Headers.ps1
=> [0.68] Add missing export for x86, and publish patched folly files in office nuget

change/react-native-windows-cb076a1b-e4cb-40ad-a74d-f7b826107a3d.json, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Shared/Threading/BatchingQueueThread.cpp
During boot we have an undecorated callInvoker since the decorated one is not available until later in the instance boot sequence.  This means that early calls into turbomodules do not call into `NativeToJsBridge::recordTurboModuleAsyncMethodCall` which causes `NativeToJsBridge` to not call `onBatchComplete` at the end of a batch.
Changing the if in `BridgeUIBatchInstanceCallback::onBatchComplete` to allow batches to be completed during boot helps so that we do not miss any batch completions that are triggered.  But we also need to ensure that any calls queued before we were using the decoratedCallInvoker also triggers an `onBatchComplete`, which we do by using the decoratedCallInvoker when queuing the switch between the invokers.
Closes …
=> Allow batches to complete during load

change/react-native-windows-da8894e2-9136-4e6a-a357-e9ab8981d965.json, vnext/src/Libraries/Pressability/Pressability.windows.js
In #9603, we re-introduced right click events to react-native-windows. We specifically prevent `onPressIn`, `onPressOut`, and `onPress` events for anything other than the default button (e.g., left click). We should do the same for `onLongPress` events. Note, it is still possible to emulate "right click" behaviors for long press on touch devices as these types of presses are still treated as the default button.
This change checks if the event uses the default button before firing the onLongPress event.
In the videos below, I test left click behaviors first, then leave the button (see hover in / hover out messages), then test right click behaviors. In the before video, notice that after hover out/in, you see …
=> Only fire `onLongPress` for left clicks

change/react-native-windows-e97fdf26-8310-4cfa-8eb4-80405b7631e5.json, vnext/Scripts/Microsoft.ReactNative.nuspec
Include import lib in the M.RN nuget package to export `RNCoreApp*` APIs
Without this, people will have to LoadLibrary/GetProcAddress to find the exports
=> Include import lib in the M.RN nuget package to export CoreApp APIs

change/react-native-windows-96cc10b8-f540-456c-a1b9-2d1f8ecb536e.json, vnext/Directory.Build.props, vnext/Folly/Folly.vcxproj, vnext/Folly/cgmanifest.json, vnext/fmt/cgmanifest.json, vnext/fmt/fmt.vcxproj
This PR updates the custom targets within the Folly.vcxproj and fmt.vcxproj projects by:
* Speeding up incremental builds by setting `Inputs` and `Outputs` properties
* Calculating paths/filenames only once
* Normalizing the download/unzip/override pattern between both projects
* Improving build logging
* Outputting the `cgmanifest.json` file within the repo to be checked-in
(rather than under `node_modules`)
Closes #10212
=> Update custom targets in Folly.vcxproj and fmt.vcxproj

change/react-native-windows-3be31b9b-9aec-4dcd-b938-25de7534b9c0.json, vnext/Microsoft.ReactNative/Utils/TransformableText.h
We probably do not want this to crash the app in production, and it's somewhat strange to depend on an inlined function from the double-conversion.h that is not being used anywhere else.
For now, just switching to `assert(false)`, which should only crash in debug builds and is used in other places throughout RN Windows.
=> Remove call to nyi() in TransformableText

change/react-native-windows-6167fbe2-bc35-447b-a0eb-5b947cc5b538.json, vnext/Scripts/Microsoft.ReactNative.targets
Creates an msbuild property for the app to set that we check in order to link in the import library (used for RNCoreApp APIs).
Makes it easy to consume RNCoreApp APIs
=> Add import lib if the app sets the UseRNCoreApp property

change/react-native-windows-7381bba4-15a0-458e-82c9-63951b1129c8.json, vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
In #9798, we added functionality to update transform props directly without first converting those props into a transform matrix in JS. This change did not account for string values of skewX and skewY.
Resolves #10364
Skew transforms can be specified in degrees (via string) rather than explicit float values. Ensure we call `ToRadians` before attempting to create the skew matrices.
https://user-images.githubusercontent.com/1106239/182689785-1fdaf726-d69e-470c-b54a-76acf24326ac.mp4
=> Fix skew transforms for string values

NuGet.Config, change/react-native-windows-018abdbd-de95-40a0-ad82-807c96ba29fa.json, vnext/Desktop.ABITests/NuGet.Config, vnext/Desktop.DLL/NuGet.Config, vnext/Desktop.IntegrationTests/NuGet.Config, vnext/Desktop.UnitTests/NuGet.Config, vnext/Desktop/NuGet.Config, vnext/NuGet.Config, vnext/ReactCommon.UnitTests/NuGet.Config
This PR changes our `NuGet.Config` files to be compliant. It assumes the following paradigm:
1. The NuGet.org feed contains all of the packages that RNW Universal/WinAppSDK projects require.
2. The `react-native-public` ADO feed conatins all of the packages that RNW Desktop projects requires.
With this in mind, the `NuGet.Config` files have been updated as follows:
* The root and `vnext` `NuGet.Config` files no longer specify any package sources, so restores will default to the user's default, (usually NuGet.org).
* The Desktop* projects specify only the `react-native-public` ADO feed as a package source.
From an app/module customer point-of-view, unless they're trying to test canary builds of our `Microsoft.ReactNative.*`, they shouldn't need to use our ADO feeds at all. And even if they …
=> Update nuget feed declarations

change/react-native-windows-8d7cf1e8-5491-4630-bf74-b2e4f942cf70.json, vnext/Microsoft.ReactNative/Utils/Helpers.h
Remove unnecessary 'typename' as recent builds of MSVC compiler will emit an error
The code contained an unnecessary 'typename' keyword which is flagged as an error by recent builds of the MSVC compiler
Remove 'typename' keyword
=> Remove incorrect `typename` keyword in helpers.h function template

change/@react-native-windows-cli-b5c97a05-d431-433f-86bb-1dffed74144b.json, packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Autolinking needs to inject the paths to modules' native projects into the solution file for the app project, so that those dependencies are built.
However, dependencies are often sourced from `node_modules` paths, which are typically under the control of the package manager being used and the actual path may change. For example, using symlinks to shared caches on disk, etc.
Until now, autolinking only looked for the _exact_ project entry in the solution file, which includes that path. If it wasn't found, it would insert the correct entry.
So if a dev moved the dependency's root folder (say by changing a package manager config) then autolinking would insert the new project entry _in addition_ to the older one, creating a duplicate which would inevitably cause build failures.
Since native …
=> Update autolinking to update project paths in solution files

change/react-native-windows-4e62363e-6ce0-4ca5-9015-2667e8695d98.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewPanel.cpp, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp, vnext/Shared/Threading/BatchingQueueThread.cpp
Adds a few SystraceSections to improve instrumentation for performance measurements.
This change adds SystraceSections to many relevant UIManager and View calls for more visibility into what work is being done by RN.
Specifically, it instruments the following:
1. Frequent view management APIs for the top-level UIManager and the NativeUIManager (e.g., createView, updateView, manageChildren, etc.). It does not currently measure any context switching from JS to UI thread.
2. Potential hot spots for ViewViewManager, like replacing the ViewPanel with a ViewControl (via ReplaceView, TransferProperties, etc.).
3. Time spent preparing for and executing Yoga layout, including extra XAML layout calls made to …
=> Adds Systrace to view management APIs for UIManager

change/react-native-windows-c75e1473-877c-4c26-8953-2b5ba565a734.json, packages/playground/Samples/image.tsx, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
backport: https://github.com/microsoft/react-native-windows/pull/10192
Internal Request
Added example from original PR, and confirmed it fixes the issue.
=> [0.69] backport "Add partial PlatformColor support for Image's tintColor"

change/react-native-windows-f4b38fb1-367a-44c5-8520-d0f178ffb25b.json, packages/playground/Samples/image.tsx, vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
backport: https://github.com/microsoft/react-native-windows/pull/10192
Internal Request
Added example from original PR, and confirmed it fixes the issue.
=> [0.68] backport "Add partial PlatformColor support for Image's tintColor"

change/react-native-windows-ed8de10f-3224-4e5d-8624-ff9f24b9cbb1.json, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp, vnext/Shared/Networking/WinRTHttpResource.cpp
These headers are needed in case alternative PCH are used to compile (e.g., with clang/BUCK).
=> Adds missing headers for HttpRequestHeaderCollection

change/react-native-windows-66d09faf-17be-44e3-8d63-fb07a333dd18.json, vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.h, vnext/Microsoft.ReactNative/Modules/AlertModule.h, vnext/Microsoft.ReactNative/Modules/AppStateModule.h, vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.h, vnext/Microsoft.ReactNative/Modules/ClipboardModule.h, vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h, vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.h, vnext/Microsoft.ReactNative/Modules/I18nManagerModule.h, vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.h, vnext/Microsoft.ReactNative/Modules/LinkingManagerModule.h, vnext/Microsoft.ReactNative/Modules/LogBoxModule.h, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
Based on feedback from #10275, we should not be using `..` in #includes. As an added bonus, this works with our clang builds (we forked these files previously).
This changes all codegen includes to not use relative paths.
RN Windows solution builds.
=> Replace all codegen includes without relative path

change/react-native-windows-a5041465-ffcd-4b52-b4d1-34cb0370b209.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Switching from xaml::FocusState::Programmatic to xaml::FocusState::Keyboard causes focus rings to be shown for "default focus" scenarios in our app (e.g., defaulting a "Done" button in a modal), which are not intended to have focus rings (at least until the user explicitly changes focus with the Keyboard).
Resolves #10265
This change reverts to Programmatic focus in the UIManager.
=> Use programmatic focus for UIManager.focus

change/react-native-windows-309d60eb-b042-4868-8277-62deee099760.json, vnext/Microsoft.ReactNative/IReactDispatcher.h
Clang doesn't like attempting to override the virtual methods from the IDispatchQueue2 interface. Also, the IDispatchQueue2 type needs to be fully qualified in the `GetUIDispatchQueue2` method for clang to compile.
Removes problematic override modifiers and fully qualifies IDispatchQueue2 interface.
React Native Windows still compiles with Visual Studio.
=> Fixes clang compile issues for IReactDispatcher.h

change/react-native-windows-80ab1dcb-5a57-4983-be91-37a76beeb23d.json, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
In #10354, a few scenarios are described where unexpected text changes occur out of sync with the shadow tree from RN, and some scenarios even crash the app.
Resolves #10354
This change ensures that we only use the fast text optimization when there is exactly one raw text child in the shadow tree, and also switches out of the fast text optimization when the number of children increases to greater than 1, rather than only when a text value is appended (i.e., we also have to switch out of fast text optimization when for a child that might be prepended at index 0).
Before:
https://user-images.githubusercontent.com/1106239/182199687-270b86d1-f347-4cd4-9df5-9cf576e8dda3.mp4
After: …
=> Fixes various issues with fast text optimization

packages/playground/windows/playground-win32/Playground-Win32.cpp
In #9345, we defaulted the UWP Playground app to use direct debugging. This just modifies Playground-win32 Xaml Islands app to the same.
=> Default playground-win32 to direct debugging

change/react-native-windows-17c67a31-ebaf-4153-84f6-d830f7910ddb.json, vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
The DynamicAutomationPeer.h header is in the parent `Views` folder and this include path is not supported by clang. 
This change adjusts the include path.
=> Fix relative include path for Views/Image

change/react-native-windows-f387ef6b-5fac-48a8-86bf-42e6afbd3744.json, vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp
In https://github.com/microsoft/react-native-windows/pull/8495, we added an interface for 3rd party view managers to override pointer event handling in the TouchEventHandler module from RNW. The features of this PR supported press events on selectable text, but to generalize this further, we need to allow 3rd party view managers to conditionally cancel pointer event sequences and prevent press events.
Resolves #10202
This change adds the ability for view managers implementing the IViewManagerWithPointerEvents interface to change an "End" event to a "Cancel" event to achieve gesture cancellation.
=> Adds gesture cancellation to pointer event handling

change/react-native-windows-1ec41f70-0685-4d1f-8037-dbb4cfd0d22a.json, vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
There are two cases where a flyout may crash when opened:
1. If the native view corresponding to the target tag is unmounted before the flyout is shown.
2. If the XamlRoot on the flyout differs from the XamlRoot of the target.
This can happen if the XamlRoot changes (e.g., window loses focus) before the UIManager operation to create the Flyout and set the isOpen prop executes. 
Note - this is only relevant to multi-window RN applications.
This change logs the error and does not attempt to show the flyout if either of these cases occur.
This change has been in production in Messenger Desktop for more than a year and has fixed a significant crash that occurred when attempting to show a flyout just before …
=> Fix XamlRoot crashes in FlyoutViewManager

change/react-native-windows-ddcc5f68-cdab-4bae-a2e7-714fdc0de029.json, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.h
@acoates-ms has reported a memory leak issue while using `ExecuteJsi`.
He has found that the issue is caused by `ReactNotificationService` providing a wrong instance of `IReactNotificationSubscription` to the notification handler. As a result, when the handler code calls `Unsubscribe()`, the `ReactNotificationService` keeps another instance of `IReactNotificationSubscription` alive with captured lambda that causes unexpected memory leaks.
The code for the `IReactNotificationService` is changed to ensure that we use correct instance of `IReactNotificationSubscription` in the notification handlers.
To do that we split the `ReactNotificationSubscription` implementation into two different classes: `ReactNotificationSubscription` and …
=> Fix `ReactNotificationService` memory leak in `ExecuteJsi`

change/@react-native-windows-cli-512117e3-b225-422d-aac1-f69efa3a70cb.json, packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Apps that contain spaces in their path fail to deploy after running `npx react-native run-windows`. Path name incorrectly sent to Powershell, as space has not been escaped correctly.
Resolves #10001
Validated in a stand alone app.
=> Fix Deploy Error for Apps that Contain Spaces in Path

change/react-native-windows-ddcc5f68-cdab-4bae-a2e7-714fdc0de029.json, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.h
Cherry pick #10408. Original PR description:
@acoates-ms has reported a memory leak issue while using `ExecuteJsi`.
He has found that the issue is caused by `ReactNotificationService` providing a wrong instance of `IReactNotificationSubscription` to the notification handler. As a result, when the handler code calls `Unsubscribe()`, the `ReactNotificationService` keeps another instance of `IReactNotificationSubscription` alive with captured lambda that causes unexpected memory leaks.
The code for the `IReactNotificationService` is changed to ensure that we use correct instance of `IReactNotificationSubscription` in the notification handlers.
To do that we split the `ReactNotificationSubscription` implementation into two different …
=> [0.68] Fix `ReactNotificationService` memory leak in `ExecuteJsi` (#10408)

change/react-native-windows-ddcc5f68-cdab-4bae-a2e7-714fdc0de029.json, vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.cpp, vnext/Microsoft.ReactNative/IReactNotificationService.h
Cherry pick #10408. Original PR description:
@acoates-ms has reported a memory leak issue while using `ExecuteJsi`.
He has found that the issue is caused by `ReactNotificationService` providing a wrong instance of `IReactNotificationSubscription` to the notification handler. As a result, when the handler code calls `Unsubscribe()`, the `ReactNotificationService` keeps another instance of `IReactNotificationSubscription` alive with captured lambda that causes unexpected memory leaks.
The code for the `IReactNotificationService` is changed to ensure that we use correct instance of `IReactNotificationSubscription` in the notification handlers.
To do that we split the `ReactNotificationSubscription` implementation into two different …
=> [0.69] Fix `ReactNotificationService` memory leak in `ExecuteJsi` (#10408)

change/@office-iss-react-native-win32-5c1734bb-75b4-41e9-b7cf-7557d39798bf.json, change/@office-iss-react-native-win32-7fce2b29-0c20-4c4f-b2c6-8c4e7001f7cd.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Adding the `alwaysShowToolTip` prop for RNWin32's View.
To keep native behavior where certain components are tagged to not show tooltips while giving clients the flexibility to use JS to override this behavior and show tooltips if necessary.
This change will be backported back to 0.66 so that it can be consumed by Office.
Added `alwaysShowToolTip` prop to the typing for ViewWin32. Also added `alwaysShowToolTip` to the list of `validAttributes`.
=> Add new prop alwaysShowToolTip to ViewWin32

change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json, vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Shared/InstanceManager.cpp, vnext/Shared/InstanceManager.h, vnext/Shared/OInstance.cpp, vnext/Shared/OInstance.h
@acoates-ms has reported an issue with RNW Turbo Module implementation where we see a crash after a RN instance is unloaded. The crash is caused by a JSI `Function` that captured in a lambda used for asynchronous callbacks or in a `Promise`.
We destroy JS engine instance when unloading the RN instance, and the JSI `Function` cannot be safely released anymore.
RN Turbo Modules that wrap up CxxModules use `LongLivedObject` and `LongLivedObjectCollection` as a mechanism to address similar issues. The callbacks are wrapped up into `CallbackWrapper` class inherited from the `LongLivedObject`. The `LongLivedObjectCollection` is cleared when JS engine instance is shut down and it releases all associated `std::shared_ptr<LongLivedObject>` …
=> Use LongLivedObjects for TurboModule callbacks

.unbroken_exclusions
CI was constatly reporting warnings due to unbroken..
Created a generic fix in https://github.com/askar/unbroken to suppress all 403's but got recommendation to just exclude the errors.
Note there is no localization in unbroken, only en-us errors and you put error messages to supporess direclty in the exclusions config...
=> Fix CI warnings on github returning 403's

change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json, vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Shared/InstanceManager.cpp, vnext/Shared/InstanceManager.h, vnext/Shared/OInstance.cpp, vnext/Shared/OInstance.h, vnext/Shared/Shared.vcxitems.filters
Cherry pick PR #10436. Original description:
@acoates-ms has reported an issue with RNW Turbo Module implementation where we see a crash after a RN instance is unloaded. The crash is caused by a JSI `Function` that captured in a lambda used for asynchronous callbacks or in a `Promise`.
We destroy JS engine instance when unloading the RN instance, and the JSI `Function` cannot be safely released anymore.
RN Turbo Modules that wrap up CxxModules use `LongLivedObject` and `LongLivedObjectCollection` as a mechanism to address similar issues. The callbacks are wrapped up into `CallbackWrapper` class inherited from the `LongLivedObject`. The `LongLivedObjectCollection` is cleared when JS engine instance is shut down and it releases all …
=> [0.68] Use LongLivedObjects for TurboModule callbacks (#10436)

.ado/jobs/macos-tests.yml
Update to later mac agent. 10.15 will be deprecated on 9/30.
See: https://github.com/actions/runner-images/issues/5583
=> Update to later Mac version, there is a brown-out today before the 9/30 deprecation fo 10.15

change/@office-iss-react-native-win32-542f6b5d-16ec-486d-b221-f0c3cf70721e.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Add the Toggle action to accessibilityActionName on ViewWin32
Adding the Toggle action will allow developers to expose the toggle pattern on win32 which is used for accessibility purposes on controls that can be toggled (like a switch). We have support for this functionality natively but have not added it as an action that can be set on ViewWin32.
Added 'Toggle' to the list of strings for accepted names for accessibilityActionName on ViewWin32
=> Add Toggle action to accessibilityActionName on ViewWin32

change/@office-iss-react-native-win32-542f6b5d-16ec-486d-b221-f0c3cf70721e.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Cherry pick PR #10434 
Add the Toggle action to accessibilityActionName on ViewWin32
Adding the Toggle action will allow developers to expose the toggle pattern on win32 which is used for accessibility purposes on controls that can be toggled (like a switch). We have support for this functionality natively but have not added it as an action that can be set on ViewWin32.
Added 'Toggle' to the list of strings for accepted names for accessibilityActionName on ViewWin32
=> [0.70] Add Toggle action to accessibilityActionName on ViewWin32 (#10434)

change/@office-iss-react-native-win32-542f6b5d-16ec-486d-b221-f0c3cf70721e.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Cherry pick PR #10434 
Add the Toggle action to accessibilityActionName on ViewWin32
Adding the Toggle action will allow developers to expose the toggle pattern on win32 which is used for accessibility purposes on controls that can be toggled (like a switch). We have support for this functionality natively but have not added it as an action that can be set on ViewWin32.
Added 'Toggle' to the list of strings for accepted names for accessibilityActionName on ViewWin32
=> [0.69] Add Toggle action to accessibilityActionName on ViewWin32 (#10434)

change/@office-iss-react-native-win32-542f6b5d-16ec-486d-b221-f0c3cf70721e.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Cherry pick PR #10434 
Add the Toggle action to accessibilityActionName on ViewWin32
Adding the Toggle action will allow developers to expose the toggle pattern on win32 which is used for accessibility purposes on controls that can be toggled (like a switch). We have support for this functionality natively but have not added it as an action that can be set on ViewWin32.
Added 'Toggle' to the list of strings for accepted names for accessibilityActionName on ViewWin32
=> [0.68] Add Toggle action to accessibilityActionName on ViewWin32 (#10434)

change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json, vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js, vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp, vnext/Microsoft.ReactNative/JSDispatcherWriter.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.cpp, vnext/Microsoft.ReactNative/TurboModulesProvider.h, vnext/Shared/InstanceManager.cpp, vnext/Shared/InstanceManager.h, vnext/Shared/OInstance.cpp, vnext/Shared/OInstance.h
Cherry pick PR #10436. Original description:
@acoates-ms has reported an issue with RNW Turbo Module implementation where we see a crash after a RN instance is unloaded. The crash is caused by a JSI `Function` that captured in a lambda used for asynchronous callbacks or in a `Promise`.
We destroy JS engine instance when unloading the RN instance, and the JSI `Function` cannot be safely released anymore.
RN Turbo Modules that wrap up CxxModules use `LongLivedObject` and `LongLivedObjectCollection` as a mechanism to address similar issues. The callbacks are wrapped up into `CallbackWrapper` class inherited from the `LongLivedObject`. The `LongLivedObjectCollection` is cleared when JS engine instance is shut down and it releases all …
=> [0.70] Use LongLivedObjects for TurboModule callbacks (#10436)

change/react-native-windows-ac0793f7-dae5-4086-850c-2ede09044870.json, vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Creating an `InstanceSettings` object on Windows 8.1 crashes when trying to get the current `DispatcherQueue` for the default value of `UIDispatcher`.
In more current versions of windows this call will return null, which is valid if the app explicitly sets the `UIDispatcher` property.  This change treats errors as null, so the app can continue if they provide a `UIDispatcher`.
=> Fix crash creating InstanceSettings on Windows 8.1

change/react-native-windows-fa7f3afb-6f45-432e-a939-5cfcc6c0dd51.json, vnext/Folly/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
=> Add `$schema` to `cgmanifest.json`

change/react-native-windows-37139ab0-cad3-4421-9c32-a0b0328c0e6f.json, vnext/Microsoft.ReactNative/XamlHelper.cpp, vnext/Microsoft.ReactNative/XamlHelper.h, vnext/Microsoft.ReactNative/XamlHelper.idl, vnext/Microsoft.ReactNative/XamlUIService.cpp, vnext/Microsoft.ReactNative/XamlUIService.h, vnext/Microsoft.ReactNative/XamlUIService.idl
In #9658 we created a new attached property to store react tags on XAML elements, but put ABI accessors on the XamlUIService, which is attached to a specific ReactContext.
However, these accessors are static and don't need a ReactContext, and in fact there are plenty of places (like RNX serialization) where we don't have (or need) a ReactContext.
Fix a mistake in #9658.
Moves the new ABI surface into XamHelper, which contains static methods.
=> Move ReactTag ABI to XamlHelper

change/react-native-windows-1f809f69-c2e9-49d5-bea5-706b281f03ff.json, vnext/Folly/Folly.vcxproj, vnext/Folly/cgmanifest.json, vnext/fmt/cgmanifest.json, vnext/fmt/fmt.vcxproj
This PR correctly implements the fix attempted in #10474, by updating the code-gen of our `cgmanifest.json` files, rather than the output.
The change to add a `$schema` field to the `cgmanifest.json` files, while righteous, was applied to generated files, and to only one of those present in our repo. This means the changes will be lost during the next build.
Updated and re-ran the code-gen to add the `$schema` field.
=> Add `$schema` to `cgmanifest.json` codegen

packages/e2e-test-app/package.json, packages/e2e-test-app/windows/RNTesterApp/packages.lock.json, yarn.lock
This PR updates the E2E test app to use the latest RNX, which among other things uses the ReactTag APIs introduced in #10485.
Want to verify that RNX works with the new APIs and that E2E test passes.
Version bump of RNX to 0.0.68.
N/A
Build and run E2Etest app locally
=> Update E2E test app to use latest RNX

change/react-native-windows-cf5f34aa-f3c5-47ba-afbe-e17d4eba1d26.json, vnext/PropertySheets/CppAppConsumeCSharpModule.props
I'm sure this logic should be generalized better at some point.  But this at least enables the builds to work with the versions that the current version of VS2022 seems to come with.
=> Add additional possible SDK versions to build logic

change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
The handling for pointerEvents moved from ViewViewManager to ViewManagerBase in #8500 so all views could participate in pointerEvents handling (including Text, etc.). During this move, the code introduced a bug where updates to pointerEvents after pointerEvents is set to `none` are not respected.
Resolves #10493
This adds an else clause to ensure we reset the `IsHitTestVisible` property when a the `pointerEvents` value is not `none`, but still valid.
Ran a simple example:
```
function App() {
const [none, setNone] = useState(false);
return (
<>
<Button title={`Set pointerEvents=\'${none ? 'auto' : 'none'}\'`} onPress={() => setNone(!none)} />
<View pointerEvents={none ? 'none' : 'box-none'} >
<View …
```
=> Fixes bug introduced by pointerEvents change

change/@office-iss-react-native-win32-e6dfec7d-c0c7-441a-a5ef-8bfc66927b49.json, change/@react-native-windows-cli-354d60b6-89df-4dc2-b5e1-c59a1be8e3ac.json, change/@react-native-windows-codegen-e80b375d-e72a-4899-a5d9-9177ab839f8d.json, change/@react-native-windows-find-repo-root-22bba5f4-f722-42c9-9993-266502e249a3.json, change/@react-native-windows-fs-6aa01d19-45b9-4eb5-9858-b977d3af2f14.json, change/@react-native-windows-package-utils-44d41335-e8a8-40ae-9694-adf4cd9ae7cb.json, change/@react-native-windows-telemetry-124ae341-b192-4a88-8116-a3c7f3437ff9.json, change/@react-native-windows-virtualized-list-7ee6957d-456b-4ff8-84b8-c0834d1afd6e.json, change/react-native-windows-e2d095c7-4462-46d3-84bf-56e11627f375.json, packages/@office-iss/react-native-win32/package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/codegen/package.json, packages/@react-native-windows/find-repo-root/package.json, packages/@react-native-windows/fs/package.json, packages/@react-native-windows/package-utils/package.json, packages/@react-native-windows/telemetry/package.json, packages/@react-native-windows/virtualized-list/package.json, vnext/package.json
- Release Cycle
Move v0.69 to Legacy
=> Move v0.69 to Legacy

packages/debug-test/DebuggingFeatures.test.ts
- add automated test
- Prevent regression of debugging features
The fix has been pushed to FB RN per https://github.com/facebook/react-native/pull/34342. Until hermes-windows picks up the containing FB ReactCommon version, the fix has been duplicated into hermes-windows as patch per https://github.com/microsoft/hermes-windows/pull/122. 
This change adds an automated test for the fix to RNW.
=> Add Regression Test for RNW:9662

change/react-native-windows-e21dad36-9fab-4c18-b6ea-440dc068dc72.json, packages/integration-test-app/windows/integrationtest/ReactPackageProvider.cpp, packages/playground/CoreApp/App.cpp, packages/playground/windows/playground/ReactPackageProvider.cpp, packages/sample-apps/index.windows.js, packages/sample-apps/windows/SampleAppCPP/ReactPackageProvider.cpp, packages/sample-apps/windows/SampleLibraryCPP/ReactPackageProvider.cpp, vnext/Desktop/ABI/TestController.cpp, vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.cpp, vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h, vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h, vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.js, vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp, vnext/Microsoft.ReactNative/IReactPackageBuilder.idl, vnext/Microsoft.ReactNative/ReactNativeHost.cpp, vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp, vnext/Microsoft.ReactNative/ReactPackageBuilder.h, vnext/template/cpp-app/src/ReactPackageProvider.cpp, vnext/template/cpp-lib/src/ReactPackageProvider.cpp
We've had TurboModule support for a while, but its always involved using an experimental API.  Its also not been easy to use with `AddAttributedModules`.
This moves the current `AddTurboModule` api from `IReactPackageBuilderExperimental` to `IReactPackageBuilder` and adds an optional parameter to  `AddAttributedModules` which can be used to specify that the attributed modules should use TurboModules.
The new architecture is moving towards TurboModules, and this will enable much easier transition to TurboModules.
=> Make AddTurboModule a non-experimental API

change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Enabling access key functionality for use in RN Win32 per client request. Setting this prop will assign the character passed into the prop to the UIA_AccessKeyProperty and will invoke onPress on the component when that letter is pressed and that component is a visible menu item.
Discussion for RNW happening in #10353 
Adds `accessibilityAccessKey` as a property of `IViewWin32Props`.
Not a visual change
Tested locally by implementing a component that uses onPress. Verified that the character passed in is assigned to the UIA_AccessKeyProperty, and that pressing the access key triggers the menu item.
Changes to the tester cannot happen yet because newer versions of the tester assert on boot, and the tester needs to be updated in …
=> Add `accessibilityAccessKey` prop to ViewWin32

change/react-native-windows-8d316c11-9ba7-4e64-a2e0-2f7066ebcc70.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
Other platforms fire `onLayout` depth first. Windows should do the same. Also, once we upgrade to React 18, it is a common case that React commits will create nodes that are not yet attached to any root (and thus do not participate in the Yoga layout for that batch / commit). This means that, in the current approach for updating layout, we would fire `onLayout` events with `NaN` values for width and height.
Resolves #10421
This changes switches from iterating over all Yoga nodes to update layout on each UIManager batch to recursively updating layout from the root shadow node. The effect is that we fire events depth first and we only attempt to update layout on nodes that have participated in Yoga layout …
=> Fixes event ordering for `onLayout`

change/react-native-windows-35fd02cc-01fa-43b1-9ea7-2fdc02b19210.json, vnext/Microsoft.ReactNative/ABIViewManager.cpp, vnext/Microsoft.ReactNative/ABIViewManager.h, vnext/Microsoft.ReactNative/IViewManager.idl
Core VMs can override `SetLayoutProps` to get a callback just before native layout values are applied from Yoga. There is no option to observe these changes from Yoga in ABI VMs.
This change introduces a new interface to receive a callback when computed Yoga layout values are being applied to a native view.
We have a use case for this interface that is also dependent on #10422 (ensuring parent SetLayoutProps occur after children), #10237 (adding an API to invoke nested Yoga layout for a given React tag), and #10393 (custom measure func). Specifically, the following sequence occurs:
1. Prop updates cause Yoga layout to be applied on a root node
2. SetLayoutProps/OnLayout is called on the custom VM
3. …
=> Adds IViewManagerWithOnLayout interface for ABI VMs

change/react-native-windows-6d3b83af-0fc7-4246-ac81-e7e058c82a3b.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Modules/NativeUIManager.h, vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
I believe this code is dead code that is no longer needed. It was originally introduced to apply Yoga paddings to ContentControlViewManager from the Polyester folder. However, since then, the approach to handling controls that implement their own padding has changed.
The code that was removed effectively walks all nodes attached to a root node every time the root view size changes or a batch of UI operations completes. Not anymore :).
RNTester runs, CI passes :)
=> Remove unnecessary tree walk in Yoga layout

change/react-native-windows-99b4d0ab-5a17-4781-8844-7bc094e0a18c.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Since we strictly speaking don't need to reset the self measure func when swapping out a native view, we can just use the `IsNativeControlWithSelfLayout` check. This internally checks for the a non-null measure function, but may future proof this case if we add additional logic to verify if a node uses self-layout.
=> Use `IsNativeControlWithSelfLayout` in ReplaceView

change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json, change/@office-iss-react-native-win32-b430ff27-e7bf-4628-bf35-ad7c766db549.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
=> [0.69] [RN Win32] Backport Add `accessibilityAccessKey` prop to ViewWin32 

README.md, change/react-native-windows-7b46659d-3215-473f-a423-7d06be47cd14.json, vnext/package.json
Update references to Facebook to Meta, and fix typo causing the LICENSE file to not be present in the npm package
=> Fix typo and references to Facebook

.ado/integrate-rn.yaml, .ado/jobs/cli-init.yml, .ado/jobs/setup.yml, .ado/publish.yml, .ado/templates/checkout-full.yml
A change in beachball behavior means we need to make sure we have (the right) credentials ready to run beachball commands in our various ADO pipelines.
I made some temporary workarounds to unblock pipelines:
- [Add persistCredentials: true to checkout](https://github.com/microsoft/react-native-windows/commit/ba5b0080a6121f5e2562e91752411d521cf7d19b)
- [Update publish.yml to not set credentials until after running credscan](https://github.com/microsoft/react-native-windows/commit/19ef0684655a119ae2dffdd0ecbd91d6bf77f63e)
- [Parameterize persistCredentials, default to true](https://github.com/microsoft/react-native-windows/commit/462407c4e4c9c4c11779d9699b168e0643cd5392)
- [Update publish.yml to not persist credentials](https://github.com/microsoft/react-native-windows/commit/8f607832651023c …
=> ADO: Change full checkout `persistCredentials` default back to `false`

change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json, change/@office-iss-react-native-win32-297898bd-1d76-4458-ab01-adf379803a6c.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backport of https://github.com/microsoft/react-native-windows/pull/10527. FluentUI React Native is currently blocked on updating to 0.68, so backporting this change down to 0.66 to unblock partners.
=> [0.66] [RN Win32] Backport Add `accessibilityAccessKey` to ViewWin32

change/@office-iss-react-native-win32-1b954575-9757-41ff-a990-c4fd5eaca44a.json, change/@office-iss-react-native-win32-b091bcc0-5900-4bf6-867b-38ae88c941a5.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Backport of #10527. FluentUI React Native is currently blocked on updating to 0.68, so backporting this change down to 0.66 to unblock partners.
=> [0.67] [RN Win32] Backport add `accessibilityAccessKey` to ViewWin32

change/@react-native-windows-automation-channel-1ab47515-a255-4e8f-94be-b8b3883cf771.json, packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground/Playground.vcxproj, packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
After PR https://github.com/microsoft/react-native-windows/pull/10567, the `ResolveNuGetPackages` property is handled by the
external property sheets. There's no need to re-set it in these individual
projects.
=> Remove unecessary ResolveNuGetPackages 

packages/debug-test/CDPDebugger.ts, packages/debug-test/DebuggingFeatures.test.ts
- Add new test
Detect regression with regard to [FB:34639](https://github.com/facebook/react-native/issues/34639).
Automated test verifying context execution identifier in Debugger.scriptParsed CDP event
Actual fix is in [FB:34640](https://github.com/facebook/react-native/pull/34640) and, as a patch, in [HW:131](https://github.com/microsoft/hermes-windows/pull/131/files)
=> test for context execution identifier in Debugger.scriptParsed event

change/@office-iss-react-native-win32-3b7051a8-fe70-470a-9c55-61fc8bd26cea.json, packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Utilities/Dimensions.win32.js
Add Dimensions.win32 to support the text scale factor property of the rn-core interface, while leaving DPI information in its currently unsupported state.  Text scale factor is a system global, and not affected by the same issues as DPI.
While the Dimensions API for DPI does not fully map the complexity of Win32 DPI scenarios, it does contain the text scale factor API that as a global can be used for good purposes in certain scenarios.
Expose the text scale factor property on the Dimensions API
Validated manually with re-enabled Dimensions test page
=> Add forked Dimensions.win32 module implementation

change/react-native-windows-abb4eabd-b346-47f7-a968-b213177e171f.json, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Utils/ImageUtils.cpp, vnext/Microsoft.ReactNative/Utils/ImageUtils.h, vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp, vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Moving a couple of functions out of ReactImage which is tied to Xaml, so it can be shared with non-xaml code.
=> Move some image functions into separate file

change/@office-iss-react-native-win32-3b7051a8-fe70-470a-9c55-61fc8bd26cea.json, packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Utilities/Dimensions.win32.js
Cherry pick of  PR #10475 
Add Dimensions.win32 to support the text scale factor property of the rn-core interface, while leaving DPI information in its currently unsupported state.  Text scale factor is a system global, and not affected by the same issues as DPI.
While the Dimensions API for DPI does not fully map the complexity of Win32 DPI scenarios, it does contain the text scale factor API that as a global can be used for good purposes in certain scenarios.
Expose the text scale factor property on the Dimensions API
Validated manually with re-enabled Dimensions test page
=> [0.70] Add forked Dimensions.win32 module implementation #10475

change/@office-iss-react-native-win32-3b7051a8-fe70-470a-9c55-61fc8bd26cea.json, packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Utilities/Dimensions.win32.js
Cherry pick of  PR #10475 
Add Dimensions.win32 to support the text scale factor property of the rn-core interface, while leaving DPI information in its currently unsupported state.  Text scale factor is a system global, and not affected by the same issues as DPI.
While the Dimensions API for DPI does not fully map the complexity of Win32 DPI scenarios, it does contain the text scale factor API that as a global can be used for good purposes in certain scenarios.
Expose the text scale factor property on the Dimensions API
Validated manually with re-enabled Dimensions test page
=> [0.69] Add forked Dimensions.win32 module implementation #10475

change/@office-iss-react-native-win32-3b7051a8-fe70-470a-9c55-61fc8bd26cea.json, packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js, packages/@office-iss/react-native-win32/src/Libraries/Utilities/Dimensions.win32.js
Cherry pick of  PR #10475 
Add Dimensions.win32 to support the text scale factor property of the rn-core interface, while leaving DPI information in its currently unsupported state.  Text scale factor is a system global, and not affected by the same issues as DPI.
While the Dimensions API for DPI does not fully map the complexity of Win32 DPI scenarios, it does contain the text scale factor API that as a global can be used for good purposes in certain scenarios.
Expose the text scale factor property on the Dimensions API
Validated manually with re-enabled Dimensions test page
=> [0.68] Add forked Dimensions.win32 module implementation #10475

.ado/config/AgentES.Exemptions.json, .ado/templates/run-compliance-prebuild.yml
Adds the Agent ES exemptions file.
The AgentES tool must be ran to determine if any banned file types are present in the repo.
Closes #10147
Adds a new task to the `run-compliance.yml` file to download the AgentES NuGet package and run the tool with our exemption file.
N/A
Ran steps manually locally.
=> Add Agent ES exemption file for compliance pipeline

change/react-native-windows-46b530e4-8447-414b-9761-43c03e7088da.json, vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
- Functionality change
Following change to accessible/focusable prop relationship in #9840, request from partner to adjust logic in order to reduce number of code edits needed. 
#9840 was needed in order to bring RNW up to Windows accessibility standards. In Windows accessibility focus and keyboard focus are the same. RNW should not allow developers to remove elements from the UIA while they still remain keyboard focusable. 
Originally, the PR set the behavior to be if either accessible or focusable was set to false the control should not be focusable or accessible. The logic is now if either accessible or focusable is set to true the control should be focusable and accessible.
=> Change Accessible/Focusable Relationship to Default to 

change/react-native-windows-26a724f0-7103-4b59-a493-7ef156733d0d.json, change/react-native-windows-d5cf0017-99f3-40eb-856e-25f6e85f6fa2.json, vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp, vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp, vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj, vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters, vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp, vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp, vnext/Desktop.UnitTests/WinRTNetworkingMocks.h, vnext/Microsoft.ReactNative/Pch/pch.h, vnext/Shared/Modules/HttpModule.cpp, vnext/Shared/Networking/IHttpResource.h, vnext/Shared/Networking/IRedirectEventSource.h, vnext/Shared/Networking/IWinRTHttpRequestFactory.h, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp, vnext/Shared/Networking/OriginPolicyHttpFilter.h, vnext/Shared/Networking/RedirectHttpFilter.cpp, vnext/Shared/Networking/RedirectHttpFilter.h, vnext/Shared/Networking/WinRTHttpResource.cpp, vnext/Shared/Networking/WinRTHttpResource.h, vnext/Shared/Shared.vcxitems, vnext/Shared/Shared.vcxitems.filters, vnext/Test/HttpServer.cpp, vnext/Test/HttpServer.h
=> [0.70] Implement HTTP redirection

change/react-native-windows-d7888a84-3523-4fec-9554-362ed0be06ad.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.h, vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.h
- Optimization (non-breaking change which improves performance)
We previously used std::map in ShadowNodeRegistry and NativeUIManager for the storage of shadow nodes (former) and Yoga nodes and context (latter), which has O(log(n)) complexity for insertion, removal, and lookup. The main reason for using std::map over std::unordered_map is when you require ordered enumeration of keys, which none of these maps require.
- Shadow nodes are only enumerated when destroying the UIManagerModule to cleanup by calling `DropView` on the shadow node. Tag indices themselves do not specify much besides creation order, and while children generally have smaller indices than parents in very simple cases, this is not always the case (consider a component that adds a child …
=> Switch to std::unordered_map for shadow and Yoga nodes

change/react-native-windows-4fcaba6c-79ae-484a-a6a8-64fa08ee4c4b.json, vnext/template/cs-app-WinAppSDK/MyApp/App.xaml.cs
Minor fix of indentation in App.xaml.cs in C# WinAppSDK project template.
It seems we don't have an auto formatter for C# code.
Just whitespace change.
=> Fix formatting in App.xaml.cs in C# WinAppSDK project template

change/react-native-windows-63ed688a-573c-4dc1-99de-f69d6f650838.json, vnext/Scripts/OfficeReact.Win32.nuspec, vnext/Shared/Networking/OriginPolicy.h
Adds OriginPolicy.h to the Desktop NuGet include headers.
OriginPolicy.h contains the necessary enums to set the app-level HTTP origin policy.
=> Export OriginPolicy.h to NuGet package

change/react-native-windows-4368402e-1685-4f6d-8750-48801eb76e19.json, packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj, packages/integration-test-app/windows/InteropTestModuleCS/InteropTestModuleCS.csproj, packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj, packages/playground/CoreApp/CoreApp.vcxproj, packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj, packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj, packages/sample-apps/windows/SampleLibraryCS/SampleLibraryCS.csproj, vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj, vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj, vnext/Microsoft.ReactNative.WindowsAppSDK/Microsoft.ReactNative.WindowsAppSDK.csproj, vnext/PropertySheets/External/Microsoft.ReactNative.Common.props, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props, vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props, vnext/PropertySheets/External/Microsoft.ReactNative.WinAppSDK.CSharpApp.props, vnext/PropertySheets/NuGet.CSharp.props, vnext/PropertySheets/NuGet.Cpp.props, vnext/PropertySheets/React.Cpp.props, vnext/template/cpp-app/proj/MyApp.vcxproj, vnext/template/cpp-lib/proj/MyLib.vcxproj, vnext/template/cs-app/proj/MyApp.csproj, vnext/template/cs-lib/proj/MyLib.csproj
This PR backports #10567 to 0.70.
The switch to PackageReference sprinkled required properties in each individual app/lib project file, instead of putting them in to the shared property sheets.
This means that customers upgrading from earlier versions of RNW must add these properties to every project they consume. So app customers must add the correct properties to their app projects when upgrading to 0.68+, and also to each native module project they depend on.
Moving the properties in to the shared props (that every project consumes) means that they all get their benefit.
Resolves #10538
Set the NuGet properties such as …
=> [0.70] Move required PackageReference properties into shared property sheets

change/react-native-windows-e25a11c7-0495-427c-a391-bf0597daa183.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
This TODO in NativeUIManager was a reminder to set up size changed events for the root view to update layout. This must have been fixed already but the TODO was never removed.
=> Deletes irrelevant TODO from NativeUIManager

change/react-native-windows-5ca2f093-d86c-4bab-9a50-4b6d722eefa4.json, vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
Currently fabric ScrollView will scroll a full viewport past the content.  This change limits its scroll range to the size of the content.
You can see this in RNTester today where you can scroll way past the bottom of the list of test pages in fabric.  With this change the behavior matches paper.
=> Fabric: Stop ScrollView from scrolling past content

change/react-native-windows-f017b5c1-bf44-4a8f-b996-203d619e5329.json, vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
Error in the insert logic was causing visuals to be inserted in the wrong order.  This causes visuals to show up with the wrong zorder.
One obvious effect of this is the yellowbox warning banner would disappear behind the app content.  But also easily visible in the zorder view test page in RNTester.
=> Fabric: fix zorder issues

change/react-native-windows-d5e1c0c0-cb20-47fd-947a-eb449f7e9677.json, vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp
[LocalBundleReader.cpp(79)](https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp#L79) adds 1 to the file length in an apparent attempt to ensure a null-terminated string (confirmed with @stecrain, the original author). The subsequent code does not adjust the string length to reflect the actual file content length, leading to a JS string that contains a '\0' char. The token scanners of Chakra and Hermes appear to tolerate the '\0' char (perhaps they skip it, or treat it as the end of the JS string, either would work). V8's token scanner, however, reports the '\0' char as an invalid token, causing script parsing to fail with an invalid syntax error.
Resolves …
=> Fix +1 problem in LocalBundleReader

change/@react-native-windows-cli-e3847c52-a0ae-4225-ae47-5e0fb5095bd2.json, change/@react-native-windows-codegen-31042724-aa30-4b89-a76d-1131ab4c8448.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/codegen/depcheck.config.js, packages/@react-native-windows/codegen/package.json, packages/@react-native-windows/codegen/src/generators/AliasGen.ts, packages/@react-native-windows/codegen/src/generators/AliasManaging.ts, packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts, packages/@react-native-windows/codegen/src/generators/GenerateTypeScript.ts, packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts, packages/@react-native-windows/codegen/src/generators/ParamTypes.ts, packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts, packages/@react-native-windows/codegen/src/generators/ValidateConstants.ts, packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts, packages/@react-native-windows/codegen/src/index.ts
react-native-tscodegen has an internal duplication of react-native-codegen. This was largely built before react-native-codegen was properly published.  Now that react-native-codegen is published, we can use the published package directly.
I've switched all our usage of react-native-tscodegen to be for types only.  Hopefully we can look at getting typing information published as part of react-native-codegen in the future to remove the need for react-native-tscodegen entirely.
=> Use react-native-codegen from react-native instead of from react-native-tscodegen

change/react-native-windows-7cf8ea6f-f155-4b6f-a4f8-06bbe79b671b.json, vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp, vnext/Microsoft.ReactNative/Modules/TimingModule.cpp, vnext/Microsoft.ReactNative/Modules/TimingModule.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
This moves the existing Timing module to be a TurboModule.  It continues to use the same queue and logic as before, so should run the same way.  This allows the module to use a codegen'd spec, and will allow future changes to use the property bag to toggle different behaviors.  (Fabric will want to use something other than xaml rendering callback)
=> Move timing native module to TurboModule

change/react-native-windows-39bb8fcb-67ab-4f56-adda-ce1fbb820810.json, vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
A recent change to FlyoutViewManager attempts to set the XamlRoot from the NativeUIManager::tryGetXamlRoot function. However, there is a race condition here where the view could be created just after the window was closed (or perhaps even that the window was closed just after the view was created and the weak reference to the XamlRoot on the Flyout resolves to null). When this occurs, attempting to call Flyout::ShowAt results in a crash in XAML Islands applications.
This change ensures that the Flyout has a valid XamlRoot before attempting to show the flyout.
=> Prevent crash in XAML Islands Flyout

change/react-native-windows-53cbb9fa-9565-4dfe-a5f9-3740f353a469.json, vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/core/LayoutableShadowNode.cpp
There was a fix made by the last RN integration that caused a loop to underflow and then attempt to index a very large number into an index.  This results in numerous crashes in fabric.
=> Fix bad fix for size_t -> int truncation from RN merge

change/react-native-windows-0f54d4e2-d544-4e6b-b6bb-3f7e6eb6d3e3.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
While not a well supported scenario, multi-window UWP applications might measure relative to the incorrect root XAML view when calling `measureInWindow` if the view is not in the currently activated / foreground window.
I was confused on why `measureInWindow` seemed to work fine in XAML Islands React Native apps, but then realized that `xaml::Window::Current().Content()` returned null in XAML Islands applications, so only UWP apps are impacted.
Previously, `measureInWindow` measured relative to `xaml::Window::Current().Content()`. Calling `TransformToVisual` with a null argument measures relative to the root XAML content, which is equivalent to `xaml::Window::Current().Content()` for the foreground window. …
=> Explicitly measure relative to the root XAML element

change/react-native-windows-81766dee-43b9-4551-9a83-d2cc2e6b1f03.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/QuirkSettings.cpp, vnext/Microsoft.ReactNative/QuirkSettings.h, vnext/Microsoft.ReactNative/QuirkSettings.idl
By default, Yoga will cache flex basis values to avoid expensive recomputation. However, there are some scenarios, particularly when resizing the window, where cached layout values from Yoga combined with cached flex basis values can produce incorrect results.
Resolves #9343
This change adds a new QuirkSetting to opt-in to the YGExperimentalFeatureWebFlexBasis option in Yoga for apps where re-use of this cached flex basis value is problematic. We'll keep this opt-in for now, as it is likely to impact performance of Yoga layout.
CI is green. Results of opting into this QuirkSetting may vary in different apps both w.r.t. to performance and …
=> Adds QuirkSetting to use YGExperimentalFeatureWebFlexBasis

change/react-native-windows-377f2770-0169-4a24-add1-e9ae515c1038.json, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h, vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp, vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
We are working on an implementation of view flattening for the Paper UIManager in react-native-windows. Since not all nodes are materialized into native components, the backing store for previous layout data cannot be the native component itself. Also, the actual top/left values that get applied to a particular view will not equal the values computed by Yoga (they will be offset by the cumulative left and top values of any flattening parents).
This change adds 4 bytes to the ShadowNode to store the latest layout constraints computed by Yoga and lifts the `onLayout` event to the NativeUIManager, so that even if a view is flattened, it can still emit `onLayout` events.
Ran RNTester > VirtualizedList …
=> Refactor the onLayout event for view flattening

change/react-native-windows-4e282efb-fc79-4999-8d71-dd5b68a36f92.json, vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
The rect being provided to RichEdit was incorrect, which was causing RichEdit to provide the wrong size for the caret.
=> Fabric: TextInput caret is incorrect size

change/react-native-windows-a912b218-3e03-4b76-8b54-d9cd603a29c0.json, vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp, vnext/Shared/Networking/RedirectHttpFilter.cpp, vnext/Shared/Shared.vcxitems.filters
Sets the User-Agent header in RedirectHttpFilter::SendRequestAsync.
Some HTTP endpoints may require the User-Agent header to be set to return a successful response (i.e. `200: OK`).
Example: `GET https://api.github.com/repos/microsoft/react-native-windows`
If the request has no `User-Agent` header, the result is `403: Forbidden`.
The User-Agent should be settable via native code by the consuming app, and not only passed from the JavaScript layer on which HTTP headers may not be directly settable.
Retrieves the runtime option string `Http.UserAgent` and appends it to an HTTP request right before sending it.
- `Http.UserAgent` Used to set the `User-Agent` header for all HTTP requests via native code.
Note, this header should always be set …
=> Set User-Agent header in Origin Policy filter

change/react-native-windows-8769dfac-39b4-4cfc-88ae-91a5456390a2.json, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Sets the `Origin` header when dealing with Simple CORS or Full CORS requests.
HTTP servers may need the `Origin` header set by the client to properly validate Origin Policy semantics.
Currently, only the CORS preflight request sets this header.
OriginPolicyHttpFilter::SendAsync appends the `Origin` header to both the preflight and main requests before sending.
=> Set Origin HTTP header during CORS

change/react-native-windows-a912b218-3e03-4b76-8b54-d9cd603a29c0.json, change/react-native-windows-d3922b8e-5a78-442a-baec-8e3453e3254c.json, vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp, vnext/Shared/Networking/OriginPolicyHttpFilter.cpp, vnext/Shared/Networking/RedirectHttpFilter.cpp, vnext/Shared/Shared.vcxitems.filters
=> [0.69] Set User-Agent header in Origin Policy filter

change/react-native-windows-9c0c9ca5-333f-4bbb-bd5a-7312b7431160.json, packages/playground/Samples/view.tsx, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp, vnext/Microsoft.ReactNative/Views/ViewViewManager.h
If a user disables focusable or accessible only in a particular View update, we will likely not run the logic to keep these values in sync.
Resolves #10687
This changes the behavior to always synchronize these values.
|focusable|accessible|pressable|expected|actual|
|-|-|-|-|-|
|✅|✅|✅|✅|✅|
|❌|✅|✅|❌|❌|
|✅|❌|✅|❌|❌|
|❌|❌|✅|❌|❌|
|✅|✅|❌|✅|✅|
|❌|✅|❌|✅|✅|
|✅|❌|❌|✅|✅|
|❌|❌|❌|❌|❌|
https://user-images.githubusercontent.com/1106239/194376872-c30fd298-adbb-49e5-ba3d-2b85e3cf6951.mp4
=> Always synchronize focusable and accessible props

packages/@react-native-windows/tester/package.json
We only use the @react-native/rntester dependency to copy code in the lage build task. We're working on an e2e testing capability that requires us to publish the code for @react-native-windows, and we can only do so by removing this actual dependency.
Ran:
```
> yarn
> yarn --cwd packages\playground
```
Ran playground and confirmed that RNTester still loads correctly.
=> Move @react-native/rntester dependency to devDependencies

change/react-native-windows-d4774adb-364c-4bd2-b53b-4a1d54b4e0a4.json, vnext/Shared/OInstance.cpp
We have preprocessor conditionals that consume the HBC version, so we should only include the header if the value will actually be used.
=> Conditionally include HBC version header

.ado/config/CredScanSuppressions.json, .ado/templates/component-governance.yml
The `resolver` NPM package includes a malformed `package.json` file for testing, but it causes every one of our compliance tools  to complain since they just assume it's a real NPM package that needs to be parsed.
I'm tired of seeing all the warnings for this non-package.
Specifies, where possible, that each compliance tool ignore the malformed file.
N/A
N/A
=> Fix warnings for malformed_package_json test file

packages/playground/windows/playground-win32/Playground-Win32.cpp
Previously, in #10263, we disabled the default option to use web debugging. This change simply flips the bit for direct debugging, which was the original intention of #10263 (just overlooked).
=> Enables direct debugging by default in Playground-win32

change/@react-native-windows-cli-72a84946-f9a2-4c32-9ab3-b7502b3cddaa.json, change/react-native-windows-e5fed6cf-085b-4951-9594-acb92c1fc660.json, packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap, packages/e2e-test-app/windows/ExperimentalFeatures.props, packages/integration-test-app/windows/ExperimentalFeatures.props, packages/playground/CoreApp/ExperimentalFeatures.props, packages/playground/windows/ExperimentalFeatures.props, vnext/ExperimentalFeatures.props, vnext/Microsoft.ReactNative.Managed/packages.lock.json, vnext/PropertySheets/JSEngine.props, vnext/template/cs-app-WinAppSDK/proj/ExperimentalFeatures.props, vnext/template/shared-app/proj/ExperimentalFeatures.props, vnext/template/shared-lib/proj/ExperimentalFeatures.props
This PR fixes the `MSB4011` warning when `JSEngine.props` tries to import `ExperimentalFeatures.props` a second time. The expectation is that all RNW projects (app or module) import the `ExperimentalFeatures.props` file (located next to the VS solution) at the very top of each project file, so all RNW-related projects are in sync with respect to the state of any Experimental Features.
However, older RNW apps/module templates did not include this import, hence `JSEngine.props`'s workaround to import it. Unfortunately, MSBuild:
* Doesn't like project files to be imported twice, so it gives the `MSB4011` warning
* Doesn't provide any built-in way to detect if a project file has already been imported
* Doesn't allow you to suppress this particular warning completely
The best solution is to …
=> Mitigate MSB4011 warning for importing ExperimentalFeatures.props 

change/react-native-windows-b2051115-6321-435c-80ff-1897606896ef.json, vnext/src/Libraries/Components/View/View.windows.js
Touchable components expect to see their children prop as the single child itself and not an array with one child. If array with one child is passed, red box error will fire and no-hide-accessibility will not work for that case.
Note: Native implementation is on its way that will be more performant. This implementation is temporarily in place to meet the end of October deadline for the accessibility pass. 
Check if children array only has one element. If so, return that element.
=> Adjust no-hide-descendants Code to Support Touchable

change/react-native-windows-7e70c472-5871-465c-bb75-e1376e8c8916.json, vnext/Microsoft.ReactNative/Utils/PropertyUtils.h, vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Here is a specific list of changes:
- **onMouseEnter**: drops IsNull check, since null values are falsy anyway
- **onMouseLeave**: drops IsNull check, since null values are falsy anyway
- **onClick**: drops IsNull check, since null values are falsy anyway
- **focusable**: drops JS value type check, this will fix a bug where setting focusable to null or undefined will not take effect, but also will now set focusable to `true` for any truthy JS values
- **enableFocusRing**: drops JS value type check, this will now set enableFocusRing to `true` for any truthy JS values
- **tabIndex**: inserts type check to ensure the value is numeric, this will fix an issue where setting tabIndex to anything other than a …
=> Simplifies and fixes various View prop handlers

change/react-native-windows-55aaf03d-9022-46b4-acd4-8d2637c6f49b.json, packages/playground/windows/NuGet.Config, packages/playground/windows/playground-win32/Playground-Win32.cpp, packages/playground/windows/playground-win32/Playground-win32.vcxproj, packages/playground/windows/playground-win32/packages.config, packages/playground/windows/playground/Playground.vcxproj, packages/playground/windows/playground/packages.config, vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj, vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj, vnext/Desktop/React.Windows.Desktop.vcxproj, vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp, vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h, vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems, vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props, vnext/PropertySheets/JSEngine.props, vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj, vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h, vnext/Shared/V8JSIRuntimeHolder.h
Picking up an updated V8 package version and fix the projects that broke because we're not actively testing this configuration. This is cherry picking the same change from 0.69 (https://github.com/microsoft/react-native-windows/pull/10766).
=> [0.70] V8 package update

change/@react-native-windows-cli-e884393e-295e-43ea-b50c-dce70f71a176.json, change/react-native-windows-90e2cc65-5baa-4b5c-9bf9-0cdfe54e132a.json, packages/@react-native-windows/cli/src/generator-windows/index.ts, vnext/ExperimentalFeatures.props, vnext/Microsoft.ReactNative.WindowsAppSDK/Microsoft.ReactNative.WindowsAppSDK.csproj, vnext/PropertySheets/WinUI.props, vnext/template/cs-app-WinAppSDK/proj/MyApp.csproj
This PR updates the following versions for the `Microsoft.ReactNative.WindowsAppSDK` project and the template for apps built agsinst it:
* Upgrade `WindowsTargetPlatformVersion` / `Microsoft.WindowsSDK` to 10.0.19041 from 10.0.18362
* Upgrade `WinUI3` / `Microsoft.WindowsAppSDK` to 1.1.4 from 1.0.0
Building the `Microsoft.ReactNative.WindowsAppSDK` project with the `WindowsTargetPlatformVersion` at 10.0.18362 means all of the dependencies (like `Microsoft.ReactNative`) also build targeting that version, which causes multiple warnings by the MIDL compiler. Updating to 10.0.19041 aligns WindowsAppSDK with the standard …
=> Update WindowsAppSDK versions to latest

change/react-native-windows-647ad113-7678-43e1-9f59-aed8eb42737d.json, vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Fixes a typo that was causing hardware back button event subscriptions to not fire in JS.
Resolves #10742 
Fixed typo "hardward" -> "hardware"
Tested locally in our app by applying this change as a patch to our node_modules via `npx patch-package`
=> Fix hardware back events

change/react-native-windows-58120787-47ec-4a2b-bde5-befd651c528f.json, vnext/Microsoft.ReactNative/XamlUIService.cpp, vnext/Microsoft.ReactNative/XamlUIService.h, vnext/Microsoft.ReactNative/XamlUIService.idl
We emulate this behavior in our app, it's probably better to expose the core functionality to walk the shadow node tree (rather than using VisualTreeHelpers).
=> Adds GetReactRootView method to XamlUIService

change/react-native-windows-a86ad746-4da6-4d3b-86d7-8b4f05cdf352.json, vnext/Microsoft.ReactNative/Modules/TimingModule.cpp, vnext/Microsoft.ReactNative/Modules/TimingModule.h
In fabric it'll be possible to run RNW without using XAML, at which point we cannot use the CompositionTarget::Rendering event.  
This unblocks the usage of various timers in fabric with no xaml - such as the composition playground app.
Instead of using the Rendering event, the timers will be fired based on a dispatch queue post call.
The Timing test page in RNTester would previously crash in the composition playground app.  Now all the buttons pass.
=> Do not use xaml rendering callback in non-xaml apps

change/react-native-windows-8a89df6e-f669-46dc-9ada-d645db4f038d.json, vnext/Microsoft.ReactNative.Managed.IntegrationTests/Microsoft.ReactNative.Managed.IntegrationTests.csproj, vnext/Microsoft.ReactNative.sln
We don't build Microsoft.ReactNative.Managed.UnitTests for ARM64 because
certain System.Xml assemblies needed by MSTest aren't present in that
configuration.
So the newly added Microsoft.ReactNative.Managed.IntegrationsTests
should also not build ARM64.
Fixes CI build / publish.
Closes #10814 
Remove project from solution's ARM64 build.
=> Remove Microsoft.ReactNative.Managed.IntegrationTests from ARM64 build 

change/react-native-windows-79f6563d-c38d-419d-b66a-00820b069c31.json, vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
This PR backports #10793 to 0.69.
* Allow customers to specify $(CppWinRTVersion)
This PR updates our shared prop file where we set the version of $(CppWinRTVersion) to use to only specify it if it's not already specifed by the customer (say in ExperimentalFeatures.props).
* Change files
* Ensure minimum version
=> [0.69] Allow customers to specify $(CppWinRTVersion)

change/react-native-windows-79f6563d-c38d-419d-b66a-00820b069c31.json, vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
This PR backports #10793 to 0.70.
* Allow customers to specify $(CppWinRTVersion)
This PR updates our shared prop file where we set the version of $(CppWinRTVersion) to use to only specify it if it's not already specifed by the customer (say in ExperimentalFeatures.props).
* Change files
* Ensure minimum version
=> [0.70] Allow customers to specify $(CppWinRTVersion)

change/@office-iss-react-native-win32-14c21e4b-fc70-4934-899a-ba3dd43c88bd.json, packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
Add accessibilityLevel as a prop on TextWin32 to set heading level for accessibility purposes.
On windows, text elements can be defined as a header using `accessibilityRole="header"` but there is no way to define a custom heading level (the current default is 2). This proposal: [RFG Accessibility APIs by necolas](https://github.com/react-native-community/discussions-and-proposals/pull/410/files#diff-0778a9f2187181434c1b3042681941d44513d93af9c5dcbbd1b3e94e329c140cR109) proposes using `accessibilityLevel` as a prop to define text heading levels and hierarchical levels (since it closely aligns with the ARIA level property and is used for the same purpose. See …
=> Add accessibilityLevel as a prop on TextWin32 to set heading level

change/@office-iss-react-native-win32-385acbc9-f9c6-40e3-8c13-3e5f6fc1778d.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Removes extra accessibilityLevel prop from ViewWin32 which I forgot to remove from IViewWin32Props when it was moved to BasePropsWin32 in #10823.
No need for accessibilityLevel to be defined in two places.
Removes accessibilityLevel prop from IViewWin32Props since it's defined in BasePropsWin32.
Manually tested existing test case scenarios in the RN Tester App locally.
=> Remove extra accessibilityLevel prop from ViewWin32

change/@react-native-windows-cli-bb3dec8a-9e52-4cac-9001-e6d08adc2e33.json, change/react-native-windows-00869e87-88ae-481d-ba9b-d6bd01cae748.json, packages/@react-native-windows/cli/src/generator-windows/index.ts, vnext/PropertySheets/External/Microsoft.ReactNative.WinAppSDK.CSharp.PackageReferences.props, vnext/PropertySheets/External/Microsoft.ReactNative.WinAppSDK.CSharpApp.targets, vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props, vnext/template/cpp-app/proj/MyApp.vcxproj, vnext/template/cpp-lib/proj/MyLib.vcxproj, vnext/template/cs-app-WinAppSDK/proj/MyApp.csproj, vnext/template/cs-app/proj/MyApp.csproj, vnext/template/cs-lib/proj/MyLib.csproj
This PR moves control of specifying various targets and package versions for PackageReferences for the WinAppSDK template into the external property sheets and uses variables that can be overridden, rather than stamping hardcoded versions into the template project files.
This PR also sets the template for C++/WinRT projects to consume the `CppWinRTVersion` variable, rather than a hardcoded version.
Closes #10796
Closes #10798
=> Align WinAppSDK template to not hardcode package versions

change/@office-iss-react-native-win32-14c21e4b-fc70-4934-899a-ba3dd43c88bd.json, change/@office-iss-react-native-win32-385acbc9-f9c6-40e3-8c13-3e5f6fc1778d.json, packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
Cherry-pick of #10823 and #10824
Add accessibilityLevel as a prop on TextWin32 to set heading level for accessibility purposes.
On windows, text elements can be defined as a header using `accessibilityRole="header"` but there is no way to define a custom heading level (the current default is 2). This proposal: [RFG Accessibility APIs by necolas](https://github.com/react-native-community/discussions-and-proposals/pull/410/files#diff-0778a9f2187181434c1b3042681941d44513d93af9c5dcbbd1b3e94e329c140cR109) proposes using `accessibilityLevel` as a prop to define text heading levels and hierarchical levels (since it closely aligns with the ARIA level property and is used for the same …
=> [0.68] Add accessibilityLevel as a prop on TextWin32 to set heading level

change/@office-iss-react-native-win32-447f3ff4-93e5-447e-8956-57f4c3e6c8bc.json, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Fixes small typo in a comment.
No change to the package, just fixes typo.
Typo is being fixed in the backports for the associated change in 0.68, 0.69, and 0.70. Need to fix the typo in the main branch so future branches will have the correct spelling.
=> Fix typo in comment

change/@office-iss-react-native-win32-14c21e4b-fc70-4934-899a-ba3dd43c88bd.json, change/@office-iss-react-native-win32-385acbc9-f9c6-40e3-8c13-3e5f6fc1778d.json, packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx, packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts, packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
Cherry-pick of #10823 and #10824
Add accessibilityLevel as a prop on TextWin32 to set heading level for accessibility purposes.
On windows, text elements can be defined as a header using `accessibilityRole="header"` but there is no way to define a custom heading level (the current default is 2). This proposal: [RFG Accessibility APIs by necolas](https://github.com/react-native-community/discussions-and-proposals/pull/410/files#diff-0778a9f2187181434c1b3042681941d44513d93af9c5dcbbd1b3e94e329c140cR109) proposes using `accessibilityLevel` as a prop to define text heading levels and hierarchical levels (since it closely aligns with the ARIA level property and is used for the same …
=> [0.70] Add accessibilityLevel as a prop on TextWin32 to set heading level

packages/debug-test/DebuggingFeatures.test.ts
- Enable test method
We're now using a hermes-windows version that contains a fix required by the test method.
Remove 'skip' attribution from test method.
=> Enable test for execution context ID

change/react-native-windows-a5d81eea-50b4-4029-80b1-944768616ecf.json, vnext/Microsoft.ReactNative/Views/Text/TextPropertyChangedParentVisitor.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.cpp, vnext/Microsoft.ReactNative/Views/TextViewManager.h
- Perf fix (non-breaking change which improves performance)
Currently, the fast text optimization is only applied for Text nodes with a single run child. If you have text like the following:
```
<Text>Count: {count}</Text>
```
This will create two inline children.
We can instead validate that the Text node has only runs for children, and concatenate the context of the runs together to keep using the optimized text path (setting the xaml::TextBlock::TextProperty).
Checked around with Text examples in Playground - behavior unchanged. Also verified that updating RawTextNode "text" props trigger updates to the optimized text when necessary.
=> Apply fast text optimization to multiple runs

change/react-native-windows-b08d7ad3-24e4-4476-a726-1fb58ad0792c.json, vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
In #7072, a change was made to always disable horizontal scrolling by default. Prior to this change, apps that enabled vertical scrolling and zoom scale (via maximumZoomScale or minimumZoomScale) could scroll in both directions. 
Resolves #10806
This change reverts the problematic commit from #7072 and puts in a better fix for the scrollToEnd issue.
Before:
https://user-images.githubusercontent.com/1106239/198719352-674449f1-3fe8-4739-bbbe-2712f54f7106.mp4
After:
https://user-images.githubusercontent.com/1106239/198719367-156485bb-6e15-4bd1-947d-85257b5f575e.mp4
=> Fixes issue with zoom and horizontal scrolling

change/react-native-windows-3cc0e9ad-707a-4364-90b8-dc391040fade.json, vnext/Microsoft.ReactNative/INativeUIManager.h, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp, vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.cpp, vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.h
In #8327, we added a root tag field to the ShadowNode. Rather than relying on a parent traversal to find the parent node, we can just directly resolve the root using the root tag.
Measure and blur APIs still function correctly.
=> Simplify root node lookups

change/react-native-windows-701f2200-7c68-46ab-9af5-099e1ca8ba0f.json, vnext/Microsoft.ReactNative/INativeUIManager.h, vnext/Microsoft.ReactNative/LayoutService.cpp, vnext/Microsoft.ReactNative/LayoutService.h, vnext/Microsoft.ReactNative/LayoutService.idl, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj, vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters, vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp, vnext/Microsoft.ReactNative/Modules/NativeUIManager.h, vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
In order to enable native layout updates, we need to expose an interface to mark Yoga nodes as dirty, and also to trigger native layout.
Resolves #9988
Towards #7601
Workaround for #9343
While we could just blindly invoke `onBatchComplete` on the NativeUIManager, it is safer to also expose an interface to test whether the UIManager is currently processing a batch of UIManager operations so we can piggy back on the current onBatchComplete call that will occur at the end of a batch if one is in progress. This is also likely to prevent UI tearing. Today, it is unlikely that an call from the UI thread to invoke Yoga and XAML layout will interrupt a batch, if we eventually implement something like eager …
=> Adds LayoutService interface to allow native layout updates

change/@react-native-windows-cli-690eac2a-adb7-4a70-961a-8cf4e6930446.json, change/@react-native-windows-telemetry-52e61840-c7f5-4b0e-9160-0fabee406aa4.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/telemetry/package.json, yarn.lock
This PR backports #10841 to RNW 0.69.
=> [0.69] CG 11/7/22: Update `@xmldom/xmldom`

change/@react-native-windows-cli-8a99690d-57f4-46af-9e61-4f6c4bb95384.json, change/@react-native-windows-telemetry-45cb351d-b880-40ef-8838-c884f8f6162b.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/telemetry/package.json, yarn.lock
This PR backports #10841 to RNW 0.70.
=> [0.70] CG 11/7/22: Update `@xmldom/xmldom`

change/@react-native-windows-cli-30efcfa1-a7c7-45e7-b9c2-186edfadad49.json, change/@react-native-windows-telemetry-9dcd5adb-bcbf-4696-b9ab-aac6ed63515d.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/telemetry/package.json, yarn.lock
=> CG 11/7/22: Update `@xmldom/xmldom`

change/@react-native-windows-cli-b0c55029-d039-44de-9750-a585afade9e5.json, change/@react-native-windows-telemetry-81f9cac6-be82-4e0c-b7f6-5dd8c79a4f9f.json, package.json, packages/@react-native-windows/cli/package.json, packages/@react-native-windows/telemetry/package.json, yarn.lock
This PR backports #10841 to RNW 0.68.
* `loader-utils` to `2.0.3` to resolve CVE-2022-37601
=> [0.68] CG 11/7/22: Update `@xmldom/xmldom`
